### ISSUE TITLE
Vectorized function not callable from nopython context

### ISSUE THREAD

**Issue by ml31415** [numba/numba#1007]
Not sure if this is actually a bug or working as intended, and I'm just not groking something obvious. At least it is really counter intuitive to me. This snippet reproduces the problem:

``` python
import numpy as np
import numba as nb

@nb.vectorize([nb.boolean(nb.boolean)], nopython=True)
def invert(x):
    return not x

@nb.jit(nopython=True)
def func(x):
    return invert(x)

func(np.random.random(100) > 0.5)
```

Which gives:

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-1-47a3dc57879c> in <module>()
     10     return invert(x)
     11 
---> 12 func(np.random.random(100) > 0.5)

/usr/local/lib/python2.7/dist-packages/numba/dispatcher.pyc in _compile_for_args(self, *args, **kws)
    151         assert not kws
    152         sig = tuple([self.typeof_pyval(a) for a in args])
--> 153         return self.jit(sig)
    154 
    155     def inspect_types(self, file=None):

/usr/local/lib/python2.7/dist-packages/numba/dispatcher.pyc in jit(self, sig, **kws)
    142         """Alias of compile(sig, **kws)
    143         """
--> 144         return self.compile(sig, **kws)
    145 
    146     def _compile_for_args(self, *args, **kws):

/usr/local/lib/python2.7/dist-packages/numba/dispatcher.pyc in compile(self, sig, locals, **targetoptions)
    277                                           self.py_func,
    278                                           args=args, return_type=return_type,
--> 279                                           flags=flags, locals=locs)
    280 
    281             # Check typing error if object mode is used

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    550     pipeline = Pipeline(typingctx, targetctx, library,
    551                         args, return_type, flags, locals)
--> 552     return pipeline.compile_extra(func)
    553 
    554 

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in compile_extra(self, func)
    261                     "extract bytecode")()
    262         if res.ok:
--> 263             return self.compile_bytecode(res.result, func_attr=self.func_attr)
    264         elif self.status.can_giveup:
    265             return self.stage_compile_interp_mode()

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in compile_bytecode(self, bc, lifted, func_attr)
    273         self.lifted = lifted
    274         self.func_attr = func_attr
--> 275         return self._compile_bytecode()
    276 
    277     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in _compile_bytecode(self)
    499 
    500         assert pipelines
--> 501         return self._run_pipeline(pipelines)
    502 
    503     def _run_pipeline(self, pipelines):

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in _run_pipeline(self, pipelines)
    524                     msg = "Failed at " + stage.msg
    525                     if pi + 1 >= len(pipelines):
--> 526                         raise _raise_error(msg, res.exception)
    527                     # Go to next fallback pipeline
    528                     else:

TypingError: Failed at nopython frontend
Untyped global name 'invert'
File "<ipython-input-1-47a3dc57879c>", line 10
```

Giving types to `func` is of no help. Any ideas for a workaround would also be welcome! :)

**Comment by shoyer** [comment]
This is a known issue, see this mailing list discussion: https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/numba-users/ibrADCziTFg/rkzAzZuKgnYJ

**Comment by ml31415** [comment]
For the sake of collecting the test cases together in one place, here the one from the mailing list:

```python
import numba as nb
import numpy as np

@nb.vectorize('f8(f8)', nopython=True)
def sinp(x):
    return np.sin(x) + 1

@nb.vectorize('f8(f8)', nopython=True)
def sinpp(x):
    return sinp(x) + 1

sinpp(8.0)
```

**Comment by seibert** [comment]
We are planning to take over ufunc creation from Numpy, which will solve a lot of these problems.

**Comment by pitrou** [comment]
Short of rewriting the ufunc machinery, we could create a simple wrapper object which would also hold the required (signatures -> entry points) mapping.

**Comment by mcg1969** [comment]
Ping. Just ran into this bug myself in my client work. Existing numpy functions like `sin`, `sqrt`, etc. do seem to exhibit the proper behavior when scalars are passed in.

**Comment by seibert** [comment]
Yes, we support all ufuncs as scalars in the current Numba (0.18.2).  In the next release (0.19), we should be able to support calling ufuncs with array arguments.  It should be out within the next week.

**Comment by serkef** [comment]
Hi, it seems to me that the problem insists, although the fix is included in 0.19 release notes as @seibert said.
My version is 0.21
My code is the following:
```python
@numba.vectorize([int64(int64,int64)],nopython=True)
def prod(x, y):
    return x * y

@numba.jit(nopython=True)
def func(a,b):
  prod.reduce(a,0,b.dtype,b)
```
Calling func() gives me the following error:
```python
a=np.array([[2,3],[2,4]],dtype=np.int)
b=np.zeros((2),dtype=np.int)
func(a,b)

TypingError: Caused By:
Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 242, in run
    res = stage()
  File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 455, in stage_nopython_frontend
    self.locals)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 751, in type_inference_stage
    infer.build_constraint()
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 494, in build_constraint
    self.constrain_statement(inst)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 651, in constrain_statement
    self.typeof_assign(inst)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 691, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 756, in typeof_global
    loc=inst.loc)
TypingError: Untyped global name 'prod'
File "<ipython-input-175-bf26e50608ee>", line 3

Failed at nopython (nopython frontend)
Untyped global name 'prod'
File "<ipython-input-175-bf26e50608ee>", line 3
```
Note that if I remove nopython from func() it works fine.

Do I miss something? Any feedback is welcome

**Comment by serkef** [comment]
Hi all, 
I retested this with version 22.1 and I keep getting the same results. Do you think this could be a bug?

I repost the code and the error.
```python
@numba.vectorize([int64(int64,int64)],nopython=True)
def prod(x, y):
    return x + y
@numba.jit(nopython=True)
def func(a,b):
  prod.reduce(a,0,b.dtype,b)
```
```python
print numba.__version__
a=np.array([[2,3],[2,4]],dtype=np.int)
b=np.zeros((2),dtype=np.int)
func(a,b)
print b
```
```python
0.22.1

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-12-f1cb5da1d16f> in <module>()
      2 a=np.array([[2,3],[2,4]],dtype=np.int)
      3 b=np.zeros((2),dtype=np.int)
----> 4 func(a,b)
      5 print b

/opt/anaconda/lib/python2.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    170         assert not kws
    171         sig = tuple([self.typeof_pyval(a) for a in args])
--> 172         return self.compile(sig)
    173 
    174     def inspect_llvm(self, signature=None):

/opt/anaconda/lib/python2.7/site-packages/numba/dispatcher.py in compile(self, sig)
    348                                           self.py_func,
    349                                           args=args, return_type=return_type,
--> 350                                           flags=flags, locals=self.locals)
    351 
    352             # Check typing error if object mode is used

/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    642     pipeline = Pipeline(typingctx, targetctx, library,
    643                         args, return_type, flags, locals)
--> 644     return pipeline.compile_extra(func)
    645 
    646 

/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py in compile_extra(self, func)
    359                 raise e
    360 
--> 361         return self.compile_bytecode(bc, func_attr=self.func_attr)
    362 
    363     def compile_bytecode(self, bc, lifted=(), lifted_from=None,

/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py in compile_bytecode(self, bc, lifted, lifted_from, func_attr)
    368         self.lifted_from = lifted_from
    369         self.func_attr = func_attr
--> 370         return self._compile_bytecode()
    371 
    372     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py in _compile_bytecode(self)
    629 
    630         pm.finalize()
--> 631         return pm.run(self.status)
    632 
    633 

/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py in run(self, status)
    249                     # No more fallback pipelines?
    250                     if is_final_pipeline:
--> 251                         raise patched_exception
    252                     # Go to next fallback pipeline
    253                     else:

TypingError: Caused By:
Traceback (most recent call last):
  File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 458, in stage_nopython_frontend
    self.locals)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 758, in type_inference_stage
    infer.build_constraint()
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 494, in build_constraint
    self.constrain_statement(inst)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 651, in constrain_statement
    self.typeof_assign(inst)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 691, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/opt/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 756, in typeof_global
    loc=inst.loc)
TypingError: Untyped global name 'prod'
File "<ipython-input-10-bf26e50608ee>", line 3

Failed at nopython (nopython frontend)
Untyped global name 'prod'
File "<ipython-input-10-bf26e50608ee>", line 3
```

**Comment by albop** [comment]
I believe I ran into the same bug today, with guvectorize:

```python
from numba import guvectorize, njit, float64, void
@guvectorize([void(float64[:],float64[:])], signature='(p),(p)')
def fun(x,out):
    out[0] = x[0]
@njit
def manual_loop(X,OUT):
    N = OUT.shape[0]
    for n in range(N):
        fun(X[n,:], OUT[n,:])

import numpy as np
x = np.ones((10,1))
out = np.zeros((10,1))
manual_loop(x,out)
```

which gives:
```
Traceback (most recent call last):
  File "test_guvec_nopython.py", line 19, in <module>
    manual_loop(x,out)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/dispatcher.py", line 171, in _compile_for_args
    return self.compile(sig)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/dispatcher.py", line 349, in compile
    flags=flags, locals=self.locals)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 665, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 366, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 375, in compile_bytecode
    return self._compile_bytecode()
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 652, in _compile_bytecode
    return pm.run(self.status)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 251, in run
    raise patched_exception
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 463, in stage_nopython_frontend
    self.locals)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/compiler.py", line 779, in type_inference_stage
    infer.build_constraint()
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 549, in build_constraint
    self.constrain_statement(inst)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 672, in constrain_statement
    self.typeof_assign(inst)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 722, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/home/pablo/.local/anaconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 788, in typeof_global
    loc=inst.loc)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Untyped global name 'fun'
File "test_guvec_nopython.py", line 12
```

**Comment by pitrou** [comment]
Yes, this is something that we are looking to support progressively.
Note that @ml31415's original use case works with the current Numba.

**Comment by albop** [comment]
Ah, perfect.

**Comment by ml31415** [comment]
As the initial example works now, I guess it makes sense to close it. @albop maybe you reopen another separate issue for your example?
