### ISSUE TITLE
one module import syntax fails on numba 0.18.0rc1

### ISSUE THREAD

**Issue by ufechner7** [numba/numba#1059]
The following code fails with numba 0.18, but works with 0.17:

```python
# -*- coding: utf-8 -*-
import numpy as np
from numba import jit
import linalg_3d_v3 as la

@jit(nopython = True)
def calcDrag(v_wind_tether, v_segment, v_apparent):
    la.sub(v_wind_tether, v_segment, v_apparent)
   
if __name__ == '__main__':
    a, b, c = np.ones(3), np.ones(3), np.ones(3)
    calcDrag(a,b,c)
```
Content of the file linalg_3d_v3.py:
```python
# -*- coding: utf-8 -*-
from numba import jit

@jit(nopython = True)
def sub(a, b, result):
    """ Calculate the difference of two 3d vectors. """
    result[0] = a[0] - b[0]
    result[1] = a[1] - b[1]
    result[2] = a[2] - b[2]
```

Error message:
```
In [4]: runfile('/home/ufechner/00PythonSoftware/KiteSim/KPS3_v2_bug.py', wdir='/home/ufechner/00PythonSoftware/KiteSim')
Reloaded modules: mini_sim_core_cpp, WinchModel, Settings, Timer, Repository, Kite_4_point, linalg_3d_v2, KCU_Sim
Traceback (most recent call last):

  File "<ipython-input-4-aa1b95d5c694>", line 1, in <module>
    runfile('/home/ufechner/00PythonSoftware/KiteSim/KPS3_v2_bug.py', wdir='/home/ufechner/00PythonSoftware/KiteSim')

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 682, in runfile
    execfile(filename, namespace)

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/spyderlib/widgets/externalshell/sitecustomize.py", line 78, in execfile
    builtins.execfile(filename, *where)

  File "/home/ufechner/00PythonSoftware/KiteSim/KPS3_v2_bug.py", line 12, in <module>
    calcDrag(a,b,c)

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1_1_g5cc97bb-py2.7-linux-x86_64.egg/numba/dispatcher.py", line 162, in _compile_for_args
    return self.compile(sig)

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1_1_g5cc97bb-py2.7-linux-x86_64.egg/numba/dispatcher.py", line 305, in compile
    flags=flags, locals=self.locals)

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1_1_g5cc97bb-py2.7-linux-x86_64.egg/numba/compiler.py", line 563, in compile_extra
    return pipeline.compile_extra(func)

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1_1_g5cc97bb-py2.7-linux-x86_64.egg/numba/compiler.py", line 301, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1_1_g5cc97bb-py2.7-linux-x86_64.egg/numba/compiler.py", line 310, in compile_bytecode
    return self._compile_bytecode()

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1_1_g5cc97bb-py2.7-linux-x86_64.egg/numba/compiler.py", line 550, in _compile_bytecode
    return pm.run(self.status)

  File "/home/ufechner/miniconda/envs/numba2/lib/python2.7/site-packages/numba-0.18.0rc1_1_g5cc97bb-py2.7-linux-x86_64.egg/numba/compiler.py", line 199, in run
    raise patched_exception

LoweringError: Internal error:
KeyError: <class 'numba.types.Dispatcher'>
```

The following import works:
```python
# -*- coding: utf-8 -*-
import numpy as np
from numba import jit
from linalg_3d_v3 import sub

@jit(nopython = True)
def calcDrag(v_wind_tether, v_segment, v_apparent):
    sub(v_wind_tether, v_segment, v_apparent)
   
if __name__ == '__main__':
    a, b, c = np.ones(3), np.ones(3), np.ones(3)
    calcDrag(a,b,c)
```

Thank's for the good work!
Uwe

**Comment by gmarkall** [comment]
I can reproduce this issue.

**Comment by gmarkall** [comment]
Also it seems that using `as` is not required:

```python
# -*- coding: utf-8 -*-
import numpy as np
from numba import jit
import linalg_3d_v3

@jit(nopython = True)
def calcDrag(v_wind_tether, v_segment, v_apparent):
    linalg_3d_v3.sub(v_wind_tether, v_segment, v_apparent)

if __name__ == '__main__':
    a, b, c = np.ones(3), np.ones(3), np.ones(3)
    calcDrag(a,b,c)
```

also reproduces the issue.

**Comment by gmarkall** [comment]
Thanks for the report @ufechner7 - fix proposed in #1060.

**Comment by ufechner7** [comment]
From my point of view this issue is resolved in:
 '0.18.0_7_g1936b61-py2.7-linux-x86_64.egg'

**Comment by pitrou** [comment]
Indeed, this is fixed in the master branch. Thanks for the report!
