### ISSUE TITLE
Error:  'Module' object has no attribute 'get_global'

### ISSUE THREAD

**Issue by rzhurov** [numba/numba#1076]
OS: Ubuntu 14.04.02 x64
llvm: 3.5.2
llvmlite: 0.2.2
numba: 0.18.1
Numba and llvmlite are both installed from pip.

So, I am running this simple code:
```
from numba import jit
@jit
def f():
	return 0
if __name__ == '__main__':
	f()
```
Actually it does not matter what is in f() function.

Here is the full output:
```
Traceback (most recent call last):
  File "/home/zhurov/projects/python/numba_testing.py", line 8, in <module>
    f()
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 162, in _compile_for_args
    return self.compile(sig)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 305, in compile
    flags=flags, locals=self.locals)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 563, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 301, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 310, in compile_bytecode
    return self._compile_bytecode()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 550, in _compile_bytecode
    return pm.run(self.status)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 199, in run
    raise patched_exception
AttributeError: Failed at object (object mode backend)
'Module' object has no attribute 'get_global'
```

**Comment by david-zwicker** [comment]
I have exactly the same problem on a very similar platform: OS: Ubuntu 14.04 LTS x64; llvm: 3.5.2; llvmlite: 0.2.2; numba: 0.18.2; Numba and llvmlite are both installed from pip.
Importing numba works, but it fails to jit any function.

**Comment by pitrou** [comment]
You must upgrade llvmlite to the latest version. If installed from pip, `pip install -U llvmlite` should do the trick.

**Comment by david-zwicker** [comment]
The latest version of `llvmlite` on pip is 0.2.2, which I had installed. I guess 0.4.0 is the latest version available, which points at an error with the pip repository. I'll investigate this later.

**Comment by david-zwicker** [comment]
As far as I can see `llvmlite` has not been updated on pip since January. I posted a note in the llvmlite bug tracker: https://github.com/numba/llvmlite/issues/34#issuecomment-91554185

**Comment by cowlicks** [comment]
Related SO question: https://stackoverflow.com/questions/28955229/numba-in-conda-environment-failing-tests

**Comment by pitrou** [comment]
Ok, closing since this is a llvmlite issue. Thanks for the report!
