### ISSUE TITLE
How unsafe is inconsistent stack offset in dataflow analysis?

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#1106]
The following code:

```python
from numba import jit

import warnings; warnings.simplefilter("error")

@jit
def f():
    if a:
        for i in range(10):
            pass

f()
```

Produces: 

```
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    f()
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 162, in _compile_for_args
    return self.compile(sig)
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 300, in compile
    flags=flags, locals=self.locals)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 565, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 303, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 312, in compile_bytecode
    return self._compile_bytecode()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 552, in _compile_bytecode
    return pm.run(self.status)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 203, in run
    res = stage()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 378, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 369, in frontend_looplift
    func_attr=self.func_attr)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 574, in compile_bytecode
    return pipeline.compile_bytecode(bc=bc, lifted=lifted, lifted_from=lifted_from, func_attr=func_attr)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 312, in compile_bytecode
    return self._compile_bytecode()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 552, in _compile_bytecode
    return pm.run(self.status)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 203, in run
    res = stage()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 327, in stage_analyze_bytecode
    self.interp = translate_stage(self.bc)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 645, in translate_stage
    interp = interpreter.Interpreter(bytecode=bytecode)
  File "/home/gmarkall/work/numba/numba/interpreter.py", line 102, in __init__
    self.dfa.run()
  File "/home/gmarkall/work/numba/numba/dataflow.py", line 26, in run
    self.infos[blk.offset] = self.run_on_block(blk)
  File "/home/gmarkall/work/numba/numba/dataflow.py", line 52, in run_on_block
    print(info.stack_offset)
RuntimeWarning: inconsistent stack offset for block(offset:32, outgoing: [], incoming: [0, 29])
```

The bytecode is: 

```
>          0    LOAD_GLOBAL(arg=0, lineno=7)
           3    POP_JUMP_IF_FALSE(arg=32, lineno=7)
           6    SETUP_LOOP(arg=23, lineno=8)
           9    LOAD_GLOBAL(arg=1, lineno=8)
          12    LOAD_CONST(arg=1, lineno=8)
          15    CALL_FUNCTION(arg=1, lineno=8)
          18    GET_ITER(arg=None, lineno=8)
>         19    FOR_ITER(arg=6, lineno=8)
          22    STORE_FAST(arg=0, lineno=8)
          25    JUMP_ABSOLUTE(arg=19, lineno=9)
>         28    POP_BLOCK(arg=None, lineno=9)
          29    JUMP_FORWARD(arg=0, lineno=9)
>         32    LOAD_CONST(arg=0, lineno=9)
          35    RETURN_VALUE(arg=None, lineno=9)
```

Does it matter if the stack offset is inconsistent in cases like this?

**Comment by sklam** [comment]
@gmarkall, are you seeing this on master?

**Comment by gmarkall** [comment]
I am, with both Python 2.7 and 3.4.

**Comment by sklam** [comment]
@gmarkall, I found the problem.

**Comment by pitrou** [comment]
As a side note, this warning is really an internal error, but when adding it I wasn't sure how reliable about stack analysis was, and I didn't want to break some real-world code. Which is why I made it a warning...
