### ISSUE TITLE
Regression with ndenumerate() and NRT

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1118]
The NRT changes broke the following function:

```
@jit(nopython=True)
def f4(x, y):
    s = 0
    for i, xi in np.ndenumerate(x):
        s += xi * y[i]
    return s

arr = np.arange(10.0)
print(f4(arr, arr))
```

One gets the following traceback:

```
Traceback (most recent call last):
  File "/home/antoine/numba/numba/lowering.py", line 148, in lower_block
    self.lower_inst(inst)
  File "/home/antoine/numba/numba/lowering.py", line 189, in lower_inst
    self.storevar(val, inst.target.name)
  File "/home/antoine/numba/numba/lowering.py", line 668, in storevar
    self.incref(self.typeof(name), value)
  File "/home/antoine/numba/numba/lowering.py", line 681, in incref
    self.context.nrt_incref(self.builder, typ, val)
  File "/home/antoine/numba/numba/targets/base.py", line 1009, in nrt_incref
    members = self.data_model_manager[typ].traverse(builder, value)
  File "/home/antoine/numba/numba/datamodel/manager.py", line 31, in __getitem__
    return self.lookup(fetype)
  File "/home/antoine/numba/numba/datamodel/manager.py", line 25, in lookup
    handler = self._handlers[type(fetype)]
KeyError: <class 'numba.types.NumpyNdEnumerateType'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nde.py", line 24, in <module>
    print(f4(arr, arr))
  File "/home/antoine/numba/numba/dispatcher.py", line 162, in _compile_for_args
    return self.compile(sig)
  File "/home/antoine/numba/numba/dispatcher.py", line 300, in compile
    flags=flags, locals=self.locals)
  File "/home/antoine/numba/numba/compiler.py", line 571, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/antoine/numba/numba/compiler.py", line 309, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/home/antoine/numba/numba/compiler.py", line 318, in compile_bytecode
    return self._compile_bytecode()
  File "/home/antoine/numba/numba/compiler.py", line 558, in _compile_bytecode
    return pm.run(self.status)
  File "/home/antoine/numba/numba/compiler.py", line 200, in run
    raise patched_exception
  File "/home/antoine/numba/numba/compiler.py", line 192, in run
    res = stage()
  File "/home/antoine/numba/numba/compiler.py", line 516, in stage_nopython_backend
    return self._backend(lowerfn, objectmode=False)
  File "/home/antoine/numba/numba/compiler.py", line 471, in _backend
    lowered = lowerfn()
  File "/home/antoine/numba/numba/compiler.py", line 462, in backend_nopython_mode
    self.flags)
  File "/home/antoine/numba/numba/compiler.py", line 705, in native_lowering_stage
    lower.lower()
  File "/home/antoine/numba/numba/lowering.py", line 77, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/antoine/numba/numba/lowering.py", line 109, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/antoine/numba/numba/lowering.py", line 135, in lower_function_body
    self.lower_block(block)
  File "/home/antoine/numba/numba/lowering.py", line 153, in lower_block
    raise LoweringError(msg, inst.loc)
numba.lowering.LoweringError: Failed at nopython (nopython mode backend)
Internal error:
KeyError: <class 'numba.types.NumpyNdEnumerateType'>
File "nde.py", line 18
```

**Comment by pitrou** [comment]
The reason this hasn't been detected by the test suite is probably that the NRT is not enabled by default when using the compiler interface.
