### ISSUE TITLE
Logical operators removed too quickly in IR.

### ISSUE THREAD

**Issue by jriehl** [numba/numba#1134]
We are currently unable to support the "and" and "or" logical operators on arrays because the logical operators are not in the IR.  For example, given the following:
```
def fn(x, y): return x and y
```
...the following IR is generated:
```
----------------------------------IR DUMP: fn-----------------------------------
label 0:
    x = arg(0, name=x)                       ['x']
    y = arg(1, name=y)                       ['y']
    $phi9.1 = x                              ['$phi9.1', 'x']
    branch x, 6, 9                           ['x']
label 6:
    $phi9.1 = y                              ['$phi9.1', 'y']
    del y                                    []
    jump 9                                   []
label 9:
    del y                                    []
    del x                                    []
    $9.2 = cast(value=$phi9.1)               ['$9.2', '$phi9.1']
    del $phi9.1                              []
    return $9.2                              ['$9.2']
```
While this works for booleans (and objects in general), it fails for element-wise logical comparisons on arrays (or mixtures of arrays and scalars):
```
  File "/home/jriehl/numba/numba/typeinfer.py", line 412, in unify
    raise TypingError("Var '%s' unified to object: %s" % (var, tv))
numba.typeinfer.TypingError: Failed at nopython (nopython frontend)
Var '$9.2' unified to object: $9.2 := {uint32, array(uint32, 1d, C)}
```

**Comment by jriehl** [comment]
Going to have to claim I had a brain fart.  Numpy doesn't support the logical and/or/not operators because of how Python compiles them (thanks to @sklam for example below).
```python
>>> import numpy as np
>>> x = np.arange(10)
>>> y = np.arange(10)
>>> x and y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
