### ISSUE TITLE
an oserro

### ISSUE THREAD

**Issue by pingzou** [numba/numba#1150]
My OS  is unbuntu 15.04, and the llvm version is 3.5.2(I download the Pre-built Binaries,
unzip,  add it to the $PATH variable, then install the llvmite,numba by pip, no
mistake occurs.)。
When I import numba with ipython notebook, no error arises, and it
can accelerate the sum2d() function in the off documentation on the website.

But when I import numba just in the Terminal (python3 or ipython), error arises,
following is the error information. 

Traceback (most recent call last):
  File "<ipython-input-20-5e93547c34a4>", line 2, in <module>
    import numba
  File "/home/ping/env/lib/python3.4/site-packages/numba/**init**.py", line 6, in <module>
    from . import testing, decorators
  File "/home/ping/env/lib/python3.4/site-packages/numba/testing.py", line 4, in <module>
    from numba import config
  File "/home/ping/env/lib/python3.4/site-packages/numba/config.py", line 9, in <module>
    import llvmlite.binding as ll
  File "/home/ping/env/lib/python3.4/site-packages/llvmlite/binding/**init**.py", line 6, in <module>
    from .dylib import *
  File "/home/ping/env/lib/python3.4/site-packages/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/home/ping/env/lib/python3.4/site-packages/llvmlite/binding/ffi.py", line 36, in <module>
    lib = ctypes.CDLL(os.path.join(_lib_dir, get_library_name()))
  File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in **init**
    self._handle = _dlopen(self._name, mode)
OSError: /home/ping/env/lib/python3.4/site-packages/llvmlite/binding/libllvmlite.so: undefined symbol: _ZNSt14error_categoryC2Ev

**Comment by ml31415** [comment]
Just had updated from 0.18.1 to recent pypi, got the same error :(

**Comment by seibert** [comment]
This was likely a weird issue with LLVM.  Hopefully this kind of problem is less common now that we have precompiled wheels in addition to conda package.
