### ISSUE TITLE
CUDA test_matmul may use invalid grid size on devices with CC 2.1

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#1168]
Reported on the mailing list by a user with a GT630M (CC 2.1):

```
======================================================================
ERROR: test_func (numba.cuda.tests.cudapy.test_matmul.TestCudaMatMul)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Conda\anaconda3\lib\site-packages\numba\cuda\tests\cudapy\test_matmul.py", line 60, in test_func
    cu_square_matrix_mul[(bpg, bpg), (tpb, tpb), stream](dA, dB, dC)
  File "C:\Conda\anaconda3\lib\site-packages\numba\cuda\compiler.py", line 307, in __call__
    sharedmem=self.sharedmem)
  File "C:\Conda\anaconda3\lib\site-packages\numba\cuda\compiler.py", line 347, in _kernel_call
    cu_func(*args)
  File "C:\Conda\anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1045, in __call__
    self.sharedmem, streamhandle, args)
  File "C:\Conda\anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1089, in launch_kernel
    None)
  File "C:\Conda\anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 215, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Conda\anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 245, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: Call to cuLaunchKernel results in CUDA_ERROR_LAUNCH_OUT_OF_RESOURCES
```

**Comment by stuartarchibald** [comment]
Closing as CC2.1 is not supported in latest releases (current is 0.40.0).
