### ISSUE TITLE
Record array not supported by dufunc

### ISSUE THREAD

**Issue by sklam** [numba/numba#1314]
```python
from numba import vectorize, njit
import numpy as np

rec_dtype = np.dtype([('x', np.int32)])
rec_array = np.recarray(2, dtype=rec_dtype)


@vectorize
def foo(a):
    return a.x + 1

print(foo(rec_array))
```
outputs:
```
Traceback (most recent call last):
  File "rectest.py", line 14, in <module>
    print(foo(rec_array))
TypeError: Not implemented for this type
```

Calling dufunc from njit also fail:

```python


@njit
def bar(a):
    return foo(a)

print(bar(rec_array))
```

```
Traceback (most recent call last):
  File "/Users/sklam/dev/numba/numba/lowering.py", line 172, in lower_block
    self.lower_inst(inst)
  File "/Users/sklam/dev/numba/numba/lowering.py", line 212, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/sklam/dev/numba/numba/lowering.py", line 361, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/sklam/dev/numba/numba/lowering.py", line 562, in lower_expr
    return self.lower_call(resty, expr)
  File "/Users/sklam/dev/numba/numba/lowering.py", line 533, in lower_call
    res = impl(self.builder, argvals)
  File "/Users/sklam/dev/numba/numba/targets/base.py", line 1090, in __call__
    return self._imp(self._context, builder, self._sig, args)
  File "/Users/sklam/dev/numba/numba/npyufunc/dufunc.py", line 58, in __call__
    explicit_output=explicit_output)
  File "/Users/sklam/dev/numba/numba/targets/npyimpl.py", line 309, in numpy_ufunc_kernel
    val_out = kernel.generate(*vals_in)
  File "/Users/sklam/dev/numba/numba/npyufunc/dufunc.py", line 38, in generate
    self.builder, entry_point, isig.return_type, isig.args, cast_args)
  File "/Users/sklam/dev/numba/numba/targets/callconv.py", line 389, in call_function
    code = builder.call(callee, realargs)
  File "/Users/sklam/dev/.conda.workspace/llvm36/lib/python3.4/site-packages/llvmlite/ir/builder.py", line 452, in call
    cconv=cconv, tail=tail)
  File "/Users/sklam/dev/.conda.workspace/llvm36/lib/python3.4/site-packages/llvmlite/ir/instructions.py", line 74, in __init__
    raise TypeError(msg.format(1 + argno, exptype, arg.type))
TypeError: Type of #4 arg mismatch: [4 x i8]* != [4 x i8]
```

This looks a calling convention mismatch.

**Comment by stuartarchibald** [comment]
This is still a problem on 0.49.x
