### ISSUE TITLE
Support recursion for autojit functions

### ISSUE THREAD

**Issue by markflorisson** [numba/numba#136]

**Comment by dnelson86** [comment]
I'm also interested in this. Here is a basic example which currently fails and shows the behavior I would need:

```
@jit(nopython=True, nogil=True)
def _updateNodeRecursive2(last):
    if last > 3:
        return

    for i in range(4):
        last += 1
        _updateNodeRecursive2(last)

@jit(nopython=True, nogil=True)
def _constructTree2():
    last = np.int32(-1)
    _updateNodeRecursive2(last)

def test():
    _constructTree2()
```

which gives

```
Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x2b69013be390>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "python2.7/site-packages/numba-0.24.0-py2.7-linux-x86_64.egg/numba/typeinfer.py", line 114, in propagate
    constraint(typeinfer)
  File "python2.7/site-packages/numba-0.24.0-py2.7-linux-x86_64.egg/numba/typeinfer.py", line 305, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "python2.7/site-packages/numba-0.24.0-py2.7-linux-x86_64.egg/numba/typeinfer.py", line 332, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "python2.7/site-packages/numba-0.24.0-py2.7-linux-x86_64.egg/numba/typing/context.py", line 126, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "python2.7/site-packages/numba-0.24.0-py2.7-linux-x86_64.egg/numba/types.py", line 451, in get_call_type
    sig = template(context).apply(args, kws)
  File "python2.7/site-packages/numba-0.24.0-py2.7-linux-x86_64.egg/numba/typing/templates.py", line 280, in apply
    assert cases
AssertionError
```

**Comment by dnelson86** [comment]
Saw #1928, updated to master and this is now working! Nice timing.

**Comment by seibert** [comment]
Closing this issue for now.  If anyone needs something beside direct recursion, we should open a new issue.
