### ISSUE TITLE
ValueError when I use "@jit" 

### ISSUE THREAD

**Issue by XuJiahao** [numba/numba#1368]
I got a ValueError when I use numba. And now I don't know what should I do...

Just run this code in a new IPython, I would get the error:
```py
from numba import jit
@jit
def greyCenter(ima, (vu, hl), (vd, hr)):
    hc = vc = np.ones((vd - vu, hr - hl))
    hc = hc * np.arange(hl, hr)
    vc = (vc.T * np.arange(vu, vd)).T

    gm = ima[vu:vd, hl:hr].astype('int')

    hc = hc * gm
    vc = vc * gm

    hcen = int(round(hc.sum() / gm.sum()))
    vcen = int(round(vc.sum() / gm.sum()))

    return (vcen, hcen)
```

I use anaconda in windows 10 and update all packages into newest.

Thanks for help!
**I'm so sorry that I can't speak English well...**

**Comment by gmarkall** [comment]
Reproduced a `ValueError` with:

```python
import numpy as np
a = np.zeros((10, 10))
greyCenter(a, (1, 1), (1, 1))
```

Giving the traceback:

```
$ python test.py 
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    @jit
  File "/home/gmarkall/miniconda3/envs/py27np19/lib/python2.7/site-packages/numba/decorators.py", line 155, in jit
    targetoptions=options)
  File "/home/gmarkall/miniconda3/envs/py27np19/lib/python2.7/site-packages/numba/dispatcher.py", line 262, in __init__
    pysig = utils.pysignature(py_func)
  File "/home/gmarkall/miniconda3/envs/py27np19/lib/python2.7/site-packages/funcsigs/__init__.py", line 94, in signature
    return Signature.from_function(obj)
  File "/home/gmarkall/miniconda3/envs/py27np19/lib/python2.7/site-packages/funcsigs/__init__.py", line 544, in from_function
    kind=_POSITIONAL_OR_KEYWORD))
  File "/home/gmarkall/miniconda3/envs/py27np19/lib/python2.7/site-packages/funcsigs/__init__.py", line 261, in __init__
    raise ValueError(msg)
ValueError: '.1' is not a valid parameter name
```

**Comment by pitrou** [comment]
I guess this is because we don't support argument tuple unpacking?

**Comment by XuJiahao** [comment]
Think you very much! It works now!
