### ISSUE TITLE
Cannot execute NumPy methods on non-contiguous arrays

### ISSUE THREAD

**Issue by aymkhalil** [numba/numba#1418]
Functions decorated with @numba.jit(nopython=True) fail to call NumPy methods with non-contiguous array parameters.

Python 2.7.10 |Anaconda 2.3.0 (x86_64):

```python
In [1]: import numpy as np

In [2]: import numba

In [3]: numba.__version__
Out[3]: '0.20.0'

In [4]: @numba.jit(nopython=True)
   ...: def sqrt(x):
   ...:         return np.sqrt(x)
   ...:

In [5]: x = np.arange(4).reshape(2, 2)

In [6]: x = x.T[0]

In [7]: sqrt(x)
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-7-2569bcc7af8e> in <module>()
----> 1 sqrt(x)

/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/dispatcher.pyc in _compile_for_args(self, *args, **kws)
    157         assert not kws
    158         sig = tuple([self.typeof_pyval(a) for a in args])
--> 159         return self.compile(sig)
    160
    161     def inspect_llvm(self, signature=None):

/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/dispatcher.pyc in compile(self, sig)
    320                                           self.py_func,
    321                                           args=args, return_type=return_type,
--> 322                                           flags=flags, locals=self.locals)
    323
    324             # Check typing error if object mode is used

/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    592     pipeline = Pipeline(typingctx, targetctx, library,
    593                         args, return_type, flags, locals)
--> 594     return pipeline.compile_extra(func)
    595
    596

/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.pyc in compile_extra(self, func)
    315                 raise e
    316
--> 317         return self.compile_bytecode(bc, func_attr=self.func_attr)
    318
    319     def compile_bytecode(self, bc, lifted=(), lifted_from=None,

/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.pyc in compile_bytecode(self, bc, lifted, lifted_from, func_attr)
    324         self.lifted_from = lifted_from
    325         self.func_attr = func_attr
--> 326         return self._compile_bytecode()
    327
    328     def compile_internal(self, bc, func_attr=DEFAULT_FUNCTION_ATTRIBUTES):

/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.pyc in _compile_bytecode(self)
    579
    580         pm.finalize()
--> 581         return pm.run(self.status)
    582
    583

/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.pyc in run(self, status)
    207                     # No more fallback pipelines?
    208                     if is_final_pipeline:
--> 209                         raise patched_exception
    210                     # Go to next fallback pipeline
    211                     else:

TypingError: Caused By:
Traceback (most recent call last):
  File "/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 201, in run
    res = stage()
  File "/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 414, in stage_nopython_frontend
    self.locals)
  File "/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 709, in type_inference_stage
    infer.propagate()
  File "/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 399, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "/Users/Ayman/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 104, in propagate
    loc=constrain.loc)
TypingError: Internal error at <numba.typeinfer.CallConstrain object at 0x105dec390>:
Don't know how to create implicit output array with 'A' layout.
File "<ipython-input-4-fcf0066fb0c7>", line 3

Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstrain object at 0x105dec390>:
Don't know how to create implicit output array with 'A' layout.
File "<ipython-input-4-fcf0066fb0c7>", line 3
```

**Comment by ketch** [comment]
@ahmadia: We're trying to accelerate PyClaw kernels with Numba and ran into this.  As you know, we use Fortran contiguous arrays for compatibility with other pieces of code.  It would be nice if we didn't have to change that.

**Comment by ahmadia** [comment]
Thanks for the report @aymkhalil and @ketch.  For now, can you use `np.copy` to pull out contiguous strips of the data you'll be working on?

```
x = np.copy(x.T[0])
```

I agree that would be ideal if Numba could handle arbitrary strides/slicing.

**Comment by ahmadia** [comment]
And feel free to ping me by email if you have more questions :)

**Comment by aymkhalil** [comment]
Thank you @ahmadia. So `x = np.copy(x.T[0])` and `x = np.ascontiguousarray(x.T[0])` does the trick, they just come with a performance hit.

**Comment by pitrou** [comment]
This was fixed in #1421.

**Comment by ahmadia** [comment]
@aymkhalil - you should be able to test this again Numba master if you'd like to avoid the performance hit and to keep your code simpler :)

**Comment by aymkhalil** [comment]
@ahmadia - I pulled that and it is working fine. Thank you!
