### ISSUE TITLE
inspect_types() raising KeyError

### ISSUE THREAD

**Issue by WeatherGod** [numba/numba#1466]
The following example, in numba v0.21.0, will raise a KeyError:
```
from __future__ import print_function
from numba import jit
import numpy as np


@jit
def distance(fromLons, fromLats, toLons, toLats):
    fromLons = np.radians(fromLons)
    fromLats = np.radians(fromLats)
    toLons = np.radians(toLons)
    toLats = np.radians(toLats)

    # Haversine formula
    return (6371.0 * 2.0 * np.arcsin(np.sqrt(np.sin((toLats - fromLats)/2.0) ** 2
                          + np.cos(fromLats) * np.cos(toLats)
                        * np.sin((toLons - fromLons)/2.0) ** 2)))



if __name__ == '__main__':
    a = np.linspace(0, 360, 20)
    b = np.linspace(10, 55, 25)

    distance(a, b[:20], 1.75, 1.5)
    distance(a[:, None], b[None, :], 1.75, 1.5)

    print("distance() types:\n", distance.inspect_types())
```

The traceback:
```
bash-4.1$ python numba_scce.py 
distance (array(float64, 1d, C), array(float64, 1d, C), float64, float64)
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "numba_scce.py", line 27, in <module>
    print("distance() types:\n", distance.inspect_types())
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/numba/dispatcher.py", line 194, in inspect_types
    print(res.type_annotation, file=file)
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/numba/annotations/type_annotations.py", line 266, in __str__
    return self.annotate()
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/numba/annotations/type_annotations.py", line 127, in annotate
    groupedinst = self.prepare_annotations()
  File "/home/broot/scratch/miniconda/lib/python2.7/site-packages/numba/annotations/type_annotations.py", line 111, in prepare_annotations
    atype = self.typemap[inst.target.name]
KeyError: 'fromLons_1'
```
I should note that commenting out the first call to `distance()` will not result in an error.

**Comment by arandaw** [comment]
I can reproduce a somewhat similar error since v0.22 or 0.23:

```python
Traceback (most recent call last):
  ...
  File "...", line 477, in <module>
    @numba.jit("void(float64[:], float64[:], float64, float64, float64[:])", nopython=True, cache=True)
  File "C:\Anaconda3\lib\site-packages\numba\decorators.py", line 169, in wrapper disp.compile(sig)
  File "C:\Anaconda3\lib\site-packages\numba\dispatcher.py", line 508, in compile self._cache.save_overload(sig, cres)
  File "C:\Anaconda3\lib\site-packages\numba\dispatcher.py", line 884, in save_overload self._save_data(data_name, cres)
  File "C:\Anaconda3\lib\site-packages\numba\dispatcher.py", line 981, in _save_data data = cres._reduce()
  File "C:\Anaconda3\lib\site-packages\numba\compiler.py", line 73, in _reduce typeann = str(self.type_annotation)
  File "C:\Anaconda3\lib\site-packages\numba\annotations\type_annotations.py", line 264,
  in __str__ return self.annotate()
  File "C:\Anaconda3\lib\site-packages\numba\annotations\type_annotations.py", line 125, 
  in annotate groupedinst = self.prepare_annotations()
  File "C:\Anaconda3\lib\site-packages\numba\annotations\type_annotations.py", line 106,
  in prepare_annotations atype = self.typemap[inst.target.name]
  
KeyError: '_141_11'
```

When debugging the interesting lines of code in `type_annotations.py` I saw that the key is somehow present in the typemap, but the formatting of the `inst.targets` name is wrong:

```python
>>> self.typemap['$141.41']
float64
>>> inst.target.name
'_141_11'
>>> self.typemap[inst.target.name]
Traceback (most recent call last):
  File "<debug input>", line 1, in <module>
KeyError: '_141_11'
```

Currently it seems like the error only occurs when the cache option is enabled.

**Comment by kitizz** [comment]
I'm also getting this error when I enable the cache option for some functions. I'm digging around, trying to figure out what about the functions appears to lead to this.

**Comment by kitizz** [comment]
Curious... I had a 3x10 array J and I was performing the following vectorized ops:
```python
u = a*(J[0]*z - dx*J[2])
v = a*(J[1]*z - dy*J[2])
```
I stopped getting KeyErrors when I put the ops into a loop:
```python
u = empty(10)
v = empty(10)
for i in range(10):
    u[i] = a*(J[0, i]*z - dx*J[2, i])
    v[i] = a*(J[1, i]*z - dy*J[2, i])
```

**Comment by smartass101** [comment]
I have also hit this bug (similar context as to what @kitizz has), still present in 0.28.1 in Anaconda. `cache=False` indeed does skip this bug.

**Comment by pitrou** [comment]
These are really two different bugs. The original bug (as posted by the OP) occurs even with caching disabled. Please post a new issue for the caching-specific bug.

**Comment by WeatherGod** [comment]
Thanks! I can confirm that my original problem is now fixed using the numba channel on conda.
