### ISSUE TITLE
Change in type promotion rules from numba 0.19->0.21 causes lowering error

### ISSUE THREAD

**Issue by talumbau** [numba/numba#1488]

**Comment by talumbau** [comment]
If you run this code:

https://gist.github.com/talumbau/de3cfd88b507b6601bea

with numba 0.21 and set `intdtype` to `'int32'` on line 41 you get this error:

```
Traceback (most recent call last):
  File "try3.py", line 87, in <module>
    hl_func(pm, pf)
  File "try3.py", line 47, in hl_func
    ap_func(pf.c02650, pf.c00100, pf._agierr, pf._posagi, pf._ywossbe, pf._ywossbc, pf._prexmp, pf.c04600, pf._ymod1, pf.c02500, pf.c02700, pf.e02615, pf.c02900, pf.e00100, pf.e02500, pf.XTOT, pm.II_em, pm.II_em_ps, pf.MARS, pf._sep, pm.II_prt, pf.DSI, )
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/dispatcher.py", line 171, in _compile_for_args
    return self.compile(sig)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/dispatcher.py", line 348, in compile
    flags=flags, locals=self.locals)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 637, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 358, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 367, in compile_bytecode
    return self._compile_bytecode()
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 624, in _compile_bytecode
    return pm.run(self.status)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 250, in run
    raise patched_exception
numba.errors.LoweringError: Caused By:
Traceback (most recent call last):
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 242, in run
    res = stage()
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 580, in stage_nopython_backend
    return self._backend(lowerfn, objectmode=False)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 533, in _backend
    lowered = lowerfn()
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 524, in backend_nopython_mode
    self.flags)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/compiler.py", line 766, in native_lowering_stage
    lower.lower()
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/lowering.py", line 123, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/lowering.py", line 158, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/lowering.py", line 183, in lower_function_body
    self.lower_block(block)
  File "/Users/talumbau/miniconda3/envs/heroku_aei/lib/python2.7/site-packages/numba/lowering.py", line 201, in lower_block
    raise LoweringError(msg, inst.loc)
LoweringError: Internal error:
NotImplementedError: No definition for lowering <class 'numba.types.Dispatcher'>(float64, float64, float64, float64, float64, int32, int32, int32, int64, array(int64, 1d, C), int32, float64, float64, int32) -> (float64, float64, float64, float64, int64, float64, int64, float64)
File "try3.py", line 38

Failed at nopython (nopython mode backend)
Internal error:
NotImplementedError: No definition for lowering <class 'numba.types.Dispatcher'>(float64, float64, float64, float64, float64, int32, int32, int32, int64, array(int64, 1d, C), int32, float64, float64, int32) -> (float64, float64, float64, float64, int64, float64, int64, float64)
File "try3.py", line 38
```

But it runs successfully with `intdtype = 'int64'`. With numba version 0.19, it run successfully when `intdtype` is either `'int32'` or `'int64'`. So, the question is:

- should it run successfully with either integer type, in which case numba 0.19 is more correct than 0.21, or is it correct to raise the error in 0.21 of numba, and if so, is that the best error exception to raise?

**Comment by seibert** [comment]
@pitrou: Can you take a look at this?
