### ISSUE TITLE
Numba installation fails after Conda installation

### ISSUE THREAD

**Issue by alirezastack** [numba/numba#1489]
The command below succeeded: 

`./conda install numba`

but installing `numba` fails:

`Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Kc7PcW/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LDkZyZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Kc7PcW/llvmlite`

I see this part that: `The following packages will be DOWNGRADED: llvmlite: 0.8.0.dev-py27_28 --> 0.7.0-py27_3`

`sudo pip install numba` gives error: 

```bash

Requirement already satisfied (use --upgrade to upgrade): numpy in /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python (from numba)
Requirement already satisfied (use --upgrade to upgrade): enum34 in /Library/Python/2.7/site-packages (from numba)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /Library/Python/2.7/site-packages (from numba)
Requirement already satisfied (use --upgrade to upgrade): funcsigs in /Library/Python/2.7/site-packages (from numba)
Requirement already satisfied (use --upgrade to upgrade): six in /Library/Python/2.7/site-packages (from singledispatch->numba)
Installing collected packages: llvmlite, numba
  Running setup.py install for llvmlite
    got version from file /private/tmp/pip-build-Kc7PcW/llvmlite/llvmlite/_version.py {'version': '0.7.0', 'full': '733306fa0556e2af5aef2df536e433d9607e1ba5'}
    /usr/bin/python /tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py
    LLVM version... 3.5.1
    MACOSX_DEPLOYMENT_TARGET=10.7 clang++ -std=c++11 -stdlib=libc++ -dynamiclib `llvm-config --cxxflags` assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.dylib `llvm-config --ldflags` `llvm-config --system-libs --libs all`
    assembly.cpp:25:17: error: use of undeclared identifier 'parseAssemblyString'; did you mean 'ParseAssemblyFile'?
        Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();
                    ^~~~~~~~~~~~~~~~~~~
                    ParseAssemblyFile
    /usr/local/Cellar/llvm/3.5.1/include/llvm/AsmParser/Parser.h:32:9: note: 'ParseAssemblyFile' declared here
    Module *ParseAssemblyFile(
            ^
    assembly.cpp:25:65: error: member reference type 'llvm::Module *' is a pointer; maybe you meant to use '->'?
        Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                                                                    ->
    assembly.cpp:25:66: error: no member named 'release' in 'llvm::Module'
        Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    3 errors generated.
    bitcode.cpp:13:30: error: use of undeclared identifier 'LLVMWriteBitcodeToMemoryBuffer'
        LLVMMemoryBufferRef MB = LLVMWriteBitcodeToMemoryBuffer(M);
                                 ^
    1 error generated.
    core.cpp:36:5: error: use of undeclared identifier 'LLVMParseCommandLineOptions'
        LLVMParseCommandLineOptions(2, argv, NULL);
        ^
    1 error generated.
    module.cpp:223:12: error: use of undeclared identifier 'LLVMCloneModule'; did you mean 'LLVMPY_CloneModule'?
        return LLVMCloneModule(M);
               ^~~~~~~~~~~~~~~
               LLVMPY_CloneModule
    module.cpp:221:1: note: 'LLVMPY_CloneModule' declared here
    LLVMPY_CloneModule(LLVMModuleRef M)
    ^
    1 error generated.
    executionengine.cpp:71:25: error: no matching constructor for initialization of 'llvm::EngineBuilder'
        llvm::EngineBuilder eb(std::unique_ptr<llvm::Module>(llvm::unwrap(M)));
                            ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::unique_ptr<llvm::Module>' to 'llvm::EngineBuilder' for 1st argument
    class EngineBuilder {
          ^
    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::unique_ptr<llvm::Module>' to 'const llvm::EngineBuilder' for 1st argument
    class EngineBuilder {
          ^
    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ExecutionEngine.h:594:3: note: candidate constructor not viable: no known conversion from 'std::unique_ptr<llvm::Module>' to 'llvm::Module *' for 1st argument
      EngineBuilder(Module *m) : M(m) {
      ^
    executionengine.cpp:105:12: error: use of undeclared identifier 'LLVMGetGlobalValueAddress'; did you mean 'LLVMPY_GetGlobalValueAddress'?
        return LLVMGetGlobalValueAddress(EE, Name);
               ^~~~~~~~~~~~~~~~~~~~~~~~~
               LLVMPY_GetGlobalValueAddress
    executionengine.cpp:102:1: note: 'LLVMPY_GetGlobalValueAddress' declared here
    LLVMPY_GetGlobalValueAddress(LLVMExecutionEngineRef EE,
    ^
    executionengine.cpp:112:12: error: use of undeclared identifier 'LLVMGetFunctionAddress'; did you mean 'LLVMPY_GetFunctionAddress'?
        return LLVMGetFunctionAddress(EE, Name);
               ^~~~~~~~~~~~~~~~~~~~~~
               LLVMPY_GetFunctionAddress
    executionengine.cpp:109:1: note: 'LLVMPY_GetFunctionAddress' declared here
    LLVMPY_GetFunctionAddress(LLVMExecutionEngineRef EE,
    ^
    executionengine.cpp:163:45: error: no type named 'MemoryBufferRef' in namespace 'llvm'; did you mean 'MemoryBuffer'?
                                          llvm::MemoryBufferRef MBR)
                                          ~~~~~~^~~~~~~~~~~~~~~
                                                MemoryBuffer
    /usr/local/Cellar/llvm/3.5.1/include/llvm/Support/MemoryBuffer.h:37:7: note: 'MemoryBuffer' declared here
    class MemoryBuffer {
          ^
    executionengine.cpp:172:49: error: virtual function 'getObject' has a different return type ('std::unique_ptr<llvm::MemoryBuffer>') than the function it overrides (which has return type 'llvm::MemoryBuffer *')
        virtual std::unique_ptr<llvm::MemoryBuffer> getObject(const llvm::Module* M)
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ObjectCache.h:36:25: note: overridden virtual function is here
      virtual MemoryBuffer* getObject(const Module* M) = 0;
              ~~~~~~~~~~~~~ ^
    executionengine.cpp:162:18: warning: 'LLVMPYObjectCache::notifyObjectCompiled' hides overloaded virtual function [-Woverloaded-virtual]
        virtual void notifyObjectCompiled(const llvm::Module *M,
                     ^
    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ObjectCache.h:30:16: note: hidden overloaded virtual function 'llvm::ObjectCache::notifyObjectCompiled' declared here: type mismatch at 2nd parameter ('const llvm::MemoryBuffer *' vs 'llvm::MemoryBuffer')
      virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;
                   ^
    executionengine.cpp:184:17: error: no viable overloaded '='
                res = llvm::MemoryBuffer::getMemBufferCopy(
                ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2459:29: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'llvm::MemoryBuffer *' to 'const std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >' for 1st argument
    class _LIBCPP_TYPE_VIS_ONLY unique_ptr
                                ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2544:47: note: candidate function not viable: no known conversion from 'llvm::MemoryBuffer *' to 'std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >' for 1st argument
            _LIBCPP_INLINE_VISIBILITY unique_ptr& operator=(unique_ptr&& __u) _NOEXCEPT
                                                  ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2600:43: note: candidate function not viable: no known conversion from 'llvm::MemoryBuffer *' to 'nullptr_t' for 1st argument
        _LIBCPP_INLINE_VISIBILITY unique_ptr& operator=(nullptr_t) _NOEXCEPT
                                              ^
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2560:13: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'llvm::MemoryBuffer *'
                operator=(unique_ptr<_Up, _Ep>&& __u) _NOEXCEPT
                ^
    executionengine.cpp:203:16: error: allocating an object of abstract class type 'LLVMPYObjectCache'
        return new LLVMPYObjectCache(notify_func, getobject_func);
                   ^
    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ObjectCache.h:30:16: note: unimplemented pure virtual method 'notifyObjectCompiled' in 'LLVMPYObjectCache'
      virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;
                   ^
    1 warning and 7 errors generated.
    linker.cpp:19:32: error: unknown type name 'DiagnosticInfo'
        auto diagnose = [&] (const DiagnosticInfo &DI) {
                                   ^
    linker.cpp:32:15: error: use of undeclared identifier 'LLVMCloneModule'
            Src = LLVMCloneModule(Src);
                  ^
    linker.cpp:33:74: error: too few arguments to function call, expected 4, have 3
        bool failed = Linker::LinkModules(unwrap(Dest), unwrap(Src), diagnose);
                      ~~~~~~~~~~~~~~~~~~~                                    ^
    /usr/local/Cellar/llvm/3.5.1/include/llvm/Linker/Linker.h:51:5: note: 'LinkModules' declared here
        static bool LinkModules(Module *Dest, Module *Src, unsigned Mode,
        ^
    3 errors generated.
    make: *** [all] Error 1
    Traceback (most recent call last):
      File "/tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py", line 114, in <module>
        main()
      File "/tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py", line 108, in main
        main_posix('osx', '.dylib')
      File "/tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py", line 96, in main_posix
        subprocess.check_call(['make', '-f', makefile])
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.osx']' returned non-zero exit status 2
    error: command '/usr/bin/python' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Kc7PcW/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LDkZyZ-record/install-record.txt --single-version-externally-managed --compile:
    running install

    running build

    got version from file /private/tmp/pip-build-Kc7PcW/llvmlite/llvmlite/_version.py {'version': '0.7.0', 'full': '733306fa0556e2af5aef2df536e433d9607e1ba5'}

    running build_ext

    /usr/bin/python /tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py

    LLVM version... 3.5.1

    MACOSX_DEPLOYMENT_TARGET=10.7 clang++ -std=c++11 -stdlib=libc++ -dynamiclib `llvm-config --cxxflags` assembly.cpp bitcode.cpp core.cpp initfini.cpp module.cpp value.cpp executionengine.cpp transforms.cpp passmanagers.cpp targets.cpp dylib.cpp linker.cpp -o libllvmlite.dylib `llvm-config --ldflags` `llvm-config --system-libs --libs all`

    assembly.cpp:25:17: error: use of undeclared identifier 'parseAssemblyString'; did you mean 'ParseAssemblyFile'?

        Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();

                    ^~~~~~~~~~~~~~~~~~~

                    ParseAssemblyFile

    /usr/local/Cellar/llvm/3.5.1/include/llvm/AsmParser/Parser.h:32:9: note: 'ParseAssemblyFile' declared here

    Module *ParseAssemblyFile(

            ^

    assembly.cpp:25:65: error: member reference type 'llvm::Module *' is a pointer; maybe you meant to use '->'?

        Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();

                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^

                                                                    ->

    assembly.cpp:25:66: error: no member named 'release' in 'llvm::Module'

        Module *m = parseAssemblyString(ir, error, *unwrap(context)).release();

                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

    3 errors generated.

    bitcode.cpp:13:30: error: use of undeclared identifier 'LLVMWriteBitcodeToMemoryBuffer'

        LLVMMemoryBufferRef MB = LLVMWriteBitcodeToMemoryBuffer(M);

                                 ^

    1 error generated.

    core.cpp:36:5: error: use of undeclared identifier 'LLVMParseCommandLineOptions'

        LLVMParseCommandLineOptions(2, argv, NULL);

        ^

    1 error generated.

    module.cpp:223:12: error: use of undeclared identifier 'LLVMCloneModule'; did you mean 'LLVMPY_CloneModule'?

        return LLVMCloneModule(M);

               ^~~~~~~~~~~~~~~

               LLVMPY_CloneModule

    module.cpp:221:1: note: 'LLVMPY_CloneModule' declared here

    LLVMPY_CloneModule(LLVMModuleRef M)

    ^

    1 error generated.

    executionengine.cpp:71:25: error: no matching constructor for initialization of 'llvm::EngineBuilder'

        llvm::EngineBuilder eb(std::unique_ptr<llvm::Module>(llvm::unwrap(M)));

                            ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'std::unique_ptr<llvm::Module>' to 'llvm::EngineBuilder' for 1st argument

    class EngineBuilder {

          ^

    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ExecutionEngine.h:570:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'std::unique_ptr<llvm::Module>' to 'const llvm::EngineBuilder' for 1st argument

    class EngineBuilder {

          ^

    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ExecutionEngine.h:594:3: note: candidate constructor not viable: no known conversion from 'std::unique_ptr<llvm::Module>' to 'llvm::Module *' for 1st argument

      EngineBuilder(Module *m) : M(m) {

      ^

    executionengine.cpp:105:12: error: use of undeclared identifier 'LLVMGetGlobalValueAddress'; did you mean 'LLVMPY_GetGlobalValueAddress'?

        return LLVMGetGlobalValueAddress(EE, Name);

               ^~~~~~~~~~~~~~~~~~~~~~~~~

               LLVMPY_GetGlobalValueAddress

    executionengine.cpp:102:1: note: 'LLVMPY_GetGlobalValueAddress' declared here

    LLVMPY_GetGlobalValueAddress(LLVMExecutionEngineRef EE,

    ^

    executionengine.cpp:112:12: error: use of undeclared identifier 'LLVMGetFunctionAddress'; did you mean 'LLVMPY_GetFunctionAddress'?

        return LLVMGetFunctionAddress(EE, Name);

               ^~~~~~~~~~~~~~~~~~~~~~

               LLVMPY_GetFunctionAddress

    executionengine.cpp:109:1: note: 'LLVMPY_GetFunctionAddress' declared here

    LLVMPY_GetFunctionAddress(LLVMExecutionEngineRef EE,

    ^

    executionengine.cpp:163:45: error: no type named 'MemoryBufferRef' in namespace 'llvm'; did you mean 'MemoryBuffer'?

                                          llvm::MemoryBufferRef MBR)

                                          ~~~~~~^~~~~~~~~~~~~~~

                                                MemoryBuffer

    /usr/local/Cellar/llvm/3.5.1/include/llvm/Support/MemoryBuffer.h:37:7: note: 'MemoryBuffer' declared here

    class MemoryBuffer {

          ^

    executionengine.cpp:172:49: error: virtual function 'getObject' has a different return type ('std::unique_ptr<llvm::MemoryBuffer>') than the function it overrides (which has return type 'llvm::MemoryBuffer *')

        virtual std::unique_ptr<llvm::MemoryBuffer> getObject(const llvm::Module* M)

                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^

    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ObjectCache.h:36:25: note: overridden virtual function is here

      virtual MemoryBuffer* getObject(const Module* M) = 0;

              ~~~~~~~~~~~~~ ^

    executionengine.cpp:162:18: warning: 'LLVMPYObjectCache::notifyObjectCompiled' hides overloaded virtual function [-Woverloaded-virtual]

        virtual void notifyObjectCompiled(const llvm::Module *M,

                     ^

    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ObjectCache.h:30:16: note: hidden overloaded virtual function 'llvm::ObjectCache::notifyObjectCompiled' declared here: type mismatch at 2nd parameter ('const llvm::MemoryBuffer *' vs 'llvm::MemoryBuffer')

      virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;

                   ^

    executionengine.cpp:184:17: error: no viable overloaded '='

                res = llvm::MemoryBuffer::getMemBufferCopy(

                ~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2459:29: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'llvm::MemoryBuffer *' to 'const std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >' for 1st argument

    class _LIBCPP_TYPE_VIS_ONLY unique_ptr

                                ^

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2544:47: note: candidate function not viable: no known conversion from 'llvm::MemoryBuffer *' to 'std::__1::unique_ptr<llvm::MemoryBuffer, std::__1::default_delete<llvm::MemoryBuffer> >' for 1st argument

            _LIBCPP_INLINE_VISIBILITY unique_ptr& operator=(unique_ptr&& __u) _NOEXCEPT

                                                  ^

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2600:43: note: candidate function not viable: no known conversion from 'llvm::MemoryBuffer *' to 'nullptr_t' for 1st argument

        _LIBCPP_INLINE_VISIBILITY unique_ptr& operator=(nullptr_t) _NOEXCEPT

                                              ^

    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2560:13: note: candidate template ignored: could not match 'unique_ptr<type-parameter-0-0, type-parameter-0-1>' against 'llvm::MemoryBuffer *'

                operator=(unique_ptr<_Up, _Ep>&& __u) _NOEXCEPT

                ^

    executionengine.cpp:203:16: error: allocating an object of abstract class type 'LLVMPYObjectCache'

        return new LLVMPYObjectCache(notify_func, getobject_func);

                   ^

    /usr/local/Cellar/llvm/3.5.1/include/llvm/ExecutionEngine/ObjectCache.h:30:16: note: unimplemented pure virtual method 'notifyObjectCompiled' in 'LLVMPYObjectCache'

      virtual void notifyObjectCompiled(const Module *M, const MemoryBuffer *Obj) = 0;

                   ^

    1 warning and 7 errors generated.

    linker.cpp:19:32: error: unknown type name 'DiagnosticInfo'

        auto diagnose = [&] (const DiagnosticInfo &DI) {

                                   ^

    linker.cpp:32:15: error: use of undeclared identifier 'LLVMCloneModule'

            Src = LLVMCloneModule(Src);

                  ^

    linker.cpp:33:74: error: too few arguments to function call, expected 4, have 3

        bool failed = Linker::LinkModules(unwrap(Dest), unwrap(Src), diagnose);

                      ~~~~~~~~~~~~~~~~~~~                                    ^

    /usr/local/Cellar/llvm/3.5.1/include/llvm/Linker/Linker.h:51:5: note: 'LinkModules' declared here

        static bool LinkModules(Module *Dest, Module *Src, unsigned Mode,

        ^

    3 errors generated.

    make: *** [all] Error 1

    Traceback (most recent call last):

      File "/tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py", line 114, in <module>

        main()

      File "/tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py", line 108, in main

        main_posix('osx', '.dylib')

      File "/tmp/pip-build-Kc7PcW/llvmlite/ffi/build.py", line 96, in main_posix

        subprocess.check_call(['make', '-f', makefile])

      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call

        raise CalledProcessError(retcode, cmd)

    subprocess.CalledProcessError: Command '['make', '-f', 'Makefile.osx']' returned non-zero exit status 2

    error: command '/usr/bin/python' failed with exit status 1

    ----------------------------------------
    Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-Kc7PcW/llvmlite/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-LDkZyZ-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Kc7PcW/llvmlite

```

**Comment by pitrou** [comment]
I don't understand what you're doing. If you've installed Numba using `conda install numba`, why are you also doing `pip install numba`?

**Comment by alirezastack** [comment]
When I `import numba` it gives `Import error: No module named numba`. I thought I should install it with pip for python! 

With `Conda` it says:

```bash

Fetching package metadata: ....
Solving package specifications: .......................
# All requested packages already installed.
# packages in environment at /Users/a.user/anaconda:
#
numba                     0.21.0              np110py27_0

```

So what is the problem?

**Comment by pitrou** [comment]
I'm not sure, what do `conda info` and `which python` say?

**Comment by alirezastack** [comment]
```bash
$ ./conda info
Current conda install:

             platform : osx-64
        conda version : 3.18.3
  conda-build version : 1.14.1
       python version : 2.7.10.final.0
     requests version : 2.8.1
     root environment : /Users/a.hosseini/anaconda  (writable)
  default environment : /Users/a.hosseini/anaconda
     envs directories : /Users/a.hosseini/anaconda/envs
        package cache : /Users/a.hosseini/anaconda/pkgs
         channel URLs : https://repo.continuum.io/pkgs/free/osx-64/
                        https://repo.continuum.io/pkgs/free/noarch/
                        https://repo.continuum.io/pkgs/pro/osx-64/
                        https://repo.continuum.io/pkgs/pro/noarch/
          config file : None
    is foreign system : False
```

----

```bash
$ which python
/usr/bin/python
```

**Comment by pitrou** [comment]
> I should mention that I call conda from its directory ./conda. It is not callable from outside of the directory. 

That sounds weird. I suggest you describe your problem on the conda mailing-list: https://groups.google.com/a/continuum.io/forum/#!forum/conda

In any case, Numba will be available from conda's Python install. Conda doesn't install packages in the system Python (`/usr/bin/python`) as doing so could create versioning or dependency conflicts with other system packages. So in your case, calling `<path to conda>/python` should work fine.

**Comment by seibert** [comment]
Closing as this sounds like a conda installation problem.
