### ISSUE TITLE
pypi release broken (installing from github release is OK)

### ISSUE THREAD

**Issue by jennolsen84** [numba/numba#1523]
```
(myenv)root@201b2ba19e7c:~# pip install numba==0.22.0
Collecting numba==0.22.0
  Downloading numba-0.22.0.tar.gz (749kB)
    100% |████████████████████████████████| 749kB 932kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-_puxbp2o/numba/setup.py", line 14, in <module>
        import versioneer
    ImportError: No module named 'versioneer'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_puxbp2o/numba
```

But this works:

```
(myenv)root@201b2ba19e7c:~# pip install https://github.com/numba/numba/archive/0.22.0.tar.gz
Collecting https://github.com/numba/numba/archive/0.22.0.tar.gz
  Downloading https://github.com/numba/numba/archive/0.22.0.tar.gz
     - 1.1MB 11.9MB/s
Requirement already satisfied (use --upgrade to upgrade): llvmlite in ./pyenvs/myenv/lib/python3.4/site-packages (from numba==0.22.0)
Requirement already satisfied (use --upgrade to upgrade): numpy in ./pyenvs/myenv/lib/python3.4/site-packages (from numba==0.22.0)
Installing collected packages: numba
  Running setup.py install for numba
Successfully installed numba-0.22.0
```

**Comment by jennolsen84** [comment]
looks like a duplicate for #1513.  Closing
