### ISSUE TITLE
@jit hangs on lambda with "large number" of conditional statements

### ISSUE THREAD

**Issue by richardotis** [numba/numba#1529]
I have some lambda functions of arithmetic expressions (including piecewise implemented with if/else) which are auto-generated using sympy. On some of those functions, jit and vectorize work great. On others, they hang indefinitely. I'm not sure why and I'm hoping to get some guidance or perhaps help to diagnose a bug. The functions are simple arithmetic but have lots of small operations.

[lambda_fast_liquid.txt](https://github.com/numba/numba/files/32335/lambda_fast_liquid.txt)
[lambda_slow_bcc.txt](https://github.com/numba/numba/files/32336/lambda_slow_bcc.txt)

The first one works without issues.

``` python
import numpy as np
import numba
with open('lambda_fast_liquid.txt') as file_:
    fast_func = eval(file_.read(), np.__dict__)
jitted_fast_func = numba.jit(fast_func)
assert jitted_fast_func(0., 0., 0.) == 0.
```

The second one hangs (numba 0.22.1).

``` python
import numpy as np
import numba
with open('lambda_slow_bcc.txt') as file_:
    slow_func = eval(file_.read(), np.__dict__)
jitted_slow_func = numba.jit(slow_func) # hangs
assert jitted_slow_func(0., 0., 0., 0., 0.) == 0.
```

**Comment by richardotis** [comment]
The hanging function is spending a lot of time here: https://github.com/numba/numba/blob/1902d7f0cfdab11ec75aab0b5adbc8f8ab2d8740/numba/dataflow.py#L675

**Comment by richardotis** [comment]
Thanks to @shoyer I tried replacing my nested if/else statements with this function:

```python
@numba.vectorize
def where(condition, x, y):
    if condition:
        return x
    else:
        return y
```

This works very well and seems to work around this issue. (See #1530 for why I don't just use `numpy.where`.)

**Comment by seibert** [comment]
I'm glad you were able to find a workaround, but this definitely looks like a problem for us when dealing with extremely complex expressions.  Reopening so we can track solution of this.

**Comment by seibert** [comment]
I let this run for 7 hours, and it never completed.  When I finally killed it, the backtrace looked like this:
```
Traceback (most recent call last):
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/compiler.py", line 243, in run
    res = stage()
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/compiler.py", line 385, in stage_analyze_bytecode
    self.interp = translate_stage(self.bc)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/compiler.py", line 716, in translate_stage
    interp = interpreter.Interpreter(bytecode=bytecode)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/interpreter.py", line 103, in __init__
    self.dfa.run()
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 27, in run
    self.infos[blk.offset] = self.run_on_block(blk)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 71, in run_on_block
    self.dispatch(info, inst)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 81, in dispatch
    fn(info, inst)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 321, in _binaryop
    lhs = info.pop()
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 657, in pop
    return self.make_incoming()
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 672, in make_incoming
    ib.request_outgoing(self, ret, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 687, in request_outgoing
    ib.request_outgoing(self, phiname, stack_index)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba-0.22.1+13.g1902d7f-py2.7-macosx-10.5-x86_64.egg/numba/dataflow.py", line 685, in request_outgoing
    assert self.incoming_blocks
```

**Comment by seibert** [comment]
Verified that this is still a problem with Numba 0.26.0.

**Comment by stuartarchibald** [comment]
This works on Numba 0.43.1, takes a minute or so but does it. Closing.
