### ISSUE TITLE
numba's numpy.where doesn't accept scalar inputs for arguments

### ISSUE THREAD

**Issue by richardotis** [numba/numba#1530]
Example
```python
import numpy as np
import numba
test_func = lambda x, y: np.where(x<y, x, y)
test_func = numba.jit(nopython=True)(test_func)
test_func(1, 3)
```
```python
Traceback (most recent call last):
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typeinfer.py", line 111, in propagate
    constraint(typeinfer)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typeinfer.py", line 270, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typeinfer.py", line 297, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typing/context.py", line 113, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/types.py", line 222, in get_call_type
    return self.template(context).apply(args, kws)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typing/templates.py", line 155, in apply
    sig = generic(args, kws)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typing/npydecl.py", line 747, in generic
    if (cond.ndim == x.ndim == y.ndim and
AttributeError: 'Boolean' object has no attribute 'ndim'
```

Attempts to coerce the scalars into numpy objects (thus with an `ndim` attribute) inside a nopython function have mostly failed.

**Comment by richardotis** [comment]
Replacing `numpy.where` with this snippet seems to work okay as a workaround.

```python
@numba.vectorize
def nbwhere(condition, x, y):
    if condition:
        return x
    else:
        return y
```
