### ISSUE TITLE
@guvectorize missing namespace variables in nopython mode

### ISSUE THREAD

**Issue by richardotis** [numba/numba#1532]
``` python
import numba
import numpy as np
external = lambda *args: np.sum(args)

@numba.guvectorize(['float64[:], float64[:]'], '(n)->(n)', nopython=False)
def func(args, result):
    result[:] = external(args)

result = np.empty((1,1))
func(np.ones((1,1)), result)
print(result)
```

```
[[ 1.]]
```

The only change is we turn on nopython mode.

``` python
import numba
import numpy as np
external = lambda *args: np.sum(args)

@numba.guvectorize(['float64[:], float64[:]'], '(n)->(n)', nopython=True)
def func(args, result):
    result[:] = external(args)

result = np.empty((1,1))
func(np.ones((1,1)), result)
print(result)
```

```
Traceback (most recent call last):
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/compiler.py", line 458, in stage_nopython_frontend
    self.locals)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/compiler.py", line 758, in type_inference_stage
    infer.build_constraint()
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typeinfer.py", line 494, in build_constraint
    self.constrain_statement(inst)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typeinfer.py", line 651, in constrain_statement
    self.typeof_assign(inst)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typeinfer.py", line 691, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/home/rotis/anaconda/envs/calphad/lib/python2.7/site-packages/numba/typeinfer.py", line 756, in typeof_global
    loc=inst.loc)
TypingError: Untyped global name 'external'
File "<ipython-input-20-8b7d439406ad>", line 7
```

**Comment by richardotis** [comment]
This has something to do with callables because if I change `external` to a tuple of float I can access those values in nopython mode fine.

**Comment by seibert** [comment]
nopython mode functions can only call other nopython mode functions.  The `external` function will not automatically be compiled.  You can jit it by calling the decorator as a function (i.e. `external = numba.jit(lambda ...`).

However, making that change reveals a different problem with limitations in our handling of `*args`.  In this code, it appears that you are wanting to capture array argument to `func` into the lambda function `*args` list, and the sum a list that contains one array?  That looks odd to me, but perhaps this is because the example has been simplified from a bigger code base.

If you can eliminate the need for `*args` calls inside nopython mode, you will be less like to run into problems with our static type inferencer.  For example, this version of the code does the same thing as the object mode example you give, but runs purely in nopython mode:
``` python
import numba
import numpy as np
external = numba.jit(lambda args: np.sum(args))	 # <- CHANGED THIS LINE

@numba.guvectorize(['float64[:], float64[:]'], '(n)->(n)', nopython=True)
def func(args, result):
    result[:] = external(args)

result = np.empty((1,1))
func(np.ones((1,1)), result)
print(result)
```

**Comment by richardotis** [comment]
Thanks for the response @seibert . I may have oversimplified in my quest to construct a MNWE. Here is a snippet of my actual code. I am trying to construct a vectorized gradient (and eventually Hessian) function.

```python
from sympy import lambdify
from pycalphad.core.utils import NumPyPrinter

import numba
import numpy as np
@numba.vectorize
def where(condition, x, y):
    if condition:
        return x
    else:
        return y
def make_gradient_from_graph(graph, wrt):
    wrt = tuple(wrt)
    grads = np.empty((len(wrt)), dtype=object)
    hess = np.empty((len(wrt), len(wrt)), dtype=object)
    for i in range(len(wrt)):
        grads[i] = graph.diff(wrt[i])
        for j in range(i, len(wrt)):
            hess[i][j] = numba.jit(lambdify(tuple(wrt), grads[i].diff(wrt[j]), dummify=True,
                                         modules=[{'where': where}, 'numpy'], printer=NumPyPrinter), nopython=True)
        grads[i] = numba.jit(lambdify(tuple(wrt), grads[i], dummify=True,
                                            modules=[{'where': where}, 'numpy'], printer=NumPyPrinter), nopython=True)
    grads = tuple(grads.tolist())
    @numba.guvectorize(['float64[:], float64[:]'], '(n)->(n)', nopython=True)
    def grad_func(args, result):
        for i in range(len(grads)):
            result[i] = grads[i](*args)
        return result
    return grad_func
```

Calling the `grad_func` returned by this function will give an untyped global error about `grads`. I understand what you are saying about starargs interacting poorly with Numba. In this example `len(args) == len(grads) == len(wrt)` but I have no idea how to write `grad_func` in a way that Numba will understand that. Do you have any suggestions?

**Comment by richardotis** [comment]
Just to clarify, `lambdify` here returns a function which accepts `len(wrt)` float arguments and returns a float. I don't know how to construct a "def" function which accepts a variable number of arguments without using starargs here. (Lambdas+eval is out because I can't use a for loop.)

If I write it like I did above and use a single argument as an array, at some point I have to unpack it to pass to `grads[i]`. The only ways I know how are either starargs or `itertools.chain`, neither of which are apparently allowed in nopython mode.

**Comment by seibert** [comment]
OK, I think I understand.  This is starting to push into the kind of use case where static compilation systems tend to use metaprogramming or macros (which Python doesn't really have) to express what you are trying to do.

Need to think about this one a bit...

**Comment by richardotis** [comment]
I'm still working on it, but I'll paste this snippet so you can see where I'm heading with this. (`lengthfix` is necessary because `guvectorize` needs `n` defined on the input side.)

```python
# forgive me guido
grad_code = compile("""def grad_func(x1, x2, x3, x4, x5, x6, lengthfix, result):
    for i in range(6):
        result[i] = grad(x1[0], x2[0], x3[0], x4[0], x5[0], x6[0])""", '<string>', 'exec')
namespace = {'grad': grads[0]}
exec grad_code in namespace
grad_func = numba.guvectorize(['float64[:], float64[:], float64[:], float64[:], float64[:], float64[:], float64[:], float64[:]'],
'(),(),(),(),(),(),(n)->(n)', nopython=True)(namespace['grad_func'])
```

**Comment by richardotis** [comment]
Incidentally, this code works in nopython mode but *won't* in object mode because `grad` only exists in the namespace defined by `namespace`.

**Comment by richardotis** [comment]
For reference this is what I ended up doing, in case someone else needs to figure out how to work around this issue. Essentially `exec` and `compile()` are doing the heavy lifting as far as metaprogramming goes. It works in nopython mode with a nice speedup in my use case, though compile time is currently an issue. For a six variable gradient, the compile time is about a minute. For the Hessian, it's about 14 minutes. Since a typical computation takes about a minute, I haven't been able to make it worth implementing in production yet.

```python
from sympy import lambdify
import numba
def make_gradient_from_graph(graph, wrt):
    wrt = tuple(wrt)
    grads = np.empty((len(wrt)), dtype=object)
    hess_indices = []
    namespace = {}
    for i in range(len(wrt)):
        grads[i] = graph.diff(wrt[i])
        for j in range(i, len(wrt)):
            namespace['hess_{0}{1}'.format(i, j)] = numba.vectorize(lambdify(tuple(wrt), grads[i].diff(wrt[j]), dummify=True,
                                                              modules=[{'where': where}, 'numpy'], printer=NumPyPrinter))
            hess_indices.append((i, j))
        namespace['grad_{0}'.format(i)] = numba.vectorize(lambdify(tuple(wrt), grads[i], dummify=True,
                                                    modules=[{'where': where}, 'numpy'], printer=NumPyPrinter))
    # Build the gradient and Hessian using compile() and exec
    # We do this because Numba needs "static" information about the arguments and functions
    call_args = ','.join(['_x{0}'.format(i) for i in range(len(wrt))])
    call_passed_args = ','.join(['_x{0}[0]'.format(i) for i in range(len(wrt))])

    grad_code = 'def grad_func({0}, lengthfix, result):'.format(call_args)
    grad_list = ['    result[{0}] = grad_{0}({1})'.format(i, call_passed_args) for i in range(len(wrt))]
    grad_code = grad_code + '\n' + '\n'.join(grad_list)
    print(grad_code)
    
    grad_code = compile(grad_code, '<string>', 'exec')
    try:
        exec grad_code in namespace
    except SyntaxError:
        exec(grad_code, namespace)

    # Now construct the Hessian
    hess_code = 'def hess_func({0}, lengthfix, result):'.format(call_args)
    hess_list = ['    result[{0},{1}] = result[{1}, {0}] = hess_{0}{1}({2})'.format(i, j, call_passed_args) for i, j in hess_indices]
    hess_code = hess_code + '\n' + '\n'.join(hess_list)
    print(hess_code)
    
    hess_code = compile(hess_code, '<string>', 'exec')
    try:
        exec hess_code in namespace
    except SyntaxError:
        exec(hess_code, namespace)

    grad_func = numba.guvectorize([','.join(['float64[:]'] * (len(wrt)+2))],
                                   ','.join(['()'] * len(wrt)) + ',(n)->(n)', nopython=True)(namespace['grad_func'])
    hess_func = None
    hess_func = numba.guvectorize([','.join(['float64[:]'] * (len(wrt)+1)) + ',float64[:,:]'],
                                   ','.join(['()'] * len(wrt)) + ',(n)->(n,n)', nopython=True)(namespace['hess_func'])
    return grad_func, hess_func
```

**Comment by richardotis** [comment]
This is what the generated functions look like
```python
def grad_func(_x0,_x1,_x2,_x3,_x4,_x5, lengthfix, result):
    result[0] = grad_0(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[1] = grad_1(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[2] = grad_2(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[3] = grad_3(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[4] = grad_4(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[5] = grad_5(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
def hess_func(_x0,_x1,_x2,_x3,_x4,_x5, lengthfix, result):
    result[0,0] = result[0, 0] = hess_00(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[0,1] = result[1, 0] = hess_01(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[0,2] = result[2, 0] = hess_02(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[0,3] = result[3, 0] = hess_03(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[0,4] = result[4, 0] = hess_04(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[0,5] = result[5, 0] = hess_05(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[1,1] = result[1, 1] = hess_11(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[1,2] = result[2, 1] = hess_12(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[1,3] = result[3, 1] = hess_13(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[1,4] = result[4, 1] = hess_14(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[1,5] = result[5, 1] = hess_15(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[2,2] = result[2, 2] = hess_22(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[2,3] = result[3, 2] = hess_23(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[2,4] = result[4, 2] = hess_24(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[2,5] = result[5, 2] = hess_25(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[3,3] = result[3, 3] = hess_33(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[3,4] = result[4, 3] = hess_34(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[3,5] = result[5, 3] = hess_35(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[4,4] = result[4, 4] = hess_44(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[4,5] = result[5, 4] = hess_45(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
    result[5,5] = result[5, 5] = hess_55(_x0[0],_x1[0],_x2[0],_x3[0],_x4[0],_x5[0])
```

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
