### ISSUE TITLE
runtests.py issue: no module named -v

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1564]
Apparently option parsing is broken on Python 2:

```
$ python -V
Python 2.7.10 :: Continuum Analytics, Inc.
$ ./runtests.py numba.tests.test_builtins -v 
Traceback (most recent call last):
  File "./runtests.py", line 9, in <module>
    result = testing.run_tests(sys.argv)
  File "/home/antoine/numba/numba/testing.py", line 558, in run_tests
    nomultiproc=nomultiproc)
  File "/home/antoine/numba/numba/testing.py", line 129, in __init__
    super(NumbaTestProgram, self).__init__(*args, **kwargs)
  File "/home/antoine/np16/lib/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/home/antoine/numba/numba/testing.py", line 159, in parseArgs
    super(NumbaTestProgram, self).parseArgs(argv)
  File "/home/antoine/np16/lib/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/home/antoine/np16/lib/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/home/antoine/np16/lib/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/antoine/np16/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named -v
```

**Comment by pitrou** [comment]
@stefanseefeld

**Comment by pitrou** [comment]
It looks like that works if `-v` comes before the test name:

```
$ ./runtests.py -v numba.tests.test_builtins 
test_abs (numba.tests.test_builtins.TestBuiltins) ... ok
test_abs_npm (numba.tests.test_builtins.TestBuiltins) ... ok
[...]
```

**Comment by stefanseefeld** [comment]
Yes, that is indeed the supported spelling. (See `./runtest.py -h`)

**Comment by pitrou** [comment]
Ok. That was because my fingers are trained to do the following:
```
$ python -m numba.tests.test_builtins -v
test_abs (__main__.TestBuiltins) ... ok
test_abs_npm (__main__.TestBuiltins) ... ok
[...]
```

**Comment by pitrou** [comment]
Let's close this as it is a Python unittest issue, then.
