### ISSUE TITLE
Error when linking a function in a library with cache=True in another numba function

### ISSUE THREAD

**Issue by synapticarbors** [numba/numba#1603]
I've started using numba's caching feature and it has been fantastic in terms of removing the overhead from jit-ing the code (especially important when you have to run the same script many times). I've run into an issue where I get a linking problem, and I think I've been able to reproduce it with a minimal example, which can be found in the following gist:

https://gist.github.com/synapticarbors/22022c166e3776bb3e0b

and copied below:

`lib1.py`
```python
import numba as nb

@nb.jit(nopython=True, cache=True)
def func(y):
    s = 0.0

    for k in range(y.shape[0]):
        s += y[k]

    return s
```

and `app.py`

```python
import numpy as np
import numba as nb

import lib1


@nb.jit(nopython=True)
def fcalc(x):
    s = lib1.func(x)
    return s * 0.5 - 1.0


def run(N):
    x = np.linspace(-1.0, 1.0, N)
    res = fcalc(x)

    print res

if __name__ == '__main__':
    N = 1000
    run(N)
```

If first time I run it (`python app.py`), it works as expected, but the second time I run it, I get the following error:

```python
$ python app.py
Traceback (most recent call last):
  File "app.py", line 21, in <module>
    run(N)
  File "app.py", line 15, in run
    res = fcalc(x)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 172, in _compile_for_args
    return self.compile(sig)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 350, in compile
    flags=flags, locals=self.locals)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 644, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 361, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 370, in compile_bytecode
    return self._compile_bytecode()
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 631, in _compile_bytecode
    return pm.run(self.status)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 251, in run
    raise patched_exception
RuntimeError: Caused By:
Traceback (most recent call last):
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 243, in run
    res = stage()
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 587, in stage_nopython_backend
    return self._backend(lowerfn, objectmode=False)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 540, in _backend
    lowered = lowerfn()
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 527, in backend_nopython_mode
    self.flags)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 786, in native_lowering_stage
    cfunc = targetctx.get_executable(library, fndesc, env)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/targets/cpu.py", line 147, in get_executable
    baseptr = library.get_pointer_to_function(fndesc.llvm_func_name)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/targets/codegen.py", line 377, in get_pointer_to_function
    self._ensure_finalized()
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/targets/codegen.py", line 67, in _ensure_finalized
    self.finalize()
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/targets/codegen.py", line 170, in finalize
    library._get_module_for_linking(), preserve=True)
  File "/Users/userx/anaconda/lib/python2.7/site-packages/numba/targets/codegen.py", line 113, in _get_module_for_linking
    % (self,))
RuntimeError: library unfit for linking: no available functions in <Library 'func' at 0x10b73ef10>

Failed at nopython (nopython mode backend)
library unfit for linking: no available functions in <Library 'func' at 0x10b73ef10>
```

I get this error in the `0.22.1` release as well as the newest conda build from the numba channel (`0.22.1 np110py27_283`). 

The contents of `__pycache__` are:

```bash
$ ls -l __pycache__/
total 24
-rw-r--r--  1 userx  staff  4599 Jan  5 11:59 lib1.func-3.py27.1.nbc
-rw-r--r--  1 userx  staff   398 Jan  5 11:59 lib1.func-3.py27.nbi
```

It's unclear to me why caching isn't working here and whether this is expected or a possible bug. Any assistance would be appreciated.

**Comment by pitrou** [comment]
Indeed, this is a bug. A fixed is now submitted for review.
Note that the cache is really efficient if you cache the outer jitted function. By caching only the inner jitted function, you will not avoid the final LLVM compilation, so the savings will be less great.
