### ISSUE TITLE
Can't call a vectorized function from another nopython function

### ISSUE THREAD

**Issue by dhirschfeld** [numba/numba#1610]
On my system (Win x64, py 3.5.1, np1.10.1) I get an *Untyped global name* error when trying to call a vectorized function from another vectorized function.

Note this only happens when `f2` is a nopython function.
```python
@vectorize([float64(float64, float64, float64)], nopython=True)
def f(a, b, c):
    return (a + b)*c

@vectorize([float64(float64, float64, float64)], nopython=True)
def f2(a, b ,c):
    return 2*f(a, b,  c)
```
```python
Traceback (most recent call last):

  File "<ipython-input-18-d2666db58ae7>", line 5, in <module>
    @vectorize([float64(float64, float64, float64)], nopython=True)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\npyufunc\decorators.py", line 111, in wrap
    vec.add(fty)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 163, in add
    self.nb_func, targetoptions, sig, argtypes, restype)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 89, in _compile_element_wise_function
    cres = nb_func.compile(sig, **targetoptions)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 65, in compile
    flags=flags, locals=locals)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 665, in compile_extra
    return pipeline.compile_extra(func)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 366, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 375, in compile_bytecode
    return self._compile_bytecode()

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 652, in _compile_bytecode
    return pm.run(self.status)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 251, in run
    raise patched_exception

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 243, in run
    res = stage()

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 463, in stage_nopython_frontend
    self.locals)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 779, in type_inference_stage
    infer.build_constraint()

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\typeinfer.py", line 549, in build_constraint
    self.constrain_statement(inst)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\typeinfer.py", line 672, in constrain_statement
    self.typeof_assign(inst)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\typeinfer.py", line 722, in typeof_assign
    self.typeof_global(inst, inst.target, value)

  File "C:\Users\dhirschf\AppData\Roaming\Continuum\Anaconda3\lib\site-packages\numba\typeinfer.py", line 788, in typeof_global
    loc=inst.loc)

TypingError: Untyped global name 'f'
```

**Comment by seibert** [comment]
Note for others: This was discussed on Gitter.  It is a current limitation of the compiler that we should fix.
