### ISSUE TITLE
Tests don't run on Python 3.5 for Windows

### ISSUE THREAD

**Issue by cgohlke** [numba/numba#1628]
Using `numba-0.23.0-cp35-none-win_amd64`, `numba.test()` errors:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "X:\Python35\lib\site-packages\numba\testing.py", line 584, in test
    return run_tests(argv=['<main>'] + list(args), **kwargs).wasSuccessful()
  File "X:\Python35\lib\site-packages\numba\testing.py", line 579, in run_tests
    nomultiproc=nomultiproc)
  File "X:\Python35\lib\site-packages\numba\testing.py", line 145, in __init__
    super(NumbaTestProgram, self).__init__(*args, **kwargs)
  File "X:\Python35\lib\unittest\main.py", line 93, in __init__
    self.parseArgs(argv)
  File "X:\Python35\lib\site-packages\numba\testing.py", line 175, in parseArgs
    super(NumbaTestProgram, self).parseArgs(argv)
  File "X:\Python35\lib\unittest\main.py", line 123, in parseArgs
    self._do_discovery([])
  File "X:\Python35\lib\site-packages\numba\testing.py", line 193, in _do_discovery
    tests = loader.discover(join(topdir, 'numba/tests'), '*.py', topdir)
  File "X:\Python35\lib\site-packages\numba\testing.py", line 95, in discover
    return load_tests(self, [], pattern)
  File "X:\Python35\lib\site-packages\numba\tests\__init__.py", line 25, in load_tests
    suite.addTests(load_testsuite(loader, dirname(__file__)))
  File "X:\Python35\lib\site-packages\numba\testing.py", line 75, in load_testsuite
    suite.addTests(loader.loadTestsFromName(f))
  File "X:\Python35\lib\unittest\loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "X:\Python35\lib\site-packages\numba\tests\test_cffi.py", line 7, in <module>
    from numba.tests.cffi_usecases import *
  File "X:\Python35\lib\site-packages\numba\tests\cffi_usecases.py", line 28, in <module>
    C = ffi.dlopen(None) # loads the entire C namespace
  File "X:\Python35\lib\site-packages\cffi\api.py", line 130, in dlopen
    lib, function_cache = _make_ffi_library(self, name, flags)
  File "X:\Python35\lib\site-packages\cffi\api.py", line 650, in _make_ffi_library
    backendlib = _load_backend_lib(backend, libname, flags)
  File "X:\Python35\lib\site-packages\cffi\api.py", line 638, in _load_backend_lib
    raise OSError("library not found: %r" % (name,))
OSError: library not found: 'c'
```

`ffi.dlopen(None)` and `ctypes.util.find_library('c')` no longer work on Python 3.5 for Windows because of the new UCRT.

**Comment by pitrou** [comment]
Is that a bug in cffi then?

**Comment by seibert** [comment]
This looks more like a shortcut in our unit tests that has become a bug.  We're using the C namespace as a way to find a C function to wrap without having to bring our own in the tests.

**Comment by pitrou** [comment]
Well, `ffi.dlopen(None)` is supposed to be a valid way of querying the C library: see https://cffi.readthedocs.org/en/latest/overview.html#simple-example-abi-level-in-line

**Comment by pitrou** [comment]
Also, our ctypes tests, while similar, don't fail on Windows.

**Comment by seibert** [comment]
Hmm.  Well we could work around the bug on windows if there was a specific library we could load for test purposes.

**Comment by pitrou** [comment]
Or try to see if there's an easy way to fix cffi. They'd probably welcome a patch.

**Comment by seibert** [comment]
Agreed.  We'll need to do both until a new CFFI can be released.

**Comment by cgohlke** [comment]
I guess CFFI won't fix this because of [Python Issue 23606: ctypes.util.find_library("c") no longer makes sense](https://bugs.python.org/issue23606).

**Comment by pitrou** [comment]
Ok, then we'll have to fix our tests.
