### ISSUE TITLE
JIT class: Internal error at resolving type of attribute

### ISSUE THREAD

**Issue by davidbrochart** [numba/numba#1643]
With numba v0.23.0, the following code:

```python
from numba import jitclass, double
import numpy as np

spec = [
        ('a', int),
        ('x', double[:]),
        ]

@jitclass(spec)
class Test:
    def __init__(self, a):
        self.a = a
        self.x = np.empty(self.a, dtype = double)

t = Test(5)
```

gives the following error:

```
numba.errors.TypingError: Failed at nopython (nopython frontend)
Failed at nopython (nopython frontend)
Internal error at resolving type of attribute "a" of "self":
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/home/david/anaconda3/lib/python3.4/site-packages/numba/typeinfer.py", line 111, in propagate
    constraint(typeinfer)
  File "/home/david/anaconda3/lib/python3.4/site-packages/numba/typeinfer.py", line 356, in __call__
    typeinfer.add_type(self.target, attrty)
  File "/home/david/anaconda3/lib/python3.4/site-packages/numba/typeinfer.py", line 572, in add_type
    unified = tv.add_type(tp)
  File "/home/david/anaconda3/lib/python3.4/site-packages/numba/typeinfer.py", line 33, in add_type
    assert isinstance(tp, types.Type), type(tp)
AssertionError: <class 'type'>
--%<-----------------------------------------------------------------
```

**Comment by pitrou** [comment]
That's because you must specify a Numba type (such as `int32`, etc.), not Python `int`.
We should catch those errors early and output a nice error message, though.

**Comment by davidbrochart** [comment]
Thanks.

**Comment by pitrou** [comment]
Reopening to make sure we add type checking in the API.
