### ISSUE TITLE
caching functions taking a JIT class

### ISSUE THREAD

**Issue by chris-b1** [numba/numba#1681]
```python
In [71]: import numba as nb
In [72]: nb.__version__
Out[72]: '0.23.1'

In [73]: @nb.jitclass([
    ...: ('value', nb.float64[:])
    ...: ])
    ...: class Container(object):
    ...:     def __init__(self, value):
    ...:         self.value = value

In [74]: @nb.jit(nopython=True)
    ...: def fun(a, container):
    ...:     return a + container.value[0]

In [75]: c = Container(np.array([1,2.4,3]))

In [77]: fun(1, c)
Out[77]: 2.0

In [78]: @nb.jit(nopython=True, cache=True)
    ...: def fun(a, container):
    ...:     return a + container.value[0]

In [79]: fun(1, c)
---------------------------------------------------------------------------
PicklingError                             Traceback (most recent call last)
<ipython-input-79-53b1add910cd> in <module>()
----> 1 fun(1, c)

C:\Users\Chris\Anaconda\lib\site-packages\numba\dispatcher.pyc in _compile_for_args(self, *args, **kws)
    169         assert not kws
    170         sig = tuple([self.typeof_pyval(a) for a in args])
--> 171         return self.compile(sig)
    172 
    173     def inspect_llvm(self, signature=None):

C:\Users\Chris\Anaconda\lib\site-packages\numba\dispatcher.pyc in compile(self, sig)
    354 
    355             self.add_overload(cres)
--> 356             self._cache.save_overload(sig, cres)
    357             return cres.entry_point
    358 

C:\Users\Chris\Anaconda\lib\site-packages\numba\dispatcher.pyc in save_overload(self, sig, cres)
    664                     break
    665             overloads[key] = data_name
--> 666             self._save_index(overloads)
    667 
    668         self._save_data(data_name, cres)

C:\Users\Chris\Anaconda\lib\site-packages\numba\dispatcher.pyc in _save_index(self, overloads)
    753     def _save_index(self, overloads):
    754         data = self._source_stamp, overloads
--> 755         data = self._dump(data)
    756         with self._open_for_write(self._index_path) as f:
    757             pickle.dump(self._version, f, protocol=-1)

C:\Users\Chris\Anaconda\lib\site-packages\numba\dispatcher.pyc in _dump(self, obj)
    765 
    766     def _dump(self, obj):
--> 767         return pickle.dumps(obj, protocol=-1)

PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed

**Comment by ma-ba** [comment]
Similar issue here (Numba 0.24.0) with
```python
from numba import jitclass, njit, intc

@jitclass([('value', intc)])
class Class:
    def __init__(self):
        self.value = 0 

@njit(cache=True)
def do_nothing(instance):
    return

do_nothing(Class())
```
resulting in the following traceback:
```
Traceback (most recent call last):
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 761, in save_overload
    data_name = overloads[key]
KeyError: ((instance.jitclass.Class#2799db8<value:int32>,), ('x86_64-unknown-linux-gnu', ...))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numba_bug_jitclass_cache.py", line 12, in <module>
    do_nothing(Class())
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 273, in _compile_for_args
    return self.compile(tuple(real_args))
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 460, in compile
    self._cache.save_overload(sig, cres)
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 770, in save_overload
    self._save_index(overloads)
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 859, in _save_index
    data = self._dump(data
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 871, in _dump
    return pickle.dumps(obj, protocol=-1)
_pickle.PicklingError: Can't pickle <class '__main__.Class'>: it's not the same object as __main__.Class
```
or randomly / alternatively the same traceback but while pickling `numba.types.ContructorTemplate`:
```
Traceback (most recent call last):
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 761, in save_overload
    data_name = overloads[key]
KeyError: ((instance.jitclass.Class#2bcb9f8<value:int32>,), ('x86_64-unknown-linux-gnu', ...))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "numba_bug_jitclass_cache.py", line 12, in <module>
    do_nothing(Class())
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 273, in _compile_for_args
    return self.compile(tuple(real_args))
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 460, in compile
    self._cache.save_overload(sig, cres)
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 770, in save_overload
    self._save_index(overloads)
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 859, in _save_index
    data = self._dump(data
  File "lib/python3.4/site-packages/numba/dispatcher.py", line 871, in _dump
    return pickle.dumps(obj, protocol=-1)
_pickle.PicklingError: Can't pickle <class 'numba.types.ConstructorTemplate'>: attribute lookup ConstructorTemplate on numba.types failed
```

**Comment by ma-ba** [comment]
Moreover pickling of `jitclass` instances is not supported, which I guess is currently expected behavior.
```python
from multiprocessing import Pool
from numba import jitclass, njit, intc

@jitclass([('value', intc)])
class Class:
    def __init__(self):
        self.value = 0

@njit
def do_nothing(instance):
    return

with Pool(1) as pool:
    pool.apply(do_nothing, (Class(),))
```
fails with:
```
Traceback (most recent call last):
  File "numba_bug_jitclass_pickle.py", line 14, in <module>
    pool.apply(do_nothing, Class())
  File "lib/python3.4/multiprocessing/pool.py", line 253, in apply
    return self.apply_async(func, args, kwds).get()
  File "lib/python3.4/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "lib/python3.4/multiprocessing/pool.py", line 385, in _handle_tasks
    put(task)
  File "lib/python3.4/multiprocessing/connection.py", line 206, in send
    self._send_bytes(ForkingPickler.dumps(obj))
  File "lib/python3.4/multiprocessing/reduction.py", line 50, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'numba.jitclass.boxing.Class'>: attribute lookup Class on numba.jitclass.boxing failed
```

**Comment by dargen3** [comment]
Hello, 

firstly, thank you for Numba, its great project! :)

secondly i want to ask, whether is there some progress with "TypeError: can't pickle JitClass objects"? I try to use JitClass with multiprocessing.pool. 

Thank you for your reply

**Comment by eric-wieser** [comment]
Note that if this pickling _did_ work, then the cached bytecode would be invalid across interpreter restarts, as it contains a hard-coded memory address of where the object used to live.
