### ISSUE TITLE
 module 'llvmlite.binding' has no attribute 'create_target_library_info'?

### ISSUE THREAD

**Issue by witheri** [numba/numba#1729]
Hi,
I'm getting the error mentioned in the title when I try to 'import numba'. My environment is:
centos6.7, x86_64
python 3.5.1
llvm 3.7.0
llvmlite (master branch)
gcc 4.8.2
numpy-1.10.4

numba-0.23.1

The funny thing is that this function 'create_target_library_info()' is defined in llvmlite's 'cygwin-0.5.1' branch only?!?

I built llvmlite, numpy, and numba using 
python setup.py build && python setup.py install --prefix=$HOME/numba_stuff

callstack:
Type "help", "copyright", "credits" or "license" for more information.
import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/__init__.py", line 7, in <module>
    from . import testing, decorators
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/decorators.py", line 10, in <module>
    from .targets import registry
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/targets/registry.py", line 11, in <module>
    class CPUTarget(TargetDescriptor):
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/targets/registry.py", line 14, in CPUTarget
    target_context = cpu.CPUContext(typing_context)
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/targets/base.py", line 173, in __init__
    self.init()
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/targets/cpu.py", line 43, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/targets/codegen.py", line 397, in __init__
    self._init(self._llvm_module)
  File "/home/cberger/numba_stuff/lib/python3.5/site-packages/numba/targets/codegen.py", line 407, in _init
    tli = ll.create_target_library_info(llvm_module.triple)
AttributeError: module 'llvmlite.binding' has no attribute 'create_target_library_info'

Any ideas?
Christian

**Comment by seibert** [comment]
The current llvmlite master branch is only compatible with the numba master branch.  You can't mix Numba 0.23.1 with llvmlite master.

**Comment by seibert** [comment]
In about a week, we'll be doing both the Numba 0.24 release and the llvmlite 0.9 release.

**Comment by witheri** [comment]
so which llvmlite branch do I have to use?

**Comment by seibert** [comment]
The combinations that work are:

- LLVM 3.6, llvmlite v0.8.0, Numba 0.23.1
- LLVM 3.7, llvmlite master, Numba master

**Comment by witheri** [comment]
Thanks @seibert 
I'll fix my environment and try again
