### ISSUE TITLE
Bug: Definition Order Matters for jitted classes (version 0.7.0)

### ISSUE THREAD

**Issue by jakevdp** [numba/numba#175]
The following code fails to compile:
``` python
from numba import jit, autojit, void

@jit(void())
def my_func():
    f = Foo()

@jit
class Foo(object):
    pass
```
The error goes away if the ``my_func`` definition is moved after the ``Foo`` definition, or if ``@autojit`` is used in place of ``@jit(void())``.

This is the traceback:
```
--------------------- Numba Encountered Errors or Warnings ---------------------

    f = Foo()
--------^
Error 5:8: No global named 'Foo'

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "tmp.py", line 3, in <module>
    @jit(void())
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 263, in _jit_decorator
    nopython=nopython, **kwargs)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 138, in compile_function
    func_env = pipeline.compile2(env, func, restype, argtypes, **kwds)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 478, in compile2
    post_ast = pipeline(func_ast, env)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 528, in __call__
    ast = self.transform(ast, env)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 907, in transform
    ast = stage(ast, env)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 892, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 531, in __call__
    ast = self.transform(ast, env)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 694, in transform
    ast, env, **crnt.kwargs)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 522, in make_specializer
    return cls(env.context, crnt.func, ast, **kws)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 88, in __init__
    self.init_locals()
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 162, in init_locals
    self.resolve_variable_types()
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 355, in resolve_variable_types
    self.analyse_assignments()
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 266, in analyse_assignments
    assmnt = self.handle_NameAssignment(stat.assignment_node)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 214, in handle_NameAssignment
    return self.visit(assignment_node)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 456, in visit
    result = super(TypeInferer, self).visit(node)
  File "/Users/jakevdp/anaconda/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 533, in visit_Assign
    node.value = self.visit(node.value)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 456, in visit
    result = super(TypeInferer, self).visit(node)
  File "/Users/jakevdp/anaconda/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 1263, in visit_Call
    node.func = self.visit(node.func)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 456, in visit
    result = super(TypeInferer, self).visit(node)
  File "/Users/jakevdp/anaconda/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 770, in visit_Name
    variable = self.init_global(node)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 726, in init_global
    value = lookup_global(self.env, global_name, name_node)
  File "/Users/jakevdp/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 51, in lookup_global
    raise error.NumbaError(position_node, "No global named '%s'" % (name,))
numba.error.NumbaError: 5:8: No global named 'Foo'
```

**Comment by pitrou** [comment]
This is outdated, since the jitted class functionality doesn't exist anymore and should be re-done from scratch.
