### ISSUE TITLE
np.timedelta64 not recognized in nopython mode

### ISSUE THREAD

**Issue by dhirschfeld** [numba/numba#1750]
As raised on the [ML](https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/4ajAJaQFJnc) the below code fails:
```python
import numpy as np
from numba import jit, vectorize
from numba.types import NPDatetime

@jit(NPDatetime('D')(NPDatetime('D')), nopython=True)
def add1(date):
    return date + np.timedelta64(1, 'D')
```
```python-traceback
  File "C:/Users/Dave/Code/sandbox/numba_dates.py", line 19, in <module>
    @jit(t_date(t_date), nopython=True)

  File "C:\bin\Anaconda3\lib\site-packages\numba\decorators.py", line 169, in wrapper
    disp.compile(sig)

  File "C:\bin\Anaconda3\lib\site-packages\numba\dispatcher.py", line 458, in compile
    cres = self._compiler.compile(args, return_type)

  File "C:\bin\Anaconda3\lib\site-packages\numba\dispatcher.py", line 79, in compile
    flags=flags, locals=self.locals)

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 687, in compile_extra
    return pipeline.compile_extra(func)

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 375, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 384, in compile_bytecode
    return self._compile_bytecode()

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 668, in _compile_bytecode
    res = pm.run(self.status)

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 246, in run
    stage()

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 472, in stage_nopython_frontend
    self.locals)

  File "C:\bin\Anaconda3\lib\site-packages\numba\compiler.py", line 803, in type_inference_stage
    infer.propagate()

  File "C:\bin\Anaconda3\lib\site-packages\numba\typeinfer.py", line 587, in propagate
    raise errors[0]

  File "C:\bin\Anaconda3\lib\site-packages\numba\typeinfer.py", line 114, in propagate
    constraint(typeinfer)

  File "C:\bin\Anaconda3\lib\site-packages\numba\typeinfer.py", line 375, in __call__
    raise UntypedAttributeError(ty, self.attr, loc=self.inst.loc)

UntypedAttributeError: Unknown attribute "timedelta64" of type Module(<module 'numpy' from 'C:\\bin\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>)
```

**Comment by dhirschfeld** [comment]
However moving the timedelta out of the function body and referencing it as a global does appear to work:
```python
import numpy as np
from numba import jit, vectorize
from numba.types import NPDatetime, NPTimedelta


dt = np.timedelta64(1, 'D')


@jit(NPDatetime('D')(NPDatetime('D')), nopython=True)
def add1(date):
    return add(date, dt)
```

**Comment by seibert** [comment]
Ah I see.  We support most of the dtype objects from NumPy as constructors of scalars with that type, but we missed `timedelta64()` with the character argument.  We support that data type generally in nopython mode, just not this way of constructing it.

@pitrou: Can we fix this easily now, or does this require a fix to the problem of functions whose return type depends on the value of an argument?

**Comment by pitrou** [comment]
> Can we fix this easily now, or does this require a fix to the problem of functions whose return type depends on the value of an argument? 

The latter, unfortunately.

**Comment by polidore** [comment]
this is still an issue. any thoughts or good workarounds?

**Comment by esc** [comment]
@polidore thanks for asking about this, seems like this issue is quite old. I went ahead and tried the example on a recent version of master and got the following error:

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-19-4917a0555771> in <module>
      6 
      7 
----> 8 @jit(NPDatetime('D')(NPDatetime('D')), nopython=True)
      9 def add1(date):
     10     return date + np.timedelta64(1, 'D')

~/git/numba/numba/decorators.py in wrapper(func)
    181             with typeinfer.register_dispatcher(disp):
    182                 for sig in sigs:
--> 183                     disp.compile(sig)
    184                 disp.disable_compile()
    185         return disp

~/git/numba/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/git/numba/numba/dispatcher.py in compile(self, sig)
    656 
    657             self._cache_misses[sig] += 1
--> 658             cres = self._compiler.compile(args, return_type)
    659             self.add_overload(cres)
    660             self._cache.save_overload(sig, cres)

~/git/numba/numba/dispatcher.py in compile(self, args, return_type)
     80                                       args=args, return_type=return_type,
     81                                       flags=flags, locals=self.locals,
---> 82                                       pipeline_class=self.pipeline_class)
     83         # Check typing error if object mode is used
     84         if cres.typing_error is not None and not flags.enable_pyobject:

~/git/numba/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    939     pipeline = pipeline_class(typingctx, targetctx, library,
    940                               args, return_type, flags, locals)
--> 941     return pipeline.compile_extra(func)
    942 
    943 

~/git/numba/numba/compiler.py in compile_extra(self, func)
    370         self.lifted = ()
    371         self.lifted_from = None
--> 372         return self._compile_bytecode()
    373 
    374     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/git/numba/numba/compiler.py in _compile_bytecode(self)
    870         """
    871         assert self.func_ir is None
--> 872         return self._compile_core()
    873 
    874     def _compile_ir(self):

~/git/numba/numba/compiler.py in _compile_core(self)
    857         self.define_pipelines(pm)
    858         pm.finalize()
--> 859         res = pm.run(self.status)
    860         if res is not None:
    861             # Early pipeline completion

~/git/numba/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/git/numba/numba/compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

~/git/numba/numba/compiler.py in run(self, status)
    242                 try:
    243                     event(stage_name)
--> 244                     stage()
    245                 except _EarlyPipelineCompletion as e:
    246                     return e.result

~/git/numba/numba/compiler.py in stage_nopython_frontend(self)
    498                 self.args,
    499                 self.return_type,
--> 500                 self.locals)
    501             self.typemap = typemap
    502             self.return_type = return_type

~/git/numba/numba/compiler.py in type_inference_stage(typingctx, interp, args, return_type, locals)
   1042 
   1043         infer.build_constraint()
-> 1044         infer.propagate()
   1045         typemap, restype, calltypes = infer.unify()
   1046 

~/git/numba/numba/typeinfer.py in propagate(self, raise_errors)
    859         if errors:
    860             if raise_errors:
--> 861                 raise errors[0]
    862             else:
    863                 return errors

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(timedelta64[]) with argument(s) of type(s): (Literal[int](1), Literal[str](D))
 * parameterized
In definition 0:
    TypeError: typer() takes 1 positional argument but 2 were given
    raised from /Users/vhaenel/git/numba/numba/typing/templates.py:263
In definition 1:
    TypeError: typer() takes 1 positional argument but 2 were given
    raised from /Users/vhaenel/git/numba/numba/typing/templates.py:263
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: class(timedelta64[])
[2] During: typing of call at <ipython-input-19-4917a0555771> (10)


File "<ipython-input-19-4917a0555771>", line 10:
def add1(date):
    return date + np.timedelta64(1, 'D')
    ^
```

**Comment by polidore** [comment]
I just made a day and a month timedelta outside numba and multiply it
inside. Not too bad of a workaround.
