### ISSUE TITLE
Compilation can be non-threadsafe

### ISSUE THREAD

**Issue by jcrist** [numba/numba#1791]
I ran into this while using numba with distributed. I tried to get the failures to occur in a local process, but can't seem to reproduce it locally. The failures occur every time in distributed though:

To setup the cluster (bash commands, requires installing distributed beforehand)

```
# In one terminal, startup a scheduler. This will print out an ip, use that below
dscheduler
# Run this in 2 other terminals
dworker --nthreads=4 ip_from_above
```

Failing python example:

``` python
import numba as nb
import numpy as np
from distributed import Executor
from dask import do

# Define a simple function
@nb.njit
def bar(x):
    o = 0
    for i in range(x.shape[0]):
        o += x[i]
    return o

# Build up a graph. This is a simple sum of sums
xs =[do(np.random.normal)(size=10000) for i in range(10)]
out = sum(map(do(bar), xs))

# Local scheduler works fine
out.compute()

# Distributed scheduler has some fun llvm errors
e = Executor(ip_address_of_scheduler)
out.compute(get=e.get)
```

With a dev build, I see some assert failures. These vary considerably, and are all from llvm. Sometimes I'll also see the bottom one from python:

```
Assertion failed: (Idx < NumElements && "Invalid element idx!"), function getElementOffset, file /Volumes/HD2/jenkins/workspace/LLVMDev/label/osxbuild/miniconda/conda-bld/work/llvm-3.6.2.src/include/llvm/IR/DataLayout.h, line 484.
Assertion failed: (i_nocapture < OperandTraits<CallInst>::operands(this) && "getOperand() out of range!"), function getOperand, file /Volumes/HD2/jenkins/workspace/LLVMDev/label/osxbuild/miniconda/conda-bld/work/llvm-3.6.2.src/include/llvm/IR/Instructions.h, line 1534.
Assertion failed: (Worklist.empty() && "Worklist must be empty to add initial group"), function AddInitialGroup, file /Volumes/HD2/jenkins/workspace/LLVMDev/label/osxbuild/miniconda/conda-bld/work/llvm-3.6.2.src/lib/Transforms/InstCombine/InstCombineWorklist.h, line 55.
Assertion failed: (Val && "isa<> used on a null pointer"), function doit, file /Volumes/HD2/jenkins/workspace/LLVMDev/label/osxbuild/miniconda/conda-bld/work/llvm-3.6.2.src/include/llvm/Support/Casting.h, line 95.
python(51456,0x112c01000) malloc: *** error for object 0x1098a5400: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
```

Package versions:

``` python
In [1]: import numba, dask, distributed

In [2]: numba.__version__
Out[2]: '0.24.0'

In [3]: dask.__version__
Out[3]: '0.8.1'

In [4]: distributed.__version__
Out[4]: '1.9.1'
```

**Comment by pitrou** [comment]
I fail running your script. I get the following error in the workers:
```
distributed.core - INFO - Failed to deserialize b'\x80\x04\x95b\x01\x00\x00\x00\x00\x00\x00\x8c\x0fnumba.serialize\x94\x8c\x12_rebuild_reduction\x94\x93\x94(\x8c\x16numba.targets.registry\x94\x8c\rCPUDispatcher\x94\x93\x94(K\x04C\x04\x16\r\r\n\x94C\x9c\xe3\x01\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00C\x00\x00\x00s6\x00\x00\x00d\x01\x00}\x01\x00x)\x00t\x00\x00|\x00\x00j\x01\x00d\x01\x00\x19\x83\x01\x00D]\x14\x00}\x02\x00|\x01\x00|\x00\x00|\x02\x00\x197}\x01\x00q\x1a\x00W|\x01\x00S)\x02N\xe9\x00\x00\x00\x00)\x02\xda\x05range\xda\x05shape)\x03\xda\x01x\xda\x01o\xda\x01i\xa9\x00r\x07\x00\x00\x00\xfa\ndaskbug.py\xda\x03bar\n\x00\x00\x00s\x08\x00\x00\x00\x00\x02\x06\x01\x1a\x01\x12\x01\x94\x87\x94}\x94(\x8c\x05range\x94\x8c\x08builtins\x94\x8c\x05range\x94\x93\x94\x8c\x08__name__\x94\x8c\x08__main__\x94u\x8c\x03bar\x94Nt\x94}\x94}\x94\x8c\x08nopython\x94\x88s\x8c\x06direct\x94\x88]\x94t\x94R\x94.'
Traceback (most recent call last):
  File "/home/antoine/35/lib/python3.5/site-packages/distributed/core.py", line 37, in loads
    return cloudpickle.loads(x)
ImportError: No module named 'numba'
distributed.worker - WARNING - Could not deserialize task
Traceback (most recent call last):
  File "/home/antoine/35/lib/python3.5/site-packages/distributed/worker.py", line 233, in compute
    function = loads(function)
  File "/home/antoine/35/lib/python3.5/site-packages/distributed/core.py", line 37, in loads
    return cloudpickle.loads(x)
ImportError: No module named 'numba'
```


```
>>> dask.__version__
'0.8.1'
>>> distributed.__version__
'1.9.1'
```

**Comment by pitrou** [comment]
Removed the previous message. I had to set `PYTHONPATH` to the Numba path.

**Comment by pitrou** [comment]
Ok, so this seems to be another instance of the multi-threading fragility issue that @sklam has been investigating. See PR #1752.

**Comment by seibert** [comment]
Closing, now that those PRs have been merged.
