### ISSUE TITLE
Compiler error when wrapping a scipy function

### ISSUE THREAD

**Issue by alxempirical** [numba/numba#1811]
The following code gives a compiler error, and I'm struggling to understand why:

```python
from numba import jit, float64
from scipy.special import gammaln

@jit(float64(float64))
def _gammaln(x):
    return gammaln(x)

@jit(float64(), nopython=True)
def failure():
    return _gammaln(1)
```

The error message is below.  I know that the `_gammaln(1)` call is triggering the error, because it doesn't happen if I replace that with `1`.  The `nopython=True` also contributes.  The `numba` version is 0.24.0.

```bash

bash-3.2$ PYTHONPATH=.. MPLBACKEND=agg python failure.py
Traceback (most recent call last):
  File "failure.py", line 8, in <module>
    @jit(float64(), nopython=True)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 169, in wrapper
    disp.compile(sig)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 458, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 79, in compile
    flags=flags, locals=self.locals)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 687, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 375, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 384, in compile_bytecode
    return self._compile_bytecode()
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 668, in _compile_bytecode
    res = pm.run(self.status)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
numba.errors.TypingError: Caused By:
Traceback (most recent call last):
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 472, in stage_nopython_frontend
    self.locals)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 803, in type_inference_stage
    infer.propagate()
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 587, in propagate
    raise errors[0]
TypingError: Internal error at <numba.typeinfer.CallConstraint object at 0x107e51150>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 114, in propagate
    constraint(typeinfer)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 305, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 332, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typing/context.py", line 126, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/types.py", line 451, in get_call_type
    sig = template(context).apply(args, kws)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typing/templates.py", line 280, in apply
    assert cases
AssertionError
--%<-----------------------------------------------------------------

File "failure.py", line 10

Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x107e51150>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 114, in propagate
    constraint(typeinfer)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 305, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 332, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typing/context.py", line 126, in resolve_function_type
    return func.get_call_type(self, args, kws)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/types.py", line 451, in get_call_type
    sig = template(context).apply(args, kws)
  File "/Users/alx/anaconda/lib/python2.7/site-packages/numba/typing/templates.py", line 280, in apply
    assert cases
AssertionError
--%<-----------------------------------------------------------------
```

**Comment by pitrou** [comment]
See answer on the mailing-list :-)
