### ISSUE TITLE
jitclass: setattr and self.__setattr__ not 

### ISSUE THREAD

**Issue by ml31415** [numba/numba#1818]
I want to initialize a jitted class with quite a list of arrays as attributes, which all need to get initialized. This means, defining the spec and initializing the attributes is highly repetitive code. Unfortunately, the logical solution, to define the list of required attributes once, and then derive as well the spec as the initialization code from it, fails. The problem is, that I can set attributes neither with `setattr` nor `self.__setattr__`, only with direct `self.asdf =` syntax. As the logic to set some attribute is obviously already implemented, it would be great if all ways of setting an attribute would actually work. 

For reference, this is the usecase I tried to get working:

```python
def get_col_type(col, for_spec=False):
    typename = defaults.get(col, 'int64') # Arbitrary generic logic
    if for_spec:
        if typename == 'bool':
            typename += '_'
        return getattr(nb, typename)[:]
    return typename

event_buffer_fields = ('maxlen', 'len', 'id') # ... lengthy list
event_buffer_spec = OrderedDict((col, get_col_type(col, for_spec=True)) for col in event_buffer_fields)
_event_buffer_dtypes = dict((col, get_col_type(col, for_spec=False)) for col in event_buffer_fields)
event_buffer_dtypes = namedtuple('event_buffer_dtypes', event_buffer_fields)(**_event_buffer_dtypes)

@nb.jitclass(event_buffer_spec)
class JEventBuffer(object):
    def __init__(self, N):
        for attr in event_buffer_fields[2:]:
            setattr(self, attr, np.zeros(N, dtype=event_buffer_dtypes[attr]))
```
This are the errors I'm getting for the both unsuccessful attempts:

```
Failed at nopython (nopython frontend)
Untyped global name 'setattr'
File "<ipython-input-2-be43349577fb>", line 39
```
```
Failed at nopython (nopython frontend)
Unknown attribute "__setattr__" of type instance.jitclass.JEventStratData#3d7a040<maxlen:int64,len:int64,id:array(int64, 1d, A),...>
File "<ipython-input-25-fb3f90759197>", line 7
```

**Comment by esc** [comment]
I just revisited this issue and it appears to be working:

```
from numba import int32
from numba.experimental import jitclass

spec = [
    ('value', int32)
]


@jitclass(spec)
class SimpleBag(object):
    def __init__(self, value):
        self.value = value


mybag = SimpleBag(21)
print(getattr(mybag, 'value'))
setattr(mybag, 'value', 19)
print(getattr(mybag, 'value'))
```

prints:

```
21
19
````

@ml31415 will this suffice for your usecase too?

**Comment by ml31415** [comment]
I should have simplified my usecase earlier, sorry for that code mess above:

```
from numba import int32
from numba import jitclass

spec = [('v1', int32), ('v2', int32)]

@jitclass(spec)
class SimpleBag(object):
    def __init__(self, value):
        for attr_type in spec:
            setattr(self, attr_type[0], value)

mybag = SimpleBag(21)
print(mybag.v1, mybag.v2)
```

At least with the not really brand new version I'm on right now, this still throws an error.
```

Traceback (most recent call last):
  File "numbatest.py", line 12, in <module>
    mybag = SimpleBag(21)
  File "/usr/local/lib/python2.7/dist-packages/numba/jitclass/base.py", line 126, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/usr/local/lib/python2.7/dist-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "<string>", line 2, in reraise
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'setattr': cannot determine Numba type of <type 'builtin_function_or_method'>

File "numbatest.py", line 10:
    def __init__(self, value):
        <source elided>
        for attr_type in spec:
            setattr(self, attr_type[0], value)
            ^

[1] During: resolving callee type: jitclass.SimpleBag#7f2d6ed2ba50<v1:int32,v2:int32>
[2] During: typing of call at <string> (3)

[3] During: resolving callee type: jitclass.SimpleBag#7f2d6ed2ba50<v1:int32,v2:int32>
[4] During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

```

**Comment by esc** [comment]
@ml31415 I see, so you are trying to use ` setattr` and `getattr` from compiled code.

**Comment by ml31415** [comment]
Shall we change the name of the issue? I guess it would still be a valid improvement, even if it's a couple of years old already.

**Comment by esc** [comment]
@ml31415 I think so, I think this should stay open as a feature request. Perhaps for the time being, you could use `setattr` and `getattr` from Python?

**Comment by esc** [comment]
I updated the issue, please feel free to adapt or change the wording if the  title can be improved upon.
