### ISSUE TITLE
dtype for array construction can not be passed as string in nopython context

### ISSUE THREAD

**Issue by ml31415** [numba/numba#1819]
``` python
from numpy import zeros
from numba import njit
@njit
def test():
    return zeros(10, dtype='int32')
test()
```

Fails with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 249, in run
    stage()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 475, in stage_nopython_frontend
    self.locals)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 799, in type_inference_stage
    infer.propagate()
  File "/usr/local/lib/python2.7/dist-packages/numba/typeinfer.py", line 613, in propagate
    raise errors[0]
TypingError: Invalid usage of Function(<built-in function zeros>) with parameters (int64, str)
 * parameterized
File "<ipython-input-1-5e362d305d47>", line 5

Failed at nopython (nopython frontend)
Invalid usage of Function(<built-in function zeros>) with parameters (int64, str)
 * parameterized
File "<ipython-input-1-5e362d305d47>", line 5
```

As I'm trying to pass the dtype around as a variable, unfortunately I can't just use the appropriate numpy dtype, as again, it can't be used in nopython context. ( usecase, see https://github.com/numba/numba/issues/1818 )

**Comment by arita37** [comment]
Same issue, here

**Comment by ml31415** [comment]
As this works nowadays, I'd be fine with closing the issue, even if the original still doesn't work.

```python
from numpy import zeros
from numba import njit
@njit
def test():
    return zeros(10, dtype=np.int32)
test()
```

**Comment by arita37** [comment]
Hello,

What is @njit  ?

Thanks

**Comment by MatthieuDartiailh** [comment]
njit is equivalent to jit(nopython=True)

**Comment by seibert** [comment]
Closing as #2201 is now tracking the dtype as string issue.
