### ISSUE TITLE
Feedback on np.nditer

### ISSUE THREAD

**Issue by shoyer** [numba/numba#1825]
xref https://github.com/numba/numba/pull/1787

First of all -- it's awesome to see nditer supported in Numba! I am very pleased to see this development.

Two usability issues that tripped me up:
- numba apparently needs a tuple of arrays for the argument to `nditer`. If you supply a list of arrays instead, you get an unhelpful `TypingError` when you attempt to run the function. Unfortunately, [all the docstring examples](http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.nditer.html) for nditer use lists of ararys.
- You can't use scalar arrays to index arrays, but have to unpack them into scalars by using `.item()` first. Otherwise, you get `TypeError: unsupported array index type array(int64, 0d, C) in [array(int64, 0d, C)]`. My code would look a little nicer if I didn't need to insert calls to `.item()`.

**Comment by pitrou** [comment]
I'm not sure I understand the second issue. Can you post an example?

**Comment by seibert** [comment]
```python
import numpy as np
from numba import jit

@jit(nopython=True)
def idx(a, i):
    return a[i]

idx(np.arange(10), np.array(0))
```
gives this output:
```
Traceback (most recent call last):
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 114, in propagate
    constraint(typeinfer)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 384, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 344, in resolve
    sig = context.resolve_function_type(fnty, pos_args, kw_args)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typing/context.py", line 112, in resolve_function_type
    res = defn.apply(args, kws)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typing/templates.py", line 185, in apply
    sig = generic(args, kws)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typing/arraydecl.py", line 159, in generic
    out = get_array_index_type(ary, idx)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typing/arraydecl.py", line 63, in get_array_index_type
    % (ty, idx))
TypeError: unsupported array index type array(int64, 0d, C) in [array(int64, 0d, C)]
```

**Comment by seibert** [comment]
Basically, NumPy lets you index with a zero-dimensional array, but Numba does not.

**Comment by pitrou** [comment]
Ah... Why would you do that, though? Just pass an empty tuple: `a[()]`, it's much cheaper.

**Comment by seibert** [comment]
A zero-dimensional array is not the same as an empty array:
```python
In [11]: np.arange(10)[np.array(0)]
Out[11]: 0

In [12]: np.arange(10)[np.array(1)]
Out[12]: 1
```
I assume the issue is because nditer can return zero-dim arrays sometimes, right?

**Comment by pitrou** [comment]
nditer() always returns zero-dim arrays, which is why using `a[()]` should be fine if one doesn't want to call `a.item()`.

**Comment by seibert** [comment]
(Ah, misunderstood your `a[()]` example.) It would be even shorter if you could use `a` directly as an index though, and this is consistent with what NumPy allows.

**Comment by pitrou** [comment]
Use `a` as an index? How so?

**Comment by pitrou** [comment]
Ok, Stan explained me what you might have meant, @shoyer .

**Comment by shoyer** [comment]
Yes, @seibert identified the issue exactly.

For example, I might want to write an N-dimensional version of `np.bincount` with Numba:
```@jit(nopython=True)
def bincount(x):
    out = np.zeros(np.max(x) + 1, np.int64)
    for i in np.nditer((x,)):
        out[i] += 1
    return out
```

**Comment by pitrou** [comment]
As for the first point:

> numba apparently needs a tuple of arrays for the argument to nditer. If you supply a list of arrays instead, you get an unhelpful TypingError when you attempt to run the function.

Numba doesn't support lists of arrays at all, right now. But that would also be less efficient, since a list is a heap-allocated resizable collection, while a tuple is an immutable stack-allocated structure.
(besides, even if supporting lists of arrays, Numba would only support _homogenous_ lists of arrays, which would limit their usefulness with `nditer()`)

**Comment by shoyer** [comment]
@pitrou I agree, but in pure Python the efficiency generally doesn't make a difference. I suspect it's used with the nditer docstring examples just because it looks a little cleaner. If possible, a more specific error message would be helpful here, just because it's likely to be something users immediately encounter when trying this out.

**Comment by seibert** [comment]
Solving the list of arrays issue is something we have to tackle from a usability perspective in Numba.

**Comment by pitrou** [comment]
Agreed, but in this case the lack of heterogenous lists would not make things significantly better. That said, I'm sure we can approve the error message :-)

**Comment by pitrou** [comment]
I've submitted #1827 for the 0d indexing issue.
