### ISSUE TITLE
Failure in CUDA tests

### ISSUE THREAD

**Issue by pitrou** [numba/numba#1858]
I get the following failure deterministically when running `./runtests.py -vf numba.cuda.tests` (although the exact integer value varies from run to run):
```
======================================================================
ERROR: test_cuda_driver_occupancy (numba.cuda.tests.cudadrv.test_cuda_driver.TestCudaDriver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antoine/numba/numba/cuda/tests/cudadrv/test_cuda_driver.py", line 117, in test_cuda_driver_occupancy
    module = self.context.create_module_ptx(self.ptx)
  File "/home/antoine/numba/numba/cuda/cudadrv/driver.py", line 646, in create_module_ptx
    return self.create_module_image(image)
  File "/home/antoine/numba/numba/cuda/cudadrv/driver.py", line 649, in create_module_image
    self.trashing.service()
  File "/home/antoine/numba/numba/servicelib/service.py", line 30, in service
    next(self._task)
  File "/home/antoine/numba/numba/cuda/cudadrv/driver.py", line 321, in process
    cb()
  File "/home/antoine/numba/numba/cuda/cudadrv/driver.py", line 779, in cleanup
    del modules[handle.value]
KeyError: 47652304
```

**Comment by pitrou** [comment]
According to `git bisect`, this was introduced in 0d67b645aadc667e26d3243d2e48779f8394524f.
