### ISSUE TITLE
Enums not interchangeable with namedtuples

### ISSUE THREAD

**Issue by ml31415** [numba/numba#1903]
Consider this code: 

```python
from collections import namedtuple
from enum import IntEnum
import numba as nb

en = enum.IntEnum('en', 'a b c d')
nt_type = namedtuple('ntt', 'a b c d')
nt = nt_type(1, 2, 3, 4)

@nb.njit
def cmp(x, y):
    return x.a == y.a

assert cmp(nt, nt)
assert cmp(en, en)
assert cmp(nt, en)
```
It works well with namedtuples, but rejects the enums as being python objects:
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 249, in run
    stage()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 468, in stage_nopython_frontend
    legalize_given_types(self.args, self.return_type)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 719, in legalize_given_types
    "mode" % (i, a))
TypeError: Arg 0 of pyobject is not legal in nopython mode

Failed at nopython (nopython frontend)
Arg 0 of pyobject is not legal in nopython mode
```
I'm not familiar with the details, but as I had planned to replace my tuple fiddlings with proper enums, this stops me from replacing them.

**Comment by sklam** [comment]
The current enum implementation does not support passing the enum type as argument.  A workaround is to refer to the enum as a global:

```python

@nb.njit
def cmp(x):
    return x.a == en.a
```

**Comment by ml31415** [comment]
This fails for me as well unfortunately and gives the same error as above. Though, passing them around as variables just like the namedtuples would really be nice.

**Comment by sklam** [comment]
The error is suggesting the `en` is not defined.

Can you try with:

```python
from collections import namedtuple
from enum import IntEnum
import numba as nb

en = IntEnum('en', 'a b c d')
nt_type = namedtuple('nt_type', 'a b c d')
nt = nt_type(1, 2, 3, 4)

@nb.njit
def cmp(x):
    return x.a == en.a

print(cmp(nt))
```

It works on master.

**Comment by ml31415** [comment]
Ok, master also for me also works. 0.25.0 crashed with the `TypingError` as written above. So about passing it as an argument, don't you think it would also be a useful feature?

**Comment by sklam** [comment]
>  So about passing it as an argument, don't you think it would also be a useful feature?

Yes, it is a useful feature and it is something that is not trivial due to limitation in current typesystem design.  This is a problem of passing type as argument.
