### ISSUE TITLE
jitclass decorator fails when encountering annotations (numba 0.25)

### ISSUE THREAD

**Issue by alexpyattaev** [numba/numba#1911]
When using jitclass decorator, if ANY of the methods in the class have annotations, the compilation fails. 
This is the code sample sufficient to trigger the error:
```
spec={
'obj':int32,
}

@jitclass(spec)
class TTT(object):
    def __init__(self, obj:int):
        self.obj = obj

    def add(self, v:int):
        return self.obj + v
```
This is the traceback:
```
python3.4 test.py 
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    class TTT(object):
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/decorators.py", line 27, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/base.py", line 170, in register_class_type
    __doc__=docstring))
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/base.py", line 70, in __new__
    outcls._set_init()
  File "/usr/lib64/python3.4/site-packages/numba/jitclass/base.py", line 76, in _set_init
    argspec = inspect.getargspec(init)
  File "/usr/lib64/python3.4/inspect.py", line 936, in getargspec
    raise ValueError("Function has keyword-only arguments or annotations"
ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them
```
This is not really a major issue, but I am certain it is easy to fix. 
Thank you!

**Comment by alexpyattaev** [comment]
Wow! So quick! Thank you very much for fixing this! 
The next-most-important-thing would probably be support of inheritance for jitclasses, at least some features. It is nice to use jitclasses to store parameters for jitted functions in one place, but duplicating specs every time is rather annoying.
