### ISSUE TITLE
Example 1.7.3 in Numba docs doesn't work with Numba 0.26.0 on Mac OS X

### ISSUE THREAD

**Issue by talumbau** [numba/numba#1923]
This code:

```
from numba import cfunc, types, carray

c_sig = types.void(types.CPointer(types.double),
                   types.CPointer(types.double),
                   types.intc, types.intc)

@cfunc(c_sig)
def my_callback(in_, out, m, n):
    in_array = carray(in_, (m, n))
    out_array = carray(out, (m, n))
    for i in range(m):
        for j in range(n):
            out_array[i, j] = 2 * in_array[i, j]
```

in file, foo.py, and then executing `python foo.py` results in an error (output below).

Conda info:

```
Current conda install:

             platform : osx-64
        conda version : 4.0.7
  conda-build version : 1.20.3
       python version : 3.5.1.final.0
```

Numba and llvmlite versions:

```
numba                     0.26.0              np111py35_0
llvmlite                  0.11.0                   py35_0
```

Error message:
```
Traceback (most recent call last):
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 196, in lower_block
    self.lower_inst(inst)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 238, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 380, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 622, in lower_expr
    res = self.lower_call(resty, expr)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 588, in lower_call
    res = impl(self.builder, argvals)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/targets/base.py", line 1105, in __call__
    return self._imp(self._context, builder, self._sig, args)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/targets/arrayobj.py", line 3226, in np_cfarray
    off = builder.mul(off, s)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/llvmlite/ir/builder.py", line 24, in wrapped
    % (lhs.type, rhs.type))
ValueError: Operands must be the same type, got (i64, i32)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "ftest.py", line 7, in <module>
    @cfunc(c_sig)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/decorators.py", line 225, in wrapper
    res.compile()
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/ccallback.py", line 65, in compile
    cres = self._compile_uncached()
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/ccallback.py", line 78, in _compile_uncached
    cres = self._compiler.compile(sig.args, sig.return_type)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/dispatcher.py", line 76, in compile
    flags=flags, locals=self.locals)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 696, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 369, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 378, in compile_bytecode
    return self._compile_bytecode()
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 662, in _compile_bytecode
    res = pm.run(self.status)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 257, in run
    raise patched_exception
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 249, in run
    stage()
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 607, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 562, in _backend
    lowered = lowerfn()
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 549, in backend_nopython_mode
    self.flags)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/compiler.py", line 824, in native_lowering_stage
    lower.lower()
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 123, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 158, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 183, in lower_function_body
    self.lower_block(block)
  File "/Users/talumbau/miniconda3/envs/webdemo/lib/python3.5/site-packages/numba/lowering.py", line 201, in lower_block
    raise LoweringError(msg, inst.loc)
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
Internal error:
ValueError: Operands must be the same type, got (i64, i32)
```

**Comment by talumbau** [comment]
also broken on Linux64 with this Python:

```
ubuntu@ip-172-31-60-154:~$ python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
and these packages:

```
llvmlite                  0.11.0                   py35_0
mkl                       11.3.3                        0
numba                     0.26.0              np111py35_0
numpy                     1.11.0                   py35_1
```

**Comment by seibert** [comment]
@pitrou: Can you take a look at this tomorrow?  We want to figure this out ASAP.  Thanks!

**Comment by pitrou** [comment]
This is a bug indeed. I've submitted a PR for it.
