### ISSUE TITLE
CUDA_ERROR_NO_BINARY_FOR_GPU

### ISSUE THREAD

**Issue by CJ-Wright** [numba/numba#1940]
Hi all,
I got the following error when trying to run some code in ipython.
Has anyone seen this kind of thing before?
Thank you very much!

```python
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/mnt/work-data/other_src/mc/envs/master_dev2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/mnt/work-data/other_src/mc/envs/master_dev2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/mnt/work-data/dev/pyIID/pyiid/experiments/elasticscatter/gpu_wrappers/gpu_wrap.py", line 51, in subs_fq
    fq += atomic_fq(q, scatter_array, qbin, k_cov, k_per_thread)
  File "/mnt/work-data/dev/pyIID/pyiid/experiments/elasticscatter/atomics/gpu_atomics.py", line 115, in atomic_fq
    from pyiid.experiments.elasticscatter.kernels.gpu_flat import \
  File "/mnt/work-data/dev/pyIID/pyiid/experiments/elasticscatter/kernels/gpu_flat.py", line 11, in <module>
    @cuda.jit(argtypes=[f4[:, :], f4[:, :], i4])
  File "/mnt/work-data/other_src/mc/envs/master_dev2/lib/python2.7/site-packages/numba/cuda/decorators.py", line 92, in kernel_jit
    kernel.bind()
  File "/mnt/work-data/other_src/mc/envs/master_dev2/lib/python2.7/site-packages/numba/cuda/compiler.py", line 503, in bind
    self._func.get()
  File "/mnt/work-data/other_src/mc/envs/master_dev2/lib/python2.7/site-packages/numba/cuda/compiler.py", line 388, in get
    linker.add_ptx(ptx)
  File "/mnt/work-data/other_src/mc/envs/master_dev2/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 1236, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
LinkerError: [209] Call to cuLinkAddData results in CUDA_ERROR_NO_BINARY_FOR_GPU
ptxas application ptx input, line 9; fatal   : Unsupported .version 4.3; current version is '4.2'
```

**Comment by CJ-Wright** [comment]
For reference, my [conda env](https://gist.github.com/CJ-Wright/1dbcc54420165a1f6f1ab5470d4baf4c)

**Comment by seibert** [comment]
This looks like the cudatoolkit package is too new for the CUDA driver.  You can either update the CUDA drivers in your OS or downgrade to cudatoolkit 7.0:
```
conda install cudatoolkit=7.0
```

**Comment by CJ-Wright** [comment]
Ah, thank you very much!
