### ISSUE TITLE
JIT compiler fails on code containing non-latin1 characters

### ISSUE THREAD

**Issue by texnokrates** [numba/numba#2003]
JIT compiler fails on any function containing any non-latin1 characters.

Versions:
Python 3.4
numba 0.26.0
llvmlite 0.12.0

I am not totally sure whether this isn't more of a llvmlite issue.

A minimal example:
```
from numba import jit

@jit
def fun():
    č = 1
    return č

fun()
```
which yields
```
Traceback (most recent call last):
  File "numbafail.py", line 8, in <module>
    fun()
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/dispatcher.py", line 277, in _compile_for_args
    return self.compile(tuple(real_args))
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/dispatcher.py", line 495, in compile
    cres = self._compiler.compile(args, return_type)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/dispatcher.py", line 76, in compile
    flags=flags, locals=self.locals)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 696, in compile_extra
    return pipeline.compile_extra(func)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 369, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 378, in compile_bytecode
    return self._compile_bytecode()
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 662, in _compile_bytecode
    res = pm.run(self.status)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 257, in run
    raise patched_exception
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 249, in run
    stage()
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 585, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 562, in _backend
    lowered = lowerfn()
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 536, in backend_object_mode
    self.flags)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/compiler.py", line 848, in py_lowering_stage
    lower.lower()
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/lowering.py", line 142, in lower
    self.library.add_ir_module(self.module)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/numba/targets/codegen.py", line 146, in add_ir_module
    ll_module = ll.parse_assembly(str(ir_module))
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/llvmlite/binding/module.py", line 16, in parse_assembly
    llvmir = _encode_string(llvmir)
  File "/u/46/necadam1/unix/.local/lib/python3.4/site-packages/llvmlite/binding/common.py", line 17, in _encode_string
    encoded = s.encode('latin1')
```

**Comment by seibert** [comment]
At its core, this is an LLVM issue that we might be able to hide.  The current LLVM IR only supports ASCII identifiers:

http://llvm.org/docs/LangRef.html#identifiers

In order to handle Python unicode identifiers in llvmlite, we would need to come up with an identifier encoding to map them to ASCII during code generation.

**Comment by texnokrates** [comment]
I see, but then I still don't understand why everything seems to work if I use characters from the upper half of latin1 (i.e. stil non-ASCII) instead.
Anyway, would there be anything wrong about implementing some arbitrary meaningful mapping from unicode to ASCII strings in llvmlite/llvmlite/binding/common.py? Or am I missing something?

**Comment by pitrou** [comment]
Quoting from the LLVM docs:

> Identifiers that require other characters in their names can be surrounded with quotes. Special characters may be escaped using "\xx" where xx is the ASCII code for the character in hexadecimal. In this way, any character can be used in a name value, even quotes themselves.

The problem is they don't say what a "character" is. ASCII? Latin-1? Unicode? Who knows. They probably treat IR as a stream of bytes, following the broken C model of "text" strings.

Still, Numba could probably escape any non-ASCII characters in user identifiers, since they are not meant to be visible from the outside (except perhaps for `@cfunc`).
