### ISSUE TITLE
finalize is None at _exitfunc

### ISSUE THREAD

**Issue by horta** [numba/numba#2026]
```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/conda/lib/python2.7/site-packages/numba/utils.py", line 629, in _exitfunc
    finalize._shutdown = True
AttributeError: 'NoneType' object has no attribute '_shutdown'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/conda/lib/python2.7/site-packages/llvmlite/binding/common.py", line 30, in _at_shutdown
    _shutting_down[0] = True
TypeError: 'NoneType' object does not support item assignment
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/opt/conda/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/opt/conda/lib/python2.7/site-packages/llvmlite/binding/common.py", line 30, in _at_shutdown
    _shutting_down[0] = True
TypeError: 'NoneType' object does not support item assignment
```

```
# python -c "import numba; print(numba.__version__)"
0.27.0+0.g6ca78ce.dirty
```

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
