### ISSUE TITLE
Windows: `PermissionError` using `@njit(cache=True)` with multiprocessing

### ISSUE THREAD

**Issue by ma-ba** [numba/numba#2028]
Writing cache for compiled functions from multiple processes may clash and thus raises `PermissionError` under Windows operation systems. See:
```python
from multiprocessing import Pool
from numba import njit

@njit(cache=True)
def callee(i):
    return i

def caller(i):
    return callee(i)

def main():
    p = 2
    with Pool(p) as pool:
        sum(pool.imap(caller, range(p)))

if __name__ == "__main__":
    main()
```
```
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Miniconda3\envs\numba\lib\site-packages\numba\caching.py", line 373, in save_overload
    data_name = overloads[key]
KeyError: ((int64,), ('x86_64-pc-windows-msvc', 'amdfam10', '-adx,-aes,-avx,-avx2,-avx512bw,-avx512cd,-avx512dq,-avx512er,-avx512f,-avx512pf,-avx512vl,-bmi,-bmi2,+cmov,+cx16,-f16c,-fma,-fma4,-fsgsbase,-hle,+lzcnt,+mmx,-movbe,-pclmul,+popcnt,+prfchw,-rdrnd,-rdseed,-rtm,-sha,+sse,+sse2,+sse3,-sse4.1,-sse4.2,+sse4a,-ssse3,-tbm,-xop'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Miniconda3\envs\numba\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\numba\njit_cache_multiprocessing.py", line 10, in caller
    return callee(i)
  File "C:\Miniconda3\envs\numba\lib\site-packages\numba\dispatcher.py", line 281, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Miniconda3\envs\numba\lib\site-packages\numba\dispatcher.py", line 529, in compile
    self._cache.save_overload(sig, cres)
  File "C:\Miniconda3\envs\numba\lib\site-packages\numba\caching.py", line 382, in save_overload
    self._save_index(overloads)
  File "C:\Miniconda3\envs\numba\lib\site-packages\numba\caching.py", line 477, in _save_index
    f.write(data)
  File "C:\Miniconda3\envs\numba\lib\contextlib.py", line 66, in __exit__
    next(self.gen)
  File "C:\Miniconda3\envs\numba\lib\site-packages\numba\caching.py", line 428, in _open_for_write
    utils.file_replace(tmpname, filepath)
PermissionError: [WinError 5] Zugriff verweigert: 'C:\\numba\\__pycache__\\__mp_main__.callee-5.py34.nbi.tmp.2332' -> 'C:\\numba\\__pycache__\\__mp_main__.callee-5.py34.nbi'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "njit_cache_multiprocessing.py", line 18, in <module>
    main()
  File "njit_cache_multiprocessing.py", line 15, in main
    sum(pool.imap(caller, range(p)))
  File "C:\Miniconda3\envs\numba\lib\multiprocessing\pool.py", line 698, in next
    raise value
PermissionError: [WinError None] Zugriff verweigert: 'C:\\numba\\__pycache__\\__mp_main__.callee-5.py34.nbi.tmp.2332' -> 'C:\\numba\\__pycache__\\__mp_main__.callee-5.py34.nbi'
```

**Comment by pitrou** [comment]
Thanks for the report! I can reproduce indeed.
