### ISSUE TITLE
CUDA Custom dtypes issue

### ISSUE THREAD

**Issue by ghost** [numba/numba#2074]
This is in response to the update to 0.28.1. I can pass in dtypes like cl_array.vec.uchar4 with no problem but as soon as I try to change any values within the array I am met with this error. I can post the code in as well if needed. I thought it might be a type error because if I do something like this "d_out[0][0] = 0" I get the LoweringError: Cannot cast int64 to Record error. I tried this "d_out[i][0] = np.uint8(0)" as well but I get this at the end instead Cannot resolve setitem: Record.

numba.errors.LoweringError: Caused By:
Traceback (most recent call last):
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 249, in run
    stage()
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 617, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 572, in _backend
    lowered = lowerfn()
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 559, in backend_nopython_mode
    self.flags)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/compiler.py", line 845, in native_lowering_stage
    lower.lower()
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 125, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 160, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 185, in lower_function_body
    self.lower_block(block)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 200, in lower_block
    self.lower_inst(inst)
  File "/home/uchytilc/anaconda2/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/errors.py", line 249, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/errors.py", line 243, in new_error_context
    yield
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 200, in lower_block
    self.lower_inst(inst)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 292, in lower_inst
    return self.lower_setitem(inst.target, inst.index, inst.value, signature)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/lowering.py", line 360, in lower_setitem
    return impl(self.builder, (target, index, value))
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/targets/base.py", line 959, in **call**
    return self._imp(self._context, builder, self._sig, args)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/targets/arrayobj.py", line 481, in setitem_array
    val = context.cast(builder, val, valty, aryty.dtype)
  File "/home/uchytilc/anaconda2/lib/python2.7/site-packages/numba/targets/base.py", line 627, in cast
    "Cannot cast %s to %s: %s" % (fromty, toty, val))
LoweringError: Cannot cast int64 to Record([(('x', 's0'), '|u1'), (('y', 's1'), '|u1'), (('z', 's2'), '|u1'), (('w', 's3'), '|u1')]): %".261" = load i64, i64\* %"$const106.1"
File "dist.py", line 34
[1] During: lowering "d_out[i] = $const106.1" at dist.py (34)

Failed at nopython (nopython mode backend)
Cannot cast int64 to Record([(('x', 's0'), '|u1'), (('y', 's1'), '|u1'), (('z', 's2'), '|u1'), (('w', 's3'), '|u1')]): %".261" = load i64, i64\* %"$const106.1"
File "dist.py", line 34
[1] During: lowering "d_out[i] = $const106.1" at dist.py (34)

**Comment by Lomelgande** [comment]
Here is some test code that shows the issue.

import numpy as np
import math
from numba import jit, cuda
import pyopencl as cl
import pyopencl.array as cl_array

W = 500
H = 500
TX = 32
TY = 32

@cuda.jit(device = True)
def clip(n):
	if n > 255:
		n = 255
	elif n < 0:
		n = 0
	return n

@cuda.jit()#"(uint8[::1], int32, int32, float32[::1])"
def distanceKernel(d_out, w, h, pos):
	c = cuda.blockIdx.x*cuda.blockDim.x + cuda.threadIdx.y
	r = cuda.blockIdx.y*cuda.blockDim.y + cuda.threadIdx.y
	i = (r*w + c)

	if c >= w or r >= h:
		return

	# d = math.sqrt((c - pos[0]) * (c - pos[0]) + (r - pos[1]) * (r - pos[1]))

	# intensity = clip(255 - d)

	d_out[i][0] = np.uint8(0) #intensity
	d_out[i][1] = 0           #intensity
	d_out[i][2] = 0
	d_out[i][3] = 255

def main():
	pos = np.zeros([2], dtype = cl_array.vec.int2)#'float32')
	blockSize = (TX, TY)
	bx = (W + TX - 1)/TX
	by = (W + TY - 1)/TY
	gridSize = (bx, by)

	out = np.zeros([W*H], dtype = cl_array.vec.uchar4)
	d_out = cuda.to_device(out)

	distanceKernel[blockSize, gridSize](d_out, W, H, pos)

	out_final = d_out.copy_to_host()
	print out_final[:50]
	print type(out_final[0][0])

if __name__ == "__main__":
	main()

**Comment by gmarkall** [comment]
After fixing up the reproducer (some syntax errors, and Python 3 changes):

```python
import numpy as np
from numba import cuda
import pyopencl.array as cl_array

W = 500
H = 500
TX = 32
TY = 32


@cuda.jit(device=True)
def clip(n):
    if n > 255:
        n = 255
    elif n < 0:
        n = 0
    return n


@cuda.jit()  # "(uint8[::1], int32, int32, float32[::1])"
def distanceKernel(d_out, w, h, pos):
    c = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.y
    r = cuda.blockIdx.y * cuda.blockDim.y + cuda.threadIdx.y
    i = r * w + c

    if c >= w or r >= h:
        return

    # d = math.sqrt((c - pos[0]) * (c - pos[0]) + (r - pos[1]) * (r - pos[1]))

    # intensity = clip(255 - d)

    d_out[i][0] = np.uint8(0)  # intensity
    d_out[i][1] = 0  # intensity
    d_out[i][2] = 0
    d_out[i][3] = 255


def main():
    pos = np.zeros([2], dtype=cl_array.vec.int2)  # 'float32'
    blockSize = (TX, TY)
    bx = (W + TX - 1) // TX
    by = (W + TY - 1) // TY
    gridSize = (bx, by)

    out = np.zeros([W * H], dtype=cl_array.vec.uchar4)
    d_out = cuda.to_device(out)

    distanceKernel[blockSize, gridSize](d_out, W, H, pos)

    out_final = d_out.copy_to_host()
    print(out_final[:50])
    print(type(out_final[0][0]))


if __name__ == "__main__":
    main()
```

This still fails with an error that appears to mean pretty much the same thing:

```
$ python repro.py 
repro.py:40: DeprecationWarning: pyopencl.array.vec is deprecated. Please use pyopencl.cltypes for OpenCL vector and scalar types
  pos = np.zeros([2], dtype=cl_array.vec.int2)  # 'float32'
repro.py:46: DeprecationWarning: pyopencl.array.vec is deprecated. Please use pyopencl.cltypes for OpenCL vector and scalar types
  out = np.zeros([W * H], dtype=cl_array.vec.uchar4)
Traceback (most recent call last):
  File "repro.py", line 57, in <module>
    main()
  File "repro.py", line 49, in main
    distanceKernel[blockSize, gridSize](d_out, W, H, pos)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 758, in __call__
    kernel = self.specialize(*args)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 769, in specialize
    kernel = self.compile(argtypes)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 785, in compile
    **self.targetoptions)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 57, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 46, in compile_cuda
    locals={})
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 98, in run_pass
    raise_errors=self._raise_errors)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 70, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 986, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (Record(s0[type=uint8;offset=0;title=x],x[type=uint8;offset=0;title=x],s1[type=uint8;offset=1;title=y],y[type=uint8;offset=1;title=y],s2[type=uint8;offset=2;title=z],z[type=uint8;offset=2;title=z],s3[type=uint8;offset=3;title=w],w[type=uint8;offset=3;title=w];4;False), Literal[int](0), uint8)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of staticsetitem at repro.py (33)

File "repro.py", line 33:
def distanceKernel(d_out, w, h, pos):
    <source elided>

    d_out[i][0] = np.uint8(0)  # intensity
```

**Comment by stuartarchibald** [comment]
@gmarkall is this possibly fixed by https://github.com/numba/numba/pull/7359 ?

**Comment by gmarkall** [comment]
Uncommenting the commented code in my last reproducer and fixing an indexing error yields:

```python
import numpy as np
from numba import cuda
import math
import pyopencl.array as cl_array

W = 500
H = 500
TX = 32
TY = 32


@cuda.jit(device=True)
def clip(n):
    if n > 255:
        n = 255
    elif n < 0:
        n = 0
    return n


@cuda.jit()  # "(uint8[::1], int32, int32, float32[::1])"
def distanceKernel(d_out, w, h, pos):
    c = cuda.blockIdx.x * cuda.blockDim.x + cuda.threadIdx.y
    r = cuda.blockIdx.y * cuda.blockDim.y + cuda.threadIdx.y
    i = r * w + c

    if c >= w or r >= h:
        return

    d = math.sqrt((c - pos[0][0]) * (c - pos[0][0]) + (r - pos[0][1]) * (r -
                                                                         pos[0][1]))

    intensity = clip(255 - d)

    d_out[i][0] = np.uint8(0)  # intensity
    d_out[i][1] = intensity
    d_out[i][2] = 0
    d_out[i][3] = 255


def main():
    pos = np.zeros([2], dtype=cl_array.vec.int2)  # 'float32'
    blockSize = (TX, TY)
    bx = (W + TX - 1) // TX
    by = (W + TY - 1) // TY
    gridSize = (bx, by)

    out = np.zeros([W * H], dtype=cl_array.vec.uchar4)
    d_out = cuda.to_device(out)

    distanceKernel[blockSize, gridSize](d_out, W, H, pos)

    out_final = d_out.copy_to_host()
    print(out_final[:50])
    print(type(out_final[0][0]))


if __name__ == "__main__":
    main()
```

which runs and outputs:

```
[(255, 255, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (239, 255, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (223, 255, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0) (  0,   0, 0, 0)
 (207, 255, 0, 0) (  0,   0, 0, 0)]
<class 'numpy.uint8'>
```

which I believe is expected.

Closing this issue as I believe it is resolved.
