### ISSUE TITLE
Feature Request: Add support for vectorizing a jitted function

### ISSUE THREAD

**Issue by dhirschfeld** [numba/numba#2114]
Currently it throws an *"unsupported callable"* TypeError
```python
In [151]: type(func)
Out[151]: numba.targets.registry.CPUDispatcher

In [152]: f = numba.vectorize(func.signatures, target='cpu')(func)
Traceback (most recent call last):

  File "<ipython-input-152-79c4e42b865b>", line 1, in <module>
    f = numba.vectorize(func.signatures, target='cpu')(func)

  File "C:\Python\lib\site-packages\numba\npyufunc\decorators.py", line 107, in wrap
    vec = Vectorize(func, **kws)

  File "C:\Python\lib\site-packages\numba\npyufunc\decorators.py", line 33, in __new__
    return imp(func, identity, kws)

  File "C:\Python\lib\site-packages\numba\npyufunc\dufunc.py", line 80, in __init__
    super(DUFunc, self).__init__(dispatcher, **kws)

  File "C:\Python\lib\inspect.py", line 1043, in getargspec
    getfullargspec(func)

  File "C:\Python\lib\inspect.py", line 1095, in getfullargspec
    raise TypeError('unsupported callable') from ex

TypeError: unsupported callable
```

**Comment by dhirschfeld** [comment]
A workaround for now:
```python
def vectorize(func, *, target='cpu'):
    """Vectorizes a jumba jitted function `func`

    Parameters
    ----------
    func : numba.dispatcher.Dispatcher
        A function which has already been jitted

    Optional Parameters
    -------------------    
    target : str, {'cpu', 'parallel', 'cuda'}
        Any valid ufunc target

    Returns
    -------
    DUFunc
        A numba Dynamic Universal Function which wraps the 
        jitted function `func`

    """
    import inspect
    from textwrap import dedent
    from numba import vectorize
    from numba.dispatcher import Dispatcher
    assert isinstance(func, Dispatcher)
    code = """
    @vectorize({signatures}, target={target!r})
    def {func_name}({parameters}):
        return func({parameters})
    """
    name = func.__name__
    parameters = inspect.signature(func).parameters
    parameters = ', '.join(parameters.keys())
    code = code.format(
        signatures=func.signatures,
        target=target,
        func_name=name,
        parameters=parameters,
    )
    exec(dedent(code))
    return locals()[name]
```

**Comment by seibert** [comment]
@sklam: Ideas for how to best handle this inside Numba directly?

**Comment by sklam** [comment]
The simplest workaround is probably:

```python
In [1]: from numba import njit, vectorize

In [2]: @njit
   ...: def foo(a, b):
   ...:     return a + b
   ...: 

In [3]: foo(1, 2)
Out[3]: 3

In [4]: foo(3, 5)
Out[4]: 8

In [5]: bar = vectorize(target='cpu')(foo.py_func)

In [6]: bar(1,2)
Out[6]: 3

In [7]: bar([1,2], [3, 5])
Out[7]: array([4, 7])

```


Directly using the signature from CPUDispatcher is probably not preferred, since `@vectorize` expects arguments types that can be stored in numpy arrays and CPUDispatcher supports more types.

**Comment by dhirschfeld** [comment]
That's a lot cleaner than my solution! It could perhaps be made to work automatically with a simple `isinstance` check:
```python
if isinstance(func, Dispatcher):
    return vectorize(**kwargs)(func.py_func)
else:
    ...
```

**Comment by dhirschfeld** [comment]
In case it's useful I put in a pull request implementing the isinstance check which seems to work for me.
