### ISSUE TITLE
Cached functions fail when called from different programs

### ISSUE THREAD

**Issue by bryanhe** [numba/numba#2116]
Functions within a package seem to cause problems if they are cached from a function call within the package and then called from the outside (and also if they are cached from the outside and then called inside).

Consider the following file structure (also attached [here](https://github.com/numba/numba/files/462934/example.zip)):

```
test.py*
package/
    __init__.py
    package.py*
    util.py
```

where \* indicates that the file is executable.

In this example, util.py contains some Numba-compiled functions, and the user is mostly expected to call package/package.py. test.py runs various test scripts for the package.

However, running the two commands:

```
./test.py
package/package.py
```

results in the following error:

```
Traceback (most recent call last):
  File "package/package.py", line 6, in <module>
    util.f()
  File "/usr/lib/python2.7/site-packages/numba-0.29.0.dev0+14.g17ab9cc-py2.7-linux-x86_64.egg/numba/dispatcher.py", line 285, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/lib/python2.7/site-packages/numba-0.29.0.dev0+14.g17ab9cc-py2.7-linux-x86_64.egg/numba/dispatcher.py", line 520, in compile
    cres = self._cache.load_overload(sig, self.targetctx)
  File "/usr/lib/python2.7/site-packages/numba-0.29.0.dev0+14.g17ab9cc-py2.7-linux-x86_64.egg/numba/caching.py", line 348, in load_overload
    return self._load_overload(sig, target_context)
  File "/usr/lib/python2.7/site-packages/numba-0.29.0.dev0+14.g17ab9cc-py2.7-linux-x86_64.egg/numba/caching.py", line 360, in _load_overload
    return self._load_data(data_name, target_context)
  File "/usr/lib/python2.7/site-packages/numba-0.29.0.dev0+14.g17ab9cc-py2.7-linux-x86_64.egg/numba/caching.py", line 491, in _load_data
    tup = pickle.loads(data)
  File "/usr/lib/python2.7/site-packages/numba-0.29.0.dev0+14.g17ab9cc-py2.7-linux-x86_64.egg/numba/lowering.py", line 30, in _rebuild_env
    mod = serialize._rebuild_module(modname)
  File "/usr/lib/python2.7/site-packages/numba-0.29.0.dev0+14.g17ab9cc-py2.7-linux-x86_64.egg/numba/serialize.py", line 38, in _rebuild_module
    __import__(name)
ImportError: ('No module named util', <function _rebuild_env at 0x7fbe528ad398>, ('package.util', []))
```

Running the commands in the opposite order results in a similar error.
This can be fixed by removing __pycache__ before switching, so it seems clear that this a caching issue.

This is run on Ubuntu 16.04 with Numba version 0.29.0.

test.py:

```
#!/usr/bin/env python

import package

package.util.f()
```

package/__init__.py:

```
import package
import util

__all__ = ['package', 'util']
```

package/package.py:

```
#!/usr/bin/env python

import util

if __name__ == '__main__':
    util.f()
```

package/util.py:

```
from __future__ import print_function
import numba


@numba.jit(cache=True)
def f():
    print('Hello')
```

**Comment by pitrou** [comment]
Your use of imports and packages is fragile and inconsistent here.
First, well, avoid calling a package and a module the same name (`package`), it's just a recipe for confusion.
Second, inside a Python package, only use intra-package imports, not "absolute" imports. That is, inside the `package` directory, use `from . import package` or `from . import util`, not `import package` nor `import util`.

**Comment by stuartarchibald** [comment]
Closing as undetermined ability to reproduce.
