### ISSUE TITLE
__init__ is mandatory for `jitclass`

### ISSUE THREAD

**Issue by ma-ba** [numba/numba#2167]
It is not possible to have a `jitclass` (without fields) and omit the explicit `__init__` method.
```python
from numba import jitclass


@jitclass([])
def Class:
    def method(self, x):
        return x
```
traceback:
```python
Traceback (most recent call last):
  File "jitclass_init_mandatory.py", line 3, in <module>
    @jitclass([])
  File "/home/maba/dev/numba/git/numba/numba/jitclass/decorators.py", line 27, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File "/home/maba/dev/numba/git/numba/numba/jitclass/base.py", line 207, in register_class_type
    __doc__=docstring))
  File "/home/maba/dev/numba/git/numba/numba/jitclass/base.py", line 90, in __new__
    outcls._set_init()
  File "/home/maba/dev/numba/git/numba/numba/jitclass/base.py", line 98, in _set_init
    init = cls.class_type.instance_type.methods['__init__']
KeyError: '__init__'
```

**Comment by esc** [comment]
I check this on current master and it doesn't yet work. I relabelled this as 'feature request'. Also the original snippet contains a typo, it should be `class` not `def`. Here is a corrected version for reference:

```
from numba import jitclass


@jitclass([])
class Class:
    def method(self, x):
        return x

c = Class()
```

**Comment by Crizomb** [comment]
It still doesn't work, but you can probably wrote a dummy class like this.
```python
@jitclass([])
class Tools:
    def __init__(self): None
    
    @staticmethod
    def norm(vec):
        return (vec[0]**2 + vec[1]**2 + vec[2]**2)**0.5
  ```
