### ISSUE TITLE
Feature request: Allow arithmetic operations with arrays and tuples

### ISSUE THREAD

**Issue by mbargull** [numba/numba#2173]
Since arithmetic operations between arrays and tuples are not supported yet, it is not possible to easily aggregate (i.e. without unpacking / single element assigning) results from functions which return tuples. Pseudo use case:

``` python
import numpy as np
from numba import njit

@njit
def do_something(i):
    return i+1, i*2

@njit
def aggregate_something(n):
    a = np.zeros(2, dtype=np.int64)
    for i in range(n):
        a += do_something(i)
    return a
```

Also note that the following gives a readable error message when simply adding an array and a tuple. When the addition is combined with an assignment, the error message is rather obscure.

``` python
import numpy as np
from numba import njit

def add_array_tuple(a, t):
    a + t

def add_assign_array_tuple(a, t):
    a += t

t = (1, 2)
a = np.array(t)
for func in (add_array_tuple, add_assign_array_tuple):
    func(a, t)
    njit()(func)(a, t)
```

Traceback for `func is add_array_tuple`:

``` python
Traceback (most recent call last):
  File "array_tuple_add.py", line 14, in <module>
    njit()(func)(a, t)
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 309, in _compile_for_args
    raise e
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 286, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 532, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 81, in compile
    flags=flags, locals=self.locals)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 684, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 348, in compile_extra
    return self._compile_bytecode()
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 649, in _compile_bytecode
    return self._compile_core()
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 636, in _compile_core
    res = pm.run(self.status)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 235, in run
    raise patched_exception
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 227, in run
    stage()
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 436, in stage_nopython_frontend
    self.locals)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 785, in type_inference_stage
    infer.propagate()
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 761, in propagate
    raise errors[0]
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 128, in propagate
    constraint(typeinfer)
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 431, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 395, in resolve
    raise TypingError(msg, loc=self.loc)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Invalid usage of + with parameters (array(int64, 1d, C), (int64 x 2))
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
 * (uint8,) -> uint64
 * (uint32,) -> uint64
 * (uint16,) -> uint64
 * (uint64,) -> uint64
 * (int32,) -> int64
 * (int16,) -> int64
 * (int64,) -> int64
 * (int8,) -> int64
 * (float32,) -> float32
 * (float64,) -> float64
 * (complex64,) -> complex64
 * (complex128,) -> complex128
 * parameterized
File "array_tuple_add.py", line 5
[1] During: typing of intrinsic-call at array_tuple_add.py (5)
```

Traceback for `func is add_assign_array_tuple`:

``` python
Traceback (most recent call last):
  File "array_tuple_add.py", line 14, in <module>
    njit()(func)(a, t)
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 309, in _compile_for_args
    raise e
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 286, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 532, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/maba/dev/numba/git/numba/numba/dispatcher.py", line 81, in compile
    flags=flags, locals=self.locals)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 684, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 348, in compile_extra
    return self._compile_bytecode()
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 649, in _compile_bytecode
    return self._compile_core()
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 636, in _compile_core
    res = pm.run(self.status)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 235, in run
    raise patched_exception
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 227, in run
    stage()
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 436, in stage_nopython_frontend
    self.locals)
  File "/home/maba/dev/numba/git/numba/numba/compiler.py", line 785, in type_inference_stage
    infer.propagate()
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 761, in propagate
    raise errors[0]
numba.errors.TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.IntrinsicCallConstraint object at 0x7ffbe8e0a438>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maba/dev/numba/git/numba/numba/errors.py", line 243, in new_error_context
    yield
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 431, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 386, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 1021, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/home/maba/dev/numba/git/numba/numba/typing/context.py", line 189, in resolve_function_type
    res = defn.apply(args, kws)
  File "/home/maba/dev/numba/git/numba/numba/typing/templates.py", line 185, in apply
    sig = generic(args, kws)
  File "/home/maba/dev/numba/git/numba/numba/typing/npydecl.py", line 235, in generic
    assert len(sig.args) == 3
AttributeError: 'NoneType' object has no attribute 'args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 128, in propagate
    constraint(typeinfer)
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 431, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/home/maba/miniconda3/envs/numba-git/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/maba/dev/numba/git/numba/numba/errors.py", line 249, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/home/maba/dev/numba/git/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/maba/dev/numba/git/numba/numba/errors.py", line 243, in new_error_context
    yield
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 431, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 386, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/home/maba/dev/numba/git/numba/numba/typeinfer.py", line 1021, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/home/maba/dev/numba/git/numba/numba/typing/context.py", line 189, in resolve_function_type
    res = defn.apply(args, kws)
  File "/home/maba/dev/numba/git/numba/numba/typing/templates.py", line 185, in apply
    sig = generic(args, kws)
  File "/home/maba/dev/numba/git/numba/numba/typing/npydecl.py", line 235, in generic
    assert len(sig.args) == 3
numba.errors.InternalError: 'NoneType' object has no attribute 'args'
[1] During: typing of intrinsic-call at array_tuple_add.py (8)
--%<-----------------------------------------------------------------

File "array_tuple_add.py", line 8
```

**Comment by stuartarchibald** [comment]
As of 0.49.x this:
```python
import numpy as np
from numba import njit

def add_assign_array_tuple(a, t):
    a += t

t = (1, 2)
a = np.array(t)
njit()(add_assign_array_tuple)(a, t)
```
does this:
```
Invalid use of Function(<built-in function iadd>) with argument(s) of type(s): (array(int64, 1d, C), UniTuple(int64 x 2))
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
<snip>
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at issue2173.py (5)

File "issue2173.py", line 5:
def add_assign_array_tuple(a, t):
    a += t
```
Closing as resolved.
