### ISSUE TITLE
Failed at nopython (nopython frontend)

### ISSUE THREAD

**Issue by ritchieng** [numba/numba#2177]
I've a numpy array `wt` and when I run. 
Numba version: 0.29.0
```
            # Get hd
            @cuda.jit
            def get_hd(s_param, type):
                s = s_param
                row = s.shape[0]
                col = s.shape[1]
                size = row

                if type == 1:
                    size = row * col
                    s = s.reshape(size, s.shape[2])

                g = np.zeros((size, 12), dtype='float32')

                for i in range(0, size):
                    gc = get_gc(s[i])
                    g[i] = gc

                g = np.transpose(g)

                h = np.zeros((12, 5), dtype='float32')

                for i in range(0, 12):
                    hd = np.zeros((5), dtype='float32')
                    hd[0] = np.mean(g[i])
                    hd[1] = np.median(g[i])
                    hd[2] = np.std(g[i])
                    hd[3] = np.min(g[i])
                    hd[4] = np.min(g[i])
                    h[i] = hd
                return h

            @cuda.jit
            def get_state(w):

                res = {}

                res[len(res) + 1] = get_gc(w)
                res[len(res) + 1] = get_hd(w, 0)[:]
                res[len(res) + 1] = get_hd(np.transpose(w), 0)[:]
                res[len(res) + 1] = get_hd(w, 1)[:]

                state = res[1].reshape(12, 1)

                for i in range(2, len(res) + 1):
                    state = np.concatenate((state, res[i]), axis=1)

                return state

            state = get_state(wt)

```

I get the following error:
```
  File "cifar_wide_resnet_tl.py", line 399, in step
    state = get_state(wt)
  File "/usr/local/lib/python2.7/dist-packages/numba/cuda/compiler.py", line 701, in __call__
    kernel = self.specialize(*args)
  File "/usr/local/lib/python2.7/dist-packages/numba/cuda/compiler.py", line 717, in specialize
    **self.targetoptions)
  File "/usr/local/lib/python2.7/dist-packages/numba/cuda/compiler.py", line 37, in core
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/cuda/compiler.py", line 75, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/usr/local/lib/python2.7/dist-packages/numba/cuda/compiler.py", line 37, in core
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/cuda/compiler.py", line 64, in compile_cuda
    locals={})
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 684, in compile_extra
    return pipeline.compile_extra(fund)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 348, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 649, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 636, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 235, in run
    raise patched_exception
NotImplementedError: Caused By:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 227, in run
    stage()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 436, in stage_nopython_frontend
    self.locals)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 784, in type_inference_stage
    infer.build_constraint()
  File "/usr/local/lib/python2.7/dist-packages/numba/typeinfer.py", line 717, in build_constraint
    self.constrain_statement(inst)
  File "/usr/local/lib/python2.7/dist-packages/numba/typeinfer.py", line 876, in constrain_statement
    self.typeof_assign(inst)
  File "/usr/local/lib/python2.7/dist-packages/numba/typeinfer.py", line 938, in typeof_assign
    self.typeof_expr(inst, inst.target, value)
  File "/usr/local/lib/python2.7/dist-packages/numba/typeinfer.py", line 1117, in typeof_expr
    raise NotImplementedError(type(expr), expo)
NotImplementedError: (<class 'numba.ir.Expr'>, build_map(items=[], size=0))

Failed at nopython (no python front-end
(<class 'numba.ir.Expr'>, build_map(items=[], size=0))
```)

**Comment by ritchieng** [comment]
My own mistake of leaving out some code that is required.
