### ISSUE TITLE
Error when using cffi.lib.myfun directly and not through alias

### ISSUE THREAD

**Issue by talkaminker** [numba/numba#2226]
Having code like this:

    import numba
    numba.register_module(mymodule)
    @numba.jit(nopython=1)
    def f():
       return mymodule.lib.fun()`
doesn't work. when the similar

    import numba
    numba.register_module(mymodule)
    fun = mymodule.lib.fun
    @numba.jit(nopython=1)
    def f():
       return fun()
does work
(I use cffi 1.9.1, python 3.5, numba 0.29.0)
This is the error I get:

     Traceback (most recent call last):
      File "<ipython-input-44-44c455c5d6d6>", line 10, in <module>
        f(a)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/dispatcher.py", line 286, in _compile_for_args
        return self.compile(tuple(argtypes))

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/dispatcher.py", line 532, in compile
        cres = self._compiler.compile(args, return_type)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/dispatcher.py", line 81, in compile
        flags=flags, locals=self.locals)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 684, in compile_extra
        return pipeline.compile_extra(func)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 348, in compile_extra
        return self._compile_bytecode()

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 649, in _compile_bytecode
        return self._compile_core()

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 636, in _compile_core
        res = pm.run(self.status)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 235, in run
        raise patched_exception

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 227, in run
        stage()

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 576, in stage_nopython_backend
        self._backend(lowerfn, objectmode=False)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 531, in _backend
        lowered = lowerfn()

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 518, in backend_nopython_mode
        self.flags)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/compiler.py", line 802, in native_lowering_stage
        lower.lower()

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 126, in lower
        self.lower_normal_function(self.fndesc)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 161, in lower_normal_function
        entry_block_tail = self.lower_function_body()

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 186, in lower_function_body
        self.lower_block(block)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 201, in lower_block
        self.lower_inst(inst)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/contextlib.py", line 77, in __exit__
        self.gen.throw(type, value, traceback)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/errors.py", line 249, in new_error_context
        six.reraise(type(newerr), newerr, sys.exc_info()[2])

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/six.py", line 658, in reraise
        raise value.with_traceback(tb)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/errors.py", line 243, in new_error_context
        yield

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 201, in lower_block
        self.lower_inst(inst)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 238, in lower_inst
        val = self.lower_assign(ty, inst)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 383, in lower_assign
        return self.lower_expr(ty, value)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/lowering.py", line 790, in lower_expr
        impl = self.context.get_getattr(ty, expr.attr)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/targets/base.py", line 521, in get_getattr
        llval = self.get_constant(attrty, pyval)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/targets/base.py", line 446, in get_constant
        return self.get_constant_generic(None, ty, val)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/targets/base.py", line 436, in get_constant_generic
        return impl(self, builder, ty, val)

      File "/home/tal/anaconda3/envs/py35/lib/python3.5/site-packages/numba/targets/builtins.py", line 269, in constant_function_pointer
        return builder.inttoptr(ptrval, ptrty)

    LoweringError: 'NoneType' object has no attribute 'inttoptr'

**Comment by jacksonloper** [comment]
This is still a weird problem as of 35.  At least maybe put it in the docs so people don't get confused.  Maybe [here?](http://numba.pydata.org/numba-doc/0.35.0/reference/pysupported.html#numba.cffi_support.register_module)

```
import numba,cffi,numba.cffi_support
ffibuilder = cffi.FFI()

ffibuilder.set_source("_example",'double gsl_sf_psi (double x);',
    libraries=['gsl','gslcblas'])
ffibuilder.cdef('double gsl_sf_psi (double x);')
ffibuilder.compile()

import _example
numba.cffi_support.register_module(_example)

digamma=_example.lib.gsl_sf_psi

@numba.jit(nopython=True)
def happy(n):
    x=0.0
    for i in range(n):
        x=x+digamma(5)
    return x

@numba.jit(nopython=True)
def sad(n):
    x=0.0
    for i in range(n):
        x=x+_example.lib.gsl_sf_psi(5)
    return x

print("happy works:",happy(5))
print(sad(5))
```

yields

```
happy works: 7.530588342159002
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/opt/conda/lib/python3.5/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    258     try:
--> 259         yield
    260     except NumbaError as e:

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_block(self, block)
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_inst(self, inst)
    264             ty = self.typeof(inst.target.name)
--> 265             val = self.lower_assign(ty, inst)
    266             self.storevar(val, inst.target.name)

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_assign(self, ty, inst)
    410         elif isinstance(value, ir.Expr):
--> 411             return self.lower_expr(ty, value)
    412 

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_expr(self, resty, expr)
    824             else:
--> 825                 impl = self.context.get_getattr(ty, expr.attr)
    826                 attrty = self.context.typing_context.resolve_getattr(ty,

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in get_getattr(self, typ, attr)
    540                 pyval = getattr(typ.pymod, attr)
--> 541                 llval = self.get_constant(attrty, pyval)
    542                 def imp(context, builder, typ, val, attr):

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in get_constant(self, ty, val)
    465         # HACK: pass builder=None to preserve get_constant() API
--> 466         return self.get_constant_generic(None, ty, val)
    467 

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in get_constant_generic(self, builder, ty, val)
    455             impl = self._get_constants.find((ty,))
--> 456             return impl(self, builder, ty, val)
    457         except NotImplementedError:

/opt/conda/lib/python3.5/site-packages/numba/targets/builtins.py in constant_function_pointer(context, builder, ty, pyval)
    267     ptrval = context.add_dynamic_addr(builder, ty.get_pointer(pyval),
--> 268                                       info=str(pyval))
    269     return builder.bitcast(ptrval, ptrty)

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in add_dynamic_addr(self, builder, intaddr, info)
    987         assert isinstance(intaddr, utils.INT_TYPES), 'dyn addr not of int type'
--> 988         mod = builder.module
    989         llvoidptr = self.get_value_type(types.voidptr)

AttributeError: 'NoneType' object has no attribute 'module'

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-1-10808ddde006> in <module>()
     27 
     28 print("happy works:",happy(5))
---> 29 print(sad(5))

/opt/conda/lib/python3.5/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    305                 argtypes.append(self.typeof_pyval(a))
    306         try:
--> 307             return self.compile(tuple(argtypes))
    308         except errors.TypingError as e:
    309             # Intercept typing error that may be due to an argument

/opt/conda/lib/python3.5/site-packages/numba/dispatcher.py in compile(self, sig)
    577 
    578                 self._cache_misses[sig] += 1
--> 579                 cres = self._compiler.compile(args, return_type)
    580                 self.add_overload(cres)
    581                 self._cache.save_overload(sig, cres)

/opt/conda/lib/python3.5/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     78                                       impl,
     79                                       args=args, return_type=return_type,
---> 80                                       flags=flags, locals=self.locals)
     81         # Check typing error if object mode is used
     82         if cres.typing_error is not None and not flags.enable_pyobject:

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    761     pipeline = Pipeline(typingctx, targetctx, library,
    762                         args, return_type, flags, locals)
--> 763     return pipeline.compile_extra(func)
    764 
    765 

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in compile_extra(self, func)
    358         self.lifted = ()
    359         self.lifted_from = None
--> 360         return self._compile_bytecode()
    361 
    362     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in _compile_bytecode(self)
    720         """
    721         assert self.func_ir is None
--> 722         return self._compile_core()
    723 
    724     def _compile_ir(self):

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in _compile_core(self)
    707 
    708         pm.finalize()
--> 709         res = pm.run(self.status)
    710         if res is not None:
    711             # Early pipeline completion

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in run(self, status)
    244                     # No more fallback pipelines?
    245                     if is_final_pipeline:
--> 246                         raise patched_exception
    247                     # Go to next fallback pipeline
    248                     else:

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in run(self, status)
    236                 try:
    237                     event(stage_name)
--> 238                     stage()
    239                 except _EarlyPipelineCompletion as e:
    240                     return e.result

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in stage_nopython_backend(self)
    642         """
    643         lowerfn = self.backend_nopython_mode
--> 644         self._backend(lowerfn, objectmode=False)
    645 
    646     def stage_compile_interp_mode(self):

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    597             self.library.enable_object_caching()
    598 
--> 599         lowered = lowerfn()
    600         signature = typing.signature(self.return_type, *self.args)
    601         self.cr = compile_result(typing_context=self.typingctx,

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in backend_nopython_mode(self)
    584                 self.return_type,
    585                 self.calltypes,
--> 586                 self.flags)
    587 
    588     def _backend(self, lowerfn, objectmode):

/opt/conda/lib/python3.5/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags)
    880 
    881     lower = lowering.Lower(targetctx, library, fndesc, interp)
--> 882     lower.lower()
    883     if not flags.no_cpython_wrapper:
    884         lower.create_cpython_wrapper(flags.release_gil)

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower(self)
    133         if self.generator_info is None:
    134             self.genlower = None
--> 135             self.lower_normal_function(self.fndesc)
    136         else:
    137             self.genlower = self.GeneratorLower(self)

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    174         # Init argument values
    175         self.extract_function_arguments()
--> 176         entry_block_tail = self.lower_function_body()
    177 
    178         # Close tail of entry block

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_function_body(self)
    199             bb = self.blkmap[offset]
    200             self.builder.position_at_end(bb)
--> 201             self.lower_block(block)
    202 
    203         self.post_lower()

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_block(self, block)
    214             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 
    218     def create_cpython_wrapper(self, release_gil=False):

/opt/conda/lib/python3.5/contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:

/opt/conda/lib/python3.5/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    263     except Exception as e:
    264         newerr = errcls(e).add_context(_format_msg(fmt_, args, kwargs))
--> 265         six.reraise(type(newerr), newerr, sys.exc_info()[2])
    266 
    267 

/opt/conda/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

/opt/conda/lib/python3.5/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    257 
    258     try:
--> 259         yield
    260     except NumbaError as e:
    261         e.add_context(_format_msg(fmt_, args, kwargs))

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_block(self, block)
    214             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    215                                    loc=self.loc, errcls_=defaulterrcls):
--> 216                 self.lower_inst(inst)
    217 
    218     def create_cpython_wrapper(self, release_gil=False):

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_inst(self, inst)
    263         if isinstance(inst, ir.Assign):
    264             ty = self.typeof(inst.target.name)
--> 265             val = self.lower_assign(ty, inst)
    266             self.storevar(val, inst.target.name)
    267 

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_assign(self, ty, inst)
    409 
    410         elif isinstance(value, ir.Expr):
--> 411             return self.lower_expr(ty, value)
    412 
    413         elif isinstance(value, ir.Var):

/opt/conda/lib/python3.5/site-packages/numba/lowering.py in lower_expr(self, resty, expr)
    823                 return res
    824             else:
--> 825                 impl = self.context.get_getattr(ty, expr.attr)
    826                 attrty = self.context.typing_context.resolve_getattr(ty,
    827                                                                      expr.attr)

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in get_getattr(self, typ, attr)
    539             else:
    540                 pyval = getattr(typ.pymod, attr)
--> 541                 llval = self.get_constant(attrty, pyval)
    542                 def imp(context, builder, typ, val, attr):
    543                     return impl_ret_borrowed(context, builder, attrty, llval)

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in get_constant(self, ty, val)
    464         """
    465         # HACK: pass builder=None to preserve get_constant() API
--> 466         return self.get_constant_generic(None, ty, val)
    467 
    468     def get_constant_undef(self, ty):

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in get_constant_generic(self, builder, ty, val)
    454         try:
    455             impl = self._get_constants.find((ty,))
--> 456             return impl(self, builder, ty, val)
    457         except NotImplementedError:
    458             raise NotImplementedError("cannot lower constant of type '%s'" % (ty,))

/opt/conda/lib/python3.5/site-packages/numba/targets/builtins.py in constant_function_pointer(context, builder, ty, pyval)
    266     ptrty = context.get_function_pointer_type(ty)
    267     ptrval = context.add_dynamic_addr(builder, ty.get_pointer(pyval),
--> 268                                       info=str(pyval))
    269     return builder.bitcast(ptrval, ptrty)
    270 

/opt/conda/lib/python3.5/site-packages/numba/targets/base.py in add_dynamic_addr(self, builder, intaddr, info)
    986         assert self.allow_dynamic_globals, "dyn globals disabled in this target"
    987         assert isinstance(intaddr, utils.INT_TYPES), 'dyn addr not of int type'
--> 988         mod = builder.module
    989         llvoidptr = self.get_value_type(types.voidptr)
    990         addr = self.get_constant(types.uintp, intaddr).inttoptr(llvoidptr)

LoweringError: Failed at nopython (nopython mode backend)
'NoneType' object has no attribute 'module'
File "<ipython-input-1-10808ddde006>", line 25
[1] During: lowering "$22.5 = getattr(value=$22.4, attr=gsl_sf_psi)" at <ipython-input-1-10808ddde006> (25)
```
