### ISSUE TITLE
Python crashes when calling compiled function with default argument

### ISSUE THREAD

**Issue by amorgun** [numba/numba#2235]
## Code for reproducing the error:
```python
import numpy as np
from numba import jit

a = np.zeros(2)
@jit
def foo(a=a):
    a[0] += 1
foo()
```
## Result:
 Crash of python.exe. At the same time `foo(a=a)` works fine.

## Environment:
```python
import sys
import numba
import platform
print(sys.version)
print(numba.__version__)
print(platform.platform())
```
Output:
```
3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)]
0.30.0
Windows-7-6.1.7601-SP1
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can replicate on Linux.

Top few frames:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7fec08a in ?? ()
(gdb) bt
#0  0x00007ffff7fec08a in ?? ()
#1  0x00007fffe57d6f48 in ?? ()
#2  0x00007fffe5539748 in ?? ()
#3  0x00007fffe489b708 in ?? ()
#4  0x00007fffe5b015f2 in call_cfunc (locals=0x0, kws=0x0, args=0x7ffff7e5ae48, cfunc=0x7fffe47a58d0, self=0x7fffe57d6f48)
    at numba/_dispatcher.c:339
#5  compile_and_invoke (self=self@entry=0x7fffe57d6f48, args=args@entry=0x7ffff7e5ae48, kws=kws@entry=0x0, 
    locals=locals@entry=0x0) at numba/_dispatcher.c:362
#6  0x00007fffe5b01f71 in Dispatcher_call (self=0x7fffe57d6f48, args=<optimized out>, kws=<optimized out>)
    at numba/_dispatcher.c:562
#7  0x00007ffff7954236 in PyObject_Call (func=0x7fffe57d6f48, arg=<optimized out>, kw=<optimized out>)
    at Objects/abstract.c:2165
#8  0x00007ffff7a2e314 in do_call (nk=<optimized out>, na=0, pp_stack=0x7fffffffd4b8, func=0x7fffe57d6f48)
    at Python/ceval.c:4936

```
compile result is like:
```python
CompileResult(typing_context=<numba.typing.context.Context object at 0x7fffe57caf60>,
target_context=<numba.targets.cpu.CPUContext object at 0x7fffe4840780>,
entry_point=<built-in method foo of _dynfunc._Closure object at 0x7fffe47a58d0>,
typing_error=None, type_annotation=<numba.annotations.type_annotations.TypeAnnotation object at 
0x7fffe4840a20>, signature=(omitted(default=array([ 0.,  0.])),) -> none, objectmode=False, lifted=(), 
fndesc=<function descriptor 'foo$1'>, interpmode=False, library=<Library 'foo' at 0x7fffe4853e10>, 
call_helper=None, environment=<numba.lowering.Environment object at 0x7fffe4853eb8>, 
has_dynamic_globals=False)
```

**Comment by stuartarchibald** [comment]
As of Numba 0.56, this does not segfault, however it doesn't replicate the behaviour without the JIT, the array `a` is not updated. It should probably also be noted that mutable default values often cause surprises, so I'm not sure that this will be fixed.
