### ISSUE TITLE
Error message needs improvement

### ISSUE THREAD

**Issue by seibert** [numba/numba#2237]
The error message when running this code:
``` python
from numba import jit
import numba
import numpy

f = numpy.zeros(shape=(3,3,3))

@jit(nopython=True)
def explorethisx(inar, x):
    places = []
    places.append((x,0))
    x1,y1 = x,0
    s = numba.int64(0)
    co = 0
    #for _ in range( 799):

    while co != numba.int16(799):
        co += 1
        a1,a2,a3 = 999,999,999
        a1 = inar[y1 + 1][x1-1][1]
        a2 = inar[y1 + 1][x1][1]
        a3 = inar[y1 + 1][x1 + 1][1]
        m = a1
        ch = -1
        if m > a2:
            m = a2
            ch = 0
        if m > a3:
            m = a3
            ch = 1
        x1 = x1 + ch
        y1 = y1 + 1
        s += inar[y1][x1][1]
        places.append((x1,y1))
    return [s, places]

print explorethisx(f,3)
```
does not indicate what line number the error is happening on, or what the problem is:
```
Traceback (most recent call last):
  File "test.py", line 35, in <module>
    print explorethisx(f,3)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 309, in _compile_for_args
    raise e
numba.errors.TypingError: Caused By:
Traceback (most recent call last):
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 228, in run
    stage()
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 442, in stage_nopython_frontend
    self.locals)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 795, in type_inference_stage
    typemap, restype, calltypes = infer.unify()
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 819, in unify
    check_var(var)
  File "/Users/stan/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 806, in check_var
    raise TypingError("Undefined variable '%s'" % (var,))
TypingError: Undefined variable '$313.3'

Failed at nopython (nopython frontend)
Undefined variable '$313.3'
```

**Comment by MSeifert04** [comment]
An identical issue has been posted on [StackOverflow](http://stackoverflow.com/questions/41558683)

Just in case you're wondering what caused this: It's because of the shape-mismatch inside the `return [s, places]`.

A minimal example to reproduce the issue is

```
from numba import jit

@jit(nopython=True)
def test():
    return [1, [1,2]]

test()
```

**Comment by stuartarchibald** [comment]
I added a patch at https://github.com/stuartarchibald/numba/commit/c64fcde5c53328266c74d5ddf711306645346a36 which will make the original traceback look like:
```python
Traceback (most recent call last):
  File "issue2237.py", line 43, in <module>
    print(explorethisx(f,3))
  File "<path>numba/numba/dispatcher.py", line 330, in _compile_for_args
    raise e
  File "<path>numba/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<path>numba/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>numba/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "<path>numba/numba/compiler.py", line 779, in compile_extra
    return pipeline.compile_extra(func)
  File "<path>numba/numba/compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File "<path>numba/numba/compiler.py", line 738, in _compile_bytecode
    return self._compile_core()
  File "<path>numba/numba/compiler.py", line 725, in _compile_core
    res = pm.run(self.status)
  File "<path>numba/numba/compiler.py", line 248, in run
    raise patched_exception
  File "<path>numba/numba/compiler.py", line 240, in run
    stage()
  File "<path>numba/numba/compiler.py", line 454, in stage_nopython_frontend
    self.locals)
  File "<path>numba/numba/compiler.py", line 882, in type_inference_stage
    typemap, restype, calltypes = infer.unify()
  File "<path>numba/numba/typeinfer.py", line 912, in unify
    check_var(var)
  File "<path>numba/numba/typeinfer.py", line 899, in check_var
    raise TypingError(msg % (var, val, loc))
numba.errors.TypingError: Failed at nopython (nopython frontend)
Undefined variable '$238.3', operation: build_list(items=[Var(s, issue2237.py (19)), Var(places, issue2237.py (16))]), location: issue2237.py (41)
```
and @MSeifert04's minimal reproducer look like:
```python
numba.errors.TypingError: Failed at nopython (nopython frontend)
Undefined variable '$0.5', operation: build_list(items=[Var($const0.1, issue2237.py (5)), Var($0.4, issue2237.py (5))]), location: issue2237.py (5)
```
if this is considered sufficient to mark the issue fixed I'll add tests and open a PR.

**Comment by seibert** [comment]
I think that's a good start.  It likely won't be clear to a new user what the problem is, but they will know where it is.  Converting the error into something easier to understand is much harder, and probably beyond the scope of this ticket anyway.

**Comment by stuartarchibald** [comment]
Thanks @seibert. I agree, this is merely a start and creating a better message that contextually describes the problem is another issue. The noted patch is a simple improvement in that it reports the location and operation that caused the problem, I've opened a PR for it https://github.com/numba/numba/pull/2741.
