### ISSUE TITLE
Numba/CFFI regression

### ISSUE THREAD

**Issue by synapticarbors** [numba/numba#2263]
I discovered what looks like a regression when calling functions via cffi in numba. I've put a minimal reproducible example in the following repository:

https://github.com/synapticarbors/numba_cffi_bug

After building the cffi module, and running `python testlib.py`, I get the following error with numba 0.30.0 and 0.30.1 on OSX but it runs without error on numba 0.29.0 and earlier. I'm using cffi 1.9.1. 

```
$ python testlib.py
Traceback (most recent call last):
  File "testlib.py", line 53, in <module>
    run()
  File "testlib.py", line 48, in run
    print(_run())
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/dispatcher.py", line 286, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/dispatcher.py", line 532, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/dispatcher.py", line 81, in compile
    flags=flags, locals=self.locals)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 350, in compile_extra
    return self._compile_bytecode()
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 658, in _compile_bytecode
    return self._compile_core()
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 645, in _compile_core
    res = pm.run(self.status)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 236, in run
    raise patched_exception
RuntimeError: Caused By:
Traceback (most recent call last):
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 228, in run
    stage()
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 583, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 538, in _backend
    lowered = lowerfn()
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 525, in backend_nopython_mode
    self.flags)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/compiler.py", line 824, in native_lowering_stage
    cfunc = targetctx.get_executable(library, fndesc, env)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/targets/cpu.py", line 156, in get_executable
    baseptr = library.get_pointer_to_function(fndesc.llvm_func_name)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/targets/codegen.py", line 403, in get_pointer_to_function
    self._ensure_finalized()
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/targets/codegen.py", line 75, in _ensure_finalized
    self.finalize()
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/numba/targets/codegen.py", line 192, in finalize
    library._get_module_for_linking(), preserve=True)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/llvmlite/binding/module.py", line 147, in link_in
    link_modules(self, other)
  File "/Users/zzz/anaconda/envs/nbtest/lib/python2.7/site-packages/llvmlite/binding/linker.py", line 12, in link_modules
    raise RuntimeError(str(outerr))
RuntimeError: Linking globals named 'numba.dynamic.globals': symbol multiply defined!

Failed at nopython (nopython mode backend)
Linking globals named 'numba.dynamic.globals': symbol multiply defined!
```

**Comment by sklam** [comment]
Thanks for the bug report.  I am able to replicate the bug with your sample code.

**Comment by synapticarbors** [comment]
@sklam Thanks for the fast response on this. Any idea when the fix will make it into a release? Is there a short term 0.30.2 planned?

**Comment by seibert** [comment]
Our next release is scheduled for ~Feb 15, so this should be merged in time for that release.

**Comment by synapticarbors** [comment]
@seibert Great, I was preparing a release of our production stack based on Anaconda 4.3 after holding off for a while, and this was the one blocking issue
