### ISSUE TITLE
'DataFlowAnalysis' object has no attribute 'op_LIST_APPEND'

### ISSUE THREAD

**Issue by asvany** [numba/numba#2301]
Name: numba
Version: 0.31.0

llvmlite-0.16.0
funcsigs-1.0.2-py2.py3-none-any.whl
llvm 3.9
ubuntu 16.04

Code:
```

import numba

@numba.jit
def prime_jit(n):
    return [ p for p in xrange(n) if len( [p % d for d in xrange(2,p/2+1) if p % d ==0] ) ==0]

```
result:

```
AttributeError                            Traceback (most recent call last)
<ipython-input-10-f2b880666b0e> in <module>()
----> 1 get_ipython().magic(u'timeit prime_jit(100)')

/home/as/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in magic(self, arg_s)
   2144         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2145         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2146         return self.run_line_magic(magic_name, magic_arg_s)
   2147 
   2148     #-------------------------------------------------------------------------

/home/as/.local/lib/python2.7/site-packages/IPython/core/interactiveshell.pyc in run_line_magic(self, magic_name, line)
   2065                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2066             with self.builtin_trap:
-> 2067                 result = fn(*args,**kwargs)
   2068             return result
   2069 

<decorator-gen-58> in timeit(self, line, cell)

/home/as/.local/lib/python2.7/site-packages/IPython/core/magic.pyc in <lambda>(f, *a, **k)
    186     # but it's overkill for just that one bit of state.
    187     def magic_deco(arg):
--> 188         call = lambda f, *a, **k: f(*a, **k)
    189 
    190         if callable(arg):

/home/as/.local/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in timeit(self, line, cell)
   1038             number = 1
   1039             for _ in range(1, 10):
-> 1040                 time_number = timer.timeit(number)
   1041                 worst_tuning = max(worst_tuning, time_number / number)
   1042                 if time_number >= 0.2:

/home/as/.local/lib/python2.7/site-packages/IPython/core/magics/execution.pyc in timeit(self, number)
    137         gc.disable()
    138         try:
--> 139             timing = self.inner(it, self.timer)
    140         finally:
    141             if gcold:

<magic-timeit> in inner(_it, _timer)

/usr/local/lib/python2.7/dist-packages/numba/dispatcher.pyc in _compile_for_args(self, *args, **kws)
    285                 argtypes.append(self.typeof_pyval(a))
    286         try:
--> 287             return self.compile(tuple(argtypes))
    288         except errors.TypingError as e:
    289             # Intercept typing error that may be due to an argument

/usr/local/lib/python2.7/dist-packages/numba/dispatcher.pyc in compile(self, sig)
    553 
    554             self._cache_misses[sig] += 1
--> 555             cres = self._compiler.compile(args, return_type)
    556             self.add_overload(cres)
    557             self._cache.save_overload(sig, cres)

/usr/local/lib/python2.7/dist-packages/numba/dispatcher.pyc in compile(self, args, return_type)
     79                                       impl,
     80                                       args=args, return_type=return_type,
---> 81                                       flags=flags, locals=self.locals)
     82         # Check typing error if object mode is used
     83         if cres.typing_error is not None and not flags.enable_pyobject:

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library)
    697     pipeline = Pipeline(typingctx, targetctx, library,
    698                         args, return_type, flags, locals)
--> 699     return pipeline.compile_extra(func)
    700 
    701 

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in compile_extra(self, func)
    350         self.lifted = ()
    351         self.lifted_from = None
--> 352         return self._compile_bytecode()
    353 
    354     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in _compile_bytecode(self)
    658         """
    659         assert self.func_ir is None
--> 660         return self._compile_core()
    661 
    662     def _compile_ir(self):

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in _compile_core(self)
    645 
    646         pm.finalize()
--> 647         res = pm.run(self.status)
    648         if res is not None:
    649             # Early pipeline completion

/usr/local/lib/python2.7/dist-packages/numba/compiler.pyc in run(self, status)
    236                     # No more fallback pipelines?
    237                     if is_final_pipeline:
--> 238                         raise patched_exception
    239                     # Go to next fallback pipeline
    240                     else:

AttributeError: Caused By:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 230, in run
    stage()
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 366, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)
  File "/usr/local/lib/python2.7/dist-packages/numba/compiler.py", line 762, in translate_stage
    return interp.interpret(bytecode)
  File "/usr/local/lib/python2.7/dist-packages/numba/interpreter.py", line 97, in interpret
    self.dfa.run()
  File "/usr/local/lib/python2.7/dist-packages/numba/dataflow.py", line 27, in run
    self.infos[blk.offset] = self.run_on_block(blk)
  File "/usr/local/lib/python2.7/dist-packages/numba/dataflow.py", line 71, in run_on_block
    self.dispatch(info, inst)
  File "/usr/local/lib/python2.7/dist-packages/numba/dataflow.py", line 80, in dispatch
    fn = getattr(self, fname)
AttributeError: 'DataFlowAnalysis' object has no attribute 'op_LIST_APPEND'

Failed at object (analyzing bytecode)
'DataFlowAnalysis' object has no attribute 'op_LIST_APPEND' 

```

**Comment by datnamer** [comment]
Numba doesn't support list comprehensions (yet?).

**Comment by sklam** [comment]
Right, due to unsupported list comprehension.  And, LIST_APPEND is only generated for list-comprehension.  A handwritten `mylist.append(myval)` wouldn't have the LIST_APPEND opcode.

**Comment by stuartarchibald** [comment]
Added in https://github.com/numba/numba/pull/2369
