### ISSUE TITLE
Closure recursively calling itself fails in bytecode analysis

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2386]
In testing https://github.com/numba/numba/pull/2369
Something like:
```python
from numba import njit

def outer(x):
    y = x + 1
    def inner(x):
        if x + y < 2:
            return 10
        else:
            inner(x - 1)
    return inner(x)

njit(outer)
```
Fails with a backtrace like:
```python
Traceback (most recent call last):
  File "<path>numba/numba/ir.py", line 69, in get
    return self._con[name]
KeyError: 'inner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path>numba/numba/ir.py", line 670, in get_exact
    return self.localvars.get(name)
  File "<path>numba/numba/ir.py", line 71, in get
    raise NotDefinedError(name)
numba.errors.NotDefinedError: 'inner' is not defined in None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path>numba/numba/ir.py", line 69, in get
    return self._con[name]
KeyError: 'inner'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path>numba/numba/tests/test_closure.py", line 218, in test_recursive_closure
    self.assertEqual(cfunc(var), ref(var))
  File "<path>numba/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<path>numba/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>numba/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "<path>numba/numba/compiler.py", line 740, in compile_extra
    return pipeline.compile_extra(func)
  File "<path>numba/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "<path>numba/numba/compiler.py", line 699, in _compile_bytecode
    return self._compile_core()
  File "<path>numba/numba/compiler.py", line 686, in _compile_core
    res = pm.run(self.status)
  File "<path>numba/numba/compiler.py", line 246, in run
    raise patched_exception
  File "<path>numba/numba/compiler.py", line 238, in run
    stage()
  File "<path>numba/numba/compiler.py", line 374, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)
  File "<path>numba/numba/compiler.py", line 803, in translate_stage
    return interp.interpret(bytecode)
  File "<path>numba/numba/interpreter.py", line 109, in interpret
    self._dispatch(inst, kws)
  File "<path>numba/numba/interpreter.py", line 238, in _dispatch
    raise e
  File "<path>numba/numba/interpreter.py", line 234, in _dispatch
    return fn(inst, **kws)
  File "<path>numba/numba/interpreter.py", line 971, in op_LOAD_CLOSURE
    gl = self.get(name)
  File "<path>numba/numba/interpreter.py", line 272, in get
    var = self.current_scope.get(name)
  File "<path>numba/numba/ir.py", line 662, in get
    return self.get_exact(name)
  File "<path>numba/numba/ir.py", line 673, in get_exact
    return self.parent.get(name)
  File "<path>numba/numba/ir.py", line 662, in get
    return self.get_exact(name)
  File "<path>numba/numba/ir.py", line 670, in get_exact
    return self.localvars.get(name)
  File "<path>numba/numba/ir.py", line 71, in get
    raise NotDefinedError(name)
numba.errors.NotDefinedError: 'inner' is not defined in <path>numba/numba/tests/test_closure.py (207)

```
The `Scope` class instance `localvars` attr is an empty dict so lookup fails and the `has_parent` is `False` so it cannot be queried.

**Comment by seibert** [comment]
Ideally, we would like to return a more understandable error indicating that recursive calls in closures are not allowed at this time.

**Comment by stuartarchibald** [comment]
Agreed. This sort of thing is fine, recursive function call in a closure...

```python
@njit
def fib3(n):
    if n < 2:
        return n
    return fib3(n - 1) + fib3(n - 2)

def outer(x):
    z = x + 1
    def inner(x):
        return x + fib3(z)
    return inner(x)

cfunc = njit(outer)
```

**Comment by ninegua** [comment]
#2369 does not give full closure support. It only supports closure calls that can be fully inlined, so a closure function calling itself is not going to work here. I'll see if we can give better error messages in this case as @seibert suggested.

**Comment by stuartarchibald** [comment]
Closing. Handled in https://github.com/numba/numba/pull/2369.
