### ISSUE TITLE
`libllvmlite.so: cannot open shared object file`

### ISSUE THREAD

**Issue by hughperkins** [numba/numba#2428]
I get this for both `pycc`, or when using `jit`

procedure:
- started docker:
```
docker run -it ubuntu:16.04
```
- then did:
```
apt-get update
apt-get install -y g++ git python python-virtualenv vim build-essential python-dev wget sudo
virtualenv -p python2 ~/env2
source ~/env2/bin/activate
mkdir git
cd git
git clone https://github.com/numba/llvmlite
cd llvmlite/
pip install enum34
python setup.py install
cat <<EOF >> /etc/apt/sources.list
deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main
deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main
EOF
wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
apt-get update
apt-get install llvm-4.0
LLVM_CONFIG=llvm-config-4.0 python setup.py install
cd ..
git clone https://github.com/numba/numba
cd numba/
cat requirements.txt | grep -v llvmlite > requirements2.txt
pip install -r requirements2.txt
python setup.py build_ext --inplace
python setup.py install
pycc
```
result of pycc:
```
(env2) root@593fb19e20fd:/git/numba# pycc
Traceback (most recent call last):
  File "/root/env2/bin/pycc", line 4, in <module>
    __import__('pkg_resources').run_script('numba==0.34.0.dev0+413.g094dfe9.dirty', 'pycc')
  File "/root/env2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/root/env2/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/root/env2/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/EGG-INFO/scripts/pycc", line 2, in <module>
    from numba.pycc import main
  File "/root/env2/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/__init__.py", line 9, in <module>
    from . import config, errors, runtests, types
  File "/root/env2/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/config.py", line 11, in <module>
    import llvmlite.binding as ll
  File "/root/env2/local/lib/python2.7/site-packages/llvmlite/binding/__init__.py", line 6, in <module>
    from .dylib import *
  File "/root/env2/local/lib/python2.7/site-packages/llvmlite/binding/dylib.py", line 4, in <module>
    from . import ffi
  File "/root/env2/local/lib/python2.7/site-packages/llvmlite/binding/ffi.py", line 50, in <module>
    raise e
OSError: /root/env2/local/lib/python2.7/site-packages/llvmlite/binding/libllvmlite.so: cannot open shared object file: No such file or directory
```

Some diag:
```
$ find ~/env2/local/lib/python2.7/site-packages/llvmlite -name 'lib*.so'
# (nothing found)
(env2) root@593fb19e20fd:/git/numba# pip freeze
enum34==1.1.6
funcsigs==1.0.2
llvmlite==0.19.0.dev0+18.g76191dc
numba==0.34.0.dev0+413.g094dfe9.dirty
numpy==1.13.0
pkg-resources==0.0.0
singledispatch==3.4.0.3
six==1.10.0
(env2) root@593fb19e20fd:/git/numba# python -c 'import llvmlite'
(env2) root@593fb19e20fd:/git/numba#
```

**Comment by hughperkins** [comment]
(seems like the files are in the cloned llvmlite folder:

```
(env2) root@593fb19e20fd:/git/llvmlite# find . -name '*.so'
./llvmlite/binding/_stub.so
./llvmlite/binding/libllvmlite.so
./ffi/libllvmlite.so
./build/lib.linux-x86_64-2.7/llvmlite/binding/_stub.so
```
)

**Comment by hughperkins** [comment]
After copying it across, by hand, works ok:

```
(env2) root@593fb19e20fd:/git/llvmlite# cp ffi/libllvmlite.so ~/env2/lib/python2.7/site-packages/llvmlite/
__init__.py   _version.py   binding/      llvmpy/       six.pyc       utils.py
__init__.pyc  _version.pyc  ir/           six.py        tests/        utils.pyc
(env2) root@593fb19e20fd:/git/llvmlite# cp ffi/libllvmlite.so ~/env2/lib/python2.7/site-packages/llvmlite/binding/
(env2) root@593fb19e20fd:/git/llvmlite# pycc
usage: pycc [-h] [-o OUTPUT] [-c | --llvm] [--header] [--python] [-d]
            inputs [inputs ...]
pycc: error: too few arguments
```

**Comment by stuartarchibald** [comment]
I think you'll need to make the change suggested here https://github.com/numba/numba/issues/2427#issuecomment-311023016 and see if that fixes it without the copy.

**Comment by hughperkins** [comment]
Not sure I understand? I already installed llvmlite. How would modifying the requirements.txt change anything?

**Comment by stuartarchibald** [comment]
I'm also slightly puzzled, suggestion was based on observation... doing the process in one env, commenting the entry leads to an error (not the same one as reported, but an error), but in a new env, with the entry patched, seemed to work ok. There's nothing in a `-vvv` log to suggest anything different happened.

**Comment by hughperkins** [comment]
:-)

I used docker, to ensure clean, reproduceable build, for the purposes of the bug reporting, by the way.

**Comment by hughperkins** [comment]
so, ok, ify ou say youve tried it, and it works, I'll try that

**Comment by hughperkins** [comment]
seems to change nothing for me:
```
(env2) root@593fb19e20fd:/git/numba# cat requirements.txt
numpy>=1.7
llvmlite>=0.19.dev
argparse
funcsigs ; python_version < '3.4'
singledispatch ; python_version < '3.4'
(env2) root@593fb19e20fd:/git/numba# pip install -r requirements.txt
Requirement already satisfied: numpy>=1.7 in /root/env2/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: llvmlite>=0.19.dev in /root/env2/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 3))
Requirement already satisfied: funcsigs in /root/env2/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: singledispatch in /root/env2/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: enum34 in /root/env2/lib/python2.7/site-packages (from llvmlite>=0.19.dev->-r requirements.txt (line 2))
Requirement already satisfied: six in /root/env2/lib/python2.7/site-packages (from singledispatch->-r requirements.txt (line 5))
(env2) root@593fb19e20fd:/git/numba# ls ~/env2/lib/python2.7/site-packages/llvmlite/binding/lib*.so
ls: cannot access '/root/env2/lib/python2.7/site-packages/llvmlite/binding/lib*.so': No such file or directory
```

**Comment by hughperkins** [comment]
Oddly, installation from llvmlite 0.16 seemed to work ok for me (but I tested llvmlite 0.16 in Mac, not in docker; the issue might be related to docker somehow. maybe some missing command, eg `tar` or something?). Anyway, I have nothing not working for me I think, so clsoing this.
