### ISSUE TITLE
`CastInstr` object has no attribute 'addrspace'

### ISSUE THREAD

**Issue by hughperkins** [numba/numba#2429]
Error message:
```
Traceback (most recent call last):
  File "test1.py", line 35, in <module>
    bubblesort_jit = numba.jit('void(f4[:])')(bubblesort)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/decorators.py", line 173, in wrapper
    **dispatcher_args)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/dispatcher.py", line 467, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/targets/registry.py", line 54, in target_context
    return self._toplevel_target_context
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/utils.py", line 283, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/targets/registry.py", line 38, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/targets/base.py", line 246, in __init__
    self.init()
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/targets/cpu.py", line 48, in init
    rtsys.initialize(self)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/runtime/nrt.py", line 35, in initialize
    self._library = nrtdynmod.compile_nrt_functions(ctx)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/runtime/nrtdynmod.py", line 199, in compile_nrt_functions
    ir_mod, library = create_nrt_module(ctx)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/runtime/nrtdynmod.py", line 185, in create_nrt_module
    _define_nrt_meminfo_data(ir_mod)
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/runtime/nrtdynmod.py", line 40, in _define_nrt_meminfo_data
    data_ptr = builder.load(cgutils.gep(builder, struct_ptr, 0, 3))
  File "/root/env2/local/lib/python2.7/site-packages/numba-0.34.0.dev0+413.g094dfe9.dirty-py2.7-linux-x86_64.egg/numba/cgutils.py", line 819, in gep
    return builder.gep(ptr, idx, name=name, inbounds=inbounds)
  File "/root/env2/local/lib/python2.7/site-packages/llvmlite/ir/builder.py", line 769, in gep
    inbounds=inbounds, name=name)
  File "/root/env2/local/lib/python2.7/site-packages/llvmlite/ir/instructions.py", line 456, in __init__
    typ = typ.as_pointer(ptr.addrspace)
AttributeError: 'CastInstr' object has no attribute 'addrspace'
```

test script:
```
from __future__ import print_function
import numba
import numpy as np
import time


def bubblesort(X):
    N = len(X)
    for end in range(N, 1, -1):
        for i in range(end - 1):
            cur = X[i]
            if cur > X[i + 1]:
                tmp = X[i]
                X[i] = X[i + 1]
                X[i + 1] = tmp


if __name__ == '__main__':
    print(numba.__version__)
    original = np.arange(0.0, 10.0, 0.01, dtype='f4')
    shuffled = original.copy()
    np.random.seed(123)
    np.random.shuffle(shuffled)
    times = []
    for it in range(5):
        sorted = shuffled.copy()
        start = time.time()
        bubblesort(sorted)
        elapsed = time.time() - start
        times.append(elapsed)
    print(np.array_equal(sorted, original))
    for time in times:
        print(time)

    bubblesort_jit = numba.jit('void(f4[:])')(bubblesort)
```

Installation procedure:
- start docker:
```
docker run -it ubuntu:16.04
```
- then do, from within docker session:
```
apt-get update
apt-get install -y g++ git python python-virtualenv vim build-essential python-dev wget sudo
virtualenv -p python2 ~/env2
source ~/env2/bin/activate
mkdir git
cd git
git clone https://github.com/numba/llvmlite
cd llvmlite/
pip install enum34
python setup.py install
cat <<EOF >> /etc/apt/sources.list
deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main
deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main
EOF
wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
apt-get update
apt-get install llvm-4.0
LLVM_CONFIG=llvm-config-4.0 python setup.py install
cp ffi/libllvmlite.so ~/env2/lib/python2.7/site-packages/llvmlite/binding/
cd ..
git clone https://github.com/numba/numba
cd numba/
cat requirements.txt | grep -v llvmlite > requirements2.txt
pip install -r requirements2.txt
python setup.py build_ext --inplace
python setup.py install
```

**Comment by stuartarchibald** [comment]
Probably due to https://github.com/numba/llvmlite/pull/279, @sklam 

@hughperkins Two questions.
 * Is there a hard requirement to use the dev versions from source opposed to released versions?
 * Is there a reason to not use `conda`, we have pre-packaged development versions in the `numba` channel.

**Comment by hughperkins** [comment]
> Is there a reason to not use conda, we have pre-packaged development versions in the numba channel.

Yes. Conda is not standard Python. It's a pre-packaged python, created by Continuum Analytics.

> Is there a hard requirement to use the dev versions from source opposed to released versions?

No. Just followign the build insturctions in git.  You're saying, I should use some specific branch of each repo instead?

**Comment by stuartarchibald** [comment]
> Yes. Conda is not standard Python. It's a pre-packaged python, created by Continuum Analytics.

Yes.

> No. Just followign the build insturctions in git. You're saying, I should use some specific branch of each repo instead?

Unless you have a specific need to use the master branch, perhaps use SHA/tags matching the packaged release versions (https://github.com/numba/numba/releases) ? `numba` and `llvmlite` release in lockstep. If you elect to use the master branch, just be aware it's under active development (hence the `GEP` bug you've just bumped in to!).

**Comment by hughperkins** [comment]
Ok installing from numba 0.33, llvmlite 0.16, and llvm-3.9 worked :-) . I do have a gentle preference to use llvm-4.0, since that's what I'm using in [my own project](https://github.com/hughperkins/coriander), but I think that's down to me to manage somehow.

You've solved my issue => closing
