### ISSUE TITLE
2D+ Dynamic Shared Memory

### ISSUE THREAD

**Issue by Lomelgande** [numba/numba#2463]
Right now you can pass an integer argument  to specify 1D dynamic shared memory. Allowing for a tuple argument to allow for 2D+ dynamic shared memory allocation would be a great addition.

**Comment by bscully** [comment]
+1

**Comment by gmarkall** [comment]
I'm thinking that this may be possible by taking a slice of dynamic shared memory and reshaping it, once #5099 is merged to fix #5073 (at the moment slicing dynamic shared memory doesn't really work properly). So perhaps once could do something like:

```python
@cuda.jit
def matrix_multiplies(r, A, x, n_matrices):
    dynsmem = cuda.shared.array(0, dtype=float32)
    matrices = dynsmem[:n_matrices * 4].reshape(n_matrices, 2, 2)
    for i in range(n_matrices):
        # Do something with each 2x2 matrix in dynamic shared memory
    # ...
```

I haven't tried this yet, but I think it might be a way to have 2D+ dynamic shared arrays.

**Comment by gmarkall** [comment]
It turns out that my strategy above does not work because reshaping shared arrays does not work:

```python
from numba import cuda, types


@cuda.jit
def foo():
    a_cache = cuda.shared.array((32, 32), types.int32)
    a_cache.reshape(64, 16)


foo[1, 1]()
```

gives:

```
$ python noreshape.py 
Traceback (most recent call last):
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 1711, in complete
    driver.cuLinkComplete(self.handle, byref(cubin), byref(size))
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 294, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 329, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuLinkComplete results in CUDA_ERROR_UNKNOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "noreshape.py", line 10, in <module>
    foo[1, 1]()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 804, in __call__
    kernel = self.specialize(*args)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 815, in specialize
    kernel = self.compile(argtypes)
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 834, in compile
    kernel.bind()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 548, in bind
    self._func.get()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 433, in get
    cubin, _size = linker.complete()
  File "/home/nfs/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 1713, in complete
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [999] Call to cuLinkComplete results in CUDA_ERROR_UNKNOWN
error   : Undefined reference to 'numba_attempt_nocopy_reshape' in '<cudapy-ptx>'
```

(above example without dynamic shared memory for simplicity, but dynamic shared memory has the same problem)

**Comment by gmarkall** [comment]
xref #7528 which describes how to implement reshape for CUDA.
