### ISSUE TITLE
Error with nested prange+range loop incorporating if statement

### ISSUE THREAD

**Issue by RemiLehe** [numba/numba#2477]
Hi,

I am encountering a strange error when incorporating if statements inside nested prange+range loop. Here is a reproducer. The first function uses a simple prange loop while the second function uses a nested prange+range loop (I know there is no point in nesting the loops here, but this is just for demonstration). The second function fails to compile. 

It does compile if I remove the if condition (but then the result of the function is of course wrong)

```python
import numpy as np
import numba

N = 1000
x = np.random.rand(N)
is_positive = np.zeros(N)

@numba.njit(parallel=True)
def detect_positive( x, is_positive, N ):
    """Detect positive values in x, and store marker in `is_positive`"""
    for i in numba.prange(N):

        is_positive[i] = 0
        if x[i] > 0:
            is_positive[i] = 1
            
    return is_positive

@numba.njit(parallel=True)
def detect_positive_split( x, is_positive, N ):
    """Detect positive values in x, and store marker in `is_positive`
    SPLIT WORK ON 2 THREADS"""
    for i in numba.prange(2):

        for j in range( i*N//2, (i+1)*N//2 ):

            is_positive[j] = 0
            if x[j] > 0:
                is_positive[j] = 1
            
    return is_positive

detect_positive( x, is_positive, N )
assert np.allclose( (x>0).astype(np.float), is_positive )
print('First test passed')

detect_positive_split( x, is_positive, N )
assert np.allclose( (x>0).astype(np.float), is_positive )
print('Second test passed')
```

Here is the traceback:
```
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    detect_positive_split( x, is_positive, N )
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/compiler.py", line 740, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/compiler.py", line 699, in _compile_bytecode
    return self._compile_core()
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/compiler.py", line 686, in _compile_core
    res = pm.run(self.status)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/compiler.py", line 494, in stage_parfor_pass
    parfor_pass.run()
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/parfor.py", line 192, in run
    self._convert_prange(self.func_ir.blocks)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/parfor.py", line 352, in _convert_prange
    self._convert_prange(parfor_blocks)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/parfor.py", line 269, in _convert_prange
    call_table, _ = get_call_table(blocks)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/ir_utils.py", line 783, in get_call_table
    topo_order = find_topo_order(blocks)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/ir_utils.py", line 747, in find_topo_order
    cfg = compute_cfg_from_blocks(blocks)
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/analysis.py", line 211, in compute_cfg_from_blocks
    term = b.terminator
  File "/Users/rlehe/miniconda3/envs/fbpic/lib/python3.5/site-packages/numba/ir.py", line 780, in terminator
    return self.body[-1]
IndexError: Failed at nopython (convert to parfors)
```

**Comment by seibert** [comment]
@ehsantn: Can you take a look at this?

**Comment by ehsantn** [comment]
Sure @seibert .

**Comment by RemiLehe** [comment]
There was a minor error in the script above (the if condition in the second function read `x[j]>1` instead of `x[j]>0`), and I just edited the above description to fix it. Sorry about this.

This does not affect the fact that the second function does not compile.

**Comment by RemiLehe** [comment]
Note: my original test was a bit trivial because 
```
x = np.random.rand(N)
```
returns only positive numbers. You might want to switch to 
```
x = np.random.rand(N)  - 0.5
```
in case you are checking the vailidy of the `detect_positive` function.

**Comment by RemiLehe** [comment]
Thanks a lot for fixing this issue by the way! ✨

**Comment by ehsantn** [comment]
Thank you for reporting this issue @RemiLehe . It led to solving a deep problem.

**Comment by stuartarchibald** [comment]
Thanks for report and fixes. Patched in https://github.com/numba/numba/pull/2478. Closing.
