### ISSUE TITLE
Thread safety issue in compiler init

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2517]
Fairly sure there's a threading issue in the compiler initialisation, purely guessing, I'm tempted to say it's a synchronisation problem between typing and impl dictionaries.

This mutation of the thread safety test demonstrates:
```python
import threading
import random
import numpy as np
from numba import jit, vectorize, guvectorize

threads=4

def run_jit( **options):
    def runner():
        @jit(**options)
        def foo(n, v): # this needs to be long and needlessly involved
            a = np.ones(n)
            b = a[:1]
            c = b[0]
            d = np.zeros(n+1)
            e = np.ones(d.shape)
            f = d + e
            g = 0
            for h in range(n):
                g = g + c + f[0]
                i = np.zeros((np.int(g), np.int(g)))
                j = np.kron(i, i)
                k = j[0]
                g += k[0]
            return g
        return foo(4, 10)
    return runner

def run_compile(fnlist):
    def chooser():
        for _ in range(10):
            fn = random.choice(fnlist)
            try:
                print("thread: %s has %s" % (threading.current_thread().name, fn))
                fn()
            except Exception as ex:
                print("thread: %s: TEST HAS FAILED" % threading.current_thread().name)
                print("thread: %s, exception %s" % (threading.current_thread().name, ex))
                raise
    ths = [threading.Thread(target=chooser, name='thread_%s' % i)
            for i in range(threads)]
    for th in ths:
        th.start()
    for th in ths:
        th.join()

def run_vectorize(**options):
    def runner():
        @vectorize(['(f8, f8)'], **options)
        def foo(a, b):
            q = a + b + np.cos(a) - np.cos(a) + np.sin(b) - np.cos(b) + np.sinh(a+b) - np.cosh(a-b)
            return q

        a = b = np.random.random(10).astype(np.float64)
        return foo(a, b)
    return runner

def run_guvectorize(**options):
    def runner():
        @guvectorize(['(f8, f8, f8[:])'], '(),()->()', **options)
        def foo(a, b, out):
            q = a + b + np.sin(a) - np.cos(a) + np.sin(b) - np.cos(b) + np.sinh(a+b) - np.cosh(a-b)
            out[0] = q.real

        a = b = np.random.random(10).astype(np.float64)
        return foo(a, b)
    return runner

def test_concurrent_mix_use():
    print("Threads = %s" % threads)
    run_compile([run_jit(nopython=True),
                 run_vectorize(nopython=True),
                 run_guvectorize(nopython=True)])


if __name__ == '__main__':
   test_concurrent_mix_use()
```
gives about 1/3 of the time:
```bash
$ python foo.py 
Threads = 4
thread: thread_0 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_1 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_2 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_3 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_3: TEST HAS FAILED
thread: thread_3, exception Failed at nopython (nopython mode backend)
No definition for lowering <built-in method kron_impl of _dynfunc._Closure object at 0x7fec26a05e18>(array(float64, 2d, C), arra
y(float64, 2d, C)) -> array(float64, 2d, C)
File "foo.py", line 22
[1] During: lowering "$80.25 = call $80.22(i, i, func=$80.22, args=[Var(i, foo.py (21)), Var(i, foo.py (21))], kws=(), vararg=No
ne)" at foo.py (22)
Exception in thread thread_3:
Traceback (most recent call last):
  File "<path>/numba/errors.py", line 243, in new_error_cont
ext
    yield
  File "<path>/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/lowering.py", line 262, in lower_inst
    val = self.lower_assign(ty, inst)
  File "<path>/numba/lowering.py", line 407, in lower_assign
    return self.lower_expr(ty, value)
  File "<path>/numba/lowering.py", line 729, in lower_expr
    res = self.lower_call(resty, expr)
  File "<path>/numba/lowering.py", line 687, in lower_call
    impl = self.context.get_function(fnty, signature)
  File "<path>/numba/targets/base.py", line 507, in get_func
tion
    return self.get_function(fn, sig, _firstcall=False)
  File "<path>/numba/targets/base.py", line 509, in get_func
tion
    raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
NotImplementedError: No definition for lowering <built-in method kron_impl of _dynfunc._Closure object at 0x7fec26a05e18>(array(
float64, 2d, C), array(float64, 2d, C)) -> array(float64, 2d, C)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<path>lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "<path>lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "foo.py", line 35, in chooser
    fn()
  File "foo.py", line 26, in runner
    return foo(4, 10)
  File "<path>/numba/dispatcher.py", line 307, in _compile_f
or_args
    return self.compile(tuple(argtypes))
  File "<path>/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "<path>/numba/compiler.py", line 740, in compile_extr
a
    return pipeline.compile_extra(func)
  File "<path>/numba/compiler.py", line 360, in compile_extr
a
    return self._compile_bytecode()
  File "<path>/numba/compiler.py", line 699, in _compile_byt
ecode
    return self._compile_core()
  File "<path>/numba/compiler.py", line 686, in _compile_cor
e
    res = pm.run(self.status)
  File "<path>/numba/compiler.py", line 246, in run
    raise patched_exception
  File "<path>/numba/compiler.py", line 238, in run
    stage()
  File "<path>/numba/compiler.py", line 621, in stage_nopyth
on_backend
    self._backend(lowerfn, objectmode=False)
  File "<path>/numba/compiler.py", line 576, in _backend
    lowered = lowerfn()
  File "<path>/numba/compiler.py", line 563, in backend_nopy
thon_mode
    self.flags)
  File "<path>/numba/compiler.py", line 858, in native_lower
ing_stage
    lower.lower()
  File "<path>/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "<path>/numba/lowering.py", line 176, in lower_normal
_function
    entry_block_tail = self.lower_function_body()
  File "<path>/numba/lowering.py", line 201, in lower_functi
on_body
    self.lower_block(block)
  File "<path>/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "<path>lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "<path>/numba/errors.py", line 249, in new_error_cont
ext
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "<path>/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "<path>/numba/errors.py", line 243, in new_error_cont
ext
    yield
  File "<path>/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/lowering.py", line 262, in lower_inst
    val = self.lower_assign(ty, inst)
  File "<path>/numba/lowering.py", line 407, in lower_assign
    return self.lower_expr(ty, value)
  File "<path>/numba/lowering.py", line 729, in lower_expr
    res = self.lower_call(resty, expr)
  File "<path>/numba/lowering.py", line 687, in lower_call
    impl = self.context.get_function(fnty, signature)
  File "<path>/numba/targets/base.py", line 507, in get_func
tion
    return self.get_function(fn, sig, _firstcall=False)
  File "<path>/numba/targets/base.py", line 509, in get_func
tion
    raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
No definition for lowering <built-in method kron_impl of _dynfunc._Closure object at 0x7fec26a05e18>(array(float64, 2d, C), arra
y(float64, 2d, C)) -> array(float64, 2d, C)
File "foo.py", line 22
[1] During: lowering "$80.25 = call $80.22(i, i, func=$80.22, args=[Var(i, foo.py (21)), Var(i, foo.py (21))], kws=(), vararg=No
ne)" at foo.py (22)

thread: thread_2 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_0 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_1 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_2 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_2 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_0 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_1 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_2 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_0 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_2 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_0 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_1 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_1 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_2 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_0 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_1 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_2 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_2 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_0 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_1 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_0 has <function run_guvectorize.<locals>.runner at 0x7fec35db5488>
thread: thread_1 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_2 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_1 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_0 has <function run_vectorize.<locals>.runner at 0x7fec35db5400>
thread: thread_1 has <function run_jit.<locals>.runner at 0x7fec35db5378>
thread: thread_0 has <function run_jit.<locals>.runner at 0x7fec35db5378>
```

**Comment by seibert** [comment]
After all the locking changes since this was opened, I can no longer reproduce this using Numba master + Python 3.6.  Should we close, @sklam?

**Comment by seibert** [comment]
Never mind.  Literally 1 second after the last post, Stuart's reproducer failed twice in a row.  Still a problem.  :(

**Comment by stuartarchibald** [comment]
Guessing... This issue is likely down to initialisation sequences not being threadsafe with various dictionaries/registries that should be in updated atomically currently being written to at different times, this allowing one thread to incorrectly determine that a function is ready for use before another thread has actually installed it. The LLVM threadsafety work would not impact this but may make its occurrence less frequent.

**Comment by stuartarchibald** [comment]
Cannot reproduce this any more. I think it would have been fixed by https://github.com/numba/numba/pull/6948 which pushes the registry initialisation out of the Numba `__init__` sequence!
