### ISSUE TITLE
NotImplementedError - unknown opcode MAKE_FUNCTION

### ISSUE THREAD

**Issue by sandroeiler** [numba/numba#2543]
I got a problem with jit and tried to break down the code to a simple representative piece.
Why does following code not work with jit?
My python version is 3.6.

    import pandas as pd
    from numba import jit
    @jit
    def my_Func ( ):
        df = pd.DataFrame ( { "A": [ 1, 2, 3 ], "B": [ 4, 5, 6 ] } )
        df = df.rename_axis ( lambda x: 2 * x )
        return df
    print ( my_Func ( ) )

I got following runtime error:
```
Traceback (most recent call last):
  File "script.py", line 8, in <module>
    print ( my_Func () )
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 704, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 357, in compile_extra
    return self._compile_bytecode()
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 665, in _compile_bytecode
    return self._compile_core()
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 652, in _compile_core
    res = pm.run(self.status)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 243, in run
    raise patched_exception
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 235, in run
    stage()
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 371, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 767, in translate_stage
    return interp.interpret(bytecode)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/interpreter.py", line 97, in interpret
    self.dfa.run()
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/dataflow.py", line 27, in run
    self.infos[blk.offset] = self.run_on_block(blk)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/dataflow.py", line 71, in run_on_block
    self.dispatch(info, inst)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/dataflow.py", line 81, in dispatch
    fn(info, inst)
  File "/home/usaaa/anaconda3/lib/python3.6/site-packages/numba/dataflow.py", line 86, in handle_unknown_opcode
    self.bytecode.func_id.filename))
NotImplementedError: Failed at object (analyzing bytecode)
Use of unknown opcode MAKE_FUNCTION at line 6 of script.py
```

**Comment by sandroeiler** [comment]
Is it possible that this is related to problems noted here?
https://pandas.pydata.org/pandas-docs/stable/enhancingperf.html#using-numba

> Note: As of numba version 0.20, pandas objects cannot be passed directly to numba-compiled functions. Instead, one must pass the numpy array underlying the pandas object to the numba-compiled function as demonstrated below.

**Comment by seibert** [comment]
Yes, the general problem is that Numba does not work directly with Pandas dataframe objects.   (The specific bug you hit is related to limitations in our support for lambda functions.)

**Comment by seibert** [comment]
Closing because Pandas support is unlikely until Pandas 2.0.
