### ISSUE TITLE
@njit(parallel=True) fails to compile when @njit(parallel=False) works. v0.35

### ISSUE THREAD

**Issue by Minimata** [numba/numba#2545]
Hello everyone.

This is a possible duplicate of #2512 . 

## The issue
Some function decorated with `@njit` is working with arrays. The thing is, when we (@sambarluc and I) enable parallel compilation, the same function fails to compile and produces an index out of range exception. This only happens on version 0.35, version 0.34 works fine with `parallel=True`.

As this is a possible duplicate of #2512 , this might be already fixed by #2492 . I can't be sure of this though, and we didn't apply the patch ourselves, all we did was `conda upgrade` and the issue's still here. So either the patch's not up on conda yet, either it doesn't fix this issue.

## The configuration
I don't know if any of this is actually useful (except for the numba version) but I still put it here because it doesn't hurt :
* Ubuntu 16.04.3
* Python 3.6.2
* **numba 0.35.0**
* numpy 1.13.1

## The technical stuff
I changed the functions a bit to remove what is should be useless to show here, so just essential stuff is present. As I might be mistaken and remove some meaningful code needed to resolve this issue, I'll upload the full code afterwards if needed.

```
    # a vanilla python function in file particleContainer.py

    def run(self, iters, timestamps_in, seed_ctx):
        active_ids = np.zeros(self.ntact, dtype="short")
        out_code = np.zeros(self.ntact, dtype="short")

        xyz = np.zeros((0, 3), dtype="float64")
        ijk = np.zeros((0, 3), dtype="int16")

        self.nvals = seed_ctx.nvals
        out_tijk = np.zeros((self.ntact, self.nvals, 4),
                            dtype="f8")
        out_xyz = np.zeros((self.ntact, self.nvals, 3),
                           dtype="f8")

        for ngi in range(1, iters.size):

            # stuff

            self.ntout += n_remove
            self.ntact = active_ids.size

            # stuff

            ext_loop(self.nvals, self.ntact,
                     xyz, ijk, out_xyz, out_tijk, out_code)
```

```
# In file CFunctions.py

@nb.njit(nogil=True, parallel=True)
def ext_loop(nvals, ntact, xyz, ijk, out_xyz, out_tijk, out_code):
    for ntrac in range(ntact):
        # initialize stuff
        ts = 0.0
        tt = 0.0 

        # output init
        for kk in range(nvals):
            out_tijk[ntrac, kk, 0] = -1e20

        rec_out = 0

        x1 = xyz[ntrac, 0]
        y1 = xyz[ntrac, 1]
        z1 = xyz[ntrac, 2]
        ib = ijk[ntrac, 0]
        jb = ijk[ntrac, 1]
        kb = ijk[ntrac, 2]

        while True:

            # lots of stuff

            out_tijk[ntrac, rec_out, 0] = tt  # Triggers the compile exception
            out_tijk[ntrac, rec_out, 1] = x1
            out_tijk[ntrac, rec_out, 2] = y1
            out_tijk[ntrac, rec_out, 3] = z1
```

The error appears like this, with all the stacktrace :
```
Traceback (most recent call last):
  File "/.../main.py", line 6, in <module>
    c.run()
  File "/.../controller.py", line 479, in run
    self._part_container.run(self.iters, self.timestamps_in, seed_ctx)
  File "/.../particleContainer.py", line 211, in run
    uflux, vflux, wflux, out_code)
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 330, in _compile_for_args
    raise e
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 722, in _compile_bytecode
    return self._compile_core()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 709, in _compile_core
    res = pm.run(self.status)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 452, in stage_nopython_frontend
    self.locals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 865, in type_inference_stage
    infer.propagate()
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 844, in propagate
    raise errors[0]
numba.errors.TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7f61740fb080>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File "/.../miniconda/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 415, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 441, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args, literals=literals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 1113, in resolve_call
    literals=literals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/typing/context.py", line 202, in resolve_function_type
    return func.get_call_type_with_literals(self, args, kws, literals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/types/abstract.py", line 266, in get_call_type_with_literals
    return self.get_call_type(context, args, kws)
  File "/.../miniconda/lib/python3.6/site-packages/numba/types/functions.py", line 175, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 269, in get_call_template
    self.compile(tuple(args))
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 722, in _compile_bytecode
    return self._compile_core()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 709, in _compile_core
    res = pm.run(self.status)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 494, in stage_parfor_pass
    parfor_pass.run()
  File "/.../miniconda/lib/python3.6/site-packages/numba/parfor.py", line 197, in run
    self.array_analysis.run()
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 604, in run
    pre, post = self._analyze_inst(label, scope, equiv_set, inst)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 629, in _analyze_inst
    result = self._analyze_expr(scope, equiv_set, inst.value)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 727, in _analyze_expr
    return guard(fn, scope, equiv_set, expr)
  File "/.../miniconda/lib/python3.6/site-packages/numba/ir_utils.py", line 1159, in guard
    return func(*args, **kwargs)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 754, in _analyze_op_static_getitem
    shape = equiv_set.get_shape(var)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 432, in get_shape
    return tuple(self.ind_to_var[i][0] for i in inds)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 432, in <genexpr>
    return tuple(self.ind_to_var[i][0] for i in inds)
IndexError: Failed at nopython (convert to parfors)
list index out of range
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 415, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/.../miniconda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/.../miniconda/lib/python3.6/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "/.../miniconda/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/.../miniconda/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 415, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 441, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args, literals=literals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/typeinfer.py", line 1113, in resolve_call
    literals=literals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/typing/context.py", line 202, in resolve_function_type
    return func.get_call_type_with_literals(self, args, kws, literals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/types/abstract.py", line 266, in get_call_type_with_literals
    return self.get_call_type(context, args, kws)
  File "/.../miniconda/lib/python3.6/site-packages/numba/types/functions.py", line 175, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 269, in get_call_template
    self.compile(tuple(args))
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "/.../miniconda/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 722, in _compile_bytecode
    return self._compile_core()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 709, in _compile_core
    res = pm.run(self.status)
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "/.../miniconda/lib/python3.6/site-packages/numba/compiler.py", line 494, in stage_parfor_pass
    parfor_pass.run()
  File "/.../miniconda/lib/python3.6/site-packages/numba/parfor.py", line 197, in run
    self.array_analysis.run()
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 604, in run
    pre, post = self._analyze_inst(label, scope, equiv_set, inst)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 629, in _analyze_inst
    result = self._analyze_expr(scope, equiv_set, inst.value)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 727, in _analyze_expr
    return guard(fn, scope, equiv_set, expr)
  File "/.../miniconda/lib/python3.6/site-packages/numba/ir_utils.py", line 1159, in guard
    return func(*args, **kwargs)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 754, in _analyze_op_static_getitem
    shape = equiv_set.get_shape(var)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 432, in get_shape
    return tuple(self.ind_to_var[i][0] for i in inds)
  File "/.../miniconda/lib/python3.6/site-packages/numba/array_analysis.py", line 432, in <genexpr>
    return tuple(self.ind_to_var[i][0] for i in inds)
numba.errors.InternalError: Failed at nopython (convert to parfors)
list index out of range
[1] During: resolving callee type: type(CPUDispatcher(<function output_to_3d_array at 0x7f6183bec6a8>))
[2] During: typing of call at /.../CFunctions.py (588)
--%<-----------------------------------------------------------------
File "/.../CFunctions.py", line 588
```

As I said, compiling from numba version 0.34.0 works fine. 
Also, replacing 
```
@nb.njit(nogil=True, parallel=True)
def ext_loop(nvals, ntact, xyz, ijk, out_xyz, out_tijk, out_code):
```
with
```
@nb.njit(nogil=True, parallel=False)
def ext_loop(nvals, ntact, xyz, ijk, out_xyz, out_tijk, out_code):
```
works fine too (even though we loose parallelism ofc, but it compiles).

So is this issue familiar to any contributor here ? Is this a known issue and I'm just another duplicate that didn't look far enough (like so many do) ? If there's already a patch for that, when will it be made available on `conda` ?

Thanks anyway for your time, and your work (numba has been quite astonishing to work with, so good job :+1: ).

**Comment by stuartarchibald** [comment]
Thanks for the report. Fairly sure the fix for https://github.com/numba/numba/issues/2512 was in the 0.35 release. You can always try Numba from the `numba` channel to get the absolute latest dev version if you are ever unsure (use `-c numba`).

As to the report, I can't reproduce the error you see. I've tried putting in false data/information into various places but that doesn't seem sufficient. I have found another bug as a result of doing this, but not the one you report. Any chance you could create a minimal working reproducer please including the data (correctly typed but small is all that's needed) and we'll take a look? Thanks.

**Comment by Minimata** [comment]
Well if the #2512 fix was in the 0.35 release then it didn't fix our issue (or generated it maybe) meaning it's not a duplicate. So that's nice.
We'll try to make the smallest full working program that generates the error and share it with you when finished.

Thanks for the quick answer =)

**Comment by stuartarchibald** [comment]
That'd be great thanks. I am suspicious it's the same as or related to this https://github.com/numba/numba/issues/2537 which is fixed in mainline.
