### ISSUE TITLE
liveness analysis failure

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2546]
This somewhat nonsensical sample fails liveness analysis, as a minimum the error message could perhaps be improved?
```python
from numba import njit
import numpy as np

@njit
def foo(x):
    for k in range(10):
        y = 0
        while True:
            x[0] = y

foo(np.zeros(10))
```
backtrace:
```python
$ python foo.py 
Traceback (most recent call last):
  File "foo.py", line 11, in <module>
    foo(np.zeros(10))
  File "<path>/lib/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<path>/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 763, in compile_extra
    return pipeline.compile_extra(func)
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 360, in compile_extra
    return self._compile_bytecode()
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 722, in _compile_bytecode
    return self._compile_core()
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 709, in _compile_core
    res = pm.run(self.status)
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    raise patched_exception
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 238, in run
    stage()
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 390, in stage_process_ir
    ir_processing_stage(self.func_ir)
  File "<path>/lib/python3.6/site-packages/numba/compiler.py", line 832, in ir_processing_stage
    post_proc.run()
  File "<path>/lib/python3.6/site-packages/numba/postproc.py", line 83, in run
    self._insert_var_dels()
  File "<path>/lib/python3.6/site-packages/numba/postproc.py", line 171, in _insert_var_dels
    self._patch_var_dels(vlt.deadmaps.internal, vlt.deadmaps.escaping)
  File "<path>/lib/python3.6/site-packages/numba/utils.py", line 283, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "<path>/lib/python3.6/site-packages/numba/postproc.py", line 56, in deadmaps
    self.usedefs.defmap)
  File "<path>/lib/python3.6/site-packages/numba/analysis.py", line 150, in compute_dead_maps
    raise RuntimeError(msg)
RuntimeError: Failed at nopython (processing IR)
liveness info missing for vars: {'y'}
```

**Comment by stuartarchibald** [comment]
Probably UB related.
