### ISSUE TITLE
Unable to use nopython mode with np.arange

### ISSUE THREAD

**Issue by HagaiHargil** [numba/numba#2557]
Hi,

I wish to use this amazing library to speed up the performance of one of my functions. So far it's been going great, but I ran into an issue today when trying to use [`np.arange`.](https://docs.scipy.org/doc/numpy-1.13.0/reference/generated/numpy.arange.html)

Namely, this function definition refuses to "compile" - i.e. I can't define it in IPython or Jupyter:
```python
@jit(int64[:](int64, int64, int64), nopython=True)
def a(start, stop, step):
    arr = np.arange(start=start, stop=stop, step=step, dtype=np.int64)
    return arr
```
If I drop the type hints in the `@jit` decorator I'm able to define the function, but I can't use it. The error message is the same in both cases:

```
Traceback (most recent call last):
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typeinfer.py", line 415, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\errors.py", line 259, in new_error_context
    yield
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typeinfer.py", line 415, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typeinfer.py", line 441, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args, literals=literals)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typeinfer.py", line 1113, in resolve_call
    literals=literals)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typing\context.py", line 202, in resolve_function_type
    return func.get_call_type_with_literals(self, args, kws, literals)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\types\functions.py", line 59, in get_call_type_with_literals
    sig = temp.apply(args, kws)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typing\templates.py", line 207, in apply
    sig = generic(args, kws)
  File "C:\Users\Hagai\Miniconda3\envs\py36pysight\lib\site-packages\numba\typing\npydecl.py", line 616, in generic
    assert not kws
numba.errors.InternalError: 
[1] During: resolving callee type: Function(<built-in function arange>)
[2] During: typing of call at <ipython-input-6-89f9e828188c> (3)
```

I'm using numba version `np113py36_10`. 
Thanks!

**Comment by MSeifert04** [comment]
That should work if you just use it as positional argument: `np.arange(start, stop, step, np.int64)`.

**Comment by HagaiHargil** [comment]
Indeed it does. I thought Numba supported function keyword arguments...

Thanks!
