### ISSUE TITLE
Array comprehension with constant range

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#2564]
Array comprehension fails if the range stop is constant.

```python
from numba import jit
import numpy as np

@jit(nopython=True)
def f():
    return np.array([ [ x * y for x in range(4) ] for y in range(3) ])

f()
```

```
Traceback (most recent call last):
  File "/home/etotoni/pse-hpc/python/numba/numba/errors.py", line 259, in new_error_context
    yield
  File "/home/etotoni/pse-hpc/python/numba/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/home/etotoni/pse-hpc/python/numba/numba/lowering.py", line 265, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/etotoni/pse-hpc/python/numba/numba/lowering.py", line 411, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/etotoni/pse-hpc/python/numba/numba/lowering.py", line 862, in lower_expr
    itemvals = [self.loadvar(i.name) for i in expr.items]
  File "/home/etotoni/pse-hpc/python/numba/numba/lowering.py", line 862, in <listcomp>
    itemvals = [self.loadvar(i.name) for i in expr.items]
  File "/home/etotoni/pse-hpc/python/numba/numba/lowering.py", line 920, in loadvar
    ptr = self.getvar(name)
  File "/home/etotoni/pse-hpc/python/numba/numba/lowering.py", line 914, in getvar
    return self.varmap[name]
KeyError: '$const6.8.20'
```

**Comment by ehsantn** [comment]
ping @ninegua .

**Comment by seibert** [comment]
Closing since this was fixed in a PR.
