### ISSUE TITLE
Opaque error message on array argument with non-native byte order

### ISSUE THREAD

**Issue by aothms** [numba/numba#2593]
I understand that non-native byte order arrays can or should not be accepted as arguments to functions compiled with numba.jit. However the current error message when doing so is not as informative as it can be in my opinion. See the following interactive session.

~~~py
>>> import numpy, numba
>>> a = numpy.arange(1, dtype=float)
>>> b = a.newbyteorder()
>>> a.dtype.byteorder
'='
>>> b.dtype.byteorder
'>'
>>> @numba.jit(numba.void(numba.float64[:]))
... def f(v): pass
...
>>> f(a)
>>> f(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Conda\lib\site-packages\numba\dispatcher.py", line 399, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) pyobject
~~~

The type **pyobject** is obviously very generic here and rather confusing, especially since numpy itself is quite cool with mixing byte orders. For example in the `repr()` output of the arrays nothing about byte order is included.

~~~py
>>> repr(a)
'array([ 0.])'
>>> repr(b)
'array([ 0.])'
~~~

Also note that in the `typeof` call stack this is actually asserted properly, but the message gets silenced somewhere.

~~~py
>>> numba.typing.typeof.typeof(b)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Conda\lib\site-packages\numba\typing\typeof.py", line 28, in typeof
    ty = typeof_impl(val, c)
  File "C:\Conda\lib\site-packages\singledispatch.py", line 210, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "C:\Conda\lib\site-packages\numba\typing\typeof.py", line 195, in _typeo_ndarray
    raise ValueError("Unsupported array dtype: %s" % (val.dtype,))
ValueError: Unsupported array dtype: >f8
~~~

**Comment by stuartarchibald** [comment]
Thanks for the report. I believe what you are seeing is valid behaviour. Upfront declaring that the function will have a given signature means it forgoes the ability to compile new signatures on the fly. As a result anything that doesn't match the provided signature will be rejected, I believe these are simply matching errors and not a matter of "support" (although you are right about byte order support). For example:
```
f(10)
```
gives:
```python
TypeError: No matching definition for argument type(s) int64
```
The compiler recognises `10` as an `int64` type and so can state that matching is invalid using the type information it has derived in the message. Whereas:
```python
class bar:
    pass
f(bar)
```
gives:
```
TypeError: No matching definition for argument type(s) pyobject
```
as the compiler has no idea what a `bar` is. This is similar to the case presented above in that the compiler tries to see the type of the variable, and a `ValueError` is raised as it doesn't know, but the foremost problem is that it can't match it to the given signature. This probably needs a chained exception so that it is noted that the `TypeError` is caused by the `ValueError`, however this may be easier said than done as I'm fairly sure at present part of the `no python mode -> object mode` fallback relies on `PyObjects` being identified in an exception free manner.
