### ISSUE TITLE
Function caching fails with KeyError

### ISSUE THREAD

**Issue by maacruz** [numba/numba#2675]
Using the last numba release 0.36.1 (installed through miniconda on linux)
In this test case, the first function fails when caching is enabled, all of them work when caching is disabled
This used to work fine a few versions ago
```python
import numpy as np
import numba


@numba.jit(cache=True)
def pass1(x, y, z):
    d2 = x**2
    d3 = y**2
    i = ((d2<=d3) & (x<z))
    return 1

@numba.jit(cache=True)
def pass2(x, y, z):
    d2 = x**2
    i = ((d2<=y**2))
    return 1

@numba.jit(cache=True)
def fail(x, y, z):
    d2 = x**2
    i = ((d2<=y**2) & (x<z))
    return 1

x = np.array([0, 0.5, 2])
y = 1.5
z = 3

print pass1(x, y, z)
print pass2(x, y, z)
print fail(x, y, z)
```

```text
$ python numba_fail.py 
1
1
Traceback (most recent call last):
  File "numba_fail.py", line 30, in <module>
    print fail(x, y, z)
  File "~/.local/lib/python2.7/site-packages/numba/dispatcher.py", line 281, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "~/.local/lib/python2.7/site-packages/numba/dispatcher.py", line 529, in compile
    self._cache.save_overload(sig, cres)
  File "~/.local/lib/python2.7/site-packages/numba/caching.py", line 384, in save_overload
    self._save_data(data_name, cres)
  File "~/.local/lib/python2.7/site-packages/numba/caching.py", line 481, in _save_data
    data = cres._reduce()
  File "~/.local/lib/python2.7/site-packages/numba/compiler.py", line 73, in _reduce
    typeann = str(self.type_annotation)
  File "~/.local/lib/python2.7/site-packages/numba/annotations/type_annotations.py", line 260, in __str__
    return self.annotate()
  File "~/.local/lib/python2.7/site-packages/numba/annotations/type_annotations.py", line 121, in annotate
    groupedinst = self.prepare_annotations()
  File "~/.local/lib/python2.7/site-packages/numba/annotations/type_annotations.py", line 105, in prepare_annotations
    atype = self.typemap[inst.target.name]
KeyError: '_0_7'
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can't seem to be able to replicate what you see:

```
$ conda create -n numba_0361_py27 numba=0.36.1 python=2.7 -q -y

Package plan for installation in environment <path>/anaconda3/envs/numba_10361_py27:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-h1d4fec5_0     
    certifi:         2017.11.5-py27h71e7faf_0  
    enum34:          1.1.6-py27h99a27e9_1      
    funcsigs:        1.0.2-py27h83f16ab_0      
    intel-openmp:    2018.0.0-hc7b2577_8       
    libedit:         3.1-heed3624_0            
    libffi:          3.2.1-hd88cf55_4          
    libgcc-ng:       7.2.0-h7cc24e2_2          
    libstdcxx-ng:    7.2.0-h7a57d05_2          
    llvmlite:        0.21.0-py27h6dad3f9_0     
    mkl:             2018.0.1-h19d6760_4       
    ncurses:         6.0-h9df7e31_2            
    numba:           0.36.1-np113py27hee5a248_0
    numpy:           1.13.3-py27hbcc08e0_0     
    openssl:         1.0.2n-hb7f436b_0         
    pip:             9.0.1-py27ha730c48_4      
    python:          2.7.14-h1571d57_29        
    readline:        7.0-ha6073c6_4            
    setuptools:      36.5.0-py27h68b189e_0     
    singledispatch:  3.4.0.3-py27h9bcb476_0    
    six:             1.11.0-py27h5f960f1_1     
    sqlite:          3.20.1-hb898158_2         
    tk:              8.6.7-hc745277_3          
    wheel:           0.30.0-py27h2bc6bb2_1     
    zlib:            1.2.11-ha838bed_2         

$ cat issue2675.py 
import numpy as np
import numba


@numba.jit(cache=True)
def pass1(x, y, z):
    d2 = x**2
    d3 = y**2
    i = ((d2<=d3) & (x<z))
    return 1

@numba.jit(cache=True)
def pass2(x, y, z):
    d2 = x**2
    i = ((d2<=y**2))
    return 1

@numba.jit(cache=True)
def fail(x, y, z):
    d2 = x**2
    i = ((d2<=y**2) & (x<z))
    return 1

x = np.array([0, 0.5, 2])
y = 1.5
z = 3

print(pass1(x, y, z))
print(pass2(x, y, z))
print(fail(x, y, z))

$ source activate numba_0361_py27

(numba_0361_py27) 
$ python issue2675.py 
1
1                                                                                                                               
1                                                                                                                               

(numba_0361_py27)                                                                                                               
$ python issue2675.py                                                                                                           
1                                                                                                                               
1                                                                                                                               
1                                                                                                                               

(numba_0361_py27)                                                                                                               
$ python issue2675.py                                                                                                           
1                                                                                                                               
1                                                                                                                               
1                                                                                                                               
```

Perhaps your cache state is somehow invalid, `__pycache__` usually contains the function cache, but it may be in a user-wide dir under certain conditions (docs below). So perhaps try clearing the cache of `*.nbi` and `*.nbc` (index and data files respectively)?

> If true, cache enables a file-based cache to shorten compilation times when the function was already compiled in a previous invocation. The cache is maintained in the `__pycache__` subdirectory of the directory containing the source file; if the current user is not allowed to write to it, though, it falls back to a platform-specific user-wide cache directory (such as $HOME/.cache/numba on Unix platforms).

**Comment by maacruz** [comment]
Thank you very much for your answer.
After further testing it seems there is some weird interaction with my user scheme installed python packages (pip install --user) outside conda.
Removing old packages from ~/.local/lib/python2.7/site-packages solved the issue.
