### ISSUE TITLE
reproducible error with numpy import when profiling

### ISSUE THREAD

**Issue by tachim** [numba/numba#2717]
Hello,
Consider the following code:

```python
@numba.jit()
def a():
    v = 3
    foo = {}
    arr = np.arange(v)
    np.random.shuffle(arr)
    return arr
```

If this is run as follows: `python -m profile -o foo.txt test.py` it throws the following exception:

```
Traceback (most recent call last):
  File "/home/tudor/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/tudor/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tudor/anaconda3/lib/python3.6/profile.py", line 589, in <module>
    main()
  File "/home/tudor/anaconda3/lib/python3.6/profile.py", line 582, in main
    runctx(code, globs, None, options.outfile, options.sort)
  File "/home/tudor/anaconda3/lib/python3.6/profile.py", line 101, in runctx
    return _Utils(Profile).runctx(statement, globals, locals, filename, sort)
  File "/home/tudor/anaconda3/lib/python3.6/profile.py", line 64, in runctx
    prof.runctx(statement, globals, locals)
  File "/home/tudor/anaconda3/lib/python3.6/profile.py", line 424, in runctx
    exec(cmd, globals, locals)
  File "test.py", line 12, in <module>
    print(a())
NameError: global name 'np' is not defined
```

However if one removes the variable assignment to `foo` as follows:

```python
@numba.jit()
def a():
    v = 3
    arr = np.arange(v)
    np.random.shuffle(arr)
    return arr
```

then the program runs successfully.

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. I wonder if it is related to this https://github.com/numba/numba/issues/2456.

**Comment by ARF1** [comment]
@stuartarchibald I stumbled across this issue as well. I could however not modify my function to side-step the issue. Is there a work-around available to allow profiling?

**Comment by stuartarchibald** [comment]
@ARF1 not that I know of I'm afraid.

For anyone revisiting this, the issue only occurs in functions that are forcibly compiled in `objectmode` or have fallen back to `objectmode`.

**Comment by stuartarchibald** [comment]
As of mainline for upcoming 0.55. This:
```python
import numba
import numpy as np

@numba.jit(forceobj=True)
def a():
    v = 3
    foo = {}
    arr = np.arange(v)
    np.random.shuffle(arr)
    return arr

a()
```
produces:
```
  File "issue2717.py", line 12, in <module>
    a()
SystemError: CPUDispatcher(<function a at 0x7f1a3e315dc0>) returned NULL without setting an error
```
when run under profiling.
