### ISSUE TITLE
Problems with PYCC on windows

### ISSUE THREAD

**Issue by sklam** [numba/numba#272]
```traceback
Microsoft (R) Incremental Linker Version 9.00.21022.08
Copyright (C) Microsoft Corporation. All rights reserved.

LINK : warning LNK4044: нераспознанный параметр "/o"; игнорируется
LINK : fatal error LNK1181: не удается открыть входной файл "4.dll"
Traceback (most recent call last):
File "C:\Anaconda\Scripts\pycc-script.py", line 5, in <module>
sys.exit(main())
File "C:\Anaconda\lib\site-packages\numba\pycc\__init__.py", line 79, in
main
subprocess.check_call(cmdargs)
File "C:\Anaconda\lib\subprocess.py", line 542, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '('link.exe', '/dll', '-o', '4.dll',
'c:\
\users\\username\\appdata\\local\\temp\\4.dll.o')' returned non-zero exit
status
1181
```

Translation:
```
LINK: warning LNK4044: unrecognized option "/ o"; ignored
LINK: fatal error LNK1181: can not open input file "4.dll"
```

**Comment by pitrou** [comment]
I'm closing since pycc has been reworked and the tests pass on Windows (when a heisenbug doesn't kick in :-/).
