### ISSUE TITLE
prange fails to reuse accumulator for reduction

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2759]
This:
```python
import numpy as np
from numba import njit, prange

def foo(n):
    acc = 0
    for i in prange(n):
        acc += i;
    for i in prange(n):
        acc += i;
    return acc

d1 = njit(parallel=True)(foo)
r = d1(5)
```
produces:
```python
Parallel for-loop #0 is produced from pattern '('prange', 'user')' at test_argmax.py (6)
Parallel for-loop #1 is produced from pattern '('prange', 'user')' at test_argmax.py (8)
After fusion, function foo has 2 parallel for-loop(s) #{0, 1}.
Traceback (most recent call last):
  File "<path>/numba/numba/errors.py", line 259, in new_error_context
    yield
  File "<path>/numba/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/numba/lowering.py", line 365, in lower_inst
    func(self, inst)
  File "<path>/numba/numba/npyufunc/parfor.py", line 77, in _lower_parfor_parallel
    lowerer, parfor, typemap, typingctx, targetctx, flags, {}, bool(alias_map))
  File "<path>/numba/numba/npyufunc/parfor.py", line 358, in _create_gufunc_for_parfor_body
    typemap[arr] = types.npytypes.Array(typemap[var], 1, "C")
  File "<path>/numba/numba/utils.py", line 261, in __setitem__
    raise AssertionError("key already in dictionary: %r" % (key,))
AssertionError: key already in dictionary: 'acc_arr'
```
as a guess, the `acc_arr` is array to hold the per thread accumulators for `acc` in each `prange` and it's being redefined in the second parfor.

Ping. @ehsantn @DrTodd13

**Comment by stuartarchibald** [comment]
Fixed by https://github.com/numba/numba/pull/3142, closing.
