### ISSUE TITLE
InternalError when performing augmented assignment of a unsigned int multidimensional array if addressing the array by only one index

### ISSUE THREAD

**Issue by krrk** [numba/numba#2784]
A string of errors is produced if you try the following code against the latest numba git. First a TypingError then while that is being raised an AttributeError occurs.

```python
@jit(nopython=True)
def foo():
    bar = np.ones((4,1), dtype=np.uint64)
    bar[0] += 1
```

The code above will raise errors for any of the unsigned integer types (uint8, uint16, uint32, uint64), but it doesn't happen for the signed integer types or for float type. You can get around the error in the above simplified code by replacing `bar[0] += 1` with either `bar[0,0] += 1` or `bar[0] = bar[0] + 1`. This is also a problem with the `-=` operator.

Here is the full traceback:
```python
Traceback (most recent call last):
  File "test-numba.py", line 9, in <module>
    foo()
  File ".../numba-git/lib/python3.6/site-packages/numba/dispatcher.py", line 330, in _compile_for_args
    raise e
  File ".../numba-git/lib/python3.6/site-packages/numba/dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File ".../numba-git/lib/python3.6/site-packages/numba/dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File ".../numba-git/lib/python3.6/site-packages/numba/dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 779, in compile_extra
    return pipeline.compile_extra(func)
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 738, in _compile_bytecode
    return self._compile_core()
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 725, in _compile_core
    res = pm.run(self.status)
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 248, in run
    raise patched_exception
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 240, in run
    stage()
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 454, in stage_nopython_frontend
    self.locals)
  File ".../numba-git/lib/python3.6/site-packages/numba/compiler.py", line 881, in type_inference_stage
    infer.propagate()
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 846, in propagate
    raise errors[0]
numba.errors.TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.IntrinsicCallConstraint object at 0x7fc8fa8205c0>:
--%<-----------------------------------------------------------------
Traceback (most recent call last):
  File ".../numba-git/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 503, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 441, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args, literals=literals)
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 1123, in resolve_call
    literals=literals)
  File ".../numba-git/lib/python3.6/site-packages/numba/typing/context.py", line 191, in resolve_function_type
    res = defn.apply(args, kws)
  File ".../numba-git/lib/python3.6/site-packages/numba/typing/templates.py", line 207, in apply
    sig = generic(args, kws)
  File ".../numba-git/lib/python3.6/site-packages/numba/typing/npydecl.py", line 236, in generic
    assert len(sig.args) == 3
AttributeError: 'NoneType' object has no attribute 'args'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 503, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File ".../numba-git/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File ".../numba-git/lib/python3.6/site-packages/numba/errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File ".../numba-git/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File ".../numba-git/lib/python3.6/site-packages/numba/errors.py", line 259, in new_error_context
    yield
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 503, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 441, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args, literals=literals)
  File ".../numba-git/lib/python3.6/site-packages/numba/typeinfer.py", line 1123, in resolve_call
    literals=literals)
  File ".../numba-git/lib/python3.6/site-packages/numba/typing/context.py", line 191, in resolve_function_type
    res = defn.apply(args, kws)
  File ".../numba-git/lib/python3.6/site-packages/numba/typing/templates.py", line 207, in apply
    sig = generic(args, kws)
  File ".../numba-git/lib/python3.6/site-packages/numba/typing/npydecl.py", line 236, in generic
    assert len(sig.args) == 3
numba.errors.InternalError: 'NoneType' object has no attribute 'args'
[1] During: typing of intrinsic-call at test-numba.py (7)
--%<-----------------------------------------------------------------

File "test-numba.py", line 7
```

**Comment by krrk** [comment]
Note also that these errors do not occur in object mode.

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. I suspect that this is because inplace operations are typed like `type(X) op type(Y) -> type(X)`, i.e. typed as if an explicit output type is given. In the case above this means a `uint64 + int64 -> uint64` which is invalid as a `uint64` cannot hold the signed part of the `int64`. This usually triggers type conversion of the output to `float` but because of the explicit type resolution it fails (also the reason why the `bar[0] = bar[0] + 1` works, less strict typing). Either way, the error message ought to be better and quite possibly `bar[0] += 1` ought to type infer like `bar[0] = bar[0] + 1`.
