### ISSUE TITLE
@guvectorize not accepting new size variable (i.e. () -> (n)) in output argument

### ISSUE THREAD

**Issue by Rik-de-Kort** [numba/numba#2797]
MnWE:
````python
from numba import guvectorize


@guvectorize("int64, int64[:]", "() -> (n)")
def result(x, res):
    for i in range(3):
        res[i] = x


if __name__ == "__main__":
    print(result(3))
````

Yields the following error:
````python
Traceback (most recent call last):
  File "C:/Users/User/Documents/numba_playground/guvectorize_test.py", line 4, in <module>
    @guvectorize("int64, int64[:]", "() -> (n)")
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\npyufunc\decorators.py", line 177, in wrap
    guvec = GUVectorize(func, signature, **kws)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\npyufunc\decorators.py", line 50, in __new__
    targetoptions=kws)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 278, in __init__
    self.sin, self.sout = parse_signature(signature)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\npyufunc\sigparse.py", line 63, in parse_signature
    raise NameError('undefined output symbols: %s' % ','.join(sorted(diff)))
NameError: undefined output symbols: n
````

Related to this discussion from 2016: https://groups.google.com/a/continuum.io/forum/#!topic/numba-users/tjkxRHj4x4k

Workaround there is to pass a dummy output array, like so:
````python
@guvectorize("int64, int64[:], int64[:]", "(), (n) -> (n)")
def result2(x, dum, res):
    for i in range(dum.shape[0]):
        res[i] = x
````

**Comment by rabernat** [comment]
I just hit this issue. I would like to write a guvectorize'd function that returns an output of different size from the input. Is this possible?

**Comment by s-m-e** [comment]
Joining the club, just hit this issue - (still) present in all pipelines, i.e. targets `cpu`, `parallel`, `cuda`.

**Comment by ricardoV94** [comment]
> Does NumPy allow new size variables in output arguments for Generalized UFuncs?

I think so?
