### ISSUE TITLE
Extensibletype's test_perfecthashing sometimes fails

### ISSUE THREAD

**Issue by eltjpm** [numba/numba#281]
There's a rare failure of perfecthashing unit test that showed up a few times in our CI builds. The error message can be slightly different, but I suspect the cause is the same. To reproduce:

```
$ for i in `seq 1000`; do python test_perfecthashing.py || break; done

test_methodtable (__main__.TestInterning) ...
1 table building took 0.000236988067627 seconds.
101 table building took 0.00116181373596 seconds.
201 table building took 0.00199198722839 seconds.
301 table building took 0.00313305854797 seconds.
401 table building took 0.00398087501526 seconds.
501 table building took 0.00597405433655 seconds.
601 table building took 0.00692415237427 seconds.
701 table building took 0.00718903541565 seconds.
801 table building took 0.00795102119446 seconds.
901 table building took 0.0124530792236 seconds.
1001 table building took 0.0133080482483 seconds.
1101 table building took 0.0155501365662 seconds.
1201 table building took 0.0147659778595 seconds.
1301 table building took 0.0160248279572 seconds.
1401 table building took 0.0165131092072 seconds.
1501 table building took 0.0170249938965 seconds.
1601 table building took 0.017324924469 seconds.
1701 table building took 0.0172760486603 seconds.
1801 table building took 0.0175180435181 seconds.
1901 table building took 0.0176138877869 seconds.
2001 table building took 0.0380890369415 seconds.
2101 table building took 0.0419509410858 seconds.
2201 table building took 0.0426738262177 seconds.
Error: No suitable table found
ERROR

======================================================================
ERROR: test_methodtable (__main__.TestInterning)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_perfecthashing.py", line 71, in test_methodtable
    build_and_verify_methodtable(ids[:i], flags[:i], funcs[:i])
  File "test_perfecthashing.py", line 22, in build_and_verify_methodtable
    table.generate_table(len(ids), ids, flags, funcs)
  File "methodtable.pyx", line 130, in extensibletype.methodtable.PerfectHashMethodTable.generate_table (build/objs/athena/src/numba/deps/pyextensibletype/extensibletype/methodtable.c:2682)
HashingError: Unable to create perfect hash table for table: PerfectHashMethodTable(
<snip>
```

**Comment by pitrou** [comment]
This issue is obsolete as Extensibletype doesn't exist anymore, closing.
