### ISSUE TITLE
CUDA SELP patch is failing tests

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2845]
On the farm, CUDA version and OS invariant fail of conda build of master branch since PR: https://github.com/numba/numba/pull/2835

Traceback is:
```
======================================================================
ERROR: test_selp (numba.cuda.tests.cudapy.test_intrinsics.TestCudaIntrinsic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/tests/cudapy/test_intrinsics.py", line 164, in test_selp
    branching_with_selps[n, 1](a, b, c)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 702, in __call__
    kernel = self.specialize(*args)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 713, in specialize
    kernel = self.compile(argtypes)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 728, in compile
    **self.targetoptions)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 36, in core
    return fn(*args, **kwargs)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 75, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 36, in core
    return fn(*args, **kwargs)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/compiler.py", line 64, in compile_cuda
    locals={})
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 780, in compile_extra
    return pipeline.compile_extra(func)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 363, in compile_extra
    return self._compile_bytecode()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 739, in _compile_bytecode
    return self._compile_core()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 726, in _compile_core
    res = pm.run(self.status)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 249, in run
    raise patched_exception
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 241, in run
    stage()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 455, in stage_nopython_frontend
    self.locals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/compiler.py", line 882, in type_inference_stage
    infer.propagate()
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 846, in propagate
    raise errors[0]
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 137, in propagate
    constraint(typeinfer)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 415, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 441, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args, literals=literals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typeinfer.py", line 1123, in resolve_call
    literals=literals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/typing/context.py", line 204, in resolve_function_type
    return func.get_call_type_with_literals(self, args, kws, literals)
  File "/opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/types/functions.py", line 137, in get_call_type_with_literals
    raise errors.TypingError(failures.format())
numba.errors.TypingError: Failed at nopython (nopython frontend)
Invalid usage of Function(<class 'numba.cuda.stubs.selp'>) with parameters (bool, float64, int64)
 * parameterized
In definition 0:
    rejected
[1] During: resolving callee type: Function(<class 'numba.cuda.stubs.selp'>)
[2] During: typing of call at /opt/miniconda/conda-bld/numba_1521762275629/<cb3_path>/lib/python3.5/site-packages/numba/cuda/tests/cudapy/test_intrinsics.py (80)
```

**Comment by stuartarchibald** [comment]
@njwhite any ideas ^ ?

**Comment by stuartarchibald** [comment]
Looking at the pattern on the build farm, I think this is a windows 64bit only problem.

**Comment by njwhite** [comment]
@stuartarchibald  I've raised #2865 to make the dtypes more explicit, but not sure why only win64 is failing to guess them?

**Comment by seibert** [comment]
The usual problem with win64 is that the default size of the C `int` is 32-bit, rather than 64-bit on 64-bit Linux/Mac.
