### ISSUE TITLE
CUDA test failures on Tegra TX2 (only a few!)

### ISSUE THREAD

**Issue by seibert** [numba/numba#2849]
Much to my surprise, Numba's CUDA target mostly "just works" on the Tegra TX2 (there are some CPU failures that I'll post in another issue).  Note that a Tegra TX2 is ARMv8 combined with a GP10B CUDA device, which is Pascal (but compute capability 6.2, different from GTX 10XX).  When using the Jetson TX2 dev board, the most common operating system is Ubuntu 16.04, where Numba can run without any modification (not even the small patch we need for ARMv7).  

After compiling LLVM 5.0.1, llvmlite master, and Numba master, you can run the CUDA unit tests with a command like this:
```
NUMBAPRO_LIBDEVICE=/usr/local/cuda/nvvm/libdevice/ NUMBAPRO_NVVM=/usr/local/cuda/nvvm/lib/libnvvm.so NUMBAPRO_CUDALIB=/usr/local/cuda/lib64/ python -m numba.runtests -v numba.cuda.tests
```
(we really need to change those environment variable names, and maybe make a convenience NUMBA_CUDA_SDK that lets you specify the top-level CUDA directory and infers the rest of this.)

This command produces the following failing tests:
<details>

```
======================================================================
ERROR: test_pinned (numba.cuda.tests.cudadrv.test_pinned.TestPinned)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudadrv/test_pinned.py", line 27, in test_pinned
    with cuda.pinned(A):
  File "/home/nvidia/jetconda3/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/api.py", line 203, in pinned
    mapped=False)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 737, in mempin
    allocator()
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 732, in allocator
    driver.cuMemHostRegister(pointer, size, flags)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [801] Call to cuMemHostRegister results in CUDA_ERROR_NOT_SUPPORTED

======================================================================
ERROR: test_pinned_memory (numba.cuda.tests.cudadrv.test_cuda_memory.TestCudaMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudadrv/test_cuda_memory.py", line 43, in test_pinned_memory
    mapped=True)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 735, in mempin
    self._attempt_allocation(allocator)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 656, in _attempt_allocation
    allocator()
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 732, in allocator
    driver.cuMemHostRegister(pointer, size, flags)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [801] Call to cuMemHostRegister results in CUDA_ERROR_NOT_SUPPORTED

======================================================================
FAIL: test_ipc_array (numba.cuda.tests.cudapy.test_ipc.TestIpcMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 157, in test_ipc_array
    self.fail(out)
AssertionError: Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 61, in ipc_array_test
    with ipcarr as darr:
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/devicearray.py", line 568, in __enter__
    return self.open()
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/devicearray.py", line 558, in open
    dptr = self._ipc_handle.open(devices.get_context())
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 944, in open
    mem = context.open_ipc_handle(self.handle, self.size)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 770, in open_ipc_handle
    driver.cuIpcOpenMemHandle(byref(dptr), handle, flags)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to call_cuIpcOpenMemHandle results in CUDA_ERROR_INVALID_VALUE


======================================================================
FAIL: test_ipc_handle (numba.cuda.tests.cudapy.test_ipc.TestIpcMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 109, in test_ipc_handle
    self.fail(out)
AssertionError: Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 22, in core_ipc_handle_test
    arr = the_work()
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 38, in the_work
    dtype=dtype) as darr:
  File "/home/nvidia/jetconda3/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/api.py", line 140, in open_ipc_array
    strides=strides, dtype=dtype)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 960, in open_array
    dptr = self.open(context)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 944, in open
    mem = context.open_ipc_handle(self.handle, self.size)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 770, in open_ipc_handle
    driver.cuIpcOpenMemHandle(byref(dptr), handle, flags)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to call_cuIpcOpenMemHandle results in CUDA_ERROR_INVALID_VALUE


======================================================================
FAIL: test_ipc_handle_serialization (numba.cuda.tests.cudapy.test_ipc.TestIpcMemory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 138, in test_ipc_handle_serialization
    self.fail(out)
AssertionError: Traceback (most recent call last):
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 22, in core_ipc_handle_test
    arr = the_work()
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/tests/cudapy/test_ipc.py", line 50, in the_work
    dtype=dtype)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 960, in open_array
    dptr = self.open(context)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 944, in open
    mem = context.open_ipc_handle(self.handle, self.size)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 770, in open_ipc_handle
    driver.cuIpcOpenMemHandle(byref(dptr), handle, flags)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nvidia/jetconda3/lib/python3.6/site-packages/numba/cuda/cudadrv/driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to call_cuIpcOpenMemHandle results in CUDA_ERROR_INVALID_VALUE


----------------------------------------------------------------------
Ran 415 tests in 236.222s

FAILED (failures=3, errors=2, skipped=4, expected failures=1)
```

</details>

All of the failing tests should be skipped because the GP10B is missing a few features that are present on the desktop Pascal cards, such as:
* CUDA IPC (limitation of the OS drivers?)
* Pinned memory (not really needed since GPU and CPU share the same memory bus)

**Comment by seibert** [comment]
Also, to clarify, it look like specifically `cuMemHostRegister` is not supported on Tegra.  The `cuMemAllocHost` call that directly allocates page-locked memory should work.

Not sure yet what the best programmatic way to detect these limitations is.

**Comment by stuartarchibald** [comment]
@gmarkall is CUDA on the TX2 now working?

**Comment by gmarkall** [comment]
@stuartarchibald The IPC tests are now skipped as unsupported and the pinned memory test has a Jetson-specific configuration that it now uses, so I believe this is resolved.
