### ISSUE TITLE
ARMv8 CPU test failures on Tegra TX2

### ISSUE THREAD

**Issue by seibert** [numba/numba#2853]
With the fix in #2852, these are the only 3 tests failing on ARMv8 (running on Ubuntu 16.04, which is the typical distribution for the Tegra TX2):
```
======================================================================
FAIL: test_multiply_dm_m (numba.tests.test_ufuncs.TestLoopTypesDatetimeNoPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_ufuncs.py", line 1515, in test_template
    self._check_loop(fn, ufunc, loop)
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_ufuncs.py", line 1472, in _check_loop
    self._check_ufunc_with_dtypes(fn, ufunc, letter_types)
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_ufuncs.py", line 1501, in _check_ufunc_with_dtypes
    ulps=ulps)
  File "/home/nvidia/bootstrap/src/numba/numba/tests/support.py", line 257, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing [   -4     0     3 'NaT' 'NaT'     0    -7 'NaT'] and [   -4     0     3 'NaT' 'NaT'     0    -7     0]: numpy.timedelta64('NaT','D') != numpy.timedelta64(0,'D') : ufunc 'multiply' arrays differ ([array([ 1.5,  0. ,  1.5,  nan, -3.5,  0. , -3.5,  nan]), array([   -3,     0,     2, 'NaT', 'NaT',    -3,     2,     0], dtype='timedelta64[D]'), array([   -4,     0,     3, 'NaT', 'NaT',     0,    -7,     0], dtype='timedelta64[D]')]):
args: exact
expected [   -4     0     3 'NaT' 'NaT'     0    -7 'NaT']
got [   -4     0     3 'NaT' 'NaT'     0    -7     0]

======================================================================
FAIL: test_multiply_md_m (numba.tests.test_ufuncs.TestLoopTypesDatetimeNoPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_ufuncs.py", line 1515, in test_template
    self._check_loop(fn, ufunc, loop)
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_ufuncs.py", line 1472, in _check_loop
    self._check_ufunc_with_dtypes(fn, ufunc, letter_types)
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_ufuncs.py", line 1501, in _check_ufunc_with_dtypes
    ulps=ulps)
  File "/home/nvidia/bootstrap/src/numba/numba/tests/support.py", line 257, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing [   -7 'NaT'     3     0     0 'NaT'    -4 'NaT'] and [   -7 'NaT'     3     0     0 'NaT'    -4     0]: numpy.timedelta64('NaT','D') != numpy.timedelta64(0,'D') : ufunc 'multiply' arrays differ ([array([    2, 'NaT',     2,     0,    -3, 'NaT',    -3,     0], dtype='timedelta64[D]'), array([-3.5,  nan,  1.5,  0. ,  0. , -3.5,  1.5,  nan]), array([   -7, 'NaT',     3,     0,     0, 'NaT',    -4,     0], dtype='timedelta64[D]')]):
args: exact
expected [   -7 'NaT'     3     0     0 'NaT'    -4 'NaT']
got [   -7 'NaT'     3     0     0 'NaT'    -4     0]

======================================================================
FAIL: test_mul (numba.tests.test_npdatetime.TestTimedeltaArithmeticNoPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_npdatetime.py", line 328, in test_mul
    check(TD(7, 'ps'), float('nan'), TD('NaT', 'ps'))
  File "/home/nvidia/bootstrap/src/numba/numba/tests/test_npdatetime.py", line 313, in check
    self.assertPreciseEqual(f(a, b), expected)
  File "/home/nvidia/bootstrap/src/numba/numba/tests/support.py", line 257, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing 0 picoseconds and NaT: numpy.timedelta64(0,'ps') != numpy.timedelta64('NaT','ps')

----------------------------------------------------------------------
Ran 6814 tests in 10757.557s

FAILED (failures=3, skipped=38, expected failures=6)
```
The failures seem to be related to differences in `NaT` handling.

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
