### ISSUE TITLE
CUDA device reset segfaults

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2875]
This happens on Linux, windows build machines are also reporting access violations, possibly the same cause?

Traces
```python
(someenv) user@machine~/numba$ python -m numba.runtests numba.cuda.tests.cudadrv.test_reset_device.TestResetDevice
<path>/envs/someenv/lib/python3.6/runpy.py:125: RuntimeWarning: 'numba.runtests' found in sys.modules after import of package 'numba', but prior to execution of 'numba.runtests'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Fatal Python error: Segmentation fault

Thread 0x00007f90719e7700 (most recent call first):
  File "<nbpath>/numba/cuda/cudadrv/driver.py", line 287 in safe_cuda_api_call
  File "<nbpath>/numba/cuda/cudadrv/driver.py", line 448 in get_primary_context
  File "<nbpath>/numba/cuda/cudadrv/devices.py", line 120 in _get_or_create_context
  File "<nbpath>/numba/cuda/cudadrv/devices.py", line 130 in push_context
  File "<nbpath>/numba/cuda/cudadrv/devices.py", line 162 in get_or_create_context
  File "<nbpath>/numba/cuda/cudadrv/devices.py", line 194 in get_context
  File "<nbpath>/numba/cuda/api.py", line 253 in select_device
  File "<nbpath>/numba/cuda/tests/cudadrv/test_reset_device.py", line 21 in newthread
  File "<path>/envs/someenv/lib/python3.6/threading.py", line 864 in run
  File "<path>/envs/someenv/lib/python3.6/threading.py", line 916 in _bootstrap_inner
  File "<path>/envs/someenv/lib/python3.6/threading.py", line 884 in _bootstrap

Thread 0x00007f9086d32700 (most recent call first):
  File "<path>/envs/someenv/lib/python3.6/threading.py", line 1072 in _wait_for_tstate_lock
  File "<path>/envs/someenv/lib/python3.6/threading.py", line 1056 in join
  File "<nbpath>/numba/cuda/tests/cudadrv/test_reset_device.py", line 32 in test_reset_device
  File "<path>/envs/someenv/lib/python3.6/unittest/case.py", line 605 in run
  File "<path>/envs/someenv/lib/python3.6/unittest/case.py", line 653 in __call__
  File "<path>/envs/someenv/lib/python3.6/unittest/suite.py", line 122 in run
  File "<path>/envs/someenv/lib/python3.6/unittest/suite.py", line 84 in __call__
  File "<path>/envs/someenv/lib/python3.6/unittest/suite.py", line 122 in run
  File "<path>/envs/someenv/lib/python3.6/unittest/suite.py", line 84 in __call__
  File "<path>/envs/someenv/lib/python3.6/unittest/runner.py", line 176 in run
  File "<path>/envs/someenv/lib/python3.6/unittest/main.py", line 256 in runTests
  File "<nbpath>/numba/testing/main.py", line 211 in run_tests_real
  File "<nbpath>/numba/testing/main.py", line 226 in runTests
  File "<path>/envs/someenv/lib/python3.6/unittest/main.py", line 95 in __init__
  File "<nbpath>/numba/testing/main.py", line 127 in __init__
  File "<nbpath>/numba/testing/__init__.py", line 70 in run_tests
  File "<nbpath>/numba/runtests.py", line 23 in _main
  File "<nbpath>/numba/runtests.py", line 116 in <module>
  File "<path>/envs/someenv/lib/python3.6/runpy.py", line 85 in _run_code
  File "<path>/envs/someenv/lib/python3.6/runpy.py", line 193 in _run_module_as_main
Segmentation fault (core dumped)
```
From gdb:
```gdb
(<path>) user@machine:~/numba$ gdb python
<snip>
Reading symbols from python...done.
(gdb) r -m numba.runtests numba.cuda.tests.cudadrv.test_reset_device.TestResetDevice
Starting program: <path>/bin/python -m numba.runtests numba.cuda.tests.cudadrv.test_reset_device.TestResetDevice
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
<path>/lib/python3.6/runpy.py:125: RuntimeWarning: 'numba.runtests' found in sys.modules after import of package 'numba', but prior to execution of 'numba.runtests'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
[New Thread 0x7fffe2c99700 (LWP 54737)]
[New Thread 0x7fffe2458700 (LWP 54740)]
[New Thread 0x7fffe1c57700 (LWP 54741)]
[New Thread 0x7fffe11ff700 (LWP 54742)]
[New Thread 0x7fffd51ff700 (LWP 54743)]

Thread 6 "python" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd51ff700 (LWP 54743)]
0x00007fffe32318d5 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
(gdb) bt
#0  0x00007fffe32318d5 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#1  0x00007fffe3381914 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#2  0x00007fffe331de80 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#3  0x00007ffff7bc16ba in start_thread (arg=0x7fffd51ff700) at pthread_create.c:333
#4  0x00007ffff78f741d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) info registers
rax            0x0      0
rbx            0x0      0
rcx            0xd5d7   54743
rdx            0x10     16
rsi            0x0      0
rdi            0x0      0
rbp            0x7fffdc776e68   0x7fffdc776e68
rsp            0x7fffd51feea0   0x7fffd51feea0
r8             0x7fffdc776e08   140736892202504
r9             0x0      0
r10            0x0      0
r11            0x0      0
r12            0x7fffdc776dd0   140736892202448
r13            0x7fffdc776e08   140736892202504
r14            0x7fffd51feef0   140736769027824
r15            0x0      0
rip            0x7fffe32318d5   0x7fffe32318d5
eflags         0x10246  [ PF ZF IF RF ]
cs             0x33     51
ss             0x2b     43
ds             0x0      0
es             0x0      0
fs             0x0      0
gs             0x0      0
k0             0x0      0
k1             0x0      0
k2             0x0      0
k3             0x0      0
k4             0x0      0
k5             0x0      0
k6             0x0      0
k7             0x0      0
```

**Comment by stuartarchibald** [comment]
I can't reproduce this locally so wonder if it is driver/dual GPU related? The issue is docker invariant, it reproduces inside and outside containers.

**Comment by stuartarchibald** [comment]
Build farm got stuck, reboot sorted it.
