### ISSUE TITLE
Incorrect dispatch if FARRAY is misaligned

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2937]
- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The set up for this is a bit convoluted and was discovered whilst working on https://github.com/numba/numba/pull/1968.

This code demonstrates the issue.
```python
import numba as nb
import numpy as np

def foo(a):
    return np.linalg.matrix_power(a, 1)

jitfoo = nb.njit(foo)

n = 64
r = int(np.sqrt(n))
dt = np.int8
count = np.complex128().itemsize // dt().itemsize

tmp = np.arange(n * count + 1, dtype=dt)

# create some arrays as Cartesian production of [F/C] x [aligned/misaligned]
C_contig_aligned = tmp[:-1].view(np.complex128).reshape(r, r)
C_contig_misaligned = tmp[1:].view(np.complex128).reshape(r, r)
F_contig_aligned = C_contig_aligned.T
F_contig_misaligned = C_contig_misaligned.T

# checking routine
def check(name, a):
    print('-' * 80)
    print("checking: %s" % name)
    print(a.flags)
    a[:, :] = np.arange(n, dtype=np.complex128).reshape(r, r)
    expected = foo(a)
    got = jitfoo(a)
    print("current overloads:")
    print(jitfoo.overloads.keys())
    print("expected:")
    print(expected)
    print("got:")
    print(got)
    np.testing.assert_allclose(expected, got)

# the checks must be run in this order to create the dispatch key sequence
check("C_contig_aligned", C_contig_aligned)
check("F_contig_aligned", F_contig_aligned)
check("C_contig_misaligned", C_contig_misaligned)
check("F_contig_misaligned", F_contig_misaligned)

```
This gives:
```
--------------------------------------------------------------------------------
checking: C_contig_aligned
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
current overloads:
odict_keys([(array(complex128, 2d, C),)])
expected:
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j 18.+0.j 19.+0.j 20.+0.j 21.+0.j 22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j 26.+0.j 27.+0.j 28.+0.j 29.+0.j 30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j 34.+0.j 35.+0.j 36.+0.j 37.+0.j 38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j 42.+0.j 43.+0.j 44.+0.j 45.+0.j 46.+0.j 47.+0.j]
 [48.+0.j 49.+0.j 50.+0.j 51.+0.j 52.+0.j 53.+0.j 54.+0.j 55.+0.j]
 [56.+0.j 57.+0.j 58.+0.j 59.+0.j 60.+0.j 61.+0.j 62.+0.j 63.+0.j]]
got:
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j 18.+0.j 19.+0.j 20.+0.j 21.+0.j 22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j 26.+0.j 27.+0.j 28.+0.j 29.+0.j 30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j 34.+0.j 35.+0.j 36.+0.j 37.+0.j 38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j 42.+0.j 43.+0.j 44.+0.j 45.+0.j 46.+0.j 47.+0.j]
 [48.+0.j 49.+0.j 50.+0.j 51.+0.j 52.+0.j 53.+0.j 54.+0.j 55.+0.j]
 [56.+0.j 57.+0.j 58.+0.j 59.+0.j 60.+0.j 61.+0.j 62.+0.j 63.+0.j]]
--------------------------------------------------------------------------------
checking: F_contig_aligned
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
current overloads:
odict_keys([(array(complex128, 2d, C),), (array(complex128, 2d, F),)])
expected:
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j 18.+0.j 19.+0.j 20.+0.j 21.+0.j 22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j 26.+0.j 27.+0.j 28.+0.j 29.+0.j 30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j 34.+0.j 35.+0.j 36.+0.j 37.+0.j 38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j 42.+0.j 43.+0.j 44.+0.j 45.+0.j 46.+0.j 47.+0.j]
 [48.+0.j 49.+0.j 50.+0.j 51.+0.j 52.+0.j 53.+0.j 54.+0.j 55.+0.j]
 [56.+0.j 57.+0.j 58.+0.j 59.+0.j 60.+0.j 61.+0.j 62.+0.j 63.+0.j]]
got:
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j 18.+0.j 19.+0.j 20.+0.j 21.+0.j 22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j 26.+0.j 27.+0.j 28.+0.j 29.+0.j 30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j 34.+0.j 35.+0.j 36.+0.j 37.+0.j 38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j 42.+0.j 43.+0.j 44.+0.j 45.+0.j 46.+0.j 47.+0.j]
 [48.+0.j 49.+0.j 50.+0.j 51.+0.j 52.+0.j 53.+0.j 54.+0.j 55.+0.j]
 [56.+0.j 57.+0.j 58.+0.j 59.+0.j 60.+0.j 61.+0.j 62.+0.j 63.+0.j]]
--------------------------------------------------------------------------------
checking: C_contig_misaligned
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : False
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
current overloads:
odict_keys([(array(complex128, 2d, C),), (array(complex128, 2d, F),)])
expected:
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j 18.+0.j 19.+0.j 20.+0.j 21.+0.j 22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j 26.+0.j 27.+0.j 28.+0.j 29.+0.j 30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j 34.+0.j 35.+0.j 36.+0.j 37.+0.j 38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j 42.+0.j 43.+0.j 44.+0.j 45.+0.j 46.+0.j 47.+0.j]
 [48.+0.j 49.+0.j 50.+0.j 51.+0.j 52.+0.j 53.+0.j 54.+0.j 55.+0.j]
 [56.+0.j 57.+0.j 58.+0.j 59.+0.j 60.+0.j 61.+0.j 62.+0.j 63.+0.j]]
got:
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j 18.+0.j 19.+0.j 20.+0.j 21.+0.j 22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j 26.+0.j 27.+0.j 28.+0.j 29.+0.j 30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j 34.+0.j 35.+0.j 36.+0.j 37.+0.j 38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j 42.+0.j 43.+0.j 44.+0.j 45.+0.j 46.+0.j 47.+0.j]
 [48.+0.j 49.+0.j 50.+0.j 51.+0.j 52.+0.j 53.+0.j 54.+0.j 55.+0.j]
 [56.+0.j 57.+0.j 58.+0.j 59.+0.j 60.+0.j 61.+0.j 62.+0.j 63.+0.j]]
--------------------------------------------------------------------------------
checking: F_contig_misaligned
  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : False
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
current overloads:
odict_keys([(array(complex128, 2d, C),), (array(complex128, 2d, F),)])
expected:
[[ 0.+0.j  1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j]
 [ 8.+0.j  9.+0.j 10.+0.j 11.+0.j 12.+0.j 13.+0.j 14.+0.j 15.+0.j]
 [16.+0.j 17.+0.j 18.+0.j 19.+0.j 20.+0.j 21.+0.j 22.+0.j 23.+0.j]
 [24.+0.j 25.+0.j 26.+0.j 27.+0.j 28.+0.j 29.+0.j 30.+0.j 31.+0.j]
 [32.+0.j 33.+0.j 34.+0.j 35.+0.j 36.+0.j 37.+0.j 38.+0.j 39.+0.j]
 [40.+0.j 41.+0.j 42.+0.j 43.+0.j 44.+0.j 45.+0.j 46.+0.j 47.+0.j]
 [48.+0.j 49.+0.j 50.+0.j 51.+0.j 52.+0.j 53.+0.j 54.+0.j 55.+0.j]
 [56.+0.j 57.+0.j 58.+0.j 59.+0.j 60.+0.j 61.+0.j 62.+0.j 63.+0.j]]
got:
[[ 0.+0.j  8.+0.j 16.+0.j 24.+0.j 32.+0.j 40.+0.j 48.+0.j 56.+0.j]
 [ 1.+0.j  9.+0.j 17.+0.j 25.+0.j 33.+0.j 41.+0.j 49.+0.j 57.+0.j]
 [ 2.+0.j 10.+0.j 18.+0.j 26.+0.j 34.+0.j 42.+0.j 50.+0.j 58.+0.j]
 [ 3.+0.j 11.+0.j 19.+0.j 27.+0.j 35.+0.j 43.+0.j 51.+0.j 59.+0.j]
 [ 4.+0.j 12.+0.j 20.+0.j 28.+0.j 36.+0.j 44.+0.j 52.+0.j 60.+0.j]
 [ 5.+0.j 13.+0.j 21.+0.j 29.+0.j 37.+0.j 45.+0.j 53.+0.j 61.+0.j]
 [ 6.+0.j 14.+0.j 22.+0.j 30.+0.j 38.+0.j 46.+0.j 54.+0.j 62.+0.j]
 [ 7.+0.j 15.+0.j 23.+0.j 31.+0.j 39.+0.j 47.+0.j 55.+0.j 63.+0.j]]
Traceback (most recent call last):
  File "test4.py", line 42, in <module>
    check("F_contig_misaligned", F_contig_misaligned)
  File "test4.py", line 36, in check
    np.testing.assert_allclose(expected, got)
  File "<py_path>/site-packages/numpy/testing/nose_tools/utils.py", line 1396, in assert_allclose
    verbose=verbose, header=header, equal_nan=equal_nan)
  File "<py_path>/site-packages/numpy/testing/nose_tools/utils.py", line 779, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 87.5%)
 x: array([[ 0.+0.j,  1.+0.j,  2.+0.j,  3.+0.j,  4.+0.j,  5.+0.j,  6.+0.j,
         7.+0.j],
       [ 8.+0.j,  9.+0.j, 10.+0.j, 11.+0.j, 12.+0.j, 13.+0.j, 14.+0.j,...
 y: array([[ 0.+0.j,  8.+0.j, 16.+0.j, 24.+0.j, 32.+0.j, 40.+0.j, 48.+0.j,
        56.+0.j],
       [ 1.+0.j,  9.+0.j, 17.+0.j, 25.+0.j, 33.+0.j, 41.+0.j, 49.+0.j,...
```

It would appear that the dispatcher is dispatching the C order implementation when the misaligned Fortran order array is presented. Application of the fix to `_typeof.c` mentioned in here https://github.com/numba/numba/pull/1968#issuecomment-384985901 fixes it.

Thoughts @sklam? I'm of the view that the fix is likely valid, and now we have a contained reproducer it will allow investigation.

**Comment by sklam** [comment]
I think the patch is good.
