### ISSUE TITLE
Compilation failure hints

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#2941]
## Feature request
GCC 8.0 is out and has the rather useful notion of supplying a hint on failure. An example from: https://gcc.gnu.org/gcc-8/changes.html
```
$ gcc incomplete.cc
incomplete.cc:1:6: error: 'string' in namespace 'std' does not name a type
 std::string s("hello world");
      ^~~~~~
incomplete.cc:1:1: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
+#include <string>
 std::string s("hello world");
 ^~~
```

The current error messages Numba reports are improved but it would be perhaps good to also provide hints, for example (`tuple` unsupported):
```python
from numba import jit

@jit(nopython=True)
def foo():
    return tuple([1.])

foo()
```
could give:
```pytb
Traceback (most recent call last):
  File "test66.py", line 7, in <module>
    foo()
  File "<path>/numba/numba/dispatcher.py", line 344, in _compile_for_args
    reraise(type(e), e, None)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Untyped global name 'tuple': cannot determine the equivalent Numba type for <class 'tuple'>
** HINT: Numba does not recognise the type given, is it supported? **

File "test66.py", line 5:
def foo():
    return tuple([1.])
```

Thoughts?

**Comment by stuartarchibald** [comment]
Closing, hints were implemented and then later removed following feedback about verbosity.
