### ISSUE TITLE
Branching on sets not supported in nopython mode

### ISSUE THREAD

**Issue by Rik-de-Kort** [numba/numba#2948]
## Description
Branching (if-statement) on a set in nopython mode yields an error related to `len` not being available for the Numba-type `Set`. `len(set)` works fine in nopython mode. Error is not present for other containers.

## MnWE
````python
@njit()
def foo(bar):
    if bar:
        return

foo(set([1]))
````

Corresponding error:
````python
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\errors.py", line 259, in new_error_context
    yield
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 274, in lower_inst
    pred = self.context.cast(self.builder, cond, condty, types.boolean)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\base.py", line 645, in cast
    return impl(self, builder, fromty, toty, val)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\numbers.py", line 1347, in any_to_boolean
    return context.is_true(builder, fromty, val)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\base.py", line 682, in is_true
    return impl(builder, (val,))
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\base.py", line 1046, in __call__
    return self._imp(self._context, builder, self._sig, args)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\builtins.py", line 327, in sized_bool
    if len(ty):
TypeError: object of type 'Set' has no len()
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-56-6257cd164155>", line 6, in <module>
    foo(set([1]))
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\dispatcher.py", line 307, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\dispatcher.py", line 579, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\dispatcher.py", line 80, in compile
    flags=flags, locals=self.locals)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 766, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 362, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 725, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 712, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 248, in run
    raise patched_exception
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 240, in run
    stage()
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 647, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 602, in _backend
    lowered = lowerfn()
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 589, in backend_nopython_mode
    self.flags)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\compiler.py", line 885, in native_lowering_stage
    lower.lower()
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\User\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\errors.py", line 265, in new_error_context
    six.reraise(type(newerr), newerr, sys.exc_info()[2])
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\errors.py", line 259, in new_error_context
    yield
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\lowering.py", line 274, in lower_inst
    pred = self.context.cast(self.builder, cond, condty, types.boolean)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\base.py", line 645, in cast
    return impl(self, builder, fromty, toty, val)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\numbers.py", line 1347, in any_to_boolean
    return context.is_true(builder, fromty, val)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\base.py", line 682, in is_true
    return impl(builder, (val,))
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\base.py", line 1046, in __call__
    return self._imp(self._context, builder, self._sig, args)
  File "C:\Users\User\Anaconda3\lib\site-packages\numba\targets\builtins.py", line 327, in sized_bool
    if len(ty):
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
object of type 'Set' has no len()
File "<ipython-input-56-6257cd164155>", line 3
[1] During: lowering "branch bar, 4, 8" at <ipython-input-56-6257cd164155> (3)
````

## Proposed Fix
Simply implement `__len__` for the `Set` type in types/containers.py.

**Comment by lagru** [comment]
I ran into this issue as well. I'm using numba version 0.24.0.

**Comment by stuartarchibald** [comment]
Closing, https://github.com/numba/numba/pull/3901 fixed.
