### ISSUE TITLE
[bug] "AssertionError: Failed at object (object mode frontend)" exception from simple code

### ISSUE THREAD

**Issue by cdluminate** [numba/numba#2955]
Minimal repro code:
```python
import sys, os, re
import numpy as np
from typing import *
import numba


@numba.jit
def numbaFailure(scores: np.ndarray, cooc: np.ndarray):
    rows, cols = scores.shape
    points = []
    for i in range(rows):
        xavv, coxv = scores[i], cooc[i]
        groups = sorted(set(coxv), reverse=True)
        idxgrp = [set(np.argwhere(coxv == x).flatten()) for x in groups]


if __name__ == '__main__':
    print(numba.__version__)
    x = np.random.random((10, 10))
    y = np.abs((np.random.randn(10, 10)*1.732)).astype(np.int)
    numbaFailure(x, y)
```

Error:
```
0.38.0
Traceback (most recent call last):
  File "x.py", line 21, in <module>
    numbaFailure(x, y)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 360, in _compile_for_args
    raise e
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 311, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 618, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 871, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 365, in compile_extra
    return self._compile_bytecode()
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 802, in _compile_bytecode
    return self._compile_core()
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 789, in _compile_core
    res = pm.run(self.status)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 251, in run
    raise patched_exception
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 243, in run
    stage()
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 436, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/compiler.py", line 416, in frontend_looplift
    flags=loop_flags)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/transforms.py", line 211, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/analysis.py", line 213, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/home/lumin/.local/lib/python3.6/site-packages/numba/controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed at object (object mode frontend)
```

Numba 0.38.0, llvmlite 0.23.0

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce. I'm fairly sure the root cause is that the closure inlining pass is modifying the IR on the instruction level during the "no python" pipeline, when this pipeline fails and "object mode" is used instead, the IR is restored from a block level copy not an instruction level copy. The problem is essentially the same as in this ticket https://github.com/numba/numba/issues/2657 (bad jump label left in the IR after nopython mode transforms).

**Comment by hiteyoshi** [comment]
Hi I didn't finish reading your problem but I once had the same error. The reason is I put the function who uses a called function forward which is why it gave me such a error. hope it helps

**Comment by Pk13055** [comment]
@hiteyoshi I didn't quite get you. Do you mean you put the function in another calling function?
