### ISSUE TITLE
Passing a jitted function reference to a jitted function makes cache=True fail

### ISSUE THREAD

**Issue by sjperkins** [numba/numba#2956]
## Reporting a bug

- [x] I am using the latest released version of Numba (0.38) (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

If one passes a reference to a njitted function into another njitted function which has caching enabled,
caching fails when attempting to pickle a `weakref`. In the example below, `fn` is assigned to one of two njitted functions and passed through to njitted function `_adder` which has `cache=True` in it's decorator..

```python
from __future__ import print_function

import numpy as np
import numba

@numba.jit(nogil=True, cache=True)
def combine_1(x, y):
    return x + y

@numba.jit(nogil=True, cache=True)
def combine_2(x, y):
    return x - y


@numba.njit(nogil=True, cache=True)
def _adder(arr1, arr2, fn):
    acc = 0.0
    for x, y in zip(arr1, arr2):
        acc += fn(x, y)

    return acc

def adder(arr1, arr2):
    if arr1.size < 10:
        fn = combine_1
    else:
        fn = combine_2

    return _adder(arr1, arr2, fn)

print(adder(np.arange(5), np.arange(5)))
```

This produces the following error:

```python-traceback
Traceback (most recent call last):
  File "test_jit_cache_fail.py", line 31, in <module>
    print(adder(np.arange(5), np.arange(5)))
  File "test_jit_cache_fail.py", line 29, in adder
    return _adder(arr1, arr2, fn)
  File "/home/sperkins/venv/afr/local/lib/python2.7/site-packages/numba/dispatcher.py", line 360, in _compile_for_args
    raise e
cPickle.PicklingError: Can't pickle <type 'weakref'>: attribute lookup __builtin__.weakref failed
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. The offending object is:
```python
((1526043960.7049644, 551), {((array(int64, 1d, C), array(int64, 1d, C), type(CPUDispatcher(<function combine_1 at 0x7f6712bcf950>))), ('x86_64-unknown-linux-gnu', 'core2', '-adx,-aes,-avx,-avx2,-avx512bitalg,-avx512bw,-avx512cd,-avx512dq,-avx512er,-avx512f,-avx512ifma,-avx512pf,-avx512vbmi,-avx512vbmi2,-avx512vl,-avx512vnni,-avx512vpopcntdq,-bmi,-bmi2,-clflushopt,-clwb,-clzero,+cmov,+cx16,-f16c,-fma,-fma4,-fsgsbase,-gfni,-ibt,-lwp,-lzcnt,+mmx,-movbe,-mwaitx,-pclmul,-pku,-popcnt,-prefetchwt1,-prfchw,-rdrnd,-rdseed,-rtm,-sgx,-sha,-shstk,+sse,+sse2,+sse3,-sse4.1,-sse4.2,-sse4a,+ssse3,-tbm,-vaes,-vpclmulqdq,-xop,-xsave,-xsavec,-xsaveopt,-xsaves')): 'issue2956._adder-15.py36m.1.nbc'})
```
and it's the `type(CPUDispatcher(<function combine_1 at 0x7f6712bcf950>)` which is the cause of complaint.

**Comment by sklam** [comment]
There are two problems here:

1. The easy one.  Make the `numba.types.Dispatcher` type pickle-able.
2. The hard one.  Make sure a dispatcher (in the type-level and value-level) be uniquely identifiable across multiple python session.  

I have fixed problem 1 at https://github.com/sklam/numba/commit/8f33f23481dc60a321816d1828ab48f0dbfe6c87.  But the cache is not working properly because the hash of a dispatcher object (CPUDispatcher instance) is different in each fresh python session.

**Comment by ehsantn** [comment]
I just ran into this issue. Does #3768 help with this?

**Comment by asmeurer** [comment]
I tested and if you swap out `pickle` for `dill` in numba.caching it makes this error go away. However, I'm not sure if it really helps because of the issue @sklam mentioned (and I didn't see any meaningful improvement in compile time after doing so).
