### ISSUE TITLE
Recursive function with optional types

### ISSUE THREAD

**Issue by synapticarbors** [numba/numba#2971]
Using python 3.6 and numba 0.39.0dev0+18.g2757c83 from the numba channel.

I was attempting to see if I could adapt the python code in the following benchmark to use numba:

https://github.com/frol/completely-unscientific-benchmarks/tree/master/python

Starting with just the first piece, I ran into an issue. The code below:

```python
from collections import OrderedDict
import random

import numba as nb


node_type = nb.deferred_type()
opt_node_type = nb.optional(node_type)
node_spec = OrderedDict([('x', nb.int32), ('y', nb.int32), ('left', opt_node_type), ('right', opt_node_type)])


@nb.jitclass(node_spec)
class Node:

    def __init__(self, x):
        self.x = x
        self.y = random.randint(0, 2**31)
        self.left = None
        self.right = None


node_type.define(Node.class_type.instance_type)


@nb.jit((opt_node_type, opt_node_type), nopython=True)
def merge(lower, greater):
    if lower is None:
        return greater

    if greater is None:
        return lower

    if lower.y < greater.y:
        tmpl = merge(lower.right, greater)
        lower.right = tmpl
        return lower
    else:
        tmpg = merge(lower, greater.left)
        greater.left = tmpg
        return greater

```

produces the following error:

```python-traceback
Traceback (most recent call last):
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/errors.py", line 491, in new_error_context
    yield
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/lowering.py", line 266, in lower_inst
    self.storevar(val, inst.target.name)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/lowering.py", line 950, in storevar
    raise AssertionError(msg)
AssertionError: Storing %"deferred.4393458824.value" to ptr of {%"deferred.4393458824.value", i1} ('$52.5'). FE type ?DeferredType#4393458824

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test1.py", line 25, in <module>
    @nb.jit((opt_node_type, opt_node_type), nopython=True)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/decorators.py", line 198, in wrapper
    disp.compile(sig)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/dispatcher.py", line 618, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 871, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 365, in compile_extra
    return self._compile_bytecode()
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 802, in _compile_bytecode
    return self._compile_core()
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 789, in _compile_core
    res = pm.run(self.status)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 251, in run
    raise patched_exception
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 243, in run
    stage()
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 676, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 626, in _backend
    lowered = lowerfn()
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 613, in backend_nopython_mode
    self.flags)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/compiler.py", line 990, in native_lowering_stage
    lower.lower()
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/errors.py", line 499, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/zzz/anaconda/envs/treap/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
Storing %"deferred.4393458824.value" to ptr of {%"deferred.4393458824.value", i1} ('$52.5'). FE type ?DeferredType#4393458824

File "test1.py", line 34:
def merge(lower, greater):
    <source elided>
    if lower.y < greater.y:
        tmpl = merge(lower.right, greater)
        ^
[1] During: lowering "$52.5 = call $52.1($52.3, greater, func=$52.1, args=[Var($52.3, test1.py (34)), Var(greater, test1.py (27))], kws=(), vararg=None)" at test1.py (34)
```

I'm wondering if I'm running into some limitation of using optional types with recursive functions or if I'm doing something incorrect, or if I've possibly found a bug.

**Comment by sklam** [comment]
https://github.com/numba/numba/pull/3009 fixes one of the issue revealed in this issue.
With that patch, a new issue is revealed:

```
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
No definition for lowering DeferredType#4497570336.right = ?DeferredType#4497570336

File "chk2971.py", line 35:
def merge(lower, greater):
    <source elided>
        tmpl = merge(lower.right, greater)
        lower.right = tmpl
        ^
```

**Comment by micsthepick** [comment]
> #3009 fixes one of the issue revealed in this issue. With that patch, a new issue is revealed:
any known workarounds, or progress towards a fix?
I am trying to implement algorithm X with a doubly linked list, and am encountering that precise lowering error, on latest conda dev package in wsl2 Ubuntu

**Comment by 99991** [comment]
My workaround for this issue was to convert my recursive function to an iterative function. Example:

```python
import numba

# Binary tree node
deferred_node_type = numba.deferred_type()

@numba.experimental.jitclass([
    ("value", numba.int64),
    ("left", numba.optional(deferred_node_type)),
    ("right", numba.optional(deferred_node_type)),
])
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

node_type = Node.class_type.instance_type
deferred_node_type.define(node_type)

"""
# Recursive implementation not possible due to Numba bug, see GitHub issue:
# https://github.com/numba/numba/issues/2971#issuecomment-393895107
@numba.njit
def insert(root, value):
    if root is None:
        return Node(value)

    if value < root.value:
        root.left = insert(root.left, value)
    else:
        root.right = insert(root.right, value)

    return root
"""
# Iterative implementation of the above
@numba.njit([
    node_type(numba.none, numba.int64),
    node_type(node_type, numba.int64),
])
def insert(root, value):
    if root is None:
        return Node(value)

    node = root
    while True:
        parent = node
        if value < node.value:
            node = node.left
            if node is None:
                parent.left = Node(value)
                return root
        else:
            node = node.right
            if node is None:
                parent.right = Node(value)
                return root

@numba.njit([
    numba.void(numba.none),
    numba.void(node_type),
])
def print_inorder(node):
    if node is not None:
        print_inorder(node.left)
        print(node.value)
        print_inorder(node.right)

def test():
    import random
    values = list(range(10))
    random.shuffle(values)
    root = None
    for value in values:
        root = insert(root, value)

    print_inorder(root)

if __name__ == "__main__":
    test()
```

As an added bonus, the iterative variant is likely faster than a recursive function would be due to lack of function call overhead. Also there is no chance of exceeding Python's recursion limit of 1000 function calls. The code might look less elegant though and might require the introduction of an additional stack variable for more complex recursive functions.
