### ISSUE TITLE
`NotImplementedError`/ `LoweringError` for any map(lambda ... )

### ISSUE THREAD

**Issue by ivirshup** [numba/numba#2992]
If I try to use a `lambda` with `map` I get a `NotImplementedError`/ `LoweringError`. This might be covered by generators not being fully supported yet, or issue #1730, but I figured it's probably better to report than not.

Example:

```python
Python 3.6.5 (default, Apr  3 2018, 18:13:10) 
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numba
>>> @numba.jit
... def foo(a):
...     map(lambda x: x, a)
... 
>>> foo([1])
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/numba/errors.py", line 491, in new_error_context
    yield
  File "/usr/local/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python3.6/site-packages/numba/objmode.py", line 65, in lower_inst
    value = self.lower_assign(inst)
  File "/usr/local/lib/python3.6/site-packages/numba/objmode.py", line 159, in lower_assign
    return self.lower_expr(value)
  File "/usr/local/lib/python3.6/site-packages/numba/objmode.py", line 373, in lower_expr
    raise NotImplementedError(expr)
NotImplementedError: make_function(name=$const0.3, code=<code object <lambda> at 0x101d381e0, file "<stdin>", line 3>, closure=None, defaults=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/numba/dispatcher.py", line 360, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.6/site-packages/numba/dispatcher.py", line 311, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.6/site-packages/numba/dispatcher.py", line 618, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 871, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 365, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 802, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 789, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 251, in run
    raise patched_exception
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 243, in run
    stage()
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 650, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 626, in _backend
    lowered = lowerfn()
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 599, in backend_object_mode
    self.flags)
  File "/usr/local/lib/python3.6/site-packages/numba/compiler.py", line 1016, in py_lowering_stage
    lower.lower()
  File "/usr/local/lib/python3.6/site-packages/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.6/site-packages/numba/lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python3.6/site-packages/numba/lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/numba/errors.py", line 499, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/usr/local/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at object (object mode backend)
make_function(name=$const0.3, code=<code object <lambda> at 0x101d381e0, file "<stdin>", line 3>, closure=None, defaults=None)

File "<stdin>", line 3:

[1] During: lowering "$0.4 = make_function(name=$const0.3, code=<code object <lambda> at 0x101d381e0, file "<stdin>", line 3>, closure=None, defaults=None)" at <stdin> (3)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If you need help writing a minimal reproducer please see:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

>>> numba.__version__
'0.38.0'
```

This occurs regardless of whether the generator is collected or returned.

- [x ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

**Comment by stuartarchibald** [comment]
Thanks for the report. Indeed `map` is not supported. However, we ought to catch `make_function` errors and rewrite them as something more user friendly as they are almost always down to use of an unsupported construct.

**Comment by stuz5000** [comment]
Are *any* map comprehensions supported. I've submitted a similar (simpler) example that fails: #3028

**Comment by stuartarchibald** [comment]
As of version 0.44 this produces:
```
numba.errors.UnsupportedError: Failed in object mode pipeline (step: ensure IR is legal prior to lowering)
Numba encountered the use of a language feature it does not support in this context: <lambda> (op code: make_function not supported). If the feature is explicitly supported it is likely that the result of the expression (<lambda>) is being used in an unsupported manner.

File "issue2992.py", line 4:
def foo(a):
    map(lambda x: x, a)
```
Closing.
