### ISSUE TITLE
Test failure on i7-3930K (win-64) (py27)

### ISSUE THREAD

**Issue by nehaljwani** [numba/numba#3047]
With numba 0.38.1:
```
C:\ci\numba_1529660792435\_test_env\lib\unittest\case.py:545: RuntimeWarning: invalid value encountered in less_equal
  if abs(first - second) <= delta:
F....................................................................................................................................................sss.s.....................................................................s............ss.s.....sssss...s
======================================================================
FAIL: test_power_ff_f (numba.tests.test_ufuncs.TestLoopTypesFloatNoPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py", line 1515, in test_template
    self._check_loop(fn, ufunc, loop)
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py", line 1472, in _check_loop
    self._check_ufunc_with_dtypes(fn, ufunc, letter_types)
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py", line 1501, in _check_ufunc_with_dtypes
    ulps=ulps)
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\support.py", line 257, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing [0.24192491        nan 1.8371173         nan 1.                inf
        nan        nan] and [0.24192491        nan 1.8371173  1.         1.                inf
        nan        nan]: nan != 1.0 within nan delta : ufunc 'power' arrays differ ([array([ 1.5,  0. ,  1.5,  nan, -3.5,  0. , -3.5,  nan], dtype=float32), array([-3.5,  nan,  1.5,  0. ,  0. , -3.5,  1.5,  nan], dtype=float32), array([0.24192491,        nan, 1.8371173 , 1.        , 1.        ,
              inf,        nan,        nan], dtype=float32)]):
args: single
expected [0.24192491        nan 1.8371173         nan 1.                inf
        nan        nan]
got [0.24192491        nan 1.8371173  1.         1.                inf
        nan        nan]

Stderr:
C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py:2: RuntimeWarning: divide by zero encountered in power

C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py:2: RuntimeWarning: invalid value encountered in power

C:\ci\numba_1529660792435\_test_env\lib\unittest\case.py:545: RuntimeWarning: invalid value encountered in less_equal
  if abs(first - second) <= delta:

======================================================================
FAIL: test_power_ff_f (numba.tests.test_ufuncs.TestLoopTypesPowerNoPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py", line 1515, in test_template
    self._check_loop(fn, ufunc, loop)
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py", line 1472, in _check_loop
    self._check_ufunc_with_dtypes(fn, ufunc, letter_types)
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py", line 1501, in _check_ufunc_with_dtypes
    ulps=ulps)
  File "C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\support.py", line 257, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing [0.24192491        nan 1.8371173         nan 1.                inf
        nan        nan] and [0.24192491        nan 1.8371173  1.         1.                inf
        nan        nan]: nan != 1.0 within nan delta : ufunc 'power' arrays differ ([array([ 1.5,  0. ,  1.5,  nan, -3.5,  0. , -3.5,  nan], dtype=float32), array([-3.5,  nan,  1.5,  0. ,  0. , -3.5,  1.5,  nan], dtype=float32), array([0.24192491,        nan, 1.8371173 , 1.        , 1.        ,
              inf,        nan,        nan], dtype=float32)]):
args: single
expected [0.24192491        nan 1.8371173         nan 1.                inf
        nan        nan]
got [0.24192491        nan 1.8371173  1.         1.                inf
        nan        nan]

Stderr:
C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py:2: RuntimeWarning: divide by zero encountered in power

C:\ci\numba_1529660792435\_test_env\lib\site-packages\numba\tests\test_ufuncs.py:2: RuntimeWarning: invalid value encountered in power

C:\ci\numba_1529660792435\_test_env\lib\unittest\case.py:545: RuntimeWarning: invalid value encountered in less_equal
  if abs(first - second) <= delta:

----------------------------------------------------------------------
Ran 6877 tests in 364.941s

FAILED (failures=2, skipped=281, expected failures=6)

(C:\ci\numba_1529660792435\_test_env) C:\ci\numba_1529660792435\test_tmp>if errorlevel 1 exit 1
```

Just posting here for the sake of public visibility. I had already shared this traceback with @stuartarchibald about 1.5 month ago.

- Surprisingly (or not?), this problem doesn't occur on the same machine for a win-32 SUBDIR build.
- If I do: `set NUMBA_DISABLE_INTEL_SVML=1`, then the test passes.
- Fails only with py27

Happy to run whatever debug steps you wish me to run.

**Comment by nehaljwani** [comment]
@seibert I can try building the RC. Could you point to the commit which fixed this issue?

**Comment by seibert** [comment]
It is this PR in llvmlite (which is actually a change to llvmdev, which then requires a rebuild of llvmlite): https://github.com/numba/llvmlite/pull/363

**Comment by seibert** [comment]
We just tagged RC1 for Numba and llvmlite, which should fix this if LLVM is rebuilt with latest conda-recipe there.

**Comment by stuartarchibald** [comment]
Resolved by https://github.com/numba/llvmlite/pull/363 closing.
