### ISSUE TITLE
array.dtype.type not working inside prange

### ISSUE THREAD

**Issue by bmerry** [numba/numba#3066]
## Reporting a bug

> - [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

I'm using the latest PyPI release (0.38.1). The CHANGE_LOG describes 0.39 but it doesn't appear to have been released.

The following code fails to compile, but changing the `numba.prange` to `range`, or setting `parallel=False`, or manually hoisting the expression `a.dtype.type(0)` into a variable set before the loop all succeed.

```python
#!/usr/bin/env python
import numpy as np
import numba

@numba.njit(parallel=True)
def func(a):
    for i in numba.prange(a.shape[0]):
        a[i] = a.dtype.type(0)

func(np.ones(10))
```

Error:
```
Traceback (most recent call last):
  File "./prange.py", line 10, in <module>
    func(np.ones(10))
  File "/home/bmerry/work/sdp/env3/lib/python3.5/site-packages/numba/dispatcher.py", line 344, in _compile_for_args
    reraise(type(e), e, None)
  File "/home/bmerry/work/sdp/env3/lib/python3.5/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed at nopython (nopython mode backend)
Failed at nopython (nopython frontend)
Unknown attribute 'type' of type class(float64)

File "prange.py", line 8:
def func(a):
    <source elided>
    for i in numba.prange(a.shape[0]):
        a[i] = a.dtype.type(0)
        ^

[1] During: typing of get attribute at ./prange.py (8)

File "prange.py", line 8:
def func(a):
    <source elided>
    for i in numba.prange(a.shape[0]):
        a[i] = a.dtype.type(0)
        ^

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.5, range = (0, $3.6, 1))]{26: <ir.Block at ./prange.py (7)>}Var(parfor_index.5, ./prange.py (7))" at ./prange.py (7)
```

**Comment by sklam** [comment]
Maybe the typing is not registered to the gufunc target

**Comment by stuartarchibald** [comment]
#3088 fixed, closing.
