### ISSUE TITLE
prange fails when array are changed with augmented assignment

### ISSUE THREAD

**Issue by kittoku** [numba/numba#3069]
**Code sample:**
```python
import numpy as np
import numba

NUM = 100

@numba.jit(nopython=True, parallel=True)
def numba_array_unary_array():
    result = np.zeros(1, np.int_)

    for i in numba.prange(NUM):
        result += np.array([i], np.int_)

    return result

print(numba_array_unary_array()) # raise numba.errors.LoweringError
```
While I was investigating `prange`'s behavior, I encountered this error. As far as I understand, it's not good to assign values to array without slice ~~or with integer indexer~~ in loops of prange (am I correct?). But the traceback let me report, so I did just in case.
(python==3.6.5, numba==0.38.0) **EDIT:** checked this can be reproduced in 0.39.0rc1
　　
**Traceback:**
<details>  

```python
Traceback (most recent call last):
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\errors.py", line 491, in new_error_context
    yield
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\lowering.py", line 365, in lower_inst
    func(self, inst)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\npyufunc\parfor.py", line 83, in _lower_parfor_parallel
    bool(alias_map), index_var_typ)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\npyufunc\parfor.py", line 357, in _create_gufunc_for_parfor_body
    typemap[arr] = types.npytypes.Array(typemap[var], 1, "C")
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\types\abstract.py", line 60, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\types\npytypes.py", line 288, in __init__
    super(Array, self).__init__(dtype, ndim, layout, name=name)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\types\common.py", line 51, in __init__
    raise TypeError("Buffer dtype cannot be buffer")
TypeError: Buffer dtype cannot be buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\dispatcher.py", line 360, in _compile_for_args
    raise e
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\dispatcher.py", line 311, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\dispatcher.py", line 618, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 871, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 365, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 802, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 789, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 251, in run
    raise patched_exception
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 243, in run
    stage()
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 676, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 626, in _backend
    lowered = lowerfn()
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 613, in backend_nopython_mode
    self.flags)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\compiler.py", line 990, in native_lowering_stage
    lower.lower()
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\errors.py", line 499, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\kittoku\Anaconda3\envs\test_env\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
Buffer dtype cannot be buffer

File "<stdin>", line 5:

[1] During: lowering "id=6[LoopNest(index_variable = parfor_index.271, range = (0, $16.3, 1))]{28: <ir.Block at <stdin> (5)>}Var(parfor_index.271, <stdin> (5))" at <stdin> (5)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If you need help writing a minimal reproducer please see:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```
</details>  

**All script:**
<details>
  
```python
import numpy as np
import numba

NUM = 100

@numba.jit(nopython=True, parallel=True)
def numba_scalar():
    result = 0

    for i in range(NUM):
        result += i

    return result

@numba.jit(nopython=True, parallel=True)
def numba_array_unary_scalar():
    result = np.zeros(1, np.int_)

    for i in numba.prange(NUM):
        result[0] += i

    return result

@numba.jit(nopython=True, parallel=True)
def numba_array_binary_array():
    result = np.zeros(1, np.int_)

    for i in numba.prange(NUM):
        result = result + np.array([i], np.int_)

    return result

@numba.jit(nopython=True, parallel=True)
def numba_array_unary_array():
    result = np.zeros(1, np.int_)

    for i in numba.prange(NUM):
        result += np.array([i], np.int_)

    return result


print(numba_scalar()) # -> 4950
print(numba_array_unary_scalar()) # -> [428]
print(numba_array_binary_array()) # -> [0]
print(numba_array_unary_array()) # raise numba.errors.LoweringError
```
</details>

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce. Also, this is broken:
```python
import numpy as np
import numba

NUM = 100

@numba.jit(nopython=True, parallel=True)
def numba_array_unary_array():
    result = np.zeros(1, np.int_)

    for i in numba.prange(NUM):
        result = result + np.array([i], np.int_)

    return result

print(numba_array_unary_array())
```
produces `[0]`.

@ehsantn @DrTodd13 any ideas? Thanks.

**Comment by kittoku** [comment]
BTW, `numba_array_unary_scalar()` failed just because of race condition, not indexer.
