### ISSUE TITLE
Segfault from test_gil_reacquire_deadlock test.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3072]
It seem that on a small number of linux machines `./runtests.py -m -b -v` fails with:
```python
Fatal Python error: Segmentation fault

Thread 0x00007f99b6c08740 (most recent call first):
  File "<numba_path>/tests/npyufunc/test_parallel_ufunc_issues.py", line 109 in test_gil_reac
quire_deadlock
  File "<env_path>/lib/python3.6/unittest/case.py", line 605 in run
  File "<env_path>/lib/python3.6/unittest/case.py", line 653 in __call__
  File "<numba_path>/testing/main.py", line 480 in __call__
  File "<env_path>/lib/python3.6/multiprocessing/pool.py", line 119 in worker
  File "<env_path>/lib/python3.6/multiprocessing/process.py", line 93 in run
  File "<env_path>/lib/python3.6/multiprocessing/process.py", line 258 in _bootstrap
  File "<env_path>/lib/python3.6/multiprocessing/popen_fork.py", line 73 in _launch
  File "<env_path>/lib/python3.6/multiprocessing/popen_fork.py", line 19 in __init__
  File "<env_path>/lib/python3.6/multiprocessing/context.py", line 277 in _Popen
  File "<env_path>/lib/python3.6/multiprocessing/process.py", line 105 in start
  File "<env_path>/lib/python3.6/multiprocessing/pool.py", line 239 in _repopulate_pool
  File "<env_path>/lib/python3.6/multiprocessing/pool.py", line 174 in __init__
  File "<env_path>/lib/python3.6/multiprocessing/context.py", line 119 in Pool
  File "<numba_path>/testing/main.py", line 558 in _run_inner
  File "<env_path>/lib/python3.6/unittest/runner.py", line 176 in run
  File "<numba_path>/testing/main.py", line 607 in run
  File "<env_path>/lib/python3.6/unittest/main.py", line 256 in runTests
  File "<numba_path>/testing/main.py", line 211 in run_tests_real
  File "<numba_path>/testing/main.py", line 226 in runTests
  File "<env_path>/lib/python3.6/unittest/main.py", line 95 in __init__
  File "<numba_path>/testing/main.py", line 127 in __init__
  File "<numba_path>/testing/__init__.py", line 70 in run_tests
  File "<numba_path>/runtests.py", line 23 in _main
  File "<numba_path>/runtests.py", line 116 in <module>
  File "<env_path>/lib/python3.6/runpy.py", line 85 in _run_code
  File "<env_path>/lib/python3.6/runpy.py", line 208 in run_module
  File "./runtests.py", line 11 in <module>
```
All Anaconda Python versions (and at least conda-forge Python 3.6) seems to be affected.

After a considerable amount of debugging, this reproduces similar behaviour outside of Numba using just the core Python modules:
```python
from multiprocessing import Pool
import multiprocessing as mp
import ctypes
from sys import version_info

def test_func(*args):
  for x in range(50):
      proto = ctypes.CFUNCTYPE(None, ctypes.c_int32)
      characters = 'abcdefghij'
      def bar(x):
        print(characters[x])
      cbar = proto(bar)

if __name__ == '__main__':
    if version_info >= (3, 0):
        mp.set_start_method('fork')
    with Pool(5) as p:
        print(p.map(test_func, [1, 2, 3]))
```
Anaconda Python 3 series typically hang, Anaconda Python 2 series typically produce:
```
Traceback (most recent call last):
  File "foo.py", line 17, in <module>
    with Pool(5) as p:
AttributeError: __exit__
```
When using system Python from Centos 7 and Fedora 28, both Python 2 and 3 seem to work as expected. This does not reproduce on OSX. This does not reproduce when using a `multiprocessing.start_method` of `forkserver` or `spawn`.

I think what's happening in the Numba test suite is that there are multiple processes from the `fork(3)`'s called in the `multiprocessing` backed test runner. The tests running at the time of failure always seem to include the two `test_gil_reacquire_deadlock` tests, which are running from separate processes (augmented output demonstrates):
```
Proc: <ForkProcess(ForkPoolWorker-7, started daemon)> test_gil_reacquire_deadlock (numba.tests.npyufunc.test_parallel_ufunc_issues.TestParGUfuncIssues)
test_remainder_int (numba.tests.npyufunc.test_errors.TestFloatingPointExceptions) ... ok
Proc: <ForkProcess(ForkPoolWorker-8, started daemon)> test_gil_reacquire_deadlock (numba.tests.npyufunc.test_parallel_ufunc_issues.TestParUfuncIssues)
```
as a result, if a machine is particularly unlucky, both of the processes hit the problematic `ctypes` behaviour (as per the example above) and a segfault ensues. Hacking at the tests a bit, removing any Numba compilation and just rewriting the `test_gil_reacquire_deadlock` tests via a timing attack style approach yielded similar results as the reproducer above. All of which makes me think this is not a Numba problem, but Numba needs a temporary fix to work around hitting the problem.

**Comment by stuartarchibald** [comment]
Closing. Not a Numba bug.
