### ISSUE TITLE
Issue with decorators

### ISSUE THREAD

**Issue by astrojuanlu** [numba/numba#3090]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I am playing with very simple decorators that use `functools.wraps`:

```
In [1]: from functools import wraps

In [2]: def dec_simple(func):
   ...:     @wraps(func)
   ...:     def wrapper():
   ...:         return func(1.0)
   ...: 
   ...:     return wrapper
   ...: 
   ...: 

In [3]: def fun(a):
   ...:     return a
   ...: 
   ...: 

In [4]: fun(1.0)
Out[4]: 1.0

In [5]: fun(2.0)
Out[5]: 2.0

In [6]: f = dec_simple(fun)

In [7]: f()
Out[7]: 1.0

In [8]: f(1.0)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-8-8afb63b2369d> in <module>()
----> 1 f(1.0)

TypeError: wrapper() takes 0 positional arguments but 1 was given

```

However, when I use `numba.jit` on the result, things are not working as expected:

```
In [9]: import numba

In [10]: fn = numba.jit(f)

In [11]: fn()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-e1d0f67027b9> in <module>()
----> 1 fn()

TypeError: not enough arguments: expected 1, got 0

In [12]: fn(1.0)
Out[12]: 1.0

In [13]: fn(2.0)
Out[13]: 1.0

In [14]: fn.inspect_types()
fun (float64,)
--------------------------------------------------------------------------------
# File: <ipython-input-2-44d925f42355>
# --- LINE 1 --- 

def fun(a):

    # --- LINE 2 --- 
    # label 0

    return a


================================================================================
```

This happened while exploring #2328 and our own issues. I tested with numba 0.38, 0.38.1 and 0.39rc1.

**Comment by Juanlu001** [comment]
With latest numba and llvmlite, this fails earlier:

```
In [10]: fn = numba.njit(f)                                                                                                             

In [11]: fn()                                                                                                                           
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-e1d0f67027b9> in <module>
----> 1 fn()

TypeError: not enough arguments: expected 1, got 0

In [12]: fn(1.0)                                                                                                                        
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-12-9b2360656022> in <module>
----> 1 fn(1.0)

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    348                 e.patch_message(msg)
    349 
--> 350             error_rewrite(e, 'typing')
    351         except errors.UnsupportedError as e:
    352             # Something unsupported is present in the user code, add help info

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    315                 raise e
    316             else:
--> 317                 reraise(type(e), e, None)
    318 
    319         argtypes = []

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'func': cannot determine Numba type of <class 'function'>

File "<ipython-input-2-b757d3295c2b>", line 4:
    def wrapper():
        return func(1.0)
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by Juanlu001** [comment]
Simpler case, without `functools`

```
In [26]: def dec_simple(func): 
    ...:     def wrapper(): 
    ...:         return func(1.0) 
    ...:     return wrapper 
    ...:                                                                                                                                

In [27]: f = dec_simple(fun)                                                                                                            

In [28]: fn = numba.njit(f)                                                                                                             

In [29]: fn()                                                                                                                           
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-29-e1d0f67027b9> in <module>
----> 1 fn()

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    348                 e.patch_message(msg)
    349 
--> 350             error_rewrite(e, 'typing')
    351         except errors.UnsupportedError as e:
    352             # Something unsupported is present in the user code, add help info

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    315                 raise e
    316             else:
--> 317                 reraise(type(e), e, None)
    318 
    319         argtypes = []

~/.miniconda36/envs/poliastro37/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'func': cannot determine Numba type of <class 'function'>

File "<ipython-input-26-3cda2bcc542c>", line 3:
    def wrapper():
        return func(1.0)
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by stuartarchibald** [comment]
I think this is because Numba doesn't know about function `fun` in `nopython` mode and as a result the code is effectively asking to call an unknown global, if however the `fun` function is jitted first it should be ok:
```python
import numba

def dec_simple(func):
    def wrapper():
        return func(1.0)
    return wrapper

@numba.njit()
def fun(a):
    return a

f = dec_simple(fun)

fn = numba.njit(f)

print(fn())
```

**Comment by stuartarchibald** [comment]
Closing this issue as no new information has been provided. It is assumed that the above resolved the reported issue, if this is not the case please reopen the issue with new information. Many thanks.
