### ISSUE TITLE
`test_optional_unpack` Heisenbug

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3098]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

Entirely valid changes are causing the build to fail, e.g. https://github.com/numba/numba/pull/3089 is valid and Travis CI reports https://travis-ci.org/numba/numba/builds/402276101?utm_source=github_status&utm_medium=notification

It would appear that the pattern of failure is somewhat random, no specific Python/NumPy combination is to blame, the failure pattern also shifts between builds. e.g. https://travis-ci.org/numba/numba/builds/402717102?utm_source=github_status&utm_medium=notification from https://github.com/numba/numba/pull/3096 has a different pattern.

I guessed at https://github.com/numba/numba/pull/3059 and https://github.com/numba/numba/pull/3060 being around the time when the errors started appearing. Applying a series of patch reverts to undo those patches gives this: https://travis-ci.org/numba/numba/builds/402765820?utm_source=github_status&utm_medium=notification i.e. everything passes apart from Py3.7 which is due to some issue with the dependent package support opposed to Numba itself.

The failing test is consistently:
```
======================================================================
ERROR: test_optional_unpack (numba.tests.test_optional.TestOptional)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/numba/numba/numba/tests/test_optional.py", line 239, in test_optional_unpack
    self.assertEqual(pyfunc((1, 2)), cfunc((1, 2)))
  File "/home/travis/build/numba/numba/numba/dispatcher.py", line 464, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) tuple(int64 x 2)
----------------------------------------------------------------------
```

I have not been able to reproduce locally on any combination of hardware, Pythons and NumPys.

Given the nature of the changes in #3059, I'm wondering if the legalization pass prevents some compilation pipeline side effect upon which Numba was relying.

**Comment by stuartarchibald** [comment]
Things it is not:
 * fork vs. spawn in the parallel test runner.
 * dictionary iteration order.

**Comment by stuartarchibald** [comment]
Closing. This bug has not appeared for about 3 years.
