### ISSUE TITLE
test_deadlock_on_exception failing on CUDA testers

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3100]
* Reporting a bug.

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Since merging: https://github.com/numba/numba/pull/3067

The CUDA testers on the build farm are all failing with:
```
======================================================================
FAIL: test_deadlock_on_exception (numba.cuda.tests.cudasim.test_cudasim_issues.TestCudaSimIssues)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\tests\cudasim\test_cudasim_issues.py", line 65, in test_deadlock_on_exception
    assign_with_sync[1, 6](x, y)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\simulator\kernel.py", line 95, in __call__
    bm.run(grid_point, *fake_args)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\simulator\kernel.py", line 254, in run
    reraise(*(t.exception))
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\simulator\kernel.py", line 153, in run
    super(BlockThread, self).run()
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\simulator\kernel.py", line 232, in target
    self._f(*args)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\tests\cudasim\test_cudasim_issues.py", line 52, in assign_with_sync
    y[i] = x[i]
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\cudadrv\devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\cudadrv\devicearray.py", line 453, in __getitem__
    return self._do_getitem(item)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\cuda\cudadrv\devicearray.py", line 463, in _do_getitem
    arr = self._dummy.__getitem__(item)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\dummyarray.py", line 244, in __getitem__
    dims = [dim.__getitem__(it) for dim, it in zip(self.dims, item)]
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\dummyarray.py", line 104, in __getitem__
    return Dim(start, stop, size, stride, single)
  File "c:\conda64\conda-bld\numba_1531346859726\_test_env\lib\site-packages\numba\dummyarray.py", line 53, in __init__
    assert not single or size == 1
AssertionError: tid=[4, 0, 0] ctaid=[0, 0, 0]

----------------------------------------------------------------------
Ran 463 tests in 77.236s

FAILED (failures=1, skipped=25, expected failures=1)
```

**Comment by stuartarchibald** [comment]
Fixed by https://github.com/numba/numba/pull/3125
