### ISSUE TITLE
parfors lowering error

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3103]
This:
```python
from numba import njit, prange

@njit(parallel=True)
def foo(x, y):
    for j in prange(y): 
        k = x
    return k

print(foo(10, 20))
```
does this:
```
$ python broken1.py 
Traceback (most recent call last):
  File "<path>/numba/numba/errors.py", line 595, in new_error_context
    yield
  File "<path>/numba/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "<path>/numba/numba/lowering.py", line 449, in lower_assign
    return self.lower_expr(ty, value)
  File "<path>/numba/numba/lowering.py", line 933, in lower_expr
    val = self.loadvar(expr.value.name)
  File "<path>/numba/numba/lowering.py", line 966, in loadvar
    ptr = self.getvar(name)
  File "<path>/numba/numba/lowering.py", line 960, in getvar
    return self.varmap[name]
KeyError: 'k'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "broken1.py", line 8, in <module>
    print(foo(10, 20))
  File "<path>/numba/numba/dispatcher.py", line 368, in _compile_for_args
    raise e
  File "<path>/numba/numba/dispatcher.py", line 325, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<path>/numba/numba/dispatcher.py", line 653, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>/numba/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "<path>/numba/numba/compiler.py", line 881, in compile_extra
    return pipeline.compile_extra(func)
  File "<path>/numba/numba/compiler.py", line 368, in compile_extra
    return self._compile_bytecode()
  File "<path>/numba/numba/compiler.py", line 812, in _compile_bytecode
    return self._compile_core()
  File "<path>/numba/numba/compiler.py", line 799, in _compile_core
    res = pm.run(self.status)
  File "<path>/numba/numba/compiler.py", line 254, in run
    raise patched_exception
  File "<path>/numba/numba/compiler.py", line 246, in run
    stage()
  File "<path>/numba/numba/compiler.py", line 679, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "<path>/numba/numba/compiler.py", line 629, in _backend
    lowered = lowerfn()
  File "<path>/numba/numba/compiler.py", line 616, in backend_nopython_mode
    self.flags)
  File "<path>/numba/numba/compiler.py", line 1000, in native_lowering_stage
    lower.lower()
  File "<path>/numba/numba/lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "<path>/numba/numba/lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "<path>/numba/numba/lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "<path>/numba/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "<env>/numba_latest/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "<path>/numba/numba/errors.py", line 603, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "<path>/numba/numba/errors.py", line 595, in new_error_context
    yield
  File "<path>/numba/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "<path>/numba/numba/lowering.py", line 449, in lower_assign
    return self.lower_expr(ty, value)
  File "<path>/numba/numba/lowering.py", line 933, in lower_expr
    val = self.loadvar(expr.value.name)
  File "<path>/numba/numba/lowering.py", line 966, in loadvar
    ptr = self.getvar(name)
  File "<path>/numba/numba/lowering.py", line 960, in getvar
    return self.varmap[name]
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
'k'

File "broken1.py", line 6:
def foo(x, y):
    <source elided>
        k = x
    return k
    ^
[1] During: lowering "$22.2 = cast(value=k)" at broken1.py (6)
```
it works with `parallel=False`.

**Comment by DrTodd13** [comment]
It's not a bug, it's a feature. :)  If different iterations of prange assign different values then it is a race and if they assign the same value it is pointless.  I'd like to see a larger example that shows how this might actually do something useful in practice.  So, one possibility is to just print a better error message if we can't think of a reason why anyone should ever legitimately do this.  If we really want to duplicate Python behavior then I'll see if there is an easy fix.

**Comment by stuartarchibald** [comment]
I think this behaviour is not particularly useful (as noted :), what I was alarmed at was the backtrace/exception. Not only is it a `LoweringError`, it also has the error message containing solely the letter `k`. Can this sort of pattern be spotted ahead of lowering and a better error message raised instead? Seems like the backtrace doesn't have anything parfors related in it, so I guess the transforms have just created illegal IR.

**Comment by DrTodd13** [comment]
Working in master.
