### ISSUE TITLE
function defined with @guvectorize target='cuda' but not used (and no NVIDIA card) gives error

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3113]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```
CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBAPRO_CUDA_DRIVER
with the file path of the CUDA driver shared library.
```

**Comment by stuartarchibald** [comment]
NOTE: edited report so that the markdown renders.

**Comment by stuartarchibald** [comment]
Thanks for the report. Here's a reproducer:
```python
import numba as nb
import numpy as np

@nb.guvectorize([(nb.int64[:], nb.int64, nb.int64[:])], '(n),()->(n)', target='cuda')
def g(x, y, res):
    for i in range(x.shape[0]):
        res[i] = x[i] + y


x = np.arange(10)
y = np.arange(10)
z = np.arange(10)
g(x, y, z)
```
On a machine with no CUDA GPU gives:
```
$ python issue3113.py 
Traceback (most recent call last):
  File "issue3113.py", line 4, in <module>
    @nb.guvectorize([(nb.int64[:], nb.int64, nb.int64[:])], '(n),()->(n)', target='cuda')
  File "<path>/numba/npyufunc/decorators.py", line 179, in wrap
    guvec.add(fty)
  File "<path>/numba/npyufunc/deviceufunc.py", line 481, in add
    kernel = self._compile_kernel(fnobj, sig=tuple(outertys))
  File "<path>/numba/cuda/vectorizers.py", line 55, in _compile_kernel
    return cuda.jit(sig)(fnobj)
  File "<path>/numba/cuda/decorators.py", line 96, in kernel_jit
    kernel.bind()
  File "<path>/numba/cuda/compiler.py", line 495, in bind
    self._func.get()
  File "<path>/numba/cuda/compiler.py", line 369, in get
    cuctx = get_context()
  File "<path>/numba/cuda/cudadrv/devices.py", line 194, in get_context
    return _runtime.get_or_create_context(devnum)
  File "<path>/numba/cuda/cudadrv/devices.py", line 162, in get_or_create_context
    return self.push_context(self.gpus[devnum])
  File "<path>/numba/cuda/cudadrv/devices.py", line 40, in __getitem__
    return self.lst[devnum]
  File "<path>/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "<path>/numba/cuda/cudadrv/driver.py", line 334, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "<path>/numba/cuda/cudadrv/driver.py", line 272, in __getattr__
    self.initialization_error)
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: 

CUDA driver library cannot be found.
If you are sure that a CUDA driver is installed,
try setting environment variable NUMBAPRO_CUDA_DRIVER
with the file path of the CUDA driver shared library.
:
```
Also, if a CUDA GPU is present but no CUDA toolkit, then this happens:
```
Traceback (most recent call last):
  File "<path>/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 111, in __new__
    inst.driver = open_cudalib('nvvm', ccc=True)
  File "<path>/lib/python3.7/site-packages/numba/cuda/cudadrv/libs.py", line 48, in open_cudalib
    raise OSError('library %s not found' % lib)
OSError: library nvvm not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "foo.py", line 4, in <module>
    @nb.guvectorize([(nb.int64[:], nb.int64, nb.int64[:])], '(n),()->(n)', target='cuda')
  File "<path>/lib/python3.7/site-packages/numba/npyufunc/decorators.py", line 179, in wrap
    guvec.add(fty)
  File "<path>/lib/python3.7/site-packages/numba/npyufunc/deviceufunc.py", line 481, in add
    kernel = self._compile_kernel(fnobj, sig=tuple(outertys))
  File "<path>/lib/python3.7/site-packages/numba/cuda/vectorizers.py", line 55, in _compile_kernel
    return cuda.jit(sig)(fnobj)
  File "<path>/lib/python3.7/site-packages/numba/cuda/decorators.py", line 96, in kernel_jit
    kernel.bind()
  File "<path>/lib/python3.7/site-packages/numba/cuda/compiler.py", line 495, in bind
    self._func.get()
  File "<path>/lib/python3.7/site-packages/numba/cuda/compiler.py", line 373, in get
    ptx = self.ptx.get()
  File "<path>/lib/python3.7/site-packages/numba/cuda/compiler.py", line 345, in get
    **self._extra_options)
  File "<path>/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 474, in llvm_to_ptx
    cu = CompilationUnit()
  File "<path>/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 146, in __init__
    self.driver = NVVM()
  File "<path>/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 116, in __new__
    raise NvvmSupportError(errmsg % e)
numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`:
library nvvm not found
Exception ignored in: <function CompilationUnit.__del__ at 0x7f43f5423048>
Traceback (most recent call last):
  File "<path>/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 152, in __del__
    driver = NVVM()
  File "<path>/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 116, in __new__
    raise NvvmSupportError(errmsg % e)
numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`:
library nvvm not found
```

The reason for this behaviour is that `guvectorize` decorated functions are compiled at the site of declaration, there is no lazy-JIT as present with most of the other decorators. I do not think it is possible to decouple the compilation chain from the driver/runtime bindings. It might be best to just put in a workaround and wrap `numba.guvectorize` in a function that calls `numba.cuda.is_available()` to check whether CUDA is present and adjust the target accordingly?

**Comment by cristipurdel** [comment]
I made it work with try/except and @numba.cuda.is_available()
For extra info also @numba.cuda.detect() is helpful
