### ISSUE TITLE
parfors hoist set item fail

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3155]
On the build farm, the latest builds of master 5215237 have failures for:
```
test_parfor_hoist_setitem (numba.tests.test_parfors.TestParfors)
```
guessing that #3089 is the root cause. Fails so far have appeared on w64 and power8. The error message is like:
```
======================================================================
FAIL: test_parfor_hoist_setitem (numba.tests.test_parfors.TestParfors)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<path>numba/tests/test_parfors.py", line 1133, in test_parfor_hoist_setitem
    self.check(test_impl, out)
  File "<path>numba/tests/test_parfors.py", line 462, in check
    self.check_parfors_vs_others(pyfunc, cfunc, cpfunc, *args, **kwargs)
  File "<path>numba/tests/test_parfors.py", line 144, in check_parfors_vs_others
    np.testing.assert_almost_equal(parfor_output, py_expected, **kwargs)
  File "<path>numpy/testing/nose_tools/utils.py", line 581, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 256.0
 DESIRED: 1024.0
```
sometimes ACTUAL is, 128 or 512, too.

CC @DrTodd13

**Comment by DrTodd13** [comment]
Hmm.  I think this came from a customer who was using the ParallelAccelerator optimizations but not its parallelism (always runs with NUMBA_NUM_THREADS=1).  It seems like test_parfor_hoist_setitem is actually a reduction but it doesn't seem like it is detected as such.
