### ISSUE TITLE
np.eye() does not support dtype argument, which is not stated in the docs and does not return meaningful error code

### ISSUE THREAD

**Issue by qwert1337** [numba/numba#3159]
## Reporting a bug

- Version 0.36.2
- np.eye() does not support the dtype argument, which is not stated in the docs and does not return a meaningful error code

`import numpy as np`
`import numba as nb`

`@nb.jit(nb.float32[:,:](nb.int64),nopython=True)`
`def eye(n):`
`    out = np.eye(n,dtype=np.float32)`
`    return out`

**Comment by stuartarchibald** [comment]
Thanks for the report. The doc for `numpy.eye()` clearly needs updating. As to meaningful errors, I'd really recommend updating your Numba installation to version 0.39 (latest), 0.38 got a large rewrite of the error reporting code and 0.39 got even more! For me, on 0.39 I get:
```python
numba.errors.TypingError: Failed at nopython (nopython frontend)
Invalid usage of Function(<function eye at 0x7f812b665730>) with parameters (int64, dtype=class(float32))
 * parameterized
In definition 0:
    TypingError: unsupported call signature
    raised from<path>/numba/typing/templates.py:263
[1] During: resolving callee type: Function(<function eye at 0x7f812b665730>)
[2] During: typing of call at issue3159.py (6)


File "issue3159.py", line 6:
def eye(n):
    out = np.eye(n,dtype=np.float32)
    ^
```
I've also updated this in the current development work for 0.40 so it says:
```python
numba.errors.TypingError: Failed at nopython (nopython frontend)
Invalid use of Function(<function eye at 0x7f590fec6730>) with argument(s) of type(s): (int64, dtype=class(float32))
 * parameterized
In definition 0:
    TypingError: unsupported call signature
    raised from <path>/numba/typing/templates.py:263
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function eye at 0x7f590fec6730>)
[2] During: typing of call at issue3159.py (6)


File "issue3159.py", line 6:
def eye(n):
    out = np.eye(n,dtype=np.float32)
```
which has the included hint:
```
This error is usually caused by passing an argument of a type that is unsupported by the named function.
```

**Comment by stuartarchibald** [comment]
Also if you install `colorama`, the error messages are color highlighted. If you decide to update, please let us know what you think, we are always interested in feedback.

**Comment by bencbartlett** [comment]
I'm also having this problem (I need to instantiate a `np.complex128` matrix with `np.eye()`). What is the best workaround for this?

**Comment by qwert1337** [comment]
You can use np.zeros and set the diagonal manually.

**Comment by stuartarchibald** [comment]
The implementation itself is now fixed in the pending PR: https://github.com/numba/numba/pull/3481

This should also work for basic "want a square identity matrix" use cases:
```python
import numba as nb
import numpy as np

@nb.jit(nb.complex128[:,:](nb.int64),nopython=True)
def eye(n):
    out = np.identity(n, nb.complex128)
    return out

print(eye(3))
```
as should this for the more complicated `np.eye` implementation (note necessity to supply all kwargs):
```python
import numba as nb
import numpy as np

@nb.jit(nb.complex128[:,:](nb.int64),nopython=True)
def eye(n):
    out = np.eye(N=n, M=n, k=0, dtype=nb.complex128)
    return out

print(eye(3))
```

**Comment by gersonjferreira** [comment]
Please reopen this issue. The solution above works with the np.identity example, but does not work with np.eye. I've simply tried copy-pasting the code above... it fails.

**Comment by esc** [comment]
@gersonjferreira thanks for reporting this. I will re-open the issue shortly. To follow up, could you please add, which code you tried to run and what the error message was that you received. Thanks!

**Comment by gersonjferreira** [comment]
I've tried to run the np.eye code above, exactly as it is:

```python
import numba as nb
import numpy as np

@nb.jit(nb.complex128[:,:](nb.int64),nopython=True)
def eye(n):
    out = np.eye(N=n, M=n, k=0, dtype=nb.complex128)
    return out

print(eye(3))
```
But in my case the code that I really need is for k != 0 and simple floats as well, like this:

```python
@nb.jit(nb.float64[:,:](nb.int64, nb.int64), nopython=True)
def eye(n, k):
    out = np.eye(N=n, M=n, k=k, dtype=nb.float64)
    return out

print(eye(3, 1))
```
I'm using Manjaro Linux with python 3.8. Could it be a compatibility issue? Should I use a previous python version? Here's the error message:

```python
/usr/lib/python3.8/site-packages/numba/dataflow.py:58: RuntimeWarning: inconsistent stack offset for block(offset:124, outgoing: [], incoming: [78, 102])
  warnings.warn("inconsistent stack offset for %s" % blk,
/usr/lib/python3.8/site-packages/numba/dataflow.py:58: RuntimeWarning: inconsistent stack offset for block(offset:124, outgoing: [], incoming: [78, 102])
  warnings.warn("inconsistent stack offset for %s" % blk,
Traceback (most recent call last):

  File "<ipython-input-1-f1ecfca255c1>", line 1, in <module>
    runfile('/home/gerson/.config/spyder-py3/temp.py', wdir='/home/gerson/.config/spyder-py3')

  File "/usr/lib/python3.8/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "/usr/lib/python3.8/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "/home/gerson/.config/spyder-py3/temp.py", line 5, in <module>
    def eye(n):

  File "/usr/lib/python3.8/site-packages/numba/decorators.py", line 201, in wrapper
    disp.compile(sig)

  File "/usr/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)

  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 81, in compile
    raise retval

  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)

  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,

  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)

  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 326, in compile_extra
    return self._compile_bytecode()

  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 385, in _compile_bytecode
    return self._compile_core()

  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 365, in _compile_core
    raise e

  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 356, in _compile_core
    pm.run(self.state)

  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 328, in run
    raise patched_exception

  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)

  File "/usr/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)

  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)

  File "/usr/lib/python3.8/site-packages/numba/typed_passes.py", line 89, in run_pass
    typemap, return_type, calltypes = type_inference_stage(

  File "/usr/lib/python3.8/site-packages/numba/typed_passes.py", line 66, in type_inference_stage
    infer.propagate()

  File "/usr/lib/python3.8/site-packages/numba/typeinfer.py", line 951, in propagate
    raise errors[0]

TypingError: Invalid use of Function(<function eye at 0x7f42cf7905e0>) with argument(s) of type(s): (M=int64, N=int64, dtype=class(complex128), k=Literal[int](0))
 * parameterized
In definition 0:
    AssertionError: Failed in nopython mode pipeline (step: analyzing bytecode)

    raised from /usr/lib/python3.8/site-packages/numba/dataflow.py:893
In definition 1:
    AssertionError: Failed in nopython mode pipeline (step: analyzing bytecode)

    raised from /usr/lib/python3.8/site-packages/numba/dataflow.py:893
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function eye at 0x7f42cf7905e0>)
[2] During: typing of call at /home/gerson/.config/spyder-py3/temp.py (6)
```

**Comment by stuartarchibald** [comment]
@gersonjferreira I think the issue here may be that of using Python 3.8, which is not supported on any released version of Numba (cf. https://github.com/numba/numba/blob/master/README.rst). The next release of Numba (0.47.0, a release candidate for which will hopefully be out this week) does support Python 3.8. I cannot replicate the issue reported on Numba 0.46 with Python 3.7, or from current Numba master branch with Python 3.8.

**Comment by gersonjferreira** [comment]
@stuartarchibald, yes... I've noticed that while I was writing the previous message! I like Manjaro on my desktop and notebook to keep things well updated while stable-ish. But python shouldn't be updated so often. On my server I keep a python virtualenv on a leash, there it is working fine, I've just tested. Sorry for the trouble, it was my mistake indeed!

**Comment by stuartarchibald** [comment]
@gersonjferreira no problem, thanks for checking back and for using Numba!

**Comment by esc** [comment]
@gersonjferreira indeed, no worries about causing some trouble and thanks for reporting back so diligently, we do appreciate the effort! If you hit any snags in future please don't hesitate to open a new issue!
