### ISSUE TITLE
how to use python / numba / @vectorize non-scalar input

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3164]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I posted this also over stackoverflow

I want to try to force to have as input an array instead of a normal scalar The solution should work for numba/vectorize (not interested in guvectorize) and also be applicable for parallel/cuda target

1st issue: When running the code, temp2 is seen as a list with 3 elements, but I cannot find a way to access the individual elements

2nd issue: When running the 'cuda' target I am getting this (although it is working on cpu & parallel) error :

```
Traceback (most recent call last):
  File "D:\Share\Documents\Python\xlwings\myproject\in_out_non_scalar.py", line 61, in <module>
    r = f(data, temp1, c)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\dispatcher.py", line 88, in __call__
    return CUDAUFuncMechanism.call(self.functions, args, kws)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\npyufunc\deviceufunc.py", line 248, in call
    args = cr.get_arguments()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\npyufunc\deviceufunc.py", line 204, in get_arguments
    self._fill_arrays()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\npyufunc\deviceufunc.py", line 105, in _fill_arrays
    raise TypeError("argument #%d has invalid type" % (i + 1,))
TypeError: argument #2 has invalid type
```

3rd issue It is not necessarily to have a list/array as input, it could be also a tuple, string or dictionary But I cannot manage to make it work as input, see dic, lis, tup, st variables

I have the following code: 

```
import numpy as np
import numba
from numba import vectorize, int32, float32
import pdb
import math
from timeit import default_timer as timer

SQRT_TWOPI = np.float32(math.sqrt(2 * math.pi))
x0 = 0
sigma = 1

def v_b1(x, temp2, count):
    temp = [2, 3, 5]

    if count == 1:
        x = math.exp(-((x - x0) / sigma)**2 / 2) / SQRT_TWOPI / sigma
    elif count == 8:
        x = x0 + sigma * count
    else:
        x = count * 10          # 5th issue : will output array with 3 elements as if which is a bit weired         
#        x = 1 + temp2 ** 0.5    # 2nd issue : will output array correctly calculated with 3 elements
#        x = temp[1]             # 1st issue kind of related : cannot retrieve value!!!
    return x

v_int = v_b1

v_cpu = numba.vectorize(['float32(float32, int32, int32)'], target = 'cpu')(v_int)
v_parallel = numba.vectorize(['float32(float32, int32, int32)'], target = 'parallel')(v_int)
v_cuda = numba.vectorize(['float32(float32, int32, int32)'], target = 'cuda')(v_int)

N = 1000

print('for function ' + str(v_int.__name__) + ' is CUDA available? ' + str(numba.cuda.is_available()))
if numba.cuda.is_available():
    print (numba.cuda.detect())

if numba.cuda.is_available() == False:
    avail = [v_cpu, v_parallel]
else:
    avail = [v_cpu, v_parallel, v_cuda]

data = np.random.uniform(-3, 3, size=N).astype(np.float32)
data = data[:,np.newaxis]

#3rd issue
dic = [{x:x+1, x+1:x+2, x+2:x+3} for x in range(N)]

lis = []
for n in range(N):
    lis.append([n, n+1, n+2])

st = [str(x)+'/'+str(x+1)+'/'+str(x+2) for x in range(N)]

tup = []
for n in range(N):
    tup.append((n, n+1, n+2))

temp1 = lis

for c in [1, 8, 64, 512]:
    print(c)
    for f in avail:
        start = timer()

        r = f(data, temp1, c)

        elapsed_time = timer() - start
        print("Time: {}".format(elapsed_time))
```
4th issue will update in the code later on
It appears that when using 'parallel' I can retrieve values from a list insider @vectorize 
But 'cuda' does not accept that, see also responses from  Robert Crovella ( target = 'cuda' compilation doesn't understand python lists, AFAIK ) from stackoverflow

5th issue
I find it a bit weird that  `x = count * 10 `is outputing an array instead of a constant

I am using numba 0.38 since I got some crashes on my CUDA machine.
Overall I find it annoying that:
1. Some things work for 'parallel' but not for 'cuda'
2. I do not want to use guvectorize since I feel more comfortable with vectorize
3. What I want at the end is also run some list/arrays calculation inside the ufunc, not just scalar operations. Because I am really not that much impressed if 'cuda' is only about "pure scalar" or "pure matrix" calculations.
Any insights?

**Comment by seibert** [comment]
Some of the issues you raise here are usability issues that we could fix (such as automatically applying the equivalent of `np.asarray()` to array-like arguments, like lists).

Many of the other limitations come about because we are trying to mimic the behavior of NumPy ufuncs, which do not have a generic way to indicate that some array-like values should be exempted from broadcasting.  (In a few cases, one can make generalized ufuncs behave this way, but it isn't generalizable.)  This would also allow us to pass through more kinds of objects, and generally make ufuncs much more usable.

Progress on this will happen after we can refactor some of our ufunc machinery to fully disconnect it from the NumPy dispatcher, which interferes with implementing some of the suggestions you and others have made.

**Comment by seibert** [comment]
Agreed.  There are several things we can do to make hybrid computing easier.

**Comment by cristipurdel** [comment]
Is there a timeline when the refactoring of the ufunc machinery will happen?

From what I ran, `vectorize `is much faster/easy to implement than `guvectorize`, but 
I cannot pass array-like objects
and I cannot access info from nDimensional arrays

**Comment by seibert** [comment]
We plan to do the first level of ufunc refactoring this year, but that won't change any of the interfaces yet.  It will just switch everything over to using Numba for dispatch (which will then allow us to explore more options for function signatures).

**Comment by cristipurdel** [comment]
numba version used: 0.40.0rc1 >>> getting similar results

modified the previous example in order to be similar to `guvectorize `: 

```
import numpy as np
import numba
from numba import vectorize, int32, float32
import pdb
import math
from timeit import default_timer as timer

SQRT_TWOPI = np.float32(math.sqrt(2 * math.pi))
x0 = 0
sigma = 1

def v_b1(x, temp2):
#    temp = [2, 3, 5]
    count = 16
    
    

    if count == 1:
        x = math.exp(-((x - x0) / sigma)**2 / 2) / SQRT_TWOPI / sigma
    elif count == 8:
        x = x0 + sigma * count
    else:
        x = count * 10          # 5th issue : will output array with 3 elements as if which is a bit weired         
        x = 1 + temp2 ** 0.5    # 2nd issue : will output array correctly calculated with 3 elements
        x = temp2[0]            # 1st issue kind of related : cannot retrieve value!!!
#        for x1 in temp2:
#            x = x1
    return x

v_int = v_b1

v_cpu = numba.vectorize(['float32(float32, int32)'], target = 'cpu')(v_int)
v_parallel = numba.vectorize(['float32(float32, int32)'], target = 'parallel')(v_int)
v_cuda = numba.vectorize(['float32(float32, int32)'], target = 'cuda')(v_int)

N = 1000

print('for function ' + str(v_int.__name__) + ' is CUDA available? ' + str(numba.cuda.is_available()))
if numba.cuda.is_available():
    print (numba.cuda.detect())

if numba.cuda.is_available() == False:
    avail = [v_cpu]
else:
    avail = [v_cuda]

data = np.random.uniform(-3, 3, size=N).astype(np.float32)
data = data[:,np.newaxis]



#data3 = np.concatenate((data, data, data), axis=1)
np3 = np.ones((N,3)).astype(np.int32)
#data3 = np.reshape((N,3)).astype(np.int32)

#3rd issue
dic = [{x:x+1, x+1:x+2, x+2:x+3} for x in range(N)]

lis = []
for n in range(N):
    lis.append([n, n+1, n+2])

st = [str(x)+'/'+str(x+1)+'/'+str(x+2) for x in range(N)]

tup = []
for n in range(N):
    tup.append((n, n+1, n+2))

lnp = [0] * N
for n in range(N):
    lnp[n] = np.ones(3).astype(np.int32)
    
#np2 = np.ones(N).astype(np.int32)
#for n in range(N):
#    np2[n] = np.ones(3).astype(np.int32)

temp1 = lnp

for c in [1, 8, 64, 512]:
    print(c)
    for f in avail:
        start = timer()

        r = f(data, temp1)

        elapsed_time = timer() - start
        print("Time: {}".format(elapsed_time))
```

Traceback error

```
Traceback (most recent call last):

  File "<ipython-input-15-d1d62a736b04>", line 1, in <module>
    runfile('D:/Share/Documents/Python/GitHub/3164_2.py', wdir='D:/Share/Documents/Python/GitHub')

  File "C:\Users\aw004ng\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\aw004ng\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:/Share/Documents/Python/GitHub/3164_2.py", line 33, in <module>
    v_parallel = numba.vectorize(['float32(float32, int32)'], target = 'parallel')(v_int)

  File "C:\Users\aw004ng\Anaconda3\lib\site-packages\numba\npyufunc\decorators.py", line 123, in wrap
    return vec.build_ufunc()

  File "C:\Users\aw004ng\Anaconda3\lib\site-packages\numba\npyufunc\ufuncbuilder.py", line 234, in build_ufunc
    dtypenums, ptr, env = self.build(cres, sig)

  File "C:\Users\aw004ng\Anaconda3\lib\site-packages\numba\npyufunc\parallel.py", line 159, in build
    dtypenums.append(np.dtype(signature.return_type.name).num)

TypeError: data type "pyobject" not understood
```

**Comment by stuartarchibald** [comment]
Closing this question as it seems to be resolved. Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!

**Comment by cristipurdel** [comment]
I posted on discourse, but got no feedback, so I really want to keep this issue open.
I am using numba version used: 0.52.0+0.g18825058a.dirty and I still cannot find a way to use vectorise on a non-scalar data type () . Below I removed some unused code, but I am still getting the following error


`TypeError: data type 'pyobject' not understood`

```
import numpy as np
import numba
from numba import vectorize, int32, float32
import pdb
import math
from timeit import default_timer as timer
import pkg_resources

print('numba version used: ' + str(pkg_resources.get_distribution("numba").version))



def v_b1(in_1D, in_nD):

    out = 0
    for t in in_nD:
        out += t
    out = in_1D + out
    
    return out

v_int = v_b1

v_cpu = numba.vectorize(['float32(float32, int32)'], target = 'cpu')(v_int)
v_parallel = numba.vectorize(['float32(float32, int32)'], target = 'parallel')(v_int)
v_cuda = numba.vectorize(['float32(float32, int32)'], target = 'cuda')(v_int)

N = 1024

print('for function ' + str(v_int.__name__) + ' is CUDA available? ' + str(numba.cuda.is_available()))
if numba.cuda.is_available():
    print (numba.cuda.detect())

if numba.cuda.is_available() == False:
    avail = [v_cpu]
else:
    avail = [v_cuda]
avail = [v_cpu]

A_in_1D = np.random.uniform(-3, 3, size=N).astype(np.float32)
A_in_1D = A_in_1D[:,np.newaxis]

B_nparray_2D = np.ones((N,3)).astype(np.int32)

B_list_dic = [{x:x+1, x+1:x+2, x+2:x+3} for x in range(N)]

B_list_list = []
for n in range(N):
    B_list_list.append([n, n+1, n+2])

#B_list_str = [str(x)+'/'+str(x+1)+'/'+str(x+2) for x in range(N)]
B_list_str = [str('1') for x in range(N)]

B_list_tuple = []
for n in range(N):
    B_list_tuple.append((n, n+1, n+2))

B_list_nparray = [0] * N
for n in range(N):
    B_list_nparray[n] = np.ones(3).astype(np.int32) + n

B_nparray_tuple_2D = np.ones((1000,1), dtype=('i4',3))
B_nparray_tuple_1D = np.ones(1000, dtype=('i4',3))

# trying to pass an array with vectorize
A_in_nD = B_list_list                                                          #0.52 not working
#A_in_nD = B_list_nparray                                                       #0.52 not working
#A_in_nD = B_nparray_2D                                                         #0.52 not working
#A_in_nD = B_list_tuple                                                         #0.52 not working
#A_in_nD = B_list_dic                                                           #0.52 not working
#A_in_nD = B_list_str                                                           #0.52 not working
#A_in_nD = B_nparray_tuple_2D                                                   #0.52 not working
#A_in_nD = B_nparray_tuple_1D                                                   #0.52 not working

for c in [1, 8, 64, 512]:
    print(c)
    for f in avail:
        start = timer()
        A_out = f(A_in_1D, A_in_nD)
        elapsed_time = timer() - start
        print("Time: {}".format(elapsed_time))
```
