### ISSUE TITLE
parfors lowering error in `build_gufunc_wrapper`

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3169]
## Reporting a bug

- [x] I am using ~the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).~ master
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Noticed this on stackoverflow https://stackoverflow.com/questions/51537589/parallelize-with-numbas-prange-and-passing-along-a-tuple and managed to reduce it to this:
```python
from numba import njit, prange
import numpy as np

@njit
def foo(grids):
    pass

def bar(grids):
    for x in prange(1):
        foo(grids)

grids = ([1],) * 2
# grids = (np.arange(1),) * 2 # also broken

print("test njit")
njit(bar)(grids)
print("test njit(parallel=True)")
njit(parallel=True)(bar)(grids)
```

gives:
```
$ python sof9.py 
test njit
test njit(parallel=True)
Traceback (most recent call last):
  File "<path>/numba/errors.py", line 595, in new_error_context
    yield
  File "<path>/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/lowering.py", line 403, in lower_inst
    func(self, inst)
  File "<path>/numba/npyufunc/parfor.py", line 120, in _lower_parfor_parallel
    index_var_typ)
  File "<path>/numba/npyufunc/parfor.py", line 708, in call_parallel_gufunc
    sout, {})
  File "<path>/numba/npyufunc/parallel.py", line 247, in build_gufunc_wrapper
    cache=cache)
  File "<path>/numba/npyufunc/wrappers.py", line 461, in build_gufunc_wrapper
    return wrapcls(py_func, cres, sin, sout, cache).build()
  File "<path>/numba/npyufunc/wrappers.py", line 413, in build
    self._build_wrapper(wrapperlib, wrapper_name)
  File "<path>/numba/npyufunc/wrappers.py", line 374, in _build_wrapper
    arg_steps, i, step_offset, typ, sym, sym_dim)
  File "<path>/numba/npyufunc/wrappers.py", line 615, in __init__
    "argument #{1}".format(typ, i + 1))
TypeError: scalar type tuple(reflected list(int64) x 2) given for non scalar argument #2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sof9.py", line 18, in <module>
    njit(parallel=True)(bar)(grids)
  File "<path>/numba/dispatcher.py", line 368, in _compile_for_args
    raise e
  File "<path>/numba/dispatcher.py", line 325, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<path>/numba/dispatcher.py", line 653, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "<path>/numba/compiler.py", line 881, in compile_extra
    return pipeline.compile_extra(func)
  File "<path>/numba/compiler.py", line 368, in compile_extra
    return self._compile_bytecode()
  File "<path>/numba/compiler.py", line 812, in _compile_bytecode
    return self._compile_core()
  File "<path>/numba/compiler.py", line 799, in _compile_core
    res = pm.run(self.status)
  File "<path>/numba/compiler.py", line 254, in run
    raise patched_exception
  File "<path>/numba/compiler.py", line 246, in run
    stage()
  File "<path>/numba/compiler.py", line 679, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "<path>/numba/compiler.py", line 629, in _backend
    lowered = lowerfn()
  File "<path>/numba/compiler.py", line 616, in backend_nopython_mode
    self.flags)
  File "<path>/numba/compiler.py", line 1000, in native_lowering_stage
    lower.lower()
  File "<path>/numba/lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "<path>/numba/lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "<path>/numba/lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "<path>/numba/lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "<env>/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "<path>/numba/errors.py", line 603, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "<path>/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
scalar type tuple(reflected list(int64) x 2) given for non scalar argument #2

File "sof9.py", line 9:
def bar(grids):
    for x in prange(1):
    ^
[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.0, range = (0, $const2.2, 1))]{12: <ir.Block at sof9.py (9)>}Var(parfor_index.0, sof9.py (9))" at sof9.py (9)
```

**Comment by stuartarchibald** [comment]
Think this is another variant on the "gufunc given tuple as argument" problem.

**Comment by stuartarchibald** [comment]
Closing as duplicate of meta-issue https://github.com/numba/numba/issues/5282, please follow that ticket for developments.
