### ISSUE TITLE
@guvectorize CudaAPIError: Call to cuLinkCreate results in CUDA_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by cristipurdel** [numba/numba#3197]
- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have a 100 line code guvectorize function that works with no issues on cuda on  3-10K elements (up to 64 MB of data stored on the GPU via cuda.to_device function)

The function is smth like : 
The code runs well on 'cpu' / 'parallel' for 1M elements but for 'cuda' it gets stuck at around 64MB, and complains about the decorator  when it previous did not complain.

see 
```
  File "folderpath/fn_guv.py", line 610, in <module>
    (x,y,c,c)->(x,f)', target = targetOpt)(guv_gen_int)
```

Any ideeas  how to get a workaround?
I tried playing with CUDA_max_blocksize and using a easier .guvectorize("form"), but I always get the same thing
I am using 0.38 since I got the spyder "white" window bug

```
def guv_gen_b1(arr1, ..... 

guv_gen_int = guv_gen_b1

targetOpt = 'cuda'

for targetOpt in ['parallel', 'cuda']:
	guv_gen = numba.guvectorize([void(float32[:,:], float32[:,:], float32[:,:], float32[:,:,:], 
					float32[:,:], float32[:,:,:,:], float32[:,:,:], float32[:,:,:,:], 
					float32[:,:,:,:], float32[:,:], float32[:,:,:,:], float32[:,:,:,:],
					float32[:,:,:,:],
					float32[:,:])], 
					'(x,j),(x,f),(c,c),(x,c,c),\
					(x,y),(x,y,c,c),(x,f,f),(x,y,c,c),\
					(x,y,c,c),(x,f),(x,y,c,c),(x,y,c,c),\
					(x,y,c,c)->(x,f)', target = targetOpt)(guv_gen_int)
```

Traceback :

```
Exception ignored in: <finalize object at 0x205fe131040; dead>
Traceback (most recent call last):
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1108, in deref
    mem.free()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1013, in free
    self._finalizer()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 863, in core
    deallocations.add_item(dtor, handle, size=bytesize)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 519, in add_item
    self.clear()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 530, in clear
    dtor(handle)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuMemFree results in CUDA_ERROR_UNKNOWN
Exception ignored in: <finalize object at 0x205fe131060; dead>
Traceback (most recent call last):
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1108, in deref
    mem.free()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1013, in free
    self._finalizer()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 863, in core
    deallocations.add_item(dtor, handle, size=bytesize)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 519, in add_item
    self.clear()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 530, in clear
    dtor(handle)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuMemFree results in CUDA_ERROR_UNKNOWN
Exception ignored in: <finalize object at 0x205fe131080; dead>
Traceback (most recent call last):
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1108, in deref
    mem.free()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1013, in free
    self._finalizer()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 863, in core
    deallocations.add_item(dtor, handle, size=bytesize)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 519, in add_item
    self.clear()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 530, in clear
    dtor(handle)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuMemFree results in CUDA_ERROR_UNKNOWN
Exception ignored in: <finalize object at 0x205fe1310a0; dead>
Traceback (most recent call last):
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1108, in deref
    mem.free()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1013, in free
    self._finalizer()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 863, in core
    deallocations.add_item(dtor, handle, size=bytesize)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 519, in add_item
    self.clear()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 530, in clear
    dtor(handle)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuMemFree results in CUDA_ERROR_UNKNOWN
Exception ignored in: <finalize object at 0x205fe1310c0; dead>
Traceback (most recent call last):
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1108, in deref
    mem.free()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1013, in free
    self._finalizer()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 863, in core
    deallocations.add_item(dtor, handle, size=bytesize)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 519, in add_item
    self.clear()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 530, in clear
    dtor(handle)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuMemFree results in CUDA_ERROR_UNKNOWN
Exception ignored in: <finalize object at 0x205fe1310e0; dead>
Traceback (most recent call last):
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1108, in deref
    mem.free()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1013, in free
    self._finalizer()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 863, in core
    deallocations.add_item(dtor, handle, size=bytesize)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 519, in add_item
    self.clear()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 530, in clear
    dtor(handle)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuMemFree results in CUDA_ERROR_UNKNOWN
Exception ignored in: <finalize object at 0x205fe131110; dead>
Traceback (most recent call last):
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1108, in deref
    mem.free()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1013, in free
    self._finalizer()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 863, in core
    deallocations.add_item(dtor, handle, size=bytesize)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 519, in add_item
    self.clear()
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 530, in clear
    dtor(handle)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [999] Call to cuMemFree results in CUDA_ERROR_UNKNOWN
Traceback (most recent call last):

  File "<ipython-input-4-8020991106b8>", line 1, in <module>
    runfile('folderpath/fn_guv.py', wdir='folderpath')

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "folderpath/fn_guv.py", line 610, in <module>
    (x,y,c,c)->(x,f)', target = targetOpt)(guv_gen_int)

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\npyufunc\decorators.py", line 179, in wrap
    guvec.add(fty)

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\npyufunc\deviceufunc.py", line 468, in add
    kernel = self._compile_kernel(fnobj, sig=tuple(outertys))

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\vectorizers.py", line 55, in _compile_kernel
    return cuda.jit(sig)(fnobj)

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\decorators.py", line 96, in kernel_jit
    kernel.bind()

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\compiler.py", line 490, in bind
    self._func.get()

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\compiler.py", line 374, in get
    linker = driver.Linker()

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1380, in __init__
    byref(self.handle))

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 288, in safe_cuda_api_call
    self._check_error(fname, retcode)

  File "C:\Users\Q1900M\Anaconda3\lib\site-packages\numba\cuda\cudadrv\driver.py", line 323, in _check_error
    raise CudaAPIError(retcode, msg)

CudaAPIError: Call to cuLinkCreate results in CUDA_ERROR_UNKNOWN
```

**Comment by sklam** [comment]
It's difficult to know what is happening without seeing the code.  I'm suspecting a logic error causing the active CUDA context to be corrupted.  I'd suggest using [cuda-memcheck](https://docs.nvidia.com/cuda/cuda-memcheck/index.html) from the [official CUDA Toolkit](https://developer.nvidia.com/cuda-toolkit) to see if there are any memory error.

Also, since you are on Windows, check if your GPU function is running too long and getting killed by the watchdog timer.

**Comment by seibert** [comment]
I notice this is on Windows.  What kind of GPU is this, and is there a possibility that the kernel is taking more than a few seconds to execute?  Unless you are using the Tesla driver, Windows will terminate kernels that run for more than a few seconds, which might leave the process in a strange state.

**Comment by cristipurdel** [comment]
This is a low end 1030 GT card. Execution time is taking some ms, but the memory trasnfer is taking I guess some seconds.
So the only workaround is to use the Tesla driver?!? I'm afraid it will cause more issues since I am using the machine also for other GPU intensive apps (BOINC) and I guess I will have other headaches

**Comment by seibert** [comment]
If this GPU is also running your Windows desktop, you will not have the full 2 GB of GPU memory to use, which may also be causing problems.  `numba.cuda.current_context().get_memory_info()` will return some information about total and free memory.

We distributed the same user libraries as come from the CUDA toolkit installer, and the Tesla drivers can only be used with Tesla (and perhaps Titan/Quadro) cards, so they won't be an option for your GeForce.

**Comment by cristipurdel** [comment]
`numba.cuda.current_context().get_memory_info()` does not return anything 

`numba.cuda.is_available()` returns

```
Found 1 CUDA devices
id 0      b'GeForce GT 1030'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 2
Summary:
        1/1 devices are supported
```

**Comment by cristipurdel** [comment]
So to better understand the situation:
I cannot use a kernel on a GeForce GPU / Windows 10 (although from what I am reading it works on Windows 7) for more than a couple of seconds since it will get killed by the watchdog timer.
Solution would be to either get a more expensive card (like Tesla, Titan or Quadro) which have TCC mode 
OR
Switch to linux
Stupid question, how come games or gpu intensive apps (which might use CUDA like BOINC projects) are not affected by the watchdog timer?

**Comment by seibert** [comment]
I'm not an expert on watchdog timer issues, but my understanding is this:

* The timer is active only when the GPU is being used for both CUDA and a graphical desktop.  (To ensure the GUI is still responsive.)
* The timer only kicks in if a single CUDA kernel call exceeds the time limit.  It doesn't matter how long your application is running, or how many kernels you launch.  This is because the CUDA driver timeslices the GPU at kernel call boundaries between different applications.
* Applications which ensure that their kernel calls are less than a few seconds long can avoid the watchdog, although kernels that run longer than 50-100 ms will make GUI updates noticeably jerky.
* The timer affects all operating systems, however, it is easily avoided on Linux because you can run without a GUI and very few CUDA users are on Mac.  As a result, most reported problems come up on Windows.
* The watchdog has been around for a while, so I would have assumed that Windows 7 and 10 would be affected the same way.
* Tesla cards can be disconnected from the Windows GUI system using the TCC driver, which both avoids the watchdog and eliminates a lot of kernel launch overhead imposed by the Windows graphical display driver system.
* Newer CUDA architectures (like Pascal) have added more preemptive multitasking capability in the hardware, so it is possible that the watchdog behavior has changed with newer cards (like your 1030).

All this said, I don't think we have conclusively determined it is the watchdog killing your kernels, but it seems likely.

**Comment by cristipurdel** [comment]
Found the solution after 2 days of searching based on Nsight Options
[https://stackoverflow.com/questions/497685/cuda-apps-time-out-fail-after-several-seconds-how-to-work-around-this](url)

**Comment by cristipurdel** [comment]
This is definitely the solution, since I got the same error on another computer.
https://docs.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys
Just set TdrDelay and TdrDdiDelay to 3600
