### ISSUE TITLE
`pip install -r requirements.txt` fails

### ISSUE THREAD

**Issue by Juanlu001** [numba/numba#323]
It seems that llvmmath requires llvm to be installed in the system. Therefore, as all the packages are downloaded and then installed,

    pip install -r requirements.txt

fails with the following error:

```
[numpy, llvm, argparse... correctly downloaded and compiled]
Downloading/unpacking llvmmath (from -r requirements.txt (line 9))
  Downloading llvmmath-0.1.1.tar.gz (58kB): 58kB downloaded
  Running setup.py egg_info for package llvmmath
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/juanlu/Development/Python/numba/venv/build/llvmmath/setup.py", line 13, in <module>
        import llvmmath
      File "./llvmmath/__init__.py", line 16, in <module>
        from .build import have_llvm_asm, have_clang
      File "./llvmmath/build.py", line 21, in <module>
        import llvm.core
    ImportError: No module named 'llvm'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/juanlu/Development/Python/numba/venv/build/llvmmath/setup.py", line 13, in <module>

    import llvmmath

  File "./llvmmath/__init__.py", line 16, in <module>

    from .build import have_llvm_asm, have_clang

  File "./llvmmath/build.py", line 21, in <module>

    import llvm.core

ImportError: No module named 'llvm'

----------------------------------------
Cleaning up...
```

**Comment by pitrou** [comment]
This bug is outdated, requirements install fine these days.
