### ISSUE TITLE
numpy.array(...) `LoweringError`

### ISSUE THREAD

**Issue by VIVelev** [numba/numba#3239]
LoweringError:
 Failed at object (object mode backend)
make_function(name=$const48.11, code=<code object <listcomp> at 0x10cb9ab70, file "/Users/victor/Documents/PyDojo/dojo/linear/LinearRegression.py", line 26>, closure=None, defaults=None)

File "dojo/linear/LinearRegression.py", line 26:
```
    def fit(self, X, y):
        <source elided>
        X = np.hstack((
            np.array([[1] for _ in range(m)]),
            ^
```
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

**This is the whole method I am calling:**
```
    @jit
    def fit(self, X, y):
        if type(X) is not np.ndarray:
            X = np.array(X)
        
        if type(y) is not np.ndarray:
            y = np.array(y)

        m, _ = X.shape
        X = np.hstack((
            np.array([[1] for _ in range(m)]),
            X
        ))

        res = linalg.inv(X.T @ X) @ X.T @ y
        self.set_params(intercept=res[0], coefs=res[1:])
        return self

```

**Comment by Rik-de-Kort** [comment]
Use ````np.ones((m, 1))```` instead of ````np.array([[1] for _ in range(m)])````. That ought to work.

This is fundamentally an issue with the fact that you're passing a list of lists. Tuple of lists or the fix above will work. :)

**Comment by stuartarchibald** [comment]
Thanks for the report. Adjusting this as a stand alone example:
```python
from numba import jit, njit
from numpy import linalg
import numpy as np

@jit
def fit(X, y):
    if type(X) is not np.ndarray:
        X = np.array(X)

    if type(y) is not np.ndarray:
        y = np.array(y)

    m, _ = X.shape
    X = np.hstack((
        np.array([[1] for _ in range(m)]),
        X
    ))

    res = linalg.inv(X.T @ X) @ X.T @ y
    intercept=res[0]
    coefs=res[1:]
    return intercept, coefs

fit(np.arange(10).reshape(1,10), np.arange(10).reshape(1,10))
```
gives:
```
    assert name in self._live_vars, name
AssertionError: array.22

<more traceback stuff>

numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
array.22

File "issue3239.py", line 15:
def fit(X, y):
    <source elided>
    X = np.hstack((
        np.array([[1] for _ in range(m)]),
        ^
[1] During: lowering "$48.18 = array.22" at issue3239.py (15)
```
on current master.

If `forceobj` is set it gives this:
```
Traceback (most recent call last):
  File "issue3239.py", line 24, in <module>
    fit(np.arange(10).reshape(1,10), np.arange(10).reshape(1,10))
NameError: global name 'unsafe_empty_inferred' is not defined
```
Ping @sklam

**Comment by sklam** [comment]
Getting to a simpler reproducer:

```python
from numba import jit, njit
import numpy as np

@jit
def fit(X):
    return np.array([[1] for _ in range(2)])


fit(np.arange(10))
```

**Comment by sklam** [comment]
Note that the following works:

```python
@jit
def fit(X):
    return np.array([1 for _ in range(2)])
```
The difference being that it's producing a flat list instead of a list-of-list.
