### ISSUE TITLE
vectorize parallel reduce producing strange answers

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3246]
From https://stackoverflow.com/questions/35459065/numbas-parallel-vectorized-functions:

This:
```python
import numpy as np
import numba as nb

@nb.vectorize([nb.float64(nb.float64, nb.float64)])
def numba_sum(element1, element2):
    return element1 + element2

@nb.vectorize([nb.float64(nb.float64, nb.float64)], target='parallel')
def numba_sum_parallel(element1, element2):
    return element1 + element2

elements=10000000
array = np.ones(elements)
np.testing.assert_almost_equal(numba_sum.reduce(array), np.sum(array))
np.testing.assert_almost_equal(numba_sum_parallel.reduce(array), np.sum(array))
```
produces e.g.:
```
Traceback (most recent call last):
  File "sof13.py", line 15, in <module>
    np.testing.assert_almost_equal(numba_sum_parallel.reduce(array), np.sum(array))
  File "<env>/lib/python3.7/site-packages/numpy/testing/_private/utils.py", line 584, in assert_almost_equal
    raise AssertionError(_build_err_msg())
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 5716550.0
 DESIRED: 10000000.0
```
Need to find the root cause.

**Comment by stuartarchibald** [comment]
Duplicate of https://github.com/numba/numba/issues/1721 closing.
