### ISSUE TITLE
Numba, use of unknown opcode FORMAT_VALUE, python 3.6

### ISSUE THREAD

**Issue by marcino239** [numba/numba#3250]
This program:
```
import numba

@numba.jit(nopython=True)
def test( a: int ):
    b = a + 1
    print( f'b:{b}' )
    return b

b = test( 1 )
print( f'b:{b}' )
```

Throws this exception:

```
(py36) [marcino@localhost numbatest]$ python test.py 
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    b = test( 1 )
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 368, in _compile_for_args
    raise e
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 325, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 653, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 873, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 804, in _compile_bytecode
    return self._compile_core()
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 791, in _compile_core
    res = pm.run(self.status)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 381, in stage_analyze_bytecode
    func_ir = translate_stage(self.func_id, self.bc)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/compiler.py", line 937, in translate_stage
    return interp.interpret(bytecode)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/interpreter.py", line 98, in interpret
    self.dfa.run()
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dataflow.py", line 28, in run
    self.infos[blk.offset] = self.run_on_block(blk)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dataflow.py", line 78, in run_on_block
    self.dispatch(info, inst)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dataflow.py", line 88, in dispatch
    fn(info, inst)
  File "/home/marcino/py36/lib/python3.6/site-packages/numba/dataflow.py", line 93, in handle_unknown_opcode
    self.bytecode.func_id.filename))
NotImplementedError: Failed at nopython (analyzing bytecode)
Use of unknown opcode FORMAT_VALUE at line 6 of test.py
```

**Comment by stuartarchibald** [comment]
Thanks for the report. The `FORMAT_VALUE` op code isn't supported (as noted by the error message), adding this as a feature request.

**Comment by rtmatx** [comment]
If you don't mid asking, what is the error message trying to mention. I got similar sort of error but don't know how to understand the error message

**Comment by anthonytec2** [comment]
For implementing the `FORMAT_VALUE` opcode, would this just require adding an opcode to the interpreter.py file and what further is required to fix this up?

**Comment by stuartarchibald** [comment]
@rtmatx the error message is mentioning that the opcode `FORMAT_VALUE` is not supported by Numba. The use of `opcode` refers to the "operation code" for a given bytecode instruction https://docs.python.org/3/library/dis.html#python-bytecode-instructions. Numba works by first interpreting the Python bytecode through the use of opcodes, more can be read about this here http://numba.pydata.org/numba-doc/dev/developer/architecture.html?highlight=bytecode#stage-1-analyze-bytecode.

**Comment by stuartarchibald** [comment]
@anthonytec2 The `FORMAT_VALUE` opcode would need adding to the interpreter+dataflow, as would `BUILD_STRING`. If this was to work under `nopython` mode then a load of typing and implementation lowering would also need writing, I imagine that this would be quite challenging.

**Comment by esc** [comment]
#3938 implements a better error message in such cases. For example, in the case above it will print:

```
💥 zsh» python v3.py                                                                                                                                          :(
Traceback (most recent call last):
  File "v3.py", line 9, in <module>
    b = test( 1 )
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 353, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/vhaenel/git/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unknown opcode 'FORMAT_VALUE'

File "v3.py", line 6:
def test( a: int ):
    <source elided>
    b = a + 1
    print( f'b:{b}' )
    ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new
```

**Comment by hbaaron** [comment]
hi guys, any workaround?

**Comment by stuartarchibald** [comment]
@hbaaron unfortunately there is no work around, use of format string (and hence that opcode) is not yet supported.

**Comment by monocongo** [comment]
I have been using formatted strings (`f"string like this with {values}"`) and everything has worked well until I saw this error today when running some code that was running well before. Maybe the previous usages of my numba annotated functions were not exercising the blocks where I have the formatted strings that cause this error? My point is that I have formatted strings throughout my code, most of which is annotated with `@numba.jit`, so I was surprised by this error being raised in code when I hadn't modified it recently. Must I remove all formatted strings in order to be safe from this issue? It seems that changing the offending lines to instead use `format()` does indeed fix things, but it's an unwelcome workaround for sure.

**Comment by stuartarchibald** [comment]
@monocongo I'm not sure what's going on in your case, `@numba.jit` would have to compile the blocks irrespective of whether they are used, which would require it interpreting bytecode containing the `FORMAT_VALUE` op code. e.g.:
```pycon
In [1]: def foo(values): 
   ...:     return f"string {values}" 
   ...:                                                                                                                         

In [2]: def bar(values): 
   ...:     return "string {}".format(values) 
   ...:                                                                                                                         

In [3]: from dis import dis                                                                                                     

In [4]: dis(foo)                                                                                                                
  2           0 LOAD_CONST               1 ('string ')
              2 LOAD_FAST                0 (values)
              4 FORMAT_VALUE             0
              6 BUILD_STRING             2
              8 RETURN_VALUE

In [5]: from numba import jit                                                                                                   

In [6]: jit(foo)(10)                                                                                                            
---------------------------------------------------------------------------
UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unknown opcode 'FORMAT_VALUE'

File "<ipython-input-1-2130adc6315a>", line 2:
def foo(values):
    return f"string {values}"
    ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new


In [7]: jit(bar)(10)                                                                                                            
Out[7]: 'string 10'

In [8]: jit(nopython=True)(bar)(10)                                                                                             
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'format' of type Literal[str](string {})

File "<ipython-input-2-852f47965480>", line 2:
def bar(values):
    return "string {}".format(values)
    ^

[1] During: typing of get attribute at <ipython-input-2-852f47965480> (2)

File "<ipython-input-2-852f47965480>", line 2:
def bar(values):
    return "string {}".format(values)
    ^

In [9]: dis(bar)                                                                                                                
  2           0 LOAD_CONST               1 ('string {}')
              2 LOAD_METHOD              0 (format)
              4 LOAD_FAST                0 (values)
              6 CALL_METHOD              1
              8 RETURN_VALUE
```
Even with a dead branch, the op code would still need to be interpreted...
```python
In [10]: def foo_branch(values, jmp): 
    ...:     if jmp > 0: 
    ...:         return f"string {values}" 
    ...:     else: 
    ...:         return "const str" 
    ...:          
    ...:                                                                                                                        

In [11]: dis(foo_branch)                                                                                                        
  2           0 LOAD_FAST                1 (jmp)
              2 LOAD_CONST               1 (0)
              4 COMPARE_OP               4 (>)
              6 POP_JUMP_IF_FALSE       18

  3           8 LOAD_CONST               2 ('string ')
             10 LOAD_FAST                0 (values)
             12 FORMAT_VALUE             0
             14 BUILD_STRING             2
             16 RETURN_VALUE

  5     >>   18 LOAD_CONST               3 ('const str')
             20 RETURN_VALUE
             22 LOAD_CONST               0 (None)
             24 RETURN_VALUE

In [12]: jit(foo_branch)(10, -1) 

UnsupportedError: Failed in object mode pipeline (step: analyzing bytecode)
Use of unknown opcode 'FORMAT_VALUE'

File "<ipython-input-10-c5ac4bf10bb6>", line 3:
def foo_branch(values, jmp):
    <source elided>
    if jmp > 0:
        return f"string {values}"
        ^
```

Also, `@jit` without specifying `nopython=True` is not necessarily beneficial http://numba.pydata.org/numba-doc/latest/user/5minguide.html#what-is-nopython-mode

**Comment by esc** [comment]
Since this is a feature request and it is probably still wanted, I'll change the title now to reflect what is being requested.

**Comment by monocongo** [comment]
Thanks, @esc. It'll be nice to be able to use f-strings in numba-annotated code once this is ready to go. I appreciate the useful work you guys do on numba, thanks!

**Comment by esc** [comment]
@monocongo thanks for the kind words! We appreciate you using Numba. 😄

**Comment by adizhol** [comment]
still no support?

**Comment by esc** [comment]
@adizhol that is correct, so sorry.

**Comment by renzhengchi** [comment]
Can I use print with argument 'end' like this: print('something', end='\r')?
Or can I do it in other way?

**Comment by Hvass-Labs** [comment]
Thanks for making numba, it is incredibly cool and powerful!

I am using numba as `@jit(forceobj=True)` because the old fallback-mode will be deprecated, and this makes my Python code easy to read and maintain, and I just need numba to optimize some for-loops. This gives me a 10x speed-up!

I would like to use f-strings but I get the same numba exception as described above.

Would it be possible to add support for f-strings when numba is running in forced object mode?

Thanks!

**Comment by IamShubhamGupto** [comment]
please fix this

**Comment by lucasjinreal** [comment]
5 years later, any updates?

**Comment by erdogant** [comment]
Unfortunately, I also get this error.

**Comment by esc** [comment]
This is clearly looking for someone to volunteer to implement it. Please don't hesitate to consider this if you need it for your Numba use-case.
