### ISSUE TITLE
Numba (--annotate) fails non-determistically

### ISSUE THREAD

**Issue by tuulos** [numba/numba#328]
I noticed very strange behavior with Numba 0.10.0-5-g34939c2

I have a moderately complex function of 140 lines in a file, a.py, decorated with numba.jit. Just executing the file 

```
python a.py
```

works as expected, although it took a while to get it compile due to Numba not recognizing types correctly. I needed to annotate types in the code by hand, by adding `u4` etc. to a few strategic places.

When I run the following command:

```
while ((1)); do numba --annotate a.py >/dev/null && echo "success"; done
```

The result is very strange:

```
success
Traceback (most recent call last):
  File "/usr/local/bin/numba", line 54, in <module>
    run(args.filename, cmdopts)
  File "/usr/local/bin/numba", line 21, in run
    eval(code, globals)
  File "a.py", line 3, in <module>
    @jit(u4(f8[:],u1[:],u2[:],u1[:],u1[:],u4[:]), nopython=True, warn=False)
  File "/usr/local/lib/python2.7/dist-packages/numba/decorators.py", line 224, in _jit_decorator
    nopython=nopython, func_ast=func_ast, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/decorators.py", line 133, in compile_function
    func_env = pipeline.compile2(env, func, restype, argtypes, func_ast=func_ast, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 144, in compile2
    post_ast = pipeline(func_ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 191, in __call__
    ast = self.transform(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 656, in transform
    ast = stage(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 641, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 194, in __call__
    ast = self.transform(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 385, in transform
    ast, env, **crnt.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 185, in make_specializer
    return cls(env.context, crnt.func, ast, **kws)
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 95, in __init__
    self.init_locals()
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 168, in init_locals
    self.resolve_variable_types()
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 425, in resolve_variable_types
    self.remove_resolved_type(start_point)
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 315, in remove_resolved_type
    assert not type.is_scc
AssertionError
success
success
success
success
success
Traceback (most recent call last):
  File "/usr/local/bin/numba", line 54, in <module>
    run(args.filename, cmdopts)
  File "/usr/local/bin/numba", line 21, in run
    eval(code, globals)
  File "a.py", line 3, in <module>
    @jit(u4(f8[:],u1[:],u2[:],u1[:],u1[:],u4[:]), nopython=True, warn=False)
  File "/usr/local/lib/python2.7/dist-packages/numba/decorators.py", line 224, in _jit_decorator
    nopython=nopython, func_ast=func_ast, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/decorators.py", line 133, in compile_function
    func_env = pipeline.compile2(env, func, restype, argtypes, func_ast=func_ast, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 144, in compile2
    post_ast = pipeline(func_ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 191, in __call__
    ast = self.transform(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 656, in transform
    ast = stage(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 641, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 194, in __call__
    ast = self.transform(ast, env)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 385, in transform
    ast, env, **crnt.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/numba/pipeline.py", line 185, in make_specializer
    return cls(env.context, crnt.func, ast, **kws)
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 95, in __init__
    self.init_locals()
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 168, in init_locals
    self.resolve_variable_types()
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 425, in resolve_variable_types
    self.remove_resolved_type(start_point)
  File "/usr/local/lib/python2.7/dist-packages/numba/type_inference/infer.py", line 315, in remove_resolved_type
    assert not type.is_scc
AssertionError
```

How is this possible? Is there anything non-deterministic in Numba that could cause this, such as a race condition? The result is totally non-deterministic - I get a varying number of successes every time I run the command.

Unfortunately I can't share a.py here publicly but it is available upon request. There's nothing particularly special about the function, it is mostly bit twiddling with nopython=True. I just wanted to check first if this anomaly is even physically possible.

**Comment by pitrou** [comment]
Closing as outdated.
