### ISSUE TITLE
LoweringError with list comprehension and object

### ISSUE THREAD

**Issue by SuperStormer** [numba/numba#3287]
## Reporting a bug

- [V] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [V] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have a file with these contents:
`from numba import jit`
`@jit`
`def a(b):`
`	return [i for i in range(5)]`
`a({})	`
Running it produces this error:
>Traceback (most recent call last):
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\errors.py", line 577, in new_error_context
    yield
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\objmode.py", line 65, in lower_inst
    value = self.lower_assign(inst)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\objmode.py", line 159, in lower_assign
    return self.lower_expr(value)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\objmode.py", line 373, in lower_expr
    raise NotImplementedError(expr)
NotImplementedError: make_function(name=$const0.5, code=<code object <listcomp> at 0x000001A82AF268A0, file "C:\XUE\Larry\PythonWorkspace\numbatest\a.py", line 5>, closure=None, defaults=None)

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "C:\XUE\Larry\PythonWorkspace\numbatest\a.py", line 6, in <module>
    a({})
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 368, in _compile_for_args
    raise e
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 325, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 653, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 873, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 804, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 791, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 253, in run
    raise patched_exception
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 652, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 628, in _backend
    lowered = lowerfn()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 601, in backend_object_mode
    self.flags)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 1018, in py_lowering_stage
    lower.lower()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "C:\Users\g\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at object (object mode backend)
?[1m?[1mmake_function(name=$const0.5, code=<code object <listcomp> at 0x000001A82AF268A0, file "C:\XUE\Larry\PythonWorkspace\numbatest\a.py", line 5>, closure=None, defaults=None)
?[1m
File "a.py", line 5:?[0m
?[1mdef a(b):
    <source elided>
        print(b)
?[1m    return [key for key in range(5)]
?[0m ?[1m^?[0m?[0m?[0m
?[0m?[1m[1] During: lowering "$0.6 = make_function(name=$const0.5, code=<code object <listcomp> at 0x000001A82AF268A0, file "C:\XUE\Larry\PythonWorkspace\numbatest\a.py", line 5>, closure=None, defaults=None)" at C:\XUE\Larry\PythonWorkspace\numbatest\a.py (5)?[0m
-------------------------------------------------------------------------------
>This should not have happened, a problem has occurred in Numba's internals.

>Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

>If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

>Thanks in advance for your help in improving Numba!

This file should run with no errors.

**Comment by stuartarchibald** [comment]
Thanks for the report. This issue was fixed in https://github.com/numba/numba/pull/3122, the 0.40.0 release (coming out soon) will have this fix in it. If you'd like to try out the fixed version now you can use a development version of Numba from the Numba channel by doing:
```
$ conda install -c numba numba
```
Closing. Thanks.
