### ISSUE TITLE
AssertionError with list comprehension and loop

### ISSUE THREAD

**Issue by SuperStormer** [numba/numba#3289]
## Reporting a bug

- [ V] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ V] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I had a file with these contents:
```from numba import jit
b=[(5,124),(52,5)]
	
@jit
def a():
	c=[b[index] for index in [0,1]]
	for x in range(5):
		pass

a()
```
It produced this error:
>Traceback (most recent call last):
  File "C:\XUE\Larry\PythonWorkspace\numbatest\a.py", line 10, in <module>
    a()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 367, in _compile_for_args
    raise e
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 656, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 903, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 369, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 834, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 821, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 255, in run
    raise patched_exception
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 246, in run
    stage()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 458, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\compiler.py", line 420, in frontend_looplift
    flags=loop_flags)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\transforms.py", line 177, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\analysis.py", line 241, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "C:\Users\g\Anaconda3\lib\site-packages\numba\controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed in object mode pipeline (step: object mode frontend)

**Comment by stuartarchibald** [comment]
@Rik-de-Kort thanks for looking at this. The reason for the error in #3289 being more informative under `@njit` is that it is failing via a well trodden error pathway (as in, this code is not supported by the compiler in `nopython` mode and it can detect that and bail). Ideally the `@njit` path shouldn't be raising from the lowering pass and the problem should really be caught by legalization, but that's another matter. The reason this fails in a seemingly poor manner under standard `@jit` is that this is a) a bug b) a bug that trips an internal assert that raises in a manner that isn't currently handled nicely. The error under `@jit` is coming from control flow analysis, a point in the pipeline which shouldn't really fail, if the code is valid python it should be analysable and so an assert when something goes wrong is reasonable. However, it ought to be caught and translated into something to ask users to report the problem, https://github.com/numba/numba/issues/3290 to track.

**Comment by stuartarchibald** [comment]
@SuperStormer thanks for the report. This is a bug, I think the closure inlining pass under the `nopython` path is mutating the IR in a manner that is causing CFA to fail when the `objectmode` fallback path is used. There is another ticket which demonstrates the same behaviour here: https://github.com/numba/numba/issues/3131. Adding `forceobj=True` as a kwarg in the `@jit` decorator "fixes" it.
