### ISSUE TITLE
Numba compilation error

### ISSUE THREAD

**Issue by ajaychat3** [numba/numba#3293]
I am using numba to compile functions in python 3.7. The code is given as below

```python
from numba import jit,prange,vectorize,njit
from sklearn.model_selection import ParameterSampler,StratifiedKFold
from sklearn.metrics import accuracy_score
import numpy as np
import lightgbm as lgb

# @jit(fastmath=True,forceobj=True)
def crossval_jit(params,train_set,train_label,n_splits=3):
    res=[]
    nfold = StratifiedKFold(n_splits=n_splits, shuffle=True, random_state=123)
    for train_index, test_index in nfold.split(train_set,train_label):
        train = train_set[train_index,:]
        test = train_set[test_index,:]
        
        labels = train_label[train_index]
        test_labels = train_label[test_index]
        
        clf = lgb.LGBMClassifier(**params,seed=123,n_jobs=3,random_state=123,
                                metric='logloss',boosting_type = 'gbdt',objective = 'binary')
        clf.fit(train, np.ravel(labels))
        
        recscore=accuracy_score(test_labels,clf.predict(test))
        res.append(recscore)
        
        
    return np.mean(res)


# @cc.export('crossval_jit')
# @njit
@jit(parallel=True,fastmath=True,nogil=True,nopython=True)
# @vectorize()
def param_search_jit(X_train,y_train,param_grid,n_iters,n_splits):
    params=[]
    modelscore=0.0 
    score=0.0 
    modelparam=[]
#     param_list = list(ParameterSampler(param_grid, n_iter=n_iters,random_state=123))
    
    for i in range(n_iters):
        params=param_grid[i] 
        
#         score = crossval_jit(params,X_train,y_train,n_splits)
        
        if score > modelscore:
            modelscore = score
            modelparam = params
        print("Iteration %i : Iteration Score %.4f : Best Score %.4f" % (i, score, modelscore)) 
        
        if i==n_iters-1:
                print('\nBest Score : %.4f' % modelscore)
                print('\nBest Params :', modelparam)

         
    return modelscore
```
----------------------------------------------------------------------

When I run the code using the following parameters, it throws

-----------------------------
```python
import warnings
warnings.filterwarnings('ignore')
from scipy.stats import randint,uniform
param_grid={}
param_grid = {'max_depth': randint(4.0, 500.0),
                'num_iterations': randint(100.0, 600.0),
                'min_child_samples': randint(1.0, 200.0),
                'colsample_bytree': uniform(0.5, 0.5),
                'learning_rate': uniform(0.001, 0.4),
                'num_leaves': randint(10.0, 500.0),
                'subsample': uniform(0.5, 0.5)}

train_set=np.array(X_train)
train_label=np.array(y_train)

param_grid1=[]
param_grid1 = list(ParameterSampler(param_grid, n_iter=3,random_state=123))
LGB_score = param_search_jit(train_set, train_label, param_grid1,2, 3)
```
---------------------------------------------------------------------------
```
TypingError                               Traceback (most recent call last)
<ipython-input-98-845f112395cc> in <module>()
     30 param_grid1=[]
     31 param_grid1 = list(ParameterSampler(param_grid, n_iter=3,random_state=123))
---> 32 LGB_score = param_search_jit(train_set, train_label, param_grid1,2, 3)
     33 
     34 

c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    347                 e.patch_message(msg)
    348 
--> 349             error_rewrite(e, 'typing')
    350         except errors.UnsupportedError as e:
    351             # Something unsupported is present in the user code, add help info

c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\dispatcher.py in error_rewrite(e, issue_type)
    314                 raise e
    315             else:
--> 316                 reraise(type(e), e, None)
    317 
    318         argtypes = []

c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x0000028A58F0D860>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\errors.py", line 577, in new_error_context
    yield
  File "c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\typeinfer.py", line 199, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\typeinfer.py", line 142, in propagate
    constraint(typeinfer)
  File "c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\typeinfer.py", line 200, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "c:\users\chatura\appdata\local\programs\python\python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "c:\users\chatura\appdata\local\programs\python\python37\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.InternalError: 
[1] During: typing of argument at <ipython-input-97-546015d290e4> (39)
--%<----------------------------------------------------------------------------


File "<ipython-input-97-546015d290e4>", line 39:
def param_search_jit(X_train,y_train,param_grid,n_iters,n_splits):
    params=[]
    ^

This error may have been caused by the following argument(s):
- argument 2: Cannot type list element of <class 'dict'>

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

```

**Comment by stuartarchibald** [comment]
NOTE: updated comment to use markdown.

**Comment by user2589** [comment]
@ajaychat3 ,

I couldn’t find a better way to contact you so I’m writing here. This comment will be deleted in one week to keep the issue discussion clean.

My name is Marat, I am a PhD student at Carnegie Mellon University. As a part of my research, I’m trying to better understand the sources of issue reports in open source.

Can you please help me by answering few questions about this issue? It shouldn’t take more than a couple of minutes. Here’s the google form: [link](https://docs.google.com/forms/d/e/1FAIpQLSfTlhMeh25AZAr0wy-DNBki_HzFP_fqdT3eIk1mf7b80mg8Lg/viewform?usp=pp_url&entry.2074867396=https://github.com/numba/numba/issues/3293)

I will share everything I learn from answers to this survey with the community afterwards.

Thank you very much!

**Comment by stuartarchibald** [comment]
Thanks for the report. In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics.
