### ISSUE TITLE
issue with np.newaxis or trying to create a new axis when slicing

### ISSUE THREAD

**Issue by eriknw** [numba/numba#3298]
This is related to #2761, and I'm not sure if this should be categorized as a bug or feature.  I have several related failing expressions I am trying to use, though, and not all use `np.newaxis`.

Here is more-or-less minimal code that also conveys what I'm trying to do:
```python
import numpy as np
import numba  # using version 0.39.0

def f1(A, b):
    rv = A.copy()
    rv[..., 1:3] = b[..., np.newaxis]
    return rv

def f2(A, b):
    rv = A.copy()
    rv[:, 1:3] = b[:, np.newaxis]
    return rv

def f3(A, b):  # works
    rv = A.copy()
    rv[:, 1:3] = b.reshape((-1, 1))
    return rv

A = np.arange(15).reshape((3, 5))
b = np.array([100, 200, 300])
f_expected = np.array([
    [0, 100, 100, 3, 4],
    [5, 200, 200, 8, 9],
    [10, 300, 300, 13, 14],
])
np.testing.assert_equal(f1(A, b), f_expected)
np.testing.assert_equal(f2(A, b), f_expected)
np.testing.assert_equal(f3(A, b), f_expected)
numba.njit(f1)(A, b)  # FAILS.  Traceback 1
numba.njit(f2)(A, b)  # FAILS
np.testing.assert_equal(numba.njit(f3)(A, b), f_expected)  # works

def g1(A):
    return A[..., [2]]

def g2(A):
    return A[..., 2, np.newaxis]

def g3(A):
    return A[:, [2]]

def g4(A):
    return A[:, 2, np.newaxis]

def g5(A):
    return A[:, 2].reshape((-1, 1))

g_expected = np.array([[2], [7], [12]])
np.testing.assert_equal(g1(A), g_expected)
np.testing.assert_equal(g2(A), g_expected)
np.testing.assert_equal(g3(A), g_expected)
np.testing.assert_equal(g4(A), g_expected)
np.testing.assert_equal(g5(A), g_expected)
numba.njit(g1)(A)  # FAILS.  Traceback 2
numba.njit(g2)(A)  # FAILS
numba.njit(g3)(A)  # FAILS
numba.njit(g4)(A)  # FAILS
numba.njit(g5)(A)  # FAILS.  Traceback 3

np.testing.assert_equal(g1(b), np.array([300]))
np.testing.assert_equal(g2(b), np.array([300]))
numba.njit(g1)(b)  # FAILS
numba.njit(g2)(b)  # FAILS
```
Traceback 1 from `numba.njit(f1)(A, b)`:
<details>

```python-traceback
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-96-790c0006b4c1> in <module>()
----> 1 numba.njit(f1)(a, b)  # FAILS.  Traceback 1

~/miniconda3/lib/python3.5/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    347                 e.patch_message(msg)
    348 
--> 349             error_rewrite(e, 'typing')
    350         except errors.UnsupportedError as e:
    351             # Something unsupported is present in the user code, add help info

~/miniconda3/lib/python3.5/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    314                 raise e
    315             else:
--> 316                 reraise(type(e), e, None)
    317 
    318         argtypes = []

~/miniconda3/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.StaticGetItemConstraint object at 0x61828a0f0>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/errors.py", line 577, in new_error_context
    yield
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 513, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 450, in resolve
    literals=literals)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 1173, in resolve_call
    literals=literals)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/context.py", line 192, in resolve_function_type
    res = defn.apply(args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/templates.py", line 207, in apply
    sig = generic(args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/arraydecl.py", line 165, in generic
    out = get_array_index_type(ary, idx)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/arraydecl.py", line 71, in get_array_index_type
    % (ty, idx))
TypeError: unsupported array index type none in (..., none)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 142, in propagate
    constraint(typeinfer)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 346, in __call__
    self.fallback(typeinfer)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 513, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/Users/ewelch/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: unsupported array index type none in (..., none)
[1] During: typing of intrinsic-call at <ipython-input-78-342b7ea4cad4> (6)
[2] During: typing of static-get-item at <ipython-input-78-342b7ea4cad4> (6)
--%<----------------------------------------------------------------------------


File "<ipython-input-78-342b7ea4cad4>", line 6:
def f1(x, y):
    <source elided>
    rv = x.copy()
    rv[..., 1:3] = y[..., np.newaxis]
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```
</details>

Traceback 2 from `numba.njit(g1)(A)`:

<details>

```python-traceback
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-97-8f9e5014c34a> in <module>()
----> 1 numba.njit(g1)(a)  # FAILS.  Traceback 2

~/miniconda3/lib/python3.5/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    347                 e.patch_message(msg)
    348 
--> 349             error_rewrite(e, 'typing')
    350         except errors.UnsupportedError as e:
    351             # Something unsupported is present in the user code, add help info

~/miniconda3/lib/python3.5/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    314                 raise e
    315             else:
--> 316                 reraise(type(e), e, None)
    317 
    318         argtypes = []

~/miniconda3/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.StaticGetItemConstraint object at 0x61855ec50>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/errors.py", line 577, in new_error_context
    yield
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 513, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 450, in resolve
    literals=literals)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 1173, in resolve_call
    literals=literals)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/context.py", line 192, in resolve_function_type
    res = defn.apply(args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/templates.py", line 207, in apply
    sig = generic(args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/arraydecl.py", line 165, in generic
    out = get_array_index_type(ary, idx)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/arraydecl.py", line 71, in get_array_index_type
    % (ty, idx))
TypeError: unsupported array index type list(int64) in (..., list(int64))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 142, in propagate
    constraint(typeinfer)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 346, in __call__
    self.fallback(typeinfer)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 513, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=self.func)
  File "/Users/ewelch/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: unsupported array index type list(int64) in (..., list(int64))
[1] During: typing of intrinsic-call at <ipython-input-48-457c682643f3> (25)
[2] During: typing of static-get-item at <ipython-input-48-457c682643f3> (25)
--%<----------------------------------------------------------------------------


File "<ipython-input-48-457c682643f3>", line 25:
def g1(x):
    return x[..., [2]]
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

</details>

Traceback 3 from `numba.njit(g5)(A)`:

<details>

```python-traceback
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-98-e5e52d72812b> in <module>()
----> 1 numba.njit(g5)(a)  # FAILS.  Traceback 3

~/miniconda3/lib/python3.5/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    347                 e.patch_message(msg)
    348 
--> 349             error_rewrite(e, 'typing')
    350         except errors.UnsupportedError as e:
    351             # Something unsupported is present in the user code, add help info

~/miniconda3/lib/python3.5/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    314                 raise e
    315             else:
--> 316                 reraise(type(e), e, None)
    317 
    318         argtypes = []

~/miniconda3/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x618563208>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/errors.py", line 577, in new_error_context
    yield
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 423, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 450, in resolve
    literals=literals)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 1173, in resolve_call
    literals=literals)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/context.py", line 205, in resolve_function_type
    return func.get_call_type_with_literals(self, args, kws, literals)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/types/functions.py", line 204, in get_call_type_with_literals
    return self.get_call_type(context, args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/types/functions.py", line 198, in get_call_type
    return self.template(context).apply(args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/templates.py", line 207, in apply
    sig = generic(args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/templates.py", line 599, in generic
    sig = method_resolver(self, ty, args, kws)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typing/arraydecl.py", line 377, in resolve_reshape
    raise TypeError("reshape() supports contiguous array only")
TypeError: reshape() supports contiguous array only

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 142, in propagate
    constraint(typeinfer)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/typeinfer.py", line 423, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/Users/ewelch/miniconda3/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/ewelch/miniconda3/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: reshape() supports contiguous array only
[1] During: resolving callee type: BoundFunction(array.reshape for array(int64, 1d, A))
[2] During: typing of call at <ipython-input-91-181700c4fadc> (2)

--%<----------------------------------------------------------------------------


File "<ipython-input-91-181700c4fadc>", line 2:
def g5(x):  # works
    return x[:, 2].reshape((-1, 1))
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

</details>

**Comment by eriknw** [comment]
I should probably add that using `numba.jit` works fine for all of these, so maybe I'm being greedy in expecting `njit` to work in these cases.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think a lot of these problems are from the use of unsupported features in indexing. Taking these in turn by error class:
* The following:
  ```python
  numba.njit(f1)(A, b)
  numba.njit(f2)(A, b)
  numba.njit(g2)(A)
  numba.njit(g4)(A)
  numba.njit(g2)(b)
  ```
  fail as `np.newaxis` is an alias of `None` which is unsupported as an indexing type.
* The following:
  ```
  numba.njit(g5)(A) 
  ```
  fails as `.reshape` in Numba is only supported on contiguous arrays, the function `g5` has a column slice of a 'C' ordered array being reshaped, which is non-contiguous hence failure.
* The following:
  ```python
  numba.njit(g1)(A)
  numba.njit(g1)(b)
  numba.njit(g3)(A)
  ```
   fail as `list` is not supported as an index type.

I've added/found these as feature requests:
* newaxis: https://github.com/numba/numba/issues/2761
* reshape non-contiguous: https://github.com/numba/numba/issues/3353
* list as index: https://github.com/numba/numba/issues/3354

**Comment by eriknw** [comment]
Thanks for distilling these into specific feature requests!

**Comment by stuartarchibald** [comment]
> Thanks for distilling these into specific feature requests!

No problem. Am going to close this as specific tickets now track each problem. Thanks for raising these issues!
