### ISSUE TITLE
Copy to host broken for __cuda_array_interface__-derived strided DeviceNDArray.

### ISSUE THREAD

**Issue by asford** [numba/numba#3334]
The copy-to-host interface of strided DeviceNDArray instances created via numba.cuda.as_cuda_arrary is currently broken, due an error in allocation of the result buffer. 

This can be reproduced by creating an "externally managed' view of an existing DeviceNDArray:

### Repro Script

```
$ cat repro_copy.py
import numpy
import numba.cuda

arr = numba.cuda.to_device(numpy.arange(100))
numpy.testing.assert_array_equal(arr.copy_to_host(), numpy.arange(100))

ext_arr = numba.cuda.as_cuda_array(arr)
numpy.testing.assert_array_equal(ext_arr.copy_to_host(), numpy.arange(100))

ext_strided_arr = numba.cuda.as_cuda_array(arr[::2])
numpy.testing.assert_array_equal(ext_strided_arr.copy_to_host(), numpy.arange(100)[::2])
```

### Repro result
```
$ python repro_copy.py
Traceback (most recent call last):
  File "repro_copy.py", line 11, in <module>
    numpy.testing.assert_array_equal(ext_strided_arr.copy_to_host(), numpy.arange(100)[::2])
  File "/scratch/USERS/fordas/workspace/numba_min/.conda/lib/python3.7/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/scratch/USERS/fordas/workspace/numba_min/.conda/lib/python3.7/site-packages/numba/cuda/cudadrv/devicearray.py", line 260, in copy_to_host
    strides=self.strides, buffer=hostary)
ValueError: strides is incompatible with shape of requested array and size of buffer
```

### Test Env
```
$ cat environment.yml
channels:
  - numba
dependencies:
  - numba
  - cudatoolkit



$ conda list
# packages in environment at /scratch/USERS/fordas/workspace/numba_min/.conda:
#
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2018.03.07                    0
certifi                   2018.8.24                py37_1
cudatoolkit               9.1                  h85f986d_0    numba
intel-openmp              2019.0                      118
libedit                   3.1.20170329         h6b74fdf_2
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgfortran-ng            7.3.0                hdf63c60_0
libstdcxx-ng              8.2.0                hdf63c60_1
llvmlite                  0.25.0           py37hf484d3e_0    numba
mkl                       2019.0                      118
mkl_fft                   1.0.4            py37h4414c95_1
mkl_random                1.0.1            py37h4414c95_1
ncurses                   6.1                  hf484d3e_0
numba                     0.41.0dev0      np115py37hf484d3e_17    numba
numpy                     1.15.1           py37h1d66e8a_0
numpy-base                1.15.1           py37h81de0dd_0
openssl                   1.0.2p               h14c3975_0
pip                       10.0.1                   py37_0
python                    3.7.0                hc3d631a_0
readline                  7.0                  h7b6447c_5
setuptools                40.2.0                   py37_0
sqlite                    3.24.0               h84994c4_0
tk                        8.6.8                hbc83047_0
wheel                     0.31.1                   py37_0
xz                        5.2.4                h14c3975_4
zlib                      1.2.11               ha838bed_2
```

**Comment by seibert** [comment]
Thanks for catching this!  We'll take a look at your PR.
