### ISSUE TITLE
typeinfer.py sets location with str instead of Loc object

### ISSUE THREAD

**Issue by Quasilyte** [numba/numba#3389]
There are at least 2 places where string literal is used instead of `Loc` object when building an error.
This leads to runtime error when `strformat` is called on `loc` attribute.
`str` lacks that method, so we have trace like:
```
Traceback (most recent call last):
  File "examples/hello.py", line 25, in <module>
    main()
  File "examples/hello.py", line 19, in main
    print(hpat(2))
  File "numba/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "numba/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "numba/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "numba/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "numba/numba/compiler.py", line 905, in compile_extra
    return pipeline.compile_extra(func)
  File "numba/numba/compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "numba/numba/compiler.py", line 836, in _compile_bytecode
    return self._compile_core()
  File "numba/numba/compiler.py", line 823, in _compile_core
    res = pm.run(self.status)
  File "numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "numba/numba/compiler.py", line 253, in run
    raise patched_exception
  File "numba/numba/compiler.py", line 244, in run
    stage()
  File "numba/numba/compiler.py", line 478, in stage_nopython_frontend
    self.locals)
  File "numba/numba/compiler.py", line 1009, in type_inference_stage
    typemap, restype, calltypes = infer.unify()
  File "numba/numba/typeinfer.py", line 924, in unify
    check_var(var)
  File "numba/numba/typeinfer.py", line 910, in check_var
    raise TypingError(msg % (var, val, loc), loc)
  File "numba/numba/errors.py", line 406, in __init__
    highlight("%s\n%s\n" % (msg, loc.strformat())))
AttributeError: Failed in hpat mode pipeline (step: nopython frontend)
'str' object has no attribute 'strformat'
```

**Comment by stuartarchibald** [comment]
Thanks for the report and potential fix. If possible the places in type inference where this is happening should be fixed with the right location information if it is available at the exception site too.
