### ISSUE TITLE
Numba cannot find libnvvm

### ISSUE THREAD

**Issue by pitrou** [numba/numba#3411]
I'm getting the following error:
```python
Traceback (most recent call last):
  File "/home/antoine/arrow/python/pyarrow/tests/test_cuda_numba_interop.py", line 137, in test_pyarrow_jit
    increment_by_one[blockspergrid, threadsperblock](darr)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 753, in __call__
    kernel = self.specialize(*args)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 764, in specialize
    kernel = self.compile(argtypes)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 783, in compile
    kernel.bind()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 500, in bind
    self._func.get()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 378, in get
    ptx = self.ptx.get()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/compiler.py", line 350, in get
    **self._extra_options)
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 474, in llvm_to_ptx
    cu = CompilationUnit()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 146, in __init__
    self.driver = NVVM()
  File "/home/antoine/miniconda3/envs/pyarrow/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 116, in __new__
    raise NvvmSupportError(errmsg % e)
numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`:
library nvvm not found
```

Even though libnvvm seems installed on my system (Ubuntu 18.04):
```
$ ls -la /usr/lib/x86_64-linux-gnu/libnvvm*
lrwxrwxrwx 1 root root       12 avril 26 14:33 /usr/lib/x86_64-linux-gnu/libnvvm.so -> libnvvm.so.3
lrwxrwxrwx 1 root root       16 avril 26 14:33 /usr/lib/x86_64-linux-gnu/libnvvm.so.3 -> libnvvm.so.3.2.0
-rw-r--r-- 1 root root 14418200 déc.   2  2017 /usr/lib/x86_64-linux-gnu/libnvvm.so.3.2.0
```
and ctypes can find it:
```python
>>> ctypes.CDLL('libnvvm.so')
<CDLL 'libnvvm.so', handle 55b4a4de2440 at 0x7f7a388db320>
```

nvcc is also here:
```
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

Note: I'm using Numba 0.40.0 (as packaged in Anaconda).

**Comment by stuartarchibald** [comment]
Thanks for the report. Do you have Anaconda's `cudatoolkit` installed in your environment? 

`ctypes.CDLL` will `dlopen('libnvvm.so')` and so will use `ld` search resolution which is probably why it succeeds in finding the system one. At present Numba does not follow that search pattern but can be asked to look for `nvvm` in a specific location by setting the `NUMBAPRO_NVVM` environment variable, more info about setting up CUDA is here http://numba.pydata.org/numba-doc/latest/user/installing.html?highlight=numbapro_nvvm#installing-using-pip-on-x86-x86-64-platforms.

There's also a couple of open tickets about trying to make this work better and be more simple to set up.
* Updated today: https://github.com/numba/numba/issues/3396#issuecomment-429852383
* https://github.com/numba/numba/issues/2879
* https://github.com/ContinuumIO/anaconda-issues/issues/6431

Hope this helps.

**Comment by pitrou** [comment]
> Thanks for the report. Do you have Anaconda's cudatoolkit installed in your environment?

No, I have Ubuntu's:
```
$ LANG=C apt search cuda-toolkit
nvidia-cuda-toolkit/bionic,now 9.1.85-3ubuntu1 amd64 [installed]
  NVIDIA CUDA development toolkit
```

Setting `NUMBAPRO_NVVM` and `NUMBAPRO_LIBDEVICE` solves the issue, but it would be nice if Numba could look in a few "standard" locations.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/4096 may fix this?

**Comment by 20zurmca** [comment]
pitrou, may I ask what you set those NUMBAPRO_NVVM and NUMBAPRO_LIBDEVICE environment variables equal to? I am having the same problem with the same operating system and setup.

**Comment by seibert** [comment]
What version of Numba are you using?  0.45 should be able to detect CUDA from the system environment, and we've also reworked the variables to be easier to set:

http://numba.pydata.org/numba-doc/latest/cuda/overview.html?highlight=cuda_home#setting-cuda-installation-path

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/4096 fixes this. Thanks all for the input.
