### ISSUE TITLE
object mode crash with list comprehension and any()

### ISSUE THREAD

**Issue by jseppanen** [numba/numba#3413]
## Reporting a bug

- [X ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

weird interaction with max of list comprehension and any of boolean array, either of them works fine alone but combined together will crash numba:

```
$ cat bug.py 

import numpy as np
from numba import jit


@jit
def foo(data):
    # commenting out this line prevents the crash:
    max_len = max([len(m) for m in data['y']])

    mask = data['x'] == 0
    if any(mask):
        print('ahaha')


data = {'x': np.arange(5), 'y': [[1], [2, 3]]}
foo(data)

$ python bug.py 
Traceback (most recent call last):
  File "bug.py", line 17, in <module>
    foo(data)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 904, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 835, in _compile_bytecode
    return self._compile_core()
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 822, in _compile_core
    res = pm.run(self.status)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 456, in stage_objectmode_frontend
    cres = self.frontend_looplift()
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/compiler.py", line 418, in frontend_looplift
    flags=loop_flags)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/transforms.py", line 191, in loop_lifting
    cfg = compute_cfg_from_blocks(blocks)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/analysis.py", line 241, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/home/jarno/miniconda3/envs/cropbot/lib/python3.6/site-packages/numba/controlflow.py", line 83, in add_edge
    assert dest in self._nodes
AssertionError: Failed in object mode pipeline (step: object mode frontend)

```
I'm running numba 0.40.0 and 0.25.0 on python 3.6.6

**Comment by jseppanen** [comment]
workaround is to put the max of list comprehension into a separate function, this doesn't crash:

```

import numpy as np
from numba import jit


@jit
def foo(data):
    ml = max_len(data['y'])
    mask = data['x'] == 0
    if any(mask):
        print('ahaha')


@jit
def max_len(xs):
    return max([len(m) for m in xs])


data = {'x': np.arange(5), 'y': [[1], [2, 3]]}
foo(data)

```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce. I think the root cause is the same as: https://github.com/numba/numba/issues/3289. Adding `forceobj=True` as a kwarg in the @jit decorator also "fixes" it.
