### ISSUE TITLE
Make it possible to annotate method from a jitclass

### ISSUE THREAD

**Issue by ogrisel** [numba/numba#3417]
Apparently at the moment it is not possible to annotate the methods of a jitclass so as to pass local types or the `parallel=True` flag for instance.

```python
>>> from numba import jitclass, njit, int8
>>> @jitclass(spec=[('a', int8)])
... class A:
...     def __init__(self, a):
...         self.a = a
... 
...     @jit(locals={'b': int8})
...     def compute_stuff(self):
...         b = 127
...         return self.a > b
...     
Traceback (most recent call last):
  File "<ipython-input-20-48fd07897bd7>", line 1, in <module>
    @jitclass(spec=[('a', int8)])
  File "/opt/venvs/py37/lib/python3.7/site-packages/numba/jitclass/decorators.py", line 27, in wrap
    return register_class_type(cls, spec, types.ClassType, ClassBuilder)
  File "/opt/venvs/py37/lib/python3.7/site-packages/numba/jitclass/base.py", line 192, in register_class_type
    raise TypeError(msg.format(members))
TypeError: class members are not yet supported: compute_stuff
```

This is observed with numba 0.40.1.

**Comment by stuartarchibald** [comment]
Thanks for this, IIRC at present the jitclass methods are each jitted with `jit(nopython=True)` with no capacity to adjust the flags etc at the location of declaration. As a work around, there shouldn't be anything stopping the class method from just calling a separately declared `njit`ed function with any flags needed. Adding the behaviour described above as a feature request...

**Comment by ogrisel** [comment]
>  class method from just calling a separately declared njited function with any flags needed

Indeed this is the work around we use now.
