### ISSUE TITLE
Issue when trying to use python's any

### ISSUE THREAD

**Issue by fabian20ro** [numba/numba#3445]
Following code:

```from numba import jit
@jit
def get_list():
    return [i for i in range(10) if any(j in range(10) for j in range(10))]
get_list()
```

Throws the following:

```C:\Python36\python.exe C:\project\small_sample.py
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\numba\errors.py", line 599, in new_error_context
    yield
  File "C:\Python36\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "C:\Python36\lib\site-packages\numba\pylowering.py", line 65, in lower_inst
    value = self.lower_assign(inst)
  File "C:\Python36\lib\site-packages\numba\pylowering.py", line 163, in lower_assign
    return self.lower_yield(value)
  File "C:\Python36\lib\site-packages\numba\pylowering.py", line 186, in lower_yield
    yp = self.generator_info.yield_points[inst.index]
AttributeError: 'NoneType' object has no attribute 'yield_points'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\project\small_sample.py", line 5, in <module>
    get_list()
  File "C:\Python36\lib\site-packages\numba\dispatcher.py", line 367, in _compile_for_args
    raise e
  File "C:\Python36\lib\site-packages\numba\dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Python36\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\numba\dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Python36\lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 904, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 835, in _compile_bytecode
    return self._compile_core()
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 822, in _compile_core
    res = pm.run(self.status)
  File "C:\Python36\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 253, in run
    raise patched_exception
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 244, in run
    stage()
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 670, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 646, in _backend
    lowered = lowerfn()
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 619, in backend_object_mode
    self.flags)
  File "C:\Python36\lib\site-packages\numba\compiler.py", line 1049, in py_lowering_stage
    lower.lower()
  File "C:\Python36\lib\site-packages\numba\lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Python36\lib\site-packages\numba\lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Python36\lib\site-packages\numba\lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "C:\Python36\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "C:\Python36\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Python36\lib\site-packages\numba\errors.py", line 607, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Python36\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
'NoneType' object has no attribute 'yield_points'

File "small_sample.py", line 4:
def get_list():
    return [i for i in range(10) if any(j in range(10) for j in range(10))]
    ^

[1] During: lowering "$4.7.79.125 = yield $4.6" at C:\project\small_sample.py (4)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!


Process finished with exit code 1
```

numba 0.40.1

For all versions, see the attached png
![versions](https://user-images.githubusercontent.com/725597/47521055-9d466680-d89a-11e8-94e2-325ff084ead9.png)

**Comment by stuartarchibald** [comment]
Thanks for the report. This is a known unsupported feature and a not particularly helpful error message! Numba does not support generator comprehension which is the root cause, a few more can be found here:
https://github.com/numba/numba/search?q=has+no+attribute+%27yield_points%27&type=Issues

Will try and at least improve the error message for the next release.

To fix your code, perhaps use a list comprehension in the `any` call?

**Comment by stuartarchibald** [comment]
The above now (as of 0.45) reports:
```
numba.errors.UnsupportedError: Failed in object mode pipeline (step: inline calls to locally defined closures)
The use of yield in a closure is unsupported.
```

**Comment by rickbeeloo** [comment]
Hey @stuartarchibald , I see this is still not supported, how would you then advise to do something like below?

Example:
```
import numpy as np
import numba as nb

m = np.zeros((30,10))

@nb.jit(nopython=True)
def run():
    a     = np.concatenate((np.arange(4), np.arange(10,30),np.arange(10001,10005)))
    print(a)
    
@nb.jit(nopython=True)
def run2():
    intervals = np.array([[0,4], [10,30], [10001,10005]])
    a     = np.concatenate(tuple(np.arange(i,j) for i,j in intervals))
    print(a)

@nb.jit(nopython=True)
def run3():
    intervals = np.array([[0,4], [10,30], [10001,10005]])  
    sizes = intervals[:,1] - intervals[:,0]
    a = np.empty(np.sum(sizes), dtype=np.intp)
    
    i = 0
    for interval in intervals:
        for val in np.arange(interval[0], interval[1]):
            a[i] = val
            i +=1
    print(a)
    
run()
run2()
run3()
```

The `run2()` here would throw `The use of yield in a closure is unsupported.`. As an alternative, I can only think of appending to an array (which would be slow) or initializing an empty array and filling that (as in `run3`), however, I'm not sure if this is what we should do when we can't use yield?

**Comment by esc** [comment]
@rickbeeloo thank you for asking about this. The issue tracker is now mostly focused on tracking bugs and their fixes. Questions about code and style are probably best asked on our Discourse: https://numba.discourse.group/
