### ISSUE TITLE
Numba could not make a constant out of something that it decided should be a constant.

### ISSUE THREAD

**Issue by malmaud** [numba/numba#3447]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numba

@numba.njit
def f(x):
    if x<1:
        raise Exception(x)
        
f(-1)
```

```
ConstantInferenceError                    Traceback (most recent call last)
<ipython-input-40-8e6746a6b70d> in <module>
----> 1 f(-1)

~/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    358             # this is from trying to infer something as constant when it isn't
    359             # or isn't supported as a constant
--> 360             error_rewrite(e, 'constant_inference')
    361         except Exception as e:
    362             if config.SHOW_HELP:

~/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    313                 raise e
    314             else:
--> 315                 reraise(type(e), e, None)
    316 
    317         argtypes = []

~/anaconda3/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

ConstantInferenceError: Failed in nopython mode pipeline (step: nopython rewrites)
Cannot make a constant from: Cannot make a constant from: Cannot make a constant from: constant inference not possible for arg(0, name=x)
Numba could not make a constant out of something that it decided should be
a constant. This could well be a current limitation in Numba's internals,
please either raise a bug report along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the example presented hits a known and documented limitation of Numba's [exception handling support](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html?highlight=exceptions#constructs):

> raise SomeException(<arguments>): in nopython mode, constructor arguments must be compile-time constants

where [`compile time constant`](http://numba.pydata.org/numba-doc/latest/glossary.html#term-compile-time-constant) is defined as:

> An expression whose value Numba can infer and freeze at compile-time. Global variables and closure variables are compile-time constants.

In the example presented `x` is not a compile time constant, but its use in the argument to `Exception` requires that to be the case.

The reason for this limitation is that at present the exception arguments are baked into the IR/machine code at compile time and as a result must be constant.

**Comment by malmaud** [comment]
Thanks for the explanation. I do wonder if the error could be made less cryptic in this context, though.

**Comment by stuartarchibald** [comment]
@malmaud no problem. The error probably is a bit cryptic and generic where in this case it is likely possible to work out what the user was doing that caused it. I've opened https://github.com/numba/numba/issues/3453 to track, thanks for the feedback.

**Comment by stuartarchibald** [comment]
@malmaud just as an update, #3718 fixes this to give output as follows:
```
Traceback (most recent call last):
  File "issue3447.py", line 8, in <module>
    f(-1)
  File "<path>/numba/numba/dispatcher.py", line 362, in _compile_for_args
    error_rewrite(e, 'constant_inference')
  File "<path>/numba/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.ConstantInferenceError: Failed in nopython mode pipeline (step: nopython rewrites)
Constant inference not possible for: arg(0, name=x)

File "issue3447.py", line 6:
def f(x):
    <source elided>
    if x<1:
        raise Exception(x)
        ^

Numba could not make a constant out of something that it decided should be
a constant. This could well be a current limitation in Numba's internals,
however please first check that your code is valid for compilation,
particularly with respect to string interpolation (not supported!) and
the requirement of compile time constants as arguments to exceptions:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html?highlight=exceptions#constructs

If the code is valid and the unsupported functionality is important to you
please file a feature request at: https://github.com/numba/numba/issues/new

If you think your code should work with Numba. 
Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by malmaud** [comment]
Thanks!
