### ISSUE TITLE
autojit bug for extension classes when one method calls another

### ISSUE THREAD

**Issue by yegulalp** [numba/numba#346]
```
from numba import autojit

@autojit
class Foo(object):
    def __init__(self,x):
        self.x = x
    def inc(self):
        self.x += 1
    def runInc(self):
        self.inc()

f = Foo(1.0)
f.inc()
f.runInc()
```

Output:

```
C:\Python33\python.exe C:/Users/yegulalp/PycharmProjects/fast/scraps/numbaBugDemo3.py
Traceback (most recent call last):
  File "C:\Python33\lib\site-packages\numba\pipeline.py", line 194, in __call__
    ast = self.transform(ast, env)
  File "C:\Python33\lib\site-packages\numba\pipeline.py", line 515, in transform
    return specializer.visit(ast)
  File "C:\Python33\lib\ast.py", line 247, in visit
    return visitor(node)
  File "C:\Python33\lib\ast.py", line 303, in generic_visit
    value = self.visit(value)
  File "C:\Python33\lib\ast.py", line 247, in visit
    return visitor(node)
  File "C:\Python33\lib\ast.py", line 312, in generic_visit
    new_node = self.visit(old_value)
  File "C:\Python33\lib\ast.py", line 247, in visit
    return visitor(node)
  File "C:\Python33\lib\site-packages\numba\specialize\exttypes.py", line 45, in visit_NativeFunctionCallNode
    self.visitchildren(node)
  File "C:\Python33\lib\ast.py", line 312, in generic_visit
    new_node = self.visit(old_value)
  File "C:\Python33\lib\ast.py", line 247, in visit
    return visitor(node)
  File "C:\Python33\lib\site-packages\numba\specialize\exttypes.py", line 56, in visit_ExtensionMethod
    "must be called" % node.attr)
numba.error.NumbaError: 10:4: Referenced extension method 'inc' must be called

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/yegulalp/PycharmProjects/fast/scraps/numbaBugDemo3.py", line 14, in <module>
    f.runInc()
  File "numbawrapper.pyx", line 288, in numba.numbawrapper.BoundSpecializingWrapper.__call__ (numba\numbawrapper.c:5041)
  File "numbawrapper.pyx", line 190, in numba.numbawrapper._NumbaSpecializingWrapper.__call__ (numba\numbawrapper.c:3726)
  File "C:\Python33\lib\site-packages\numba\wrapping\compiler.py", line 69, in compile_from_args
    return self.compile(signature)
  File "C:\Python33\lib\site-packages\numba\wrapping\compiler.py", line 121, in compile
    self.env, self.extclass, self.method, signature)
  File "C:\Python33\lib\site-packages\numba\exttypes\autojitclass.py", line 174, in autojit_method_compiler
    argtypes=signature.args)
  File "C:\Python33\lib\site-packages\numba\pipeline.py", line 144, in compile2
    post_ast = pipeline(func_ast, env)
  File "C:\Python33\lib\site-packages\numba\pipeline.py", line 191, in __call__
    ast = self.transform(ast, env)
  File "C:\Python33\lib\site-packages\numba\pipeline.py", line 656, in transform
    ast = stage(ast, env)
  File "C:\Python33\lib\site-packages\numba\pipeline.py", line 641, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "C:\Python33\lib\site-packages\numba\pipeline.py", line 202, in __call__
    reporting.report(env, exc=e)
  File "C:\Python33\lib\site-packages\numba\reporting.py", line 181, in report
    raise exc
  File "C:\Python33\lib\site-packages\numba\reporting.py", line 175, in report
    function_error_env.collection.report(post_mortem)
  File "C:\Python33\lib\site-packages\numba\reporting.py", line 130, in report
    raise error.NumbaError("(see below)\n" + message.strip(), has_report=True)
numba.error.NumbaError: (see below)
--------------------- Numba Encountered Errors or Warnings ---------------------
        self.inc()
----^
Error 10:4: Referenced extension method 'inc' must be called
--------------------------------------------------------------------------------

Process finished with exit code 1
```

**Comment by seibert** [comment]
Closing as this form of jit classes was dropped in Numba 0.13
