### ISSUE TITLE
parfors SIGFPE core dumps

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3461]
## Reporting a bug

- [x] I am using the ~~latest released~~ master branch version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Not sure if this is something wrong with parfors code gen or the threading backend or both, but this:
```python
from numba import njit, prange
import numpy as np

def test_impl(X):
    n = X.shape[0]
    acc = 0
    for i in prange(n):
        acc += np.sum(np.arange(i) + np.sum(np.arange(i)[:i]))
    return acc

n = 128
np.random.seed(0)
X = np.random.ranf(n)
print(test_impl(X))
print(njit(test_impl)(X))
print(njit(parallel=True)(test_impl)(X))
```
does this:
```
$ python test3455.py 
33028128
33028128
Floating point exception (core dumped)
```
and under `gdb`:
```
Program received signal SIGFPE, Arithmetic exception.
[Switching to Thread 0x7fffd9421700 (LWP 18393)]
0x00007fffeaf7833c in $3cdynamic$3e::__numba_parfor_gufunc__0x7ffff80002639dfc$2416(Array<unsigned long long, 1, C, mutable, aligned>, Array<long long, 1, C, mutable, aligned>) ()
(gdb) bt
#0  0x00007fffeaf7833c in $3cdynamic$3e::__numba_parfor_gufunc__0x7ffff80002639dfc$2416(Array<unsigned long long, 1, C, mutable, aligned>, Array<long long, 1, C, mutable, aligned>) ()
#1  0x00007fffeaf7608f in __gufunc__._ZN13$3cdynamic$3e46__numba_parfor_gufunc__0x7ffff80002639dfc$2416E5ArrayIyLi1E1C7mutable7alignedE5ArrayIxLi1E1C7mutable7alignedE ()
#2  0x00007fffd9424180 in thread_worker ()
   from<path>/numba/npyufunc/workqueue.cpython-37m-x86_64-linux-gnu.so
#3  0x00007ffff7bc6e25 in start_thread (arg=0x7fffd9421700) at pthread_create.c:308
#4  0x00007ffff78f0bad in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113
```
doesn't matter which threading backend is used, the result is the same.

**Comment by DrTodd13** [comment]
This problem has something to do with slicing.  If you sum np.arange(i) instead of np.arange(i)[:i] then it works.  Also, if you change it to np.arange(i+1)[:i] then it also works.
