### ISSUE TITLE
LoweringError when passing kwargs to print()

### ISSUE THREAD

**Issue by nathanielvirgo** [numba/numba#3474]
- [* ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [* ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I tried to pass `flush=True` to `print()` in `nopython` mode, and got the error below, so I am duly reporting it. It occurs for any keyword argument passed to `print()`. I'll open a separate feature request for the ability to flush STDOUT. 

This is with numba 0.40.1, using Python 3.6 installed via macports on OS X 10.11. numba is installed using pip.

Minimal reproducer:

```
import numba as nb

@nb.njit
def test():
	print("hello", foo=True)

test()

```

resulting error:

```
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
unsupported keyword arguments when calling Function(<built-in function print>)

File "minimal_reproducer.py", line 5:
def test():
	print("hello", foo=True)
 ^

[1] During: lowering "$0.5 = call $0.1($const0.2, func=$0.1, args=[Var($const0.2, min_nwa.py (5))], kws=[('foo', Var($const0.3, min_nwa.py (5)))], vararg=None)" at min_nwa.py (5)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment]
Thanks for the report. The lack of support for kwargs in `print` should have been caught ahead of trying to lower the print function to machine code. I've opened #3487 to feedback this issue to the user, with the patch applied, the sample code now does:
```python
$ python issue3474.py  
Traceback (most recent call last):
  File "issue3474.py", line 7, in <module>
    test()
  File "<path>/numba/numba/dispatcher.py", line 351, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "<path>/numba/numba/dispatcher.py", line 315, in error_rewrite
    reraise(type(e), e, None)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in nopython mode pipeline (step: nopython rewrites)
Numba's print() function implementation does not support keyword arguments.

File "issue3474.py", line 5:
def test():
        print("hello", flush=True)
        ^

Unsupported functionality was found in the code Numba was trying to compile.

If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new
```
