### ISSUE TITLE
NotImplementedError: Unable to cast from { i64, i8* }* to { i64, i8* }

### ISSUE THREAD

**Issue by riccardomurri** [numba/numba#350]
When trying to run the [FatGHoL](http://fatghol.googlecode.com/) code
through Numba, I get the following error and traceback:

    Traceback (most recent call last):
      File "/home/user/rmurri/euroscipy2013/fatghol.numba/fatghol/mgn.py", line 57, in <module>
        from fatghol.graph_homology import FatgraphComplex, NumberedFatgraphPool
      File "/home/user/rmurri/euroscipy2013/fatghol.numba/fatghol/graph_homology.py", line 48, in <module>
        from fatghol.homology import (
      File "/home/user/rmurri/euroscipy2013/fatghol.numba/fatghol/homology.py", line 44, in <module>
        NullMatrix = SimpleMatrix(0,0)
      File "numbawrapper.pyx", line 288, in numba.numbawrapper.BoundSpecializingWrapper.__call__ (numba/numbawrapper.c:5041)
      File "numbawrapper.pyx", line 190, in numba.numbawrapper._NumbaSpecializingWrapper.__call__ (numba/numbawrapper.c:3726)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/wrapping/compiler.py", line 69, in compile_from_args
        return self.compile(signature)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/wrapping/compiler.py", line 88, in compile
        compiled_function = dec(self.py_func)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/decorators.py", line 224, in _jit_decorator
        nopython=nopython, func_ast=func_ast, **kwargs)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/decorators.py", line 133, in compile_function
        func_env = pipeline.compile2(env, func, restype, argtypes, func_ast=func_ast, **kwds)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/pipeline.py", line 144, in compile2
        post_ast = pipeline(func_ast, env)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/pipeline.py", line 191, in __call__
        ast = self.transform(ast, env)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/pipeline.py", line 656, in transform
        ast = stage(ast, env)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/pipeline.py", line 641, in _stage
        return _check_stage_object(stage_obj)(ast, env)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/pipeline.py", line 194, in __call__
        ast = self.transform(ast, env)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/pipeline.py", line 553, in transform
        func_env.translator.translate()
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/codegen/translate.py", line 342, in translate
        self.visit(node)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/codegen/translate.py", line 152, in visit
        result = fn(node)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/codegen/translate.py", line 590, in visit_Assign
        decref=decref, incref=incref)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/codegen/translate.py", line 603, in generate_assign_stack
        lvalue = self.caster.cast(lvalue, ltarget.type.pointee)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/llvm_types.py", line 91, in cast
        return self.build_cast(self.builder, lvalue, dst_ltype, *args, **kws)
      File "/home/user/rmurri/sw/src/numba-numba-a1f09db/lib/python2.7/site-packages/numba/llvm_types.py", line 191, in build_cast
        (str(lty1), str(lty2)))
    NotImplementedError: Unable to cast from { i64, i8* }* to { i64, i8* }.

The code runs just fine with Python 2.6+, all I did was adding
`@numba.autojit` decorators to some functions.

Full output available at <https://gist.github.com/riccardomurri/6763235>

**Comment by pitrou** [comment]
Closing as outdated. Don't hesitate to reopen if you can reproduce with a recent Numba.
