### ISSUE TITLE
"This should not have happened" ~ checking for value in numpy array

### ISSUE THREAD

**Issue by cubu0178** [numba/numba#3525]
jupyter notebooks via anaconda
version 0.39.0

```python
@jit(nopython=True)
def qw():
    q=np.array([1,2])
    t=False
    for i in q:
        if i ==np.array([1,2]):
            t==True
    if t:
        print('in')
    return q
            
qw()
```
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
C:\Users\Curry\Anaconda3\lib\site-packages\numba\targets\base.py in cast(self, builder, val, fromty, toty)
    675             impl = self._casts.find((fromty, toty))
--> 676             return impl(self, builder, fromty, toty, val)
    677         except NotImplementedError:

C:\Users\Curry\Anaconda3\lib\site-packages\numba\targets\numbers.py in any_to_boolean(context, builder, fromty, toty, val)
   1346 def any_to_boolean(context, builder, fromty, toty, val):
-> 1347     return context.is_true(builder, fromty, val)
   1348 

C:\Users\Curry\Anaconda3\lib\site-packages\numba\targets\base.py in is_true(self, builder, typ, val)
    711         """
--> 712         impl = self.get_function(bool, typing.signature(types.boolean, typ))
    713         return impl(builder, (val,))

C:\Users\Curry\Anaconda3\lib\site-packages\numba\targets\base.py in get_function(self, fn, sig, _firstcall)
    536             self.refresh()
--> 537             return self.get_function(fn, sig, _firstcall=False)
    538 

C:\Users\Curry\Anaconda3\lib\site-packages\numba\targets\base.py in get_function(self, fn, sig, _firstcall)
    538 
--> 539         raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
    540 

NotImplementedError: No definition for lowering <class 'bool'>(array(bool, 1d, C),) -> bool

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
C:\Users\Curry\Anaconda3\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    576     try:
--> 577         yield
    578     except NumbaError as e:

C:\Users\Curry\Anaconda3\lib\site-packages\numba\lowering.py in lower_block(self, block)
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 

C:\Users\Curry\Anaconda3\lib\site-packages\numba\lowering.py in lower_inst(self, inst)
    311             condty = self.typeof(inst.cond.name)
--> 312             pred = self.context.cast(self.builder, cond, condty, types.boolean)
    313             assert pred.type == Type.int(1), ("cond is not i1: %s" % pred.type)

C:\Users\Curry\Anaconda3\lib\site-packages\numba\targets\base.py in cast(self, builder, val, fromty, toty)
    678             raise NotImplementedError(
--> 679                 "Cannot cast %s to %s: %s" % (fromty, toty, val))
    680 

NotImplementedError: Cannot cast array(bool, 1d, C) to bool: %".541" = load {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}* %"$37.9"

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-48-2a58a6748a6e> in <module>()
----> 1 qw()

C:\Users\Curry\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    366                     e.patch_message(''.join(e.args) + help_msg)
    367             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 368             raise e
    369 
    370     def inspect_llvm(self, signature=None):

C:\Users\Curry\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    323                 argtypes.append(self.typeof_pyval(a))
    324         try:
--> 325             return self.compile(tuple(argtypes))
    326         except errors.TypingError as e:
    327             # Intercept typing error that may be due to an argument

C:\Users\Curry\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    651 
    652                 self._cache_misses[sig] += 1
--> 653                 cres = self._compiler.compile(args, return_type)
    654                 self.add_overload(cres)
    655                 self._cache.save_overload(sig, cres)

C:\Users\Curry\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     81                                       args=args, return_type=return_type,
     82                                       flags=flags, locals=self.locals,
---> 83                                       pipeline_class=self.pipeline_class)
     84         # Check typing error if object mode is used
     85         if cres.typing_error is not None and not flags.enable_pyobject:

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    871     pipeline = pipeline_class(typingctx, targetctx, library,
    872                               args, return_type, flags, locals)
--> 873     return pipeline.compile_extra(func)
    874 
    875 

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    365         self.lifted = ()
    366         self.lifted_from = None
--> 367         return self._compile_bytecode()
    368 
    369     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    802         """
    803         assert self.func_ir is None
--> 804         return self._compile_core()
    805 
    806     def _compile_ir(self):

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    789         self.define_pipelines(pm)
    790         pm.finalize()
--> 791         res = pm.run(self.status)
    792         if res is not None:
    793             # Early pipeline completion

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    251                     # No more fallback pipelines?
    252                     if is_final_pipeline:
--> 253                         raise patched_exception
    254                     # Go to next fallback pipeline
    255                     else:

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in run(self, status)
    243                 try:
    244                     event(stage_name)
--> 245                     stage()
    246                 except _EarlyPipelineCompletion as e:
    247                     return e.result

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in stage_nopython_backend(self)
    676         """
    677         lowerfn = self.backend_nopython_mode
--> 678         self._backend(lowerfn, objectmode=False)
    679 
    680     def stage_compile_interp_mode(self):

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in _backend(self, lowerfn, objectmode)
    626             self.library.enable_object_caching()
    627 
--> 628         lowered = lowerfn()
    629         signature = typing.signature(self.return_type, *self.args)
    630         self.cr = compile_result(

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in backend_nopython_mode(self)
    613                 self.return_type,
    614                 self.calltypes,
--> 615                 self.flags)
    616 
    617     def _backend(self, lowerfn, objectmode):

C:\Users\Curry\Anaconda3\lib\site-packages\numba\compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags)
    990 
    991     lower = lowering.Lower(targetctx, library, fndesc, interp)
--> 992     lower.lower()
    993     if not flags.no_cpython_wrapper:
    994         lower.create_cpython_wrapper(flags.release_gil)

C:\Users\Curry\Anaconda3\lib\site-packages\numba\lowering.py in lower(self)
    171         if self.generator_info is None:
    172             self.genlower = None
--> 173             self.lower_normal_function(self.fndesc)
    174         else:
    175             self.genlower = self.GeneratorLower(self)

C:\Users\Curry\Anaconda3\lib\site-packages\numba\lowering.py in lower_normal_function(self, fndesc)
    212         # Init argument values
    213         self.extract_function_arguments()
--> 214         entry_block_tail = self.lower_function_body()
    215 
    216         # Close tail of entry block

C:\Users\Curry\Anaconda3\lib\site-packages\numba\lowering.py in lower_function_body(self)
    237             bb = self.blkmap[offset]
    238             self.builder.position_at_end(bb)
--> 239             self.lower_block(block)
    240 
    241         self.post_lower()

C:\Users\Curry\Anaconda3\lib\site-packages\numba\lowering.py in lower_block(self, block)
    252             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    253                                    loc=self.loc, errcls_=defaulterrcls):
--> 254                 self.lower_inst(inst)
    255 
    256     def create_cpython_wrapper(self, release_gil=False):

C:\Users\Curry\Anaconda3\lib\contextlib.py in __exit__(self, type, value, traceback)
     75                 value = type()
     76             try:
---> 77                 self.gen.throw(type, value, traceback)
     78                 raise RuntimeError("generator didn't stop after throw()")
     79             except StopIteration as exc:

C:\Users\Curry\Anaconda3\lib\site-packages\numba\errors.py in new_error_context(fmt_, *args, **kwargs)
    583         from numba import config
    584         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 585         six.reraise(type(newerr), newerr, tb)
    586 
    587 

C:\Users\Curry\Anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed at nopython (nopython mode backend)
Cannot cast array(bool, 1d, C) to bool: %".541" = load {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, i8*, [1 x i64], [1 x i64]}* %"$37.9"

File "<ipython-input-46-ed1b37711e9f>", line 6:
def qw():
    <source elided>
    for i in q:
        if i ==np.array([1,2]):
        ^
[1] During: lowering "branch $37.9, 67, 98" at <ipython-input-46-ed1b37711e9f> (6)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment]
NOTE: formatted comment to markdown.

**Comment by stuartarchibald** [comment]
Thanks for the report. It seems like the sample code:
```python
import numpy as np

def qw():
    q=np.array([1, 2])
    t=False
    for i in q:
        if i == np.array([1, 2]):
            t == True
    if t:
        print('in')
    return q

qw()
```
does not work without the Numba `@jit` decorator either, it gives:
```
$ python issue3525.py 
Traceback (most recent call last):
  File "issue3525.py", line 13, in <module>
    qw()
  File "issue3525.py", line 7, in qw
    if i == np.array([1, 2]):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
However, Numba's error message/problem catching needs improvement as this should have failed earlier with a more meaningful message. For this reason I'm going to mark this as a bug.

**Comment by stuartarchibald** [comment]
As of mainline for 0.55, Numba replicates NumPy with:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
Closing.
