### ISSUE TITLE
NotImplementedError: make_function - during tuple unpacking

### ISSUE THREAD

**Issue by joerobmunoz** [numba/numba#3547]
### Description
Reporting this because the prompt asked me to.

Simple functions seem to fail creation when combining list comprehension and a dataframe parameter. I haven't played around to see what the extent of breaking parameters are, nor have I dug into the list comprehension.

### Code
```python
from numba import jit
import pandas as pd

@jit
def test_pass(x):
    """Base case: param, no list comprehension"""
    a, b = (1, 2)
    return a, b

@jit
def test_pass_no_params():
    """Base case: no params, list comprehension"""
    a, b = [1 for col in range(2)]
    return a, b

@jit
def test_fail(x):
    """
    Pass in a dataframe, but do not use it as in 'test_pass_no_params'.
    Case: unused param + list comprehension
    """
    a, b = [1 for col in range(2)]
    return a, b


# Garbage data
x = pd.DataFrame([['11safsd','11sas'],['22fafads','22asd']], columns=['a','b'])

for i, row in x.iterrows():
    a, b = test_pass(x)
    print(f'test_pass: {a,b}')
    a, b = test_pass_no_params()
    print(f'test_pass_no_params: {a,b}')
    a, b = test_fail(x)
    print(f'test_fail: {a,b}')
```

### Output
```
test_pass: (1, 2)
test_pass_no_params: (1, 1)
Traceback (most recent call last):
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\errors.py", line 577, in new_error_context
    yield
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\objmode.py", line 65, in lower_inst
    value = self.lower_assign(inst)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\objmode.py", line 159, in lower_assign
    return self.lower_expr(value)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\objmode.py", line 373, in lower_expr
    raise NotImplementedError(expr)
NotImplementedError: make_function(name=$const0.2, code=<code object <listcomp> at 0x00000000021D9D20, file "<REDACTED>\test.py", line 35>, closure=None, defaults=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<REDACTED>\test.py", line 47, in <module>
    a, b = test_fail(x)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\dispatcher.py", line 368, in _compile_for_args
    raise e
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\dispatcher.py", line 325, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\dispatcher.py", line 653, in compile
    cres = self._compiler.compile(args, return_type)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 873, in compile_extra
    return pipeline.compile_extra(func)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 367, in compile_extra
    return self._compile_bytecode()
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 804, in _compile_bytecode
    return self._compile_core()
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 791, in _compile_core
    res = pm.run(self.status)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 253, in run
    raise patched_exception
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 652, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 628, in _backend
    lowered = lowerfn()
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 601, in backend_object_mode
    self.flags)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\compiler.py", line 1018, in py_lowering_stage
    lower.lower()
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\lowering.py", line 173, in lower
    self.lower_normal_function(self.fndesc)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\lowering.py", line 214, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\lowering.py", line 239, in lower_function_body
    self.lower_block(block)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\lowering.py", line 254, in lower_block
    self.lower_inst(inst)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\errors.py", line 585, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "<REDACTED>\AppData\Local\Continuum\Anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at object (object mode backend)
[1m[1mmake_function(name=$const0.2, code=<code object <listcomp> at 0x00000000021D9D20, file "<REDACTED>\test.py", line 35>, closure=None, defaults=None)
[1m
File "test.py", line 35:[0m
[1mdef test_fail(x):
    <source elided>
    """
[1m    a, b = [1 for col in range(2)]
[0m    [1m^[0m[0m[0m
[0m[1m[1] During: lowering "$0.3 = make_function(name=$const0.2, code=<code object <listcomp> at 0x00000000021D9D20, file "<REDACTED>\test.py", line 35>, closure=None, defaults=None)" at <REDACTED>\test.py (35)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Which version of Numba are you using? I tried the above with `0.41.0` (latest release) and could not reproduce, I think the issue you are seeing was caused by a missing compiler pass in the object mode compilation pipeline that got fixed in https://github.com/numba/numba/pull/3122 (patch went into Numba version 0.40.0).

**Comment by joerobmunoz** [comment]
Great catch.

I've upgraded to 0.41.0 and each test case seems to be working great.

Thanks and closing.

**Comment by stuartarchibald** [comment]
Thanks for reporting back, glad it is now working for you.
