### ISSUE TITLE
Cannot unify Literal[int](0) and int64

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#3565]
Upgrading to the latest numba version `0.41.0` broke some old code of mine, which used to work with numba `0.40.1`. I believe the issue boils down to the newly introduced integer literals not working as expected. A minimal example for reproducing the error is

```python
from numba import njit
from typing import NamedTuple

class Data2(NamedTuple):
    a: int
    b: int

        
@njit
def Data1(value):
    return Data2(value, 0)


@njit
def call(i, j):
    if j == 0:
        result = Data1(i)
    else:
        result = Data2(i, j)

    return result            

call(1, 1)
```

This results in the following error:

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-60-b047fa49e45c> in <module>()
----> 1 call(1, 1)

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    346                 e.patch_message(msg)
    347 
--> 348             error_rewrite(e, 'typing')
    349         except errors.UnsupportedError as e:
    350             # Something unsupported is present in the user code, add help info

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    313                 raise e
    314             else:
--> 315                 reraise(type(e), e, None)
    316 
    317         argtypes = []

/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify Data2(int64, Literal[int](0)) and Data2(int64 x 2) for 'result', defined at <ipython-input-59-68b6396882a7> (14)

File "<ipython-input-59-68b6396882a7>", line 14:
def call(i, j):
    <source elided>
    if j == 0:
        result = Data1(i)
        ^

[1] During: typing of assignment at <ipython-input-59-68b6396882a7> (16)

File "<ipython-input-59-68b6396882a7>", line 16:
def call(i, j):
    <source elided>
    else:
        result = Data2(i, j)
        ^
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Should be fixed by @sklam in https://github.com/numba/numba/pull/3567.
