### ISSUE TITLE
Error when calling parallelized function from compiled function

### ISSUE THREAD

**Issue by david-zwicker** [numba/numba#3582]
While playing around with parallelization in numba using `numba.prange` I encountered the following error, which might be a bug. A self-contained example is

```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def func_(arr, out):
    for i in prange(arr.size):
        out[i] = arr[i]
        
@njit
def func(arr, out=None):
    """ apply laplace operator to array `arr` """
    if out is None:
        out = np.empty_like(arr)
    func_(arr, out)
    return out

func(np.arange(3))
```

The resulting error is 
```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-3-5c0fe7e83cab> in <module>()
     15     return out
     16 
---> 17 func(np.arange(3))

/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    346                 e.patch_message(msg)
    347 
--> 348             error_rewrite(e, 'typing')
    349         except errors.UnsupportedError as e:
    350             # Something unsupported is present in the user code, add help info

/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    313                 raise e
    314             else:
--> 315                 reraise(type(e), e, None)
    316 
    317         argtypes = []

/srv/conda/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7f0dd4b1ba58>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/numba/errors.py", line 609, in new_error_context
    yield
  File "/srv/conda/lib/python3.6/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/srv/conda/lib/python3.6/site-packages/numba/lowering.py", line 408, in lower_inst
    func(self, inst)
  File "/srv/conda/lib/python3.6/site-packages/numba/npyufunc/parfor.py", line 280, in _lower_parfor_parallel
    parfor.races)
  File "/srv/conda/lib/python3.6/site-packages/numba/npyufunc/parfor.py", line 1261, in call_parallel_gufunc
    builder.store(arg, ptr)
  File "/srv/conda/lib/python3.6/site-packages/llvmlite/ir/builder.py", line 704, in store
    % (value.type, ptr.type))
TypeError: cannot store {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i1} to {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i8}*: mismatching types

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/conda/lib/python3.6/site-packages/numba/typeinfer.py", line 141, in propagate
    constraint(typeinfer)
  File "/srv/conda/lib/python3.6/site-packages/numba/typeinfer.py", line 422, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/srv/conda/lib/python3.6/site-packages/numba/typeinfer.py", line 446, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/srv/conda/lib/python3.6/site-packages/numba/typeinfer.py", line 1231, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/srv/conda/lib/python3.6/site-packages/numba/typing/context.py", line 190, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/srv/conda/lib/python3.6/site-packages/numba/typing/context.py", line 242, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/srv/conda/lib/python3.6/site-packages/numba/types/functions.py", line 280, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py", line 272, in get_call_template
    self.compile(tuple(args))
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 717, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 653, in backend_nopython_mode
    self.metadata)
  File "/srv/conda/lib/python3.6/site-packages/numba/compiler.py", line 1048, in native_lowering_stage
    lower.lower()
  File "/srv/conda/lib/python3.6/site-packages/numba/lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "/srv/conda/lib/python3.6/site-packages/numba/lowering.py", line 219, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/srv/conda/lib/python3.6/site-packages/numba/lowering.py", line 244, in lower_function_body
    self.lower_block(block)
  File "/srv/conda/lib/python3.6/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/srv/conda/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/srv/conda/lib/python3.6/site-packages/numba/errors.py", line 617, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/srv/conda/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
cannot store {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i1} to {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i8}*: mismatching types

File "<ipython-input-3-5c0fe7e83cab>", line 6:
def func_(arr, out):
    for i in prange(arr.size):
    ^

[1] During: lowering "id=1[LoopNest(index_variable = parfor_index.47, range = (0, $2.3, 1))]{14: <ir.Block at <ipython-input-3-5c0fe7e83cab> (6)>}Var(parfor_index.47, <ipython-input-3-5c0fe7e83cab> (6))" at <ipython-input-3-5c0fe7e83cab> (6)
[2] During: resolving callee type: type(CPUDispatcher(<function func_ at 0x7f0dd4b806a8>))
[3] During: typing of call at <ipython-input-3-5c0fe7e83cab> (14)

--%<----------------------------------------------------------------------------


File "<ipython-input-3-5c0fe7e83cab>", line 14:
def func(arr, out=None):
    <source elided>
        out = np.empty_like(arr)
    func_(arr, out)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
[...]
```

Note that my intention was to write a function like the following
```python
@njit(parallel=True)
def func(arr, out=None):
    """ apply laplace operator to array `arr` """
    if out is None:
        out = np.empty_like(arr)
    for i in prange(arr.size):
        out[i] = arr[i]
    return out
```
which fails with a different error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/srv/conda/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    608     try:
--> 609         yield
    610     except NumbaError as e:

/srv/conda/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 

/srv/conda/lib/python3.6/site-packages/numba/lowering.py in lower_inst(self, inst)
    407                 if isinstance(inst, _class):
--> 408                     func(self, inst)
    409                     return

/srv/conda/lib/python3.6/site-packages/numba/npyufunc/parfor.py in _lower_parfor_parallel(lowerer, parfor)
    279         index_var_typ,
--> 280         parfor.races)
    281     if config.DEBUG_ARRAY_OPT:

/srv/conda/lib/python3.6/site-packages/numba/npyufunc/parfor.py in call_parallel_gufunc(lowerer, cres, gu_signature, outer_sig, expr_args, expr_arg_types, loop_ranges, redvars, reddict, redarrdict, init_block, index_var_typ, races)
   1260                 ptr = cgutils.alloca_once(builder, typ)
-> 1261                 builder.store(arg, ptr)
   1262             else:

/srv/conda/lib/python3.6/site-packages/llvmlite/ir/builder.py in store(self, value, ptr, align)
    703             raise TypeError("cannot store %s to %s: mismatching types"
--> 704                             % (value.type, ptr.type))
    705         st = instructions.StoreInstr(self.block, value, ptr)

TypeError: cannot store {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i1} to {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i8}*: mismatching types

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-6-476298123cdd> in <module>()
      7         out[i] = arr[i]
      8     return out
----> 9 func(np.arange(3))

/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    365                     e.patch_message(''.join(e.args) + help_msg)
    366             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 367             raise e
    368 
    369     def inspect_llvm(self, signature=None):

/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    322                 argtypes.append(self.typeof_pyval(a))
    323         try:
--> 324             return self.compile(tuple(argtypes))
    325         except errors.TypingError as e:
    326             # Intercept typing error that may be due to an argument

/srv/conda/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, sig)
    653 
    654             self._cache_misses[sig] += 1
--> 655             cres = self._compiler.compile(args, return_type)
    656             self.add_overload(cres)
    657             self._cache.save_overload(sig, cres)

/srv/conda/lib/python3.6/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     80                                       args=args, return_type=return_type,
     81                                       flags=flags, locals=self.locals,
---> 82                                       pipeline_class=self.pipeline_class)
     83         # Check typing error if object mode is used
     84         if cres.typing_error is not None and not flags.enable_pyobject:

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    924     pipeline = pipeline_class(typingctx, targetctx, library,
    925                               args, return_type, flags, locals)
--> 926     return pipeline.compile_extra(func)
    927 
    928 

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in compile_extra(self, func)
    372         self.lifted = ()
    373         self.lifted_from = None
--> 374         return self._compile_bytecode()
    375 
    376     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in _compile_bytecode(self)
    855         """
    856         assert self.func_ir is None
--> 857         return self._compile_core()
    858 
    859     def _compile_ir(self):

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in _compile_core(self)
    842         self.define_pipelines(pm)
    843         pm.finalize()
--> 844         res = pm.run(self.status)
    845         if res is not None:
    846             # Early pipeline completion

/srv/conda/lib/python3.6/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    253                     # No more fallback pipelines?
    254                     if is_final_pipeline:
--> 255                         raise patched_exception
    256                     # Go to next fallback pipeline
    257                     else:

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in run(self, status)
    244                 try:
    245                     event(stage_name)
--> 246                     stage()
    247                 except _EarlyPipelineCompletion as e:
    248                     return e.result

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in stage_nopython_backend(self)
    715         """
    716         lowerfn = self.backend_nopython_mode
--> 717         self._backend(lowerfn, objectmode=False)
    718 
    719     def stage_compile_interp_mode(self):

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    664             self.library.enable_object_caching()
    665 
--> 666         lowered = lowerfn()
    667         signature = typing.signature(self.return_type, *self.args)
    668         self.cr = compile_result(

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in backend_nopython_mode(self)
    651                 self.calltypes,
    652                 self.flags,
--> 653                 self.metadata)
    654 
    655     def _backend(self, lowerfn, objectmode):

/srv/conda/lib/python3.6/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags, metadata)
   1046         lower = lowering.Lower(targetctx, library, fndesc, interp,
   1047                                metadata=metadata)
-> 1048         lower.lower()
   1049         if not flags.no_cpython_wrapper:
   1050             lower.create_cpython_wrapper(flags.release_gil)

/srv/conda/lib/python3.6/site-packages/numba/lowering.py in lower(self)
    176         if self.generator_info is None:
    177             self.genlower = None
--> 178             self.lower_normal_function(self.fndesc)
    179         else:
    180             self.genlower = self.GeneratorLower(self)

/srv/conda/lib/python3.6/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    217         # Init argument values
    218         self.extract_function_arguments()
--> 219         entry_block_tail = self.lower_function_body()
    220 
    221         # Close tail of entry block

/srv/conda/lib/python3.6/site-packages/numba/lowering.py in lower_function_body(self)
    242             bb = self.blkmap[offset]
    243             self.builder.position_at_end(bb)
--> 244             self.lower_block(block)
    245 
    246         self.post_lower()

/srv/conda/lib/python3.6/site-packages/numba/lowering.py in lower_block(self, block)
    257             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 
    261     def create_cpython_wrapper(self, release_gil=False):

/srv/conda/lib/python3.6/contextlib.py in __exit__(self, type, value, traceback)
     97                 value = type()
     98             try:
---> 99                 self.gen.throw(type, value, traceback)
    100             except StopIteration as exc:
    101                 # Suppress StopIteration *unless* it's the same exception that

/srv/conda/lib/python3.6/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    615         from numba import config
    616         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 617         six.reraise(type(newerr), newerr, tb)
    618 
    619 

/srv/conda/lib/python3.6/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
cannot store {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i1} to {{i8*, i8*, i64, i64, i64*, [1 x i64], [1 x i64]}, i8}*: mismatching types

File "<ipython-input-6-476298123cdd>", line 6:
def func(arr, out=None):
    <source elided>
        out = np.empty_like(arr)
    for i in prange(arr.size):
    ^

[1] During: lowering "id=2[LoopNest(index_variable = parfor_index.92, range = (0, $20.3, 1))]{32: <ir.Block at <ipython-input-6-476298123cdd> (6)>}Var(parfor_index.92, <ipython-input-6-476298123cdd> (6))" at <ipython-input-6-476298123cdd> (6)
[...]
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. I suspect that it is the branch `if out is None` that is causing this as it means the type of `out` will end up as an optional array (`?array(int64, 1d, C)`).

**Comment by david-zwicker** [comment]
Yes, removing the `if out is None` part makes everything compile. I forgot to mention that the above codes runs without problems when `parallel=False`. I guess the parallel code is a bit more restricted and can't deal with `?array(int64, 1d, C)`, which might not be a bug, but rather a missing feature.

**Comment by stuartarchibald** [comment]
Yes, perhaps so, there are certainly more limitations on what ParallelAccelerator can handle. I think either way this shouldn't materialize as a lowering error as they are not exactly user friendly!
