### ISSUE TITLE
Numba fails with `numba.errors.LoweringError: Failed in object mode pipeline`

### ISSUE THREAD

**Issue by llimllib** [numba/numba#3584]
This program, a solution for advent of code day 11, part 2, succeeds without numba but fails when I try to jit the maxn function:

```
import math
import numpy as np
from numba import jit


@jit
def maxn(a, n):
    return max(
        (np.sum(a[i : i + n, j : j + n]), i, j)
        for i in range(300 - n)
        for j in range(300 - n)
    )


def f(x, y, serial):
    power = ((x + 10) * y + serial) * (x + 10)
    return math.floor((power % 1000) / 100) - 5


def do(serial):
    m = np.zeros((300, 300))
    z = np.array([f(x, y, serial) for (x, y), _ in np.ndenumerate(m)]).reshape(300, 300)
    (msum, x, y), n = max((maxn(z, n), n) for n in range(1, 300))
    print(f"{x}, {y}, {n}: {msum}")
    return z

do(9424)
```

The traceback looks like:

```
$ python c.py
Traceback (most recent call last):
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/errors.py", line 609, in new_error_context
    yield
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/pylowering.py", line 96, in lower_inst
    value = self.lower_assign(inst)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/pylowering.py", line 194, in lower_assign
    return self.lower_yield(value)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/pylowering.py", line 217, in lower_yield
    yp = self.generator_info.yield_points[inst.index]
AttributeError: 'NoneType' object has no attribute 'yield_points'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c.py", line 31, in <module>
    do(9424)
  File "c.py", line 23, in do
    (msum, x, y), n = max((maxn(z, n), n) for n in range(1, 300))
  File "c.py", line 23, in <genexpr>
    (msum, x, y), n = max((maxn(z, n), n) for n in range(1, 300))
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 691, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 638, in backend_object_mode
    self.flags)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/compiler.py", line 1075, in py_lowering_stage
    lower.lower()
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/lowering.py", line 219, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/lowering.py", line 244, in lower_function_body
    self.lower_block(block)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/errors.py", line 617, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/llimllib/.pyenv/versions/3.7.0/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
'NoneType' object has no attribute 'yield_points'

File "c.py", line 11:
def maxn(a, n):
    <source elided>
        for i in range(300 - n)
        for j in range(300 - n)
        ^

[1] During: lowering "$20.23.93 = yield $20.22" at c.py (11)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
```

I wouldn't have submitted unless the error message asked me to, I hope this is helpful!

**Comment by seibert** [comment]
thanks!  This is an error related to our generator support that should have been caught earlier in the pipeline.

**Comment by stuartarchibald** [comment]
Duplicates:
https://github.com/numba/numba/search?q=has+no+attribute+%27yield_points%27&type=Issues

**Comment by llimllib** [comment]
Looks like #3366 is a very good dupe, I'll close this for that one
