### ISSUE TITLE
config.threading_layer = 'intel-openmp'

### ISSUE THREAD

**Issue by 350dlc** [numba/numba#3637]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/numba/errors.py", line 609, in new_error_context
    yield
  File "/usr/local/lib/python3.5/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python3.5/site-packages/numba/lowering.py", line 408, in lower_inst
    func(self, inst)
  File "/usr/local/lib/python3.5/site-packages/numba/npyufunc/parfor.py", line 280, in _lower_parfor_parallel
    parfor.races)
  File "/usr/local/lib/python3.5/site-packages/numba/npyufunc/parfor.py", line 1082, in call_parallel_gufunc
    _launch_threads()
  File "/usr/local/lib/python3.5/site-packages/numba/npyufunc/parallel.py", line 371, in _launch_threads
    raise ValueError(msg % t)
ValueError: The threading layer requested 'intel-openmp' is unknown to Numba.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.5/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.5/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python3.5/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 717, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 653, in backend_nopython_mode
    self.metadata)
  File "/usr/local/lib/python3.5/site-packages/numba/compiler.py", line 1048, in native_lowering_stage
    lower.lower()
  File "/usr/local/lib/python3.5/site-packages/numba/lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.5/site-packages/numba/lowering.py", line 219, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python3.5/site-packages/numba/lowering.py", line 244, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python3.5/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/site-packages/numba/errors.py", line 617, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/usr/local/lib/python3.5/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
The threading layer requested 'intel-openmp' is unknown to Numba.

File "<stdin>", line 3:
<source missing, REPL/exec in use?>

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.8, range = (0, a_size0.1, 1))]{1: <ir.Block at <stdin> (3)>}Var(parfor_index.8, <stdin> (3))" at <stdin> (3)

**Comment by 350dlc** [comment]
The following code is what I attempted to run. I had already set the threading layers, which produced the above error message. 

############################################################
from numba import config, njit, threading_layer
import numpy as np

# set the threading layer before any parallel target compilation
config.THREADING_LAYER = 'intel-openmp'

@njit(parallel=True)
def foo(a, b):
    return a + b

x = np.arange(10.)
y = x.copy()

# this will force the compilation of the function, select a threading layer
# and then execute in parallel
foo(x, y)
############################################################

I even used the command "numba -s" to ensure I had successfully installed tbb and intel-openmp

**Comment by stuartarchibald** [comment]
To indicate you want to use the Open-MP backed threading layer the string literal `"omp"` should be used, whereas the code above has it set as `"intel-openmp"`. Try altering the line:
```python
config.THREADING_LAYER = 'intel-openmp'
```
to read like:
```python
config.THREADING_LAYER = 'omp'
```

**Comment by 350dlc** [comment]
When I make the above corrections it says "Intel OpenMP is required" and to try "conda/pip install-openmp", which I've already installed. I reinstalled it and the above python script results in an error.

**Comment by stuartarchibald** [comment]
Closing due to lack of information. If more information becomes available please reopen this issue and provide the new information as a comment. Many thanks.
