### ISSUE TITLE
Broken module found for simple custom class

### ISSUE THREAD

**Issue by oentaryorj** [numba/numba#364]
I have this simple Python class:

import numpy as np
from numba import autojit

@autojit
class Model(object):
    def **init**(self, ncols, nfactors, sigma):
        self.nfactors = nfactors
        self.w0 = 0.0
        self.W = np.zeros(ncols, order='C')
        self.V = np.random.randn(nfactors, ncols) \* sigma
        print self.V

```
def output(self, inst):
    pred = self.w0
    for f in inst:
        key, val = f[0], f[1]
        pred += self.W[key] * val
    sums = np.zeros(self.nfactors, order='C')
    for k in xrange(self.nfactors):
        sum_p = 0.0
        sum_sq = 0.0
        for f in inst:
            key, val = f[0], f[1]
            p = self.V[k,key] * val
            sum_p += p
            sum_sq += p * p
        pred += 0.5 * (sum_p * sum_p - sum_sq)
        sums[k] = sum_p     # cache the sum values 
    return pred     
```

m = Model(2, 3, 0.01)
sums = np.zeros(3, order='C')
m.output([(0, 1.0), (1, 3.0)])

However, when I execute the code, I got this error:

Traceback (most recent call last):
  File "model.py", line 41, in <module>
    m.output([(0, 1.0), (1, 3.0)])
  File "numbawrapper.pyx", line 287, in numba.numbawrapper.BoundSpecializingWrapper.**call** (numba/numbawrapper.c:5039)
  File "numbawrapper.pyx", line 189, in numba.numbawrapper._NumbaSpecializingWrapper.__call__ (numba/numbawrapper.c:3724)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/wrapping/compiler.py", line 69, in compile_from_args
    return self.compile(signature)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/wrapping/compiler.py", line 121, in compile
    self.env, self.extclass, self.method, signature)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/exttypes/autojitclass.py", line 174, in autojit_method_compiler
    argtypes=signature.args)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 144, in compile2
    post_ast = pipeline(func_ast, env)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 191, in **call**
    ast = self.transform(ast, env)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 656, in transform
    ast = stage(ast, env)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 641, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 194, in __call__
    ast = self.transform(ast, env)
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 553, in transform
    func_env.translator.translate()
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/numba/codegen/translate.py", line 364, in translate
    self.llvm_module.verify()  # only Module level verification checks everything.
  File "/home/roentaryo/anaconda/lib/python2.7/site-packages/llvm/core.py", line 590, in verify
    raise llvm.LLVMException(errio.getvalue())
llvm.LLVMException: Instruction does not dominate all uses!
  %277 = load { i64, i8\* }*\* %objtemp48, !tbaa !2
  %sum_p_3 = phi { i64, i8\* }\* [ %277, %"no_error_30:17" ], [ %233, %"no_error_34:2640" ]
Instruction does not dominate all uses!
  %282 = load { i64, i8\* }*\* %objtemp50, !tbaa !2
  %sum_sq_3 = phi { i64, i8\* }\* [ %282, %"no_error_30:17" ], [ %244, %"no_error_34:2640" ]
Broken module found, compilation terminated.
Broken module found, compilation terminated.

By right, this should be compiled correctly. Can you tell what's wrong?

**Comment by sklam** [comment]
This issue refers to depredcated ``@autojit`.  For jitting classes, see http://numba.pydata.org/numba-doc/latest/user/jitclass.html?highlight=jitclass.

Closing
