### ISSUE TITLE
LLVM IR parsing error in a large function

### ISSUE THREAD

**Issue by yukoba** [numba/numba#3666]
This bug only exists in Numba 0.42.0.
Numba 0.41.0 does not have this bug.

I created the environment by ```conda create -n numba-env python numba```.
- Numba 0.42.0
- Python 3.7.2
- llvmlite 0.27.0

This code creates the following error message.
v2, v3, and v4 are not used but if I comment out one of them, there is no error.
I feel the bug exists in a large function.
This is the smallest code I can reproduce the error.

```Python
import numpy as np
from numba import jit

@jit
def map_array(f, ary):
    # return np.array([f(x) for x in ary])
    return np.array(tuple([f(x) for x in ary]))

@jit
def sort_by(f, ary):
    return ary[np.argsort(map_array(f, ary))]

@jit
def get_ev(v):
    return v[4]

@jit
def eval_pop(v):
    return np.sum(v * v)

@jit
def main():
    init_pop = np.random.standard_normal((10, 2)).astype(np.float32)
    init_strategy = np.full((10, 2), 0.1, dtype=np.float32)
    v1 = np.concatenate((init_pop, init_strategy, np.expand_dims(map_array(eval_pop, init_pop), 1)), axis=1)
    v2 = np.random.randint(10, size=(2, 3), dtype=np.int32)
    v3 = np.reshape(np.take(v1, range(4), axis=1), (10, 2, 2))
    v4 = np.random.randint(2, size=(3, 1, 2), dtype=np.int32).astype(np.float32)
    return sort_by(get_ev, v1)[:10][0, 4]

print(main())
```

Error message.

```
Traceback (most recent call last):
  File "C:/Users/yukoba/.IntelliJIdea2018.3/config/scratches/scratch_1.py", line 31, in <module>
    print(main())
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 367, in _compile_for_args
    raise e
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 255, in run
    raise patched_exception
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 246, in run
    stage()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 691, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 638, in backend_object_mode
    self.flags)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 1075, in py_lowering_stage
    lower.lower()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\lowering.py", line 203, in lower
    self.library.add_ir_module(self.module)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\targets\codegen.py", line 184, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\llvmlite\binding\module.py", line 26, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:2917:33: error: use of undefined value '%B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif'
  %".2523" = phi i8* [%".2461", %"B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif"], [%".2521", %"B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.if.endif.endif.endif"]
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This clearly shouldn't be happening. A slightly smaller reproducer is:
```python
import numpy as np
from numba import jit

def sort_by(ary):
    return ary

def main():
    init_pop = np.random.standard_normal((10, 2)).astype(np.float32)
    a = np.zeros((10, 2), dtype=np.float32)
    z = np.expand_dims(np.zeros((10,)), 1)
    v1 = np.concatenate((init_pop, a, z), axis=1)
    v3 = np.reshape(np.take(v1, range(4), axis=1), (10, 2, 2))
    v2 = np.random.randint(10, size=(2, 3), dtype=np.int32)
    v4 = np.random.randint(2, size=(3, 1, 2), dtype=np.int32).astype(np.float32)
    return sort_by(v1)[:10][0, 4]

print(main())
print(jit(forceobj=True)(main)())
```

**Comment by londumas** [comment]
I had the same issue in my project https://github.com/igmhub/picca, and it was fixed by requiring `llvmlite==0.26.0`. So it does seem this issue is linked to llvmlite more than to numba.

**Comment by yukoba** [comment]
Yes! You're right. This problem does not happen if I use ```conda create -n numba-env python numba llvmlite==0.26.0```.

**Comment by stuartarchibald** [comment]
If the use of `llvmlite==0.26` is forced it will cause Numba 0.41 to be installed. Numba 0.42 needs `llvmlite==0.27`. The change from llvmlite 0.26->0.27 involved changing the LLVM backend version from 6->7, it's quite possibly related to that.

**Comment by yukoba** [comment]
> Numba 0.41 to be installed

Yes. ```conda create -n numba-env python numba==0.42.0 llvmlite==0.26.0``` is impossible.

**Comment by stuartarchibald** [comment]
The IR from LLVM 6 and LLVM 7 isn't hugely dissimilar (generating from Numba 0.41 and 0.42 respectively). `opt -verify` from LLVM 7 fails in the same way on both the LLVM 6 and LLVM 7 generated IR.

* Numba 0.41/LLVM 6 IR is [here](https://gist.githubusercontent.com/stuartarchibald/cd67c583623b5a1630ff171b026c496e/raw/d971b119e9c11a37ef6ef386c137b400c7081ced/llvm41.ll)
* Numba 0.42/LLVM 7 IR is [here](https://gist.githubusercontent.com/stuartarchibald/b7ae7f950dbb732c6fede251509c8b58/raw/a04b9decb49447078ffb18c8931b7713f4f2e28a/llvm42.ll)

LLVM 6 `opt` cannot parse the LLVM 7 IR, but LLVM 7 `opt` can parse both and fails in the same way on both.

**Comment by stuartarchibald** [comment]
This is also broken on llvm 7.0.1.

**Comment by seibert** [comment]
We have resolved this with numba/llvmlite#454, which will have its next scheduled release at the end of February.  In the meantime, you can install a development version of llvmlite via conda:
```
conda install -c numba/label/dev llvmlite
```
Let us know if this resolves the issue.  Thanks!

**Comment by yukoba** [comment]
I used ```conda create -c numba/label/dev -n numba-env python numba llvmlite```, but nothing is changed. Why?? Should I wait one more day?

```
llvmlite:        0.27.0dev0-py37h6538335_28       numba/label/dev
numba:           0.43.0dev0-np115py37h6538335_192 numba/label/dev
```

```
Traceback (most recent call last):
  File "1.py", line 31, in <module>
    print(main())
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 369, in _compile_for_args
    raise e
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 922, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 371, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 853, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 840, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 252, in run
    raise patched_exception
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 243, in run
    stage()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 687, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 663, in _backend
    lowered = lowerfn()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 635, in backend_object_mode
    self.flags)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\compiler.py", line 1068, in py_lowering_stage
    lower.lower()
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\lowering.py", line 202, in lower
    self.library.add_ir_module(self.module)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\numba\targets\codegen.py", line 185, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "C:\Users\yukoba\Anaconda3\envs\numba-env\lib\site-packages\llvmlite\binding\module.py", line 26, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:2917:33: error: use of undefined value '%B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif'
  %".2523" = phi i8* [%".2461", %"B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif"], [%".2521", %"B0.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.if.endif.endif.endif"]
```

**Comment by seibert** [comment]
Ah, I think I made a mistake in my directions.  Try same command, but `conda update`.  The fixed llvmlite package should have _39 at the end of the package version.

**Comment by yukoba** [comment]
I found the solution.
I should use ```conda install -c numba/label/dev -n numba-env numba==0.42.0 llvmlite==0.28.0dev0```.
I should not use numba 0.43.0dev0.

```
llvmlite                  0.28.0dev0      py37h6538335_39    numba/label/dev
numba                     0.42.0           py37hf9181ef_0
```

And I can run the program by llvmlite 0.28.0dev0!
Thank you very much.
