### ISSUE TITLE
getitem on 0d arrays broken/unsupported

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#3667]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This:
```python
from numba import njit
import numpy as np

@njit
def foo(x):
    return x[0]

def run(a):
    print(a.ndim)
    print(a.shape)
    print(a.size)
    foo(a)
    print('ok for ', a)

run(np.array([10]))
run(np.array(10))
```
does this:
```
$ python 0dgetter.py 
1
(1,)
1
ok for  [10]
0
()
1
Traceback (most recent call last):
  File "0dgetter.py", line 16, in <module>
    run(np.array(10))
  File "0dgetter.py", line 12, in run
    foo(a)
  File "<path>/numba/numba/dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "<path>/numba/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(int64, 0d, C), Literal[int](0))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    TypeError: cannot index array(int64, 0d, C) with 1 indices: [Literal[int](0)]
    raised from <path>/numba/numba/typing/arraydecl.py:87
In definition 7:
    TypeError: cannot index array(int64, 0d, C) with 1 indices: [int64]
    raised from <path>/numba/numba/typing/arraydecl.py:87
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at 0dgetter.py (6)
[2] During: typing of static-get-item at 0dgetter.py (6)

File "0dgetter.py", line 6:
def foo(x):
    return x[0]
```
seems like `getitem` on a `0d` array is broken.

**Comment by danielwe** [comment]
I don't think you should be able to use an index like `(0,)` on a 0d array. The ones I know to work are `...` and `()`. In plain numpy:
```python
>>> import numpy as np
>>> a = np.array(10)
>>> a[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: too many indices for array
>>> a[...]
array(10)
>>> a[()]
10
```
Your reproducer works as expected with `()`, but I get a lowering error with `...`.

**Comment by stuartarchibald** [comment]
@danielwe thanks for bringing this to my attention, indeed this is the behaviour (context: I was running into trouble through the need to convert what _may_ be a 0d array to a scalar depending on compilation path).

It's interesting to note:
```
In [1]: import numpy as np                                                                                                      

In [2]: a = np.array(10)                                                                                                        

In [3]: a.take(0)                                                                                                               
Out[3]: 10
```
