### ISSUE TITLE
array manipulation

### ISSUE THREAD

**Issue by saidctb** [numba/numba#3680]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

i have this minimal example that does not work for some reason 
```
from numba import jit
import numpy as np
from itertools import product

arr = np.zeros((1,1,1,1))
M   = np.zeros((1,1,1,1))

@jit
def assembly(arr, M):

    mat = np.zeros((1,1,1,1))

    for i,j in product(range(0, 1), range(0, 1)):

        M[:, :, : , : ] = mat[ : , : , : , : ]

        a = arr[0, : , : , : ]
        b = arr[0, : , : , : ]
        c = arr[0, : , : , : ]
        

assembly(arr, M)
```

it gets me this error:

Traceback (most recent call last):
  File "test.py", line 25, in <module>
    assembly(arr, M)
  File "/usr/local/lib/python3.5/dist-packages/numba/dispatcher.py", line 369, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.5/dist-packages/numba/dispatcher.py", line 326, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numba/dispatcher.py", line 774, in compile
    lifted_from=self.lifted_from)
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 937, in compile_ir
    lifted_from=lifted_from)
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 379, in compile_ir
    return self._compile_ir()
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 860, in _compile_ir
    return self._compile_core()
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 840, in _compile_core
    res = pm.run(self.status)
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 252, in run
    raise patched_exception
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 243, in run
    stage()
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 687, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 663, in _backend
    lowered = lowerfn()
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 635, in backend_object_mode
    self.flags)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 331, in giveup_context
    yield
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 635, in backend_object_mode
    self.flags)
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 1073, in py_lowering_stage
    del lower
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.5/dist-packages/numba/targets/base.py", line 1103, in push_code_library
    yield
  File "/usr/local/lib/python3.5/dist-packages/numba/compiler.py", line 1068, in py_lowering_stage
    lower.lower()
  File "/usr/local/lib/python3.5/dist-packages/numba/lowering.py", line 202, in lower
    self.library.add_ir_module(self.module)
  File "/usr/local/lib/python3.5/dist-packages/numba/targets/codegen.py", line 185, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "/usr/local/lib/python3.5/dist-packages/llvmlite/binding/module.py", line 26, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:6825:33: error: use of undefined value '%B52.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif'
  %".6171" = phi i8* [%".6069", %"B52.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif"], [%".6169", %"B52.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.endif.if.endif.endif.endif"]
                                ^

**Comment by stuartarchibald** [comment]
Thanks for the report. This is due to a bug in LLVM 7, cause is incorrect parsing of very long labels. https://github.com/numba/numba/issues/3669 and https://github.com/numba/numba/issues/3666 are also due to the same problem. A fix will be coming soon.

**Comment by seibert** [comment]
We have resolved this with numba/llvmlite#454, which will have its next scheduled release at the end of February.  In the meantime, you can install a development version of llvmlite via conda:
```
conda install -c numba/label/dev llvmlite
```
Let us know if this resolves the issue.  Thanks!

**Comment by seibert** [comment]
OK, to ensure you get the correct combination of versions, another user has suggested the following command to test:
```
conda install -c numba/label/dev -n numba-env numba==0.42.0 llvmlite==0.28.0dev0
```

**Comment by saidctb** [comment]
yes the problem has been fixed , thanks a lot
