### ISSUE TITLE
Cannot convert Python enum type to unsigned integer

### ISSUE THREAD

**Issue by yt87** [numba/numba#3714]
Here is a minimal example:

```
from enum import IntFlag
import numba as nb
class Precip(IntFlag):
    RA = 1
    DZ = 2
    SN = 4
    
@nb.njit
def example():
    ptype = np.zeros((2,), dtype=np.uint64)
    ptype[0] = np.uint64(Precip.RA)
    return ptype
nb.__version__
example()
```
The exception message is not clear. First it states `NotImplementedError`, at the end it says "This should not have happened, a problem has occurred in Numba's internals."

```
'0.42.0'

---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/targets/base.py in cast(self, builder, val, fromty, toty)
    688         try:
--> 689             impl = self._casts.find((fromty, toty))
    690             return impl(self, builder, fromty, toty, val)

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/targets/base.py in find(self, sig)
     49         if out is None:
---> 50             out = self._find(sig)
     51             self._cache[sig] = out

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/targets/base.py in _find(self, sig)
     58         else:
---> 59             raise NotImplementedError(self, sig)
     60 

NotImplementedError: (<numba.targets.base.OverloadSelector object at 0x7fcc687a92b0>, (Enum<int64>(Precip), uint64))

During handling of the above exception, another exception occurred:

NotImplementedError                       Traceback (most recent call last)
~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    616     try:
--> 617         yield
    618     except NumbaError as e:

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_inst(self, inst)
    307             ty = self.typeof(inst.target.name)
--> 308             val = self.lower_assign(ty, inst)
    309             self.storevar(val, inst.target.name)

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_assign(self, ty, inst)
    453         elif isinstance(value, ir.Expr):
--> 454             return self.lower_expr(ty, value)
    455 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_expr(self, resty, expr)
    882         elif expr.op == 'call':
--> 883             res = self.lower_call(resty, expr)
    884             return res

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_call(self, resty, expr)
    848 
--> 849             res = impl(self.builder, argvals, self.loc)
    850 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/targets/base.py in __call__(self, builder, args, loc)
   1123     def __call__(self, builder, args, loc=None):
-> 1124         return self._imp(self._context, builder, self._sig, args, loc=loc)
   1125 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/targets/base.py in wrapper(*args, **kwargs)
   1146             kwargs.pop('loc')     # drop unused loc
-> 1147             return fn(*args, **kwargs)
   1148 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/targets/builtins.py in number_constructor(context, builder, sig, args)
    275         [valty] = sig.args
--> 276         return context.cast(builder, val, valty, sig.return_type)
    277 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/targets/base.py in cast(self, builder, val, fromty, toty)
    692             raise NotImplementedError(
--> 693                 "Cannot cast %s to %s: %s" % (fromty, toty, val))
    694 

NotImplementedError: Cannot cast Enum<int64>(Precip) to uint64: %".104" = load i64, i64* %"$0.11"

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-24-eb2c67621d0b> in <module>
     12     return ptype
     13 nb.__version__
---> 14 example()

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    365                     e.patch_message(''.join(e.args) + help_msg)
    366             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 367             raise e
    368 
    369     def inspect_llvm(self, signature=None):

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    322                 argtypes.append(self.typeof_pyval(a))
    323         try:
--> 324             return self.compile(tuple(argtypes))
    325         except errors.TypingError as e:
    326             # Intercept typing error that may be due to an argument

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, sig)
    653 
    654             self._cache_misses[sig] += 1
--> 655             cres = self._compiler.compile(args, return_type)
    656             self.add_overload(cres)
    657             self._cache.save_overload(sig, cres)

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     80                                       args=args, return_type=return_type,
     81                                       flags=flags, locals=self.locals,
---> 82                                       pipeline_class=self.pipeline_class)
     83         # Check typing error if object mode is used
     84         if cres.typing_error is not None and not flags.enable_pyobject:

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    924     pipeline = pipeline_class(typingctx, targetctx, library,
    925                               args, return_type, flags, locals)
--> 926     return pipeline.compile_extra(func)
    927 
    928 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in compile_extra(self, func)
    372         self.lifted = ()
    373         self.lifted_from = None
--> 374         return self._compile_bytecode()
    375 
    376     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in _compile_bytecode(self)
    855         """
    856         assert self.func_ir is None
--> 857         return self._compile_core()
    858 
    859     def _compile_ir(self):

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    842         self.define_pipelines(pm)
    843         pm.finalize()
--> 844         res = pm.run(self.status)
    845         if res is not None:
    846             # Early pipeline completion

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    253                     # No more fallback pipelines?
    254                     if is_final_pipeline:
--> 255                         raise patched_exception
    256                     # Go to next fallback pipeline
    257                     else:

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    244                 try:
    245                     event(stage_name)
--> 246                     stage()
    247                 except _EarlyPipelineCompletion as e:
    248                     return e.result

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in stage_nopython_backend(self)
    715         """
    716         lowerfn = self.backend_nopython_mode
--> 717         self._backend(lowerfn, objectmode=False)
    718 
    719     def stage_compile_interp_mode(self):

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    664             self.library.enable_object_caching()
    665 
--> 666         lowered = lowerfn()
    667         signature = typing.signature(self.return_type, *self.args)
    668         self.cr = compile_result(

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in backend_nopython_mode(self)
    651                 self.calltypes,
    652                 self.flags,
--> 653                 self.metadata)
    654 
    655     def _backend(self, lowerfn, objectmode):

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags, metadata)
   1046         lower = lowering.Lower(targetctx, library, fndesc, interp,
   1047                                metadata=metadata)
-> 1048         lower.lower()
   1049         if not flags.no_cpython_wrapper:
   1050             lower.create_cpython_wrapper(flags.release_gil)

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower(self)
    176         if self.generator_info is None:
    177             self.genlower = None
--> 178             self.lower_normal_function(self.fndesc)
    179         else:
    180             self.genlower = self.GeneratorLower(self)

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    217         # Init argument values
    218         self.extract_function_arguments()
--> 219         entry_block_tail = self.lower_function_body()
    220 
    221         # Close tail of entry block

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_function_body(self)
    242             bb = self.blkmap[offset]
    243             self.builder.position_at_end(bb)
--> 244             self.lower_block(block)
    245 
    246         self.post_lower()

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    257             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    258                                    loc=self.loc, errcls_=defaulterrcls):
--> 259                 self.lower_inst(inst)
    260 
    261     def create_cpython_wrapper(self, release_gil=False):

~/miniconda3/envs/devel1/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    623         from numba import config
    624         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 625         six.reraise(type(newerr), newerr, tb)
    626 
    627 

~/miniconda3/envs/devel1/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast Enum<int64>(Precip) to uint64: %".104" = load i64, i64* %"$0.11"

File "<ipython-input-24-eb2c67621d0b>", line 11:
def example():
    <source elided>
    ptype = np.zeros((2,), dtype=np.uint64)
    ptype[0] = np.uint64(Precip.RA)
    ^

[1] During: lowering "$0.12 = call $0.9($0.11, func=$0.9, args=[Var($0.11, <ipython-input-24-eb2c67621d0b> (11))], kws=(), vararg=None)" at <ipython-input-24-eb2c67621d0b> (11)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment]
Thanks for the report. IIRC `IntFlag` is not fully supported at present, there is a feature request for it here: https://github.com/numba/numba/issues/2773. 

Thanks also for the feedback on error messages. The error message is verbose because Numba detected that it was attempting to do something it didn't understand and so captured the first error message and back trace so as to be useful for developers, and wrapped it in the second asking for it to be reported. The error handling system is scheduled for additional work in the near future and this is something we are hoping to improve. At present Numba tries to catch problems as soon as possible and most error messages are considerably shorter (it's the unknown situation ones which are long, like the one you hit), for example:

```python
from numba import njit
import numpy as np

@njit
def foo(a):
    # np.asanyarray not implemented yet...
    return np.asanyarray(a)

foo((1,2,3,))
```
produces:
```
$ python issue3714b.py
Traceback (most recent call last):
  File "issue3714b.py", line 9, in <module>
    foo((1,2,3,))
  File "<path>/numba/numba/dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "<path>/numba/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "<path>/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Use of unsupported NumPy function 'numpy.asanyarray' or unsupported use of the function.

File "issue3714b.py", line 7:
def foo(a):
    <source elided>
    # np.asanyarray not implemented yet...
    return np.asanyarray(a)
    ^

[1] During: typing of get attribute at issue3714b.py (7)

File "issue3714b.py", line 7:
def foo(a):
    <source elided>
    # np.asanyarray not implemented yet...
    return np.asanyarray(a)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reprodu
```

**Comment by stuartarchibald** [comment]
NOTE: Changed title to reflect issue.
