### ISSUE TITLE
Numba wheel doesn't install six

### ISSUE THREAD

**Issue by pitrou** [numba/numba#3737]
`six` seems to be a dependency, but it does not seem to get install by `pip install numba` inside an empty environment.

**Comment by seibert** [comment]
Our approach has been to vendor the parts of `six` we need into `numba.six`, but there have been places in the past where someone accidentally used the global `six`.  Did you find something?

**Comment by pitrou** [comment]
Ah, I see. I got:
```python
>>> increment[64, 64](da)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/compiler.py", line 765, in __call__
    kernel = self.specialize(*args)
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/compiler.py", line 776, in specialize
    kernel = self.compile(argtypes)
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/compiler.py", line 792, in compile
    **self.targetoptions)
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/compiler.py", line 62, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/compiler.py", line 925, in compile_extra
    args, return_type, flags, locals)
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/compiler.py", line 276, in __init__
    targetctx.refresh()
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/targets/base.py", line 271, in refresh
    self.load_additional_registries()
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/target.py", line 72, in load_additional_registries
    from . import cudaimpl, printimpl, libdevice
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/cudaimpl.py", line 5, in <module>
    import six
ModuleNotFoundError: No module named 'six'
```

**Comment by seibert** [comment]
ah, yes, it looks like you tripped over this bug which we fixed:

https://github.com/numba/numba/commit/64f6859b0a5f172acf8244fc0923664e591e6315#diff-a3ad32c82e29f57220d54a522266e48c

The next release is planned for the end of February.

**Comment by pitrou** [comment]
Thanks for the quick response :-) Feel free to close.
