### ISSUE TITLE
Exceptions at shutdown

### ISSUE THREAD

**Issue by pitrou** [numba/numba#3739]
I got the following exceptions when shutting down an IPython session in which I had run a CUDA kernel:
```python
>>>                                                                                                                                                     
Exception ignored in: <function CompilationUnit.__del__ at 0x7ff32b2950d0>
Traceback (most recent call last):
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 153, in __del__
    err = driver.nvvmDestroyProgram(byref(self._handle))
AttributeError: 'CompilationUnit' object has no attribute '_handle'
Exception ignored in: <function CompilationUnit.__del__ at 0x7ff32b2950d0>
Traceback (most recent call last):
  File "/home/antoine/t/tt/lib/python3.7/site-packages/numba/cuda/cudadrv/nvvm.py", line 153, in __del__
    err = driver.nvvmDestroyProgram(byref(self._handle))
AttributeError: 'CompilationUnit' object has no attribute '_handle'
```

**Comment by seibert** [comment]
To help us reproduce things, can you attach the output of `numba -s`?

**Comment by pitrou** [comment]
Here it is:
https://gist.github.com/pitrou/cbaeeba7dc77d64339ab3980ad0fac3d

By the way, the conda information in that paste is irrelevant. This was from a pip-installed Numba in a virtualenv.

Also, in that IPython session I first had a failed kernel compilation before I set the proper environment variables to point to the CUDA install.

**Comment by pitrou** [comment]
IOW, it may simply be a case of a constructor raising an exception before it got a change to set the `_handle` attribute.

**Comment by seibert** [comment]
looks like we also need to fix the CUDA library reporting when using environment variables.  Which CUDA version is this?

**Comment by pitrou** [comment]
Apparently it's `9.1.85-3ubuntu1`.
```
$ LANG=C apt show nvidia-cuda-toolkit
Package: nvidia-cuda-toolkit
Version: 9.1.85-3ubuntu1
Priority: extra
Section: multiverse/devel
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian NVIDIA Maintainers <pkg-nvidia-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 61,0 MB
Depends: nvidia-profiler (= 9.1.85-3ubuntu1), nvidia-cuda-dev (= 9.1.85-3ubuntu1), nvidia-opencl-dev (= 9.1.85-3ubuntu1) | opencl-dev, gcc-6 | clang-4.0 | clang-3.9 | clang-3.8 | clang (<< 1:5~) | gcc-5 | gcc-4.9 | gcc-4.8, g++-6 | clang-4.0 | clang-3.9 | clang-3.8 | clang (<< 1:5~) | g++-5 | g++-4.9 | g++-4.8, libc6 (>= 2.4), libgcc1 (>= 1:3.0), libnvvm3 (>= 7.0), libstdc++6 (>= 4.1.1)
Recommends: nvidia-cuda-doc (= 9.1.85-3ubuntu1), nvidia-cuda-gdb (= 9.1.85-3ubuntu1), nvidia-visual-profiler (= 9.1.85-3ubuntu1)
Suggests: libcupti-dev, nvidia-driver (>= 387.26)
Conflicts: cuda-license-7-5, cuda-repo-ubuntu1204, cuda-repo-ubuntu1404, cuda-repo-ubuntu1404-7-5-local, cuda-repo-ubuntu1410, cuda-repo-ubuntu1504, cuda-repo-ubuntu1504-7-5-local
Homepage: https://developer.nvidia.com/cuda-zone
Download-Size: 30,4 MB
APT-Manual-Installed: yes
APT-Sources: http://fr.archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages
Description: NVIDIA CUDA development toolkit
 The Compute Unified Device Architecture (CUDA) enables NVIDIA
 graphics processing units (GPUs) to be used for massively parallel
 general purpose computation.
 .
 This package contains the nvcc compiler and other tools needed for building
 CUDA applications.
 .
 Running CUDA applications requires a supported NVIDIA GPU and the NVIDIA
 driver kernel module.

```
