### ISSUE TITLE
`LinkError` using `np.arctan2`  in AOT compilation on Windows

### ISSUE THREAD

**Issue by AndrewYY** [numba/numba#3759]
OS: Windows 10
Numba version: 0.42.0
Reproducer:
```
import numpy as np
import numba as nb
import numba.pycc as pycc

cc = pycc.CC('test')

@cc.export('atan2', 'f8(f8, f8)')
def atan2(y, x):
    return np.arctan2(y, x)

cc.verbose = True
cc.compile()
```
Error: 
```
test.cp36-win_amd64.o : error LNK2001: unresolved external symbol atan2_fixed
C:\[snip]\test.cp36-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
```

**Comment by AndrewYY** [comment]
Possibly related to #796

**Comment by AndrewYY** [comment]
As far as I'm aware, removing references to atan2-fixed resolves this issue, without introducing new test failures: https://github.com/AndrewYY/numba/commit/70e0e56986b4f2a18721fc15617892384573ff2e

**Comment by JaschaParis** [comment]
Same here:
os: win 10
python: 3.7.3
numba: 0.45.1
numpy 1.17.1

But in addition to the atan2 issue, there is also an issue with np.sqrt appliying it to vectors.

This one leads to the error "error LNK2001: unresolved symbol "atan2_fixed"
`@kinematiccc.export('vecnorm', 'f8[:](f8[:,:],i8)')
def vecnorm(v, axis):
    return np.sqrt(np.sum(v ** 2, axis))`

This one works fine: (please see that v is only a vector f8[:])
`@kinematiccc.export('vecnorm', 'f8[:](f8[:],i8)')
def vecnorm(v, axis):
    return np.sqrt(np.sum(v ** 2, axis))`

**Comment by stuartarchibald** [comment]
@JaschaParis thanks for the report. I think what you are seeing is a different problem given the unresolved symbol. Do you have a small working reproducer for this please? The missing symbol is from SVML which should be available by default on Windows+Anaconda Python.

**Comment by JaschaParis** [comment]
Sure. Though, because of your comment, I realize that my translation of the error message might have been to short. The reproducer is shown below. Also I added an example which works without any problem.
I am using standard python installation and a pipenv. No Anaconda. Just updated to numpy 1.17.2 with no difference.

Complete (paths shortened) error message:
```
Traceback (most recent call last):
  File "[...]\Local\Programs\Python\Python37\Lib\distutils\_msvccompiler.py", line 520, in link
   Bibliothek "[...]\kinematic_bug.cp37-win_amd64.lib" und Objekt "[...]\kinematic_bug.cp37-win_amd64.exp" werden erstellt.
kinematic_bug.cp37-win_amd64.o : error LNK2001: Nicht aufgelöstes externes Symbol "__svml_sqrt2_ha".
(Translation: not resolved external symbol)
[...]\kinematic_bug.cp37-win_amd64.pyd : fatal error LNK1120: 1 nicht aufgelöste Externe (Translation: not resolved external)
    self.spawn([self.linker] + ld_args)
  File "[...]AppData\Local\Programs\Python\Python37\Lib\distutils\_msvccompiler.py", line 543, in spawn
    return super().spawn(cmd)
  File "[...]\lib\site-packages\numpy\distutils\ccompiler.py", line 92, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "[...]\lib\site-packages\numpy\distutils\ccompiler.py", line 172, in CCompiler_spawn
    (cmd, s, msg))
distutils.errors.DistutilsExecError: Command "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.22.27905\bin\HostX86\x64\link.exe [... many paths ...] failed with exit status 1120
```

Reproducer:
```

from numba.pycc import CC
import numpy as np
from numba import jit

kinematic_bug = CC('kinematic_bug')
kinematic_bug.verbose = True

@kinematic_bug.export('vecnorm', 'f8[:](f8[:,:],i8)')
@jit(nopython=True, cache=True)
def vecnorm(v, axis):
    return np.sqrt(np.sum(v ** 2, axis))


@kinematic_bug.export('vecnorm_xy', 'f8[:](f8[:,:],i8)')
@jit(nopython=True, cache=True)
def vecnorm_xy(v, axis):
    return np.sqrt(np.sum(v[0:2, :] ** 2, axis))


if __name__ == "__main__":
    kinematic_bug.compile()
```

This is example works perfectly fine:

```
from numba.pycc import CC
import numpy as np
from numba import jit

kinematic_wroks = CC('kinematic_wroks ')
kinematic_wroks.verbose = True

@kinematic_wroks.export('interp_array', 'f8[:,:](f8[:],f8[:],f8[:,:])')
@jit('f8[:,:](f8[:],f8[:],f8[:,:])', nopython=True, cache=True)
def interp_array(xq, x, y):
    yp = np.zeros((np.shape(y)[0], np.shape(xq)[0]))
    for idx in np.arange(0, np.shape(y)[0]):
        yp[idx, :] = np.interp(xq, x, y[idx, :])
    return yp


if __name__ == "__main__":
    kinematic_wroks.compile()
```

**Comment by AndrewYY** [comment]
The svml issue seems to be unrelated to this ticket and tracked in #5670 for which the workaround is to disable SVML when compiling AOT via 
```os.environ['NUMBA_DISABLE_INTEL_SVML'] = '1'```
