### ISSUE TITLE
Crash when using AOT compiled code containing namedtuples

### ISSUE THREAD

**Issue by AndrewYY** [numba/numba#3761]
OS: Windows 10
Numba version: 0.42.0
Reproducer:
```
import collections
import numba as nb
import numba.pycc as pycc


T = collections.namedtuple('T', ['a', 'b'])
t_type = nb.types.NamedTuple((nb.i8, nb.f8), T)
cc = pycc.CC('test')

@cc.export('instantiate', t_type())
def instantiate():
    return T(1, 2.0)

cc.verbose = True
cc.compile()
```

Compiles ok. Then on runtime:

```
import test
test.instantiate() // crashes
```

workaround:
```
import test
T = collections.namedtuple('T', ['a', 'b'])
test.instantiate() // does not crash
```

The namespace that `T` needs to be in depends on the namespace it was in during compilation. In this case, that namespace is `__main__`.

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce locally. Back trace:
```
#0  PyObject_Call () at /tmp/build/80754af9/python_1544812943833/work/Objects/call.c:225
#1  0x00007f5d8df1d334 in ._pycc_method_instantiate () from test.cpython-37m-x86_64-linux-gnu.so
#2  0x0000556b5aaf0004 in _PyMethodDef_RawFastCallKeywords ()
    at /tmp/build/80754af9/python_1544812943833/work/Objects/call.c:690
```

**Comment by sklam** [comment]
note: probably has a runtime reference to the namedtuple type

**Comment by AndrewYY** [comment]
another workaround for me is to just remove python visibility to the namedtuple:

```
import collections
import numba as nb
import numba.pycc as pycc


T = collections.namedtuple('T', ['a', 'b'])
t_type = nb.types.Tuple((nb.i8, nb.f8))
cc = pycc.CC('test')

@cc.export('instantiate', t_type())
def instantiate():
    return (1, 2.0)

@cc.export('access', nb.i8(t_type))
def access(t):
    t = T(*t)
    return t.a

cc.verbose = True
cc.compile()
```
