### ISSUE TITLE
Error in accessing string within a numba struct

### ISSUE THREAD

**Issue by synapticarbors** [numba/numba#377]
Suppose I have a numpy recarray with a heterogenous dtype that includes fixed length strings:

``` python
import numpy as np
import numba

N = 10
numpy_dtype = [('a', np.float64), ('b', np.int32), ('c', (np.str_, 5))]
arr = np.recarray(N, dtype=numpy_dtype)

# Fill with data
arr.a = np.random.normal(size=(N,))
arr.b = np.arange(N).astype(np.int32)
arr.c = np.array(['abcde']*N, (np.str_, 5))

### Is there a better type to use below rather than numba.string_ ?
numba_type_map = {'<f8': numba.f8, '<i4': numba.i4, '|S5': numba.string_} 
numba_dtype = [(field, numba_type_map[field_type]) for field, field_type in arr.dtype.descr]
record_type = numba.struct(numba_dtype)

@numba.jit(numba.void(record_type[:]))
def test(x):
    sz = x.shape[0]
    for k in xrange(sz):
        s = x[k].c   #<<<<<<<<<<<<<<<<<<<<<<<
        if s == 'abcde':
            print k, s, numba.typeof(s)

if __name__ == '__main__':
    test(arr)
```

In the above code if `s=x[k].c`, I get an error:

``` python
Traceback (most recent call last):
  File "ntest.py", line 17, in <module>
    @numba.jit(numba.void(record_type[:]))
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 224, in _jit_decorator
    nopython=nopython, func_ast=func_ast, **kwargs)
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 133, in compile_function
    func_env = pipeline.compile2(env, func, restype, argtypes, func_ast=func_ast, **kwds)
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 144, in compile2
    post_ast = pipeline(func_ast, env)
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 191, in __call__
    ast = self.transform(ast, env)
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 656, in transform
    ast = stage(ast, env)
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 641, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 202, in __call__
    reporting.report(env, exc=e)
  File "/Users/lev/anaconda/lib/python2.7/site-packages/numba/reporting.py", line 181, in report
    raise exc
numba.error.NumbaError: (see below)
--------------------- Numba Encountered Errors or Warnings ---------------------
        if s == 'abcde':
-----------^
Error 23:11: Comparisons of types string and string are not yet supported
--------------------------------------------------------------------------------
```

However, if `s=x.c[k]`, I get the expected result:

``` python
0 abcde object
1 abcde object
2 abcde object
3 abcde object
4 abcde object
5 abcde object
6 abcde object
7 abcde object
8 abcde object
9 abcde object
```

although, I do not completely understand why numba is typing the fixed length string as an object. For the code that breaks, `numba.typeof(s)` for `s=x[k].c` returns `string`.

Is there a better way to type fixed length strings in numba than the way I'm currently doing things? @markflorisson88, @teoliphant - Will numba 0.2 possibly address the error?

This code was tested using Anaconda 1.8.0 on OS X with numba 0.11.1.

**Comment by stuartarchibald** [comment]
Closing this as it uses code that simply does not exist any more (latest Numba is 0.43.1).
