### ISSUE TITLE
Set freezes

### ISSUE THREAD

**Issue by klicperajo** [numba/numba#3772]
I'm trying to speed up my calculation of the personalized PageRank vector (PPV) with Numba using sets. `indices` and `indptr` are from a CSR-matrix representing the adjacency matrix of a graph.

The following code works without Numba but freezes with it. I've tried to reduce this as much as possible, but I couldn't get further than this.

```Python
import numpy as np
import numba

indices = np.array([ 7, 19,  9, 11,  9, 18, 14, 18,  0, 16, 19,  1,  5, 16,  2, 14, 21,
                    14,  6, 11, 12, 18, 16,  7, 10, 15, 18,  5,  6, 14, 16,  0,  7, 11],
                   dtype=np.int32)
indptr = np.array([ 0,  2,  3,  4,  4,  4,  6,  8, 11, 11, 13, 14,
                   17, 18, 18, 22, 23, 27, 27, 31, 33, 33, 34],
                  dtype=np.int32)

@numba.jit(nopython=True)
def calc_ppv_test(inode: int, nnodes: int, indptr: np.ndarray, indices: np.ndarray, deg: np.ndarray, alpha: float, epsilon: float):
    r = np.zeros(nnodes, dtype=np.float32)
    r[inode] = 1.
    q = {inode}
    while len(q) > 0:
        unode = q.pop()
        res = r[unode]
        r[unode] = 0
        for vnode in indices[indptr[unode]:indptr[unode + 1]]:
            r[vnode] += (1 - alpha) * res / deg[unode]
            if r[vnode] >= epsilon * deg[vnode]:
                q.add(vnode)

deg = indptr[1:] - indptr[:-1]
nnodes = len(indptr) - 1
for inode in range(nnodes):
    calc_ppv_test(inode, nnodes, indptr, indices, deg, 0.1, 1e-3)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce locally, seems like this is a bug.

**Comment by stuartarchibald** [comment]
Had a bit of time to look at this... augmenting the code with a bounds checker:

```python
import numpy as np
import numba
from numba import gdb_init
from numba.types import *

indices = np.array([ 7, 19,  9, 11,  9, 18, 14, 18,  0, 16, 19,  1,  5, 16,  2, 14, 21,
                    14,  6, 11, 12, 18, 16,  7, 10, 15, 18,  5,  6, 14, 16,  0,  7, 11],
                   dtype=np.int32)
indptr = np.array([ 0,  2,  3,  4,  4,  4,  6,  8, 11, 11, 13, 14,
                   17, 18, 18, 22, 23, 27, 27, 31, 33, 33, 34],
                  dtype=np.int32)

@numba.jit(nopython=True)
def assert_inbounds(arr, idx):
    if idx >= len(arr):
        print("Got value", arr[idx])
        raise AssertionError("Out of bounds access")

@numba.jit(nopython=True)
def calc_ppv_test(inode: int, nnodes: int, indptr: np.ndarray, indices: np.ndarray,
                  deg: np.ndarray, alpha: float, epsilon: float):
    r = np.zeros(nnodes, dtype=np.float32)
    assert_inbounds(r, inode)
    r[inode] = 1.
    q = {inode}
    while len(q) > 0:
        unode = q.pop()
        assert_inbounds(r, unode)
        res = r[unode]
        r[unode] = 0
        assert_inbounds(indptr, unode)
        assert_inbounds(indptr, unode + 1)
        assert_inbounds(indices, indptr[unode])
        assert_inbounds(indices, indptr[unode + 1])
        for vnode in indices[indptr[unode]:indptr[unode + 1]]:
            assert_inbounds(r, vnode)
            assert_inbounds(deg, unode)
            r[vnode] += (1 - alpha) * res / deg[unode]
            if r[vnode] >= epsilon * deg[vnode]:
                q.add(vnode)

deg = indptr[1:] - indptr[:-1]
nnodes = len(indptr) - 1
for inode in range(nnodes):
    calc_ppv_test(inode, nnodes, indptr, indices, deg, 0.1, 1e-3)
```
gives:
```
Got value 65
Traceback (most recent call last):
  File "issue3772.py", line 44, in <module>
    calc_ppv_test(inode, nnodes, indptr, indices, deg, 0.1, 1e-3)
  File "issue3772.py", line 16, in assert_inbounds
    raise AssertionError("Out of bounds access")
AssertionError: Out of bounds access
```
the error is from `indptr[unode + 1]` accessing out of bounds, so I think it is probably hanging because of invalid memory access leading to nonsense values in use?

**Comment by klicperajo** [comment]
I can still reproduce this with Numba 0.48.0.
