### ISSUE TITLE
Failure when trying to use return value of yield

### ISSUE THREAD

**Issue by nathanielvirgo** [numba/numba#3780]
When running the following code, I get an error telling me to submit a bug report, so I am doing so.

```
import numba as nb

@nb.njit
def test():
    i=0
    while True:
       i = yield i

g = test()
```

So far, any time I try to use the return value of yield it throws one error or another. Is this supported? 

The notes at https://numba.pydata.org/numba-doc/dev/reference/pysupported.html say that the `yield from` construct is not supported, but they don't mention using the return value of `yield`, so I was hopeful that it would be supported.

Here is the error that the above code gives:

```
Traceback (most recent call last):
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/errors.py", line 617, in new_error_context
    yield
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 308, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 482, in lower_assign
    res = self.lower_yield(ty, value)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 502, in lower_yield
    retval = self.context.get_return_value(self.builder, typ, yret)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 653, in get_return_value
    return self.data_model_manager[ty].as_return(builder, val)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/datamodel/models.py", line 895, in as_return
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minrep2.py", line 10, in <module>
    g = test()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 717, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 653, in backend_nopython_mode
    self.metadata)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 1048, in native_lowering_stage
    lower.lower()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 184, in lower
    self.genlower.lower_next_func(self)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/generators.py", line 153, in lower_next_func
    entry_block_tail = lower.lower_function_body()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 244, in lower_function_body
    self.lower_block(block)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/errors.py", line 625, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "minrep2.py", line 7:
def test():
    <source elided>
    while True:
       j = yield i
       ^

[1] During: lowering "$6.2 = yield i" at minrep2.py (7)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by nathanielvirgo** [comment]
A better minimal reproducer is this:

```
import numba as nb

@nb.njit
def test():
	yield None
	yield 1

g = test()
```

I guess the only bug here is in the error message, since if I change `None` to (for example) `'a'`, I get a message saying that the return types of yield are incompatible, which I think is the problem here.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the root cause here is actually the same issue as #3779, augmenting the sample with print statements and switching off the JIT...

```python
import numba as nb

#@nb.njit
def test():
    i=0
    print("entering while")
    while True:
       print("in true, about to yield, i=", i)
       i = yield i
       print("in true, resume from yield, i=", i)
    print("exit while")

g = test()

print(next(g))
print("")
print(next(g))
print("")
print(next(g))
```
gives:
```
entering while
in true, about to yield, i= 0
0

in true, resume from yield, i= None
in true, about to yield, i= None
None

in true, resume from yield, i= None
in true, about to yield, i= None
None
```
which demonstrates that the return type is `None` or `0`, again, Numba will type this as an Optional type which is the problem encountered in #3779. With #3782 applied (and `@njit` added back in) the following happens:
```
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Can't unify yield type from the following types: ?Literal[int](0)

Yield of: IR 'yield i', type '?Literal[int](0)', location: 
File "issue3780.py", line 9:
def test():
    <source elided>
       print("in true, about to yield, i=", i)
       i = yield i
```
which is hopefully more useful? I might actually patch up that error message further to expand out and note what's going on with optional types.

> So far, any time I try to use the return value of yield it throws one error or another. Is this supported?
> The notes at https://numba.pydata.org/numba-doc/dev/reference/pysupported.html say that the yield from construct is not supported, but they don't mention using the return value of yield, so I was hopeful that it would be supported.

Yes, it seems you've just been unlucky and hit the same bug twice from different directions, see https://github.com/numba/numba/blob/f5b2867cd64fbe4e9cdda20c876bf708c289bf5f/numba/tests/test_generators.py#L33-L117 for some examples of `yield` that work.

**Comment by stuartarchibald** [comment]
Updated #3782 to do this:
```python
import numba as nb

@nb.njit
def test():
    i = 0
    yield 1j
    while True:
       i = yield i

g = test()
```
produces:
```
Can't unify yield type from the following types: complex128, int64, none

Yield of: IR 'yield $const0.2', type 'complex128', location: 
File "issue3780.py", line 6:
def test():
    <source elided>
    i = 0
    yield 1j
    ^
Yield of: IR 'yield i', type '?Literal[int](0)', location: 
File "issue3780.py", line 8:
def test():
    <source elided>
    while True:
       i = yield i
       ^
```

**Comment by nathanielvirgo** [comment]
Thanks for posting the list of examples of using yield, it's really helpful. But none of them use the return value of the yield statement. I noticed also that if I try to use `send` on a numba generator, I get the message

```
'_dynfunc._Generator' object has no attribute 'send'
```

So I guess that using `send` on generators is not a supported feature, is that right? If it's possible to support it, it would be really cool.

**Comment by stuartarchibald** [comment]
Do you have an example of what you are trying to do (within the scope of what is known to be supported)? Thanks.

> So I guess that using send on generators is not a supported feature, is that right? If it's possible to support it, it would be really cool.

Correct, this is unsupported, please open a feature request if you think this would be useful.

**Comment by evfro** [comment]
As this is still open, I'd like to report another related issue. Compare two functions:
```python
@nb.jit
def test1():
    i=0
    dct = {i:i}
    while True:
        yield dct[i] # accessing element
```
and
```python
@nb.jit
def test2():
    i=0
    dct = {i:i}
    while True:
        yield dct.get(i, i) # accessing element with default value fallback
```

`g = test1()` works just fine. However, `g = test2()` throws the error `Can't unify yield type`.
Is there an easy fix for the `test2` case so that it doesn't fail?

**Comment by evfro** [comment]
The only modification I can think of is to replace `dct.get(i, i)` with `dct.setdefault(i, i)` (which works in this case). But it's only applicable when the code below `yield` statement doesn't depend on key `i` being present in `dct`. So it's not a very general workaround.

**Comment by stuartarchibald** [comment]
@evfro thanks for the report, expect the root cause is the same as https://github.com/numba/numba/issues/5468.

**Comment by evfro** [comment]
@stuartarchibald thanks! In case someone also has issue with `get` method, I've just found that the line
```python
yield dct[i] if i in dct else i
```
also works and it doesn't mutate `dct`, so it's a better workaround than `setdefault(i, i)`.
