### ISSUE TITLE
Failure when trying to use a JitClass

### ISSUE THREAD

**Issue by nathanielvirgo** [numba/numba#3781]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The following code produces an error message telling me to submit a bug report, so I am doing so.

I expected it to call `test.get_value()` and print the returned value of 1. If I remove the line `@nb.njit`, it does this.

```
import numba as nb

@nb.jitclass([])
class Test:
	def __init__(self):
		pass
	def get_value(self):
		return 1

test = Test()

@nb.njit
def use_test():
	return test.get_value()

print(use_test())
```

Here is the error message it gives:

```
Traceback (most recent call last):
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 499, in get_constant_generic
    impl = self._get_constants.find((ty,))
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 50, in find
    out = self._find(sig)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 59, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.targets.base.OverloadSelector object at 0x11c2e1a58>, (instance.jitclass.Test#7f9f394d82a8<>,))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/errors.py", line 617, in new_error_context
    yield
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 308, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 449, in lower_assign
    value.value)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/targets/base.py", line 502, in get_constant_generic
    raise NotImplementedError("Cannot lower constant of type '%s'" % (ty,))
NotImplementedError: Cannot lower constant of type 'instance.jitclass.Test#7f9f394d82a8<>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "minrep3.py", line 16, in <module>
    print(use_test())
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 367, in _compile_for_args
    raise e
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 324, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 655, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/dispatcher.py", line 82, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 926, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 374, in compile_extra
    return self._compile_bytecode()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 857, in _compile_bytecode
    return self._compile_core()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 844, in _compile_core
    res = pm.run(self.status)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 255, in run
    raise patched_exception
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 246, in run
    stage()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 717, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 666, in _backend
    lowered = lowerfn()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 653, in backend_nopython_mode
    self.metadata)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/compiler.py", line 1048, in native_lowering_stage
    lower.lower()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 219, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 244, in lower_function_body
    self.lower_block(block)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/lowering.py", line 259, in lower_block
    self.lower_inst(inst)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/errors.py", line 625, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/ndv/Library/Python/3.6/lib/python/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot lower constant of type 'instance.jitclass.Test#7f9f394d82a8<>'

File "minrep3.py", line 14:
def use_test():
	return test.get_value()
 ^

[1] During: lowering "$0.1 = global(test: <numba.jitclass.boxing.Test object at 0x11cd45f10>)" at minrep3.py (14)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This should have been caught earlier during the type inference phase. The issue is that instantiating the `Test` outside of the `njit` function leads to it being considered a compile time constant (see http://numba.pydata.org/numba-doc/latest/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable) and there's no mechanism to compile in this particular pattern yet. Conversely, this sort of thing works fine:
```python
import numba as nb

@nb.jitclass([])
class Test:
        def __init__(self):
                pass
        def get_value(self):
                return 1


@nb.njit
def use_test():
    test = Test() # <--- instantiate in the function
    return test.get_value()

print(use_test())


@nb.njit
def use_test2(x): 
    return x.get_value() 

foo = Test()  # <--- instantiate outside the function
print(use_test2(foo))   # <--- pass in as argument
```
