### ISSUE TITLE
Passing a range causes typing to fail

### ISSUE THREAD

**Issue by ivirshup** [numba/numba#3784]
I've managed to get this one pretty short:

```python
import numba

@numba.njit
def foo(x):
    return list(range(x))

@numba.njit
def bar(x):
    return list(x)

foo(3)  # Returns [1, 2, 3]

bar(range(3))  # Throws the TypingError:
```

<details>

```python
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-2-6a02ce2a7a63> in <module>
----> 1 bar(range(3))

/usr/local/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    346                 e.patch_message(msg)
    347 
--> 348             error_rewrite(e, 'typing')
    349         except errors.UnsupportedError as e:
    350             # Something unsupported is present in the user code, add help info

/usr/local/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    313                 raise e
    314             else:
--> 315                 reraise(type(e), e, None)
    316 
    317         argtypes = []

/usr/local/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.ArgConstraint object at 0x11c14fd68>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numba/errors.py", line 617, in new_error_context
    yield
  File "/usr/local/lib/python3.7/site-packages/numba/typeinfer.py", line 198, in __call__
    assert ty.is_precise()
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/numba/typeinfer.py", line 141, in propagate
    constraint(typeinfer)
  File "/usr/local/lib/python3.7/site-packages/numba/typeinfer.py", line 199, in __call__
    typeinfer.add_type(self.dst, ty, loc=self.loc)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/site-packages/numba/errors.py", line 625, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/usr/local/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.InternalError: 
[1] During: typing of argument at <ipython-input-1-95ca53cca6e8> (9)
--%<----------------------------------------------------------------------------


File "<ipython-input-1-95ca53cca6e8>", line 9:
def bar(x):
    return list(x)
    ^

This error may have been caused by the following argument(s):
- argument 0: cannot determine Numba type of <class 'range'>
```

</details>

I figured both of these should work since the docs say [range types are supported](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#built-in-functions).

I'm running `numba` `0.42.1` on macOS 10.14.3, in python `3.7.2`.

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue is that `range` is supported as a function (listed in the docs under `Built-in functions`), but not as a type, I've wording to clarify here https://github.com/numba/numba/pull/3785.

**Comment by stuartarchibald** [comment]
Updated title to reflect nature of issue.
