### ISSUE TITLE
Writing to local graphics memory causes llvm error: Invalid user of intrinsic instruction!

### ISSUE THREAD

**Issue by hugohadfield** [numba/numba#3786]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This numba cuda code:

```
import numba.cuda

@numba.cuda.jit(device=True)
def set_as_unit_rotor_device(array):
    for j in range(1,32):
        array[j] = 0.0
    array[0] = 1.0

@numba.cuda.jit(device=True)
def min_repoducer():
    r_running = numba.cuda.local.array(32, dtype=numba.float64)
    set_as_unit_rotor_device(r_running)
    return 1.0

@numba.cuda.jit
def min_repoducer_kernel():
    i = numba.cuda.grid(1)
    if i < 100:
        total_cost = min_repoducer()

blockdim = 64
griddim = 100
min_repoducer_kernel[griddim, blockdim]()
```

Produces this error:
```
Invalid user of intrinsic instruction!
void (i8*, i8, i64, i32, i1)* bitcast (void (i8*, i8, i64, i1)* @llvm.memset.p0i8.i64 to void (i8*, i8, i64, i32, i1)*)
Broken module found, compilation terminated!
Traceback (most recent call last):
  File "numbacudabug.py", line 23, in <module>
    min_repoducer_kernel[griddim, blockdim]()
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/compiler.py", line 753, in __call__
    kernel = self.specialize(*args)
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/compiler.py", line 764, in specialize
    kernel = self.compile(argtypes)
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/compiler.py", line 783, in compile
    kernel.bind()
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/compiler.py", line 500, in bind
    self._func.get()
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/compiler.py", line 378, in get
    ptx = self.ptx.get()
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/compiler.py", line 350, in get
    **self._extra_options)
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/cudadrv/nvvm.py", line 502, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/cudadrv/nvvm.py", line 233, in compile
    self._try_error(err, 'Failed to compile\n')
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/cudadrv/nvvm.py", line 251, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "/usr/local/lib/python3.5/dist-packages/numba/cuda/cudadrv/nvvm.py", line 141, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile


NVVM_ERROR_COMPILATION

```

The error message is very cryptic (at least for me as someone who knows no llvm) and I think this might be a bug in numba.cuda

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm afraid I cannot reproduce, here is an attempt to do so:
```
$ python -c 'import numba; import llvmlite; print(numba.__version__, llvmlite.__version__)'
0.42.0 0.27.0

$ cat issue3786.py 
import numba.cuda

@numba.cuda.jit(device=True)
def set_as_unit_rotor_device(array):
    for j in range(1,32):
        array[j] = 0.0
    array[0] = 1.0

@numba.cuda.jit(device=True)
def min_repoducer():
    r_running = numba.cuda.local.array(32, dtype=numba.float64)
    set_as_unit_rotor_device(r_running)
    return 1.0

@numba.cuda.jit
def min_repoducer_kernel():
    i = numba.cuda.grid(1)
    if i < 100:
        total_cost = min_repoducer()

blockdim = 64
griddim = 100
min_repoducer_kernel[griddim, blockdim]()


$ python issue3786.py 


$
```

**Comment by stuartarchibald** [comment]
Please could you paste the output of numba -s (redact any parts you don't want to share first!)? Thanks.

**Comment by hugohadfield** [comment]
Ah apologies, just retried this with a different machine, it was a numba version config problem. Thought I was on 0.42.0 but was on 0.40.0!

**Comment by stuartarchibald** [comment]
Thanks for confirming and closing.
