### ISSUE TITLE
Segmentation Fault after string comparison in jitted, cached function

### ISSUE THREAD

**Issue by juergendrachta** [numba/numba#3825]
String comparison in a jitted, cached function leads to a Segmentation fault on numba 0.42.1, Python 3.6.7, (L)Ubuntu 18.04.
On the first call of the minimal example below, the kernel doesn't crash. On the second run, I get a segmentation fault. In both cases -- `nopython=True` and `nopython=False`

Minimal example:

    from numba import jit

    @jit(cache=True)
    def f(x):
        return x == "a"

    if __name__ == "__main__":
        f("b")

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. gdb backtrace:
```
#0  0x0000000000000000 in ?? ()
#1  0x00007f58865e538a in cpython::__main__::f$243(unicode_type) ()
#2  0x00007f587a4da6a4 in call_cfunc ()
   from <path>/3825/lib/python3.7/site-packages/numba/_dispatcher.cpython-37m-x86_64-linux-gnu.so
#3  0x00007f587a4daae9 in compile_and_invoke ()
   from <path>/3825/lib/python3.7/site-packages/numba/_dispatcher.cpython-37m-x86_64-linux-gnu.so
#4  0x00007f587a4dac5f in Dispatcher_call ()
   from <path>/3825/lib/python3.7/site-packages/numba/_dispatcher.cpython-37m-x86_64-linux-gnu.so
#5  0x000055b22ba4146b in _PyObject_FastCallKeywords () at /tmp/build/80754af9/python_1546061345851/work/Objects/call.c:199
```

asm:
```
   │0x7f58865e5321 <_ZN7cpython8__main__5f$243E12unicode_type+1>    push   %r15                                                │
   │0x7f58865e5323 <_ZN7cpython8__main__5f$243E12unicode_type+3>    push   %r14                                                │
   │0x7f58865e5325 <_ZN7cpython8__main__5f$243E12unicode_type+5>    push   %rbx                                                │
   │0x7f58865e5326 <_ZN7cpython8__main__5f$243E12unicode_type+6>    sub    $0xf8,%rsp                                          │
   │0x7f58865e532d <_ZN7cpython8__main__5f$243E12unicode_type+13>   movabs $0x7f58865e6002,%rax                                │
   │0x7f58865e5337 <_ZN7cpython8__main__5f$243E12unicode_type+23>   movabs $0x0,%rcx                                           │
   │0x7f58865e5341 <_ZN7cpython8__main__5f$243E12unicode_type+33>   mov    $0x1,%r8d                                           │
   │0x7f58865e5347 <_ZN7cpython8__main__5f$243E12unicode_type+39>   mov    %r8d,%r9d                                           │
   │0x7f58865e534a <_ZN7cpython8__main__5f$243E12unicode_type+42>   xor    %r8d,%r8d                                           │
   │0x7f58865e534d <_ZN7cpython8__main__5f$243E12unicode_type+45>   mov    %r8b,%r10b                                          │
   │0x7f58865e5350 <_ZN7cpython8__main__5f$243E12unicode_type+48>   lea    0xf0(%rsp),%r8                                      │
   │0x7f58865e5358 <_ZN7cpython8__main__5f$243E12unicode_type+56>   mov    %rdi,0xa0(%rsp)                                     │
   │0x7f58865e5360 <_ZN7cpython8__main__5f$243E12unicode_type+64>   mov    %rsi,%rdi                                           │
   │0x7f58865e5363 <_ZN7cpython8__main__5f$243E12unicode_type+67>   mov    %rax,%rsi                                           │
   │0x7f58865e5366 <_ZN7cpython8__main__5f$243E12unicode_type+70>   mov    %rdx,0x98(%rsp)                                     │
   │0x7f58865e536e <_ZN7cpython8__main__5f$243E12unicode_type+78>   mov    %r9,%rdx                                            │
   │0x7f58865e5371 <_ZN7cpython8__main__5f$243E12unicode_type+81>   mov    %rcx,0x90(%rsp)                                     │
   │0x7f58865e5379 <_ZN7cpython8__main__5f$243E12unicode_type+89>   mov    %r9,%rcx                                            │
   │0x7f58865e537c <_ZN7cpython8__main__5f$243E12unicode_type+92>   mov    %r10b,%al                                           │
   │0x7f58865e537f <_ZN7cpython8__main__5f$243E12unicode_type+95>   mov    0x90(%rsp),%r9                                      │
   │0x7f58865e5387 <_ZN7cpython8__main__5f$243E12unicode_type+103>  callq  *%r9                                                │
  >│0x7f58865e538a <_ZN7cpython8__main__5f$243E12unicode_type+106>  movq   $0x0,0xd8(%rsp)
```
general registers:
```
│rax            0x7f58865e6000   140018188181504                rbx            0x7f58865e5320   140018188178208                │
│rcx            0x1      1                                      rdx            0x1      1                                      │
│rsi            0x7f58865e6002   140018188181506                rdi            0x7f587a389898   140017984379032                │
│rbp            0x7f587a389898   0x7f587a389898                lrsp            0x7fffe02e10b0   0x7fffe02e10b0                 │
│r8             0x7fffe02e11a0   140736954503584                r9             0x0      0                                      │
│r10            0x7f5879f0b700   140017979668224                r11            0x7f5879fee000   140017980596224                │
│r12            0x0      0                                      r13            0x7f587a3d0930   140017984670000                │
│r14            0x7f587a3d0930   140017984670000                r15            0x7f5879f0b750   140017979668304                │
│rip            0x7f58865e538a   0x7f58865e538a <cpython::__maineflags         0x10246  [ PF ZF IF RF ]                        │
│cs             0x33     51                                     ss             0x2b     43                                     │
│ds             0x0      0                                      es             0x0      0                                      │
│fs             0x0      0                                      gs             0x0      0
```
cause is seemingly legitimate null deref, so expect this is a logic bug.

**Comment by stuartarchibald** [comment]
On mainline for the 0.55 release, this does not reproduce any more. Closing, assume fixed by the work on pickling/caching.
