### ISSUE TITLE
Install fails on clean Python 3.5 environment

### ISSUE THREAD

**Issue by TobyRoseman** [numba/numba#3846]
Numba 0.42.1 (the latest version at this time) [has no wheel on PyPI for Python 3.5](https://pypi.org/project/numba/0.42.1/#files). So `pip` will fall back to building the `tar.gz` file. However `numpy` is a dependency to build Numba. So the build will fail if `numpy` is not installed. 

Below are the logs from running `pip install numba` in a new Python 3.5 environment:
```
Collecting numba
  Using cached https://files.pythonhosted.org/packages/e6/45/d1c15c431d3361f074a25dcb278e79367b34ee44b6ca1bc2b7992e2382aa/numba-0.42.1.tar.gz
Collecting llvmlite>=0.27.0dev0 (from numba)
  Using cached https://files.pythonhosted.org/packages/3d/3a/c86c350076bd693cf30878e8625b340f8f36b93fb32ca1d900db7612bae7/llvmlite-0.27.0-cp35-cp35m-macosx_10_9_x86_64.whl
Collecting numpy (from numba)
  Using cached https://files.pythonhosted.org/packages/0e/65/a27186c1692901f7b451572857f6d8d0031b6928500fa479c30a489afeed/numpy-1.16.2-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
Building wheels for collected packages: numba
  Running setup.py bdist_wheel for numba ... error
  Complete output from command /Users/tobyroseman/anaconda3/envs/numba35test/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/g_/_qq7342d05qdqmylcrsvnr9w0000gn/T/pip-install-q3puuyzl/numba/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/g_/_qq7342d05qdqmylcrsvnr9w0000gn/T/pip-wheel-2tdwabes --python-tag cp35:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/g_/_qq7342d05qdqmylcrsvnr9w0000gn/T/pip-install-q3puuyzl/numba/setup.py", line 359, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/private/var/folders/g_/_qq7342d05qdqmylcrsvnr9w0000gn/T/pip-install-q3puuyzl/numba/setup.py", line 96, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ImportError: No module named 'numpy'
  
  ----------------------------------------
  Failed building wheel for numba
  Running setup.py clean for numba
  Complete output from command /Users/tobyroseman/anaconda3/envs/numba35test/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/g_/_qq7342d05qdqmylcrsvnr9w0000gn/T/pip-install-q3puuyzl/numba/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/g_/_qq7342d05qdqmylcrsvnr9w0000gn/T/pip-install-q3puuyzl/numba/setup.py", line 359, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/private/var/folders/g_/_qq7342d05qdqmylcrsvnr9w0000gn/T/pip-install-q3puuyzl/numba/setup.py", line 96, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ImportError: No module named 'numpy'
  
  ----------------------------------------
  Failed cleaning build dir for numba
Failed to build numba
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Python 3.5 wheels are available for 0.43.x series, please try upgrading your Numba version? Closing.
