### ISSUE TITLE
"locals" don't work with for loop

### ISSUE THREAD

**Issue by chtlp** [numba/numba#387]
Here is my code:

```
from numba import *
import numba

import numpy as np

@autojit(locals={"x_pv": Py_uintptr_t, "y_pv": Py_uintptr_t}, nopython=True)
def ddot0(x, x_pv, y, y_pv):

    N = len(x)
    for b in range(N):
        pass


length = 33
x = np.arange(length, dtype=np.float32)
y = x.copy()

x_pv = x.ctypes.data
y_pv = y.ctypes.data

ddot0(x, x_pv, y, y_pv)
```

Here is the trace.  dummy_type_infer seems to be the problem.

```
Traceback (most recent call last):
  File "numba_locals_bug.py", line 22, in <module>
    ddot0(x, x_pv, y, y_pv)
  File "numbawrapper.pyx", line 189, in numba.numbawrapper._NumbaSpecializingWrapper.__call__ (numba/numbawrapper.c:3731)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/wrapping/compiler.py", line 69, in compile_from_args
    return self.compile(signature)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/wrapping/compiler.py", line 88, in compile
    compiled_function = dec(self.py_func)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 224, in _jit_decorator
    nopython=nopython, func_ast=func_ast, **kwargs)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 133, in compile_function
    func_env = pipeline.compile2(env, func, restype, argtypes, func_ast=func_ast, **kwds)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 144, in compile2
    post_ast = pipeline(func_ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 191, in __call__
    ast = self.transform(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 656, in transform
    ast = stage(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 641, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 194, in __call__
    ast = self.transform(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 413, in transform
    return transform.visit(ast)
  File "/memex/linpengt/anaconda/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/memex/linpengt/anaconda/lib/python2.7/ast.py", line 297, in generic_visit
    value = self.visit(value)
  File "/memex/linpengt/anaconda/lib/python2.7/ast.py", line 241, in visit
    return visitor(node)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/specialize/loops.py", line 258, in visit_For
    return self.rewrite_range_iteration(node)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/specialize/loops.py", line 147, in rewrite_range_iteration
    body=body, else_body=else_body)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/visitors.py", line 259, in run_template
    func=func)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/templating.py", line 172, in template_type_infer
    return dummy_type_infer(self.context, tree, env=self.env, **kwargs)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/templating.py", line 183, in dummy_type_infer
    function_level=1, locals=func_env.locals, **kwargs)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 100, in run_env
    pipeline(func_env.ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 191, in __call__
    ast = self.transform(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 656, in transform
    ast = stage(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 641, in _stage
    return _check_stage_object(stage_obj)(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 194, in __call__
    ast = self.transform(ast, env)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 385, in transform
    ast, env, **crnt.kwargs)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/pipeline.py", line 185, in make_specializer
    return cls(env.context, crnt.func, ast, **kws)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 97, in __init__
    self.init_locals()
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 164, in init_locals
    self.handle_locals(arg_types)
  File "/memex/linpengt/anaconda/lib/python2.7/site-packages/numba/type_inference/infer.py", line 143, in handle_locals
    arg_types[idx] = local_type
IndexError: list assignment index out of range
```

**Comment by pitrou** [comment]
Closing as outdated.
