### ISSUE TITLE
support bytes as key_type in typed Dict

### ISSUE THREAD

**Issue by talkaminker** [numba/numba#3877]
currently only unicode_type is supported as key_type in the new Dict.
bytes are also immutable and should be supported.
currently trying to do 
`d = Dict.empty(key_type=numba.typeof(b''),value_type=types.int32)`
will result an error 

Traceback (most recent call last):

  File "<ipython-input-41-897fa6428797>", line 1, in <module>
    d = Dict.empty(key_type=numba.typeof(b''),value_type=types.int32)

  File "C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\typed\typeddict.py", line 86, in empty
    return cls(dcttype=DictType(key_type, value_type))

  File "C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\typed\typeddict.py", line 97, in __init__
    self._dict_type, self._opaque = self._parse_arg(**kwargs)

  File "C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\typed\typeddict.py", line 106, in _parse_arg
    opaque = _make_dict(dcttype.key_type, dcttype.value_type)

  File "C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')

  File "C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)

  File "C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)

TypingError: Invalid use of Function(<function new_dict at 0x00000168CF31FD90>) with argument(s) of type(s): (typeref[readonly bytes(uint8, 1d, C)], class(int32))
 * parameterized
In definition 0:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No definition for lowering <built-in function eq>(readonly bytes(uint8, 1d, C), readonly bytes(uint8, 1d, C)) -> bool

File "..\..\..\..\..\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py", line 792:
    def imp(key, value):
        <source elided>
        dp = _dict_new_minsize(keyty, valty)
        _dict_set_method_table(dp, keyty, valty)
        ^

[1] During: lowering "$0.9 = call $0.5(dp, $0.7, $0.8, func=$0.5, args=[Var(dp, C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (791)), Var($0.7, C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (792)), Var($0.8, C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (792))], kws=(), vararg=None)" at C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (792)
    raised from C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\six.py:659
In definition 1:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No definition for lowering <built-in function eq>(readonly bytes(uint8, 1d, C), readonly bytes(uint8, 1d, C)) -> bool

File "..\..\..\..\..\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py", line 792:
    def imp(key, value):
        <source elided>
        dp = _dict_new_minsize(keyty, valty)
        _dict_set_method_table(dp, keyty, valty)
        ^

[1] During: lowering "$0.9 = call $0.5(dp, $0.7, $0.8, func=$0.5, args=[Var(dp, C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (791)), Var($0.7, C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (792)), Var($0.8, C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (792))], kws=(), vararg=None)" at C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\dictobject.py (792)
    raised from C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\six.py:659
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function new_dict at 0x00000168CF31FD90>)
[2] During: typing of call at C:\Users\tal\Anaconda3\envs\py37\lib\site-packages\numba\typed\typeddict.py (18)

version: win10, python 3.7, numba 0.43

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the issue is lack of `bytes` support more generally, https://github.com/numba/numba/issues/3323#issuecomment-422547994, were bytes supported, IIRC the hashing alg is already implemented and all that would be needed is some wiring up, then it would be permissible for `bytes` to be a key type. At present, valid key types are numerical types, tuples and unicode.

**Comment by jeffteixeira** [comment]
Any news?

**Comment by jeffteixeira** [comment]
I'm converting a value from bytes to string to be able to use it as a key of a typed dictionary and the program has slowed down a lot.

**Comment by stuartarchibald** [comment]
@jeffteixeira the issue is seemingly this: https://github.com/numba/numba/issues/7921, were this fixed then a `__hash__` method would need writing for the `numba.types.Bytes` type, at which point this should all work ok.

**Comment by jeffteixeira** [comment]
Thanks for the clarifications, @stuartarchibald.
