### ISSUE TITLE
test_record_arg_transform tests fail with 0.43.0 on openSUSE/Tumbleweed

### ISSUE THREAD

**Issue by mcepl** [numba/numba#3882]
## Reporting a bug
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (well, the released one, 0.43.0).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When running the test suite on openSUSE/Tumbleweed (x86_64 on ThinkPad T480 if that matters), I get these test failing:
```
[ 9646s] ======================================================================
[ 9646s] FAIL: test_record_arg_transform (numba.tests.test_record_dtype.TestRecordDtype)
[ 9646s] ----------------------------------------------------------------------
[ 9646s] Traceback (most recent call last):
[ 9646s]   File "/home/abuild/rpmbuild/BUILD/numba-0.43.0/numba/tests/test_record_dtype.py", line 694, in test_record_arg_transform
[ 9646s]     self.assertLess(len(transformed), 50)
[ 9646s] AssertionError: 50 not less than 50
[ 9646s] 
[ 9646s] ======================================================================
[ 9646s] FAIL: test_record_arg_transform (numba.tests.test_record_dtype.TestRecordDtypeWithDispatcher)
[ 9646s] ----------------------------------------------------------------------
[ 9646s] Traceback (most recent call last):
[ 9646s]   File "/home/abuild/rpmbuild/BUILD/numba-0.43.0/numba/tests/test_record_dtype.py", line 694, in test_record_arg_transform
[ 9646s]     self.assertLess(len(transformed), 50)
[ 9646s] AssertionError: 50 not less than 50
[ 9646s] 
[ 9646s] ======================================================================
[ 9646s] FAIL: test_record_arg_transform (numba.tests.test_record_dtype.TestRecordDtypeWithStructArrays)
[ 9646s] ----------------------------------------------------------------------
[ 9646s] Traceback (most recent call last):
[ 9646s]   File "/home/abuild/rpmbuild/BUILD/numba-0.43.0/numba/tests/test_record_dtype.py", line 694, in test_record_arg_transform
[ 9646s]     self.assertLess(len(transformed), 50)
[ 9646s] AssertionError: 50 not less than 50
[ 9646s] 
[ 9646s] ======================================================================
[ 9646s] FAIL: test_record_arg_transform (numba.tests.test_record_dtype.TestRecordDtypeWithStructArraysAndDispatcher)
[ 9646s] ----------------------------------------------------------------------
[ 9646s] Traceback (most recent call last):
[ 9646s]   File "/home/abuild/rpmbuild/BUILD/numba-0.43.0/numba/tests/test_record_dtype.py", line 694, in test_record_arg_transform
[ 9646s]     self.assertLess(len(transformed), 50)
[ 9646s] AssertionError: 50 not less than 50
[ 9646s] 
[ 9646s] ----------------------------------------------------------------------
[ 9646s] Ran 7590 tests in 9626.825s
[ 9646s] 
[ 9646s] FAILED (failures=4, skipped=1225, expected failures=9)
[ 9653s] error: Bad exit status from /var/tmp/rpm-tmp.fuDsQ9 (%check)
[ 9653s] 
[ 9653s] 
[ 9653s] RPM build errors:
[ 9653s]     Bad exit status from /var/tmp/rpm-tmp.fuDsQ9 (%check)
[ 9653s] 
[ 9653s] stitny failed "build python-numba.spec" at Mon Mar 18 21:15:33 UTC 2019.
[ 9653s] 

The buildroot was: /var/tmp/build-root/openSUSE_Tumbleweed-x86_64
python-numba$ 
```
Full log of the build process and testing is [log.txt](https://github.com/numba/numba/files/2980488/log.txt).

**Comment by mcepl** [comment]
Hmm, but when run  inside of the official build system, I get [all tests passing](https://build.opensuse.org/package/live_build_log/home:mcepl:branches:devel:languages:python:numeric/python-numpy/openSUSE_Tumbleweed/x86_64). Any idea, what's going on?

**Comment by stuartarchibald** [comment]
Thanks for the report. Seems like the log has disappeared. If possible perhaps put a call to `numba -s` into your build scripts so that when Numba has finished building it can dump out information about the environment. I wonder if it was a NumPy update/change that caused it (the error is because a record dtype representation is a bit longer than expected).

Thanks.

**Comment by mcepl** [comment]
What? https://github.com/numba/numba/files/2980488/log.txt ?

**Comment by stuartarchibald** [comment]
Was looking for differences against this https://build.opensuse.org/package/live_build_log/home:mcepl:branches:devel:languages:python:numeric/python-numpy/openSUSE_Tumbleweed/x86_64

**Comment by mcepl** [comment]
Obviously I have excluded the failing tests from the openSUSE test run.

**Comment by mcepl** [comment]
This is obsolete now.

**Comment by esc** [comment]
@mcepl thank for following up on this!
