### ISSUE TITLE
numpy searchsorted doesn't work on integer arrays

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#3953]
Numba `master` has a bug in the implementation of `np.searchsorted`. It doesn't consider that `np.isnan` is only implemented for floating-point, therefore making it impossible to use it on integer arrays.

Ref: (from dask/dask#4525) https://travis-ci.org/dask/dask/jobs/515911552

MWE:

```python
>>> ss = numba.njit(np.searchsorted)
>>> ss(2, np.array([1,2,3], dtype=np.int64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hameerabbasi/Quansight/numba/numba/dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/hameerabbasi/Quansight/numba/numba/dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/hameerabbasi/Quansight/numba/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name '_wrapfunc': cannot determine Numba type of <class 'function'>

File "../../anaconda/envs/numba/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1246:
def searchsorted(a, v, side='left', sorter=None):
    <source elided>
    """
    return _wrapfunc(a, 'searchsorted', v, side=side, sorter=sorter)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

This would completely break `sparse`, so I hope it's resolved quickly. As I see it, we can do this in two ways:

- Realize that `nan < * == False` and `nan > * == False` and use this fact to implement searchsorted (preferred)
- Implement `np.isnan(integer_dtype)` to return `False`.

If someone gives me a hint here I may be able to send in a PR.

**Comment by seibert** [comment]
I believe in another PR, we needed to implement `np.isnan()` for integers anyway.

**Comment by seibert** [comment]
#3789 is looking for the same feature, but on the GPU

**Comment by hameerabbasi** [comment]
Welp. Looks like I jumped the gun... The issue is not there anymore. Seems like direct-jitting of Numpy functions isn't supported.

```python
>>> def f(a, v):
...   return np.searchsorted(a, v)
...
>>> numba.njit(f)(np.array([1,2,3], dtype=np.int64), 2)
1
```
