### ISSUE TITLE
incorrect handling of if statements with nopython=True

### ISSUE THREAD

**Issue by 0xf0f** [numba/numba#4108]
Each of the following variations on the same code results in numba raising a 'Tuple index out of range' error regarding (it seems) `array.shape[1]`.

The checks on `len(array.shape)` and `array.ndim` are completely ignored.

Code to reproduce:

```python
from numba import jit
import numpy as np
import traceback


@jit(nopython=True)
def test_1(array: np.ndarray):
    if array.ndim == 2:
        if array.shape[1] == 2:
            return 1
    return 0


@jit(nopython=True)
def test_2(array: np.ndarray):
    if array.ndim == 2 and array.shape[1] == 2:
        return 1
    return 0


@jit(nopython=True)
def test_3(array: np.ndarray):
    if len(array.shape) == 2:
        if array.shape[1] == 2:
            return 1
    return 0


@jit(nopython=True)
def test_4(array: np.ndarray):
    if len(array.shape) == 2 and array.shape[1] == 2:
        return 1
    return 0


array = np.empty((1,))

for test in (test_1, test_2, test_3, test_4):
    try:
        test(array)

    except:
        traceback.print_exc()
```

Tracebacks:
```
Traceback (most recent call last):
  File "C:/Users/admin/Documents/Projects/scraps/numba_bug_test.py", line 40, in <module>
    test(array)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 350, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 317, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.StaticGetItemConstraint object at 0x000001BF103C9EB8>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 627, in new_error_context
    yield
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typeinfer.py", line 343, in __call__
    value=ty, index=self.index,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typing\context.py", line 300, in resolve_static_getitem
    return self.resolve_function_type("static_getitem", args, kws)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typing\context.py", line 204, in resolve_function_type
    res = self._resolve_builtin_function_type(func, args, kws)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typing\context.py", line 221, in _resolve_builtin_function_type
    res = defn.apply(args, kws)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typing\templates.py", line 207, in apply
    sig = generic(args, kws)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typing\builtins.py", line 611, in generic
    ret = tup.types[idx]
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typeinfer.py", line 144, in propagate
    constraint(typeinfer)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typeinfer.py", line 351, in __call__
    self.fallback(typeinfer)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 635, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.InternalError: tuple index out of range
[1] During: typing of static-get-item at C:/Users/admin/Documents/Projects/scraps/numba_bug_test.py (9)
--%<----------------------------------------------------------------------------

File "numba_bug_test.py", line 9:
def test_1(array: np.ndarray):
    <source elided>
    if array.ndim == 2:
        if array.shape[1] == 2:
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
```
```
File "numba_bug_test.py", line 16:
def test_2(array: np.ndarray):
    if array.ndim == 2 and array.shape[1] == 2:
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
```
```
File "numba_bug_test.py", line 24:
def test_3(array: np.ndarray):
    <source elided>
    if len(array.shape) == 2:
        if array.shape[1] == 2:
        ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
```
```
File "numba_bug_test.py", line 31:
def test_4(array: np.ndarray):
    if len(array.shape) == 2 and array.shape[1] == 2:
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. What you are seeing is due to two things interacting:
1. Numba, by default, has to compile all branches as if the code were static (there is a caveat, will explain below).
2. As part of compilation, Numba tries to turn get/set with a constant index into a special "static get/set item" node in the intermediate representation it uses when compiling. It does this as it leads to easier analysis/better performance. The assumption made though is that the constant index is a valid index.

As a combination of 1. and 2., the branch which looks dead still needs compiling and then because the `array.shape` of a 1D array is a length one tuple, accessing index 1 is out of bounds,  hence the error.

Switching off the rewrite passes (one of which is the static get/set item rewrite) makes the code work as expected:
```python
from numba import jit
import numpy as np

@jit(nopython=True, no_rewrites=True)
def test_1(array: np.ndarray):
    if array.ndim == 2:
        if array.shape[1] == 2:
            return 1
    return 0


array = np.empty((1,))
print(array.shape)
print(array.ndim)
test_1(array)
```

How to fix this? In the context of the Numba compilation pipeline there is currently a compiler pass which prunes dead branches based on comparison to None, i.e. this pattern:

```python
@jit(nopython=True)
def dead_branch_prune(a, maybe_none):
    if maybe_none is None:
        return a
    else:
        return a + maybe_none

print(dead_branch_prune(10, None))
print(dead_branch_prune(10, 20))
```

this code would suffer the same problem as in the original post, in that there's a branch that could be taken `return a + maybe_none` where, if `maybe_none` is actually None then trying to statically compile it would lead to an error (there's no way to add `numba.types.Integer` and `None`). To get around this Numba analyses the code, spots that there's a comparison between an input argument and None and removes whichever branch won't be taken. I think it might be possible to apply a similar scheme to the case above, in that `array.ndim` is a compile time constant being compared to a user defined compile time constant (`2`), so the dead branch could be pruned.

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/4113 fixes the first two cases, the latter two would be better off waiting for true constant propagation. Hope this helps.
