### ISSUE TITLE
NUMBA_ENABLE_CUDASIM broken with record arrays

### ISSUE THREAD

**Issue by asmeurer** [numba/numba#4111]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```py
$ python
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0] :: Anaconda custom (64-bit) on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba import cuda
>>> import numpy as np
>>> a = np.recarray((1,), dtype=[("value1", np.int64), ("value2", np.float64)]) 
>>> def test(x):
...     x.value1
... 
>>> cuda.jit(test)(a)
>>> 
>>> 
$ NUMBA_ENABLE_CUDASIM=1 python
Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 23:01:00) 
[GCC 7.3.0] :: Anaconda custom (64-bit) on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba import cuda
>>> import numpy as np
>>> a = np.recarray((1,), dtype=[("value1", np.int64), ("value2", np.float64)]) 
>>> def test(x):
...     x.value1
... 
>>> cuda.jit(test)(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/numba/cuda/simulator/kernel.py", line 95, in __call__
    bm.run(grid_point, *fake_args)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/numba/cuda/simulator/kernel.py", line 258, in run
    reraise(*(t.exception))
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/numba/cuda/simulator/kernel.py", line 157, in run
    super(BlockThread, self).run()
  File "/home/aaronmeurer/anaconda3/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/numba/cuda/simulator/kernel.py", line 236, in target
    self._f(*args)
  File "<stdin>", line 2, in test
  File "/home/aaronmeurer/anaconda3/lib/python3.7/site-packages/numba/cuda/simulator/cudadrv/devicearray.py", line 61, in __getattr__
    % attrname), e)
  File "<string>", line 2, in raise_from
AttributeError: tid=[0, 0, 0] ctaid=[0, 0, 0]: Wrapped array has no attribute 'value1'
```

**Comment by asmeurer** [comment]
Using the `x['value1']` syntax works. 

None of the arithmetic operations like `-`, `<`, etc. work either. The `__getattr__` on FakeCUDAArray doesn't handle those. I'm not clear why it isn't handling the record array lookups. My guess is it gets converted to a normal array somewhere (e.g., `a = np.array([(1,1.)], dtype=[("value1", np.int64), ("value2", np.float64)])`), which work with getitem but not getattr lookups on the dtype values.

**Comment by hmgaudecker** [comment]
#4398 looks very similar to this.

A little ironic twist to it is that this pops up in the code that @gmarkall originally wrote the CUDA simulator for back in the day :-). Would be great to have it fixed!
