### ISSUE TITLE
Numba --annotate fails because of llvmlite version

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#4176]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

As title suggest, `numba file.py --anotate` fails with the following error:

```
/usr/local/miniconda3/lib/python3.7/site-packages/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
/Users/guilhermeleobas/Documents/GitHub/numba/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    from numba import njit
  File "/Users/guilhermeleobas/Documents/GitHub/numba/numba/__init__.py", line 163, in <module>
    _ensure_llvm()
  File "/Users/guilhermeleobas/Documents/GitHub/numba/numba/__init__.py", line 85, in _ensure_llvm
    raise ImportError(msg)
ImportError: Numba requires at least version 0.29.0 of llvmlite.
Installed version is 0.28.0.
Please update llvmlite./usr/local/miniconda3/lib/python3.7/site-packages/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
/Users/guilhermeleobas/Documents/GitHub/numba/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
Traceback (most recent call last):
  File "a.py", line 1, in <module>
    from numba import njit
  File "/Users/guilhermeleobas/Documents/GitHub/numba/numba/__init__.py", line 163, in <module>
    _ensure_llvm()
  File "/Users/guilhermeleobas/Documents/GitHub/numba/numba/__init__.py", line 85, in _ensure_llvm
    raise ImportError(msg)
ImportError: Numba requires at least version 0.29.0 of llvmlite.
Installed version is 0.28.0.
Please update llvmlite.
```

Below if the info from `which -a numba` and `numba -s`

```/usr/local/miniconda3/bin/numba```

```
/usr/local/miniconda3/lib/python3.7/site-packages/numba/errors.py:105: UserWarning: Insufficiently recent colorama version found. Numba requires colorama >= 0.3.9
  warnings.warn(msg)
System info:
--------------------------------------------------------------------------------
__Time Stamp__
2019-06-13 02:59:58.550103

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : broadwell
CPU count                                     : 4
CPU Features                                  :
adx aes avx avx2 bmi bmi2 cmov cx16 f16c fma fsgsbase invpcid lzcnt mmx movbe
pclmul popcnt prfchw rdrnd rdseed sahf sse sse2 sse3 sse4.1 sse4.2 ssse3 xsave
xsaveopt

__OS Information__
Platform                                      : Darwin-18.6.0-x86_64-i386-64bit
Release                                       : 18.6.0
System Name                                   : Darwin
Version                                       : Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64
OS specific info                              : 10.14.5   x86_64

__Python Information__
Python Compiler                               : Clang 4.0.1 (tags/RELEASE_401/final)
Python Implementation                         : CPython
Python Version                                : 3.7.1
Python Locale                                 : en_US UTF-8

__LLVM information__
LLVM version                                  : 7.0.0

__CUDA Information__
CUDA driver library cannot be found or no CUDA enabled devices are present.
Error class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init:

HSA is not currently supported on this platform (darwin).
:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : False
+--> Disabled due to                          : Unknown import problem.
OpenMP Threading layer available              : True
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
conda_build_version                           : not installed
conda_env_version                             : 4.6.14
platform                                      : osx-64
python_version                                : 3.7.1.final.0
root_writable                                 : True

__Current Conda Env__
appnope                   0.1.0            py36hf537a9a_0    anaconda
backcall                  0.1.0                    py36_0    anaconda
blas                      1.0                         mkl
ca-certificates           2019.5.15                     0
certifi                   2019.3.9                 py36_0    anaconda
cffi                      1.12.2           py36hb5b8e2f_1
decorator                 4.4.0                    py36_1    anaconda
entrypoints               0.3                      pypi_0    pypi
flake8                    3.7.7                    pypi_0    pypi
intel-openmp              2019.1                      144
ipython                   7.5.0            py36h39e3cac_0    anaconda
ipython_genutils          0.2.0            py36h241746c_0    anaconda
jedi                      0.13.3                   py36_0    anaconda
jinja2                    2.10                     py36_0
libcxx                    4.0.1                hcfea43d_1
libcxxabi                 4.0.1                hcfea43d_1
libedit                   3.1.20181209         hb402a30_0
libffi                    3.2.1                h475c297_4
libgfortran               3.0.1                h93005f0_2
llvmlite                  0.29.0                   py36_0    numba
markupsafe                1.1.1            py36h1de35cc_0
mccabe                    0.6.1                    pypi_0    pypi
mkl                       2019.1                      144
mkl_fft                   1.0.10           py36h5e564d8_0
mkl_random                1.0.2            py36h27c97d8_0
ncurses                   6.1                  h0a44026_1
numpy                     1.16.2           py36hacdab7b_0
numpy-base                1.16.2           py36h6575580_0
openssl                   1.1.1                h1de35cc_0    anaconda
parso                     0.4.0                      py_0    anaconda
pexpect                   4.7.0                    py36_0    anaconda
pickleshare               0.7.5                    py36_0    anaconda
pip                       19.0.3                   py36_0
prompt_toolkit            2.0.9                    py36_0    anaconda
ptyprocess                0.6.0                    py36_0    anaconda
pycodestyle               2.5.0                    pypi_0    pypi
pycparser                 2.19                     py36_0
pyflakes                  2.1.1                    pypi_0    pypi
pygments                  2.4.0                      py_0    anaconda
python                    3.6.8                haf84260_0
readline                  7.0                  h1de35cc_5
scipy                     1.2.1            py36h1410ff5_0
setuptools                40.8.0                   py36_0
six                       1.12.0                   py36_0    anaconda
sphinx-bootstrap-theme    0.7.1                    pypi_0    pypi
sqlite                    3.27.2               ha441bb4_0
tk                        8.6.8                ha441bb4_0
traitlets                 4.3.2            py36h65bd3ce_0    anaconda
wcwidth                   0.1.7            py36h8c6ec74_0    anaconda
wheel                     0.33.1                   py36_0
xz                        5.2.4                h1de35cc_4
zlib                      1.2.11               h1de35cc_3
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================
```

Just a quick note that if I try to import llvmlite from the REPL, everything works fine.

**Comment by stuartarchibald** [comment]
Thanks for the report. I suspect that this is because you are doing development work with Numba but haven't run `python setup.py install` to install the `numba` binary from the development tree into your current environment. It looks like the `numba -s` command being executed above is finding the `numba` binary from the Anaconda base install. Also, you may find http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#Dispatcher.inspect_types useful as it is similar information but accessible programatically.

**Comment by guilhermeleobas** [comment]
Thanks, @stuartarchibald. I forgot that I had a version of numba installed globally on my computer. Removing it and installing the developed on solved the problem.

**Comment by stuartarchibald** [comment]
@guilhermeleobas thanks for confirming, glad it's now working, closing.
