### ISSUE TITLE
numba.cuda.cudadrv.devicearray.DeviceNDArray is not iterable 

### ISSUE THREAD

**Issue by leofang** [numba/numba#4201]
## Reporting a bug

- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

MWE:
```python
>>> from numba import cuda
>>> a = cuda.device_array((5,))
>>> a[:] = range(5)
>>>
>>> # this throws an AssertionError
... for v in a:
...     print(v)
... 
0.0
1.0
2.0
3.0
4.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/cudadrv/devices.py", line 212, in _require_cuda_context
    return fn(*args, **kws)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/cudadrv/devicearray.py", line 479, in __getitem__
    return self._do_getitem(item)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/cuda/cudadrv/devicearray.py", line 489, in _do_getitem
    arr = self._dummy.__getitem__(item)
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/dummyarray.py", line 219, in __getitem__
    dims = [dim.__getitem__(it) for dim, it in zip(self.dims, item)]
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/dummyarray.py", line 219, in <listcomp>
    dims = [dim.__getitem__(it) for dim, it in zip(self.dims, item)]
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/dummyarray.py", line 78, in __getitem__
    single=True,
  File "/home/leofang/conda_envs/cupy_dev/lib/python3.6/site-packages/numba/dummyarray.py", line 51, in __init__
    assert not single or size == 1
AssertionError
>>> # but manually limiting the range works fine
... for i in range(5):
...     print(a[i])
... 
0.0
1.0
2.0
3.0
4.0
>>>
```
It seems that the `StopIteration` exception should have been raised somewhere...

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce with:
```python
from numba import cuda
a = cuda.device_array((5,))
a[:] = range(5)

# this throws an AssertionError
for v in a:
    print(v)
```
seems like there's a problem in the logic of `__getitem__`, I think that if the `dummyarray.Dim` class needs to be `single` the list comp in `dummyarray.Array.__getitem__` should raise `IndexError`.
