### ISSUE TITLE
Conditional numpy array slicing

### ISSUE THREAD

**Issue by andimarafioti** [numba/numba#4225]
## Feature request

Hey! I come from issue #1246. The kind of code that I do (math/signal processing stuff) would be very easy to port to numba if numpy's conditional array slicing was supported. This is a minimal example of it and the error message I currently (numba 0.44.1) get: 

```
from numba import njit
import numpy as np

@njit
def test_jit_numpy_slicing():
    diag = np.array([[1,0],[0,1]])
    zeros = np.zeros((3,3))
    return zeros[diag>0]
```

The output is: 

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-34-d37f51e18613> in <module>()
----> 1 test_jit_numpy_slicing()

~/.local/lib/python3.5/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    349                 e.patch_message(msg)
    350 
--> 351             error_rewrite(e, 'typing')
    352         except errors.UnsupportedError as e:
    353             # Something unsupported is present in the user code, add help info

~/.local/lib/python3.5/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    316                 raise e
    317             else:
--> 318                 reraise(type(e), e, None)
    319 
    320         argtypes = []

~/.local/lib/python3.5/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(float64, 2d, C), array(bool, 2d, C))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    TypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
    raised from /home/amarafioti/.local/lib/python3.5/site-packages/numba/typing/arraydecl.py:71
In definition 9:
    TypeError: unsupported array index type array(bool, 2d, C) in [array(bool, 2d, C)]
    raised from /home/amarafioti/.local/lib/python3.5/site-packages/numba/typing/arraydecl.py:71
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at <ipython-input-33-7dc37423919a> (5)

File "<ipython-input-33-7dc37423919a>", line 5:
def test_jit_numpy_slicing():
    <source elided>
    zeros = np.zeros((3,3))
    return zeros[diag>0]
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

Thank you for numba, I got it to work with my project today after a few workarounds (https://github.com/tifgan/stftGAN/blob/master/data/pghi%20test.ipynb)

**Comment by sklam** [comment]
The provided reproducer has a bug because the dimension didn't match up.  It will produce the following in plain python:

```python
Traceback (most recent call last):
  File "iss4225.py", line 11, in <module>
    r = foo()
  File "iss4225.py", line 8, in foo
    return zeros[diag > 0]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 2
```

Here's a new producer:

```python
from numba import njit
import numpy as np

@njit
def foo():
    diag = np.array([[1,0],[0,1]])
    zeros = np.zeros_like(diag)
    return zeros[diag > 0]


r = foo()
```

**Comment by sklam** [comment]
Numba only supports the boolean indexing case at for 1d arrays at the moment.  There's a potential workaround by first using `.ravel()` to view the input array as 1d.

**Comment by andimarafioti** [comment]
Sorry about my producer not working, I edited the comment now. Yours is a bit more clever, it's what I am looking for. Would the ravel fix work for arbitrary dimensionalities? I might be able to submit a work around if it doesn't involve getting too familiar with the inner working of numba.

**Comment by sklam** [comment]
The ravel fix will only work when the source array and the mask array have the same dimensionality.  In such cases, the result will always be a 1D array.
