### ISSUE TITLE
Numba Strange error while using nopython mode

### ISSUE THREAD

**Issue by juxiangwu** [numba/numba#4243]
import numba
from numba import jit
import numpy as np

@jit(nopython=True)
def rgb2hsv(arr):
    #assert src != None and src.ndim == 3 and src.shape[-1] == 3
    arr = np.float32(src) / 255.0

    out = np.empty_like(arr)

    # -- V Channel
    out_v = arr.max(-1)

    # -- S Channel
    delta = arr.ptp(-1) + 1.0e-9

    # Ignore div by zero
    # old_settings = np.seterr(invalid='ignore')

    out_s = delta / out_v
    out_s[delta == 0.] = 0.

    # -- H Channel

    # R is max
    idx = (arr[:,:,0] == out_v)
    out[idx,0] = (arr[idx,1] - arr[idx,2]) / delta[idx]

    # G is max
    idx = (arr[:,:,1] == out_v)
    out[idx,0] = 2. + (arr[idx,2] - arr[idx,0]) / delta[idx]

    # B is max
    idx = (arr[:,:,2] == out_v)
    out[idx,0] = 4. + (arr[idx,0] - arr[idx,1]) / delta[idx]

    out_h = (out[:,:,0] / 6.0) % 1.
    out_h[delta == 0.] = 0.

    #np.seterr(**old_settings)

    out[:,:,0] = out_h
    out[:,:,1] = out_s
    out[:,:,2] = out_v

    out = np.clip(out,0,255).astype(np.uint8)
    return out

import imageio
src = imageio.imread('resources/images/f1.jpg')
hsv = color.rgb2hsv(src)

while i try to use numba to acceralte the function,got  errors bellow:

PS D:\Develop\machine-vision-workbench> python -u "d:\Develop\machine-vision-workbench\projects\image-processing\numba-imtools\1-color_rgb2hsv.py"
Traceback (most recent call last):
  File "d:\Develop\machine-vision-workbench\projects\image-processing\numba-imtools\1-color_rgb2hsv.py", line 8, in <module>
    dst = color.rgb2hsv(src)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\dispatcher.py", line 351, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\dispatcher.py", line 318, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
?[1m?[1mUnknown attribute 'max' of type float64
?[1m
File "projects\image-processing\numba-imtools\utils\color.py", line 13:?[0m
?[1mdef rgb2hsv(src):
    <source elided>
    # -- V Channel
?[1m    out_v = arr.max(-1)
?[0m    ?[1m^?[0m?[0m
?[0m
?[0m?[1m[1] During: typing of get attribute at d:\Develop\machine-vision-workbench\projects\image-processing\numba-imtools\utils\color.py (13)?[0m
?[1m
File "projects\image-processing\numba-imtools\utils\color.py", line 13:?[0m
?[1mdef rgb2hsv(src):
    <source elided>
    # -- V Channel
?[1m    out_v = arr.max(-1)
?[0m    ?[1m^?[0m?[0m

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by esc** [comment]
@juxiangwu thanks for using Numba! I will edit your report and fix the syntax and highlighting.

**Comment by esc** [comment]
@juxiangwu would it be possible to upload a copy of `f1.jpg` so that I can run your code locally. In the meantime, from the error message it may be that `arr` isn't an array, but instead a scalar, but it is hard to say without being able to run the code.

**Comment by esc** [comment]
@juxiangwu also, could you try to run your code without `@jit` and see if it works.

**Comment by stuartarchibald** [comment]
Reproducer:
```python
from numba import jit
import numpy as np

@jit(nopython=True)
def foo(arr):
    arr = np.float32(src) / 255.0
    out = np.empty_like(arr)
    out_v = arr.max(-1)
    return out

src = np.zeros((10, 10))
foo(src)
```

**Comment by juxiangwu** [comment]
@esc You can also try the code below:
```
import numba
from numba import jit,vectorize
import numpy as np

@jit(nopython=True)
def get_channels_max_values(src):
    #assert src != None and src.ndim == 3 and src.shape[-1] == 3
    out = src.max(-1)
    return out

src = np.random.randint(255,size=(512,512,3))
max_values = get_channels_max_values(src)

```
the same issue occurs

PS D:\Develop\machine-vision-workbench> python -u "d:\Develop\machine-vision-workbench\projects\image-processing\numba-imtools\1-color_rgb2hsv.py"
Traceback (most recent call last):
  File "d:\Develop\machine-vision-workbench\projects\image-processing\numba-imtools\1-color_rgb2hsv.py", line 10, in <module>
    max_values = color.get_channels_max_values(src)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\dispatcher.py", line 351, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\dispatcher.py", line 318, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x000002B75251D080>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\errors.py", line 661, in new_error_context
    yield
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typeinfer.py", line 455, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typeinfer.py", line 474, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typeinfer.py", line 1314, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typing\context.py", line 186, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typing\context.py", line 238, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\types\functions.py", line 214, in get_call_type
    out = template.apply(args, kws)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typing\templates.py", line 225, in apply
    sig = generic(args, kws)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typing\arraydecl.py", line 601, in generic_homog
    assert not args
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typeinfer.py", line 144, in propagate
    constraint(typeinfer)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\typeinfer.py", line 455, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "C:\Users\jenson\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\errors.py", line 669, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\jenson\Anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.InternalError: ?[1m?[1m?[1m?[0m
?[0m?[1m[1] During: resolving callee type: BoundFunction(array.max for array(int32, 3d, C))?[0m
?[0m?[1m[2] During: typing of call at d:\Develop\machine-vision-workbench\projects\image-processing\numba-imtools\utils\color.py (54)
?[0m
--%<----------------------------------------------------------------------------

?[1m
File "projects\image-processing\numba-imtools\utils\color.py", line 54:?[0m
?[1mdef get_channels_max_values(src):
    <source elided>
    #assert src != None and src.ndim == 3 and src.shape[-1] == 3
?[1m    out = src.max(-1)
?[0m    ?[1m^?[0m?[0m

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by juxiangwu** [comment]
@esc Here's [f1.jpg](https://github.com/juxiangwu/machine-vision-workbench/blob/master/resources/images/f1.jpg)

**Comment by stuartarchibald** [comment]
The issue in https://github.com/numba/numba/issues/4243#issuecomment-507713386 is that Numba's `np.ndarray.max()` implementation does not support arguments.

**Comment by juxiangwu** [comment]
@stuartarchibald ,Thanks,when np.ndarray.max() with arguments will implement?

**Comment by stuartarchibald** [comment]
The root cause of the originally reported problem is demonstrated by this:
```python
from numba import jit
import numpy as np

@jit(nopython=True)
def foo():
    arr = np.float32(src)
    return arr

src = np.zeros((10, 10))
foo()
```
issuing a call to `np.float32` in numba will type the result as a `float32` which is incorrect if the argument is array-like.

**Comment by stuartarchibald** [comment]
@juxiangwu RE https://github.com/numba/numba/issues/4243#issuecomment-507723586 this ticket is tracking https://github.com/numba/numba/issues/4258

**Comment by stuartarchibald** [comment]
As of 0.55 this produces:
```
numba.core.errors.TypingError: Casting readonly array(float64, 2d, C) to float32 directly is unsupported. Try doing '<array>.astype(np.float32)' instead
```
which indicates the change needed.

**Comment by gmarkall** [comment]
Given the advice in the present error message, it seems like this could now be closed?
