### ISSUE TITLE
Lowering error with Numpy.fromiter

### ISSUE THREAD

**Issue by yujianll** [numba/numba#4271]
Error message:

```
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
'NoneType' object has no attribute 'yield_points'

File "code/utility.py", line 96:
def error():
    <source elided>
    sampled = np.zeros(10, dtype=types)
    res = np.fromiter((func(x) for x in sampled), dtype=int)
    ^

[1] During: lowering "$4.5.117 = yield $4.4" at code/utility.py (96)
```

Reproducer:

```
def func(x):
    return x[0]

@jit
def error():
    topo = [chr(ord('a') + i) for i in range(5)]
    types = [(var_name, "int") for var_name in topo]
    sampled = np.zeros(10, dtype=types)
    res = np.fromiter((func(x) for x in sampled), dtype=int)

error()
```

**Comment by yujianll** [comment]
Similar error, another reproducer:

`@jit
def error():
topo = [chr(ord('a') + i) for i in range(5)]
types = [(var_name, "int") for var_name in topo]
sampled = np.zeros(10, dtype=types)
issue = tuple(sampled[i] for i in top[:3])

error()`

**Comment by esc** [comment]
@yujianll thanks for reporting this! We appreciate you using Numba and taking the time to open issues. I will reformat your comments for legibility and queue this for inspection.

**Comment by esc** [comment]
I actually get a slightly different error:

```
vhaenel@parraline [numba] [numba:typed_list:★ ★ ★ ] ~/git/numba
💥 zsh» python foo11.py
Traceback (most recent call last):
  File "foo11.py", line 17, in <module>
    error()
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 351, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 316, in error_rewrite
    raise e
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 245, in run
    stage()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 501, in stage_nopython_frontend
    self.locals)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 1104, in type_inference_stage
    infer.build_constraint()
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 877, in build_constraint
    self.constrain_statement(inst)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 1156, in constrain_statement
    self.typeof_assign(inst)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 1227, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 1324, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 1248, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'chr': cannot determine Numba type of <class 'builtin_function_or_method'>

File "foo11.py", line 11:
def error():
    topo = [chr(ord('a') + i) for i in range(5)]
```

**Comment by esc** [comment]
Using plan `@jit` I can reproduce the error you mentioned.

**Comment by yujianll** [comment]
Yeah I tried both modes. I want to use fromiter to apply function to each row of Numpy array in the first case, and construct a tuple in the second case.

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue in this function (and the other reproducer):
```python
@jit
def error():
    topo = [chr(ord('a') + i) for i in range(5)]
    types = [(var_name, "int") for var_name in topo]
    sampled = np.zeros(10, dtype=types)
    res = np.fromiter((func(x) for x in sampled), dtype=int)

error()
```
is that Numba does not support generator comprehensions, switching the arg to `np.fromiter` to a list comprehension fixes it, this works fine:
```python
from numba import jit
import numpy as np

def func(x):
    return x[0]

@jit
def error():
    topo = [chr(ord('a') + i) for i in range(5)]
    types = [(var_name, "int") for var_name in topo]
    sampled = np.zeros(10, dtype=types)
    res = np.fromiter([func(x) for x in sampled], dtype=int)

error()
```
am going to note this as a bug because the lowering error should not have happened as the unsupported functionality should have been caught earlier.

**Comment by yujianll** [comment]
Thanks! So I cannot use generator comprehensions even in plain `@jit` mode?

**Comment by esc** [comment]
@yujianll running the following suggests that you are correct:

```
from numba import jit


@jit
def error():
    gen = (i**2 for i in range(10))
    print(gen)


error.py_func()
error()
```

The first---the original python function---works and prints something about the generator, whereas the second one fails.

**Comment by yujianll** [comment]
Thanks!
