### ISSUE TITLE
New @jit option to get mixed nopython/forceobj (old default behavior)

### ISSUE THREAD

**Issue by jpivarski** [numba/numba#4278]
## Feature request

In a recent Numba release, the old fallback to object mode has been deprecated; the future behavior of `@numba.jit` will be the same as `@numba.njit`. One thing that was lost, however, was the mode that would partially lower a function (e.g. for loops that consist of purely lowerable variables and functions) and partially use object mode (e.g. statements outside the for loops that use unlowerable functions or functions unknown to Numba).

This is neither `nopython=True`, which attempts to lower everything and raises an error if unsuccessful, nor `forceobj=True`, which uses object mode for everything, lowering nothing.

Here is an example function in which the old default behavior was perfect:

```python
@numba.jit                                 # no qualification in old Numba
def run_numba(height, width, maxiterations=20):
    y, x = numpy.ogrid[-1:0:height*1j, -1.5:0:width*1j]
    c = x + y*1j
    fractal = numpy.full(c.shape, maxiterations, dtype=numpy.int32)
    for h in range(height):
        for w in range(width):             # for each pixel (h, w)...
            z = c[h, w]
            for i in range(maxiterations): # iterate at most 20 times
                z = z**2 + c[h, w]         # applying z → z² + c
                if abs(z) > 2:             # if it diverges (|z| > 2)
                    fractal[h, w] = i      # color the plane with iteration number
                    break                  # we're done, no need to keep iterating
    return fractal
```

The first few lines use functions unknown to Numba (`numpy.ogrid`, I believe) and, in the old behavior, were left in object mode, while the for loops were lowered. This demonstrably had the same running time as

```python
def run_numba(height, width, maxiterations=20):
    y, x = numpy.ogrid[-1:0:height*1j, -1.5:0:width*1j]
    c = x + y*1j
    fractal = numpy.full(c.shape, maxiterations, dtype=numpy.int32)
    tight_loop(c, fractal, maxiterations)
    return fractal

@numba.jit(nopython=True)
def tight_loop(c, fractal, maxiterations):
    for h in range(height):
        for w in range(width):             # for each pixel (h, w)...
            z = c[h, w]
            for i in range(maxiterations): # iterate at most 20 times
                z = z**2 + c[h, w]         # applying z → z² + c
                if abs(z) > 2:             # if it diverges (|z| > 2)
                    fractal[h, w] = i      # color the plane with iteration number
                    break                  # we're done, no need to keep iterating
```

except that I didn't have to find the cut point manually.

I don't mind that the new default will be `nopython=True` (I think it's a good change), but I'd like an option to get mixed compilation when I want it.

**Comment by stuartarchibald** [comment]
@jpivarski Thanks for the write up, much appreciated. I'll make sure this is raised at the core developer meeting.

**Comment by domokane** [comment]
I have same issue. It has broken all my code. Can this be fixed asap please.

**Comment by stuartarchibald** [comment]
> I have same issue. It has broken all my code. Can this be fixed asap please.

@domokane please could you expand on this? The fall-back behaviour to mixed/object mode has only been deprecated, no actual change to this code path has taken place as yet.

**Comment by domokane** [comment]
Hi Stuart

I updated numba two days ago and now I am getting errors in code that previously worked. I have a customised class called FinDate. I thought it might be due to this change.

The warning and error message are as listed below. I could perhaps move the FinDate class outside the function so that only floats are inside but as this previously worked I had not expected to have to do this. I am simply using @jit - I am not specifying nopython on the function.

Any help would be appreciated.

Regards

D

=====================================================================================

FinAsianOption.py:552: NumbaWarning:
Compilation is falling back to object mode WITH looplifting enabled because Function "valueMC_fast" failed type inference due to: Untyped global name 'FinDate': cannot determine Numba type of <class 'type'>

File "FinAsianOption.py", line 565:
   def valueMC_fast(self,
       <source elided>

        t0 = FinDate.datediff(valueDate,self._startAveragingDate)/gDaysInYear
        ^

 @jit
Traceback (most recent call last):

............... There is then a list of files and lines from compiler.py and lowering,py and then error.py  and then ......

  File "C:\Users\Dominic\Anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value

LoweringError: (<class 'numba.ir.StaticRaise'>, <numba.ir.StaticRaise object at 0x000001C56A91F2E8>)

=========================================================================================


On 22/07/2019 09:20, stuartarchibald wrote:

I have same issue. It has broken all my code. Can this be fixed asap please.

@domokane<https://github.com/domokane> please could you expand on this? The fall-back behaviour to mixed/object mode has only been deprecated, no actual change to this code path has taken place as yet.

**Comment by stuartarchibald** [comment]
@domokane thanks for the update. This was a bug in the 0.44.x series for which there exist numerous duplicate issues, the fix went in here https://github.com/numba/numba/pull/4224. If you update to the recently released version 0.45.0 (available on the Numba channel and will be on default channels soon) then your code should work fine, if it does not please open a **new** issue with a reproducer for the problem, thanks. Try this to get an updated Numba:
```
conda install -c numba numba=0.45
```
