### ISSUE TITLE
dtype error which I can't explain

### ISSUE THREAD

**Issue by Nathan-Furnal** [numba/numba#4322]
Hi,

So I was trying to answer some question which worked well in NumPy and I thought I could use Numba but it doesn't work : 

```
import numpy as np
from numba import jit
ts = np.arange(60_000,step=4)
x = 100*np.random.rand(1,1500)
prob = 100*np.random.rand(15_000,1500)
xx = x.T @ x
idx = np.tril_indices(n=xx.shape[0])
len_ts = len(ts)
xx_values = xx[idx]
```
I was basically looping over some indexes I grabbed earlier and then I summed the answers that I stored in an array.
This function works well in numpy and does the job

```
def fast_loop(xx_values, prob, idx, ts):
    
    final = np.zeros(len(ts),dtype=np.float64)
    idx_0, idx_1 = idx
    
    for index, time in enumerate(ts):
        print(index)
        final[index] = np.sum(prob[time,idx_0] * prob[time, idx_1] * xx_values)
    
    return final

```
yet when I do 

```
@jit(nopython=True)
def fast_loop(xx_values, prob, idx, ts):
    
    final = np.zeros(len(ts),dtype=np.float64)
    idx_0, idx_1 = idx
    
    for index, time in enumerate(ts):
        print(index)
        final[index] = np.sum(prob[time,idx_0] * prob[time, idx_1] * xx_values)
    
    return final
```
I get 

> ---------------------------------------------------------------------------
> TypingError                               Traceback (most recent call last)
> <ipython-input-81-74592f00f35a> in <module>
> ----> 1 tst = fast_loop(xx_values, prob, idx, ts)
> 
> ~\Miniconda3\envs\ml\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
>     349                 e.patch_message(msg)
>     350 
> --> 351             error_rewrite(e, 'typing')
>     352         except errors.UnsupportedError as e:
>     353             # Something unsupported is present in the user code, add help info
> 
> ~\Miniconda3\envs\ml\lib\site-packages\numba\dispatcher.py in error_rewrite(e, issue_type)
>     316                 raise e
>     317             else:
> --> 318                 reraise(type(e), e, None)
>     319 
>     320         argtypes = []
> 
> ~\Miniconda3\envs\ml\lib\site-packages\numba\six.py in reraise(tp, value, tb)
>     656             value = tp()
>     657         if value.__traceback__ is not tb:
> --> 658             raise value.with_traceback(tb)
>     659         raise value
>     660 
> 
> TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (array(float64, 2d, C), (int32, array(int64, 1d, A)))
>  * parameterized
> In definition 0:
>     All templates rejected with literals.
> In definition 1:
>     All templates rejected without literals.
> In definition 2:
>     All templates rejected with literals.
> In definition 3:
>     All templates rejected without literals.
> In definition 4:
>     All templates rejected with literals.
> In definition 5:
>     All templates rejected without literals.
> In definition 6:
>     All templates rejected with literals.
> In definition 7:
>     All templates rejected without literals.
> In definition 8:
>     NotImplementedError: only one advanced index supported
>     raised from C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\numba\typing\arraydecl.py:67
> In definition 9:
>     NotImplementedError: only one advanced index supported
>     raised from C:\Users\natha\Miniconda3\envs\ml\lib\site-packages\numba\typing\arraydecl.py:67
> This error is usually caused by passing an argument of a type that is unsupported by the named function.
> [1] During: typing of intrinsic-call at <ipython-input-80-7aa9ad980061> (9)
> 
> File "<ipython-input-80-7aa9ad980061>", line 9:
> def fast_loop(xx_values, prob, idx, ts):
>     <source elided>
>         print(index)
>         final[index] = np.sum(prob[time,idx_0] * prob[time, idx_1] * xx_values)
>         ^
> 
> This is not usually a problem with Numba itself but instead often caused by
> the use of unsupported features or an issue in resolving types.
> 
> To see Python/NumPy features supported by the latest release of Numba visit:
> http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
> and
> http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html
> 
> For more information about typing errors and how to debug them visit:
> http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
> 
> If you think your code should work with Numba, please report the error message
> and traceback, along with a minimal reproducer at:
> https://github.com/numba/numba/issues/new
> 

Which I don't understand because I didn't try any advanced indexing afaik

Thanks !

**Comment by stuartarchibald** [comment]
Thanks for the report. This:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function() with argument(s) of type(s): (array(float64, 2d, C), (int32, array(int64, 1d, A)))
```
is the problem, in that it looks like Numba is being asked to index a 2D array using an int32 and another array, which is not supported. Thankfully the work around seems to be relatively easy (write a loop) and because Numba compiles loops there's no cost:
```python
import numpy as np
from numba import jit
ts = np.arange(60_000,step=4)
x = 100*np.random.rand(1,1500)
prob = 100*np.random.rand(15_000,1500)
xx = x.T @ x
idx = np.tril_indices(n=xx.shape[0])
len_ts = len(ts)
xx_values = xx[idx]

@jit(nopython=True)
def fast_loop(xx_values, prob, idx, ts):

    final = np.zeros(len(ts),dtype=np.float64)
    idx_0, idx_1 = idx

    for index, time in enumerate(ts):
        for ix0, ix1 in zip(idx_0, idx_1):
            final[index] += np.sum(prob[time, ix0] * prob[time, ix1] * xx_values)

    return final

fast_loop(xx_values, prob, idx, ts)
```






For reference, this also reproduces the original error:
```pycon
In [29]: @njit 
    ...: def foo(x, y): 
    ...:     return x[0, y] 
    ...:                                                                                                                        

In [30]: x = np.arange(100).reshape(10, 10)                                                                                     

In [31]: y = np.array([1, 4, 7])                                                                                                

In [32]: foo(x, y) 
```

**Comment by Nathan-Furnal** [comment]
@stuartarchibald Thank you for taking the time to answer my question !

For some reason when I run your function, it just leaves me hanging and nothing happens. I tried to put ``print`` statements at different places of the code but still nothing.

I'm using numba ``0.44.1`` and numpy ``1.16.4``

**Comment by stuartarchibald** [comment]
@Nathan-Furnal perhaps try with less data?

**Comment by Nathan-Furnal** [comment]
It runs fine in Numpy and compilation of the function shouldn’t take long though ? I’ll try with a more minimal example and get back to you !

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : stuartarchibald <notifications@github.com>
Envoyé : Monday, July 15, 2019 1:21:45 PM
À : numba/numba
Cc : Nathan Furnal; Mention
Objet : Re: [numba/numba] dtype error which I can't explain (#4322)


@Nathan-Furnal<https://github.com/Nathan-Furnal> perhaps try with less data?

**Comment by stuartarchibald** [comment]
I can reproduce it just "hanging" but if you use less data it completes.

**Comment by Nathan-Furnal** [comment]
Do you know why it is the case ? Should I try to put my data in chunks in the future ? Thanks !

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : stuartarchibald <notifications@github.com>
Envoyé : Monday, July 15, 2019 1:23:36 PM
À : numba/numba
Cc : Nathan Furnal; Mention
Objet : Re: [numba/numba] dtype error which I can't explain (#4322)


I can reproduce it just "hanging" but if you use less data it completes.

**Comment by esc** [comment]
I just had another look at this and it seems this now yields a different error (although that may be, because the way errors are displayed has changed):

```
In [10]: foo(x, y)
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
~/git/numba/numba/core/typeinfer.py in propagate(self, typeinfer)
    153                 try:
--> 154                     constraint(typeinfer)
    155                 except ForceLiteralArg as e:

~/git/numba/numba/core/typeinfer.py in __call__(self, typeinfer)
    688                 fnty = typeinfer.resolve_value_type(None, fnty)
--> 689             self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
    690

~/git/numba/numba/core/typeinfer.py in resolve(self, typeinfer, typevars, fnty)
    585         try:
--> 586             sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
    587         except ForceLiteralArg as e:

~/git/numba/numba/core/typeinfer.py in resolve_call(self, fnty, pos_args, kw_args)
   1535             # Normal non-recursive call
-> 1536             return self.context.resolve_function_type(fnty, pos_args, kw_args)
   1537

~/git/numba/numba/core/typing/context.py in resolve_function_type(self, func, args, kws)
    210         if res is None and last_exception is not None:
--> 211             raise last_exception
    212

~/git/numba/numba/core/typing/context.py in resolve_function_type(self, func, args, kws)
    193         try:
--> 194             res = self._resolve_user_function_type(func, args, kws)
    195         except errors.TypingError as e:

~/git/numba/numba/core/typing/context.py in _resolve_user_function_type(self, func, args, kws, literals)
    245             # XXX fold this into the __call__ attribute logic?
--> 246             return func.get_call_type(self, args, kws)
    247

~/git/numba/numba/core/types/functions.py in get_call_type(self, context, args, kws)
    320                                  "or successful signature")
--> 321         failures.raise_error()
    322

~/git/numba/numba/core/types/functions.py in raise_error(self)
    225                     raise fail.error
--> 226         raise errors.TypingError(self.format())
    227

TypingError: No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(array(int64, 2d, C), Tuple(Literal[int](0), array(int64, 1d, C)))

There are 22 candidate implementations:
  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(int64, 2d, C), Tuple(int64, array(int64, 1d, C)))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 162.
    With argument(s): '(array(int64, 2d, C), Tuple(int64, array(int64, 1d, C)))':
   Rejected as the implementation raised a specific error:
     NotImplementedError: only one advanced index supported
       Traceback (most recent call last):
         File "/Users/vhaenel/git/numba/numba/core/types/functions.py", line 298, in get_call_type
           sig = temp.apply(nolitargs, nolitkws)
         File "/Users/vhaenel/git/numba/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 165, in generic
           out = get_array_index_type(ary, idx)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 65, in get_array_index_type
           raise NotImplementedError("only one advanced index supported")
       NotImplementedError: only one advanced index supported
  raised from /Users/vhaenel/git/numba/numba/core/typing/arraydecl.py:65

During: typing of intrinsic-call at <ipython-input-5-4af8c476cb04> (3)

The above exception was the direct cause of the following exception:

TypingError                               Traceback (most recent call last)
<ipython-input-10-390364e37253> in <module>
----> 1 foo(x, y)

~/git/numba/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    412                 e.patch_message(msg)
    413
--> 414             error_rewrite(e, 'typing')
    415         except errors.UnsupportedError as e:
    416             # Something unsupported is present in the user code, add help info

~/git/numba/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    353                 e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    354             if config.FULL_TRACEBACKS:
--> 355                 raise e
    356             else:
    357                 raise e.with_traceback(None)

~/git/numba/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    364                 argtypes.append(self.typeof_pyval(a))
    365         try:
--> 366             return self.compile(tuple(argtypes))
    367         except errors.ForceLiteralArg as e:
    368             # Received request for compiler re-entry with the list of arguments

~/git/numba/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34

~/git/numba/numba/core/dispatcher.py in compile(self, sig)
    816             self._cache_misses[sig] += 1
    817             try:
--> 818                 cres = self._compiler.compile(args, return_type)
    819             except errors.ForceLiteralArg as e:
    820                 def folded(args, kws):

~/git/numba/numba/core/dispatcher.py in compile(self, args, return_type)
     79             return retval
     80         else:
---> 81             raise retval
     82
     83     def _compile_cached(self, args, return_type):

~/git/numba/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
     89
     90         try:
---> 91             retval = self._compile_core(args, return_type)
     92         except errors.TypingError as e:
     93             self._failed_cache[key] = e

~/git/numba/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    102
    103         impl = self._get_implementation(args, {})
--> 104         cres = compiler.compile_extra(self.targetdescr.typing_context,
    105                                       self.targetdescr.target_context,
    106                                       impl,

~/git/numba/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    625     pipeline = pipeline_class(typingctx, targetctx, library,
    626                               args, return_type, flags, locals)
--> 627     return pipeline.compile_extra(func)
    628
    629

~/git/numba/numba/core/compiler.py in compile_extra(self, func)
    361         self.state.lifted = ()
    362         self.state.lifted_from = None
--> 363         return self._compile_bytecode()
    364
    365     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/git/numba/numba/core/compiler.py in _compile_bytecode(self)
    423         """
    424         assert self.state.func_ir is None
--> 425         return self._compile_core()
    426
    427     def _compile_ir(self):

~/git/numba/numba/core/compiler.py in _compile_core(self)
    403                 self.state.status.fail_reason = e
    404                 if is_final_pipeline:
--> 405                     raise e
    406         else:
    407             raise CompilerError("All available pipelines exhausted")

~/git/numba/numba/core/compiler.py in _compile_core(self)
    394             res = None
    395             try:
--> 396                 pm.run(self.state)
    397                 if self.state.cr is not None:
    398                     break

~/git/numba/numba/core/compiler_machinery.py in run(self, state)
    337                     (self.pipeline_name, pass_desc)
    338                 patched_exception = self._patch_error(msg, e)
--> 339                 raise patched_exception
    340
    341     def dependency_analysis(self):

~/git/numba/numba/core/compiler_machinery.py in run(self, state)
    328                 pass_inst = _pass_registry.get(pss).pass_inst
    329                 if isinstance(pass_inst, CompilerPass):
--> 330                     self._runPass(idx, pass_inst, state)
    331                 else:
    332                     raise BaseException("Legacy pass in use")

~/git/numba/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34

~/git/numba/numba/core/compiler_machinery.py in _runPass(self, index, pss, internal_state)
    287             mutated |= check(pss.run_initialization, internal_state)
    288         with SimpleTimer() as pass_time:
--> 289             mutated |= check(pss.run_pass, internal_state)
    290         with SimpleTimer() as finalize_time:
    291             mutated |= check(pss.run_finalizer, internal_state)

~/git/numba/numba/core/compiler_machinery.py in check(func, compiler_state)
    260
    261         def check(func, compiler_state):
--> 262             mangled = func(compiler_state)
    263             if mangled not in (True, False):
    264                 msg = ("CompilerPass implementations should return True/False. "

~/git/numba/numba/core/typed_passes.py in run_pass(self, state)
     90                               % (state.func_id.func_name,)):
     91             # Type inference
---> 92             typemap, return_type, calltypes = type_inference_stage(
     93                 state.typingctx,
     94                 state.func_ir,

~/git/numba/numba/core/typed_passes.py in type_inference_stage(typingctx, interp, args, return_type, locals, raise_errors)
     68
     69         infer.build_constraint()
---> 70         infer.propagate(raise_errors=raise_errors)
     71         typemap, restype, calltypes = infer.unify(raise_errors=raise_errors)
     72

~/git/numba/numba/core/typeinfer.py in propagate(self, raise_errors)
   1069                                   if isinstance(e, ForceLiteralArg)]
   1070                 if not force_lit_args:
-> 1071                     raise errors[0]
   1072                 else:
   1073                     raise reduce(operator.or_, force_lit_args)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(array(int64, 2d, C), Tuple(Literal[int](0), array(int64, 1d, C)))

There are 22 candidate implementations:
  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(array(int64, 2d, C), Tuple(int64, array(int64, 1d, C)))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 162.
    With argument(s): '(array(int64, 2d, C), Tuple(int64, array(int64, 1d, C)))':
   Rejected as the implementation raised a specific error:
     NotImplementedError: only one advanced index supported
       Traceback (most recent call last):
         File "/Users/vhaenel/git/numba/numba/core/types/functions.py", line 298, in get_call_type
           sig = temp.apply(nolitargs, nolitkws)
         File "/Users/vhaenel/git/numba/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 165, in generic
           out = get_array_index_type(ary, idx)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 65, in get_array_index_type
           raise NotImplementedError("only one advanced index supported")
       NotImplementedError: only one advanced index supported
  raised from /Users/vhaenel/git/numba/numba/core/typing/arraydecl.py:65

During: typing of intrinsic-call at <ipython-input-5-4af8c476cb04> (3)

File "<ipython-input-5-4af8c476cb04>", line 3:
def foo(x, y):
    return x[0,y]
```

**Comment by gmarkall** [comment]
Closing this as the original question appears to be answered and no further follow-up received.
