### ISSUE TITLE
Can't use typed list in pandas constructor

### ISSUE THREAD

**Issue by leohaim** [numba/numba#4347]
I do not know if I should name it a bug or a feature request: Currently using the new numba typed list available since numba 0.45 for constructing a pandas data frame leads to the following error:

File "/fio/srvx7/leo/python/typed_dict_list.py", line 30, in <module>
  pl=pd.DataFrame(y)
File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 451, in __init__
  copy=copy)
File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 146, in init_ndarray
  values = prep_ndarray(values, copy=copy)
File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 246, in prep_ndarray
  if values.ndim == 1:

builtins.AttributeError: 'List' object has no attribute 'ndim'

If I convert the List object to a regular list before putting it into the pandas constructor, it works. 
Using typed dicts as input for pandas constructors also works. 

Thus I am asking it if is feasible to add the ndim attribute to List objects. 

The whole reproducer:

import os,sys,glob
from numba import *
from numba import types
from numba.typed import Dict,List
import numpy
import pandas as pd
import time

@njit
def lappend(n):
    
    l=List()
    for i in range(n):
        l.append(numpy.float32(i))
        
    return l

t=time.time()
x = Dict.empty(
    key_type=types.unicode_type,
    value_type=types.float32[:],
)

n=100000
x['a']=numpy.arange(n,dtype=numpy.float32)
y=lappend(n)

p=pd.DataFrame(x)

# pl=pd.DataFrame(list(y))  # this works
pl=pd.DataFrame(y)  # this fails

print(time.time()-t)
print()

**Comment by gnu-user** [comment]
Having the exact same issue as well, had to revert to just using the default list instead.

**Comment by esc** [comment]
@leohaim thanks for trying out the typed-list and for reporting this! I'll reformat your comment for legibility. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by esc** [comment]
So, I took a look at this, and if I add the `ndim` attribute to the typed-list using the following patch:

```
diff --git i/numba/typed/typedlist.py w/numba/typed/typedlist.py
index fd885d2dd3..045f225bb0 100644
--- i/numba/typed/typedlist.py
+++ w/numba/typed/typedlist.py
@@ -189,6 +189,10 @@ class List(MutableSequence):
         """
         return self._list_type is not None

+    @property
+    def ndim(self):
+        return 1
+
     def _initialise_list(self, item):
         lsttype = types.ListType(typeof(item))
         self._list_type, self._opaque = self._parse_arg(lsttype)
```

I get the followup error:

```
146 vhaenel@parraline [numba] [numba:master:★ ★ ★ ★ ] ~/git/numba
💥 zsh» python foo19.py                                                                                                                                                                                                             :(
Traceback (most recent call last):
  File "foo19.py", line 32, in <module>
    pl = pd.DataFrame(y)  # this fails
  File "/Users/vhaenel/miniconda3/envs/numba/lib/python3.7/site-packages/pandas/core/frame.py", line 451, in __init__
    copy=copy)
  File "/Users/vhaenel/miniconda3/envs/numba/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 146, in init_ndarray
    values = prep_ndarray(values, copy=copy)
  File "/Users/vhaenel/miniconda3/envs/numba/lib/python3.7/site-packages/pandas/core/internals/construction.py", line 247, in prep_ndarray
    values = values.reshape((values.shape[0], 1))
AttributeError: 'List' object has no attribute 'reshape'
```

I don't think it is feasible to add `reshape` as a method to typed-list, so we will have to search for an alternative solution.

**Comment by esc** [comment]
Looking further, I am not sure what the typed-list needs to provide in order for Pandas to accept it as a 'list like' container. Looking at the Pandas code here:

https://github.com/pandas-dev/pandas/blob/master/pandas/core/dtypes/cast.py#L67

Probably for the time being, your best bet is to cast it to a Numpy array before converting it into a Pandas object.

**Comment by jbrockmendel** [comment]
It looks like the safe thing to do is add an extra `values = np.asarray(values)` in `internals.construction.prep_ndarray`.  I'll need to look more closely to see if we (pandas) can make use of the typed-ness.

**Comment by leohaim** [comment]
Thanks for the clarifications. 

I tried using pd.DataFrame(numpy.asarray(y)) and found that it is about 2x slower than pd.DateFrame(list(y)) when using a typed list of 100000 float elements.

**Comment by seibert** [comment]
@esc: Would it be possible for lists where the element type maps to a NumPy dtype to be able to create a NumPy array view on the internal list data?  This view would become invalid if the list length is changed, but it would be useful in these sorts of cases to speed import of lists into things that expect numpy arrays.

**Comment by jbrockmendel** [comment]
@leohaim can you open an issue on the pandas tracker with the perf difference; that's pretty surprising

**Comment by esc** [comment]
@seibert yes, that would probably be possible. I think it would require some additional infrastructure such as a mutation lock that is set when the view is exported and invalidated when any mutation operation such as "del", "pop", "setitem" or "append" is called. Incidentally, this would also help in the iterator case where detecting mutation during iteration only works when the length changes. None the less I would suggest to discuss this in a separate issue.

**Comment by esc** [comment]
I am relabelling this as a 'feature_request' - but it may be the case that the logic for accepting a `numba.typed.List` in a Dataframe must be implemented in Pandas.
