### ISSUE TITLE
Unsupported context manager in use

### ISSUE THREAD

**Issue by WilliamHoltam** [numba/numba#4360]
```
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\multiprocess\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "<ipython-input-2-e0c1d945678a>", line 17, in speed_test_parallel
  File "c:\users\williamholtam\documents\githubrepos\galliumresearch\galliumresearch\gallium.py", line 139, in classify
    self._set_accuracy_context(data)
  File "c:\users\williamholtam\documents\githubrepos\galliumresearch\galliumresearch\gallium.py", line 184, in _set_accuracy_context
    abs_area, Dt = self.median_worst_area(data)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\dispatcher.py", line 395, in _compile_for_args
    raise e
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler.py", line 266, in run
    raise patched_exception
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler.py", line 257, in run
    stage()
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\compiler.py", line 461, in stage_frontend_withlift
    locals=self.locals,
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\transforms.py", line 335, in with_lifting
    cmkind, extra = _get_with_contextmanager(func_ir, blocks, blk_start)
  File "C:\Users\WilliamHoltam\Miniconda3\lib\site-packages\numba\transforms.py", line 396, in _get_with_contextmanager
    loc=blocks[blk_start].loc,
numba.errors.CompilerError: Failed in nopython mode pipeline (step: Handle with contexts)
Unsupported context manager in use

    def func(self, data):
        dt = np.diff(data[:, 0])
        with np.errstate(all="ignore"):
        ^

"This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.0."
```

**Comment by esc** [comment]
@WilliamHoltam thanks for the report and for helping to improve Numba. I will reformat your comment now using the markdown syntax.

**Comment by esc** [comment]
@WilliamHoltam thanks for this, in order to investigate this further, would it be possible to post the code, or the code snippet that led to this error?

**Comment by WilliamHoltam** [comment]
@esc I can't post the exact code but the error was caused by the context manager ``` with np.errstate(all="ignore"):``` used within this method:
```
def func(self, data):
        dt = np.diff(data[:, 0])
        with np.errstate(all="ignore"):
             print("Do Something")
```

**Comment by esc** [comment]
@WilliamHoltam thanks for that. Looking at http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html  it may be that using `np.errstate` isn't supported. However when looking at http://numba.pydata.org/numba-doc/latest/reference/fpsemantics.html#warnings-and-errors it seems like it should be. Also, doing a `git grep` in the Numba codebase, doesn't yield anything useful:

```
💥 zsh» git --no-pager grep errstate
docs/source/reference/fpsemantics.rst:settings, or the :class:`numpy.errstate` context manager to switch them
docs/source/reference/fpsemantics.rst:   with np.errstate(all='ignore'):
```

**Comment by stuartarchibald** [comment]
I think the issue is that in general context managers are not supported, as noted [here](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html#constructs).

The single (user visible) exception to this is an `objmode` context manager for jumping out of `nopython` mode into object mode in the managed block, [documentation here](http://numba.pydata.org/numba-doc/latest/user/withobjmode.html#the-objmode-context-manager).

`np.errstate` itself is also not supported, see [here](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html ) for the parts of NumPy that are. There is a small amount of control over divide by zero behaviour through the use of the `error_model` kwarg to `@jit` et al. See [here](http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#jit-functions) for more information.

Hope this helps.
