### ISSUE TITLE
Appending a Python int to a Numba typed list (of type np.intp) raises an error.

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#4370]
I can't append a  Python `int` to `nb.typed.List.empty_list(np.intp)`

```
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numpy as np

In [2]: import numba as nb

In [3]: nb.typed.List.empty_list(np.intp).append(42)
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-3-20f63de11a16> in <module>
----> 1 nb.typed.List.empty_list(np.intp).append(42)

~/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/typed/typedlist.py in append(self, item)
    221         if not self._typed:
    222             self._initialise_list(item)
--> 223         _append(self, item)
    224
    225     def __setitem__(self, i, item):

~/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

~/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344
    345         argtypes = []

~/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x624a51160>.
Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast int64 to <class 'numpy.int64'>: %".42" = load i64, i64* %"casteditem"

File "miniconda3/envs/uarray/lib/python3.7/site-packages/numba/listobject.py", line 433:
    def impl(l, item):
        <source elided>
        casteditem = _cast(item, itemty)
        status = _list_append(l, casteditem)
        ^

[1] During: lowering "$0.8 = call $0.5(l, casteditem, func=$0.5, args=[Var(l, /Users/hameerabbasi/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/listobject.py (432)), Var(casteditem, /Users/hameerabbasi/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/listobject.py (432))], kws=(), vararg=None)" at /Users/hameerabbasi/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/listobject.py (433)
[2] During: resolving callee type: BoundFunction((<class 'numba.types.containers.ListType'>, 'append') for ListType[<class 'numpy.int64'>])
[3] During: typing of call at /Users/hameerabbasi/miniconda3/envs/uarray/lib/python3.7/site-packages/numba/typed/typedlist.py (39)

Enable logging at debug level for details.

File "miniconda3/envs/uarray/lib/python3.7/site-packages/numba/typed/typedlist.py", line 39:
def _append(l, item):
    l.append(item)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by hameerabbasi** [comment]
The motivation for typing upfront is to avoid typing errors with empty lists when passing into `nopython` functions. Consider the following:

```python
@njit
def foo(a):
     return a
```

Here, passing in a typed list will work but not an untyped (empty) one.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think that what might be missing here is a way to construct an empty typed list from some non `numba.types` type, i.e. something more familiar, like a NumPy type/value. I'm wondering if `numba.typed.List.empty(item=<something>)` could be written, so that users can supply a concrete item of the type they anticipate using in the list and an empty list is created with the item type being the Numba `types` equivalent of `item`.

@esc @sklam, thoughts? This, for me, is just a reincarnation of the `[<inst> for _ in range(0)]` problem.

**Comment by hameerabbasi** [comment]
It's a little better than that, since if the type can be inferred at compile time, things are okay. For example, the following is okay:

```python
@njit
def foo(flag):
    x = List()
    if flag:
        x.append(42)
    return x
```

This works for `True` and `False` whereas before it would only work on `True`.

**Comment by esc** [comment]
@stuartarchibald maybe that can be done, maybe it needs to be explicit as `empty_from_instance`, not sure exactly.

**Comment by stuartarchibald** [comment]
@esc thanks. I think two things probably need to come out of this:

1. `nb.typed.List.empty_list` right now ought to be patched to make sure the thing a user is supplying as a type is a `numba.types.Type` instance which would stop the above problem.
2. Consider implementing the `from_instance` pattern. Seems like the number of users having to use Numba types is going to increase since `numba.typed` appeared and there's no type inference to help in certain use cases. I also think that the type constructors need some strengthening  (https://github.com/numba/numba/issues/4369 had an unrelated problem but related issue in using `numba.types`).

**Comment by hameerabbasi** [comment]
In situations like these (also for `Dict`, `Set`, et. al.) I feel it would be nice to use the square-bracket syntax already familiar to `mypy` users: `numba.Typed.List[np.intp]()`.

**Comment by sklam** [comment]
The square-bracket support requires py3.7+ for `__class_getitem__` added in [PEP560](https://www.python.org/dev/peps/pep-0560/)

**Comment by hameerabbasi** [comment]
Not really, one can always define a metaclass with `__getitem__`.

**Comment by 00sapo** [comment]
I was trying to let numba infer the type as workaround but it doesn't work:

`[np.array(0).astype(np.intp)][1:].append(42)`

To make the code cleaner, you can also define a function for this:

```python
import numpy as np
import numba as nb

@nb.njit
def empty_np_list():
    [np.array(0).astype(np.intp)][1:].append(42)
empty_np_list()
```

**Comment by gmarkall** [comment]
> I was trying to let numba infer the type as workaround but it doesn't work:
> 
> `[np.array(0).astype(np.intp)][1:].append(42)`

I think this is a [reflected list](https://numba.readthedocs.io/en/stable/reference/pysupported.html?highlight=reflected%20list#list-reflection) rather than a typed list, so although it doesn't work, it differs from the original issue.

**Comment by esc** [comment]
@00sapo I think this is an issue with scalar Numpy arrays. Here is a workaround:

```
In [5]: import numpy as np
   ...: import numba as nb
   ...:
   ...: @nb.njit
   ...: def empty_np_list():
   ...:     [int(np.array([0]).astype(np.intp)[0])][1:].append(42)
   ...: empty_np_list()
```
