### ISSUE TITLE
windows 10, Ryzen1800X cpu, python ver 3.7 numba error

### ISSUE THREAD

**Issue by BugQualia** [numba/numba#4379]
```
C:\projects\NERM\venv\Scripts\python.exe C:/projects/NERM/dreamer.py
Traceback (most recent call last):
  File "C:/projects/NERM/dreamer.py", line 8, in <module>
    l4_cell = CNS.EntropyReducer(1000, 800, 1000, 400, 500)
  File "C:\projects\NERM\body\CNS.py", line 134, in __init__
    self.prox = Synapse(self.cell_count, prox_in_size, max_prox_count)
  File "C:\projects\NERM\body\CNS.py", line 77, in __init__
    self.remap(np.arange(self.cell_count, dtype='int32'))
  File "C:\projects\NERM\body\CNS.py", line 89, in remap
    maybe = self.pref[i][np.where(nb_isin(self.pref[i], maybe))[0][:self.max_syn_count - poss.size]]
  File "C:\projects\NERM\venv\lib\site-packages\numba\dispatcher.py", line 395, in _compile_for_args
    raise e
  File "C:\projects\NERM\venv\lib\site-packages\numba\dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\projects\NERM\venv\lib\site-packages\numba\dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\projects\NERM\venv\lib\site-packages\numba\dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\projects\NERM\venv\lib\site-packages\numba\dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\projects\NERM\venv\lib\site-packages\numba\dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 266, in run
    raise patched_exception
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 257, in run
    stage()
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "C:\projects\NERM\venv\lib\site-packages\numba\compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "C:\projects\NERM\venv\lib\site-packages\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\projects\NERM\venv\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\projects\NERM\venv\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "C:\projects\NERM\venv\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\projects\NERM\venv\lib\site-packages\numba\lowering.py", line 410, in lower_inst
    func(self, inst)
  File "C:\projects\NERM\venv\lib\site-packages\numba\npyufunc\parfor.py", line 51, in _lower_parfor_parallel
    ensure_parallel_support()
  File "C:\projects\NERM\venv\lib\site-packages\numba\parfor.py", line 3985, in ensure_parallel_support
    raise errors.UnsupportedParforsError(msg)
numba.errors.UnsupportedParforsError: Failed in nopython mode pipeline (step: nopython mode backend)
The 'parallel' target is not currently supported on Windows operating systems when using Python 2.7, or on 32 bit hardware.
[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.10, range = (0, $42.6, 1))]{74: <ir.Block at C:\projects\NERM\body\CNS.py (11)>, 84: <ir.Block at C:\projects\NERM\body\CNS.py (12)>, 60: <ir.Block at C:\projects\NERM\body\CNS.py (10)>, 94: <ir.Block at C:\projects\NERM\body\CNS.py (10)>}Var(parfor_index.10, C:\projects\NERM\body\CNS.py (10))" at C:\projects\NERM\body\CNS.py (10)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!



Process finished with exit code 1

```

This error occured when compiling a function:
```python
@nb.jit(parallel=True, nopython=True)
def nb_isin(matrix, search):
    flat_mat = matrix.reshape(-1)
    out = np.empty(flat_mat.shape[0], dtype=nb.boolean)
    search = set(search)
    for i in nb.prange(flat_mat.shape[0]):
        if flat_mat[i] in search:
            out[i] = True
        else:
            out[i] = False
    return out.reshape(matrix.shape)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. It looks like your system is either running `windows+python2.7` or `32 bit windows`, both of which are not supported on the `parallel=True` target, is this the case?


RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment]
Note: formatted OP.

**Comment by BugQualia** [comment]
Thanks. The problem is that I was running on `windows10 64bit + python 32bit` 
Once I reinstalled python 64bit, It works perfectly.

Was not expecting to get the response this quickly. 
Thanks for the formatting. Have a great day :D

**Comment by stuartarchibald** [comment]
No problem, glad you got it working.
