### ISSUE TITLE
CUDA simulator mode does not recognize customized numpy dtype array

### ISSUE THREAD

**Issue by codemk8** [numba/numba#4398]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I cannot access structure names in cuda simulator mode.

The following is the code that can demonstrate this problem:

```python
from numba import cuda
from numpy import float32, int32
import numpy as np

DTYPE = [('f1', float32), ('i1', int32)]
                               

@cuda.jit
def naive_kernel(arr):
    arr[cuda.threadIdx.x].f1 = 3.0
    arr[cuda.threadIdx.x].i1 = cuda.threadIdx.x

if __name__ == '__main__':
    print(cuda.gpus)
    host_arr = np.zeros(32, dtype=np.dtype(DTYPE))
    device_arr = cuda.to_device(host_arr)
    naive_kernel[1, 32](device_arr)
```

It runs fine with my GPUs. But if I switch over to simulation mode, I got the following error:

```bash
# It runs fine in non-simulation mode
$ python3 numba_dtype_sim.py 
<Managed Device 0>
# Switch to simulation mode
$ export NUMBA_ENABLE_CUDASIM=1
$ python3 numba_dtype_sim.py 
<Managed Device 0>
Traceback (most recent call last):
  File "numba_dtype_sim.py", line 17, in <module>
    naive_kernel[1, 32](device_arr)
  File "/home/.../.local/lib/python3.6/site-packages/numba/cuda/simulator/kernel.py", line 95, in __call__
    bm.run(grid_point, *fake_args)
  File "/home/.../.local/lib/python3.6/site-packages/numba/cuda/simulator/kernel.py", line 258, in run
    reraise(*(t.exception))
  File "/home/....local/lib/python3.6/site-packages/numba/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/home/.../.local/lib/python3.6/site-packages/numba/cuda/simulator/kernel.py", line 157, in run
    super(BlockThread, self).run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/.../.local/lib/python3.6/site-packages/numba/cuda/simulator/kernel.py", line 236, in target
    self._f(*args)
  File "numba_dtype_sim.py", line 10, in naive_kernel
    arr[cuda.threadIdx.x].f1 = 3.0
AttributeError: tid=[18, 0, 0] ctaid=[0, 0, 0]: 'numpy.void' object has no attribute 'f1'
```

I am on python 3.6.7, numba 0.44 (pretty sure same behavior in 0.45).

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce, this is a bug.

**Comment by stuartarchibald** [comment]
Related: https://github.com/numba/numba/issues/4413. Think there needs to be a stronger differentiation between record array and array of structured dtype.

**Comment by c200chromebook** [comment]
Cosigned

**Comment by c200chromebook** [comment]
I believe https://github.com/numba/numba/pull/5343 fixes
