### ISSUE TITLE
Compilation/Type Error with opaque pointers in cffi

### ISSUE THREAD

**Issue by aseyboldt** [numba/numba#4424]
I am trying to use a cffi wrapped c library that uses opaque pointers. I created a minimal C lib similar to it for debugging purposes. It contains two functions: `make_vector` that creates an opaque pointer object, and `sum` that consumes it.

<details>

```python
from cffi import FFI
import numba
import numba.cffi_support
import numpy as np

ffi = FFI()
ffi.set_source(
    '_ffi',
    '''
    struct Vector_t {
        double x1;
        double x2;
    };
    typedef struct Vector_t *Vector;
    typedef double(*Vecfunc)(Vector);

    Vector make_vector(void) {
        Vector vec = malloc(sizeof(struct Vector_t));
        if (vec == NULL) {
            abort();
        }
        return vec;
    }
    
    double apply_vecfunc(Vecfunc func, Vector vec) {
        return func(vec);
    }

    double sum(Vector vec) {
        return vec->x1 + vec->x2;
    }
    '''
)
ffi.cdef(
    '''
    typedef ... *Vector;
    typedef double(*Vecfunc)(Vector);
    
    double apply_vecfunc(Vecfunc func, Vector vec);
    Vector make_vector(void);
    double sum(Vector vec);
    ''')
ffi.compile()
```

</details>

If I call the functions in nopython mode, I get typing errors, because as far as I understand it, numba doesn't know how to map the return type of `make_vector` to a numba type.

```python
numba.cffi_support.register_module(_ffi)
#numba.cffi_support.register_type(
#    _ffi.ffi.typeof('Vector').item,
#    numba.types.Opaque('Vector'))

@numba.njit
def foo():
    vec = _ffi.lib.make_vector()
    return _ffi.lib.sum(vec)
```

<details>

```
TypingError                               Traceback (most recent call last)
<ipython-input-7-c19b6d9633cf> in <module>
----> 1 foo()

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375 
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344 
    345         argtypes = []

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at resolving type of attribute "make_vector" of "$0.2".
<ctype 'struct $$Vector'>
[1] During: typing of get attribute at <ipython-input-6-fb79965445b4> (8)
Enable logging at debug level for details.

File "<ipython-input-6-fb79965445b4>", line 8:
def foo():
    vec = _ffi.lib.make_vector()
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

</details>

If I uncomment the line that registers `Vector` as an opaque type, type checking seems to work.
```python
>>> vec = _ffi.lib.make_vector()
>>> numba.cffi_support.map_type(_ffi.ffi.typeof(vec))
Vector*
```
But it fails with an exception during compilation:

<details>

```
AttributeError                            Traceback (most recent call last)
~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    661     try:
--> 662         yield
    663     except NumbaError as e:

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower_inst(self, inst)
    300             ty = self.typeof(inst.target.name)
--> 301             val = self.lower_assign(ty, inst)
    302             self.storevar(val, inst.target.name)

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower_assign(self, ty, inst)
    458         elif isinstance(value, ir.Expr):
--> 459             return self.lower_expr(ty, value)
    460 

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower_expr(self, resty, expr)
   1008             else:
-> 1009                 impl = self.context.get_getattr(ty, expr.attr)
   1010                 attrty = self.context.typing_context.resolve_getattr(ty,

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/targets/base.py in get_getattr(self, typ, attr)
    587                 pyval = getattr(typ.pymod, attr)
--> 588                 llval = self.get_constant(attrty, pyval)
    589                 def imp(context, builder, typ, val, attr):

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/targets/base.py in get_constant(self, ty, val)
    509         # HACK: pass builder=None to preserve get_constant() API
--> 510         return self.get_constant_generic(None, ty, val)
    511 

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/targets/base.py in get_constant_generic(self, builder, ty, val)
    499             impl = self._get_constants.find((ty,))
--> 500             return impl(self, builder, ty, val)
    501         except NotImplementedError:

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/targets/builtins.py in constant_function_pointer(context, builder, ty, pyval)
    292     ptrval = context.add_dynamic_addr(builder, ty.get_pointer(pyval),
--> 293                                       info=str(pyval))
    294     return builder.bitcast(ptrval, ptrty)

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/targets/base.py in add_dynamic_addr(self, builder, intaddr, info)
   1052         assert isinstance(intaddr, utils.INT_TYPES), 'dyn addr not of int type'
-> 1053         mod = builder.module
   1054         llvoidptr = self.get_value_type(types.voidptr)

AttributeError: 'NoneType' object has no attribute 'module'

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-9-c19b6d9633cf> in <module>
----> 1 foo()

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    393                     e.patch_message(''.join(e.args) + help_msg)
    394             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 395             raise e
    396 
    397     def inspect_llvm(self, signature=None):

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    350                 argtypes.append(self.typeof_pyval(a))
    351         try:
--> 352             return self.compile(tuple(argtypes))
    353         except errors.TypingError as e:
    354             # Intercept typing error that may be due to an argument

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, sig)
    691 
    692             self._cache_misses[sig] += 1
--> 693             cres = self._compiler.compile(args, return_type)
    694             self.add_overload(cres)
    695             self._cache.save_overload(sig, cres)

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in compile(self, args, return_type)
     74 
     75     def compile(self, args, return_type):
---> 76         status, retval = self._compile_cached(args, return_type)
     77         if status:
     78             return retval

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in _compile_cached(self, args, return_type)
     88 
     89         try:
---> 90             retval = self._compile_core(args, return_type)
     91         except errors.TypingError as e:
     92             self._failed_cache[key] = e

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in _compile_core(self, args, return_type)
    106                                       args=args, return_type=return_type,
    107                                       flags=flags, locals=self.locals,
--> 108                                       pipeline_class=self.pipeline_class)
    109         # Check typing error if object mode is used
    110         if cres.typing_error is not None and not flags.enable_pyobject:

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    970     pipeline = pipeline_class(typingctx, targetctx, library,
    971                               args, return_type, flags, locals)
--> 972     return pipeline.compile_extra(func)
    973 
    974 

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in compile_extra(self, func)
    388         self.lifted = ()
    389         self.lifted_from = None
--> 390         return self._compile_bytecode()
    391 
    392     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in _compile_bytecode(self)
    901         """
    902         assert self.func_ir is None
--> 903         return self._compile_core()
    904 
    905     def _compile_ir(self):

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in _compile_core(self)
    888         self.define_pipelines(pm)
    889         pm.finalize()
--> 890         res = pm.run(self.status)
    891         if res is not None:
    892             # Early pipeline completion

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    264                     # No more fallback pipelines?
    265                     if is_final_pipeline:
--> 266                         raise patched_exception
    267                     # Go to next fallback pipeline
    268                     else:

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in run(self, status)
    255                 try:
    256                     event("-- %s" % stage_name)
--> 257                     stage()
    258                 except _EarlyPipelineCompletion as e:
    259                     return e.result

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in stage_nopython_backend(self)
    762         """
    763         lowerfn = self.backend_nopython_mode
--> 764         self._backend(lowerfn, objectmode=False)
    765 
    766     def stage_compile_interp_mode(self):

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in _backend(self, lowerfn, objectmode)
    701             self.library.enable_object_caching()
    702 
--> 703         lowered = lowerfn()
    704         signature = typing.signature(self.return_type, *self.args)
    705         self.cr = compile_result(

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in backend_nopython_mode(self)
    688                 self.calltypes,
    689                 self.flags,
--> 690                 self.metadata)
    691 
    692     def _backend(self, lowerfn, objectmode):

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/compiler.py in native_lowering_stage(targetctx, library, interp, typemap, restype, calltypes, flags, metadata)
   1141         lower = lowering.Lower(targetctx, library, fndesc, interp,
   1142                                metadata=metadata)
-> 1143         lower.lower()
   1144         if not flags.no_cpython_wrapper:
   1145             lower.create_cpython_wrapper(flags.release_gil)

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower(self)
    175         if self.generator_info is None:
    176             self.genlower = None
--> 177             self.lower_normal_function(self.fndesc)
    178         else:
    179             self.genlower = self.GeneratorLower(self)

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower_normal_function(self, fndesc)
    216         # Init argument values
    217         self.extract_function_arguments()
--> 218         entry_block_tail = self.lower_function_body()
    219 
    220         # Close tail of entry block

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower_function_body(self)
    241             bb = self.blkmap[offset]
    242             self.builder.position_at_end(bb)
--> 243             self.lower_block(block)
    244 
    245         self.post_lower()

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/lowering.py in lower_block(self, block)
    256             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    257                                    loc=self.loc, errcls_=defaulterrcls):
--> 258                 self.lower_inst(inst)
    259 
    260     def create_cpython_wrapper(self, release_gil=False):

~/anaconda3/envs/pymc/lib/python3.7/contextlib.py in __exit__(self, type, value, traceback)
    128                 value = type()
    129             try:
--> 130                 self.gen.throw(type, value, traceback)
    131             except StopIteration as exc:
    132                 # Suppress StopIteration *unless* it's the same exception that

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/errors.py in new_error_context(fmt_, *args, **kwargs)
    668         from numba import config
    669         tb = sys.exc_info()[2] if config.FULL_TRACEBACKS else None
--> 670         six.reraise(type(newerr), newerr, tb)
    671 
    672 

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    657         if value.__traceback__ is not tb:
    658             raise value.with_traceback(tb)
--> 659         raise value
    660 
    661 else:

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
'NoneType' object has no attribute 'module'

File "<ipython-input-8-3672370f2198>", line 8:
def foo():
    vec = _ffi.lib.make_vector()
    ^

[1] During: lowering "$0.3 = getattr(value=$0.2, attr=make_vector)" at <ipython-input-8-3672370f2198> (8)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

</details>

The error seems not to be related to the `Vector` type directly. I also hacked the numba source code a bit to make sure that all cffi `Vector*` types map to `numba.types.voidptr` in `numba.cffi_support.map_type`, but this led to the same error message during compilation.

Is it that opaque types through cffi are in general not supported?

The error message is the same as #4417.
This seems related: #4115

**Comment by aseyboldt** [comment]
I just figured out that the second error message goes away if I redefine the cffi functions outside the njit function:

```
numba.cffi_support.register_module(_ffi)
numba.cffi_support.register_type(
    _ffi.ffi.typeof('Vector').item,
    numba.types.Opaque('Vector'))

make_vector = _ffi.lib.make_vector
sum = _ffi.lib.sum

@numba.njit
def foo():
    vec = make_vector()
    return sum(vec)
```

**Comment by aseyboldt** [comment]
As a feature request: A better error message or support for accessing cffi functions through `_ffi.lib` would make this easier.

As I've not seen the `numba.types.Opaque` trick in the documentation: Most cffi features seem to work just fine, including creating cfuncs that take opaque pointers as argument:
```python
numba.cffi_support.register_module(_ffi)
numba.cffi_support.register_type(
    _ffi.ffi.typeof('Vector').item,
    numba.types.Opaque('Vector'))

vecfunc_type = numba.cffi_support.map_type(_ffi.ffi.typeof('Vecfunc'))

sum = _ffi.lib.sum

@numba.cfunc(vecfunc_type)
def foo(vec):
    return sum(vec)

_ffi.lib.apply_vecfunc(foo.cffi, vec)
```

One thing that still fails for me however, is creating functions that take the cffi python value of the opaque object as input:
```python
numba.cffi_support.register_module(_ffi)
numba.cffi_support.register_type(
    _ffi.ffi.typeof('Vector').item,
    numba.types.Opaque('Vector'))

make_vector = _ffi.lib.make_vector
sum = _ffi.lib.sum

@numba.njit(numba.float64(numba.cffi_support.map_type(_ffi.ffi.typeof('Vector'))))
def foo(vec):
    return sum(vec)

vec = make_vector()
foo(vec)
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-29-033fc935bb16> in <module>
     13     return sum(vec)
     14 
---> 15 foo(vec)

~/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/dispatcher.py in _explain_matching_error(self, *args, **kws)
    498         msg = ("No matching definition for argument type(s) %s"
    499                % ', '.join(map(str, args)))
--> 500         raise TypeError(msg)
    501 
    502     def _search_new_conversions(self, *args, **kws):

TypeError: No matching definition for argument type(s) pyobject
```

**Comment by aseyboldt** [comment]
And just some thought on how to fix that from someone who really doesn't know the internals of numba. Probably safe to ignore... :-)

With a small change to `cffi_support.map_type` it should be possible to define a custom numba type for a opaque cffi *pointer* (not the opaque value as previously):
```diff
diff --git a/numba/typing/cffi_utils.py b/home/adr/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/typing/cffi_utils.py
index cc3c70966..cb777bbc8 100644
--- a/numba/typing/cffi_utils.py
+++ b/home/adr/anaconda3/envs/pymc/lib/python3.7/site-packages/numba/typing/cffi_utils.py
@@ -107,6 +107,10 @@ def map_type(cffi_type, use_record_dtype=False):
         When True, struct types are mapped to a NumPy Record dtype.
 
     """
+    predefined = _type_map().get(cffi_type)
+    if predefined is not None:
+        return predefined
+
     primed_map_type = partial(map_type, use_record_dtype=use_record_dtype)
     kind = getattr(cffi_type, 'kind', '')
     if kind == 'union':
@@ -130,10 +134,7 @@ def map_type(cffi_type, use_record_dtype=False):
     elif kind == 'struct' and use_record_dtype:
         return map_struct_to_record_dtype(cffi_type)
     else:
-        result = _type_map().get(cffi_type)
-        if result is None:
-            raise TypeError(cffi_type)
-        return result
+        raise TypeError(cffi_type)
 
 
 def map_struct_to_record_dtype(cffi_type):
```

After that, could we define the necessary logic for the cdata type in a new type? I'm a bit lost on how something like that should work however. Somehow numba would have to be told how to represent the new type to llvm I guess. The `numba.datamodel` seems to be involved in that. :-)

```python
class CFFIOpaquePointer(numba.types.CPointer):
    def __init__(self, ffi, cffi_type):
        super(CFFIOpaquePointer, self).__init__(np.dtype('void'))
        self._ffi = ffi
        self._cffi_type = cffi_type
        self.name = cffi_type.cname

    def cast_python_value(self, args):
        cffi_type = self._ffi.typeof(args)
        if cffi_type != self._cffi_type:
            raise TypeError(
                'Invalid python object. Should be %s' % self.name)
        voidptr = int(_ffi.ffi.cast('intptr_t', vec))
        return voidptr ## ??

Vector = CFFIOpaquePointer(_ffi.ffi, _ffi.ffi.typeof('Vector'))

numba.cffi_support.register_module(_ffi)
numba.cffi_support.register_type(
    _ffi.ffi.typeof('Vector'),
    Vector)

make_vector = _ffi.lib.make_vector
sum = _ffi.lib.sum

vec = make_vector()

@numba.njit(numba.float64(Vector))
def foo(vec):
    return sum(vec)

foo(Vector(vec))
```

If that is indeed the right way forward, I could try to come up with a PR.
