### ISSUE TITLE
nb.deferred_type for jitclass does not work with any built-in method

### ISSUE THREAD

**Issue by bohan-gsm** [numba/numba#4460]
### nb.defered_type does not work with special method __getitem__
`next_type = nb.deferred_type()
@nb.jitclass(spec=[
    ('next', next_type),
])
class Node(object):
    def __init__(self):
        self.next = [self]
    
    def get_next(self):
        return self.next[0]

next_type.define(nb.types.List(Node.class_type.instance_type))

node = Node()
node.next[0]  # OK

node.get_next()`  # Error

`
TypingError                               Traceback (most recent call last)
<ipython-input-53-244b6721f5e8> in <module>
----> 1 NIL.get_next()

D:\ProgramData\Anaconda3\lib\site-packages\numba\jitclass\boxing.py in wrapper(*args, **kwargs)
     60     @wraps(func)
     61     def wrapper(*args, **kwargs):
---> 62         return method(*args, **kwargs)
     63 
     64     return wrapper

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375 
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

D:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344 
    345         argtypes = []

D:\ProgramData\Anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function getitem>) with argument(s) of type(s): (none, Literal[int](0))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of intrinsic-call at <ipython-input-51-b3677d56155c> (17)
[2] During: typing of static-get-item at <ipython-input-51-b3677d56155c> (17)

File "<ipython-input-51-b3677d56155c>", line 17:
    def get_next(self):
        <source elided>
        l = self.next.extend([self for i in range(0)])
        return l[0]
        ^

[1] During: resolving callee type: BoundFunction((<class 'numba.types.misc.ClassInstanceType'>, 'get_next') for instance.jitclass.Node#242f82b86a0<value:float64,next:DeferredType#2486654699224,width:list(int64)>)
[2] During: typing of call at <string> (3)

[3] During: resolving callee type: BoundFunction((<class 'numba.types.misc.ClassInstanceType'>, 'get_next') for instance.jitclass.Node#242f82b86a0<value:float64,next:DeferredType#2486654699224,width:list(int64)>)
[4] During: typing of call at <string> (3)

File "<string>", line 3:
<source missing, REPL/exec in use?>

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
`

**Comment by bohan-gsm** [comment]
```
import numba as nb

next_type = nb.deferred_type()
@nb.jitclass(spec=[
('next', next_type),
])
class Node(object):
    def init(self):
    self.next = [self]

    def get_next(self):
        return self.next[0]

    def get_next_copy(self):
        next_copy = self.next.copy()
        return next_copy[0]

next_type.define(nb.types.List(Node.class_type.instance_type))

node = Node()
node.next[0]  # OK
nodes.get_next_copy()  # OK

node.get_next()` # Error
```

**Comment by bohan-gsm** [comment]
deferred type does not support any built-in method

**Comment by stuartarchibald** [comment]
RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax).

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce, I'm not sure that this pattern is accepted by jitclass (yet!), someone will take a look.

**Comment by bohan-gsm** [comment]
Thanks so much!
I want to write a skipList. This requires a list of Node.
