### ISSUE TITLE
Issue using differently shaped NumPy array

### ISSUE THREAD

**Issue by esc** [numba/numba#4469]
From the mailinglist:

> I am writing a 2D physics solver with Python/Numba and ran into a problem with
> Numba. Maybe someone can help me find a work around.
> 
> The problem is the following; I am trying to pass a list of numpy structured
> array (same data type) but with different sizes to a @numba.njit function.
> Numba complains about heterogeneous list (because the numpy structured array
> have different sizes).
> 
> If I replace the list of numpy structured array with a tuple containing numpy
> structure array, Numba compiles the function but error at execution.
> 
> In C, I would pass a list of pointers and it would not be an issue.
> I am wondering if it is an issue or a feature not yet implemented.

Reproducer is:

```python
"""
@author: Vincent Bonnet
@description : Experimentations with Numba
"""

import numba
import numpy as np

def allocate_particles_as_sof(num_particles):
    '''
    Allocate particle data as a structure of array (sof)
    '''
    array_dtype = []
    for name in ['x', 'v', 'f']:
        array_dtype.append((name, np.float32, (num_particles, 2)))

    particle_data = np.zeros(1, dtype=np.dtype(array_dtype))
    return particle_data

@numba.njit
def print_first_particle_system(array_data):
    '''
    '''
    indices = [0, 1, 2] # silly but trigger issue
    print(array_data[indices[0]][0]['x'])

# WORKS - only because array have same size
particle_data0 = allocate_particles_as_sof(10)
particle_data1 = allocate_particles_as_sof(10)
my_array = [particle_data0, particle_data1]
print_first_particle_system(my_array)

# DOESN'T WORK - array do not have same size
# ERROR 1 - can't unbox heterogeneous list
#particle_data0 = allocate_particles_as_sof(10)
#particle_data1 = allocate_particles_as_sof(15)
#my_array = [particle_data0, particle_data1]
#print_first_particle_system(my_array)

# DOESN'T WORK - array do not have same size
# ERROR 2 - Invalid use of Function(<built-in function getitem>)
#particle_data0 = allocate_particles_as_sof(10)
#particle_data1 = allocate_particles_as_sof(15)
#my_array = [particle_data0, particle_data1]
#print_first_particle_system(tuple(my_array))
```

**Comment by esc** [comment]
It might also be worth looking at the following package, which may do exactly what is wanted:

https://github.com/scikit-hep/awkward-array

For reference, I have tried to use the new typed list to solve this issue:

```python
# TRYING TO USE TYPED LIST
particle_data0 = allocate_particles_as_sof(10)
particle_data1 = allocate_particles_as_sof(15)
tl = numba.typed.List()
tl.append(particle_data0)
tl.append(particle_data1)
print_first_particle_system(tl)
```

But that resulted in the following lowering error:

```
💥 zsh» python foo20.py
/Users/vhaenel/git/numba/numba/ir_utils.py:1966: NumbaPendingDeprecationWarning:
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'array_data' of function 'print_first_particle_system'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "foo20.py", line 23:
@numba.njit
def print_first_particle_system(array_data):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/errors.py", line 668, in new_error_context
    yield
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 461, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 921, in lower_expr
    res = self.lower_call(resty, expr)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 713, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 882, in _lower_call_normal
    fnty, signature, expr.args, expr.vararg, expr.kws,
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 657, in fold_call_args
    stararg_handler)
  File "/Users/vhaenel/git/numba/numba/typing/templates.py", line 173, in fold_arguments
    ba.arguments[name] = normal_handler(i, param, ba.arguments[name])
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 640, in normal_handler
    return self._cast_var(var, signature.args[index])
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 619, in _cast_var
    return self.context.cast(self.builder, val, varty, ty)
  File "/Users/vhaenel/git/numba/numba/targets/base.py", line 692, in cast
    return impl(self, builder, fromty, toty, val)
  File "/Users/vhaenel/git/numba/numba/targets/arrayobj.py", line 4798, in array_to_array
    assert fromty.mutable != toty.mutable or toty.layout == 'A'
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 147, in propagate
    constraint(typeinfer)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 462, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 481, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 1329, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 199, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/context.py", line 251, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/Users/vhaenel/git/numba/numba/types/functions.py", line 214, in get_call_type
    out = template.apply(args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/templates.py", line 225, in apply
    sig = generic(args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/templates.py", line 729, in generic
    sig = self._resolve_impl_sig(typ, attr, args, kws)
  File "/Users/vhaenel/git/numba/numba/typing/templates.py", line 682, in _resolve_impl_sig
    sig = disp_type.get_call_type(self.context, sig_args, sig_kws)
  File "/Users/vhaenel/git/numba/numba/types/functions.py", line 271, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 300, in get_call_template
    self.compile(tuple(args))
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 742, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 976, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 391, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 907, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 894, in _compile_core
    res = pm.run(self.status)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 267, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 258, in run
    stage()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 766, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 705, in _backend
    lowered = lowerfn()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 692, in backend_nopython_mode
    self.metadata)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 1147, in native_lowering_stage
    lower.lower()
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 220, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 245, in lower_function_body
    self.lower_block(block)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/Users/vhaenel/miniconda3/envs/numba/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/vhaenel/git/numba/numba/errors.py", line 676, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/vhaenel/git/numba/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
  File "/Users/vhaenel/git/numba/numba/errors.py", line 668, in new_error_context
    yield
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 461, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 921, in lower_expr
    res = self.lower_call(resty, expr)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 713, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 882, in _lower_call_normal
    fnty, signature, expr.args, expr.vararg, expr.kws,
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 657, in fold_call_args
    stararg_handler)
  File "/Users/vhaenel/git/numba/numba/typing/templates.py", line 173, in fold_arguments
    ba.arguments[name] = normal_handler(i, param, ba.arguments[name])
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 640, in normal_handler
    return self._cast_var(var, signature.args[index])
  File "/Users/vhaenel/git/numba/numba/lowering.py", line 619, in _cast_var
    return self.context.cast(self.builder, val, varty, ty)
  File "/Users/vhaenel/git/numba/numba/targets/base.py", line 692, in cast
    return impl(self, builder, fromty, toty, val)
  File "/Users/vhaenel/git/numba/numba/targets/arrayobj.py", line 4798, in array_to_array
    assert fromty.mutable != toty.mutable or toty.layout == 'A'
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "numba/listobject.py", line 432:
    def impl(l, item):
        casteditem = _cast(item, itemty)
        ^

[1] During: lowering "$0.4 = call $0.1(item, $0.3, func=$0.1, args=[Var(item, /Users/vhaenel/git/numba/numba/listobject.py (432)), Var($0.3, /Users/vhaenel/git/numba/numba/listobject.py (432))], kws=(), vararg=None)" at /Users/vhaenel/git/numba/numba/listobject.py (432)
[2] During: resolving callee type: BoundFunction((<class 'numba.types.containers.ListType'>, 'append') for ListType[unaligned array(Record(x[type=nestedarray(float32, (10, 2));offset=0],v[type=nestedarray(float32, (10, 2));offset=80],f[type=nestedarray(float32, (10, 2));offset=160];240;False), 1d, C)])
[3] During: typing of call at /Users/vhaenel/git/numba/numba/typed/typedlist.py (39)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foo20.py", line 55, in <module>
    tl.append(particle_data1)
  File "/Users/vhaenel/git/numba/numba/typed/typedlist.py", line 223, in append
    _append(self, item)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 376, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 341, in error_rewrite
    raise e
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 742, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 80, in compile
    raise retval
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 976, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 391, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 907, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 894, in _compile_core
    res = pm.run(self.status)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 267, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 258, in run
    stage()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 517, in stage_nopython_frontend
    self.locals)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 1128, in type_inference_stage
    infer.propagate()
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 928, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x120168f98>.
Failed in nopython mode pipeline (step: nopython mode backend)


File "numba/listobject.py", line 432:
    def impl(l, item):
        casteditem = _cast(item, itemty)
        ^

[1] During: lowering "$0.4 = call $0.1(item, $0.3, func=$0.1, args=[Var(item, /Users/vhaenel/git/numba/numba/listobject.py (432)), Var($0.3, /Users/vhaenel/git/numba/numba/listobject.py (432))], kws=(), vararg=None)" at /Users/vhaenel/git/numba/numba/listobject.py (432)
[2] During: resolving callee type: BoundFunction((<class 'numba.types.containers.ListType'>, 'append') for ListType[unaligned array(Record(x[type=nestedarray(float32, (10, 2));offset=0],v[type=nestedarray(float32, (10, 2));offset=80],f[type=nestedarray(float32, (10, 2));offset=160];240;False), 1d, C)])
[3] During: typing of call at /Users/vhaenel/git/numba/numba/typed/typedlist.py (39)

Enable logging at debug level for details.

File "numba/typed/typedlist.py", line 39:
def _append(l, item):
    l.append(item)
    ^
```

**Comment by stuartarchibald** [comment]
Does this help?
```python
import numba
import numpy as np
from collections import namedtuple

ty = namedtuple('ty', 'x v f')

def gen(npart, init_val):
    arr = np.ones((npart, 2)) * init_val
    return ty(arr, arr, arr)

array_data = [gen(2, 2), gen(3, 3), gen(4, 4)]

@numba.njit
def print_first_particle_system2(array_data):
    for thing in array_data:
        print(thing.x)
        print(thing.v)
        print(thing.f)

print_first_particle_system2(array_data)
```
------------------
The `getitem` issue above is because this:
```python
    indices = [0, 1, 2] # silly but trigger issue
    print(array_data[indices[0]][0]['x'])
```
leads to a standard `getitem` node being generated in the IR and it can't be resolved into the structured array, whereas
```python
    print(array_data[0][0]['x'])
```
will work fine as it is "static", i.e.  a const value look up so it'll end up as a `staticgetitem` node in the IR which will be resolved into the structured array.
