### ISSUE TITLE
Array order check is too strict

### ISSUE THREAD

**Issue by lzlarryli** [numba/numba#4471]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Numpy identifies `1 x n` or `n x 1` matrices as both C- and F-contiguous. Such matrices fail to pass numba's contiguity check as F-contiguous.

Code example
```python
>>> from numba import njit                                                      
>>> import numpy as np                                                          
>>>                                                                             
>>> # This definition generates a warning                                       
>>> @njit('f8[:, :], f8[:]') 
... def prod(A, x): 
...     return A.T @ x 
...                                                                             
<ipython-input-9-ed5020607679>:3: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (array(float64, 2d, A), array(float64, 1d, A))
  return A.T @ x
/Users/lizli/anaconda3/lib/python3.7/site-packages/numba/typing/npydecl.py:967: NumbaPerformanceWarning: '@' is faster on contiguous arrays, called on (array(float64, 2d, A), array(float64, 1d, A))
  warnings.warn(NumbaPerformanceWarning(msg))
>>> # OK, I will be more specific              
>>> @njit('f8[::1, :], f8[::1]') 
... def prod(A, x): 
...     return A.T @ x 
...                                                                             
>>> # All good                                                                  
>>> prod(np.zeros((2, 2), order='F'), np.zeros(2))                              
array([0., 0.])
>>> # But there are cases where the matrix can be both C and F                  
>>> A = np.zeros((2, 1), order='F')                                             
>>> print(A.flags)                                                              
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
>>> prod(A, np.zeros(2))                                                        
Traceback (most recent call last):
  File "<ipython-input-18-e21ff4da4503>", line 1, in <module>
    prod(A, np.zeros(2))
  File "/Users/lizli/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 466, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) array(float64, 2d, C), array(float64, 1d, C)

>>>              
```

Further information:
* Python 3.7.3
* Numpy 1.16.4
* Numba 0.44.1

**Comment by esc** [comment]
@lzlarryli thanks for reporting this! I have just been able to reproduce this and can verify that is probably a bug in Numba.

**Comment by stuartarchibald** [comment]
Code to reproduce:
```python
from numba import njit
import numpy as np

@njit('f8[:, :], f8[:]')
def prod(A, x):
    return A.T @ x

@njit('f8[::1, :], f8[::1]')
def prod(A, x): 
    return A.T @ x

prod(np.zeros((2, 2), order='F'), np.zeros(2))

A = np.zeros((2, 1), order='F')
print(A.flags)
prod(A, np.zeros(2))
```

**Comment by stuartarchibald** [comment]
I've a feeling that this is a duplicate as I'm sure I've looked at this before. Fundamentally the issue is that the dispatcher checks the order of the array in the order of `'C', 'F'` and if neither it assigns `'A'`. I'm not sure how easy it would be to accommodate the above situation as I anticipate the above logic is implicitly assumed in a number of places in the code base.

**Comment by astrojuanlu** [comment]
Possibly related? #4585, #6998
