### ISSUE TITLE
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend) array.3

### ISSUE THREAD

**Issue by Koushikphy** [numba/numba#4488]
Here's the simplified code that produces the error,
```python
import numpy as np
from numba import jit
geomList  = np.stack( np.mgrid[0.1:5.0:50j,0:180:181j], axis=2).reshape(-1,2)


@jit
def func():
    dist = np.array([geomList[30] for i in range(30)])
    return dist

print func()
```
produces this error
```
Traceback (most recent call last):
  File "/home/koushik/CODES/numba_error.py", line 12, in <module>
    print func()
  File "/home/koushik/.local/lib/python2.7/site-packages/numba/dispatcher.py", line 369, in _compile_for_args
    raise e
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
array.3

File "numba_error.py", line 8:
def func():
    dist = np.array([geomList[30] for i in range(30)])
    ^

[1] During: lowering "$38.5 = array.3" at /home/koushik/CODES/numba_error.py (8)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
```
is this a numba error or am I doing something wrong?

**Comment by cakedev0** [comment]
I don't get the same error as you.
Acutally, when I just use `@jit`, I don't get any error but I get a warning.
When I use `@jit(nopython=True)` I get an error.

It seems that creating a `np.array` from list of 1d array (or from a list of list) doesn't work.
You can use this alternative implementation : 
```python
import numpy as np
from numba import jit
geomList = np.stack( np.mgrid[0.1:5.0:50j,0:180:181j], axis=2).reshape(-1,2)

@jit(nopython=True)
def func():
    dist = np.empty((30, 2))
    for i in range(30):
        dist[i, :] = geomList[30, :]
    return dist

print(func())
```
It works for me (python 3.6, numba 0.45) 

It seems that the numba implemenation of `np.array(list)` creates an empty 1d array and then fills it with the element of the list. In the case here, it does not notice that the given list represents a 2d array and so fails to fill the array. I think this because I get this error : 
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (array(undefined, 1d, C), int64, readonly array(float64, 1d, C))
```

I guess that it could be solved by implementing a kind of "dimension inference".

**Comment by sklam** [comment]
I think `_inline_arraycall()` did not consider the case that the list can contain other arrays:

Alternative reproducer:

```python
import numpy as np
from numba import njit


@njit
def func():
    inner = np.array([1, 2])
    dist = [inner for i in range(10)]
    return np.array(dist)


r = func()
print(r)

```

**Comment by Koushikphy** [comment]
If its all about a multidimensional array then why the following gives me the same error
```python
geomList = np.linspace(0,50)
f = lambda x: x**2
@jit
def func():
        dist = np.array([f(i) for i in geomList])
        return dist
```
Its just an 1D array. But if I remove the function and use direct approach then, it runs okay
```python
@jit
def func():
        dist = np.array([i**2 for i in geomList])
        return dist
```

**Comment by cakedev0** [comment]
Your exemple doesn't work because you didn't jitted the `f` function. This works : 

```python
geomList = np.linspace(0,50)

f = jit(lambda x : x**2)

@jit
def func():
        dist = np.array([f(i) for i in geomList])
        return dist
    
func()
```

**Comment by stuartarchibald** [comment]
As of mainline for Numba 0.55, the OP does not reproduce, but there's still an issue in `nopython` mode.

**Comment by gmarkall** [comment]
MWR in nopython mode of OP (Python 3 compatible :-)):

```python
import numpy as np
from numba import njit

geomList  = np.stack( np.mgrid[0.1:5.0:50j,0:180:181j], axis=2).reshape(-1,2)

@njit
def func():
    dist = np.array([geomList[30] for i in range(30)])
    return dist

print(func())
```

and corresponding error:

```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(array(undefined, 1d, C), int64, readonly array(float64, 1d, C))
 
There are 16 candidate implementations:
  - Of which 16 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(array(undefined, 1d, C), int64, readonly array(float64, 1d, C))':
   No match.

During: typing of setitem at /home/gmarkall/numbadev/issues/4488/repro.py (9)

File "repro.py", line 9:
def func():
    dist = np.array([geomList[30] for i in range(30)])
    ^
```
