### ISSUE TITLE
Jitclass method call fails with keyword argument

### ISSUE THREAD

**Issue by luk-f-a** [numba/numba#4495]
import numba
Hi, currently jitclasses allow methods to be declared with keyword arguments, but unlike njit functions, it is not possible to call these methods with keyword arguments. The problem ocurs with and without default values
```python
@numba.jitclass(spec=[])
class norm_gen():
    
    def __init__(self):
        pass
    
    def foo(self, loc=0, size=1):
        return size
    
    def bar(self, loc, size):
        return size
    
norm = norm_gen()
#all these fail
norm.foo(loc=0, size=10)
norm.foo(size=10)
norm.bar(loc=0, size=10)
#this works
norm.foo(0, 10)
```

**Comment by stuartarchibald** [comment]
Thanks, this is a bug/lack of implementation. Root cause is that methods are generated via this template:
https://github.com/numba/numba/blob/60d2bddd0a9ddf84cf900a70e4b7e17bcbe5dc87/numba/jitclass/boxing.py#L28-L31

from this call:
https://github.com/numba/numba/blob/60d2bddd0a9ddf84cf900a70e4b7e17bcbe5dc87/numba/jitclass/boxing.py#L50-L64

docstring notes that `the wrapper will only accept positional arguments. `

**Comment by luk-f-a** [comment]
@stuartarchibald , is it correct to assume that a solution would be harder than just
```

_method_code_template = """ 
 def method(__numba_self_, *args, **kwargs): 
     return __numba_self_.{method}(*args, **kwargs) 
 """ 
```

I would be happy to contribute that PR if it were that easy. :smile:

**Comment by stuartarchibald** [comment]
Unfortunately, I think it'll be a bit harder than that, not least because `CALL_FUNCTION_EX` (`**kwargs`) is not supported.

**Comment by DreamBoatOve** [comment]
numba can not support dict data type in jitclass, so i changed my code(a class).  
GPU only work on function, so i give up the hope to run my class on GPU
Now, it can only support positional arguments, i have to change it again...
Come on, guys!!!

**Comment by DreamBoatOve** [comment]
code:
import numpy as np

from numba import jitclass
from collections import OrderedDict
from numba import float64
# ------------------ jitclass multidimensional array test ------------------
spec = OrderedDict()
spec['arr_1d'] = float64[:]
spec['arr_2d'] = float64[:,:]
spec['arr_3d'] = float64[:,:,:]
spec['num_float'] = float64

@jitclass(spec)
class arr_test(object):
    def __init__(self):
        # self.arr_1d = np.zeros(3), error example, have to add data type
        self.arr_1d = np.zeros(3, dtype=np.float64)
        self.arr_2d = np.random.randn(3,5) 
        self.arr_3d = np.random.randn(3, 5, 2)
        self.num_float = np.random.randn()

    def add(self, x, y, z=1, q=2, w=0.1, e=np.array([1])):
        return x+y+z+q+w

if __name__ == '__main__':
    at = arr_test()
    print(at.arr_1d)
    print(at.arr_2d)
    print(at.arr_3d)
    print(at.num_float)

    print(at.add(1,2))

output:
6.1

Process finished with exit code 0
-----------------------------------------------------
it seems to work fine to me now

**Comment by DreamBoatOve** [comment]
what happens to the positional arguments?

**Comment by JustGlowing** [comment]
Is there any update on this?

**Comment by esc** [comment]
@JustGlowing thanks for asking about this, there is no update at this time.

**Comment by xgao1023** [comment]
Although flexible (dynamic **kwargs would be hard to support), I think it could be easier to just support normal named (positional) parameters expressed as keyword arguments

So in the wrapper, we could "restore" the call to using position arguments, this requires to check the parameter list of the function so it will make the call slightly slower.

I will be happy to provide a PR if this idea make sense

In _numba/numba/jitclass/boxing.py_

    def _generate_method(name, func):
        """
        Generate a wrapper for calling a method.  Note the wrapper will only
        accept positional arguments.
        """
        source = _method_code_template.format(method=name)
        glbls = {}
        exec(source, glbls)
        method = njit(glbls['method'])
        signature = inspect.signature(func)
        parameters = list(signature.parameters.values())
    
        @wraps(func)
        def wrapper(*args, **kwargs):
            if len(kwargs) != 0:
                real_args = [
                    args[i] if i < len(args)  # Use positional arg if provided
                    else (
                        kwargs[p.name] if p.name in kwargs  # use kwargs if provided
                        else p.default  # Use default value (must exist if not provided explictly)
                    )
                    for i, p in enumerate(parameters)
                ]
    
                args = real_args
                kwargs = {}
    
            return method(*args, **kwargs)
    
        return wrapper

**Comment by jazzp0** [comment]
@stuartarchibald Is it possible that this can go for PR? It seems to work

**Comment by stuartarchibald** [comment]
@jazzp0 I'm not quite sure to what you are referring, but PRs for open bugs/feature requests are welcomed. Thanks!

**Comment by jazzp0** [comment]
@stuartarchibald I am referring to the solution that @xgao1023 mentioned above.
`def _generate_method(name, func):
    """
    Generate a wrapper for calling a method.  Note the wrapper will only
    accept positional arguments.
    """
    source = _method_code_template.format(method=name)
    glbls = {}
    exec(source, glbls)
    method = njit(glbls['method'])
    signature = inspect.signature(func)
    parameters = list(signature.parameters.values())

    @wraps(func)
    def wrapper(*args, **kwargs):
        if len(kwargs) != 0:
            real_args = [
                args[i] if i < len(args)  # Use positional arg if provided
                else (
                    kwargs[p.name] if p.name in kwargs  # use kwargs if provided
                    else p.default  # Use default value (must exist if not provided explictly)
                )
                for i, p in enumerate(parameters)
            ]

            args = real_args
            kwargs = {}

        return method(*args, **kwargs)

    return wrapper`

I implemented this and it seems to work. As it is his idea, maybe better that he does PR? Otherwise I might be able to do it as well.

**Comment by shaunc** [comment]
@xgao1023's solution would be quite useful to express code meaning clearly and maintain functions with long argument lists.

**Comment by milannnnn** [comment]
It would probably be a good idea to include this on the [jitclass/limitations documentation page](https://numba.readthedocs.io/en/stable/user/jitclass.html#limitations) (at least until the issue is solved).

I've had an issue with a keyword argument within one of the child classes, and I've spent quite some time trying to debug the issue.

```
from numba.experimental import jitclass

@jitclass
class HelperClass:
    _a: float    
    
    def __init__(self, a: float=1.0):
        self._a = a
    
    @property
    def a(self) -> float:
        return self._a
    
@jitclass
class MainClass:
    _helper: HelperClass
    
    def __init__(self):
        self._helper = HelperClass()
        
    @property
    def helper_a(self) -> float:
        return self._helper.a
        

# This works
helper = HelperClass()
print(helper.a)
# But this one fails
main = MainClass()
print(main.helper_a)
```

Output:
```
TypingError                               Traceback (most recent call last)
Input In [34], in <cell line: 30>()
     28 print(helper.a)
     29 # But this one fails
---> 30 main = MainClass()
     31 print(main.helper_a)

File ~\AppData\Roaming\Python\Python310\site-packages\numba\experimental\jitclass\base.py:124, in JitClassType.__call__(cls, *args, **kwargs)
    122 bind = cls._ctor_sig.bind(None, *args, **kwargs)
    123 bind.apply_defaults()
--> 124 return cls._ctor(*bind.args[1:], **bind.kwargs)

File ~\AppData\Roaming\Python\Python310\site-packages\numba\core\dispatcher.py:468, in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 468     error_rewrite(e, 'typing')
    469 except errors.UnsupportedError as e:
    470     # Something unsupported is present in the user code, add help info
    471     error_rewrite(e, 'unsupported_error')

File ~\AppData\Roaming\Python\Python310\site-packages\numba\core\dispatcher.py:409, in _DispatcherBase._compile_for_args.<locals>.error_rewrite(e, issue_type)
    407     raise e
    408 else:
--> 409     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x000002AD3A873490>.
Failed in nopython mode pipeline (step: native lowering)
invalid number of args: expected 2, got 1

File "..\..\..\Users\milan\AppData\Local\Temp\ipykernel_40684\2253113363.py", line 19:
<source missing, REPL/exec in use?>

During: lowering "$4call_function.1 = call $2load_global.0(func=$2load_global.0, args=[], kws=(), vararg=None, varkwarg=None, target=None)" at C:\Users\milan\AppData\Local\Temp\ipykernel_40684\2253113363.py (19)
During: resolving callee type: jitclass.MainClass#2ad3a3c3250<_helper:instance.jitclass.HelperClass#2ad3a3c3940<_a:float64>>
During: typing of call at <string> (3)

Enable logging at debug level for details.

File "<string>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by d-magiera** [comment]
Hi, is there still no update on this?

**Comment by esc** [comment]
> Hi, is there still not update on this?

no
