### ISSUE TITLE
Trouble converting between typed list and array with string values

### ISSUE THREAD

**Issue by ivirshup** [numba/numba#4505]
Numba doesn't currently allow converting from a typed list of strings to an array of strings or from and array of strings to a typed list of strings. I think allowing that would be useful.

Here's the error from converting an array of unicode to a typed list:

```python
import numba
import numpy as np

@numba.njit
def foo(x):
    return list(x)

foo(np.array(list("abc")))
```

The full resulting traceback is about 500 lines, so I've put it [in a gist](https://gist.github.com/ivirshup/50c966dd031a89b9bde055403aadb09e), but here's the last bit:

```python

LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)
<numba.datamodel.models.UnicodeCharSeq object at 0x12121cef0>

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/listobj.py", line 464:
    def list_impl(iterable):
        res = []
        ^

[1] During: lowering "$0.1 = build_list(items=[])" at /usr/local/lib/python3.7/site-packages/numba/targets/listobj.py (464)
[2] During: lowering "$0.3 = call $0.1(x, func=$0.1, args=[Var(x, <ipython-input-1-9ba5acf21b48> (6))], kws=(), vararg=None)" at <ipython-input-1-9ba5acf21b48> (6)
```

For converting a list to an array:

```python
@numba.njit 
def baz(x): 
    return np.array(x)

baz(list("abc"))
```

<details>
<summary> Traceback </summary>

```python
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-17-0e3e46e565a7> in <module>
----> 1 baz(list("abc"))

/usr/local/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375 
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

/usr/local/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344 
    345         argtypes = []

/usr/local/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function array>) with argument(s) of type(s): (reflected list(unicode_type))
 * parameterized
In definition 0:
    NotImplementedError: unicode_type cannot be represented as a Numpy dtype
    raised from /usr/local/lib/python3.7/site-packages/numba/numpy_support.py:150
In definition 1:
    NotImplementedError: unicode_type cannot be represented as a Numpy dtype
    raised from /usr/local/lib/python3.7/site-packages/numba/numpy_support.py:150
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function array>)
[2] During: typing of call at <ipython-input-16-1850252d5042> (3)


File "<ipython-input-16-1850252d5042>", line 3:
def baz(x):
    return np.array(x)
    ^

```

</details>

I think this is related to not being able to use the elements of a string np.array as keys in a typed dict.

```python
@numba.njit
def bar(x):
    d = {}
    for k, v in zip(x, np.arange(len(x))):
        d[k] = v
    return d

bar(np.array(list("abc")))
```

<details>
<summary> Traceback </summary>

```python
TypingError                               Traceback (most recent call last)
<ipython-input-13-610c1321b729> in <module>
----> 1 bar(np.array(list("abc")))

/usr/local/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    374                 e.patch_message(msg)
    375 
--> 376             error_rewrite(e, 'typing')
    377         except errors.UnsupportedError as e:
    378             # Something unsupported is present in the user code, add help info

/usr/local/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    341                 raise e
    342             else:
--> 343                 reraise(type(e), e, None)
    344 
    345         argtypes = []

/usr/local/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (DictType[undefined,undefined], [unichr x 1], int64)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function hash>) with argument(s) of type(s): ([unichr x 1])
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute '__hash__' of type [unichr x 1]

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

[1] During: typing of get attribute at /usr/local/lib/python3.7/site-packages/numba/targets/hashing.py (64)

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

    raised from /usr/local/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute '__hash__' of type [unichr x 1]

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

[1] During: typing of get attribute at /usr/local/lib/python3.7/site-packages/numba/targets/hashing.py (64)

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

    raised from /usr/local/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function hash>)
[2] During: typing of call at /usr/local/lib/python3.7/site-packages/numba/dictobject.py (677)


File "../../../../usr/local/lib/python3.7/site-packages/numba/dictobject.py", line 677:
    def impl(d, key, value):
        <source elided>
        castedval = _cast(value, valty)
        status = _dict_insert(d, castedkey, hash(castedkey), castedval)
        ^

    raised from /usr/local/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 3:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function hash>) with argument(s) of type(s): ([unichr x 1])
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute '__hash__' of type [unichr x 1]

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

[1] During: typing of get attribute at /usr/local/lib/python3.7/site-packages/numba/targets/hashing.py (64)

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

    raised from /usr/local/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute '__hash__' of type [unichr x 1]

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

[1] During: typing of get attribute at /usr/local/lib/python3.7/site-packages/numba/targets/hashing.py (64)

File "../../../../usr/local/lib/python3.7/site-packages/numba/targets/hashing.py", line 64:
    def impl(obj):
        return obj.__hash__()
        ^

    raised from /usr/local/lib/python3.7/site-packages/numba/typeinfer.py:927
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function hash>)
[2] During: typing of call at /usr/local/lib/python3.7/site-packages/numba/dictobject.py (677)


File "../../../../usr/local/lib/python3.7/site-packages/numba/dictobject.py", line 677:
    def impl(d, key, value):
        <source elided>
        castedval = _cast(value, valty)
        status = _dict_insert(d, castedkey, hash(castedkey), castedval)
        ^

    raised from /usr/local/lib/python3.7/site-packages/numba/typeinfer.py:927
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at <ipython-input-8-6e07a0e29476> (5)

File "<ipython-input-8-6e07a0e29476>", line 5:
def bar(x):
    <source elided>
    for k, v in zip(x, np.arange(len(x))):
        d[k] = v

```

</details>

**Comment by stuartarchibald** [comment]
Thanks for the report. https://github.com/numba/numba/pull/4425 fixes the first example (will be in Numba 0.46). I think the second fails because the list is typed as a list of `unicode_type` and there's no way to represent that as a NumPy `dtype`. The third example also now works on master due to #4425.

**Comment by sklam** [comment]
With #4425, unicode array works when it is provided as argument.  There is still no way to convert a `List[unicode]` into a numpy array in `njit`.  

There is a workaround but it is not really usable:

```python

In [12]: @njit
    ...: def foo():
    ...:     lst = List()
    ...:     lst.append("a")
    ...:     lst.append("bcd")
    ...:     a = np.zeros(2, dtype=np.dtype("<U3"))  # hardcoded unicode max-length
    ...:     a[0] = lst[0]
    ...:     a[1] = lst[1]
    ...:     return a
```

**Comment by sklam** [comment]
At the very least, we should support `np.asarray(list_of_str, dtype=np.dtype("<U12"))`

**Comment by esc** [comment]
I hit this issue also with https://github.com/numba/numba/pull/5231

**Comment by stuartarchibald** [comment]
As of 0.49 this works:
```python
import numba
import numpy as np

@numba.njit
def foo(x):
    return list(x)

print(foo(np.array(list("abc"))))
```

**Comment by stuartarchibald** [comment]
The only case not working on mainline for 0.55 is:
```python
import numba
import numpy as np

@numba.njit
def baz(x):
    return np.array(x)

baz(list("abc"))
```
fails with:
```
NumbaNotImplementedError: unicode_type cannot be represented as a NumPy dtype
```

**Comment by JacobHayes** [comment]
This would be useful for me too - I'm wanting to write some code like:
```
bases = np.array(["A", "AT", "T"])  # [unichr x 2] in numba
max_length = max([len(b) for b in bases])  # computed elsewhere
np.array([b[: max_length - 1] for b in bases], dtype="U")
```
. unichr doesn't support slicing (only getitem - https://github.com/numba/numba/issues/5802#issuecomment-641168227), but converting `str(b)` will fix slicing. However, then I can no longer create the `np.array` (which is what I pass to another function).
