### ISSUE TITLE
numba.errors.TypingError: Failed in nopython mode pipeline

### ISSUE THREAD

**Issue by laetella** [numba/numba#4527]
```
D:\Python\Python35\lib\site-packages\sklearn\utils\validation.py:558: FutureWarn
ing: Beginning in version 0.22, arrays of bytes/strings will be converted to dec
imal numbers if dtype='numeric'. It is recommended that you convert the array to
 a float dtype before using it in scikit-learn, for example by using your_array
= your_array.astype(np.float64).
  FutureWarning)
Traceback (most recent call last):
  File "test.py", line 57, in <module>
    mogaal.fit(point_set)
  File "D:\Python\Python35\lib\site-packages\pyod\models\abod.py", line 165, in
fit
    self._fit_fast()
  File "D:\Python\Python35\lib\site-packages\pyod\models\abod.py", line 212, in
_fit_fast
    X_ind)
  File "D:\Python\Python35\lib\site-packages\pyod\models\abod.py", line 86, in _
calculate_wocs
    wcos_list.append(_wcos(curr_pt, a, b))
  File "D:\Python\Python35\lib\site-packages\numba\dispatcher.py", line 376, in
_compile_for_args
    error_rewrite(e, 'typing')
  File "D:\Python\Python35\lib\site-packages\numba\dispatcher.py", line 343, in
error_rewrite
    reraise(type(e), e, None)
  File "D:\Python\Python35\lib\site-packages\numba\six.py", line 658, in reraise

    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython front
end)
Invalid use of Function(<built-in function sub>) with argument(s) of type(s): (a
rray([char x 1], 1d, C), array([char x 1], 1d, C))
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupporte
d by the named function.
[1] During: typing of intrinsic-call at D:\Python\Python35\lib\site-packages\pyo
d\models\abod.py (45)

File "..\..\Python\Python35\lib\site-packages\pyod\models\abod.py", line 45:
def _wcos(curr_pt, a, b):  # pragma: no cover
    <source elided>

    a_curr = a - curr_pt
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-
compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by esc** [comment]
@laetella thanks for submitting this, we appreciate your efforts to improve Numba. I will now reformat the code you posted to make it more legible. When submitting issues in the future, triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax). Also, could you please post the code that you ran that lead to the above exception, thanks!

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
