### ISSUE TITLE
numba doesn't raise exception for broadcast error with += 

### ISSUE THREAD

**Issue by asmeurer** [numba/numba#4542]
Originally from https://github.com/numba/numba/pull/4432#issuecomment-527571792

```py
>>> def test1(a, b):
...     a += b
>>> def test2(a, b):
...     return a + b
>>> @njit
... def test1_jit(a, b):
...     a += b
>>> @njit
... def test2_jit(a, b):
...     return a + b
>>> test1(np.empty((3, 4)), np.empty((3, 5)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test1
ValueError: operands could not be broadcast together with shapes (3,4) (3,5) (3,4)
>>> test2(np.empty((3, 4)), np.empty((3, 5)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in test2
ValueError: operands could not be broadcast together with shapes (3,4) (3,5)
>>> test1_jit(np.empty((3, 4)), np.empty((3, 5)))
>>> test2_jit(np.empty((3, 4)), np.empty((3, 5)))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: unable to broadcast argument 1 to output array
File "<stdin>", line 3,
```

The issue is `test1_jit`, which should raise an exception.

As an aside, the error line for `test2_jit` is messed up somehow.

**Comment by esc** [comment]
@asmeurer thanks for reporting this. I can reproduce this myself and will now label this as 'bug'.

Also, @stuartarchibald here is the minimal reproducer for your convenience:

```python
import numpy as np
from numba import njit


@njit
def test1(a, b):
    a += b


@njit
def test2(a, b):
    return a + b


c = np.empty((3, 4))
d = np.empty((3, 5))

try:
    test1.py_func(c, d)
except Exception as e:
    print(e)
else:
    print("NO EXCEPTION")

try:
    test2.py_func(c, d)
except Exception as e:
    print(e)
else:
    print("NO EXCEPTION")


try:
    test1(c, d)
except Exception as e:
    print(e)
else:
    print("NO EXCEPTION")


try:
    test2(c, d)
except Exception as e:
    print(e)
else:
    print("NO EXCEPTION")
```

**Comment by stuartarchibald** [comment]
I think that this is a variant of the actual problem which is that an explicitly supplied output array to a ufunc is not checked for suitability (infix operators are rewritten to look like function calls with explicit output):

```python
import numpy as np
from numba import njit

@njit
def test1(a, b, c):
    np.add(a, b, c)

c = np.ones((3, 4))
d = np.ones((3, 4))
f = np.zeros((3, 5))

try:
    test1(c, d, f)
except Exception as e:
    print(e)
else:
    print("NO EXCEPTION")
    print(f)
```
gives:
```
NO EXCEPTION
[[2.00000000e+000 2.00000000e+000 2.00000000e+000 2.00000000e+000
  2.00000000e+000]
 [2.00000000e+000 2.00000000e+000 2.00000000e+000 2.00000000e+000
  2.00000000e+000]
 [2.00000000e+000 2.00000000e+000 2.00000000e+000 2.00000000e+000
  1.38348601e-309]]
```
