### ISSUE TITLE
Parallel execution crash

### ISSUE THREAD

**Issue by crotron** [numba/numba#4633]
Was playing around with seeing if it's possible to append to a list inside a parallel for loop. I tried it and got an error. This only happens when parallel=True.

```
@jit(nopython=True, parallel=True)
def test():
    results = [x for x in range(0)]  # tell numba what type this is
    for i in prange(5):
        results.append(i)
    return results
```

Here is my error log:
```
Traceback (most recent call last):
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/errors.py", line 662, in new_error_context
    yield
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 301, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 482, in lower_assign
    res = self.context.cast(self.builder, val, argty, ty)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/targets/base.py", line 692, in cast
    return impl(self, builder, fromty, toty, val)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/targets/listobj.py", line 1092, in list_to_list
    assert fromty.dtype == toty.dtype
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/[REDACTED]/Applications/pycharm-community-2018.3/helpers/pydev/pydevd.py", line 1741, in <module>
    main()
  File "/home/[REDACTED]/Applications/pycharm-community-2018.3/helpers/pydev/pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/[REDACTED]/Applications/pycharm-community-2018.3/helpers/pydev/pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/[REDACTED]/Applications/pycharm-community-2018.3/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/mnt/Projects/Programming/Python/Personal/[REDACTED]/[REDACTED]", line 22, in <module>
    results = find(low_hp_template, source, threshold=0, limit=1)
  File "/mnt/Projects/Programming/Python/Personal/[REDACTED]/[REDACTED]/[REDACTED]", line 49, in find
    test()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 395, in _compile_for_args
    raise e
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 410, in lower_inst
    func(self, inst)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/npyufunc/parfor.py", line 240, in _lower_parfor_parallel
    bool(alias_map), index_var_typ, parfor.races)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/npyufunc/parfor.py", line 1103, in _create_gufunc_for_parfor_body
    locals)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 1036, in compile_ir
    lifted_from=lifted_from)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 398, in compile_ir
    return self._compile_ir()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 910, in _compile_ir
    return self._compile_core()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/[REDACTED]/miniconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)


File "<string>", line 2:
<source missing, REPL/exec in use?>

[1] During: lowering "_results_24 = arg(1, name=_results_24)" at <string> (2)
[2] During: lowering "id=0[LoopNest(index_variable = parfor_index.18, range = (0, $const20.2, 1))]{53: <ir.Block at /mnt/Projects/Programming/Python/Personal/[REDACTED]/[REDACTED]/[REDACTED] (63)>}Var(parfor_index.18, /mnt/Projects/Programming/Python/Personal/[REDACTED]/[REDACTED]/[REDACTED] (63))" at /mnt/Projects/Programming/Python/Personal/[REDACTED]/[REDACTED]/[REDACTED] (63)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

```
(sorry for the redactions, some of these folders/files have personal information in their names)

**Comment by esc** [comment]
@crotron thank you for reporting this. I can reproduce this no problem. I am not sure, that it is possible to mutate data structures in a parallel context (locking, deadlocks, etc..). Maybe @stuartarchibald or @DrTodd13 know more?

**Comment by stuartarchibald** [comment]
List append is not threadsafe in a parallel context https://github.com/numba/numba/issues/2408. Closing as a duplicate.
