### ISSUE TITLE
Accessing a numpy array from a module using module name prefix fails in nopython mode

### ISSUE THREAD

**Issue by buran21** [numba/numba#4663]
Suppose there is a module `nmod.py`:

```
import numpy as np
narr = np.array([1, 2, 5])
```

Then the following code works just fine in both _object_ and _nopython_ mode:

```
import numpy as np
from numba import jit
from nmod import narr
@jit(nopython=True)
def numba_test():
    return np.sum(narr)
print(numba_test())
```

Output:
`8`

However, accessing `narr `with module name prefix fails in  _nopython_ mode:

```
import numpy as np
from numba import jit
import nmod
@jit(nopython=True)
def numba_test():
    print(np.sum(nmod.narr))
numba_test()
```

Output:
```
Traceback (most recent call last):
  File "C:\Users\User\venv\lib\site-packages\numba\errors.py", line 662, in new_error_context
    yield
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 301, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 459, in lower_assign
    return self.lower_expr(ty, value)
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 1009, in lower_expr
    impl = self.context.get_getattr(ty, expr.attr)
  File "C:\Users\User\venv\lib\site-packages\numba\targets\base.py", line 588, in get_getattr
    llval = self.get_constant(attrty, pyval)
  File "C:\Users\User\venv\lib\site-packages\numba\targets\base.py", line 510, in get_constant
    return self.get_constant_generic(None, ty, val)
  File "C:\Users\User\venv\lib\site-packages\numba\targets\base.py", line 500, in get_constant_generic
    return impl(self, builder, ty, val)
  File "C:\Users\User\venv\lib\site-packages\numba\targets\arrayobj.py", line 2383, in constant_array
    return context.make_constant_array(builder, ty, pyval)
  File "C:\Users\User\venv\lib\site-packages\numba\targets\base.py", line 1015, in make_constant_array
    data = cgutils.global_constant(builder, ".const.array.data", consts)
  File "C:\Users\User\venv\lib\site-packages\numba\cgutils.py", line 876, in global_constant
    module = builder_or_module.module
AttributeError: 'NoneType' object has no attribute 'module'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/User/.../ntest.py", line 9, in <module>
    print(numba_test())
  File "C:\Users\User\venv\lib\site-packages\numba\dispatcher.py", line 395, in _compile_for_args
    raise e
  File "C:\Users\User\venv\lib\site-packages\numba\dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\User\venv\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\User\venv\lib\site-packages\numba\dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\User\venv\lib\site-packages\numba\dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\User\venv\lib\site-packages\numba\dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\User\venv\lib\site-packages\numba\dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\User\venv\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 266, in run
    raise patched_exception
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 257, in run
    stage()
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "C:\Users\User\venv\lib\site-packages\numba\compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "C:\Users\User\venv\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\Users\User\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\User\venv\lib\site-packages\numba\errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\User\venv\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
'NoneType' object has no attribute 'module'

File "ntest.py", line 8:
def numba_test():
    return np.sum(nmod.narr)
    ^

[1] During: lowering "$0.4 = getattr(value=$0.3, attr=narr)" at C:/Users/User/.../ntest.py (8)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

In _object_ mode programs runs with the warning:

```
import numpy as np
from numba import jit
import nmod
@jit
def numba_test():
    return np.sum(nmod.narr)
print(numba_test())
```

Output:
```
C:/Users/User/.../ntest.py:5: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function numba_test failed at nopython mode lowering due to: 'NoneType' object has no attribute 'module'

File "ntest.py", line 8:
def numba_test():
    return np.sum(nmod.narr)
    ^

[1] During: lowering "$0.4 = getattr(value=$0.3, attr=narr)" at C:/Users/User/.../ntest.py (8)
  @jit
C:\Users\User\venv\lib\site-packages\numba\compiler.py:742: NumbaWarning: Function "numba_test" was compiled in object mode without forceobj=True.

File "ntest.py", line 7:
# @jit(nopython=True)
def numba_test():
^

  self.func_ir.loc))
C:\Users\User\venv\lib\site-packages\numba\compiler.py:751: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "ntest.py", line 7:
# @jit(nopython=True)
def numba_test():
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, self.func_ir.loc))
8

```

Aliasing the module doesn't help:

```
import nmod as nm
...
    return np.sum(nm.narr)
```
Also tried different numpy functions with the same result.

**Comment by stuartarchibald** [comment]
Thanks for the report. I'm pretty sure that this is a known bug, will try and find the duplicate.

**Comment by stuartarchibald** [comment]
The issue is that, `some_module.some_thing` resolves as a `getattr`, which hits this:
https://github.com/numba/numba/blob/5bd018fd55ab2ff0916ab2c6360334fe94e471a4/numba/targets/base.py#L571-L591
and because the type is a module it will go specifically through this call:
https://github.com/numba/numba/blob/5bd018fd55ab2ff0916ab2c6360334fe94e471a4/numba/targets/base.py#L588
and `get_constant` needs work as it only works for simple types as noted in the comments:
https://github.com/numba/numba/blob/5bd018fd55ab2ff0916ab2c6360334fe94e471a4/numba/targets/base.py#L504-L510

xref: https://github.com/numba/numba/issues/3138 (and I think there's at least one more)
