### ISSUE TITLE
generated_jit doesn't get passed correct arguments with inline='always' argument

### ISSUE THREAD

**Issue by sjperkins** [numba/numba#4692]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).

0.46.0

- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The below:

```python
from numba import njit, generated_jit
from numba import types
import numpy as np


@generated_jit(nopython=True, inline='always')
def inlining(array):
    if isinstance(array, types.npytypes.Array):
        def impl(array):
            return array
    else:
        def impl(array):
            return array

    return impl

@njit
def fn(array):
    return inlining(array)

print(fn(np.zeros(10)))
```

fails with:

```traceback
Traceback (most recent call last):
  File "test_inlining_generated_jit.py", line 24, in <module>
    print(fn(np.zeros(10)))
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/sperkins/venv/afr3/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'isinstance': cannot determine Numba type of <class 'builtin_function_or_method'>

File "test_inlining_generated_jit.py", line 9:
def inlining(array):
    <source elided>
    if isinstance(array, types.npytypes.Array):
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

but succeeds with `inline='never'`. It seems to be passed in a function instead of a Array type for the `array` argument.

**Comment by stuartarchibald** [comment]
Thanks for the report, this is not supported and is documented as such: http://numba.pydata.org/numba-doc/latest/developer/inlining.html#notes-on-inlining 

>The decorators numba.jit() and numba.extending.overload() both support the keyword argument inline.

but failure probably ought to be more graceful.

**Comment by EPronovost** [comment]
I just ran into this as well.  Should we assert that `inline not in kwargs` in `generated_jit`?

**Comment by stuartarchibald** [comment]
Think that this patch should make it work:
```python
diff --git a/numba/core/untyped_passes.py b/numba/core/untyped_passes.py
index 7e90b58aa..ee46a78f6 100644
--- a/numba/core/untyped_passes.py
+++ b/numba/core/untyped_passes.py
@@ -377,7 +377,27 @@ class InlineInlinables(FunctionPass):
                     if not inline_opt.is_never_inline:
                         # yes, it could be inlinable
                         do_inline = True
-                        pyfunc = val.py_func
+                        # See if it's a generated_jit function and if so
+                        # resolve it.
+                        from numba.core.dispatcher import \
+                            _GeneratedFunctionCompiler
+                        compiler = val._compiler
+                        if isinstance(compiler,
+                                      _GeneratedFunctionCompiler):
+                            do_raise = False
+                            resolver = compiler._get_implementation
+                            try:
+                                pyfunc = resolver(state.args, {})
+                            except TypeError:
+                                do_raise = True
+                            if do_raise or pyfunc is None:
+                                msg = ("Could not resolve @generated_jit "
+                                       "decorated function '{}' for arguments "
+                                       "{}.".format(to_inline.name,
+                                                    state.args))
+                                raise errors.TypingError(msg, expr.func.loc)
+                        else:
+                            pyfunc = val.py_func
```
needs tests etc.

**Comment by stuartarchibald** [comment]
Following on from discussion in #8466 and implementation to deprecate in #8499, `generated_jit` is now deprecated and this will not be fixed. The `numba.extending.overload` API provides equivalent functionality and also has support for the `inline` kwarg.
