### ISSUE TITLE
Internal error in type inference

### ISSUE THREAD

**Issue by pitrou** [numba/numba#473]
```
>>> @jit(double[:](double[:,:], double[:]), nopython=True)
... def npsum(a, b):
...     return np.sum(a, 0) + b
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numba\decorators.py", line 128, in wrapper
    disp.compile(sig)
  File "numba\dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "numba\compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "numba\compiler.py", line 120, in compile_bytecode
    locals)
  File "numba\compiler.py", line 283, in type_inference_stage
    infer.propagate()
  File "numba\typeinfer.py", line 312, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "numba\typeinfer.py", line 114, in propagate
    raise TypingError("Internal error:\n%s" % e, constrain.loc)
numba.typeinfer.TypingError: Internal error:
(Module(<module 'numpy' from 'c:\t\XXX\numba-dev\numpy\__init__.pyc'>), 'sum')
File "<stdin>", line 3
```

**Comment by pitrou** [comment]
This issue unfortunately spans several problems, but most of them have been fixed. Closing, more specific issues can be opened if desired.
