### ISSUE TITLE
Parallel failing in no python mode

### ISSUE THREAD

**Issue by damon-chem-e** [numba/numba#4748]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This is perhaps related to issue #2512.

When the code below is run with `@njit(parallel=False)`, everything runs fine.

Numba version: 0.46.0
System: Ubuntu 18.04.3 and Windows 10 (replicated on both)

Code: 

```
@njit(parallel=True)
def _ols_numba_parallel(d,ti,yvari,xvari):
    periods = np.unique(d[:,ti])
    gammas = np.zeros((periods.shape[0],xvari.shape[0]))
    for i in prange(periods.shape[0]):
        dp = d[d[:,ti]==periods[i]]
        assert np.linalg.matrix_rank(dp[:,xvari])==xvari.shape[0], 'Independent variable matrix is not full column rank. Check data carefully.'
        gamma,nul1,nul2,nul3 = np.linalg.lstsq(dp[:,xvari],dp[:,yvari],rcond=-1)
        gammas[i,:] = gamma
    return gammas        

def fama_macbeth_numba(data,t,yvar,xvar,intercept=True,parallel=False):

    if intercept==True:
        data['intercept'] = 1
        xvar.insert(0,'intercept')
    ti = data.columns.get_loc(t)
    yvari = data.columns.get_loc(yvar)
    xvari = [data.columns.get_loc(x) for x in xvar]
    d = data.to_numpy()
    if parallel:
        gammas = _ols_numba_parallel(d,ti,np.array(yvari),np.array(xvari))
    else:
        gammas = _ols_numba(d,ti,np.array(yvari),np.array(xvari))
    result = pd.DataFrame(gammas,columns=xvar,index=data[t].unique())
    return result

n_firms = 10
n_periods = 10

def firm(fid):
    f = np.random.random((int(n_periods),4))
    f = pd.DataFrame(f)
    f['period'] = f.index
    f['firmid'] = fid
    return f
df = [firm(i) for i in range(int(n_firms))]
df = pd.concat(df).rename(columns={0:'ret',1:'exmkt',2:'smb',3:'hml'})

result = fama_macbeth_numba(df,'period','ret',['exmkt','smb','hml'],intercept=True,parallel=True)
```

Provides the following error: 

```
Traceback (most recent call last):

  File "<ipython-input-101-c2c55c205bd8>", line 1, in <module>
    runfile('C:/Users/rpham/Desktop/FIN_Library/test.py', wdir='C:/Users/rpham/Desktop/FIN_Library')

  File "C:\Users\rpham\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/rpham/Desktop/FIN_Library/test.py", line 19, in <module>
    result = fama_macbeth_numba(df,'period','ret',['exmkt','smb','hml'],intercept=True,parallel=True)

  File "C:\Users\rpham\Desktop\FIN_Library\finance_byu\fama_macbeth.py", line 202, in fama_macbeth_numba
    gammas = _ols_numba_parallel(d,ti,np.array(yvari),np.array(xvari))

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\dispatcher.py", line 370, in _compile_for_args
    raise e

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\dispatcher.py", line 327, in _compile_for_args
    return self.compile(tuple(argtypes))

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler.py", line 377, in compile_extra
    return self._compile_bytecode()

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler.py", line 886, in _compile_bytecode
    return self._compile_core()

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler.py", line 873, in _compile_core
    res = pm.run(self.status)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler.py", line 254, in run
    raise patched_exception

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler.py", line 245, in run
    stage()

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\compiler.py", line 565, in stage_parfor_pass
    parfor_pass.run()

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\parfor.py", line 1448, in run
    self.array_analysis.run(self.func_ir.blocks)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\array_analysis.py", line 916, in run
    pre, post = self._analyze_inst(label, scope, equiv_set, inst)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\array_analysis.py", line 987, in _analyze_inst
    equiv_set.insert_equiv(lhs, shape)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\array_analysis.py", line 445, in insert_equiv
    obj_names = [self._get_names(x) for x in objs]

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\array_analysis.py", line 445, in <listcomp>
    obj_names = [self._get_names(x) for x in objs]

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\array_analysis.py", line 363, in _get_names
    return tuple(self._get_names(x)[0] for x in obj)

  File "C:\Users\rpham\Anaconda3\lib\site-packages\numba\array_analysis.py", line 363, in <genexpr>
    return tuple(self._get_names(x)[0] for x in obj)

IndexError: Failed in nopython mode pipeline (step: convert to parfors)
tuple index out of range
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. The issue is in array analysis when using a 0d array as an index. MWE:
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def foo(x, idx):
    for i in prange(1):
        _ = x[:, idx]

d = np.zeros((100,7))
ix = np.array(4) # make this a 1d array and the code is fine
foo(d, ix)
```
CC: @DrTodd13

**Comment by damon-chem-e** [comment]
This solved the error. Thank you!
