### ISSUE TITLE
Allow casting numpy scalars

### ISSUE THREAD

**Issue by dhirschfeld** [numba/numba#4749]
From [gitter](https://gitter.im/numba/numba?at=5db266f2a03ae1584f04f64d):
I'm running into the below error:
```
TypeError: No matching definition for argument type(s) array(float64, 0d, C), float64, float64, float64, float64, float64
```
My function is jit compiled to accept float64args. I'm passing it to an external routine which internally casts one of the args to a 0d numpy array and hence I get the above error.

It would be great if there were some way to tell numba to cast numpy scalars to their underlying type.

**Comment by dhirschfeld** [comment]
I tried `typeof_impl.register` but it appears to want a class, not an instance:
```python
In [17]: from numba.extending import typeof_impl

In [18]: typeof_impl.register(types.Array(types.float64, 0, 'C'))
Traceback (most recent call last):

  File "<ipython-input-18-01da58bcf25a>", line 1, in <module>
    typeof_impl.register(types.Array(types.float64, 0, 'C'))

  File "C:\Users\dhirschf\envs\dev\lib\functools.py", line 817, in register
    f"Invalid first argument to `register()`: {cls!r}. "

TypeError: Invalid first argument to `register()`: array(float64, 0d, C). Use either `@register(some_class)` or plain `@register` on an annotated function.
```

**Comment by dhirschfeld** [comment]
On gitter @stuartarchibald suggested to also explicitly compile with array arguments:
```python
from numba.types import float64, Array

@njit([
       float64(float64, float64),
       float64(
               Array(float64, 0, 'C'),
               Array(float64, 0, 'C'),
        ),
])
def add(x, y):
    return x + y
```
...which works great:
```python
In [22]: add(3.0, 7.0)
Out[22]: 10.0

In [23]: add(np.array(3.0), np.array(7.0))
Out[23]: 10.0
```
...*except* for mixed arguments:
```python

In [24]: add(np.array(3.0), 7.0)
Traceback (most recent call last):

  File "<ipython-input-24-3904fb28ffea>", line 1, in <module>
    add(np.array(3.0), 7.0)

  File "C:\Users\dhirschf\envs\dev\lib\site-packages\numba\dispatcher.py", line 574, in _explain_matching_error
    raise TypeError(msg)

TypeError: No matching definition for argument type(s) array(float64, 0d, C), float64
```

With 6 arguments to my function, any of which may be cast to a numpy scalar manually specifying all the possible permutations is a bit labourious so it would be nice to allow casts from numpy scalars to their underlying type

**Comment by dhirschfeld** [comment]
The workaround would be a lot easier if you could specify a union type - e.g.
```python
float64_or_array_scalar = types.Union(float64,  Array(float64, 0, 'C'))
```

**Comment by stuartarchibald** [comment]
Thanks for the suggestion, I'll raise it at the core developers meeting this week.

**Comment by sklam** [comment]
Discussion notes from today's developer meeting:

* Support implicit casting at dispatching that an actual parameter of array scalar (0d array) is provided for a parameter expecting a scalar. 
* It is too easy to have arrayscalar in pure-python code; i.e `a_numpy_array[idx]` can yield one.
* Investigate whether we can support the same implicit casting in jit-code, where arrayscalar is less likely to occur because numba is likely to degrade an arrayscalar to an actual scalar.
