### ISSUE TITLE
Numba 0.46.0 depends on pkg_resources but does not declare a setuptools dependency

### ISSUE THREAD

**Issue by eric-wieser** [numba/numba#4763]
Results in this CI failure on a system without any `setuptools` installation:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=85208

Stack trace is:

```
    import numba
  File "/home/conda/feedstock_root/build_artifacts/clifford_1572349688184/.../lib/python3.7/site-packages/numba/__init__.py", line 30, in <module>
    from .decorators import (autojit, cfunc, generated_jit, jit, njit, stencil,
  File "/home/conda/feedstock_root/build_artifacts/clifford_1572349688184/.../lib/python3.7/site-packages/numba/decorators.py", line 14, in <module>
    from .targets import registry
  File "/home/conda/feedstock_root/build_artifacts/clifford_1572349688184/.../lib/python3.7/site-packages/numba/targets/registry.py", line 5, in <module>
    from . import cpu
  File "/home/conda/feedstock_root/build_artifacts/clifford_1572349688184/.../lib/python3.7/site-packages/numba/targets/cpu.py", line 20, in <module>
    import numba.entrypoints
  File "/home/conda/feedstock_root/build_artifacts/clifford_1572349688184/.../lib/python3.7/site-packages/numba/entrypoints.py", line 3, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```

cc @hugohadfield

**Comment by seibert** [comment]
Good catch.  We should fix this in our planned patch release.

**Comment by eric-wieser** [comment]
Note this is already fixed in numba 0.46.0_1 on conda-forge

**Comment by PerchunPak** [comment]
Also have this problem, for install used pip
```
python main.py
Traceback (most recent call last):
  File "E:\servers\programming\pyton\test\main.py", line 1, in <module>
    from numba import njit
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\__init__.py", line 39, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\stencils\stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\registry.py", line 4, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 16, in <module>
    from numba.core import utils, types, errors, typing, serialize, config, compiler, sigutils
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 6, in <module>
    from numba.core import (utils, errors, typing, interpreter, bytecode, postproc,
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\cpu.py", line 16, in <module>
    import numba.core.entrypoints
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\entrypoints.py", line 4, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'```

**Comment by esc** [comment]
@PerchunPak thank you for adding this to the Numba issue tracker. Since you are commenting on an older issue here, it is likely that you have encountered a new issue that shows the same symptoms of the older issue. My recommendation to resolve this would be to:

a) Open a new issue
b) State which operating system and version you are working on
c) Submit a full trace-back of the installation process (including the command your typed and any and all output)

This should help us get to the bottom of your issue. Thank you kindly in advance for your cooperation.
