### ISSUE TITLE
Numba v0.46.0 issue when executing umap

### ISSUE THREAD

**Issue by shuo-shan** [numba/numba#4778]
```
Traceback (most recent call last):
  File "C:\Users\CrystalChutki\Desktop\Zlab\Enhancer_clustering_exercise\enhancer_clustering_analysis.py", line 24, in <module>
    umap_data = reducer.fit_transform(scaled_m.T)
  File "C:\Python27\lib\site-packages\umap\umap_.py", line 1598, in fit_transform
    self.fit(X, y)
  File "C:\Python27\lib\site-packages\umap\umap_.py", line 1417, in fit
    self.verbose,
  File "C:\Python27\lib\site-packages\umap\umap_.py", line 478, in fuzzy_simplicial_set
    knn_indices, knn_dists, sigmas, rhos
  File "C:\Python27\lib\site-packages\numba\dispatcher.py", line 420, in _compile_for_args
    raise e
UnsupportedParforsError: Failed in nopython mode pipeline (step: nopython mode backend)
[1m[1mThe 'parallel' target is not currently supported on Windows operating systems when using Python 2.7, or on 32 bit hardware.[0m
[0m[1m[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.26, range = (0, $0.13, 1))]{362: <ir.Block at C:\Python27\lib\site-packages\umap\umap_.py (330)>}Var(parfor_index.26, C:\Python27\lib\site-packages\umap\umap_.py (330))" at C:\Python27\lib\site-packages\umap\umap_.py (330)[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new
```

**Comment by esc** [comment]
@shuo-shan thanks for reporting this, I have fixed up the formatting to use markdown. Feel free to checkout the following guid about Github markdown:

https://help.github.com/en/github/writing-on-github

**Comment by esc** [comment]
Taking a closer look at the error message, it appears you are using an unsupported platform or python version:

```
�[1m�[1mThe 'parallel' target is not currently supported on Windows operating systems when using Python 2.7, or on 32 bit hardware.�[0m
````

Can you confirm?

If so, @lmcinnes - it might be worth disabling the parallel target in such cases?

**Comment by shuo-shan** [comment]
Thank you @esc! Yes I was running it on Python2.7 using 64bit hardware. I will try running my code again using Python3.x and keep you posted on whether this error show up again.

**Comment by esc** [comment]
@shuo-shan if that is an option, great!

**Comment by shuo-shan** [comment]
@esc I used Python3.7.4 and it worked. Thank you for the help!

**Comment by esc** [comment]
@shuo-shan thanks for reporting back. Will close this issue now.
