### ISSUE TITLE
Cannot generate sphinx documentation with Python 3

### ISSUE THREAD

**Issue by seibert** [numba/numba#478]
Running `make html` produces the following backtrace in sphinx-doc:
```
# Sphinx version: 1.2.2
# Python version: 3.3.5
# Docutils version: 0.11 release
# Jinja2 version: 2.7.2
# Loaded extensions:
#   sphinx.ext.graphviz from /Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/ext/graphviz.py
#   sphinx.ext.mathjax from /Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/ext/mathjax.py
#   sphinx.ext.autodoc from /Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/ext/autodoc.py
#   sphinxjp.themecore from /Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinxjp/themecore/__init__.py
#   sphinx.ext.oldcmarkup from /Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/ext/oldcmarkup.py
Traceback (most recent call last):
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/application.py", line 212, in build
    self.builder.build_update()
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 234, in build
    purple, length):
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/environment.py", line 477, in update_generator
    self.read_doc(docname, app=app)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/environment.py", line 624, in read_doc
    pub.publish()
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2301, in explicit_markup
    self.explicit_list(blank_finish)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2331, in explicit_list
    match_titles=self.state_machine.match_titles)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 319, in nested_list_parse
    node=node, match_titles=match_titles)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2604, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/ext/autodoc.py", line 1401, in run
    documenter.generate(more_content=self.content)
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/ext/autodoc.py", line 718, in generate
    if not self.import_object():
  File "/Users/stan/anaconda/envs/numba_dev33/lib/python3.3/site-packages/sphinx/ext/autodoc.py", line 1186, in import_object
    obj_from_parent = self.parent.__dict__.get(self.object_name)
AttributeError: 'NoneType' object has no attribute '__dict__'
```

**Comment by pitrou** [comment]
This works fine with the new docs.
