### ISSUE TITLE
Issue Report - New to bug reporting onGitHub

### ISSUE THREAD

**Issue by bigcats01** [numba/numba#4792]
```
<ipython-input-26-9cb74ba32ba8>:1: NumbaWarning: [1m
Compilation is falling back to object mode WITH looplifting enabled because Function "gett_info" failed type inference due to: [1mUntyped global name 'd1819':[0m [1m[1mcannot determine Numba type of <class 'pandas.core.series.Series'>[0m
[1m
File "<ipython-input-26-9cb74ba32ba8>", line 3:[0m
[1mdef gett_info():
[1m    ri10percent1819 = (d1819['RI.10PositiveChange']/(d1819['RI.10NegativeChange'] + d1819['RI.10PositiveChange']+d1819['RI.10NoChange']))*100
[0m    [1m^[0m[0m
[0m[0m
  @jit
---------------------------------------------------------------------------

ForbiddenConstruct                        Traceback (most recent call last)

<ipython-input-26-9cb74ba32ba8> in <module>
      7     ri10percent = [ri10percent1516,ri10percent1617,ri10percent1718,ri10percent1819]
      8     return locals()
----> 9 gett_info()

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    418                     e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    419             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 420             raise e
    421 
    422     def inspect_llvm(self, signature=None):

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    351                 argtypes.append(self.typeof_pyval(a))
    352         try:
--> 353             return self.compile(tuple(argtypes))
    354         except errors.ForceLiteralArg as e:
    355             # Received request for compiler re-entry with the list of arguments

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, sig)
    766             self._cache_misses[sig] += 1
    767             try:
--> 768                 cres = self._compiler.compile(args, return_type)
    769             except errors.ForceLiteralArg as e:
    770                 def folded(args, kws):

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in compile(self, args, return_type)
     75 
     76     def compile(self, args, return_type):
---> 77         status, retval = self._compile_cached(args, return_type)
     78         if status:
     79             return retval

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_cached(self, args, return_type)
     89 
     90         try:
---> 91             retval = self._compile_core(args, return_type)
     92         except errors.TypingError as e:
     93             self._failed_cache[key] = e

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_core(self, args, return_type)
    107                                       args=args, return_type=return_type,
    108                                       flags=flags, locals=self.locals,
--> 109                                       pipeline_class=self.pipeline_class)
    110         # Check typing error if object mode is used
    111         if cres.typing_error is not None and not flags.enable_pyobject:

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    526     pipeline = pipeline_class(typingctx, targetctx, library,
    527                               args, return_type, flags, locals)
--> 528     return pipeline.compile_extra(func)
    529 
    530 

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in compile_extra(self, func)
    324         self.state.lifted = ()
    325         self.state.lifted_from = None
--> 326         return self._compile_bytecode()
    327 
    328     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _compile_bytecode(self)
    383         """
    384         assert self.state.func_ir is None
--> 385         return self._compile_core()
    386 
    387     def _compile_ir(self):

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    363                 self.state.status.fail_reason = e
    364                 if is_final_pipeline:
--> 365                     raise e
    366         else:
    367             raise CompilerError("All available pipelines exhausted")

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler.py in _compile_core(self)
    354             res = None
    355             try:
--> 356                 pm.run(self.state)
    357                 if self.state.cr is not None:
    358                     break

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_machinery.py in run(self, state)
    326                     (self.pipeline_name, pass_desc)
    327                 patched_exception = self._patch_error(msg, e)
--> 328                 raise patched_exception
    329 
    330     def dependency_analysis(self):

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_machinery.py in run(self, state)
    317                 pass_inst = _pass_registry.get(pss).pass_inst
    318                 if isinstance(pass_inst, CompilerPass):
--> 319                     self._runPass(idx, pass_inst, state)
    320                 else:
    321                     raise BaseException("Legacy pass in use")

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     30         def _acquire_compile_lock(*args, **kwargs):
     31             with self:
---> 32                 return func(*args, **kwargs)
     33         return _acquire_compile_lock
     34 

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_machinery.py in _runPass(self, index, pss, internal_state)
    279             mutated |= check(pss.run_initialization, internal_state)
    280         with SimpleTimer() as pass_time:
--> 281             mutated |= check(pss.run_pass, internal_state)
    282         with SimpleTimer() as finalize_time:
    283             mutated |= check(pss.run_finalizer, internal_state)

C:\ProgramData\Anaconda3\lib\site-packages\numba\compiler_machinery.py in check(func, compiler_state)
    266 
    267         def check(func, compiler_state):
--> 268             mangled = func(compiler_state)
    269             if mangled not in (True, False):
    270                 msg = ("CompilerPass implementations should return True/False. "

C:\ProgramData\Anaconda3\lib\site-packages\numba\object_mode_passes.py in run_pass(self, state)
    143                                                state.flags)
    144 
--> 145         lowered = backend_object_mode()
    146         signature = typing.signature(state.return_type, *state.args)
    147         from numba.compiler import compile_result

C:\ProgramData\Anaconda3\lib\site-packages\numba\object_mode_passes.py in backend_object_mode()
    141                                                state.library,
    142                                                state.func_ir,
--> 143                                                state.flags)
    144 
    145         lowered = backend_object_mode()

C:\ProgramData\Anaconda3\lib\site-packages\numba\object_mode_passes.py in _py_lowering_stage(self, targetctx, library, interp, flags)
     98         with targetctx.push_code_library(library):
     99             lower = pylowering.PyLower(targetctx, library, fndesc, interp)
--> 100             lower.lower()
    101             if not flags.no_cpython_wrapper:
    102                 lower.create_cpython_wrapper()

C:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower(self)
    177         if self.generator_info is None:
    178             self.genlower = None
--> 179             self.lower_normal_function(self.fndesc)
    180         else:
    181             self.genlower = self.GeneratorLower(self)

C:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_normal_function(self, fndesc)
    218         # Init argument values
    219         self.extract_function_arguments()
--> 220         entry_block_tail = self.lower_function_body()
    221 
    222         # Close tail of entry block

C:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_function_body(self)
    243             bb = self.blkmap[offset]
    244             self.builder.position_at_end(bb)
--> 245             self.lower_block(block)
    246 
    247         self.post_lower()

C:\ProgramData\Anaconda3\lib\site-packages\numba\lowering.py in lower_block(self, block)
    258             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    259                                    loc=self.loc, errcls_=defaulterrcls):
--> 260                 self.lower_inst(inst)
    261 
    262     def create_cpython_wrapper(self, release_gil=False):

C:\ProgramData\Anaconda3\lib\site-packages\numba\pylowering.py in lower_inst(self, inst)
     94     def lower_inst(self, inst):
     95         if isinstance(inst, ir.Assign):
---> 96             value = self.lower_assign(inst)
     97             self.storevar(value, inst.target.name)
     98 

C:\ProgramData\Anaconda3\lib\site-packages\numba\pylowering.py in lower_assign(self, inst)
    190             return self.lower_expr(value)
    191         elif isinstance(value, ir.Global):
--> 192             return self.lower_global(value.name, value.value)
    193         elif isinstance(value, ir.Yield):
    194             return self.lower_yield(value)

C:\ProgramData\Anaconda3\lib\site-packages\numba\pylowering.py in lower_global(self, name, value)
    430             if value in _unsupported_builtins:
    431                 raise ForbiddenConstruct("builtins %s() is not supported"
--> 432                                          % name, loc=self.loc)
    433         except TypeError:
    434             # `value` is unhashable, ignore

ForbiddenConstruct: Failed in object mode pipeline (step: object mode backend)
builtins locals() is not supported

File "<ipython-input-26-9cb74ba32ba8>", line 8:
def gett_info():
    <source elided>
    ri10percent = [ri10percent1516,ri10percent1617,ri10percent1718,ri10percent1819]
    return locals()
    ^

[1] During: lowering "$0.74 = global(locals: <built-in function locals>)" at <ipython-input-26-9cb74ba32ba8> (8)
```

REPORDUCTION:

```
import pandas as pd
from matplotlib import rc
rc('text', usetex=True)
nice = ['#899477', '#4da1a9', '#e59500','#7f99b1']
from matplotlib.gridspec import GridSpec
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import datetime 
rc('text', usetex=True)
pd.options.display.float_format = '{:,}'.format
import numpy as np
from matplotlib.ticker import(AutoMinorLocator)
from numba import jit
#%%

d1819 = pd.read_excel('FAST.xlsx',sheet_name ='SY1819' )
d1718 = pd.read_excel('FAST.xlsx',sheet_name ='SY1718')
d1617 = pd.read_excel('FAST.xlsx',sheet_name ='SY1617')
d1516 = pd.read_excel('FAST.xlsx',sheet_name = 'SY1516')

#%%

d1819 =d1819.iloc[-1]
d1718 = d1718.iloc[-1]
d1617 = d1617.iloc[-1]
d1516 = d1516.iloc[-1]
#%%
@jit
def gett_info():
    ri10percent1819 = (d1819['RI.10PositiveChange']/(d1819['RI.10NegativeChange'] + d1819['RI.10PositiveChange']+d1819['RI.10NoChange']))*100
    ri10percent1718 = (d1718['RI.10PositiveChange']/(d1718['RI.10NegativeChange'] + d1718['RI.10PositiveChange']+d1718['RI.10NoChange']))*100
    ri10percent1617 = (d1617['RI.10PositiveChange']/(d1617['RI.10NegativeChange'] + d1617['RI.10PositiveChange']+d1617['RI.10NoChange']))*100
    ri10percent1516 = (d1516['RI.10PositiveChange']/(d1516['RI.10NegativeChange'] + d1516['RI.10PositiveChange']+d1516['RI.10NoChange']))*100
    ri10percent = [ri10percent1516,ri10percent1617,ri10percent1718,ri10percent1819]
    return locals()
gett_info()
```

**Comment by esc** [comment]
@bigcats01 thanks for submitting this report and helping to improve Numba. I have reformatted your submission using Github markdown. A summary of which can be found here:

https://guides.github.com/features/mastering-markdown/

As for your issue, `locals()` isn't supported by Numba. Here is a minimal reproducer of the issue:

```
from numba import jit


def foo():
    a = 1
    return locals()


print(foo())
nfoo = jit(foo)
print(nfoo())
```

Maybe we can help you find a workaround. Perhaps you can return the `ri10percent*` variables in a tuple?

```
return (ri10percent1819, ri10percent1718, ...)
```

**Comment by bigcats01** [comment]
I see, I did notice I can return a list of local variables from within the function. Tuple could work too, I was just avoiding typing, there are like 30+ variables from the data analysis. I am new to numba, and frankly still unsure on how to properly use it.
