### ISSUE TITLE
TypingError with random.random() if not NUMBA_ENABLE_CUDASIM=1

### ISSUE THREAD

**Issue by jetxeberria** [numba/numba#4801]
Numba version: 0.46.0

This code (minimal_test.py):

```python
from numba import cuda
from random import random

@cuda.jit()
def foo():
    random()

foo[1, 1]()
```

- Works if called with:

```python
NUMBA_ENABLE_CUDASIM=1 python minimal_test.py
```

- Raises TypingError if called with:

```python
python minimal_test.py
```
Error traceback:

```
Traceback (most recent call last):
  File "minimal_testing.py", line 8, in <module>
    foo[1, 1]()
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 799, in __call__
    kernel = self.specialize(*args)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 810, in specialize
    kernel = self.compile(argtypes)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 826, in compile
    **self.targetoptions)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 62, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler.py", line 326, in compile_extra
    return self._compile_bytecode()
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler.py", line 385, in _compile_bytecode
    return self._compile_core()
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler.py", line 365, in _compile_core
    raise e
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler.py", line 356, in _compile_core
    pm.run(self.state)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 328, in run
    raise patched_exception
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/typed_passes.py", line 94, in run_pass
    state.locals)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/typed_passes.py", line 65, in type_inference_stage
    infer.build_constraint()
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/typeinfer.py", line 904, in build_constraint
    self.constrain_statement(inst)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/typeinfer.py", line 1188, in constrain_statement
    self.typeof_assign(inst)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/typeinfer.py", line 1259, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/typeinfer.py", line 1358, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/typeinfer.py", line 1280, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'random': cannot determine Numba type of <class 'builtin_function_or_method'>

File "minimal_testing.py", line 6:
def foo():
    random()
    ^
```

**Comment by seibert** [comment]
`random.random()` is not supported on the GPU due to how parallel RNGs need to work.  You can use a more GPU friendly generator, documented here:

http://numba.pydata.org/numba-doc/latest/cuda/random.html

**Comment by seibert** [comment]
(note that for debug purposes, the CUDA simulator allows you to write whatever Python you like in a kernel, which is why this worked for you.)

**Comment by jetxeberria** [comment]
Thanks! I didn't know that point!

However I've tried to reproduce the example shown in that documentation and I get NumbaDeprecationWarning.

Is there any example I could check that is up to date?

Nevertheless should this issue be closed and ask about usage of random number generator in another place?

**Comment by seibert** [comment]
What deprecation warning are you getting?  Is it related to this CUDA function, or something else?

**Comment by jetxeberria** [comment]
Executing the example code with 
```
NUMBA_ENABLE_CUDASIM=1 python random_testing.py
```
It outputs:
```
/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py:135: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "xoroshiro128p_uniform_float32" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at /home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py (145)

File "../../../../../../../../../../../../home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py", line 145:
def xoroshiro128p_uniform_float32(states, index):
    <source elided>
    '''
    index = int64(index)
    ^

  @jit
/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "xoroshiro128p_uniform_float32" was compiled in object mode without forceobj=True.

File "../../../../../../../../../../../../home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py", line 136:
@jit
def xoroshiro128p_uniform_float32(states, index):
^

  state.func_ir.loc))
/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/object_mode_passes.py:187: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../../../../../../../../../../../../home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py", line 136:
@jit
def xoroshiro128p_uniform_float32(states, index):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, state.func_ir.loc))
/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py:71: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "xoroshiro128p_next" failed type inference due to: non-precise type pyobject
[1] During: typing of argument at /home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py (81)

File "../../../../../../../../../../../../home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py", line 81:
def xoroshiro128p_next(states, index):
    <source elided>
    '''
    index = int64(index)
    ^

  @jit
/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/object_mode_passes.py:178: NumbaWarning: Function "xoroshiro128p_next" was compiled in object mode without forceobj=True.

File "../../../../../../../../../../../../home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py", line 72:
@jit
def xoroshiro128p_next(states, index):
^

  state.func_ir.loc))
/home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/object_mode_passes.py:187: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "../../../../../../../../../../../../home/jetxeberria/documents/programs/anaconda/anaconda3/envs/testing3/lib/python3.7/site-packages/numba/cuda/random.py", line 72:
@jit
def xoroshiro128p_next(states, index):
^

  warnings.warn(errors.NumbaDeprecationWarning(msg, state.func_ir.loc))
random_testing.py:16: RuntimeWarning: overflow encountered in ulong_scalars
  x = xoroshiro128p_uniform_float32(rng_states, thread_id)
random_testing.py:17: RuntimeWarning: overflow encountered in ulong_scalars
  y = xoroshiro128p_uniform_float32(rng_states, thread_id)
random_testing.py:16: RuntimeWarning: overflow encountered in ulong_scalars
  x = xoroshiro128p_uniform_float32(rng_states, thread_id)
pi: 3.1367188
```

**Comment by jetxeberria** [comment]
I've changed the iterations to 10 to have result faster (that's why the PI results is so bad)

**Comment by seibert** [comment]
Ah, interesting.  That says there is something wrong with the RNG implementation that is preventing full compilation on the CPU.  That is a bug we should fix.  Can you open a separate issue on that problem?

**Comment by jetxeberria** [comment]
Sure! Thanks!

**Comment by jetxeberria** [comment]
Closing issue because random.random() is known to be not supported by Numba
