### ISSUE TITLE
Some (but not all) unicode characters causing errors in jitclass

### ISSUE THREAD

**Issue by jstac** [numba/numba#4816]
Using numba version 0.44.1 on Anaconda 3.7 for linux, 64bit.

Minimal example:

```
from numba import jitclass, float64

data = [('ϕ', float64)]

@jitclass(data)
class Foo:
    
    def __init__(self, ϕ=1.0):
        self.ϕ = ϕ
        
foo = Foo()
```

Error message is shown below.  Interestingly, no error if the symbol for phi is replaced by the symbol for alpha.

Error also goes away if not using unicode.

```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-98-ebd3874f6c4e> in <module>
      9         self.ϕ = ϕ
     10 
---> 11 foo = Foo()

~/anaconda3/lib/python3.7/site-packages/numba/jitclass/base.py in __call__(cls, *args, **kwargs)
    124         bind = cls._ctor_sig.bind(None, *args, **kwargs)
    125         bind.apply_defaults()
--> 126         return cls._ctor(*bind.args[1:], **bind.kwargs)
    127 
    128 

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    349                 e.patch_message(msg)
    350 
--> 351             error_rewrite(e, 'typing')
    352         except errors.UnsupportedError as e:
    353             # Something unsupported is present in the user code, add help info

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    316                 raise e
    317             else:
--> 318                 reraise(type(e), e, None)
    319 
    320         argtypes = []

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Cannot resolve setattr: (instance.jitclass.Foo#55f838fb2cb8<ϕ:float64>).φ = float64

File "<ipython-input-98-ebd3874f6c4e>", line 9:
    def __init__(self, ϕ=1.0):
        self.ϕ = ϕ
        ^

[1] During: typing of set attribute 'φ' at <ipython-input-98-ebd3874f6c4e> (9)

File "<ipython-input-98-ebd3874f6c4e>", line 9:
    def __init__(self, ϕ=1.0):
        self.ϕ = ϕ
        ^

[1] During: resolving callee type: jitclass.Foo#55f838fb2cb8<ϕ:float64>
[2] During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by esc** [comment]
@jstac thanks for reporting this issue! I can confirm that I am able to reproduce this locally.

**Comment by stuartarchibald** [comment]
Related:
```python
from numba.ir_utils import compile_to_numba_ir
def foo(x):
    return x.ϕ

compile_to_numba_ir(foo, {}).dump()
```

**Comment by sklam** [comment]
This may not be a numba issue.

```python
data = 'ϕ'
print('data', data[0], ord(data))
class Foo:
    def __init__(self, ϕ=1.0):
        self.ϕ = ϕ
code = Foo.__init__.__code__
print('code.co_varnames[1]', code.co_varnames[1], ord(code.co_varnames[1]))
print('code.co_names[0]', code.co_names[0], ord(code.co_names[0]))
```
prints
```
data ϕ 981
code.co_varnames[1] φ 966
code.co_names[0] φ 966
```
The variable name in the python Code object is "normalized" to something different it seems.

and phi `ϕ` is a special unicode:

```
>>> ord('ϕ')
981
>>> ord('ϕ'.upper())
934
>>> ord('ϕ'.lower())
981
>>> ord('ϕ'.upper().lower())
966
```

**Comment by sklam** [comment]
Here's a code that shows CPython having this issue:

```python
from collections import namedtuple

class Bag:
    __slots__ = ['ϕ']

bag = Bag()
bag.ϕ = 1
```

if you read the above as a file ("bug.py"):

```python
# -*- coding: utf-8 -*-
import tokenize

with open('bug.py', 'rb') as fin:
    tokens = tokenize.tokenize(fin.readline)

    for tok in tokens:
        if tok.type in (1, 3):   # show "STRING" and "NAME"
            print(tok)
            print('    ', tok.string, ord(tok.string.strip("'\"")[0]))
```

The tokenizer is seeing the phis as:

```
TokenInfo(type=3 (STRING), string="'ϕ'", start=(4, 17), end=(4, 20), line="    __slots__ = ['ϕ']\n")
     'ϕ' 981
TokenInfo(type=1 (NAME), string='ϕ', start=(7, 4), end=(7, 5), line='bag.ϕ = 1\n')
     ϕ 981
```

Both are the same character in the string and in the variable name.

**Comment by jstac** [comment]
Thanks @sklam.  Not an easy fix then, apart from skipping some unicode characters. 

( I personally like to use unicode characters whenever they appear in equations, to bring code visually close to the maths.  I find it makes a big difference with debugging.)

**Comment by sklam** [comment]
@jstac, I have read more on the CPython unicode normalization for variable names and I now think this is a "feature not a bug" ;-). So according to the spec https://docs.python.org/3/reference/lexical_analysis.html#identifiers, it says

> All identifiers are converted into the normal form NFKC while parsing; comparison of identifiers is based on NFKC.

The phi character in your code in codepoint 981, which when normalized by CPython it becomes a different character:

```python
>>> import unicodedata
>>> ord(unicodedata.normalize("NFKC", chr(981)))
966
```

To use phi, you should use the normalized form in the source code, thus use the codepoint 966:

```python
>>> ord(unicodedata.normalize("NFKC", chr(966)))
966
```

So the solution is to use normalized form (this phi `φ` (`chr(966)`)) in source code.  I tested this on the posted code and it works.

I think linters need to check for this kind of "invisible bugs".

**Comment by jstac** [comment]
@sklam Thanks so much for clearing this up.  A note for others is that, when using Jupyter, `\phi` followed by tab produces ``ϕ`` but, from the above discussion a better option is to type `\varphi` followed by tab, which produces ``φ``.

A similar statement might be true about `\epsilon` and `\varepsilon`, although I haven't tried it.
