### ISSUE TITLE
it doesn't work in my RaspberryPi3

### ISSUE THREAD

**Issue by CHENntust** [numba/numba#4856]
Traceback (most recent call last):
  File "/home/pi/Downloads/ppatest.py", line 12, in <module>
    X_paa = paa.fit_transform(norm_array)
  File "/usr/local/lib/python3.7/dist-packages/sklearn/base.py", line 553, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/home/pi/.local/lib/python3.7/site-packages/pyts/approximation/paa.py", line 111, in transform
    start, end, n_timestamps_new)
  File "/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/usr/local/lib/python3.7/dist-packages/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler.py", line 326, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler.py", line 385, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler.py", line 365, in _compile_core
    raise e
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler.py", line 356, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py", line 328, in run
    raise patched_exception
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.7/dist-packages/numba/compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.7/dist-packages/numba/typed_passes.py", line 380, in run_pass
    NativeLowering().run_pass(state) # TODO: Pull this out into the pipeline
  File "/usr/local/lib/python3.7/dist-packages/numba/typed_passes.py", line 325, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.7/dist-packages/numba/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.7/dist-packages/numba/lowering.py", line 220, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python3.7/dist-packages/numba/lowering.py", line 245, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python3.7/dist-packages/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python3.7/dist-packages/numba/lowering.py", line 414, in lower_inst
    func(self, inst)
  File "/usr/local/lib/python3.7/dist-packages/numba/npyufunc/parfor.py", line 51, in _lower_parfor_parallel
    ensure_parallel_support()
  File "/usr/local/lib/python3.7/dist-packages/numba/parfor.py", line 3987, in ensure_parallel_support
    raise errors.UnsupportedParforsError(msg)
numba.errors.UnsupportedParforsError: Failed in nopython mode pipeline (step: nopython mode backend)
[1m[1mThe 'parallel' target is not currently supported on Windows operating systems when using Python 2.7, or on 32 bit hardware.[0m
[0m[1m[1] During: lowering "id=2[LoopNest(index_variable = parfor_index.52, range = (0, n_samples, 1))]{26: <ir.Block at /home/pi/.local/lib/python3.7/site-packages/pyts/approximation/paa.py (17)>}Var(parfor_index.52, /home/pi/.local/lib/python3.7/site-packages/pyts/approximation/paa.py (17))" at /home/pi/.local/lib/python3.7/site-packages/pyts/approximation/paa.py (17)[0m

**Comment by DrTodd13** [comment]
@CHENntust  Your answer is hidden in the error report.  "The 'parallel' target is not currently supported on Windows operating systems when using Python 2.7, or on 32 bit hardware."  So, it is clear that you're on Windows and most hardware is 64 bit so I suspect you're also using Python 2.7.  So, you have two choices.  You can write Numba but not use parallel=True or  you can try switching to Python 3.7.

**Comment by esc** [comment]
@CHENntust I will close this issue now because I believe it is resolved. If you continue to encounter the error after trying the suggestions from @DrTodd13 please don't hesitate to re-open the issue.
