### ISSUE TITLE
type inference error with np.sin

### ISSUE THREAD

**Issue by pitrou** [numba/numba#487]
```
>>> @jit(nopython=True)
... def nsin(a):
...     return np.sin(a)
... 
>>> arr = np.arange(10)
>>> arr
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> nsin(arr)
Traceback (most recent call last):
  File "/home/antoine/numba/numba/typeinfer.py", line 116, in propagate
    constrain(context, typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 168, in __call__
    self.resolve(context, typevars, fnty)
  File "/home/antoine/numba/numba/typeinfer.py", line 177, in resolve
    sig = context.resolve_function_type(fnty, args, ())
  File "/home/antoine/numba/numba/typing/context.py", line 44, in resolve_function_type
    return func.template(self).apply(args, kws)
  File "/home/antoine/numba/numba/typing/templates.py", line 193, in apply
    sig = generic(args, kws)
  File "/home/antoine/numba/numba/typing/npydecl.py", line 46, in generic
    ndims = max(*[a.ndim if isinstance(a, types.Array) else 0 for a in args])
TypeError: 'int' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/numba/numba/dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "/home/antoine/numba/numba/dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "/home/antoine/numba/numba/dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "/home/antoine/numba/numba/compiler.py", line 96, in compile_extra
    return_type, flags, locals)
  File "/home/antoine/numba/numba/compiler.py", line 122, in compile_bytecode
    locals)
  File "/home/antoine/numba/numba/compiler.py", line 285, in type_inference_stage
    infer.propagate()
  File "/home/antoine/numba/numba/typeinfer.py", line 318, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 120, in propagate
    raise TypingError("Internal error:\n%s" % e, constrain.loc)
numba.typeinfer.TypingError: Internal error:
'int' object is not iterable
File "<stdin>", line 3
```

**Comment by pitrou** [comment]
This is now fixed, closing.
