### ISSUE TITLE
a problem with using numba with python operation

### ISSUE THREAD

**Issue by mhusseinsh** [numba/numba#4878]
I am trying to use numba to utlize my python script with GPU
I receive this error

 ```
File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/dispatcher.py", line 42, in __call__
    return self.compiled(*args, **kws)

  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 799, in __call__
    kernel = self.specialize(*args)

  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 810, in specialize
    kernel = self.compile(argtypes)

  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 826, in compile
    **self.targetoptions)

  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 62, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)

  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})

  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)

  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 326, in compile_extra
    return self._compile_bytecode()

  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 385, in _compile_bytecode
    return self._compile_core()

  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 365, in _compile_core
    raise e

TypeError: Failed in nopython mode pipeline (step: fix up args)

Signature mismatch: 2 argument types given, but function takes 3 arguments

```

**Comment by seibert** [comment]
Can you give us more information?  Which version of Numba is this?  What is the function you are trying to compile?

**Comment by mhusseinsh** [comment]
Hello @seibert 
I am using numba version 0.46.0
I wrote a sample of the function I am using in a separate script, and here what I get

```
from numba import jit, cuda 
import numpy as np 
# to measure exec time 
from timeit import default_timer as timer
import random
from sklearn.manifold import TSNE
RS = 20150101
  
# normal function to run on cpu 
def func(a):
    X = np.vstack([a])
    tsneData = TSNE(n_components=2, random_state=RS, perplexity=30).fit_transform(a)
  
# function optimized to run on gpu  
@jit(target ="cuda")                          
def func2(a): 
    X = np.vstack([a])
    tsneData = TSNE(n_components=2, random_state=RS, perplexity=30).fit_transform(a)

if __name__=="__main__": 

    data = []
    for i in range (11):
        data1 = np.random.randint(low=0, high=255, size=100, dtype=np.uint8)
        data.append(data1)

    start = timer() 
    func(data) 
    print("without GPU:", timer()-start)     
    
    start = timer() 
    func2(data) 
    print("with GPU:", timer()-start) 
```
The error is:
```
('without GPU:', 0.08172798156738281)
/home/user/.local/lib/python2.7/site-packages/numba/cuda/decorators.py:113: UserWarning: autojit is deprecated and will be removed in a future release. Use jit instead.
  warn('autojit is deprecated and will be removed in a future release. Use jit instead.')
Traceback (most recent call last):
  File "testGPU.py", line 41, in <module>
    func2(data) 
  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/dispatcher.py", line 42, in __call__
    return self.compiled(*args, **kws)
  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 799, in __call__
    kernel = self.specialize(*args)
  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 810, in specialize
    kernel = self.compile(argtypes)
  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 826, in compile
    **self.targetoptions)
  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 62, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/user/.local/lib/python2.7/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 326, in compile_extra
    return self._compile_bytecode()
  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 385, in _compile_bytecode
    return self._compile_core()
  File "/home/user/.local/lib/python2.7/site-packages/numba/compiler.py", line 365, in _compile_core
    raise e
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'TSNE': cannot determine Numba type of <type 'type'>

File "testGPU.py", line 24:
def func2(a): 
    <source elided>
    X = np.vstack([a])
    tsneData = TSNE(n_components=2, random_state=RS, perplexity=30).fit_transform(a)
```
I don't know why did I get a different error than it was in my original script, but anyways, it still does not work

**Comment by esc** [comment]
@mhusseinsh thanks for reporting this. Unfortunately Numba doesn't know what to do with `TSNE`. I.e. we don't support compiling `sklear.manifold.TSNE`. Only a limited number of Python and Numpy features are supported for compilation on CPU. The same is true for GPU. You can view the supported features here:

* http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
* http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

In case you need functionality from Scipy, there is an add-on here:

https://github.com/numba/numba-scipy

**Comment by mhusseinsh** [comment]
Hello @esc 

There is no documentation on the link you provided for numba-scipy that shows how to use it, or how can I call the scipy functions

**Comment by esc** [comment]
@mhusseinsh yes, it is still in the early stages of development where the code itself is the only documentation. 😅 

Please feel free to join our gitter chat to ask questions about it: https://gitter.im/numba/numba

**Comment by stuartarchibald** [comment]
Docs are here: https://numba-scipy.readthedocs.io/en/latest/

**Comment by esc** [comment]
@stuartarchibald oh, didn't know that, thanks for following up. I updated the scipy-numba repo with a link to the docs at the top of the page, next top the description to ensure that users will find the docs easier in future.

**Comment by stuartarchibald** [comment]
and the 0.46 release demo shows how to use it, basically, install it, it's auto-discovered, then use the supported things:
https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2FNumba_046_release_demo.ipynb

**Comment by esc** [comment]
@mhusseinsh I am closing this issue now as I believe  it has been resolved.

**Comment by mhusseinsh** [comment]
hello @esc , @stuartarchibald 
sorry for commenting again, but I cannot find the TSNE in the special functions, how can I use TSNE with GPU then?

**Comment by seibert** [comment]
Someone will have to port the TSNE function to the GPU.  I'm not aware of anyone who has done that.
