### ISSUE TITLE
TypeError using default arguments with multiprocessing

### ISSUE THREAD

**Issue by jurreht** [numba/numba#4888]
When using default arguments in a jit'ed function, I get a TypeError when the function is called from a `multiprocessing` worker and the default arguments are omitted. The function works when run single-threaded. Minimal working example:

```python
from multiprocessing import Pool

from numba import jit


@jit
def add1(x):
    return x + 1

@jit
def add2(x, y=1):
    return x + y

if __name__ == "__main__":
    with Pool(2) as p:
        print(p.map(add1, [1, 2, 3]))  # [2, 3, 4] (OK)
        print(add2(1))  # 2 (OK)
        print(p.map(add2, [1, 2, 3]))  # TypeError
```

Output:
```
[2, 3, 4]
2
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
TypeError: not enough arguments: expected 2, got 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "smpe_paper/numba_test.py", line 18, in <module>
    print(p.map(add2, [1, 2, 3]))
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: not enough arguments: expected 2, got 1
(smpe-paper) root@5b798e37487d:/smpe-paper# python smpe_paper/numba_test.py
[2, 3, 4]
2
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
TypeError: not enough arguments: expected 2, got 1
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "smpe_paper/numba_test.py", line 18, in <module>
    print(p.map(add2, [1, 2, 3]))  # TypeError
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/root/.pyenv/versions/3.7.3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
TypeError: not enough arguments: expected 2, got 1
```

Expected output:
```
[2, 3, 4]
2
[2, 3, 4]
```

Enviroment:
- Python 3.7.4
- Numba 0.46.0
- ubuntu:latest on Docker

**Comment by esc** [comment]
I can reproduce this locally.

**Comment by seibert** [comment]
current hypothesis is that somehow pickling the numba function is losing the default argument?  Need to investigate this further.

**Comment by alihalabyah** [comment]
Any updates?

**Comment by esc** [comment]
@alihalabyah thanks for circling back on this, unfortunately it seems we haven't yet had the time to look into this.

**Comment by esc** [comment]
So the exception itself is raised in the dispatcher:

https://github.com/numba/numba/blob/master/numba/_dispatcher.c#L413
