### ISSUE TITLE
pow operator unsupported on np arrays

### ISSUE THREAD

**Issue by pitrou** [numba/numba#489]
```
>>> arr = np.arange(10, dtype=np.int32)
>>> @jit(nopython=True)
... def sq(a):
...     return a ** 2
... 
>>> sq(arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/numba/numba/dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "/home/antoine/numba/numba/dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "/home/antoine/numba/numba/dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "/home/antoine/numba/numba/compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "/home/antoine/numba/numba/compiler.py", line 120, in compile_bytecode
    locals)
  File "/home/antoine/numba/numba/compiler.py", line 283, in type_inference_stage
    infer.propagate()
  File "/home/antoine/numba/numba/typeinfer.py", line 312, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 110, in propagate
    constrain(context, typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 181, in __call__
    self.resolve(context, typevars, fnty=self.func)
  File "/home/antoine/numba/numba/typeinfer.py", line 174, in resolve
    raise TypingError(msg, loc=self.loc)
numba.typeinfer.TypingError: Undeclared **(array(int32, 1d, C), int32)
File "<stdin>", line 3
```

**Comment by pitrou** [comment]
This now works ok.
