### ISSUE TITLE
TypingError raised with float32 arguments to np.interp

### ISSUE THREAD

**Issue by watsonjj** [numba/numba#4890]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When using njit-compiled `np.interp` with float32 arguments, a TypingError is raised unless at least one of either `xp` or `fp` are float64:

```python
from numba import njit
import numpy as np

@njit
def interp(x, xp, fp):
   return np.interp(x, xp, fp)

xp = np.arange(10, dtype=np.float64)
fp = (xp ** 2).astype(np.float64)
x = np.linspace(2, 3, 10, dtype=np.float32)
interp(x, xp, fp)  # WORKS

xp = np.arange(10, dtype=np.float32)
fp = (xp ** 2).astype(np.float64)
x = np.linspace(2, 3, 10, dtype=np.float32)
interp(x, xp, fp)  # WORKS

xp = np.arange(10, dtype=np.float64)
fp = (xp ** 2).astype(np.float32)
x = np.linspace(2, 3, 10, dtype=np.float32)
interp(x, xp, fp)  # WORKS

xp = np.arange(10, dtype=np.float32)
fp = (xp ** 2).astype(np.float32)
x = np.linspace(2, 3, 10, dtype=np.float32)
interp(x, xp, fp)  # ERROR
```

Error output:

```
In [17]: xp = np.arange(10, dtype=np.float32)
    ...: fp = (xp ** 2).astype(np.float32)
    ...: x = np.linspace(2, 3, 10, dtype=np.float32)
    ...: interp(x, xp, fp)  # ERROR
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-17-431cf7dde0e1> in <module>
      2 fp = (xp ** 2).astype(np.float32)
      3 x = np.linspace(2, 3, 10, dtype=np.float32)
----> 4 interp(x, xp, fp)  # ERROR

~/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345
    346         argtypes = []

~/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function interp at 0x1089840e0>) with argument(s) of type(s): (array(float32, 1d, C), array(float32, 1d, C), array(float32, 1d, C))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x6235bab90>) with argument(s) of type(s): (array(float32, 1d, C), array(float32, 1d, C), array(float32, 1d, C), dtype(float64))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2248)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2248:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2250)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2250:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/typeinfer.py:951
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2248)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2248:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2250)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2250:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/typeinfer.py:951
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x6235bab90>)
[2] During: typing of call at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2365)


File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2365:
        def np_interp_impl(x, xp, fp):
            return inner(x, xp, fp, dtype)
            ^

    raised from /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/typeinfer.py:951
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x6235bab90>) with argument(s) of type(s): (array(float32, 1d, C), array(float32, 1d, C), array(float32, 1d, C), dtype(float64))
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2248)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2248:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2250)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2250:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/typeinfer.py:951
In definition 1:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(float32, 1d, C) and array(float64, 1d, C) for 'slopes', defined at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2248)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2248:
    def impl(x, xp, fp, dtype):
        <source elided>
            if lenxp <= lenx:
                slopes = (dy[1:] - dy[:-1]) / (dx[1:] - dx[:-1])
                ^

[1] During: typing of assignment at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2250)

File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2250:
    def impl(x, xp, fp, dtype):
        <source elided>
            else:
                slopes = np.empty(0, dtype=dtype)
                ^

    raised from /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/typeinfer.py:951
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function np_interp_impl_inner_factory.<locals>.impl at 0x6235bab90>)
[2] During: typing of call at /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py (2365)


File "../../../../opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/targets/arraymath.py", line 2365:
        def np_interp_impl(x, xp, fp):
            return inner(x, xp, fp, dtype)
            ^

    raised from /Users/Jason/opt/anaconda3/envs/cta/lib/python3.7/site-packages/numba-0.46.0-py3.7-macosx-10.9-x86_64.egg/numba/typeinfer.py:951
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function interp at 0x1089840e0>)
[2] During: typing of call at <ipython-input-8-52ff25153033> (6)


File "<ipython-input-8-52ff25153033>", line 6:
def interp(x, xp, fp):
   return np.interp(x, xp, fp)
   ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

**Comment by seibert** [comment]
It seems that this type combination was not included when interp was added.  That seems like a reasonable thing to add.

**Comment by esc** [comment]
@seibert thanks for following up with this, I have labeled the issue accordingly as 'feature_request'.

**Comment by EPronovost** [comment]
Is this issue closed?

**Comment by esc** [comment]
I just tried this on current master (0.50.0dev0-7-g917f582433). And it seems fine. Hence, closing this. @EPronovost thanks for the ping!
