### ISSUE TITLE
Using string[:] data types as class attributes.

### ISSUE THREAD

**Issue by asett0** [numba/numba#4894]
Currently trying to use `numba` version `0.45.1` with classes in Python and trying to use an array of strings as a class attribute.

Below are the class definitions
```
from numba import jitclass, int8, njit, optional
from numba.types import string, DictType


A_spec = [('x', int8), ('y', int8), ('z', optional(string[:]))]


@jitclass(A_spec)
class A:
    def __init__(self, x: int, str_arg: str = None):
        self.x = x
        self.y = self.x**2
        self.z = str_arg


A_instance = A.class_type.instance_type


@njit
def scale(a_obj: A, s: int):
    return A(a_obj.x*s, a_obj.z)


B_spec = [("a_list", DictType(string, A_instance))]


@jitclass(B_spec)
class B:
    def __init__(self, a_obj: A):
        self.a_list = {"b_1": scale(a_obj, 1), "b_2": scale(
            a_obj, 2), "b_3": scale(a_obj, 3)}
```
and below are the functions that take the corresponding objects and return something. 

```
from test_classes import A, B
from numba import njit

@njit
def f_on_a(a_obj_1: A) -> A:
    return a_obj_1.x + a_obj_1.y


@njit
def f_on_b(b_obj: B):
    s = 0
    for a in b_obj.a_list.values():
        s += f_on_a(a)
    return s


a_1 = A(2, ["you", "poo", "crew"])
a_2 = A(3)

print(f_on_a(a_1))

print(f_on_a(a_2))

b_1 = B(a_1)
b_2 = B(a_2)

print(f_on_b(b_1))

print(f_on_b(b_2))
```

Before I was testing this example where `A.z` was just a string and everything was working fine. When I try to use an array of strings I get the following error. 

```
$ python algorithm/test_calc.py
Traceback (most recent call last):
  File "algorithm/test_calc.py", line 32, in <module>
    a_1 = A(2, ["you","poo","crew"])
  File "C:\Anaconda3\lib\site-packages\numba\jitclass\base.py", line 126, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "C:\Anaconda3\lib\site-packages\numba\dispatcher.py", line 376, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Anaconda3\lib\site-packages\numba\dispatcher.py", line 343, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Anaconda3\lib\site-packages\numba\six.py", line 658, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x000002ED16860748>.
?[1m?[1mFailed in nopython mode pipeline (step: nopython mode backend)
?[1m?[1mCannot cast reflected list(unicode_type) to OptionalType(array(unicode_type, 1d, A)) i.e. the type 'array(unicode_type, 1d, A) or None': %".96" = load {i8*, i8*}, {i8*, i8*}* %"str_arg"
?[1m
File "algorithm\test_classes.py", line 15:?[0m
?[1m    def __init__(self, x: int, str_arg: str = None):
        <source elided>
        self.y = self.x**2
?[1m        self.z = str_arg
?[0m        ?[1m^?[0m?[0m
?[0m
?[0m?[1m[1] During: lowering "(self).z = str_arg" at C:\repos\FSOx-Algorithm\algorithm\test_classes.py (15)?[0m
?[0m?[1m[2] During: resolving callee type: jitclass.A#2ed16002dc8<x:int8,y:int8,z:OptionalType(array(unicode_type, 1d, A)) i.e. the type 'array(unicode_type, 1d, A) or None'>?[0m
?[0m?[1m[3] During: typing of call at <string> (3)
?[0m
Enable logging at debug level for details.
?[1m
File "<string>", line 3:?[0m
?[1m<source missing, REPL/exec in use?>?[0m

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

Looks like this is the error but I'm not too sure where to go from here.
```
Cannot cast reflected list(unicode_type) to OptionalType(array(unicode_type, 1d, A)) i.e. the type 'array(unicode_type, 1d, A) or None'
```

What is the standard approach for using arrays of strings with `numba`?

**Comment by hmc-cs-mdrissi** [comment]
If you want to use a list of strings you can use typed.List. string[:] sounds like you want a numpy array of strings. For your jitclass's spec the right thing would be something like,
```

from numba.types import List, string, optional

A_spec = [('x', int8), ('y', int8), ('z', optional(List(string)))]


```

As for creating a typed list for the list ["a", "b", "c"], you can do something like
```

ls = typed.List()
ls.append("a")
ls.append("b")
ls.append("c")

```

Practically if you commonly want to pass normal lists to a function that takes typed lists, I'd write a small helper function to convert between the two.

**Comment by asett0** [comment]
@hmc-cs-mdrissi thanks :) I got it working now using this example.
```
from test_classes import A, B
from numba import njit, typed
from numba.types import string


def convert(norm_list):
    numba_list = typed.List.empty_list(string)

    for e in norm_list:
        numba_list.append(e)

    return numba_list


@njit
def f_on_a(a_obj_1: A) -> A:
    return a_obj_1.x + a_obj_1.y


@njit
def f_on_b(b_obj: B):
    s = 0
    for a in b_obj.a_list.values():
        s += f_on_a(a)
    return s


a_1 = A(2, convert(["you", "poo", "crew"]))
a_2 = A(3)

print(f_on_a(a_1))

print(f_on_a(a_2))

b_1 = B(a_1)
b_2 = B(a_2)

print(f_on_b(b_1))

print(f_on_b(b_2))
```
Won't using this helper function be really inefficient though? We essentially have to append every item of the list every time we pass in a list argument. Is there no way to type cast the list to a `numba` list?

**Comment by asett0** [comment]
Oh and these were the changes I made to the classes.
```
from numba import jitclass, int8, njit, optional
from numba.types import string, DictType, ListType
from typing import List


A_spec = [('x', int8), ('y', int8), ('z', optional(ListType(string)))]


@jitclass(A_spec)
class A:
    def __init__(self, x: int, str_arg: List[str] = None):
        self.x = x
        self.y = self.x**2
        self.z = str_arg


A_instance = A.class_type.instance_type


@njit
def scale(a_obj: A, s: int):
    return A(a_obj.x*s, a_obj.z)


B_spec = [("a_list", DictType(string, A_instance))]


@jitclass(B_spec)
class B:
    def __init__(self, a_obj: A):
        self.a_list = {"b_1": scale(a_obj, 1), "b_2": scale(
            a_obj, 2), "b_3": scale(a_obj, 3)}
```

**Comment by esc** [comment]
@asett0 thanks for asking about this and @hmc-cs-mdrissi thanks for stepping up to provide an answer. As for the inefficiency of the typed list, yes the helper function will involve copying all the values from the Python (or regular) list to a Numba typed list, which, depending on the size of the list may incur a significant and noticeable performance overhead. It isn't possible to type cast a Python list to a Numba typed list because the underlying storage models differ significantly. There is however a pull-request currently in flight at #4883 which will enable automatic conversion (a.k.a. unboxing) of a Python list into a Numba typed list so you won't have to write the converter. Also, the Numba typed list has a very, very similar API as the Python list so you can actually use it as a replacement. For example, when you initialize your list, use a typed list instead and you won't have to incur the conversion.

I hope that answers all the open questions here, but do let me know if I have missed something.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
