### ISSUE TITLE
np.copy unsupported

### ISSUE THREAD

**Issue by pitrou** [numba/numba#490]
I'm not sure this one is very important.

```
>>> @jit(nopython=True)
... def np_copy(a):
...     return np.copy(a, 'F')
... 
>>> np_copy(np.arange(10, dtype=np.float64))
Traceback (most recent call last):
  File "/home/antoine/numba/numba/typeinfer.py", line 110, in propagate
    constrain(context, typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 197, in __call__
    attrty = context.resolve_getattr(value=ty, attr=self.attr)
  File "/home/antoine/numba/numba/typing/context.py", line 78, in resolve_getattr
    return attrinfo.resolve(value, attr)
  File "/home/antoine/numba/numba/typing/templates.py", line 220, in resolve
    raise NotImplementedError(value, attr)
NotImplementedError: (Module(<module 'numpy' from '/home/antoine/34/lib/python3.4/site-packages/numpy/__init__.py'>), 'copy')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/numba/numba/dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "/home/antoine/numba/numba/dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "/home/antoine/numba/numba/dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "/home/antoine/numba/numba/compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "/home/antoine/numba/numba/compiler.py", line 120, in compile_bytecode
    locals)
  File "/home/antoine/numba/numba/compiler.py", line 283, in type_inference_stage
    infer.propagate()
  File "/home/antoine/numba/numba/typeinfer.py", line 312, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 114, in propagate
    raise TypingError("Internal error:\n%s" % e, constrain.loc)
numba.typeinfer.TypingError: Internal error:
(Module(<module 'numpy' from '/home/antoine/34/lib/python3.4/site-packages/numpy/__init__.py'>), 'copy')
File "<stdin>", line 3
```

**Comment by pitrou** [comment]
This is now supported except for the `order` argument.
