### ISSUE TITLE
transposition fails type inference

### ISSUE THREAD

**Issue by pitrou** [numba/numba#491]
```
>>> @jit(nopython=True)
... def transpose(a):
...     return a.T
... 
>>> arr = np.arange(10).reshape((2, 5))
>>> arr
array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])
>>> transpose(arr)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/numba/numba/dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "/home/antoine/numba/numba/dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "/home/antoine/numba/numba/dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "/home/antoine/numba/numba/compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "/home/antoine/numba/numba/compiler.py", line 120, in compile_bytecode
    locals)
  File "/home/antoine/numba/numba/compiler.py", line 284, in type_inference_stage
    typemap, restype, calltypes = infer.unify()
  File "/home/antoine/numba/numba/typeinfer.py", line 326, in unify
    if unified == types.pyobject:
  File "/home/antoine/numba/numba/types.py", line 40, in __eq__
    return self.name == other.name
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by pitrou** [comment]
This certainly works now, closing.
