### ISSUE TITLE
Invalid use of Function(<built-in function pow>) with argument(s) of type(s): (Literal[int](10), int64, Literal[int](1000000007))

### ISSUE THREAD

**Issue by neel112358** [numba/numba#4913]
```
from numba import njit, jit
from tqdm import tqdm
fib=[1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,1597,2584,4181,6765,10946,17711,28657,46368,75025,121393,196418,317811,514229,832040,1346269,2178309,3524578,5702887,9227465,14930352,24157817,39088169,63245986,102334155,165580141,267914296,433494437,701408733,1134903170,1836311903,2971215073,4807526976,7778742049,12586269025,20365011074,32951280099,53316291173,86267571272,139583862445,225851433717,365435296162,591286729879,956722026041,1548008755920,2504730781961,4052739537881,6557470319842,10610209857723,17167680177565,27777890035288,44945570212853,72723460248141,117669030460994,190392490709135,308061521170129,498454011879264,806515533049393,1304969544928657,2111485077978050,3416454622906707,5527939700884757,8944394323791464,14472334024676221,23416728348467685,37889062373143906,61305790721611591,99194853094755497,160500643816367088,259695496911122585,420196140727489673,679891637638612258,1100087778366101931,1779979416004714189]
m=1000000007
t=0
@njit(fastmath=True)
def s(f):
	tt=0
	x=0
	if f//9!=0:
		tt=45
		x=9
	for i in range(1,f//9):
		tt=(tt+((45*pow(10,i,m))%m+(x*9)%m)%m)%m
		x=x*10+9
	xx=f%9
	tt=(tt+(((xx*(xx+1))/2)%m+(x*xx)%m)%m)%m
	# print(tt)
	return tt

for f in tqdm(fib):
	t=(t+s(f))%m
print(t)
```
Here is a full traceback while running this code :

```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    t=(t+s(f))%m
  File "C:\Users\Neel\Anaconda3\envs\env_1\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Neel\Anaconda3\envs\env_1\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\Neel\Anaconda3\envs\env_1\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function pow>) with argument(s) of type(s): (Literal[int](10), int64, Literal[int](1000000007))
Known signatures:
 * (float64, int64) -> float64
 * (float64, uint64) -> float64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<built-in function pow>)
[2] During: typing of call at test.py (15)


File "test.py", line 15:
def s(f):
    <source elided>
        for i in range(1,f//9):
                tt=(tt+((45*math.pow(10,i,m))%m+(x*9)%m)%m)%m
  ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```
I presently have tried njit & jit both with functions pow, numpy.pow and math.pow, none of which work.

**Comment by rjenc29** [comment]
Hi, I think the error means that `pow` supports the 2-argument form only.

Maybe substitute this:

```python
pow(10,i,m)
```

With...
```python
pow(10, i) % m
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I think @rjenc29's assessment is correct, this is a feature request for the three argument form of `pow`.

**Comment by filips123** [comment]
I would also support for the third argument in `pow`. It is useful for calculating modular multiplicative inverse.

Substituting `pow(a, -1, n)` with `pow(a, -1) % n` won't work for this use-case, as `pow` will only calculate the normal inverse and apply the modulo afterwards.
