### ISSUE TITLE
array copy constructor unsupported

### ISSUE THREAD

**Issue by pitrou** [numba/numba#492]
```
>>> @jit(nopython=True)
... def convert(a):
...     return np.array(a, dtype=np.double)
... 
>>> arr = np.arange(10)
>>> arr
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> convert(arr)
Traceback (most recent call last):
  File "/home/antoine/numba/numba/typeinfer.py", line 110, in propagate
    constrain(context, typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 197, in __call__
    attrty = context.resolve_getattr(value=ty, attr=self.attr)
  File "/home/antoine/numba/numba/typing/context.py", line 78, in resolve_getattr
    return attrinfo.resolve(value, attr)
  File "/home/antoine/numba/numba/typing/templates.py", line 220, in resolve
    raise NotImplementedError(value, attr)
NotImplementedError: (Module(<module 'numpy' from '/home/antoine/34/lib/python3.4/site-packages/numpy/__init__.py'>), 'array')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/numba/numba/dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "/home/antoine/numba/numba/dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "/home/antoine/numba/numba/dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "/home/antoine/numba/numba/compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "/home/antoine/numba/numba/compiler.py", line 120, in compile_bytecode
    locals)
  File "/home/antoine/numba/numba/compiler.py", line 283, in type_inference_stage
    infer.propagate()
  File "/home/antoine/numba/numba/typeinfer.py", line 312, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 114, in propagate
    raise TypingError("Internal error:\n%s" % e, constrain.loc)
numba.typeinfer.TypingError: Internal error:
(Module(<module 'numpy' from '/home/antoine/34/lib/python3.4/site-packages/numpy/__init__.py'>), 'array')
File "<stdin>", line 3
```

**Comment by seibert** [comment]
Copy constructor and np.copy were added to Numba later.
