### ISSUE TITLE
CUDA guvectorize target does not copy back modified input arrays

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#4952]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This is either a documentation bug or an implementation bug - it would be nice to think of it as an implementation bug, because it would be good to support this use case in the CUDA target.

If I write a gufunc that writes to the inputs, then the writes to the input are reflected in the array when using the CPU target. However, on the CUDA target, writes to inputs are "lost". In the example below, writing to `pos` on CUDA does not affect the `pos_cuda` array after execution finishes: 

```python
import numpy as np
from numba import guvectorize, float32

@guvectorize([(float32[:], float32[:])], '()->()')
def init_cpu(pos, accel):
    pos[0] = 6.5
    accel[0] = 4.2 * pos[0]

@guvectorize([(float32[:], float32[:])], '()->()', target='cuda')
def init_cuda(pos, accel):
    pos[0] = 6.5
    accel[0] = 4.2 * pos[0]

pos_cpu = np.zeros( shape=(50, 50), dtype=np.float32 )
pos_cuda = np.zeros( shape=(50, 50), dtype=np.float32 )

accel_cpu = init_cpu(pos_cpu)
accel_cuda = init_cuda(pos_cuda)

print(pos_cpu)
print(pos_cuda)

print(accel_cpu)
print(accel_cuda)

assert np.isclose(accel_cpu, accel_cuda).all()
assert np.isclose(pos_cpu, pos_cuda).all()
```

The output is:

```
[[6.5 6.5 6.5 ... 6.5 6.5 6.5]
 [6.5 6.5 6.5 ... 6.5 6.5 6.5]
 [6.5 6.5 6.5 ... 6.5 6.5 6.5]
 ...
 [6.5 6.5 6.5 ... 6.5 6.5 6.5]
 [6.5 6.5 6.5 ... 6.5 6.5 6.5]
 [6.5 6.5 6.5 ... 6.5 6.5 6.5]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 ...
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]]
[[27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 ...
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]
 [27.3 27.3 27.3 ... 27.3 27.3 27.3]]
Traceback (most recent call last):
  File "bug.py", line 27, in <module>
    assert np.isclose(pos_cpu, pos_cuda).all()
AssertionError
```

Additionally I tried writing the layout string as `(),()`, in case that would make the CUDA target get the idea (noting that the reference manual states that you should write a signature that way if there are no outputs, implying that it is legal to write to inputs: http://numba.pydata.org/numba-doc/latest/reference/jit-compilation.html#numba.guvectorize). However, I then found I ran into #2011 - only one output is supported on CUDA at the moment:

```
Traceback (most recent call last):
  File "bug.py", line 9, in <module>
    @guvectorize([(float32[:], float32[:])], '(),()', target='cuda')
  File "/home/nfs/gmarkall/numbadev/numba/numba/npyufunc/decorators.py", line 177, in wrap
    guvec = GUVectorize(func, signature, **kws)
  File "/home/nfs/gmarkall/numbadev/numba/numba/npyufunc/decorators.py", line 50, in __new__
    targetoptions=kws)
  File "/home/nfs/gmarkall/numbadev/numba/numba/npyufunc/deviceufunc.py", line 446, in __init__
    assert len(self.outputsig) == 1, "only support 1 output"
AssertionError: only support 1 output
```

Possible ways to resolve this:

1. Document that you can't write to inputs on CUDA, and raise an error when compiling a function that writes to an input for the CUDA target.
2. Detect when inputs are written to on the CUDA target, and copy them back.

I'd prefer to fix this with option 2, but I have yet to scope out how difficult that would be (it would probably fix #2011 in conjunction as well).

**Comment by seibert** [comment]
I think we need to go with option 1, because AFAIK this only works on accident on the CPU.  The gufunc machinery in NumPy (which Numba still relies on with the CPU target) can copy inputs to temporary buffers, for example to upcast things, in which case changes to inputs will be lost.

Example where the ufunc expects float64, but is passed a float32 array, so in-place updates are lost to the temporary buffer NumPy created:
```
@guvectorize([(float64[:], float64[:])], '()->()')
def init_cpu_fail(pos, accel):
    pos[0] = 6.5
    accel[0] = 4.2 * pos[0]

pos_cpu = np.zeros( shape=(50, 50), dtype=np.float32 )
accel_cpu = init_cpu_fail(pos_cpu)

print(pos_cpu)
```
output
```
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
```

**Comment by gmarkall** [comment]
Thanks for the thoughts! A PR to go for option 1 is in #4957.

**Comment by gmarkall** [comment]
Now that #4957 is merged, this is half-resolved - an error still needs to be raised when writing to an input when using the CUDA target.
