### ISSUE TITLE
pip install numba fails on windows with python 3.8 https://github.com/numba/numba/issues/2918

### ISSUE THREAD

**Issue by sweeneyde** [numba/numba#4976]
Very similar to: https://github.com/numba/numba/issues/2918, the following happens when I try to use `pip install numba` on Windows 10 with Python 3.8.0:

```
PS C:\Users\sween\Desktop> pip install numba
Collecting numba
  Using cached https://files.pythonhosted.org/packages/33/6f/47d87ded23f3d1aa1e221d75278caf427e8da80649c14312172857bad64f/numba-0.46.0.tar.gz
Collecting llvmlite>=0.30.0dev0
  Using cached https://files.pythonhosted.org/packages/8b/b0/df26861e6ce2fc91c8bb93ea808fa2e631ee8a29fc4c3bc96626b78dae74/llvmlite-0.30.0.tar.gz
Requirement already satisfied: numpy in c:\program files (x86)\python38b1\lib\site-packages (from numba) (1.17.3)
Installing collected packages: llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\program files (x86)\python38b1\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sween\\AppData\\Local\\Temp\\pip-install-2yrxdn_4\\llvmlite\\setup.py'"'"'; __file__='"'"'C:\\Users\\sween\\AppData\\Local\\Temp\\pip-install-2yrxdn_4\\llvmlite\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sween\AppData\Local\Temp\pip-record-pf51nvdi\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\
    Complete output (27 lines):
    running install
    running build
    got version from file C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\llvmlite/_version.py {'version': '0.30.0', 'full': '3cad106e2f727bc400f1b426ce306b1e30e34b72'}
    running build_ext
    c:\program files (x86)\python38b1\python.exe C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\ffi\build.py
    Trying generator 'Visual Studio 14 2015 Win64'
    Traceback (most recent call last):
      File "C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\ffi\build.py", line 168, in <module>
        main()
      File "C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\ffi\build.py", line 156, in main
        main_win32()
      File "C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\sween\AppData\Local\Temp\pip-install-2yrxdn_4\llvmlite\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "c:\program files (x86)\python38b1\lib\subprocess.py", line 359, in check_call
        retcode = call(*popenargs, **kwargs)
      File "c:\program files (x86)\python38b1\lib\subprocess.py", line 340, in call
        with Popen(*popenargs, **kwargs) as p:
      File "c:\program files (x86)\python38b1\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "c:\program files (x86)\python38b1\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
    error: command 'c:\\program files (x86)\\python38b1\\python.exe' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python38b1\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\sween\\AppData\\Local\\Temp\\pip-install-2yrxdn_4\\llvmlite\\setup.py'"'"'; __file__='"'"'C:\\Users\\sween\\AppData\\Local\\Temp\\pip-install-2yrxdn_4\\llvmlite\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\sween\AppData\Local\Temp\pip-record-pf51nvdi\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by stuartarchibald** [comment]
@sweeneyde thanks for the report. I think the issue here may be that of using Python 3.8, which is not supported on any released version of Numba (cf. https://github.com/numba/numba/blob/master/README.rst). The next release of Numba (0.47.0, a release candidate for which will hopefully be out this week) does support Python 3.8. Can you reproduce this problem using Python 3.7?
