### ISSUE TITLE
`numba.typed.List` does not work with elements of type `typing.NamedTuple`, but works with `collections.namedtuple`

### ISSUE THREAD

**Issue by poroale** [numba/numba#5008]
I'm having the following issue with numba 0.46.0 on Python 3.6.

Using the `namedtuple` from `collections` works fine with numba typed list
```
import numba
from collections import namedtuple

Point = namedtuple("Point", "x y")
tmp_l = numba.typed.List()
tmp_l.append(Point(1, "jee"))
tmp_l.append(Point(2, "juu"))
```

but the `NamedTuple` from `typing` does not
```
import numba
from typing import NamedTuple

class Point(NamedTuple):
    x: int
    y: str

tmp_l = numba.typed.List()
tmp_l.append(Point(10, "jee"))
tmp_l.append(Point(11, "juu"))
```

<details><summary>stack trace</summary>
<p>

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/folder/venv/lib/python3.6/site-packages/numba/typed/typedlist.py", line 223, in append
    _append(self, item)
  File "/home/folder/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/folder/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/home/folder/venv/lib/python3.6/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7f6f36fe6cf8>.
Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast Point(int64, unicode_type) to Point(int64, unicode_type): %".30" = load {i64, {i8*, i64, i32, i32, i64, i8*, i8*}}, {i64, {i8*, i64, i32, i32, i64, i8*, i8*}}* %"item"
File "venv/lib/python3.6/site-packages/numba/listobject.py", line 434:
    def impl(l, item):
        casteditem = _cast(item, itemty)
        ^
[1] During: lowering "$0.4 = call $0.1(item, $0.3, func=$0.1, args=[Var(item, /home/folder/venv/lib/python3.6/site-packages/numba/listobject.py (434)), Var($0.3, /home/folder/venv/lib/python3.6/site-packages/numba/listobject.py (434))], kws=(), vararg=None)" at /home/folder/venv/lib/python3.6/site-packages/numba/listobject.py (434)
[2] During: resolving callee type: BoundFunction((<class 'numba.types.containers.ListType'>, 'append') for ListType[Point(int64, unicode_type)])
[3] During: typing of call at /home/folder/venv/lib/python3.6/site-packages/numba/typed/typedlist.py (39)
Enable logging at debug level for details.
File "venv/lib/python3.6/site-packages/numba/typed/typedlist.py", line 39:
def _append(l, item):
    l.append(item)
    ^
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.
To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/latest/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html
For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new
```

</p>
</details>

Is this expected? I was wondering because the `typing.NamedTuple` works otherwise in `nopython` mode:
```
import numba
from typing import NamedTuple

class Point(NamedTuple):
    x: int
    y: str

p = Point(11, "juu")

@numba.njit()
def test(l):
    print(p.x)
    print(p.y)

test(p)
```

**Comment by poroale** [comment]
My bad, seemed to be some sort of environment issue, as restarting Python fixed the issue.
