### ISSUE TITLE
Indexing global variable inside list comprehension leads to LoweringError

### ISSUE THREAD

**Issue by poroale** [numba/numba#5041]
There seems to be some issue with the indexing of the global variable inside a list comprehension?
```
import numba as nb

from typing import NamedTuple, List


class Shift(NamedTuple):
    start_time: int
    end_time: int
    work_hours: int


shifts = nb.typed.List()
shifts.append(Shift(0, 10, 10))
shifts.append(Shift(0, 2, 3))


@nb.njit()
def nb_sum(tpl: List[int]) -> int:
    tmp_sum = 0
    for val in tpl:
        tmp_sum += val
    return tmp_sum


@nb.njit()
def check_worker_feasibility(assigned_shifts, max_work_hours: int) -> bool:
    work_hours = nb_sum([shifts[i].work_hours for i in assigned_shifts])
    if work_hours > max_work_hours:
        return False

    return True


assigned_shifts = nb.typed.List()
assigned_shifts.append(1)
check_worker_feasibility(assigned_shifts, 100)
```

<details><summary>stack trace</summary>
<p>

```
Traceback (most recent call last):
  File "/test/venv/lib/python3.6/site-packages/numba/targets/base.py", line 499, in get_constant_generic
    impl = self._get_constants.find((ty,))
  File "/test/venv/lib/python3.6/site-packages/numba/targets/base.py", line 50, in find
    out = self._find(sig)
  File "/test/venv/lib/python3.6/site-packages/numba/targets/base.py", line 59, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.targets.base.OverloadSelector object at 0x7f2d924a4240>, (ListType[Shift(int64 x 3)],))
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/test/venv/lib/python3.6/site-packages/numba/errors.py", line 717, in new_error_context
    yield
  File "/test/venv/lib/python3.6/site-packages/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/test/venv/lib/python3.6/site-packages/numba/lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/test/venv/lib/python3.6/site-packages/numba/lowering.py", line 460, in lower_assign
    value.value)
  File "/test/venv/lib/python3.6/site-packages/numba/targets/base.py", line 502, in get_constant_generic
    raise NotImplementedError("Cannot lower constant of type '%s'" % (ty,))
NotImplementedError: Cannot lower constant of type 'ListType[Shift(int64 x 3)]'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 46, in <module>
  File "/test/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/test/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/test/venv/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/test/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/test/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/test/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/test/venv/lib/python3.6/site-packages/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/test/venv/lib/python3.6/site-packages/numba/compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)
  File "/test/venv/lib/python3.6/site-packages/numba/compiler.py", line 326, in compile_extra
    return self._compile_bytecode()
  File "/test/venv/lib/python3.6/site-packages/numba/compiler.py", line 385, in _compile_bytecode
    return self._compile_core()
  File "/test/venv/lib/python3.6/site-packages/numba/compiler.py", line 365, in _compile_core
    raise e
  File "/test/venv/lib/python3.6/site-packages/numba/compiler.py", line 356, in _compile_core
    pm.run(self.state)
  File "/test/venv/lib/python3.6/site-packages/numba/compiler_machinery.py", line 328, in run
    raise patched_exception
  File "/test/venv/lib/python3.6/site-packages/numba/compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "/test/venv/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/test/venv/lib/python3.6/site-packages/numba/compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/test/venv/lib/python3.6/site-packages/numba/compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "/test/venv/lib/python3.6/site-packages/numba/typed_passes.py", line 380, in run_pass
    NativeLowering().run_pass(state) # TODO: Pull this out into the pipeline
  File "/test/venv/lib/python3.6/site-packages/numba/typed_passes.py", line 325, in run_pass
    lower.lower()
  File "/test/venv/lib/python3.6/site-packages/numba/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "/test/venv/lib/python3.6/site-packages/numba/lowering.py", line 220, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/test/venv/lib/python3.6/site-packages/numba/lowering.py", line 245, in lower_function_body
    self.lower_block(block)
  File "/test/venv/lib/python3.6/site-packages/numba/lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/test/venv/lib/python3.6/site-packages/numba/errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/test/venv/lib/python3.6/site-packages/numba/six.py", line 669, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot lower constant of type 'ListType[Shift(int64 x 3)]'
File "<input>", line 37:
<source missing, REPL/exec in use?>
[1] During: lowering "$6.2.14 = global(shifts: [Shift(start_time=0, end_time=10, work_hours=10), Shift(start_time=0, end_time=2, work_hours=3)])" at <input> (37)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.
Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new
If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba
Thanks in advance for your help in improving Numba!
```

</p>
</details>

**Comment by stuartarchibald** [comment]
Thanks for the report. The reason for the problem is that global level mutable containers should not be accepted for compilation as [Numba treats globals as compile time constants](http://numba.pydata.org/numba-doc/latest/user/faq.html#numba-doesn-t-seem-to-care-when-i-modify-a-global-variable). What should happen is that this is spotted at type inference time and reported to the user, opposed to a lowering error above. This is a smaller reproducer:
```python
from numba import njit, typed
import numpy as np

shifts = typed.List()
[shifts.append(i) for i in range(5)]

@njit()
def ff():
    x = typed.List()
    for i in shifts:
        x.append(i)

ff()
```
CC @esc

**Comment by stuartarchibald** [comment]
NOTE: updated title to reflect underlying issue.

**Comment by poroale** [comment]
Ah, I see. I noticed that my example contained quite a lot of unnecessary code to reproduce the issue, but good that you caught the essentials. I'll switch to a tuple to avoid the issue with the mutable container. Thank you for the prompt reply.

**Comment by stuartarchibald** [comment]
> Ah, I see. I noticed that my example contained quite a lot of unnecessary code to reproduce the issue, but good that you caught the essentials. I'll switch to a tuple to avoid the issue with the mutable container. Thank you for the prompt reply.

Great, thanks for reporting back, `tuple` should work fine.

**Comment by esc** [comment]
Note to self, look at: line 1051 of `typeinfer.py`

**Comment by esc** [comment]
Fix in: #5078
