### ISSUE TITLE
Generator comprehensions unsupported

### ISSUE THREAD

**Issue by pitrou** [numba/numba#505]
```
>>> @jit
... def f():
...     for i in (x * 2 for x in range(5)):
...         return i
...
>>> f()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numba\dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "numba\dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "numba\dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "numba\compiler.py", line 90, in compile_extra
    bc = bytecode.ByteCode(func=func)
  File "numba\bytecode.py", line 296, in __init__
    table = utils.SortedMap(ByteCodeIter(code))
  File "numba\utils.py", line 46, in __init__
    for i, (k, v) in enumerate(sorted(seq)):
  File "numba\bytecode.py", line 216, in next
    raise NotImplementedError(ts % tv)
NotImplementedError: offset=6 opcode=84 opname=MAKE_FUNCTION
```

**Comment by stuartarchibald** [comment]
If anyone looks for this, under at least Numba 0.37 and greater this works (list comp):
```
from numba import njit
@njit
def f():
    for i in [x * 2 for x in range(5)]:
        return i
f()
```

**Comment by sklam** [comment]
As of Numba 0.48.0dev0, an ``UnsupportedError`` is raised:

```
UnsupportedError: Failed in nopython mode pipeline (step: inline calls to locally defined closures)
The use of yield in a closure is unsupported.

File "<ipython-input-34-71bef5ceab8e>", line 4:
def f():
    <source elided>
    c = 0
    for i in (x * 2 for x in range(5)):
```
