### ISSUE TITLE
ValueError: Argument types for wrap_index must match in @njit(parallel=True) when using int32 as index

### ISSUE THREAD

**Issue by flying-sheep** [numba/numba#5056]
This should work:

```py
import numba
import numpy as np

@numba.njit(parallel=True)
def test(data, indptr):
    sums = np.zeros((indptr.size - 1), dtype=data.dtype)
    for i in numba.prange(indptr.size - 1):
        start, end = indptr[i], indptr[i + 1]
        sums[i] = np.sum(data[start:end])
    return sums.reshape((indptr.size - 1, 1))

test(np.array([.3, .4, .5, .6]), np.array([0, 2, 4], dtype=np.int32))
```

But I get:

```pytb
Traceback (most recent call last):
  File "/home/phil/.PyCharm2019.3/config/scratches/scratch_1.py", line 12, in <module>
    test(np.array([.3, .4, .5, .6]),np.array([0, 2, 4], dtype=np.int32))
  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/usr/lib/python3.8/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<intrinsic wrap_index>) with argument(s) of type(s): (int32, int64)
 * parameterized
In definition 0:
    ValueError: Argument types for wrap_index must match
    raised from /usr/lib/python3.8/site-packages/numba/array_analysis.py:72
In definition 1:
    ValueError: Argument types for wrap_index must match
    raised from /usr/lib/python3.8/site-packages/numba/array_analysis.py:72
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<intrinsic wrap_index>)
[2] During: typing of call at /home/phil/.PyCharm2019.3/config/scratches/scratch_1.py (9)


File "scratch_1.py", line 9:
def test(data, indptr):
    <source elided>
        start, end = indptr[i], indptr[i + 1]
        sums[i] = np.sum(data[start:end])
        ^

[1] During: lowering "id=2[LoopNest(index_variable = parfor_index.50, range = (0, $34binary_subtract.15, 1))]{42: <ir.Block at /home/phil/.PyCharm2019.3/config/scratches/scratch_1.py (7)>}Var(parfor_index.50, scratch_1.py:7)" at /home/phil/.PyCharm2019.3/config/scratches/scratch_1.py (7)
```

Numba 0.47.0

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. Looks like this is a bug in array analysis used by the parallel CPU target.

**Comment by stuartarchibald** [comment]
Smaller reproducer:
```python
import numba
import numpy as np

@numba.njit(parallel=True)
def test(data):
    N = data.shape[0]
    sums = np.zeros(N)
    for i in numba.prange(N):
        sums[i] = np.sum(data[np.int32(0):np.int32(1)])
    return sums

test(np.arange(10.))
```
