### ISSUE TITLE
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)

### ISSUE THREAD

**Issue by bobbyskymind** [numba/numba#5076]
Could anyone please help on this error? Thanks.

![image](https://user-images.githubusercontent.com/51943800/72327664-80d75980-36ec-11ea-8ceb-92ccb7aa631d.png)

Error :
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 717, in new_error_context
    yield
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 465, in lower_assign
    return self.lower_expr(ty, value)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 1070, in lower_expr
    return self.context.build_list(self.builder, resty, castvals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\cpu.py", line 129, in build_list
    return listobj.build_list(self, builder, list_type, items)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 451, in build_list
    inst = ListInstance.allocate(context, builder, list_type, nitems)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 319, in allocate
    ok, self = cls.allocate_ex(context, builder, list_type, nitems)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 268, in allocate_ex
    self.zfill(self.size.type(0), nitems)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 222, in zfill
    cgutils.memset(builder, base, size, ir.IntType(8)(0))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cgutils.py", line 866, in memset
    builder.call(fn, [ptr, value, size, int32_t(0), bool_t(0)])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\llvmlite\ir\builder.py", line 841, in call
    cconv=cconv, tail=tail, fastmath=fastmath)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\llvmlite\ir\instructions.py", line 84, in __init__
    raise TypeError(msg)
TypeError: Type of #4 arg mismatch: i1 != i32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py", line 128, in preprocess
    img = illumination_compensation(img)
  File "C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py", line 203, in illumination_compensation
    estimate_light_distribution(width, height, erosion, cei, int_img)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 420, in _compile_for_args
    raise e
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 326, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 385, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 365, in _compile_core
    raise e
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 356, in _compile_core
    pm.run(self.state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 328, in run
    raise patched_exception
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typed_passes.py", line 380, in run_pass
    NativeLowering().run_pass(state) # TODO: Pull this out into the pipeline
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typed_passes.py", line 325, in run_pass
    lower.lower()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 220, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 245, in lower_function_body
    self.lower_block(block)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\six.py", line 669, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "data\preproc.py", line 232:
def estimate_light_distribution(width, height, erosion, cei, int_img):
    <source elided>
                if n <= 30:
                    h, e = [], []
                    ^

[1] During: lowering "$130.1 = build_list(items=[])" at C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py (232)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 63, in <module>
    ds.preprocess_partitions(input_size=input_size)
  File "C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\reader.py", line 45, in preprocess_partitions
    self.dataset[y]['dt'] = pool.map(partial(pp.preprocess, input_size=input_size), self.dataset[y]['dt'])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "data\preproc.py", line 232:
def estimate_light_distribution(width, height, erosion, cei, int_img):
    <source elided>
                if n <= 30:
                    h, e = [], []
                    ^

[1] During: lowering "$130.1 = build_list(items=[])" at C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py (232)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src>python main.py --source=bentham --transform
The bentham dataset will be transformed...
Partitions will be preprocessed...
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 717, in new_error_context
    yield
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 303, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 465, in lower_assign
    return self.lower_expr(ty, value)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 1070, in lower_expr
    return self.context.build_list(self.builder, resty, castvals)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\cpu.py", line 129, in build_list
    return listobj.build_list(self, builder, list_type, items)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 451, in build_list
    inst = ListInstance.allocate(context, builder, list_type, nitems)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 319, in allocate
    ok, self = cls.allocate_ex(context, builder, list_type, nitems)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 268, in allocate_ex
    self.zfill(self.size.type(0), nitems)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\targets\listobj.py", line 222, in zfill
    cgutils.memset(builder, base, size, ir.IntType(8)(0))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\cgutils.py", line 866, in memset
    builder.call(fn, [ptr, value, size, int32_t(0), bool_t(0)])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\llvmlite\ir\builder.py", line 841, in call
    cconv=cconv, tail=tail, fastmath=fastmath)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\llvmlite\ir\instructions.py", line 84, in __init__
    raise TypeError(msg)
TypeError: Type of #4 arg mismatch: i1 != i32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 44, in mapstar
    return list(map(*args))
  File "C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py", line 128, in preprocess
    img = illumination_compensation(img)
  File "C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py", line 203, in illumination_compensation
    estimate_light_distribution(width, height, erosion, cei, int_img)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 420, in _compile_for_args
    raise e
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 528, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 326, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 385, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 365, in _compile_core
    raise e
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler.py", line 356, in _compile_core
    pm.run(self.state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 328, in run
    raise patched_exception
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 319, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 281, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\compiler_machinery.py", line 268, in check
    mangled = func(compiler_state)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typed_passes.py", line 380, in run_pass
    NativeLowering().run_pass(state) # TODO: Pull this out into the pipeline
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\typed_passes.py", line 325, in run_pass
    lower.lower()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 220, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 245, in lower_function_body
    self.lower_block(block)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\lowering.py", line 260, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\six.py", line 669, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "data\preproc.py", line 231:
def estimate_light_distribution(width, height, erosion, cei, int_img):
    <source elided>
                if n <= 30:
                    h = []
                    ^

[1] During: lowering "$130.1 = build_list(items=[])" at C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py (231)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 63, in <module>
    ds.preprocess_partitions(input_size=input_size)
  File "C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\reader.py", line 45, in preprocess_partitions
    self.dataset[y]['dt'] = pool.map(partial(pp.preprocess, input_size=input_size), self.dataset[y]['dt'])
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\multiprocessing\pool.py", line 657, in get
    raise self._value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "data\preproc.py", line 231:
def estimate_light_distribution(width, height, erosion, cei, int_img):
    <source elided>
                if n <= 30:
                    h = []
                    ^

[1] During: lowering "$130.1 = build_list(items=[])" at C:\Users\Admin\Desktop\Bentham_Dataset\handwritten-text-recognition-master\src\data\preproc.py (231)

-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.46.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by stuartarchibald** [comment]
@bobbyskymind Thanks for the report. `TypeError: Type of #4 arg mismatch: i1 != i32` suggests you have `Numba 0.46` in use with `llvmlite=0.31`, these are incompatible releases. Please try either upgrading Numba to 0.47 or downgrading llvmlite to 0.30. Working combinations are Numba 0.46 + llvmlite 0.30, OR, Numba 0.47 + llvmlite 0.31. Thanks.

**Comment by bobbyskymind** [comment]
Thanks. Try with upgrading to Numba 0.47 works!

**Comment by stuartarchibald** [comment]
Great, thanks for confirming.
