### ISSUE TITLE
nopython mode fails to detect dead return point

### ISSUE THREAD

**Issue by pitrou** [numba/numba#510]
This is a regression from issue #34.

```
>>> def f():
...     for i in range(10):
...         return 1
...
>>> g = jit(int_())(f)
>>> g()
1L
>>> g = jit(int_(), nopython=True)(f)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numba\decorators.py", line 128, in wrapper
    disp.compile(sig)
  File "numba\dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "numba\compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "numba\compiler.py", line 120, in compile_bytecode
    locals)
  File "numba\compiler.py", line 282, in type_inference_stage
    infer.build_constrain()
  File "numba\typeinfer.py", line 305, in build_constrain
    self.constrain_statement(inst)
  File "numba\typeinfer.py", line 410, in constrain_statement
    self.typeof_assign(inst)
  File "numba\typeinfer.py", line 437, in typeof_assign
    self.typeof_const(inst, inst.target, value.value)
  File "numba\typeinfer.py", line 455, in typeof_const
    self.typevars[target.name].lock(types.none)
  File "numba\typeinfer.py", line 79, in lock
    "'%s'" % (typ, expect, self.var))
numba.typeinfer.TypingError: No conversion from none to int32 for '$24'
```

**Comment by pitrou** [comment]
This now works fine, because the return type is inferred as an optional value ("?int32").
