### ISSUE TITLE
Passing a set of strings to Numba function fails

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#5125]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Passing a `set` of string values to a Numba function fails:
```python
@numba.njit
def g(s):
    return "A" in s

g(set(("AB","D")))
```
```
Traceback (most recent call last):
  File "../str_map.py", line 41, in <module>
    g(set(("AB","D")))
  File "/Users/ehsan/dev/numba/numba/dispatcher.py", line 604, in typeof_pyval
    tp = typeof(val, Purpose.argument)
  File "/Users/ehsan/dev/numba/numba/typing/typeof.py", line 30, in typeof
    ty = typeof_impl(val, c)
  File "/opt/anaconda3/envs/TEST3/lib/python3.7/functools.py", line 827, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/ehsan/dev/numba/numba/typing/typeof.py", line 180, in _typeof_set
    return types.Set(ty, reflected=True)
  File "/Users/ehsan/dev/numba/numba/types/abstract.py", line 69, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "/Users/ehsan/dev/numba/numba/types/containers.py", line 432, in __init__
    assert isinstance(dtype, (Hashable, Undefined))
AssertionError
```
This assertion shouldn't probably fail since string objects are hashable. Commenting out the `assert` statement gives lowering error:
```
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No definition for lowering <built-in function eq>(unicode_type, unicode_type) -> bool

File "../str_map.py", line 39:
def g(s):
    return "A" in s
    ^

[1] During: lowering "$6compare_op.2 = $const2.0 in s" at ../str_map.py (39)
```
Adding the lowerer gives another error:
```python
@lower_builtin(operator.eq, numba.types.unicode_type, numba.types.unicode_type)
def lower_string_eq(context, builder, sig, args):
    return context.compile_internal(builder, numba.unicode.unicode_eq(*sig.args), sig, args)
```
```
  File "/Users/ehsan/dev/numba/numba/typed_passes.py", line 351, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/ehsan/dev/numba/numba/lowering.py", line 302, in create_cpython_wrapper
    release_gil=release_gil)
  File "/Users/ehsan/dev/numba/numba/targets/cpu.py", line 162, in create_cpython_wrapper
    builder.build()
  File "/Users/ehsan/dev/numba/numba/callwrapper.py", line 124, in build
    self.build_wrapper(api, builder, closure, args, kws)
  File "/Users/ehsan/dev/numba/numba/callwrapper.py", line 157, in build_wrapper
    val = cleanup_manager.add_arg(builder.load(obj), ty)
  File "/Users/ehsan/dev/numba/numba/callwrapper.py", line 32, in add_arg
    native = self.api.to_native_value(ty, obj)
  File "/Users/ehsan/dev/numba/numba/pythonapi.py", line 1425, in to_native_value
    return impl(typ, obj, c)
  File "/Users/ehsan/dev/numba/numba/targets/boxing.py", line 888, in unbox_set
    _python_set_to_native(typ, obj, c, size, setptr, errorptr)
  File "/Users/ehsan/dev/numba/numba/targets/boxing.py", line 842, in _python_set_to_native
    inst.add_pyapi(c.pyapi, native.value, do_resize=False)
  File "/Users/ehsan/dev/numba/numba/targets/setobj.py", line 488, in add_pyapi
    self._add_key(payload, item, h, do_resize)
  File "/Users/ehsan/dev/numba/numba/targets/setobj.py", line 425, in _add_key
    found, i = payload._lookup(item, h, for_insert=True)
  File "/Users/ehsan/dev/numba/numba/targets/setobj.py", line 241, in _lookup
    check_entry(i)
  File "/Users/ehsan/dev/numba/numba/targets/setobj.py", line 221, in check_entry
    eq = eqfn(builder, (item, entry.key))
  File "/Users/ehsan/dev/numba/numba/targets/base.py", line 1146, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/Users/ehsan/dev/numba/numba/targets/base.py", line 1176, in wrapper
    return fn(*args, **kwargs)
  File "../str_map.py", line 43, in lower_string_eq
    return context.compile_internal(builder, numba.unicode.unicode_eq(*sig.args), sig, args)
  File "/Users/ehsan/dev/numba/numba/targets/base.py", line 873, in compile_internal
    return self.call_internal(builder, cres.fndesc, sig, args)
  File "/Users/ehsan/dev/numba/numba/targets/base.py", line 887, in call_internal
    self.call_conv.return_status_propagate(builder, status)
  File "/Users/ehsan/dev/numba/numba/targets/callconv.py", line 441, in return_status_propagate
    builder.store(status.excinfoptr, excptr)
  File "/opt/anaconda3/envs/TEST3/lib/python3.7/site-packages/llvmlite/ir/builder.py", line 740, in store
    % (value.type, ptr.type))
TypeError: Failed in nopython mode pipeline (step: nopython mode backend)
cannot store {i8*, i32}* to i8*: mismatching types
```

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce.

1. `types.Unicode` needs to also inherit from `types.abstract.Hashable`
2. The complaint about `operator.eq` being missing is because the `set` `contains` code doesn't do the `resolve_value_type` then `get_call_type` pattern so there's no overload resolution.
3. This is due to call convention mismatch, there's a converter being working on, should land in the next couple of weeks.

**Comment by ehsantn** [comment]
Thank you @stuartarchibald . This all makes sense (I suspected and tried to explored these things to some extent). I'd add that `set` object doesn't handle reference counted objects yet. I remember a brief discussion about it in the core meeting but I don't remember if there is a timeline yet.

**Comment by Honghe** [comment]
＠ehsantn How do you bypass this bug right now?

**Comment by ehsantn** [comment]
by using a dictionary instead of set

**Comment by stuartarchibald** [comment]
As of 0.55 this produces:
```
numba.core.errors.NumbaValueError: Failed in nopython mode pipeline (step: native lowering)
Use of reference counted items in 'set()' is unsupported, offending type is: 'unicode_type'.
```

**Comment by ChristianRomberg** [comment]
I also just came across this bug. I'm shocked to see that it's known for this long. Is this something that can be quickly done or is there any way one can assist? I'd like to see this fixed.

**Comment by gmarkall** [comment]
I'd guess it's not something that can be quickly done - I'm not sure why using refcounted items in `set()` is unsupported (or even if that exception should be raised) but my general understanding is that the typed set code is in need of work in various ways.

> I'm shocked to see that it's known for this long.

There are 1.5k open issues right now, a small group of developers who focus on Numba, and constant ongoing maintenance burdens (adapting to new CPython versions' bytecodes, new LLVM versions, new NumPy versions, etc.). There will be other things that are known for a long time and unresolved.
