### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by intel-maxmurphy** [numba/numba#5148]
I have been having stability issues while using @jitclass. The latest issue relates to the program breaking unexpected while using a compiled module in Python's interactive console. I can usually get a single function call out and then about 10-12 seconds until the entire stack is brought down with the exit code mentioned in the title. 

I don't know what further information you'll need, but I'll provide as much as I can.

**Comment by stuartarchibald** [comment]
Thanks for the report. Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
2. Any data needed to run the code.
3. The full trace back of the exception.

Once we have a reproducer someone can take a look and work on a fix. Thanks for your help.

**Comment by intel-maxmurphy** [comment]
Note : My current working environment is a venv within PyCharm on Windows 10, using Python 3.7. I've tried running the code within the Python Console on PyCharm and on PowerShell.

**Comment by intel-maxmurphy** [comment]
1. Here is the code required to reproduce the issue

``` python
import numpy as np
from numba import jitclass
from numba import uint8, uint32
from numba.typed import List
from numba.types import string, ListType

spec = [
    ('name', string),
    ('increment', uint32),
    ('zz_upper_c', uint32),
    ('zz_lower_c', uint32),
    ('zz_p', uint8),
    ('num_st', uint8),
    ('hj_c', uint32[:]),
    ('c', uint32[:, :]),
    ('p', uint8[:, :]),
    ('p_no_r', uint8[:, :]),
    ('b_y', uint8[:, :]),
    ('b_p', uint8[:, :]),
    ('c_gg', uint32),
    ('c_dt', uint32),
    ('w_m', uint32),
    ('w_st', uint32),
    ('q_st', ListType(uint8)),
    ('q_ms', ListType(uint32)),
    ('num_i', uint8)
]
@jitclass(spec=spec)
class MM:
    # Constructor
    def __init__(self, name="", increment=0, zz_upper_c=0, zz_lower_c=0, zz_p=0,
                 num_st=10, hj_c=uint32[:]):
        """ Creates a new ____ ____ for the ____ """
        # Set ____ Variables
        self.name = name
        self.increment = increment
        self.zz_upper_c = zz_upper_c
        self.zz_lower_c = zz_lower_c
        self.zz_p = zz_p
        self.num_st = num_st
        self.hj_c = hj_c
        self.c = np.zeros((self.num_st, self.num_i), np.uint32)
        self.p = np.zeros((self.num_st, self.num_i), np.uint8)
        self.p_no_r = np.zeros((self.num_st, self.num_i), np.uint8)
        self.b_y = np.zeros((self.num_st, 1), np.uint8)
        self.b_p = np.zeros((self.num_i, self.num_st), np.uint8)
        self.c_gg = 0
        self.c_dt = 0
        self.w_m = 0
        self.w_st = 0
        self.q_st = List.empty_list(uint8)
        self.q_ms = List.empty_list(uint32)

        # Calculate ____ Variables
        self.num_i = len(hj_c)

    # Reset Variables
    def resetVariables(self):
        # Reset Class Variables
        self.c = np.zeros((self.num_st, self.num_i), np.uint32)
        self.p = np.zeros((self.num_st, self.num_i), np.uint8)
        self.p_no_r = np.zeros((self.num_st, self.num_i), np.uint8)
        self.b_y = np.zeros((self.num_st, 1), np.uint8)
        self.b_p = np.zeros((self.num_i, self.num_st), np.uint8)
        self.c_gg = 0
        self.c_dt = 0
        self.w_m = 0
        self.w_st = 0
        self.q_st = List.empty_list(uint8)
        self.q_ms = List.empty_list(uint32)

    # Calculate Related Values - ____ ____
    # Note: This is stripped down to speed up processing of the ____
    def calculateRelatedValuesStripped(self):
        # Calculate ____
        ## Note : The stripped version of this function has cut out ____ for speed.
        gg_st = self.p_no_r.sum(axis=0)
        for s in range(self.num_st):
            if gg_st[s] > self.zz_p:
                for i in range(gg_st[s] - self.zz_p):
                    self.w_st = self.w_st + 1
                    self.q_st.append(s)

        ## RULE : DON'T GO ____ THE ____ ____ THE ____
        for c in range(self.num_i):
            for m in self.c[c]:
                if m > self.zz_upper_c:
                    self.w_m = self.w_m + 1
                    self.q_ms.append(c)

        ## Rule : DON'T ____ ____ THE ____ ____ THIS ____ (Half a point)
        for c in range(self.num_i):
            for m in range(self.num_st):
                if m > 0:
                    value = self.c[c][m - 1] + 200
                    if value < self.zz_lower_c and self.p_no_r[c][m]:
                        self.w_m = self.w_m + 0.5
                        self.q_ms.append(c)
                        self.c_dt = self.c_dt + abs(
                            self.c_dt + abs(value - self.zz_lower_c))

    def calculateRelatedValuesui(self):
        # Calculate ____
        self.calculateRelatedValuesStripped()

    # Generate ____
    ## From ____
    def generatezz(self):
        """ Generates Related ____s for the ____ Based on the ____ ____ ____"""
        # Reset Class Variables
        self.resetVariables()

        # Generate the ____
        for i_num in range(self.num_i):
            for j in range(self.num_st):
                # Is this the first ____?
                if j == 0:
                    # YES
                    # ____
                    # Loop
                    self.c[i_num][j] = self.hj_c[i_num]
                    self.p[i_num][j] = 0
                    self.p_no_r[i_num][j] = 0
                    self.c_gg += self.hj_c[i_num]
                    continue
                # Was that ____ ____ for the previous ____?
                if self.p[i_num][len(self.p[i_num]) - 1] == 1:
                    # YES
                    # ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.p[i_num][j] = 2
                    self.p_no_r[i_num][j] = 0
                    continue
                # Is this ____ value going to ____ ____ the ____
                value = self.c[i_num][j - 1] + self.increment
                if value >= self.zz_upper_c:
                    # YES
                    # ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.p[i_num][j] = 1
                    self.p_no_r[i_num][j] = 1
                    self.c_dt = self.c_dt + abs(value - self.zz_upper_c)
                    continue
                else:
                    # NO
                    self.c[i_num][j] = value
                    self.p[i_num][j] = 0
                    self.p_no_r[i_num][j] = 0
                    self.c_gg += value
                    continue

        # Calculate Related Values
        self.calculateRelatedValuesui()

    ## From ____ ____
    def generatep(self, p_rf, ui=True):
        """ Generates related ____-____s based on the a ____ ____ """
        # Reset Variables
        self.resetVariables()

        # Set ____ to the given ____ ____
        self.p = p_rf
        self.p_no_r = np.zeros((self.num_st, self.num_i), np.uint8)

        # Generate the ____
        for i_num in range(self.num_i):
            for j in range(self.num_st):
                # Is this the first ____?
                if j == 0:
                    # YES
                    if self.p[i_num][j] == 1:
                        self.c[i_num][j] = 0
                        self.c_dt = self.c_dt + abs(self.hj_c[i_num] - self.zz_upper_c)
                        self.p_no_r[i_num][j] = 1
                    else:
                        # ____ = ____ Value of ____ for that ____
                        # No ____
                        # Loop
                        self.c[i_num][j] = self.hj_c[i_num]
                        self.c_gg += self.hj_c[i_num]
                        if self.hj_c[i_num] > self.zz_upper_c:
                            self.c_dt = self.c_dt + abs(
                                self.hj_c[i_num] - self.zz_upper_c)
                        self.p_no_r[i_num][j] = 0
                    continue
                # Was that ____ ____ for the ____ ____?
                if self.p[i_num][j - 1] == 1:
                    # YES
                    # ____ = 0
                    # No ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.p[i_num][j] = 2
                    self.p_no_r[i_num][j] = 0
                    continue
                # Defines the new ____ value
                value = self.c[i_num][len(self.c[i_num]) - 1] + self.increment
                # We are given a ____ ____ so that dictates whether or not we are ____ ____ ____ the ____
                if self.p[i_num][j] == 1:
                    # YES
                    # ____ = 0
                    # ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.c_dt = self.c_dt + abs(value - self.zz_upper_c)
                    self.p_no_r[i_num][j] = 1
                    continue
                else:
                    # NO
                    # ____ = ____ + increment
                    self.c[i_num][j] = value
                    self.c_gg += self.increment
                    if value > self.zz_upper_c:
                        self.c_dt = self.c_dt + abs(
                            self.hj_c[i_num] - self.zz_upper_c)
                    self.p_no_r[i_num][j] = 0
                    continue

        # Calculate Related Values
        if ui:
            self.calculateRelatedValuesui()
        else:
            self.calculateRelatedValuesStripped()
```
2. These are the commands needed to run this code
``` python
from MMDeclassified import MM
import numpy as np
i = [1706,2816,2389,71,330,2508,904,1353,3130,1993,88,2359,5,1502,33,2246,562,134,1278,743,0,795,1315,2801,87,2903,3134,931,1744,1026]
i = np.asarray(i).astype(np.uint32)
fd = MM(name="", zz_upper_c=3500, zz_lower_c=3000, zz_p=2, increment=200, hj_c=i, num_st=20)
fd.generatezz()
```
3. The full back-trace is quite literally this.

> PyDev console: starting.

> Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32

> from MMDeclassified import MM

>...import numpy as np
>...i = [1706,2816,2389,71,330,2508,904,1353,3130,1993,88,2359,5,1502,33,2246,562,134,1278,743,0,795,1315,2801,87,2903,3134,931,1744,1026]
>...i = np.asarray(i).astype(np.uint32)
>...fd = MM(name="", zz_upper_c=3500, zz_lower_c=3000, zz_p=2, increment=200, hj_c=i, num_st=20)
>...fd.generatezz()
><string>:3: NumbaTypeSafetyWarning: unsafe cast from uint64 to uint32. Precision may be lost.
><string>:3: NumbaTypeSafetyWarning: unsafe cast from uint64 to uint8. Precision may be lost.
>Process finished with exit code -1073741819 (0xC0000005)

**Comment by intel-maxmurphy** [comment]
![backtrace](https://user-images.githubusercontent.com/60356112/73196886-a81b2700-40ed-11ea-9d09-358ad6fe86a7.png)

**Comment by stuartarchibald** [comment]
@intel-maxmurphy the code sample presented does not work without Numba:
```python
import numpy as np

class MM:
    # Constructor
    def __init__(self, name="", increment=0, zz_upper_c=0, zz_lower_c=0, zz_p=0,
                 num_st=10, hj_c=None):
        """ Creates a new ____ ____ for the ____ """
        # Set ____ Variables
        self.name = name
        self.increment = increment
        self.zz_upper_c = zz_upper_c
        self.zz_lower_c = zz_lower_c
        self.zz_p = zz_p
        self.num_st = num_st
        self.hj_c = hj_c
        # Calculate ____ Variables
        self.num_i = len(hj_c)
        self.c = np.zeros((self.num_st, self.num_i), np.uint32)
        self.p = np.zeros((self.num_st, self.num_i), np.uint8)
        self.p_no_r = np.zeros((self.num_st, self.num_i), np.uint8)
        self.b_y = np.zeros((self.num_st, 1), np.uint8)
        self.b_p = np.zeros((self.num_i, self.num_st), np.uint8)
        self.c_gg = 0
        self.c_dt = 0
        self.w_m = 0
        self.w_st = 0
        self.q_st = []
        self.q_ms = []


    # Reset Variables
    def resetVariables(self):
        # Reset Class Variables
        self.c = np.zeros((self.num_st, self.num_i), np.uint32)
        self.p = np.zeros((self.num_st, self.num_i), np.uint8)
        self.p_no_r = np.zeros((self.num_st, self.num_i), np.uint8)
        self.b_y = np.zeros((self.num_st, 1), np.uint8)
        self.b_p = np.zeros((self.num_i, self.num_st), np.uint8)
        self.c_gg = 0
        self.c_dt = 0
        self.w_m = 0
        self.w_st = 0
        self.q_st = []
        self.q_ms = []

    # Calculate Related Values - ____ ____
    # Note: This is stripped down to speed up processing of the ____
    def calculateRelatedValuesStripped(self):
        # Calculate ____
        ## Note : The stripped version of this function has cut out ____ for speed.
        gg_st = self.p_no_r.sum(axis=0)
        for s in range(self.num_st):
            if gg_st[s] > self.zz_p:
                for i in range(gg_st[s] - self.zz_p):
                    self.w_st = self.w_st + 1
                    self.q_st.append(s)

        ## RULE : DON'T GO ____ THE ____ ____ THE ____
        for c in range(self.num_i):
            for m in self.c[c]:
                if m > self.zz_upper_c:
                    self.w_m = self.w_m + 1
                    self.q_ms.append(c)

        ## Rule : DON'T ____ ____ THE ____ ____ THIS ____ (Half a point)
        for c in range(self.num_i):
            for m in range(self.num_st):
                if m > 0:
                    value = self.c[c][m - 1] + 200
                    if value < self.zz_lower_c and self.p_no_r[c][m]:
                        self.w_m = self.w_m + 0.5
                        self.q_ms.append(c)
                        self.c_dt = self.c_dt + abs(
                            self.c_dt + abs(value - self.zz_lower_c))

    def calculateRelatedValuesui(self):
        # Calculate ____
        self.calculateRelatedValuesStripped()

    # Generate ____
    ## From ____
    def generatezz(self):
        """ Generates Related ____s for the ____ Based on the ____ ____ ____"""
        # Reset Class Variables
        self.resetVariables()

        # Generate the ____
        for i_num in range(self.num_i):
            for j in range(self.num_st):
                # Is this the first ____?
                if j == 0:
                    # YES
                    # ____
                    # Loop
                    self.c[i_num][j] = self.hj_c[i_num]
                    self.p[i_num][j] = 0
                    self.p_no_r[i_num][j] = 0
                    self.c_gg += self.hj_c[i_num]
                    continue
                # Was that ____ ____ for the previous ____?
                if self.p[i_num][len(self.p[i_num]) - 1] == 1:
                    # YES
                    # ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.p[i_num][j] = 2
                    self.p_no_r[i_num][j] = 0
                    continue
                # Is this ____ value going to ____ ____ the ____
                value = self.c[i_num][j - 1] + self.increment
                if value >= self.zz_upper_c:
                    # YES
                    # ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.p[i_num][j] = 1
                    self.p_no_r[i_num][j] = 1
                    self.c_dt = self.c_dt + abs(value - self.zz_upper_c)
                    continue
                else:
                    # NO
                    self.c[i_num][j] = value
                    self.p[i_num][j] = 0
                    self.p_no_r[i_num][j] = 0
                    self.c_gg += value
                    continue

        # Calculate Related Values
        self.calculateRelatedValuesui()

    ## From ____ ____
    def generatep(self, p_rf, ui=True):
        """ Generates related ____-____s based on the a ____ ____ """
        # Reset Variables
        self.resetVariables()

        # Set ____ to the given ____ ____
        self.p = p_rf
        self.p_no_r = np.zeros((self.num_st, self.num_i), np.uint8)

        # Generate the ____
        for i_num in range(self.num_i):
            for j in range(self.num_st):
                # Is this the first ____?
                if j == 0:
                    # YES
                    if self.p[i_num][j] == 1:
                        self.c[i_num][j] = 0
                        self.c_dt = self.c_dt + abs(self.hj_c[i_num] - self.zz_upper_c)
                        self.p_no_r[i_num][j] = 1
                    else:
                        # ____ = ____ Value of ____ for that ____
                        # No ____
                        # Loop
                        self.c[i_num][j] = self.hj_c[i_num]
                        self.c_gg += self.hj_c[i_num]
                        if self.hj_c[i_num] > self.zz_upper_c:
                            self.c_dt = self.c_dt + abs(
                                self.hj_c[i_num] - self.zz_upper_c)
                        self.p_no_r[i_num][j] = 0
                    continue
                # Was that ____ ____ for the ____ ____?
                if self.p[i_num][j - 1] == 1:
                    # YES
                    # ____ = 0
                    # No ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.p[i_num][j] = 2
                    self.p_no_r[i_num][j] = 0
                    continue
                # Defines the new ____ value
                value = self.c[i_num][len(self.c[i_num]) - 1] + self.increment
                # We are given a ____ ____ so that dictates whether or not we are ____ ____ ____ the ____
                if self.p[i_num][j] == 1:
                    # YES
                    # ____ = 0
                    # ____
                    # Loop
                    self.c[i_num][j] = 0
                    self.c_dt = self.c_dt + abs(value - self.zz_upper_c)
                    self.p_no_r[i_num][j] = 1
                    continue
                else:
                    # NO
                    # ____ = ____ + increment
                    self.c[i_num][j] = value
                    self.c_gg += self.increment
                    if value > self.zz_upper_c:
                        self.c_dt = self.c_dt + abs(
                            self.hj_c[i_num] - self.zz_upper_c)
                    self.p_no_r[i_num][j] = 0
                    continue

        # Calculate Related Values
        if ui:
            self.calculateRelatedValuesui()
        else:
            self.calculateRelatedValuesStripped()

import numpy as np
i = [1706,2816,2389,71,330,2508,904,1353,3130,1993,88,2359,5,1502,33,2246,562,134,1278,743,0,795,1315,2801,87,2903,3134,931,1744,1026]
i = np.asarray(i).astype(np.uint32)
fd = MM(name="", zz_upper_c=3500, zz_lower_c=3000, zz_p=2, increment=200, hj_c=i, num_st=20)
fd.generatezz()
```
there's an out of bounds access:
```
$ python issue5148.py 
Traceback (most recent call last):
  File "issue5148.py", line 205, in <module>
    fd.generatezz()
  File "issue5148.py", line 95, in generatezz
    self.c[i_num][j] = self.hj_c[i_num]
IndexError: index 20 is out of bounds for axis 0 with size 20
```
It's quite possible that this is causing the problem you are seeing.
