### ISSUE TITLE
Cannot add edge as dest node on Arch Linux

### ISSUE THREAD

**Issue by 99991** [numba/numba#5156]
I am using numba version `0.47.0` on this Docker Arch Linux Image: https://hub.docker.com/_/archlinux/

There seems to be an issue with parallelization on Arch Linux.

The error does **not** occur on Ubuntu or when setting `parallel=False`.

This issue was originally discovered in: https://github.com/pymatting/pymatting/issues/3

## Code

```python
import numpy as np
from numba import njit, prange

@njit("void()", parallel=True, cache=True)
def foo():
    for _ in prange(10):
        n = 1
        while n > 0:
            n -= 1
```

## Error

```python
Traceback (most recent call last):
  File "test.py", line 5, in <module>
    def foo():
  File "/usr/lib/python3.8/site-packages/numba/decorators.py", line 200, in wrapper
    disp.compile(sig)
  File "/usr/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/usr/lib/python3.8/site-packages/numba/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 373, in _compile_core
    raise e
  File "/usr/lib/python3.8/site-packages/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 347, in run
    raise patched_exception
  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/lib/python3.8/site-packages/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "/usr/lib/python3.8/site-packages/numba/typed_passes.py", line 269, in run_pass
    parfor_pass.run()
  File "/usr/lib/python3.8/site-packages/numba/parfor.py", line 1513, in run
    self._convert_loop(self.func_ir.blocks)
  File "/usr/lib/python3.8/site-packages/numba/parfor.py", line 1950, in _convert_loop
    self._replace_loop_access_indices(
  File "/usr/lib/python3.8/site-packages/numba/parfor.py", line 1975, in _replace_loop_access_indices
    labels = find_topo_order(loop_body)
  File "/usr/lib/python3.8/site-packages/numba/ir_utils.py", line 1061, in find_topo_order
    cfg = compute_cfg_from_blocks(blocks)
  File "/usr/lib/python3.8/site-packages/numba/analysis.py", line 243, in compute_cfg_from_blocks
    cfg.add_edge(k, target)
  File "/usr/lib/python3.8/site-packages/numba/controlflow.py", line 89, in add_edge
    raise ValueError("Cannot add edge as dest node %s not in nodes %s" %
ValueError: Failed in nopython mode pipeline (step: convert to parfors)
Cannot add edge as dest node 10 not in nodes {26, 18, 12, 39}
```

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. This is a Python 3.8 specific issue, it does not occur in Python < 3.8. Am wondering if it's a problem with 3.8 CFA in general or that parfors needs an update for 3.8 changes.

**Comment by stuartarchibald** [comment]
CC @sklam @DrTodd13

**Comment by sklam** [comment]
Problem confirm with `parallel=True` only. Not affected by `cache=True`.

**Comment by sklam** [comment]
I think this is a unique to py3.8 because the code base is assuming that loop-exit node cannot be overlapping with another loop's header node. We are seeing CFG like this:
![numba_cfg dot](https://user-images.githubusercontent.com/1929845/73676719-7caeb400-467a-11ea-891c-a69730625505.png)
And the loops are:
```python
loops {10: Loop(entries={0}, exits={46}, header=10, body={26, 10, 18, 12}), 18: Loop(entries={12}, exits={10}, header=18, body={18, 26})}
```
The parfor `_convert_loop` code start from the innermost loop. And it has incorrectly removed node 10. 

The problem goes away if we break the sharing of the loop-exit and loop-header by adding an extra statement after the while loop:

```python
import numpy as np
from numba import njit, prange

@njit("void()", parallel=True)
def foo():
    for _ in prange(10):
        n = 1
        while n > 0:
            n -= 1
        n += 0


foo()
```
