### ISSUE TITLE
Multiple tests involving NaT datetimes fail in Python 3.8 with NumPy 1.18.1

### ISSUE THREAD

**Issue by jjhelmus** [numba/numba#5178]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Multiple unit tests in involving Not a Time (NaT) datetimes fail when run with NumPy 1.18.1.  Earlier versions of NumPy (I tested with 1.17.4 and 1.16.6) do not have this issue.

Tested on the 0.48.0 numba release.

A short reproducer run on Ubuntu 18.04:

```
$ conda create -n test_numba python=3.8 numba numpy=1.18
<snip>
$ conda activate test_numba
$ python -m numba.runtests -k "*time*"
skipped HSA tests
skipped HSA tests
...............................................
<snip>
======================================================================
FAIL: test_minimum_MM_M (numba.tests.test_ufuncs.TestLoopTypesDatetimeNoPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/test_ufuncs.py", line 1576, in test_template
    self._check_loop(fn, ufunc, loop)
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/test_ufuncs.py", line 1533, in _check_loop
    self._check_ufunc_with_dtypes(fn, ufunc, letter_types)
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/test_ufuncs.py", line 1561, in _check_ufunc_with_dtypes
    self.assertPreciseEqual(py_arg, c_arg, prec=prec, msg=msg,
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/support.py", line 290, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing [       'NaT' '1970-01-01'        'NaT' '1970-01-01' '1970-01-02'
 '1970-01-02'        'NaT' '1970-01-01'] and ['1970-01-02' '1970-01-01'        'NaT' '1970-01-01' '1970-01-02'
 '1970-01-02' '1970-01-02' '1970-01-01']: True != False

======================================================================
FAIL: test_minimum_mm_m (numba.tests.test_ufuncs.TestLoopTypesDatetimeNoPython)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/test_ufuncs.py", line 1576, in test_template
    self._check_loop(fn, ufunc, loop)
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/test_ufuncs.py", line 1533, in _check_loop
    self._check_ufunc_with_dtypes(fn, ufunc, letter_types)
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/test_ufuncs.py", line 1561, in _check_ufunc_with_dtypes
    self.assertPreciseEqual(py_arg, c_arg, prec=prec, msg=msg,
  File "/home/jhelmus/conda/envs/test_numba/lib/python3.8/site-packages/numba/tests/support.py", line 290, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing [   -3 'NaT'     2 'NaT' 'NaT' 'NaT'    -3     0] and [-3  0  2  0 -3 -3 -3  0]: True != False

----------------------------------------------------------------------
Ran 1050 tests in 51.586s

FAILED (failures=8, errors=4, expected failures=1)
```

A more complete log is: [test_log.txt](https://github.com/numba/numba/files/4141660/test_log.txt)

**Comment by esc** [comment]
@jjhelmus thanks for submitting this, it will need some triaging.

**Comment by stuartarchibald** [comment]
I think we anticipated this based on the 1.18 change log. Datetime has churned quite a bit in the last few releases.
