### ISSUE TITLE
TupleTestHashing unit tests fails on 32-bit Windows in Python 3.8

### ISSUE THREAD

**Issue by jjhelmus** [numba/numba#5179]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The `numba.tests.test_hashing.TestTupleHasing` tests fail when run on a Windows with a 32-bit Python 3.8 interpreter.

```
(base) C:\Users\jhelmus>set CONDA_SUBDIR=win-32

(base) C:\Users\jhelmus>conda create -n test_numba python=3.8 numba=0.48.0 numpy=1.18
Collecting package metadata (current_repodata.json): done
Solving environment: done
...
(base) C:\Users\jhelmus>conda activate test_numba
(test_numba) C:\Users\jhelmus>python -m numba.runtests -k "*TupleHash*" -v
skipped CUDA tests
skipped CUDA tests
skipped HSA tests
skipped HSA tests
test_heterogeneous_tuples (numba.tests.test_hashing.TestTupleHashing) ... val, nb_hash, hash(val)
(0, 0.0) 207041508 -168982784
abs(val), hashing._PyHASH_MODULUS - 1
ERROR
test_homogeneous_tuples (numba.tests.test_hashing.TestTupleHashing) ... val, nb_hash, hash(val)
(0, 0) 207041508 -168982784
abs(val), hashing._PyHASH_MODULUS - 1
ERROR
test_py27 (numba.tests.test_hashing.TestTupleHashing) ... skipped 'Python 2 only test'

======================================================================
ERROR: test_heterogeneous_tuples (numba.tests.test_hashing.TestTupleHashing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 52, in check_hash_values
    self.assertEqual(nb_hash, hash(val))
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 207041508 != -168982784

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 258, in test_heterogeneous_tuples
    self.check_tuples(self.int_samples(), split)
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 216, in check_tuples
    self.check_hash_values(tuples)
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 57, in check_hash_values
    print(abs(val), hashing._PyHASH_MODULUS - 1)
TypeError: bad operand type for abs(): 'tuple'

======================================================================
ERROR: test_homogeneous_tuples (numba.tests.test_hashing.TestTupleHashing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 52, in check_hash_values
    self.assertEqual(nb_hash, hash(val))
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\unittest\case.py", line 912, in assertEqual
    assertion_func(first, second, msg=msg)
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\unittest\case.py", line 905, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 207041508 != -168982784

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 240, in test_homogeneous_tuples
    self.check_tuples(self.int_samples(), split2)
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 216, in check_tuples
    self.check_hash_values(tuples)
  File "C:\Users\jhelmus\mc\envs\test_numba\lib\site-packages\numba\tests\test_hashing.py", line 57, in check_hash_values
    print(abs(val), hashing._PyHASH_MODULUS - 1)
TypeError: bad operand type for abs(): 'tuple'

----------------------------------------------------------------------
Ran 3 tests in 2.565s

FAILED (errors=2, skipped=1)
```

These test pass when run with Python 3.7 on win-32 or Python 3.8 on win-64.

**Comment by esc** [comment]
@jjhelmus thanks for submitting this, it will need some triage for sure.

**Comment by stuartarchibald** [comment]
Have to wonder why our build farm didn't pick this up!? Otherwise, this is likely due to me mis-translating the patch to the tuple hash function that went in for 3.8. Suspect there's some different consts for 32 bit systems or something that I forgot!

**Comment by seibert** [comment]
At the time you were updating the hash function, I don't think we had python packages for Python 3.8 on Win32.

**Comment by jjhelmus** [comment]
These two tests are still failing with numba 0.49.0 on 32-bit Windows on Python 3.8

**Comment by stuartarchibald** [comment]
> These two tests are still failing with numba 0.49.0 on 32-bit Windows on Python 3.8


hmmmm, I thought I fixed this, perhaps that was something else. https://github.com/numba/numba/commit/67feaba1c46037a0c7c7c6feac57728dbddbf9c4 fixed up the SSA issues for 32bit, and I ran this on a 32bit linux box to test. Guess I'll need to have another look.

**Comment by stuartarchibald** [comment]
Closing, fixed in https://github.com/numba/numba/pull/6254
