### ISSUE TITLE
Memory leak with raised error in cascaded overloads

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5180]
Writing test-cases for some overloads I stumbled across the following memory-leak bug in master.

Minimal reproducer:

```python
import numpy as np

import numba.unittest_support as unittest
from numba import njit
from numba.extending import overload
from numba.tests.support import MemoryLeakMixin, TestCase


def func1():
    # Stub for overload
    pass


def func2(bar):
    # Stub for overload
    pass


@overload(func1)
def _func1_ovl():
    def func1_impl():
        raise ValueError('error message')
        return

    return func1_impl


@overload(func2)
def func2_ovl(bar):
    def func2_impl(bar):
        func1()
        return bar

    return func2_impl


class TestArrayManipulation(MemoryLeakMixin, TestCase):
    def test_func2(self):
        @njit
        def test_func2_use(a):
            return func2(a)

        arr = np.arange(1)
        with self.assertRaises(ValueError) as raises:
            test_func2_use(arr)


if __name__ == '__main__':
    unittest.main()
```

Output:
```
F
======================================================================
FAIL: test_func2 (__main__.TestArrayManipulation)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\My User\Documents\My Project\libraries\numba\numba\tests\support.py", line 694, in tearDown
    self.memory_leak_teardown()
  File "C:\Users\My User\Documents\My Project\libraries\numba\numba\tests\support.py", line 668, in memory_leak_teardown
    self.assert_no_memory_leak()
  File "C:\Users\My User\Documents\My Project\libraries\numba\numba\tests\support.py", line 677, in assert_no_memory_leak
    self.assertEqual(total_alloc, total_free)
AssertionError: 1 != 0

----------------------------------------------------------------------
Ran 1 test in 0.227s

FAILED (failures=1)
```

**Comment by ARF1** [comment]
I just realised that this is probably a known issue since some tests use `self.disable_leak_check()` with explicit comments to errors leaking references.

Please feel free to close this, if it is a known issue.

**Comment by esc** [comment]
@ARF1 this is correct, exceptions leak references and any tests that test exceptions will require you to explicitly disable the leak checks.
