### ISSUE TITLE
Eq-Comparison of `Optional(unicode_type)` and `unicode_type` does not work 

### ISSUE THREAD

**Issue by asodeur** [numba/numba#5199]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
from numba import jit, types

@jit(types.boolean(types.unicode_type, types.Optional(types.unicode_type)), nopython=True)
def foo(x, y):
    return x == y

assert foo('horst', 'horst')    # should compare equal even though the second arg is forced to Optional()
```

**Comment by asodeur** [comment]
The issue seems to be with `numba.unicode.unicode_eq`:
```python
@overload(operator.eq)
def unicode_eq(a, b):
    if not (a.is_internal and b.is_internal):
        return
    accept = (types.UnicodeType, types.StringLiteral, types.UnicodeCharSeq)
    a_unicode = isinstance(a, accept)
    b_unicode = isinstance(b, accept)
    if a_unicode and b_unicode:
        ... omitted
    elif a_unicode ^ b_unicode:  # <- this includes the case when one is Optional(unicode_type)
        # one of the things is unicode, everything compares False
        def eq_impl(a, b):
            return False 
        return eq_impl
```

Returning no implementation when either of the arguments is optional should allow the typer to try unpacking the optional arg(s) which would then give the right implementation.

**Comment by esc** [comment]
@asodeur thanks for reporting this, I can reproduce and here is the backtrace:

```
💥 zsh» python foo/foo117.py
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 147, in propagate
    constraint(typeinfer)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 183, in __call__
    typeinfer.copy_type(self.src, self.dst, loc=self.loc)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 1005, in copy_type
    self.typevars[dest_var].union(self.typevars[src_var], loc=loc)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 99, in union
    self.add_type(other.type, loc=loc)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 62, in add_type
    loc=loc)
numba.errors.TypingError: No conversion from bool to none for '$8return_value.3', defined at None

File "foo/foo117.py", line 5:
def foo(x, y):
    return x == y
    ^

[1] During: typing of assignment at foo/foo117.py (5)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foo/foo117.py", line 3, in <module>
    @jit(types.void(types.unicode_type, types.Optional(types.unicode_type)), nopython=True)
  File "/Users/vhaenel/git/numba/numba/decorators.py", line 199, in wrapper
    disp.compile(sig)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 81, in compile
    raise retval
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 547, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 327, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 389, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 369, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/compiler.py", line 360, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 336, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 327, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 93, in run_pass
    raise_errors=self._raise_errors)
  File "/Users/vhaenel/git/numba/numba/typed_passes.py", line 65, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/Users/vhaenel/git/numba/numba/typeinfer.py", line 984, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No conversion from bool to none for '$8return_value.3', defined at None

File "foo/foo117.py", line 5:
def foo(x, y):
    return x == y
    ^

[1] During: typing of assignment at foo/foo117.py (5)

File "foo/foo117.py", line 5:
def foo(x, y):
    return x == y
    ^
```

**Comment by asodeur** [comment]
Sorry, changed the reproducer slightly from what I posted on Gitter and introduced the `TypingError`.  Should give an `AssertionError` now.

**Comment by stuartarchibald** [comment]
On mainline at ~0.55 this does not reproduce anymore, assuming fixed, closing!
