### ISSUE TITLE
np.asarray sometimes doesn't work on List

### ISSUE THREAD

**Issue by hameerabbasi** [numba/numba#5226]
```python
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> from numba import njit
>>> from numba.typed import List
>>> @njit
... def lt(a, b):
...   return np.asarray(a) <= np.asarray(b)
...
>>> l1 = List()
>>> l1.append(4)
>>> l1.append(2)
>>> l1.append(1)
>>>
>>> l2 = List()
>>> l2.append(2)
>>> l2.append(2)
>>> l2.append(2)
>>>
>>> print(lt(l1, l2))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hameerabbasi/miniconda3/envs/sparse/lib/python3.7/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/hameerabbasi/miniconda3/envs/sparse/lib/python3.7/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/hameerabbasi/miniconda3/envs/sparse/lib/python3.7/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function asarray at 0x7f8df02a0440>) with argument(s) of type(s): (ListType[int64])
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function asarray at 0x7f8df02a0440>)
[2] During: typing of call at <stdin> (3)


File "<stdin>", line 3:
<source missing, REPL/exec in use?>

>>> import numba
>>> numba.__version__
'0.48.0'
```

**Comment by hameerabbasi** [comment]
Smaller reproducer:

```python
Python 3.7.6 (default, Jan  8 2020, 13:42:34)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import numba as nb
>>>
>>> @nb.njit
... def to_array(x):
...     return np.asarray(x)
...
>>> l = nb.typed.List()
>>> l.append(5)
>>> to_array(l)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hameerabbasi/miniconda3/envs/sparse/lib/python3.7/site-packages/numba/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/hameerabbasi/miniconda3/envs/sparse/lib/python3.7/site-packages/numba/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/hameerabbasi/miniconda3/envs/sparse/lib/python3.7/site-packages/numba/six.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function asarray at 0x7fb330038440>) with argument(s) of type(s): (ListType[int64])
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: resolving callee type: Function(<function asarray at 0x7fb330038440>)
[2] During: typing of call at <stdin> (3)


File "<stdin>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by esc** [comment]
Should be possible to implement.

**Comment by rohitsanj** [comment]
Thanks for filing the issue! @hameerabbasi 
I will try to implement this.

**Comment by stuartarchibald** [comment]
Great, thanks @rohitsanj

**Comment by stuartarchibald** [comment]
@rohitsanj The use of Numba's extension API `@overload` decorator is strongly recommended for this task. A guide to using `@overload` is [here](http://numba.pydata.org/numba-doc/dev/extending/overloading-guide.html?highlight=overload) and API documentation is [here](http://numba.pydata.org/numba-doc/latest/extending/high-level.html#implementing-functions).
As a new contributor, some instructions for getting set up for development are [here](http://numba.pydata.org/numba-doc/latest/developer/contributing.html#getting-set-up) and are a great place to start.

It may be useful to take a look at examples of pull requests adding support for a NumPy function that have already been done if guidance is needed... here's a couple:

* `np.roll`: https://github.com/numba/numba/pull/3563/files
* `np.roots`: https://github.com/numba/numba/pull/2135/files

**Comment by rohitsanj** [comment]
Thanks for the links! 😄 @stuartarchibald
