### ISSUE TITLE
numba fails with possibly undefined variables

### ISSUE THREAD

**Issue by pitrou** [numba/numba#523]
```
>>> def f():
...     for i in range(10):
...         if i > 5:
...            x = z + 1
...         else:
...            z = 10
...     return x
...
>>> f()
11
>>> jit(f)()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numba\dispatcher.py", line 125, in _compile_and_call
    self.jit(sig)
  File "numba\dispatcher.py", line 120, in jit
    return self.compile(sig, **kws)
  File "numba\dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "numba\compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "numba\compiler.py", line 99, in compile_bytecode
    interp = translate_stage(bc)
  File "numba\compiler.py", line 246, in translate_stage
    interp.interpret()
  File "numba\interpreter.py", line 62, in interpret
    self._dispatch(inst, kws)
  File "numba\interpreter.py", line 180, in _dispatch
    return fn(inst, **kws)
  File "numba\interpreter.py", line 554, in op_BINARY_ADD
    self._binop('+', lhs, rhs, res)
  File "numba\interpreter.py", line 548, in _binop
    lhs = self.get(lhs)
  File "numba\interpreter.py", line 205, in get
    return self.current_scope.get(name)
  File "numba\ir.py", line 359, in get
    return self.parent.get(name)
  File "numba\ir.py", line 356, in get
    return self.localvars.get(name)
  File "numba\ir.py", line 66, in get
    raise NotDefinedError(name)
numba.ir.NotDefinedError: z
```

**Comment by jbarros35** [comment]
So, any updates about it?

**Comment by sklam** [comment]
Numba's static analysis will never be able to handle this case. The liveness of `z` can only be known dynamically. Currently at Numba 0.48.0dev0, the following error is shown:

```python
NotDefinedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Variable 'z' is not defined.

File "<ipython-input-4-3d06b27d6aac>", line 5:
def f():
    <source elided>
         if i > 5:
            x = z + 1
            ^
```

This gives enough information for the user to take the appropriate action to workaround the insufficiency of the static analysis; e.g. add an initializer at the loop entry. 

To address this issue, Numba will need to keep some runtime bookkeeping on the liveness of the problematic variable. Doing so will likely deoptimize the function. Since Numba is a performance optimization tool, highlighting this problem for users is more useful than hiding it in inefficient code.  I'm in the view that this issue can be closed.
