### ISSUE TITLE
Test discovery with vscode fails

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5238]
With the current master, test discovery using vscode (using pytest backend) fails with the error messages:

```python
________________________________________________ ERROR collecting numba/tests/test_runtests.py _________________________________________________
ImportError while importing test module 'C:\Users\My User\Documents\numba\numba\tests\test_runtests.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests\test_runtests.py:4: in <module>
    from numba import cuda
cuda\__init__.py:7: in <module>
    from .device_init import *
cuda\device_init.py:14: in <module>
    from .decorators import jit, autojit, declare_device
cuda\decorators.py:3: in <module>
    from .compiler import (compile_kernel, compile_device, declare_device_function,
cuda\compiler.py:16: in <module>
    from .cudadrv.devices import get_context
cuda\cudadrv\devices.py:17: in <module>
    from .driver import driver
cuda\cudadrv\driver.py:30: in <module>
    from numba import mviewbuf
E   ImportError: cannot import name 'mviewbuf' from 'numba' (C:\Users\My User\Documents\numba\numba\__init__.py)
```

Using the `unittest` backend, test discovery of vscode fails with:

```
Traceback (most recent call last):
  File "c:\Users\My User\Documents\numba\numba\testing\__init__.py", line 29, in load_testsuite
    suite.addTests(loader.loadTestsFromName(f))
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\unittest\loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "c:\Users\My User\Documents\numba\numba\tests\npyufunc\test_caching.py", line 8, in <module>
    from ..support import capture_cache_log
ValueError: attempted relative import beyond top-level package
```

I know numba has its own way of running the test suite, but it would be nice, if test discovery could be made to work. Running a single test with a click would be much more convenient than specifying the fairly long test-paths on the command line.

I did look into this a bit but it was not immediately obvious to me how to avoid this problem. Is solving this possible with reasonable effort?

**Comment by ARF1** [comment]
This was a dirty repo it seems. `python setup.py build_ext --inplace` solved it.
