### ISSUE TITLE
literally() fails when used in implementations with default arguments and overload_method 

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5242]
`literally()` fails when used in implementations with default arguments and `overload_method` on current master.

Note: The same impementation works with `overload`.

Reproducer:

```python
import numpy as np

from numba import literally, njit
from numba.core import types
from numba.extending import overload, overload_method


def foo(a, b=0):
    "stub for overload"


@overload(foo)
@overload_method(types.Array, 'foo')
def foo_ovl(a, b=0):
    b_is_default = b == 0

    if b_is_default is True:
        def foo_impl(a, b=0):
            return 0
    else:
        def foo_impl(a, b=0):
            return literally(b)
                
    return foo_impl


@njit
def works(arr):
    return foo(arr)

@njit
def does_not_work(arr):
    return arr.foo()

works(np.arange(3))
does_not_work(np.arange(3))
```

Output:
```

(llvmlite-dev) c:\Users\My User\Documents\numba>cd "c:\Users\My User\Documents\numba" && cmd /C "set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\python.exe "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.62710\pythonFiles\ptvsd_launcher.py" --default --nodebug --client --host localhost --port 51462 "c:\Users\My User\Documents\numba\literal_bug.py" "
Traceback (most recent call last):
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 770, in compile
    cres = self._compiler.compile(args, return_type)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 548, in compile_extra
    return pipeline.compile_extra(func)
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 328, in compile_extra
    return self._compile_bytecode()
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 390, in _compile_bytecode
    return self._compile_core()
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 370, in _compile_core
    raise e
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 361, in _compile_core
    pm.run(self.state)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 335, in run
    raise patched_exception
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 326, in run
    self._runPass(idx, pass_inst, state)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 290, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 263, in check
    mangled = func(compiler_state)
  File "c:\Users\My User\Documents\numba\numba\core\untyped_passes.py", line 411, in run_pass
    find_literally_calls(state.func_ir, state.args)
  File "c:\Users\My User\Documents\numba\numba\core\analysis.py", line 564, in find_literally_calls
    raise errors.ForceLiteralArg(marked_args, loc=loc)
numba.core.errors.ForceLiteralArg: Failed in nopython mode pipeline (step: find literally calls)
?[1mPseudo-exception to force literal arguments in the dispatcher
?[1m
File "literal_bug.py", line 22:?[0m
?[1m        def foo_impl(a, b=0):
?[1m            return literally(b)
?[0m            ?[1m^?[0m?[0m
?[0m

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 770, in compile
    cres = self._compiler.compile(args, return_type)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 548, in compile_extra
    return pipeline.compile_extra(func)
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 328, in compile_extra
    return self._compile_bytecode()
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 390, in _compile_bytecode
    return self._compile_core()
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 370, in _compile_core
    raise e
  File "c:\Users\My User\Documents\numba\numba\core\compiler.py", line 361, in _compile_core
    pm.run(self.state)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 335, in run
    raise patched_exception
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 326, in run
    self._runPass(idx, pass_inst, state)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 290, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "c:\Users\My User\Documents\numba\numba\core\compiler_machinery.py", line 263, in check
    mangled = func(compiler_state)
  File "c:\Users\My User\Documents\numba\numba\core\typed_passes.py", line 407, in run_pass
    NativeLowering().run_pass(state)
  File "c:\Users\My User\Documents\numba\numba\core\typed_passes.py", line 349, in run_pass
    lower.lower()
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 178, in lower
    self.lower_normal_function(self.fndesc)
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 231, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 256, in lower_function_body
    self.lower_block(block)
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 271, in lower_block
    self.lower_inst(inst)
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 343, in lower_inst
    val = self.lower_assign(ty, inst)
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 517, in lower_assign
    return self.lower_expr(ty, value)
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 982, in lower_expr
    res = self.lower_call(resty, expr)
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 774, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "c:\Users\My User\Documents\numba\numba\core\lowering.py", line 953, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "c:\Users\My User\Documents\numba\numba\core\base.py", line 1148, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "c:\Users\My User\Documents\numba\numba\core\base.py", line 1178, in wrapper
    return fn(*args, **kwargs)
  File "c:\Users\My User\Documents\numba\numba\core\typing\templates.py", line 781, in method_impl
    sig = cls._get_signature(typing_context, fnty, sig.args, {})
  File "c:\Users\My User\Documents\numba\numba\core\typing\templates.py", line 753, in _get_signature
    sig = fnty.get_call_type(typingctx, args, kws)
  File "c:\Users\My User\Documents\numba\numba\core\types\functions.py", line 148, in get_call_type
    failures.raise_error()
  File "c:\Users\My User\Documents\numba\numba\core\types\functions.py", line 76, in raise_error
    raise e
  File "c:\Users\My User\Documents\numba\numba\core\types\functions.py", line 127, in get_call_type
    sig = temp.apply(args, kws)
  File "c:\Users\My User\Documents\numba\numba\core\typing\templates.py", line 246, in apply
    sig = generic(args, kws)
  File "c:\Users\My User\Documents\numba\numba\core\typing\templates.py", line 490, in generic
    sig = disp_type.get_call_type(self.context, new_args, kws)
  File "c:\Users\My User\Documents\numba\numba\core\types\functions.py", line 272, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 301, in get_call_template
    self.compile(tuple(args))
  File "c:\Users\My User\Documents\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 774, in compile
    raise e.bind_fold_arguments(folded)
numba.core.errors.ForceLiteralArg: Failed in nopython mode pipeline (step: nopython mode backend)
?[1m?[1mPseudo-exception to force literal arguments in the dispatcher
?[1m
File "literal_bug.py", line 22:?[0m
?[1m        def foo_impl(a, b=0):
?[1m            return literally(b)
?[0m            ?[1m^?[0m?[0m
?[0m
?[0m?[1m[1] During: lowering "$6call_method.2 = call $4load_method.1(func=$4load_method.1, args=[], kws=(), vararg=None)" at c:\Users\My User\Documents\numba\literal_bug.py (33)?[0m

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "c:\Users\My User\Documents\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 774, in compile
    raise e.bind_fold_arguments(folded)
numba.core.errors.ForceLiteralArg: ?[1mPseudo-exception to force literal arguments in the dispatcher
?[1m
File "literal_bug.py", line 22:?[0m
?[1m        def foo_impl(a, b=0):
?[1m            return literally(b)
?[0m            ?[1m^?[0m?[0m
?[0m

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.62710\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.62710\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.62710\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\My User\Documents\numba\literal_bug.py", line 36, in <module>
    does_not_work(np.arange(3))
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 360, in _compile_for_args
    already_lit_pos = [i for i in e.requested_args
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 361, in <listcomp>
    if isinstance(args[i], types.Literal)]
IndexError: tuple index out of range
```

**Comment by stuartarchibald** [comment]
Thanks for the report. Think this is a bug in the logic for `literally()` handling, quite possibly related to https://github.com/numba/numba/issues/5221 / similar logic paths need looking at.

**Comment by stuartarchibald** [comment]
Note: root cause of exception is that the `literally()` is on a kwarg, which appears as "argument index 1" but the `args` container only holds the positional arguments so is length 1, hence OOB access.
