### ISSUE TITLE
Raising an error casts result to OptionalType

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5259]
On the current master, raising an error in the function body forces the result of the function to `OptionalType`:

```python
import numpy as np
from numba import njit


closure_var = True # this would not be static in the real world...


@njit
def barbar_works(a):
    return 1.0


@njit
def barbar_does_not_work(a):
    if closure_var is True:
        raise ValueError('error message')
    return 1.0


@njit
def foo(a):
    if a.size == 0:
        result = barbar_works(a)
    else:
        result = 0.0
    return np.isfinite(result)


foo(np.arange(10)/10)


@njit
def foo(a):
    if a.size == 0:
        result = barbar_does_not_work(a)
    else:
        result = 0.0
    return np.isfinite(result)


foo(np.arange(10)/10)
```

Output:
```
(llvmlite-dev) c:\Users\My User\Documents\numba>cd "c:\Users\My User\Documents\numba" && cmd /C "set "PYTHONPATH=C:/Users/My User/Documents/Finance/python/libraries/numba;" && set "PYTHONIOENCODING=UTF-8" && set "PYTHONUNBUFFERED=1" && Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\python.exe "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63072\pythonFiles\ptvsd_launcher.py" --default --nodebug --client --host localhost --port 61302 "c:\Users\My User\Documents\numba\test_optional.py" "
Traceback (most recent call last):
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63072\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63072\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63072\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\My User\Documents\numba\test_optional.py", line 41, in <module>
    foo(np.arange(10)/10)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "c:\Users\My User\Documents\numba\numba\core\utils.py", line 77, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
?[1m?[1m?[1mInvalid use of Function(<ufunc 'isfinite'>) with argument(s) of type(s): (OptionalType(float64) i.e. the type 'float64 or None')
 * parameterized
?[1mIn definition 0:?[0m
?[1m    TypingError: ?[1mcan't resolve ufunc isfinite for types (OptionalType(float64),)?[0m?[0m
    raised from c:\Users\My User\Documents\numba\numba\core\typing\npydecl.py:106
?[1mIn definition 1:?[0m
?[1m    TypingError: ?[1mcan't resolve ufunc isfinite for types (OptionalType(float64),)?[0m?[0m
    raised from c:\Users\My User\Documents\numba\numba\core\typing\npydecl.py:106
?[1mThis error is usually caused by passing an argument of a type that is unsupported by the named function.?[0m?[0m
?[0m?[1m[1] During: resolving callee type: Function(<ufunc 'isfinite'>)?[0m
?[0m?[1m[2] During: typing of call at c:\Users\My User\Documents\numba\test_optional.py (38)
?[0m
?[1m
File "test_optional.py", line 38:?[0m
?[1mdef foo(a):
    <source elided>
        result = 0.0
?[1m    return np.isfinite(result)
?[0m    ?[1m^?[0m?[0m
```

Note that manually inlining works:
```python
import numpy as np
from numba import njit


closure_var = True # this would not be static in the real world...


@njit
def foo(a):
    if a.size == 0:
        if closure_var is True:
            raise ValueError('error message')
        result = 1.0
    else:
        result = 0.0
    return np.isfinite(result)


foo(np.arange(10)/10)
```

**Comment by esc** [comment]
@ARF1 thanks for reporting this. I have tried locally and I can reproduce this error.  I also tried using the `inline` keyword:

```python
import numpy as np
from numba import njit


closure_var = True # this would not be static in the real world...


@njit(inline="always")
def barbar_does_not_work(a):
    if closure_var is True:
        raise ValueError('error message')
    return 1.0


@njit
def foo(a):
    if a.size == 0:
        result = barbar_does_not_work(a)
    else:
        result = 0.0
    return np.isfinite(result)


foo(np.arange(10)/10)

```

But that results in the following:

```
💥 zsh» python foo/foo125.py                                                                                                                                        :(
Traceback (most recent call last):
  File "foo/foo125.py", line 41, in <module>
    foo(np.arange(10)/10)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 342, in error_rewrite
    raise e
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 104, in _compile_core
  1 import numpy as np¬
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 548, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 328, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 390, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 370, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 361, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 335, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 326, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 290, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 263, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 89, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 66, in type_inference_stage
    infer.build_constraint()
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 938, in build_constraint
    self.constrain_statement(inst)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 1297, in constrain_statement
    raise UnsupportedError(msg, loc=inst.loc)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: nopython frontend)
Unsupported constraint encountered: raise $14call_function.2.6

File "foo/foo125.py", line 16:
def barbar_does_not_work(a):
    <source elided>
    if closure_var is True:
        raise ValueError('error message')
        ^
```

**Comment by stuartarchibald** [comment]
> Unsupported constraint encountered: raise $14call_function.2.6

expect the pipeline needs to run the `GenericRewrites` pass after inlining, https://github.com/numba/numba/blob/f3ca34da03b03c62a27daacfbddf63f7d72e7cee/numba/core/compiler.py#L455-L456, or the inliner itself needs to run an `untyped IR` subpipeline, which actually might more more sense as the IR being injected should then be legal regardless where the inliner is sequenced.

**Comment by stuartarchibald** [comment]
Think this is a feature request asking for type refinement based on CFG+predicate type analysis.

**Comment by ARF1** [comment]
@esc I tried the `inline` keyword as well. :-) By in my instance it probably would not have been a solution anyway since I split my function into multiple functions explicitly to deal with typing problems that occurred when all the code was in a single function.
