### ISSUE TITLE
Writing to a global array silently fails

### ISSUE THREAD

**Issue by pitrou** [numba/numba#528]
(but reading from it succeeds)

```
>>> a = np.arange(10)
>>> b = np.arange(10, 20)
>>> def read_global(target):
...     target[1] = a[1]
... 
>>> def write_global(source):
...     b[2] = source[2]
... 
>>> jit(nopython=True)(read_global)(b)
>>> b
array([10,  1, 12, 13, 14, 15, 16, 17, 18, 19])
>>> jit(nopython=True)(write_global)(a)
>>> b
array([10,  1, 12, 13, 14, 15, 16, 17, 18, 19])
```

**Comment by ssarangi** [comment]
while trying the above sequence of commands I see another set of errors instead of the results. 
I also tried explicitly setting b.flags.writeable=True but made no difference.

jit(nopython=True)(write_global)(a)
Traceback (most recent call last):
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typeinfer.py", line 98, in propagate
    constrain(context, typevars)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typeinfer.py", line 293, in __call__
    if not context.resolve_setitem(target=ty, index=it, value=vt):
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typing\context.py", line 120, in resolve_setitem
    return self.resolve_function_type("setitem", args, kws)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typing\context.py", line 89, in resolve_function_type
    res = defn.apply(args, kws)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typing\templates.py", line 142, in apply
    sig = generic(args, kws)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typing\builtins.py", line 506, in generic
    raise TypeError("Cannot modify value of type %s" %(ary,))
TypeError: Cannot modify value of type readonly array(int32, 1d, C)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Tools\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3035, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-28-aaeb61366823>", line 1, in <module>
    jit(nopython=True)(write_global)(a)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\dispatcher.py", line 159, in _compile_for_args
    return self.compile(sig)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\dispatcher.py", line 322, in compile
    flags=flags, locals=self.locals)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 594, in compile_extra
    return pipeline.compile_extra(func)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 317, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 326, in compile_bytecode
    return self._compile_bytecode()
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 581, in _compile_bytecode
    return pm.run(self.status)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 209, in run
    raise patched_exception
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 201, in run
    res = stage()
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 414, in stage_nopython_frontend
    self.locals)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\compiler.py", line 709, in type_inference_stage
    infer.propagate()
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typeinfer.py", line 399, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "E:\Tools\Anaconda3\lib\site-packages\numba\typeinfer.py", line 104, in propagate
    loc=constrain.loc)
numba.errors.TypingError: Failed at nopython (nopython frontend)
Internal error at <numba.typeinfer.SetItemConstrain object at 0x000000000687F630>:
Cannot modify value of type readonly array(int32, 1d, C)
File "<ipython-input-25-77015b89a1df>", line 2

**Comment by stuartarchibald** [comment]
As of Numba 0.37 the original sample does this:
```
numba.errors.InternalError: Cannot modify value of type readonly array(int64, 1d, C)
[1] During: typing of staticsetitem at issue528.py (9)
```
silent failure is prevented. Please reopen if this is still an issue.
