### ISSUE TITLE
Compilation failure when overload contains *args and multiple keyword arguments

### ISSUE THREAD

**Issue by ARF1** [numba/numba#5291]
On the current master, compilation fails when an overloaded function contains `*args` and multiple keyword arguments.

Note: In the example below, if one deletes `bar`, compilation succeeds.

```python
from numba import njit
from numba.extending import overload

def foo(*args, **kwargs):
    # stub for overload
    pass


@overload(foo)
def foo_ovl(*args, bar1=None, bar2=None):
    def foo_impl(*args, bar1=None, bar2=None):
        return args

    return foo_impl


@njit
def test(a, b):
    return foo(a, b)


test(1, 2)
```

Output:
```
Traceback (most recent call last):
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\My User\.vscode\extensions\ms-python.python-2020.2.63990\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "Z:\Systemdateien\Miniconda3\envs\llvmlite-dev\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\My User\Documents\numba\Untitled-2.py", line 22, in <module>
    test(1, 2)
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "c:\Users\My User\Documents\numba\numba\core\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "c:\Users\My User\Documents\numba\numba\core\utils.py", line 77, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
?[1m?[1m?[1mInvalid use of Function(<function foo at 0x0000027BE7E333A0>) with argument(s) of type(s): (int64, int64)
 * parameterized
?[1mIn definition 0:?[0m
?[1m    IndexError: tuple index out of range?[0m
    raised from c:\Users\My User\Documents\numba\numba\core\typing\templates.py:169
?[1mIn definition 1:?[0m
?[1m    IndexError: tuple index out of range?[0m
    raised from c:\Users\My User\Documents\numba\numba\core\typing\templates.py:169
?[1mThis error is usually caused by passing an argument of a type that is unsupported by the named function.?[0m?[0m
?[0m?[1m[1] During: resolving callee type: Function(<function foo at 0x0000027BE7E333A0>)?[0m
?[0m?[1m[2] During: typing of call at c:\Users\My User\Documents\numba\Untitled-2.py (19)
?[0m
?[1m
File "Untitled-2.py", line 19:?[0m
?[1mdef test(a, b):
?[1m    return foo(a, b)
?[0m    ?[1m^?[0m?[0m
```

**Comment by esc** [comment]
@ARF1 thanks for reporting this, you continued efforts to debug Numba are appreciated. I can reproduce this locally and will mark as a bug. Also note that I have recently encountered similar issues related to star-arg ( `*args`)  handling while attempting to implement a feature. 

Also note that I tried the following variant:

```python
def foo(*args, bar1=None, bar2=None):
    # stub for overload
    pass
```

I.e. spec'ing the keyword arguments explicitly in the function that is being overloaded---but it didn't make any difference.

**Comment by ARF1** [comment]
@esc I promise, I am not really setting out to find bugs in numba. ;-) I am working on unifying the array reduction routines and in doing so I keep stumbling across the bugs by accident...

In case this helps pinpoint this issue further, this issue is not specific to `overload`. It also occurs with `generated_jit`_

```python
from numba import njit, generated_jit


@generated_jit
def foo(*args, bar1=None, bar2=None):
    def foo_impl(*args, bar1=None, bar2=None):
        return args

    return foo_impl


@njit
def test(a, b):
    return foo(a, b)


test(1, 2)
```

**Comment by esc** [comment]
@ARF1 no worries, please do keep them coming. If the bugs you find can be attached to a real-world use-case of something you are trying to achieve all the better. I think there are some 'wobbly' bits in `numba/core/typing/templates.py`.

**Comment by stuartarchibald** [comment]
Think this is just a bug, it's binding with the assumption that all kwargs are provided. Suggested fix:
```diff
--- a/numba/core/typing/templates.py
+++ b/numba/core/typing/templates.py
@@ -165,8 +165,11 @@ def fold_arguments(pysig, args, kws, normal_handler, default_handler,
         bind_args = args
     bind_kws = kws.copy()
     if kwonly:
+        largs = len(args)
         for idx, n in enumerate(kwonly):
-            bind_kws[n] = args[len(kwonly) + idx]
+            aidx = len(kwonly) + idx
+            if aidx < largs:
+                bind_kws[n] = args[aidx]
 

```
however, I am suspicious that the `*args` is still not going to work as expected because it should consume non-kwonly args ahead of the bind to them. This code has been revisited numerous times, argument binding is hard, I don't expect this will be the last time it's visited.

**Comment by ARF1** [comment]
@stuartarchibald This fixes the compile error but you were right, `*args` is not yet working with your patch. It is empty.

```python
from numba import njit, generated_jit


@generated_jit
def foo(*args, bar1=None, bar2=None):
    def foo_impl(*args, bar1=None, bar2=None):
        return args

    return foo_impl


@njit
def test(a, b):
    return foo(a, b)


print(test(1, 2))
```

Output:
```
()
```

**Comment by stuartarchibald** [comment]
Thanks for confirming, and yes, I think the second part to do with star args consuming ahead of binding needs to be done for it to work, else the kwonly part will just consume as many args as it can for those args known to be kwonly.

**Comment by ARF1** [comment]
@stuartarchibald The following seems to work for me:

```patch
diff --git a/numba/core/typing/templates.py b/numba/core/typing/templates.py
index 8674b2fc3..c2eec23a9 100644
--- a/numba/core/typing/templates.py
+++ b/numba/core/typing/templates.py
@@ -152,19 +152,21 @@ def fold_arguments(pysig, args, kws, normal_handler, default_handler,
         # Normalize dict kws
         kws = dict(kws)
 
-    # deal with kwonly args
+
+    # deal with var_positional and kwonly args
     params = pysig.parameters
+    var_positional = any(p.kind == p.VAR_POSITIONAL for name, p in params.items())
     kwonly = []
     for name, p in params.items():
         if p.kind == p.KEYWORD_ONLY:
             kwonly.append(name)
 
-    if kwonly:
+    if kwonly and not var_positional:
         bind_args = args[:-len(kwonly)]
     else:
         bind_args = args
     bind_kws = kws.copy()
-    if kwonly:
+    if kwonly and not var_positional:
         for idx, n in enumerate(kwonly):
             bind_kws[n] = args[len(kwonly) + idx]
 
```

Test-case:
```python
from numba import njit, generated_jit


@generated_jit
def foo(a, *args, bar1=None, bar2=None):
    def foo_impl(a, *args, bar1=None, bar2=None):
        print('a: ', a)
        print('args: ', args)
        print('bar1: ', bar1)
        print('bar2: ', bar2)

    return foo_impl


@njit
def test(a, b):
    foo(a, b, 3, 5, bar2=4)


test(1, 2)
```

Output:
```
a:  1
args:  (2, 3, 5)
bar1:  None
bar2:  4
```

There is however still an unrelated issue elsewhere: `p.kind` is `POSITIONAL_OR_KEYWORD` for parameter `a` in the test-case when it should be `POSITIONAL_ONLY`. This does not seem to hurt ATM however.

**Comment by ARF1** [comment]
The above mentioned classification as `POSITIONAL_OR_KEYWORD` is in fact correct.

**Comment by ARF1** [comment]
Fixed with PR #5292.
