### ISSUE TITLE
uninitialized typed-list extending iterable that cannot be sliced

### ISSUE THREAD

**Issue by rohitsanj** [numba/numba#5306]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

An unitialized typed-list cannot extend an iterable that cannot be sliced. 

Reproducible example:
```python
from numba.typed import List

def foo():
     l = List()
     l.extend("")
     return l

foo()
```
Error:
```
Traceback (most recent call last):
  File "test_iterable.py", line 8, in <module>
    foo()
  File "test_iterable.py", line 5, in foo
    l.extend("")
  File "/Users/rohitsanjay/numba/numba/typed/typedlist.py", line 323, in extend
    self._initialise_list(iterable[0])
IndexError: string index out of range
```
https://github.com/numba/numba/blob/master/numba/typed/typedlist.py#L318-L326

This issue was encountered while working on test cases for #5295 

cc @esc @stuartarchibald

**Comment by esc** [comment]
@rohitsanj thanks for looking into this, I think the issue here is that the `iterable` is empty and so the `getitem` fails, probably some cases have to be added for this. The fix can be a part of #5295

**Comment by esc** [comment]
Probably it's fine to just check that it doesn't have zero length for now.

**Comment by rohitsanj** [comment]
Alright, and what if it does have zero length?

**Comment by esc** [comment]
@rohitsanj not sure what the semantics should be, but looking at what cPython does is usually a good start.

```
In [1]: l = list("abc")

In [2]: l.extend("")

In [3]: l
Out[3]: ['a', 'b', 'c']
```

So, and extend with an empty thing results in a no-op and this what I think Numba should do also.

**Comment by rohitsanj** [comment]
I have modified the `extend` function as follows:
```
diff --git a/numba/typed/typedlist.py b/numba/typed/typedlist.py
index 0b0f73d6d..0e5313af2 100644
--- a/numba/typed/typedlist.py
+++ b/numba/typed/typedlist.py
@@ -320,9 +320,10 @@ class List(MutableSequence):
             # Need to get the first element of the iterable to initialise the
             # type of the list. FIXME: this may be a problem if the iterable
             # can not be sliced.
-            self._initialise_list(iterable[0])
-            self.append(iterable[0])
-            return _extend(self, iterable[1:])
+            if len(iterable) > 0:
+                self._initialise_list(iterable[0])
+                self.append(iterable[0])
+                return _extend(self, iterable[1:])
         return _extend(self, iterable)
```
And now it throws this error when I try to run the example mentioned in the PR desc:
```
Traceback (most recent call last):
  File "test_iterable.py", line 8, in <module>
    foo()
  File "test_iterable.py", line 5, in foo
    l.extend("")
  File "/Users/rohitsanjay/numba/numba/typed/typedlist.py", line 327, in extend
    return _extend(self, iterable)
  File "/Users/rohitsanjay/numba/numba/core/dispatcher.py", line 604, in typeof_pyval
    tp = typeof(val, Purpose.argument)
  File "/Users/rohitsanjay/numba/numba/core/typing/typeof.py", line 29, in typeof
    ty = typeof_impl(val, c)
  File "/Users/rohitsanjay/miniconda3/lib/python3.7/functools.py", line 827, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/rohitsanjay/numba/numba/core/typing/typeof.py", line 55, in typeof_impl
    return getattr(val, "_numba_type_", None)
  File "/Users/rohitsanjay/numba/numba/typed/typedlist.py", line 229, in _numba_type_
    raise TypeError("invalid operation on untyped list")
TypeError: invalid operation on untyped list
```

I'm not sure how to make it result in a no-op. Can you help me out? :)

**Comment by esc** [comment]
The comment about non-slicable  iterables  is about things like generators, where we can only iterate over the things, but not access the items with random access (i.e. `getitem`)  or get their length. This makes it hard to refine the list.

**Comment by esc** [comment]
@rohitsanj I am not sure where that error comes from.

**Comment by rohitsanj** [comment]
Alright, I will look into it.

Also, I'm not sure which comment you are referring to. 

Will I have to implement `extend` for generators? Or is it an edge case that needs to be handled well?

**Comment by esc** [comment]
@rohitsanj maybe it makes most sense to continue on #5295 and I'll review the code there?
