### ISSUE TITLE
typed.List variables cannot be assigned from reflected_list

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#5353]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi, 

On Numba 0.48.0 we experience a problem with typed.Lists which cannot be assigned from instances of normal or reflected list, probably due to the lack of implicit conversions, e.g. with both reproducers below compilation fails with errors similar to:

```
======================================================================
ERROR: test_numba_typed_vs_reflected_lists (sdc.tests.test_series.TestSeries)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\hpat\sdc\tests\test_series.py
", line 6777, in test_numba_typed_vs_reflected_lists
    print(jitted(ref_list))
  File "c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\numba\disp
atcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\numba\disp
atcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\numba\six.
py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (DictT
ype[int64,ListType[int64]], Literal[int](3), reflected list(int32))
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast reflected list(int32) to ListType[int64]: %".51" = load {i8*, i8*}, {i8*, i8
*}* %"value"

File "..\numba_master\numba\numba\dictobject.py", line 683:
    def impl(d, key, value):
        <source elided>
        castedkey = _cast(key, keyty)
        castedval = _cast(value, valty)
        ^

[1] During: lowering "$18call_function.7 = call $12load_global.4(value, $16load_deref.6,
 func=$12load_global.4, args=[Var(value, dictobject.py:682), Var($16load_deref.6, dictob
ject.py:683)], kws=(), vararg=None)" at c:\users\akozlov\appdata\local\continuum\anacond
a3\numba_master\numba\numba\dictobject.py (683)
    raised from c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\nu
mba\six.py:669
In definition 3:
    LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast reflected list(int32) to ListType[int64]: %".51" = load {i8*, i8*}, {i8*, i8
*}* %"value"

File "..\numba_master\numba\numba\dictobject.py", line 683:
    def impl(d, key, value):
        <source elided>
        castedkey = _cast(key, keyty)
        castedval = _cast(value, valty)
        ^

[1] During: lowering "$18call_function.7 = call $12load_global.4(value, $16load_deref.6,
 func=$12load_global.4, args=[Var(value, dictobject.py:682), Var($16load_deref.6, dictob
ject.py:683)], kws=(), vararg=None)" at c:\users\akozlov\appdata\local\continuum\anacond
a3\numba_master\numba\numba\dictobject.py (683)
    raised from c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\nu
mba\six.py:669
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
In definition 14:
    All templates rejected with literals.
In definition 15:
    All templates rejected without literals.
In definition 16:
    TypingError: Operator setitem(). The object
 given: DictType[int64,ListType[int64]]
 expected: SeriesType
    raised from C:\Users\akozlov\AppData\Local\Continuum\anaconda3\hpat\sdc\utilities\sd
c_typing_utils.py:75
In definition 17:
    TypingError: Operator setitem(). The object
 given: DictType[int64,ListType[int64]]
 expected: SeriesType
    raised from C:\Users\akozlov\AppData\Local\Continuum\anaconda3\hpat\sdc\utilities\sd
c_typing_utils.py:75
This error is usually caused by passing an argument of a type that is unsupported by the
 named function.
[1] During: typing of staticsetitem at C:\Users\akozlov\AppData\Local\Continuum\anaconda
3\hpat\sdc\tests\test_series.py (6766)

File "sdc\tests\test_series.py", line 6766:
        def test_impl(ref_list):
            <source elided>
            a_dict = Dict.empty(types.int64, list_type1)
            a_dict[3] = ref_list
            ^
```

Can you please fix that?

Reproducers:
```
    def test_numba_typed_vs_reflected_lists(self):
        import numba
        from numba import types
        from numba.typed import Dict, List
        list_type1 = types.ListType(types.int64)

        def test_impl(ref_list):
            # normal python list is still by default old List type
            # so this fails to compile as we assign reflected list 
            # to a variable that expects typed.List
#             ref_list = [i for i in np.arange(n) if i in values]
            a_dict = Dict.empty(types.int64, list_type1)
            a_dict[3] = ref_list

            # example workaround:
#             a_dict[3] = List.empty_list(types.int64)
#             a_dict[3].extend(ref_list)

            return len(a_dict[3])
        jitted = numba.njit(test_impl)

        n = 10
        ref_list = list(np.arange(n))
        print(jitted(ref_list))
```
or
```
    def test_numba_typed_vs_reflected_lists(self):
        import numba
        from numba import types
        from numba.typed import Dict, List
        list_type1 = types.ListType(types.int64)

        def test_impl(n, values):
            # normal python list is still by default old List type
            # so this fails to compile as we assign reflected list 
            # to a variable that expects typed.List
            ref_list = [i for i in np.arange(n) if i in values]
            a_dict = Dict.empty(types.int64, list_type1)
            a_dict[3] = ref_list

            # example workaround:
#             a_dict[3] = List.empty_list(types.int64)
#             a_dict[3].extend(ref_list)

            return len(a_dict[3])
        jitted = numba.njit(test_impl)

        n = 10
        good_values = {1, 2, 4, 6}
        print(jitted(n, good_values))
```
 
Numba version:
# Name                    Version                   Build  Channel
numba                     0.48.0                    dev_0    <develop>

Best Regards,
Alexey.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is expected given reflected lists and typed lists are fundamentally different types. Once typed list becomes default this will hopefully resolve itself.
