### ISSUE TITLE
0.48.0 breaks TBB support (installing from pip)

### ISSUE THREAD

**Issue by bmerry** [numba/numba#5371]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When using parallel mode and requesting TBB (either as `'tbb'` or `'safe'`), I get an exception, but it worked in 0.47. I am installing `numba` from a wheel (numba-0.48.0-cp36-cp36m-manylinux1_x86_64.whl) and have also done `pip install tbb` (and even `pip install tbb4py`). Testing with tbb4py-2019.0-cp36-cp36m-manylinux1_x86_64.whl and tbb-2019.0-py2.py3-none-manylinux1_x86_64.whl.

## Example code

```python
#!/usr/bin/env python
import numpy as np
import numba
numba.config.THREADING_LAYER = 'safe'

@numba.jit(nopython=True, parallel=True)
def add(a, b):
    for i in numba.prange(len(a)):
        a[i] += b[i]


a = np.ones(4)
b = np.ones(4)
add(a, b)
print(a)
```

## Output

```
Traceback (most recent call last):
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/errors.py", line 717, in new_error_context
    yield
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/lowering.py", line 288, in lower_block
    self.lower_inst(inst)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/lowering.py", line 476, in lower_inst
    func(self, inst)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/npyufunc/parfor.py", line 284, in _lower_parfor_parallel
    parfor.races)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/npyufunc/parfor.py", line 1240, in call_parallel_gufunc
    _launch_threads()
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/npyufunc/parallel.py", line 444, in _launch_threads
    raise_with_hint(requirements)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/npyufunc/parallel.py", line 389, in raise_with_hint
    raise ValueError(errmsg % hint)
ValueError: No threading layer could be loaded.
HINT:
Intel TBB is required, try:
$ conda/pip install tbb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./numba-tbb.py", line 14, in <module>
    add(a, b)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler.py", line 373, in _compile_core
    raise e
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 347, in run
    raise patched_exception
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/typed_passes.py", line 407, in run_pass
    NativeLowering().run_pass(state)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/typed_passes.py", line 349, in run_pass
    lower.lower()
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/lowering.py", line 195, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/lowering.py", line 248, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/lowering.py", line 273, in lower_function_body
    self.lower_block(block)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/lowering.py", line 288, in lower_block
    self.lower_inst(inst)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/errors.py", line 725, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/bmerry/work/sdp/env3/lib/python3.6/site-packages/numba/six.py", line 669, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No threading layer could be loaded.
HINT:
Intel TBB is required, try:
$ conda/pip install tbb

File "numba-tbb.py", line 8:
def add(a, b):
    for i in numba.prange(len(a)):
    ^

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.4, range = (0, a_size0.1, 1))]{20: <ir.Block at ./numba-tbb.py (8)>}Var(parfor_index.4, numba-tbb.py:8)" at ./numba-tbb.py (8)
```

## numba -s

```
__Time Stamp__
2020-03-10 11:26:10.398523

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake
Number of accessible CPU cores                : 8
Listed accessible CPUs cores                  : 0-7
CFS restrictions                              : None
CPU Features                                  : 
64bit adx aes avx avx2 bmi bmi2 clflushopt cmov cx16 f16c fma fsgsbase invpcid
lzcnt mmx movbe pclmul popcnt prfchw rdrnd rdseed sahf sgx sse sse2 sse3 sse4.1
sse4.2 ssse3 xsave xsavec xsaveopt xsaves

__OS Information__
Platform                                      : Linux-5.3.0-40-generic-x86_64-with-Ubuntu-18.04-bionic
Release                                       : 5.3.0-40-generic
System Name                                   : Linux
Version                                       : #32~18.04.1-Ubuntu SMP Mon Feb 3 14:05:59 UTC 2020
OS specific info                              : Ubuntu18.04bionic
glibc info                                    : glibc 2.25

__Python Information__
Python Compiler                               : GCC 8.0.1 20180414 (experimental) [trunk revision 259383
Python Implementation                         : CPython
Python Version                                : 3.6.6
Python Locale                                 : en_GB UTF-8

__LLVM information__
LLVM version                                  : 8.0.0

__CUDA Information__
Found 1 CUDA devices
id 0     b'GeForce GTX 1070'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 1
Summary:
	1/1 devices are supported
CUDA driver version                           : 10010
CUDA libraries:
Finding cublas from System
	named  libcublas.so
	trying to open library...	ok
Finding cusparse from System
	named  libcusparse.so.10.3.0.243
	trying to open library...	ok
Finding cufft from System
	named  libcufft.so.10.1.1.243
	trying to open library...	ok
Finding curand from System
	named  libcurand.so.10.1.1.243
	trying to open library...	ok
Finding nvvm from System
	named  libnvvm.so.3.3.0
	trying to open library...	ok
Finding libdevice from System
	searching for compute_20...	ok
	searching for compute_30...	ok
	searching for compute_35...	ok
	searching for compute_50...	ok

__ROC Information__
ROC available                                 : False
Error initialising ROC due to                 : No ROC toolchains found.
No HSA Agents found, encountered exception when searching:
Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:

__SVML Information__
SVML state, config.USING_SVML                 : False
SVML library found and loaded                 : False
llvmlite using SVML patched LLVM              : True
SVML operational                              : False

__Threading Layer Information__
TBB Threading layer available                 : False
+--> Disabled due to                          : Unknown import problem.
OpenMP Threading layer available              : False
+--> Disabled due to                          : Unknown import problem.
Workqueue Threading layer available           : True

__Numba Environment Variable Information__
None set.

__Conda Information__
Conda not present/not working.
Error was [Errno 2] No such file or directory: 'conda': 'conda'
```

**Comment by bmerry** [comment]
Incidentally, if I compile from source and set TBBROOT=/usr then things work, even without the tbb/tbb4py Python packages (I'm assuming because it picks up my OS-provided TBB). So my suspicion is that the wheel was just compiled without TBB support, but I'm not sure how to prove it.

**Comment by stuartarchibald** [comment]
Thanks for the report.
```
$ find <path>/_tmp_issue5371/lib/python3.7/site-packages/numba/|grep -i "\\.so"
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/runtime/_nrt_python.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/cuda/cudadrv/_extras.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/mviewbuf.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/jitclass/_box.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/npyufunc/workqueue.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/npyufunc/_internal.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/typeconv/_typeconv.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/_dynfunc.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/_dispatcher.cpython-37m-x86_64-linux-gnu.so
<path>/_tmp_issue5371/lib/python3.7/site-packages/numba/_helperlib.cpython-37m-x86_64-linux-gnu.so
```
suggests no TBB compiled in.

**Comment by stuartarchibald** [comment]
@sklam do you recall if the wheel builder changed between 0.47 and 0.48?

**Comment by sklam** [comment]
oh, I automated it in our build farm. I need to verify the scripts there.

**Comment by stuartarchibald** [comment]
Should probably check OpenMP at the same time as TBB ?

**Comment by sklam** [comment]
This should now be fixed in the upcoming 0.49.0rc1 wheels. Note we will need to have a TBB enabled wheel and a no-TBB wheel. The TBB library uses symbol that is only available in `manylinux2014`,

**Comment by stuartarchibald** [comment]
Builds from your channel work @sklam :
```
$ pip install tbb
Collecting tbb                                                                                                                  
  Using cached tbb-2020.0.133-py2.py3-none-manylinux1_x86_64.whl (933 kB)                                                       
Installing collected packages: tbb
Successfully installed tbb-2020.0.133

$ pip list
Package     Version            
----------- -------------------
certifi     2019.11.28         
llvmlite    0.31.0             
mkl-fft     1.0.15             
mkl-random  1.1.0              
mkl-service 2.3.0              
numba       0.49.0rc1          
numpy       1.18.1             
pip         20.0.2             
setuptools  46.1.3.post20200330
six         1.14.0             
tbb         2020.0.133         
wheel       0.34.2  

$ numba -s|grep TBB
TBB Threading layer available                 : True
```
and OP example code works fine.

@bmerry test binaries are available via:
```
pip install  -i https://pypi.anaconda.org/sklam/label/airflow/simple numba
```
usual caveats about development versions etc apply.

**Comment by bmerry** [comment]
Thanks for working on it @sklam. I'll try it out once there is a final release.
