### ISSUE TITLE
Shared Memory behaves inconsistently in NUMBA_ENABLE_CUDASIM

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#5374]
The following will happily work in real CUDA, but not NUMBA_ENABLE_CUDASIM. Shared stuff on the simulated card needs further review.
```
    import numpy as np
    import numba as nb
    from numba import cuda
    def test_record_access(self):
        backyard_type = [('statue', np.float64),
                         ('newspaper', np.float64, (6,))]

        goose_type = [('garden', np.float64, (12,)),
                      ('town', np.float64, (42,)),
                      ('backyard', backyard_type)]

        goose_np_type = np.dtype(goose_type, align=True)

        goose_nb_type = nb.from_dtype(goose_np_type)

        @cuda.jit
        def simple_kernel(f):
            f.garden[0] = 45.0
            shr = cuda.shared.array(1, dtype=goose_nb_type)
            shr[0].backyard.statue = 45
            f.backyard.statue = shr[0].backyard.statue
            f.backyard.newspaper[3] = 2.0
            f.backyard.newspaper[3] = f.backyard.newspaper[3] + 3.0

        item = np.recarray(1, dtype=goose_np_type)
        simple_kernel[1, 1](item[0])
        np.testing.assert_equal(item[0]['garden'][0], 45)
        np.testing.assert_equal(item[0]['backyard']['newspaper'][3], 5)
        np.testing.assert_equal(item[0]['backyard']['statue'], 45)
```

**Comment by stuartarchibald** [comment]
CC @gmarkall

**Comment by gmarkall** [comment]
Thanks for the report!

Could you outline the difference between the CUDA target and the simulator in this case please? E.g. does the simulator crash, or does it produce different results?

Do you have self-contained example that demonstrates the issue?

**Comment by c200chromebook** [comment]
also needs the includes, sorry:
```
import numpy as np
import numba as nb
from numba import cuda
```

Cuda Target:

Process finished with exit code 0

Cudasim:
```
Traceback (most recent call last):
  File "mpidemo.py", line 27, in <module>
    simple_kernel[1, 1](item[0])
  File "numba\cuda\simulator\kernel.py", line 106, in __call__
    bm.run(grid_point, *fake_args)
  File "numba\cuda\simulator\kernel.py", line 271, in run
    reraise(*(t.exception))
  File "numba\core\utils.py", line 77, in reraise
    raise value.with_traceback(tb)
  File "numba\cuda\simulator\kernel.py", line 170, in run
    super(BlockThread, self).run()
  File "lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "numba\cuda\simulator\kernel.py", line 249, in target
    self._f(*args)
  File "mpidemo.py", line 21, in simple_kernel
    shr[0].backyard.statue = 45
AttributeError: tid=[0, 0, 0] ctaid=[0, 0, 0]: 'numpy.void' object has no attribute 'backyard'
```

**Comment by esc** [comment]
@gmarkall would you have a spare minute to take another look at this? Thank you!

**Comment by gmarkall** [comment]
With Numba master, this now seems to finish with exit code 0 for me with both the hardware and the simulator - @c200chromebook could you confirm whether the issue is resolved please?

**Comment by gmarkall** [comment]
Closing as there's no further update and the issue appears not to reproduce.
