### ISSUE TITLE
CUDA simulator atomic operation differs to documentation

### ISSUE THREAD

**Issue by geromidg** [numba/numba#5458]
According to [docs](https://numba.pydata.org/numba-doc/dev/cuda/intrinsics.html), the CUDA atomic `add` and `max` operations return the old value at the index location, but the fake [implementation](https://github.com/numba/numba/blob/master/numba/cuda/simulator/kernelapi.py#L106) in the CUDA simulator does not return anything.

Is that intentional in the simulator? Does the actual CUDA operation have a return value?
Thank you.

**Comment by esc** [comment]
@geromidg thanks for asking about this on the Numba issue tracker. @gmarkall , could you perhaps take a look at this one.

**Comment by gmarkall** [comment]
I can - sounds like a bug, I'll see if I can reproduce.

**Comment by esc** [comment]
@gmarkall awesome, thanks!

**Comment by gmarkall** [comment]
Executable reproducer:

```python
from numba import cuda
import numpy as np


@cuda.jit
def atomic_test(x):
    x[1] = cuda.atomic.add(x, 0, 1)


x = np.zeros(2, dtype=np.int32)
INITIAL = 10
x[0] = INITIAL

atomic_test[1, 1](x)
assert x[1] == INITIAL
```

Works fine on hardware, on the simulator falls over with:

```
$ NUMBA_ENABLE_CUDASIM=1 python repro.py 
Traceback (most recent call last):
  File "repro.py", line 14, in <module>
    atomic_test[1, 1](x)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 106, in __call__
    bm.run(grid_point, *fake_args)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 271, in run
    reraise(*(t.exception))
  File "/home/gmarkall/numbadev/numba/numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 170, in run
    super(BlockThread, self).run()
  File "/home/gmarkall/miniconda3/envs/numbaenv/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/kernel.py", line 249, in target
    self._f(*args)
  File "repro.py", line 7, in atomic_test
    x[1] = cuda.atomic.add(x, 0, 1)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/cudadrv/devicearray.py", line 72, in __setitem__
    self._item.__setitem__(idx, val)
  File "/home/gmarkall/numbadev/numba/numba/cuda/simulator/cudadrv/devicearray.py", line 131, in __setitem__
    return self._ary_access.__setitem__(idx, val)
TypeError: tid=[0, 0, 0] ctaid=[0, 0, 0]: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

**Comment by gmarkall** [comment]
I've started working on a fix in https://github.com/gmarkall/numba/tree/grm-issue-5458 - I need to fix up some of the tests I've added first (issues around handling NaNs correctly).
