### ISSUE TITLE
typed.Dict.get return value has OptionalType when default value is provided

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#5468]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi, 

Please take a look at the following issue with typed.Dict.get method for which the type of return value is inferred as OptionalType even when default argument is provided and is of the same type as dictionary's value_type.

Here's the reproducer:
```
import numba
from numba import types
from numba.typed import Dict, List

import unittest
import numpy as np

class TestSuite(unittest.TestCase):

    def test_numba_typed_dict_get_optional_type(self):

        def test_impl(A):
            res = np.empty(len(A), dtype=types.int64)
            group_to_count = List.empty_list(types.int64)
            key_to_group_number = {}

            total_keys = 0
            for i, value in enumerate(A):
                # the type of grp is inferred as OptionalType(int64)
                # even though default arg was provided and is not None
                grp = key_to_group_number.get(value, -1)
                if grp == -1:        # this line compiles OK
                    key_to_group_number[value] = total_keys
                    group_to_count.append(1)
                    res[i] = total_keys
                    total_keys += 1
                else:
                    group_to_count[grp] += 1   # but this won't
                    # a workaround is make explicit cast:
                    # group_to_count[types.int64(grp)] += 1
                    res[i] = grp

            return res, group_to_count
        jitted = numba.njit(test_impl)

        np.random.seed(0)
        n = 20
        A = np.random.choice(['a', 'b', 'c', 'd', 'e'], n)
        grouper, group_sizes = jitted(A)

        print(f'data: {A}')
        print(f'grouper: {grouper}')
        print(f'group_sizes: {group_sizes}')

if __name__ == "__main__":
    unittest.main()
```

Gives:
```
Traceback (most recent call last):
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\example_test.py", line 76,
in test_numba_typed_dict_get_optional_type
    grouper, group_sizes = jitted(A)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py",
line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py",
line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\utils.py", line
79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
list indices must be integers or slices
[1] During: typing of intrinsic-call at C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\n
umba\example_test.py (65)

File "example_test.py", line 65:
        def test_impl(A):
            <source elided>
                else:
                    group_to_count[grp] += 1   # but this won't
                    ^
```

If workaround is applied, inspect_types() shows grp is OptionalType:
```
                # --- LINE 21 ---
                #   $60load_method.6 = getattr(value=key_to_group_number, attr=get)  :: BoundFunction((<c
lass 'numba.core.types.containers.DictType'>, 'get') for DictType[[unichr x 1],int64])
                #   $const64.8 = const(int, -1)  :: Literal[int](-1)
                #   $66call_method.9 = call $60load_method.6(value, $const64.8, func=$60load_method.6, ar
gs=[Var(value, example_test.py:18), Var($const64.8, example_test.py:21)], kws=(), vararg=None)  :: ([unic
hr x 1], Literal[int](-1)) -> OptionalType(int64) i.e. the type 'int64 or None'
                #   del $const64.8
                #   del $60load_method.6
                #   grp = $66call_method.9  :: OptionalType(int64) i.e. the type 'int64 or None'
                #   del $66call_method.9

                grp = key_to_group_number.get(value, -1)
```

The issue is observed both on Numba 0.48 branch and master:
# Name                    Version                   Build  Channel
numba                     0.49.0.dev0+1043.g0a8b81189           dev_0    <develop>

Best Regards,
Alexey.

**Comment by esc** [comment]
@kozlov-alexey thanks for reporting this. I can reproduce this locally so I will mark as a bug. I think there may have been a similar issue on the issue tracker recently but I failed to find it.

**Comment by stuartarchibald** [comment]
Small reproducer:
```python
@njit
def test_impl():
    key_to_group_number = {}
    key_to_group_number[12] = 9
    z = key_to_group_number.get(10, -1)
    return z

test_impl()
print(test_impl.inspect_types())
```
this is because the lookup in the dict is always typed as an optional:
https://github.com/numba/numba/blob/1e2dc49c699b72c48b258a7c15998b505058289a/numba/typed/dictobject.py#L412-L419

One way to fix would be to add the default value type into the lookup's typing to avoid having to produce the optional if the types are the same.

**Comment by esc** [comment]
IIRC the reason that `Optional` is used here to allow `numba_dict_lookup` to return if the slot in the dict for this key isn't occupied yet.

**Comment by stuartarchibald** [comment]
That may be so, does it really matter whether it's there if there's a default of a coercable type? Probably just needs a bit of design adjustment?

**Comment by esc** [comment]
@stuartarchibald yes, probably, in the end it is the return code that decides, so using a default value, whatever it may be for the given type, will probably be possible.
