### ISSUE TITLE
Capturing freevar tuples as tuples of consts

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#5469]
Hi,

It looks like capturing tuples from outside context does not preserve constness of tuple elements, unlike it's for scalar types, like integers that are captured as literal values. So attempting to use captured tuple in the following use case fails:

```
import numba
from numba import types
from numba.special import literal_unroll
from numba.extending import overload

def foo(item):
    pass

@overload(foo)
def foo_overload(item):
    if not isinstance(item, types.StringLiteral):
        return None
    item_literal_value = item.literal_value
    def foo_impl(item):
        return len(item_literal_value)
    return foo_impl

captured_tuple = ('abc', 'bb', 'c', 'dddd')
def test_impl():

    # freevar tuples are captured as tuples of non-const values, i.e.
    # captured_tuple is UniTuple(unicode_type x 4)
    for s in literal_unroll(captured_tuple):
        value = foo(s)
        print(value)

    # while this works, as tested_tuple is tuple of const values, i.e.
    # Tuple(Literal[str](abc), ... Literal[str](dddd))
#     tested_tuple = ('abc', 'bb', 'c', 'dddd')
#     for s in literal_unroll(tested_tuple):
#         value = foo(s)
#         print(value)

    return value

hpat_func = numba.njit(test_impl)
hpat_func()
```

Gives:
```
(SDC_MASTER) C:\Users\akozlov\AppData\Local\Continuum\anaconda3\hpat>python literal_u
nroll_over_captured.py
Traceback (most recent call last):
  File "literal_unroll_over_captured.py", line 37, in <module>
    hpat_func()
  File "c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\numba\d
ispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\numba\d
ispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "c:\users\akozlov\appdata\local\continuum\anaconda3\numba_master\numba\numba\s
ix.py", line 668, in reraise
    raise value.with_traceback(tb)
numba.errors.UnsupportedError: Failed in nopython mode pipeline (step: handles litera
l_unroll)
Failed in literal_unroll_subpipeline mode pipeline (step: switch const list for tuple
s)
Invalid use of literal_unroll, argument should be a tuple or a list of constant value
s, found unknown problem

File "literal_unroll_over_captured.py", line 23:
def test_impl():
    <source elided>
    # captured_tuple is UniTuple(unicode_type x 4)
    for s in literal_unroll(captured_tuple):
    ^

```

Can you please consider changing this so that freevar tuples are built as tuple of literal values?

Above was tested on:
numba                     0.48.0+0.gcc7e7c7cf.dirty           dev_0    <develop>

Best Regards,
Alexey.

**Comment by esc** [comment]
@kozlov-alexey thanks for reporting this, I can reproduce this and have labelled it as a bug accordingly.

**Comment by stuartarchibald** [comment]
@kozlov-alexey this is fixed on master and 0.49.0RC1 by virtue of https://github.com/numba/numba/pull/5182, the issue was the guard being too strong and not accepting freevar and global tuples, this bit is the fix https://github.com/numba/numba/pull/5182/files#diff-cf441a3a1255d5f19c14caa32641d71fR677-R680

Please could you confirm this to be the case? Thanks.

**Comment by kozlov-alexey** [comment]
@stuartarchibald Yes, it seems it's working on master already. Sorry for reporting, I should have tested on latest dev branch. So this can be closed.

**Comment by stuartarchibald** [comment]
@kozlov-alexey no problem, reports are always welcome. Thanks for confirming the fix. Closing.
