### ISSUE TITLE
Default value is not literal

### ISSUE THREAD

**Issue by AlexanderKalistratov** [numba/numba#5471]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numba

def inner(a):
    pass

@numba.extending.overload(inner)
def inner_overload(a):
    if not isinstance(a, numba.types.Literal):
        return None

    def impl(a):
        print(a)

    return impl

@numba.extending.register_jitable
def my_func(a='a'):
    inner(a)

@numba.njit()
def f():
    my_func()

f()
```

Output:
```
Traceback (most recent call last):
  File "./test.py", line 24, in <module>
    f()
  File ".../numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File ".../numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File ".../numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function my_func at 0x7ff222b79f70>) with argument(s) of type(s): ()
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<function inner at 0x7ff23f0ab700>) with argument(s) of type(s): (unicode_type)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
```

Version:
```python
@numba.njit()
def f_1():
    my_func('a')
```

Works fine.

Numba version is 0a8b8118987944e82603bfa3c90d87b80ffe5d99

**Comment by sklam** [comment]
Confirmed issue. Same problem if using `njit` instead of `register_jitable`.
