### ISSUE TITLE
literally with default values

### ISSUE THREAD

**Issue by AlexanderKalistratov** [numba/numba#5472]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
import numba

@numba.extending.register_jitable
def literally_with_default(a='a'):
    print(numba.literally(a))

@numba.njit()
def f():
    literally_with_default()

f()
```

Output:
```
Traceback (most recent call last):
  File "./literally_with_default.py", line 11, in <module>
    f()
  File ".../numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File ".../numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File ".../numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot request literal type.
```

Numba version is 0a8b8118987944e82603bfa3c90d87b80ffe5d99

**Comment by esc** [comment]
I just tried this with current `master`: `0.50.0dev0-4-g1e2dc49c69` and can confirm that I am able to reproduce it.

**Comment by sklam** [comment]
I'll need to check this against https://github.com/numba/numba/pull/5478
