### ISSUE TITLE
Raising of an exception in inlined function fails on compilation

### ISSUE THREAD

**Issue by densmirn** [numba/numba#5476]
- [ ] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

```python
from numba import njit

@njit(inline='always')
def inlining(msg):
    raise ValueError(msg)

@njit
def fn():
    return inlining('Something happened')

print(fn())
```

Traceback:
```
Traceback (most recent call last):
  File "test_inline.py", line 14, in <module>
    print(fn())
  File "numba\numba\dispatcher.py", line 420, in _compile_for_args
    raise e
  File "numba\numba\dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "numba\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "numba\numba\dispatcher.py", line 768, in compile
    cres = self._compiler.compile(args, return_type)
  File "numba\numba\dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "numba\numba\dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "numba\numba\dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "numba\numba\compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "numba\numba\compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "numba\numba\compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "numba\numba\compiler.py", line 373, in _compile_core
    raise e
  File "numba\numba\compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "numba\numba\compiler_machinery.py", line 347, in run
    raise patched_exception
  File "numba\numba\compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "numba\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "numba\numba\compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "numba\numba\compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "numba\numba\untyped_passes.py", line 312, in run_pass
    state.func_ir.blocks = simplify_CFG(state.func_ir.blocks)
  File "numba\numba\ir_utils.py", line 1237, in simplify_CFG
    return rename_labels(blocks)
  File "numba\numba\ir_utils.py", line 1188, in rename_labels
    topo_order.remove(return_label)
ValueError: Failed in nopython mode pipeline (step: inline inlinable functions)
list.remove(x): x not in list
```

 I faced the issue accidentally and unfortunately don't know real use case of that.
Numba version: ef119bcd1733ff49d71bdf2da8a66e91bb704f83

**Comment by stuartarchibald** [comment]
Thanks for the report. I expect this is because the inliner translates the bytecode of the function to IR and doesn't run passes to e.g. fix up raising exceptions. Fairly sure I've seen this reported, or a variant of it reported, before.

**Comment by stuartarchibald** [comment]
I've taken a bit of a look at what it would require to get this working. Essentially the `inline_closure_call` function would need its signature changing so as to take a load of the compiler state information to permit a correct compilation of the `callee`. This is because the `callee` should really be compiled to IR using the same options as the caller, as the inline option is applicable at IR level. The compiler itself can then have two new pipelines added, "untyped" and "typed", and the existing "nopython" pipeline can just be composed in part of these. The "untyped" pipeline can then be run on the `callee` to obtain IR with all the usual transforms taking place.

**Comment by stuartarchibald** [comment]
Ah, and, the `ValueError` coming from the CFG simplification is because once inlined the IR ends up like:
```
label 0:
    $2load_global.0 = global(inlining: CPUDispatcher(<function inlining at 0x7f0861b7c550>)) ['$2load_global.0']
    jump 1                                   []
label 1:
    $const2.0.0 = const(str, broken)         ['$const2.0.0']
    msg.1 = $const2.0.0                      ['$const2.0.0', 'msg.1']
    $6load_global.1.2 = global(ValueError: <class 'ValueError'>) ['$6load_global.1.2']
    $10call_function.3.4 = call $6load_global.1.2(msg.1, func=$6load_global.1.2, args=[Var(msg.1, issue5476.py:5)], kws=(), vararg=None) ['$10call_function.3.4', '$6load_global.1.2', 'msg.1']
    raise <class 'ValueError'>('broken')     []
label 2:
    $6return_value.2 = cast(value=$4call_function.1) ['$4call_function.1', '$6return_value.2']
    return $6return_value.2                  ['$6return_value.2']
```
block 2 is unreachable. Probably need to prune the CFG after inlining.
