### ISSUE TITLE
Installation fails on Windows 7 x64 with Python 3.8.2

### ISSUE THREAD

**Issue by LostInDarkMath** [numba/numba#5479]
The command `pip install numba` leads to this error:
```
Collecting numba
  Using cached https://files.pythonhosted.org/packages/c3/81/453926761dc00b02b22d1cd6935aaa8a736fca011d33615315bc7c132788/numba-0.48.0.tar.gz
Collecting llvmlite<0.32.0,>=0.31.0dev0 (from numba)
  Using cached https://files.pythonhosted.org/packages/17/fc/da81203725cb22d53e4f819374043bbfe3327831f3cb4388a3c020d7a497/llvmlite-0.31.0.tar.gz
Requirement already satisfied: numpy>=1.15 in d:\temp\mica\lib\site-packages (from numba) (1.18.2)
Requirement already satisfied: setuptools in d:\temp\mica\lib\site-packages\setuptools-40.8.0-py3.8.egg (from numba) (40.8.0)
Installing collected packages: llvmlite, numba
  Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    Complete output from command D:\Temp\MICA\Scripts\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\WILLI\\AppData\\Local\\Temp\\pip-install-x37fv0l1\\llvmlite\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\WILLI\AppData\Local\Temp\pip-record-z6pxzzr3\install-record.txt --single-version-externally-managed --compile --install-headers D:\Temp\MICA\include\site\python3.8\llvmlite:
    running install
    running build
    got version from file C:\Users\WILLI\AppData\Local\Temp\pip-install-x37fv0l1\llvmlite\llvmlite/_version.py {'version': '0.31.0', 'full': 'fe7d985f6421d87f613bd414479d29d912771562'}
    running build_ext
    D:\Temp\MICA\Scripts\python.exe C:\Users\WILLI\AppData\Local\Temp\pip-install-x37fv0l1\llvmlite\ffi\build.py
    Trying generator 'Visual Studio 14 2015'
    Traceback (most recent call last):
      File "C:\Users\WILLI\AppData\Local\Temp\pip-install-x37fv0l1\llvmlite\ffi\build.py", line 168, in <module>
        main()
      File "C:\Users\WILLI\AppData\Local\Temp\pip-install-x37fv0l1\llvmlite\ffi\build.py", line 156, in main
        main_win32()
      File "C:\Users\WILLI\AppData\Local\Temp\pip-install-x37fv0l1\llvmlite\ffi\build.py", line 88, in main_win32
        generator = find_win32_generator()
      File "C:\Users\WILLI\AppData\Local\Temp\pip-install-x37fv0l1\llvmlite\ffi\build.py", line 76, in find_win32_generator
        try_cmake(cmake_dir, build_dir, generator)
      File "C:\Users\WILLI\AppData\Local\Temp\pip-install-x37fv0l1\llvmlite\ffi\build.py", line 28, in try_cmake
        subprocess.check_call(['cmake', '-G', generator, cmake_dir])
      File "C:\Python\lib\subprocess.py", line 359, in check_call
        retcode = call(*popenargs, **kwargs)
      File "C:\Python\lib\subprocess.py", line 340, in call
        with Popen(*popenargs, **kwargs) as p:
      File "C:\Python\lib\subprocess.py", line 854, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Python\lib\subprocess.py", line 1307, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden
    error: command 'D:\\Temp\\MICA\\Scripts\\python.exe' failed with exit status 1
```

Have can I get numba work?

**Comment by LostInDarkMath** [comment]
It was a problem of my python interpreter and not of your package. After fixing my interpreter, the installation was succesful.
Sry for opening this issue.

**Comment by esc** [comment]
@LostInDarkMath thanks for following up and closing the issue again! If you hit any snags in future please don't hesitate to open issues.
