### ISSUE TITLE
Compatibility shims raise cryptic error

### ISSUE THREAD

**Issue by eric-wieser** [numba/numba#5484]
An issue with the 0.49 shims:
```
In [11]: import numba.targets

In [12]: numba.targets.test
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-12-88852dcaa72f> in <module>
----> 1 numba.targets.test

c:\users\wiese\repos\ga\numba\numba\core\errors.py in wrapper(attr)
    434     """
    435     def wrapper(attr):
--> 436         mod = import_module(new_module)
    437         ret_attr = getattr(mod, attr)
    438         msg = _moved_msg2.format(attr, old_module, new_module)

~\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py in import_module(name, package)
    116     """
    117     level = 0
--> 118     if name.startswith('.'):
    119         if not package:
    120             msg = ("the 'package' argument is required to perform a relative "

AttributeError: 'NoneType' object has no attribute 'startswith'
```

I think you need a check for `new_module is None`, to emit a more useful error message.

**Comment by stuartarchibald** [comment]
Thanks, this needs fixing for 0.49.

**Comment by stuartarchibald** [comment]
#5954 fixes I hope. With that in place this happens:
```
$ python -c 'import numba.targets; numba.targets.nonsense'
<string>:1: NumbaDeprecationWarning: No direct replacement for 'numba.targets' available. Visit https://gitter.im/numba/numba-dev to request help. Thanks!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<path>/numba/numba/core/errors.py", line 439, in wrapper
    raise AttributeError(_moved_no_replacement.format(modnattr))
AttributeError: No direct replacement for 'numba.targets.nonsense' available. Visit https://gitter.im/numba/numba-dev to request help. Thanks!
```
