### ISSUE TITLE
Post SSA: type unification error

### ISSUE THREAD

**Issue by esc** [numba/numba#5501]
- [x] using Numba master (0.50.0dev0-7-g917f582433)
 - [x] I have included below a minimal working reproducer 

The following was discovered in https://github.com/numba/numba/issues/5475 

The code snippet works with 0.48.0 but doesn't work with current master, we are currently assuming an SSA related issue.

```python
from numba import njit
from numpy import arange, tanh


bar = arange(5**2).reshape(5, 5)


@njit
def foo(a):
    trace = 0
    for i in range(a.shape[0]):
        trace += tanh(a[i, i])
    return a + trace


foo(bar)
```

Traceback is: 

```
💥 zsh» python foo029.py
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 149, in propagate
    constraint(typeinfer)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 610, in __call__
    self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 538, in resolve
    typeinfer.add_type(self.target, sig.return_type, loc=self.loc)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 998, in add_type
    unified = tv.add_type(tp, loc=loc)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 70, in add_type
    raise TypingError(msg % (self.type, tp, self.var,
numba.core.errors.TypingError: Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$50binary_add.2', defined at foo029.py (13)

File "foo029.py", line 13:
def foo(a):
    <source elided>
        trace += tanh(a[i, i])
    return a + trace
    ^

[1] During: typing of intrinsic-call at foo029.py (13)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "foo029.py", line 16, in <module>
    foo(bar)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 342, in error_rewrite
    raise e
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 81, in compile
    raise retval
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 92, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 70, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 986, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify array(int64, 2d, C) and array(float64, 2d, C) for '$50binary_add.2', defined at foo029.py (13)

File "foo029.py", line 13:
def foo(a):
    <source elided>
        trace += tanh(a[i, i])
    return a + trace
    ^

[1] During: typing of intrinsic-call at foo029.py (13)

File "foo029.py", line 13:
def foo(a):
    <source elided>
        trace += tanh(a[i, i])
    return a + trace
```

@stuartarchibald further writes:

```python
from numba import njit
from numpy import arange, tanh

bar = arange(5**2).reshape(5, 5)

@njit
def foo(a):
    # trace is defined as an int64
    trace = 0
    # It's not possible to tell at compile time if this loop will run. If it does
    # then `trace` becomes a float64 by virtue of the infix addition of tanh()
    for i in range(a.shape[0]): 
        trace += tanh(a[i, i])
    # if the loop executes then the return type is:
    #     2d of array int64 + float64 -> 2d array of float64
    # if the loop does not execute then the return type is:
    #     2d of array int64 + int64 -> 2d array of int64
    # The compile cannot statically determine what the return type will be.
    return a + trace


foo(bar)
```

And the workaround is to declare `trace` as float using the literal: `0.0`.

**Comment by esc** [comment]
@sklam since this is 'maybe SSA' I'll assign it to you.

**Comment by stuartarchibald** [comment]
@sklam to save you effort. `trace` is `float64` if the loop executes and `intp` if it does not, the return type depends `unify(int array + int64, int array + float64)` which fails. This worked prior to SSA because `trace` got typed as `float64` throughout by virtue of the aliased names.

**Comment by sklam** [comment]
I think SSA means that we can update how types are assigned to type variables. Pre-SSA, every type-variable can change during type inference. Post-SSA, no type-variable should change type unless if is undergoing refinement. I need to experiment with changing it.

**Comment by esc** [comment]
During the core-developer meeting today, we concluded that type stability is preferable and we will not fix this as we don't consider it 'broken'. Old, pre-SSA behavior is deemed to 'have worked by accident' and that behavior was not intentional/deliberate.
