### ISSUE TITLE
ZeroDivisionError if an empty array is passed to np.mean()

### ISSUE THREAD

**Issue by santhisenan** [numba/numba#5502]
## Reporting a bug

- [X] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

The following code raises ZeroDivisionError in nopython mode.

```python
from numba import njit
import numpy as np

@njit
def mean(arr):
    return np.mean(arr)

mean(np.asarray([]))
```
Without njit decorator, the function returns NaN

### Traceback

ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-11-60946af0372d> in <module>
----> 1 mean(np.asarray([]))

ZeroDivisionError: division by zero

**Comment by esc** [comment]
@santhisenan thanks for reporting this, I can reproduce it locally.

**Comment by esc** [comment]
Also note, that w/o `njit` i get:

```
💥 zsh» python foo032.py                                                                                                                                            :(
/Users/vhaenel/miniconda3/envs/numba_3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py:3334: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/Users/vhaenel/miniconda3/envs/numba_3.8/lib/python3.8/site-packages/numpy/core/_methods.py:161: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
```

**Comment by esc** [comment]
Current best guess is the following line is the troublemaker:

https://github.com/numba/numba/blob/master/numba/np/arraymath.py#L413

**Comment by esc** [comment]
The following patch fixes:

```
diff --git i/numba/np/arraymath.py w/numba/np/arraymath.py
index 15c4d6c2c0..4678e34cdd 100644
--- i/numba/np/arraymath.py
+++ w/numba/np/arraymath.py
@@ -405,6 +405,9 @@ def array_mean(context, builder, sig, args):
     zero = sig.return_type(0)

     def array_mean_impl(arr):
+        # Empty arrays as a special case.
+        if arr.size == 0:
+            return np.nan
         # Can't use the naive `arr.sum() / arr.size`, as it would return
         # a wrong result on integer sum overflow.
         c = zero
```

**Comment by esc** [comment]
@santhisenan if you are interested, please do feel free to grab the patch, add some tests and submit a PR yourself. Otherwise, one of the core maintainers will get around to it eventually. Also I am tagging this as a bug since the Numpy API isn't being replicated faithfully.

**Comment by santhisenan** [comment]
@esc I will start working on it.

**Comment by santhisenan** [comment]
@esc Handling empty arrays by returning NaN after checking upfront leads to the following error in test_mean_npdatetime.
```
======================================================================
ERROR: test_mean_npdatetime (numba.tests.test_array_reductions.TestArrayReductions)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/santhisenan/Documents/projects/numba/numba/tests/test_array_reductions.py", line 706, in test_mean_npdatetime
    self.check_nptimedelta(array_mean)
  File "/Users/santhisenan/Documents/projects/numba/numba/tests/test_array_reductions.py", line 678, in check_nptimedelta
    self._do_check_nptimedelta(pyfunc, arr)
  File "/Users/santhisenan/Documents/projects/numba/numba/tests/test_array_reductions.py", line 657, in _do_check_nptimedelta
    self.assertPreciseEqual(cfunc(arr), pyfunc(arr))
  File "/Users/santhisenan/Documents/projects/numba/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/santhisenan/Documents/projects/numba/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/santhisenan/Documents/projects/numba/numba/core/utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
No conversion from float64 to timedelta64[s] for '$16return_value.2', defined at None

File "numba/np/arraymath.py", line 410:
    def array_mean_impl(arr):
        <source elided>
        if arr.size == 0:
            return np.nan
            ^

[1] During: typing of assignment at /Users/santhisenan/Documents/projects/numba/numba/np/arraymath.py (410)

File "numba/np/arraymath.py", line 410:
    def array_mean_impl(arr):
        <source elided>
        if arr.size == 0:
            return np.nan
            ^
```

**Comment by santhisenan** [comment]
@esc Is this the right way to do the fix?
```
diff --git a/numba/np/arraymath.py b/numba/np/arraymath.py
index 15c4d6c2c..f71452d65 100644
--- a/numba/np/arraymath.py
+++ b/numba/np/arraymath.py
@@ -402,15 +402,34 @@ def array_cumprod(context, builder, sig, args):
 @lower_builtin(np.mean, types.Array)
 @lower_builtin("array.mean", types.Array)
 def array_mean(context, builder, sig, args):
+    ty = sig.args[0].dtype
     zero = sig.return_type(0)

-    def array_mean_impl(arr):
-        # Can't use the naive `arr.sum() / arr.size`, as it would return
-        # a wrong result on integer sum overflow.
-        c = zero
-        for v in np.nditer(arr):
-            c += v.item()
-        return c / arr.size
+    if isinstance(ty, (types.NPDatetime, types.NPTimedelta)):
+        def array_mean_impl(arr):
+            # Handle empty arrays
+            if arr.size == 0:
+                return ty('NaT')
+
+            # Can't use the naive `arr.sum() / arr.size`, as it would return
+            # a wrong result on integer sum overflow.
+            c = zero
+            for v in np.nditer(arr):
+                c += v.item()
+            return c / arr.size
+
+    else:
+        def array_mean_impl(arr):
+            # Handle empty arrays
+            if arr.size == 0:
+                return np.nan
+
+            # Can't use the naive `arr.sum() / arr.size`, as it would return
+            # a wrong result on integer sum overflow.
+            c = zero
+            for v in np.nditer(arr):
+                c += v.item()
+            return c / arr.size

     res = context.compile_internal(builder, array_mean_impl, sig, args,
                                    locals=dict(c=sig.return_type))
```

**Comment by esc** [comment]
@santhisenan that looks like a good start. In order to facilitate quicker debugging, perhaps it would be good to get a pull-request going? That would make it easier for me to grab the changes you suggested and try them out locally. My guess would that it might be possible to determine the `nan/NaT` return object outside of the `array_mean_impl` and then simply hand that in. Here is some untested pseudocode to illustrate this idea:

```
def array_mean(context, builder, sig, args):
    # use isinstance to determine `nan/NaT` return
    return_object = ...
    def array_mean_impl(arr):
        if arr.size = 0:
            return return_object
        ....
```

That would also reduce the amount of copy and paste needed, (if it works).
