### ISSUE TITLE
[0.49.0-rc1] (was #5413) numba.errors.RedefinedError: ... (step: analyzing bytecode) $const_0.5

### ISSUE THREAD

**Issue by slayoo** [numba/numba#5508]
Previously closed bug #5413 still occurs in 0.49.0-rc1

Minimal code:
```python
import numba
@numba.njit(numba.float64())
def test():
    a = (0, 1)
    return fun(*a, +.5, 0) * fun(*a, 0, 0) + fun(*a, +.25, 0) * fun(*a, 0, 0)
```

output

```
test.py:None (test.py)
test.py:2: in <module>
    @numba.njit(numba.float64())
../PySDM/venv/lib/python3.7/site-packages/numba/decorators.py:200: in wrapper
    disp.compile(sig)
../PySDM/venv/lib/python3.7/site-packages/numba/compiler_lock.py:32: in _acquire_compile_lock
    return func(*args, **kwargs)
../PySDM/venv/lib/python3.7/site-packages/numba/dispatcher.py:768: in compile
    cres = self._compiler.compile(args, return_type)
../PySDM/venv/lib/python3.7/site-packages/numba/dispatcher.py:77: in compile
    status, retval = self._compile_cached(args, return_type)
../PySDM/venv/lib/python3.7/site-packages/numba/dispatcher.py:91: in _compile_cached
    retval = self._compile_core(args, return_type)
../PySDM/venv/lib/python3.7/site-packages/numba/dispatcher.py:109: in _compile_core
    pipeline_class=self.pipeline_class)
../PySDM/venv/lib/python3.7/site-packages/numba/compiler.py:551: in compile_extra
    return pipeline.compile_extra(func)
../PySDM/venv/lib/python3.7/site-packages/numba/compiler.py:331: in compile_extra
    return self._compile_bytecode()
../PySDM/venv/lib/python3.7/site-packages/numba/compiler.py:393: in _compile_bytecode
    return self._compile_core()
../PySDM/venv/lib/python3.7/site-packages/numba/compiler.py:373: in _compile_core
    raise e
../PySDM/venv/lib/python3.7/site-packages/numba/compiler.py:364: in _compile_core
    pm.run(self.state)
../PySDM/venv/lib/python3.7/site-packages/numba/compiler_machinery.py:347: in run
    raise patched_exception
../PySDM/venv/lib/python3.7/site-packages/numba/compiler_machinery.py:338: in run
    self._runPass(idx, pass_inst, state)
../PySDM/venv/lib/python3.7/site-packages/numba/compiler_lock.py:32: in _acquire_compile_lock
    return func(*args, **kwargs)
../PySDM/venv/lib/python3.7/site-packages/numba/compiler_machinery.py:302: in _runPass
    mutated |= check(pss.run_pass, internal_state)
../PySDM/venv/lib/python3.7/site-packages/numba/compiler_machinery.py:275: in check
    mangled = func(compiler_state)
../PySDM/venv/lib/python3.7/site-packages/numba/untyped_passes.py:89: in run_pass
    func_ir = interp.interpret(bc)
../PySDM/venv/lib/python3.7/site-packages/numba/interpreter.py:132: in interpret
    self._dispatch(inst, kws)
../PySDM/venv/lib/python3.7/site-packages/numba/interpreter.py:371: in _dispatch
    return fn(inst, **kws)
../PySDM/venv/lib/python3.7/site-packages/numba/interpreter.py:729: in op_LOAD_CONST
    target = self.store(val_const, name=nm, redefine=True)
../PySDM/venv/lib/python3.7/site-packages/numba/interpreter.py:394: in store
    target = self.current_scope.redefine(name, loc=self.loc, rename=rename)
../PySDM/venv/lib/python3.7/site-packages/numba/ir.py:1095: in redefine
    return self.define(newname, loc)
../PySDM/venv/lib/python3.7/site-packages/numba/ir.py:1048: in define
    self.localvars.define(v.name, v)
../PySDM/venv/lib/python3.7/site-packages/numba/ir.py:261: in define
    raise RedefinedError(name)
E   numba.errors.RedefinedError: Failed in nopython mode pipeline (step: analyzing bytecode)
E   $const_0.5
```

**Comment by gmarkall** [comment]
I can't reproduce this. With the minimal code above, I get:

```
Traceback (most recent call last):
  File "repro.py", line 2, in <module>
    @numba.njit(numba.float64())
  File "/home/gmarkall/numbadev/numba/numba/core/decorators.py", line 198, in wrapper
    disp.compile(sig)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 81, in compile
    raise retval
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 98, in run_pass
    raise_errors=self._raise_errors)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 69, in type_inference_stage
    infer.build_constraint()
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 939, in build_constraint
    self.constrain_statement(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1283, in constrain_statement
    self.typeof_assign(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1354, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1455, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1375, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'fun': cannot determine Numba type of <class 'numba.core.ir.UndefinedType'>

File "repro.py", line 5:
def test():
    <source elided>
    a = (0, 1)
    return fun(*a, +.5, 0) * fun(*a, 0, 0) + fun(*a, +.25, 0) * fun(*a, 0, 0)
    ^
```

Assuming the minimal code should include `fun` (from #5413):

```python
import numba

print(numba.__version__)

@numba.njit()
def fun(a, b, c, d):
    return 0


@numba.njit(numba.float64())
def test():
    a = (0, 1)
    return fun(*a, +.5, 0) * fun(*a, 0, 0) + fun(*a, +.25, 0) * fun(*a, 0, 0)

if __name__ == '__main__':
    print(test())
```

Then the output I get with 0.49.0rc1 is:

```
$ python repro.py 
0.49.0rc1
0.0
```

Can you provide your output when running with the example code above please?

**Comment by slayoo** [comment]
Thanks for checking!
I've tested it yesterday with Python 3.7.2 and numba from https://github.com/Quansight/numba/tree/pearu/issue5470 branch. Will try ASAP with bare rc1 and Python 3.8, and report

**Comment by slayoo** [comment]
Python 3.8.2 & 0.48.0: KO
Python 3.8.2 & 0.49.0-rc1: OK
Python 3.8.2 & pearu/issue5470: OK

Will reopen if I will get it back failing on 3.7.2

**Comment by slayoo** [comment]
Just confirming Python 3.7 with pearu/issue5470 works OK, very sorry for false alarm - I must have mixed the venvs last night

**Comment by gmarkall** [comment]
No problem - thanks for confirming!
