### ISSUE TITLE
Part of compilation failure message is dropped when handling literal args

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#5559]
- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi, 

I think I've found an issue related to loosing actual error message and traceback in functions.py BoundFunction::get_call_type. Unlike BaseFunction::get_call_type, the former catches and silently discards exceptions occurred while trying to compile with literal arguments:

```
    def get_call_type(self, context, args, kws):
        template = self.template(context)
        e = None
        # Try with Literal
        try:
            out = template.apply(args, kws)
        except Exception:       # <------ here we don't record why literal step failed
            out = None
        # If that doesn't work, remove literals
        if out is None:
            args = [unliteral(a) for a in args]
            kws = {k: unliteral(v) for k, v in kws.items()}
            out = template.apply(args, kws)
        if out is None and e is not None:
            raise e
        return out
```

This causes compilation failure messages in some scenarios to be very opaque, as unliteral step might fail to compile due to different reasons, e.g. consider the following reproducer:

```
import operator
import numpy as np

import numba
from numba import types
from numba.core import cgutils
from numba.extending import (
    make_attribute_wrapper,
    overload,
    overload_method,
    models,
    register_model,
    type_callable,
    typeof_impl,
    lower_builtin,
)
from numba.errors import TypingError

def make_dummy_type():
    class Dummy(object):
        def __init__(self, value):
            self.value = value

    class DummyType(types.Type):
        def __init__(self):
            super(DummyType, self).__init__(name="Dummy")

    dummy_type = DummyType()

    @register_model(DummyType)
    class DummyModel(models.StructModel):
        def __init__(self, dmm, fe_type):
            members = [("value", types.intp)]
            models.StructModel.__init__(self, dmm, fe_type, members)

    make_attribute_wrapper(DummyType, "value", "value")

    @type_callable(Dummy)
    def type_dummy(context):
        def typer(value):
            return dummy_type
        return typer

    @lower_builtin(Dummy, types.intp)
    def impl_dummy(context, builder, sig, args):
        typ = sig.return_type
        [value] = args
        dummy = cgutils.create_struct_proxy(typ)(context, builder)
        dummy.value = value
        return dummy._getvalue()

    @typeof_impl.register(Dummy)
    def typeof_dummy(val, c):
        return DummyType()

    # Store attributes
    return Dummy, DummyType

Dummy, DummyType = make_dummy_type()


@overload_method(DummyType, 'foo')
def dummy_foo_ovld(self, dtype='str'):
    if not isinstance(self, DummyType):
        return None

    print("DEBUG: typing Dummy::foo, dtype:", dtype)
    # suppose kind has to be known at compile time
    if not isinstance(dtype, (types.StringLiteral, types.Omitted, str)):
        raise TypingError("DummyType::foo() requires literal dtype arg")

    # omitted arg case
    if isinstance(dtype, str):
        literal_dtype = dtype
    else:
        literal_dtype = dtype.literal_value
    def dummy_foo_impl(self, dtype='str'):
        # suppose we have erroneous code here, which will fail
        # compilation for literal dtype argument (and for non-literal)
        # we'll always intercept at typing
        if literal_dtype == 'int':
            res = 42
        elif literal_dtype == 'str':
            res = '42'
        else:
            res = 42.0

        return res + self.value     # '42' + integer is a no op

    return dummy_foo_impl


@numba.njit
def test_impl(x):
    # this fails but shows correct error msg:
    # return Dummy(x).foo()

    # this fails but shows error msg overwritten by msg at unliteral step:
    return Dummy(x).foo(dtype='str')

if __name__ == "__main__":
    print(test_impl(1))
```

which gives following output:

```
(SDC_MASTER) C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba>p
ython -W ignore example_script.py
DEBUG: typing Dummy::foo, dtype: Literal[str](str)
DEBUG: typing Dummy::foo, dtype: unicode_type
DEBUG: typing Dummy::foo, dtype: unicode_type
DEBUG: typing Dummy::foo, dtype: unicode_type
DEBUG: typing Dummy::foo, dtype: unicode_type
DEBUG: typing Dummy::foo, dtype: unicode_type
DEBUG: typing Dummy::foo, dtype: unicode_type
Traceback (most recent call last):
  File "example_script.py", line 104, in <module>
    print(test_impl(1))
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\
core\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\
core\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\
core\utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython fron
tend)
Invalid use of Function(<function dummy_foo_ovld at 0x000001DE70C7A550>) with argume
nt(s) of type(s): (Dummy, dtype=unicode_type)
 * parameterized
In definition 0:
    TypingError: DummyType::foo() requires literal dtype arg
    raised from example_script.py:71
In definition 1:
    TypingError: DummyType::foo() requires literal dtype arg
    raised from example_script.py:71
This error is usually caused by passing an argument of a type that is unsupported by
 the named function.
[1] During: resolving callee type: BoundFunction((<class '__main__.make_dummy_type.<
locals>.DummyType'>, 'foo') for Dummy)
[2] During: typing of call at example_script.py (100)


File "example_script.py", line 100:
def test_impl(x):
    <source elided>
    # this fails but shows error msg overwritten by msg at unliteral step
    return Dummy(x).foo(dtype='str')
    ^
```

So it's not possible from this message to understand why compilation has failed at all.
At the same time typeinfer for the case when dtype argument is omitted works fine and gives:

```
(SDC_MASTER) C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba>p
ython -W ignore example_script.py
DEBUG: typing Dummy::foo, dtype: str
Traceback (most recent call last):
  File "example_script.py", line 96, in <module>
    print(test_impl(1))
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\
core\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\
core\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\
core\utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython fron
tend)
Invalid use of Function(<function dummy_foo_ovld at 0x00000188A38AB550>) with argume
nt(s) of type(s): (Dummy)
 * parameterized
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function add>) with argument(s) of type(s): (Liter
al[str](42), int64)
Known signatures:
 * (int64, int64) -> int64
 * (int64, uint64) -> int64
 * (uint64, int64) -> int64
 * (uint64, uint64) -> uint64
 * (float32, float32) -> float32
 * (float64, float64) -> float64
 * (complex64, complex64) -> complex64
 * (complex128, complex128) -> complex128
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
In definition 6:
    All templates rejected with literals.
In definition 7:
    All templates rejected without literals.
In definition 8:
    All templates rejected with literals.
In definition 9:
    All templates rejected without literals.
In definition 10:
    All templates rejected with literals.
In definition 11:
    All templates rejected without literals.
In definition 12:
    All templates rejected with literals.
In definition 13:
    All templates rejected without literals.
In definition 14:
    All templates rejected with literals.
In definition 15:
    All templates rejected without literals.
In definition 16:
    All templates rejected with literals.
In definition 17:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by
 the named function.
[1] During: typing of intrinsic-call at example_script.py (85)

File "example_script.py", line 85:
    def dummy_foo_impl(self, dtype='str'):
        <source elided>

        return res + self.value     # '42' + integer is a no op
        ^

    raised from C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numb
a\numba\core\typeinfer.py:986
In definition 1:
    .............

    raised from C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numb
a\numba\core\typeinfer.py:986
This error is usually caused by passing an argument of a type that is unsupported by
 the named function.
[1] During: resolving callee type: BoundFunction((<class '__main__.make_dummy_type.<
locals>.DummyType'>, 'foo') for Dummy)
[2] During: typing of call at example_script.py (92)


File "example_script.py", line 92:
def test_impl(x):
    return Dummy(x).foo()
    ^

```

Can you please fix that in future releases?

**Numba version used:**  0.49.0.dev0+1116.g9aed4b847

Best Regards,
Alexey.

**Comment by stuartarchibald** [comment]
Thanks for the report. Just to make sure, is the expectation here that this part:
```
In definition 0:
    TypingError: DummyType::foo() requires literal dtype arg
    raised from example_script.py:71
In definition 1:
    TypingError: DummyType::foo() requires literal dtype arg
    raised from example_script.py:71
```
actually expands with a full traceback?

**Comment by kozlov-alexey** [comment]
@stuartarchibald No, I actually thought that a correct message should just include all definitions (for both literal and non-literal args) and for each definition an error with which it failed (assuming that nested functions variants go into different top level definitions), e.g.
```
In definition 0:
    TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function add>) with argument(s) of type(s): (Liter
al[str](42), int64)
......
In definition 2:
    TypingError: DummyType::foo() requires literal dtype arg
    raised from example_script.py:71
```

**Comment by stuartarchibald** [comment]
@kozlov-alexey I see, thanks for clarifying.

**Comment by stuartarchibald** [comment]
I've managed to get Numba to do this in response to the above code:
```
$ NUMBA_DEVELOPER_MODE=0 python issue5559.py 
DEBUG: typing Dummy::foo, dtype: Literal[str](a_string)
Made it through to impl
DEBUG: typing Dummy::foo, dtype: unicode_type
Raising TypingError for literal dtype
DEBUG: typing Dummy::foo, dtype: unicode_type
Raising TypingError for literal dtype
DEBUG: typing Dummy::foo, dtype: unicode_type
Raising TypingError for literal dtype
DEBUG: typing Dummy::foo, dtype: unicode_type
Raising TypingError for literal dtype
DEBUG: typing Dummy::foo, dtype: unicode_type
Raising TypingError for literal dtype
DEBUG: typing Dummy::foo, dtype: unicode_type
Raising TypingError for literal dtype
Traceback (most recent call last):
  File "issue5559.py", line 104, in <module>
    print(test_impl(1))
  File "<numba_path>/numba/core/dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "<numba_path>/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "<numba_path>/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
    No implementation of function Function(<function dummy_foo_ovld at 0x7f1d639414c0>) found for signature:

     >>> dummy_foo_ovld(Dummy, dtype=Literal[str](a_string))

    There are 2 candidate implementations:
       - Of which 1 did not match due to:
       Overload in function 'dummy_foo_ovld': File: numba/issue5559.py: Line 62.
         With argument(s): '(Dummy, dtype=Literal[str](a_string))':
        Rejected as the implementation raised a specific error:
          TypingError: Failed in nopython mode pipeline (step: nopython frontend)
          No implementation of function Function(<built-in function add>) found for signature:

           >>> add(Literal[str](42), int64)

          There are 18 candidate implementations:
            - Of which 16 did not match due to:
            Overload in function 'add': File: <built-in>: Line <N/A>.
              With argument(s): '(Literal[str](42), int64)':
             No match.
            - Of which 2 did not match due to:
            Overload in function 'add': File: <built-in>: Line <N/A>.
              With argument(s): '(Literal[str](42), int64)':
             No match for registered cases:
              * (int64, int64) -> int64
              * (int64, uint64) -> int64
              * (uint64, int64) -> int64
              * (uint64, uint64) -> uint64
              * (float32, float32) -> float32
              * (float64, float64) -> float64
              * (complex64, complex64) -> complex64
              * (complex128, complex128) -> complex128
        [1] During: typing of intrinsic-call at issue5559.py (90)
        
        File "issue5559.py", line 90:
            def dummy_foo_impl(self, dtype='a_string'):
                <source elided>
                return res + self.value     # '42' + integer is a no op
                ^
      raised from <numba_path>/numba/core/typeinfer.py:986
       - Of which 1 did not match due to:
       Overload in function 'dummy_foo_ovld': File: numba/issue5559.py: Line 62.
         With argument(s): '(Dummy, dtype=unicode_type)':
        Rejected as the implementation raised a specific error:
          TypingError: DummyType::foo() requires literal dtype arg
      raised from issue5559.py:71
- Resolution failure for non-literal arguments:
      No implementation of function Function(<function dummy_foo_ovld at 0x7f1d639414c0>) found for signature:

       >>> dummy_foo_ovld(Dummy, dtype=unicode_type)

      There are 2 candidate implementations:
          - Of which 2 did not match due to:
          Overload in function 'dummy_foo_ovld': File: numba/issue5559.py: Line 62.
            With argument(s): '(Dummy, dtype=unicode_type)':
           Rejected as the implementation raised a specific error:
             TypingError: DummyType::foo() requires literal dtype arg
        raised from issue5559.py:71

[1] During: resolving callee type: BoundFunction((<class '__main__.make_dummy_type.<locals>.DummyType'>, 'foo') for Dummy)
[2] During: typing of call at issue5559.py (101)


File "issue5559.py", line 101:
def test_impl(x):
    <source elided>
    # this fails but shows error msg overwritten by msg at unliteral step:
    return Dummy(x).foo(dtype='a_string')
    ^
```
@kozlov-alexey in your view is that sufficient information/a suitable response to the problem by the compiler? Would anything else help/do you have any suggestions? Thanks.

**Comment by kozlov-alexey** [comment]
@stuartarchibald I think it's quite informative now and totally solves described problem. To me it looks strange that the second candidate rejected during "Resolution failure for literal arguments" step actually has dtype=unicode_type (non-literal one), but I suppose it's the matter of how compilation was actually made.

**Comment by stuartarchibald** [comment]
> @stuartarchibald I think it's quite informative now and totally solves described problem. To me it looks strange that the second candidate rejected during "Resolution failure for literal arguments" step actually has dtype=unicode_type (non-literal one), but I suppose it's the matter of how compilation was actually made.

Thanks. It is indeed down to the compilation path.

Fixed in https://github.com/numba/numba/pull/5722 closing.
