### ISSUE TITLE
RuntimeError: cannot cache function '__shear_dense' 

### ISSUE THREAD

**Issue by openedev** [numba/numba#5566]
## Reporting a bug

- [y] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [y] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This numba issue while I'm importing librosa. so I suspect it would related to numba, since I didn't get any resolutions from librosa.

Error while importing librosa though all the required dependencies are installed properly.
Steps/Code to Reproduce

$ python --version
Python 3.8.2
$ python3 -c "import audioread"
$ python3 -c "import six"
$ python3 -c "import joblib"
$ python3 -c "import scipy"
$ python3 -c "import numpy"
$ python3 -c "import numba"
$ python3 -c "import resampy"
$ python3 -c "import sklearn"
$ python3 -c "import soundfile"
$ python3 -c "import librosa"
Traceback (most recent call last):
File "", line 1, in
File "usr/lib/python3.8/site-packages/librosa/init.py", line 12, in
File "usr/lib/python3.8/site-packages/librosa/core/init.py", line 125, in
File "usr/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in
File "usr/lib/python3.8/site-packages/librosa/util/init.py", line 77, in
File "usr/lib/python3.8/site-packages/librosa/util/utils.py", line 1825, in
File "usr/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
File "usr/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
File "usr/lib/python3.8/site-packages/numba/caching.py", line 614, in init
File "usr/lib/python3.8/site-packages/numba/caching.py", line 348, in init
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'usr/lib/python3.8/site-packages/librosa/util/utils.py'

Few versions I'm running on my system.

Linux-5.6.0-aarch64-with-glibc2.17
Python 3.8.2 (default, Apr 12 2020, 21:58:31)
[GCC 8.4.0]
NumPy 1.18.2
SciPy 1.4.1

Any help?

**Comment by stuartarchibald** [comment]
Thanks for the report. Did you install something as `root` user and as a standard user don't have permission to write to cache locations (or something along those lines)?

**Comment by openedev** [comment]
@stuartarchibald yes, I have logged as root. I'm a root user and I have free disk space as well.

**Comment by stuartarchibald** [comment]
It's probably something permissions related. If you set the environment variable `NUMBA_CACHE_DIR` to somewhere like `/tmp/<you create a directory>`, does it then work?

**Comment by openedev** [comment]
Yes, tried that as well.

# pwd
/root
# mkdir cache
# NUMBA_CACHE_DIR=/root/cache
# echo $NUMBA_CACHE_DIR
/root/cache
# python3 -c "import librosa"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "usr/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/utils.py", line 1825, in <module>
  File "usr/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
  File "usr/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'usr/lib/python3.8/site-packages/librosa/uti
l/utils.py'

**Comment by stuartarchibald** [comment]
Are you running this as root/a user with sufficient permissions to write?

What does this give you:
```
python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserProvidedCacheLocator(lambda x:x, 'string').get_cache_path())"
```

**Comment by openedev** [comment]
I'm running as a root user. Yes, I have all permissions to access.

$ python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserPro
videdCacheLocator(lambda x:x, 'string').get_cache_path())"
root

**Comment by stuartarchibald** [comment]
Are you actually exporting the environment variable?

**Comment by openedev** [comment]
@stuartarchibald yes I did.

$ ls
cache  test
$ NUMBA_CACHE_DIR=/root/cache
$ echo $NUMBA_CACHE_DIR
/root/cache
$ python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserPro
videdCacheLocator(lambda x:x, 'string').get_cache_path())"
root
$ python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserPro
videdCacheLocator(lambda x:x, 'string').get_cache_path())"
root
# python -c "import librosa"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "usr/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/utils.py", line 1825, in <module>
  File "usr/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
  File "usr/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'usr/lib/python3.8/site-packages/librosa/uti
l/utils.py'

Did I miss anything?

**Comment by stuartarchibald** [comment]
You need to export the variable so it's available in the python subprocess?
```bash
$ pwd
/tmp

$ mkdir cache1

$ NUMBA_CACHE_DIR=/tmp/cache1

$ python -c 'import os; [print(x) for x in os.environ.keys() if x.startswith("NUMBA")]'

$ export NUMBA_CACHE_DIR

$ python -c 'import os; [print(x) for x in os.environ.keys() if x.startswith("NUMBA")]'
NUMBA_CACHE_DIR

$  python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserProvidedCacheLocator(lambda x:x, 'string').get_cache_path())"
/tmp/cache1/tmp
```

**Comment by openedev** [comment]
$ cd /tmp/
$ ls
messages
$ mkdir cache1
$ NUMBA_CACHE_DIR=/tmp/cache1
$ python -c 'import os; [print(x) for x in os.environ.keys() if x.startswith("NU
MBA")]'
[   36.215312] random: python: uninitialized urandom read (24 bytes read)
[   36.299048] random: crng init done
$ export NUMBA_CACHE_DIR
$ python -c 'import os; [print(x) for x in os.environ.keys() if x.startswith("NU
MBA")]'
NUMBA_CACHE_DIR
$ python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserPro
videdCacheLocator(lambda x:x, 'string').get_cache_path())"
/tmp/cache1/tmp
$ python -c "import librosa"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "usr/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/utils.py", line 1825, in <module>
  File "usr/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
  File "usr/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'usr/lib/python3.8/site-packages/librosa/uti
l/utils.py'

**Comment by stuartarchibald** [comment]
Does this work if you are not root?

**Comment by openedev** [comment]
Yes, same result.

$ whoami 
test
$ mkdir /tmp/cache1
$ NUMBA_CACHE_DIR=/tmp/cache1
$ python -c 'import os; [print(x) for x in os.environ.keys() if x.startswith("NU
MBA")]'
$ export NUMBA_CACHE_DIR
$ python -c 'import os; [print(x) for x in os.environ.keys() if x.startswith("NU
MBA")]'
NUMBA_CACHE_DIR
$ python -c "from numba.caching import _UserProvidedCacheLocator; print(_UserPro
videdCacheLocator(lambda x:x, 'string').get_cache_path())"
/tmp/cache1/
$ python -c "import librosa"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "usr/lib/python3.8/site-packages/librosa/__init__.py", line 12, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/__init__.py", line 125, in <module>
  File "usr/lib/python3.8/site-packages/librosa/core/time_frequency.py", line 11, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/__init__.py", line 77, in <module>
  File "usr/lib/python3.8/site-packages/librosa/util/utils.py", line 1825, in <module>
  File "usr/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
  File "usr/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
  File "usr/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
RuntimeError: cannot cache function '__shear_dense': no locator available for file 'usr/lib/python3.8/site-packages/librosa/uti
l/utils.py'

**Comment by stuartarchibald** [comment]
Apologies, I didn't make this clear. Does this work if you install Numba/librosa as a user and then execute it as a user? It seems these problems stem from using an installation made by the root user, I'm unsure, however, why running a root install as root doesn't work, given root should be able to write anywhere?

**Comment by openedev** [comment]
Basically I'm using rootfs for embedded platform, so no distribution. I tried running the test with root and normal user, results are same not working.

**Comment by seibert** [comment]
We should make caching fail with a printed warning and disable itself when a suitable location cannot be found to write the cache.  It isn't an essential operation, and a number of libraries are now shipping with caching enabled by default.

Out of curiosity, can you say what embedded platform this is?  We've had some people try to get Numba running on unusual Android systems with mixed results (due to other behavioral differences compared to standard Linux distributions).

**Comment by openedev** [comment]
@seibert I have buildroot rootfs running on arm64 dev board.

**Comment by TheEternalToast** [comment]
This seems to be related to https://github.com/librosa/librosa/issues/1013#

**Comment by esc** [comment]
@TheEternalToast thanks for updating the issue, we appreciate your input.

**Comment by thesby** [comment]
So how to solve this problem? I cannot install miniconda since I use the server as a user, no permission to install package except pip

**Comment by esc** [comment]
@thesby thanks for asking about this. To the best  of my knowledge, `miniconda` can be installed in a server as a user. Simply download the installer, run it, and follow the instructions to install `miniconda` into a users `$HOME`directory.

**Comment by TheEternalToast** [comment]
That might work, too. But I just now solved the issue for me by using librosa 0.7.2 instead of 0.8.0

**Comment by projects-g** [comment]
cannot cache function '__shear_dense': no locator available for file '/home/gma56/.local/lib/python3.8/site-packages/librosa/util/utils.py'

**Comment by yomguy** [comment]
I have manage.py to fix this applying a `chown` for the right user (www-data in my case) to the directory defined by the env variable `NUMBA_CACHE_DIR`

**Comment by zhimin-z** [comment]
same issue, fail to resolve it....

**Comment by shoaibmalek21** [comment]
I only use this command, and it works for me.
- Pip install librosa -U

**Comment by milahu** [comment]
> can you say what embedded platform this is?

i get this error in the [nix](https://github.com/NixOS/nix) build sandbox

`_UserProvidedCacheLocator` fails because `config.CACHE_DIR` is unset
`_InTreeCacheLocator` fails because `/nix/store/` is read-only
`_UserWideCacheLocator` fails because `$HOME` is unset, or `$HOME` is set to `/some/invalid/path`
`_IPythonCacheLocator` fails because its not running in `ipython`

fixed by setting `HOME=/tmp` or `NUMBA_CACHE_DIR=/tmp`

if writing the cache file is required, then numba should try harder to find a writable location
for example in `$TMP` or `$TEMP` or `/tmp`

<details>

`numba/core/caching.py`

```py
class CacheImpl(metaclass=ABCMeta):
    """
    Provides the core machinery for caching.
    - implement how to serialize and deserialize the data in the cache.
    - control the filename of the cache.
    - provide the cache locator
    """
    _locator_classes = [_UserProvidedCacheLocator,
                        _InTreeCacheLocator,
                        _UserWideCacheLocator,
                        _IPythonCacheLocator]

    def __init__(self, py_func):
        self._lineno = py_func.__code__.co_firstlineno
        # Get qualname
        try:
            qualname = py_func.__qualname__
        except AttributeError:
            qualname = py_func.__name__
        # Find a locator
        source_path = inspect.getfile(py_func)
        print("numba/core/caching.py looping self._locator_classes")
        for cls in self._locator_classes:
            locator = cls.from_function(py_func, source_path)

            # debug
            print("numba/core/caching.py cls", repr(cls))
            print("numba/core/caching.py py_func", repr(py_func))
            print("numba/core/caching.py source_path", repr(source_path))
            print("numba/core/caching.py locator", repr(locator))

            if locator is not None:
                break
        else:
            raise RuntimeError("cannot cache function %r: no locator available "
                               "for file %r" % (qualname, source_path))
```

output from debug prints

```
numba/core/caching.py cls <class 'numba.core.caching._UserProvidedCacheLocator'>
numba/core/caching.py py_func <function __o_fold at 0x7fffa5b06de0>
numba/core/caching.py source_path '/nix/store/w1p1j1k051k2ak3s2v63z4c0xb5r6lv7-python3.11-librosa-0.10.2/lib/python3.11/site-packages/librosa/core/notation.py'
numba/core/caching.py locator None
```

`_UserProvidedCacheLocator` fails because `config.CACHE_DIR` is unset

```
numba/core/caching.py cls <class 'numba.core.caching._InTreeCacheLocator'>
numba/core/caching.py py_func <function __o_fold at 0x7fffa5b06de0>
numba/core/caching.py source_path '/nix/store/w1p1j1k051k2ak3s2v63z4c0xb5r6lv7-python3.11-librosa-0.10.2/lib/python3.11/site-packages/librosa/core/notation.py'
numba/core/caching.py locator None
```

`_InTreeCacheLocator` fails because `/nix/store/` is read-only

```
numba/core/caching.py cls <class 'numba.core.caching._UserWideCacheLocator'>
numba/core/caching.py py_func <function __o_fold at 0x7fffa5b06de0>
numba/core/caching.py source_path '/nix/store/w1p1j1k051k2ak3s2v63z4c0xb5r6lv7-python3.11-librosa-0.10.2/lib/python3.11/site-packages/librosa/core/notation.py'
numba/core/caching.py locator None
```

`_UserWideCacheLocator` fails because `$HOME` is unset, or `$HOME` is set to `/some/invalid/path`


```
numba/core/caching.py cls <class 'numba.core.caching._IPythonCacheLocator'>
numba/core/caching.py py_func <function __o_fold at 0x7fffa5b06de0>
numba/core/caching.py source_path '/nix/store/w1p1j1k051k2ak3s2v63z4c0xb5r6lv7-python3.11-librosa-0.10.2/lib/python3.11/site-packages/librosa/core/notation.py'
numba/core/caching.py locator None
```

`_IPythonCacheLocator` fails because its not running in `ipython`

</details>
