### ISSUE TITLE
A typo affecting binop typeinfer in parfor's _arrayexpr_tree_to_ir

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#5575]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Hi, 

While investigating issue caused by #5157 I observed strange behavior when overloaded operator.eq for user type was reentered with wrong type of second argument resulting in completely unrelated compilation failure message, like:
```

  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\parfor.py", line 2218, in _arrayexpr_to_parfor
    _arrayexpr_tree_to_ir(
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\parfor.py", line 2662, in _arrayexpr_tree_to_ir
    func_typ = typingctx.resolve_function_type(op, (el_typ1, el_typ), {})   # FI
XME
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\typing\context.py", line 199, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\typing\context.py", line 251, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\types\functions.py", line 150, in get_call_type
    failures.raise_error()
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\types\functions.py", line 79, in raise_error
    raise errors.TypingError(self.format())
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\types\functions.py", line 44, in format
    explain = self._context.explain_function_type(self._function_type)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\typing\context.py", line 170, in explain_function_type
    sigs, param = func.get_call_signatures()
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\types\functions.py", line 156, in get_call_signatures
    sigs += getattr(temp, 'cases', [])
TypeError: Failed in nopython mode pipeline (step: convert to parfors)
'Signature' object is not iterable
```

I was able to find that it was caused by a typo in parfor.py _arrayexpr_tree_to_ir() which calls resolve_function_type() with wrong parameters, i.e.
```
def _arrayexpr_tree_to_ir(
    ...
        if op in npydecl.supported_array_operators:
            el_typ1 = typemap[arg_vars[0].name]
            if len(arg_vars) == 2:
                el_typ2 = typemap[arg_vars[1].name]
                func_typ = typingctx.resolve_function_type(op, (el_typ1, el_typ), {})   # <---- triggers typeinfer with operation result type (bool) as a second argument type
                ir_expr = ir.Expr.binop(op, arg_vars[0], arg_vars[1], loc)
```

It can be reproduced on master with the following script (but the resulting error is now different and correctly refers to wrong types used with operator.eq):
```
import numba
from numba.extending import (
    overload,
    models,
    lower_builtin,
    register_model,
    make_attribute_wrapper,
    type_callable,
    typeof_impl,
)
from numba import types, cgutils
from numba import njit
import operator
import numpy as np


class StringArray(object):
    def __init__(self, str_list):
        # dummy constructor
        self.data = str_list

    def __repr__(self):
        return 'StringArray({})'.format(self.data)

class StringArrayType(types.Type):
    def __init__(self):
        super(StringArrayType, self).__init__(
            name='StringArrayType()')

    @property
    def dtype(self):
        return types.unicode_type

string_array_type = StringArrayType()
str_arr_data_type = types.containers.List(types.unicode_type)

@typeof_impl.register(StringArray)
def typeof_string_array(val, c):
    return string_array_type

@type_callable(StringArray)
def type_string_array_call(context):
    def typer(str_list):
        return string_array_type
    return typer

@register_model(StringArrayType)
class StringArrayModel(models.StructModel):
    def __init__(self, dmm, fe_type):

        members = [
            ('data', str_arr_data_type),
        ]
        models.StructModel.__init__(self, dmm, fe_type, members)

make_attribute_wrapper(StringArrayType, 'data', '_data')


@lower_builtin(StringArray, str_arr_data_type)
def impl_dummy(context, builder, sig, args):
    data_val, = args
    str_arr = cgutils.create_struct_proxy(
        sig.return_type)(context, builder)
    str_arr.data = data_val

    # increase refcount of stored values
    if context.enable_nrt:
        context.nrt.incref(builder, sig.args[0], data_val)

    return str_arr._getvalue()


@overload(operator.eq)
def str_arr_operator_eq_ovld(lhs, rhs):
    print("DEBUG: typing operator_add: lhs={}, rhs={}".format(lhs, rhs))
    if isinstance(lhs, StringArrayType) and isinstance(rhs, StringArrayType):

        def impl(lhs, rhs):
            n = len(lhs._data)
            res = np.empty(n, dtype=types.bool_)
            for i in numba.prange(n):
                res[i] = lhs._data[i] == rhs._data[i]
            return res

        return impl


@njit(parallel=True)
def foo(a, b):

    left = StringArray(a)
    right = StringArray(b)
    return left == right


a1 = ['a', 'b', 'c']
a2 = ['a', 'b', 'c']
print(foo(a1, a2))

```
gives:
```
(SDC_MASTER) C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\num
ba>python -W ignore .\example_script.py
DEBUG: typing operator_add: lhs=StringArrayType(), rhs=StringArrayType()
DEBUG: typing operator_add: lhs=StringArrayType(), rhs=bool
DEBUG: typing: str_arr_operator_eq_overload: left, right StringArrayType() bool
Traceback (most recent call last):
  File ".\example_script.py", line 98, in <module>
    print(foo(a1, a2))
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\core\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\core\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\nu
mba\core\utils.py", line 79, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: convert t
o parfors)
Invalid use of Function(<built-in function eq>) with argument(s) of type(s): (St
ringArrayType(), bool)
Known signatures:
 * (bool, bool) -> bool
 * (int8, int8) -> bool
 * (int16, int16) -> bool
 * (int32, int32) -> bool
 * (int64, int64) -> bool
 * (uint8, uint8) -> bool
 * (uint16, uint16) -> bool
 * (uint32, uint32) -> bool
 * (uint64, uint64) -> bool
 * (float32, float32) -> bool
 * (float64, float64) -> bool
 * (complex64, complex64) -> bool
 * (complex128, complex128) -> bool
 * parameterized
In definition 0:
    All templates rejected with literals.
    ...
    All templates rejected with literals.
In definition 35:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
```

So since the issues is still applicable on master, it's probably worth fixing.

Numba version: 0.50.0.dev0+72.g296250b61

Best Regards,
Alexey.

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce. Looks like it ought to be something like:
```
func_typ = typingctx.resolve_function_type(op, (el_typ1, el_typ2), {}) 
```
? i.e. resolve on the types of the two args. Applying that locally gives me a lowering error `No definition for lowering <class '__main__.StringArray'>(reflected list(unicode_type),) -> StringArrayType()` which seems reasonable.

**Comment by kozlov-alexey** [comment]
@stuartarchibald  Yes, exactly, that will solve the issue. I initially wanted to reproduce the problem of #5157 with the script, but missed that I have to use 'reflected=True' in _str_arr_data_type_ definition. But anyway the script should fail to compile with the fix too and it's not really important what first error message is overwritten.

**Comment by stuartarchibald** [comment]
@kozlov-alexey I see, thanks. I think that given this is evidently incorrect, I'm inclined to go with a test that asserts that such a case doesn't fail with `Invalid use of Function(<built-in function eq>) with argument(s) of type(s): (StringArrayType(), bool)`, i.e. invalid lookup, and that'd be fine. Will get a patch in shortly.

**Comment by stuartarchibald** [comment]
Patching up the example so the lowering is available for the types presented:
```python
import numba
from numba.extending import (
    overload,
    models,
    lower_builtin,
    register_model,
    make_attribute_wrapper,
    type_callable,
    typeof_impl,
)
from numba.core import types, cgutils
from numba import njit
import operator
import numpy as np


class StringArray(object):
    def __init__(self, str_list):
        # dummy constructor
        self.data = str_list

    def __repr__(self):
        return 'StringArray({})'.format(self.data)

class StringArrayType(types.Type):
    def __init__(self):
        super(StringArrayType, self).__init__(
            name='StringArrayType()')

    @property
    def dtype(self):
        return types.unicode_type

string_array_type = StringArrayType()
str_arr_data_type = types.containers.List(types.unicode_type, True)

@typeof_impl.register(StringArray)
def typeof_string_array(val, c):
    return string_array_type

@type_callable(StringArray)
def type_string_array_call(context):
    def typer(str_list):
        return string_array_type
    return typer

@register_model(StringArrayType)
class StringArrayModel(models.StructModel):
    def __init__(self, dmm, fe_type):

        members = [
            ('data', str_arr_data_type),
        ]
        models.StructModel.__init__(self, dmm, fe_type, members)

make_attribute_wrapper(StringArrayType, 'data', '_data')


@lower_builtin(StringArray, str_arr_data_type)
def impl_dummy(context, builder, sig, args):
    data_val, = args
    str_arr = cgutils.create_struct_proxy(
        sig.return_type)(context, builder)
    str_arr.data = data_val

    # increase refcount of stored values
    if context.enable_nrt:
        context.nrt.incref(builder, sig.args[0], data_val)

    return str_arr._getvalue()


@overload(operator.eq)
def str_arr_operator_eq_ovld(lhs, rhs):
    print("DEBUG: typing operator_add: lhs={}, rhs={}".format(lhs, rhs))
    if isinstance(lhs, StringArrayType) and isinstance(rhs, StringArrayType):

        def impl(lhs, rhs):
            n = len(lhs._data)
            res = np.empty(n, dtype=types.bool_)
            for i in numba.prange(n):
                res[i] = lhs._data[i] == rhs._data[i]
            return res

        return impl


@njit(parallel=True)
def foo(a, b):

    left = StringArray(a)
    right = StringArray(b)
    return left == right


a1 = ['a', 'b', 'c']
a2 = ['a', 'b', 'c']
print(foo(a1, a2))
```
and applying https://github.com/numba/numba/pull/5614 gives:
```
DEBUG: typing operator_add: lhs=StringArrayType(), rhs=StringArrayType()
<path>/numba/core/ir_utils.py:2031: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'a' of function 'foo'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "issue5575.py", line 89:
@njit(parallel=True)
def foo(a, b):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
<path>/numba/core/ir_utils.py:2031: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'b' of function 'foo'.

For more information visit http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "issue5575.py", line 89:
@njit(parallel=True)
def foo(a, b):
^

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
Traceback (most recent call last):
  File "<path>/numba/core/errors.py", line 726, in new_error_context
    yield
  File "<path>/numba/core/lowering.py", line 267, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/core/lowering.py", line 480, in lower_inst
    func(self, inst)
  File "<path>/numba/parfors/parfor_lowering.py", line 69, in _lower_parfor_parallel
    lowerer.lower_inst(instr)
  File "<path>/numba/core/lowering.py", line 364, in lower_inst
    val = self.lower_assign(ty, inst)
  File "<path>/numba/core/lowering.py", line 538, in lower_assign
    return self.lower_expr(ty, value)
  File "<path>/numba/core/lowering.py", line 1062, in lower_expr
    res = self.lower_call(resty, expr)
  File "<path>/numba/core/lowering.py", line 798, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "<path>/numba/core/lowering.py", line 1022, in _lower_call_normal
    argvals = self.fold_call_args(
  File "<path>/numba/core/lowering.py", line 734, in fold_call_args
    argvals = typing.fold_arguments(pysig,
  File "<path>/numba/core/typing/templates.py", line 238, in fold_arguments
    ba.arguments[name] = normal_handler(i, param, ba.arguments[name])
  File "<path>/numba/core/lowering.py", line 721, in normal_handler
    return self._cast_var(var, signature.args[index])
  File "<path>/numba/core/lowering.py", line 699, in _cast_var
    val = self.loadvar(var.name)
  File "<path>/numba/core/lowering.py", line 1284, in loadvar
    ptr = self.getvar(name)
  File "<path>/numba/core/lowering.py", line 1278, in getvar
    return self.varmap[name]
KeyError: '$22compare_op.8_size0.1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "issue5575.py", line 98, in <module>
    print(foo(a1, a2))
  File "<path>/numba/core/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "<path>/numba/core/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<path>/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<path>/numba/core/dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "<path>/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "<path>/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "<path>/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "<path>/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "<path>/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "<path>/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "<path>/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "<path>/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "<path>/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "<path>/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<path>/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "<path>/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "<path>/numba/core/typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "<path>/numba/core/typed_passes.py", line 370, in run_pass
    lower.lower()
  File "<path>/numba/core/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "<path>/numba/core/lowering.py", line 227, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "<path>/numba/core/lowering.py", line 253, in lower_function_body
    self.lower_block(block)
  File "<path>/numba/core/lowering.py", line 267, in lower_block
    self.lower_inst(inst)
  File "/<env>/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "<path>/numba/core/errors.py", line 733, in new_error_context
    reraise(type(newerr), newerr, tb)
  File "<path>/numba/core/utils.py", line 80, in reraise
    raise value
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
'$22compare_op.8_size0.1'

File "issue5575.py", line 93:
def foo(a, b):
    <source elided>
    right = StringArray(b)
    return left == right
    ^

[1] During: lowering "id=0[LoopNest(index_variable = parfor_index.2, range = (0, $22compare_op.8_size0.1, 1))]{1: <ir.Block at issue5575.py (93)>}Var(parfor_index.2, issue5575.py:93)" at issue5575.py (93)
```
am wondering if array analysis/generation from that needs an update too?

**Comment by kozlov-alexey** [comment]
@stuartarchibald Thank you for a quick fix. I think nothing more is needed, as now error message is perfectly correct and above array analysis problem is investigated separately.
