### ISSUE TITLE
BUG: Bug with parfors reduction (parallel=True) in 0.49

### ISSUE THREAD

**Issue by larsoner** [numba/numba#5584]
Code that works on 0.48 fails on 0.49:

<details>
<summary>(Somewhat) minimal example</summary>

```
import numpy as np
from numba import jit, prange

r1 = np.zeros((1, 3))
r2 = np.zeros((2, 3))


@jit(nopython=True, parallel=True)
def run(rrs, r2):
    """Find nearest point mapping to a set of triangles."""
    tri_idx = np.empty(len(r1), np.int64)
    for ri in prange(len(r1)):
        rr = np.reshape(r1[ri], (1, 3))
        drs = rr - r2
        dist = np.inf
        found = False
        for ii in range(len(drs)):
            this_dist = np.dot(drs[ii], drs[ii])
            if np.abs(this_dist) < np.abs(dist):
                found = True
                pt, dist = ii, this_dist

        if not found:
            pt = 0
        tri_idx[ri] = pt
    return tri_idx


run(r1, r2)
```

</details>

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "bug.py", line 29, in <module>
    run(r1, r2)
  File "/home/larsoner/python/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/home/larsoner/python/numba/numba/core/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/larsoner/python/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/larsoner/python/numba/numba/core/dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/larsoner/python/numba/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/larsoner/python/numba/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/larsoner/python/numba/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/larsoner/python/numba/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/larsoner/python/numba/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/home/larsoner/python/numba/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/home/larsoner/python/numba/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/home/larsoner/python/numba/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/home/larsoner/python/numba/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/home/larsoner/python/numba/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/home/larsoner/python/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/larsoner/python/numba/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/larsoner/python/numba/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/home/larsoner/python/numba/numba/core/typed_passes.py", line 288, in run_pass
    parfor_pass.run()
  File "/home/larsoner/python/numba/numba/parfors/parfor.py", line 2694, in run
    get_parfor_reductions(self.func_ir, p, p.params, self.calltypes)
  File "/home/larsoner/python/numba/numba/parfors/parfor.py", line 3288, in get_parfor_reductions
    reduce_nodes = get_reduce_nodes(param, param_nodes[param], func_ir)
  File "/home/larsoner/python/numba/numba/parfors/parfor.py", line 3394, in get_reduce_nodes
    assert reduce_nodes, "Invalid reduction format"
AssertionError: Failed in nopython mode pipeline (step: convert to parfors)
Invalid reduction format
```

</details>

This can be easily fixed for example by just doing `pt = 0` before the loop rather than messing around with the `pt` business, so I can work around it for now (even though the full/non-minimal example is a bit more complex in practice). But it might be worth looking into the source of the error at the `numba` end. A `git bisect` suggests that this was introduced by 76b606ddfde801b8ea833120fc6c3d6691bda0e6, though it's always possible I did it wrong.

FWIW, during some steps in the bisect I did get some potentially informative warnings (followed by dense tracebacks), like:
```
/home/larsoner/python/numba/numba/core/ssa.py:307: NumbaWarning: Detected uninitialized variable pt

File "bug.py", line 25:
def run(rrs, r2):
    <source elided>
            pt = 0
        tri_idx[ri] = pt
        ^
```
So even if this code no longer works, this sort of warning would at least point toward a suitable fix.

**Comment by stuartarchibald** [comment]
Thanks for the report. I suspect the changes to Numba's intermediate representation to [static single assignment](https://en.wikipedia.org/wiki/Static_single_assignment_form) may be involved. Given this works without `parallel=True`, I am wondering if the scan for reductions needs an update.

**Comment by stuartarchibald** [comment]
CC @DrTodd13

**Comment by DrTodd13** [comment]
@stuartarchibald @larsoner Seems to be working on master now.  Will close this but please re-open if master doesn't work for you.
