### ISSUE TITLE
builtins.ImportError: Numba could not be imported.

### ISSUE THREAD

**Issue by MihailTsybakov** [numba/numba#5585]
Hi! I tried to run a simple python code:
```python
from numba import njit

@njit
def factorial(integer):
    factorial = 1
    for i in range(1, integer + 1):
        factorial = factorial * i
    print( factorial )
    
factorial(20)
```

and then I encountered the following problem:

"builtins.ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed' "

 I obtained Numba by "pip install numba",  my os is Windows.

I would be grateful for any information how to solve this problem, thank you in advance.

**Comment by misantroop** [comment]
Same issue here since latest update:

> Traceback (most recent call last):
>   File "C:\Users\s\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
>     from numba.core.typeconv import _typeconv
> ImportError: DLL load failed while importing _typeconv: The specified module could not be found.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "c:/WERK/proj3/git/projQt3_20.py", line 2, in <module>
>     import sys, os, glob, math, re, numba, traceback, operator, itertools
>   File "C:\Users\s\AppData\Roaming\Python\Python38\site-packages\numba\__init__.py", line 20, in <module>
>     from numba.misc.special import (
>   File "C:\Users\s\AppData\Roaming\Python\Python38\site-packages\numba\misc\special.py", line 3, in <module>
>     from numba.core.typing.typeof import typeof
>   File "C:\Users\s\AppData\Roaming\Python\Python38\site-packages\numba\core\typing\__init__.py", line 1, in <module>
>     from .context import BaseContext, Context
>   File "C:\Users\s\AppData\Roaming\Python\Python38\site-packages\numba\core\typing\context.py", line 11, in <module>
>     from numba.core.typeconv import Conversion, rules
>   File "C:\Users\s\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
>     from .typeconv import TypeManager, TypeCastingRules
>   File "C:\Users\s\AppData\Roaming\Python\Python38\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
>     raise ImportError(msg % (url, reportme, str(e), sys.executable))
> ImportError: Numba could not be imported.
> If you are seeing this message and are undertaking Numba development work, you may need to re-run:
> 
> python setup.py build_ext --inplace
> 
> (Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)
> 
> If you are not working on Numba development:
> 
> Please report the error message and traceback, along with a minimal reproducer
> at: https://github.com/numba/numba/issues/new
> 
> If more help is needed please feel free to speak to the Numba core developers
> directly at: https://gitter.im/numba/numba
> 
> Thanks in advance for your help in improving Numba!
> 
> The original error was: 'DLL load failed while importing _typeconv: The specified module could not be found.'
> --------------------------------------------------------------------------------
> If possible please include the following in your error report:
> 
> sys.executable: C:\Python\python.exe

**Comment by misantroop** [comment]
On 0.48, no issues.

**Comment by stuartarchibald** [comment]
Thanks for the report. This typically occurs if the version of python being used to import Numba is mismatched with the Numba installation, looks like at least in the second case you have:
```
C:\Users\s\AppData\Roaming\Python\Python38 <---- Numba install
sys.executable: C:\Python\python.exe  <---- the python you are using the import numba
```

**Comment by MihailTsybakov** [comment]
After a few days I can say that problem solved more trivially than I expected: I just installed latest version of python (I used 3.6, now i have 3.8) and  it worked!

**Comment by tkr789** [comment]
Hi, I got this error too and upgrading to python 3.8 didn't work.:

```
(cellpose) C:\Users\porch>python -m cellpose
Traceback (most recent call last):
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed while importing _typeconv: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 7, in <module>
    from . import utils, models, io
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 13, in <module>
    from . import transforms, dynamics, utils, resnet_style, plot
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\cellpose\dynamics.py", line 9, in <module>
    from numba import njit, float32, int32, vectorize
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\porch\anaconda3\envs\cellpose\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed while importing _typeconv: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\porch\anaconda3\envs\cellpose\python.exe
```

**Comment by VladimirNT** [comment]
Same here with Python 3.7:
Python 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import librosa
Traceback (most recent call last):
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\vturov\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide http://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: The specified module could not be found.'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\vturov\AppData\Local\Programs\Python\Python37\python.exe

**Comment by esc** [comment]
@VladimirNT thanks for commenting on this issue. Can you check #5600 - it looks like this might be your issue. Also, there is a workaround listed here https://github.com/numba/numba/issues/5600#issuecomment-617937885 that you could try.

**Comment by VladimirNT** [comment]
Thanks, after installing **numba==0.47.0** it worked

**Comment by esc** [comment]
> numba==0.48.0 works

FYI: the latest Numba is https://pypi.org/project/numba/0.55.2/
