### ISSUE TITLE
 cannot determine Numba type of <class 'lmfit.parameter.Parameter'>. Error while using Numba with lmfit

### ISSUE THREAD

**Issue by shankardutt** [numba/numba#5590]
Hi, 
I am trying to use lmfit with Numba compiled model. The model is as follows:

```
import numpy as np
from scipy import integrate
from scipy.special import j1
from scipy.special import j0
from numpy import sin
from numpy import cos
from numpy import pi
import time
import numba as nb
from numba import jit
from numba import cfunc
from numba.types import intc, CPointer, float64
from scipy import LowLevelCallable
from matplotlib import pyplot as plt

def HC_angular(q, amp, background, radius, pd, roughness, angle):
    #q = np.linspace(0.03, 1.0, 1000)
    #pd = 0.03
    #radius = 40
    #angle = 1
    length = 20000 #20000nm = 20um
    c = radius
    s = pd * c
    l = length / 2
    
    def jit_integrand_function(integrand_function):
        jitted_function = jit(integrand_function, nopython=True)
        @cfunc(float64(intc, CPointer(float64)), error_model="numpy", fastmath=True)
        def wrapped(n, xx):
            ar = nb.carray(xx, n)
            return jitted_function(ar[0], ar[1], ar[2])
        return LowLevelCallable(wrapped.ctypes)

    @jit_integrand_function
    def f(z,theta,q):
        def ff(theta, z, q):
            qz = q * sin(theta)
            qr = q * cos(theta)
            return (sin(qz * l) * z * j1(qr * z) / (qr * qz)) ** 2

        def g_distribution(z, radius, pd):
            return  np.exp(-0.5 * (((z - radius) / s) ** 2))

        return ff(theta,z,q)*g_distribution(z,radius,pd)* sin(theta)


    va = radius - 4*pd*radius
    if va<0:
        va = 0
    vb = radius + 4*pd*radius
    
    
    def lower_inner(z):
        return va

    def upper_inner(z):
        return vb

    y = np.empty(len(q))
    for n in range(len(q)):
        y[n] = integrate.dblquad(f, 0, angle*pi/180, lower_inner, upper_inner,args=(q[n],),epsabs=1e-2,epsrel=1e-2)[0]
    
    y = (16 * pi**2)*(1 / (np.sqrt(2 * pi) * s)) * 1e7 * (1 / (pi * radius ** 2 * length)) *  y
    
    return y * amp ** 2 * np.exp(-(roughness*q)**2)  + background
```
When I try to fit it using ```lmfit``` I get the following error:
```
Traceback (most recent call last):
  File "SD_fit.py", line 512, in <module>
    fit(arguments)
  File "SD_fit.py", line 206, in fit
    fit_hc_a(q, r, p)
  File "SD_fit.py", line 461, in fit_hc_a
    result = minner.minimize()
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/lmfit/minimizer.py", line 2176, in minimize
    return function(**kwargs)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/lmfit/minimizer.py", line 1568, in leastsq
    lsout = scipy_leastsq(self.__residual, variables, **lskws)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 383, in leastsq
    shape, dtype = _check_func('leastsq', 'func', func, x0, args, n)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/scipy/optimize/minpack.py", line 26, in _check_func
    res = atleast_1d(thefunc(*((x0[:numinputs],) + args)))
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/lmfit/minimizer.py", line 530, in __residual
    out = self.userfcn(params, *self.userargs, **self.userkws)
  File "SD_fit.py", line 456, in fcn2mmin
    model = smdls.HC_angular(q, amp, background, radius, pd, roughness, angle)
  File "/home/shankar/SD_1D_SAXS/models/Special_Models.py", line 35, in HC_angular
    def f(z,theta,q):
  File "/home/shankar/SD_1D_SAXS/models/Special_Models.py", line 29, in jit_integrand_function
    def wrapped(n, xx):
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/decorators.py", line 259, in wrapper
    res.compile()
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/ccallback.py", line 70, in compile
    cres = self._compile_uncached()
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/ccallback.py", line 84, in _compile_uncached
    cres = self._compiler.compile(sig.args, sig.return_type)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/dispatcher.py", line 81, in compile
    raise retval
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler.py", line 373, in _compile_core
    raise e
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler_machinery.py", line 347, in run
    raise patched_exception
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/typed_passes.py", line 89, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/typed_passes.py", line 67, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/home/shankar/anaconda3/envs/Double_Int/lib/python3.8/site-packages/numba/typeinfer.py", line 985, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'radius': cannot determine Numba type of <class 'lmfit.parameter.Parameter'>

File "models/Special_Models.py", line 44:
        def g_distribution(z, radius, pd):
            <source elided>

        return ff(theta,z,q)*g_distribution(z,radius,pd)* sin(theta)
        ^

[1] During: resolving callee type: type(CPUDispatcher(<function HC_angular.<locals>.f at 0x7ff57d998790>))
[2] During: typing of call at /home/shankar/SD_1D_SAXS/models/Special_Models.py (31)

[3] During: resolving callee type: type(CPUDispatcher(<function HC_angular.<locals>.f at 0x7ff57d998790>))
[4] During: typing of call at /home/shankar/SD_1D_SAXS/models/Special_Models.py (31)


File "models/Special_Models.py", line 31:
        def wrapped(n, xx):
            <source elided>
            ar = nb.carray(xx, n)
            return jitted_function(ar[0], ar[1], ar[2])
            ^
```

Please let me know what to do?

**Comment by stuartarchibald** [comment]
Thanks for the report. In general only a subset of NumPy and Python functions/features are supported by Numba, documentation on those supported can be found here.
 * [NumPy Features](http://numba.pydata.org/numba-doc/latest/reference/numpysupported.html)
 * [Python Features](http://numba.pydata.org/numba-doc/latest/reference/pysupported.html)


The error message from trying to compile your code says: `Untyped global name 'radius': cannot determine Numba type of <class 'lmfit.parameter.Parameter'>`, i.e. there's a variable `radius` that is of type `lmfit.parameter.Parameter` and Numba has no idea what to do with it. If you can make it into a numerical constant (like a float, int or tuple) in the globals then that should work.

Hope this helps?
