### ISSUE TITLE
First class function type breaks literal_unroll

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#5615]
## Reporting a bug

- [x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

This worked on 0.48:
```python
from numba import literal_unroll, njit
import numba
import numpy as np

@njit
def foo1(x):
    return x + 1


@njit
def foo2(x):
    return x + 2


tup = ((foo1, foo2), (foo2, foo1))


@njit
def bar(fcs):
    x = 0
    a = 10
    for t in literal_unroll(fcs):
        i, j = t
        x += i(j(a))
    return x

print(numba.__version__)
print(bar(tup))
```
e.g.
```
$ python foo.py                                                                                                               
0.48.0                                                                                                                          
26 
```
but in 0.49 it does this:
```
0.50.0dev0+128.g82c7d37ad
<path>/numba/core/utils.py:508: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
gi196.py:22: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  for t in literal_unroll(fcs):
gi196.py:22: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  for t in literal_unroll(fcs):
gi196.py:23: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  i, j = t
<path>/numba/core/utils.py:508: NumbaExperimentalFeatureWarning: First-class function type feature is experimental
  warnings.warn("First-class function type feature is experimental",
Traceback (most recent call last):
  File "<path>/numba/core/errors.py", line 726, in new_error_context
    yield
  File "<path>/numba/core/lowering.py", line 267, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/core/lowering.py", line 364, in lower_inst
    val = self.lower_assign(ty, inst)
  File "<path>/numba/core/lowering.py", line 538, in lower_assign
    return self.lower_expr(ty, value)
  File "<path>/numba/core/lowering.py", line 1193, in lower_expr
    return impl(self.builder, (self.loadvar(expr.value.name),
  File "<path>/numba/core/base.py", line 1155, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "<path>/numba/core/base.py", line 1185, in wrapper
    return fn(*args, **kwargs)
  File "<path>/numba/cpython/tupleobj.py", line 253, in getitem_typed
    DOCAST = context.typing_context.unify_types(sig.args[0][i],
  File "<path>/numba/core/typing/context.py", line 630, in unify_types
    unified = self.unify_pairs(unified, tp)
  File "<path>/numba/core/typing/context.py", line 649, in unify_pairs
    unified = first.unify(self, second)
  File "<path>/numba/core/types/containers.py", line 319, in unify
    return Tuple(unified)
  File "<path>/numba/core/types/abstract.py", line 65, in __call__
    inst = type.__call__(cls, *args, **kwargs)
  File "<path>/numba/core/types/containers.py", line 280, in __new__
    t = utils.unified_function_type(types, require_precise=True)
  File "<path>/numba/core/utils.py", line 536, in unified_function_type
    assert undefined_function == t
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "gi196.py", line 28, in <module>
    print(bar(tup))
  File "<path>/numba/core/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "<path>/numba/core/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "<path>/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<path>/numba/core/dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "<path>/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "<path>/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "<path>/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "<path>/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "<path>/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "<path>/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "<path>/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "<path>/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "<path>/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "<path>/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "<path>/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "<path>/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "<path>/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "<path>/numba/core/typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "<path>/numba/core/typed_passes.py", line 370, in run_pass
    lower.lower()
  File "<path>/numba/core/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "<path>/numba/core/lowering.py", line 227, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "<path>/numba/core/lowering.py", line 253, in lower_function_body
    self.lower_block(block)
  File "<path>/numba/core/lowering.py", line 267, in lower_block
    self.lower_inst(inst)
  File "<env>/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "<path>/numba/core/errors.py", line 733, in new_error_context
    reraise(type(newerr), newerr, tb)
  File "<path>/numba/core/utils.py", line 80, in reraise
    raise value
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)


File "gi196.py", line 22:
def bar(fcs):
    <source elided>
    a = 10
    for t in literal_unroll(fcs):
    ^

[1] During: lowering "t.25 = typed_getitem(value=$14call_function.4, dtype=Tuple(type(CPUDispatcher(<function foo1 at 0x7f7d000f5ca0>)), type(CPUDispatcher(<function foo2 at 0x7f7ceeec6d30>))), index=$phi20.1)" at gi196.py (22)
```
and I think that this is fundamentally because type unification is broken:
```python
from numba import njit, typeof
from numba.core.typing.context import Context
import numpy as np

@njit
def foo1(x):
    return x + 1


@njit
def foo2(x):
    return x + 2


x = (foo1, foo2)
y = (foo2, foo1)

xty = typeof(x)
yty = typeof(y)


tyctx = Context()
tyctx.unify_types(xty, yty)
```
gives:
```
/numba/core/utils.py", line 536, in unified_function_type
    assert undefined_function == t
AssertionError
```
where it should probably just refuse to unify and return `None`, or the caller catch the assert (which I'd rather it didn't as control flow by exception handling can be avoided here).

CC @pearu

**Comment by pearu** [comment]
While returning `None` fixes the AssertionError issue, it does not fix the `literal_unroll` breakage issue.
I tried to turn off the first-class function type feature but I still get
```
E                   numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
E                   Invalid use of getiter with parameters (Tuple(Tuple(type(CPUDispatcher(<function TestMiscIssues.test_issue_5615.<locals>.foo1 at 0x7fae815f4e50>)), type(CPUDispatcher(<function TestMiscIssues.test_issue_5615.<locals>.foo2 at 0x7fae815f4ee0>))), Tuple(type(CPUDispatcher(<function TestMiscIssues.test_issue_5615.<locals>.foo2 at 0x7fae815f4ee0>)), type(CPUDispatcher(<function TestMiscIssues.test_issue_5615.<locals>.foo1 at 0x7fae815f4e50>)))))
E                    * parameterized
E                   [1] During: typing of intrinsic-call at /home/pearu/git/Quansight/numba/numba/tests/test_function_type.py (1109)
E                   
E                   File "numba/tests/test_function_type.py", line 1109:
E                           def bar(fcs):
E                               <source elided>
E                               a = 10
E                               for t in literal_unroll(fcs):
E                               ^
```

**Comment by pearu** [comment]
It turns out that the above `TypingError` occurs with the numba git revision ef4418561744346b0ad717ebfdaf0b86221735ee (that is the one before merging the first-class function type PR) as well. So the `TypingError` issue may be a separate issue.

**Comment by stuartarchibald** [comment]
This hack:
```patch
diff --git a/numba/core/types/containers.py b/numba/core/types/containers.py
index 00cf0ce1e..026537249 100644
--- a/numba/core/types/containers.py
+++ b/numba/core/types/containers.py
@@ -277,7 +277,11 @@ class Tuple(BaseAnonymousTuple, _HeterogeneousTuple):
 
     def __new__(cls, types):
 
-        t = utils.unified_function_type(types, require_precise=True)
+        t = None
+        try:
+            t = utils.unified_function_type(types, require_precise=True)
+        except AssertionError as e:
+            pass
         if t is not None:
             return UniTuple(dtype=t, count=len(types))
```
seems to fix the issue on `master` and `release0.49` branches for the sample in the OP. Do you have a reproducer for the issue you are seeing? Thanks.

**Comment by pearu** [comment]
Yes, I expect that `test_issue_5615` in #5626 will fail TypingError but when using the same code from a standalone script, the test works ok.

Neither catching assert exception nor disabling are not ideal solutions. I am investigating another approach but for the 0.49.1RC1 both fixes would be fine.

**Comment by sklam** [comment]
@pearu, @stuartarchibald, the reason the test is failing inside a `unittest.TestCase` is that the `from numba import literal_unroll` match needs to be a global because of this line https://github.com/numba/numba/blob/1873621f1a4a53520c5e8b9f6604e7c55bdf90da/numba/core/untyped_passes.py#L618

**Comment by stuartarchibald** [comment]
> @pearu, @stuartarchibald, the reason the test is failing inside a `unittest.TestCase` is that the `from numba import literal_unroll` match needs to be a global because of this line
> 
> https://github.com/numba/numba/blob/1873621f1a4a53520c5e8b9f6604e7c55bdf90da/numba/core/untyped_passes.py#L618

Thanks, patched in https://github.com/numba/numba/pull/5638

**Comment by stuartarchibald** [comment]
Closing as #5626 and #5658 fixed.
