### ISSUE TITLE
Parallel example function error

### ISSUE THREAD

**Issue by wtld** [numba/numba#5633]
- [x] I am using the latest released version of Numba (0.49.0)
- [x] I have included below a minimal working reproducer

The following code uses the example function from the Numba documentation (https://numba.pydata.org/numba-doc/dev/user/parallel.html):
```
from numba import njit
import numpy as np

@njit(parallel=True)
def prange_test(A):
    s = 0
    # Without "parallel=True" in the jit-decorator
    # the prange statement is equivalent to range
    for i in prange(A.shape[0]):
        s += A[i]
    return s

a = np.array(range(10000))

prange_test(a)
````
and I am getting this error:
```
Traceback (most recent call last):

  File "xxx\numba_mp_test.py", line 15, in <module>
    prange_test(a)

  File "C:\ProgramData\WPy64-3820\python-3.8.2.amd64\lib\site-packages\numba\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')

  File "C:\ProgramData\WPy64-3820\python-3.8.2.amd64\lib\site-packages\numba\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)

  File "C:\ProgramData\WPy64-3820\python-3.8.2.amd64\lib\site-packages\numba\six.py", line 668, in reraise
    raise value.with_traceback(tb)

TypingError: cannot determine Numba type of <class 'numba.ir.UndefinedType'>
```
I use numba 0.49.0, Python 3.8.2 and numpy 1.18.2 (from winpython installation)

**Comment by wtld** [comment]
I forgot to import "prange" :) I'm sorry for the confusion.

**Comment by stuartarchibald** [comment]
@wtld no problem, it should have warned you, did it not? I get:
```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)                                       
Untyped global name 'prange': cannot determine Numba type of <class 'numba.core.ir.UndefinedType'>                              
                                                                                                                                
File "issue5633.py", line 9:                                                                                                    
def prange_test(A):                                                                                                             
    <source elided>                                                                                                             
    # the prange statement is equivalent to range                                                                               
    for i in prange(A.shape[0]):                                                                                                
    ^                                                                                                                           
                                                                                                                                
'prange' looks like a Numba internal function, has it been imported (i.e. 'from numba import prange')?  
```

**Comment by wtld** [comment]
Yes, I see now this warning in the Python console. But I use IPython console in Spyder and quoted output is everything I get there.
