### ISSUE TITLE
Unable to install numba - any help much appreciated! 

### ISSUE THREAD

**Issue by alistairone** [numba/numba#5647]
Traceback (most recent call last):
  File "C:\Users\A.Salisbury\Anaconda3\Scripts\numba-script.py", line 6, in <module>
    from numba.numba_entry import main
  File "C:\Users\A.Salisbury\Anaconda3\lib\site-packages\numba\__init__.py", line 20, in <module>
    from numba.misc.special import (
  File "C:\Users\A.Salisbury\Anaconda3\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\A.Salisbury\Anaconda3\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\A.Salisbury\Anaconda3\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\A.Salisbury\Anaconda3\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\A.Salisbury\Anaconda3\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.

sys.executable: C:\Users\A.Salisbury\Anaconda3\python.exe

**Comment by stuartarchibald** [comment]
Thanks for the report. Does this https://github.com/numba/numba/issues/5600#issuecomment-617937885 help ?

**Comment by alistairone** [comment]
I let you know..!

> Thanks for the report. Does this [#5600 (comment)](https://github.com/numba/numba/issues/5600#issuecomment-617937885) help ?

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
