### ISSUE TITLE
Doesn’t work outright on latest Centos from Google cloud compute

### ISSUE THREAD

**Issue by ytrezq** [numba/numba#5691]
I just did that on a fresh Centᴏꜱ Skylake ᴠᴍ today :

    dnf install python38-devel
    sudo python3.8 -m pip install numba
then :

    Python 3.8.0 (default, Mar 10 2020, 14:58:28)
    [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import numba
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib64/python3.8/site-packages/numba/__init__.py", line 298, in <module>
        import numba.typed
      File "/usr/local/lib64/python3.8/site-packages/numba/typed/__init__.py", line 1, in <module>
        from .typeddict import Dict
      File "/usr/local/lib64/python3.8/site-packages/numba/typed/typeddict.py", line 23, in <module>
        def _make_dict(keyty, valty):
      File "/usr/local/lib64/python3.8/site-packages/numba/core/decorators.py", line 236, in njit
        return jit(*args, **kws)
      File "/usr/local/lib64/python3.8/site-packages/numba/core/decorators.py", line 173, in jit
        return wrapper(pyfunc)
      File "/usr/local/lib64/python3.8/site-packages/numba/core/decorators.py", line 187, in wrapper
        disp = dispatcher(py_func=func, locals=locals,
      File "/usr/local/lib64/python3.8/site-packages/numba/core/dispatcher.py", line 670, in __init__
        self.targetctx = self.targetdescr.target_context
      File "/usr/local/lib64/python3.8/site-packages/numba/core/registry.py", line 47, in target_context
        return self._toplevel_target_context
      File "/usr/local/lib64/python3.8/site-packages/numba/core/utils.py", line 331, in __get__
        res = instance.__dict__[self.name] = self.func(instance)
      File "/usr/local/lib64/python3.8/site-packages/numba/core/registry.py", line 31, in _toplevel_target_context
        return cpu.CPUContext(self.typing_context)
      File "/usr/local/lib64/python3.8/site-packages/numba/core/base.py", line 259, in __init__
        self.init()
      File "/usr/local/lib64/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
        return func(*args, **kwargs)
      File "/usr/local/lib64/python3.8/site-packages/numba/core/cpu.py", line 47, in init
        self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
      File "/usr/local/lib64/python3.8/site-packages/numba/core/codegen.py", line 645, in __init__
        self._init(self._llvm_module)
      File "/usr/local/lib64/python3.8/site-packages/numba/core/codegen.py", line 654, in _init
        tm = target.create_target_machine(**tm_options)
      File "/usr/local/lib64/python3.8/site-packages/llvmlite/binding/targets.py", line 229, in create_target_machine
        assert 0 <= opt <= 3
    AssertionError
    >>>

**Comment by stuartarchibald** [comment]
Thanks for the report. Do you happen to have the environment variable `NUMBA_OPT` set to something that isn't 0, 1, 2, or 3?

**Comment by ytrezq** [comment]
You re correct. I set it to 4 because llvm support 4 levels of optimizations and I wanted the highest one.

**Comment by stuartarchibald** [comment]
The `NUMBA_OPT` level corresponds roughly to LLVM `opt`'s `-O` levels. Seems like there's no `-O4` for `opt`:
```
$ opt --version
LLVM (http://llvm.org/):
  LLVM version 10.0.0
  Optimized build.
  <snip>

$ opt -O4
opt: Unknown command line argument '-O4'.  Try: 'opt --help'
opt: Did you mean '--O0'?
```
LLVM master has this encoded:
https://github.com/llvm/llvm-project/blob/25d6995079431531c2c7c8955ebe9a3d1875180d/llvm/tools/opt/opt.cpp#L893-L909

What's supporting `-O4`, are you perhaps thinking of clang?

**Comment by guilhermeleobas** [comment]
From the [clang docs](https://clang.llvm.org/docs/CommandGuide/clang.html#cmdoption-o0), -O4 is equivalent to -O3.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
