### ISSUE TITLE
Overload float(), int() and str() to do number <-> string conversion

### ISSUE THREAD

**Issue by DannyWeitekamp** [numba/numba#5723]
So currently all three of these jitted functions will fail

```python
@njit
def failed_str():
	str(1.2)
@njit
def failed_float():
	float("1.2")
@njit
def failed_int():
	int("1.2")
```
I've tried re-implementing these and overloading them.
Strings -> Numbers
```python
@njit
def str_to_posint(s):
	final_index, result = len(s) - 1, 0
	for i,v in enumerate(s):
		result += (ord(v) - 48) * (10 ** (final_index - i))
	return result

@njit
def str_to_int(s):
	neg = (s[0] == "-")
	if(neg): s = s[1:]
	result = str_to_posint(s)
	return -result if neg else result

@njit
def str_to_float(s):
	neg = (s[0] == "-")
	if(neg): s = s[1:]

	exp,dec_loc,exp_loc = 1,-1, len(s)
	for i,c in enumerate(s):
		if(c == "."): 
			dec_loc=i
		elif(c == "e"):
			exp_loc=i
			exp = str_to_int(s[exp_loc+1:])

	if(dec_loc != -1):
		result = str_to_posint(s[:dec_loc])
		result += float(str_to_posint(s[dec_loc+1:exp_loc])) / np.power(10,(exp_loc-dec_loc-1))
	else:
		result = str_to_posint(s)

	if(exp != 1):
		result *= 10.**exp

	if(neg): result = -result
	return result
``` 
Numbers -> Strings
```python
@overload(str)
def _str(x):
	if isinstance(x,types.Integer):
		def int_to_str(x):
			isneg = int(x < 0.0)
			x = np.abs(x)
			l = 0 
			_x = x
			while _x > 0:
				_x = _x // 10
				l += 1
			s = _empty_string(PY_UNICODE_1BYTE_KIND,l+isneg)
			if(isneg): _set_code_point(s,0,DASH)
			for i in range(l):
				digit = x % 10
				_set_code_point(s,isneg+l-i-1,digit + DIGITS_START)
				x = x // 10
			return s
		return int_to_str
	elif isinstance(x,types.Float):
		def float_to_str(x):
			if(x == np.inf):
				return 'inf'
			elif(x == -np.inf):
				return '-inf'

			isneg = int(x < 0.0)
			x = np.abs(x)
			l1,l2 = 0,-1
			_x = x
			while _x > 0:
				_x = _x // 10
				l1 += 1
			_x = x % 10 
			while _x > 1e-10:
				_x = (_x * 10) % 10
				l2 += 1

			l2 = max(1,l2)
			l = l1+l2+1

			_x = x-np.floor(x)
			s = _empty_string(PY_UNICODE_1BYTE_KIND,l+isneg)
			if(isneg): _set_code_point(s,0,DASH)


			_x = x
			for i in range(l1):
				digit = int(_x % 10)
				# print('a',digit,(isneg+l1)-i-1)
				_set_code_point(s,(isneg+l1)-i-1,digit + DIGITS_START)
				_x = _x // 10

			# if(l2 > 0):
			_set_code_point(s,l1+isneg,DOT)

			_x = x % 10 
			for i in range(l2):
				_x = (_x * 10) % 10
				digit = int(_x)  
				# print('here',i,digit)
				# print('b',digit,(isneg+l1)+i+1)
				_set_code_point(s,(isneg+l1)+i+1,digit + DIGITS_START)
			return s
		return float_to_str
```

But it seems that just letting numba loop lift the native python is pretty consistently faster than anything that I can write.

```python
import timeit
N=1000
def time_ms(f):
		f() #warm start
		return " %0.6f ms" % (1000.0*(timeit.timeit(f, number=N)/float(N)))

@njit
def numba_to_str(x):
	return str(x)

def py_to_str(x):
	return str(x)

from warnings import catch_warnings

with catch_warnings(record=True) as w:
	@jit
	def nb_lotsa_strings():
		for i in range(1000):
			numba_to_str(14.58)

	@jit
	def nb_lotsa_strings_int():
		for i in range(1000):
			numba_to_str(14)

	@jit
	def py_lotsa_strings():
		for i in range(1000):
			py_to_str(14.58)

	@jit
	def py_lotsa_strings_int():
		for i in range(1000):
			py_to_str(14)

	print("nb_to_str",time_ms(nb_lotsa_strings))
	print("nb_int_to_str",time_ms(nb_lotsa_strings_int))
	print("py_to_str",time_ms(py_lotsa_strings))
	print("py_int_to_str",time_ms(py_lotsa_strings_int))
```
```bash
----numba---
nb_to_str  1.287220 ms
nb_int_to_str  0.047568 ms
---python---
py_to_str  0.424743 ms
py_int_to_str  0.246021 ms

```

So my feature request is can str(int/float), float(str) and int(str) just be overloaded to grab the GIL and just call native python? Or might there be a way for these to just call out directly to the cpython implementations?

This is related to #5650 and #4758

**Comment by Fryuni** [comment]
Why is this documented as supported if it's a feature request?

https://numba.pydata.org/numba-doc/dev/reference/pysupported.html#built-in-functions says
> int: only the one-argument form

Yet this is not supported:
```python
@njit
def foo(val):
    return int(val) # Look, one argument! It is supported!

foo('123') # Fail
```

Spent nearly 3 hours trying to find out what I was doing wrong. Turns out, I am not, the documentation is.  
It supports "only the one-_numeric_-argument form" or "only numeric conversions".
Saying that it supports "only the one-argument form" induces the comparison to the two-argument form, used to set a different base when converting _only from a string_. So if the doc say that it only support one argument what I get is that you can't set a custom base, not that you can't use strings at all.

Quite sad to lose trust in the docs of a library.

**Comment by astrojuanlu** [comment]
> Yet this is not supported:

You forgot to disclose the version of numba you're using and attach a complete traceback. It's how users help developers fix bugs.

> Spent nearly 3 hours trying to find out what I was doing wrong. Turns out, I am not, the documentation is.

It's entirely possible that the docs are wrong, or slightly incomplete or misleading. It so happens that sometimes humans make mistakes. The good news is that this is an open source project and we can discuss it openly. Or, you know, propose improvements in a constructive way.

> Quite sad to lose trust in the docs of a library.

Leaving dismissive or passive-agressive comments in a public issue tracker that may reach an indeterminate number of subscribers is however a very wrong approach. I, for one, didn't subscribe to this issue to read rants from angry users. I hope you reconsider your attitude.

**Comment by Fryuni** [comment]
Hi @astrojuanlu, sorry about that. I sent it 3 in the morning after a stressful week integrating with undocumented code where I could not change anything. I should not be ranting online in that state, and certainly not on GitHub 😅 

---

Environment:
```
numba==0.53.1
llvmlite==0.36.0
numpy==1.20.1
```

The traceback is the same as the one in the other linked issue #5650:
```
Traceback (most recent call last):
  File "/home/nero/Workspace/python-experiments/scratch.py", line 9, in <module>
    foo('123')
  File "/home/nero/.local/share/virtualenvs/python-experiments-h2LPE6Ld/lib/python3.9/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/nero/.local/share/virtualenvs/python-experiments-h2LPE6Ld/lib/python3.9/site-packages/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<class 'int'>) found for signature:

 >>> int(unicode_type)

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload of function 'int': File: numba/core/typing/builtins.py: Line 925.
    With argument(s): '(unicode_type)':
   No match.

During: resolving callee type: Function(<class 'int'>)
During: typing of call at /home/nero/Workspace/python-experiments/scratch.py (6)


File "scratch.py", line 6:
def foo(val):
    return int(val)
    ^
```

I manage to implement a parsing for my use case based on the suggestion on that same issue.
I'll open a PR suggesting a change in the docs

And sorry everyone, this is a great library

**Comment by esc** [comment]
> And sorry everyone, this is a great library

You apology is accepted, thank you for following up.
