### ISSUE TITLE
failure to use Prange with @njit(parallel=True) on loop which can be parallelised

### ISSUE THREAD

**Issue by ritvik06** [numba/numba#5735]
I am using a function func1 which is as follows :-

**Comment by sklam** [comment]
Can you provide a minimal reproducer, i.e. a script that calls `func1`? Numba will specialize the function with respect to the argument types. Thus, the error you see can be specific to the types that you have.

**Comment by ritvik06** [comment]
What I can do is describe to you types of all the arguments.
```
k ---> int
indexes ---> 1d np array
child0, child1 ---> int, int 
T_node, T_child0, T_child1 ---> int
B_child0, B_child1 ---> a 1d np array
```

I am able to run this code without parallel=True and I am getting the expected by speedup with Numba as well. But only when setting parallel=True I get the error.

**Comment by ritvik06** [comment]
Do you think issue #5601 and this issue are similar, ie. I also use slicing inside my for loop?

**Comment by ritvik06** [comment]
I am now able to run my implementation after building from source using the master branch. But setting parallel=True increases my time of implementation as compared to not setting it(serial implementation). This shouldn't be the case, should it? Please advice.

**Comment by m-beau** [comment]
Hi, I have a similar issue here - the following code works without any error when decorated with @njit(parallel=False) but crashes when parallel=True with the same error:
```
TypeError: Failed in nopython mode pipeline (step: convert to parfors)
object of type 'NoneType' has no len()

> /home/maxime/anaconda3/envs/spy/lib/python3.7/site-packages/numba/parfors/array_analysis.py(2792)<listcomp>()
   2790         asserts = []
   2791         new_shape = []
-> 2792         max_dim = max([len(shape) for shape in shapes])
   2793         const_size_one = None
   2794         for i in range(max_dim):
```

and interestingly enough a different error when decorated with @jit(parallel=True):
```
File "<timed exec>", line 1, in <module>
NameError: global name 'numba' is not defined
> <timed exec>(1)<module>()
```

Here is the function that I am running (spk1 and spk2 are arrays of int64, available_memory is a float):
```
def cisi_numba_para(spk1, spk2, available_memory):
    spk1=np.sort(spk1).astype(np.float64)
    spk2=np.sort(spk1).astype(np.float64)
    memory_el=(0.01*available_memory)//spk1.itemsize
    if memory_el<((len(spk1)*len(spk2))*0.1):
        s=int(len(spk1)//((len(spk1)*len(spk2))//memory_el))
        chunks=split(List(spk1), sample_size=s, return_last=True, overlap=0)
    else:
        s=len(spk1)
        chunks=np.expand_dims(spk1, 0)
    # the trick to make things fast is to only consider
    # the relevant slice of spk2, which is possible assuming that spk1 and spk2 are sorted
    isi_1to2=np.zeros(len(spk1))
    n=chunks.shape[0]
    for i in range(n):
        chunk=chunks[i]
        if i==n-1:chunk=chunk[~np.isnan(chunk)]

        m1=np.array(list(spk2>=chunk[0])[1:]+[True]) # shift left to add spike right before
        m2=np.array([True]+list(spk2<=chunk[-1])[:-1]) # shift right to add spike right after
        chunk2=spk2[m1&m2]
    
        a1=(chunk*np.ones((chunk2.shape[0], chunk.shape[0]))).T
        a2=chunk2*np.ones((chunk.shape[0], chunk2.shape[0]))
        d=np.abs(a1-a2)
        for di in range(d.shape[0]):
            isi_1to2[i*s+di]=np.min(d[di])
        
    return isi_1to2
```

**Comment by stuartarchibald** [comment]
@m-beau thanks for the report.  Please could you provide more information about what caused this problem:

1. The code that you were running (as a minimal working reproducer, if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports). Current code is missing the `split()` function and some example input.
2. Any data needed to run the code.

Once we have a reproducer someone can take a look and work on a fix. Thanks for your help.

**Comment by stuartarchibald** [comment]
> It seems that issue #5601 and this are similar, please add duplicate label

@ritvik06 Please could you provide a minimal working reproducer so that we can verify it is the same problem,  if you are unsure how to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports. Thanks for your help.

**Comment by m-beau** [comment]
Yes, sorry - here you go:

```
import psutil
import numpy as np
from numba import jit, njit, prange
from numba.typed import List

spk1=np.arange(1000)
spk2=spk1+3
available_memory=psutil.virtual_memory().available

@njit(cache=True)
def make_2D_array(arr_lis, accept_heterogeneous=False):
    """Function to get 2D array from a list of lists
    """
    lis=[np.asarray(l) for l in arr_lis]
    n = len(lis)
    lengths = [len(l) for l in lis]
    if accept_heterogeneous:
        max_len = max(lengths)
        arr = np.zeros((n, max_len))*np.nan
        for i,l in enumerate(lis):
            arr[i, :lengths[i]] = l
    else:
        assert max(lengths)==min(lengths)
        arr = np.zeros((n, len(lis[0])))*np.nan
        for i,l in enumerate(lis):
            arr[i, :] = l
    return arr

@njit(cache=True)
def split(arr, sample_size=0, n_samples=0, overlap=0, return_last=True, prnt=True):
    '''
    Parameters:
        - arr: array to split into EITHER n_samples OR samples of size sample_size.
               samples_size has priority over n_samples.
        - s_samples: int, size of of samples to split the array into.
        - n_samples: int, number of samples to split the array into.
        - overlap: 0<=float<1, fraction of overlapping between consecutive samples | Default 0
        - return_last: bool, whether to return the last sample (whose size usually does not match the ones before).
    Returns:
        samples: array or list of samples
    '''
    arr=np.asarray(arr)
    assert n_samples!=0 or sample_size!=0, 'You need to specify either a sample number or size!'
    assert 0<=overlap<1, 'overlap needs to be between 0 and 1, 1 excluded (samples would all be the same)!'
    
    if n_samples!=0 and sample_size!=0:
        print('''WARNING you provided n_samples AND sample_size!
              By convention, sample_size has priority over n_samples. n_samples ignored.''')
        n_samples=0
        
    if n_samples==0: n_samples=len(arr)//sample_size+1
    if sample_size==0: sample_size=len(arr)//(n_samples)
    
    assert n_samples<=len(arr)
        
    # step=1 for maximum overlap (every sample would be the first sample for step = 0);
    # step=s for 0 overlap; overlap is
    s=sample_size
    step = s-round(s*overlap)
    real_o=round((s-step)/s, 2)
    if overlap!=real_o and prnt: print('Real overlap: ', round(real_o, 2))
    samples = List([arr[i : i + s] for i in range(0, len(arr), step)])
    
    # always return last sample if len matches
    if len(samples[-1])==s:
        return make_2D_array(samples)
    
    if return_last:
        return make_2D_array(samples, accept_heterogeneous=True)
    
    lasti=-1
    sp=samples[lasti]
    while len(sp)!=s:
        lasti-=1
        sp=samples[lasti]
    return make_2D_array(samples[:lasti+1])

@njit(cache=True, parallel=True)
def cisi_numba_para(spk1, spk2, available_memory):
    spk1=np.sort(spk1).astype(np.float64)
    spk2=np.sort(spk1).astype(np.float64)
    memory_el=(0.01*available_memory)//spk1.itemsize
    if memory_el<((len(spk1)*len(spk2))*0.1):
        s=int(len(spk1)//((len(spk1)*len(spk2))//memory_el))
        chunks=split(List(spk1), sample_size=s, return_last=True, overlap=0)
    else:
        s=len(spk1)
        chunks=np.expand_dims(spk1, 0)
    # the trick to make things fast is to only consider
    # the relevant slice of spk2, which is possible assuming that spk1 and spk2 are sorted
    isi_1to2=np.zeros(len(spk1))
    n=chunks.shape[0]
    for i in prange(n):
        chunk=chunks[i]
        if i==n-1:chunk=chunk[~np.isnan(chunk)]

        m1=np.array(list(spk2>=chunk[0])[1:]+[True]) # shift left to add spike right before
        m2=np.array([True]+list(spk2<=chunk[-1])[:-1]) # shift right to add spike right after
        chunk2=spk2[m1&m2]
    
        a1=(chunk*np.ones((chunk2.shape[0], chunk.shape[0]))).T
        a2=chunk2*np.ones((chunk.shape[0], chunk2.shape[0]))
        d=np.abs(a1-a2)
        for di in prange(d.shape[0]):
            isi_1to2[i*s+di]=np.min(d[di])
        
    return isi_1to2

cisi=cisi_numba_para(spk1, spk2, available_memory)
```

Any optimization advice is welcome.

**Comment by esc** [comment]
@m-beau thanks for submitting this. When running the full code listed above, I receive the following error:

```
Traceback (most recent call last):
  File "foo067.py", line 109, in <module>
    cisi=cisi_numba_para(spk1, spk2, available_memory)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    raise e
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 288, in run_pass
    parfor_pass.run()
  File "/Users/vhaenel/git/numba/numba/parfors/parfor.py", line 2590, in run
    self._pre_run()
  File "/Users/vhaenel/git/numba/numba/parfors/parfor.py", line 2585, in _pre_run
    self.array_analysis.run(self.func_ir.blocks)
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 1117, in run
    self._run_on_blocks(topo_order, blocks, cfg, init_equiv_set)
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 1137, in _run_on_blocks
    pending_transforms = self._determine_transform(
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 1218, in _determine_transform
    pre, post = self._analyze_inst(
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 1253, in _analyze_inst
    result = self._analyze_expr(scope, equiv_set, inst.value)
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 1473, in _analyze_expr
    return guard(fn, scope, equiv_set, expr)
  File "/Users/vhaenel/git/numba/numba/core/ir_utils.py", line 1450, in guard
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 2055, in _analyze_op_arrayexpr
    return self._analyze_broadcast(
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 2814, in _analyze_broadcast
    return self._broadcast_assert_shapes(
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 2824, in _broadcast_assert_shapes
    max_dim = max([len(shape) for shape in shapes])
  File "/Users/vhaenel/git/numba/numba/parfors/array_analysis.py", line 2824, in <listcomp>
    max_dim = max([len(shape) for shape in shapes])
TypeError: Failed in nopython mode pipeline (step: convert to parfors)
object of type 'NoneType' has no len()
```

This is using:

```
@njit(cache=True, parallel=True)
def cisi_numba_para(spk1, spk2, available_memory):
```

But when I use:

```
@njit(cache=True, parallel=False)
def cisi_numba_para(spk1, spk2, available_memory):
```

The code runs fine. So it is probably something to do with `parallel` indeed.

The next step would be to reduce the code example to be minimal. I.e. to remove any code that is not involved in reproducing the error message.

**Comment by ritvik06** [comment]
Have you tried running the code by building Numba from source using the master branch? There was a recent change regarding the parallel accelerator. Numba is unable to handle slicing of np arrays using parallel and maybe hence the error, in the recent version this error is ignored.

**Comment by esc** [comment]
I just ran the code above again with `0.50.0dev0-328-ge3002f06ff` just to be sure and it  is indeed still not working. The error is still `object of type 'NoneType' has no len()`.

@ritvik06 thanks for following up and confirming that the issue is now resolved for you.

**Comment by DrTodd13** [comment]
> Yes, sorry - here you go:
> 
> ```
> import psutil
> import numpy as np
> from numba import jit, njit, prange
> from numba.typed import List
> 
> spk1=np.arange(1000)
> spk2=spk1+3
> available_memory=psutil.virtual_memory().available
> 
> @njit(cache=True)
> def make_2D_array(arr_lis, accept_heterogeneous=False):
>     """Function to get 2D array from a list of lists
>     """
>     lis=[np.asarray(l) for l in arr_lis]
>     n = len(lis)
>     lengths = [len(l) for l in lis]
>     if accept_heterogeneous:
>         max_len = max(lengths)
>         arr = np.zeros((n, max_len))*np.nan
>         for i,l in enumerate(lis):
>             arr[i, :lengths[i]] = l
>     else:
>         assert max(lengths)==min(lengths)
>         arr = np.zeros((n, len(lis[0])))*np.nan
>         for i,l in enumerate(lis):
>             arr[i, :] = l
>     return arr
> 
> @njit(cache=True)
> def split(arr, sample_size=0, n_samples=0, overlap=0, return_last=True, prnt=True):
>     '''
>     Parameters:
>         - arr: array to split into EITHER n_samples OR samples of size sample_size.
>                samples_size has priority over n_samples.
>         - s_samples: int, size of of samples to split the array into.
>         - n_samples: int, number of samples to split the array into.
>         - overlap: 0<=float<1, fraction of overlapping between consecutive samples | Default 0
>         - return_last: bool, whether to return the last sample (whose size usually does not match the ones before).
>     Returns:
>         samples: array or list of samples
>     '''
>     arr=np.asarray(arr)
>     assert n_samples!=0 or sample_size!=0, 'You need to specify either a sample number or size!'
>     assert 0<=overlap<1, 'overlap needs to be between 0 and 1, 1 excluded (samples would all be the same)!'
>     
>     if n_samples!=0 and sample_size!=0:
>         print('''WARNING you provided n_samples AND sample_size!
>               By convention, sample_size has priority over n_samples. n_samples ignored.''')
>         n_samples=0
>         
>     if n_samples==0: n_samples=len(arr)//sample_size+1
>     if sample_size==0: sample_size=len(arr)//(n_samples)
>     
>     assert n_samples<=len(arr)
>         
>     # step=1 for maximum overlap (every sample would be the first sample for step = 0);
>     # step=s for 0 overlap; overlap is
>     s=sample_size
>     step = s-round(s*overlap)
>     real_o=round((s-step)/s, 2)
>     if overlap!=real_o and prnt: print('Real overlap: ', round(real_o, 2))
>     samples = List([arr[i : i + s] for i in range(0, len(arr), step)])
>     
>     # always return last sample if len matches
>     if len(samples[-1])==s:
>         return make_2D_array(samples)
>     
>     if return_last:
>         return make_2D_array(samples, accept_heterogeneous=True)
>     
>     lasti=-1
>     sp=samples[lasti]
>     while len(sp)!=s:
>         lasti-=1
>         sp=samples[lasti]
>     return make_2D_array(samples[:lasti+1])
> 
> @njit(cache=True, parallel=True)
> def cisi_numba_para(spk1, spk2, available_memory):
>     spk1=np.sort(spk1).astype(np.float64)
>     spk2=np.sort(spk1).astype(np.float64)
>     memory_el=(0.01*available_memory)//spk1.itemsize
>     if memory_el<((len(spk1)*len(spk2))*0.1):
>         s=int(len(spk1)//((len(spk1)*len(spk2))//memory_el))
>         chunks=split(List(spk1), sample_size=s, return_last=True, overlap=0)
>     else:
>         s=len(spk1)
>         chunks=np.expand_dims(spk1, 0)
>     # the trick to make things fast is to only consider
>     # the relevant slice of spk2, which is possible assuming that spk1 and spk2 are sorted
>     isi_1to2=np.zeros(len(spk1))
>     n=chunks.shape[0]
>     for i in prange(n):
>         chunk=chunks[i]
>         if i==n-1:chunk=chunk[~np.isnan(chunk)]
> 
>         m1=np.array(list(spk2>=chunk[0])[1:]+[True]) # shift left to add spike right before
>         m2=np.array([True]+list(spk2<=chunk[-1])[:-1]) # shift right to add spike right after
>         chunk2=spk2[m1&m2]
>     
>         a1=(chunk*np.ones((chunk2.shape[0], chunk.shape[0]))).T
>         a2=chunk2*np.ones((chunk.shape[0], chunk2.shape[0]))
>         d=np.abs(a1-a2)
>         for di in prange(d.shape[0]):
>             isi_1to2[i*s+di]=np.min(d[di])
>         
>     return isi_1to2
> 
> cisi=cisi_numba_para(spk1, spk2, available_memory)
> ```
> 
> Any optimization advice is welcome.

This is not a minimal reproducer.  I simplified the example while retaining the error and got it down to 25 lines (and even that is not absolutely minimal).  As you can imagine, the less code we have to wade through to find the error, the easier it is on us.

In terms of optimization, isn't your first prange parallelizing over a very small number (1 in the case of expand_dims).

**Comment by stuartarchibald** [comment]
This is still an issue on 0.55 but the error has changed.

**Comment by Debabrataadak** [comment]
@njit(cache=True,parallel=True)
def jit_linsolve(A, b):
    m = A.shape[0]
    n=A.shape[-1]
    k=b.shape[-1]
    ret = np.empty((m, n,k))
    for i in prange(m):
        ret[i, :] = np.linalg.solve(A[i], b)
    #print(ret) 
    return ret

def my_numba_solver(a,b):
    return jit_linsolve(a,b)



this what my simple code is. When I am going to run this in HPC, getting error message:
  return jit_linsolve(a,b)
TypeError: expected dtype object, got 'numpy.dtype[float64]'
