### ISSUE TITLE
Using Exceptions to trigger continue in loops fails

### ISSUE THREAD

**Issue by p-ortmann** [numba/numba#5749]
using the latest version (v0.49.1), would expect this to work without an error - it's not particularly urgent though
```
from numba import njit
import numpy as np
a=np.arange(10)
@njit
def foo(a):
         for _ in a:
            try:
               raise Exception
            except Exception:
               continue
 foo(a)     
```         
Traceback (most recent call last):
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-e48c672f35a5>", line 11, in <module>
    foo(a)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\dispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\dispatcher.py", line 342, in error_rewrite
    raise e
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\dispatcher.py", line 353, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\dispatcher.py", line 794, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\dispatcher.py", line 109, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler.py", line 568, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler.py", line 381, in _compile_core
    raise e
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler_machinery.py", line 341, in run
    raise patched_exception
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\untyped_passes.py", line 86, in run_pass
    func_ir = interp.interpret(bc)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\interpreter.py", line 116, in interpret
    flow.run()
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\byteflow.py", line 107, in run
    runner.dispatch(state)
  File "C:\Workdir\Programs\Anaconda2\envs\LTM\lib\site-packages\numba\core\byteflow.py", line 269, in dispatch
    raise UnsupportedError(msg, loc=self.get_debug_loc(inst.lineno))
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (CONTINUE_LOOP) found
File "<ipython-input-5-e48c672f35a5>", line 10:
def foo(a):
    <source elided>
            except Exception:
                continue
                ^
Unsupported functionality was found in the code Numba was trying to compile.
If this functionality is important to you please file a feature request at:
https://github.com/numba/numba/issues/new
<!--

**Comment by esc** [comment]
@p-ortmann thanks for reporting this. Unfortunately, I am unable to reproduce this using both `master` and `0.49.1`. Perhaps you could share more details about your system, such as operating system  version and Python version and any other details that might be relevant? Thanks!

For reference, here is my terminal session to make sure I have run the code as intended.

```
💥 zsh» cat foo072.py
from numba import njit
import numpy as np


a = np.arange(10)


@njit
def foo(a):
    for _ in a:
        try:
            raise Exception
        except Exception:
            continue


foo(a)
💥 zsh» python foo072.py
💥 zsh» echo $?
0

**Comment by p-ortmann** [comment]
@esc it's win 10 enterprise 17763 and python 3.7.7, if it's related to my setup maybe it's not worth while to pursue this.. it's easy to work around it. Thanks for checking anyhow!

**Comment by stuartarchibald** [comment]
@esc if you are using Python 3.8 you won't see it because `CONTINUE_LOOP` opcode was removed. Pretty sure that this is a bug.

```
$ python --version
Python 3.7.7

$ cat issue5749.py
from numba import njit, __version__
import numpy as np

print(__version__)

a=np.arange(10)

@njit
def foo(a):
    for _ in a:
        try:
            raise Exception
        except Exception:
            continue

foo(a)

$ python issue5749.py
0.49.1
Traceback (most recent call last):
  File "issue5749.py", line 16, in <module>
    foo(a)
  File "<path>/lib/python3.7/site-packages/numba/core/dispatcher.py", line 404, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "<path>/lib/python3.7/site-packages/numba/core/dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "<path>/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
Use of unsupported opcode (CONTINUE_LOOP) found

File "issue5749.py", line 14:
def foo(a):
    <source elided>
        except Exception:
            continue
            ^
```

**Comment by esc** [comment]
@stuartarchibald indeed, with 3.7 I can reproduce it too!
