### ISSUE TITLE
CUDA atomicrmw error on windows

### ISSUE THREAD

**Issue by sklam** [numba/numba#5818]
## Reporting a bug

- [x] I am using the latest released version (0.50.0rc1) of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

@gmarkall 

Looks the llvm patch did not fix the problem for windows.
```pytb
======================================================================
ERROR: test_atomic_add_float (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\path\lib\site-packages\numba\cuda\tests\cudapy\test_atomics.py", line 215, in test_atomic_add_float
    cuda_atomic_add_float = cuda.jit('void(float32[:])')(atomic_add_float)
  File "C:\path\lib\site-packages\numba\cuda\decorators.py", line 103, in kernel_jit
    kernel.bind()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 586, in bind
    self._func.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 462, in get
    ptx = self.ptx.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 433, in get
    **self._extra_options)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 515, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 232, in compile
    self._try_error(err, 'Failed to compile\n')
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 250, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 140, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (50, 17): parse expected binary operation in atomicrmw
NVVM_ERROR_COMPILATION

======================================================================
ERROR: test_atomic_add_float_2 (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\path\lib\site-packages\numba\cuda\tests\cudapy\test_atomics.py", line 227, in test_atomic_add_float_2
    cuda_atomic_add2 = cuda.jit('void(float32[:,:])')(atomic_add_float_2)
  File "C:\path\lib\site-packages\numba\cuda\decorators.py", line 103, in kernel_jit
    kernel.bind()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 586, in bind
    self._func.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 462, in get
    ptx = self.ptx.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 433, in get
    **self._extra_options)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 515, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 232, in compile
    self._try_error(err, 'Failed to compile\n')
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 250, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 140, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (62, 18): parse expected binary operation in atomicrmw
NVVM_ERROR_COMPILATION

======================================================================
ERROR: test_atomic_add_float_3 (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\path\lib\site-packages\numba\cuda\tests\cudapy\test_atomics.py", line 234, in test_atomic_add_float_3
    cuda_atomic_add3 = cuda.jit('void(float32[:,:])')(atomic_add_float_3)
  File "C:\path\lib\site-packages\numba\cuda\decorators.py", line 103, in kernel_jit
    kernel.bind()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 586, in bind
    self._func.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 462, in get
    ptx = self.ptx.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 433, in get
    **self._extra_options)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 515, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 232, in compile
    self._try_error(err, 'Failed to compile\n')
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 250, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 140, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (62, 18): parse expected binary operation in atomicrmw
NVVM_ERROR_COMPILATION

======================================================================
ERROR: test_atomic_add_returns_old (numba.cuda.tests.cudapy.test_atomics.TestCudaAtomics)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\path\lib\site-packages\numba\cuda\tests\cudapy\test_atomics.py", line 489, in test_atomic_add_returns_old
    self._test_atomic_returns_old(kernel, 10)
  File "C:\path\lib\site-packages\numba\cuda\tests\cudapy\test_atomics.py", line 478, in _test_atomic_returns_old
    kernel[1, 1](x)
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 815, in __call__
    kernel = self.specialize(*args)
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 826, in specialize
    kernel = self.compile(argtypes)
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 845, in compile
    kernel.bind()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 586, in bind
    self._func.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 462, in get
    ptx = self.ptx.get()
  File "C:\path\lib\site-packages\numba\cuda\compiler.py", line 433, in get
    **self._extra_options)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 515, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 232, in compile
    self._try_error(err, 'Failed to compile\n')
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 250, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "C:\path\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 140, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (25, 17): parse expected binary operation in atomicrmw
NVVM_ERROR_COMPILATION

----------------------------------------------------------------------
```

**Comment by sklam** [comment]
Actually, this maybe a buildfarm issue

**Comment by sklam** [comment]
This has only occurred in the py3.7 build. Py3.8 and Py3.6 builds are fine.

**Comment by geeimabum** [comment]
@sklam, I am seeing what I believe is the same issue that you note above in both the Py3.7 and Py3.8 builds of Numba 0.50.1 on Windows.

Example:
```
import numpy as np
from numba import cuda

@cuda.jit
def test(array1):
    for i in range(len(array1)):
        cuda.atomic.add(array1, i, 1.)

if __name__ == "__main__":
    d_array1 = cuda.to_device(np.zeros(10, dtype=np.float32))

    test[1,1](d_array1)

    print(d_array1.copy_to_host())
```

results in error:

```
Traceback (most recent call last):
  File "C:/Users/timothy37400/AppData/Roaming/JetBrains/PyCharm2020.1/scratches/scratch_2.py", line 12, in <module>
    test[1,1](d_array1)
  File "C:\Miniconda\lib\site-packages\numba\cuda\compiler.py", line 833, in __call__
    kernel = self.specialize(*args)
  File "C:\Miniconda\lib\site-packages\numba\cuda\compiler.py", line 844, in specialize
    kernel = self.compile(argtypes)
  File "C:\Miniconda\lib\site-packages\numba\cuda\compiler.py", line 863, in compile
    kernel.bind()
  File "C:\Miniconda\lib\site-packages\numba\cuda\compiler.py", line 604, in bind
    self._func.get()
  File "C:\Miniconda\lib\site-packages\numba\cuda\compiler.py", line 480, in get
    ptx = self.ptx.get()
  File "C:\Miniconda\lib\site-packages\numba\cuda\compiler.py", line 451, in get
    **self._extra_options)
  File "C:\Miniconda\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 515, in llvm_to_ptx
    ptx = cu.compile(**opts)
  File "C:\Miniconda\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 232, in compile
    self._try_error(err, 'Failed to compile\n')
  File "C:\Miniconda\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 250, in _try_error
    self.driver.check_error(err, "%s\n%s" % (msg, self.get_log()))
  File "C:\Miniconda\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 140, in check_error
    raise exc
numba.cuda.cudadrv.error.NvvmError: Failed to compile

<unnamed> (32, 17): parse expected binary operation in atomicrmw
NVVM_ERROR_COMPILATION
```

If I switch to using np.int32 all is well. The above code works as expected with Numba 0.49.1

**Comment by gmarkall** [comment]
@geeimabum how did you install Numba and llvmlite?

**Comment by geeimabum** [comment]
@gmarkall, `conda install numba` and pulling from the conda-forge channel

**Comment by gmarkall** [comment]
@geeimabum Numba 0.50 depends on llvmlite 0.33, which switched to LLVM 9. With LLVM 9, a patch is required to stop it auto-upgrading atomic intrinsics when reading in IR (https://github.com/numba/llvmlite/pull/593), otherwise it converts them to a form that NVVM doesn't support (using the `atomicrmw` instruction). However, it looks like conda-forge did not build LLVM with this patch, and atomic operations on floats will be unusable with LLVM/llvmlite from conda-forge.

This will be fixed in Numba 0.51 so that it doesn't depend on the LLVM patch (see #6030) - in the meantime, can you use numba/llvmlite from the main channel?

**Comment by gmarkall** [comment]
Conda-forge issue opened: https://github.com/conda-forge/numba-feedstock/issues/55

**Comment by geeimabum** [comment]
@gmarkall I created a fresh environment from the main channel and I am still seeing the error.

```
# Name                    Version                   Build  Channel
blas                      1.0                         mkl
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py38_0
cudatoolkit               10.2.89              h74a9793_1
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2020.1                      216
libllvm9                  9.0.1                h21ff451_0
llvmlite                  0.33.0           py38ha925a31_0
mkl                       2020.1                      216
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.1.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
numba                     0.50.1           py38h47e9c7a_0
numpy                     1.18.5           py38h6530119_0
numpy-base                1.18.5           py38hc3f5095_0
openssl                   1.1.1g               he774522_0
pip                       20.1.1                   py38_1
python                    3.8.3                he1778fa_2
setuptools                49.2.0                   py38_0
six                       1.15.0                     py_0
sqlite                    3.32.3               h2a8f88b_0
tbb                       2020.0               h74a9793_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.34.2                   py38_0
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4
```

Is it possible that 0.50.1 on the main channel was also built without the patch?

It is not a problem for me to downgrade to 0.49.1 for the time being, especially if you believe this will not be an issue in 0.51.

**Comment by gmarkall** [comment]
Looking at the recipe for libllvm9-9.0.1-h21ff451_0, it does appear to have been built without the required patch. As an alternative to downgrading to 0.49.1, you could also install the packages from the numba channel, which don't appear to have this problem.

**Comment by geeimabum** [comment]
@gmarkall, that works! Thanks for the quick responses!

**Comment by gmarkall** [comment]
You're welcome - glad it works!
