### ISSUE TITLE
Bug: Argwhere returns `a` storage 

### ISSUE THREAD

**Issue by PhilipVinc** [numba/numba#5880]
## Reporting a bug

- [ x] I am using the latest released version of Numba (most recent is visible in
 the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x ] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

`np.argwhere` returns an object with storage type `a`, but this should not happen (I think), because non-numb numpy returns a standard array and the code works fine.

cc @gcarleo

Reproducer:
```python
>>> from numba import njit
>>> import numpy as np
>>> a=np.array([True, False, False, True, False])
>>> @njit
... def test(arr):
...   return np.argwhere(arr).reshape(-1)
...
>>> test(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
reshape() supports contiguous array only
- Resolution failure for non-literal arguments:
reshape() supports contiguous array only

During: resolving callee type: BoundFunction(array.reshape for array(int64, 2d, A))
During: typing of call at <stdin> (3)


File "<stdin>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by sklam** [comment]
This has to do with `np.transpose`

**Comment by likangk** [comment]
Hello, have you solve that problem? I also encountered this problem

**Comment by likangk** [comment]
> ## Reporting a bug
> * [ x] I am using the latest released version of Numba (most recent is visible in
>   the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
> * [x ] I have included below a minimal working reproducer (if you are unsure how
>   to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).
> 
> `np.argwhere` returns an object with storage type `a`, but this should not happen (I think), because non-numb numpy returns a standard array and the code works fine.
> 
> cc @gcarleo
> 
> Reproducer:
> 
> ```python
> >>> from numba import njit
> >>> import numpy as np
> >>> a=np.array([True, False, False, True, False])
> >>> @njit
> ... def test(arr):
> ...   return np.argwhere(arr).reshape(-1)
> ...
> >>> test(a)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
>     error_rewrite(e, 'typing')
>   File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
>     reraise(type(e), e, None)
>   File "/Users/filippovicentini/Documents/pythonenvs/1_Carleo_FFNN/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
>     raise value.with_traceback(tb)
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> - Resolution failure for literal arguments:
> reshape() supports contiguous array only
> - Resolution failure for non-literal arguments:
> reshape() supports contiguous array only
> 
> During: resolving callee type: BoundFunction(array.reshape for array(int64, 2d, A))
> During: typing of call at <stdin> (3)
> 
> 
> File "<stdin>", line 3:
> <source missing, REPL/exec in use?>
> ```
> 
> ```
> import numba
> >>> numba.__version__
> '0.50.0'
> ```

Hello, have you solve that problem? I also encountered this problem
