### ISSUE TITLE
numpy ediff1d tests have TypeError in `to_end` (numpy 1.19)

### ISSUE THREAD

**Issue by RizzerOnGitHub** [numba/numba#5929]
- [x] I have tried using the latest released version of Numba: 0.50.1
- [x] I have included below a minimal working reproducer

I'm seeing some errors in tests, building and running numba 0.50.1 on Debian unstable (python 3.8.3, numpy 1.19.0).

I'll focus on runtime test failures here (running tests on installed system, not build-time tests).  Runtime [tests](https://salsa.debian.org/science-team/numba/-/blob/debian/experimental/debian/tests/python3-numba) are triggered with `MPLBACKEND=Agg python3.8 -Wd -m numba.runtests -v -m` but the failing tests can be run manually. The second error isn't reproduced when I run the test (test_threading_concurrent_mix_use_masks_tbb in test_parallel_backend.py ) manually, so I'll just report the first, which is reproducible:

    python3 -m pytest -k "test_ediff1d_edge_cases" /usr/lib/python3/dist-packages/numba/tests/test_np_functions.py -v

The error summary is

    ======================================================================
    ERROR: test_ediff1d_edge_cases (numba.tests.test_np_functions.TestNPFunctions)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/numba/tests/test_np_functions.py", line 2045, in test_ediff1d_edge_cases
        _check_raises_type_error(params, 'to_begin')
      File "/usr/lib/python3/dist-packages/numba/tests/test_np_functions.py", line 2012, in _check_raises_type_error
        pyfunc(**params)
      File "/usr/lib/python3/dist-packages/numba/tests/test_np_functions.py", line 229, in ediff1d
        return np.ediff1d(ary, to_end, to_begin)
      File "<__array_function__ internals>", line 5, in ediff1d
      File "/usr/lib/python3/dist-packages/numpy/lib/arraysetops.py", line 107, in ediff1d
        raise TypeError("dtype of `to_end` must be compatible "
    TypeError: dtype of `to_end` must be compatible with input `ary` under the `same_kind` rule.

This is with numpy 1.19 which has only just been released, so I'm wonderful if it's an adjustment which numba needs to make in test_ediff1d_edge_cases to work with the new numpy.

**Comment by esc** [comment]
@RizzerOnGitHub thanks for reporting this. If this happens with Numpy 1.19 and not 1.18 then it is likely a change in Numpy that is causing the Numba tests to fail.

**Comment by stuartarchibald** [comment]
xref... reported issue: https://github.com/numpy/numpy/issues/13103 and patch that fixed https://github.com/numpy/numpy/pull/14981. NumPy 1.19 changelog https://github.com/numpy/numpy/releases/tag/v1.19.0 suggests this as the cause.

**Comment by esc** [comment]
I can reproduce this with the Numpy 1.19 wheel on PyPi. Doesn't happen with 1.18.

**Comment by stonebig** [comment]
see https://github.com/numba/numba/wiki/Minutes_2020_06_30

> #5929 - numpy ediff1d tests have TypeError in to_end (numpy 1.19)
> remove a patch we made to fix older numpy

**Comment by jakirkham** [comment]
Did anyone try this with NumPy 1.19.1? Is it still an issue there?

cc @mbargull

**Comment by RizzerOnGitHub** [comment]
Confirmed, still failing with numpy 1.91.1.

**Comment by stuartarchibald** [comment]
Brief history is (from memory so might not be spot on), there was a (what turned out to be) bug introduced NumPy 1.16 in the `ediff1d` function, Numba development found it and reported to NumPy. Numba replicated the behaviour as it wasn't clear it was a bug at the time. NumPy fixed the bug in 1.19. Numba doesn't match NumPy 1.19 `ediff1d` as a result.

**Comment by stuartarchibald** [comment]
I just tried writing the patch to make this work and discovered https://github.com/numpy/numpy/pull/17457
