### ISSUE TITLE
Unification error for datetimes (minimum/maximum)

### ISSUE THREAD

**Issue by AA-Turner** [numba/numba#5932]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

Checked the docs and GH issues and can't find anything similar after a quick search.

conda list produces for numpy/numba:
```
numba                     0.49.1           py38h47e9c7a_0
numpy                     1.18.5           py38h6530119_0
numpy-base                1.18.5           py38hc3f5095_0
```

### Minimum Workable Example
```
import numpy as np
import numba

@numba.njit
def test(a, b, some_condition):
    if some_condition:
        x = a
    else:
        x = np.minimum(a, b)

    return x

test(np.datetime64("2000-01-01"), np.datetime64("2020-06-29"), False)
```

This produces the following error:
```
Cannot unify datetime64[] and datetime64[D] for 'x.2'

def test(a, b, some_condition):
    <source elided>

    return x
    ^
```
## Expected outcome
I would expect the smallest datetime (or largest for np.maximum) to be returned. For integers the test works great so what I think is happening is that np.minimum discards some metadata of the dtype, though I'm not entirely clear on how to fix this (e.g. if I use np.minimum(a, b).astype("datetime64[D]") I get a new error `Unknown attribute 'astype' of type datetime64[]`). 

## Full traceback

<details>
<summary>Traceback details</summary>

test(np.datetime64("1700-01-01"), np.datetime64("2000-01-01"), False)
Traceback (most recent call last):
  File "<...>\lib\site-packages\numba\core\dispatcher.py", line 401, in _compile_for_args
    error_rewrite(e, 'typing')
  File "<...>\lib\site-packages\numba\core\dispatcher.py", line 344, in error_rewrite
    reraise(type(e), e, None)
  File "<...>\lib\site-packages\numba\core\utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Cannot unify datetime64[] and datetime64[D] for 'x.2', defined at <...>/scratch.py (691)

File "scratch.py", line 691:
def test(a, b, some_condition):
    <source elided>

    return x
    ^

[1] During: typing of assignment at <...>/scratch.py (691)

File "M1Code.py", line 691:
def test(a, b, some_condition):
    <source elided>

    return x
    ^
</details>

**Comment by AA-Turner** [comment]
Conda isn't giving me Numba 0.50.1 with either `conda update --all` or `conda install -c numba numba` so I will try a new environment in a short while

**Comment by esc** [comment]
@AA-Turner thanks for submitting this, I can confirm I am able to reproduce this on this mornings master `0.51.0dev0-122-g9ce5c30d32`. It seems like it might be a bug in Numpy and I do agree with your initial guess.
