### ISSUE TITLE
ndarray.flags.writeable = False for structured array compiles/silently fails to assign with njit

### ISSUE THREAD

**Issue by nelson2005** [numba/numba#5950]
I'd have expected some kind of error, either compile-time or run-time with the following code:

```python
import numpy as np
from numba import njit
cb_type = np.dtype([('a', np.int32), ])
types = np.zeros(1, dtype=cb_type)
types[0]['a'] = 4
types.flags.writeable = False
print(types)

@njit
def set_val():
    types[0]['a'] = 3

set_val()
print(types)
```
Instead, the assignment appears to be silently ignored, resulting in output of
```
[(4,)]
[(4,)]
```

Running as plain-python produces the expected exception:
```
ValueError: assignment destination is read-only
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This is bug.

**Comment by pfheatwole** [comment]
Similarly, passing a read-only array with a structured dtype (or a read-only view of a writeable array with a structured dtype) as an argument will silently corrupt:

``` python
import numpy as np
from numba import njit

@njit
def set_val(arr):
    arr[0]['a'] = 1

z = np.zeros(1, dtype=[('a', int)])
z.flags.writeable = False
set_val(z)
print(z)
```

### Expected behavior

Without `@njit`, numpy correctly fails with:

```
Traceback (most recent call last):
  File "/home/peter/broken_numba.py", line 12, in <module>
    set_val(z)
  File "/home/peter/broken_numba.py", line 7, in set_val
    arr[0]['a'] = 1
ValueError: assignment destination is read-only
```

### Actual behavior

With `@njit`, numba incorrectly writes to the array and the output is `[(1,)]`.
