### ISSUE TITLE
Intel TBB is required, no threading layer could be loaded, however TBB is already installed

### ISSUE THREAD

**Issue by Runkli** [numba/numba#5982]
Using Numba 0.50.1, and Python 3.8.2, here is the code causing the bug:
```
from numba import config, njit, threading_layer
import numpy as np

# set the threading layer before any parallel target compilation
config.THREADING_LAYER = 'tbb'

@njit(parallel=True)
def foo(a, b):
	return a + b
x = np.arange(10.)
y = x.copy()

foo(x, y)
# demonstrate the threading layer chosen
print("Threading layer chosen: %s" % threading_layer())
```

Which gives me the error
```
Traceback (most recent call last):
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/errors.py", line 745, in new_error_context
    yield
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 273, in lower_block
    self.lower_inst(inst)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 486, in lower_inst
    func(self, inst)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/parfors/parfor_lowering.py", line 271, in _lower_parfor_parallel
    call_parallel_gufunc(
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/parfors/parfor_lowering.py", line 1398, in call_parallel_gufunc
    _launch_threads()
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 486, in _launch_threads
    raise_with_hint(requirements)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 431, in raise_with_hint
    raise ValueError(errmsg % hint)
ValueError: No threading layer could be loaded.
HINT:
Intel TBB is required, try:
$ conda/pip install tbb

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 17, in <module>
    foo(x, y)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 434, in _compile_for_args
    raise e
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 367, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 808, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 78, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 92, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 105, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 603, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 339, in compile_extra
    return self._compile_bytecode()
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 401, in _compile_bytecode
    return self._compile_core()
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 381, in _compile_core
    raise e
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 372, in _compile_core
    pm.run(self.state)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 370, in run_pass
    lower.lower()
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 179, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 233, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 259, in lower_function_body
    self.lower_block(block)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 273, in lower_block
    self.lower_inst(inst)
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/errors.py", line 752, in new_error_context
    reraise(type(newerr), newerr, tb)
  File "/home/ilknull/.local/lib/python3.8/site-packages/numba/core/utils.py", line 81, in reraise
    raise value
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
No threading layer could be loaded.
HINT:
Intel TBB is required, try:
$ conda/pip install tbb

File "test.py", line 10:
def foo(a, b):
	return a + b
 ^

During: lowering "id=0[LoopNest(index_variable = parfor_index.8, range = (0, a_size0.1, 1))]{1: <ir.Block at test.py (10)>}Var(parfor_index.8, test.py:10)" at test.py (10)
```

However, ```pip3 install tbb``` produces:
```
Requirement already satisfied: tbb in /home/ilknull/.local/lib/python3.8/site-packages (2020.0.133)
```
Any ways I could fix this issue? I'm not sure what is happening, I also used ```pip3 install numba``` to install Numba. Much appreciated

**Comment by sklam** [comment]
Can you paste the output of `numba -s`? It will help us diagnose the problem. Note: you may want to review the output in case it contains information that you find to be sensitive.

**Comment by Runkli** [comment]
Output I get is the following:
```
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2020-07-14 00:02:20.999070
UTC start time                                : 2020-07-13 20:02:20.999075
Running time (s)                              : 1.138761

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : sandybridge
CPU Count                                     : 4
Number of accessible CPUs                     : 4
List of accessible CPUs cores                 : 0 1 2 3
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit aes avx cmov cx16 cx8 fxsr
                                                mmx pclmul popcnt sahf sse sse2
                                                sse3 sse4.1 sse4.2 ssse3 xsave
                                                xsaveopt

Memory Total (MB)                             : 15996
Memory Available (MB)                         : 13142

__OS Information__
Platform Name                                 : Linux-5.4.0-40-generic-x86_64-with-glibc2.29
Platform Release                              : 5.4.0-40-generic
OS Name                                       : Linux
OS Version                                    : #44-Ubuntu SMP Tue Jun 23 00:01:04 UTC 2020
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31

__Python Information__
Python Compiler                               : GCC 9.3.0
Python Implementation                         : CPython
Python Version                                : 3.8.2
Python Locale                                 : en_US.UTF-8

__LLVM Information__
LLVM Version                                  : 9.0.1

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : 10020
CUDA Detect Output:
Found 1 CUDA devices
id 0    b'GeForce GTX 1050 Ti'                              [SUPPORTED]
                      compute capability: 6.1
                           pci device id: 0
                              pci bus id: 1
Summary:
	1/1 devices are supported

CUDA Librairies Test Output:
Finding cublas from <unknown>
	named  libcublas.so
	trying to open library...	ERROR: failed to open cublas:
libcublas.so: cannot open shared object file: No such file or directory
Finding cusparse from <unknown>
	named  libcusparse.so
	trying to open library...	ERROR: failed to open cusparse:
libcusparse.so: cannot open shared object file: No such file or directory
Finding cufft from <unknown>
	named  libcufft.so
	trying to open library...	ERROR: failed to open cufft:
libcufft.so: cannot open shared object file: No such file or directory
Finding curand from <unknown>
	named  libcurand.so
	trying to open library...	ERROR: failed to open curand:
libcurand.so: cannot open shared object file: No such file or directory
Finding nvvm from <unknown>
	named  libnvvm.so
	trying to open library...	ERROR: failed to open nvvm:
libnvvm.so: cannot open shared object file: No such file or directory
Finding libdevice from <unknown>
	searching for compute_20...	ERROR: can't open libdevice for compute_20
	searching for compute_30...	ERROR: can't open libdevice for compute_30
	searching for compute_35...	ERROR: can't open libdevice for compute_35
	searching for compute_50...	ERROR: can't open libdevice for compute_50


__ROC information__
ROC Available                                 : False
ROC Toolchains                                : None
HSA Agents Count                              : 0
HSA Agents:
None
HSA Discrete GPUs Count                       : 0
HSA Discrete GPUs                             : None

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : False
+--> Disabled due to Unknown import problem.
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.

__Installed Packages__
Package                   Version       
------------------------- --------------
alabaster                 0.7.8         
alembic                   1.4.2         
apturl                    0.5.2         
astroid                   2.3.3         
attrs                     19.3.0        
azure-core                1.6.0         
azure-storage-blob        12.3.2        
Babel                     2.6.0         
backcall                  0.1.0         
bcrypt                    3.1.7         
bleach                    3.1.1         
blinker                   1.4           
Brlapi                    0.7.0         
certifi                   2019.11.28    
chardet                   3.0.4         
click                     7.1.2         
cloudpickle               1.3.0         
command-not-found         0.3           
cryptography              2.8           
cupshelpers               1.0           
databricks-cli            0.11.0        
dbus-python               1.2.16        
decorator                 4.4.2         
defer                     1.0.6         
defusedxml                0.6.0         
distro                    1.4.0         
distro-info               0.23ubuntu1   
docker                    4.2.2         
docutils                  0.16          
duplicity                 0.8.12.0      
entrypoints               0.3           
fasteners                 0.14.1        
Flask                     1.1.2         
future                    0.18.2        
gitdb                     4.0.5         
GitPython                 3.1.3         
gorilla                   0.3.0         
gpg                       1.13.1-unknown
gunicorn                  20.0.4        
html5lib                  1.0.1         
httplib2                  0.14.0        
hydra-core                0.11.3        
idna                      2.8           
imagesize                 1.2.0         
importlib-metadata        1.5.0         
ipykernel                 5.2.0         
ipython                   7.13.0        
ipython-genutils          0.2.0         
isodate                   0.6.0         
isort                     4.3.4         
itsdangerous              1.1.0         
jedi                      0.15.2        
Jinja2                    2.10.1        
jsonschema                3.2.0         
jupyter-client            6.1.2         
jupyter-core              4.6.3         
keyring                   18.0.1        
language-selector         0.1           
launchpadlib              1.10.13       
lazr.restfulclient        0.14.2        
lazr.uri                  1.0.3         
lazy-object-proxy         1.4.3         
llvmlite                  0.33.0        
lockfile                  0.12.2        
logilab-common            1.4.3         
louis                     3.12.0        
macaroonbakery            1.3.1         
Mako                      1.1.0         
MarkupSafe                1.1.0         
mccabe                    0.6.1         
mistune                   0.8.4         
mlflow                    1.9.1         
mock                      3.0.5         
monotonic                 1.5           
more-itertools            4.2.0         
mpi4py                    3.0.3         
msrest                    0.6.17        
nbconvert                 5.6.1         
nbformat                  5.0.4         
netifaces                 0.10.4        
numba                     0.50.1        
numpy                     1.19.0        
numpydoc                  0.7.0         
oauthlib                  3.1.0         
olefile                   0.46          
omegaconf                 1.4.1         
packaging                 20.3          
pandas                    1.0.5         
pandocfilters             1.4.2         
paramiko                  2.6.0         
parso                     0.5.2         
pbr                       5.4.5         
pexpect                   4.6.0         
pickleshare               0.7.5         
Pillow                    7.0.0         
pip                       20.0.2        
prometheus-client         0.8.0         
prometheus-flask-exporter 0.14.1        
prompt-toolkit            2.0.10        
protobuf                  3.6.1         
psutil                    5.5.1         
pycairo                   1.16.2        
pycodestyle               2.5.0         
pycups                    1.9.73        
pyflakes                  2.1.1         
Pygments                  2.3.1         
PyGObject                 3.36.0        
PyJWT                     1.7.1         
pylint                    2.4.4         
pymacaroons               0.13.0        
PyNaCl                    1.3.0         
pyparsing                 2.4.6         
PyQt5                     5.14.1        
pyRFC3339                 1.1           
pyrsistent                0.15.5        
PySocks                   1.6.8         
pysvn                     1.9.9         
python-apt                2.0.0         
python-dateutil           2.7.3         
python-debian             0.1.36ubuntu1 
python-editor             1.0.4         
pytz                      2019.3        
pyxdg                     0.26          
PyYAML                    5.3.1         
pyzmq                     18.1.1        
QtAwesome                 0.4.4         
qtconsole                 4.6.0         
QtPy                      1.9.0         
querystring-parser        1.2.4         
reportlab                 3.5.34        
requests                  2.22.0        
requests-oauthlib         1.3.0         
requests-unixsocket       0.2.0         
roman                     2.0.0         
rope                      0.10.5        
screen-resolution-extra   0.0.0         
SecretStorage             2.3.1         
setuptools                45.2.0        
simplejson                3.16.0        
sip                       4.19.21       
six                       1.14.0        
smmap                     3.0.4         
Sphinx                    1.8.5         
spyder                    3.3.6         
spyder-kernels            0.5.2         
SQLAlchemy                1.3.13        
sqlparse                  0.3.1         
systemd-python            234           
tabulate                  0.8.7         
tbb                       2020.0.133    
testpath                  0.4.4         
tornado                   5.1.1         
traitlets                 4.3.3         
ubuntu-advantage-tools    20.3          
ubuntu-drivers-common     0.0.0         
ufw                       0.36          
unattended-upgrades       0.1           
urllib3                   1.25.8        
usb-creator               0.3.7         
wadllib                   1.3.3         
wcwidth                   0.1.8         
webencodings              0.5.1         
websocket-client          0.57.0        
Werkzeug                  1.0.1         
wheel                     0.34.2        
wrapt                     1.11.2        
xkit                      0.0.0         
zipp                      1.0.0         

No errors reported.


__Warning log__
Warning (roc): Error initialising ROC: No ROC toolchains found.
Warning (roc): No HSA Agents found, encountered exception when searching: Error at driver init: 
NUMBA_HSA_DRIVER /opt/rocm/lib/libhsa-runtime64.so is not a valid file path.  Note it must be a filepath of the .so/.dll/.dylib or the driver:
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda'
```

**Comment by sklam** [comment]
I tested on a ubuntu with `Linux-4.4.0-87-generic-x86_64-with-glibc2.10` and I couldn't replicate the problem.

My steps:

- make new bare python=3.8 environment with conda
- `pip install numba==0.50.1` 
- `pip install tbb==2020.0.133`
- run the provided code

It is also odd that `numba -s` is able to load TBB but the provided script could not:

```
__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
```

**Comment by Runkli** [comment]
This was using pip, I did everything on Conda and it turned out fine, maybe it was just some path problem that pip caused

**Comment by esc** [comment]
@Runkli thanks for following up on this, I'll close the issue now as it appears to be resolved. If that is not the case, please feel free to re-open.

**Comment by JeppeDruedahl** [comment]
I have a similar problem. I have installed Anaconda3-2020.07-Windows-x86_64 (Python 3.8.3) on two computers. TBB is installed and running `numba -s` it is recognized. But I still get the error when setting the threading layer to 'tbb'.

**Comment by HugoStrand** [comment]
Hi! I have the same issue. I am using 
```
tbb @2020.3_0 
py38-numba @0.52.0_0+tbb
```
installed using Macports.

When running python from command line the `tbbpool` backend can be loaded without any problems
```
$ python -c "from numba.np.ufunc import tbbpool as lib; print(dir(lib))"
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'add_task', 'do_scheduling_signed', 'do_scheduling_unsigned', 'get_num_threads', 'get_thread_id', 'launch_threads', 'parallel_for', 'ready', 'set_num_threads', 'synchronize']
```
But when trying to compile a simple parallell example 
```python
import numpy as np
import numba as nb

nb.config.THREADING_LAYER = 'tbb'

@nb.jit((nb.float64[::1],), cache=False, nopython=True, parallel=True)
def test_numba_prange(A_i):
    for i in nb.prange(len(A_i)):
        A_i[i] += i

test_numba_prange(np.zeros(100))
```
it breaks on the same import (when the import is done in `./numba/np/ufunc/parallel.py`)
```
$ python test_numba_tbb.py
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/core/lowering.py", line 443, in lower_inst
    func(self, inst)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/parfors/parfor_lowering.py", line 292, in _lower_parfor_parallel
    call_parallel_gufunc(
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/parfors/parfor_lowering.py", line 1439, in call_parallel_gufunc
    _launch_threads()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 497, in _launch_threads
    raise_with_hint(requirements)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numba/np/ufunc/parallel.py", line 442, in raise_with_hint
    raise ValueError(errmsg % hint)
ValueError: No threading layer could be loaded.
HINT:
Intel TBB is required, try:
$ conda/pip install tbb
```
even though `numba --sysinfo` (which also just test that the above import works) says that `tbb` is available
```
$ numba-3.8 --sysinfo
...
__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
```
it seems like the `numba` backend compilation is not using the same environment as my command line python and that (possibly due to missing librarypaths?) importing `tbbpool` breaks only during the compilation stage?

Is it possible to control the environment of the numba compilation stage somehow?

**Comment by HugoStrand** [comment]
I figured out the problem. The error message is incorrect because of a bug in the function `_launch_threads()` in `./numba/np/ufunc/parallel.py`.

If as in my case the `libtbb.dylib` is not in the library path, an exception is (correctly) raised by the function `_check_tbb_version_compatible()`. However, it is silently suppressed in `_launch_threads()` in favor of the `ValueError: No threading layer could be loaded.` exception that is raised instead.

Setting my `LD_LIBRARY_PATH` correctly solves the problem.

Fixing the bug, so that the more informative exception is raised (instead of being silenced) would of course be nicer.

However, this will require fixing the rather involved way errors are handled in `parallel.py`. Just checking if loading succeeded by doing `if lib is None:` as is done now is not sufficient. (handling multiple error cases is what exceptions are for, how about using them?)

The library `ImportError` due to wrong library paths 
```ImportError: Problem with TBB. Reason: dlopen(libtbb.dylib, 6): image not found```
is suppressed here
https://github.com/numba/numba/blob/master/numba/np/ufunc/parallel.py#L394

and poor mans exception handling is done here
https://github.com/numba/numba/blob/master/numba/np/ufunc/parallel.py#L498

giving a general non informative error 
```ValueError: No threading layer could be loaded.```
here
https://github.com/numba/numba/blob/master/numba/np/ufunc/parallel.py#L498

**Comment by stuartarchibald** [comment]
@HugoStrand Could you perhaps open a new issue about this please? The code as-is is to handle common problems in practice, patches to add improvements for dealing with diagnosing new problems are welcomed. This is possibly related https://github.com/numba/numba/issues/6108.
