### ISSUE TITLE
Cache Fails When Cannot Find Unrelated Custom Definitions 

### ISSUE THREAD

**Issue by DannyWeitekamp** [numba/numba#6018]
- [x] I have tried using the latest released version of Numba (0.50.1).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

When reading cached njitted functions it seems numba will try to load every overload it has encountered so far even if that overload is unrelated to the current execution of the function. When only using predefined types this works just fine, but user defined types like NamedTuples and jitclasses (I imagine there are others too), break this behavior in a way that is pretty confusing to the end user. Consider the following situation: 
1. The user defines a new custom type and uses it in an cache=True function
2. The user adds another custom type and uses it with the same function 
3. The user deletes the first custom type and runs their function again with the second type
4. The user gets an unpickling error because the overload associated with the first custom type cannot be resolved, even though it isn't being used.

Here is a reproducing example: `rep_cache_bug.py`
```python
import os,sys
from numba import njit
from numba.typed import List

do_both = len(sys.argv) > 1 and sys.argv[1] == "both"

@njit(cache=True)
def add_values(l):
	v = 0
	for x in l:
		v += x.value
	return v

store_code = '' + \
'from numba.core.types import NamedTuple, float64, unicode_type \n' + \
'from collections import namedtuple \n' + \
'Store = namedtuple("Store", ["name", "owner", "value"]) \n' + \
'Store_NT = NamedTuple([unicode_type,unicode_type,float64],Store) \n' 

shop_code = '' + \
'from numba.core.types import NamedTuple, float64, unicode_type \n'+  \
'from collections import namedtuple \n' + \
'Shop = namedtuple("Shop", ["name", "owner", "value"]) \n' + \
'Shop_NT = NamedTuple([unicode_type,unicode_type,float64],Shop) \n' 


with open("store.py", 'w') as f:
	f.write(store_code)

from store import Store, Store_NT 
stores = List.empty_list(Store_NT)
stores.append(Store("Franks", "Frank", 100.0))
stores.append(Store("Gems n stuff", "Alice", 600.0))

print(add_values(stores))
os.remove("store.py")

if(do_both):
	with open("shop.py", 'w') as f:
		f.write(shop_code)

	from shop import Shop, Shop_NT 
	shops = List.empty_list(Shop_NT)
	shops.append(Shop("Franks", "Frank", 100.0))
	shops.append(Shop("Gems n stuff", "Alice", 600.0))	

	print(add_values(shops))
	os.remove("shop.py")
```

First run
`python rep_cache_bug.py both`
Second run
`python rep_cache_bug.py`
Error
```
Traceback (most recent call last):
  File "rep_cache_bug.py", line 35, in <module>
    print(add_values(stores))
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 436, in _compile_for_args
    raise e
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 369, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 798, in compile
    cres = self._cache.load_overload(sig, self.targetctx)
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/caching.py", line 648, in load_overload
    return self._load_overload(sig, target_context)
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/caching.py", line 655, in _load_overload
    data = self._cache_file.load(key)
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/caching.py", line 497, in load
    overloads = self._load_index()
  File "/home/danny/.local/lib/python3.8/site-packages/numba/core/caching.py", line 525, in _load_index
    stamp, overloads = pickle.loads(data)
ModuleNotFoundError: No module named 'shop'
```

**Comment by esc** [comment]
@DannyWeitekamp thanks for reporting this issue. I can confirm I am able to reproduce this. I imagine the custom types are stored within the signature of the function which is pickled alongside the function itself.

**Comment by esc** [comment]
@stuartarchibald @sklam I am not sure we can do much in this case, I don't really see a way to load the types lazily, do you?

**Comment by esc** [comment]
Perhaps we could check for a `ModuleNotFound` exception and then prune the corresponding signature?

**Comment by esc** [comment]
Further thoughts on this:

* need to check if Python w/o Numba can do this using just NamedTuple
* perhaps cloudpickl could help?

**Comment by stuartarchibald** [comment]
This doesn't reproduce under 0.51.2.
```
$ rm __pycache__/*


$ cat issue6018.py
import os,sys
from numba import njit
from numba.typed import List

do_both = len(sys.argv) > 1 and sys.argv[1] == "both"

@njit#(cache=True)
def add_values(l):
        v = 0
        for x in l:
                v += x.value
        return v

store_code = '' + \
'from numba.core.types import NamedTuple, float64, unicode_type \n' + \
'from collections import namedtuple \n' + \
'Store = namedtuple("Store", ["name", "owner", "value"]) \n' + \
'Store_NT = NamedTuple([unicode_type,unicode_type,float64],Store) \n'

shop_code = '' + \
'from numba.core.types import NamedTuple, float64, unicode_type \n'+  \
'from collections import namedtuple \n' + \
'Shop = namedtuple("Shop", ["name", "owner", "value"]) \n' + \
'Shop_NT = NamedTuple([unicode_type,unicode_type,float64],Shop) \n'


with open("store.py", 'w') as f:
        f.write(store_code)

from store import Store, Store_NT
stores = List.empty_list(Store_NT)
stores.append(Store("Franks", "Frank", 100.0))
stores.append(Store("Gems n stuff", "Alice", 600.0))

print(add_values(stores))
os.remove("store.py")

if(do_both):
        with open("shop.py", 'w') as f:
                f.write(shop_code)

        from shop import Shop, Shop_NT
        shops = List.empty_list(Shop_NT)
        shops.append(Shop("Franks", "Frank", 100.0))
        shops.append(Shop("Gems n stuff", "Alice", 600.0))

        print(add_values(shops))
        os.remove("shop.py")

$ python issue6018.py "both"
700.0
700.0


$ python issue6018.py
700.0


$ NUMBA_DISABLE_JIT=1 python issue6018.py
700.0
```
think all the work on caching improvements/robustness fixed it.

**Comment by DannyWeitekamp** [comment]
@stuartarchibald I still get this error. Just updated to 0.51.2, and double checked by printing numba.__version__.  It's odd that it is working just fine for you, but not for me.

**Comment by esc** [comment]
@DannyWeitekamp did you do this from a new conda/virtualenv environment? We have had issues in the past with multiple versions installed in the same env.

**Comment by DannyWeitekamp** [comment]
@esc I just tried again on a virtualenv, and again on a remote server. Both times I got the error. Machines are Ubuntu 18 and 20 respectively.

**Comment by esc** [comment]
@esc thanks for trying this, that is very strange indeed.

**Comment by esc** [comment]
I will open this again, as it appears to not be resolved.
