### ISSUE TITLE
Floating-point bit twiddling in CUDA

### ISSUE THREAD

**Issue by zhihaoy** [numba/numba#6026]
## Feature request

I need to use `view` individual floating-point numbers as integers and backwards.  For example:
```python
np.array(np.array(23.65).view('i8') | 1).view('d').item()
```
should give `23.650000000000002` in CUDA device functions.

I also need to use `frexp` and `ldexp` in CUDA device functions.

**Comment by zhihaoy** [comment]
```python
@cuda.jit(device=True)
def foo(val):
    return np.float64(val).view(np.int64)

@cuda.jit
def bar(v):
    print(foo(v))

bar[1,1](10.)
```

#3763 (view on scalars) doesn't work for GPU target either.

**Comment by esc** [comment]
@zhihaoy thanks for submitting this, I have labelled it as a feature request accordingly.

**Comment by gmarkall** [comment]
This also appears not to work in nopython mode:

```python
from numba import cuda, njit
import numpy as np


@njit
def f():
    return np.array(np.array(23.65).view('i8') | 1).view('d').item()

print(f())
```

gives:

```
Traceback (most recent call last):
  File "repro.py", line 9, in <module>
    print(f())
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/home/gmarkall/numbadev/numba/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of BoundFunction(array.view for array(float64, 0d, C)) with parameters (Literal[str](i8))

During: resolving callee type: BoundFunction(array.view for array(float64, 0d, C))
During: typing of call at repro.py (7)


File "repro.py", line 7:
def f():
    return np.array(np.array(23.65).view('i8') | 1).view('d').item()
    ^
```

or for scalars:

```python
from numba import cuda, njit
import numpy as np


@njit
def f():
    return (np.float64(23.65).view('i8') | 1).view('d')

print(f())
```

gives:

```
Traceback (most recent call last):
  File "repro2.py", line 9, in <module>
    print(f())
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/home/gmarkall/numbadev/numba/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function scalar_view at 0x7fcc4a32b040>) found for signature:

 >>> scalar_view(float64, Literal[str](i8))

There are 4 candidate implementations:
   - Of which 4 did not match due to:
   Overload of function 'scalar_view': File: <numerous>: Line N/A.
     With argument(s): '(float64, Literal[str](i8))':
    No match.

- Resolution failure for non-literal arguments:
No implementation of function Function(<function scalar_view at 0x7fcc4a32b040>) found for signature:

 >>> scalar_view(float64, unicode_type)

There are 4 candidate implementations:
    - Of which 4 did not match due to:
    Overload of function 'scalar_view': File: <numerous>: Line N/A.
      With argument(s): '(float64, unicode_type)':
     No match.


During: resolving callee type: BoundFunction((<class 'numba.core.types.scalars.Float'>, 'view') for float64)
During: typing of call at repro2.py (7)
```

**Comment by zhihaoy** [comment]
> This also appears not to work in nopython mode:
> 

Passing string literal to `.view` doesn't work, passing types do:

```python
@njit
def foo(val):
    return np.float64(val).view(np.int64)
```

**Comment by gmarkall** [comment]
> I also need to use `frexp` and `ldexp` in CUDA device functions.

@zhihaoy You can use the code in https://numba.discourse.group/t/cuda-building-extensions-to-call-libdevice-functions-cube-root-example/140 as a starting point for making a Numba extension to call `__nv_ldexp` and `__nv_frexp` as a workaround for now - if you modify the names of the functions (and the Python implementation of `cbrt` so that it is `ldexp` / `frexp`) then that should give you `ldexp` and `frexp` functions you can call from CUDA kernels.

**Comment by zhihaoy** [comment]
Libdevice functions `__nv_float_as_int`, `__nv_longlong_as_double` etc. can be used for implementing the scalar `view`.  But after I've done typing, I couldn't find a way to register the lowering function.  I wrote a decl module with:

```python
@infer_attr
class FloatAttribute(AttributeTemplate):
    key = types.Float

    @bound_function('scalar.view')
    def resolve_view(self, n, args, kws):
        assert not kws
        ty, = args
        R = ty.dtype
        if R.is_precise() and n.bitwidth == R.bitwidth:
            return signature(R, types.Any)
        else:
            raise errors.TypingError(
                "Float can only be viewed as integers of the same size")
```

Then in an impl module I did:

```python
def view_implement(nvname):
    def core(context, builder, sig, args):
        ty, _ = sig.args
        R = context.get_value_type(sig.return_type)
        T = context.get_value_type(ty)
        fnty = Type.function(R, [T])
        fn = builder.module.get_or_insert_function(fnty, name=nvname)
        return builder.call(fn, (args[0],))

    return core


for ty, nvname in ((types.float32, '__nv_float_as_int'),
                   (types.float64, '__nv_double_as_longlong'),
                   (types.int32, '__nv_int_as_float'),
                   (types.int64, '__nv_longlong_as_double')):
    lower('scalar.view', ty, types.DTypeSpec)(view_implement(nvname))
```

But the "scalar.view" function still couldn't be looked up:

```
No definition for lowering scalar.view(float32, any) -> int32

File "numba\cuda\tests\cudapy\test_intrinsics.py", line 114:
def simple_view_i4(ary, n):
    ary[0] = np.float32(n).view(np.int32)
    ^

During: lowering "$16call_method.7 = call $10load_method.4($14load_attr.6, func=$10load_method.4, args=[Var($14load_attr.6, test_intrinsics.py:114)], kws=(), vararg=None)" at
```

Help wanted.

**Comment by gmarkall** [comment]
@zhihaoy Could you push your changes so far to a branch please? That would make it a bit easier to fiddle around with to see what the right thing to do here is.

**Comment by zhihaoy** [comment]
> @zhihaoy Could you push your changes so far to a branch please? That would make it a bit easier to fiddle around with to see what the right thing to do here is.

Here it is https://github.com/zhihaoy/numba/commit/57a465c26615363ae6608996dae604800b575d02

**Comment by gmarkall** [comment]
@zhihaoy Just to let you know I do still have this on my to-do list. When I took a brief look the other day, I noticed that the lowering doesn't match because the typing types the argument as `types.Any`: https://github.com/zhihaoy/numba/commit/57a465c26615363ae6608996dae604800b575d02#diff-a4c8bfad8504b6079f6838c4d80b3941R19

However the lowering is for a `DTypeSpec` argument: https://github.com/zhihaoy/numba/commit/57a465c26615363ae6608996dae604800b575d02#diff-dc2c32327b1e66a7a00752003be303cfR25

Even if you pass a dtype in your code, the `Any` won't get specialized into a `DTypeSpec` - the signature will remain as-is (as `(float32, any) -> int32)` throughout the pipeline.

I haven't yet determined the exact right way to go here (mainly because of time constraints) - however, if this is enough info to go on and allow you to proceed, then great! If not, let me know and I'll look into a more precise suggestion.

**Comment by zhihaoy** [comment]
> @zhihaoy Just to let you know I do still have this on my to-do list. When I took a brief look the other day, I noticed that the lowering doesn't match because the typing types the argument as `types.Any`: [zhihaoy@57a465c#diff-a4c8bfad8504b6079f6838c4d80b3941R19](https://github.com/zhihaoy/numba/commit/57a465c26615363ae6608996dae604800b575d02#diff-a4c8bfad8504b6079f6838c4d80b3941R19)
> 
> However the lowering is for a `DTypeSpec` argument: [zhihaoy@57a465c#diff-dc2c32327b1e66a7a00752003be303cfR25](https://github.com/zhihaoy/numba/commit/57a465c26615363ae6608996dae604800b575d02#diff-dc2c32327b1e66a7a00752003be303cfR25)

I changed it to `Any` because `DTypeSpec` doesn't work here:

```
Traceback (most recent call last):
  File "C:\Users\zy\devel\numba\numba\core\base.py", line 712, in cast
    impl = self._casts.find((fromty, toty))
  File "C:\Users\zy\devel\numba\numba\core\base.py", line 49, in find
    out = self._find(sig)
  File "C:\Users\zy\devel\numba\numba\core\base.py", line 58, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.core.base.OverloadSelector object at 0x000001E782A56A30>, (class(int32), <class 'numba.core.types.abstract.DTypeSpec'>))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zy\devel\numba\numba\core\errors.py", line 745, in new_error_context
    yield
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 327, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 501, in lower_assign
    return self.lower_expr(ty, value)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 1026, in lower_expr
    res = self.lower_call(resty, expr)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 763, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 986, in _lower_call_normal
    argvals = self.fold_call_args(
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 682, in fold_call_args
    argvals = [self._cast_var(var, sigty)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 682, in <listcomp>
    argvals = [self._cast_var(var, sigty)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 665, in _cast_var
    return self.context.cast(self.builder, val, varty, ty)
  File "C:\Users\zy\devel\numba\numba\core\base.py", line 715, in cast
    raise NotImplementedError(
NotImplementedError: Cannot cast class(int32) to <class 'numba.core.types.abstract.DTypeSpec'>: %".51" = load i8*, i8** %"$14load_attr.6"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\zy\devel\numba\numba\cuda\tests\cudapy\test_intrinsics.py", line 386, in test_view_f4_to_i4
    compiled = cuda.jit("void(int32[:], float32)")(simple_view_i4)
  File "C:\Users\zy\devel\numba\numba\cuda\decorators.py", line 136, in kernel_jit
    return Dispatcher(func, sigs, bind=bind, targetoptions=targetoptions)
  File "C:\Users\zy\devel\numba\numba\cuda\compiler.py", line 804, in __init__
    self.compile(sigs[0])
  File "C:\Users\zy\devel\numba\numba\cuda\compiler.py", line 916, in compile
    kernel = compile_kernel(self.py_func, argtypes,
  File "C:\Users\zy\devel\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\zy\devel\numba\numba\cuda\compiler.py", line 57, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "C:\Users\zy\devel\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\zy\devel\numba\numba\cuda\compiler.py", line 40, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "C:\Users\zy\devel\numba\numba\core\compiler.py", line 625, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\zy\devel\numba\numba\core\compiler.py", line 361, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\zy\devel\numba\numba\core\compiler.py", line 423, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\zy\devel\numba\numba\core\compiler.py", line 403, in _compile_core
    raise e
  File "C:\Users\zy\devel\numba\numba\core\compiler.py", line 394, in _compile_core
    pm.run(self.state)
  File "C:\Users\zy\devel\numba\numba\core\compiler_machinery.py", line 341, in run
    raise patched_exception
  File "C:\Users\zy\devel\numba\numba\core\compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\zy\devel\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\zy\devel\numba\numba\core\compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\zy\devel\numba\numba\core\compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "C:\Users\zy\devel\numba\numba\core\typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "C:\Users\zy\devel\numba\numba\core\typed_passes.py", line 370, in run_pass
    lower.lower()
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\zy\Miniconda3\envs\numba-dev\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\zy\devel\numba\numba\core\errors.py", line 752, in new_error_context
    reraise(type(newerr), newerr, tb)
  File "C:\Users\zy\devel\numba\numba\core\utils.py", line 80, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\zy\devel\numba\numba\core\errors.py", line 745, in new_error_context
    yield
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 327, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 501, in lower_assign
    return self.lower_expr(ty, value)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 1026, in lower_expr
    res = self.lower_call(resty, expr)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 763, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 986, in _lower_call_normal
    argvals = self.fold_call_args(
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 682, in fold_call_args
    argvals = [self._cast_var(var, sigty)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 682, in <listcomp>
    argvals = [self._cast_var(var, sigty)
  File "C:\Users\zy\devel\numba\numba\core\lowering.py", line 665, in _cast_var
    return self.context.cast(self.builder, val, varty, ty)
  File "C:\Users\zy\devel\numba\numba\core\base.py", line 715, in cast
    raise NotImplementedError(
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast class(int32) to <class 'numba.core.types.abstract.DTypeSpec'>: %".51" = load i8*, i8** %"$14load_attr.6"

File "numba\cuda\tests\cudapy\test_intrinsics.py", line 114:
def simple_view_i4(ary, n):
    ary[0] = np.float32(n).view(np.int32)
    ^

During: lowering "$16call_method.7 = call $10load_method.4($14load_attr.6, func=$10load_method.4, args=[Var($14load_attr.6, test_intrinsics.py:114)], kws=(), vararg=None)" at C:\Users\zy\devel\numba\numba\cuda\tests\cudapy\test_intrinsics.py (114)

----------------------------------------------------------------------
Ran 32 tests in 3.522s

FAILED (errors=1)
```

**Comment by gmarkall** [comment]
Now that `@overload` is supported on the CUDA target, I have made a start on reusing the implementation in the core of Numba for this: https://github.com/gmarkall/numba/tree/cuda-scalar-view - the change itself is only:

```diff
diff --git a/numba/cpython/numbers.py b/numba/cpython/numbers.py
index d01152359..9021e3ee4 100644
--- a/numba/cpython/numbers.py
+++ b/numba/cpython/numbers.py
@@ -1359,5 +1359,5 @@ def scalar_view(scalar, viewty):
         return impl
 
 
-overload_method(types.Float, 'view')(scalar_view)
-overload_method(types.Integer, 'view')(scalar_view)
+overload_method(types.Float, 'view', target='generic')(scalar_view)
+overload_method(types.Integer, 'view', target='generic')(scalar_view)
```

however there are some test failures for this functionality on the CUDA target - I have not yet looked into whether there is a problem in the implementation related to CUDA, or if the tests need some adjustment.

**Comment by shaunc** [comment]
Any word on this? I'm getting:
```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
E           Unknown attribute 'float_as_int' of type Module(<module 'numba.cuda.libdevice'
```
when compiling to cuda. 

(Also, are all the cuda errors going to be moved to numpy-cuda? Or is talking about them here still ok?)
