### ISSUE TITLE
Unable to pass a local memory array to a device function?

### ISSUE THREAD

**Issue by nosachamos** [numba/numba#6103]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

I have a small code that demonstrates an issue I'm having. All it does is allocate some local memory and pass it into a CUDA device function:

```
import numpy as np
from numba import cuda, types


@cuda.jit(device=True, debug=True)
def mutate_genome(instruction_positions):
    return 0


@cuda.jit
def generate_mutants():
    instruction_positions = cuda.local.array(500, np.int64)

    mutate_genome(instruction_positions)


if __name__ == "__main__":
    generate_mutants[1, 1]()
```

However, when I run it with cuda-memcheck:

`cuda-memcheck python xtests.py`

I get this error:

```
========= CUDA-MEMCHECK
Traceback (most recent call last):
  File "xtests.py", line 18, in <module>
    generate_mutants[1, 1]()
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 804, in __call__
    kernel = self.specialize(*args)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 815, in specialize
    kernel = self.compile(argtypes)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 831, in compile
    **self.targetoptions)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 61, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/cuda/compiler.py", line 50, in compile_cuda
    locals={})
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 331, in compile_extra
    return self._compile_bytecode()
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 393, in _compile_bytecode
    return self._compile_core()
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 373, in _compile_core
    raise e
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 364, in _compile_core
    pm.run(self.state)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 347, in run
    raise patched_exception
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 338, in run
    self._runPass(idx, pass_inst, state)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 302, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/compiler_machinery.py", line 275, in check
    mangled = func(compiler_state)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/typed_passes.py", line 95, in run_pass
    raise_errors=self._raise_errors)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/typed_passes.py", line 67, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/home/stark/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 985, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x7f77bf6bb850>.
type object 'numpy.int64' has no attribute 'is_precise'
[1] During: resolving callee type: Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x7f772a8e0210>)
[2] During: typing of call at xtests.py (14)

Enable logging at debug level for details.

File "xtests.py", line 14:
def generate_mutants():
    <source elided>

    mutate_genome(instruction_positions)
    ^

```

What am I doing wrong? Is this a bug or an issue with what I'm doing?

Thanks!

**Comment by nosachamos** [comment]
Ah, found out that if I use numba.types.int32 it works. Closing.

**Comment by gmarkall** [comment]
Reopening as this really ought to work with NumPy types as as Numba ones.

**Comment by gmarkall** [comment]
(Thanks for the report, btw! :-) )

**Comment by gmarkall** [comment]
Just noticed this duplicates #5901
