### ISSUE TITLE
#6147 broke CUDASIM

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6167]
Simulator failing on current master (ea5655232) with:
```
$ NUMBA_ENABLE_CUDASIM=1 ./runtests.py numba.tests.test_runtests.TestCase -v -f
test_all (numba.tests.test_runtests.TestCase) ... ok
test_check_slice (numba.tests.test_runtests.TestCase) ... ok
test_check_slicing_equivalent (numba.tests.test_runtests.TestCase) ... ok
test_cuda (numba.tests.test_runtests.TestCase) ... ok
test_cuda_submodules (numba.tests.test_runtests.TestCase) ... FAIL

======================================================================
FAIL: test_cuda_submodules (numba.tests.test_runtests.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<path>/numba/numba/tests/test_runtests.py", line 62, in test_cuda_submodules
    self.check_listing_prefix('numba.cuda.tests.cudadrv')
  File "<path>/numba/numba/tests/test_runtests.py", line 23, in check_listing_prefix
    self.assertTrue(ln.startswith(prefix), msg=errmsg)
AssertionError: False is not true : 'unittest.loader._FailedTest.test_nvvm_driver' not startswith 'numba.cuda.tests.cudadrv'

----------------------------------------------------------------------
Ran 5 tests in 22.324s

FAILED (failures=1)
```
likely due to https://github.com/numba/numba/pull/6147. Needs fixing for 0.51.1.

**Comment by sklam** [comment]
Closed by #6168
