### ISSUE TITLE
umap.UMAP.    error 

### ISSUE THREAD

**Issue by shoaib03339770257** [numba/numba#6178]
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-14-396f7ff3c107> in <module>
      3 
      4 X_topics = svd_model.fit_transform(X)
----> 5 embedding = umap.UMAP(n_neighbors=150, min_dist=0.5, random_state=12).fit_transform(X_topics)
      6 plt.figure(figsize=(7,5))
      7 plt.scatter(embedding[:, 0], embedding[:, 1], 

~/.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/umap_.py in fit_transform(self, X, y)
   2012             Embedding of the training data in low-dimensional space.
   2013         """
-> 2014         self.fit(X, y)
   2015         return self.embedding_
   2016 

~/.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/umap_.py in fit(self, X, y)
   1799                 self.low_memory,
   1800                 use_pynndescent=True,
-> 1801                 verbose=self.verbose,
   1802             )
   1803 

~/.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/umap_.py in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, low_memory, use_pynndescent, verbose)
    395                     leaf_array=leaf_array,
    396                     n_iters=n_iters,
--> 397                     verbose=verbose,
    398                 )
    399 

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    349                 e.patch_message(msg)
    350 
--> 351             error_rewrite(e, 'typing')
    352         except errors.UnsupportedError as e:
    353             # Something unsupported is present in the user code, add help info

~/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    316                 raise e
    317             else:
--> 318                 reraise(type(e), e, None)
    319 
    320         argtypes = []

~/anaconda3/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x12f4ad358>:
--%<----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 661, in new_error_context
    yield
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 301, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 459, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 918, in lower_expr
    res = self.lower_call(resty, expr)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 711, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 890, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1132, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/targets/base.py", line 1157, in wrapper
    return fn(*args, **kwargs)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/targets/arrayobj.py", line 3374, in numpy_zeros_nd
    _zero_fill_array(context, builder, ary)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/targets/arrayobj.py", line 3304, in _zero_fill_array
    cgutils.memset(builder, ary.data, builder.mul(ary.itemsize, ary.nitems), 0)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/cgutils.py", line 866, in memset
    builder.call(fn, [ptr, value, size, int32_t(0), bool_t(0)])
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/llvmlite/ir/builder.py", line 851, in call
    cconv=cconv, tail=tail, fastmath=fastmath)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/llvmlite/ir/instructions.py", line 84, in __init__
    raise TypeError(msg)
TypeError: Type of #4 arg mismatch: i1 != i32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 144, in propagate
    constraint(typeinfer)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 455, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 474, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/typeinfer.py", line 1314, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/typing/context.py", line 186, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/typing/context.py", line 238, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/types/functions.py", line 271, in get_call_type
    template, pysig, args, kws = self.dispatcher.get_call_template(args, kws)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 275, in get_call_template
    self.compile(tuple(args))
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 659, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 955, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 377, in compile_extra
    return self._compile_bytecode()
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 886, in _compile_bytecode
    return self._compile_core()
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 873, in _compile_core
    res = pm.run(self.status)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 254, in run
    raise patched_exception
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 245, in run
    stage()
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 747, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 687, in _backend
    lowered = lowerfn()
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 674, in backend_nopython_mode
    self.metadata)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1124, in native_lowering_stage
    lower.lower()
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/Users/shoaib/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 669, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/Users/shoaib/anaconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "../../.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/utils.py", line 160:
def make_heap(n_points, size):
    <source elided>
    result = np.zeros(
        (np.int64(3), np.int64(n_points), np.int64(size)), dtype=np.float64
        ^

[1] During: lowering "$0.19 = call $0.2($0.15, func=$0.2, args=[Var($0.15, /Users/shoaib/.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/utils.py (160))], kws=[('dtype', Var($0.17, /Users/shoaib/.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/utils.py (160)))], vararg=None)" at /Users/shoaib/.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/utils.py (160)
[2] During: resolving callee type: type(CPUDispatcher(<function make_heap at 0x12d117d90>))
[3] During: typing of call at /Users/shoaib/.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/nndescent.py (188)

--%<----------------------------------------------------------------------------

File "../../.local/lib/python3.7/site-packages/umap_learn-0.4.6-py3.7.egg/umap/nndescent.py", line 188:
def nn_descent(
    <source elided>

    current_graph = make_heap(data.shape[0], n_neighbors)
    ^

This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by gmarkall** [comment]
Thanks for the issue report. Some questions:

- How did you install UMAP / Numba?
- What code are you running that generates the problem?
- What is the output of `numba -s`?

**Comment by esc** [comment]
This might be a Numba and llvmlite version mismatch. Which versions of these libraries do you have installed?

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
