### ISSUE TITLE
mainline @ 159510a is failing CI

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6315]
Failing run: https://dev.azure.com/numba/numba/_build/results?buildId=6831&view=logs&j=a506c6d0-8428-5bb5-7d36-c242a5467a36&t=3b81a997-a0fe-5621-27e6-18b6744841b9&l=9361

Details: https://gist.github.com/stuartarchibald/ace0bea10f04abb44d65a0ed9f8ba2cb

**Comment by stuartarchibald** [comment]
Dumping out the error:
```
AssertionError: 'cannot index array' not found in 'Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function flipud at 0x7f64ef745b00>) found for signature:
 
 >>> flipud(int64)
 
There are 2 candidate implementations:
  - Of which 1 did not match due to:
  Overload in function \'np_flip_ud\': File: numba/np/arrayobj.py: Line 4917.
    With argument(s): \'(int64)\':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   Internal error at <numba.core.typeinfer.StaticGetItemConstraint object at 0x7f64cd53e4d0>.
   \'TestOverloadInlining\' object has no attribute \'DummyType\'
   During: typing of intrinsic-call at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
   During: typing of static-get-item at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
   Enable logging at debug level for details.
   
   File "numba/np/arrayobj.py", line 4930:
       def impl(a):
           <source elided>
               raise ValueError(\'Input must be >= 1-d.\')
           return A[::-1, ...]
           ^
   
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 677, in _get_impl
           impl, args = self._impl_cache[cache_key]
       KeyError: (<numba.core.typing.context.Context object at 0x7f64e14c37d0>, (int64,), ())
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 677, in _get_impl
           impl, args = self._impl_cache[cache_key]
       KeyError: (<numba.core.typing.context.Context object at 0x7f64e14c37d0>, (array(int64, 0d, C), Tuple(slice<a:b:c>, ...)), ())
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/errors.py", line 738, in new_error_context
           yield
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 689, in __call__
           self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 586, in resolve
           sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 1535, in resolve_call
           return self.context.resolve_function_type(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 207, in resolve_function_type
           res = self._resolve_builtin_function_type(func, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 224, in _resolve_builtin_function_type
           res = defn.apply(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 597, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 679, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 710, in _build_impl
           ovf_result = self._overload_func(*args, **kws)
         File "/home/vsts/work/1/s/numba/tests/test_ir_inlining.py", line 660, in overload_dummy_getitem
           if isinstance(obj, self.DummyType):
       AttributeError: \'TestOverloadInlining\' object has no attribute \'DummyType\'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 154, in propagate
           constraint(typeinfer)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 469, in __call__
           self.fallback(typeinfer)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 689, in __call__
           self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
         File "/home/vsts/miniconda3/envs/travisci/lib/python3.7/contextlib.py", line 130, in __exit__
           self.gen.throw(type, value, traceback)
         File "/home/vsts/work/1/s/numba/core/errors.py", line 745, in new_error_context
           raise newerr.with_traceback(tb)
         File "/home/vsts/work/1/s/numba/core/errors.py", line 738, in new_error_context
           yield
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 689, in __call__
           self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 586, in resolve
           sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 1535, in resolve_call
           return self.context.resolve_function_type(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 207, in resolve_function_type
           res = self._resolve_builtin_function_type(func, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 224, in _resolve_builtin_function_type
           res = defn.apply(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 597, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 679, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 710, in _build_impl
           ovf_result = self._overload_func(*args, **kws)
         File "/home/vsts/work/1/s/numba/tests/test_ir_inlining.py", line 660, in overload_dummy_getitem
           if isinstance(obj, self.DummyType):
       numba.core.errors.InternalError: \'TestOverloadInlining\' object has no attribute \'DummyType\'
       During: typing of intrinsic-call at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       During: typing of static-get-item at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       The above exception was the direct cause of the following exception:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/types/functions.py", line 298, in get_call_type
           sig = temp.apply(nolitargs, nolitkws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 597, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 679, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 740, in _build_impl
           disp_type.get_call_type(self.context, args, kws)
         File "/home/vsts/work/1/s/numba/core/types/functions.py", line 511, in get_call_type
           self.dispatcher.get_call_template(args, kws)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 311, in get_call_template
           self.compile(tuple(args))
         File "/home/vsts/work/1/s/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
           return func(*args, **kwargs)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 818, in compile
           cres = self._compiler.compile(args, return_type)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 81, in compile
           raise retval
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 91, in _compile_cached
           retval = self._compile_core(args, return_type)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 109, in _compile_core
           pipeline_class=self.pipeline_class)
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 602, in compile_extra
           return pipeline.compile_extra(func)
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 352, in compile_extra
           return self._compile_bytecode()
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 414, in _compile_bytecode
           return self._compile_core()
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 394, in _compile_core
           raise e
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 385, in _compile_core
           pm.run(self.state)
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 339, in run
           raise patched_exception
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 330, in run
           self._runPass(idx, pass_inst, state)
         File "/home/vsts/work/1/s/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
           return func(*args, **kwargs)
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 289, in _runPass
           mutated |= check(pss.run_pass, internal_state)
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 262, in check
           mangled = func(compiler_state)
         File "/home/vsts/work/1/s/numba/core/typed_passes.py", line 99, in run_pass
           raise_errors=self._raise_errors)
         File "/home/vsts/work/1/s/numba/core/typed_passes.py", line 71, in type_inference_stage
           infer.propagate(raise_errors=raise_errors)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 1071, in propagate
           raise errors[0]
       numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
       Internal error at <numba.core.typeinfer.StaticGetItemConstraint object at 0x7f64cd53e4d0>.
       \'TestOverloadInlining\' object has no attribute \'DummyType\'
       During: typing of intrinsic-call at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       During: typing of static-get-item at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       Enable logging at debug level for details.
       File "numba/np/arrayobj.py", line 4930:
           def impl(a):
               <source elided>
                   raise ValueError(\'Input must be >= 1-d.\')
               return A[::-1, ...]
               ^
  raised from /home/vsts/work/1/s/numba/core/typeinfer.py:1071
  - Of which 1 did not match due to:
  Overload in function \'np_flip_ud\': File: numba/np/arrayobj.py: Line 4917.
    With argument(s): \'(int64)\':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   Internal error at <numba.core.typeinfer.StaticGetItemConstraint object at 0x7f64ce4bfb50>.
   \'TestOverloadInlining\' object has no attribute \'DummyType\'
   During: typing of intrinsic-call at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
   During: typing of static-get-item at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
   Enable logging at debug level for details.
   
   File "numba/np/arrayobj.py", line 4930:
       def impl(a):
           <source elided>
               raise ValueError(\'Input must be >= 1-d.\')
           return A[::-1, ...]
           ^
   
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 677, in _get_impl
           impl, args = self._impl_cache[cache_key]
       KeyError: (<numba.core.typing.context.Context object at 0x7f64e14c37d0>, (int64,), ())
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 677, in _get_impl
           impl, args = self._impl_cache[cache_key]
       KeyError: (<numba.core.typing.context.Context object at 0x7f64e14c37d0>, (array(int64, 0d, C), Tuple(slice<a:b:c>, ...)), ())
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/errors.py", line 738, in new_error_context
           yield
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 689, in __call__
           self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 586, in resolve
           sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 1535, in resolve_call
           return self.context.resolve_function_type(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 207, in resolve_function_type
           res = self._resolve_builtin_function_type(func, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 224, in _resolve_builtin_function_type
           res = defn.apply(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 597, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 679, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 710, in _build_impl
           ovf_result = self._overload_func(*args, **kws)
         File "/home/vsts/work/1/s/numba/tests/test_ir_inlining.py", line 660, in overload_dummy_getitem
           if isinstance(obj, self.DummyType):
       AttributeError: \'TestOverloadInlining\' object has no attribute \'DummyType\'
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 154, in propagate
           constraint(typeinfer)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 469, in __call__
           self.fallback(typeinfer)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 689, in __call__
           self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
         File "/home/vsts/miniconda3/envs/travisci/lib/python3.7/contextlib.py", line 130, in __exit__
           self.gen.throw(type, value, traceback)
         File "/home/vsts/work/1/s/numba/core/errors.py", line 745, in new_error_context
           raise newerr.with_traceback(tb)
         File "/home/vsts/work/1/s/numba/core/errors.py", line 738, in new_error_context
           yield
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 689, in __call__
           self.resolve(typeinfer, typeinfer.typevars, fnty=fnty)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 586, in resolve
           sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 1535, in resolve_call
           return self.context.resolve_function_type(fnty, pos_args, kw_args)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 207, in resolve_function_type
           res = self._resolve_builtin_function_type(func, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/context.py", line 224, in _resolve_builtin_function_type
           res = defn.apply(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 597, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 679, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 710, in _build_impl
           ovf_result = self._overload_func(*args, **kws)
         File "/home/vsts/work/1/s/numba/tests/test_ir_inlining.py", line 660, in overload_dummy_getitem
           if isinstance(obj, self.DummyType):
       numba.core.errors.InternalError: \'TestOverloadInlining\' object has no attribute \'DummyType\'
       During: typing of intrinsic-call at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       During: typing of static-get-item at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       The above exception was the direct cause of the following exception:
       Traceback (most recent call last):
         File "/home/vsts/work/1/s/numba/core/types/functions.py", line 293, in get_call_type
           sig = temp.apply(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 345, in apply
           sig = generic(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 597, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 679, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/home/vsts/work/1/s/numba/core/typing/templates.py", line 740, in _build_impl
           disp_type.get_call_type(self.context, args, kws)
         File "/home/vsts/work/1/s/numba/core/types/functions.py", line 511, in get_call_type
           self.dispatcher.get_call_template(args, kws)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 311, in get_call_template
           self.compile(tuple(args))
         File "/home/vsts/work/1/s/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
           return func(*args, **kwargs)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 818, in compile
           cres = self._compiler.compile(args, return_type)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 81, in compile
           raise retval
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 91, in _compile_cached
           retval = self._compile_core(args, return_type)
         File "/home/vsts/work/1/s/numba/core/dispatcher.py", line 109, in _compile_core
           pipeline_class=self.pipeline_class)
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 602, in compile_extra
           return pipeline.compile_extra(func)
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 352, in compile_extra
           return self._compile_bytecode()
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 414, in _compile_bytecode
           return self._compile_core()
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 394, in _compile_core
           raise e
         File "/home/vsts/work/1/s/numba/core/compiler.py", line 385, in _compile_core
           pm.run(self.state)
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 339, in run
           raise patched_exception
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 330, in run
           self._runPass(idx, pass_inst, state)
         File "/home/vsts/work/1/s/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
           return func(*args, **kwargs)
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 289, in _runPass
           mutated |= check(pss.run_pass, internal_state)
         File "/home/vsts/work/1/s/numba/core/compiler_machinery.py", line 262, in check
           mangled = func(compiler_state)
         File "/home/vsts/work/1/s/numba/core/typed_passes.py", line 99, in run_pass
           raise_errors=self._raise_errors)
         File "/home/vsts/work/1/s/numba/core/typed_passes.py", line 71, in type_inference_stage
           infer.propagate(raise_errors=raise_errors)
         File "/home/vsts/work/1/s/numba/core/typeinfer.py", line 1071, in propagate
           raise errors[0]
       numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
       Internal error at <numba.core.typeinfer.StaticGetItemConstraint object at 0x7f64ce4bfb50>.
       \'TestOverloadInlining\' object has no attribute \'DummyType\'
       During: typing of intrinsic-call at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       During: typing of static-get-item at /home/vsts/work/1/s/numba/np/arrayobj.py (4930)
       Enable logging at debug level for details.
       File "numba/np/arrayobj.py", line 4930:
           def impl(a):
               <source elided>
                   raise ValueError(\'Input must be >= 1-d.\')
               return A[::-1, ...]
               ^
  raised from /home/vsts/work/1/s/numba/core/typeinfer.py:1071

During: resolving callee type: Function(<function flipud at 0x7f64ef745b00>)
During: typing of call at /home/vsts/work/1/s/numba/tests/test_np_functions.py (121)


File "numba/tests/test_np_functions.py", line 121:
def flipud(a):
    return np.flipud(a)
    ^

````

**Comment by stuartarchibald** [comment]
Suspect this is due to https://github.com/numba/numba/pull/6027.

**Comment by stuartarchibald** [comment]
Think the issue is as follows...

This: https://github.com/numba/numba/blob/159510ad270b70fabf0f47107babb06fe7857d35/numba/tests/test_ir_inlining.py#L511-L513

calls this:
https://github.com/numba/numba/blob/159510ad270b70fabf0f47107babb06fe7857d35/numba/tests/test_ir_inlining.py#L135-L155

the problem being the mutation of `self`:
```
        self.Dummy = Dummy
        self.DummyType = DummyType
```
these two tests then register overloads for static getitem on these types:
https://github.com/numba/numba/blob/159510ad270b70fabf0f47107babb06fe7857d35/numba/tests/test_ir_inlining.py#L647-L691

the problem appears in typing when the `StaticGetItemConstraint` searches overloads and finds that `TestOverloadInlining` has no `DummyType` attr, question is why.

**Comment by stuartarchibald** [comment]
An intermittently successful method of reproducing is:
```
NUMBA_ENABLE_CUDASIM=1 python -m numba.runtests -f -b -j "2,None,18" --exclude-tags='long_running' -m 2 -v  -- numba.tests
```

**Comment by sklam** [comment]
> the problem appears in typing when the `StaticGetItemConstraint` searches overloads and finds that `TestOverloadInlining` has no `DummyType` attr, question is why.

Did you figure out why? `setUp` is executed once per test method. I wonder if it's because `self.Dummy` and `self.DummyType` may sometimes leak into the next test because there were no `tearDown`.
