### ISSUE TITLE
NamedTuple type and List

### ISSUE THREAD

**Issue by tsangwpx** [numba/numba#6355]
## Reporting a bug
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included below a minimal working reproducer (if you are unsure how
 to write one see http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports).

It seem that the `namedtuple` type is determined when creating an instance, which may not be compatible with the type of the existing list of `namedtuple`. Decimal numbers `float46` are also working. but integral types did not. The ordinary `tuple` seem working. 

```python
from __future__ import annotations

import collections

import numba
import numpy as np

print('version', numba.__version__)

# class Node(typing.NamedTuple):
#     count: int
#     index: int

Node = collections.namedtuple('Node', ('count', 'index'))


@numba.njit()
def example(seq):
    nodes = [
        Node(0, 0),
    ]
    total = 0

    for count in seq:
        total += count
        nodes.append(Node(count, len(nodes)))

    nodes[0] = Node(total, 0) # this also cause an error because `total` is int32, not shown.

    print(nodes)


print(example(
    np.array(np.arange(10)),
))
```

Output:
```text
version 0.51.2
Traceback (most recent call last):
  File "numba_namedtuple.py", line 33, in <module>
    print(example(
  File "lib\site-packages\numba\core\dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "lib\site-packages\numba\core\dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "lib\site-packages\numba\core\utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of BoundFunction(list.append for list(Node(int64 x 2))<iv=None>) with parameters (Node(int32, int64))

During: resolving callee type: BoundFunction(list.append for list(Node(int64 x 2))<iv=None>)
During: typing of call at numba_namedtuple.py (26)


File "numba_namedtuple.py", line 26:
def example(seq):
    <source elided>
        total += count
        nodes.append(Node(count, len(nodes)))
        ^

```

**Comment by gmarkall** [comment]
With Numba master I get:

```
$ python repro.py 
version 0.52.0dev0+573.gc5788551c
[Node(count=45, index=0), Node(count=0, index=1), Node(count=1, index=2), Node(count=2, index=3), Node(count=3, index=4), Node(count=4, index=5), Node(count=5, index=6), Node(count=6, index=7), Node(count=7, index=8), Node(count=8, index=9), Node(count=9, index=10)]
```

**Comment by gmarkall** [comment]
Ah, I'm on Linux though - I guess you're on Windows? Can you include the output of `numba -s`?

**Comment by gmarkall** [comment]
Executable reproducer for all platforms:

```python
from __future__ import annotations

import collections

import numba
import numpy as np

print("version", numba.__version__)

# class Node(typing.NamedTuple):
#     count: int
#     index: int

Node = collections.namedtuple("Node", ("count", "index"))


@numba.njit()
def example(seq):
    nodes = [Node(0, 0)]  # placeholder
    total = 0

    for count in seq:
        total += count
        nodes.append(Node(count, len(nodes)))

    nodes[0] = Node(
        total, 0
    )  # this also cause an error because `total` is int32, not shown.

    print(nodes)


print(example(np.array(np.arange(10), dtype=np.int32)))
```

**Comment by gmarkall** [comment]
I'm not sure this is a bug, but is what I'd expect to happen. To ensure that the node is created with the type matching the type of nodes in the list, you can cast `count` - first import `int64`:

```python
from numba import int64
```

then change the line that creates and appends the node to:

```python
        nodes.append(Node(int64(count), len(nodes)))
```

**Comment by tsangwpx** [comment]
output of `display_info()`: https://gist.github.com/tsangwpx/fa9834025ac765a96023e051c2bdc248
I am not sure about the development version 0.52.0.

Type inference produce unintended but reasonable results.
I feel odd that `namedtuple` and `tuple` behave differently.

Is there a way to specify types of `namedtuple` like ones in `jitclass`?
Explicit casting may be a workaround but not preferable because it must be used whenever creating a `namedtuple` instance to specify types explicitly.

**Comment by gmarkall** [comment]
Thanks for posting the output!

> I feel odd that `namedtuple` and `tuple` behave differently.

OK, I see with:

```python
from __future__ import annotations

import collections

import numba
import numpy as np

from numba import int64


print("version", numba.__version__)

# class Node(typing.NamedTuple):
#     count: int
#     index: int


@numba.njit()
def example(seq):
    nodes = [(0, 0)]  # placeholder
    total = 0

    for count in seq:
        total += count
        nodes.append((count, len(nodes)))

    nodes[0] = (
        total, 0
    )  # this also cause an error because `total` is int32, not shown.

    print(nodes)


print(example(np.array(np.arange(10), dtype=np.int32)))
```

refinement works and typing succeeds. However, for:

```python
from __future__ import annotations

import collections

import numba
import numpy as np

from numba import int64


print("version", numba.__version__)

# class Node(typing.NamedTuple):
#     count: int
#     index: int


@numba.njit()
def example(seq):
    nodes = [tuple(0, 0)]  # placeholder
    total = 0

    for count in seq:
        total += count
        nodes.append(tuple(count, len(nodes)))

    nodes[0] = tuple(
        total, 0
    )  # this also cause an error because `total` is int32, not shown.

    print(nodes)


print(example(np.array(np.arange(10), dtype=np.int32)))
```

Then typing fails, probably because a tuple constraint is not built due to the call to `tuple` rather than a `build_tuple` op appearing in the IR.

I suspect this could be fixed by also building a tuple constraint for namedtuples, but this is an area I'm not too familiar with - a core developer may have a clearer idea here.

> Is there a way to specify types of namedtuple like ones in jitclass?

You can express the type of a namedtuple as Numba sees it with `numba.core.types.NamedTuple`. Modifying your example to use this type, and the `locals` argument to the `@njit` decorator to specify the types of local variables, we have:

```python
from __future__ import annotations

import collections

import numba
import numpy as np

from numba import int32, int64
from numba.core.types import List, NamedTuple


Node = collections.namedtuple("Node", ("count", "index"))
NodeType = NamedTuple((int32, int64), Node)
NodeListType = List(NodeType)


@numba.njit(locals={'nodes': NodeListType, 'total': int32})
def example(seq):
    nodes = [Node(int32(0), 0)]  # placeholder
    total = 0

    for count in seq:
        total += count
        nodes.append(Node(count, len(nodes)))

    nodes[0] = Node(
        total, 0
    )  # this also cause an error because `total` is int32, not shown.

    print(nodes)


print(example(np.array(np.arange(10), dtype=np.int32)))
```

Here I had to cast the constant `0` to `int32` when creating the `Node` on the `# placeholder` line because it types as `int64`. Does this provide a more helpful workaround?

> Explicit casting may be a workaround but not preferable because it must be used whenever creating a namedtuple instance to specify types explicitly.

Indeed - does the above workaround reduce the need for casting enough to make it more workable?

**Comment by tsangwpx** [comment]
thanks for the insights of the numba internals and  the useful examples. I am interested in the result from the master branch. Probably this issue is indeed solved.

**Comment by gmarkall** [comment]
> thanks for the insights of the numba internals and the useful examples. I am interested in the result from the master branch. Probably this issue is indeed solved.

I don't think it is solved - the only reason I didn't initially see the issue was because on Linux, the default NumPy int dtype is `int64`, so I ended up creating a `Node` with two `int64`s, which was an OK typing. The general issue that namedtuples don't quite type the same as tuples still exists - I can still reproduce the issue with the master branch.

**Comment by sklam** [comment]
So, one way to replicate in an OS agnostic way is to force `int32` type:

```python
from __future__ import annotations

import collections

import numba
import numpy as np

print('version', numba.__version__)

# class Node(typing.NamedTuple):
#     count: int
#     index: int

Node = collections.namedtuple('Node', ('count', 'index'))


@numba.njit()
def example(seq):
    nodes = [
        Node(np.int32(0), np.int32(0)), # force different type
    ]
    total = 0

    for count in seq:
        total += count
        nodes.append(Node(count, len(nodes)))

    nodes[0] = Node(total, 0) # this also cause an error because `total` is int32, not shown.

    print(nodes)


print(example(
    np.array(np.arange(10)),
))
```
If `Node` is replaced so it is just a simple `tuple`, the program works.
Note, in the 2nd code snippet in https://github.com/numba/numba/issues/6355#issuecomment-707757497, `tuple(0, 0)` is invalid use of the `tuple` ctor.

**Comment by sklam** [comment]
To add the requested behavior, we need to add a `unify` call to NamedTuple types just like this for Tuple: https://github.com/numba/numba/blob/3a682bd827e416335e3574bc7b10f0ec69adb701/numba/core/types/containers.py#L331-L342
