### ISSUE TITLE
np.shift_left and np.shift_right unsupported for np.uint64

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6381]
Hello. From what I can tell numpy arrays with 64 bit unsigned integers seem to fail in compilation. Here is a reproducer:

 
```python
In [48]: arr = np.array([1, 2, 1, 1, 1, 31,4], np.uint64)

In [49]: np.left_shift(arr, 1)
Out[49]: array([ 2,  4,  2,  2,  2, 62,  8], dtype=uint64)

In [50]: numba.njit(lambda arr: np.left_shift(arr, 1))
Out[50]: CPUDispatcher(<function <lambda> at 0x7fe165c65b80>)

In [51]: arr = np.array([1, 2, 1, 1, 1, 31,4], np.uint64)

In [52]: np.left_shift(arr, 1)
Out[52]: array([ 2,  4,  2,  2,  2, 62,  8], dtype=uint64)

In [53]: numba.njit(lambda arr: np.left_shift(arr, 1))(arr)
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-53-d08695da763c> in <module>
----> 1 numba.njit(lambda arr: np.left_shift(arr, 1))(arr)

~/Documents/bodo/Bodo/bodo/numba_compat.py in _compile_for_args(***failed resolving arguments***)
    919             e.patch_message(msg)
    920 
--> 921         error_rewrite(e, "typing")
    922     except errors.UnsupportedError as e:
    923         # Something unsupported is present in the user code, add help info

~/Documents/bodo/Bodo/bodo/numba_compat.py in error_rewrite(e, issue_type)
    843             raise e
    844         else:
--> 845             reraise(type(e), e, None)
    846 
    847     argtypes = []

~/Documents/bodo/numba/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<ufunc 'left_shift'>) found for signature:
 
 >>> left_shift(array(uint64, 1d, C), Literal[int](1))
 
There are 5 candidate implementations:
      - Of which 1 did not match due to:
      Overload in function 'Numpy_rules_ufunc.generic': File: numba/core/typing/npydecl.py: Line 96.
        With argument(s): '(array(uint64, 1d, C), int64)':
       Rejected as the implementation raised a specific error:
         TypingError: can't resolve ufunc left_shift for types (array(uint64, 1d, C), int64)
  raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/npydecl.py:102
      - Of which 1 did not match due to:
      Overload in function 'Numpy_rules_ufunc.generic': File: numba/core/typing/npydecl.py: Line 96.
        With argument(s): '(array(uint64, 1d, C), Literal[int](1))':
       Rejected as the implementation raised a specific error:
         TypingError: can't resolve ufunc left_shift for types (array(uint64, 1d, C), Literal[int](1))
  raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/npydecl.py:102
      - Of which 3 did not match due to:
      Overload of function 'left_shift': File: <numerous>: Line N/A.
        With argument(s): '(array(uint64, 1d, C), Literal[int](1))':
       No match.

During: resolving callee type: Function(<ufunc 'left_shift'>)
During: typing of call at <ipython-input-53-d08695da763c> (1)


File "<ipython-input-53-d08695da763c>", line 1:
numba.njit(lambda arr: np.left_shift(arr, 1))(arr)
^


In [54]: np.right_shift(arr, 1)
Out[54]: array([ 0,  1,  0,  0,  0, 15,  2], dtype=uint64)

In [55]: numba.njit(lambda arr: np.right_shift(arr, 1))(arr)
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-55-bf0e79c0242b> in <module>
----> 1 numba.njit(lambda arr: np.right_shift(arr, 1))(arr)

~/Documents/bodo/Bodo/bodo/numba_compat.py in _compile_for_args(***failed resolving arguments***)
    919             e.patch_message(msg)
    920 
--> 921         error_rewrite(e, "typing")
    922     except errors.UnsupportedError as e:
    923         # Something unsupported is present in the user code, add help info

~/Documents/bodo/Bodo/bodo/numba_compat.py in error_rewrite(e, issue_type)
    843             raise e
    844         else:
--> 845             reraise(type(e), e, None)
    846 
    847     argtypes = []

~/Documents/bodo/numba/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<ufunc 'right_shift'>) found for signature:
 
 >>> right_shift(array(uint64, 1d, C), Literal[int](1))
 
There are 5 candidate implementations:
      - Of which 1 did not match due to:
      Overload in function 'Numpy_rules_ufunc.generic': File: numba/core/typing/npydecl.py: Line 96.
        With argument(s): '(array(uint64, 1d, C), int64)':
       Rejected as the implementation raised a specific error:
         TypingError: can't resolve ufunc right_shift for types (array(uint64, 1d, C), int64)
  raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/npydecl.py:102
      - Of which 1 did not match due to:
      Overload in function 'Numpy_rules_ufunc.generic': File: numba/core/typing/npydecl.py: Line 96.
        With argument(s): '(array(uint64, 1d, C), Literal[int](1))':
       Rejected as the implementation raised a specific error:
         TypingError: can't resolve ufunc right_shift for types (array(uint64, 1d, C), Literal[int](1))
  raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/npydecl.py:102
      - Of which 3 did not match due to:
      Overload of function 'right_shift': File: <numerous>: Line N/A.
        With argument(s): '(array(uint64, 1d, C), Literal[int](1))':
       No match.

During: resolving callee type: Function(<ufunc 'right_shift'>)
During: typing of call at <ipython-input-55-bf0e79c0242b> (1)


File "<ipython-input-55-bf0e79c0242b>", line 1:
numba.njit(lambda arr: np.right_shift(arr, 1))(arr)
^
```

**Comment by esc** [comment]
@njriasan thank you for submitting this, I can reproduce. For reference here is stand-alone reproducer:

```
from numba import njit
import numpy as np


@njit
def foo(a):
    return np.left_shift(a, 1)

arr = np.array([1, 2, 1, 1, 1, 31,4], np.uint64)

print(foo(arr))
````
I can also confirm that `int64` arrays work fine and it is only the `uint64` variant that fails to compile.

**Comment by stuartarchibald** [comment]
I don't think there's a ufunc loop suitable, Numba won't cast a signed int to an unsigned as it isn't safe:
```pycon
In [1]: np.left_shift.types
Out[1]: 
['bb->b',
 'BB->B',
 'hh->h',
 'HH->H',
 'ii->i',
 'II->I',
 'll->l',
 'LL->L',
 'qq->q',
 'QQ->Q',
 'OO->O']
```
workaround, specify the dtype of the number of bits:
```pycon
In [2]: import numpy as np

In [3]: import numba

In [4]: arr = np.array([1, 2, 1, 1, 1, 31,4], np.uint64)

In [5]: numba.njit(lambda arr: np.right_shift(arr, np.uint64(1)))(arr)
Out[5]: array([ 0,  1,  0,  0,  0, 15,  2], dtype=uint64)
```

**Comment by esc** [comment]
@stuartarchibald so, to summarize, if you try to shift an array of unsigned int64s, the number you shift with must  also be unsigned int64?

**Comment by stuartarchibald** [comment]
> @stuartarchibald so, to summarize, if you try to shift an array of unsigned int64s, the number you shift with must also be unsigned int64?

It just needs to be unsigned, bit width doesn't matter.
```pycon
In [6]: numba.njit(lambda arr: np.right_shift(arr, np.uint8(1)))(arr)
Out[6]: array([ 0,  1,  0,  0,  0, 15,  2], dtype=uint64)
```

**Comment by esc** [comment]
@stuartarchibald I don't think there is anything we can do to fix this, right?

**Comment by esc** [comment]
We have decided to re-label this as a feature request as it is possible, but tedious to implement.
