### ISSUE TITLE
NamedTuple fails if type name doesn't match variable name

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6388]
I encounter an issue when trying to used namedtuple. If I run the following code:

```python
from collections import namedtuple
import numba
from numba.extending import overload


example = namedtuple("Example", ["x", "y"])

def test_namedtuple(x, y):
    pass

@overload(test_namedtuple)
def test_namedtuple_overload(x, y):
    return lambda x, y: example(x, y)

@numba.njit()
def f(x, y):
    return test_namedtuple(x, y)


print(f(3, 4))
```
I get the following error:
```python
Traceback (most recent call last):
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/pythonapi.py", line 1361, in serialize_object
    gv = self.module.__serialized[obj]
KeyError: <class '__main__.Example'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "namedtuple_bug.py", line 20, in <module>
    print(f(3, 4))
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 434, in _compile_for_args
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 367, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 820, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 78, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 92, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 105, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 627, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 363, in compile_extra
    return self._compile_bytecode()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 425, in _compile_bytecode
    return self._compile_core()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 405, in _compile_core
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 396, in _compile_core
    pm.run(self.state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 341, in run
    raise patched_exception
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typed_passes.py", line 442, in run_pass
    NativeLowering().run_pass(state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typed_passes.py", line 372, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/lowering.py", line 242, in create_cpython_wrapper
    self.context.create_cpython_wrapper(self.library, self.fndesc,
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/cpu.py", line 161, in create_cpython_wrapper
    builder.build()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/callwrapper.py", line 122, in build
    self.build_wrapper(api, builder, closure, args, kws)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/callwrapper.py", line 176, in build_wrapper
    obj = api.from_native_return(retty, retval, env_manager)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/pythonapi.py", line 1388, in from_native_return
    out = self.from_native_value(typ, val, env_manager)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/pythonapi.py", line 1402, in from_native_value
    return impl(typ, val, c)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/boxing.py", line 502, in box_namedtuple
    cls_obj = c.pyapi.unserialize(c.pyapi.serialize_object(typ.instance_class))
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/pythonapi.py", line 1363, in serialize_object
    struct = self.serialize_uncached(obj)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/pythonapi.py", line 1334, in serialize_uncached
    data = serialize.dumps(obj)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/serialize.py", line 168, in dumps
    p.dump(obj)
_pickle.PicklingError: Failed in nopython mode pipeline (step: nopython mode backend)
Can't pickle <class '__main__.Example'>: attribute lookup Example on __main__ failed
```

However if I change the code so the variable and type name match:
```python
from collections import namedtuple
import numba
from numba.extending import overload


example = namedtuple("example", ["x", "y"])

def test_namedtuple(x, y):
    pass

@overload(test_namedtuple)
def test_namedtuple_overload(x, y):
    return lambda x, y: example(x, y)

@numba.njit()
def f(x, y):
    return test_namedtuple(x, y)


print(f(3, 4))
```

Now everything runs as expected:
```python
example(x=3, y=4)
```

**Comment by stuartarchibald** [comment]
Numba needs to be able to serialize the type, don't think this is a Numba problem:
```python
from collections import namedtuple
import pickle

example = namedtuple("Example", ["x", "y"])
pickle.dumps(example)
```
gives:
```
_pickle.PicklingError: Can't pickle <class '__main__.Example'>: attribute lookup Example on __main__ failed
```

**Comment by gmarkall** [comment]
Closing this issue as it seems not to be an issue in Numba, but a general issue with serializing namedtuples whose name differs from their variable name.
