### ISSUE TITLE
Constant lowering compliant dictionary types

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6404]
Hi. There are certain cases that can arise where it may be useful or necessary to perform certain calculations at compile time  alongside an overload. If that calculation involves a dictionary, my understanding is that it is currently not possible to lower that constant dictionary, even though it may be strictly typed (or calculated in a jit function). I think it would be useful to offer constant lower in these situations. Here is an example piece of code that I think should work. It doesn't need this feature, but its a much simpler example of a more complicated case where I actually need to calculate the result at compile time.

```python
import numba
from numba.extending import overload
import numpy as np

@numba.njit
def f(key):
    return get_key(key)


def get_key(key):
    pass


@numba.njit
def get_typed_dict():
    # Return a dictionary produced from a jit func
    return {1: 1, 2: 6}

@overload(get_key)
def get_key_overload(key):
    keys_dict = get_typed_dict()
    def impl(key):
        return keys_dict[key]

    return impl

f(2)
```

Here is the output I get, which is why I believe it should be possible to lower this constant:
```python
Traceback (most recent call last):
  File "lower_dict.py", line 27, in <module>
    f(2)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function get_key at 0x7fe7d106c9d0>) found for signature:
 
 >>> get_key(int64)
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'get_key_overload': File: ../tests/lower_dict.py: Line 19.
    With argument(s): '(int64)':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   Untyped global name 'keys_dict': cannot determine Numba type of <class 'dict'>
   
   File "lower_dict.py", line 23:
       def impl(key):
           return keys_dict[key]
           ^

  raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typeinfer.py:1460

During: resolving callee type: Function(<function get_key at 0x7fe7d106c9d0>)
During: typing of call at lower_dict.py (7)


File "lower_dict.py", line 7:
def f(key):
    return get_key(key)
    ^

(DEV) nicholasriasanovsky@x86_64-apple-darwin13 tests % vim lower_dict.py   
(DEV) nicholasriasanovsky@x86_64-apple-darwin13 tests % python lower_dict.py
Traceback (most recent call last):
  File "lower_dict.py", line 27, in <module>
    f(2)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function get_key at 0x7f825116c9d0>) found for signature:
 
 >>> get_key(int64)
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'get_key_overload': File: ../tests/lower_dict.py: Line 19.
    With argument(s): '(int64)':
   Rejected as the implementation raised a specific error:
     LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
   Cannot lower constant of type 'DictType[int64,int64]<iv={1: 1, 2: 6}>'
   
   File "lower_dict.py", line 23:
       def impl(key):
           return keys_dict[key]
           ^
   
   During: lowering "$2load_deref.0 = freevar(keys_dict: {1: 1, 2: 6})" at lower_dict.py (23)
  raised from /Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/utils.py:81

During: resolving callee type: Function(<function get_key at 0x7f825116c9d0>)
During: typing of call at lower_dict.py (7)


File "lower_dict.py", line 7:
def f(key):
    return get_key(key)
    ^
```

**Comment by stuartarchibald** [comment]
@njriasan Thanks for the suggestion. Are the keys literals?

**Comment by stuartarchibald** [comment]
This help?
```python
import numba
from numba import literally, types
from numba.extending import overload
import numpy as np

@numba.njit
def f(key):
    return get_key(key)


def get_key(key):
    pass


@numba.njit
def get_typed_dict():
    # Return a dictionary produced from a jit func
    return {1: 1, 2: 6}


@overload(get_key)
def get_key_overload(key):
    if isinstance(key, types.IntegerLiteral):
        keys_dict = get_typed_dict()
        value = keys_dict[key.literal_value]
        def impl(key):
            return value
        return impl
    else:
        return lambda key: literally(key)


print(f(2))
```

**Comment by njriasan** [comment]
That is extremely helpful to know in general and handles my current usage. Thank you.

**Comment by gmarkall** [comment]
Closing this issue as it seems to be resolved.

**Comment by stuartarchibald** [comment]
Great, thanks for confirming.

**Comment by njriasan** [comment]
Would it be possible to keep supporting constant lowering for dictionaries open as a suggested feature? My particular use case doesn't require it, but I think when possible supporting constant lowering is important for user experience.
