### ISSUE TITLE
Issue created list of dictionary with constant keys and heterogenous data

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6417]
I was trying to work with dictionaries inside an njit function and I encountered some issues while trying to create a list with constant keys and heterogeneous data. Based on this documentation, https://numba.readthedocs.io/en/stable/reference/pysupported.html#heterogeneous-literal-string-key-dictionary, I believe this usage should be supported.

Here are two reproducers demonstrating my issues:

```python
In [10]: @numba.njit
    ...: def f():
    ...:     s = []
    ...:     for i in range(10):
    ...:       d = {'a': 1, 'b': 'data'}
    ...:       s.append(d)
    ...:     return s
    ...:
    ...:
In [11]: f()
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-11-c43e34e6d405> in <module>
----> 1 f()
~/dev/numba/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info
~/dev/numba/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359
    360         argtypes = []
~/dev/numba/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Poison type used in arguments; got Poison<LiteralStrKey[Dict]({Literal[str](a): Literal[int](1), Literal[str](b): Literal[str](data)})>
During: resolving callee type: BoundFunction(list.append for list(undefined)<iv=None>)
During: typing of call at <ipython-input-10-4ad4bb8e6cc0> (6)
File "<ipython-input-10-4ad4bb8e6cc0>", line 6:
def f():
    <source elided>
      d = {'a': 1, 'b': 'data'}
      s.append(d)
      ^
which produces the output
```python
@numba.njit
    ...: def f():
    ...:     s = []
    ...:     for i in range(10):
    ...:       d = {'a': 1, 'b': 'data'}
    ...:       s.append(d)
    ...:     return s
```

```python
In [12]: @numba.njit
    ...: def f():
    ...:     s = []
    ...:     for i in range(10):
    ...:       d = {'a': 1, 'b': 2.2}
    ...:       s.append(d)
    ...:     return s
    ...:
    ...:
In [13]: f()
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-13-c43e34e6d405> in <module>
----> 1 f()
~/dev/numba/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info
~/dev/numba/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359
    360         argtypes = []
~/dev/numba/numba/core/utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82
TypingError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 >>> setitem(DictType[unicode_type,int64]<iv=None>, Literal[str](b), float64)
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(DictType[unicode_type,int64]<iv=None>, unicode_type, float64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'impl_setitem': File: numba/typed/dictobject.py: Line 671.
    With argument(s): '(DictType[unicode_type,int64]<iv=None>, unicode_type, float64)':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<intrinsic _cast>) found for signature:
    >>> <unknown function>(float64, class(int64))
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Intrinsic in function '_cast': File: numba/typed/typedobjectutils.py: Line 23.
           With argument(s): '(float64, class(int64))':
          Rejected as the implementation raised a specific error:
            TypingError: cannot safely cast float64 to int64. Please cast explicitly.
     raised from /Users/ehsan/dev/numba/numba/typed/typedobjectutils.py:76
   During: resolving callee type: Function(<intrinsic _cast>)
   During: typing of call at /Users/ehsan/dev/numba/numba/typed/dictobject.py (680)
   File "../numba/numba/typed/dictobject.py", line 680:
       def impl(d, key, value):
           <source elided>
           castedkey = _cast(key, keyty)
           castedval = _cast(value, valty)
           ^
  raised from /Users/ehsan/dev/numba/numba/core/typeinfer.py:1071
During: typing of setitem at /Users/ehsan/dev/numba/numba/typed/dictobject.py (1106)
File "../numba/numba/typed/dictobject.py", line 1106:
                def put(d, k, v):
                    d[k] = v
                    ^
During: lowering "$24build_const_key_map.7 = build_map(items=[(Var($24build_const_key_map.5, <ipython-input-12-4ee2dbb48a06>:5), Var($const18.2, <ipython-input-12-4ee2dbb48a06>:5)), (Var($24build_const_key_map.6, <ipython-input-12-4ee2dbb48a06>:5), Var($const20.3, <ipython-input-12-4ee2dbb48a06>:5))], size=2, literal_value={'a': 1, 'b': 2.2}, value_indexes={'a': 0, 'b': 1})" at <ipython-input-12-4ee2dbb48a06> (5)
```

**Comment by gmarkall** [comment]
With the first issue:

```python
from numba import njit
from numba.typed import List


@njit
def f():
    s = List()
    for i in range(10):
        d = {"a": 1, "b": "data"}
        s.append(d)
    return s


f()
```

I can reproduce the error. It seems that the `LiteralStrKeyDict`'s `__unliteral__` method returns a `Poison` type, but the unliteral version of the type is needed for determining the type of the list. If I modify the `__unliteral__` method of `LiteralStrKeyDict` to:

```diff
diff --git a/numba/core/types/containers.py b/numba/core/types/containers.py
index 6191852af..2dafd628b 100644
--- a/numba/core/types/containers.py
+++ b/numba/core/types/containers.py
@@ -777,7 +777,7 @@ class LiteralStrKeyDict(Literal, ConstSized, Hashable):
         self.name = "LiteralStrKey[Dict]({})".format(literal_value)
 
     def __unliteral__(self):
-        return Poison(self)
+        return NamedTuple(self.types, self.tuple_ty)
 
     def unify(self, typingctx, other):
         """
```

then there's a lowering error:

```
$ python repro.py 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 712, in cast
    impl = self._casts.find((fromty, toty))
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 49, in find
    out = self._find(sig)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 58, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.core.base.OverloadSelector object at 0x7f672fe94b80>, (LiteralStrKey[Dict]({Literal[str](a): Literal[int](1), Literal[str](b): Literal[str](data)}), _ntclazz(Literal[int](1), Literal[str](data))))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 327, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 502, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 1023, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 761, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 983, in _lower_call_normal
    argvals = self.fold_call_args(
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 700, in fold_call_args
    argvals = typing.fold_arguments(pysig,
  File "/home/gmarkall/numbadev/numba/numba/core/typing/templates.py", line 239, in fold_arguments
    ba.arguments[name] = normal_handler(i, param, ba.arguments[name])
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 687, in normal_handler
    return self._cast_var(var, signature.args[index])
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 666, in _cast_var
    return self.context.cast(self.builder, val, varty, ty)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 715, in cast
    raise NotImplementedError(
NotImplementedError: Cannot cast LiteralStrKey[Dict]({Literal[str](a): Literal[int](1), Literal[str](b): Literal[str](data)}) to _ntclazz(Literal[int](1), Literal[str](data)): %".255" = load {i64, i8*}, {i64, i8*}* %"d"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repro.py", line 14, in <module>
    f()
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 433, in _compile_for_args
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 366, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 857, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 602, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 352, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 414, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 394, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 385, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 449, in run_pass
    NativeLowering().run_pass(state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 373, in run_pass
    lower.lower()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/miniconda3/envs/numba/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Cannot cast LiteralStrKey[Dict]({Literal[str](a): Literal[int](1), Literal[str](b): Literal[str](data)}) to _ntclazz(Literal[int](1), Literal[str](data)): %".255" = load {i64, i8*}, {i64, i8*}* %"d"

File "repro.py", line 10:
def f():
    <source elided>
        d = {"a": 1, "b": "data"}
        s.append(d)
        ^

During: lowering "$36call_method.11 = call $32load_method.9(d, func=$32load_method.9, args=[Var(d, repro.py:9)], kws=(), vararg=None)" at repro.py (10)
```

so I think this could be made to work, but it would need a little more work.

**Comment by gmarkall** [comment]
Looking over the documentation again (https://numba.readthedocs.io/en/stable/reference/pysupported.html#heterogeneous-literal-string-key-dictionary), the use cases of these dictionaries is quite limited. So I'm marking this as a feature request, for these additional use cases to be supported.

**Comment by stuartarchibald** [comment]
> With the first issue:
> 
> ```python
> from numba import njit
> from numba.typed import List
> 
> 
> @njit
> def f():
>     s = List()
>     for i in range(10):
>         d = {"a": 1, "b": "data"}
>         s.append(d)
>     return s
> 
> 
> f()
> ```
> 
> I can reproduce the error. It seems that the `LiteralStrKeyDict`'s `__unliteral__` method returns a `Poison` type, but the unliteral version of the type is needed for determining the type of the list. If I modify the `__unliteral__` method of `LiteralStrKeyDict` to:
> 
> ```diff
> diff --git a/numba/core/types/containers.py b/numba/core/types/containers.py
> index 6191852af..2dafd628b 100644
> --- a/numba/core/types/containers.py
> +++ b/numba/core/types/containers.py
> @@ -777,7 +777,7 @@ class LiteralStrKeyDict(Literal, ConstSized, Hashable):
>          self.name = "LiteralStrKey[Dict]({})".format(literal_value)
>  
>      def __unliteral__(self):
> -        return Poison(self)
> +        return NamedTuple(self.types, self.tuple_ty)
>  
>      def unify(self, typingctx, other):
>          """
> ```
> 
> then there's a lowering error:
> 

\<snip\>

> 
> so I think this could be made to work, but it would need a little more work.


I think there is no non-literal representation of a string key dictionary (the keys have to be literal?) and as a result calling `unliteral*` correctly leads to `Poison` type generation?

Am wondering if this:
https://github.com/numba/numba/blob/5dcb2f1252f30f30060725171facee0217685394/numba/core/types/functions.py#L396-L401
might benefit from looking like:
```python
                skip = False
                try:
                    unliteral_args = tuple([_unlit_non_poison(a) for a in args])
                    unliteral_kws = {k: _unlit_non_poison(v)
                                    for k, v in kws.items()}
                except errors.TypingError as exc:
                    skip = True
                    nonliteral_e = exc
                else:
                    skip = unliteral_args == args and kws == unliteral_kws
```
and then `unliteral` being updated to raise if it encounters `Poison`. With this change it might be possible for cases such as the above to survive further into type inference. If some updates are then also made to the typing of `list.append` such that it is ok with a literal value in the first refinement and then unification is used to deal with subsequent refinements, the list should type ok too. The error trigger for this path is here:
https://github.com/numba/numba/blob/5dcb2f1252f30f30060725171facee0217685394/numba/core/types/containers.py#L419
and this is used when copying the list 
https://github.com/numba/numba/blob/5dcb2f1252f30f30060725171facee0217685394/numba/core/types/containers.py#L432
as needed when doing the `append`:
https://github.com/numba/numba/blob/5dcb2f1252f30f30060725171facee0217685394/numba/core/typing/listdecl.py#L43

This, however, is going to require fundamental and tricky changes to type inference and I'm not sure the risk balances the reward for an experimental feature.

**Comment by stuartarchibald** [comment]
The second issue:
```python
@njit
def f():
    s = []
    for i in range(10):
      d = {'a': 1, 'b': 2.2}
      s.append(d)
    return s

f()
```
has the problem reported in the error message:
```
   No implementation of function Function(<intrinsic _cast>) found for signature:

    >>> <unknown function>(float64, class(int64))
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Intrinsic in function '_cast': File: numba/typed/typedobjectutils.py: Line 23.
           With argument(s): '(float64, class(int64))':
          Rejected as the implementation raised a specific error:
            TypingError: cannot safely cast float64 to int64. Please cast explicitly.
```
i.e. the dictionary was typed as a map of `unicode_type->int64` from the addition of `'a': 1` but subsequently a `float64` was used as a value (`2.2`) and that's not safe to cast. Suggest manually casting the `1` to a `float64` to fix.

**Comment by gmarkall** [comment]
Since there are two distinct issues here, let's move discussion of the second one into #6420.
