### ISSUE TITLE
ByteArray doesn't support boxing or slicing

### ISSUE THREAD

**Issue by njriasan** [numba/numba#6459]
When working with a byte array type it seems that unboxing is supported, but boxing is not supported. Here is an example reproducer.

```python
import numba

arr = bytearray([1, 2, 3, 4])
print(numba.njit(lambda x: x)(arr))
```

with output:
```python
Traceback (most recent call last):
  File "test_bytearray.py", line 4, in <module>
    print(numba.njit(lambda x: x)(arr))
TypeError: cannot convert native bytearray(uint8, 1d, C) to Python object
```

In addition ByteArrays doesn't seems to support getitem with slices. Here is the reproducer:
```python
import numba

arr = bytearray([1, 2, 3, 4])
print(numba.njit(lambda x: x)(arr))
```

with output:
```python
Traceback (most recent call last):
  File "test_bytearray.py", line 4, in <module>
    print(numba.njit(lambda x: x[1:3])(arr))
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(bytearray(uint8, 1d, C), slice<a:b>)
 
There are 22 candidate implementations:
  - Of which 22 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(bytearray(uint8, 1d, C), slice<a:b>)':
   No match.

During: typing of intrinsic-call at test_bytearray.py (4)
During: typing of static-get-item at test_bytearray.py (4)

File "test_bytearray.py", line 4:
arr = bytearray([1, 2, 3, 4])
print(numba.njit(lambda x: x[1:3])(arr))
```

This appears to be because the getitem overload for buffer types works with borrowed references and ByteArray has `slice_is_copy` set to True. As a result `getitem_arraynd_intp` is never entered, so I assume this requires a separate overload that makes a fresh copy.

**Comment by sklam** [comment]
Categorizing as a feature request for:

- [ ] bytearray boxing
- [ ] bytearray slicing

IIRC, we have relied on memoryview interface to support minimal number of operations for bytearray. There is a `test_buffer_protocol.py` in the test that test some of the `memoryview` operations.

I also remember that we have previously advised users to use numpy array instead, but it will be useful to have more support for bytearray now that the project is more mature.
