### ISSUE TITLE
booleans and arithmetic operations fail in nopython mode

### ISSUE THREAD

**Issue by ovillellas** [numba/numba#647]
Python converts booleans to ints automatically on expressions, with True=1 and False=0. So the following happens:

```python
In [1]: 4*True
Out[1]: 4

In [2]: True*False
Out[2]: 0

In [3]: True+True
Out[3]: 2

In [4]: -True
Out[4]: -1
```

However, trying to compile the following function fails:
```python
@numba.njit('int32(bool_, bool_)')
def test(a,b):
    c = a+b
    return c
```

with the rather obscure error message (and stacktrace):

```
Traceback (most recent call last):
  File "pity.py", line 4, in <module>
    @numba.njit('int32(bool_, bool_)')
  File "/Users/continuum/anaconda/envs/numba/lib/python2.7/site-packages/numba/decorators.py", line 128, in wrapper
    disp.compile(sig)
  File "/Users/continuum/anaconda/envs/numba/lib/python2.7/site-packages/numba/dispatcher.py", line 127, in compile
    flags=flags, locals=locs)
  File "/Users/continuum/anaconda/envs/numba/lib/python2.7/site-packages/numba/compiler.py", line 107, in compile_extra
    return_type, flags, locals)
  File "/Users/continuum/anaconda/envs/numba/lib/python2.7/site-packages/numba/compiler.py", line 133, in compile_bytecode
    locals)
  File "/Users/continuum/anaconda/envs/numba/lib/python2.7/site-packages/numba/compiler.py", line 301, in type_inference_stage
    infer.propagate()
  File "/Users/continuum/anaconda/envs/numba/lib/python2.7/site-packages/numba/typeinfer.py", line 372, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "/Users/continuum/anaconda/envs/numba/lib/python2.7/site-packages/numba/typeinfer.py", line 111, in propagate
    raise TypingError("Internal error:\n%s" % e, constrain.loc)
numba.typeinfer.TypingError: Internal error:
min() arg is an empty sequence
```

**Comment by pitrou** [comment]
This was fixed somewhere along the way.
