### ISSUE TITLE
Error using np.int32(np.random.random(n_spins))

### ISSUE THREAD

**Issue by kwsgd** [numba/numba#6512]
Traceback (most recent call last):
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\targets\base.py", line 691, in cast
    impl = self._casts.find((fromty, toty))
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\targets\base.py", line 50, in find
    out = self._find(sig)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\targets\base.py", line 59, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.targets.base.OverloadSelector object at 0x0000026B60B3FD48>, (array(float64, 1d, C), int32))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\errors.py", line 662, in new_error_context
    yield
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 301, in lower_inst
    val = self.lower_assign(ty, inst)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 459, in lower_assign
    return self.lower_expr(ty, value)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 919, in lower_expr
    res = self.lower_call(resty, expr)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 711, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 890, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\targets\base.py", line 1132, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\targets\base.py", line 1157, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\targets\builtins.py", line 278, in number_constructor
    return context.cast(builder, val, valty, sig.return_type)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\targets\base.py", line 695, in cast
    "Cannot cast %s to %s: %s" % (fromty, toty, val))
NotImplementedError: Cannot cast array(float64, 1d, C) to int32: %".760" = load {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}* %"$88.8"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "aprogram.py", line 158, in <module>
    twoXtwo(L, temp, max_cycles)
  File "aprogram.py", line 139, in twoXtwo
    numerical_solution(spin_matrix, n_cycles, temp, L)
  File "aprogram.py", line 108, in numerical_solution
    quantities       = MC(spin_matrix, n_cycles, temp)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\dispatcher.py", line 395, in _compile_for_args
    raise e
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 266, in run
    raise patched_exception
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 257, in run
    stage()
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 764, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 690, in backend_nopython_mode
    self.metadata)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\compiler.py", line 1143, in native_lowering_stage
    lower.lower()
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "C:\Users\Anna-\Anaconda3\lib\contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "C:\Users\Anna-\Anaconda3\lib\site-packages\numba\six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
←[1m←[1mCannot cast array(float64, 1d, C) to int32: %".760" = load {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}, {i8*, i8*, i64, i64, double*, [1 x i64], [1 x i64]}* %"$88.8"
←[1m
File "aprogram.py", line 70:←[0m
←[1mdef MC(spin_matrix, n_cycles, temp):
    <source elided>

←[1m            ix = np.int32(np.random.random(n_spins))
←[0m            ←[1m^←[0m←[0m
←[0m
←[0m←[1m[1] During: lowering "$88.9 = call $88.3($88.8, func=$88.3, args=[Var($88.8, aprogram.py (70))], kws=(), vararg=None)" at aprogram.py (70)←[0m
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by gmarkall** [comment]
Numba 0.45.1 is quite old now - can you try again with Numba 0.51.2?

If the problem persists, could you post an executable sample of code that reproduces the issue?

**Comment by stuartarchibald** [comment]
This is still an issue on mainline, repro:
```python
from numba import njit
import numpy as np

@njit
def foo(x):
    return np.int32(np.random.random(x))

foo(12)
```
requires single element array to scalar type casting.

**Comment by stuartarchibald** [comment]
I think this is happening because there's a fall through to this:
https://github.com/numba/numba/blob/3b1e4abd1b82ab5dc60f912ad43faa6e26cd87ba/numba/core/types/abstract.py#L173-L178
from here:
https://github.com/numba/numba/blob/3b1e4abd1b82ab5dc60f912ad43faa6e26cd87ba/numba/core/typing/context.py#L239
and I'm fairly sure this is a side effect opposed to intent.
