### ISSUE TITLE
Can't compile recursive function ahead of time

### ISSUE THREAD

**Issue by nubol23** [numba/numba#6513]
When trying to compile a simple recursive function

```python
@cc.export('flood_fill', 'b1(u1[:,:], i8, i8, f8[:])')
def flood_fill(mat, i, j, coord):
    if mat[i, j] == 0:
        return
    
    directions = np.asarray([(-1, -1), (0, -1), (1, -1), (-1, 0), (1, 0), (-1, 1), (0, 1), (1, 1)])
    
    mat[i, j] = 0
    coord[0] = min(coord[0], j)
    coord[1] = min(coord[1], i)
    coord[2] = max(coord[2], j)
    coord[3] = max(coord[3], i)
    
    for dx, dy in directions:
        flood_fill(mat, i+dy, j+dx, coord)
        
    return True
```

i get

```bash
Untyped global name 'flood_fill': cannot determine Numba type of <class 'function'>
```

with the arrow pointing at the recursive call, added a dummy boolean return to ensure explicit typing of the function but still the error persists.

**Comment by gmarkall** [comment]
I can reproduce the issue with the following:

```python
from numba.pycc import CC
import numpy as np


cc = CC('repro')


@cc.export('flood_fill', 'b1(u1[:,:], i8, i8, f8[:])')
def flood_fill(mat, i, j, coord):
    if mat[i, j] == 0:
        return False

    directions = np.asarray([(-1, -1), (0, -1), (1, -1), (-1, 0), (1, 0),
                             (-1, 1), (0, 1), (1, 1)])

    mat[i, j] = 0
    coord[0] = min(coord[0], j)
    coord[1] = min(coord[1], i)
    coord[2] = max(coord[2], j)
    coord[3] = max(coord[3], i)

    for dx, dy in directions:
        flood_fill(mat, i+dy, j+dx, coord)

    return True


if __name__ == '__main__':
    cc.compile()
```

(note that the original was inconsistent in its return type - the `return` statement returned `None`, whereas the declared return type is `bool`, so I edited that to `return False`).

Compiling the function with `@njit` works as expected.

Full error with AOT compilation:

```
Traceback (most recent call last):
  File "repro.py", line 29, in <module>
    cc.compile()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/pycc/cc.py", line 214, in compile
    objects, dll_exports = self._compile_object_files(build_dir)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/pycc/cc.py", line 202, in _compile_object_files
    compiler.write_native_object(temp_obj, wrap=True)
  File "/home/gmarkall/numbadev/numba/numba/pycc/compiler.py", line 201, in write_native_object
    library = self._cull_exports()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/pycc/compiler.py", line 153, in _cull_exports
    cres = compile_extra(self.typing_context, self.context,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 602, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 352, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 414, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 394, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 385, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 94, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 71, in type_inference_stage
    infer.build_constraint()
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1024, in build_constraint
    self.constrain_statement(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1371, in constrain_statement
    self.typeof_assign(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1442, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1542, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1463, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'flood_fill': Cannot determine Numba type of <class 'function'>

File "repro.py", line 23:
def flood_fill(mat, i, j, coord):
    <source elided>
    for dx, dy in directions:
        flood_fill(mat, i+dy, j+dx, coord)
        ^
```

**Comment by stuartarchibald** [comment]
I don't think AOT supports the direct export of recursive functions. A workaround is buffer the recursive function call through a `@njit` compiled function, for example:
```python
from numba.pycc import CC
from numba import njit
import numpy as np


cc = CC('repro')


@njit
def recursive(mat, i, j, coord):
    if mat[i, j] == 0:
        return False

    directions = np.asarray([(-1, -1), (0, -1), (1, -1), (-1, 0), (1, 0),
                             (-1, 1), (0, 1), (1, 1)])

    mat[i, j] = 0
    coord[0] = min(coord[0], j)
    coord[1] = min(coord[1], i)
    coord[2] = max(coord[2], j)
    coord[3] = max(coord[3], i)

    for dx, dy in directions:
        recursive(mat, i+dy, j+dx, coord)

    return True


@cc.export('flood_fill', 'b1(u1[:,:], i8, i8, f8[:])')
def flood_fill(mat, i, j, coord):
    return recursive(mat, i, j, coord)


if __name__ == '__main__':
    cc.compile()
```

**Comment by gmarkall** [comment]
Marking as a feature request for AOT compilation of recursive functions.
