### ISSUE TITLE
Array comprehension fails against multidimensional array with nopython and typed List

### ISSUE THREAD

**Issue by dizcza** [numba/numba#6550]
## Reporting a bug

I'm reporting a regression bug for https://github.com/numba/numba/issues/3659 when `@njit` and typed lists are used.

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
import numba
import numpy as np
from numba.typed import List


@numba.njit
def main(a):
    return np.array([x[0] for x in a])


a = [np.array([1,2]), np.array([3, 4, 5])]
a = List(a)
print(main(a))
```

```
Traceback (most recent call last):
  File "/home/ulianych/PycharmProjects/elephant/elephant/temp2.py", line 13, in <module>
    print(main(a))
  File "/home/ulianych/anaconda3/envs/elephant/lib/python3.8/site-packages/numba/core/dispatcher.py", line 414, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/ulianych/anaconda3/envs/elephant/lib/python3.8/site-packages/numba/core/dispatcher.py", line 357, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<intrinsic range_iter_len>) found for signature:
 
 >>> <unknown function>(iter[ListType[array(int64, 1d, C)]->array(int64, 1d, C)])
 
There are 2 candidate implementations:
   - Of which 2 did not match due to:
   Intrinsic of function '<unknown function>': File: numba/cpython/rangeobj.py: Line 183.
     With argument(s): '(iter[ListType[array(int64, 1d, C)]->array(int64, 1d, C)])':
    No match.

During: resolving callee type: Function(<intrinsic range_iter_len>)
During: typing of call at /home/ulianych/PycharmProjects/elephant/elephant/temp2.py (8)


File "temp2.py", line 8:
def main(a):
    return np.array([x[0] for x in a])
    ^
```

Works fine for ragged lists (not typed).

Numba v0.52.0
Python 3.8.5

**Comment by stuartarchibald** [comment]
Thanks for the report. Think this is a missing feature, the `typed.List` isn't known to the `range_iter_len` intrinsic and so the closure inlining used for list comp raises.

Starter patch to fix:
```patch
diff --git a/numba/cpython/rangeobj.py b/numba/cpython/rangeobj.py
index 0f61a4ff3..7ffbe1b74 100644
--- a/numba/cpython/rangeobj.py
+++ b/numba/cpython/rangeobj.py
@@ -201,6 +201,14 @@ def range_iter_len(typingctx, val):
             iterobj = ListIterInstance(context, builder, sig.args[0], value)
             return impl_ret_untracked(context, builder, intp_t, iterobj.size)
         return signature(types.intp, val), codegen
+    elif isinstance(val, types.ListTypeIteratorType):
+        def codegen(context, builder, sig, args):
+            (value,) = args
+            intp_t = context.get_value_type(types.intp)
+            from numba.typed.listobject import ListIterInstance
+            iterobj = ListIterInstance(context, builder, sig.args[0], value)
+            return impl_ret_untracked(context, builder, intp_t, iterobj.size)
+        return signature(types.intp, val), codegen
```
