### ISSUE TITLE
dict getitem in list comprehension results in LLVM IR parsing error

### ISSUE THREAD

**Issue by Cebtenzzre** [numba/numba#6588]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

#### Example Code
```python
from numba import jit

@jit(forceobj=True)
def foo():
    mydict = {'zero': 0}
    return [mydict['zero'] for x in (1,)]

print(foo())
```
#### Traceback
```
$ python repr.py
Traceback (most recent call last):
  File "repr.py", line 8, in <module>
    print(foo())
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 433, in _compile_for_args
    raise e
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 366, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 857, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 602, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 352, in compile_extra
    return self._compile_bytecode()
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 414, in _compile_bytecode
    return self._compile_core()
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 394, in _compile_core
    raise e
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler.py", line 385, in _compile_core
    pm.run(self.state)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/object_mode_passes.py", line 120, in run_pass
    lowered = backend_object_mode()
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/object_mode_passes.py", line 115, in backend_object_mode
    return self._py_lowering_stage(state.targetctx,
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/object_mode_passes.py", line 78, in _py_lowering_stage
    lower.lower()
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/lowering.py", line 174, in lower
    self.library.add_ir_module(self.module)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/numba/core/codegen.py", line 648, in add_ir_module
    ll_module = ll.parse_assembly(ir)
  File "/home/cebtenzzre/.local/lib/python3.8/site-packages/llvmlite/binding/module.py", line 25, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))
RuntimeError: Failed in object mode pipeline (step: object mode backend)
LLVM IR parsing error
<string>:553:48: error: expected value token
  %".427" = call i8* @"PyLong_FromSsize_t"(i64 zero)
                                               ^
```

#### Software Versions
numba 0.52.0
Python 3.8

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. I suspect this problem is a result of the closure inlining pass not working correctly in this somewhat rare use case (forced object mode, with dictionary in a list comprehension).
