### ISSUE TITLE
np.where fails in @vectorize

### ISSUE THREAD

**Issue by crusaderky** [numba/numba#6624]
numba 0.52
numpy 0.19.4
python 3.8.6

numpy.where seems to only work inside ``@jit``; I can't make it work inside ``@vectorize`` or ``@guvectorize``: 
```python
@numba.vectorize(["f8(f8)"], nopython=True)
def f(a):
    return np.where(a, 1.0, 2.0)
```
Output:
```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No conversion from array(float64, 0d, C) to float64 for '$14return_value.6', defined at None
```
#### Workaround:
Use the ternary pure Python operator ``a if cond else b``.

#### Impact:
This issue impacts me because I'm trying to generate code that transparently works both with and without ``@vectorize`` decorator, and I'm forced to change the code I emit inside the function because of this issue.

**Comment by esc** [comment]
@crusaderky thank you for reporting this. For reference when using `@guvectorize` you can't or shouldn't return anything as outlined here:

https://numba.readthedocs.io/en/stable/user/vectorize.html#the-guvectorize-decorator

Also, for future reference it would make our life easier if you could submit a fully runnable reproducer, i.e. including imports and a statement to execute the code in question. That way I can simply copy and paste it into my editor to reproduce it. Like this I need to fix it up. Thanks!

**Comment by esc** [comment]
reproducer:

```
import numpy as np
import numba

@numba.vectorize(["f8(f8)"], nopython=True)
def f(a):
    return np.where(a, 1.0, 2.0)

a = np.array([1.0, 2.0, 3.0])
f(a)
```

Error:

```
File "issue6624.py", line 6:
def f(a):
    return np.where(a, 1.0, 2.0)
    ^

During: typing of assignment at issue6624.py (6)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue6624.py", line 5, in <module>
    def f(a):
  File "/Users/vhaenel/git/numba/numba/np/ufunc/decorators.py", line 125, in wrap
    vec.add(sig)
  File "/Users/vhaenel/git/numba/numba/np/ufunc/dufunc.py", line 170, in add
    return self._compile_for_argtys(args, return_type)
  File "/Users/vhaenel/git/numba/numba/np/ufunc/dufunc.py", line 218, in _compile_for_argtys
    cres, argtys, return_type = ufuncbuilder._compile_element_wise_function(
  File "/Users/vhaenel/git/numba/numba/np/ufunc/ufuncbuilder.py", line 144, in _compile_element_wise_function
    cres = nb_func.compile(sig, **targetoptions)
  File "/Users/vhaenel/git/numba/numba/np/ufunc/ufuncbuilder.py", line 93, in compile
    return self._compile_core(sig, flags, locals)
  File "/Users/vhaenel/git/numba/numba/np/ufunc/ufuncbuilder.py", line 125, in _compile_core
    cres = compiler.compile_extra(typingctx, targetctx,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 94, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 72, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 1071, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No conversion from array(float64, 0d, C) to float64 for '$14return_value.6', defined at None

File "issue6624.py", line 6:
def f(a):
    return np.where(a, 1.0, 2.0)
    ^

During: typing of assignment at issue6624.py (6)

File "issue6624.py", line 6:
def f(a):
    return np.where(a, 1.0, 2.0)
```

**Comment by esc** [comment]
@crusaderky I am not sure my reproducer is correct. The Numpy documentation states:


```
numpy.where(condition[, x, y])¶
Return elements chosen from x or y depending on condition.
```

So, I guess `a` should be a condition instead? Please clarify, thank you.

**Comment by stuartarchibald** [comment]
I think this is the 0d array not degrading to scalar problem?

**Comment by gimperiale** [comment]
@esc 
- I know guvectorize doesn't return anything. My reproducer doesn't use guvectorize; it uses vectorize.
- My reproducer is fully runnable; you literally just need to add the imports to obtain the stack trace I posted.
- numpy.where means that, for every element of condition that is (castable to) true, pick the matching element of x, else pick the matching element of y. This is downstream of general numpy broadcasting rules.

**Comment by stuartarchibald** [comment]
@gimperiale / @crusaderky What's the input value in use? Is it a 0d array?

I think the issue here is that `np.where` will return an array of the same dimension as its first argument/call `asarray` on the first argument then do the same return behaviour https://github.com/numpy/numpy/blob/v1.19.0/numpy/core/src/multiarray/multiarraymodule.c#L2950-L2956

As `@vectorize` functions need a scalar output, and Numba won't degrade a 0d array to a scalar, this leads to the above. Does that describe the issue?

**Comment by gimperiale** [comment]
@stuartarchibald the input is an arbitrary n-dimensional array.

> As @vectorize functions need a scalar output, and Numba won't degrade a 0d array to a scalar, this leads to the above. Does that describe the issue?

Yes, this is accurate.

**Comment by gimperiale** [comment]
So to recap there are two discussions here:
1. whether numba should downgrade a 0d array to scalar in this use case. It makes sense to me that it should, for the same reason that you can assign a point of a nd array to the value contained in a scalar array ``a[x, y, z] = b`` in pure numpy.
2. the fact that numpy.where should IMHO behave like a ufunc and return a scalar if the input is scalar; this is an upstream discussion for numpy and I strongly suspect that the answer would be "no because such a change would break a ton of existing user code".

**Comment by stuartarchibald** [comment]
RE above:
1. This has been a long running thing, on the one hand, it acts as a performance linter for not accidentally using arrays when scalars are fine, on the other, it causes problems like this.
2. Yes, would recommend asking on the NumPy issue tracker, but also suspect the current behaviour is too entrenched to change.

Does this help as a work around?
```python
from numba import njit, vectorize
import numpy as np
from numba.extending import overload

# python will use this version of hack
def hack(x):
    return x

# Numba will resolve hack via this so we can modify the behaviour
@overload(hack)
def ol_hack(x):
    def impl(x):
        return np.take(x, 0)
    return impl

def f(a):
    return hack(np.where(a, 1.0, 2.0))

for ndim in range(5):
    a = np.ones((2,) * ndim)
    print(f"ndim {a.ndim}")
    vectorized = vectorize(["f8(f8)"])(f)
    print(f(a))
    print(vectorized(a))
    print("")
```

**Comment by esc** [comment]
@gimperiale @stuartarchibald thank you for the clarification! I have labeled this as "bug - failure to compile". Do you by any chance recall if an issue like this exists already and if there is perhaps a duplicate?

**Comment by gimperiale** [comment]
@stuartarchibald doesn't seem to work with a function that is already recognized by numba, unless I did something wrong:

```python
import numpy
from numba.extending import overload

# Numba will resolve hack via this so we can modify the behaviour
@overload(numpy.where)
def ol_where(cond, a, b):
    def impl(cond, a, b):
        return a if cond else b
    return impl

@numba.vectorize(["f8(f8)"], nopython=True)
def f(x):
    return numpy.where(x > 0, 1, 2)


TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No conversion from array(int64, 0d, C) to float64 for '$18return_value.8', defined at None
```

I worked around the problem by defining a ufunc:
```python
@numba.vectorize(nopython=True, cache=True)
def if_(cond, a, b):
    """Like numpy.where, but as a ufunc.
    Unlike numpy.where, it returns a scalar if all inputs are scalar.
    """
    return a if cond else b

@numba.vectorize(["f8(f8)"], nopython=True)
def f(x):
    return if_(x > 0, 1, 2)

>>> f([1, 2, -1])
array([1., 1., 2.])
```

**Comment by stuartarchibald** [comment]
@gimperiale thanks for reporting back. Glad you found a workaround that suits. From memory, overloading already overloaded functions is not well defined.

**Comment by stuartarchibald** [comment]
> @gimperiale @stuartarchibald thank you for the clarification! I have labeled this as "bug - failure to compile". Do you by any chance recall if an issue like this exists already and if there is perhaps a duplicate?

@esc xref https://github.com/numba/numba/issues/4749 https://github.com/numba/numba/issues/6000 and probably others.
