### ISSUE TITLE
Cannot iterate over fields of record array

### ISSUE THREAD

**Issue by leohaim** [numba/numba#6634]
When iterating over the fields of a record array, numba complains about a not implemented getitem. 
Accessing the fields by name outside a loop works. I am using numba 0.52, the problem occurs on both Windows and linux

## This is the ipython cell that produces the error:

```python
%pylab
import numpy.random
from numba import njit

@njit
def recarriterator(rec):
    for o in 'a','b','c':
        print(rec[o][0])
    return
        
@njit
def recarriterator2(rec):
    print(rec['a'][0])
    print(rec['b'][0])
    print(rec['c'][0])
    return
        
ldd=[]
ldk=[]
keys='a','b','c'
for o in keys:
    #if not (o == 'observation_id' or o == 'report_id' or o == 'sensor_id' or o == 'source_id'):
        ldd.append(random.rand(5))
        ldk.append((o,ldd[-1].dtype))
rec = numpy.rec.fromarrays(ldd, dtype=ldk)
    
recarriterator2(rec)
recarriterator(rec)
```
## The error code:
```
Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib
0.26156099390229226
0.4919898206995005
0.363624558244539
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-1-56c6c55bddcf> in <module>
     26 
     27 recarriterator2(rec)
---> 28 recarriterator(rec)

~\anaconda3\lib\site-packages\numba\core\dispatcher.py in _compile_for_args(self, *args, **kws)
    413                 e.patch_message(msg)
    414 
--> 415             error_rewrite(e, 'typing')
    416         except errors.UnsupportedError as e:
    417             # Something unsupported is present in the user code, add help info

~\anaconda3\lib\site-packages\numba\core\dispatcher.py in error_rewrite(e, issue_type)
    356                 raise e
    357             else:
--> 358                 reraise(type(e), e, None)
    359 
    360         argtypes = []

~\anaconda3\lib\site-packages\numba\core\utils.py in reraise(tp, value, tb)
     78         value = tp()
     79     if value.__traceback__ is not tb:
---> 80         raise value.with_traceback(tb)
     81     raise value
     82 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(unaligned array(Record(a[type=float64;offset=0],b[type=float64;offset=8],c[type=float64;offset=16];24;False), 1d, C), unicode_type)
 
There are 22 candidate implementations:
  - Of which 20 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(unaligned array(Record(a[type=float64;offset=0],b[type=float64;offset=8],c[type=float64;offset=16];24;False), 1d, C), unicode_type)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'GetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 162.
    With argument(s): '(unaligned array(Record(a[type=float64;offset=0],b[type=float64;offset=8],c[type=float64;offset=16];24;False), 1d, C), unicode_type)':
   Rejected as the implementation raised a specific error:
     TypeError: unsupported array index type unicode_type in [unicode_type]
  raised from C:\Users\leopo\anaconda3\lib\site-packages\numba\core\typing\arraydecl.py:68

During: typing of intrinsic-call at <ipython-input-1-56c6c55bddcf> (8)

File "<ipython-input-1-56c6c55bddcf>", line 8:
def recarriterator(rec):
    <source elided>
    for o in 'a','b','c':
        print(rec[o][0])
        ^
```

**Comment by stuartarchibald** [comment]
Thanks for the report. RE formatting in GitHub issues, for future reference triple backticks are needed around a code block (with optional language syntax specified), for example: ` ```python <your code> ``` `. GitHub also has a basic guide to its markdown syntax available [here](https://help.github.com/articles/basic-writing-and-formatting-syntax). I've edited the above so it renders correctly.

**Comment by stuartarchibald** [comment]
I think the issue here is that Numba cannot work out what to do with a `unicode_type` as an index. In this case:
```python
@njit
def recarriterator(rec):
    for o in 'a','b','c':
        print(rec[o][0])
    return
```
Induction variable `o` is a `unicode_type` and whilst we can "see" that `rec[o]` will return the same type regardless of the runtime value of `o`, Numba cannot.

In this case:
```python
@njit
def recarriterator2(rec):
    print(rec['a'][0])
    print(rec['b'][0])
    print(rec['c'][0])
    return
```
the equivalent of the induction variable `o` above is actually now a compile time constant and so Numba can work out precisely what is going on.

I half hoped that loop body versioning with [`literal_unroll`](https://numba.readthedocs.io/en/stable/reference/pysupported.html#heterogeneous-tuples) might help and tried:
```python
import numpy.random as random
from numba import njit, literal_unroll
import numpy

keys = ('a','b','c')

@njit
def recarriterator(rec):
    for o in literal_unroll(keys):
        print(rec[o])
    return

ldd=[]
ldk=[]
for o in keys:
    ldd.append(random.rand(5))
    ldk.append((o,ldd[-1].dtype))
rec = numpy.rec.fromarrays(ldd, dtype=ldk)

recarriterator(rec)
```
but this still fails because because the `getitem` on the recarray is still dynamic. This suggests that the dynamic->static getitem rewrite pass needs running after the transform that deals with loop body versioning, and if I do that, it works:
```patch
diff --git a/numba/core/compiler.py b/numba/core/compiler.py
index <???> 100644
--- a/numba/core/compiler.py
+++ b/numba/core/compiler.py
@@ -538,6 +538,7 @@ class DefaultPassBuilder(object):
 
         pm.add_pass(FindLiterallyCalls, "find literally calls")
         pm.add_pass(LiteralUnroll, "handles literal_unroll")
+        pm.add_pass(GenericRewrites, "nopython rewrites")
 
         if state.flags.enable_ssa:
             pm.add_pass(ReconstructSSA, "ssa")
```
example with above patch:
```
$ cat issue6634.py
import numpy.random as random
from numba import njit, literal_unroll
import numpy

keys = ('a','b','c')

@njit
def recarriterator(rec):
    for o in literal_unroll(keys):
        print(rec[o])
    return

ldd=[]
ldk=[]
for o in keys:
    ldd.append(random.rand(5))
    ldk.append((o,ldd[-1].dtype))
rec = numpy.rec.fromarrays(ldd, dtype=ldk)

$ python issue6634.py
[0.65043893 0.44405371 0.39395911 0.73871605 0.33635819]
[0.91916801 0.48012113 0.03028403 0.89127616 0.09568529]
[0.78778575 0.17708125 0.18378633 0.44769406 0.22908587]
```

**Comment by stuartarchibald** [comment]
https://github.com/numba/numba/pull/6635 should fix it.

**Comment by leohaim** [comment]
Thanks, I will try asap.

I do not know if I should mention this here, but instead of using the tuple of literals for the loop, I would rather like to retrieve the loop items from the recarray itself. Outside a jitted function, for example, I can get a list of the column names like this:
    
`keys=List(rec.dtype.fields.keys())
`

I found no way to get something similar working inside a jitted function. Perhaps you can give me a hint

**Comment by stuartarchibald** [comment]
@leohaim no problem.

You're almost there with the above, it just needs a "trick" to bake the information in at compile time, you can use the [`numba.extending.overload`](https://numba.readthedocs.io/en/stable/extending/overloading-guide.html) decorator to help with that...
```python
import numpy.random as random
from numba import njit, literal_unroll
from numba.extending import overload
import numpy

def get_keys(recarr):
    pass

@overload(get_keys)
def ol_get_keys(recarr):
    keys = tuple(recarr.dtype.fields.keys())
    print(f"Type inference time, has recarr fields as: {keys}")
    return lambda recarr: keys

@njit
def recarriterator(rec):
    for o in literal_unroll(get_keys(rec)):
        print(rec[o])
    return

ldd=[]
ldk=[]
for o in ('a','b','c'):
    ldd.append(random.rand(5))
    ldk.append((o, ldd[-1].dtype))
rec = numpy.rec.fromarrays(ldd, dtype=ldk)
recarriterator(rec)
```
gives
```
$ python issue6634_2.py 
Type inference time, has recarr fields as: ('a', 'b', 'c')
[0.45558716 0.17695257 0.16769568 0.00891983 0.65667821]
[0.327091   0.80823457 0.87636252 0.38173431 0.72652096]
[0.27248001 0.78576076 0.91742059 0.23224509 0.80710958]
```

**Comment by pwuertz** [comment]
This should be working in current numba (0.55.1), right?
I'm getting the original "no implementation of getitem" error when trying to literal-loop over field names:
```python
import numpy as np
import numba as nb

dt = np.dtype([("a", np.uint8), ("b", np.uint8)])
dt_names = dt.names

@nb.njit
def test():
    rec = np.zeros(1, dtype=dt)
    for f in nb.literal_unroll(dt_names):
        rec[0][f] = 1
    return rec

test()
```
Same with `literal_unroll(("a", "b"))`.

**Comment by esc** [comment]
@pwuertz thank you for submitting this. I can confirm that I am able to reproduce on current `main` (`3781d6836d78f3467b02500b19a889039bdaf3bb`) with the following error:

```
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/issue_6634.py", line 14, in <module>
    test()
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:

 >>> setitem(Record(a[type=uint8;offset=0],b[type=uint8;offset=1];2;False), unicode_type, Literal[int](1))

There are 16 candidate implementations:
  - Of which 16 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(Record(a[type=uint8;offset=0],b[type=uint8;offset=1];2;False), unicode_type, int64)':
   No match.

During: typing of setitem at /Users/vhaenel/git/numba/issue_6634.py (11)

File "issue_6634.py", line 11:
def test():
    <source elided>
    for f in nb.literal_unroll(dt_names):
        rec[0][f] = 1
```

**Comment by stuartarchibald** [comment]
This should work:
```python
import numpy as np
import numba as nb
from numba import literal_unroll

dt = np.dtype([("a", np.uint8), ("b", np.uint8)])
dt_names = dt.names

@nb.njit
def test():
    rec = np.zeros(1, dtype=dt)
    for f in literal_unroll(dt_names):
        rec[0][f] = 1
    return rec

print(test())
```
note that `literal_unroll` is imported explicitly. This is a known bug, think it's a duplicate of https://github.com/numba/numba/issues/5344.
