### ISSUE TITLE
Nested dict-of-jitclass throws pickling error

### ISSUE THREAD

**Issue by nelson2005** [numba/numba#6640]
Numba 0.52.0, 64-bit Python 3.7.3 on Windows
Discourse discussion is [here](https://numba.discourse.group/t/how-do-i-nest-dict-of-jitclass/434)

The code below doesn't work, but seems like it ought to

```python
from numba import types, typed, njit
from numba.experimental import jitclass

@jitclass([
    ("x", types.int64),
])
class Level1:
    def __init__(self):
        self.x = 12

level1 = Level1()  # Okay, I can create a Level1 instance
level1_instance_type = Level1.class_type.instance_type
level1_kv = (types.int64, level1_instance_type)

@jitclass([
    ("level1s", types.DictType(*level1_kv)),
])
class Level2(object):
    def __init__(self):
        self.level1s = typed.Dict.empty(*level1_kv)
        self.level1s[0] = Level1()


level2 = Level2()  # Okay, I can create a Level2 instance
level2_instance_type = Level2.class_type.instance_type
level2_kv = (types.int64, level2_instance_type)

@jitclass([
    ("level2s", types.DictType(*level2_kv)),
])
class Level3(object):
    def __init__(self):
        self.level2s = typed.Dict.empty(*level2_kv)

# _pickle.PicklingError: Can't pickle <class 'numba.experimental.jitclass.base.Level1'>: it's not found as numba.experimental.jitclass.base.Level1
# level3 = Level3()
```

**Comment by stuartarchibald** [comment]
Thanks for reporting this @nelson2005, pretty sure this is a bug. CC @sklam, who might have an idea why without having to debug what's going on, else it'll need some digging around in the source. The direct problem is likely from trying to pickle a decorated class (`@jitclass`) and that in turn comes from boxing/unboxing which needs serialisation to work. This is why instantiating a `Level3` instance in a `jit` compiled function would work, there's no box/unbox needed.

**Comment by sklam** [comment]
#6977 would just give a better error:

```
Failed in nopython mode pipeline (step: native lowering)
pickling of <class 'numba.experimental.jitclass.base.JitClassType'> is disabled
```

**Comment by stuartarchibald** [comment]
Ah I forgot to uncomment the line that triggered the error. Never mind!

**Comment by esc** [comment]
This still reproduces, on OSX even with current `master` (cbb4301852d0950f15eef0a2b8c0478db5d57201):

```
 💣 zsh» python issu6640.py                                                                                                                                         :(
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/core/pythonapi.py", line 1371, in serialize_object
    gv = self.module.__serialized[obj]
KeyError: DictType[int64,instance.jitclass.Level2#7fcb5b38c610<level1s:DictType[int64,instance.jitclass.Level1#7fcb54ac9fd0<x:int64>]<iv=None>>]<iv=None>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "issu6640.py", line 41, in <module>
    level3 = Level3()
  File "/Users/vhaenel/git/numba/numba/experimental/jitclass/base.py", line 124, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 440, in _compile_for_args
    raise e
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 373, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 911, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 80, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 94, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 107, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 675, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 419, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 483, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 462, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 453, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 398, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/vhaenel/git/numba/numba/core/lowering.py", line 242, in create_cpython_wrapper
    self.context.create_cpython_wrapper(self.library, self.fndesc,
  File "/Users/vhaenel/git/numba/numba/core/cpu.py", line 183, in create_cpython_wrapper
    builder.build()
  File "/Users/vhaenel/git/numba/numba/core/callwrapper.py", line 123, in build
    self.build_wrapper(api, builder, closure, args, kws)
  File "/Users/vhaenel/git/numba/numba/core/callwrapper.py", line 188, in build_wrapper
    obj = api.from_native_return(retty, retval, env_manager)
  File "/Users/vhaenel/git/numba/numba/core/pythonapi.py", line 1398, in from_native_return
    out = self.from_native_value(typ, val, env_manager)
  File "/Users/vhaenel/git/numba/numba/core/pythonapi.py", line 1412, in from_native_value
    return impl(typ, val, c)
  File "/Users/vhaenel/git/numba/numba/experimental/jitclass/boxing.py", line 139, in _box_class_instance
    box_subclassed = _specialize_box(typ)
  File "/Users/vhaenel/git/numba/numba/experimental/jitclass/boxing.py", line 122, in _specialize_box
    fast_fget = fget.compile((typ,))
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 911, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 80, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 94, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 107, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 675, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 419, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 483, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 462, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 453, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 398, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/vhaenel/git/numba/numba/core/lowering.py", line 242, in create_cpython_wrapper
    self.context.create_cpython_wrapper(self.library, self.fndesc,
  File "/Users/vhaenel/git/numba/numba/core/cpu.py", line 183, in create_cpython_wrapper
    builder.build()
  File "/Users/vhaenel/git/numba/numba/core/callwrapper.py", line 123, in build
    self.build_wrapper(api, builder, closure, args, kws)
  File "/Users/vhaenel/git/numba/numba/core/callwrapper.py", line 188, in build_wrapper
    obj = api.from_native_return(retty, retval, env_manager)
  File "/Users/vhaenel/git/numba/numba/core/pythonapi.py", line 1398, in from_native_return
    out = self.from_native_value(typ, val, env_manager)
  File "/Users/vhaenel/git/numba/numba/core/pythonapi.py", line 1412, in from_native_value
    return impl(typ, val, c)
  File "/Users/vhaenel/git/numba/numba/typed/typeddict.py", line 242, in box_dicttype
    dicttype_obj = c.pyapi.unserialize(c.pyapi.serialize_object(typ))
  File "/Users/vhaenel/git/numba/numba/core/pythonapi.py", line 1373, in serialize_object
    struct = self.serialize_uncached(obj)
  File "/Users/vhaenel/git/numba/numba/core/pythonapi.py", line 1344, in serialize_uncached
    data = serialize.dumps(obj)
  File "/Users/vhaenel/git/numba/numba/core/serialize.py", line 57, in dumps
    p.dump(obj)
  File "/Users/vhaenel/git/numba/numba/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/Users/vhaenel/git/numba/numba/core/serialize.py", line 185, in reducer_override
    _no_pickle(obj)  # noreturn
  File "/Users/vhaenel/git/numba/numba/core/serialize.py", line 164, in _no_pickle
    raise pickle.PicklingError(f"Pickling of {type(obj)} is unsupported")
_pickle.PicklingError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: native lowering)
Pickling of <class 'numba.experimental.jitclass.base.JitClassType'> is unsupported
```

**Comment by gmarkall** [comment]
@esc does this still need triage? It seems to clearly be a bug.

**Comment by tombh** [comment]
I'm seeing something similar on 0.53.1 with nested list-of-jitclass:

``` python
from typing import List
import numba
from numba.experimental import jitclass


@jitclass
class Grandchild:
    def __init__(self):
        print("ok")


@jitclass
class Child:
    grandchildren: List[Grandchild]

    def __init__(self):
        self.grandchildren = numba.typed.List([Grandchild()])


@jitclass
class Parent:
    children: List[Child]

    def __init__(self):
        self.children = numba.typed.List([Child()])


Child()
# ok

Parent()
# Can't pickle <class 'numba.experimental.jitclass.base.Grandchild'>: attribute lookup Grandchild on numba.experimental.jitclass.base failed

```

I'm using poetry to install numba which makes it hard to try master because of having to compile llvmlite, but willing to try if there's a chance of a fix.

**Comment by esc** [comment]
@tombh thanks I can confirm I am seeing this on `master` (5f6859908e7b73f7e1baf30381bac9e863640210) too.

**Comment by Azmisov** [comment]
For those that missed the discourse link mentioned in OP's report, a workaround is to always access the jitclass from a jitted function/method. As long as it never needs to be boxed for the python interpreter, the pickling error won't occur. Following @nelson2005's idea,  you can put a jitclass in a typed List and pass it around without it getting boxed.

Here is an example where I have nesting A->B->C, but then I add an additional pure python class CProxy. The CProxy utilizes the workaround, wrapping C in a typed List and proxying all the methods for it. As long as we don't access the C instance directly, no errors are thrown. Theoretically it is possible to proxy any operation or member access you wish to perform from the interpreter (though perhaps not practical for very complex data structures).

```python
from numba import uint64, njit
from numba.types import ListType, DictType
from numba.typed import List, Dict
from numba.extending import as_numba_type
from numba.experimental import jitclass

@jitclass
class A:
	def __init__(self): pass

@jitclass
class B:
	a: ListType(A)
	def __init__(self): pass

BDictType = (uint64, as_numba_type(B))
@jitclass
class C:
	b: DictType(*BDictType)
	def __init__(self):
		self.b = Dict.empty(*BDictType)
	def length(self):
		return len(self.b)

class CProxy:
	def __init__(self):
		self._ref = List.empty_list(as_numba_type(C))
		CProxy._wrap(self._ref)
	@njit
	def _wrap(ref):
		""" construct class of interest inside jitted function;
			as long as we don't try to access ref[0] from interpreter, pickling error won't arise
		"""
		ref.append(C())
	@njit
	def _length(ref):
		""" calls C through jitted layer to avoid python interpreter boxing """
		return ref[0].length()
	def length(self):
		""" proxy the actual method """
		return CProxy._length(self._ref)

c = CProxy()
print(c.length())
```

**Comment by Azmisov** [comment]
I've written a function which can auto-generate such a Proxy class. Note that it only creates proxies of instance methods:

```python
import inspect
from inspect import Parameter, Signature
from numba import njit
from numba.typed import List
from numba.extending import as_numba_type

def make_jitclass_proxy(cls, njit_signatures:dict=None):
	""" Create a proxy class to provide indirect access to a jitclass. This can be used as a
	 	workaround for a bug in numba where nested jitclass's triggers a pickling error when trying
	  	to access via the python interpreter. This uses reflection to wrap all the instance
		function-style methods, including ``__init__`` and any dunder methods. Attribute/property
		access is not proxied, but this function could be enhanced to add such.

		See https://github.com/numba/numba/issues/6640#issuecomment-1784009756
	
		:param cls: class to make a proxy of
		:param njit_signatures: optional signature objects to pass to @njit when creating proxied
			methods; the first argument will always be ListType(as_numba_type(cls))
		:returns: proxied class
	"""
	class Proxy:
		__slots__ = ["_ref"]
		_methods = {}

	methods = Proxy._methods
	def attach_method(k, v):
		sig = inspect.signature(v)

		# strip defaults/annotations for the jitted method signature;
		# replaces "self" arg with __numba_proxy;
		# constructs arguments to pass to jitted method
		sig_python = []
		sig_proxy = []
		sig_args = []
		self_kind = Parameter.POSITIONAL_OR_KEYWORD
		for p in sig.parameters.values():
			if p.kind == Parameter.POSITIONAL_ONLY:
				self_kind = p.kind
			# ignore first positional, which is the "self" arg
			if not sig_proxy and (
					p.kind == Parameter.POSITIONAL_ONLY or
					p.kind == Parameter.POSITIONAL_OR_KEYWORD
			):
				continue
			sig_python.append(p)
			sig_proxy.append(p.replace(
				default=Parameter.empty,
				annotation=Parameter.empty
			))
			# build argument to be passed to actual method
			prefix = ""
			name = p.name
			if p.kind == Parameter.VAR_POSITIONAL:
				prefix = "*"
			elif p.kind == Parameter.KEYWORD_ONLY:
				prefix = name+"="
			elif p.kind == Parameter.VAR_KEYWORD:
				prefix = "**"
			sig_args.append(prefix+name)
		sig_python = Signature(sig_python)
		# used in place of "self" argument
		sig_proxy.insert(0, Parameter("__numba_proxy_ref", self_kind))
		sig_proxy = str(Signature(sig_proxy))
		sig_args = ', '.join(sig_args)

		# build proxy method
		fn = f"def {k}{sig_proxy}:"
		if k == "__init__":
			fn += f"\n\t__numba_proxy_ref.append({cls.__name__}({sig_args}))"
		else:
			fn += f"\n\treturn __numba_proxy_ref[0].{k}({sig_args})"
		#print(fn) # can use to debug complex signatures
		exec(fn, None, methods)
		# manual signature specified for use?
		if njit_signatures is not None and k in njit_signatures:
			decorator = njit(njit_signatures[k])
		else:
			decorator = njit()
		methods[k] = decorator(methods[k])

		# python interface for the method
		if k == "__init__":
			def interface(self, *args, **kwargs):
				ba = sig_python.bind(*args, **kwargs)
				ba.apply_defaults()
				self._ref = List.empty_list(as_numba_type(cls))
				self.__class__._methods[k](self._ref, *args, **kwargs)
		else:
			def interface(self, *args, **kwargs):
				ba = sig_python.bind(*args, **kwargs)
				ba.apply_defaults()
				return self.__class__._methods[k](self._ref, *args, **kwargs)
		setattr(Proxy, k, interface)

	# find instance methods of the raw class which jitclass wraps
	attrs = cls.__mro__[1].__dict__
	for k,v in attrs.items():
		if inspect.isfunction(v):
			# closure
			attach_method(k, v)

	return Proxy
```

Use it like so:

```python
CProxy = make_jitclass_proxy(C)
c = CProxy()
print(c.length())
```

**Comment by shaunc** [comment]
I'm getting this error too, but get it when I try to use `nb.objmode()` and use a list of jitclasses. It seems the workaround will not help me because I get the error immediately on entering objmode. (Unless someone can thing of a way around?)

```py
@nb.njit  # type: ignore
def load_intermediates(
    runner_id: np.int64,
    intermediates: list[TDataRingFloat32],
):
    """
    Load intermediates into datarings.

    Used in restart mode.

    Args:
        runner_id: id to find runner.
        intermediates: list of intermediates to load.
    """
    with nb.objmode():  # type: ignore
        TrainingRunner.instances[runner_id].load_intermediates(intermediates)
```
where `intermediates` is a list of jitclass instances.

**Comment by shrealist** [comment]
Modify the dumps function on line 52 of numba/core/serialize.py:

def dumps(obj):
    """Similar to `pickle.dumps()`. Returns the serialized object in bytes.
    """
    pickler = NumbaPickler
    with io.BytesIO() as buf:
        # p = pickler(buf, protocol=4)
        p = pickle._Pickler(buf, protocol=4)
        p.dump(obj)
        pickled = buf.getvalue()

    return pickled

and the program will run successfully

**Comment by Azmisov** [comment]
@shaunc Late reply, but I'm pretty sure in your case objmode is going to try to unbox the list of Numba jitclass's as a regular Python list. And this would of course trigger the pickling error. The general workaround is to:
- hold the value(s) inside a `numba.typed.List`; violated if you unbox the list via objmode
- never access the values themselves outside of a jitted function/class; violated if you try access list elements outside of njit

I think you'd have to redesign your code slightly to avoid passing in/out of numba:
```python
_cur_intermediates = None

@njit
def _load_intermediates(intermediates: numba.typed.List):
    with objmode():
        Foo.load_intermediates()

def load_intermediates(intermediates: numba.typed.List):
    # global variable to avoid passing out of numba and causing unboxing errors
    _cur_intermediates = intermediates
    return _load_intermediates(intermediates)

class Foo:
    def load_intermediates(self):
        intermediates = _cur_intermediates
        # Note: cannot access intermediates[i] or it will trigger pickling error
        # need to pass to another jitted function to manipulate individual elements
        ...
```

**Comment by shaunc** [comment]
Thank you @Azmisov! I think we stumbled on something of the sort after much ad-hoc experimentation. The explanation is helpful. Odd that it needs to unbox like this if it is declared and passed in as a typed list.
