### ISSUE TITLE
typed.List segfault, maybe from empty list.

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6644]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This segfaults.
```python
from numba import njit
import numpy as np
from numba.typed import List

@njit
def demo_list_keys(nkeys):
    np.random.seed(0)
    # create some random sized lists for keys
    tl = List()
    for _ in range(nkeys):
        tl.append(List([x for x in range(np.random.randint(10))]))
    print(tl)

    for item in tl:
        print(item)

demo_list_keys(5)
```

**Comment by stuartarchibald** [comment]
`NUMBA_OPT=0 python issue6644.py` works fine.

**Comment by stuartarchibald** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
0x00007fa9cdfe20ab in cpython::numba::typed::typedlist::_length$2422(ListType$5bint64$5d) ()
(gdb) bt
#0  0x00007fa9cdfe20ab in cpython::numba::typed::typedlist::_length$2422(ListType$5bint64$5d) ()
#1  0x00007fa9e358c4ec in call_cfunc(Dispatcher*, _object*, _object*, _object*, _object*) ()
```

**Comment by stuartarchibald** [comment]
This hangs:
```python
from numba import njit, gdb
import numpy as np
from numba.typed import List

@njit(debug=True)
def foo():
    z = List()
    z.append(1)

    tl = List()
    tl.append(z)

    print(tl)

    for item in tl:
        len(item)

foo()
```

**Comment by stuartarchibald** [comment]
Debugging...
```
NUMBA_LLVM_REFPRUNE_PASS=1 NUMBA_LLVM_REFPRUNE_FLAGS='per_bb,diamond,fanout_raise' NUMBA_NUMBA_OPT=3 python issue6644.py
```
the `fanout_raise` seems to switch the reported problem on/off with this script.
```python
from numba import njit, gdb
import numpy as np
from numba.typed import List

@njit(debug=True)
def foo():
    #gdb()
    z = List()
    z.append(1)

    tl = List()
    tl.append(z)

    print(tl)
    for item in tl:
        len(item)

foo.compile(())
print(foo.inspect_cfg(foo.signatures[0], strip_ir=False, interleave=True, highlight=True).display(view=True))
print(foo.inspect_disasm_cfg(foo.signatures[0]))
foo()
```
I've left in all the debug output generation.

**Comment by sklam** [comment]
The `fanout_raise` prune around:

```python
    print(tl)
    for item in tl:
        len(item)
```

seems legal by looking at the output of `inspect_cfg`. However, turning on `_debug_print` in `nrtdynmod.py` shows the premature free...

without `fanout_raise`:

```
...
*** NRT_Decref 4 [0x7fbf6e822410]
*** NRT_Decref 3 [0x7fbf6e822410]
[[1]]
*** NRT_Decref 1 [0x7fbf6e815b00]
*** NRT_Decref 1 [0x7fbf6e822410]
```

with `fanout_raise`:

```
...
*** NRT_Decref 3 [0x7fc4d36c6c50]
*** NRT_Decref 1 [0x7fc4d36c6c50]
[[1]]
```

Note the `[[1]]` is from the `print(tl)`.

**Comment by sklam** [comment]
I am suspecting that the issue is related with the boxing at `print()`. Not sure what it is yet.

**Comment by stuartarchibald** [comment]
> I am suspecting that the issue is related with the boxing at `print()`. Not sure what it is yet.

I conclude the same, from the CFG output, the prune looks legal. This is probably pointing to some issue with `print`.
