### ISSUE TITLE
Type of #4 arg mismatch: i1 != i32

### ISSUE THREAD

**Issue by elenichri** [numba/numba#6649]
Hello.

I was running the cellbench.ipynb from the mars tool (https://github.com/snap-stanford/mars) and got the following error. Could you please help me understand the problem here?

>>> sc.pp.neighbors(adata, n_neighbors=30, use_rep='X')
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/errors.py", line 491, in new_error_context
    yield
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 265, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 411, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 743, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 709, in lower_call
    res = impl(self.builder, argvals)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/targets/base.py", line 1043, in __call__
    return self._imp(self._context, builder, self._sig, args)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/targets/arrayobj.py", line 3262, in numpy_zeros_nd
    _zero_fill_array(context, builder, ary)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/targets/arrayobj.py", line 3191, in _zero_fill_array
    cgutils.memset(builder, ary.data, builder.mul(ary.itemsize, ary.nitems), 0)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/cgutils.py", line 847, in memset
    builder.call(fn, [ptr, value, size, int32_t(0), bool_t(0)])
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/llvmlite/ir/builder.py", line 851, in call
    cconv=cconv, tail=tail, fastmath=fastmath)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/llvmlite/ir/instructions.py", line 84, in __init__
    raise TypeError(msg)
TypeError: Type of #4 arg mismatch: i1 != i32

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/scanpy/neighbors/__init__.py", line 95, in neighbors
    random_state=random_state,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/scanpy/neighbors/__init__.py", line 683, in compute_neighbors
    self.n_neighbors,
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/scanpy/neighbors/__init__.py", line 321, in compute_connectivities_umap
    local_connectivity=local_connectivity)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/umap/umap_.py", line 602, in fuzzy_simplicial_set
    knn_dists, float(n_neighbors), local_connectivity=float(local_connectivity),
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 360, in _compile_for_args
    raise e
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 311, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 618, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/dispatcher.py", line 83, in compile
    pipeline_class=self.pipeline_class)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 871, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 365, in compile_extra
    return self._compile_bytecode()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 802, in _compile_bytecode
    return self._compile_core()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 789, in _compile_core
    res = pm.run(self.status)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 251, in run
    raise patched_exception
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 243, in run
    stage()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 676, in stage_nopython_backend
    self._backend(lowerfn, objectmode=False)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 626, in _backend
    lowered = lowerfn()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 613, in backend_nopython_mode
    self.flags)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/compiler.py", line 990, in native_lowering_stage
    lower.lower()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 135, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 176, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 201, in lower_function_body
    self.lower_block(block)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/lowering.py", line 216, in lower_block
    self.lower_inst(inst)
  File "/home/ubuntu/anaconda3/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/errors.py", line 499, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/ubuntu/anaconda3/lib/python3.6/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed at nopython (nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "../anaconda3/lib/python3.6/site-packages/umap/umap_.py", line 154:
def smooth_knn_dist(distances, k, n_iter=64, local_connectivity=1.0, bandwidth=1.0):
    <source elided>
    target = np.log2(k) * bandwidth
    rho = np.zeros(distances.shape[0], dtype=np.float32)
    ^
[1] During: lowering "$0.16 = call $0.8($0.12, func=$0.8, args=[Var($0.12, /home/ubuntu/anaconda3/lib/python3.6/site-packages/umap/umap_.py (154))], kws=[('dtype', Var($0.14, /home/ubuntu/anaconda3/lib/python3.6/site-packages/umap/umap_.py (154)))], vararg=None)" at /home/ubuntu/anaconda3/lib/python3.6/site-packages/umap/umap_.py (154)
-------------------------------------------------------------------------------

**Comment by esc** [comment]
@elenichri without a reproducer (the code that causes this exception), we will be unable to diagnose the exact root cause of the issue you are seeing. However, having said that the stack trace looks something you get with an `llvmlite` version mismatch. To further debug this issue, please update with the following information:

* What code was run to produce the above?
* Which versions of Numba and llvmlite do you have installed and which method did you use to install them?

**Comment by elenichri** [comment]
Hello esc, thank you very much for the prompt reply.
I was running _cellbench.ipynb_ from the mars repository [https://github.com/snap-stanford/mars/blob/master/notebooks/cellbench.ipynb]

The error appeared when I ran the command `sc.pp.neighbors(adata, n_neighbors=30, use_rep='X')`

I have llmvlite==0.32.1 and numba==0.38.0 installed.

Actually, the requirements.txt of the respective github package that I am running, state numba==0.45.0. But I could not install this version. I remember I had issues with running the requirements.txt. There is no explicit requirement for llmvlite but I had the following error when I tried to import scnpy.api
`Error that I got when importing scnpy.api as sc
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'`

I overcame the above error by installing llmvlite using
`pip install -U llvmlite==0.32.1`

I installed numba via conda...

Thanks a lot for your help!

**Comment by esc** [comment]
@elenichri thank you for updating the issue. This does look like a versioning mismatch indeed. The Numba version 0.38.0 is now almost 3 years old. I did some research and the correct llvmlite version you need is 0.23.2. In general you should be able to install the correct llvmlite version for Numba by doing:

```
conda install numba==0.38.0
```

Perhaps you could try that, maybe it will help?

**Comment by esc** [comment]
It may also be worth reaching out to the developers of Mars, requesting an update of the dependencies for the notebook in question.

**Comment by elenichri** [comment]
@esc Thank you very much. Upgrating numba worked :)

**Comment by esc** [comment]
@elenichri I am glad, thank you for reporting back. Please don't hesitate to get in touch should you hit any more snags and thank you for using Numba!
