### ISSUE TITLE
'Bad token in signature' with @guvectorize

### ISSUE THREAD

**Issue by yohplala** [numba/numba#6690]
- [x] I have tried using the version 0.51.2 of Numba
- [x] I have included a self contained code sample to reproduce the problem

Hi,
I am sorry, I am aware it is more a 'usage' question or perhaps a 'feature request'.
I have posted the question on [SO here](https://stackoverflow.com/questions/66052723/bad-token-in-signature-with-numba-guvectorize), but it does not meet much success.

Please, can we setup a constant number of columns for a result array in function signature?
I have tried this way, but get here below error message.

```python
import numpy as np
from numba import guvectorize

@guvectorize('void(float64[:], float64, uint32[:,2])', '(m),()->(m,2)', nopython=True)
def array_copy(data, delta, result):
    for i, val in np.ndenumerate(data):
        # Open i.
        i, = i
        result[i,:] = [i, int(val)+delta]

data = np.arange(3, dtype='float64')
res = np.zeros((data.shape[0], 2), dtype='uint32')
array_copy(data, 3, res)
```

```python
Traceback (most recent call last):

  File "<ipython-input-17-63f8983bbf61>", line 5, in <module>
    def array_copy(data, delta, result):

  File "/home/pierre/anaconda3/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 177, in wrap
    guvec = GUVectorize(func, signature, **kws)

  File "/home/pierre/anaconda3/lib/python3.8/site-packages/numba/np/ufunc/decorators.py", line 49, in __new__
    return imp(func, signature, identity=identity, cache=cache,

  File "/home/pierre/anaconda3/lib/python3.8/site-packages/numba/np/ufunc/ufuncbuilder.py", line 298, in __init__
    self.sin, self.sout = parse_signature(signature)

  File "/home/pierre/anaconda3/lib/python3.8/site-packages/numba/np/ufunc/sigparse.py", line 49, in parse_signature
    outputs = list(parse(outs))

  File "/home/pierre/anaconda3/lib/python3.8/site-packages/numba/np/ufunc/sigparse.py", line 35, in parse
    raise ValueError('bad token in signature "%s"' % tok[1])

ValueError: bad token in signature "2"
```

**Comment by esc** [comment]
@yohplala thank you for asking about this. As far as I can tell this feature is not yet supported by Numba.

**Comment by sklam** [comment]
Related NBEP: https://numpy.org/neps/nep-0020-gufunc-signature-enhancement.html

**Comment by esc** [comment]
Also, important to note that: `uint32[:,2]` isn't valid code in this case.

**Comment by yohplala** [comment]
> Also, important to note that: `uint32[:,2]` isn't valid code in this case.

Thanks for the tip. What would be valid code then?

**Comment by esc** [comment]
@yohplala I am not sure, but it may be that `uint32[:,:]` is the only legitmate answer, but maybe the following helps:

```
In [1]: from numba import uint32

In [2]: uint32[:,2]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-c343ab4fd798> in <module>
----> 1 uint32[:,2]

~/git/numba/numba/core/types/abstract.py in __getitem__(self, args)
    183         """
    184         from numba.core.types import Array
--> 185         ndim, layout = self._determine_array_spec(args)
    186         return Array(dtype=self, ndim=ndim, layout=layout)
    187

~/git/numba/numba/core/types/abstract.py in _determine_array_spec(self, args)
    208         else:
    209             # Raise a KeyError to not be handled by collection constructors (e.g. list).
--> 210             raise KeyError(f"Can only index numba types with slices with no start or stop, got {args}.")
    211
    212         return ndim, layout

KeyError: 'Can only index numba types with slices with no start or stop, got (slice(None, None, None), 2).'

In [3]: uint32[:,:]
Out[3]: array(uint32, 2d, A)
```

**Comment by esc** [comment]
@yohplala so, to follow up, from what I know, the shape of the array is not part of the type specification, only the dimensionality.

**Comment by yohplala** [comment]
thanks a lot for your help @esc !

**Comment by yohplala** [comment]
I confirm the issue is still open. A PR appears to have been proposed, but not merged yet.

**Comment by esc** [comment]
@yohplala thank you for following up on this, do you happen to know the ID of the PR being proposed?

**Comment by yohplala** [comment]
Hi @esc , it is just mentionned above : #6694

**Comment by esc** [comment]
@yohplala thank you kindly, I had missed that. I have relabelled this issue accordingly now and thank you very much for bringing this to our attention!

**Comment by yohplala** [comment]
> @yohplala thank you kindly, I had missed that. I have relabelled this issue accordingly now and thank you very much for bringing this to our attention!

No worries, thank you for helping @esc !
I only responded to the bot pinging us :)

**Comment by ClementMaliet** [comment]
Hello, any news on this front ? The PR was marked as ready to review two years ago.

**Comment by esc** [comment]
> Hello, any news on this front ? The PR was marked as ready to review two years ago.

No, no news on this front. Looks like the PR was never reviewed, is now stale and conflicting with `main`. This happens in open-source development sometimes for various reasons. I know this can be disappointing.

@ClementMaliet if you are interested in this I might suggest adopting the pull-request, resolving the conflicts, creating a fresh PR and maybe you will get lucky and find someone to review it! 🍀
