### ISSUE TITLE
CUDA parallel testing sometimes has an issue with the driver and/or runtime API

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#6703]
Lately I've occasionally been seeing something going wrong with initializing CUDA when running the testsuite in parallel:

```
$ python -m numba.runtests numba.cuda.tests.cudapy -vf -m
Parallel: 329. Serial: 585
test_signature_3 (numba.cuda.tests.cudapy.test_gufunc_scheduling.TestGUFuncScheduling) ... ok
test_signature_2 (numba.cuda.tests.cudapy.test_gufunc_scheduling.TestGUFuncScheduling) ... ok
test_signature_7 (numba.cuda.tests.cudapy.test_gufunc_scheduling.TestGUFuncScheduling) ... ok
test_signature_4 (numba.cuda.tests.cudapy.test_gufunc_scheduling.TestGUFuncScheduling) ... ok
test_signature_5 (numba.cuda.tests.cudapy.test_gufunc_scheduling.TestGUFuncScheduling) ... ok
test_signature_6 (numba.cuda.tests.cudapy.test_gufunc_scheduling.TestGUFuncScheduling) ... ok
test_signature_1 (numba.cuda.tests.cudapy.test_gufunc_scheduling.TestGUFuncScheduling) ... ok
test_const_string (numba.cuda.tests.cudapy.test_const_string.TestCudaConstString) ... ok
test_device_function (numba.cuda.tests.cudapy.test_compiler.TestCompileToPTX) ... ERROR

======================================================================
ERROR: test_device_function (numba.cuda.tests.cudapy.test_compiler.TestCompileToPTX)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_compiler.py", line 33, in test_device_function
    ptx, resty = compile_ptx(add, args, device=True)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 112, in compile_ptx
    arch = nvvm.get_arch_option(*cc)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 386, in get_arch_option
    arch = find_closest_arch((major, minor))
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 359, in find_closest_arch
    raise NvvmSupportError(msg)
numba.cuda.cudadrv.error.NvvmSupportError: No supported GPU compute capabilities found. Please check your cudatoolkit version matches your CUDA version.

----------------------------------------------------------------------
Ran 9 tests in 0.227s

FAILED (errors=1)
```

I see this occur with different branches.

**Comment by gmarkall** [comment]
Note - there's a chance that the cause is that I have a damaged CUDA installation, but I'm going to keep this issue open to track any further notes on this issue.

**Comment by gmarkall** [comment]
I just realised this always happens when I run the test package `numba.cuda.tests.cudapy` with the `-m` flag - something about the initialization of CUDA when `cudapy` runs first (as opposed to `cudadrv`) causes this.

**Comment by gmarkall** [comment]
`TestCompileToPTX` is erroring because it is marked as a normal test case (`unittest.TestCase`) and not a CUDA test case, on the assumption that it doesn't require a CUDA context. Some of its tests run in a child process that then tries to get the supported compute capabilities using `cudaRuntimeGetVersion` in order to use NVVM:

```
======================================================================
ERROR: test_device_function_with_debug (numba.cuda.tests.cudapy.test_compiler.TestCompileToPTX)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/tests/cudapy/test_compiler.py", line 80, in test_device_function_with_debug
    ptx, resty = compile_ptx(f, [], device=True, debug=True)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 221, in compile_ptx
    ptx = lib.get_asm_str(cc=cc)
  File "/home/gmarkall/numbadev/numba/numba/cuda/codegen.py", line 110, in get_asm_str
    arch = nvvm.get_arch_option(*cc)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 421, in get_arch_option
    arch = find_closest_arch((major, minor))
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 389, in find_closest_arch
    supported_cc = get_supported_ccs()
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/nvvm.py", line 348, in get_supported_ccs
    cudart_version_major, cudart_version_minor = runtime.get_version()
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/runtime.py", line 113, in get_version
    self.cudaRuntimeGetVersion(ctypes.byref(rtver))
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/runtime.py", line 82, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/runtime.py", line 91, in _check_error
    raise CudaRuntimeAPIError(retcode, msg)
numba.cuda.cudadrv.runtime.CudaRuntimeAPIError: [3] Call to cudaRuntimeGetVersion results in CUDA_ERROR_NOT_INITIALIZED
```

For some child processes it returns that error.
