### ISSUE TITLE
As discussed privately, this will depend on `dot()` support an integer version.  We will defer this problem.

### ISSUE THREAD

**Issue by slayoo** [numba/numba#6714]
As discussed privately, this will depend on `dot()` support an integer version.  We will defer this problem.

_Originally posted by @sklam in https://github.com/numba/numba/pull/2134#discussion_r80932581_

**Comment by slayoo** [comment]
As mentioned above, numba's version of np.dot() only supports  float and complex arrays:

```python
import numba, numpy

@numba.njit()
def test(a, b):
    return numpy.dot(a, b)

if __name__ == '__main__':
    print(numba.__version__)
    a = numpy.empty((10,), dtype=numpy.int)
    b = numpy.empty((10,), dtype=numpy.int)
    test(a, b)
```
gives
```
0.52.0
Traceback (most recent call last):
  File "/home/slayoo/Downloads/test.py", line 11, in <module>
    test(a, b)
  File "/home/slayoo/devel/venvs/python3.8/lib/python3.8/site-packages/numba/core/dispatcher.py", line 414, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/slayoo/devel/venvs/python3.8/lib/python3.8/site-packages/numba/core/dispatcher.py", line 357, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function dot at 0x7fd66d299550>) found for signature:
 
 >>> dot(array(int64, 1d, C), array(int64, 1d, C))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'dot': File: numba/core/typing/npydecl.py: Line 953.
    With argument(s): '(array(int64, 1d, C), array(int64, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: np.dot() only supported on float and complex arrays
  raised from /home/slayoo/devel/venvs/python3.8/lib/python3.8/site-packages/numba/core/typing/npydecl.py:938

During: resolving callee type: Function(<function dot at 0x7fd66d299550>)
During: typing of call at /home/slayoo/Downloads/test.py (5)


File "test.py", line 5:
def test(a, b):
    return numpy.dot(a, b)
    ^


```

**Comment by gmarkall** [comment]
Thanks for the request! I'm marking this for triage for now, so it can be discussed at the next triage meeting.

**Comment by stuartarchibald** [comment]
From memory, support for this wasn't written in part as a performance linting behaviour. This to place the onus on the user to decide an appropriate floating point type in which to do the operation and write an explicit cast. I don't think there's any technical reason why the behaviour of NumPy could not be replicated.

**Comment by esc** [comment]
@slayoo thank you for pinging on this. I took a closer look and devised this initial attempt:

```
diff --git i/numba/core/typing/npydecl.py w/numba/core/typing/npydecl.py
index d3fdae3955..38f10ea1a5 100644
--- i/numba/core/typing/npydecl.py
+++ w/numba/core/typing/npydecl.py
@@ -937,7 +937,7 @@ class MatMulTyperMixin(object):
         if not all(x.dtype == a.dtype for x in all_args):
             raise TypingError("%s arguments must all have "
                               "the same dtype" % (self.func_name,))
-        if not isinstance(a.dtype, (types.Float, types.Complex)):
+        if not isinstance(a.dtype, (types.Integer, types.Float, types.Complex)):
             raise TypingError("%s only supported on "
                               "float and complex arrays"
                               % (self.func_name,))
```

But unfortunately, this yields a different error:

```
$ python issue6741.py                                                                                                                                        :(
0.54.0dev0+452.g145e4435c9.dirty
Traceback (most recent call last):
  File "/Users/esc/git/numba/numba/core/typeinfer.py", line 154, in propagate
    constraint(typeinfer)
  File "/Users/esc/git/numba/numba/core/typeinfer.py", line 566, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/Users/esc/git/numba/numba/core/typeinfer.py", line 586, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/Users/esc/git/numba/numba/core/typeinfer.py", line 1538, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/Users/esc/git/numba/numba/core/typing/context.py", line 212, in resolve_function_type
    raise last_exception
  File "/Users/esc/git/numba/numba/core/typing/context.py", line 195, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/Users/esc/git/numba/numba/core/typing/context.py", line 247, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/Users/esc/git/numba/numba/core/types/functions.py", line 348, in get_call_type
    failures.raise_error()
  File "/Users/esc/git/numba/numba/core/types/functions.py", line 227, in raise_error
    raise errors.TypingError(self.format())
numba.core.errors.TypingError: No implementation of function Function(<function dot at 0x7f99b2be9a60>) found for signature:

 >>> dot(array(int64, 1d, C), array(int64, 1d, C))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function '_OverloadWrapper._build.<locals>.ol_generated': File: numba/core/overload_glue.py: Line 106.
    With argument(s): '(array(int64, 1d, C), array(int64, 1d, C))':
   Rejected as the implementation raised a specific error:
     LoweringError: Failed in nopython mode pipeline (step: native lowering)
   unsupported dtype for <BLAS function>()

   File "<string>", line 3:
   <source missing, REPL/exec in use?>

   During: lowering "$8call_function.3 = call $2load_global.0(tmp0, tmp1, func=$2load_global.0, args=[Var(tmp0, <string>:3), Var(tmp1, <string>:3)], kws=(), vararg=None, hardware=None)" at <string> (3)
       Traceback (most recent call last):
         File "/Users/esc/git/numba/numba/core/errors.py", line 744, in new_error_context
           yield
         File "/Users/esc/git/numba/numba/core/lowering.py", line 230, in lower_block
           self.lower_inst(inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 323, in lower_inst
           val = self.lower_assign(ty, inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 499, in lower_assign
           return self.lower_expr(ty, value)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 1028, in lower_expr
           res = self.lower_call(resty, expr)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 758, in lower_call
           res = self._lower_call_normal(fnty, expr, signature)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 999, in _lower_call_normal
           res = impl(self.builder, argvals, self.loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1193, in __call__
           res = self._imp(self._context, builder, self._sig, args, loc=loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1223, in wrapper
           return fn(*args, **kwargs)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 541, in dot_2
           return dot_2_vv(context, builder, sig, args)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 520, in dot_2_vv
           call_xxdot(context, builder, conjugate, dtype, n, a.data, b.data, out)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 351, in call_xxdot
           kind = get_blas_kind(dtype)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 50, in get_blas_kind
           raise TypeError("unsupported dtype for %s()" % (func_name,))
       TypeError: unsupported dtype for <BLAS function>()
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/Users/esc/git/numba/numba/core/types/functions.py", line 329, in get_call_type
           sig = temp.apply(nolitargs, nolitkws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 347, in apply
           sig = generic(args, kws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 601, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 699, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 799, in _build_impl
           disp_type.get_call_type(self.context, args, kws)
         File "/Users/esc/git/numba/numba/core/types/functions.py", line 552, in get_call_type
           self.dispatcher.get_call_template(args, kws)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 316, in get_call_template
           self.compile(tuple(args))
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 911, in compile
           cres = self._compiler.compile(args, return_type)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 80, in compile
           status, retval = self._compile_cached(args, return_type)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 94, in _compile_cached
           retval = self._compile_core(args, return_type)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 107, in _compile_core
           cres = compiler.compile_extra(self.targetdescr.typing_context,
         File "/Users/esc/git/numba/numba/core/compiler.py", line 675, in compile_extra
           return pipeline.compile_extra(func)
         File "/Users/esc/git/numba/numba/core/compiler.py", line 419, in compile_extra
           return self._compile_bytecode()
         File "/Users/esc/git/numba/numba/core/compiler.py", line 483, in _compile_bytecode
           return self._compile_core()
         File "/Users/esc/git/numba/numba/core/compiler.py", line 462, in _compile_core
           raise e
         File "/Users/esc/git/numba/numba/core/compiler.py", line 453, in _compile_core
           pm.run(self.state)
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 339, in run
           raise patched_exception
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 330, in run
           self._runPass(idx, pass_inst, state)
         File "/Users/esc/git/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
           return func(*args, **kwargs)
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 289, in _runPass
           mutated |= check(pss.run_pass, internal_state)
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 262, in check
           mangled = func(compiler_state)
         File "/Users/esc/git/numba/numba/core/typed_passes.py", line 396, in run_pass
           lower.lower()
         File "/Users/esc/git/numba/numba/core/lowering.py", line 136, in lower
           self.lower_normal_function(self.fndesc)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 190, in lower_normal_function
           entry_block_tail = self.lower_function_body()
         File "/Users/esc/git/numba/numba/core/lowering.py", line 216, in lower_function_body
           self.lower_block(block)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 230, in lower_block
           self.lower_inst(inst)
         File "/Users/esc/miniconda3/envs/numba_3.8/lib/python3.8/contextlib.py", line 131, in __exit__
           self.gen.throw(type, value, traceback)
         File "/Users/esc/git/numba/numba/core/errors.py", line 751, in new_error_context
           raise newerr.with_traceback(tb)
         File "/Users/esc/git/numba/numba/core/errors.py", line 744, in new_error_context
           yield
         File "/Users/esc/git/numba/numba/core/lowering.py", line 230, in lower_block
           self.lower_inst(inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 323, in lower_inst
           val = self.lower_assign(ty, inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 499, in lower_assign
           return self.lower_expr(ty, value)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 1028, in lower_expr
           res = self.lower_call(resty, expr)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 758, in lower_call
           res = self._lower_call_normal(fnty, expr, signature)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 999, in _lower_call_normal
           res = impl(self.builder, argvals, self.loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1193, in __call__
           res = self._imp(self._context, builder, self._sig, args, loc=loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1223, in wrapper
           return fn(*args, **kwargs)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 541, in dot_2
           return dot_2_vv(context, builder, sig, args)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 520, in dot_2_vv
           call_xxdot(context, builder, conjugate, dtype, n, a.data, b.data, out)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 351, in call_xxdot
           kind = get_blas_kind(dtype)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 50, in get_blas_kind
           raise TypeError("unsupported dtype for %s()" % (func_name,))
       numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
       unsupported dtype for <BLAS function>()

       File "<string>", line 3:
       <source missing, REPL/exec in use?>

       During: lowering "$8call_function.3 = call $2load_global.0(tmp0, tmp1, func=$2load_global.0, args=[Var(tmp0, <string>:3), Var(tmp1, <string>:3)], kws=(), vararg=None, hardware=None)" at <string> (3)
  raised from /Users/esc/git/numba/numba/np/linalg.py:50

During: resolving callee type: Function(<function dot at 0x7f99b2be9a60>)
During: typing of call at issue6741.py (5)


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue6741.py", line 11, in <module>
    test(a, b)
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 421, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 360, in error_rewrite
    raise e
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 373, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 911, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 84, in compile
    raise retval
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 94, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 107, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/esc/git/numba/numba/core/compiler.py", line 675, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/esc/git/numba/numba/core/compiler.py", line 419, in compile_extra
    return self._compile_bytecode()
  File "/Users/esc/git/numba/numba/core/compiler.py", line 483, in _compile_bytecode
    return self._compile_core()
  File "/Users/esc/git/numba/numba/core/compiler.py", line 462, in _compile_core
    raise e
  File "/Users/esc/git/numba/numba/core/compiler.py", line 453, in _compile_core
    pm.run(self.state)
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/esc/git/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/esc/git/numba/numba/core/typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/Users/esc/git/numba/numba/core/typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/Users/esc/git/numba/numba/core/typeinfer.py", line 1071, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function dot at 0x7f99b2be9a60>) found for signature:

 >>> dot(array(int64, 1d, C), array(int64, 1d, C))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function '_OverloadWrapper._build.<locals>.ol_generated': File: numba/core/overload_glue.py: Line 106.
    With argument(s): '(array(int64, 1d, C), array(int64, 1d, C))':
   Rejected as the implementation raised a specific error:
     LoweringError: Failed in nopython mode pipeline (step: native lowering)
   unsupported dtype for <BLAS function>()

   File "<string>", line 3:
   <source missing, REPL/exec in use?>

   During: lowering "$8call_function.3 = call $2load_global.0(tmp0, tmp1, func=$2load_global.0, args=[Var(tmp0, <string>:3), Var(tmp1, <string>:3)], kws=(), vararg=None, hardware=None)" at <string> (3)
       Traceback (most recent call last):
         File "/Users/esc/git/numba/numba/core/errors.py", line 744, in new_error_context
           yield
         File "/Users/esc/git/numba/numba/core/lowering.py", line 230, in lower_block
           self.lower_inst(inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 323, in lower_inst
           val = self.lower_assign(ty, inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 499, in lower_assign
           return self.lower_expr(ty, value)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 1028, in lower_expr
           res = self.lower_call(resty, expr)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 758, in lower_call
           res = self._lower_call_normal(fnty, expr, signature)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 999, in _lower_call_normal
           res = impl(self.builder, argvals, self.loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1193, in __call__
           res = self._imp(self._context, builder, self._sig, args, loc=loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1223, in wrapper
           return fn(*args, **kwargs)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 541, in dot_2
           return dot_2_vv(context, builder, sig, args)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 520, in dot_2_vv
           call_xxdot(context, builder, conjugate, dtype, n, a.data, b.data, out)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 351, in call_xxdot
           kind = get_blas_kind(dtype)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 50, in get_blas_kind
           raise TypeError("unsupported dtype for %s()" % (func_name,))
       TypeError: unsupported dtype for <BLAS function>()
       During handling of the above exception, another exception occurred:
       Traceback (most recent call last):
         File "/Users/esc/git/numba/numba/core/types/functions.py", line 329, in get_call_type
           sig = temp.apply(nolitargs, nolitkws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 347, in apply
           sig = generic(args, kws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 601, in generic
           disp, new_args = self._get_impl(args, kws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 699, in _get_impl
           impl, args = self._build_impl(cache_key, args, kws)
         File "/Users/esc/git/numba/numba/core/typing/templates.py", line 799, in _build_impl
           disp_type.get_call_type(self.context, args, kws)
         File "/Users/esc/git/numba/numba/core/types/functions.py", line 552, in get_call_type
           self.dispatcher.get_call_template(args, kws)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 316, in get_call_template
           self.compile(tuple(args))
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 911, in compile
           cres = self._compiler.compile(args, return_type)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 80, in compile
           status, retval = self._compile_cached(args, return_type)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 94, in _compile_cached
           retval = self._compile_core(args, return_type)
         File "/Users/esc/git/numba/numba/core/dispatcher.py", line 107, in _compile_core
           cres = compiler.compile_extra(self.targetdescr.typing_context,
         File "/Users/esc/git/numba/numba/core/compiler.py", line 675, in compile_extra
           return pipeline.compile_extra(func)
         File "/Users/esc/git/numba/numba/core/compiler.py", line 419, in compile_extra
           return self._compile_bytecode()
         File "/Users/esc/git/numba/numba/core/compiler.py", line 483, in _compile_bytecode
           return self._compile_core()
         File "/Users/esc/git/numba/numba/core/compiler.py", line 462, in _compile_core
           raise e
         File "/Users/esc/git/numba/numba/core/compiler.py", line 453, in _compile_core
           pm.run(self.state)
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 339, in run
           raise patched_exception
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 330, in run
           self._runPass(idx, pass_inst, state)
         File "/Users/esc/git/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
           return func(*args, **kwargs)
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 289, in _runPass
           mutated |= check(pss.run_pass, internal_state)
         File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 262, in check
           mangled = func(compiler_state)
         File "/Users/esc/git/numba/numba/core/typed_passes.py", line 396, in run_pass
           lower.lower()
         File "/Users/esc/git/numba/numba/core/lowering.py", line 136, in lower
           self.lower_normal_function(self.fndesc)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 190, in lower_normal_function
           entry_block_tail = self.lower_function_body()
         File "/Users/esc/git/numba/numba/core/lowering.py", line 216, in lower_function_body
           self.lower_block(block)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 230, in lower_block
           self.lower_inst(inst)
         File "/Users/esc/miniconda3/envs/numba_3.8/lib/python3.8/contextlib.py", line 131, in __exit__
           self.gen.throw(type, value, traceback)
         File "/Users/esc/git/numba/numba/core/errors.py", line 751, in new_error_context
           raise newerr.with_traceback(tb)
         File "/Users/esc/git/numba/numba/core/errors.py", line 744, in new_error_context
           yield
         File "/Users/esc/git/numba/numba/core/lowering.py", line 230, in lower_block
           self.lower_inst(inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 323, in lower_inst
           val = self.lower_assign(ty, inst)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 499, in lower_assign
           return self.lower_expr(ty, value)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 1028, in lower_expr
           res = self.lower_call(resty, expr)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 758, in lower_call
           res = self._lower_call_normal(fnty, expr, signature)
         File "/Users/esc/git/numba/numba/core/lowering.py", line 999, in _lower_call_normal
           res = impl(self.builder, argvals, self.loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1193, in __call__
           res = self._imp(self._context, builder, self._sig, args, loc=loc)
         File "/Users/esc/git/numba/numba/core/base.py", line 1223, in wrapper
           return fn(*args, **kwargs)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 541, in dot_2
           return dot_2_vv(context, builder, sig, args)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 520, in dot_2_vv
           call_xxdot(context, builder, conjugate, dtype, n, a.data, b.data, out)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 351, in call_xxdot
           kind = get_blas_kind(dtype)
         File "/Users/esc/git/numba/numba/np/linalg.py", line 50, in get_blas_kind
           raise TypeError("unsupported dtype for %s()" % (func_name,))
       numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
       unsupported dtype for <BLAS function>()

       File "<string>", line 3:
       <source missing, REPL/exec in use?>

       During: lowering "$8call_function.3 = call $2load_global.0(tmp0, tmp1, func=$2load_global.0, args=[Var(tmp0, <string>:3), Var(tmp1, <string>:3)], kws=(), vararg=None, hardware=None)" at <string> (3)
  raised from /Users/esc/git/numba/numba/np/linalg.py:50

During: resolving callee type: Function(<function dot at 0x7f99b2be9a60>)
During: typing of call at issue6741.py (5)


File "issue6741.py", line 5:
def test(a, b):
    return numpy.dot(a, b)
    ^

```

**Comment by slayoo** [comment]
> cast back and forth from/to float and use what is there

IMHO, this will sooner or later lead to users reporting surprising behaviour.

> please respond with any updates and confirm that this issue still needs to be addressed

it does :)

**Comment by esc** [comment]
@slayoo thank you for the confirmation, I have updated the labels accordingly.

**Comment by sg495** [comment]
Yeah, this issue needs to be addressed at some point 😆. I'm surprised it doesn't come up more often...

**Comment by jorgepiloto** [comment]
One option to avoid using `np.dot` is to use the matrix multiplication:

```python
ans = vector1 @ vector2
```
Nevertheless, this does not fix the current issue with `np.dot`.
