### ISSUE TITLE
Regression in 0.53.0rc1 for boolean conversion

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#6721]
See reproducer below. Reverting the temporary assignment change (d938288) solves the issue, but the underlying bug is most probably something else. This only happens with inlining so maybe inliner needs a closer look.

```python
import numba
import numpy as np
import pandas as pd

val_one = True

def f(S):
    pass

@numba.extending.overload(f, inline="always")
def f_overload(A):

    def impl(A):
        for i in range(len(A)):
            val = val_one
            if A[i]:
                val = A[i]
        return val
    return impl

@numba.njit
def f2(A):
    return f(A)

print(f2(np.array([True, False, True])))
```
```
Traceback (most recent call last):
  File "../bool_cast_err2.py", line 25, in <module>
    print(f2(np.array([True, False, True])))
  File "/Users/ehsan/tmp/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/ehsan/tmp/numba/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function f at 0x7fc275ff3f70>) found for signature:

 >>> f(array(bool, 1d, C))

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'f_overload': File: ../bool_cast_err2.py: Line 10.
    With argument(s): '(array(bool, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: No conversion from bool to Literal[bool](True) for 'val', defined at ../bool_cast_err2.py (15)

   File "../bool_cast_err2.py", line 17:
       def impl(A):
           <source elided>
               if A[i]:
                   val = A[i]
                   ^

   During: typing of intrinsic-call at ../bool_cast_err2.py (17)

   File "../bool_cast_err2.py", line 17:
       def impl(A):
           <source elided>
               if A[i]:
                   val = A[i]
                   ^

  raised from /Users/ehsan/tmp/numba/numba/core/typeinfer.py:1071

During: resolving callee type: Function(<function f at 0x7fc275ff3f70>)
During: typing of call at ../bool_cast_err2.py (23)


File "../bool_cast_err2.py", line 23:
def f2(A):
    return f(A)
    ^
```

**Comment by gmarkall** [comment]
Many thanks for the report!

I can reproduce the issue with current master, and also observe that reverting the merge d938288 resolves the issue. The issue doesn't reproduce with Numba 0.52, hence is a regression.
