### ISSUE TITLE
Multiple overload method/attribute templates for same type overlap

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#6781]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi,

I was trying to extend Numba types with a new type family in a similar way it's done for typed.Dict that uses overloading of TypeRef's method `empty` to create instances of concrete typed dict types, but ran into the problem when it's not possible to overload TypeRef's `empty` since it breaks Dict methods compilation.

After a bit of debugging I found that problem is likely caused by `@overload_method` and `@overload_attribute` decorators not supporting multiple entries for the same type-family (each providing separate specializations for concrete types) since it ends up in multiple OverloadAttributeTemplate-s registered for the same key (which is a metaclass name).

Here's the reproducer:
```
import numba
from numba import types
from numba.extending import (
    make_attribute_wrapper,
    overload,
    overload_method,
    models,
    register_model,
)
from numba.core.types.abstract import TypeRef


class DummyType(types.Type):
    def __init__(self, name):
        self.name = name
        super(DummyType, self).__init__(name=f"Dummy({name})")

# we have several concrete types created from DummyType
dummy_type_a = DummyType('a')
dummy_type_b = DummyType('b')


@register_model(DummyType)
class DummyModel(models.StructModel):
    def __init__(self, dmm, fe_type):
        value_type = types.int64 if fe_type.name == 'a' else types.unicode_type
        members = [("value", value_type)]
        models.StructModel.__init__(self, dmm, fe_type, members)

make_attribute_wrapper(DummyType, "value", "_value")


'''
# singe overload_method registering all specializations works OK
@overload_method(TypeRef, 'get')
def dummy_get_ovld(self):

    if not isinstance(self.instance_type, DummyType):
        return None

    if self.instance_type is dummy_type_a:
        def dummy_type_a_get_impl(self):
            return 'a'
        return dummy_type_a_get_impl

    def dummy_type_b_get_impl(self):
        return 'b'
    return dummy_type_b_get_impl
'''

# multiple overload methods (e.g. when they are placed in different files
# or like in this case when overloading internal Numba type - TypeRef)
# override themselves (don't work together, but work if only one is used)
@overload_method(TypeRef, 'get')
def dummy_type_a_get_ovld(self):

    if self.instance_type is not dummy_type_a:
        return None

    def dummy_type_a_get_impl(self):
        return 'a'
    return dummy_type_a_get_impl


@overload_method(TypeRef, 'get')
def dummy_type_b_get_ovld(self):

    if self.instance_type is not dummy_type_b:
        return None

    def dummy_type_b_get_impl(self):
        return 'b'
    return dummy_type_b_get_impl


@numba.njit
def test_func():
    a = dummy_type_a.get()
    b = dummy_type_b.get()
    return a, b

print(test_func())
# test_func.inspect_types()
```

While it works when there's a single `@overload_method(TypeRef, 'get')` entry that provides implementation for all TypeRef instances it doesn't work if multiple functions are decorated with overload_method. This actually prevents user from overloading on internal Numba types such as TypeRef.

Above reproducer gives:
```
Traceback (most recent call last):
  File "test_overload_method_1.py", line 79, in <module>
    print(test_func())
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 356, in error_rewrite
    raise e
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 367, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 819, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 82, in compile
    raise retval
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 92, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 105, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 627, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 363, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 425, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 405, in _compile_core
    raise e
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 396, in _compile_core
    pm.run(self.state)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 341, in run
    raise patched_exception
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 332, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 291, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 264, in check
    mangled = func(compiler_state)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typed_passes.py", line 92, in run_pass
    typemap, return_type, calltypes = type_inference_stage(
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typed_passes.py", line 70, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 1071, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function dummy_type_a_get_ovld at 0x0000018EB06659D0>) found for signature:

 >>> dummy_type_a_get_ovld(typeref[Dummy(b)])

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload of function 'dummy_type_a_get_ovld': File: test_overload_method_1.py: Line 51.
    With argument(s): '(typeref[Dummy(b)])':
   No match.

- Resolution failure for non-literal arguments:
None

During: resolving callee type: BoundFunction((<class 'numba.core.types.abstract.TypeRef'>, 'get') for typeref[Dummy(b)])
During: typing of call at test_overload_method_1.py (76)


File "test_overload_method_1.py", line 76:
def test_func():
    <source elided>
    a = dummy_type_a.get()
    b = dummy_type_b.get()
    ^
```

And debugging shows there are multiple overload templates with the same signature registered:
>>> func
(<class 'numba.core.types.abstract.TypeRef'>, 'get')
>>> self.versions
[((<class 'numba.core.types.abstract.TypeRef'>, *any), <function _OverloadMethodTemplate.do_class_init.<locals>.method_impl at 0x00000259E3185AF0>), ((<class 'numba.core.types.abstract.TypeRef'>, *any), <function _OverloadMethodTemplate.do_class_init.<locals>.method_impl at 0x00000259E3185B80>)]

I verified problem can be reproduced on numba=0.52.0

Best Regards,
Alexey.

**Comment by gmarkall** [comment]
Many thanks for the report - I can reproduce the issue on master with the above code.

**Comment by esc** [comment]
I believe this issue is known, and hence the `empty` method of the `numba.typed.List` is called `empty_list` rather than `empty`. IIRC @sklam and I have not yet managed to come up with a good solution.

**Comment by sklam** [comment]
Right, this is a known problem

**Comment by gmarkall** [comment]
Labelling as bug (in the design) / feature request.

**Comment by arthurp** [comment]
I think this is also a documentation bug. The documentation does not specify that overloading only actually works with `@overload` and that `@overload_method` can only usefully be specified once per method name.
