### ISSUE TITLE
parfors lowering error from sum with internal prange (suspect SSA related!?)

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6783]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This:
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def test_simple_2(X):
    M, N = X.shape
    out = np.zeros(M, dtype=np.float_)
    for k in prange(M):
        x = X[k, :].astype(np.float_)
        total = 0.0
        for i in range(N):
            i_indices = np.arange(5)
            i_data = np.ones(5)
            val = (i_data).sum()
            total += val
        out[k] = total
    return out


X = np.ones((3, 4))

print(test_simple_2(X))
```
does this:
```
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: native lowering)
'val.72'

File "numba/parfors/parfor.py", line 256:
        def sum_1(in_arr):
            <source elided>
            for i in numba.parfors.parfor.internal_prange(len(in_arr)):
                val += in_arr[i]
                ^

During: lowering "$val.72.315 = inplace_binop(fn=<built-in function iadd>, immutable_fn=<built-in function add>, lhs=val.72, rhs=$expr_out_var.117, static_lhs=Undefined, static_rhs=Undefined)" 
```

xref: https://github.com/numba/numba/issues/6774#issuecomment-788789663 reported by @ivirshup.

CC @DrTodd13

**Comment by DrTodd13** [comment]
@stuartarchibald This one also seems to work for me.

**Comment by stuartarchibald** [comment]
If I do this:
```python
from numba import njit, prange, version_info
import numpy as np

print(version_info)

def test_simple_2(X):
    M, N = X.shape
    out = np.zeros(M, dtype=np.float_)
    for k in prange(M):
        x = X[k, :].astype(np.float_)
        total = 0.0
        for i in range(N):
            i_indices = np.arange(5)
            i_data = np.ones(5)
            val = (i_data).sum()
            total += val
        out[k] = total
    return out


X = np.ones((3, 4))

print("python ", test_simple_2(X))
print("njit   ",njit(test_simple_2)(X))
print("parfors",njit(parallel=True)(test_simple_2)(X))
```
I get:
```
$ python issue6783.py 
version_info(major=0, minor=54, patch=None, short=(0, 54), full=(0, 54, None), string='0.54.0dev0+88.g00c15b7', tuple=('0', '54', '0dev0+88', 'g00c15b7'), git_revision='g00c15b7')
python  [20. 20. 20.]
njit    [20. 20. 20.]
Traceback (most recent call last):
  File "<path>/numba/core/errors.py", line 744, in new_error_context
    yield
  File "<path>/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "<path>/numba/core/lowering.py", line 327, in lower_inst
    val = self.lower_assign(ty, inst)
  File "<path>/numba/core/lowering.py", line 502, in lower_assign
    return self.lower_expr(ty, value)
  File "<path>/numba/core/lowering.py", line 1007, in lower_expr
    return self.lower_binop(resty, expr, expr.immutable_fn)
  File "<path>/numba/core/lowering.py", line 574, in lower_binop
    lhs = self.loadvar(lhs.name)
  File "<path>/numba/core/lowering.py", line 1255, in loadvar
    ptr = self.getvar(name)
  File "<path>/numba/core/lowering.py", line 1249, in getvar
    return self.varmap[name]
KeyError: 'val.72'
```
and
```
$ git rev-parse HEAD
00c15b7cace13fbb03f5edb19e5dcba8c395be32
```
which is HEAD of mainline: 00c15b7cace13fbb03f5edb19e5dcba8c395be32
