### ISSUE TITLE
parfors invalid/outdated varmap

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#6784]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.
This:
```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def test2(g_data, g_indices, g_indptr, X):
    M, N = X.shape
    out = np.zeros(M, dtype=np.float_)
    for k in prange(M):
        x = X[k, :].astype(np.float_)
        total = 0.0
        for i in range(N):
            s = slice(g_indptr[i], g_indptr[i + 1])
            i_indices = g_indices[s]
            i_data = g_data[s]
#             tmp = (i_data * (x[i] - x[i_indices])  ** 2) uncomment this and get a different error!
            val = (i_data * ((x[i] - x[i_indices]) ** 2)).sum()
            total += val
        out[k] = total
    return out

g_data = np.array([1, 2, 3, 4])
g_indptr = np.array([0, 0, 1, 2, 3, 4], dtype=np.int32)
g_indices = np.array([1, 2, 3, 4], dtype=np.int32)
X = np.zeros((5, 5))
test2(g_data, g_indptr, g_indices, X)
```
produces:
```
numba/core/lowering.py", line 1249, in getvar
    return self.varmap[name]
KeyError: 'i_data'
<snip>
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: native lowering)
'i_data'

File "issue6774_4.py", line 16:
def test2(g_data, g_indices, g_indptr, X):
    <source elided>
#             tmp = (i_data * (x[i] - x[i_indices])  ** 2)
            val = (i_data * ((x[i] - x[i_indices]) ** 2)).sum()
```
note that uncommenting the line that's commented instead produces an assertion error:
```
AssertionError: Sizes of i_data, $130binary_subscr.25 
```
xref: https://github.com/numba/numba/issues/6774#issuecomment-788789663 reported by @ivirshup.

CC @DrTodd13

**Comment by DrTodd13** [comment]
@stuartarchibald g_indptr and g_indices are in reverse order at the callsite compared to the function declaration.  If you put them in the right order then this works.  It doesn't even work in Python if you have them in the wrong order.

**Comment by ivirshup** [comment]
@DrTodd13, just to be sure we're checking the same thing:

```python
test2(g_data, g_indices, g_indptr, X)
```

On the current release candidate, this works if assignment to `tmp` is uncommented, but not if it's commented.

**Comment by DrTodd13** [comment]
> @DrTodd13, just to be sure we're checking the same thing:
> 
> ```python
> test2(g_data, g_indices, g_indptr, X)
> ```
> 
> On the current release candidate, this works if assignment to `tmp` is uncommented, but not if it's commented.

@ivirshup 
If you use that tmp line (which I presume should really be "val =" instead of "tmp =") then you are trying to add an array of floats to a float and so that is a legitimate typing error.

**Comment by ivirshup** [comment]
> If you use that tmp line (which I presume should really be "val =" instead of "tmp =") 

So, to me this is what makes the bug so weird. Assignment to `tmp` shouldn't do anything to the result, as it's never used. But somehow including that line makes compilation succeed, and removing it makes compilation fail.

This was discovered purely through serendipity while trying to cut down the reproducing example. I believe what I was checking was just whether it was specifically the `sum` call causing the compilation failure, and ran a case where the expressions with and without `sum()` were both included.

**Comment by DrTodd13** [comment]
> > If you use that tmp line (which I presume should really be "val =" instead of "tmp =")
> 
> So, to me this is what makes the bug so weird. Assignment to `tmp` shouldn't do anything to the result, as it's never used. But somehow including that line makes compilation succeed, and removing it makes compilation fail.
> 
> This was discovered purely through serendipity while trying to cut down the reproducing example. I believe what I was checking was just whether it was specifically the `sum` call causing the compilation failure, and ran a case where the expressions with and without `sum()` were both included.

It still works for me if the unused tmp and val are both included.

**Comment by ivirshup** [comment]
And it works if the assignment to `tmp` is not included? 

<details>
<summary> Exact code to reproduce </summary>

```python
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def test2(g_data, g_indices, g_indptr, X):
    M, N = X.shape
    out = np.zeros(M, dtype=np.float_)
    for k in prange(M):
        x = X[k, :].astype(np.float_)
        total = 0.0
        for i in range(N):
            s = slice(g_indptr[i], g_indptr[i + 1])
            i_indices = g_indices[s]
            i_data = g_data[s]
#             tmp = (i_data * (x[i] - x[i_indices])  ** 2) uncomment this and get a different error!
            val = (i_data * ((x[i] - x[i_indices]) ** 2)).sum()
            total += val
        out[k] = total
    return out

g_data = np.array([1, 2, 3, 4])
g_indptr = np.array([0, 0, 1, 2, 3, 4], dtype=np.int32)
g_indices = np.array([1, 2, 3, 4], dtype=np.int32)
X = np.zeros((5, 5))
test2(g_data, g_indices, g_indptr, X)
```

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 327, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 502, in lower_assign
    return self.lower_expr(ty, value)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 1158, in lower_expr
    return self.lower_getitem(resty, expr, expr.value, expr.index,
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 633, in lower_getitem
    baseval = self.loadvar(value.name)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 1255, in loadvar
    ptr = self.getvar(name)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 1249, in getvar
    return self.varmap[name]
KeyError: '$i_data.99'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./bug.py", line 26, in <module>
    test2(g_data, g_indices, g_indptr, X)
  File "/usr/local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 433, in _compile_for_args
    raise e
  File "/usr/local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 366, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 857, in compile
    cres = self._compiler.compile(args, return_type)
  File "/usr/local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 77, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/usr/local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 91, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/usr/local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 104, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 602, in compile_extra
    return pipeline.compile_extra(func)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 352, in compile_extra
    return self._compile_bytecode()
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 414, in _compile_bytecode
    return self._compile_core()
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 394, in _compile_core
    raise e
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 385, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 449, in run_pass
    NativeLowering().run_pass(state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 373, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 443, in lower_inst
    func(self, inst)
  File "/usr/local/lib/python3.8/site-packages/numba/parfors/parfor_lowering.py", line 259, in _lower_parfor_parallel
    exp_name_to_tuple_var) = _create_gufunc_for_parfor_body(
  File "/usr/local/lib/python3.8/site-packages/numba/parfors/parfor_lowering.py", line 1361, in _create_gufunc_for_parfor_body
    kernel_func = compiler.compile_ir(
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 665, in compile_ir
    return pipeline.compile_ir(func_ir=func_ir, lifted=lifted,
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 362, in compile_ir
    return self._compile_ir()
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 421, in _compile_ir
    return self._compile_core()
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 394, in _compile_core
    raise e
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler.py", line 385, in _compile_core
    pm.run(self.state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 449, in run_pass
    NativeLowering().run_pass(state)
  File "/usr/local/lib/python3.8/site-packages/numba/core/typed_passes.py", line 373, in run_pass
    lower.lower()
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/usr/local/lib/python3.8/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/usr/local/Cellar/python@3.8/3.8.6_2/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Failed in nopython mode pipeline (step: nopython mode backend)
'$i_data.99'

File "bug.py", line 16:
def test2(g_data, g_indices, g_indptr, X):
    <source elided>
#             tmp = (i_data * (x[i] - x[i_indices])  ** 2) uncomment this and get a different error!
            val = (i_data * ((x[i] - x[i_indices]) ** 2)).sum()
            ^

During: lowering "$arg_out_var.76 = getitem(value=$i_data.99, index=parfor_index.71, fn=<built-in function getitem>)" at ./bug.py (16)
During: lowering "id=0[LoopNest(index_variable = parfor_index.66, range = (0, X_size0.38, 1))]{76: <ir.Block at ./bug.py (7)>, 78: <ir.Block at ./bug.py (11)>, 222: <ir.Block at ./bug.py (18)>, 205: <ir.Block at ./bug.py (11)>}Var(parfor_index.66, bug.py:7)" at ./bug.py (7)
```

</details>

Also, is this on master, with #6779 applied, or some release?

**Comment by DrTodd13** [comment]
Works for me and this isn't related to 6779.

**Comment by stuartarchibald** [comment]
@DrTodd13, RE https://github.com/numba/numba/issues/6784#issuecomment-789332293 apologies, I put in the arguments transposed, it's invalid though shouldn't impact the `varmap` bug.

@DrTodd13 @ivirshup 
The "Exact code to reproduce" in the `<details>` from @ivirshup's comment here https://github.com/numba/numba/issues/6784#issuecomment-789370684 reproduces the problem for me and I'm on:
```
$ git rev-parse HEAD
00c15b7cace13fbb03f5edb19e5dcba8c395be32
```
i.e. current HEAD of mainline. I also can reproduce that uncommenting the line "fixes" it!

**Comment by DrTodd13** [comment]
```(official_numba) taanders@psephi10:~/numba/intel_numba/numba$ git rev-parse HEAD
00c15b7cace13fbb03f5edb19e5dcba8c395be32
(official_numba) taanders@psephi10:~/numba/intel_numba/numba$ cat /tmp/issue6784.py
from numba import njit, prange
import numpy as np

@njit(parallel=True)
def test2(g_data, g_indices, g_indptr, X):
    M, N = X.shape
    out = np.zeros(M, dtype=np.float_)
    for k in prange(M):
        x = X[k, :].astype(np.float_)
        total = 0.0
        for i in range(N):
            s = slice(g_indptr[i], g_indptr[i + 1])
            i_indices = g_indices[s]
            i_data = g_data[s]
            tmp = (i_data * (x[i] - x[i_indices])  ** 2)  # uncomment this and get a different error!
            val = (i_data * ((x[i] - x[i_indices]) ** 2)).sum()
            total += val
        out[k] = total
    return out

g_data = np.array([1, 2, 3, 4])
g_indptr = np.array([0, 0, 1, 2, 3, 4], dtype=np.int32)
g_indices = np.array([1, 2, 3, 4], dtype=np.int32)
X = np.zeros((5, 5))
test2(g_data, g_indices, g_indptr, X)
print("DONE")
(official_numba) taanders@psephi10:~/numba/intel_numba/numba$ python /tmp/issue6784.py
DONE
```
@stuartarchibald

**Comment by stuartarchibald** [comment]
@DrTodd13 I guess the question is... what's different between the environments?! as it seems to reproduce somewhere :) I tested with Python 3.8 on Linux.
