### ISSUE TITLE
ListType to numpy array issue

### ISSUE THREAD

**Issue by justinblaber** [numba/numba#6803]
If I have a list that I want to eventually convert into a numpy array, I have to use a reflected list rather than a `ListType`.

For example:

```
@numba.jit(nopython=True)
def foo1():
    A = [-1]
    numpy.array(A)

@numba.jit(nopython=True)
def foo2():
    A = numba.typed.List([-1])
    numpy.array(A)
    
foo1()
foo2()
```

`foo1()` works but `foo2()` fails. I have some use cases where this requires me to use the old reflected list instead of the new `ListType`.

**Comment by gmarkall** [comment]
I can reproduce this. Copy-pastable reproducer:

```python
import numba
import numpy


@numba.jit(nopython=True)
def foo1():
    A = [-1]
    numpy.array(A)


@numba.jit(nopython=True)
def foo2():
    A = numba.typed.List([-1])
    numpy.array(A)


foo1()
foo2()
```

Traceback:

```
$ python repro.py 
Traceback (most recent call last):
  File "repro.py", line 18, in <module>
    foo2()
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 421, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 362, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function array>) found for signature:
 
 >>> array(ListType[int64])
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'array': File: numba/core/typing/npydecl.py: Line 489.
    With argument(s): '(ListType[int64])':
   Rejected as the implementation raised a specific error:
     NotImplementedError: ListType[int64] cannot be represented as a Numpy dtype
  raised from /home/gmarkall/numbadev/numba/numba/np/numpy_support.py:156

During: resolving callee type: Function(<built-in function array>)
During: typing of call at repro.py (14)


File "repro.py", line 14:
def foo2():
    <source elided>
    A = numba.typed.List([-1])
    numpy.array(A)
    ^
```

**Comment by gmarkall** [comment]
Labelling as a feature request to support conversion of typed lists to NumPy arrays.

**Comment by 00sapo** [comment]
Any workaround?

**Comment by esc** [comment]
@00sapo you could simply use a loop. Numba likes loops and can compile them to run very fast (unlike regular Python).

**Comment by 00sapo** [comment]
I'm trying to do that, even if it's not like a simple header change. How can I get the type of the list? `my_list.dtype` doesn't work...

**Comment by justinblaber** [comment]
> @00sapo how about:
> 
> ```
> In [8]: @njit
>    ...: def foo2():
>    ...:     A = List([1,2, 3, 4])
>    ...:     a = np.empty(len(A), dtype=A._dtype)
>    ...:     for i,v in enumerate(A):
>    ...:         a[i] = v
>    ...:     return a
>    ...:
>    ...:
> ```
> 
> Does that help?

This obviously works but is not a "good solution"... 

But... would llvm be smart enough to compile it out?

**Comment by 00sapo** [comment]
> @00sapo how about:
> 
> ```
> In [8]: @njit
>    ...: def foo2():
>    ...:     A = List([1,2, 3, 4])
>    ...:     a = np.empty(len(A), dtype=A._dtype)
>    ...:     for i,v in enumerate(A):
>    ...:         a[i] = v
>    ...:     return a
>    ...:
>    ...:
> ```
> 
> Does that help?

For me, it doesn't work. Not sure if I'm correct: I have created lists by using `typed.List.empty_list(numba.int64)`; they do not have `_dtype` nor `dtype`, even though in the code in master branch they seem to have; maybe it's because I'm using version 0.48 and cannot upgrade due to oter dependencies

**Comment by esc** [comment]
> > > This obviously works but is not a "good solution"...
> > 
> > 
> > Can you elaborate why you would not consider this a "good solution"?
> 
> I guess I assumed numpy would take ownership of the list memory (assuming its dynamic heap memory). In your above case it would duplicate allocations and copy contents which isn't good. But maybe that assumption was wrong.

Yes, the example is just hypothetical, it' unlikely that, in production code you would create a list only to immediately turn it into a Numpy array. I don't think there is a way (yet) to make Numpy re-use the allocated list memory from either a Python list (very unlikely) or a Numba typed list (or a reflected one for that matter). Although we have discussed exposing the typed lists's underlying data buffer in such a way that Numpy could create a view of it, which would allow you to use the Numpy functions on a `numba.typed.List`s data.

**Comment by esc** [comment]
A not for anyone who like to tackle this: it may be possible to use `memcpy` under the hood to (assuming a contiguous 1-D Numpy array) simply copy the underlying data buffer. Intuition indicates that this should be blazingly fast.

**Comment by HDembinski** [comment]
> it' unlikely that, in production code you would create a list only to immediately turn it into a Numpy array.

In my field (high energy physics) it is common. The typical case is that you get some input, then you select a subset of the input for processing and then you want to return the processed numbers as numpy array. You cannot know in advance how many elements shall be returned, so you need to make a list first and then convert it into a numpy array at the end.

[I made a small benchmark that compares different ways of doing this](https://nbviewer.jupyter.org/github/HDembinski/essays/blob/master/benchmark%20of%20building%20an%20array%20with%20numba.ipynb). It turns out that filling a list in Numba and then convert it to an array with `numpy.asarray` is the fastest solution for simple cases. For returning more complex structures, such as lists of lists, the Numba-compatible [awkward](https://github.com/scikit-hep/awkward-1.0) library is faster.
