### ISSUE TITLE
int() doesn't support booleans

### ISSUE THREAD

**Issue by pitrou** [numba/numba#685]
```
>>> def f(x): return int(x)
... 
>>> g = jit('int64(boolean)', nopython=True)(f)
Traceback (most recent call last):
  File "/home/antoine/numba/numba/typeinfer.py", line 107, in propagate
    constrain(context, typevars)
  File "/home/antoine/numba/numba/typeinfer.py", line 222, in __call__
    self.resolve(context, typevars, fnty)
  File "/home/antoine/numba/numba/typeinfer.py", line 231, in resolve
    sig = context.resolve_function_type(fnty, args, ())
  File "/home/antoine/numba/numba/typing/context.py", line 53, in resolve_function_type
    return func.template(self).apply(args, kws)
  File "/home/antoine/numba/numba/typing/templates.py", line 196, in apply
    sig = generic(args, kws)
  File "/home/antoine/numba/numba/typing/builtins.py", line 683, in generic
    raise TypeError("int() only support for numbers")
TypeError: int() only support for numbers
```

**Comment by pitrou** [comment]
This now works properly, closing.
