### ISSUE TITLE
Error "The use of yield in a closure is unsupported"

### ISSUE THREAD

**Issue by Babaika25** [numba/numba#6853]
I have code:
```
from itertools import product

def prob(dice, pips, target):
    rolls = product(range(1, pips+1), repeat=dice)
    targets = sum(1 for roll in rolls if sum(roll) == target)
    return targets / pips**dice

x = int(input())
y = int(input())
s = 0

for i in range(x*1, x*y+1):
    print(i, prob(x, y, i))
    s = s + prob(x, y, i)
print('sum: ', s)
```

Using numba like that:
```
from itertools import product
from numba import jit

@jit
def prob(dice, pips, target):
    rolls = product(range(1, pips+1), repeat=dice)
    targets = sum(1 for roll in rolls if sum(roll) == target)
    return targets / pips**dice

x = int(input())
y = int(input())
s = 0

for i in range(x*1, x*y+1):
    print(i, prob(x, y, i))
    s = s + prob(x, y, i)
print('sum: ', s)
```

And I have error:
```
Traceback (most recent call last):
  File "C:\Users\Valery\Desktop\main.py", line 15, in <module>
    print(i, prob(x, y, i))
  File "C:\Users\Valery\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 423, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "C:\Users\Valery\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.UnsupportedError: Failed in object mode pipeline (step: inline calls to locally defined closures)
The use of yield in a closure is unsupported.

File "main.py", line 7:
def prob(dice, pips, target):
    <source elided>
    rolls = product(range(1, pips+1), repeat=dice)
    targets = sum(1 for roll in rolls if sum(roll) == target)
    ^

```

How I can fix that?

**Comment by sklam** [comment]
> The use of yield in a closure is unsupported.

is referring to the generator-comprehension in `(1 for roll in rolls if sum(roll) == target)`. I would suggest making it a list-comprehension, however `sum` is also not supported yet (#5088).

Something like this would work:

```python
from numba import njit

@njit
def mysum(xs):
    tmp = 0
    for x in xs:
        tmp += x

    return tmp


@njit
def foo(rolls, target):
    return mysum([1 for roll in rolls if mysum(roll) == target])


rolls = ((1,), (2,), (3,))

s = 0
r = foo(rolls, 2)
print(r)

```

**Comment by gmarkall** [comment]
I think this is a simpler instantiation of the same issue, for anyone looking into a fix for this in future:

```python
from numba import njit

@njit('bool(int64[::1])')
def f(x):
    return all(v == 0 for v in x)
```

(just run into this myself)
