### ISSUE TITLE
truth value of arrays not implemented

### ISSUE THREAD

**Issue by pitrou** [numba/numba#686]
```
>>> def f(arg):
...   if arg:
...     return arg[0]
...   return 0
... 
>>> g = jit(nopython=True)(f)
>>> g(np.array([1, 2, 3]))
Traceback (most recent call last):
  File "/home/antoine/numba/numba/lowering.py", line 248, in lower_block
    self.lower_inst(inst)
  File "/home/antoine/numba/numba/lowering.py", line 274, in lower_inst
    pred = self.context.cast(self.builder, cond, condty, types.boolean)
  File "/home/antoine/numba/numba/targets/base.py", line 721, in cast
    return self.is_true(builder, fromty, val)
  File "/home/antoine/numba/numba/targets/base.py", line 742, in is_true
    raise NotImplementedError("is_true", val, typ)
NotImplementedError: ('is_true', <llvm.core.Instruction object at 0x7fdd44648898>, array(int64, 1d, C))
```

**Comment by pitrou** [comment]
Ok, I'm closing my own feature request, as it's probably not a good idea in the end (see reasons above).
