### ISSUE TITLE
CUDA: Eagerly compiling kernels with tuple parameters causes a segfault

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#6868]
Reproducer:

```python
from numba import cuda, types, int32, void
import numpy as np


@cuda.jit(void(types.UniTuple(int32[::1], 2)))
def f(x):
    x[0][0] = x[1][0]


x = np.zeros(10)
y = np.zeros_like(10)

f[1, 1]((x, y))
```

Partial traceback:

```
#0  0x00007fffe0c8e3fe in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#1  0x00007fffe0cdd27c in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#2  0x00007fffe0e74902 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#3  0x00007fffe0cdeb81 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#4  0x00007fffe0f1aa60 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#5  0x00007fffe0c83ea9 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#6  0x00007fffe0c84eec in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#7  0x00007fffe0d4d115 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so
#8  0x00007ffff67749dd in ffi_call_unix64 () from /home/gmarkall/miniconda3/envs/numba/lib/python3.8/lib-dynload/../../libffi.so.7
#9  0x00007ffff6774067 in ffi_call_int () from /home/gmarkall/miniconda3/envs/numba/lib/python3.8/lib-dynload/../../libffi.so.7
#10 0x00007ffff678ada8 in _call_function_pointer (argcount=11, resmem=0x7fffffffb610, restype=<optimised out>, atypes=<optimised out>, 
    avalues=0x7fffffffb5a0, pProc=0x7fffe0d3a580 <cuLaunchKernel>, flags=4353) at /usr/local/src/conda/python-3.8.5/Modules/_ctypes/callproc.c:871
#11 _ctypes_callproc (pProc=<optimised out>, 
    argtuple=(<c_void_p at remote 0x7fffdfddbcc0>, 1, 1, 1, 1, 1, 1, 0, None, <c_void_p_Array_12 at remote 0x7fffdfbf6740>, None), flags=<optimised out>, 
    argtypes=(<built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a47940>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a44a00>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a44a00>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a44a00>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a44a00>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a44a00>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a44a00>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a44a00>, <built-in method from_param of _ctypes.PyCSimpleType object at remote 0x555555a47940>, <built-in method from_param of _ctypes.PyCPointerType object at remote 0x5555563e6fa0>, <built-in method from_param of _ctypes.PyCPointerType object at remote 0x5555563e6fa0>), restype=<optimised out>, checker=<optimised out>) at /usr/local/src/conda/python-3.8.5/Modules/_ctypes/callproc.c:1214
#12 0x00007ffff678b08c in PyCFuncPtr_call (self=<optimised out>, inargs=<optimised out>, kwds=0x0)
    at /usr/local/src/conda/python-3.8.5/Modules/_ctypes/_ctypes.c:4201
#13 0x0000555555690f70 in PyObject_Call () at /tmp/build/80754af9/python_1596615979580/work/Objects/call.c:245
#14 0x000055555571652e in do_call_core (kwdict=0x0, 
    callargs=(<c_void_p at remote 0x7fffdfddbcc0>, 1, 1, 1, 1, 1, 1, 0, None, <c_void_p_Array_12 at remote 0x7fffdfbf6740>, None), 
    func=<_FuncPtr(__name__='cuLaunchKernel') at remote 0x7fffe2ffe640>, tstate=<optimised out>)
    at /tmp/build/80754af9/python_1596615979580/work/Python/ceval.c:5010
#15 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1596615979580/work/Python/ceval.c:3559
...
```

**Comment by gmarkall** [comment]
I made a mistake in my reproducer:

```python
x = np.zeros(10)
y = np.zeros_like(10)
```

this should have been:

```python
x = np.zeros(10)
y = np.zeros_like(x)
```

The problem is that signatures are not checked for eagerly-compiled kernels - at some point when doing the CUDA dispatcher work (#6432), I did have argument checking for eagerly-compiled kernels, but it increased the dispatch time a bit so I turned it off again - I think once other kernel launch overheads have been reduced, it would be acceptable from a performance perspective to turn it on again.

Closing this for now, as it's not a new / unknown issue.
