### ISSUE TITLE
Cuda functions treat `*args` as a normal parameter

### ISSUE THREAD

**Issue by MegaIng** [numba/numba#6891]
## Reporting a bug

- [x] I have tried using the latest released version (53.1/97fe221b3704bd17567b57ea47f4fc6604476cf9) of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When a `cuda.jit` function has `*args` parameter, it fails compilation with different errors, depending on how many arguments were passed.

This code:

```
from numba import cuda
import numpy as np

@cuda.jit()
def apply(array, *args):
    x = cuda.grid(1)
    if x < array.shape[0]:
        array[x] = args[0]

array = np.empty(128)

apply[8, 16](array, 2)
```

fails with 

>```
>No implementation of function Function(<built-in function getitem>) found for signature:
> 
> >>> getitem(int64, Literal[int](0))
>
>```

and when instead you call `apply[8, 16](array, 2, 3)`, you get
> ```Signature mismatch: 3 argument types given, but function takes 2 arguments```

It appears as if the cuda pipeline just ignores the `*`, treating `*args` as a single parameter.
If it is for some reason not possible to correctly deal with this, I would at least expect a sane error message.

<details>
<summary> Full tracback example one argument</summary>

> ```
> Traceback (most recent call last):
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\test_cuda.py", line 12, in <module>
>     apply[8, 16](array, 2)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 821, in __call__
>     return self.dispatcher.call(args, self.griddim, self.blockdim,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 964, in call
>     kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 972, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 1093, in compile
>     kernel = _Kernel(self.py_func, argtypes, link=self.link,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 509, in __init__
>     cres = compile_cuda(self.py_func, types.void, self.argtypes,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 47, in compile_cuda
>     cres = compiler.compile_extra(typingctx=typingctx,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 606, in compile_extra
>     return pipeline.compile_extra(func)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 353, in compile_extra
>     return self._compile_bytecode()
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
>     return self._compile_core()
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 395, in _compile_core
>     raise e
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 386, in _compile_core
>     pm.run(self.state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
>     raise patched_exception
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
>     self._runPass(idx, pass_inst, state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
>     mutated |= check(pss.run_pass, internal_state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
>     mangled = func(compiler_state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\typed_passes.py", line 104, in run_pass
>     typemap, return_type, calltypes, errs = type_inference_stage(
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\typed_passes.py", line 82, in type_inference_stage
>     errs = infer.propagate(raise_errors=raise_errors)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\typeinfer.py", line 1071, in propagate
>     raise errors[0]
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> No implementation of function Function(<built-in function getitem>) found for signature:
>  
>  >>> getitem(int64, Literal[int](0))
>  
> There are 22 candidate implementations:
>   - Of which 22 did not match due to:
>   Overload of function 'getitem': File: <numerous>: Line N/A.
>     With argument(s): '(int64, int64)':
>    No match.
> 
> During: typing of intrinsic-call at C:\Users\tramp\PycharmProjects\numba_render_engine\test_cuda.py (8)
> During: typing of static-get-item at C:\Users\tramp\PycharmProjects\numba_render_engine\test_cuda.py (8)
> 
> File "test_cuda.py", line 8:
> def apply(array, *args):
>     <source elided>
>     if x < array.shape[0]:
>         array[x] = args[0]
>         ^
> 
> ```

</details>

<details>
<summary> Full tracback example two arguments</summary>

> 
> ```
> Traceback (most recent call last):
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\test_cuda.py", line 12, in <module>
>     apply[8, 16](array, 2, 3)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 821, in __call__
>     return self.dispatcher.call(args, self.griddim, self.blockdim,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 964, in call
>     kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 972, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 1093, in compile
>     kernel = _Kernel(self.py_func, argtypes, link=self.link,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 509, in __init__
>     cres = compile_cuda(self.py_func, types.void, self.argtypes,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 47, in compile_cuda
>     cres = compiler.compile_extra(typingctx=typingctx,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 606, in compile_extra
>     return pipeline.compile_extra(func)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 353, in compile_extra
>     return self._compile_bytecode()
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
>     return self._compile_core()
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 395, in _compile_core
>     raise e
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 386, in _compile_core
>     pm.run(self.state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
>     raise patched_exception
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
>     self._runPass(idx, pass_inst, state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
>     mutated |= check(pss.run_pass, internal_state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
>     mangled = func(compiler_state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\untyped_passes.py", line 105, in run_pass
>     raise TypeError("Signature mismatch: %d argument types given, "
> TypeError: Failed in nopython mode pipeline (step: fix up args)
> Signature mismatch: 3 argument types given, but function takes 2 arguments
> 
> Process finished with exit code 1
> 
> ```

</details>

The errors get even more confusing when you try to call a device function. This code:

```
@cuda.jit(device=True)
def process(x, t):
    return t

@cuda.jit()
def apply(array, *args):
    x = cuda.grid(1)
    if x < array.shape[0]:
        array[x] = process(x, *args)

array = np.empty(128)

apply[8, 16](array, 2)
```

instead fails with

> 
> ```
> No implementation of function Function(<built-in function add>) found for signature:
>  
>  >>> add(UniTuple(int32 x 1), int64)
> ```

<details>
  <summary>Full Traceback</summary>
  

> ```
> Traceback (most recent call last):
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\test_cuda.py", line 27, in <module>
>     apply[8, 16](array, 2)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 821, in __call__
>     return self.dispatcher.call(args, self.griddim, self.blockdim,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 964, in call
>     kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 972, in _compile_for_args
>     return self.compile(tuple(argtypes))
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 1093, in compile
>     kernel = _Kernel(self.py_func, argtypes, link=self.link,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 509, in __init__
>     cres = compile_cuda(self.py_func, types.void, self.argtypes,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\cuda\compiler.py", line 47, in compile_cuda
>     cres = compiler.compile_extra(typingctx=typingctx,
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 606, in compile_extra
>     return pipeline.compile_extra(func)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 353, in compile_extra
>     return self._compile_bytecode()
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
>     return self._compile_core()
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 395, in _compile_core
>     raise e
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler.py", line 386, in _compile_core
>     pm.run(self.state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
>     raise patched_exception
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
>     self._runPass(idx, pass_inst, state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
>     mutated |= check(pss.run_pass, internal_state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
>     mangled = func(compiler_state)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\typed_passes.py", line 104, in run_pass
>     typemap, return_type, calltypes, errs = type_inference_stage(
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\typed_passes.py", line 82, in type_inference_stage
>     errs = infer.propagate(raise_errors=raise_errors)
>   File "C:\Users\tramp\PycharmProjects\numba_render_engine\venv\lib\site-packages\numba\core\typeinfer.py", line 1071, in propagate
>     raise errors[0]
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> No implementation of function Function(<built-in function add>) found for signature:
>  
>  >>> add(UniTuple(int32 x 1), int64)
>  
> There are 12 candidate implementations:
>   - Of which 2 did not match due to:
>   Operator Overload in function 'add': File: unknown: Line unknown.
>     With argument(s): '(UniTuple(int32 x 1), int64)':
>    No match for registered cases:
>     * (int64, int64) -> int64
>     * (int64, uint64) -> int64
>     * (uint64, int64) -> int64
>     * (uint64, uint64) -> uint64
>     * (float32, float32) -> float32
>     * (float64, float64) -> float64
>     * (complex64, complex64) -> complex64
>     * (complex128, complex128) -> complex128
>   - Of which 10 did not match due to:
>   Overload of function 'add': File: <numerous>: Line N/A.
>     With argument(s): '(UniTuple(int32 x 1), int64)':
>    No match.
> 
> During: typing of intrinsic-call at C:\Users\tramp\PycharmProjects\numba_render_engine\test_cuda.py (23)
> 
> File "test_cuda.py", line 23:
> def apply(array, *args):
>     <source elided>
>     if x < array.shape[0]:
>         array[x] = process(x, *args)
>         ^
> 
> ```

</details>

**Comment by gmarkall** [comment]
I can reproduce the tracebacks. Presently CUDA doesn't support `*args`, and it would be better for the use of it to be caught and a helpful error message presented.
