### ISSUE TITLE
x in ... resolvable at compile time behaves inconsistently between cuda/njit

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#6897]
The following will happily compile in njit, but bombs in cuda.
```
import numba as nb
import numpy as np
from numba import cuda


@cuda.jit(device=True)
def b(q):
    if q in ('a', 'b'):
        return 1
    else:
        return 2


@cuda.jit(nb.void(nb.int32[::1]))
def a(r):
    r[0] = b('a')
    r[1] = b('2')
```

It yields:
```
Traceback (most recent call last):
  File "in.py", line 14, in <module>
    @cuda.jit(nb.void(nb.int32[::1]))
  File "lib\site-packages\numba\cuda\decorators.py", line 136, in kernel_jit
    targetoptions=targetoptions)
  File "lib\site-packages\numba\cuda\compiler.py", line 811, in __init__
    self.compile(sigs[0])
  File "lib\site-packages\numba\cuda\compiler.py", line 949, in compile
    **self.targetoptions)
  File "lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "lib\site-packages\numba\cuda\compiler.py", line 57, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "lib\site-packages\numba\cuda\compiler.py", line 46, in compile_cuda
    locals={})
  File "lib\site-packages\numba\core\compiler.py", line 602, in compile_extra
    return pipeline.compile_extra(func)
  File "lib\site-packages\numba\core\compiler.py", line 352, in compile_extra
    return self._compile_bytecode()
  File "lib\site-packages\numba\core\compiler.py", line 414, in _compile_bytecode
    return self._compile_core()
  File "lib\site-packages\numba\core\compiler.py", line 394, in _compile_core
    raise e
  File "lib\site-packages\numba\core\compiler.py", line 385, in _compile_core
    pm.run(self.state)
  File "lib\site-packages\numba\core\compiler_machinery.py", line 339, in run
    raise patched_exception
  File "lib\site-packages\numba\core\compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "lib\site-packages\numba\core\compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "lib\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "lib\site-packages\numba\core\compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "lib\site-packages\numba\core\typed_passes.py", line 100, in run_pass
    raise_errors=self._raise_errors)
  File "lib\site-packages\numba\core\typed_passes.py", line 72, in type_inference_stage
    infer.propagate(raise_errors=raise_errors)
  File "lib\site-packages\numba\core\typeinfer.py", line 1071, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x000001DFD6F92608>) found for signature:
 
 >>> b <CUDA device function>(Literal[str](a))
 
There are 2 candidate implementations:
   - Of which 2 did not match due to:
   Overload in function 'b <CUDA device function>': File: in.py: Line 6.
     With argument(s): '(unicode_type)':
    Rejected as the implementation raised a specific error:
      LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
    Failed in nopython mode pipeline (step: nopython mode backend)
    No definition for lowering <built-in method eq_impl of _dynfunc._Closure object at 0x000001DFFFC9C908>(unicode_type, unicode_type) -> bool
    
    File "lib\site-packages\numba\cpython\listobj.py", line 662:
        def seq_contains_impl(lst, value):
            <source elided>
            for elem in lst:
                if elem == value:
                ^
    
    During: lowering "$16compare_op.4 = elem == value" at lib\site-packages\numba\cpython\listobj.py (662)
    During: lowering "$6compare_op.2 = q in $const4.1" at in.py (8)
  raised from lib\site-packages\numba\core\errors.py:751

During: resolving callee type: Function(<numba.cuda.compiler.DeviceFunctionTemplate object at 0x000001DFD6F92608>)
During: typing of call at in.py (16)


File "in.py", line 16:
def a(r):
    r[0] = b('a')
    ^
```

**Comment by gmarkall** [comment]
Smaller reproducer:

```python
from numba import cuda, void, int32


@cuda.jit(void(int32[::1]))
def a(r):
    r[0] = 1 if 'a' in ('a', 'b') else 2
```

<details>
<summary>Traceback:</summary>

```
$ python onefunc.py 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 323, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 499, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 996, in lower_expr
    return self.lower_binop(resty, expr, expr.fn)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 625, in lower_binop
    impl = self.context.get_function(op, sig)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 570, in get_function
    return self.get_function(fn, sig, _firstcall=False)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 572, in get_function
    raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
NotImplementedError: No definition for lowering <built-in method eq_impl of _dynfunc._Closure object at 0x7f33ad926580>(unicode_type, unicode_type) -> bool

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onefunc.py", line 5, in <module>
    def a(r):
  File "/home/gmarkall/numbadev/numba/numba/cuda/decorators.py", line 94, in kernel_jit
    return Dispatcher(func, [func_or_sig], targetoptions=targetoptions)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 868, in __init__
    self.compile(sigs[0])
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 1055, in compile
    kernel = _Kernel(self.py_func, argtypes, link=self.link,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 481, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 157, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 675, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 419, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 483, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 462, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 453, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 391, in run_pass
    lower.lower()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 323, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 499, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 996, in lower_expr
    return self.lower_binop(resty, expr, expr.fn)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 626, in lower_binop
    res = impl(self.builder, (lhs, rhs))
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 1190, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 1220, in wrapper
    return fn(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cpython/listobj.py", line 667, in in_seq
    return context.compile_internal(builder, seq_contains_impl, sig, args)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 892, in compile_internal
    cres = self.compile_subroutine(builder, impl, sig, locals)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 877, in compile_subroutine
    cres = self._compile_subroutine_no_cache(builder, impl, sig,
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 848, in _compile_subroutine_no_cache
    cres = compiler.compile_internal(self.typing_context, self,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 749, in compile_internal
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 419, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 483, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 462, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 453, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 391, in run_pass
    lower.lower()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/miniconda3/envs/numba/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in cuda mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: native lowering)
No definition for lowering <built-in method eq_impl of _dynfunc._Closure object at 0x7f33ad926580>(unicode_type, unicode_type) -> bool

File "../../numba/numba/cpython/listobj.py", line 663:
    def seq_contains_impl(lst, value):
        <source elided>
        for elem in lst:
            if elem == value:
            ^

During: lowering "$14compare_op.4 = elem == value" at /home/gmarkall/numbadev/numba/numba/cpython/listobj.py (663)
During: lowering "$6compare_op.2 = $const2.0 in $const4.1" at onefunc.py (6)
```
</details>

**Comment by gmarkall** [comment]
However, it does work OK for numeric values, the limitation being on lowering `in` for `unicode_type`:

```python
from numba import cuda, void, int32


@cuda.jit(void(int32[::1]))
def a(r):
    r[0] = 1 if 3 in (3, 4) else 2
```

runs without error.

**Comment by gmarkall** [comment]
@c200chromebook If this worked for unicode literals, would that solve the problem in your wider context?

**Comment by c200chromebook** [comment]
> @c200chromebook If this worked for unicode literals, would that solve the problem in your wider context?

In a perfect world it works for any list of strings but `in (...)` is an improvement
