### ISSUE TITLE
jax.ndarray.shape not working in @njit with error `unknown attribute shape of readonly buffer

### ISSUE THREAD

**Issue by PhilipVinc** [numba/numba#6980]
jax arrays define the __array__ interface so i expected them to work. Not writeable, of course, but at least readable.

Happening because `numba.typeof(jax.numpy.ones(3))` is a Buffer and not a Array 

MWE:
```python
>>> import jax, numba
>>> a=jax.numpy.ones((3,4))
>>> @numba.njit
... def test(x):
...   return x.shape[0]
... 
>>> test(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/filippovicentini/Documents/pythonenvs/netket_env/lib64/python3.8/site-packages/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'shape' of type readonly buffer(float64, 2d, C)

File "<stdin>", line 3:
<source missing, REPL/exec in use?>

During: typing of get attribute at <stdin> (3)

File "<stdin>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by PhilipVinc** [comment]
cc @stuartarchibald

**Comment by stuartarchibald** [comment]
Thanks for the report. Think something like:
```python
from numba import njit, types
import numpy as np

from numba.extending import overload_attribute, intrinsic
from numba.np.arrayobj import make_array

@intrinsic
def buffer_shape(tyctx, array_ty):
    sig = types.UniTuple(types.intp, array_ty.ndim)(array_ty)
    def impl(cgctx, builder, sig, ll_args):
        array_type = sig.args[0]
        array_struct = make_array(array_type)(cgctx, builder, ll_args[0])
        return array_struct.shape
    return sig, impl


@overload_attribute(types.Buffer, 'shape')
def ol_buffer_shape(buf):
    def impl(buf):
        return buffer_shape(buf)
    return impl


@njit(types.none(types.Buffer(types.float64, 2, 'C', readonly=True)))
def test(x):
    print(x.shape[0])
```
will fix it.

**Comment by PhilipVinc** [comment]
Are you suggesting we should carry this in our code or it’s something that will eventually be addressed in Numba?

**Comment by sklam** [comment]
`Buffer` is referring a type that exports the [buffer protocol](https://docs.python.org/3/c-api/buffer.html), which does not inform Numba about what methods or attributes it should have because it is not a `PyObject` in python level. To support `.shape`, Numba needs more typing information. We either needs to know that `jax.ndarray` is NumPy ndarray like or that the code request a `memoryview` from the buffer.

**Comment by PhilipVinc** [comment]
Looking at your link it seems to me that a Py_Buffer should support shape, but maybe i get it wrong...

**Comment by sklam** [comment]
`Py_Buffer` is a C struct. But the interface for the buffer protocol is empty in the python level, for example, `bytes` exports the buffer protocol but do not have `.shape`.

**Comment by PhilipVinc** [comment]
Bump.
Can't we make it so numba interprets jax arrays as standard readonly numpy arrays?

**Comment by jwnys** [comment]
Every few months I keep bumping into this cryptic error, after searching for too long. Can this be fixed in numba, by at least giving a clear error, rather than saying that .shape is not a property? Thanks!

**Comment by esc** [comment]
@stuartarchibald was the above a starter patch that is only missing tests?

**Comment by esc** [comment]
@jwnys thank you for asking about this, it can probably be fixed to give a better error message. Pull-requests welcome.

**Comment by gmarkall** [comment]
I've removed the needtriage label to prevent this going stale and closed, as it looks more like a feature request.
