### ISSUE TITLE
[BUG] cannot pickle generator when there is only one function that uses input or serial

### ISSUE THREAD

**Issue by NobodyXu** [numba/numba#7014]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The following code gives me pickle error:

```
import numba
import numpy as np

kws = {'cache': True}

@numba.njit(**kws)
def g(raw_data):
    for i in range(100000):
        yield i

@numba.jit(**kws)
def calibration():
    for i in range(1):
        data = input("Input anything: ").encode()
        for each in g(data):
            pass

calibration()
```

Gave me:

```
Input anything: ecqcfe
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    calibration()
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 439, in _c
ompile_for_args
    raise e
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 372, in _c
ompile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 915, in co
mpile
    self._cache.save_overload(sig, cres)
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/caching.py", line 661, in save_
overload
    self._save_overload(sig, data)
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/caching.py", line 671, in _save
_overload
    self._cache_file.save(key, data)
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/caching.py", line 489, in save
    self._save_data(data_name, data)
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/caching.py", line 547, in _save
_data
    data = self._dump(data)
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/caching.py", line 560, in _dump
    return pickle.dumps(obj, protocol=-1)
_pickle.PicklingError: Can't pickle <function g at 0x7f5edfa051f0>: it's not the same object as __ma
in__.g
```

However, if I change my code a little bit by adding another normal function that is pure:

```
import numba
import numpy as np

kws = {'cache': True}

@numba.njit(**kws)
def g(raw_data):
    for i in range(100000):
        yield i

@numba.njit(**kws)
def f():
    l = []
    for each in g(b"anything"):
        l.append(each)
    return l
f()

@numba.jit(**kws)
def calibration():
    for i in range(1):
        data = input("Input anything: ").encode()
        for each in g(data):
            pass

calibration()
```

Then it works as expected.

The numba on my computer is installed via `pip3`:

```
version_info(major=0, minor=53, patch=1, short=(0, 53), full=(0, 53, 1), string='0.53.1', tuple=('0', '53', '1'), git_revision=None)                                                                    
```

**Comment by NobodyXu** [comment]
Thanks for the advice, thus in my application, part of the loop reads uses `serial` and `print`, thus there is really no way to avoid object mode altogether, thus the core computation is pure and can be run under nopython mode.

**Comment by NobodyXu** [comment]
Also, I discovered a workaround:

 if I removed `cache = True` for `g` alone, then it works just fine:

```
import numba
import numpy as np

kws = {'cache': True}

@numba.njit
def g(raw_data):
    for i in range(100000):
        yield i

@numba.jit(**kws)
def calibration():
    for i in range(1):
        data = input("Input anything: ").encode()
        for each in g(data):
            pass

calibration()
```

**Comment by njriasan** [comment]
> Also, I discovered a workaround:
> 
> if I removed `cache = True` for `g` alone, then it works just fine:
> 
> ```
> import numba
> import numpy as np
> 
> kws = {'cache': True}
> 
> @numba.njit
> def g(raw_data):
>     for i in range(100000):
>         yield i
> 
> @numba.jit(**kws)
> def calibration():
>     for i in range(1):
>         data = input("Input anything: ").encode()
>         for each in g(data):
>             pass
> 
> calibration()
> ```
> 
> Thus it seems that `numba` doesn't cache the compilation result of `calibration` at all.

Based on this description I think this failure is related to objmode. I've seen this once before with a Bodo issue, but I couldn't craete a reproduce in Numba. @stuartarchibald can I investigate this?
