### ISSUE TITLE
Poor performance on cuda const memory

### ISSUE THREAD

**Issue by yhnmj6666** [numba/numba#7026]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello, I'm now currently working on one numba project that will use a **large const** array. I tried to create the memory using `cuda.const.array_like` but it was somehow different from what i thought:
1. the const memory creation process took a really, really long time; 
2. it cost a large amount of host memory.

Here is the testing code:
```python
import numpy as np
import numba
from numba import cuda
import time

const_mem=np.arange(2**24,dtype=np.int8) # 16M memory

@cuda.jit()
def cuda_copy(copy_test):
  tx = cuda.threadIdx.x
  ty = cuda.blockIdx.x
  bw = cuda.blockDim.x
  pos = tx + ty * bw
  cuda_const_mem=cuda.const.array_like(const_mem)

  copy_test[pos]=cuda_const_mem[pos]

@cuda.jit()
def cuda_copy2(copy_test,source):
  tx = cuda.threadIdx.x
  ty = cuda.blockIdx.x
  bw = cuda.blockDim.x
  pos = tx + ty * bw

  copy_test[pos]=source[pos]

to_be_filled=np.empty((2**24,),dtype=np.int8)
threadsperblock = 512
blockspergrid = len(to_be_filled)//threadsperblock

start_time = time.time()
cuda_copy2[blockspergrid, threadsperblock](to_be_filled,const_mem)
print(f'cuda_copy2: {time.time()-start_time:.3f} seconds')

start_time = time.time()
cuda_copy[blockspergrid, threadsperblock](to_be_filled)
print(f'cuda_copy: {time.time()-start_time:.3f} seconds')
```

And the output:
```python traceback
cuda_copy2: 1.337 seconds
Traceback (most recent call last):
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\cudadrv\driver.py", line 2160, in add_ptx
    driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "U:\Projects\python\numba_const_test.py", line 36, in <module>
    cuda_copy[blockspergrid, threadsperblock](to_be_filled)
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\compiler.py", line 821, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\compiler.py", line 964, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\compiler.py", line 972, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\compiler.py", line 1102, in compile
    kernel.bind()
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\compiler.py", line 590, in bind
    self._func.get()
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\compiler.py", line 441, in get
    linker.add_ptx(ptx)
  File "V:\Program Files\Python\lib\site-packages\numba\cuda\cudadrv\driver.py", line 2163, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [218] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas error   : File uses too much global constant data (0x1000000 bytes, 0x10000 max)
```

I was able to come up with a work around that pass the const array as a parameter of cuda function, but i believe the performance of cuda const array should be a improved.

**Comment by stuartarchibald** [comment]
Thanks for the report. @gmarkall could you take a look at this please? Thanks.

**Comment by gmarkall** [comment]
The constant memory size is only 64KB - see Table 15 in https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#compute-capabilities

Therefore you can't use more than 64KB of constant data. If you have this much data, you will need to put it in a device array and pass it into your kernel as a parameter.

**Comment by yhnmj6666** [comment]
Thanks for answering.the problem is solved 😄
