### ISSUE TITLE
Trouble transferring array with string values on cuda

### ISSUE THREAD

**Issue by JamesHoi** [numba/numba#7041]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hello! First off, thanks for developing and maintaining numba!

As title. Here is the code.
```python
from numba import cuda
import numpy as np

@cuda.jit
def gpu_run(gpu_result,N):
  idx = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x 
  if (idx < N):
    gpu_result[idx] = 'a'

def main():
  gpu_result = cuda.to_device(np.zeros(9).astype("<U12"))
  gpu_run[2, 4](gpu_result,8)
  print(gpu_result.copy_to_host())
  cuda.synchronize()

if __name__ == "__main__":
  main()
```
it produces the following output:
```python
/usr/local/lib/python3.7/dist-packages/numba/cuda/cudadrv/nvvm.py in _replace_llvm_memset_usage(m)
    687     align_attr = re.search(r'align (\d+)', params[0])
    688     if not align_attr:
--> 689         raise ValueError("No alignment attribute found on memset dest")
    690     else:
    691         align = align_attr.group(1)

ValueError: No alignment attribute found on memset dest
```
<details><summary>Traceback</summary>
<p>

```python
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-158cd6de03c4> in <module>()
     15 
     16 if __name__ == "__main__":
---> 17   main()

9 frames
<ipython-input-20-158cd6de03c4> in main()
     10 def main():
     11   gpu_result = cuda.to_device(np.zeros(9).astype("<U12"))
---> 12   gpu_run[2, 4](gpu_result,8)
     13   print(gpu_result.copy_to_host())
     14   cuda.synchronize()

/usr/local/lib/python3.7/dist-packages/numba/cuda/compiler.py in __call__(self, *args)
    768     def __call__(self, *args):
    769         return self.dispatcher.call(args, self.griddim, self.blockdim,
--> 770                                     self.stream, self.sharedmem)
    771 
    772 

/usr/local/lib/python3.7/dist-packages/numba/cuda/compiler.py in call(self, args, griddim, blockdim, stream, sharedmem)
    859         argtypes = tuple(
    860             [self.typingctx.resolve_argument_type(a) for a in args])
--> 861         kernel = self.compile(argtypes)
    862         kernel.launch(args, griddim, blockdim, stream, sharedmem)
    863 

/usr/local/lib/python3.7/dist-packages/numba/cuda/compiler.py in compile(self, sig)
    933             self.definitions[(cc, argtypes)] = kernel
    934             if self._bind:
--> 935                 kernel.bind()
    936             self.sigs.append(sig)
    937         return kernel

/usr/local/lib/python3.7/dist-packages/numba/cuda/compiler.py in bind(self)
    574         Force binding to current CUDA context
    575         """
--> 576         self._func.get()
    577 
    578     @property

/usr/local/lib/python3.7/dist-packages/numba/cuda/compiler.py in get(self)
    444         cufunc = self.cache.get(device.id)
    445         if cufunc is None:
--> 446             ptx = self.ptx.get()
    447 
    448             # Link

/usr/local/lib/python3.7/dist-packages/numba/cuda/compiler.py in get(self)
    414             arch = nvvm.get_arch_option(*cc)
    415             ptx = nvvm.llvm_to_ptx(self.llvmir, arch=arch,
--> 416                                    **self._extra_options)
    417             self.cache[cc] = ptx
    418             if config.DUMP_ASSEMBLY:

/usr/local/lib/python3.7/dist-packages/numba/cuda/cudadrv/nvvm.py in llvm_to_ptx(llvmir, **opts)
    519     llvmir = llvmir.replace('llvm.numba_nvvm.atomic', 'llvm.nvvm.atomic')
    520 
--> 521     llvmir = llvm39_to_34_ir(llvmir)
    522     cu.add_module(llvmir.encode('utf8'))
    523     cu.add_module(libdevice.get())

/usr/local/lib/python3.7/dist-packages/numba/cuda/cudadrv/nvvm.py in llvm39_to_34_ir(ir)
    662                 line = re_parenthesized_list.sub(
    663                     _replace_llvm_memset_usage,
--> 664                     line,
    665                     )
    666         if 'declare' in line:

/usr/local/lib/python3.7/dist-packages/numba/cuda/cudadrv/nvvm.py in _replace_llvm_memset_usage(m)
    687     align_attr = re.search(r'align (\d+)', params[0])
    688     if not align_attr:
--> 689         raise ValueError("No alignment attribute found on memset dest")
    690     else:
    691         align = align_attr.group(1)

ValueError: No alignment attribute found on memset dest
```

</p>
</details>

However, when `gpu_result` is not assigned a new value, it works.
```python
from numba import cuda
import numpy as np

@cuda.jit
def gpu_run(gpu_result,N):
  idx = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x 
  if (idx < N):
    pass#gpu_result[idx] = 'a'

def main():
  gpu_result = cuda.to_device(np.zeros(9).astype("<U12"))
  gpu_run[2, 4](gpu_result,8)
  print(gpu_result.copy_to_host())#['0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0']
  cuda.synchronize()

if __name__ == "__main__":
  main()
```
Thanks.

**Comment by gmarkall** [comment]
With current master, the traceback is:

```
$ python repro.py 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 710, in cast
    impl = self._casts.find((fromty, toty))
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 48, in find
    out = self._find(sig)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 57, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.core.base.OverloadSelector object at 0x7fbe50b3bee0>, (Literal[str](a), unicode_type))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 379, in lower_inst
    return self.lower_setitem(inst.target, inst.index, inst.value,
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 470, in lower_setitem
    value = self.context.cast(self.builder, value, valuety,
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 713, in cast
    raise NotImplementedError(
NotImplementedError: Cannot cast Literal[str](a) to unicode_type: %".135" = load i8*, i8** %"$const34.0"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/7041/repro.py", line 20, in <module>
    main()
  File "/home/gmarkall/numbadev/issues/7041/repro.py", line 14, in main
    gpu_run[2, 4](gpu_result, 8)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 827, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 970, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 978, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 1092, in compile
    kernel = _Kernel(self.py_func, argtypes, link=self.link,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 518, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 158, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 675, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 419, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 483, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 462, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 453, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 396, in run_pass
    lower.lower()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in cuda mode pipeline (step: native lowering)
Cannot cast Literal[str](a) to unicode_type: %".135" = load i8*, i8** %"$const34.0"

File "repro.py", line 9:
def gpu_run(gpu_result, N):
    <source elided>
    if idx < N:
        gpu_result[idx] = "a"
        ^

During: lowering "gpu_result[idx] = $const34.0" at /home/gmarkall/numbadev/issues/7041/repro.py (9)
```

**Comment by gmarkall** [comment]
Strings are not supported in the CUDA target, which is the root cause of the issue - see the list of supported features in the CUDA target: https://numba.readthedocs.io/en/latest/cuda/cudapysupported.html

However, I'm looking into whether this simple use case can be supported. @JamesHoi if your reproducer above worked, are there operations you want to do with strings other than assigning them to array elements in order to use the CUDA target for your application?

**Comment by stuartarchibald** [comment]
xref https://github.com/numba/numba/pull/6917 which implements the type conversion.

**Comment by gmarkall** [comment]
Also xref #7052 which adds a missing (sometimes) type conversion. I still need to go back and check if this makes any difference to this issue (in conjunction with #6917 perhaps).
