### ISSUE TITLE
TypingError: movemen is not defined

### ISSUE THREAD

**Issue by NobodyXu** [numba/numba#7054]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```
Traceback (most recent call last):                                                                    
  File "./.py", line 269, in <module>                                                          
    data = load(name)                                                                                 
  File "./py", line 263, in load                                                              
    data.append(extract_features(...))
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')                                                                        
  File "/home/nobodyxu/.local/lib/python3.8/site-packages/numba/core/dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)                                                                      
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
NameError: name 'movemen' is not defined
```

`extract_features` return a `list` of `numpy` array and `data` is a python `list`.

This error here looks like a typo in the implementation of numba where it is supposed to be `movemem`, but typed as `movemen`.

**Comment by NobodyXu** [comment]
After inspecting my code, this seems to be a typo there.
