### ISSUE TITLE
Support accessing static values of classes in JIT functions

### ISSUE THREAD

**Issue by ehsantn** [numba/numba#7069]
---

## Feature request

I came across this gap recently. Static values of classes can be handled similar to global/free variables I think.

```python
import numba

class Foo:
    pass

class Bar:
    a = Foo()

@numba.njit
def f():
    return Bar.a

f()
```
```
  File "/Users/ehsan/dev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/ehsan/dev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/ehsan/dev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/ehsan/dev/numba/numba/core/typed_passes.py", line 104, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/Users/ehsan/dev/numba/numba/core/typed_passes.py", line 80, in type_inference_stage
    infer.build_constraint()
  File "/Users/ehsan/dev/numba/numba/core/typeinfer.py", line 1024, in build_constraint
    self.constrain_statement(inst)
  File "/Users/ehsan/dev/numba/numba/core/typeinfer.py", line 1371, in constrain_statement
    self.typeof_assign(inst)
  File "/Users/ehsan/dev/numba/numba/core/typeinfer.py", line 1442, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/Users/ehsan/dev/numba/numba/core/typeinfer.py", line 1542, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "/Users/ehsan/dev/numba/numba/core/typeinfer.py", line 1463, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'Bar': Cannot determine Numba type of <class 'type'>

File "../tmp/class_static.py", line 12:
def f():
    return Bar.a
    ^
```

**Comment by esc** [comment]
thank you @ehsantn -- I have marked this as a feature request.

**Comment by jeertmans** [comment]
Hi !
After trying on my own, I think your feature would be implemented by adding support for static class members:

```python
from numba.experimental import jitclass
from numba import njit

@jitclass
class Foo:
    def __init__(self):
        pass

@jitclass
class Bar:
    a = Foo()
    def __init__(self):
        pass


@njit
def f():
    return Bar.a

f()
```

```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-a7328867ffb4> in <module>
     13 
     14 @jitclass
---> 15 class Bar:
     16     a = Foo()
     17     def __init__(self):

~/.local/lib/python3.8/site-packages/numba/experimental/jitclass/decorators.py in jitclass(cls_or_spec, spec)
     79         return wrap
     80     else:
---> 81         return wrap(cls_or_spec)

~/.local/lib/python3.8/site-packages/numba/experimental/jitclass/decorators.py in wrap(cls)
     74             return cls
     75         else:
---> 76             return register_class_type(cls, spec, types.ClassType, ClassBuilder)
     77 
     78     if cls_or_spec is None:

~/.local/lib/python3.8/site-packages/numba/experimental/jitclass/base.py in register_class_type(cls, spec, class_ctor, builder)
    209         msg = "class members are not yet supported: {0}"
    210         members = ', '.join(others.keys())
--> 211         raise TypeError(msg.format(members))
    212 
    213     for k, v in props.items():

TypeError: class members are not yet supported: a
```

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/issues/5339
