### ISSUE TITLE
Numba caches relative imports and not absolute

### ISSUE THREAD

**Issue by mikaeltw** [numba/numba#7075]
Calling a function decorated with `@numba.njit(cache=True)` results in a relative import being stored to `__pycache__`. When the cached compiled function is later imported and called from a file in another directory than where it is was called when the cache was created a  `ModuleNotFoundError` is thrown.

The issue for me occurs since I test the `njit` decorated functions using `pytest` before calling them in my production code. This relative storage of module paths then leads to the error being thrown in runtime since the `__pycache__` is already there from the run with `pytest`.

Could the `cache=True` store absolute paths or not store the paths at all perhaps?

Tested on:
Linux Ubuntu 20.04 LTS with `numba==0.53.1` and `python==3.8.5`

Reproducible code:
Deflate the tar.gz file and run the script `test_path.sh` inside to reproduce the issue.
[issue_numba_cache_import.tar.gz](https://github.com/numba/numba/files/6591209/issue_numba_cache_import.tar.gz)

**Comment by gmarkall** [comment]
Traceback:

```
$ ./test_path.sh 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/7075/issue_numba_cache_import/call_jit.py", line 3, in <module>
    module.myfunc(value=5)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 440, in _compile_for_args
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 373, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 892, in compile
    cres = self._cache.load_overload(sig, self.targetctx)
  File "/home/gmarkall/numbadev/numba/numba/core/caching.py", line 644, in load_overload
    return self._load_overload(sig, target_context)
  File "/home/gmarkall/numbadev/numba/numba/core/caching.py", line 651, in _load_overload
    data = self._cache_file.load(key)
  File "/home/gmarkall/numbadev/numba/numba/core/caching.py", line 500, in load
    return self._load_data(data_name)
  File "/home/gmarkall/numbadev/numba/numba/core/caching.py", line 542, in _load_data
    tup = pickle.loads(data)
  File "/home/gmarkall/numbadev/numba/numba/core/environment.py", line 51, in _rebuild_env
    mod = importlib.import_module(modname)
  File "/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'module'
```

**Comment by gmarkall** [comment]
Following on from triage meeting discussion: this is a bug, and either:

- This is disallowed and needs a better error message, or
- This should be supported, but doesn't work correctly in this case.

(which of the two above is not yet determined)
