### ISSUE TITLE
Numba throwing time error help needed urgently

### ISSUE THREAD

**Issue by ituMINali** [numba/numba#7076]
`Traceback (most recent call last):
  File "mainFILE.py", line 154, in <module>
    onCMD()
  File "mainFILE.py", line 145, in onCMD
    onSCRN()
  File "C:\Users\DR0ID_Y\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\dispatcher.py", line 420, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\DR0ID_Y\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\dispatcher.py", line 361, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'sleep' of type Module(<module 'time' (built-in)>)

File "mainFILE.py", line 144:
    def onSCRN():
        <source elided>
            print(frame)
            time.sleep(frminterval)
            ^

During: typing of get attribute at mainFILE.py (144)

File "mainFILE.py", line 144:
    def onSCRN():
        <source elided>
            print(frame)
            time.sleep(frminterval)
            ^`

**Comment by seibert** [comment]
Numba doesn't support compiling `time.sleep()`, which is why you see this error.

**Comment by gmarkall** [comment]
Questions like this are best asked on the Discourse group: https://numba.discourse.group

**Comment by ituMINali** [comment]
thank you
