### ISSUE TITLE
Numba causes crash when using python climate-indices package in terminal

### ISSUE THREAD

**Issue by Linimie** [numba/numba#7091]
Dear all,

I have installed and have been trying to apply the climate indices python package that is usable in the terminal with their provided example data. The PET, SPI and SPEI commands work without error, but when choosing 'palmers' I get an error based on Numba. Does anybody know how to solve this? I am using Ubuntu 20.04.2 LTS

The climate indices package plus example information I downloaded from here: https://pypi.org/project/climate-indices/

 The Numba error that I am receiving in the terminal is as follows:
 
`process_climate_indices --index palmers --periodicity monthly --netcdf_precip nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc nclimgrid_lowres_soil.nc --var_name_awc awc --output_file_base ../output/linda_nclimgrid_lowres --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all
2021-06-08  14:57:40 INFO Start time:    2021-06-08 14:57:40.184163
2021-06-08  14:57:40 INFO Computing PALMERS
2021-06-08  14:57:53 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 662, in new_error_context
    yield
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/pylowering.py", line 176, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.ir.EnterWith'>, <numba.ir.EnterWith object at 0x7fc191806f10>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1478, in _apply_along_axis_palmers
    precip[j], pet[j], awc[j], parameters=args
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1142, in _palmers
    calibration_end_year=parameters["calibration_end_year"])
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 395, in _compile_for_args
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 728, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 675, in backend_object_mode
    self.flags)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1167, in py_lowering_stage
    lower.lower()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.EnterWith'>, <numba.ir.EnterWith object at 0x7fc191806f10>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

[1] During: lowering "enter_with $phi100.1" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1813, in main
    _compute_write_index(kwrgs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 869, in _compute_write_index
    args=args,
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1296, in _parallel_process
    pool.map(_apply_along_axis_palmers, chunk_params)
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.EnterWith'>, <numba.ir.EnterWith object at 0x7fc191806f10>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

[1] During: lowering "enter_with $phi100.1" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 662, in new_error_context
    yield
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/pylowering.py", line 176, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.ir.EnterWith'>, <numba.ir.EnterWith object at 0x7fc191806f10>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1478, in _apply_along_axis_palmers
    precip[j], pet[j], awc[j], parameters=args
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1142, in _palmers
    calibration_end_year=parameters["calibration_end_year"])
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 395, in _compile_for_args
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 352, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 693, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 76, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 90, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/dispatcher.py", line 108, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 728, in stage_objectmode_backend
    self._backend(lowerfn, objectmode=True)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 703, in _backend
    lowered = lowerfn()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 675, in backend_object_mode
    self.flags)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/compiler.py", line 1167, in py_lowering_stage
    lower.lower()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 177, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 218, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 243, in lower_function_body
    self.lower_block(block)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/lowering.py", line 258, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/errors.py", line 670, in new_error_context
    six.reraise(type(newerr), newerr, tb)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/six.py", line 659, in reraise
    raise value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.EnterWith'>, <numba.ir.EnterWith object at 0x7fc191806f10>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

[1] During: lowering "enter_with $phi100.1" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/linda/anaconda3/bin/process_climate_indices", line 10, in <module>
    sys.exit(main())
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1813, in main
    _compute_write_index(kwrgs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 869, in _compute_write_index
    args=args,
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1296, in _parallel_process
    pool.map(_apply_along_axis_palmers, chunk_params)
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
numba.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.ir.EnterWith'>, <numba.ir.EnterWith object at 0x7fc191806f10>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with warnings.catch_warnings():
    ^

[1] During: lowering "enter_with $phi100.1" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.45.1.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
`

**Comment by stuartarchibald** [comment]
Thanks for the report. I think the issue(s) are as follows:
1. 0.45.0 is a very old version of Numba, please consider updating this, 0.53.x is the latest version.
2. `with` driven context manager use is very limited in Numba, there's only one real use case supported in nopython mode and that's `with numba.objmode` https://numba.readthedocs.io/en/stable/user/withobjmode.html#numba.objmode. In object mode it should work but will need a recent version of Numba.

**Comment by Linimie** [comment]
Thank you very much for your prompt response.
I have updated my Numba to version 0.53.1 and ran the climate indices again. It still crashed but with a somewhat smaller error code than the one above, however it is indeed still finding fault in `with`.  
When altering the code too: `with objmode(warnings.catch_warnings()):` (see attached file) I get the following error (similar to the last one):


`process_climate_indices --index palmers --periodicity monthly --netcdf_precip nclimgrid_lowres_prcp.nc --var_name_precip prcp --netcdf_pet nclimgrid_lowres_pet.nc --var_name_pet pet --netcdf_awc nclimgrid_lowres_soil.nc --var_name_awc awc --output_file_base ../output/linda_nclimgrid_lowres --calibration_start_year 1951 --calibration_end_year 2010 --multiprocessing all
2021-06-08  15:33:22 INFO Start time:    2021-06-08 15:33:22.467978
2021-06-08  15:33:22 INFO Computing PALMERS
2021-06-08  15:33:37 ERROR Failed to complete
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/errors.py", line 744, in new_error_context
    yield
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/pylowering.py", line 168, in lower_inst
    raise NotImplementedError(type(inst), inst)
NotImplementedError: (<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7fbdfc86e790>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/linda/anaconda3/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1478, in _apply_along_axis_palmers
    precip[j], pet[j], awc[j], parameters=args
  File "/home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/__main__.py", line 1142, in _palmers
    calibration_end_year=parameters["calibration_end_year"])
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 439, in _compile_for_args
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 372, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 909, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 79, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 93, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/dispatcher.py", line 111, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 353, in compile_extra
    return self._compile_bytecode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 415, in _compile_bytecode
    return self._compile_core()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 395, in _compile_core
    raise e
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler.py", line 386, in _compile_core
    pm.run(self.state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 339, in run
    raise patched_exception
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 120, in run_pass
    lowered = backend_object_mode()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 118, in backend_object_mode
    state.flags)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/object_mode_passes.py", line 78, in _py_lowering_stage
    lower.lower()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 136, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 190, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 216, in lower_function_body
    self.lower_block(block)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/lowering.py", line 230, in lower_block
    self.lower_inst(inst)
  File "/home/linda/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/linda/anaconda3/lib/python3.7/site-packages/numba/core/errors.py", line 751, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in object mode pipeline (step: object mode backend)
(<class 'numba.core.ir.EnterWith'>, <numba.core.ir.EnterWith object at 0x7fbdfc86e790>)

File "../../../../../../anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py", line 512:
def _cafec_coefficients(potential_evapotranspiration: np.ndarray,
    <source elided>

    with objmode(warnings.catch_warnings()):
    ^

During: lowering "enter_with $phi106.0" at /home/linda/anaconda3/lib/python3.7/site-packages/climate_indices/palmer.py (512)
"""
`
[palmer.txt](https://github.com/numba/numba/files/6616951/palmer.txt)

**Comment by stuartarchibald** [comment]
@Linimie thanks for the update. I think it might be a good idea to report this on the `climate_indices` issue tracker https://github.com/monocongo/climate_indices/issues, they may have more sense of what the issue is or what is intended to work.

As an aside, `with objmode` is not intended to be used as presented ([docs](https://numba.readthedocs.io/en/stable/user/withobjmode.html#numba.objmode)), though I don't think it will impact the error the that is occurring.

**Comment by Linimie** [comment]
@stuartarchibald  thank you very much for thinking along. I agree to open an issue with climate_indices and will do so later today.

**Comment by stuartarchibald** [comment]
Closing this issue as it seems to be resolved. If this is not the case please re-open with a comment about any item that appears to be unresolved. Many thanks.
