### ISSUE TITLE
Bug with recursion in no-python mode

### ISSUE THREAD

**Issue by mblondel** [numba/numba#716]
I am trying to implement a `quicksort` function so as to quickly sort an array in-place from another jitted function. Unfortunately, I get a `numba.typeinfer.TypingError: Untyped global name 'quicksort'` error.

Code:
```python
@numba.njit("void(f8[:], i4[:], i4, i4)")
def _dual_swap(values, indices, i1, i2):
    dtmp = values[i1]
    values[i1] = values[i2]
    values[i2] = dtmp

    itmp = indices[i1]
    indices[i1] = indices[i2]
    indices[i2] = itmp

@numba.njit("i4(f8[:], i4[:], i4, i4)")
def _partition(values, indices, start, end):
    pivot_idx = start + (end - start + 1) / 2
    _dual_swap(values, indices, start, pivot_idx)
    pivot = values[start]
    i = start + 1
    j = start + 1

    while j <= end:
        if values[j] <= pivot:
            _dual_swap(values, indices, i, j)
            i += 1
        j += 1

    _dual_swap(values, indices, start, i - 1)

    return i - 1

@numba.njit("void(f8[:], i4[:], i4, i4)")
def quicksort(values, indices, start, end):
    size = end - start + 1

    if size > 1:
        i = _partition(values, indices, start, end)
        quicksort(values, indices, start, i - 1)
        quicksort(values, indices, i + 1, end)

if __name__ == '__main__':
    import numpy as np
    from numpy.testing import assert_array_equal

    rng = np.random.RandomState(0)
    values = rng.rand(500)
    indices = np.arange(len(values)).astype(np.int32)

    sorted_idx = np.argsort(values)
    sorted_values = values[sorted_idx]
    sorted_indices = indices[sorted_idx]

    quicksort(values, indices, 0, len(values) - 1)

    assert_array_equal(sorted_values, values)
    assert_array_equal(sorted_indices, indices)
```

Full traceback:
```
Traceback (most recent call last):
  File "ivalice/impl/sort.py", line 77, in <module>
    @numba.njit("i4(f8[:], i4[:], i4, i4)")
  File "/anaconda/lib/python2.7/site-packages/numba/decorators.py", line 128, in wrapper
    disp.compile(sig)
  File "/anaconda/lib/python2.7/site-packages/numba/dispatcher.py", line 108, in compile
    flags=flags, locals=locs)
  File "/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 94, in compile_extra
    return_type, flags, locals)
  File "/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 120, in compile_bytecode
    locals)
  File "/anaconda/lib/python2.7/site-packages/numba/compiler.py", line 282, in type_inference_stage
    infer.build_constrain()
  File "/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 299, in build_constrain
    self.constrain_statement(inst)
  File "/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 404, in constrain_statement
    self.typeof_assign(inst)
  File "/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 436, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/anaconda/lib/python2.7/site-packages/numba/typeinfer.py", line 547, in typeof_global
    loc=inst.loc)
numba.typeinfer.TypingError: Untyped global name 'quicksort
```

**Comment by seibert** [comment]
Direct recursion support was added in #1928.  Support will be expanded in the future, but it should cover many use cases.
