### ISSUE TITLE
LoweringError with tuple_setitem and slice

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7166]
The reproducer:

```python
from numba import njit
from numba.cpython.unsafe.tuple import tuple_setitem


@njit
def settuple(t):
    new_t = tuple_setitem(t, 0, t[1])
    return tuple_setitem(new_t, 1, t[0])


t = (0, slice(None, None, None))
print(settuple(t))
```

fails with a `LoweringError` with the following traceback:

```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 710, in cast
    impl = self._casts.find((fromty, toty))
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 48, in find
    out = self._find(sig)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 57, in _find
    raise NotImplementedError(self, sig)
NotImplementedError: (<numba.core.base.OverloadSelector object at 0x7f54542962b0>, (slice<a:b>, Union[int64,slice<a:b>]))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 755, in new_error_context
    yield
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 231, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 361, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 537, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 1065, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 796, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 1018, in _lower_call_normal
    argvals = self.fold_call_args(
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 735, in fold_call_args
    argvals = typing.fold_arguments(pysig,
  File "/home/gmarkall/numbadev/numba/numba/core/typing/templates.py", line 243, in fold_arguments
    ba.arguments[name] = normal_handler(i, param, ba.arguments[name])
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 722, in normal_handler
    return self._cast_var(var, signature.args[index])
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 701, in _cast_var
    return self.context.cast(self.builder, val, varty, ty)
  File "/home/gmarkall/numbadev/numba/numba/core/base.py", line 713, in cast
    raise NotImplementedError(
NotImplementedError: Cannot cast slice<a:b> to Union[int64,slice<a:b>]: %".8" = extractvalue {i64, {i64, i64, i64}} %"inserted.f1", 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "repro.py", line 12, in <module>
    print(settuple(t))
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 501, in _compile_for_args
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 434, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 979, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 141, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 155, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 168, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 682, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 426, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 490, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 469, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 460, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 396, in run_pass
    lower.lower()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 137, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 191, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 217, in lower_function_body
    self.lower_block(block)
  File "/home/gmarkall/numbadev/numba/numba/core/lowering.py", line 231, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/miniconda3/envs/numbacuda102/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/gmarkall/numbadev/numba/numba/core/errors.py", line 765, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Cannot cast slice<a:b> to Union[int64,slice<a:b>]: %".8" = extractvalue {i64, {i64, i64, i64}} %"inserted.f1", 1

File "repro.py", line 7:
def settuple(t):
    new_t = tuple_setitem(t, 0, t[1])
    ^

During: lowering "new_t = call $2load_global.0(t, $const6.2, $12binary_subscr.5, func=$2load_global.0, args=[Var(t, repro.py:7), Var($const6.2, repro.py:7), Var($12binary_subscr.5, repro.py:7)], kws=(), vararg=None, target=None)" at repro.py (7)
```

**Comment by gmarkall** [comment]
cc @itamarst

**Comment by stuartarchibald** [comment]
I don't think this code is a legal use of `tuple_setitem`. Looking at the docs:
https://github.com/numba/numba/blob/e7db1d9174f9ac329c161f3ac977972dcaa5ba66/numba/cpython/unsafe/tuple.py#L11-L22

> The dtype of the tuple cannot be changed. 

Is the key part. In the above `t` is a `Tuple` so it's `dtype` is a composed of the dtypes of its members (`Union`), altering the tuple to make it larger would alter the dtype. It fails at the cast because you can't cast a slice type to union.

**Comment by itamarst** [comment]
1. The tuple is not being made larger, it's the same size.
2. Given a dtype of `Union([A, B])`, why shouldn't one be able to set a value of type `A` or `B`?

Lacking this functionality, it's impossible to construct tuples that are mixes of slices and integers, which means certain NumPy operations are impossible.

**Comment by stuartarchibald** [comment]
>     1. The tuple is not being made larger, it's the same size.

Apologies, you are correct, it is not altering size, but the dtype of the tuple members would be changing. I.e. first is becoming a slice?

>     2. Given a dtype of `Union([A, B])`, why shouldn't one be able to set a value of type `A` or `B`?

I think this is because at present `Union` is a type inference convenience, the lowered data structure has to be concrete and is stack allocated. In the above error there's `{i64, {i64, i64, i64}}`, i.e. first item is `int64`, second is `3 x int64` (slice), so you cannot set the first item to be a slice because it's type is `int64`. I also suspect there's some lowering/casting problem that needs looking at but don't think it would necessarily impact this.

> Lacking this functionality, it's impossible to construct tuples that are mixes of slices and integers, which means certain NumPy operations are impossible.

What's the most minimal thing you are trying to do (just in pure python syntax)? Perhaps we can work something out.

**Comment by itamarst** [comment]
I'm trying to implement `take_along_axis`. Two alternative implementations are either the example code in the notes here (https://numpy.org/doc/stable/reference/generated/numpy.take_along_axis.html) which uses mixed int/slice tuples, or the actual implementations which I believe (but could be wrong) relies on fancy indexing Numba doesn't support (https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/lib/shape_base.py#L29).

**Comment by stuartarchibald** [comment]
I think there's a bug in `tuple_setitem`, this patch yields the error I'd expect:
```diff
diff --git a/numba/cpython/unsafe/tuple.py b/numba/cpython/unsafe/tuple.py
index 7e30b07..5777ed0 100644
--- a/numba/cpython/unsafe/tuple.py
+++ b/numba/cpython/unsafe/tuple.py
@@ -29,7 +29,7 @@ def tuple_setitem(typingctx, tup, idx, val):
         builder.store(val, offptr)
         return builder.load(stack)
 
-    sig = tup(tup, idx, tup.dtype)
+    sig = tup(tup, idx, val)
     return sig, codegen
```
OP now produces:
```
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
cannot store {i64, i64, i64} to i64*: mismatching types
```
which matches what is going on.

**Comment by itamarst** [comment]
I think I can manage to do what I want to do if I can copy an integer into an index in the tuple that already has an integer, but that doesn't work either:

```python
from numba import njit
from numba.cpython.unsafe.tuple import tuple_setitem


@njit
def settuple(t, i):
    return tuple_setitem(t, i, 456)


t = (123, slice(None, None, None))
print(settuple(t, 0))
```

Notice that I'm trying to override 123 with 456, but it still doesn't work.

**Comment by itamarst** [comment]
```
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Cannot cast Literal[int](456) to Union[int64,slice<a:b>]: i64 456

File "example2.py", line 7:
def settuple(t, i):
    return tuple_setitem(t, i, 456)
    ^

During: lowering "$10call_function.4 = call $2load_global.0(t, i, $const8.3, func=$2load_global.0, args=[Var(t, example2.py:7), Var(i, example2.py:7), Var($const8.3, example2.py:7)], kws=(), vararg=None, target=None)" at example2.py (7)
```

**Comment by itamarst** [comment]
I don't think the proposed change is correct, when I try the second example (just above) with that change, there's what is probably an `AttributeError` (`'Argument' object has no attribute 'constant'`).

**Comment by stuartarchibald** [comment]
@itamarst I think this does what you are looking for RE `take_along_axis`:
```python
import numpy as np
from numba import njit
from numba.extending import overload
from numba.cpython.unsafe.tuple import tuple_setitem

# Translated from/inspired by the notes section of:
# https://numpy.org/doc/stable/reference/generated/numpy.take_along_axis.html
# Source reference:
# https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/lib/shape_base.py#L88-L107
# NumPy source license: https://github.com/numpy/numpy/blob/main/LICENSE.txt

@overload(np.take_along_axis, jit_options={'boundscheck':True})
def ol_take_along_axis(arr, indices, axis):

    n = arr.ndim
    t = tuple([((0,)*a, (0,)*b) for a, b in [(x, n - x - 1) for x in range(n)]])

    def impl(arr, indices, axis):
        z = t[axis]
        Ni = z[0]
        for i in range(len(Ni)):
            Ni = tuple_setitem(Ni, i, arr.shape[i])
        M = arr.shape[axis]
        Nk = z[1]
        for i in range(len(Nk)):
            Nk = tuple_setitem(Nk, i, arr.shape[axis + i])

        J = indices.shape[axis]
        out = np.empty(Ni + (J,) + Nk, arr.dtype)

        for ii in np.ndindex(Ni):
            for kk in np.ndindex(Nk):
                np_s_ = (slice(None, None, None),)
                a_1d       = a      [ii + np_s_ + kk]
                indices_1d = indices[ii + np_s_ + kk]
                out_1d     = out    [ii + np_s_ + kk]
                for j in range(J):
                    out_1d[j] = a_1d[indices_1d[j]]
        return out
    return impl


a = np.arange(24).reshape((3, 2, 2, 2))
ai = np.argsort(a, axis=1)

@njit
def foo(a, ai):
    return np.take_along_axis(a, ai, axis=1)

for x in range(a.ndim):
    print(foo(a, ai))
    print(foo.py_func(a, ai))
```

**Comment by itamarst** [comment]
Thank you! That needs a bunch of additional changes (e.g. lowering tuple_setitem fails if compiler notices it's being called on empty tuple, even if in practice the for loop actually prevents it from being called—reproducible with axis=0) but I might I have some solutions for that. Maybe :grinning:

**Comment by itamarst** [comment]
(Turns out the real take_along_axis and the sketch in NumPy docs that is based on do not have the same behavior :cry:)

**Comment by stuartarchibald** [comment]
> (Turns out the real take_along_axis and the sketch in NumPy docs that is based on do not have the same behavior cry)

That's a shame. If this function is to be supported, I guess this is the first thing to work out.

**Comment by itamarst** [comment]
Further testing suggests I was at fault, not NumPy: I forgot to rename a variable, so it got bound to variable from nested parent function. So I hope to have PR of initial `take_along_axis` in not too distant future.

But I still want better tuple support :(
