### ISSUE TITLE
operator.eq with Bytes selects Numpy_rules_ufunc template's signature

### ISSUE THREAD

**Issue by njriasan** [numba/numba#7174]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I tried checking equality on two bytes types and get the folllowing error.

```python
import numba
@numba.njit
def test(lhs, rhs):
    return lhs == rhs
print(test(b'hello', b'124223'))
```

```python
Traceback (most recent call last):
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typeinfer.py", line 154, in propagate
    constraint(typeinfer)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typeinfer.py", line 190, in __call__
    typeinfer.copy_type(self.src, self.dst, loc=self.loc)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typeinfer.py", line 1095, in copy_type
    self.typevars[dest_var].union(self.typevars[src_var], loc=loc)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typeinfer.py", line 106, in union
    self.add_type(other.type, loc=loc)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typeinfer.py", line 61, in add_type
    raise TypingError(msg % (tp, self.type, self.var,
numba.core.errors.TypingError: No conversion from array(bool, 1d, C) to bool for '$8return_value.3', defined at None

File "temp_test.py", line 1:
import numba
^

During: typing of assignment at temp_test.py (1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "temp_test.py", line 8, in <module>
    print(test(b'hello', b"124223"))
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 421, in error_rewrite
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 434, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 979, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 145, in compile
    raise retval
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 155, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 168, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 686, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 428, in compile_extra
    return self._compile_bytecode()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 492, in _compile_bytecode
    return self._compile_core()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 471, in _compile_core
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 462, in _compile_core
    pm.run(self.state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typed_passes.py", line 396, in run_pass
    lower.lower()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 138, in lower
    self.lower_normal_function(self.fndesc)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 192, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 221, in lower_function_body
    self.lower_block(block)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 235, in lower_block
    self.lower_inst(inst)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 373, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 549, in lower_assign
    return self.lower_expr(ty, value)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 1283, in lower_expr
    res = self.context.special_ops[expr.op](self, expr)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/np/ufunc/array_exprs.py", line 384, in _lower_array_expr
    cres = context.compile_subroutine(builder, impl, inner_sig, flags=flags,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/base.py", line 875, in compile_subroutine
    cres = self._compile_subroutine_no_cache(builder, impl, sig,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/base.py", line 846, in _compile_subroutine_no_cache
    cres = compiler.compile_internal(self.typing_context, self,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 760, in compile_internal
    return pipeline.compile_extra(func)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 428, in compile_extra
    return self._compile_bytecode()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 492, in _compile_bytecode
    return self._compile_core()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 471, in _compile_core
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 462, in _compile_core
    pm.run(self.state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typeinfer.py", line 1074, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: native lowering)
Failed in nopython mode pipeline (step: nopython frontend)
No conversion from array(bool, 1d, C) to bool for '$8return_value.3', defined at None

File "temp_test.py", line 1:
import numba
^

During: typing of assignment at temp_test.py (1)

File "temp_test.py", line 1:
import numba
^

During: lowering "$6compare_op.2 = arrayexpr(expr=(<built-in function eq>, [Var(lhs, temp_test.py:5), Var(rhs, temp_test.py:5)]), ty=array(bool, 1d, C))" at temp_test.py (5)
```

This isn't suprising because `operator.eq` doesn't appear to be implemented for bytes. However, what is surprising is that it matches a signature with output `types.Array(bool, 1, "C")`. This appears to happen because bytes is a subclass of ArrayCompatable, so the Numpy_rules_ufunc template matches.

I've tried to provide an overload for eq, but I can't seem to get Numba to select it (maybe because the return types don't match).

**Comment by njriasan** [comment]
Should bytes extend ArrayCompatable (via Buffer)? It seems more reasonable that like UnicodeType Bytes should just extend IterableType.

**Comment by gmarkall** [comment]
I can reproduce this. Further, i note that the source location marker is inaccurate here:

```
File "repro.py", line 1:
import numba
^
```

Though the line/column information for the expression is correct:

```
During: lowering "$6compare_op.2 = arrayexpr(expr=(<built-in function eq>, [Var(lhs, repro.py:4), Var(rhs, repro.py:4)]), ty=array(bool, 1d, C))" at /home/gmarkall/numbadev/issues/7174/repro.py (4)
```

**Comment by stuartarchibald** [comment]
> I can reproduce this. Further, i note that the source location marker is inaccurate here:
> 
> ```
> File "repro.py", line 1:
> import numba
> ^
> ```
> 
> Though the line/column information for the expression is correct:
> 
> ```
> During: lowering "$6compare_op.2 = arrayexpr(expr=(<built-in function eq>, [Var(lhs, repro.py:4), Var(rhs, repro.py:4)]), ty=array(bool, 1d, C))" at /home/gmarkall/numbadev/issues/7174/repro.py (4)
> ```

I noticed that too, I expect it's something small that's out in the formatter.
