### ISSUE TITLE
CUDA: IPC tests run and fail when IPC is unsupported

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7178]
Running the IPC tests when IPC is not supported (E.g. on a Jetson) results in fails like:

```
======================================================================
ERROR: test_ipc_array (numba.cuda.tests.cudapy.test_ipc.TestIpcMemory) (index=None, foreign=False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/numba/numba/cuda/tests/cudapy/test_ipc.py", line 190, in test_ipc_array
    self.check_ipc_array(index, foreign)
  File "/home/nvidia/numba/numba/cuda/tests/cudapy/test_ipc.py", line 172, in check_ipc_array
    ipch = devarr.get_ipc_handle()
  File "/home/nvidia/numba/numba/cuda/cudadrv/devicearray.py", line 306, in get_ipc_handle
    ipch = devices.get_context().get_ipc_handle(self.gpu_data)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 1145, in get_ipc_handle
    return self.memory_manager.get_ipc_handle(memory)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 837, in get_ipc_handle
    driver.cuIpcGetMemHandle(byref(ipchandle), base)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [801] Call to cuIpcGetMemHandle results in CUDA_ERROR_NOT_SUPPORTED

======================================================================
======================================================================
ERROR: test_ipc_array (numba.cuda.tests.cudapy.test_ipc.TestIpcMemory) (index=None, foreign=True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nvidia/numba/numba/cuda/tests/cudapy/test_ipc.py", line 190, in test_ipc_array
    self.check_ipc_array(index, foreign)
  File "/home/nvidia/numba/numba/cuda/tests/cudapy/test_ipc.py", line 172, in check_ipc_array
    ipch = devarr.get_ipc_handle()
  File "/home/nvidia/numba/numba/cuda/cudadrv/devicearray.py", line 306, in get_ipc_handle
    ipch = devices.get_context().get_ipc_handle(self.gpu_data)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 1145, in get_ipc_handle
    return self.memory_manager.get_ipc_handle(memory)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 837, in get_ipc_handle
    driver.cuIpcGetMemHandle(byref(ipchandle), base)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/nvidia/numba/numba/cuda/cudadrv/driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [801] Call to cuIpcGetMemHandle results in CUDA_ERROR_NOT_SUPPORTED
```

The test suite should check whether IPC is supported and skip these tests where it is not.

**Comment by seibert** [comment]
Also related: #2849

**Comment by gmarkall** [comment]
Thanks @seibert - I did come across that after opening this issue - I'll have a look into the host memory registration issue whilst I'm having a look at this (although I didn't bump into that problem, so maybe Xavier supports it).

**Comment by gmarkall** [comment]
It turns out the resolution will be straightforward - skipping this test when the platform is ARM or AArch64 will be appropriate.

**Comment by gmarkall** [comment]
#7189 contains a fix (cc @jeffhammond)
