### ISSUE TITLE
No module named 'pkg_resources'

### ISSUE THREAD

**Issue by PerchunPak** [numba/numba#7181]
## Reporting a bug
Full traceback of error
```
python main.py
Traceback (most recent call last):
  File "E:\servers\programming\pyton\test\main.py", line 1, in <module>
    from numba import njit
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\__init__.py", line 39, in <module>
    from numba.core.decorators import (cfunc, generated_jit, jit, njit, stencil,
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\decorators.py", line 12, in <module>
    from numba.stencils.stencil import stencil
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\stencils\stencil.py", line 11, in <module>
    from numba.core import types, typing, utils, ir, config, ir_utils, registry
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\registry.py", line 4, in <module>
    from numba.core import utils, typing, dispatcher, cpu
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 16, in <module>
    from numba.core import utils, types, errors, typing, serialize, config, compiler, sigutils
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\compiler.py", line 6, in <module>
    from numba.core import (utils, errors, typing, interpreter, bytecode, postproc,
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\cpu.py", line 16, in <module>
    import numba.core.entrypoints
  File "C:\Users\perch\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\entrypoints.py", line 4, in <module>
    from pkg_resources import iter_entry_points
ModuleNotFoundError: No module named 'pkg_resources'
```
My code
```
import numba
```
Installing log
```
C:\Windows\system32>pip uninstall numba
Found existing installation: numba 0.53.1
Uninstalling numba-0.53.1:
  Would remove:
    c:\users\perch\appdata\local\programs\python\python38\lib\site-packages\numba-0.53.1.dist-info\*
    c:\users\perch\appdata\local\programs\python\python38\lib\site-packages\numba\*
    c:\users\perch\appdata\local\programs\python\python38\scripts\numba
    c:\users\perch\appdata\local\programs\python\python38\scripts\pycc
Proceed (y/n)? y
  Successfully uninstalled numba-0.53.1

C:\Windows\system32>pip uninstall setuptools
Found existing installation: setuptools 57.0.0
Uninstalling setuptools-57.0.0:
  Would remove:
    c:\users\perch\appdata\local\programs\python\python38\lib\site-packages\_distutils_hack\*
    c:\users\perch\appdata\local\programs\python\python38\lib\site-packages\distutils-precedence.pth
    c:\users\perch\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\*
    c:\users\perch\appdata\local\programs\python\python38\lib\site-packages\setuptools-57.0.0.dist-info\*
    c:\users\perch\appdata\local\programs\python\python38\lib\site-packages\setuptools\*
Proceed (y/n)? y
  Successfully uninstalled setuptools-57.0.0

C:\Windows\system32>pip install numba
Collecting numba
  Using cached numba-0.53.1-cp38-cp38-win_amd64.whl (2.3 MB)
Requirement already satisfied: numpy>=1.15 in c:\users\perch\appdata\local\programs\python\python38\lib\site-packages (from numba) (1.21.0)
Requirement already satisfied: llvmlite<0.37,>=0.36.0rc1 in c:\users\perch\appdata\local\programs\python\python38\lib\site-packages (from numba) (0.36.0)
Collecting setuptools
  Downloading setuptools-57.1.0-py3-none-any.whl (818 kB)
     |████████████████████████████████| 818 kB 3.2 MB/s
Installing collected packages: setuptools, numba
Successfully installed numba-0.53.1 setuptools-57.1.0

C:\Windows\system32>pip install setuptools
Requirement already satisfied: setuptools in c:\users\perch\appdata\local\programs\python\python38\lib\site-packages (57.1.0)

C:\Windows\system32>python
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by esc** [comment]
@PerchunPak thank you for submitting this. The one thing I notice, is that Python versions seem to be mixed up here.

When you install, this seems to be for Python 3.8:

<img width="831" alt="Screen Shot 2021-07-05 at 09 47 38" src="https://user-images.githubusercontent.com/41563/124436425-39c4a480-dd76-11eb-9eaa-3db477a718b2.png">


But when you run the `python` command you seem to be getting 3.9:

<img width="831" alt="Screen Shot 2021-07-05 at 09 47 48" src="https://user-images.githubusercontent.com/41563/124436463-4517d000-dd76-11eb-9dc1-b0317fe05bb9.png">

Perhaps that is something to look into?

**Comment by PerchunPak** [comment]
Yes, in this error. Thanks

**Comment by esc** [comment]
@PerchunPak thank you for following up and closing this issue.
