### ISSUE TITLE
error_model target option not working with cfunc (and maybe other target options?)

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7183]
The following:

```python
from numba import cfunc, njit

rec_cfunc = cfunc('double(double)', nopython=True, error_model='numpy')(lambda x:  1.0 / x)
rec_njit = njit('f8(f8,)', fastmath=True, error_model='numpy')(lambda x: 1.0 / x)

print(rec_njit(0.0))
print(rec_cfunc(0.0))
```

results in:

```
$ python repro.py 
inf
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/vlovero/repro.py", line 8, in <module>
    print(rec_cfunc(0.0))
  File "/home/gmarkall/numbadev/numba/numba/core/ccallback.py", line 134, in __call__
    return self._pyfunc(*args, **kwargs)
  File "/home/gmarkall/numbadev/issues/vlovero/repro.py", line 4, in <lambda>
    rec_cfunc = cfunc('double(double)', nopython
```

It looks from inspection of the implementation (`cfunc`, `_CFuncCompiler`, `_FunctionCompiler`, etc.) that target options should be passed through as they are with `njit` (I didn't look too deeply though), but `error_model` seems to ultimately have no effect with the `cfunc` decorator - it may be that target options aren't working in general?

**Comment by stuartarchibald** [comment]
Thanks for the report. I can reproduce. In the debugger, it looks like the flags are ending up in the `numba.core.dispatcher._FunctionCompiler` used by `cfunc`, but it's a class member on the `target_context` instance that governs the code gen for e.g. `error_model` and that appears to not be set. The "fix" is probably to remove flag based state from the `target_context` instance and use the config stack.
