### ISSUE TITLE
Unexpected Numba Warnings

### ISSUE THREAD

**Issue by timhdesilva** [numba/numba#7194]
Hi,

I'm fairly new to ``numba`` and am having some issues running basic code. The code I'm running is the following:
```
from numba import jit
import numpy as np

# Parameters
Rf = 1.025 # risk free rate in levels
mu = 1.055 # risky asset average return
W0 = 250000 # initial wealth
sigma = 0.20 # std dev of shock in returns in levels

# Grids of parameters you want to solve over
f_grid = np.linspace(0,5000,10)
theta0_grid = np.linspace(0,1,100)
gamma_grid = np.linspace(1,10,10)

# Grid for posisble portfolio choices
theta_grid = np.linspace(0,1,100)

# Utility funciton
@jit
def Utility(W, gamma):
    if gamma != 1:
        return W**(1-gamma)/(1-gamma)
    else:
        return np.log(W)

# End of period wealth for a given realization of return
@jit
def W1(W0, theta, theta0, f, mu, Rf, eps):
    W1 = W0 * ((1-theta) * Rf + theta * mu * eps)
    if theta != theta0:
        W1 -= f # pay fixed cost of portfolio is adjusted
    return W1

# Realized utility
@jit
def RealizedUtility(W0, theta, theta0, f, mu, Rf, eps, gamma):
    W = W1(W0, theta, theta0, f, mu, Rf, eps)
    return Utility(W, gamma)

# Choose optimal portfolio given parameters
@jit
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    V = -99
    thetaopt = 0
    for theta in theta_grid:
        EU = np.mean([RealizedUtility(W0, theta, theta0, f, mu, Rf, x, gamma) for x in np.random.lognormal(0, sigma, 100)])
        if EU > V:
            V = EU
            thetaopt = theta
    return thetaopt
        
# Solve for different parameters
@jit
def Simulations(f_grid, theta0_grid, gamma_grid):
    results = np.zeros((len(f_grid)*len(theta0_grid)*len(gamma_grid), 4))
    i = 0
    for gamma in gamma_grid:
        for theta0 in theta0_grid:
            for f in f_grid:
                results[i, 0] = gamma
                results[i, 1] = theta0
                results[i, 2] = f
                results[i, 3] = PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma)
                i += 1
    return results

output = Simulations(f_grid, theta0_grid, gamma_grid)
```

Upon doing so, I get the following warnings message that I do not understand:
```
/Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py:68: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "Simulations" failed type inference due to: Invalid use of type(CPUDispatcher(<function PortfolioChoice at 0x7ff72be2d160>)) with parameters (readonly array(float64, 1d, C), Literal[int](250000), float64, float64, float64, float64, float64, float64)

During: resolving callee type: type(CPUDispatcher(<function PortfolioChoice at 0x7ff72be2d160>))
During: typing of call at /Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py (78)


File "simulation.py", line 78:
def Simulations(f_grid, theta0_grid, gamma_grid):
    <source elided>
                results[i, 2] = f
                results[i, 3] = PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma)
                ^

  @jit
/Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py:68: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "Simulations" failed type inference due to: Cannot determine Numba type of <class 'numba.core.dispatcher.LiftedLoop'>

File "simulation.py", line 72:
def Simulations(f_grid, theta0_grid, gamma_grid):
    <source elided>
    i = 0
    for gamma in gamma_grid:
    ^

  @jit
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "Simulations" was compiled in object mode without forceobj=True, but has lifted loops.

File "simulation.py", line 70:
def Simulations(f_grid, theta0_grid, gamma_grid):
    results = np.zeros((len(f_grid)*len(theta0_grid)*len(gamma_grid), 4))
    ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "simulation.py", line 70:
def Simulations(f_grid, theta0_grid, gamma_grid):
    results = np.zeros((len(f_grid)*len(theta0_grid)*len(gamma_grid), 4))
    ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
/Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py:68: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "Simulations" failed type inference due to: Invalid use of type(CPUDispatcher(<function PortfolioChoice at 0x7ff72be2d160>)) with parameters (readonly array(float64, 1d, C), Literal[int](250000), float64, float64, float64, float64, float64, float64)

During: resolving callee type: type(CPUDispatcher(<function PortfolioChoice at 0x7ff72be2d160>))
During: typing of call at /Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py (78)


File "simulation.py", line 78:
def Simulations(f_grid, theta0_grid, gamma_grid):
    <source elided>
                results[i, 2] = f
                results[i, 3] = PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma)
                ^

  @jit
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "Simulations" was compiled in object mode without forceobj=True.

File "simulation.py", line 72:
def Simulations(f_grid, theta0_grid, gamma_grid):
    <source elided>
    i = 0
    for gamma in gamma_grid:
    ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "simulation.py", line 72:
def Simulations(f_grid, theta0_grid, gamma_grid):
    <source elided>
    i = 0
    for gamma in gamma_grid:
    ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
/Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py:55: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "PortfolioChoice" failed type inference due to: No implementation of function Function(<function mean at 0x7ff743571160>) found for signature:
 
mean(list(float64)<iv=None>)
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload of function 'mean': File: numba/core/typing/npydecl.py: Line 348.
        With argument(s): '(list(float64)<iv=None>)':
       No match.

During: resolving callee type: Function(<function mean at 0x7ff743571160>)
During: typing of call at /Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py (61)


File "simulation.py", line 61:
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    <source elided>
        # Approximation of expected value via integration
        EU = np.mean([RealizedUtility(W0, theta, theta0, f, mu, Rf, x, gamma) for x in np.random.lognormal(0, sigma, 100)])
        ^

  @jit
/Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py:55: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "PortfolioChoice" failed type inference due to: Cannot determine Numba type of <class 'numba.core.dispatcher.LiftedLoop'>

File "simulation.py", line 59:
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    <source elided>
    thetaopt = 0
    for theta in theta_grid:
    ^

  @jit
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "PortfolioChoice" was compiled in object mode without forceobj=True, but has lifted loops.

File "simulation.py", line 57:
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    V = -99
    ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "simulation.py", line 57:
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    V = -99
    ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
/Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py:55: NumbaWarning: 
Compilation is falling back to object mode WITHOUT looplifting enabled because Function "PortfolioChoice" failed type inference due to: No implementation of function Function(<function mean at 0x7ff743571160>) found for signature:
 
mean(list(float64)<iv=None>)
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload of function 'mean': File: numba/core/typing/npydecl.py: Line 348.
        With argument(s): '(list(float64)<iv=None>)':
       No match.

During: resolving callee type: Function(<function mean at 0x7ff743571160>)
During: typing of call at /Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py (61)


File "simulation.py", line 61:
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    <source elided>
        # Approximation of expected value via integration
        EU = np.mean([RealizedUtility(W0, theta, theta0, f, mu, Rf, x, gamma) for x in np.random.lognormal(0, sigma, 100)])
        ^

  @jit
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:151: NumbaWarning: Function "PortfolioChoice" was compiled in object mode without forceobj=True.

File "simulation.py", line 59:
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    <source elided>
    thetaopt = 0
    for theta in theta_grid:
    ^

  warnings.warn(errors.NumbaWarning(warn_msg,
/Users/timdesilva/opt/anaconda3/lib/python3.8/site-packages/numba/core/object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-back from the nopython compilation path to the object mode compilation path has been detected, this is deprecated behaviour.

For more information visit https://numba.pydata.org/numba-doc/latest/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit

File "simulation.py", line 59:
def PortfolioChoice(theta_grid, W0, theta0, f, mu, Rf, gamma, sigma):
    <source elided>
    thetaopt = 0
    for theta in theta_grid:
    ^

  warnings.warn(errors.NumbaDeprecationWarning(msg,
Traceback (most recent call last):

  File "/Users/timdesilva/Dropbox (MIT)/Projects/InertiaPortfolioChoice/Two-period simulation/simulation.py", line 82, in <module>
    output = Simulations(f_grid, theta0_grid, gamma_grid)

  File "<__array_function__ internals>", line 2, in mean

KeyboardInterrupt


```

Thanks in advance for the help!

**Comment by guoqiangqi** [comment]
Hi @timhdesilva ，lt seems like that was caused by the unsupport of `np.mean` in nopython mode, i run this script successfully after simply replaced `np.mean(...)` in `PortfolioChoice` with number 0.

**Comment by guoqiangqi** [comment]
`np.mean` just works with `array` type, not `list`.
Change code:
```python
EU = np.mean([RealizedUtility(W0, theta, theta0, f, mu, Rf, x, gamma) for x in np.random.lognormal(0, sigma, 100)])
```
to
```python
EU = np.mean(np.asarray([RealizedUtility(W0, theta, theta0, f, mu, Rf, x, gamma) for x in np.random.lognormal(0, sigma, 100)]))
```
should work.

**Comment by stuartarchibald** [comment]
@timhdesilva as noted by @guoqiangqi the fix is to use an array with `np.mean` as lists are not yet supported as inputs to that function.

More generally, the warnings encountered are due to Numba's compiler trying to compile the code in `nopython` mode and finding it cannot because Numba's `np.mean` implementation doesn't support lists, as a result the compiler falls back to `object mode` and creates a lot of noisy warnings about it. The reason for the warnings it because the performance in object mode isn't always particularly good and can sometimes even be worse than interpreted python.

If you are new to Numba, perhaps take a look at the [5 minute guide](http://numba.pydata.org/numba-doc/latest/user/5minguide.html) first and/or click one of the `Try Now` buttons here http://numba.pydata.org/ to open up an interactive Numba demo in your browser, [this one](https://mybinder.org/v2/gh/numba/numba-examples/master?filepath=notebooks%2Fbasics.ipynb) demonstrates the basics. Both `nopython` and `object mode` are explained in the 5 minute guide.

Given your code is numerically orientated, I'd recommend using `@jit(nopython=True)`/`@njit` (they are aliases) and just fixing things up until it compiles, you'll get much better performance.

Hope this helps?

**Comment by timhdesilva** [comment]
@guoqiangqi and @stuartarchibald -- thank you both very much for the helpful comments! Things work great now, I will definitely look into the ``Try Now`` examples, which I didn't know existed. Thanks again!

**Comment by timhdesilva** [comment]
@stuartarchibald -- one other question if you don't mind (is there a better place to be asking questions than here?) If I want to parallelize the loops in ``PortfolioChoice()`` and ``Simulations()``, I assume I just add ``parallel = True`` to ``@jit(nopython = True)``? I tried doing this and it takes along time (over five minutes) to call the function for the first time, while calling it without the parallel option only takes 4 seconds. Does this with have to do with the fact that the process ``Numba`` uses to compile the function takes longer when ``parallel = True``?

**Comment by guoqiangqi** [comment]
Hi @timhdesilva, We have a channel [numba/numba](https://gitter.im/numba/numba) for discussion on Gitter, you can ask general questions there, the issues here are mostly used to report `feature requests` and `bugs`. When you call the function for the first time in this case, the time you measured  includes the time taken to compile your function in the execution time, check [how-to-measure-the-performance-of-numba](https://numba.readthedocs.io/en/stable/user/5minguide.html#how-to-measure-the-performance-of-numba) in `5 minute guide to Numba` for details.

**Comment by guoqiangqi** [comment]
You can also set the signatures of your function which will allow numba compile the function before it is called, we call this mode [eager-compilation](https://numba.readthedocs.io/en/stable/user/jit.html#eager-compilation).

**Comment by stuartarchibald** [comment]
@timhdesilva as mentioned by @guoqiangqi if you get stuck/need a hand, the Numba core developers are available on [gitter.im](https://gitter.im/numba/numba) real time chat. Numba also has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!

RE: timings. As noted by @guoqiangqi it's important to differentiate between compile time and execution time. It's also worth considering whether all your functions need `parallel=True`, it looks like `Simulations` could benefit from being written with a `prange` loop over `i`, but I don't think there's a need to nest the parallelism and have `PortfolioChoice` also running in parallel. If you did run both with `parallel=True` you'd potentially end up with n-threads from `Simulations` all launching n-threads to run `PortfolioChoice` which could well degrade performance.

**Comment by timhdesilva** [comment]
Sounds good, thanks very much @guoqiangqi and @stuartarchibald!
