### ISSUE TITLE
CUDA: Multi-GPU tests failing on Windows

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7253]
Current master seems to do this for me:

```
======================================================================
FAIL: test_with_context (numba.cuda.tests.cudapy.test_multigpu.TestMultiGPUContext)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\work\numbadev\numba\numba\cuda\tests\cudapy\test_multigpu.py", line 113, in test_with_context
    np.testing.assert_equal(arr1.copy_to_host(), (hostarr + 2))
  File "C:\work\miniconda3\envs\numba\lib\site-packages\numpy\testing\_private\utils.py", line 342, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "C:\work\miniconda3\envs\numba\lib\site-packages\numpy\testing\_private\utils.py", line 930, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "C:\work\miniconda3\envs\numba\lib\site-packages\numpy\testing\_private\utils.py", line 840, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

Mismatched elements: 10 / 10 (100%)
Max absolute difference: 11.
Max relative difference: 1.
 x: array([0.0e+00, 1.4e-45, 2.8e-45, 4.2e-45, 5.6e-45, 7.0e-45, 8.4e-45,
       9.8e-45, 1.1e-44, 1.3e-44], dtype=float32)
 y: array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.], dtype=float32)
```

on Windows 10 with 2x Quadro RTX 8000s, CUDA toolkit 11.4.

**Comment by gmarkall** [comment]
It turns out this was always broken (I tried a few old Numba versions) - it's just that I never tested on a machine with multiple GPUs where peer access was disabled before. #7266 fixes the issue by skipping the check when appropriate.
