### ISSUE TITLE
the error traceback infomation of import numba.

### ISSUE THREAD

**Issue by Milkwayer** [numba/numba#7287]
Traceback (most recent call last):
  File "D:\python\lib\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\phth\Desktop\test.py", line 1, in <module>
    import numba as nb
  File "D:\python\lib\site-packages\numba\__init__.py", line 24, in <module>
    from numba.misc.special import (
  File "D:\python\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "D:\python\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "D:\python\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "D:\python\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "D:\python\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.

**Comment by stuartarchibald** [comment]
@Milkwayer thanks for the report. Please could you include the full error message? There should be a line which says what the system executable is, something like:
```
If possible please include the following in your error report:

sys.executable: <SOME PATH>\python.exe
```
thanks!

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
