### ISSUE TITLE
Compilation fails when creating dicts with lists as mapped values

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#7308]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi,

As it was discussed previously I'm opening a case on this. 
Here's the reproducer:
```
import numba
from numba import types, njit
import numpy as np

@njit
def test_impl():
    aggs = {
        'one': ['mean'],
        'two': ['min', 'max', 'mean'],
        'three': ['std', 'mean']
    }
    return len(aggs)

print(test_impl())
```

That throws:

> Traceback (most recent call last):
>   File "test_numba_dicts_1.py", line 14, in <module>
>     print(test_impl())
>   File "/localdisk/work/akozlov/miniconda3/numba_master/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
>     error_rewrite(e, 'typing')
>   File "/localdisk/work/akozlov/miniconda3/numba_master/numba/numba/core/dispatcher.py", line 361, in error_rewrite
>     raise e.with_traceback(None)
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> list(unicode_type)<iv=None> as value is forbidden
> During: typing of dict at test_numba_dicts_1.py (7)
> 
> File "test_numba_dicts_1.py", line 7:
> def test_impl():
>     aggs = {
>     ^

And explicit use of typed.Dicts ctor with value_type requesting reflected_list as values fails too:

```
import numba
from numba import types, njit
import numpy as np
from numba.typed import Dict

dict_val_type = types.List(types.unicode_type)

@njit
def test_impl():

    aggs = Dict.empty(types.unicode_type, dict_val_type)
    return len(aggs)

print(test_impl())
```

Giving:
>    There are 2 candidate implementations:
>          - Of which 2 did not match due to:
>          Overload in function 'impl_new_dict': File: numba/typed/dictobject.py: Line 639.
>            With argument(s): '(typeref[unicode_type], typeref[list(unicode_type)<iv=None>])':
>           Rejected as the implementation raised a specific error:
>             TypingError: Failed in nopython mode pipeline (step: nopython frontend)
>           No implementation of function Function(<intrinsic _make_dict>) found for signature:
> 
>            >>> <unknown function>(typeref[unicode_type], typeref[list(unicode_type)<iv=None>], void*)
> 
>           There are 2 candidate implementations:
>                 - Of which 2 did not match due to:
>                 Intrinsic in function '_make_dict': File: numba/typed/dictobject.py: Line 598.
>                   With argument(s): '(typeref[unicode_type], typeref[list(unicode_type)<iv=None>], void*)':
>                  Rejected as the implementation raised a specific error:
>                    TypingError: list(unicode_type)<iv=None> as value is forbidden
>             raised from /localdisk/work/akozlov/miniconda3/numba_master/numba/numba/core/types/containers.py:686
> 
>           During: resolving callee type: Function(<intrinsic _make_dict>)
>           During: typing of call at /localdisk/work/akozlov/miniconda3/numba_master/numba/numba/typed/dictobject.py (655)

I think this should be support in some way, otherwise jitting function utilizing python dicts becomes quite difficult.

Best Regards,
Alexey.

**Comment by stuartarchibald** [comment]
Thanks for the report. IIRC this is banned at present to avoid the complexities of reflection, _but_, if the dictionary doesn't ever get returned to the interpreter it could potentially be supported.
