### ISSUE TITLE
heapq failures on win32

### ISSUE THREAD

**Issue by sklam** [numba/numba#7313]
## Reporting a bug

Observed on e050fd691abcde71ac84dd8f748d158332ff060c in buildfarm run. Buildfarm has not been auto testing mainline since 0.54 rc, so first failing commit could be earlier.

The errors
```pytb
======================================================================
ERROR: test_heapsort (numba.tests.test_heapq.TestHeapqReflectedList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py", line 397, in test_heapsort
    cfunc_heappush(heap, item)
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\core\dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\core\dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function heappush>) found for signature:

 >>> heappush(reflected list(int32)<iv=None>, int64)

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'heappush': File: numba\cpython\heapq.py: Line 150.
    With argument(s): '(reflected list(int32)<iv=None>, int64)':
   Rejected as the implementation raised a specific error:
     TypingError: heap type must be the same as item type
  raised from C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\cpython\heapq.py:119

During: resolving callee type: Function(<built-in function heappush>)
During: typing of call at C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py (24)


File "..\..\..\..\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py", line 24:
def heappush(heap, item):
    return hq.heappush(heap, item)
    ^


======================================================================
ERROR: test_nbest_with_pushpop (numba.tests.test_heapq.TestHeapqTypedList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py", line 445, in test_nbest_with_pushpop
    cfunc_heappushpop(heap, item)
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\core\dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\core\dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function heappushpop>) found for signature:

 >>> heappushpop(ListType[int64], int32)

There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'heappushpop': File: numba\cpython\heapq.py: Line 176.
        With argument(s): '(ListType[int64], int32)':
       Rejected as the implementation raised a specific error:
         TypingError: heap type must be the same as item type
  raised from C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\cpython\heapq.py:119

During: resolving callee type: Function(<built-in function heappushpop>)
During: typing of call at C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py (28)


File "..\..\..\..\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py", line 28:
def heappushpop(heap, item):
    return hq.heappushpop(heap, item)
    ^


======================================================================
ERROR: test_nbest_with_pushpop (numba.tests.test_heapq.TestHeapqReflectedList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py", line 445, in test_nbest_with_pushpop
    cfunc_heappushpop(heap, item)
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\core\dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\core\dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function heappushpop>) found for signature:

 >>> heappushpop(reflected list(int32)<iv=None>, int64)

There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'heappushpop': File: numba\cpython\heapq.py: Line 176.
    With argument(s): '(reflected list(int32)<iv=None>, int64)':
   Rejected as the implementation raised a specific error:
     TypingError: heap type must be the same as item type
  raised from C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\cpython\heapq.py:119

During: resolving callee type: Function(<built-in function heappushpop>)
During: typing of call at C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py (28)


File "..\..\..\..\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\test_heapq.py", line 28:
def heappushpop(heap, item):
    return hq.heappushpop(heap, item)
    ^


======================================================================
FAIL: test_nbest_with_pushpop (numba.tests.test_heapq.TestHeapqTypedList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\support.py", line 779, in tearDown
    self.memory_leak_teardown()
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\support.py", line 753, in memory_leak_teardown
    self.assert_no_memory_leak()
  File "C:\Users\ci\32\miniconda3\envs\testenv_0ca9fc0b-ca29-4f20-8382-ad13e833b078\lib\site-packages\numba\tests\support.py", line 762, in assert_no_memory_leak
    self.assertEqual(total_alloc, total_free)
AssertionError: 3 != 1

----------------------------------------------------------------------
```

Update 1:

- problem seems to be agnostic to python versions. failed on py3.7 and py3.9. py3.8 not tested in the farm.

**Comment by sklam** [comment]
The most recent changes to `heapq` is https://github.com/numba/numba/pull/7260

**Comment by stuartarchibald** [comment]
`C:\Users\ci\32` suggests this is a 32bit issue on windows, so probably `intp` related.

**Comment by stuartarchibald** [comment]
I think the issue with the reflected list may be a result of this:
```python
from numba import njit, typeof
import numpy as np

@njit
def foo(heap):
    heap[0] = heap[0]

dt = np.uint8
tmp = list((dt(x) for x in range(5)))
print(typeof(tmp))
print(type(tmp[0]))
foo(tmp)
print(typeof(tmp))
print(type(tmp[0]))
```
which gives:
```
reflected list(uint8)<iv=None>
<class 'numpy.uint8'>
reflected list(int64)<iv=None>
<class 'int'>
```
i.e. the round trip through Numba has ended up with the type of the list changing.

**Comment by stuartarchibald** [comment]
I think https://github.com/numba/numba/issues/7313#issuecomment-901056155 is an instance of the issue that python and NumPy types are aliased in the type system, and reflection exacerbates the problem in this case. The instantiation of the list is correctly a `uint8` type list. Were `foo` to not write to the list, such that reflection did not occur, then the type of the list would not change. However, in the case above `foo` writes to the list, this triggers reflection behaviour. It is this reflection that rebuilds the list and unboxes the list items into the relected contents. Code involved is here:
https://github.com/numba/numba/blob/28272e45156e3234d05e3d350e9fa1ffd394659e/numba/core/boxing.py#L768-L780
note that the items in the list are being boxed based on their Numba type e.g.
https://github.com/numba/numba/blob/28272e45156e3234d05e3d350e9fa1ffd394659e/numba/core/boxing.py#L771
such that a `uint8` type would go through `types.Integer` boxing:
https://github.com/numba/numba/blob/28272e45156e3234d05e3d350e9fa1ffd394659e/numba/core/boxing.py#L36-L43
this creating a `PyLong` and the list ending up being a list of `long`s, which in the demonstration case is a list of `int64` Numba types.

This manifests as a problem in the unit tests for `heapq` as `heapify` is called on a list which is a different size to the system `PyLong` and as it gets reflected it ends up as the `PyLong` size. Then the method being checked, e.g. `heappushpop` fails as it either interprets a const as an `i64` when it should be an `i32` (system size) (or vice versa in the `typed.List` case) and the heapified list is not the dtype that is expected from the code as `heapify` altered it.
