### ISSUE TITLE
cuda.local.array produces TypingError even though the shape argument is defined at the top of the script (i.e. globally)

### ISSUE THREAD

**Issue by sgbaird** [numba/numba#7314]
## Example
Here is an example that works, but only by hard-coding (i.e. typing directly into the input function using the keyboard keys `2` and `0`) the number of columns of the concatenated array.

concatenate-gpu-test.py
```python
# -*- coding: utf-8 -*-
"""
Created on Tue Aug 17 23:16:43 2021.

@author: sterg
"""

import numpy as np
from numba import cuda
from numba.types import float32, int32

bits = 32
nb_float_type = float32
np_float_type = np.float32

# sample data
a = np.random.rand(100, 10)
b = np.random.rand(100, 10)

# I want to be able to programmatically define the total number of columns for later array allocation
cols = a.shape[1]
tot_cols = np.int32(a.shape[1] + b.shape[1])


@cuda.jit(device=True)
def vec_concatenate(vec, vec2, vec3):

    # number of elements in each vector
    n = len(vec)
    n2 = len(vec2)

    # populate vec3 with element-wise concatenation
    for i in range(n):
        vec3[i] = vec[i]
    for i in range(n2):
        vec3[i + n] = vec2[i]


@cuda.jit("void(float{0}[:, :], float{0}[:, :], float{0}[:, :])".format(bits))
def foo_stuff(mat, mat2, out):

    i = cuda.grid(1)

    # unpack vectors
    vec = mat[i]
    vec2 = mat2[i]

    # note the `20` is hardcoded into the shape argument
    vec3 = cuda.local.array(20, float32)
    vec_concatenate(vec, vec2, vec3)
    for j in range(tot_cols):
        out[i, j] = vec3[j]


def mat_concatenate(mat, mat2):

    # black and grid dimensions
    rows = mat.shape[0]
    block_dim = 16
    grid_dim = np.int32(rows / block_dim + 1)

    # output initialization
    cuda_out = cuda.device_array((rows, tot_cols), np.float32)

    # CUDA setup
    stream = cuda.stream()

    # copying data to GPU
    cuda_mat = cuda.to_device(np.asarray(mat, dtype=np_float_type), stream=stream)
    cuda_mat2 = cuda.to_device(np.asarray(mat2, dtype=np_float_type), stream=stream)
    foo_stuff[grid_dim, block_dim](cuda_mat, cuda_mat2, cuda_out)

    # copy it to the CPU
    out = cuda_out.copy_to_host(stream=stream)

    return out


c = mat_concatenate(a, b)
print(c.shape)
print(a[0:2], b[0:2])
print(c[0:2])
if not np.all(np.array(a[0], dtype=np.float32) == c[0, 0:cols]):
    raise ValueError("the concatenation was not successful. The values differ.")
```

## Error Stack Trace
If I change
```python
vec3 = cuda.local.array(20, float32)
```
to
```python
vec3 = cuda.local.array(tot_cols, float32)
```
where `tot_cols` is defined towards the top of the script, I get the following error (Spyder 5.0.5):

```python
Traceback (most recent call last):

  File "C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D\ElM2D\concatenate-gpu-test.py", line 39, in <module>
    @cuda.jit("void(float{0}[:, :], float{0}[:, :], float{0}[:, :])".format(bits))

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\cuda\decorators.py", line 95, in kernel_jit
    return Dispatcher(func, [func_or_sig], targetoptions=targetoptions)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\cuda\compiler.py", line 899, in __init__
    self.compile(sigs[0])

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\cuda\compiler.py", line 1094, in compile
    **self.targetoptions)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\cuda\compiler.py", line 511, in __init__
    inline=inline)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\cuda\compiler.py", line 53, in compile_cuda
    locals={})

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler.py", line 606, in compile_extra
    return pipeline.compile_extra(func)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler.py", line 353, in compile_extra
    return self._compile_bytecode()

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler.py", line 415, in _compile_bytecode
    return self._compile_core()

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler.py", line 395, in _compile_core
    raise e

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler.py", line 386, in _compile_core
    pm.run(self.state)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler_machinery.py", line 339, in run
    raise patched_exception

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler_machinery.py", line 330, in run
    self._runPass(idx, pass_inst, state)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\typed_passes.py", line 110, in run_pass
    raise_errors=self._raise_errors)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\typed_passes.py", line 82, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)

  File "C:\Users\sterg\AppData\Roaming\Python\Python37\site-packages\numba\core\typeinfer.py", line 1071, in propagate
    raise errors[0]

TypingError: No implementation of function Function(<function local.array at 0x000002603CBDD9D8>) found for signature:
 
array(int32, class(float32))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload of function 'array': File: numba\cuda\cudadecl.py: Line 44.
        With argument(s): '(int32, class(float32))':
       No match.

During: resolving callee type: Function(<function local.array at 0x000002603CBDD9D8>)
During: typing of call at C:\Users\sterg\Documents\GitHub\sparks-baird\ElM2D\ElM2D\concatenate-gpu-test.py (48)
```

Distance metrics generally can take vectors of variable length. Euclidean distance for example is defined in 1, 2, 3+ dimensions. I've tried defining the variable in the top-level function `mat_concatenate()`, but get the same error:
```python
TypingError: No implementation of function Function(<function local.array at 0x000002603CBDD9D8>) found for signature:
 
array(int32, class(float32))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload of function 'array': File: numba\cuda\cudadecl.py: Line 44.
        With argument(s): '(int32, class(float32))':
       No match.
```

## Workarounds
 The only programmatic workaround I can really think of is to do some sort of weird rewrite of the file before running it. This seems pretty "hacky" and would probably mean I need to mess with `tokenizer` and `parser`, which supposedly are difficult to work with. See [Programmatically editing Python source](https://stackoverflow.com/questions/32385/programmatically-editing-python-source). I also don't have experience with these.  I could incorporate a shell command with regexp, but this might be even hackier as the source files may be located in different places based on how a package was installed (conda, pip, etc.)

# Possibly a bug
Looking further, I found a Google Groups post [Call cuda.local.array with variables in the shape argument](https://groups.google.com/a/continuum.io/g/numba-users/c/l1dQR-Ol8NA) which seems to suggest that I should be able to do what was shown. I was able to run the solution posted there successfully, and am trying to figure out why my example breaks down.

Here's the Google Groups solution:
```python
from numba import cuda, int64
import numpy as np

x = 2
y = 2

@cuda.jit('void(float64[:])')
def foo(arr):

    pos = cuda.grid(1)
    if pos < arr.size:
        the_sum = 0
        # Create a local array
        loc_arr = cuda.local.array((x, y), dtype=int64) # <- Conflicting line
        # Do random calculations involving the array
        for i in range(x):
            for j in range(y):
                loc_arr[i, j] = pos*x*y
        for i in range(x):
            for j in range(y):
                the_sum += 1.5*loc_arr[i, j]
        arr[pos] = the_sum

arr = np.zeros(512)
tbp = 8
bpg = int(arr.shape[0]/8)

foo[bpg, tbp](arr)
```

Here's a version of my example that's a bit closer to the Google Groups code, but it still produces the same error.
bug.py
```python
# -*- coding: utf-8 -*-
"""
Created on Wed Aug 18 00:44:16 2021

@author: sterg
"""

import numpy as np
from numba import cuda
from numba.types import float32, int32

bits = 32
nb_float_type = float32
np_float_type = np.float32

# sample data
a = np.random.rand(100, 10)
b = np.random.rand(100, 10)

# I want to be able to programmatically define the total number of columns for local array allocation
cols = a.shape[1]
tot_cols = np.int32(a.shape[1] * 2)


@cuda.jit(device=True)
def vec_concatenate(vec, vec2, vec3):

    # number of elements in each vector
    n = len(vec)
    n2 = len(vec2)

    # populate vec3 with element-wise concatenation
    for i in range(n):
        vec3[i] = vec[i]
    for i in range(n2):
        vec3[i + n] = vec2[i]


@cuda.jit("void(float{0}[:, :], float{0}[:, :], float{0}[:, :])".format(bits))
def foo_stuff(mat, mat2, out):

    i = cuda.grid(1)

    # unpack vectors
    vec = mat[i]
    vec2 = mat2[i]

    # note the `20` is hardcoded into the shape argument
    vec3 = cuda.local.array(tot_cols, float32)
    vec_concatenate(vec, vec2, vec3)
    for j in range(tot_cols):
        out[i, j] = vec3[j]


# black and grid dimensions
rows = a.shape[0]
block_dim = 16
grid_dim = np.int32(rows / block_dim + 1)

c = np.zeros((rows, tot_cols))
foo_stuff[grid_dim, block_dim](a, b, c)
```

There's also a [Numba Issue][1] which talks about dynamic array allocation, but this is using function input arguments rather than a global variable.

  [1]: https://github.com/numba/numba/issues/6549

**Comment by sgbaird** [comment]
Wow..

It turns out that the problem is with using `np.int32` as in:
`tot_cols = a.shape[1] * 2`
instead of:
`tot_cols = np.int32(a.shape[1] * 2)`
Maybe this could be clarified in the [docs](https://numba.pydata.org/numba-doc/latest/cuda/memory.html) under `cuda.local.array`? Maybe just that NumPy `int` types don't work as shape arguments.

**Comment by stuartarchibald** [comment]
@sgbaird Thanks for the report. The typer (thing that works out the types) for `cuda.local.array` is here:
https://github.com/numba/numba/blob/28272e45156e3234d05e3d350e9fa1ffd394659e/numba/cuda/cudadecl.py#L43-L64
It looks like it will take integer literals only (in the `types.Integer` case).

CC @gmarkall, I don't think that this is specifically a CUDA issue? Numba could be programmed to "see" through NumPy int classes in globals to get their value but it might break expected behaviours where a specific NumPy int type is deliberately requested. Updating the docs is probably the safest thing to do?

**Comment by sgbaird** [comment]
Devs still working on wording
