### ISSUE TITLE
Control flow analysis failure in object mode when loop nested inside if statement

### ISSUE THREAD

**Issue by seibert** [numba/numba#734]
When Numba attempts to lift loops that are nested inside of an if-else construct, the control flow analysis will fail.  Here is a simple example:

``` python
from numba import jit, void, int32, double

@jit(void(int32, double[:]), forceobj=True)
def forloop_with_if(u, a):
    if u == 0:
        for i in range(a.shape[0]):
            a[i] = a[i] * 2.0
    else:
        for i in range(a.shape[0]):
            a[i] = a[i] + 1.0
```

The resulting exception is:

```
Traceback (most recent call last):
  File "mincase.py", line 4, in <module>
    @jit(void(int32, double[:]), forceobj=True)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/decorators.py", line 128, in wrapper
    disp.compile(sig)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/dispatcher.py", line 235, in compile
    flags=flags, locals=locs)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/compiler.py", line 146, in compile_extra
    func_attr=func_attr)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/compiler.py", line 215, in compile_bytecode
    func_attr=func_attr)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/compiler.py", line 154, in compile_bytecode
    interp = translate_stage(bc)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/compiler.py", line 330, in translate_stage
    interp = interpreter.Interpreter(bytecode=bytecode)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/interpreter.py", line 71, in __init__
    self.cfa.run()
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/controlflow.py", line 520, in run
    graph.add_edge(b.offset, out, pops)
  File "/Users/stan/anaconda/envs/numba_dev/lib/python2.7/site-packages/numba/controlflow.py", line 80, in add_edge
    assert dest in self._nodes
AssertionError
```

This was reported on the numba-users mailing list: https://groups.google.com/a/continuum.io/d/msgid/numba-users/52256cd0-6b65-48d4-8193-3b1f51ae40c4%40continuum.io

**Comment by MCCCSunny** [comment]
I want to know how to solve the bug?
can you help me?
Thank you!
