### ISSUE TITLE
try .. finally construct throws AssertionError when try block throws exception

### ISSUE THREAD

**Issue by hn-sl** [numba/numba#7379]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
numba version : 0.53.1 and 0.54.0
```python
import numba

@numba.njit
def test1():
    try:
        print('main block')
    finally:
        print('final block')

        
@numba.njit
def test2():
    try:
        print('main block')
        raise ValueError("")
    finally:
        print('final block')
        
@numba.njit
def test3(a):
    try:
        print('main block')
        if a:
            raise ValueError("")
    finally:
        print('final block')

```

```test1()``` success but ```test2()``` and ```test2(True)``` throw below error.

AssertionError: Unreachable condition reached (op code RERAISE executed)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.54.0.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

**Comment by esc** [comment]
@hn-sl thank you for reporting this. I am unable to reproduce this on OSX using Conda Python 3.8.2. Which platform (operating system and architecture) and version of Python are you using?

**Comment by hn-sl** [comment]
I tested on x86_64/20.04.2 LTS and x86-64/amazon linux 2 with python version 3.9.5 manually installed from source code. I got same error on both platform.

**Comment by esc** [comment]
@hn-sl thank you for reporting back. I can confirm I am able to reproduce this using Python 3.9 on OSX:

```
 💣 zsh» python issue_7379.py
main block
final block
main block
final block
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/issue_7379.py", line 29, in <module>
    test2()
  File "/Users/vhaenel/git/numba/issue_7379.py", line 17, in test2
    print('final block')
AssertionError: Unreachable condition reached (op code RERAISE executed)
-------------------------------------------------------------------------------
This should not have happened, a problem has occurred in Numba's internals.
You are currently using Numba version 0.55.0dev0+185.ge031b70c31.

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new?template=bug_report.md

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!
```

**Comment by stuartarchibald** [comment]
From memory, `RERAISE` https://docs.python.org/3/library/dis.html#opcode-RERAISE is Python 3.9 only, IIRC it's not yet handled and is usually caught elsewhere.
