### ISSUE TITLE
str is parsed as unicode_type thus can't be passed as str argument to func like np.argsort

### ISSUE THREAD

**Issue by auderson** [numba/numba#7383]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
@njit
def test(a):
    kind =  'mergesort' if a == 1 else 'quicksort'
    return np.argsort(np.arange(5), kind=kind)
```

```python
>>> test(2)
```
```Traceback (most recent call last):
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-93-14ddcd275974>", line 1, in <module>
    test(2)
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/auderson/miniconda3/lib/python3.8/site-packages/numba/core/dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function argsort at 0x7f795ce98040>) found for signature:
 
 >>> argsort(array(int64, 1d, C), kind=unicode_type)
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Overload in function 'Numpy_method_redirection.generic': File: numba/core/typing/npydecl.py: Line 378.
        With argument(s): '(array(int64, 1d, C), kind=unicode_type)':
       Rejected as the implementation raised a specific error:
         TypingError: - Resolution failure for literal arguments:
       "kind" must be a string literal
       - Resolution failure for non-literal arguments:
       None
       
  raised from /home/auderson/miniconda3/lib/python3.8/site-packages/numba/core/types/functions.py:476
During: resolving callee type: Function(<function argsort at 0x7f795ce98040>)
During: typing of call at <ipython-input-91-a788401e4f51> (4)
File "<ipython-input-91-a788401e4f51>", line 4:
def test(a):
    <source elided>
    kind =  'mergesort' if a == 1 else 'quicksort'
    return np.argsort(np.arange(5), kind=kind)
```

It seems `kind` is parsed as `unicode_type` in this case. For now this will work:

```python
@njit
def test(a):
    if a == 1:
        return np.argsort(np.arange(5), kind='mergesort')
    return np.argsort(np.arange(5), kind='quicksort')
```

numba.__version__
Out[97]: '0.54.0'

**Comment by sklam** [comment]
Thank you for the report.

Due to limiation of type inference, Numba requires the `kind` argument in `argsort()` to be a literal string. In other words, the compiler needs to know the value in `kind`. The statement `kind =  'mergesort' if a == 1 else 'quicksort'` makes it impossible to tell what `kind` will be at compile-time. Your workaround avoids this problem.
