### ISSUE TITLE
Support for Record type in jitclass

### ISSUE THREAD

**Issue by hn-sl** [numba/numba#7410]
---

## Feature request
It would be great if it was possible to have Record type member in jitclass.

```python
import numpy as np
import numba
from numba.experimental import jitclass
my_type = np.dtype([("age", np.int32), ("height", np.int32)])
a = np.zeros(1, dtype=my_type)[0]

spec=[
    ("_a", numba.typeof(a))
]
@jitclass(spec=spec)
class A:
    def __init__(self, a):
        self._a = a
        
A(a) # This throw below exception
```
```python
Traceback (most recent call last):
  File "/opt/test/test.py", line 15, in <module>
    A(a) # This throw below exception
  File "/opt/python/py3.9/lib/python3.9/site-packages/numba/experimental/jitclass/base.py", line 124, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/opt/python/py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/opt/python/py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)

numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f42aef1b280>.
Failed in nopython mode pipeline (step: native lowering)
use load_from_data_pointer() instead

File "test.py", line 13:
    def __init__(self, a):
        self._a = a
        ^

During: lowering "(self)._a = a" at /opt/test/test.py (13)
During: resolving callee type: jitclass.A#7f4306358400<_a:Record(age[type=int32;offset=0],height[type=int32;offset=4];8;False)>
During: typing of call at <string> (3)

Enable logging at debug level for details.

File "<string>", line 3:
<source missing, REPL/exec in use?>
```
This was tested on latest numba version (0.54.0)

**Comment by gmarkall** [comment]
I can reproduce this.

**Comment by esc** [comment]
> ## Feature request
> It would be great if it was possible to have Record type member in jitclass.
> 
> ```python
> import numpy as np
> import numba
> from numba.experimental import jitclass
> my_type = np.dtype([("age", np.int32), ("height", np.int32)])
> a = np.zeros(1, dtype=my_type)[0]
> 
> spec=[
>     ("_a", numba.typeof(a))
> ]
> @jitclass(spec=spec)
> class A:
>     def __init__(self, a):
>         self._a = a
>         
> A(a) # This throw below exception
> ```
> 
> ```python
> Traceback (most recent call last):
>   File "/opt/test/test.py", line 15, in <module>
>     A(a) # This throw below exception
>   File "/opt/python/py3.9/lib/python3.9/site-packages/numba/experimental/jitclass/base.py", line 124, in __call__
>     return cls._ctor(*bind.args[1:], **bind.kwargs)
>   File "/opt/python/py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py", line 482, in _compile_for_args
>     error_rewrite(e, 'typing')
>   File "/opt/python/py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py", line 423, in error_rewrite
>     raise e.with_traceback(None)
> 
> numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
> Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f42aef1b280>.
> Failed in nopython mode pipeline (step: native lowering)
> use load_from_data_pointer() instead
> 
> File "test.py", line 13:
>     def __init__(self, a):
>         self._a = a
>         ^
> 
> During: lowering "(self)._a = a" at /opt/test/test.py (13)
> During: resolving callee type: jitclass.A#7f4306358400<_a:Record(age[type=int32;offset=0],height[type=int32;offset=4];8;False)>
> During: typing of call at <string> (3)
> 
> Enable logging at debug level for details.
> 
> File "<string>", line 3:
> <source missing, REPL/exec in use?>
> ```
> 
> This was tested on latest numba version (0.54.0)

I can reproduce this, thank you for reporting. If you want a record member inside a jitclass, I would suggest trying to use a tuple as a temporary workaround, would that work for your use-case.

**Comment by esc** [comment]
Removing both the 'needtriage' and 'stale' labels.

**Comment by iyz91** [comment]
I would appreciate this as well. Can currently set Numpy structured arrays on jitclasses no problem, but can't set a specific accessed row (with roughly the same error above). Current workaround is to just keep track of the index I want and access the row on the higher ndarray as needed in the methods instead of storing it for easier access.

**Comment by yxdragon** [comment]
```python
import numpy as np
import numba
from numba.experimental import jitclass
my_type = np.dtype([("age", np.int32), ("height", np.int32)])
a = np.zeros(1, dtype=my_type)[0]

spec=[
    ("_a", numba.typeof(a))
]
@jitclass(spec=spec)
class A:
    def __init__(self, a):
        self._a = a
        
A(a) # This throw below exception
```

it works in current version, but I got a error when I use np.recarray in the jitclass 's __init__ method.
I know np.zeros(n, dtype=my_type) works, but I just want to use a.age instead of a['age'], so I want to generate a recarray.
