### ISSUE TITLE
Default constructor of jitclass not useable from jitted code

### ISSUE THREAD

**Issue by HPLegion** [numba/numba#7413]
## Reporting a bug

During a discussion on Gitter I noticed that a jitclass instance cannot be created from default arguments inside jitted code.

:point_up: [Gitter September 17, 2021 3:17 PM](https://gitter.im/numba/numba?at=6144957b4c7be06b79c20b06)

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
from numba.experimental import jitclass
from numba import njit
from numba.types import int32


@jitclass
class A:
    a: int32

    def __init__(self, a=3):
        self.a = a

def a_explicit():
    return A(1)

def a_default():
    return A()


print("Explicit from python:", a_explicit())
print("Explicit from numba:", njit(a_explicit)())
print("Default from python:", a_default())
print("Default from numba:", njit(a_default)())

```

Output 
```
Explicit from python: <numba.experimental.jitclass.boxing.A object at 0x7f8e6d104ad0>
Explicit from numba: <numba.experimental.jitclass.boxing.A object at 0x7f8e6a080a10>
Default from python: <numba.experimental.jitclass.boxing.A object at 0x7f8e69eceb10>
Traceback (most recent call last):
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/errors.py", line 776, in new_error_context
    yield
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 235, in lower_block
    self.lower_inst(inst)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 380, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 556, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 1084, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 815, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 1055, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/base.py", line 1194, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/base.py", line 1224, in wrapper
    return fn(*args, **kwargs)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/experimental/jitclass/base.py", line 581, in ctor_impl
    call(builder, realargs)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/base.py", line 1194, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/base.py", line 1224, in wrapper
    return fn(*args, **kwargs)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/imputils.py", line 195, in imp
    status, retval = context.call_conv.call_function(
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/callconv.py", line 570, in call_function
    args = list(arginfo.as_arguments(builder, args))
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/datamodel/packer.py", line 91, in as_arguments
    raise TypeError("invalid number of args: expected %d, got %d"
TypeError: invalid number of args: expected 2, got 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "jitclass_default_constructor.py", line 23, in <module>
    print("Default from numba:", njit(a_default)())
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py", line 501, in _compile_for_args
    raise e
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py", line 434, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py", line 979, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py", line 141, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py", line 155, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py", line 168, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler.py", line 686, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler.py", line 428, in compile_extra
    return self._compile_bytecode()
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler.py", line 492, in _compile_bytecode
    return self._compile_core()
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler.py", line 471, in _compile_core
    raise e
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler.py", line 462, in _compile_core
    pm.run(self.state)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/typed_passes.py", line 396, in run_pass
    lower.lower()
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 138, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 192, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 221, in lower_function_body
    self.lower_block(block)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/lowering.py", line 235, in lower_block
    self.lower_inst(inst)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/hpahl/anaconda3/envs/py38/lib/python3.8/site-packages/numba/core/errors.py", line 786, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
invalid number of args: expected 2, got 1

File "jitclass_default_constructor.py", line 17:
def a_default():
    return A()
    ^

During: lowering "$4call_function.1 = call $2load_global.0(func=$2load_global.0, args=[], kws=(), vararg=None, target=None)" at jitclass_default_constructor.py (17)
```

`numba -s`
<details>
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2021-09-17 18:26:09.738632
UTC start time                                : 2021-09-17 16:26:09.738637
Running time (s)                              : 4.969007

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : skylake
CPU Count                                     : 8
Number of accessible CPUs                     : 8
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                clflushopt cmov cx16 cx8 f16c fma
                                                fsgsbase fxsr invpcid lzcnt mmx
                                                movbe pclmul popcnt prfchw rdrnd
                                                rdseed rtm sahf sgx sse sse2 sse3
                                                sse4.1 sse4.2 ssse3 xsave xsavec
                                                xsaveopt xsaves

Memory Total (MB)                             : 15885
Memory Available (MB)                         : 7265

__OS Information__
Platform Name                                 : Linux-5.10.61-1-MANJARO-x86_64-with-glibc2.10
Platform Release                              : 5.10.61-1-MANJARO
OS Name                                       : Linux
OS Version                                    : #1 SMP PREEMPT Thu Aug 26 20:36:54 UTC 2021
OS Specific Version                           : ?
Libc Version                                  : glibc 2.33

__Python Information__
Python Compiler                               : GCC 7.3.0
Python Implementation                         : CPython
Python Version                                : 3.8.5
Python Locale                                 : en_GB.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.54.0
llvmlite Version                              : 0.37.0

__LLVM Information__
LLVM Version                                  : 11.1.0

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

__SVML Information__
SVML State, config.USING_SVML                 : True
SVML Library Loaded                           : True
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : True

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : 3.17.1
Conda Env                                     : 4.9.2
Conda Platform                                : linux-64
Conda Python Version                          : 3.7.4.final.0
Conda Root Writable                           : True

__Installed Packages__
_anaconda_depends         2020.07                  py38_0  
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
alabaster                 0.7.12                     py_0  
anaconda                  custom                   py38_1  
anaconda-client           1.7.2                    py38_0  
anaconda-project          0.8.4                      py_0  
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
argh                      0.26.2                   py38_0  
argon2-cffi               20.1.0           py38h7b6447c_1  
asn1crypto                1.4.0                      py_0  
asteval                   0.9.23             pyhd8ed1ab_0    conda-forge
astroid                   2.4.2                    py38_0  
astropy                   4.0.2            py38h7b6447c_0  
async_generator           1.10                       py_0  
atomicwrites              1.4.0                      py_0  
attrs                     20.3.0             pyhd3eb1b0_0  
autopep8                  1.5.4                      py_0  
babel                     2.8.1              pyhd3eb1b0_0  
backcall                  0.2.0                      py_0  
backports                 1.0                        py_2  
backports.shutil_get_terminal_size 1.0.0                    py38_2  
beautifulsoup4            4.9.3              pyhb0f4dca_0  
bibtexparser              1.2.0                    pypi_0    pypi
bitarray                  1.6.1            py38h27cfd23_0  
bkcharts                  0.2                      py38_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
blosc                     1.20.1               hd408876_0  
bokeh                     2.2.3                    py38_0  
boto                      2.49.0                   py38_0  
bottleneck                1.3.2            py38heb32a55_1  
brotli-python             1.0.9            py38heb0550a_2  
brotlipy                  0.7.0           py38h7b6447c_1000  
build                     0.6.0.post1              pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.7.5             h06a4308_1  
cairo                     1.14.12              h8948797_3  
certifi                   2021.5.30        py38h06a4308_0  
cffi                      1.14.3           py38he30daa8_0  
cfgv                      3.2.0                      py_0    conda-forge
chardet                   3.0.4                 py38_1003  
click                     7.1.2                      py_0  
cloudpickle               1.6.0                      py_0  
clyent                    1.2.2                    py38_1  
colorama                  0.4.4                      py_0  
contextlib2               0.6.0.post1                py_0  
cryptography              3.1.1            py38h1ba5d50_0  
curl                      7.71.1               hbc83047_1  
cycler                    0.10.0                   py38_0  
cython                    0.29.21          py38he6710b0_0  
cytoolz                   0.11.0           py38h7b6447c_0  
dash                      1.19.0             pyhd3eb1b0_0  
dash-core-components      1.3.1                      py_0  
dash-html-components      1.0.1                      py_0  
dash-renderer             1.1.2                      py_0  
dash-table                4.4.1                      py_0  
dask                      2.30.0                     py_0  
dask-core                 2.30.0                     py_0  
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
diff-match-patch          20200713                   py_0  
distlib                   0.3.1              pyh9f0ad1d_0    conda-forge
distributed               2.30.1           py38h06a4308_0  
docutils                  0.16                     py38_1  
ebisim                    0.2.0                     dev_0    <develop>
editdistance              0.5.3            py38h950e882_2    conda-forge
entrypoints               0.3                      py38_0  
et_xmlfile                1.0.1                   py_1001  
expat                     2.2.10               he6710b0_2  
fastcache                 1.1.0            py38h7b6447c_0  
filelock                  3.0.12                     py_0  
flake8                    3.8.4                      py_0  
flask                     1.1.2                      py_0  
flask-compress            1.8.0              pyhd3eb1b0_0  
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
fribidi                   1.0.10               h7b6447c_0  
fsspec                    0.8.3                      py_0  
future                    0.18.2                   py38_1  
get_terminal_size         1.0.0                haa9412d_0  
gevent                    20.9.0           py38h7b6447c_0  
glib                      2.66.1               h92f7085_0  
glob2                     0.7                        py_0  
gmp                       6.1.2                h6c8ec71_1  
gmpy2                     2.0.8            py38hd5f6e3b_3  
graphite2                 1.3.14               h23475e2_0  
greenlet                  0.4.17           py38h7b6447c_0  
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
h5py                      2.10.0           py38h7918eee_0  
harfbuzz                  2.4.0                hca77d97_1  
hdf5                      1.10.4               hb1b8bf9_0  
heapdict                  1.0.1                      py_0  
html5lib                  1.1                        py_0  
icc_rt                    2020.2                intel_254    numba
icu                       58.2                 he6710b0_3  
identify                  1.5.13             pyh44b312d_0    conda-forge
idna                      2.10                       py_0  
imageio                   2.9.0                      py_0  
imagesize                 1.2.0                      py_0  
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
iniconfig                 1.1.1                      py_0  
intel-openmp              2021.3.0          h06a4308_3350  
intervaltree              3.1.0                      py_0  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.19.0           py38hb070fc8_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                      py_1  
isort                     5.6.4                      py_0  
itsdangerous              1.1.0                      py_0  
jbig                      2.1                  hdba287a_0  
jdcal                     1.4.1                      py_0  
jedi                      0.17.1                   py38_0  
jeepney                   0.5.0              pyhd3eb1b0_0  
jinja2                    2.11.2                     py_0  
joblib                    1.0.0              pyhd3eb1b0_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5                      py_0  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py38_0  
jupyterlab                2.2.6                      py_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0  
keyring                   21.4.0                   py38_1  
kiwisolver                1.3.0            py38h2531618_0  
krb5                      1.18.2               h173b8e3_0  
lazy-object-proxy         1.4.3            py38h7b6447c_0  
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libarchive                3.4.2                h62408e4_0  
libcurl                   7.71.1               h20c2e04_1  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h9cbead1_17  
libgfortran-ng            7.3.0                hdf63c60_0  
libgomp                   9.3.0               h9cbead1_17  
liblief                   0.10.1               he6710b0_0  
libllvm10                 10.0.1               hbcb73fb_5  
libllvm9                  9.0.1                h4a3c616_1  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libspatialindex           1.9.3                he6710b0_0  
libssh2                   1.9.0                h1ba5d50_1  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtiff                   4.1.0                h2733197_1  
libtool                   2.4.6             h7b6447c_1005  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
libxslt                   1.1.34               hc22bd24_0  
llvmlite                  0.37.0           py38he1b5a44_0    numba
lmfit                     1.0.2              pyhd8ed1ab_0    conda-forge
locket                    0.2.0                    py38_1  
lxml                      4.6.1            py38hefd8a0e_0  
lz4-c                     1.9.2                heb0550a_3  
lzo                       2.10                 h7b6447c_2  
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.3.2                         0  
matplotlib-base           3.3.2            py38h817c723_0  
mccabe                    0.6.1                    py38_1  
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2021.3.0           h06a4308_520  
mkl-service               2.4.0            py38h7f8727e_0  
mkl_fft                   1.3.0            py38h42c9631_2  
mkl_random                1.2.2            py38h51133e4_0  
mock                      4.0.2                      py_0  
more-itertools            8.6.0              pyhd3eb1b0_0  
mpc                       1.1.0                h10f8cd9_1  
mpfr                      4.0.2                hb69a4c5_1  
mpmath                    1.1.0                    py38_0  
msgpack-python            1.0.0            py38hfd86e86_1  
multipledispatch          0.6.0                    py38_0  
mypy                      0.800              pyhd3eb1b0_0  
mypy_extensions           0.4.3                    py38_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.2              pyhd3eb1b0_0  
networkx                  2.5                        py_0  
nltk                      3.5                        py_0  
nodeenv                   1.5.0              pyh9f0ad1d_0    conda-forge
nose                      1.3.7                    py38_2  
notebook                  6.1.4                    py38_0  
numba                     0.54.0          np1.11py3.8hc13618b_g5888895d3_0    numba
numexpr                   2.7.3            py38h22e1b3c_1  
numpy                     1.20.3           py38hf144106_0  
numpy-base                1.20.3           py38h74d4b33_0  
numpydoc                  1.1.0              pyhd3eb1b0_1  
olefile                   0.46                       py_0  
openpyxl                  3.0.5                      py_0  
openssl                   1.1.1k               h27cfd23_0  
packaging                 20.4                       py_0  
pandas                    1.1.3            py38he6710b0_0  
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.3            py38h06a4308_1  
pango                     1.45.3               hd140c19_0  
parso                     0.7.0                      py_0  
partd                     1.1.0                      py_0  
patchelf                  0.12                 he6710b0_0  
path                      15.0.0                   py38_0  
path.py                   12.5.0                        0  
pathlib2                  2.3.5                    py38_0  
pathtools                 0.1.2                      py_1  
patsy                     0.5.1                    py38_0  
pbr                       5.5.1                      py_0  
pcre                      8.44                 he6710b0_0  
pep517                    0.11.0                   pypi_0    pypi
pep8                      1.7.1                    py38_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pillow                    8.0.1            py38he98fc37_0  
pip                       20.2.4           py38h06a4308_0  
pixman                    0.40.0               h7b6447c_0  
pkginfo                   1.6.1            py38h06a4308_0  
plotly                    4.14.3             pyhd3eb1b0_0  
pluggy                    0.13.1                   py38_0  
ply                       3.11                     py38_0  
pre-commit                2.10.1           py38h578d9bd_0    conda-forge
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
psutil                    5.7.2            py38h7b6447c_0  
ptyprocess                0.6.0                    py38_0  
py                        1.9.0                      py_0  
py-lief                   0.10.1           py38h403a769_0  
pycodestyle               2.6.0                      py_0  
pycosat                   0.6.3            py38h7b6447c_1  
pycparser                 2.20                       py_2  
pycurl                    7.43.0.6         py38h1ba5d50_0  
pydocstyle                5.1.1                      py_0  
pyflakes                  2.2.0                      py_0  
pygments                  2.7.2              pyhd3eb1b0_0  
pylint                    2.6.0                    py38_0  
pyodbc                    4.0.30           py38he6710b0_0  
pyopenssl                 19.1.0                     py_1  
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.17.3           py38h7b6447c_0  
pysocks                   1.7.1                    py38_0  
pytables                  3.6.1            py38h9fd0a39_0  
pytest                    6.1.1                    py38_0  
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1                      py_0  
python-jsonrpc-server     0.4.0                      py_0  
python-language-server    0.35.1                     py_0  
python-libarchive-c       2.9                        py_0  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                     py_0  
pywavelets                1.1.1            py38h7b6447c_2  
pyxdg                     0.27               pyhd3eb1b0_0  
pyyaml                    5.3.1            py38h7b6447c_1  
pyzmq                     19.0.2           py38he6710b0_1  
qdarkstyle                2.8.1                      py_0  
qt                        5.9.7                h5867ecd_1  
qtawesome                 1.0.1                      py_0  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
regex                     2020.10.15       py38h7b6447c_0  
requests                  2.24.0                     py_0  
retrying                  1.3.3                      py_2  
ripgrep                   12.1.1                        0  
rope                      0.18.0                     py_0  
rtree                     0.9.4                    py38_1  
ruamel_yaml               0.15.87          py38h7b6447c_1  
scikit-image              0.17.2           py38hdf5156a_0  
scikit-learn              0.23.2           py38h0573a6f_0  
scipy                     1.6.2            py38had2a1c9_1  
seaborn                   0.11.0                     py_0  
secretstorage             3.1.2                    py38_0  
send2trash                1.5.0                    py38_0  
setuptools                50.3.1           py38h06a4308_1  
simplegeneric             0.8.1                    py38_2  
singledispatch            3.4.0.3                 py_1001  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0           py38h06a4308_0  
snappy                    1.1.8                he6710b0_0  
snowballstemmer           2.0.0                      py_0  
sortedcollections         1.2.1                      py_0  
sortedcontainers          2.2.2                      py_0  
soupsieve                 2.0.1                      py_0  
sphinx                    3.2.1                      py_0  
sphinx-autodoc-typehints  1.11.1                   pypi_0    pypi
sphinx_rtd_theme          0.5.1              pyhd3deb0d_0    conda-forge
sphinxcontrib             1.0                      py38_1  
sphinxcontrib-apidoc      0.3.0                      py_1    conda-forge
sphinxcontrib-applehelp   1.0.2                      py_0  
sphinxcontrib-devhelp     1.0.2                      py_0  
sphinxcontrib-htmlhelp    1.0.3                      py_0  
sphinxcontrib-jsmath      1.0.1                      py_0  
sphinxcontrib-qthelp      1.0.3                      py_0  
sphinxcontrib-serializinghtml 1.1.4                      py_0  
sphinxcontrib-websupport  1.2.4                      py_0  
spyder                    4.1.5                    py38_0  
spyder-kernels            1.9.4                    py38_0  
sqlalchemy                1.3.20           py38h7b6447c_0  
sqlite                    3.33.0               h62c20be_0  
statsmodels               0.12.0           py38h7b6447c_0  
sympy                     1.6.2            py38h06a4308_1  
tbb                       2021.2.0             hff7bd54_0  
tblib                     1.7.0                      py_0  
tct                       0.1.0                     dev_0    <develop>
terminado                 0.9.1                    py38_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tifffile                  2020.10.1        py38hdd07704_2  
tk                        8.6.10               hbc83047_0  
toml                      0.10.1                     py_0  
tomli                     1.2.1                    pypi_0    pypi
toolz                     0.11.1                     py_0  
tornado                   6.0.4            py38h7b6447c_1  
tqdm                      4.50.2                     py_0  
traitlets                 5.0.5                      py_0  
typed-ast                 1.4.2            py38h27cfd23_1  
typing_extensions         3.7.4.3                    py_0  
ujson                     4.0.1            py38he6710b0_0  
uncertainties             3.1.5              pyhd8ed1ab_0    conda-forge
unicodecsv                0.14.1                   py38_0  
unixodbc                  2.3.9                h7b6447c_0  
urllib3                   1.25.11                    py_0  
virtualenv                20.4.2           py38h578d9bd_0    conda-forge
watchdog                  0.10.3                   py38_0  
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1                      py_0  
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.11.2           py38h7b6447c_0  
wurlitzer                 2.0.1                    py38_0  
xlrd                      1.2.0                      py_0  
xlsxwriter                1.3.7                      py_0  
xlwt                      1.3.0                    py38_0  
xz                        5.2.5                h7b6447c_0  
yaml                      0.2.5                h7b6447c_0  
yapf                      0.30.0                     py_0  
zeromq                    4.3.3                he6710b0_3  
zict                      2.0.0                      py_0  
zipp                      3.4.0              pyhd3eb1b0_0  
zlib                      1.2.11               h7b6447c_3  
zope                      1.0                      py38_1  
zope.event                4.5.0                    py38_0  
zope.interface            5.1.2            py38h7b6447c_0  
zstd                      1.4.5                h9ceee32_0  

No errors reported.

__Warning log__
Warning (cuda): CUDA driver library cannot be found or no CUDA enabled devices are present.
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================

</details>

**Comment by esc** [comment]
Thank you, I can reproduce! Assume an issue in argument handling for the `jitclass` constructor.
