### ISSUE TITLE
Loss of functionality in .54 - change in slicing behavior on user defined types

### ISSUE THREAD

**Issue by c200chromebook** [numba/numba#7426]
possible dupe of : https://github.com/numba/numba/issues/7355
The following code worked prior to 0.54, but no longer will run:

```
import numpy as np
import numba as nb

ALT_TYPE = [('Z', np.float64, 3)]
np_alt = np.dtype(ALT_TYPE, align=True)
nb_alt = nb.from_dtype(np_alt)
print(np_alt)
print(nb_alt)


@nb.njit(nb.void(nb_alt[:]))
def new_kern(z):
    z[0]['Z'][:] = 7


dta = np.zeros((1,), dtype=nb_alt)
new_kern(dta)
print(dta)
```

Yields:

```
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(nestedarray(float64, (3,)), slice<a:b>, Literal[int](7))
 
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(nestedarray(float64, (3,)), slice<a:b>, int64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'SetItemBuffer.generic': File: numba\core\typing\arraydecl.py: Line 171.
    With argument(s): '(nestedarray(float64, (3,)), slice<a:b>, int64)':
   Rejected as the implementation raised a specific error:
     TypeError: __init__() got an unexpected keyword argument 'ndim'
```

Expected behavior:
``` [([7,7,7],)]```

The bug affects CUDA as well but this is probably incidental.

**Comment by c200chromebook** [comment]
have confirmed still happens in `numba-0.55.0.dev0+299.gf299c6aa7-py3.7-win-amd64`

**Comment by esc** [comment]
@c200chromebook thank you for reporting this. I can reproduce, here is the full stack trace.

```
 💣 zsh» python issue7426.py
{'names':['Z'], 'formats':[('<f8', (3,))], 'offsets':[0], 'itemsize':24, 'aligned':True}
Record(Z[type=nestedarray(float64, (3,));offset=0];24;True)
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 154, in propagate
    constraint(typeinfer)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 807, in __call__
    sig = typeinfer.context.resolve_setitem(targetty, idxty, valty)
  File "/Users/vhaenel/git/numba/numba/core/typing/context.py", line 349, in resolve_setitem
    sig = fnty.get_call_type(self, (target, index, value), {})
  File "/Users/vhaenel/git/numba/numba/core/types/functions.py", line 348, in get_call_type
    failures.raise_error()
  File "/Users/vhaenel/git/numba/numba/core/types/functions.py", line 227, in raise_error
    raise errors.TypingError(self.format())
numba.core.errors.TypingError: No implementation of function Function(<built-in function setitem>) found for signature:

 >>> setitem(nestedarray(float64, (3,)), slice<a:b>, Literal[int](7))

There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(nestedarray(float64, (3,)), slice<a:b>, int64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'SetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 171.
    With argument(s): '(nestedarray(float64, (3,)), slice<a:b>, int64)':
   Rejected as the implementation raised a specific error:
     TypeError: __init__() got an unexpected keyword argument 'ndim'
       Traceback (most recent call last):
         File "/Users/vhaenel/git/numba/numba/core/types/functions.py", line 329, in get_call_type
           sig = temp.apply(nolitargs, nolitkws)
         File "/Users/vhaenel/git/numba/numba/core/typing/templates.py", line 351, in apply
           sig = generic(args, kws)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 178, in generic
           out = get_array_index_type(ary, idx)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 149, in get_array_index_type
           res = ary.copy(ndim=ndim, layout=layout)
         File "/Users/vhaenel/git/numba/numba/core/types/npytypes.py", line 456, in copy
           return cls(dtype=dtype, ndim=ndim, layout=layout, readonly=readonly,
         File "/Users/vhaenel/git/numba/numba/core/types/abstract.py", line 66, in __call__
           inst = type.__call__(cls, *args, **kwargs)
       TypeError: __init__() got an unexpected keyword argument 'ndim'
  raised from /Users/vhaenel/git/numba/numba/core/types/abstract.py:66

During: typing of staticsetitem at issue7426.py (13)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "issue7426.py", line 12, in <module>
    def new_kern(z):
  File "/Users/vhaenel/git/numba/numba/core/decorators.py", line 226, in wrapper
    disp.compile(sig)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 979, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 145, in compile
    raise retval
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 155, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 168, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 686, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 428, in compile_extra
    return self._compile_bytecode()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 492, in _compile_bytecode
    return self._compile_core()
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 471, in _compile_core
    raise e
  File "/Users/vhaenel/git/numba/numba/core/compiler.py", line 462, in _compile_core
    pm.run(self.state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 343, in run
    raise patched_exception
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 334, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 289, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/vhaenel/git/numba/numba/core/compiler_machinery.py", line 262, in check
    mangled = func(compiler_state)
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/Users/vhaenel/git/numba/numba/core/typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/Users/vhaenel/git/numba/numba/core/typeinfer.py", line 1074, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:

 >>> setitem(nestedarray(float64, (3,)), slice<a:b>, Literal[int](7))

There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(nestedarray(float64, (3,)), slice<a:b>, int64)':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'SetItemBuffer.generic': File: numba/core/typing/arraydecl.py: Line 171.
    With argument(s): '(nestedarray(float64, (3,)), slice<a:b>, int64)':
   Rejected as the implementation raised a specific error:
     TypeError: __init__() got an unexpected keyword argument 'ndim'
       Traceback (most recent call last):
         File "/Users/vhaenel/git/numba/numba/core/types/functions.py", line 329, in get_call_type
           sig = temp.apply(nolitargs, nolitkws)
         File "/Users/vhaenel/git/numba/numba/core/typing/templates.py", line 351, in apply
           sig = generic(args, kws)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 178, in generic
           out = get_array_index_type(ary, idx)
         File "/Users/vhaenel/git/numba/numba/core/typing/arraydecl.py", line 149, in get_array_index_type
           res = ary.copy(ndim=ndim, layout=layout)
         File "/Users/vhaenel/git/numba/numba/core/types/npytypes.py", line 456, in copy
           return cls(dtype=dtype, ndim=ndim, layout=layout, readonly=readonly,
         File "/Users/vhaenel/git/numba/numba/core/types/abstract.py", line 66, in __call__
           inst = type.__call__(cls, *args, **kwargs)
       TypeError: __init__() got an unexpected keyword argument 'ndim'
  raised from /Users/vhaenel/git/numba/numba/core/types/abstract.py:66

During: typing of staticsetitem at issue7426.py (13)

File "issue7426.py", line 13:
def new_kern(z):
    z[0]['Z'][:] = 7
```

**Comment by esc** [comment]
I tried #7359  with this reproducer and the error went away. So that probably fixes this.

```
 💣 zsh» python issue7426.py
{'names':['Z'], 'formats':[('<f8', (3,))], 'offsets':[0], 'itemsize':24, 'aligned':True}
Record(Z[type=nestedarray(float64, (3,));offset=0];24;True)
[([7., 7., 7.],)]
```

**Comment by esc** [comment]
@c200chromebook could you try #7359 and double check if that fixes it for you too?

**Comment by esc** [comment]
There is also #7428 as an alternative to #7359 -- might be worth trying that too.

**Comment by esc** [comment]
```
 💣 zsh» gh pr checkout 7428
remote: Enumerating objects: 18, done.
remote: Counting objects: 100% (18/18), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 18 (delta 11), reused 18 (delta 11), pack-reused 0
Unpacking objects: 100% (18/18), done.
From github.com:numba/numba
 * [new ref]               refs/pull/7428/head -> fix/iss7355_minimal
Switched to branch 'fix/iss7355_minimal'
vhaenel@x86_64-apple-darwin13 [numba_3.8] [numba:fix/iss7355_minimal:★★₃₂★] ~/git/numba
 💣 zsh» make clean && make
...
 💣 zsh» python issue7426.py
{'names':['Z'], 'formats':[('<f8', (3,))], 'offsets':[0], 'itemsize':24, 'aligned':True}
Record(Z[type=nestedarray(float64, (3,));offset=0];24;True)
[([7., 7., 7.],)]
```

I can confirm that #7428 will fix this too.

**Comment by c200chromebook** [comment]
> ```
>  💣 zsh» gh pr checkout 7428
> remote: Enumerating objects: 18, done.
> remote: Counting objects: 100% (18/18), done.
> remote: Compressing objects: 100% (7/7), done.
> remote: Total 18 (delta 11), reused 18 (delta 11), pack-reused 0
> Unpacking objects: 100% (18/18), done.
> From github.com:numba/numba
>  * [new ref]               refs/pull/7428/head -> fix/iss7355_minimal
> Switched to branch 'fix/iss7355_minimal'
> vhaenel@x86_64-apple-darwin13 [numba_3.8] [numba:fix/iss7355_minimal:★★₃₂★] ~/git/numba
>  💣 zsh» make clean && make
> ...
>  💣 zsh» python issue7426.py
> {'names':['Z'], 'formats':[('<f8', (3,))], 'offsets':[0], 'itemsize':24, 'aligned':True}
> Record(Z[type=nestedarray(float64, (3,));offset=0];24;True)
> [([7., 7., 7.],)]
> ```
> 
> I can confirm that #7428 will fix this too.

can confirm that fixes it

**Comment by esc** [comment]
> > ```
> >  💣 zsh» gh pr checkout 7428
> > remote: Enumerating objects: 18, done.
> > remote: Counting objects: 100% (18/18), done.
> > remote: Compressing objects: 100% (7/7), done.
> > remote: Total 18 (delta 11), reused 18 (delta 11), pack-reused 0
> > Unpacking objects: 100% (18/18), done.
> > From github.com:numba/numba
> >  * [new ref]               refs/pull/7428/head -> fix/iss7355_minimal
> > Switched to branch 'fix/iss7355_minimal'
> > vhaenel@x86_64-apple-darwin13 [numba_3.8] [numba:fix/iss7355_minimal:★★₃₂★] ~/git/numba
> >  💣 zsh» make clean && make
> > ...
> >  💣 zsh» python issue7426.py
> > {'names':['Z'], 'formats':[('<f8', (3,))], 'offsets':[0], 'itemsize':24, 'aligned':True}
> > Record(Z[type=nestedarray(float64, (3,));offset=0];24;True)
> > [([7., 7., 7.],)]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I can confirm that #7428 will fix this too.
> 
> can confirm that fixes it

Great, thank you!

**Comment by esc** [comment]
Closing now as #7428 was merged!
