### ISSUE TITLE
Implement array reshape for CUDA

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7528]
The following:

```python
from numba import cuda
import numpy as np


@cuda.jit('void()')
def f():
    x = cuda.shared.array(0, dtype=np.int32)
    x.reshape(2, 2)
```

Gives:

```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 2222, in complete
    driver.cuLinkComplete(self.handle, byref(cubin), byref(size))
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 303, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 343, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [300] Call to cuLinkComplete results in CUDA_ERROR_INVALID_SOURCE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/gabri94/repro.py", line 6, in <module>
    def f():
  File "/home/gmarkall/numbadev/numba/numba/cuda/decorators.py", line 109, in kernel_jit
    return Dispatcher(func, [func_or_sig], targetoptions=targetoptions)
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 938, in __init__
    self.compile(sigs[0])
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 1117, in compile
    kernel.bind()
  File "/home/gmarkall/numbadev/numba/numba/cuda/compiler.py", line 628, in bind
    self._codelibrary.get_cufunc()
  File "/home/gmarkall/numbadev/numba/numba/cuda/codegen.py", line 201, in get_cufunc
    cubin = self.get_cubin(cc=device.compute_capability)
  File "/home/gmarkall/numbadev/numba/numba/cuda/codegen.py", line 178, in get_cubin
    cubin_buf, size = linker.complete()
  File "/home/gmarkall/numbadev/numba/numba/cuda/cudadrv/driver.py", line 2224, in complete
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [300] Call to cuLinkComplete results in CUDA_ERROR_INVALID_SOURCE
error   : Undefined reference to 'numba_attempt_nocopy_reshape' in '<cudapy-ptx>'
```

Given that we got through typing and lowering and ended up with a linker error, it might not be too difficult to fix up the implementation for CUDA.

**Comment by gmarkall** [comment]
This may be a good issue for someone who's already managed to implement a basic addition to the CUDA target - labelling accordingly.

**Comment by gmarkall** [comment]
A little further investigation reveals that `numba_attempt_nocopy_reshape` is implemented in `_helperlib.c` - this could do with being compiled to PTX into a "CUDA helperlib" and linked in as required. This is a bit much for a "good second issue".

**Comment by gmarkall** [comment]
Starter hack:

`_cuda_helperlib.cu`, taken from `_numba/_helperlib.c`:

```cuda
#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
#include <numpy/ndarrayobject.h>

/*
 * Handle reshaping of zero-sized array.
 * See numba_attempt_nocopy_reshape() below.
 */
extern "C" __device__ int
nocopy_empty_reshape(npy_intp nd, const npy_intp *dims, const npy_intp *strides,
                     npy_intp newnd, const npy_intp *newdims,
                     npy_intp *newstrides, npy_intp itemsize,
                     int is_f_order)
{
    int i;
    /* Just make the strides vaguely reasonable
     * (they can have any value in theory).
     */
    for (i = 0; i < newnd; i++)
        newstrides[i] = itemsize;
    return 1;  /* reshape successful */
}

/*
 * Straight from Numpy's _attempt_nocopy_reshape()
 * (np/core/src/multiarray/shape.c).
 * Attempt to reshape an array without copying data
 *
 * This function should correctly handle all reshapes, including
 * axes of length 1. Zero strides should work but are untested.
 *
 * If a copy is needed, returns 0
 * If no copy is needed, returns 1 and fills `npy_intp *newstrides`
 *     with appropriate strides
 */

extern "C" __device__ int
numba_attempt_nocopy_reshape(npy_intp nd, const npy_intp *dims, const npy_intp *strides,
                             npy_intp newnd, const npy_intp *newdims,
                             npy_intp *newstrides, npy_intp itemsize,
                             int is_f_order)
{
    int oldnd;
    npy_intp olddims[NPY_MAXDIMS];
    npy_intp oldstrides[NPY_MAXDIMS];
    npy_intp np, op, last_stride;
    int oi, oj, ok, ni, nj, nk;

    oldnd = 0;
    /*
     * Remove axes with dimension 1 from the old array. They have no effect
     * but would need special cases since their strides do not matter.
     */
    for (oi = 0; oi < nd; oi++) {
        if (dims[oi]!= 1) {
            olddims[oldnd] = dims[oi];
            oldstrides[oldnd] = strides[oi];
            oldnd++;
        }
    }

    np = 1;
    for (ni = 0; ni < newnd; ni++) {
        np *= newdims[ni];
    }
    op = 1;
    for (oi = 0; oi < oldnd; oi++) {
        op *= olddims[oi];
    }
    if (np != op) {
        /* different total sizes; no hope */
        return 0;
    }

    if (np == 0) {
        /* the Numpy code does not handle 0-sized arrays */
        return nocopy_empty_reshape(nd, dims, strides,
                                    newnd, newdims, newstrides,
                                    itemsize, is_f_order);
    }

    /* oi to oj and ni to nj give the axis ranges currently worked with */
    oi = 0;
    oj = 1;
    ni = 0;
    nj = 1;
    while (ni < newnd && oi < oldnd) {
        np = newdims[ni];
        op = olddims[oi];

        while (np != op) {
            if (np < op) {
                /* Misses trailing 1s, these are handled later */
                np *= newdims[nj++];
            } else {
                op *= olddims[oj++];
            }
        }

        /* Check whether the original axes can be combined */
        for (ok = oi; ok < oj - 1; ok++) {
            if (is_f_order) {
                if (oldstrides[ok+1] != olddims[ok]*oldstrides[ok]) {
                     /* not contiguous enough */
                    return 0;
                }
            }
            else {
                /* C order */
                if (oldstrides[ok] != olddims[ok+1]*oldstrides[ok+1]) {
                    /* not contiguous enough */
                    return 0;
                }
            }
        }

        /* Calculate new strides for all axes currently worked with */
        if (is_f_order) {
            newstrides[ni] = oldstrides[oi];
            for (nk = ni + 1; nk < nj; nk++) {
                newstrides[nk] = newstrides[nk - 1]*newdims[nk - 1];
            }
        }
        else {
            /* C order */
            newstrides[nj - 1] = oldstrides[oj - 1];
            for (nk = nj - 1; nk > ni; nk--) {
                newstrides[nk - 1] = newstrides[nk]*newdims[nk];
            }
        }
        ni = nj++;
        oi = oj++;
    }

    /*
     * Set strides corresponding to trailing 1s of the new shape.
     */
    if (ni >= 1) {
        last_stride = newstrides[ni - 1];
    }
    else {
        last_stride = itemsize;
    }
    if (is_f_order) {
        last_stride *= newdims[ni - 1];
    }
    for (nk = ni; nk < newnd; nk++) {
        newstrides[nk] = last_stride;
    }

    return 1;
}
```

Compiled with (paths on my system):

```
nvcc -ptx -rdc true -gencode=arch=compute_75,code=compute_75 numba/_cuda_helperlib.cu -I/home/gmarkall/miniconda3/envs/numbanp120/lib/python3.9/site-packages/numpy/core/include -I/home/gmarkall/miniconda3/envs/numbanp120/include -I/home/gmarkall/miniconda3/envs/numbanp120/include/python3.9
```

User code:

```python
from numba import cuda
import numpy as np


@cuda.jit('void(int32[:,::1])', link=['_cuda_helperlib.ptx'])
def f(arr):
    x = cuda.shared.array(0, dtype=np.int32)
    x[0] = 11
    x[1] = 12
    x[2] = 21
    x[3] = 22
    y = x.reshape(2, 2)

    arr[0, 0] = y[0, 0]
    arr[0, 1] = y[0, 1]
    arr[1, 0] = y[1, 0]
    arr[1, 1] = y[1, 1]

NX = 2
NY = 2
ITEMSIZE = 4
DYNSMEM = NX * NY * ITEMSIZE

data = np.zeros((NX, NY), dtype=np.int32)

f[1, 1, 0, DYNSMEM](data)

print(data)
```

produces:

```
[[11 12]
 [21 22]]
```

**Comment by gmarkall** [comment]
xref #2463 which should be a use case enabled by implementing this.

**Comment by gmarkall** [comment]
I listed a simpler workaround until this is resolved in https://github.com/numba/numba/issues/9340#issuecomment-1849833085 - the workaround is essentially the same as above, but now linking CUDA C/C++ directly is possible in Numba, that workaround saves a separate compile step.

**Comment by hnsl** [comment]
I hit this yesterday and the workaround you posted in [#9340 (comment)](https://github.com/numba/numba/issues/9340#issuecomment-1849833085) worked flawlessly.

That begs the question, why is this a workaround instead of just checked in source code? It really surprised me that I get a linker error to a function that doesn't exist, but exists as a workaround. You usually get linker errors because you have an error in your toolchain/headers, not because you're trying to use an unsupported feature.

**Comment by gmarkall** [comment]
>  why is this a workaround instead of just checked in source code?

Only because we'd not yet reached the point where this is checked in in the source code. The PR that will eventually address this in the hopefully not-too-distant future is https://github.com/NVIDIA/numba-cuda/pull/47
