### ISSUE TITLE
numba-core-cpu-importing-stuff-from-numba-experimental

### ISSUE THREAD

**Issue by AhmetCanSolak** [numba/numba#7532]
---

## Feature request

Hello all. I am opening this issue as a follow up to this: https://numba.discourse.group/t/numba-core-cpu-importing-stuff-from-numba-experimental/995

I am wondering if there is a better way to handle `install_registry` calls given. here:
https://github.com/numba/numba/blob/6c95d38d945bb5ee77e52662bed416e24a2770ef/numba/core/cpu.py#L86

This is particularly causing a problem to me when I am bundling my package with pyinstaller(while having numba as a dependency). "_box" shared library file in numba.experimental.jitclass particularly causing trouble but I do not depend on any experimental feature and I am manually dropping experimental submodule to save the day. This is how I am handling things currently but I want to discuss here to see if we can have cleaner solutions on both end. 

As far as I understood, experimental features meant to be for the users who want to use them and shouldn't affect the stable API experience in the rest of the codebase. Aside from the inconvenience I am facing with pyinstaller, it can be useful to not import anything experimental unless user asks for it IMHO.

I can appreciate that this can be hard to resolve and I am happy to contribute as much as I can.

**Comment by sklam** [comment]
This relates to moving experimental features to https://github.com/numba/numba-extras as briefly discussed in the numba dev meetings. Then, these features can be registered automatically via [extension-entrypoints](https://numba.readthedocs.io/en/stable/extending/entrypoints.html).

**Comment by esc** [comment]
@AhmetCanSolak can you outline what kind of problems you were having? I.e. were there any error messages or such? Maybe we can make it easier to include this shared library.

**Comment by AhmetCanSolak** [comment]
Thank you @esc ! I kept getting `_box` not found at `from numba.experimental.jitclass import _box` errors when I try to run my executables. I followed the calls back and fount out in `numba/numba/core/cpu.py` file imports from experimental submodule otherwise I am not using anything from `experimental`. I tried copying this shared library to my pyinstaller bundle manually but shared library was causing trouble in load time as well. Hence, I ended up manually removing experimental imports on my build environment for now. Any suggestions?

**Comment by esc** [comment]
> Thank you @esc ! I kept getting `_box` not found at `from numba.experimental.jitclass import _box` errors when I try to run my executables. I followed the calls back and fount out in `numba/numba/core/cpu.py` file imports from experimental submodule otherwise I am not using anything from `experimental`. I tried copying this shared library to my pyinstaller bundle manually but shared library was causing trouble in load time as well. Hence, I ended up manually removing experimental imports on my build environment for now. Any suggestions?

No sure exactly. Can you just strip the import when you package it maybe? Otherwise, maybe you can remember what error the shared library was causing? I am also surprised as to why it was not installed by default.

**Comment by AhmetCanSolak** [comment]
I strip imports manually every time I create a new build environment, that's my solution for now.

Here is the full trace of the error if it helps:
```
Traceback (most recent call last):
  File "build/osx/runtimehooks/hook-splash.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "aydin/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "aydin/restoration/denoise/classic.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "aydin/it/classic_denoisers/bmnd.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/pynndescent_.py", line 16, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/sparse.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/utils.py", line 14, in <module>
  File "numba/core/decorators.py", line 226, in wrapper
  File "numba/core/dispatcher.py", line 960, in compile
  File "numba/core/caching.py", line 642, in load_overload
  File "numba/core/base.py", line 274, in refresh
  File "numba/core/cpu.py", line 86, in load_additional_registries
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "numba/experimental/jitclass/base.py", line 16, in <module>
ImportError: cannot import name '_box' from 'numba.experimental.jitclass' (/path/to/numba/experimental/jitclass/__init__.pyc)
```

**Comment by esc** [comment]
Interesting, it seems like the real error is being swallowed somehow. I wonder if the library is maybe in the wrong place or perhaps it has been miscompiled.

**Comment by AhmetCanSolak** [comment]
I don't know but I am using latest numba version available always, so if it fixes itself on newer version I can tell.

**Comment by gmarkall** [comment]
@AhmetCanSolak Can you provide a list of steps to reproduce the issue you see with importing `_box` in your build environment?

**Comment by AhmetCanSolak** [comment]
hello @gmarkall, 

I found out that pyinstaller was not bringing the binaries from `numba.experimental` on linux and windows. So, I started manually copying binaries to my bundles with a script.  To reproduce the problem, you can try to bundle one of our projects with Pyinstaller like this one on Windows: https://github.com/royerlab/aydin/blob/master/build/win/aydin.spec and when you try to run the resulting bundle you will be getting the same import error as above:
```
Traceback (most recent call last):
  File "build/osx/runtimehooks/hook-splash.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "aydin/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "aydin/restoration/denoise/classic.py", line 22, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "aydin/it/classic_denoisers/bmnd.py", line 4, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/pynndescent_.py", line 16, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/sparse.py", line 10, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "pynndescent/utils.py", line 14, in <module>
  File "numba/core/decorators.py", line 226, in wrapper
  File "numba/core/dispatcher.py", line 960, in compile
  File "numba/core/caching.py", line 642, in load_overload
  File "numba/core/base.py", line 274, in refresh
  File "numba/core/cpu.py", line 86, in load_additional_registries
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "numba/experimental/jitclass/base.py", line 16, in <module>
ImportError: cannot import name '_box' from 'numba.experimental.jitclass' (/path/to/numba/experimental/jitclass/__init__.pyc)
```

I think copying binaries that pyinstaller is not gathering is a decent solution for my case but I would still appreciate if experimental features can move to `numba-extras`. Since @sklam mentioned there are already some discussion around this, if this issue is not helpful to those discussion, feel free to close this.

**Comment by gmarkall** [comment]
@AhmetCanSolak I think it's OK to keep this issue - I've updated the title and made an edit to the description so it's clear what we need to do - during the process of moving `numba.experimental` the person undertaking it might also want to consider why binaries in that module don't get found by PyInstaller.

**Comment by AhmetCanSolak** [comment]
hello @gmarkall , are there any updates on this? anything I might be helpful with?
