### ISSUE TITLE
 from numba.core.typeconv import _typeconv

### ISSUE THREAD

**Issue by kjz1997** [numba/numba#7536]
from numba.core.typeconv import _typeconv
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/python/Datashader.py", line 1, in <module>
    import datashader as ds, pandas as pd, colorcet
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\datashader\__init__.py", line 8, in <module>
    from .core import Canvas                                 # noqa (API import)
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\datashader\core.py", line 15, in <module>
    from .utils import Dispatcher, ngjit, calc_res, calc_bbox, orient_array, \
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\datashader\utils.py", line 8, in <module>
    import numba as nb
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\__init__.py", line 24, in <module>
    from numba.misc.special import (
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\DELL\AppData\Local\Programs\Python\Python37\lib\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide https://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'DLL load failed: 找不到指定的模块。'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\DELL\AppData\Local\Programs\Python\Python37\python.exe

**Comment by sklam** [comment]
@kjz1997, This is a common symptom of installation problem. Can you tell us more about how Numba is installed?

**Comment by kjz1997** [comment]
I didn't use conda . I was using pycharm, and then I followed the instructions on the official website and used pip install datashader

发自我的iPhone

> 在 2021年11月4日，下午11:15，Siu Kwan Lam ***@***.***> 写道：
> 
> This is a common symptom of installation problem. Can you tell us more about how Numba is installed?

**Comment by kjz1997** [comment]
I didn't use conda. I was using pycharm, and then I followed the instructions on the official website and used pip install datashader

发自我的iPhone

**Comment by esc** [comment]
@kjz1997 IIRC installation via pycharm has caused issues for other users in the past. It may be worthwhile searching the issue tracker and/or discourse.

**Comment by kjz1997** [comment]
Thank you！I am using jupyter。

发自我的iPhone

**Comment by Fngg** [comment]
python -m pip uninstall numba
python -m pip install numba==0.47.0

**Comment by kjz1997** [comment]
Thank you！I will try it later

发自我的iPhone

**Comment by esc** [comment]
I am closing this now as no new information has been provided and hence I am assuming resolved. A similar issue was also closed today and you can read more about the reasoning here:

https://github.com/numba/numba/issues/6973#issuecomment-988581265
