### ISSUE TITLE
Assignment to slice fails in nopython mode

### ISSUE THREAD

**Issue by seibert** [numba/numba#755]
(This issue pulled out of #626)

This function will fail when compiled:

```
@jit
def train_function(X, y, H):
      classes = np.unique(y)
      no_samples = X.shape[0]
      no_features = X.shape[1]
      no_classes = len(classes)

      weights = np.empty([n,m])
      for curr_n in range(n):
          weights[curr_n,:] = 1.0/(n) # this is line 103
```

The error message from #626 is:

```
Traceback (most recent call last):
File "C:\work_asaaki\code\gbc_classifier_train_7.py", line 54, in 
gentlebooster.train(X_train, y_train, boosting_rounds)
File "C:\work_asaaki\code\gentleboost_c_class_jit_v7_nolimit.py", line 298, in train
self.g_per_round, self.g = train_function(X, y, H)

File "C:\Anaconda\lib\site-packages\numba\dispatcher.py", line 152, in _compile_for_args
return self.jit(sig)
File "C:\Anaconda\lib\site-packages\numba\dispatcher.py", line 143, in jit
return self.compile(sig, **kws)
File "C:\Anaconda\lib\site-packages\numba\dispatcher.py", line 250, in compile
locals=self.locals)
File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 183, in compile_bytecode
flags.no_compile)
File "C:\Anaconda\lib\site-packages\numba\compiler.py", line 323, in native_lowering_stage
lower.lower()
File "C:\Anaconda\lib\site-packages\numba\lowering.py", line 219, in lower
self.lower_block(block)
File "C:\Anaconda\lib\site-packages\numba\lowering.py", line 254, in lower_block
raise LoweringError(msg, inst.loc)
numba.lowering.LoweringError: Internal error:
NotImplementedError: ('cast', , slice3_type, int64)
File "gentleboost_c_class_jit_v7_nolimit.py", line 103
```

**Comment by stuartarchibald** [comment]
This appears to compile fine under Numba 0.37:
```python
from numba import jit
import numpy as np

m = 3
n = 4
@jit
def train_function(X, y, H):
      classes = np.unique(y)
      no_samples = X.shape[0]
      no_features = X.shape[1]
      no_classes = len(classes)

      weights = np.empty([n, m])
      for curr_n in range(n):
          weights[curr_n,:] = 1.0/(n) # this is line 103

X = np.zeros((10, 20))
y = np.zeros(7)
H = 5
train_function(X, y, H)
```
Closing. Please reopen if this is still an issue.
