### ISSUE TITLE
Support nested tuples as tuples of literal elements

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#7566]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi, 

I recently encountered a case when type-inference tends to 'unliteral' tuple elements (more precisely nested tuples elements), which seems quite odd because similar code expressed differently may work or not work. Here's the reproducer:
```
from numba import njit
from numba.core import types
from numba.extending import overload


def bar(x):
    pass

@overload(bar, prefer_literal=True)
def bar_ovld(x):
    assert (isinstance(x, types.BaseTuple)
            and isinstance(x[0], types.BaseTuple)
            and isinstance(x[0][0], types.StringLiteral)), \
            f"bar only supported with literal first values in tuple elements, given: {x}"

    return lambda x: 42


b = ('A', 1)

@njit()
def test_impl_1():
    a = (b, )
    return bar(a)


@njit()
def test_impl_2():
    b = ('A', 1)
    a = (b, )
    return bar(a)


@njit()
def test_impl_3():
    a = (('A', 1), )
    return bar(a)


# tested = test_impl_2    # this works
tested = test_impl_3    # this fails due to non-literal tuple received by bar

print(tested())
tested.inspect_types()
```

In this case both capturing a tuple as a global variable or creating an inner tuple a separate variable works, so that `bar` compiles and runs with signature: `(UniTuple(Tuple(Literal[str](A), Literal[int](1)) x 1),) -> Literal[int](42)`. But `test_impl_3` fails with:
> There are 2 candidate implementations:
>   - Of which 2 did not match due to:
>   Overload in function 'bar_ovld': File: ..\..\..\..\..\hpat\test_numba_1.py: Line 9.
>     With argument(s): '(UniTuple(Tuple(unicode_type, int64) x 1))':
>    Rejected as the implementation raised a specific error:
>      AssertionError: bar only supported with literal first values in tuple elements, given: UniTuple(Tuple(unicode_type, int64) x 1)
>   raised from test_numba_1.py:14

because the IR in this case has a `const_('A', 1)` node, which is type-inferred via `typeof_const`, that attempts to find `Literal` ctor for tuples and fails:
```
>>> self.func_ir.dump()
label 0:
    $const_('A', 1) = const(tuple, ('A', 1)) ["$const_('A', 1)"]
    a = build_tuple(items=[Var($const_('A', 1), test_numba_1.py:99)]) ["$const_('A', 1)", 'a']
    $6load_global.1 = global(bar: <function bar at 0x0000014780D9ADC8>) ['$6load_global.1']
    $10call_function.3 = call $6load_global.1(a, func=$6load_global.1, args=[Var(a, test_numba_1.py:99)], kws=(), vararg=None, target=None) ['$10call_function.3', '$6load_global.1', 'a']
    $12return_value.4 = cast(value=$10call_function.3) ['$10call_function.3', '$12return_value.4']
    return $12return_value.4                 ['$12return_value.4']

>>> str(inst)
"$const_('A', 1) = const(tuple, ('A', 1))"
>>> inst.value
const(tuple, ('A', 1))
>>> inst.value.use_literal_type
True
>>> ty
<class 'tuple'>
>>> Literal.ctor_map[ty]
Traceback (most recent call last):
  File "C:\Users\akozlov\eclipse\cpp-2020-03\eclipse\plugins\org.python.pydev.core_8.0.0.202009061309\pysrc\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<console>", line 1, in <module>
KeyError: <class 'tuple'>
```

I was wondering if it's possible (or would be a good thing) to extend the `types.misc.literal` so that it will type-infer tuples as literal types as well? At first glance it seems beneficial to align the behavior, as well as preserve literality of tuple elements as long as possible. What do you think?

Best Regards,
Alexey.

**Comment by stuartarchibald** [comment]
Thanks for the report. I think this is because in the `test_impl_3` the tuple item is derived from an `ir.Const` which as noted in the above is type inferred via:
https://github.com/numba/numba/blob/5fc9d3c56da4e4c6aef7189e588ce9c44263d4a6/numba/core/typeinfer.py#L1481-L1487
and there's no literal type for it which is why it behaves differently. Will raise this at the public meeting tomorrow. Previous concerns about `literal` values/types have largely revolved around over specialisation of functions, but I think in this case it creates a somewhat strange to predict behaviour in typing.

**Comment by stuartarchibald** [comment]
@kozlov-alexey Following on from today's public Numba development meeting. The outcome of the discussion on this ticket was to make the three cases consistent and in all cases the nested tuple should be literal.
