### ISSUE TITLE
Using literally suppresses info in compilation failure traceback

### ISSUE THREAD

**Issue by kozlov-alexey** [numba/numba#7568]
- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Hi,

This is regarding `numba.literally` which is working normally itself, but has a shortcoming of masking the real compilation error when it is applied before compilation reaches some non-supported code, i.e. the compilation failure traceback only references to 'Repeated literal typing request', but not to the root cause of compilation failure, which complicates the debugging. Here's the example that demonstrates the problem:

```
import numba
from numba import njit, literally
from numba.core import types
from numba.extending import overload
from numba.core.errors import TypingError

def foo(x):
    pass

def bar(y):
    pass

@overload(bar)
def bar_ovld(y):

    # consider this is the only impl that is currently provided, and reject others with TypingError
    if not isinstance(y, types.NoneType):
        raise TypingError("bar only supported arg is None")

    return lambda y: 43

@overload(foo)
def foo_ovld(x):
    if not isinstance(x, types.Literal):
        return lambda x: literally(x)

    x_literal_val = x.literal_value
    def foo_impl(x):
        if x_literal_val == 1:
            return 42
        else:
            return bar(x)

    return foo_impl

@njit
def test_impl(x):
    return foo(x)

val = 'sdf'
print(test_impl(val))
```

This prints the following huge traceback, that has no references to `bar`'s TypingError message (in case of some LoweringError from the bar_impl it would be suppressed too, so it becomes difficult to understand what went wrong):

> (NUMBA_MASTER_4) C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba>python test_literally_err.py
> Traceback (most recent call last):
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 979, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 141, in compile
>     status, retval = self._compile_cached(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 155, in _compile_cached
>     retval = self._compile_core(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 173, in _compile_core
>     pipeline_class=self.pipeline_class)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 686, in compile_extra
>     return pipeline.compile_extra(func)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 428, in compile_extra
>     return self._compile_bytecode()
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 492, in _compile_bytecode
>     return self._compile_core()
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 471, in _compile_core
>     raise e
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 462, in _compile_core
>     pm.run(self.state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 343, in run
>     raise patched_exception
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 334, in run
>     self._runPass(idx, pass_inst, state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 289, in _runPass
>     mutated |= check(pss.run_pass, internal_state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 262, in check
>     mangled = func(compiler_state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\untyped_passes.py", line 430, in run_pass
>     find_literally_calls(state.func_ir, state.args)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\analysis.py", line 620, in find_literally_calls
>     raise errors.ForceLiteralArg(marked_args, loc=loc)
> numba.core.errors.ForceLiteralArg: Failed in nopython mode pipeline (step: find literally calls)
> Pseudo-exception to force literal arguments in the dispatcher
> 
> File "test_literally_err.py", line 28:
> def foo_ovld(x):
>     <source elided>
>     if not isinstance(x, types.Literal):
>         return lambda x: literally(x)
>         ^
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 589, in resolve
>     sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 1541, in resolve_call
>     return self.context.resolve_function_type(fnty, pos_args, kw_args)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typing\context.py", line 195, in resolve_function_type
>     res = self._resolve_user_function_type(func, args, kws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typing\context.py", line 247, in _resolve_user_function_type
>     return func.get_call_type(self, args, kws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\types\functions.py", line 348, in get_call_type
>     failures.raise_error()
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\types\functions.py", line 226, in raise_error
>     raise fail.error
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\types\functions.py", line 329, in get_call_type
>     sig = temp.apply(nolitargs, nolitkws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typing\templates.py", line 351, in apply
>     sig = generic(args, kws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typing\templates.py", line 605, in generic
>     disp, new_args = self._get_impl(args, kws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typing\templates.py", line 704, in _get_impl
>     impl, args = self._build_impl(cache_key, args, kws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typing\templates.py", line 805, in _build_impl
>     disp_type.get_call_type(self.context, args, kws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\types\functions.py", line 555, in get_call_type
>     self.dispatcher.get_call_template(args, kws)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 377, in get_call_template
>     self.compile(tuple(args))
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 984, in compile
>     raise e.bind_fold_arguments(folded)
> numba.core.errors.ForceLiteralArg: Pseudo-exception to force literal arguments in the dispatcher
> 
> File "test_literally_err.py", line 28:
> def foo_ovld(x):
>     <source elided>
>     if not isinstance(x, types.Literal):
>         return lambda x: literally(x)
>         ^
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 979, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 141, in compile
>     status, retval = self._compile_cached(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 155, in _compile_cached
>     retval = self._compile_core(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 173, in _compile_core
>     pipeline_class=self.pipeline_class)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 686, in compile_extra
>     return pipeline.compile_extra(func)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 428, in compile_extra
>     return self._compile_bytecode()
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 492, in _compile_bytecode
>     return self._compile_core()
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 471, in _compile_core
>     raise e
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 462, in _compile_core
>     pm.run(self.state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 343, in run
>     raise patched_exception
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 334, in run
>     self._runPass(idx, pass_inst, state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 289, in _runPass
>     mutated |= check(pss.run_pass, internal_state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 262, in check
>     mangled = func(compiler_state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typed_passes.py", line 112, in run_pass
>     raise_errors=self._raise_errors)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typed_passes.py", line 83, in type_inference_stage
>     errs = infer.propagate(raise_errors=raise_errors)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 1076, in propagate
>     raise reduce(operator.or_, force_lit_args)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 154, in propagate
>     constraint(typeinfer)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 566, in __call__
>     self.resolve(typeinfer, typevars, fnty)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 607, in resolve
>     raise ForceLiteralArg(requested, loc=self.loc)
> numba.core.errors.ForceLiteralArg: Failed in nopython mode pipeline (step: nopython frontend)
> Pseudo-exception to force literal arguments in the dispatcher
> 
> File "test_literally_err.py", line 43:
> def test_impl(x):
>     return foo(x)
>     ^
> 
> During: resolving callee type: Function(<function foo at 0x000001AAD5AACA68>)
> During: typing of call at test_literally_err.py (43)
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 434, in _compile_for_args
>     return_val = self.compile(tuple(argtypes))
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 984, in compile
>     raise e.bind_fold_arguments(folded)
> numba.core.errors.ForceLiteralArg: Pseudo-exception to force literal arguments in the dispatcher
> 
> File "test_literally_err.py", line 43:
> def test_impl(x):
>     return foo(x)
>     ^
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 979, in compile
>     cres = self._compiler.compile(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 141, in compile
>     status, retval = self._compile_cached(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 155, in _compile_cached
>     retval = self._compile_core(args, return_type)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 173, in _compile_core
>     pipeline_class=self.pipeline_class)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 686, in compile_extra
>     return pipeline.compile_extra(func)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 428, in compile_extra
>     return self._compile_bytecode()
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 492, in _compile_bytecode
>     return self._compile_core()
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 471, in _compile_core
>     raise e
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler.py", line 462, in _compile_core
>     pm.run(self.state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 343, in run
>     raise patched_exception
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 334, in run
>     self._runPass(idx, pass_inst, state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
>     return func(*args, **kwargs)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 289, in _runPass
>     mutated |= check(pss.run_pass, internal_state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\compiler_machinery.py", line 262, in check
>     mangled = func(compiler_state)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typed_passes.py", line 112, in run_pass
>     raise_errors=self._raise_errors)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typed_passes.py", line 83, in type_inference_stage
>     errs = infer.propagate(raise_errors=raise_errors)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 1076, in propagate
>     raise reduce(operator.or_, force_lit_args)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 154, in propagate
>     constraint(typeinfer)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 566, in __call__
>     self.resolve(typeinfer, typevars, fnty)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\typeinfer.py", line 607, in resolve
>     raise ForceLiteralArg(requested, loc=self.loc)
> numba.core.errors.ForceLiteralArg: Failed in nopython mode pipeline (step: nopython frontend)
> Pseudo-exception to force literal arguments in the dispatcher
> 
> File "test_literally_err.py", line 43:
> def test_impl(x):
>     return foo(x)
>     ^
> 
> During: resolving callee type: Function(<function foo at 0x000001AAD5AACA68>)
> During: typing of call at test_literally_err.py (43)
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 434, in _compile_for_args
>     return_val = self.compile(tuple(argtypes))
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 984, in compile
>     raise e.bind_fold_arguments(folded)
> numba.core.errors.ForceLiteralArg: Pseudo-exception to force literal arguments in the dispatcher
> 
> File "test_literally_err.py", line 43:
> def test_impl(x):
>     return foo(x)
>     ^
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "test_literally_err.py", line 47, in <module>
>     print(test_impl(val))
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 457, in _compile_for_args
>     return_val = self._compile_for_args(*args)
>   File "C:\Users\akozlov\AppData\Local\Continuum\anaconda3\numba_master\numba\numba\core\dispatcher.py", line 450, in _compile_for_args
>     raise errors.CompilerError(m.format(info))
> numba.core.errors.CompilerError: Repeated literal typing request.
> Arg #0 is Literal[str](sdf).
> This is likely caused by an error in typing. Please see nested and suppressed exceptions.
> 

Best Regards,
Alexey.

**Comment by stuartarchibald** [comment]
@kozlov-alexey Thanks for the report. If you switch on logging the exception is in there.
```
$ head -n 10 issue7568.py
import numba
from numba import njit, literally
from numba.core import types
from numba.extending import overload
from numba.core.errors import TypingError

import logging
logging.basicConfig(level=logging.DEBUG)

def foo(x):
```
running with that also gives a large backtrace but it does contain:
```
numba.core.errors.TypingError: No implementation of function Function(<function bar at 0x7ff72eafee50>) found for signature:
 
 >>> bar(Literal[str](sdf))
 
There are 2 candidate implementations:
    - Of which 2 did not match due to:
    Overload in function 'bar_ovld': File: issue7568.py: Line 16.
      With argument(s): '(unicode_type)':
     Rejected as the implementation raised a specific error:
       TypingError: bar only supported arg is None
```
