### ISSUE TITLE
test_no_accidental_warnings (numba.tests.test_import.TestNumbaImport) fails on Python 3.9 Windows

### ISSUE THREAD

**Issue by Vyacheslav-Smirnov** [numba/numba#7576]
test_no_accidental_warnings (numba.tests.test_import.TestNumbaImport) fails on Python 3.9 Windows with following message:
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses

How to reproduce:

```
conda create -n test_env python=3.9 pywin32=228 numba=0.54.1 pytest  -c main --override-channels
conda activate test_env
python -u -m numba.runtests -m -v numba.tests.test_import.TestNumbaImport
```

Output:

```
Parallel: 4. Serial: 0
test_no_accidental_warnings (numba.tests.test_import.TestNumbaImport) ... FAIL
test_import_star (numba.tests.test_import.TestNumbaImport) ... ok
test_laziness (numba.tests.test_import.TestNumbaImport)
Importing top-level numba features should not import too many modules. ... ok
test_no_impl_import (numba.tests.test_import.TestNumbaImport)
Tests that importing jit does not trigger import of modules containing ... ok

======================================================================
FAIL: test_no_accidental_warnings (numba.tests.test_import.TestNumbaImport)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\numba\tests\test_import.py", line 103, in test_no_accidental_warnings
    run_in_subprocess(code, flags)
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\numba\tests\support.py", line 996, in run_in_subprocess
    raise AssertionError(msg % (popen.returncode, err.decode()))
AssertionError: process failed with code 1: stderr follows
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\numba\__init__.py", line 19, in <module>
    from numba.core import config
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\numba\core\config.py", line 16, in <module>
    import llvmlite.binding as ll
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\llvmlite\binding\__init__.py", line 4, in <module>
    from .dylib import *
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\llvmlite\binding\dylib.py", line 3, in <module>
    from llvmlite.binding import ffi
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\llvmlite\binding\ffi.py", line 178, in <module>
    from pkg_resources import resource_filename
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\pkg_resources\__init__.py", line 74, in <module>
    from pkg_resources.extern import appdirs
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\pkg_resources\extern\__init__.py", line 52, in create_module
    return self.load_module(spec.name)
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\pkg_resources\extern\__init__.py", line 37, in load_module
    __import__(extant)
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\pkg_resources\_vendor\appdirs.py", line 560, in <module>
    import win32com.shell
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\win32com\__init__.py", line 6, in <module>
    import pythoncom
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\pythoncom.py", line 2, in <module>
    import pywintypes
  File "C:\work\Miniconda3\envs\test_env\lib\site-packages\win32\lib\pywintypes.py", line 2, in <module>
    import imp, sys, os
  File "C:\work\Miniconda3\envs\test_env\lib\imp.py", line 31, in <module>
    warnings.warn("the imp module is deprecated in favour of importlib; "
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses



----------------------------------------------------------------------
Ran 4 tests in 11.274s

FAILED (failures=1)
```

**Comment by gmarkall** [comment]
This error appears to be coming from pywin32, not Numba - I tried this in an environment without pywin32 and the tests passed. After adding pywin32 to the environment, the test failed. The traceback above seems to indicate that `win32.lib.pywintypes` is importing `imp`.

Am I misunderstanding something here?

**Comment by Vyacheslav-Smirnov** [comment]
I need to have both packages in single environment. At the same time, I cannot reproduce the issue with pywin32 package directly:
If I try to import pywintypes, it works without any warnings:

```
(test_env) C:\work>python -c "import pywintypes"

```

But for some reason this warning appears in numba test.

**Comment by stuartarchibald** [comment]
I think it's the `from pkg_resources import resource_filename` that causes the searching around the local installation and it's this that hits the `DeprecationWarning` in `pywintypes`. This was added into llvmlite to resolve: https://github.com/numba/llvmlite/issues/468.

I think any situation where:
* a test suite asserts for no deprecation warnings
* `resource_filename` is in use somewhere prior to running the test
* there's a package like `pywintypes` that has a deprecation warning in it

will likely hit this problem. Given `pywin32` and `pywintypes` are not declared as dependencies or optional dependencies of either Numba or llvmlite, I'm not sure that this is a Numba or a llvmlite issue?

**Comment by Vyacheslav-Smirnov** [comment]
Ok, looks like the issue was fixed in pywin32 package 302 build.
So I am closing this issue.

**Comment by stuartarchibald** [comment]
> Ok, looks like the issue was fixed in pywin32 package 302 build. So I am closing this issue.

Great, thanks for confirming @Vyacheslav-Smirnov.
