### ISSUE TITLE
numba.tests.test_refop_pruning.TestRefOpPruning.test_diamond_2 test failure

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#7643]
## Reporting a bug

This is to track that there has been an intermittent and seemingly impossible to reproduce outside of CI error, where the test `numba.tests.test_refop_pruning.TestRefOpPruning.test_diamond_2 test` fails with:
```
FAIL: test_diamond_2 (numba.tests.test_refop_pruning.TestRefOpPruning)
Parallel: 468. Serial: 36
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\1\s\numba\tests\test_refop_pruning.py", line 95, in test_diamond_2
    fanout=False, fanout_raise=False)
  File "D:\a\1\s\numba\tests\test_refop_pruning.py", line 49, in check
    self.assertEqual(stat, 0, msg=msg)
AssertionError: 7 != 0 : failed checking fanout_raise
```
It has so far only occurred on Azure jobs with Windows, Python 3.7, NumPy 1.18.

It was first seen in https://github.com/numba/numba/pull/7244. Subsequent debugging in https://github.com/numba/numba/pull/7638 whereby most of the PR is reverted makes me think that it is not related to https://github.com/numba/numba/pull/7244. Cause is unknown at present, moving mainline and adding some new tests seems to have made it "go away" in https://github.com/numba/numba/pull/7244, which potentially makes this potentially a latent problem.

**Comment by stuartarchibald** [comment]
This hasn't been seen since reported. It doesn't mean it has gone away, but am going to close this, if it reappears it can be opened again.
