### ISSUE TITLE
parallel `LoweringError` when aliasing `a = a.flat`

### ISSUE THREAD

**Issue by lgarrison** [numba/numba#7658]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Here's a small error I found for a corner case, where the user tries to redefine a variable as `a = a.flat`. Defining a new variable instead, e.g. `b = a.flat` and looping over that doesn't trigger the error.

```python
import numba
import numpy as np

@numba.njit(parallel=True)
def parallel(a):
    a = a.flat
    for i in numba.prange(len(a)):
        a[i] += 1

a = np.arange(10)
parallel(a)
```

Truncated output:
```
[...]
LoweringError: Failed in nopython mode pipeline (step: native lowering)
Type of #18 arg mismatch: i64* != i64

File "<ipython-input-2-40361620b89e>", line 7:
def parallel(a):
    <source elided>
    a = a.flat
    for i in numba.prange(len(a)):
    ^

During: lowering "id=0[LoopNest(index_variable = parfor_index.2, range = (0, $16call_function.6, 1))]{24: <ir.Block at <ipython-input-2-40361620b89e> (7)>}Var(parfor_index.2, <ipython-input-2-40361620b89e>:7)" at <ipython-input-2-40361620b89e> (7)
```

Full output:
<details>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/numba/numba/core/errors.py in new_error_context(fmt_, *args, **kwargs)
    816     try:
--> 817         yield
    818     except NumbaError as e:

~/numba/numba/core/lowering.py in lower_block(self, block)
    279                                    loc=self.loc, errcls_=defaulterrcls):
--> 280                 self.lower_inst(inst)
    281         self.post_block(block)

~/numba/numba/core/lowering.py in lower_inst(self, inst)
    551                     if isinstance(inst, _class):
--> 552                         func(self, inst)
    553                         return

~/numba/numba/parfors/parfor_lowering.py in _lower_parfor_parallel(lowerer, parfor)
    315         print("loop_ranges = ", loop_ranges)
--> 316     call_parallel_gufunc(
    317         lowerer,

~/numba/numba/parfors/parfor_lowering.py in call_parallel_gufunc(lowerer, cres, gu_signature, outer_sig, expr_args, expr_arg_types, loop_ranges, redvars, reddict, redarrdict, init_block, index_var_typ, races, exp_name_to_tuple_var)
   1463 
-> 1464     info = build_gufunc_wrapper(llvm_func, cres, sin, sout,
   1465                                 cache=False, is_parfors=True)

~/numba/numba/np/ufunc/parallel.py in build_gufunc_wrapper(py_func, cres, sin, sout, cache, is_parfors)
    258     signature = cres.signature
--> 259     innerinfo = ufuncbuilder.build_gufunc_wrapper(
    260         py_func, cres, sin, sout, cache=cache, is_parfors=is_parfors,

~/numba/numba/np/ufunc/wrappers.py in build_gufunc_wrapper(py_func, cres, sin, sout, cache, is_parfors)
    500                else _GufuncWrapper)
--> 501     return wrapcls(
    502         py_func, cres, sin, sout, cache, is_parfors=is_parfors,

~/numba/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock

~/numba/numba/np/ufunc/wrappers.py in build(self)
    454         wrapper_name = "__gufunc__." + self.fndesc.mangled_name
--> 455         wrapperlib = self._compile_wrapper(wrapper_name)
    456         return _wrapper_info(

~/numba/numba/np/ufunc/wrappers.py in _compile_wrapper(self, wrapper_name)
    433             # Build wrapper
--> 434             self._build_wrapper(wrapperlib, wrapper_name)
    435         # Non-parfors?

~/numba/numba/np/ufunc/wrappers.py in _build_wrapper(self, library, name)
    411             args = [a.get_array_at_offset(loop.index) for a in arrays]
--> 412             innercall, error = self.gen_loop_body(builder, pyapi, func, args)
    413             # If error, escape

~/numba/numba/np/ufunc/wrappers.py in gen_loop_body(self, builder, pyapi, func, args)
    460     def gen_loop_body(self, builder, pyapi, func, args):
--> 461         status, retval = self.call_conv.call_function(
    462             builder, func, self.signature.return_type, self.signature.args,

~/numba/numba/core/callconv.py in call_function(self, builder, callee, resty, argtys, args, attrs)
    580             raise TypeError("attrs must be an iterable of strings or None")
--> 581         code = builder.call(callee, realargs, attrs=_attrs)
    582         status = self._get_return_status(builder, code,

~/miniconda3/envs/forge/lib/python3.8/site-packages/llvmlite/ir/builder.py in call(self, fn, args, name, cconv, tail, fastmath, attrs, arg_attrs)
    879         """
--> 880         inst = instructions.CallInstr(self.block, fn, args, name=name,
    881                                       cconv=cconv, tail=tail, fastmath=fastmath,

~/miniconda3/envs/forge/lib/python3.8/site-packages/llvmlite/ir/instructions.py in __init__(self, parent, func, args, name, cconv, tail, fastmath, attrs, arg_attrs)
     91                        .format(1 + i, expected_type, arg.type))
---> 92                 raise TypeError(msg)
     93             args[i] = arg

TypeError: Type of #18 arg mismatch: i64* != i64

During handling of the above exception, another exception occurred:

LoweringError                             Traceback (most recent call last)
<ipython-input-2-40361620b89e> in <module>
      9 
     10 a = np.arange(10)
---> 11 parallel(a)

~/numba/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    485                     e.patch_message('\n'.join((str(e).rstrip(), help_msg)))
    486             # ignore the FULL_TRACEBACKS config, this needs reporting!
--> 487             raise e
    488         finally:
    489             self._types_active_call = []

~/numba/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    418         return_val = None
    419         try:
--> 420             return_val = self.compile(tuple(argtypes))
    421         except errors.ForceLiteralArg as e:
    422             # Received request for compiler re-entry with the list of arguments

~/numba/numba/core/dispatcher.py in compile(self, sig)
    963                 with ev.trigger_event("numba:compile", data=ev_details):
    964                     try:
--> 965                         cres = self._compiler.compile(args, return_type)
    966                     except errors.ForceLiteralArg as e:
    967                         def folded(args, kws):

~/numba/numba/core/dispatcher.py in compile(self, args, return_type)
    123 
    124     def compile(self, args, return_type):
--> 125         status, retval = self._compile_cached(args, return_type)
    126         if status:
    127             return retval

~/numba/numba/core/dispatcher.py in _compile_cached(self, args, return_type)
    137 
    138         try:
--> 139             retval = self._compile_core(args, return_type)
    140         except errors.TypingError as e:
    141             self._failed_cache[key] = e

~/numba/numba/core/dispatcher.py in _compile_core(self, args, return_type)
    150 
    151         impl = self._get_implementation(args, {})
--> 152         cres = compiler.compile_extra(self.targetdescr.typing_context,
    153                                       self.targetdescr.target_context,
    154                                       impl,

~/numba/numba/core/compiler.py in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    691     pipeline = pipeline_class(typingctx, targetctx, library,
    692                               args, return_type, flags, locals)
--> 693     return pipeline.compile_extra(func)
    694 
    695 

~/numba/numba/core/compiler.py in compile_extra(self, func)
    427         self.state.lifted = ()
    428         self.state.lifted_from = None
--> 429         return self._compile_bytecode()
    430 
    431     def compile_ir(self, func_ir, lifted=(), lifted_from=None):

~/numba/numba/core/compiler.py in _compile_bytecode(self)
    495         """
    496         assert self.state.func_ir is None
--> 497         return self._compile_core()
    498 
    499     def _compile_ir(self):

~/numba/numba/core/compiler.py in _compile_core(self)
    474                     self.state.status.fail_reason = e
    475                     if is_final_pipeline:
--> 476                         raise e
    477             else:
    478                 raise CompilerError("All available pipelines exhausted")

~/numba/numba/core/compiler.py in _compile_core(self)
    461                 res = None
    462                 try:
--> 463                     pm.run(self.state)
    464                     if self.state.cr is not None:
    465                         break

~/numba/numba/core/compiler_machinery.py in run(self, state)
    351                     (self.pipeline_name, pass_desc)
    352                 patched_exception = self._patch_error(msg, e)
--> 353                 raise patched_exception
    354 
    355     def dependency_analysis(self):

~/numba/numba/core/compiler_machinery.py in run(self, state)
    339                 pass_inst = _pass_registry.get(pss).pass_inst
    340                 if isinstance(pass_inst, CompilerPass):
--> 341                     self._runPass(idx, pass_inst, state)
    342                 else:
    343                     raise BaseException("Legacy pass in use")

~/numba/numba/core/compiler_lock.py in _acquire_compile_lock(*args, **kwargs)
     33         def _acquire_compile_lock(*args, **kwargs):
     34             with self:
---> 35                 return func(*args, **kwargs)
     36         return _acquire_compile_lock
     37 

~/numba/numba/core/compiler_machinery.py in _runPass(self, index, pss, internal_state)
    294             mutated |= check(pss.run_initialization, internal_state)
    295         with SimpleTimer() as pass_time:
--> 296             mutated |= check(pss.run_pass, internal_state)
    297         with SimpleTimer() as finalize_time:
    298             mutated |= check(pss.run_finalizer, internal_state)

~/numba/numba/core/compiler_machinery.py in check(func, compiler_state)
    267 
    268         def check(func, compiler_state):
--> 269             mangled = func(compiler_state)
    270             if mangled not in (True, False):
    271                 msg = ("CompilerPass implementations should return True/False. "

~/numba/numba/core/typed_passes.py in run_pass(self, state)
    394                 lower = lowering.Lower(targetctx, library, fndesc, interp,
    395                                        metadata=metadata)
--> 396                 lower.lower()
    397                 if not flags.no_cpython_wrapper:
    398                     lower.create_cpython_wrapper(flags.release_gil)

~/numba/numba/core/lowering.py in lower(self)
    181         if self.generator_info is None:
    182             self.genlower = None
--> 183             self.lower_normal_function(self.fndesc)
    184         else:
    185             self.genlower = self.GeneratorLower(self)

~/numba/numba/core/lowering.py in lower_normal_function(self, fndesc)
    235         # Init argument values
    236         self.extract_function_arguments()
--> 237         entry_block_tail = self.lower_function_body()
    238 
    239         # Close tail of entry block, do not emit debug metadata else the

~/numba/numba/core/lowering.py in lower_function_body(self)
    264             bb = self.blkmap[offset]
    265             self.builder.position_at_end(bb)
--> 266             self.lower_block(block)
    267         self.post_lower()
    268         return entry_block_tail

~/numba/numba/core/lowering.py in lower_block(self, block)
    278             with new_error_context('lowering "{inst}" at {loc}', inst=inst,
    279                                    loc=self.loc, errcls_=defaulterrcls):
--> 280                 self.lower_inst(inst)
    281         self.post_block(block)
    282 

~/miniconda3/envs/forge/lib/python3.8/contextlib.py in __exit__(self, type, value, traceback)
    129                 value = type()
    130             try:
--> 131                 self.gen.throw(type, value, traceback)
    132             except StopIteration as exc:
    133                 # Suppress StopIteration *unless* it's the same exception that

~/numba/numba/core/errors.py in new_error_context(fmt_, *args, **kwargs)
    829             else:
    830                 tb = None
--> 831             raise newerr.with_traceback(tb)
    832         elif use_new_style_errors():
    833             raise e

LoweringError: Failed in nopython mode pipeline (step: native lowering)
Type of #18 arg mismatch: i64* != i64

File "<ipython-input-2-40361620b89e>", line 7:
def parallel(a):
    <source elided>
    a = a.flat
    for i in numba.prange(len(a)):
    ^

During: lowering "id=0[LoopNest(index_variable = parfor_index.2, range = (0, $16call_function.6, 1))]{24: <ir.Block at <ipython-input-2-40361620b89e> (7)>}Var(parfor_index.2, <ipython-input-2-40361620b89e>:7)" at <ipython-input-2-40361620b89e> (7)
```
</details>

Tested on 0.55.0dev0 and master.  Maybe related to the old #2954 and #3015.

**Comment by stuartarchibald** [comment]
Thanks for the report, I can reproduce. Seems like this is a ParallelAccelerator issue (works when `parallel=False`). CC @DrTodd13
