### ISSUE TITLE
IntEnum as array index? No implementation of getitem found for signature

### ISSUE THREAD

**Issue by JapanYoshi** [numba/numba#7662]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.
[advent_2021_15.zip](https://github.com/numba/numba/files/7722820/advent_2021_15.zip)

I have an observably bad Python program that I tried to apply Numba to. Unfortunately, JIT fails with some arcane reason that could be related to trying to use an IntEnum as an array index.
```
Traceback (most recent call last):
  File "advent_2021_15.py", line 194, in <module>
    (width + height) * pages - 2, # heuristic
  File "C:\Users\Haley\AppData\Roaming\Python\Python37\site-packages\numba\core\dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Haley\AppData\Roaming\Python\Python37\site-packages\numba\core\dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(reflected list(int32)<iv=None>, IntEnum<int32>(Route))

There are 22 candidate implementations:
      - Of which 22 did not match due to:
      Overload of function 'getitem': File: <numerous>: Line N/A.
        With argument(s): '(reflected list(int32)<iv=None>, IntEnum<int32>(Route))':
       No match.

During: typing of intrinsic-call at advent_2021_15.py (170)
During: typing of static-get-item at advent_2021_15.py (170)

File "advent_2021_15.py", line 170:
def push_route(route):
    <source elided>
 for i, r in enumerate(frontier):
  if r[Route.X] == route[Route.X] and r[Route.Y] == route[Route.Y]:
  ^
```

**Comment by JapanYoshi** [comment]
I've begrudgingly removed the enum and I get this error:

`The use of a reflected list(reflected list(int32)<iv=None>)<iv=None> type, assigned to variable 'frontier' in globals, is not supported as globals are considered compile-time constants and there is no known way to compile a reflected list(reflected list(int32)<iv=None>)<iv=None> type as a constant.`

**Comment by gmarkall** [comment]
For the original reported issue, this can be reproduced with:

```python
from numba import njit
from enum import IntEnum

@njit
def f(x, i):
    return x[i]

class Channel(IntEnum):
    RED = 0
    GREEN = 1
    BLUE = 2
    ALPHA = 3

f([1, 2, 3, 4], Channel.RED)
```

which produces:

```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(reflected list(int64)<iv=None>, IntEnum<int64>(Channel))
 
There are 22 candidate implementations:
  - Of which 22 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(reflected list(int64)<iv=None>, IntEnum<int64>(Channel))':
   No match.

During: typing of intrinsic-call at /home/gmarkall/numbadev/issues/7662/repro.py (7)

File "repro.py", line 7:
def f(x, i):
    return x[i]
    ^
```

I'll mark this as a bug rather than a feature request, as it does seem that `IntEnum` members ought to be supported as list indices. A similar problem exists for typed lists:

```python
from numba import njit
from numba.typed import List
from enum import IntEnum

@njit
def f(x, i):
    return x[i]

class Channel(IntEnum):
    RED = 0
    GREEN = 1
    BLUE = 2
    ALPHA = 3

f(List([1, 2, 3, 4]), Channel.RED) 
```

giving:

```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
list indices must be integers or slices
During: typing of intrinsic-call at /home/gmarkall/numbadev/issues/7662/typed.py (8)

File "typed.py", line 8:
def f(x, i):
    return x[i]
    ^
```

> I've begrudgingly removed the enum and I get this error:

Can you try using a [typed list](https://numba.readthedocs.io/en/latest/reference/pysupported.html?highlight=typed%20list#typed-list) and see if you get the same result? If you still have a problem, could you open a new issue with a small executable sample of code that reproduces the error please? (reflected lists are deprecated and the use of Typed lists is the preferred way to go in the future).
