### ISSUE TITLE
numpy.copy messes up result of njitted generator

### ISSUE THREAD

**Issue by PrefixCoder** [numba/numba#7666]
The generator `neighborgood` is meant to generate all versions of 0-1 array with a single item flipped:
```python
@numba.njit
def neighborgood(x):
    n = len(x)
    for i in range(n):
        y = numpy.copy(x)
        y[i] = 1 - y[i]
        yield y
```
Example use: 
```python
>>> list(neighborgood(numpy.array([0, 1, 0, 0, 0], dtype=np.int8)))
[array([1, 1, 0, 0, 0], dtype=int8),
 array([0, 0, 0, 0, 0], dtype=int8),
 array([0, 1, 1, 0, 0], dtype=int8),
 array([0, 1, 0, 1, 0], dtype=int8),
 array([0, 1, 0, 0, 1], dtype=int8)]
```
But when `numpy.copy` or `numpy.ndarray.copy` is called after `yield` statement, something mysterious happens:
```python
@numba.njit
def neighborgood(x):
    n = len(x)
    for i in range(n):
        y = numpy.copy(x)
        y[i] = 1 - y[i]
        yield y
        numpy.copy(y)
```
```python
>>> list(neighborgood(np.array([0, 1, 0, 0, 0], dtype=np.int8)))
[array([-34, -34, -34, -34, -34], dtype=int8),
 array([-34, -34, -34, -34, -34], dtype=int8),
 array([-34, -34, -34, -34, -34], dtype=int8),
 array([-34, -34, -34, -34, -34], dtype=int8),
 array([-34, -34, -34, -34, -34], dtype=int8)]
```

**Comment by gmarkall** [comment]
I can reproduce the issue with master. Copy/pastable executable reproducer:

```python
from numba import njit
import numpy as np


@njit
def neighborgood_1(x):
    n = len(x)
    for i in range(n):
        y = np.copy(x)
        y[i] = 1 - y[i]
        yield y


@njit
def neighborgood_2(x):
    n = len(x)
    for i in range(n):
        y = np.copy(x)
        y[i] = 1 - y[i]
        yield y
        np.copy(y)


print(list(neighborgood_1(np.array([0, 1, 0, 0, 0], dtype=np.int8))))
print(list(neighborgood_2(np.array([0, 1, 0, 0, 0], dtype=np.int8))))
```

produces:

```
[array([1, 1, 0, 0, 0], dtype=int8), array([0, 0, 0, 0, 0], dtype=int8), array([0, 1, 1, 0, 0], dtype=int8), array([0, 1, 0, 1, 0], dtype=int8), array([0, 1, 0, 0, 1], dtype=int8)]
[array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8)]
```

**Comment by stuartarchibald** [comment]
Locally, I see corruption:
```
[array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8), array([-34, -34, -34, -34, -34], dtype=int8)]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff71684bc in malloc_consolidate () from libc.so.6
(gdb) bt
#0  0x00007ffff71684bc in malloc_consolidate () from libc.so.6
#1  0x00007ffff716a135 in _int_malloc () from libc.so.6
#2  0x00007ffff716bd72 in _int_realloc () from libc.so.6
#3  0x00007ffff716de12 in realloc () from libc.so.6
```
this:
```
from numba import njit, types
import numpy as np

@njit
def foo(x):
    n = len(x)
    for i in range(n):
        y = np.copy(x)
        y[i] = 1 - y[i]
        yield y
        np.copy(y)

foo.compile((types.Array(types.int8, 1, 'C'),))
foo.inspect_types()
```
shows this:
```
<snip>
       # --- LINE 10 --- 
        #   $50yield_value.14 = yield y  :: none
        #   del $50yield_value.14

        yield y

        # --- LINE 11 --- 
        #   $54load_global.15 = global(np: <module 'numpy' from '<env>/lib/python3.9/site-packages/numpy/__init__.py'>)  :: Module(<module 'numpy' from '<env>/lib/python3.9/site-packages/numpy/__init__.py'>)
        #   $56load_method.16 = getattr(value=$54load_global.15, attr=copy)  :: Function(<function copy at 0x7fba5353dd30>)
        #   del $54load_global.15
        #   $60call_method.18 = call $56load_method.16(y, func=$56load_method.16, args=[Var(y, issue7666.py:8)], kws=(), vararg=None, target=None)  :: (array(int8, 1d, C),) -> array(int8, 1d, C)
        #   del y
        #   del $60call_method.18
        #   del $56load_method.16
        #   jump 18
        # label 66
        #   del x
        #   del $phi20.1
        #   del $phi18.0
        #   del $18for_iter.3
        #   $const66.0 = const(NoneType, None)  :: none
        #   $68return_value.1 = cast(value=$const66.0)  :: none
        #   del $const66.0
        #   return $68return_value.1

        np.copy(y)
```
looks like there's a lifetime issue, there's a `del y` ahead of the `np.copy`?
