### ISSUE TITLE
`parallel=True` causes `AssertionError` in slicing even with no parallel transformation

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7677]
A slightly modified version of the reproducer from https://numba.discourse.group/t/how-do-i-parallelize-this-code/1085/7?u=gmarkall:

```python
from numba import njit
import numpy as np

@njit(parallel=True)
def myFoo(par,x):
    par[:,0:1]*x
    return 1

x=np.array(np.arange(0,10,2.0))
par=np.array([[i*10.0,i*4.0] for i in range(1,3)])
myFoo(par,x)
```

produces:

```
/home/gmarkall/numbadev/numba/numba/core/typed_passes.py:331: NumbaPerformanceWarning: 
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see https://numba.pydata.org/numba-doc/latest/user/parallel.html#diagnostics for help.

File "repro2.py", line 5:
@njit(parallel=True)
def myFoo(par,x):
^

  warnings.warn(errors.NumbaPerformanceWarning(msg,
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/discourse-1085/repro2.py", line 11, in <module>
    myFoo(par,x)
AssertionError: Sizes of $18binary_subscr.10, x do not match on /home/gmarkall/numbadev/issues/discourse-1085/repro2.py (6)
```

(running with `parallel=False` produces no error)

Could you take a look please @DrTodd13 ?

**Comment by DrTodd13** [comment]
@gmarkall This is expected behavior.  We really need to find a way to deliver this messaging automatically.  Maybe we should just change these assertion errors to start with "ERROR: Likely attempt to use NumPy broadcasting in parallel=True mode, which is not supported."  If someone with your Numba experience doesn't catch this issue then what hope do the mere mortals have?  From the beginning, we should have at least checked that the dimensionality matches at compile time and give  those errors a nice message at compile time.  Unfortunately, when the dimensionality matches, there are going to be cases where some dimensions are size 1 making broadcasting in regular Python/NumPy legitimate but unsupported in parallel mode.  We can only catch those at runtime.  For issue7676 I tried catching the dimensionality mismatch at compile time like I mentioned above.  We should have done that from the beginning but now there's so much water under the bridge it could be tricky to do this now.  For my attempt in 7676, I am able to do it but it raises a huge number of problems because now suddenly arrayexprs are in the gufunc IR and now pass through parts of the compilation pipeline they never have before such as typing.  I hacked the ability to type them but there were yet more problems.  I think with enough effort we could probably catch the dimensionality mismatch cases but we could never catch all broadcasting at compile time as I mentioned above.  There were other problems that came up in my attempt in 7676 that led me to believe it could be a long sequence of issue after issue.  The upside would be that we could allow dimension mismatch broadcasting by falling back to regular Numba behavior but the downside is the time to do it and the weirdness of only disallowing dimension-matching broadcasting which will make it even harder for users to know the rules.

**Comment by gmarkall** [comment]
@DrTodd13 Thanks for having a look and commenting. 

>  If someone with your Numba experience doesn't catch this issue then what hope do the mere mortals have?

Although I have accumulated a reasonable amount of Numba expertise, I don't think I have a very strong understanding of the parallel accelerator - my usage and experience of it is quite limited, and is mostly confined to simple uses and fiddling with reproducers. I think there's probably quite a few "power users" who know it much better than I do :slightly_smiling_face: 

I guess @stuartarchibald and @sklam are better placed to further comment on your suggestions - I can follow what you're saying, but I find it hard to think of any helpful feedback.

**Comment by nicrie** [comment]
Stumbled upon this after setting `parallel=True` in my `numba` function. I also found the error message confusing:

```py
AssertionError: Sizes of x.1, $420binary_subscr.42 do not match on <ipython-input-7-66753253d282> (54)
The above exception was the direct cause of the following exception:

SystemError: CPUDispatcher(<function lpcas_numba at 0x7f7fc73ddf80>) returned a result with an exception set
```

First I thought it was related to some incompatibility  between `numpy` and `numba` (although I use `conda-forge`). Retried with several fresh environments, until I finally came here.
