### ISSUE TITLE
Cannot Pass Literals are argument that aren't hashable

### ISSUE THREAD

**Issue by njriasan** [numba/numba#7707]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/master/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Passing literals that aren't hashable fails at lowering in Numba. Here is a reproducer with a slice.

```python
import numba

@numba.njit
def f(x):
    slc = numba.literally(x)
    return slc

print(f(slice(1, 2)))
```

Which produces the following stack trace
```
Traceback (most recent call last):
  File "test_unhashable_literal.py", line 8, in <module>
    print(f(slice(1, 2)))
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 443, in _compile_for_args
    return_val = self._compile_for_args(*args)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 472, in _compile_core
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 349, in run
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/typed_passes.py", line 398, in run_pass
    lower.create_cpython_wrapper(flags.release_gil)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/lowering.py", line 292, in create_cpython_wrapper
    self.context.create_cpython_wrapper(self.library, self.fndesc,
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/cpu.py", line 184, in create_cpython_wrapper
    library.add_ir_module(wrapper_module)
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/codegen.py", line 727, in add_ir_module
    ir = cgutils.normalize_ir_text(str(ir_module))
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/module.py", line 242, in __repr__
    lines += self._get_body_lines()
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/module.py", line 212, in _get_body_lines
    lines += [str(v) for v in self.globals.values()]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/module.py", line 212, in <listcomp>
    lines += [str(v) for v in self.globals.values()]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 1002, in __str__
    self.descr(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 997, in descr
    self.descr_body(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 991, in descr_body
    blk.descr(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 1131, in descr
    buf += ["  {0}\n".format(instr) for instr in self.instructions]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 1131, in <listcomp>
    buf += ["  {0}\n".format(instr) for instr in self.instructions]
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/_utils.py", line 48, in __str__
    s = self.__cached_str = self._to_string()
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/values.py", line 548, in _to_string
    self.descr(buf)
  File "/Users/nicholasriasanovsky/miniconda3/envs/NUMBA55/lib/python3.8/site-packages/llvmlite/ir/instructions.py", line 218, in descr
    .format(self.opname, return_value.type,
AttributeError: 'tuple' object has no attribute 'type'
```

The source of the problem appears to be `serialize_object` because the line `gv = self.module.__serialized[obj]` always fails when a literal isn't hashable.

I think a reasonable solution would be to support passing a key to `serialize_object`. `box_literal` could then construct a unique object to use as a key.

A possible implementation could build a wrapper type around the literal type that reuse the literal type's hash (but uses a different object to avoid collisions with actually serializing the type).

**Comment by njriasan** [comment]
You can assign this issue to me. I opened a first PR, but if this needs a discussion I'm happy to make changes.

**Comment by swap357** [comment]
This issue was fixed by https://github.com/numba/numba/pull/7714. Closing issue.
