### ISSUE TITLE
`memcpy_region` looks suspiciously wrong

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7734]
https://github.com/numba/numba/blob/f427bd63bbe89a32f16c58d5e01c5867902abefb/numba/core/unsafe/bytes.py#L36-L49

Here `cgutils.raw_memcpy()` is used as:

```python
cgutils.raw_memcpy(builder, dst_ptr, src_ptr, nbytes_val, align_val)
```

whereas `raw_memcpy()` is defined as:

https://github.com/numba/numba/blob/f427bd63bbe89a32f16c58d5e01c5867902abefb/numba/core/cgutils.py#L1051

so this looks like a call to `raw_memcpy` where the `count` is the total number of bytes to copy, and the `itemsize` is the value of `align_val` (which is probably equivalent to 1 in a lot of cases, so this is probably wrong but gets away with it in most cases).

**Comment by gmarkall** [comment]
Adding the following test:

```diff
diff --git a/numba/tests/test_unsafe_intrinsics.py b/numba/tests/test_unsafe_intrinsics.py
index d53e0a652..1fcc96528 100644
--- a/numba/tests/test_unsafe_intrinsics.py
+++ b/numba/tests/test_unsafe_intrinsics.py
@@ -145,6 +145,23 @@ class TestBytesIntrinsic(TestCase):
         expected = [0, 0, 0, 0, 1, 2, 3, 4, 5, 0]
         np.testing.assert_array_equal(d, expected)
 
+    def test_memcpy_region_8byte_align(self):
+        @njit
+        def foo(dst, dst_index, src, src_index, nbytes):
+            # last arg is assume 1 byte alignment
+            memcpy_region(dst.ctypes.data, dst_index,
+                          src.ctypes.data, src_index, nbytes, 8)
+
+        d = np.zeros(10, dtype=np.int64)
+        s = np.arange(10, dtype=np.int64)
+
+        # copy s[1:6] to d[4:9]
+        foo(d, 4, s, 1, 5)
+
+        expected = [0, 0, 0, 0, 1, 2, 3, 4, 5, 0]
+        np.testing.assert_array_equal(d, expected)
+
+
 
 class TestRefCount(TestCase):
     def test_dump_refcount(self):
```

fails with:

```
$ python -m numba.runtests numba.tests.test_unsafe_intrinsics.TestBytesIntrinsic
.F
======================================================================
FAIL: test_memcpy_region_8byte_align (numba.tests.test_unsafe_intrinsics.TestBytesIntrinsic)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/tests/test_unsafe_intrinsics.py", line 162, in test_memcpy_region_8byte_align
    np.testing.assert_array_equal(d, expected)
  File "/home/gmarkall/mambaforge/envs/numbadev/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 934, in assert_array_equal
    assert_array_compare(operator.__eq__, x, y, err_msg=err_msg,
  File "/home/gmarkall/mambaforge/envs/numbadev/lib/python3.10/site-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Arrays are not equal

Mismatched elements: 8 / 10 (80%)
Max absolute difference: 83886078
Max relative difference: 67108863.
 x: array([       0, 16777216, 33554432, 50331648, 67108864, 83886080,
              0,        0,        0,        0])
 y: array([0, 0, 0, 0, 1, 2, 3, 4, 5, 0])

----------------------------------------------------------------------
Ran 2 tests in 0.250s

FAILED (failures=1)
```

so it probably is broken.

**Comment by gmarkall** [comment]
... It turns out that the `align` parameter is completely ignored anyway, and the function signature is a little confusing. I think I've made an error in my test above, but this function is definitely a footgun.

**Comment by gmarkall** [comment]
Noting the differences between `cgutils.raw_memcpy()`'s API and that of the current LLVM version: https://releases.llvm.org/11.0.0/docs/LangRef.html#llvm-memcpy-intrinsic my plan is to update the cgutils API to match it and update all uses in Numba.

**Comment by gmarkall** [comment]
See #7737 for progress.
