### ISSUE TITLE
`ufunc did not contain a loop with signature matching types` error with NumPy 1.22

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7756]
For example, running:

```
$ python -m numba.runtests numba.tests.npyufunc -vf
```

results in:

```
test_basic_gufunc (numba.tests.npyufunc.test_ufuncbuilding.TestGUfuncBuilding) ... ok
test_basic_gufunc (numba.tests.npyufunc.test_ufuncbuilding.TestGUfuncBuildingJitDisabled) ... ok
test_basic_ufunc (numba.tests.npyufunc.test_ufuncbuilding.TestUfuncBuilding) ... ERROR

======================================================================
ERROR: test_basic_ufunc (numba.tests.npyufunc.test_ufuncbuilding.TestUfuncBuilding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/numba/numba/tests/npyufunc/test_ufuncbuilding.py", line 89, in test_basic_ufunc
    check(a)
  File "/home/gmarkall/numbadev/numba/numba/tests/npyufunc/test_ufuncbuilding.py", line 84, in check
    b = ufunc(a, a)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (<class 'numpy.dtype[int32]'>, <class 'numpy.dtype[int32]'>) -> None

----------------------------------------------------------------------
Ran 3 tests in 0.300s
```

**Comment by seberg** [comment]
Just a note, this should be fixed in NumPy 1.22.3, there is nothing to do about it in numba probably.

(it would be good to confirm though, I had pinged sklam, but I have not strictly confirmed that this problem with DUFuncs is fixed)

**Comment by stuartarchibald** [comment]
> Just a note, this should be fixed in NumPy 1.22.3, there is nothing to do about it in numba probably.
> 
> (it would be good to confirm though, I had pinged sklam, but I have not strictly confirmed that this problem with DUFuncs is fixed)

Thanks for noting this @seberg, I just tested a NumPy 1.22.3 build against the `numba.tests.npyufunc` tests and they all passed. Am just running the entire test suite to see if anything else that was reported failing is now ok.

**Comment by stuartarchibald** [comment]
On a run of the whole Numba test suite with NumPy 1.22.3 (tested SciPy but not TBB or other optional deps). There was a single error `numba.tests.test_ufuncs.TestUfuncIssues.test_issue_713` which fails with a`TypingError`:
```
numba.core.errors.TypingError: No implementation for function Function(<ufunc 'floor_divide'>) found for signature:

 >>> floor_divide(complex128, complex128)
```
error was raised from here:
https://github.com/numba/numba/blob/59fa2e335be68148b3bd72a29de3ff011430038d/numba/core/typing/npydecl.py#L106-L107
basically, there's no loop available for those types for that function. If you look at the `np.floor_divide.types` under NumPy 1.22 there's no `[FF->F, 'DD->D', 'GG->G']` as there was in previous versions (i.e. complex type support has been removed from this ufunc).

**Comment by seberg** [comment]
>  (i.e. complex type support has been removed from this ufunc).

I believe that was an intential change., because `floor` is not defined for `complex` either, so the result isn't really defined.

**Comment by stuartarchibald** [comment]
> > (i.e. complex type support has been removed from this ufunc).
> 
> I believe that was an intential change., because `floor` is not defined for `complex` either, so the result isn't really defined.

Thanks for confirming, it makes sense, thankfully the fix is I think trivial on Numba's side, just requires masking off those loop types from the database.

**Comment by seberg** [comment]
Cool, will be nice to have the newest NumPy and numba working again soon :).  I am a bit curious, do you always pin the numpy version because you want to ensure full compatibility across the NumPy API?
Mainly, I am wondering if we can reduce the "downtime" where the newest NumPy isn't supported by `numba` (at least on a fresh install) a bit in some simple way, e.g. by pre-release testing  (giving us a month or so to fix up NumPy and up to a month head-start on numba changes when necessary).

**Comment by stuartarchibald** [comment]
> Cool, will be nice to have the newest NumPy and numba working again soon :).

Indeed, should be fixed for the next Numba release!

> I am a bit curious, do you always pin the numpy version because you want to ensure full compatibility across the NumPy API?

Yes, but not just API, also numerical match. There's also that we can't guarantee forward compatibility and historically have found tickets opened about Numba X not working with NumPy Y (where Y is some version after Numba X was released) and this breaking in production uses.

> Mainly, I am wondering if we can reduce the "downtime" where the newest NumPy isn't supported by `numba` (at least on a fresh install) a bit in some simple way, e.g. by pre-release testing (giving us a month or so to fix up NumPy and up to a month head-start on numba changes when necessary).

I think this is something we should consider doing. What do you think would be the best way to handle this? Would it be an idea to perhaps N (N=10?) weeks before a scheduled NumPy release open a ticket on the Numba tracker to start looking at compatibility? Other ideas are welcomed!

**Comment by esc** [comment]
> Cool, will be nice to have the newest NumPy and numba working again soon :). I am a bit curious, do you always pin the numpy version because you want to ensure full compatibility across the NumPy API? Mainly, I am wondering if we can reduce the "downtime" where the newest NumPy isn't supported by `numba` (at least on a fresh install) a bit in some simple way, e.g. by pre-release testing (giving us a month or so to fix up NumPy and up to a month head-start on numba changes when necessary).

Yes, I am the right person to talk to about this. We do want to start tracking NumPy closer to ensure comaptability with upcoming releases. We usually pin Numpy on our release branch to the latest working version at the time to prevent any unfortunate surprises if a Numpy release comes out half-way during our own releases cycle. I think it will be good idea however to discuss upgrading out "infrastructure" in it's own ticket.

**Comment by seberg** [comment]
> I think there's probably two separate issues?

Yes, I guess so.  I believe I had mentioned it before, aside from `--pre` releases, we do have NumPy dev wheels available: https://anaconda.org/scipy-wheels-nightly/numpy
If you test against those "nightlies", you probably want to say it is OK for that test to fail.  But it would give a nice heads up about upcoming changes and allow you to float issues to NumPy quickly.  (I guess testing numba is difficult, so I am not sure how easy this is.)
