### ISSUE TITLE
`return type must be specified for object mode` with NumPy 1.22

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7757]
With NumPy 1.22, `numba.tests.npyufunc.test_ufuncbuilding.TestUfuncBuilding.test_ufunc_forceobj`

gives:

```
======================================================================
ERROR: test_ufunc_forceobj (numba.tests.npyufunc.test_ufuncbuilding.TestUfuncBuilding)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/site-packages/numba/tests/npyufunc/test_ufuncbuilding.py", line 126, in test_ufunc_forceobj
    b = ufunc(a, a)
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/site-packages/numba/np/ufunc/dufunc.py", line 202, in _compile_for_args
    return self._compile_for_argtys(tuple(argtys))
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/site-packages/numba/np/ufunc/dufunc.py", line 221, in _compile_for_argtys
    actual_sig = ufuncbuilder._finalize_ufunc_signature(
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/site-packages/numba/np/ufunc/ufuncbuilder.py", line 185, in _finalize_ufunc_signature
    raise TypeError("return type must be specified for object mode")
TypeError: return type must be specified for object mode
```

**Comment by 1844144** [comment]
numba.tests.npyufunc.test_ufuncbuilding.TestUfuncBuilding.test_ufunc_forceobj works fine with numpy 1.22.3
