### ISSUE TITLE
`test_gitdiff` fails with NumPy 1.22

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#7759]
With NumPy 1.22 we get:

```
 ======================================================================
ERROR: test_gitdiff (numba.tests.test_runtests.TestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/site-packages/numba/tests/test_runtests.py", line 149, in test_gitdiff
    outs = self.get_testsuite_listing(['-g'])
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/site-packages/numba/tests/test_runtests.py", line 34, in get_testsuite_listing
    out_bytes = subprocess.check_output(cmd, **subp_kwargs)
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/esc/miniconda3/envs/numba-dev/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/esc/miniconda3/envs/numba-dev/bin/python', '-m', 'numba.runtests', '-l', '-g']' returned non-zero exit status 1.
```

**Comment by 1844144** [comment]
Passed ok with numpy 1.22.3
