### ISSUE TITLE
numba fails with UNKNOWN CUDA ERROR, what is the cuda toolkit that is suitable to the latest numba 0.55.x?

### ISSUE THREAD

**Issue by myanuka** [numba/numba#7768]
numba fails with UNKNOWN CUDA ERROR, what is the cuda toolkit that is suitable to the latest numba 0.55.x?

**Comment by myanuka** [comment]
I reInstall every thing and still a simple application which calculate
gaussian kernel using @jit fails. something must be wrong

*Moti Yanuka*

*050-6415606*
***@***.*** ***@***.***> *

**Comment by myanuka** [comment]
> Any version from 9.2 to 11.6 is suitable.

See this code and runtime erros
# This is a sample Python script.

# Press Shift+F10 to execute it or replace it with your code.
# Press Double Shift to search everywhere for classes, files, tool windows, actions, and settings.
import numba
import math
import numpy as np

SQRT_TWOPI = np.float32(math.sqrt(2 * math.pi))

@numba.vectorize(['float32(float32, float32, float32)'], target='cuda')
def gaussian(x, x0, sigma):
    return math.exp(-((x - x0) / sigma)**2 / 2) / SQRT_TWOPI / sigma

x = np.linspace(-3, 3, 10000, dtype=np.float32)
print(x)
g = gaussian(x, 0, 1)  # 1D result
print(g)
x2d = x.reshape((100,100))
g2d = gaussian(x2d, 0, 1) # 2D result
print(g2d)
# See PyCharm help at https://www.jetbrains.com/help/pycharm/
C:\Users\myanu\PycharmProjects\pythonProject5\venv\Scripts\python.exe C:/Users/myanu/PycharmProjects/pythonProject4/main.py
[-3.        -2.9994    -2.9987998 ...  2.9987998  2.9994     3.       ]
Traceback (most recent call last):
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\cudadrv\driver.py", line 2682, in add_ptx
    driver.cuLinkAddData(self.handle, enums.CU_JIT_INPUT_PTX,
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\cudadrv\driver.py", line 319, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\cudadrv\driver.py", line 384, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myanu\PycharmProjects\pythonProject4\main.py", line 17, in <module>
    g = gaussian(x, 0, 1)  # 1D result
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\dispatcher.py", line 37, in __call__
    return CUDAUFuncMechanism.call(self.functions, args, kws)
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\np\ufunc\deviceufunc.py", line 297, in call
    cr.launch(func, shape[0], stream, devarys)
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\dispatcher.py", line 155, in launch
    func.forall(count, stream=stream)(*args)
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\compiler.py", line 334, in __call__
    kernel = self.kernel.specialize(*args)
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\compiler.py", line 972, in specialize
    specialization = Dispatcher(self.py_func, [types.void(*argtypes)],
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\compiler.py", line 805, in __init__
    self.compile(sigs[0])
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\compiler.py", line 1093, in compile
    kernel.bind()
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\compiler.py", line 466, in bind
    self._codelibrary.get_cufunc()
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\codegen.py", line 201, in get_cufunc
    cubin = self.get_cubin(cc=device.compute_capability)
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\codegen.py", line 174, in get_cubin
    linker.add_ptx(ptx.encode())
  File "C:\Users\myanu\PycharmProjects\pythonProject5\venv\lib\site-packages\numba\cuda\cudadrv\driver.py", line 2685, in add_ptx
    raise LinkerError("%s\n%s" % (e, self.error_log))
numba.cuda.cudadrv.driver.LinkerError: [222] Call to cuLinkAddData results in UNKNOWN_CUDA_ERROR
ptxas application ptx input, line 9; fatal   : Unsupported .version 7.6; current version is '7.1'

Process finished with exit code 1

**Comment by gmarkall** [comment]
You have a driver that supports up to CUDA 11.1, but you are using the CUDA toolkit 11.6. You need to either:

- Update to a driver that supports CUDA 11.6 (510.39.01 or above) - recommended if you can do it, or
- Downgrade to using the CUDA toolkit 11.1.

**Comment by myanuka** [comment]
Thanks for the tip!

בתאריך יום ו׳, 21 בינו׳ 2022, 09:14, מאת Graham Markall ‏<
***@***.***>:

**Comment by myanuka** [comment]
Hi
I am trying to whtie image processing kernel which does image smoothing
(blur)
do you have and example for how to do it, I attach my version which takes
0.7 second
probably I wrote it not optimized
*Moti Yanuka*

*050-6415606*
***@***.*** ***@***.***> *

**Comment by myanuka** [comment]
Hi Graham
thanks for your help
I am trying to whtie image processing kernel which does image smoothing
(blur)
do you have and example for how to do it, I attach my version which takes
0.7 second
probably I wrote it not optimized

*Moti Yanuka*

*050-6415606*
***@***.*** ***@***.***> *

**Comment by gmarkall** [comment]
Unfortunately it's not possible to email attachments to Github issues. I would suggest creating a post on https://numba.discourse.group with your code and a description of how to run it to replicate the issues you face in order to get further assistance.

I'm going to close this issue now as the original problem (the mismatch between driver and runtime versions) appears to be resolved.
