### ISSUE TITLE
A problem of  fails with UNKNOWN CUDA ERROR

### ISSUE THREAD

**Issue by ammm911** [numba/numba#7769]
### 
Hello everyone
When I call a kernel function of CUDA in a loop, I receive an unexpected message at step 7  of the loop  , that 
  **numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuCtxSynchronize results in UNKNOWN_CUDA_ERROR**
but when I try to debug the code，step by step of the loop  , every step of the loop is normal，there are no exceptions。
How can I avoid this problem？I need some advice，please thank you。
environment
os： windows 10
device ： GeForce GTX 1060
soft： python 3.8 numba 0.53.1
### logs
F:\AnaCondaEvn\envs\SSC\AR\python.exe F:/SSC/AR/tests/testMB/testBO.py
loop step 0
loop step 1
loop step 2
loop step 3
loop step 4
loop step 5
loop step 6
loop step 7
Traceback (most recent call last):
  File "F:/SSC/AR/tests/testMB/testBO.py", line 37, in <module>
    doTest()
  File "F:/SSC/AR/tests/testMB/testBO.py", line 32, in doTest
    MB.BO.buildBlocksMap(IM, WRSP)
  File "F:\SSC\AR\MB\BO.py", line 27, in buildBlocksMap
    buildBlocks(orgDateMaps[i], WRSP)
  File "F:\SSC\AR\MB\BO.py", line 41, in buildBlocks
    touch.Halfinger.getDate(orgDate,
  File "F:\SSC\AR\touch\Halfinger.py", line 38, in getDate
    buildHalfinger(dataMap)
  File "F:\SSC\AR\touch\Halfinger.py", line 326, in buildHalfinger
    cuda.synchronize()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\api.py", line 238, in synchronize
    return current_context().synchronize()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1223, in synchronize
    driver.cuCtxSynchronize()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuCtxSynchronize results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 642, in _exitfunc
    f()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1804, in deref
    mem.free()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1617, in free
    self._finalizer()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1285, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 970, in add_item
    self.clear()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 981, in clear
    dtor(handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 642, in _exitfunc
    f()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1804, in deref
    mem.free()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1617, in free
    self._finalizer()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1285, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 970, in add_item
    self.clear()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 981, in clear
    dtor(handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 642, in _exitfunc
    f()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1804, in deref
    mem.free()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1617, in free
    self._finalizer()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1285, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 970, in add_item
    self.clear()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 981, in clear
    dtor(handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 642, in _exitfunc
    f()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1804, in deref
    mem.free()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1617, in free
    self._finalizer()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1285, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 970, in add_item
    self.clear()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 981, in clear
    dtor(handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 642, in _exitfunc
    f()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1804, in deref
    mem.free()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1617, in free
    self._finalizer()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1285, in core
    deallocations.add_item(driver.cuMemFree, handle, size)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 970, in add_item
    self.clear()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 981, in clear
    dtor(handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuMemFree results in UNKNOWN_CUDA_ERROR
Traceback (most recent call last):
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 642, in _exitfunc
    f()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\weakref.py", line 566, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1364, in core
    dealloc.add_item(module_unload, handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 970, in add_item
    self.clear()
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 981, in clear
    dtor(handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 1362, in module_unload
    driver.cuModuleUnload(handle)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\AnaCondaEvn\envs\SSC\AR\lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuModuleUnload results in UNKNOWN_CUDA_ERROR

Process finished with exit code 1

**Comment by gmarkall** [comment]
I think it's likely that there's an issue in the kernel causing it to do an illegal memory access. Some things you can try to debug:

- Run with `compute-sanitizer` - instead of `python testBO.py` run `compute-sanitizer python testBO.py` - if an illegal memory access is detected it will report on the thread and illegal address being accessed. Note that this doesn't detect all access violations, so the absence of an error message is not necessarily the absence of an error - however, in my experience it is very good at spotting most/many of them, and runs as fast as normally running your program.
- Run with the [CUDA simulator](https://numba.readthedocs.io/en/latest/cuda/simulator.html) - set the environment variable `NUMBA_ENABLE_CUDASIM` to 1 - if your code is compatible with the simulator (not all features are supported in the simulator) then you will be able to debug the code using the normal Python debugger, and any Python exceptions that would have been raised will be raised (e.g. bounds errors). The CUDA simulator is very slow though, so you may need to reduce the size of input and your launch configuration to be able to work with it at a reasonable speed.
- Paste a runnable version of the code that reproduces the issue here, and I might be able to suggest how to look further into the issue.

**Comment by ammm911** [comment]
> 
Thank you for your advice，I will try，It seems to be a serious problem

**Comment by gmarkall** [comment]
Do feel free to provide more details / info / questions if you need any more troubleshooting guidance.

**Comment by ammm911** [comment]
> Do feel free to provide more details / info / questions if you need any more troubleshooting guidance.

I did some tests as following code
### test code
from time import time
from numba import jit, cuda
import numpy as np

@cuda.jit()
def doTestCubaFun(A, N):
    tx = cuda.threadIdx.x
    bx = cuda.blockIdx.x
    bw = cuda.blockDim.x
    pos = tx + bx * bw
    if pos < A.shape[0]:
       # illegal address
        **A[pos + 1000000] = pos // N**  

def doTest():
    start = time()
    A_host = np.empty(1024, dtype=np.int64)
    N = 20
    A = cuda.to_device(A_host)
    doTestCubaFun[1, 1024](A, N)
    cuda.synchronize()
    A.copy_to_host(A_host)
    print("cost time " + str(time() - start))
    print(A_host)

### logs
Traceback (most recent call last):
  File "F:\numbaTest\GPUTEST.py", line 77, in <module>
    doTest()
  File "F:\numbaTest\GPUTEST.py", line 33, in doTest
    cuda.synchronize()
  File "F:\numbaTest\Anaconda3\envs\numbaTest\Lib\site-packages\numba\cuda\api.py", line 238, in synchronize
    return current_context().synchronize()
  File "F:\numbaTest\Anaconda3\envs\numbaTest\Lib\site-packages\numba\cuda\cudadrv\driver.py", line 1223, in synchronize
    driver.cuCtxSynchronize()
  File "F:\numbaTest\Anaconda3\envs\numbaTest\Lib\site-packages\numba\cuda\cudadrv\driver.py", line 300, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "F:\numbaTest\Anaconda3\envs\numbaTest\Lib\site-packages\numba\cuda\cudadrv\driver.py", line 335, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [700] Call to cuCtxSynchronize results in UNKNOWN_CUDA_ERROR

But interestingly ， if the illegal address  is  A[pos + 2000] = pos // N   there is no exception。

Thank you again for your advice， I'll check what my code is for

**Comment by gmarkall** [comment]
> But interestingly ， if the illegal address is A[pos + 2000] = pos // N there is no exception。

You can often step a little outside the bounds of an array without causing a CUDA error - the further out you are, the more likely an observable error like this is to occur.

**Comment by ammm911** [comment]
> Do feel free to provide more details / info / questions if you need any more troubleshooting guidance.
Hey,gmarkall 
I think I found the main reason for the problem. the problem was caused by cuda Atomic Operations.
The result of the operations ,  I got some wrong data for the address .
What features do we need to know to use the cuda Atomic Operations in loop?
I did some comparative tests.
Following the data  of the loop  starts at 0 step and starts at 7 step are different .The last two columns are different.

### the  loop starts at 7 step 
 (This calculation is correct, the number of setp is not parament)
>   Before using the Atomic Operations data
>       block 239 240 316.0 76.0
>       block 272 273 206.5 138.0
>       block 396 397 206.5 158.0
>       block 489 490 206.5 144.0
>  After using the Atomic Operations data
>       block 239 641 117.0 235.0
>       block 272 775 348.0 122.5
>       block 396 1052 348.0 309.5
>       block 489 1282 348.0 322.3
###  the loop starts at 0 step 
(This calculation result is wrong ,the number of setp is not parament)
> Before using the Atomic Operations data
>        block 239 240 316.0 76.0
>        block 272 273 206.5 138.0
>        block 396 397 206.5 158.0
>        block 489 490 206.5 144.0
> After using the Atomic Operations data
>        block 239 641 864.0 960.0
>        block 272 775 867.5 601.5
>        block 396 1052 867.5 963.7
>        block 489 1282 867.5 423.3
I'll make a little program later to simulate this process for you thansk.

**Comment by ammm911** [comment]
@gmarkall  sorry，I can't reproduce this exception in the new program, but I solved the problem by modifying a small piece of code，Use  cuda.to_device instead of cuda.device_array_like to create a CUDA device array,thank you again for your advice.

**Comment by stuartarchibald** [comment]
For future, Numba now has a discourse forum https://numba.discourse.group/ which is great for questions like this, please do consider posting there in future :) Thanks!
