### ISSUE TITLE
Providing many keyword arguments triggers assertion error with Python 3.10 due to unsupported bytecode

### ISSUE THREAD

**Issue by njriasan** [numba/numba#7812]
It seems that Python 3.10 produces a different bytecode instruction, `CALL_FUNCTION_EX` when using a large number of keyword arguments. From my testing it seems like this occurs once you reach 16 keyword arguments. I only see this behavior on Python 3.10 and not Python 3.9. Here is a reproducer:

```python
import numba

@numba.njit
def my_func1(a=None, b=None, c=None, d=None, e=None, f=None, g=None, h=None, i=None, j=None, k=None, l=None, m=None, n=None, o=None, p=None):
    return my_func2(
        a=a,
        b=b,
        c=c,
        d=d,
        e=e,
        f=f,
        g=g,
        h=h,
        i=i,
        j=j,
        k=k,
        l=l,
        m=m,
        n=n,
        o=o,
        p=p
    )


@numba.njit
def my_func2(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p):
    return


print(my_func1())
```

**Comment by njriasan** [comment]
It seems like this example does produce issues with Python 3.9, but its a different issue that says `No type info available for none as a callable.`

**Comment by njriasan** [comment]
I found the mistake in my reproducer and edited the issue. I don't see any issue with Python 3.9 but I do with Python 3.10.

**Comment by njriasan** [comment]
I'm not sure if this should be classified as a bug, but I believe this is a regression due to changes in the bytecode.

**Comment by njriasan** [comment]
Here is the full bytecode in case this is helpful:

```python3
>          0	NOP(arg=None, lineno=5)
           2	LOAD_GLOBAL(arg=0, lineno=5)
           4	LOAD_CONST(arg=17, lineno=5)
           6	BUILD_MAP(arg=0, lineno=5)
           8	LOAD_CONST(arg=1, lineno=5)
          10	LOAD_FAST(arg=0, lineno=6)
          12	MAP_ADD(arg=1, lineno=6)
          14	LOAD_CONST(arg=2, lineno=5)
          16	LOAD_FAST(arg=1, lineno=7)
          18	MAP_ADD(arg=1, lineno=7)
          20	LOAD_CONST(arg=3, lineno=5)
          22	LOAD_FAST(arg=2, lineno=8)
          24	MAP_ADD(arg=1, lineno=8)
          26	LOAD_CONST(arg=4, lineno=5)
          28	LOAD_FAST(arg=3, lineno=9)
          30	MAP_ADD(arg=1, lineno=9)
          32	LOAD_CONST(arg=5, lineno=5)
          34	LOAD_FAST(arg=4, lineno=10)
          36	MAP_ADD(arg=1, lineno=10)
          38	LOAD_CONST(arg=6, lineno=5)
          40	LOAD_FAST(arg=5, lineno=11)
          42	MAP_ADD(arg=1, lineno=11)
          44	LOAD_CONST(arg=7, lineno=5)
          46	LOAD_FAST(arg=6, lineno=12)
          48	MAP_ADD(arg=1, lineno=12)
          50	LOAD_CONST(arg=8, lineno=5)
          52	LOAD_FAST(arg=7, lineno=13)
          54	MAP_ADD(arg=1, lineno=13)
          56	LOAD_CONST(arg=9, lineno=5)
          58	LOAD_FAST(arg=8, lineno=14)
          60	MAP_ADD(arg=1, lineno=14)
          62	LOAD_CONST(arg=10, lineno=5)
          64	LOAD_FAST(arg=9, lineno=15)
          66	MAP_ADD(arg=1, lineno=15)
          68	LOAD_CONST(arg=11, lineno=5)
          70	LOAD_FAST(arg=10, lineno=16)
          72	MAP_ADD(arg=1, lineno=16)
          74	LOAD_CONST(arg=12, lineno=5)
          76	LOAD_FAST(arg=11, lineno=17)
          78	MAP_ADD(arg=1, lineno=17)
          80	LOAD_CONST(arg=13, lineno=5)
          82	LOAD_FAST(arg=12, lineno=18)
          84	MAP_ADD(arg=1, lineno=18)
          86	LOAD_CONST(arg=14, lineno=5)
          88	LOAD_FAST(arg=13, lineno=19)
          90	MAP_ADD(arg=1, lineno=19)
          92	LOAD_CONST(arg=15, lineno=5)
          94	LOAD_FAST(arg=14, lineno=20)
          96	MAP_ADD(arg=1, lineno=20)
          98	LOAD_CONST(arg=16, lineno=5)
         100	LOAD_FAST(arg=15, lineno=21)
         102	MAP_ADD(arg=1, lineno=21)
         104	CALL_FUNCTION_EX(arg=1, lineno=5)
         106	RETURN_VALUE(arg=None, lineno=5)
```

**Comment by esc** [comment]
@njriasan thank you very much for reporting this! I concur that this is probably a 3.10 issue. It probably slipped through because we hadn't had a unit test for this. For reference the the backtrace is:

```
 💣 zsh» python issue7812.py
Traceback (most recent call last):
  File "/Users/esc/git/numba/issue7812.py", line 30, in <module>
    print(my_func1())
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 471, in _compile_for_args
    error_rewrite(e, 'unsupported_error')
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 407, in error_rewrite
    raise e
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/esc/git/numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/esc/git/numba/numba/core/compiler.py", line 707, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/esc/git/numba/numba/core/compiler.py", line 443, in compile_extra
    return self._compile_bytecode()
  File "/Users/esc/git/numba/numba/core/compiler.py", line 511, in _compile_bytecode
    return self._compile_core()
  File "/Users/esc/git/numba/numba/core/compiler.py", line 490, in _compile_core
    raise e
  File "/Users/esc/git/numba/numba/core/compiler.py", line 477, in _compile_core
    pm.run(self.state)
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 353, in run
    raise patched_exception
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/esc/git/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/esc/git/numba/numba/core/compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "/Users/esc/git/numba/numba/core/untyped_passes.py", line 86, in run_pass
    func_ir = interp.interpret(bc)
  File "/Users/esc/git/numba/numba/core/interpreter.py", line 358, in interpret
    flow.run()
  File "/Users/esc/git/numba/numba/core/byteflow.py", line 107, in run
    runner.dispatch(state)
  File "/Users/esc/git/numba/numba/core/byteflow.py", line 282, in dispatch
    fn(state, inst)
  File "/Users/esc/git/numba/numba/core/byteflow.py", line 832, in op_CALL_FUNCTION_EX
    raise UnsupportedError(errmsg)
numba.core.errors.UnsupportedError: Failed in nopython mode pipeline (step: analyzing bytecode)
CALL_FUNCTION_EX with **kwargs not supported

```

**Comment by esc** [comment]
We will have to decide next week if this should be a bug or a feature!

**Comment by stuartarchibald** [comment]
I'm reasonably sure that this can be fixed, but it potentially involves a lot of work. Maybe the fix could come as rewrite of the sequence or through the use of `LiteralStrKeyDict`, the latter would likely permit more use of `**kwargs` in general.

**Comment by sklam** [comment]
i'd guess rewriting the sequence will be way faster (dev and runtime)

**Comment by njriasan** [comment]
> We will have to decide next week if this should be a bug or a feature!

I would argue this should be considered a bug because its a regression of behavior that was supported in Python 3.9.

**Comment by njriasan** [comment]
> i'd guess rewriting the sequence will be way faster (dev and runtime)

@sklam could you elaborate on what you and @stuartarchibald are referring to when you say rewriting the sequence? If possible could you point me to where I can look in the source code to understand this better?

**Comment by sklam** [comment]
@njriasan, we are referring to rewriting the bytecode sequence as part of [`interpreter.py`](https://github.com/numba/numba/blob/main/numba/core/interpreter.py). An example of the rewrite can be find at:

https://github.com/numba/numba/blob/d9efc9ebce26c61eee2b3665144d0e321327131e/numba/core/interpreter.py#L82

**Comment by njriasan** [comment]
I've found the section of CPython responsible for this change.

https://github.com/python/cpython/blob/a58ebcc701dd6c43630df941481475ff0f615a81/Python/compile.c#L55
https://github.com/python/cpython/blob/a58ebcc701dd6c43630df941481475ff0f615a81/Python/compile.c#L4442

It does occur only when you have > 16 keyword arguments.

**Comment by njriasan** [comment]
For clarity purposes, here is the Python3.9 branch. Python3.10 just added that extra case.

https://github.com/python/cpython/blob/c11f41b2c989121e34ccf94cb5b7896fbdb859ab/Python/compile.c#L4265

**Comment by esc** [comment]
@njriasan awesome, great find! 🕵️‍♂️

**Comment by njriasan** [comment]
I'm going to use this issue to record some background information on this issue and the optimizations made. I'll include all of this information in the code as well, but since it may take a bit of time to construct a draft PR, I want to get this information written down while it is fresh.

I did a deeper dive into the bytecode and it seems like there are 6 "distinct" cases where the bytecode differs and this path is taken. For all of these case I assume `(n_args / 2) + n_kws > 15` holds. The cases are:

1. No args and > 15 KWS
2. < 30 args and < 15 KWS
3. > 30 args and <= 15 KWS
4. <= 30 args and > 15 KWS
5. > 30 args and > 15 KWS

The main cases to consider are when `(n_args / 2) > 15` or `n_kws > 15` holds independently vs when only `(n_args / 2) + n_kws > 15` holds. I'll briefly discuss the bytecode patterns independently for args and kws. I should note that  `> 30 args and No KWS` is already handled by existing optimizations and thus omitted.

## > 15 KWS

This is the case from the original example. The bytecode above shows the example, but the general structure is

```python
LOAD_CONST # Load the final size of the map
BUILD_MAP # Construct the map
# START REPEAT N times, once for each kwarg
LOAD_CONST # Load a constant for the name of the argument
LOAD_FAST # Load the argument
MAP_ADD # Append the (key, value) pair to the map
# END REPEAT N times, once for each kwarg
CALL_FUNCTION_EX # Call the function with the map
```

## <= 15 KWS

When there are fewer than 15 KWS, the bytecode is somewhat simpler because the map is built on the stack. Instead the bytecode is:

```python
# START REPEAT N times, once for each kwarg
LOAD_FAST # Load the argument
# END REPEAT N times, once for each kwarg
LOAD_CONST # Load the size of the map
BUILD_CONST_KEY_MAP # Build the map
```
## > 30 ARGS

When there are > 30 args, the input arguments get converted to a tuple after a list is already created.

```python
BUILD_LIST # Create the list
# START REPEAT N times, once for each arg
LOAD_FAST # Load the argument
LIST_APPEND # Add the argument to the list
# END REPEAT N times, once for each arg
LIST_TO_TUPLE # Convert the args to a tuple.
```
I believe this should be similar to the existing `peep_hole_list_to_tuple`, but it cannot just be reused as is because it won't contain `extend`.

## <= 30 ARGS

When there are <= 30 args, the input args are just a tuple.

```python
# START REPEAT N times, once for each arg
LOAD_FAST # Load the argument
# END REPEAT N times, once for each arg
BUILD_TUPLE # Create the tuple.
```

**Comment by njriasan** [comment]
To clarify, the `LOAD_FAST` is just the way to load the argument in my example. It may be many other things in general.

**Comment by stuartarchibald** [comment]
I don't think at present the transform will be able to handle inline control flow at the call site. For example, the rather contrived:
```python
import numba
import dis

@numba.njit
def my_func1(a=None, b=None, c=None, d=None, e=None, f=None, g=None, h=None, i=None, j=None, k=None, l=None, m=None, n=None, o=None, p=None):
    return my_func2(
        a=a,
        b=b,
        c=c,
        d=d,
        e=e,
        f=f,
        g=g,
        h=h,
        i=i,
        j=j,
        k=k,
        l=l,
        m=m,
        n=n,
        o=o,
        p = False if a else True
    )


@numba.njit
def my_func2(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p):
    return

print(dis.dis(my_func1.py_func))
print(my_func1())
```
which gives a bytecode that has:
```
  6          96 LOAD_CONST              16 ('p')

 22          98 LOAD_FAST                0 (a)
            100 POP_JUMP_IF_FALSE       55 (to 110)
            102 LOAD_CONST              17 (False)
            104 MAP_ADD                  1

  6         106 CALL_FUNCTION_EX         1
            108 RETURN_VALUE

 22     >>  110 LOAD_CONST              18 (True)
            112 MAP_ADD                  1

  6         114 CALL_FUNCTION_EX         1
```
at the location where `p` is resolved and added to the map prior to the call.

**Comment by stuartarchibald** [comment]
A similar issue exists in the `nargs>30` use case:
```python
import numba
import dis

@numba.njit
def my_func1(a01, a02, a03, a04, a05, a06, a07, a08, a09, a10,
             a11, a12, a13, a14, a15, a16, a17, a18, a19, a20,
             a21, a22, a23, a24, a25, a26, a27, a28, a29, a30,
             a31,
             ):
    return my_func2(a01, a02, a03, a04, a05, a06, a07, a08, a09, a10,
                    a11, a12, a13, a14, a15, a16, a17, a18, a19, True if a01 else False,
                    a21, a22, a23, a24, a25, a26, a27, a28, a29, a30, a31)


@numba.njit
def my_func2(a01, a02, a03, a04, a05, a06, a07, a08, a09, a10,
             a11, a12, a13, a14, a15, a16, a17, a18, a19, a20,
             a21, a22, a23, a24, a25, a26, a27, a28, a29, a30,
             a31):
    return

print(dis.dis(my_func1.py_func))
print(my_func1(*range(31)))
```
which gives:
```
Unsupported op-code encountered: list_to_tuple(info=('$phi92.1',))
```
as I think the transform fails due to the branch occurring within the `LOAD_FAST`+`LIST_APPEND` sequence that occurs ahead of the `LIST_TO_TUPLE`.

**Comment by stuartarchibald** [comment]
Those two previous comments are intended for the PR, not this issue, so I'll duplicate them there, apologies.
