### ISSUE TITLE
Support passing non-constant values to Exceptions in JIT

### ISSUE THREAD

**Issue by njriasan** [numba/numba#7834]
---

## Feature Request

In many cases it seems like it would be desirable to raise exceptions with strings that aren't constants. My strongest use case is that I have an exception that happens in object mode, but because the message may be unclear and hard to determine, I want to append some additional information about the jit function is triggering this exception (for example function name and maybe argument values).

Here is an example where my exception message arises from using object mode.

```python
import numba

@numba.njit
def f():
    with numba.objmode(res="unicode_type"):
        res = g()
    raise ValueError(f"Exception in f(): {res}")

def g():
    return "This is an Exception"

f()
```

**Comment by czgdp1807** [comment]
So, I started working on this locally. Since, `ValueError` is a callable so while inferring constants in its arguments it reaches the following line,

https://github.com/numba/numba/blob/0f5953df2a2ee6eea1ac44b974bcd954aae91bc6/numba/core/consts.py#L96

Now, since we are passing a non-constant string so the above line fails and hence we get a `ConstantInferenceError`. The fix which I have thought of is this, if the callable is an exception then ignore the constaness of the message (i.e., change the above loop with the body having `try-except` block, catch `ConstantInferenceError`, if `_exc` is `True` then add `a` otherwise raise the caught exception). And in the `numba/core/lowering.py` add support for `ir.Raise` in a way similar to `StaticRaise`. I will post a diff on Monday even though if I fail implementing this approach (for learning purposes).

cc: @stuartarchibald @guilhermeleobas

**Comment by czgdp1807** [comment]
Hi. So, I did some more investiagtion and came up with the following diff. Basically I used the fact that if print is able to handle dynamic strings (i.e., those whose value is only determined at runtime), then `ValueError` (or for that matter any exception) should be able to handle dynamic strings as well. So, I used the string handling logic from print lowering and called `PyErr_Format` (in `pythonapi.py`). Now the point is the exception doesn't get raised. Instead it produces the LLVM instruction as string in the error message. Is there anyway to make `pyapi.raise_nonconst_exception(exc_arg)` effective (it doesn't do anything). @stuartarchibald Would love to know your thoughts on this. Thanks.

**Diff**

```diff
diff --git a/numba/core/callconv.py b/numba/core/callconv.py
index b3fa6cbbd..6974c08c9 100644
--- a/numba/core/callconv.py
+++ b/numba/core/callconv.py
@@ -10,6 +10,7 @@ from llvmlite import ir
 
 from numba.core import types, cgutils
 from numba.core.base import PYOBJECT, GENERIC_POINTER
+from numba.core.ir import Var
 
 
 TryStatus = namedtuple('TryStatus', ['in_try', 'excinfo'])
@@ -396,6 +397,47 @@ class CPUCallConv(BaseCallConv):
             # Return from the current function
             self._return_errcode_raw(builder, RETCODE_USEREXC, mark_exc=True)
 
+    def set_dynamic_user_exc(self, builder, exc, exc_arg, loc=None,
+                             func_name=None):
+        if not issubclass(exc, BaseException):
+            raise TypeError("exc should exception class, got %r"
+                            % (exc,))
+
+        pyapi = self.context.get_python_api(builder)
+        # Build excinfo struct
+        if loc is not None:
+            fname = loc._raw_function_name()
+            if fname is None:
+                # could be exec(<string>) or REPL, try func_name
+                fname = func_name
+
+            locinfo = (fname, loc.filename, loc.line)
+            if None in locinfo:
+                locinfo = None
+        else:
+            locinfo = None
+
+        pyapi.print_object(exc_arg)
+        pyapi.raise_nonconst_exception(exc_arg)
+        exc = (exc, (exc_arg,), locinfo)
+        struct_gv = pyapi.serialize_object(exc)
+        excptr = self._get_excinfo_argument(builder.function)
+        builder.store(struct_gv, excptr)
+
+    def return_non_const_user_exc(self, builder, exc, exc_args, loc=None,
+                                  func_name=None):
+        try_info = getattr(builder, '_in_try_block', False)
+        self.set_dynamic_user_exc(builder, exc, exc_args,
+                                  loc=loc, func_name=func_name)
+        trystatus = self.check_try_status(builder)
+        if try_info:
+            # This is a hack for old-style impl.
+            # We will branch directly to the exception handler.
+            builder.branch(try_info['target'])
+        else:
+            # Return from the current function
+            self._return_errcode_raw(builder, RETCODE_USEREXC, mark_exc=True)
+
     def _get_try_state(self, builder):
         try:
             return builder.__eh_try_state
diff --git a/numba/core/consts.py b/numba/core/consts.py
index d062b3208..d65dac5ab 100644
--- a/numba/core/consts.py
+++ b/numba/core/consts.py
@@ -93,8 +93,17 @@ class ConstantInference(object):
         _slice = func in (slice,)
         _exc = isinstance(func, type) and issubclass(func, BaseException)
         if _slice or _exc:
-            args = [self.infer_constant(a.name, loc=expr.loc) for a in
-                    expr.args]
+            args = []
+            for a in expr.args:
+                new_a = None
+                try:
+                    new_a = self.infer_constant(a.name, loc=expr.loc)
+                except ConstantInferenceError as cie:
+                    if _exc:
+                        new_a = a
+                    else:
+                        raise cie
+                args.append(new_a)
             if _slice:
                 return func(*args)
             elif _exc:
diff --git a/numba/core/lowering.py b/numba/core/lowering.py
index f4913437a..e557de595 100644
--- a/numba/core/lowering.py
+++ b/numba/core/lowering.py
@@ -166,6 +166,12 @@ class BaseLower(object):
         Called after lowering a block.
         """
 
+    def return_non_const_exception(self, exc_class, exc_args, loc=None):
+        self.call_conv.return_non_const_user_exc(
+            self.builder, exc_class, exc_args,
+            loc=loc, func_name=self.func_ir.func_id.func_name,
+        )
+
     def return_exception(self, exc_class, exc_args=None, loc=None):
         """Propagate exception to the caller.
         """
@@ -632,7 +638,21 @@ class Lower(BaseLower):
             # Reraise
             self.return_exception(None, loc=self.loc)
         else:
-            self.return_exception(inst.exc_class, inst.exc_args, loc=self.loc)
+            exc_args = inst.exc_args
+            if (isinstance(exc_args, tuple) and
+                len(exc_args) >= 1 and
+                isinstance(exc_args[0], ir.Var)):
+                pyapi = self.context.get_python_api(self.builder)
+                env_manager = self.context.get_env_manager(self.builder)
+                _inst = exc_args[0]
+                ty = self.typeof(_inst.name)
+                val = self.loadvar(_inst.name)
+                if self.context.enable_nrt:
+                    self.context.nrt.incref(self.builder, ty, val)
+                obj = pyapi.from_native_value(ty, val, env_manager)
+                self.return_non_const_exception(inst.exc_class, obj, loc=self.loc)
+            else:
+                self.return_exception(inst.exc_class, inst.exc_args, loc=self.loc)
 
     def lower_static_try_raise(self, inst):
         if inst.exc_class is None:
@@ -641,6 +661,13 @@ class Lower(BaseLower):
         else:
             self.set_exception(inst.exc_class, inst.exc_args, loc=self.loc)
 
+    def lower_Var(self, ty, value):
+        val = self.loadvar(value.name)
+        oty = self.typeof(value.name)
+        res = self.context.cast(self.builder, val, oty, ty)
+        self.incref(ty, res)
+        return res
+
     def lower_assign(self, ty, inst):
         value = inst.value
         # In nopython mode, closure vars are frozen like globals
@@ -654,11 +681,7 @@ class Lower(BaseLower):
             return self.lower_expr(ty, value)
 
         elif isinstance(value, ir.Var):
-            val = self.loadvar(value.name)
-            oty = self.typeof(value.name)
-            res = self.context.cast(self.builder, val, oty, ty)
-            self.incref(ty, res)
-            return res
+            return self.lower_Var(ty, value)
 
         elif isinstance(value, ir.Arg):
             # Suspend debug info else all the arg repacking ends up being
diff --git a/numba/core/pythonapi.py b/numba/core/pythonapi.py
index 421a491cc..1de9d7352 100644
--- a/numba/core/pythonapi.py
+++ b/numba/core/pythonapi.py
@@ -1176,6 +1176,11 @@ class PythonAPI(object):
         fn = self._get_function(fnty, name="PySys_FormatStdout")
         return self.builder.call(fn, (fmt,) + args)
 
+    def sys_raise_valuerror(self, fmt, *args):
+        fnty = ir.FunctionType(self.pyobj, [self.pyobj, self.cstring], var_arg=True)
+        fn = self._get_function(fnty, name="PyErr_Format")
+        self.builder.call(fn, (self.get_c_object("PyExc_ValueError"), args[0]))
+
     def object_dump(self, obj):
         """
         Dump a Python object on C stderr.  For debugging purposes.
@@ -1304,6 +1309,14 @@ class PythonAPI(object):
         self.sys_write_stdout(fmt, cstr)
         self.decref(strobj)
 
+    def raise_nonconst_exception(self, obj):
+        strobj = self.object_str(obj)
+        cstr = self.string_as_string(strobj)
+        fmt = self.context.insert_const_string(self.module, "%s")
+        ret = self.sys_raise_valuerror(fmt, cstr)
+        self.decref(strobj)
+        return ret
+
     def print_string(self, text):
         fmt = self.context.insert_const_string(self.module, text)
         self.sys_write_stdout(fmt)
diff --git a/numba/core/rewrites/static_raise.py b/numba/core/rewrites/static_raise.py
index 61f7b5742..e8c57e50f 100644
--- a/numba/core/rewrites/static_raise.py
+++ b/numba/core/rewrites/static_raise.py
@@ -1,4 +1,5 @@
 from numba.core import errors, ir
+from numba.core.errors import ConstantInferenceError
 from numba.core.rewrites import register_rewrite, Rewrite
 
 
@@ -43,16 +44,22 @@ class RewriteConstRaises(Rewrite):
         # Detect all raise statements and find which ones can be
         # rewritten
         for inst in block.find_insts((ir.Raise, ir.TryRaise)):
+            const_inference_happened = True
             if inst.exception is None:
                 # re-reraise
                 exc_type, exc_args = None, None
             else:
                 # raise <something> => find the definition site for <something>
-                const = func_ir.infer_constant(inst.exception)
                 loc = inst.exception.loc
-                exc_type, exc_args = self._break_constant(const, loc)
+                try:
+                    const = func_ir.infer_constant(inst.exception)
+                    exc_type, exc_args = self._break_constant(const, loc)
+                except ConstantInferenceError:
+                    exc_type, exc_args = None, None
+                    const_inference_happened = False
             if isinstance(inst, ir.Raise):
-                raises[inst] = exc_type, exc_args
+                if const_inference_happened:
+                    raises[inst] = exc_type, exc_args
             elif isinstance(inst, ir.TryRaise):
                 tryraises[inst] = exc_type, exc_args
             else:
diff --git a/numba/core/typeinfer.py b/numba/core/typeinfer.py
index 678ec3a89..bfd8253b0 100644
--- a/numba/core/typeinfer.py
+++ b/numba/core/typeinfer.py
@@ -1396,6 +1396,8 @@ https://numba.readthedocs.io/en/stable/user/troubleshoot.html#my-code-has-an-unt
             self.typeof_print(inst)
         elif isinstance(inst, ir.StoreMap):
             self.typeof_storemap(inst)
+        elif isinstance(inst, ir.Raise):
+            pass
         elif isinstance(inst, (ir.Jump, ir.Branch, ir.Return, ir.Del)):
             pass
         elif isinstance(inst, (ir.StaticRaise, ir.StaticTryRaise)):

```

**Output**

```bash
Exception in f(): g
Traceback (most recent call last):
  File "../debug/error_msg.py", line 26, in <module>
    f2()
  File "../debug/error_msg.py", line 16, in f2
    raise ValueError(f"Exception in f(): {res}\n")
ValueError: %".190" = call i8* @"PyUnicode_FromKindAndData"(i32 %".185", i8* %".187", i64 %".189")
```

**NOTE**

If I remove the following code from `set_dynamic_user_exc` and then I get segmenation fault,

**Code removed from the above diff**

```python
exc = (exc, (exc_arg,), locinfo)
struct_gv = pyapi.serialize_object(exc)
excptr = self._get_excinfo_argument(builder.function)
builder.store(struct_gv, excptr)
```

**Output**

```bash
Exception in f(): g
zsh: segmentation fault  python ../debug/error_msg.py
```

**Comment by czgdp1807** [comment]
So, me and @guilhermeleobas met and figured out a way to fill `excinfo` struct at runtime. We were getting a lot of pickling errors. So, I continued the investigation today and figured out that there are two steps in raising an exception in Numba,

1. Fill the `excinfo`. Now, the scene is that `excinfo` has three elements, `data`, `length` and `hash`. The `data` here is not just the exception message but a serialised `tuple` of (<ExceptionClass>, <ConstantErrorMessage>, <TheLocation>). So, Numba serialises this tuple via, `pythonapi.serialize_object` and then gives a structure literal (containing the first element as serialised tuple, the length and the SHA1 hash of the serialised tuple) which is stored in `excinfo`.
2. Now, for raising the exception Numba extracts the `data`, `length` and `hash` and sends it to `numba_unpickle` which returns the original tuple after un-pickling. Now this tuple is further sent to `numba_do_raise` which then extracts the <ExceptionClass>, <ConstantErrorMessage> and <TheLocation> and then sets the error object by calling `PyErr_SetObject`, adds the location to traceback.

So, the bottomline of the above analysis is that to support non-constant error messages in exceptions we need to either do the first step at runtime (right now it happens at compile time and probably that's why only constant error messages are allowed). Or, try setting the error object in case of non-constant error messages (`PyErr_SetObject` or `PyErr_SetString` from Python's C-API). Will try to implement both the ideas.

**Comment by guilhermeleobas** [comment]
Not sure if it is relevant here but Python 3.11 is changing the (type, val, tb) exception representation:
https://github.com/python/cpython/issues/89874

**Comment by guilhermeleobas** [comment]
I have a few questions regarding how exceptions are handled in Numba (cc @sklam, @stuartarchibald). 

The exception triple `(exc, val, tb)` is serialized to the LLVM module as a constant string ([ref](https://github.com/numba/numba/blob/b1be2f12c83c01f57fe34fab9a9d77334f9baa1d/numba/core/callconv.py#L380-L383)). Is there any reason to why this step is important? Is there any feature (i.e. cache, object mode, AOT) that requires the exception triple to be serialized to the LLVM module?

By inspecting the LLVM module, the exception triple lifetime is:

- Serialized to the LLVM module as a constant string.
- At runtime, assuming an exception was raised, unpacks the `excinfo` pointer and calls `_helperlib.c::numba_unpickle` to reconstruct the triple as a pyobject.
- Send the triple to `_helperlib.c::numba_do_raise` which reraises the exception.

The code below generates the following wrapper
```python
@njit
def foo(a):
    raise ValueError('test message')
```

<details>
  <summary> Wrapper generated </summary>

```llvm
...

entry.endif.endif.endif:                          ; preds = %entry.endif.endif
  %.64 = call i32 @_ZN8__main__3fooB2v1B42c8tJTIcFHzwl2ILiXkcBV0KBSqPHEky4CKJAEwA_3dE12unicode_type(i8** undef, { i8*, i32, i8* }** nonnull %excinfo, i8* %.29, i64 %.31, i32 %.32, i32 %.33, i64 %.34, i8* %.48, i8* %.20) #2
  %.65 = load { i8*, i32, i8* }*, { i8*, i32, i8* }** %excinfo, align 8
  call void @NRT_decref(i8* %.48)
  switch i32 %.64, label %entry.endif.endif.endif.endif [
    i32 -2, label %entry.endif.endif.endif.if
    i32 0, label %entry.endif.endif.endif.if
  ]

entry.endif.endif.endif.if:                       ; preds = %entry.endif.endif.endif, %entry.endif.endif.endif
  call void @Py_IncRef(i8* nonnull @_Py_NoneStruct)
  ret i8* @_Py_NoneStruct

entry.endif.endif.endif.endif:                    ; preds = %entry.endif.endif.endif
  %.72 = icmp sgt i32 %.64, 0
  br i1 %.72, label %entry.endif.endif.endif.endif.if, label %entry.endif.endif.endif.endif.endif

entry.endif.endif.endif.endif.if:                 ; preds = %entry.endif.endif.endif.endif
  call void @PyErr_Clear()
  %.85 = load { i8*, i32, i8* }, { i8*, i32, i8* }* %.65, align 8
  %.86 = extractvalue { i8*, i32, i8* } %.85, 0
  %.88 = extractvalue { i8*, i32, i8* } %.85, 1
  %.90 = extractvalue { i8*, i32, i8* } %.85, 2
  %.91 = call i8* @numba_unpickle(i8* %.86, i32 %.88, i8* %.90)
  %.92.not = icmp eq i8* %.91, null
  br i1 %.92.not, label %entry.if, label %entry.endif.endif.endif.endif.if.if, !prof !7

entry.endif.endif.endif.endif.endif:              ; preds = %entry.endif.endif.endif.endif
  switch i32 %.64, label %entry.endif.endif.endif.endif.endif.endif.endif [
    i32 -3, label %entry.endif.endif.endif.endif.endif.if
    i32 -1, label %entry.if
  ]

entry.endif.endif.endif.endif.if.if:              ; preds = %entry.endif.endif.endif.endif.if
  call void @numba_do_raise(i8* nonnull %.91)
  br label %entry.if
```

</details>

-----

Unless I am missing something, it seems to be possible to skip the serialization step and use the `excinfo` to store the triple directly. And with that, one could support non-constant messages in an exception.
