### ISSUE TITLE
CUDA: `ptx` attribute fails for device function

### ISSUE THREAD

**Issue by isVoid** [numba/numba#7849]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Min repro:
```python
from numba import cuda

def f(x):
    return x + 3.14

compiled = cuda.jit("float32(float32)", device=True)(f)
print(compiled.ptx)
```

Failure:
```
Traceback (most recent call last):
  File "/home/yhw/dev/numba_explore/cuda_device_get_ptx.py", line 8, in <module>
    print(compiled.ptx)
  File "/home/yhw/dev/numba/numba/cuda/dispatcher.py", line 909, in ptx
    return {sig: overload.ptx for sig, overload in self.overloads.items()}
  File "/home/yhw/dev/numba/numba/cuda/dispatcher.py", line 909, in <dictcomp>
    return {sig: overload.ptx for sig, overload in self.overloads.items()}
AttributeError: 'CompileResult' object has no attribute 'ptx'
```

Expected result (work around, assuming compiled for current device):

Same as following output.
```python
cc = get_current_device().compute_capability
args, return_type = sigutils.normalize_signature("float32(float32)")
lib = compiled.overloads[args].library
ptx = lib.get_asm_str(cc=cc)
```

**Comment by gmarkall** [comment]
This has accidentally survived - getting PTX for decorated device functions was intended to be removed because it had various problems that meant the PTX you got might not be the PTX you expected: https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-the-inspect-ptx-method

I documented the removal of `inspect_ptx()` but missed the `ptx` property. The recommended way to get `ptx` for a device function is to use `compile_ptx` or `compile_ptx_for_current_device` instead, e.g.:

```python
from numba import cuda, float32

def f(x):
    return x + 3.14

ptx, resty = cuda.compile_ptx_for_current_device(f, (float32,),
                                                 device=True)
print(ptx)
```

Does this suit your use cases, or is there a use case I've overlooked here?

**Comment by isVoid** [comment]
Got it. `compute_ptx_*` works for my scenario. I wasn't aware `ptx` attribute is about to be deprecated. Is it still recommended to retrieve ptx for kernels with `ptx` attribute?

**Comment by gmarkall** [comment]
> Got it. `compute_ptx_*` works for my scenario. I wasn't aware `ptx` attribute is about to be deprecated. Is it still recommended to retrieve ptx for kernels with `ptx` attribute?

I think we should instead use `inspect_asm()` which is consistent with the rest of Numba - the `ptx` property is a historical anomaly.
