### ISSUE TITLE
Some random distributions do not accept size=None arguments

### ISSUE THREAD

**Issue by rishi-kulkarni** [numba/numba#7856]
From a discussion in #7690 

Some of numba's random distribution functions cannot handle size=None arguments, despite size=None being the default value for all of these functions. 

```python
import numpy as np
import numba as nb

# this works
@nb.njit
def nb_chi2(df):
    return np.random.chisquare(df)

nb_chi2(2)

# this also works
np.random.chisquare(2)

# this does not work
@nb.njit
def nb_chi2(df, size):
    return np.random.chisquare(df, size)

nb_chi2(2, None)

# while this does
np.random.chisquare(2, None)
```
This means you have to write something like this everywhere if you want to use np.random.chisquare in a jitted function, though you'd hope that numba's dispatch mechanism would be handling this for you. 

```python
if size is None:
    return np.random.chisquare(df)
else:
    return np.random.chisquare(df, size)
```
Trying the above nonfunctioning function gives this error:
```
              Traceback (most recent call last):
                File "/Users/vhaenel/git/numba/numba/core/types/functions.py", line 308, in get_call_type
                  sig = temp.apply(nolitargs, nolitkws)
                File "/Users/vhaenel/git/numba/numba/core/typing/templates.py", line 351, in apply
                  sig = generic(args, kws)
                File "/Users/vhaenel/git/numba/numba/core/typing/templates.py", line 972, in generic
                  result = self._definition_func(self.context, *args, **kws)
                File "/Users/vhaenel/git/numba/numba/core/overload_glue.py", line 37, in stub
                  return body(tyctx)  # noqa: F821
                File "/Users/vhaenel/git/numba/numba/core/overload_glue.py", line 140, in body
                  sig = typing.apply(ol_args, ol_kwargs)
                File "/Users/vhaenel/git/numba/numba/core/typing/templates.py", line 414, in apply
                  sig = typer(*args, **kws)
                File "/Users/vhaenel/git/numba/numba/core/typing/randomdecl.py", line 277, in typer
                  return self.array_typer(size)(a)
                File "/Users/vhaenel/git/numba/numba/core/typing/randomdecl.py", line 63, in typer
                  shape, ndim = normalize_shape(size)
                File "/Users/vhaenel/git/numba/numba/core/typing/randomdecl.py", line 37, in normalize_shape
                  ndim = len(shape)
              TypeError: object of type 'NoneType' has no len()
```

@stuartarchibald points out that the issue is likely in here.

https://github.com/numba/numba/blob/290bcaa63804fb99b1fe238b0f8fe1caf7686899/numba/core/typing/randomdecl.py#L264-L278

My main question is - is it worth just rewriting these functions to use the new API? It'd be quite a project (that I'm happy to chip away at), but would improve the clarity of randomimpl, which currently uses both extension APIs.

**Comment by stuartarchibald** [comment]
@rishi-kulkarni thanks for opening a ticket to track this. Ideally rewriting these functions to use the new APIs (`@overload`/`@intrinsic` etc) would be the way to go. Having a mixture of the two tends to cause problems, particularly when `@glue_typing` is involved (this acts as a conversion shim between the two). If you were interested in contributing in this area by translating the existing implementations to the new API, this would be welcomed. I think it might be a little challenging in places but I think once one of the functions is translated the rest should be able to just follow the same pattern. Many thanks for your help.

**Comment by rishi-kulkarni** [comment]
@stuartarchibald I'll take a crack at it. At first glance, it seems like this issue goes all the way down to the `np.random.random` calls that these distributions use for their randomness, which look harder to change due to Numba's desire to match Numpy's (admittedly legacy) PRNG. 

The easiest (though admittedly not perfectly clean) solution I see is to add an `overload` for `np.random.random` that dispatches to `np.random.random()` in the `size=None` case, at which point fixing the other functions becomes fairly straightforward. Does this sound about right to you, or are there other considerations to keep in mind?

**Comment by stuartarchibald** [comment]
@rishi-kulkarni Many thanks for offering to work on this. I think your assessment is correct, getting the `np.random.random` function as an `@overload` will probably unlock the same for the rest of distribution functions. Foreseeable issues include:
* there may be problems where a `typing_key` is needed for the typer functions and support for this would need to be added to `@overload`.
* a load of the CPython RNG implementation (standard library `random` module) shares the same code, if it makes it easier to debug I suggest duplicating code paths for now and then when it all works we can figure out how to de-duplicate.

Thanks again!
