### ISSUE TITLE
incorrect float64 type assigned

### ISSUE THREAD

**Issue by deus777** [numba/numba#7888]
minimal code to replicate

```
@njit(int32(uint64, uint64))
def func(a, b):

    while 1:
        b = b & ~(1 << 1)
    return -1

a = 0b11111
b = 0b10111111000

print(func(a,b))
```

gives

```
No implementation of function Function(<built-in function and_>) found for signature:
 
 >>> and_(float64, Literal[int](-3))
 
There are 6 candidate implementations:
  - Of which 4 did not match due to:
  Overload of function 'and_': File: <numerous>: Line N/A.
    With argument(s): '(float64, int64)':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'and_': File: unknown: Line unknown.
    With argument(s): '(float64, int64)':
   No match for registered cases:
    * (bool, bool) -> bool
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64

During: typing of intrinsic-call at /Users/vic/Desktop/POKER/VIC_POKER_SRC/v.py (9)

File "v.py", line 9:
def func(a, b):
    <source elided>
    while 1:
        b = b & ~(1 << 1)
```

env

_```
_OS Information__
Platform Name                                 : macOS-10.16-x86_64-i386-64bit
Platform Release                              : 21.3.0
OS Name                                       : Darwin
OS Version                                    : Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64
OS Specific Version                           : 10.16   x86_64
Libc Version                                  : ?

__Python Information__
Python Compiler                               : Clang 10.0.0 
Python Implementation                         : CPython
Python Version                                : 3.9.7
Python Locale                                 : en_AU.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.54.1
llvmlite Version                              : 0.37.0

__LLVM Information__
LLVM Version                                  : 11.1.0
```

**Comment by esc** [comment]
My assumption is that type-inference is failing for some reason. If you use:

```
from numba import njit, types


@njit(types.int32(types.uint64, types.uint64))
def func(a, b):

    while 1:
        a = b & ~(1 << 1)
    return -1


a = 0b11111
b = 0b10111111000

print(func(a,b))
```

It seems to work "fine":

```
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/issue_7888.py", line 15, in <module>
    print(func(a,b))
SystemError: CPUDispatcher(<function func at 0x7fcead355f70>) returned NULL without setting an error
```

I would assume that that is a different error, though.

**Comment by esc** [comment]
As an alternative workaround, you can force an explicit cast to work around the type-inference issue:

```
from numba import njit, types


@njit(types.int32(types.uint64, types.uint64))
def func(a, b):

    while 1:
        b = types.uint64(b) & types.uint64(~(1 << 1))
    return -1


a = 0b11111
b = 0b10111111000

print(func(a,b))
```

And this should help with cases where you do need to update `b` in place.

**Comment by esc** [comment]
Here is the type system debug:

```
In [4]: func.inspect_types()
func (uint64, uint64)
--------------------------------------------------------------------------------
# File: /Users/vhaenel/git/numba/issue_7888.py
# --- LINE 4 ---

@njit(types.int32(types.uint64, types.uint64))

# --- LINE 5 ---

def func(a, b):

# --- LINE 6 ---



    # --- LINE 7 ---

    while 1:

        # --- LINE 8 ---
        # label 0
        #   a = arg(0, name=a)  :: uint64
        #   del a
        #   b = arg(1, name=b)  :: uint64
        #   b.2 = b  :: uint64
        #   del b
        #   jump 2
        # label 2
        #   x = const(int, 2)  :: Literal[int](2)

        x = 1 << 1

        # --- LINE 9 ---
        #   y = unary(fn=<built-in function invert>, value=x)  :: int64
        #   del x

        y = ~x

        # --- LINE 10 ---
        #   $14load_global.4 = global(types: <module 'numba.core.types' from '/Users/vhaenel/git/numba/numba/core/types/__init__.py'>)  :: Module(<module 'numba.core.types' from '/Users/vhaenel/git/numba/numba/core/types/__init__.py'>)
        #   $16load_method.5 = getattr(value=$14load_global.4, attr=uint64)  :: class(uint64)
        #   del $14load_global.4
        #   $20call_method.7 = call $16load_method.5(y, func=$16load_method.5, args=[Var(y, issue_7888.py:9)], kws=(), vararg=None, target=None)  :: (int64,) -> uint64
        #   del y
        #   del $16load_method.5
        #   $22binary_and.8 = b.2 & $20call_method.7  :: uint64
        #   del $20call_method.7
        #   b.1 = $22binary_and.8  :: uint64
        #   del $22binary_and.8
        #   b.2 = b.1  :: uint64
        #   del b.1
        #   jump 2

        b = b & types.uint64(y)

    # --- LINE 11 ---

    return -1


================================================================================
```

**Comment by esc** [comment]
So, I'm not sure this is even a bug or if we can do anything about this.

**Comment by esc** [comment]
If you type the `1` as a `uint64` from the onset, then typing does seem to work correctly also:

```
from numba import njit, types


@njit(types.int32(types.uint64, types.uint64))
def func(a, b):

    while 1:
        one = types.uint64(1)
        b = b & ~(one << one)
    return -1


a = 0b11111
b = 0b10111111000

print(func(a,b))
```

**Comment by deus777** [comment]
there is actually a variable in the << operator. the actual code is  1<< t. 
but it generates a float type either way.

I had to resort to forcing the types. the float propagated through the rest of the code. was a bit confused with float errors popping up in completely unrelated code when no floats or doubles are used anywhere. I eventually tracked it down to this one liner. If you pull the while loop out it generates a completely different error
could be a mac related problem?

**Comment by esc** [comment]
My guess is that this is the result of the type-inference seeing the binary `and` for a signed and unsigned int during the type-inference algorithm. IIRC type unification kicks in and the only type to hold the potential result of a binary between an int `and` uint is a float.

**Comment by stuartarchibald** [comment]
```
SystemError: CPUDispatcher(<function func at 0x7fcead355f70>) returned NULL without setting an error
```
the infinite while loop is undefined behaviour.

The reason the OP fails to type is that `b & ~(1 << 1)` ends up as an `int64` on the first propagation of types, and to get a type for the `phi(b)` (phi of b-in-loop and b-the-arg) that `int64` (b-in-loop) has to unify with the specified `uint64`(b-the-arg) and that triggers the type to be `float64`. Running with env var `NUMBA_DEBUG_TYPEINFER=1` will show this.

**Comment by deus777** [comment]
this is minimal code, I have removed everything that still allowed the
problem to materialise.
the problem with this casting to float is that it propagated back into the
rest of the program causing errors, leaving me scratching my head as to
where it was coming from given there are no floats or doubles anywhere.

seems a strange choice to go via float from int64 to uint64.

**Comment by stuartarchibald** [comment]
> seems a strange choice to go via float from int64 to uint64.

IIRC it comes from NumPy:
```
In [11]: import numpy as np

In [12]: np.common_type(np.int64(1), np.uint64(1))
Out[12]: numpy.float64
```
at present Numba doesn't differentiate between CPython type derived scalars and NumPy type derived scalars (it has been discussed as an area to explore in the future), were this the case it would potentially be possible to restrict the scope of this casting rule.
