### ISSUE TITLE
`cfunc` unable to compile UDF with record dtype that accesses a record attribute

### ISSUE THREAD

**Issue by eriknw** [numba/numba#7896]
## Reporting a bug

I want to use numba to compile functions that operate on custom numpy dtypes (including record dtypes) to use with `cffi`.  To do this, I use `numba.cfunc` that takes in pointers ofthe output and input arguments.

Here is a working example that doesn't access a record attribute:
```python
import numba
import numpy as np

record_dtype = np.dtype([("x", np.float64), ("y", np.float64)], align=True)
numba_dtype = numba.typeof(record_dtype)
sample = np.zeros(1, dtype=record_dtype)[0]

##############
# This works #
##############

@numba.njit
def identity(val):
    return val

assert identity(sample) == sample

wrapper_signature = numba.types.void(
    numba.types.CPointer(numba_dtype),
    numba.types.CPointer(numba_dtype),
)

@numba.cfunc(wrapper_signature, nopython=True)
def wrapper(result_ptr, val_ptr):
    result_ptr[0] = identity(val_ptr[0])
```

This fails:
```python
@numba.njit
def get0(val):
    return val[0]

assert get0(sample) == sample[0]

wrapper_signature = numba.types.void(
    numba.types.CPointer(numba.types.float64),
    numba.types.CPointer(numba_dtype),
)

@numba.cfunc(wrapper_signature, nopython=True)  # <-- fails here
def wrapper(result_ptr, val_ptr):
    result_ptr[0] = get0(val_ptr[0])
```
and this fails:
```python
@numba.njit
def getx(val):
    return val["x"]

assert getx(sample) == sample["x"]

wrapper_signature = numba.types.void(
    numba.types.CPointer(numba.types.float64),
    numba.types.CPointer(numba_dtype),
)

@numba.cfunc(wrapper_signature, nopython=True)  # <-- fails here
def wrapper(result_ptr, val_ptr):
    result_ptr[0] = getx(val_ptr[0])
```
Here is a traceback:
```python-traceback
Traceback (most recent call last):
  File "/home/erik/git/grblas/run8.py", line 44, in <module>
    def wrapper(result_ptr, val_ptr):
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/decorators.py", line 282, in wrapper
    res.compile()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/ccallback.py", line 67, in compile
    cres = self._compile_uncached()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/ccallback.py", line 81, in _compile_uncached
    return self._compiler.compile(sig.args, sig.return_type)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/dispatcher.py", line 129, in compile
    raise retval
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 476, in _compile_core
    raise e
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 353, in run
    raise patched_exception
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/typed_passes.py", line 105, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/typed_passes.py", line 83, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/typeinfer.py", line 1086, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:

 >>> getitem(dtype(Record(x[type=float64;offset=0],y[type=float64;offset=8];16;True)), Literal[int](0))

There are 22 candidate implementations:
  - Of which 22 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(dtype(Record(x[type=float64;offset=0],y[type=float64;offset=8];16;True)), int64)':
   No match.

During: typing of intrinsic-call at /home/erik/git/grblas/run8.py (34)
During: typing of static-get-item at /home/erik/git/grblas/run8.py (34)

File "run8.py", line 34:
def get0(val):
    return val[0]
    ^

During: resolving callee type: type(CPUDispatcher(<function get0 at 0x7f8c300fbd30>))
During: typing of call at /home/erik/git/grblas/run8.py (45)

During: resolving callee type: type(CPUDispatcher(<function get0 at 0x7f8c300fbd30>))
During: typing of call at /home/erik/git/grblas/run8.py (45)


File "run8.py", line 45:
def wrapper(result_ptr, val_ptr):
    result_ptr[0] = get0(val_ptr[0])
    ^
```
And I'm curious: what's the difference between `numba_dtype` and `numba_dtype.dtype`?  I get different errors when I use `numba_dtype.dtype` above.
```python
In [4]: numba_dtype
Out[4]: dtype(Record(x[type=float64;offset=0],y[type=float64;offset=8];16;True))

In [5]: numba_dtype.dtype
Out[5]: Record(x[type=float64;offset=0],y[type=float64;offset=8];16;True)
```

**Comment by eriknw** [comment]
Let me also explain why I'm asking about the difference between `numba_dtype` and `numba_dtype.dtype` in the above example.

Given
```python
record_dtype = np.dtype([("x", np.float64), ("y", np.float64)], align=True)
numba_dtype = numba.typeof(record_dtype)
sample = np.zeros(1, dtype=record_dtype)[0]

@numba.njit
def identity(val):
    return val
```
we get
```python
In [2]: assert identity(sample) == sample

In [3]: list(identity.overloads)
Out[3]: [(Record(x[type=float64;offset=0],y[type=float64;offset=8];16;True),)]
```
so the dtype in the signature here used `numba_dtype.dtype`.

If instead we do
```python
wrapper_signature = numba.types.void(
    numba.types.CPointer(numba_dtype),
    numba.types.CPointer(numba_dtype),
)

@numba.cfunc(wrapper_signature, nopython=True)
def wrapper(result_ptr, val_ptr):
    result_ptr[0] = identity(val_ptr[0])
```
we get
```python
In [2]: list(identity.overloads)
Out[2]: [(dtype(Record(x[type=float64;offset=0],y[type=float64;offset=8];16;True)),)]
```
so the dtype here used `numba_dtype`, not `numba_dtype.dtype`.

If we instead used `numba_dtype.dtype` in the wrapper signature:
```python
wrapper_signature = numba.types.void(
    numba.types.CPointer(numba_dtype.dtype),
    numba.types.CPointer(numba_dtype.dtype),
)

@numba.cfunc(wrapper_signature, nopython=True)
def wrapper(result_ptr, val_ptr):
    result_ptr[0] = identity(val_ptr[0])
```
We get the following error:
```python-traceback
Traceback (most recent call last):
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/errors.py", line 823, in new_error_context
    yield
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 293, in lower_block
    self.lower_inst(inst)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 438, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 624, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 1159, in lower_expr
    res = self.lower_call(resty, expr)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 889, in lower_call
    res = self._lower_call_normal(fnty, expr, signature)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 1130, in _lower_call_normal
    res = impl(self.builder, argvals, self.loc)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/base.py", line 1201, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/base.py", line 1231, in wrapper
    return fn(*args, **kwargs)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/imputils.py", line 195, in imp
    status, retval = context.call_conv.call_function(
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/callconv.py", line 581, in call_function
    code = builder.call(callee, realargs, attrs=_attrs)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/llvmlite/ir/builder.py", line 880, in call
    inst = instructions.CallInstr(self.block, fn, args, name=name,
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/llvmlite/ir/instructions.py", line 92, in __init__
    raise TypeError(msg)
TypeError: Type of #3 arg mismatch: [16 x i8]* != [16 x i8]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/erik/git/grblas/run8.py", line 24, in <module>
    def wrapper(result_ptr, val_ptr):
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/decorators.py", line 282, in wrapper
    res.compile()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/ccallback.py", line 67, in compile
    cres = self._compile_uncached()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/ccallback.py", line 81, in _compile_uncached
    return self._compiler.compile(sig.args, sig.return_type)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 693, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 429, in compile_extra
    return self._compile_bytecode()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 497, in _compile_bytecode
    return self._compile_core()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 476, in _compile_core
    raise e
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler.py", line 463, in _compile_core
    pm.run(self.state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 353, in run
    raise patched_exception
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/typed_passes.py", line 394, in run_pass
    lower.lower()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 196, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 250, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 279, in lower_function_body
    self.lower_block(block)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/lowering.py", line 293, in lower_block
    self.lower_inst(inst)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/erik/miniconda3/envs/grblas/lib/python3.9/site-packages/numba/core/errors.py", line 837, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
Type of #3 arg mismatch: [16 x i8]* != [16 x i8]

File "run8.py", line 25:
def wrapper(result_ptr, val_ptr):
    result_ptr[0] = identity(val_ptr[0])
    ^

During: lowering "$10call_function.4 = call $2load_global.0($8binary_subscr.3, func=$2load_global.0, args=[Var($8binary_subscr.3, run8.py:25)], kws=(), vararg=None, target=None)" at /home/erik/git/grblas/run8.py (25)
```
Which dtype should we use when creating the signature?

**Comment by eriknw** [comment]
Alright, I think I stumbled upon a workaround.  It works if I wrap the pointers in `numba.carray`.  Note that the below workflow works fine _without_ `carray` when using builtin types.

Here's a working example of a function that was failing above:
```python
import numba
import numpy as np
from numba import carray

record_dtype = np.dtype([("x", np.float64), ("y", np.float64)], align=True)
numba_dtype = numba.typeof(record_dtype)

@numba.njit
def getx(val):
    return val["x"]

wrapper_signature = numba.types.void(
    numba.types.CPointer(numba.types.float64),
    numba.types.CPointer(numba_dtype.dtype),  # Note `.dtype` here!
)

@numba.cfunc(wrapper_signature, nopython=True)
def wrapper(result_ptr, val_ptr):
    result = numba.carray(result_ptr, 1)
    val = numba.carray(val_ptr, 1)
    result[0] = getx(val[0])
```

**Comment by sklam** [comment]
I still need to check why without the `carray` call it is producing the error `Type of #3 arg mismatch: [16 x i8]* != [16 x i8]`
