### ISSUE TITLE
Error importing numba (I think as part of importing numpy)

### ISSUE THREAD

**Issue by JamesIvesProgrammerOfHives** [numba/numba#7899]
Here's the traceback:

Traceback (most recent call last):
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\James Ives\Downloads\wetransfer_benchmark-py_2022-03-10_1254\Benchmark.py", line 22, in <module>
    import librosa
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\librosa\__init__.py", line 211, in <module>
    from . import core
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\librosa\core\__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\librosa\core\convert.py", line 7, in <module>
    from . import notation
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\librosa\core\notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\librosa\util\__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\librosa\util\utils.py", line 10, in <module>
    import numba
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\__init__.py", line 24, in <module>
    from numba.misc.special import (
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\misc\special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typing\__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typing\context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\typeconv.py", line 17, in <module>
    raise ImportError(msg % (url, reportme, str(e), sys.executable))
ImportError: Numba could not be imported.
If you are seeing this message and are undertaking Numba development work, you may need to re-run:

python setup.py build_ext --inplace

(Also, please check the development set up guide https://numba.pydata.org/numba-doc/latest/developer/contributing.html.)

If you are not working on Numba development:

Please report the error message and traceback, along with a minimal reproducer
at: https://github.com/numba/numba/issues/new

If more help is needed please feel free to speak to the Numba core developers
directly at: https://gitter.im/numba/numba

Thanks in advance for your help in improving Numba!

The original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv\__init__.py)'
--------------------------------------------------------------------------------
If possible please include the following in your error report:

sys.executable: C:\Users\James Ives\AppData\Local\Programs\Thonny\python.exe

**Comment by JamesIvesProgrammerOfHives** [comment]
Current version of numba 0.53.1, upgraded to 0.55.1 and it started working.

**Comment by gmarkall** [comment]
This looks like your Python environments are somehow a bit mixed up - if your Python executable is C:\Users\James Ives\AppData\Local\Programs\Thonny\python.exe but the Numba path is C:\Users\James Ives\AppData\Roaming\Python\Python37\site-packages\numba\core\typeconv_init.py then it looks like multiple versions of packages could get found / mixed up.
