### ISSUE TITLE
Numpy allows float indexing of arrays, but Numba does not support it

### ISSUE THREAD

**Issue by seibert** [numba/numba#792]
Numpy allows arrays to be indexed with floats, which are implicitly cast to ints, but Numba does not allow this.  (Python lists, however, do not allow float indexes.)

Example function:
``` python
from numba import jit
@jit('float64(float64[:,:])', nopython=True)
def float_index(a):
    return a[0.0, 0.0]
```
Resulting exception:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "numba/decorators.py", line 171, in wrapper
    disp.compile(sig)
  File "numba/dispatcher.py", line 238, in compile
    flags=flags, locals=locs)
  File "numba/compiler.py", line 151, in compile_extra
    func_attr=func_attr)
  File "numba/compiler.py", line 162, in compile_bytecode
    locals, lifted, func_attr, status)
  File "numba/compiler.py", line 201, in _compile_core
    locals)
  File "numba/compiler.py", line 401, in type_inference_stage
    infer.propagate()
  File "numba/typeinfer.py", line 386, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "numba/typeinfer.py", line 112, in propagate
    constrain(context, typevars)
  File "numba/typeinfer.py", line 249, in __call__
    self.resolve(context, typevars, fnty=self.func)
  File "numba/typeinfer.py", line 242, in resolve
    raise TypingError(msg, loc=self.loc)
numba.typeinfer.TypingError: Undeclared getitem(array(float64, 2d, A, nonconst), (float64 x 2))
File "<stdin>", line 3
```

**Comment by pitrou** [comment]
Closing as we have decided not to support this.
