### ISSUE TITLE
Issue using with objmode with custom output type

### ISSUE THREAD

**Issue by sakshamkumar-byt** [numba/numba#7942]
I am using Numba 0.52.0

When running 
```
@njit
def foo():
    with objmode(y='DataFrameType'):  # annotate return type
        y = pd.DataFrame({'1': [1,2,3]})
    return y
```

I get the error

```
>>> foo()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saksham.kumar/miniconda3/envs/sdc-fourth/lib/python3.7/site-packages/numba/core/dispatcher.py", line 414, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/saksham.kumar/miniconda3/envs/sdc-fourth/lib/python3.7/site-packages/numba/core/dispatcher.py", line 357, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: Handle with contexts)
Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.StaticGetItemConstraint object at 0x7fe516eb9ed0>.
<class 'numba.core.types.abstract._TypeMetaclass'>
During: typing of static-get-item at <stdin> (1)
Enable logging at debug level for details.

File "<stdin>", line 1:
<source missing, REPL/exec in use?>
```

However when running 
```
>>> import pandas as pd
>>> @njit
def foo():
    df = pd.DataFrame({'A': [1.0, 2.0, 3.0, 1.0], 'B': [4, 5, 6, 7]})
    df2 = pd.DataFrame({'C': [1.0, 2.0, 3.0, 1.0], 'D': [4, 5, 6, 7]})
    with objmode(z='intp'):  # annotate return type
        d = pd.concat([df, df2], axis=1)
        z = len(d)
    return z 

>>> foo()
4
```

I am trying to debug but the error doesnt provide much details

**Comment by esc** [comment]
@sakshamkumar-byt thank you for asking about this. Is this something worth asking on the SDC tracker:

https://github.com/IntelPython/sdc

**Comment by ehsantn** [comment]
@sakshamkumar-byt Two issues here: 1) Numba requires full specific data types 2) Numba doesn't support Pandas dataframes.
Here are some examples with Bodo: https://docs.bodo.ai/2022.2/objmode/

**Comment by stuartarchibald** [comment]
The specific data type required in `objectmode` return type annotations can be found by using Numba's `numba.typeof` function. Borrowing a minimal `pandas.Series`-like object from `numba.tests.pdlike_usecase`, this sort of thing should work:

```python
from numba import njit, typeof, objmode
import numpy as np
import pandas as pd
from numba.tests.pdlike_usecase import Series, Index

# Pandas-like objects
idx = Index(np.arange(4))
series1 = Series(np.arange(4), idx)
series2 = Series(np.arange(-4, 0), idx)

# Find the Numba type of the Series instance, the
# pure_python_function below return this type. The
# reference to this type must be in globals or freevars
# to the JIT function, hence calling this here.
objmode_return_type = typeof(series1)

def pure_python_function(a, b):
    print("This is pure python")
    return Series(a._values + b._values, a._index)

@njit
def foo(x, y):
    with objmode(ret = objmode_return_type):
        ret = pure_python_function(x, y)
    return ret

print(foo(series1, series2))
```

Am going to close this as there's a couple of examples of how to do this presented.
