### ISSUE TITLE
Support loading dispatcher metadata from cached functions

### ISSUE THREAD

**Issue by njriasan** [numba/numba#7960]
## Feature request

I would like to look at the dispatcher metadata information on a cached function. However, when loading from cache this data isn't written to the cache, so functions that access the metadata fail when loading from cache succeeds. Here is a reproducer:

```python3
import numba
import numpy as np

@numba.njit(cache=True, parallel=True)
def g(A, n):
    B = A + n
    return B

g(np.ones(4), 10)
g.parallel_diagnostics()
```

The first time this runs successfully, but the output when loading from cache is:
```python3
Traceback (most recent call last):
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/test_cache.py", line 10, in <module>
    print(g.parallel_diagnostics())
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 1027, in parallel_diagnostics
    [dump(sig) for sig in self.signatures]
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 1027, in <listcomp>
    [dump(sig) for sig in self.signatures]
  File "/Users/nicholasriasanovsky/Documents/bodo/nick-numba/numba/core/dispatcher.py", line 1019, in dump
    pfdiag = ol.metadata.get('parfor_diagnostics', None)
AttributeError: 'NoneType' object has no attribute 'get'
```
Any feedback you have on the best way to go about this would be greatly appreciated.

**Comment by njriasan** [comment]
Summary from the meeting discussion. The metadata serves a general "trash can" of information that anyone can write to. The proposal is to let people contribute information that must/should be cached to a new "cached_metadata" field that will be easier to manage.

**Comment by benwilliamgraham** [comment]
If this were to be implemented, where would be a good place to put the cached metadata?

**Comment by stuartarchibald** [comment]
> If this were to be implemented, where would be a good place to put the cached metadata?

There's probably two parts to this:

1. Where and how to expose such a cache to users of Numba

I'm not sure if it's necessary to differentiate between cacheable and uncacheable metadata from the point of view of the user. I imagine users will just want to know what the data is, whether it's cached or not probably doesn't matter? Or is there some specific case where knowing this is useful? To this effect I'm wondering if the existing `get_metadata` on the dispatcher should retrieve this, however an issue arises through reuse of this method in that it already addresses the `metadata` dictionary on a compile result object and addressing two dictionaries will potentially lead to problems with duplicated keys. I think this means there either has to be a new method e.g. `get_cached_metadata()`, or a kwarg e.g. `get_metadata(cached=True)` to the method that would make it possible to differentiate between the two dictionaries, or some API added to make it clear whether metadata should be cached or not at the point of addition this permitting the hiding of the implementation details for addition/retrieval. Alternatively, the idea proposed in the public meeting by @sklam where the keys in the current `metadata` dictionary have a "cacheable" flag, should allow similar. This potentially needs a short discussion at the next public meeting.

2. Where to actually hold a reference to the cached metadata.

Assuming that this cached metadata is implemented as a new dictionary, it probably needs adding to the `numba.core.compiler.CompileResult`, with appropriate updates made to the `_reduce` and `_rebuild` methods.

**Comment by stuartarchibald** [comment]
Following on from a bit of discussion at today's public meeting, most of 1. above was me forgetting that the API doesn't accept a key into the metadata, it just retrieves the whole thing. It's therefore probably fine to just have a `get_cached_metadata` cf. `get_metadata` on the dispatcher object.
