### ISSUE TITLE
vectorized ufunc doesn't support default arguments

### ISSUE THREAD

**Issue by auderson** [numba/numba#7983]
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
_norm_pdf_C = np.sqrt(2 * np.pi)


@numba.vectorize
def norm_pdf(x, loc=0, scale=1):
    return np.exp(-((x - loc) / scale) ** 2 * 0.5) / _norm_pdf_C / scale

norm_pdf(np.arange(10))
```
```
Traceback (most recent call last):
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-a8ed1afc0938>", line 1, in <cell line: 1>
    norm_pdf(np.arange(10))
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/numba/np/ufunc/dufunc.py", line 184, in _compile_for_args
    assert (args_len == nin) or (args_len == nin + self.ufunc.nout)
AssertionError
```
If we precompile it
```python
@numba.vectorize(['float64(float64, int64, int64)'])
def norm_pdf(x, loc=0, scale=1):
    return np.exp(-((x - loc) / scale) ** 2 * 0.5) / _norm_pdf_C / scale

norm_pdf(np.arange(10))
```
```
Traceback (most recent call last):
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-25-a8ed1afc0938>", line 1, in <cell line: 1>
    norm_pdf(np.arange(10))
TypeError: norm_pdf() takes from 3 to 4 positional arguments but 1 were given
```

**Comment by guilhermeleobas** [comment]
Thanks for the report, @auderson. I've marked this issue as a feature request. 

Related to: https://github.com/numba/numba/issues/6954
