### ISSUE TITLE
Parallel fails when using .real and .imag attributes with numpy functions

### ISSUE THREAD

**Issue by cdfredrick** [numba/numba#8012]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```
import numpy as np
from numba import njit

@njit(parallel=True)
def fails(z):
    return np.sum(z.real**2 + z.imag**2)

@njit(parallel=False)
def works(z):
    return np.sum(z.real**2 + z.imag**2)

@njit(parallel=True) 
def also_works(z):
    return np.sum(np.real(z)**2 + np.imag(z)**2)

n = 10
z = np.arange(n) + 1j*np.arange(n)
print(works(z))
print(also_works(z))
print(fails(z)) # this one throws an error
```

`parallel=True` fails when sending values derived from `.real` and `.imag` array attribute to a numpy reduction or math function. The example given here uses `np.sum()`, but other functions also show the same error (`np.prod`, `np.min`, `np.max`, `np.argmin`, `np.argmax`, `np.mean`, `np.var`, and `np.std`). Using `np.real()` and `np.imag()` to access the real and imaginary components, instead of `.real` and `.imag` array attributes, works as expected.

**Comment by czgdp1807** [comment]
I get the following error. Looking into it.

```python
Traceback (most recent call last):
  File "../debug.py", line 407, in <module>
    test_parallel()
  File "../debug.py", line 405, in test_parallel
    print(fails(z)) # this one throws an error
  File "/Users/czgdp1807/numba_project/numba/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/Users/czgdp1807/numba_project/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/czgdp1807/numba_project/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/czgdp1807/numba_project/numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/Users/czgdp1807/numba_project/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/czgdp1807/numba_project/numba/numba/core/dispatcher.py", line 157, in _compile_core
    pipeline_class=self.pipeline_class)
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler_machinery.py", line 353, in run
    raise patched_exception
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler_machinery.py", line 341, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler_machinery.py", line 296, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/czgdp1807/numba_project/numba/numba/core/compiler_machinery.py", line 269, in check
    mangled = func(compiler_state)
  File "/Users/czgdp1807/numba_project/numba/numba/core/typed_passes.py", line 306, in run_pass
    parfor_pass.run()
  File "/Users/czgdp1807/numba_project/numba/numba/parfors/parfor.py", line 2877, in run
    self.array_analysis.run(self.func_ir.blocks)
  File "/Users/czgdp1807/numba_project/numba/numba/parfors/array_analysis.py", line 1178, in run
    self._run_on_blocks(topo_order, blocks, cfg, init_equiv_set)
  File "/Users/czgdp1807/numba_project/numba/numba/parfors/array_analysis.py", line 1199, in _run_on_blocks
    cfg, block, label, scope, init_equiv_set
  File "/Users/czgdp1807/numba_project/numba/numba/parfors/array_analysis.py", line 1274, in _determine_transform
    label, scope, equiv_set, inst, redefined
  File "/Users/czgdp1807/numba_project/numba/numba/parfors/array_analysis.py", line 1395, in _analyze_inst
    equiv_set, lhs, typ.ndim, shape, post
  File "/Users/czgdp1807/numba_project/numba/numba/parfors/array_analysis.py", line 3192, in _gen_shape_call
    typ = self.typemap[shape[i].name]
KeyError: "Failed in nopython mode pipeline (step: convert to parfors)\n'$8load_attr.3_size0.112'"
```

**Comment by czgdp1807** [comment]
I noticed that if you deal with only `.real` or `.imag` and don't do any operation with them (like raising to a power) then no error is thrown,

```
def test_parallel():

    @njit(parallel=True)
    def fails(z):
        return np.sum(z.real)

    n = 10
    z = np.arange(n) + 1j*np.arange(n)
    print(fails(z)) # this one throws an error

test_parallel()
```

**Comment by czgdp1807** [comment]
I see. Nice. The fix was easier than I thought. Thanks for sharing the logic behind it.
