### ISSUE TITLE
When dict value_type is namedtuple, cannot set item for the dict

### ISSUE THREAD

**Issue by dlee992** [numba/numba#8026]
```
from collections import namedtuple

from numba import njit
from numba.core import types
from numba.typed.typeddict import Dict

def test_misc():
        @njit
        def use_tuple_dict(d):
            return d

        Node = namedtuple("Node", ["ID", "Name"])
        node1 = Node("1", "abc")
        dct = Dict.empty(
            key_type  =types.unicode_type, 
            value_type=types.NamedTuple(
                (types.unicode_type, types.unicode_type), 
                Node)
        )
        dct["1"] = node1
        pv = use_tuple_dict.py_func(dct)
        jv = use_tuple_dict(dct)
        assert pv == jv
```
And an Error was reported:
```
Traceback (most recent call last):
  File "/Users/ld/Code/numba/numba/tests/test_unicode_array.py", line 919, in test_misc4
    dct["1"] = node1
  File "/Users/ld/Code/numba/numba/typed/typeddict.py", line 155, in __setitem__
    return _setitem(self, key, value)
  File "/Users/ld/Code/numba/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/ld/Code/numba/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function setitem>) found for signature:
 
 >>> setitem(DictType[unicode_type,Node(unicode_type, unicode_type)]<iv=None>, unicode_type, Node(unicode_type x 2))
 
There are 16 candidate implementations:
  - Of which 14 did not match due to:
  Overload of function 'setitem': File: <numerous>: Line N/A.
    With argument(s): '(DictType[unicode_type,Node(unicode_type, unicode_type)]<iv=None>, unicode_type, Node(unicode_type x 2))':
   No match.
  - Of which 2 did not match due to:
  Overload in function 'impl_setitem': File: numba/typed/dictobject.py: Line 695.
    With argument(s): '(DictType[unicode_type,Node(unicode_type, unicode_type)]<iv=None>, unicode_type, Node(unicode_type x 2))':
   Rejected as the implementation raised a specific error:
     LoweringError: Failed in nopython mode pipeline (step: native lowering)
   
   
   File "../typed/dictobject.py", line 705:
       def impl(d, key, value):
           <source elided>
           castedkey = _cast(key, keyty)
           castedval = _cast(value, valty)
           ^
   
   During: lowering "castedval = call $12load_global.4(value, $16load_deref.6, func=$12load_global.4, args=[Var(value, dictobject.py:704), Var($16load_deref.6, dictobject.py:705)], kws=(), vararg=None, target=None)" at /Users/ld/Code/numba/numba/typed/dictobject.py (705)
  raised from /Users/ld/Code/numba/numba/core/errors.py:837

During: typing of setitem at /Users/ld/Code/numba/numba/typed/typeddict.py (33)

File "../typed/typeddict.py", line 33:
def _setitem(d, key, value):
    d[key] = value
    ^

```
cc @luk-f-a

**Comment by dlee992** [comment]
A related problem I met before: sometimes, I want when numba call `pyval_of` to transform python tuple into numba type. I hope the numba type should be `Tuple(unicode_type, unicode_type)`, but numba actually gives me `UniTuple(unicode_type x 2)` or sth like this. How to control this behavior?

**Comment by luk-f-a** [comment]
I think there's a bug, or at least an inconsistency in the handling of a tuple with two unicode fields. 

```python
import numba as nb
a = nb.typed.Dict.empty(nb.types.unicode_type, nb.types.NamedTuple(nb.types.UniTuple(nb.types.unicode_type, 2), Node))
nb.typeof(a)
Out[51]: DictType[unicode_type,Node(unicode_type, unicode_type)]<iv=None>

Node = namedtuple("Node", ["ID", "Name"])
node1 = Node("1", "abc")
nb.typeof(node1)
Out[55]: Node(unicode_type x 2)
```
Notice the inconsistency between `Node(unicode_type, unicode_type)`  and `Node(unicode_type x 2)`
Even worse
```python
a = nb.typed.Dict.empty(nb.types.unicode_type, nb.types.NamedTuple(nb.typeof(node1), Node))
nb.typeof(a)
Out[70]: DictType[unicode_type,Node(unicode_type, unicode_type)]<iv=None>
```

**Comment by luk-f-a** [comment]
oh, I forgot `NamedUniTuple` existed. This seems like a simple fix, I'll see if I can push a PR.
