### ISSUE TITLE
support for `numba._DUFunc` in `@overload`

### ISSUE THREAD

**Issue by auderson** [numba/numba#8034]
As title. 
Here's an example:
```python
import numba
import numpy as np
from numba import njit, vectorize
from numba.extending import overload

@vectorize(["float64(float64)"])
def vf_eager(a):
    return a + 1


def vf(a):
    return a + 1


@overload(vf)
def vf_overload(a):
    return vf_eager


@njit
def f(a):
    return vf(a)


arr = np.arange(10.0)

f(arr)
```

```
Traceback (most recent call last):
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3361, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-f09a2fd81d0d>", line 27, in <cell line: 27>
    f(arr)
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function vf at 0x7ff5842c1280>) found for signature:
 
 >>> vf(array(float64, 1d, C))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'vf_overload': File: ../../../../../../Techfin/<ipython-input-2-f09a2fd81d0d>: Line 15.
    With argument(s): '(array(float64, 1d, C))':
   Rejected as the implementation raised a specific error:
     AssertionError: Implementator function returned by `@overload` has an unexpected type.  Got <numba._DUFunc 'vf_eager'>
  raised from /home/auderson/miniconda3/envs/py3.9/lib/python3.9/site-packages/numba/core/typing/templates.py:814
During: resolving callee type: Function(<function vf at 0x7ff5842c1280>)
During: typing of call at <ipython-input-2-f09a2fd81d0d> (22)
File "<ipython-input-2-f09a2fd81d0d>", line 22:
def f(a):
    return vf(a)
    ^

```

**Comment by auderson** [comment]
Looks like this is a workaround:
```python
@overload(vf)
def vf_overload(a):
    def vf_eager_jit(a):
        return vf_eager(a)

    return vf_eager_jit
```
wrap dufunc in a function works.

**Comment by stuartarchibald** [comment]
Thanks for raising this. The implementation function returned by an `@overload` is wrapped by the target's declared `jit` decorator, so it has to be something that such a decorator can consume e.g. a pure python function. This is why the noted workaround works.
https://github.com/numba/numba/blob/0f5953df2a2ee6eea1ac44b974bcd954aae91bc6/numba/core/typing/templates.py#L819-L827
