### ISSUE TITLE
Jit functions with optional shape arguments for creating numpy arrays

### ISSUE THREAD

**Issue by haiiliin** [numba/numba#8062]
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I am implementing a jitted functions with optional shape arguments for creating numpy arrays, when the optional arguments are used to create a numpy array in the shape argument as a tuple, a `TypingError` occurs:

```python
import numba
import numpy as np

@numba.njit
def create_1D_numpy_array_with_tuple_shape(size: int = None):
    if size is None:
        size = 3
    array = np.zeros((size, ))
    print(array)

create_1D_numpy_array_with_tuple_shape()  # Fails
```

But when I create a 1D array and provide an int value to the shape argument, it is fine:

```python
import numba
import numpy as np

@numba.njit
def create_1D_numpy_array_with_int_shape(size: int = None):
    if size is None:
        size = 3
    array = np.zeros(size)
    print(array)

create_1D_numpy_array_with_int_shape()  # Passes
```

When I assign the argument to a temporary variable, it is also fine:

```python
import numba
import numpy as np

@numba.njit
def create_1D_numpy_array_with_temp_tuple_shape(size: int = None):
    temp_size = size if size is not None else 3
    array = np.zeros((temp_size, ))
    print(array)

create_1D_numpy_array_with_temp_tuple_shape()  # Passes
```

The error message for the above example is:

```python
Traceback (most recent call last):
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python39\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-0c27157a3534>", line 1, in <cell line: 1>
    create_1D_numpy_array_with_tuple_shape()
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function zeros>) found for signature:
 
 >>> zeros(UniTuple(OptionalType(int64) x 1))
 
There are 4 candidate implementations:
  - Of which 4 did not match due to:
  Overload in function '_OverloadWrapper._build.<locals>.ol_generated': File: numba\core\overload_glue.py: Line 131.
    With argument(s): '(UniTuple(OptionalType(int64) x 1))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<intrinsic stub>) found for signature:
    
    >>> stub(UniTuple(OptionalType(int64) x 1))
    
   There are 2 candidate implementations:
     - Of which 2 did not match due to:
     Intrinsic of function 'stub': File: numba\core\overload_glue.py: Line 35.
       With argument(s): '(UniTuple(OptionalType(int64) x 1))':
      No match.
   
   During: resolving callee type: Function(<intrinsic stub>)
   During: typing of call at <string> (3)
   
   
   File "<string>", line 3:
   <source missing, REPL/exec in use?>
  raised from C:\Users\Hailin\AppData\Local\Programs\Python\Python39\lib\site-packages\numba\core\typeinfer.py:1086
During: resolving callee type: Function(<built-in function zeros>)
During: typing of call at <ipython-input-5-b6f5eb4992d3> (5)
File "<ipython-input-5-b6f5eb4992d3>", line 5:
def create_1D_numpy_array_with_tuple_shape(size: int = None):
    <source elided>
        size = 3
    array = np.zeros((size, ))  # or array = np.zeros((rows, cols)), also fails
    ^
```

**Comment by apmasell** [comment]
We'll have a discussion about how fixable this is. There may be conflicts where some complex are meant to have optionals inside them. For now, the temporary variable is probably the best solution.
