### ISSUE TITLE
Occasional finalizer exceptions in CUDA target

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#8086]
Sometimes I'm observing:

```
Exception ignored in: <finalize object at 0x7f04086923e0; dead>
Traceback (most recent call last):
  File "/home/gmarkall/mambaforge/envs/numbadev/lib/python3.10/weakref.py", line 591, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 314, in finalizer
    targetctx.remove_user_function(cres.entry_point)
AttributeError: '_Kernel' object has no attribute 'entry_point'
```

I'm not sure if this is related to caching only or potentially a general issue - so far it sometimes comes up when running the caching tests in my branch https://github.com/gmarkall/numba/tree/cuda-caching-2-rebase

**Comment by gmarkall** [comment]
It turns out that this was because kernels loaded from the cache were being created without an `entry_point` property.
