### ISSUE TITLE
`typed.List` is not considered a `types.Sequence` while a reflected list is

### ISSUE THREAD

**Issue by kc611** [numba/numba#8128]
As title, a `typed.List` is not considered a `types.Sequence` while a reflected list is. Might lead to problems if we shift from reflected to typed lists down the line.

**Comment by sklam** [comment]
Good catch. 

https://github.com/numba/numba/blob/86cb2d1160778b521a27272a0cc94955fdc0518e/numba/core/types/containers.py#L612

In fact, it should be a `types.MutableSequence`.

**Comment by sklam** [comment]
@esc, do you remember if there was a reason we chose not to use `MutableSequence`? or was that just we overlooked?

**Comment by esc** [comment]
> > @esc, do you remember if there was a reason we chose not to use `MutableSequence`? or was that just we overlooked?
> 
> No, I don't. I presume I may have copied from `DictType`. I wonder what happens if we simply change that.

To answer that, there is one failure:

```
$ python -m numba.runtests -v numba.tests.test_listobject
======================================================================
FAIL: test_list_setitem_singleton_typing_error_on_item (numba.tests.test_listobject.TestSetitem)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/numba/tests/test_listobject.py", line 583, in test_list_setitem_singleton_typing_error_on_item
    self.assertIn(
AssertionError: 'can only assign an iterable when using a slice with assignment/setitem' not found in 'Failed in nopython mode pipeline (step: native lowering)\n\x1b[33m\x1b[1m\x1b[33m\x1b[1mCannot cast Literal[int](1) to ListType[int32]: i64 1\x1b[0m\n\x1b[0m\x1b[37m\x1b[1mDuring: lowering "l[slice(None, None, None)] = $const22.8" at /Users/vhaenel/git/numba/numba/tests/test_listobject.py (579)\x1b[0m'

----------------------------------------------------------------------
Ran 119 tests in 27.591s
```

```
$ git diff
diff --git i/numba/core/types/containers.py w/numba/core/types/containers.py
index 0930104f25..01848ce2f0 100644
--- i/numba/core/types/containers.py
+++ w/numba/core/types/containers.py
@@ -609,7 +609,7 @@ class SetEntry(Type):
         return self.set_type


-class ListType(IterableType):
+class ListType(MutableSequence):
     """List type
     """
```

**Comment by esc** [comment]
> ```
> $ python -m numba.runtests -v numba.tests.test_listobject
> ...
> ======================================================================
> FAIL: test_list_setitem_singleton_typing_error_on_item (numba.tests.test_listobject.TestSetitem)
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/vhaenel/git/numba/numba/tests/test_listobject.py", line 583, in test_list_setitem_singleton_typing_error_on_item
>     self.assertIn(
> AssertionError: 'can only assign an iterable when using a slice with assignment/setitem' not found in 'Failed in nopython mode pipeline (step: native lowering)\n\x1b[33m\x1b[1m\x1b[33m\x1b[1mCannot cast Literal[int](1) to ListType[int32]: i64 1\x1b[0m\n\x1b[0m\x1b[37m\x1b[1mDuring: lowering "l[slice(None, None, None)] = $const22.8" at /Users/vhaenel/git/numba/numba/tests/test_listobject.py (579)\x1b[0m'
> 
> ----------------------------------------------------------------------
> Ran 119 tests in 27.591s
> ```

So, I think the reason this makes it through to lowering, is because there is a generic Setitem implementation for `MutableSeuence` here:

https://github.com/numba/numba/blob/main/numba/core/typing/collections.py#L54-L66

With the following diff, the test passes again:

```
diff --git i/numba/core/types/containers.py w/numba/core/types/containers.py
index 0930104f25..01848ce2f0 100644
--- i/numba/core/types/containers.py
+++ w/numba/core/types/containers.py
@@ -609,7 +609,7 @@ class SetEntry(Type):
         return self.set_type


-class ListType(IterableType):
+class ListType(MutableSequence):
     """List type
     """

diff --git i/numba/core/typing/collections.py w/numba/core/typing/collections.py
index bb4639a3e7..e0f7997603 100644
--- i/numba/core/typing/collections.py
+++ w/numba/core/typing/collections.py
@@ -51,19 +51,19 @@ class GetItemSequence(AbstractTemplate):
             elif isinstance(idx, types.Integer):
                 return signature(seq.dtype, seq, idx)

-@infer_global(operator.setitem)
-class SetItemSequence(AbstractTemplate):
-    def generic(self, args, kws):
-        seq, idx, value = args
-        if isinstance(seq, types.MutableSequence):
-            idx = normalize_1d_index(idx)
-            if isinstance(idx, types.SliceType):
-                return signature(types.none, seq, idx, seq)
-            elif isinstance(idx, types.Integer):
-                if not self.context.can_convert(value, seq.dtype):
-                    msg = "invalid setitem with value of {} to element of {}"
-                    raise errors.TypingError(msg.format(types.unliteral(value), seq.dtype))
-                return signature(types.none, seq, idx, seq.dtype)
+#@infer_global(operator.setitem)
+#class SetItemSequence(AbstractTemplate):
+#    def generic(self, args, kws):
+#        seq, idx, value = args
+#        if isinstance(seq, types.MutableSequence):
+#            idx = normalize_1d_index(idx)
+#            if isinstance(idx, types.SliceType):
+#                return signature(types.none, seq, idx, seq)
+#            elif isinstance(idx, types.Integer):
+#                if not self.context.can_convert(value, seq.dtype):
+#                    msg = "invalid setitem with value of {} to element of {}"
+#                    raise errors.TypingError(msg.format(types.unliteral(value), seq.dtype))
+#                return signature(types.none, seq, idx, seq.dtype)


 @infer_global(operator.delitem)
```

**Comment by sklam** [comment]
Relates to overload resolution ambiguity problem we are trying solve for array but this will need more design work to solve
