### ISSUE TITLE
Truediv Parfor fails when input array and return value has control flow

### ISSUE THREAD

**Issue by njriasan** [numba/numba#8146]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [X] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Here is a dummy reproducer to show the issue.

```
import numpy as np
import numba

@numba.njit(parallel=True)
def f(arr, flag1, flag2):  # pragma: no cover
    inv = np.arange(arr.size)
    if flag1:
        return inv.astype(np.float64)
    if flag2:
        ret = inv[inv]
    else:
        ret = inv[inv - 1]
    return ret / arr.size

arr = np.arange(100)
print(f(arr, True, False))
```

This outputs:

```python3
func_fnty: Function(<function runtime_broadcast_assert_shapes at 0x1154f9700>)
typs: [array(int64, 1d, C)]
dims: [1] 1
fargs: [Literal[int](1), array(int64, 1d, C)]
Traceback (most recent call last):
  File "/Users/nicholasriasanovsky/Documents/bodo/Bodo/test_numba.py", line 16, in <module>
    print(f(arr, True, False))
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 407, in error_rewrite
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 129, in compile
    raise retval
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typed_passes.py", line 306, in run_pass
    parfor_pass.run()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/parfor.py", line 2864, in run
    self._pre_run()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/parfor.py", line 2856, in _pre_run
    self.array_analysis.run(self.func_ir.blocks)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 1178, in run
    self._run_on_blocks(topo_order, blocks, cfg, init_equiv_set)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 1198, in _run_on_blocks
    pending_transforms = self._determine_transform(
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 1273, in _determine_transform
    pre, post = self._analyze_inst(
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 1311, in _analyze_inst
    result = self._analyze_expr(scope, equiv_set, inst.value, lhs)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 1571, in _analyze_expr
    return guard(fn, scope, equiv_set, expr, lhs)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/ir_utils.py", line 1527, in guard
    return func(*args, **kwargs)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 2183, in _analyze_op_arrayexpr
    return self._analyze_broadcast(
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 3056, in _analyze_broadcast
    return self._insert_runtime_broadcast_call(
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/parfors/array_analysis.py", line 2982, in _insert_runtime_broadcast_call
    func_sig = self.context.resolve_function_type(func_fnty, fargs, {})
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/context.py", line 213, in resolve_function_type
    raise last_exception
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/context.py", line 196, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/context.py", line 248, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/types/functions.py", line 331, in get_call_type
    failures.raise_error()
  File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/types/functions.py", line 227, in raise_error
    raise errors.TypingError(self.format())
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: convert to parfors)
No implementation of function Function(<function runtime_broadcast_assert_shapes at 0x1154f9700>) found for signature:
 
 >>> runtime_broadcast_assert_shapes(Literal[int](1), array(int64, 1d, C))
 
There are 2 candidate implementations:
 - Of which 2 did not match due to:
 Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 159.
   With argument(s): '(int64, array(int64, 1d, C))':
  Rejected as the implementation raised a specific error:
    TypeError: missing a required argument: 'arg1'
      Traceback (most recent call last):
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/types/functions.py", line 308, in get_call_type
          sig = temp.apply(nolitargs, nolitkws)
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/templates.py", line 351, in apply
          sig = generic(args, kws)
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/templates.py", line 614, in generic
          disp, new_args = self._get_impl(args, kws)
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/templates.py", line 713, in _get_impl
          impl, args = self._build_impl(cache_key, args, kws)
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/templates.py", line 824, in _build_impl
          disp_type.get_call_type(self.context, args, kws)
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/types/functions.py", line 541, in get_call_type
          self.dispatcher.get_call_template(args, kws)
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 359, in get_call_template
          pysig, args = self._compiler.fold_argument_types(args, kws)
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/dispatcher.py", line 118, in fold_argument_types
          args = fold_arguments(self.pysig, args, kws,
        File "/Users/nicholasriasanovsky/Documents/bodo/numba/numba/core/typing/templates.py", line 221, in fold_arguments
          ba = pysig.bind(*bind_args, **bind_kws)
        File "/Users/nicholasriasanovsky/mambaforge/envs/DEV/lib/python3.9/inspect.py", line 3050, in bind
          return self._bind(args, kwargs)
        File "/Users/nicholasriasanovsky/mambaforge/envs/DEV/lib/python3.9/inspect.py", line 2965, in _bind
          raise TypeError(msg) from None
      TypeError: missing a required argument: 'arg1'
  raised from /Users/nicholasriasanovsky/mambaforge/envs/DEV/lib/python3.9/inspect.py:2965
```

which occurs because `runtime_broadcast_assert_shapes` tries to run with 1 array. Skipping the `_insert_runtime_broadcast_call` by returning None produces. 

```python3
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
'$62binary_true_divide.3_size0.11'

File "test_numba.py", line 13:
def f(arr, flag1, flag2):  # pragma: no cover
    <source elided>
        ret = inv[inv - 1]
    return ret / arr.size
```
because the parfor uses `$62binary_true_divide.3_size0.11` as an index but it is not defined in the IR.

**Comment by stuartarchibald** [comment]
Thanks for the report. xref: https://github.com/numba/numba/pull/8147#pullrequestreview-1003510313 which has a suggested root cause and fix.

**Comment by adofarsi** [comment]
Dear @stuartarchibald and @sk1p,
I have tested @njriasan 's dummy reproducer code and it still fails with current release of Numba (0.56.4) on both Mac (macOS-13.0.1-x86_64-i386-64bit) and Linux VM (Linux-5.15.0-1018-gcp-x86_64-with-glibc2.35) with output:

```
func_fnty: Function(<function runtime_broadcast_assert_shapes at 0x116ee3040>)
typs: [array(int64, 1d, C)]
dims: [1] 1
fargs: [Literal[int](1), array(int64, 1d, C)]
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
/var/folders/bh/g86lgxvj67x8_qdx30vwmw500000gn/T/ipykernel_44644/293618984.py in <module>
     14 
     15 arr = np.arange(100)
---> 16 print(f(arr, True, False))

~/opt/anaconda3/envs/ado/lib/python3.9/site-packages/numba/core/dispatcher.py in _compile_for_args(self, *args, **kws)
    466                 e.patch_message(msg)
    467 
--> 468             error_rewrite(e, 'typing')
    469         except errors.UnsupportedError as e:
    470             # Something unsupported is present in the user code, add help info

~/opt/anaconda3/envs/ado/lib/python3.9/site-packages/numba/core/dispatcher.py in error_rewrite(e, issue_type)
    407                 raise e
    408             else:
--> 409                 raise e.with_traceback(None)
    410 
    411         argtypes = []

TypingError: Failed in nopython mode pipeline (step: convert to parfors)
No implementation of function Function(<function runtime_broadcast_assert_shapes at 0x116ee3040>) found for signature:
 
 >>> runtime_broadcast_assert_shapes(Literal[int](1), array(int64, 1d, C))
 
There are 2 candidate implementations:
 - Of which 2 did not match due to:
 Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 159.
   With argument(s): '(int64, array(int64, 1d, C))':
  Rejected as the implementation raised a specific error:
    TypeError: missing a required argument: 'arg1'
  raised from /Users/adofarsi/opt/anaconda3/envs/ado/lib/python3.9/inspect.py:2960
```

**Comment by manassharma07** [comment]
I also faced this issue with my code today. So I got led here. I tried the reproducing script posted here and it fails for me too.

**Comment by adofarsi** [comment]
Hi @manassharma07 , I have solved this issue by installing the developer version of Numba, see #8147

**Comment by manassharma07** [comment]
Hi @adofarsi, Thanks a lot. I am checking it out!
