### ISSUE TITLE
Program crashes without error message on set inside Typed List

### ISSUE THREAD

**Issue by cppietime** [numba/numba#8160]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I have use for a 2-D sequence of Sets of varying size, so numpy arrays are not applicable here. I am trying to use `numba.typed.List` instead, as it allows for a reflected inner type, but the following test program crashes without an error message:

```py
import numba

input_set_list = numba.typed.List([numba.typed.List([
    {1, 2, 3} for _ in range(2)
]) for __ in range(2)])
print('Created')
print(input_set_list)
for pisl in input_set_list:
    print(f'{pisl=}')
    for isl in pisl:
        print(f'{isl=}')
        isl.update({9, 8})
```

I would expect this to print out something like:

```
Created
[[{1, 2, 3}, {1, 2, 3}], [{1, 2, 3}, {1, 2, 3}]]
pisl=[{1, 2, 3}, {1, 2, 3}]
isl={1, 2, 3, 9, 8}
isl={1, 2, 3, 9, 8}
pisl=[{1, 2, 3, 9, 8}, {1, 2, 3, 9, 8}]
isl={1, 2, 3, 9, 8}
isl={1, 2, 3, 9, 8}
```

Instead, I see only the following in my console:

```
C:\Users\alpac\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\typed\typedlist.py:83: NumbaPendingDeprecationWarning: ←[1m←[1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected set' found for argument 'item' of function 'impl_append.<locals>.impl'.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
←[1m
File "C:\Users\alpac\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\typed\listobject.py", line 599:←[0m
←[1m
←[1m    def impl(l, item):
←[0m    ←[1m^←[0m←[0m
←[0m←[0m
  l.append(item)
C:\Users\alpac\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\ir_utils.py:2152: NumbaPendingDeprecationWarning: ←[1m
Encountered the use of a type that is scheduled for deprecation: type 'reflected set' found for argument 'item' of function '_append'.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types
←[1m
File "C:\Users\alpac\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\typed\typedlist.py", line 82:←[0m
←[1m@njit
←[1mdef _append(l, item):
←[0m←[1m^←[0m←[0m
←[0m
  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
Created
```

It ends after the "Created" line with no error message or stacktrace, so I do not know what to make of this.
For context, I am trying to JIT compile a function that takes a set of ints, a list of sets of ints, and another set of ints, and reurns the union of the first provided set and all the sets in the list indexed by the members of the final argument. I would be calling this on many lists, so I want to be able to have a list of lists of sets, though only the list of sets would be passed to the JIT function.

**Comment by guilhermeleobas** [comment]
Hi @cppietime. Thanks for the report, I can reproduce the error.

```python
from numba.typed import List

input_set_list = List([
    List([{1, 2, 3}, {1, 2, 3}]) for __ in range(2)
])
print('Created')
print(input_set_list)
for pisl in input_set_list:
    print(f'{pisl=}')
    for isl in pisl:
        print(f'{isl=}')
        isl.update({9, 8})
```

I believe the innermost set (`[1, 2, 3]`) uses the same reference for both objects, which is deallocated when the second print stmt is executed. Below is the gdb stacktrace

```
#0  0x00005555556ac29a in _PyObject_GC_UNTRACK_impl (op=0x7fff2a61b200, lineno=2242, filename=0x5555557bc6d8 "/home/conda/feedstock_root/build_artifacts/python-split_1653669926144/work/Modules/gcmodule.c")
    at /usr/local/src/conda/python-3.9.13/Modules/gcmodule.c:2235
#1  PyObject_GC_UnTrack (op_raw=0x7fff2a61b200) at /usr/local/src/conda/python-3.9.13/Modules/gcmodule.c:2242
#2  set_dealloc (so=0x7fff2a61b200) at /usr/local/src/conda/python-3.9.13/Objects/setobject.c:475
#3  0x00005555556843a0 in _Py_Dealloc (op=<optimized out>) at /usr/local/src/conda/python-3.9.13/Objects/object.c:2203
#4  _Py_DECREF (op=<optimized out>) at /usr/local/src/conda/python-3.9.13/Include/object.h:430
#5  _Py_XDECREF (op=<optimized out>) at /usr/local/src/conda/python-3.9.13/Include/object.h:497
#6  _PyEval_EvalFrameDefault (tstate=<optimized out>, f=<optimized out>, throwflag=<optimized out>) at /usr/local/src/conda/python-3.9.13/Python/ceval.c:1500
#7  0x0000555555691043 in _PyEval_EvalFrame (throwflag=0, f=0x7fff29e18c40, tstate=0x555555910930) at /usr/local/src/conda/python-3.9.13/Include/internal/pycore_ceval.h:40
#8  function_code_fastcall (tstate=0x555555910930, co=<optimized out>, args=<optimized out>, nargs=<optimized out>, globals=0x7ffff77bdcc0) at /usr/local/src/conda/python-3.9.13/Objects/call.c:330
#9  0x00005555556e367f in _PyFunction_Vectorcall (kwnames=0x0, nargsf=<optimized out>, stack=0x7fffffffd1b0, func=0x7fff2a5e74c0) at /usr/local/src/conda/python-3.9.13/Objects/call.c:346
...
```

**Comment by stuartarchibald** [comment]
xref: https://github.com/numba/numba/issues/6644#issuecomment-761180376 is this the same problem?
