### ISSUE TITLE
Failed in object mode pipeline (step: object mode frontend)

### ISSUE THREAD

**Issue by VERISBABY** [numba/numba#8176]
**I run a file using python with tkinter is GUI interface. And have this error:**
```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python310\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Program Files\Python310\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.NumbaNotImplementedError: Failed in object mode pipeline (step: object mode frontend)
Failed in object mode pipeline (step: object mode backend)
<class 'numba.core.ir.StaticRaise'>, <static> raise <class 'AssertionError'>("Unreachable condition reached (op code RERAISE executed)\n-------------------------------------------------------------------------------\n
```

**Comment by guilhermeleobas** [comment]
Hi @VERISBABY, can you share the snippet of code you're trying to execute?

**Comment by stuartarchibald** [comment]
Closing this issue due to lack of information. If more information becomes available please add it and reopen the issue. Thanks.
