### ISSUE TITLE
Pin max numpy version in `setup.py`

### ISSUE THREAD

**Issue by divya-gopinath** [numba/numba#8188]
## Feature request
As of 6/22/22, numpy v1.23 has released. It is possible to install numpy v1.23 alongside numba, though when importing numba, the following error is thrown:

```python
File "/home/divya/external_dependencies/miniconda3/envs/truera-c492f339dfe9d66881580e3ea4cc559e6dae9d7e/lib/python3.9/site-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.22 or less")
```

Can we specify a max numpy version in `install_requires` of numba's `setup.py` file? This way if `numba` is specified in a package list, it will force an installation of numpy that is compatible with numba.

Obviously long term is it best to make sure numba is compatible with the latest numpy, but it would be great to pin a max numpy version during install rather than throwing an error at runtime.

**Comment by esc** [comment]
@divya-gopinath thank you for asking about this. In general we tend to pin NumPy on release branches only. Looking at the most recent release branch `release_0.55`, it seems like this is already setup via `install_requires`(?):

https://github.com/numba/numba/blob/release0.55/setup.py#L361
https://github.com/numba/numba/blob/release0.55/setup.py#L403

So, I am not sure how you ended up in that situation, but the runtime checks are in there in case something does go wrong during installation. 

How did you install NumPy and Numba?

**Comment by esc** [comment]
`pip` can be quite unforgiving, here for example, it is entirely possible to create something with mismatching dependencies:

```
 💣 zsh» pip install numba
Collecting numba
  Downloading numba-0.55.2-cp310-cp310-macosx_10_14_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 2.1 MB/s
Collecting llvmlite<0.39,>=0.38.0rc1
  Downloading llvmlite-0.38.1-cp310-cp310-macosx_10_9_x86_64.whl (25.5 MB)
     |████████████████████████████████| 25.5 MB 973 kB/s
Collecting numpy<1.23,>=1.18
  Downloading numpy-1.22.4-cp310-cp310-macosx_10_15_x86_64.whl (17.7 MB)
     |████████████████████████████████| 17.7 MB 7.8 MB/s
Requirement already satisfied: setuptools in ./miniconda3/envs/issue_8188/lib/python3.10/site-packages (from numba) (61.2.0)
Installing collected packages: numpy, llvmlite, numba
Successfully installed llvmlite-0.38.1 numba-0.55.2 numpy-1.22.4
pip install numba  6.71s user 1.73s system 30% cpu 27.899 total

 💣 zsh» pip install numpy -U
Requirement already satisfied: numpy in ./miniconda3/envs/issue_8188/lib/python3.10/site-packages (1.22.4)
Collecting numpy
  Downloading numpy-1.23.0-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
     |████████████████████████████████| 18.1 MB 4.1 MB/s
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.22.4
    Uninstalling numpy-1.22.4:
      Successfully uninstalled numpy-1.22.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
numba 0.55.2 requires numpy<1.23,>=1.18, but you have numpy 1.23.0 which is incompatible.
Successfully installed numpy-1.23.0

 💣 zsh» python
Python 3.10.4 (main, Mar 31 2022, 03:38:35) [Clang 12.0.0 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
imp>>> import numba
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/site-packages/numba/__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/site-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.22 or less")
ImportError: Numba needs NumPy 1.22 or less

```

**Comment by esc** [comment]
Also, if we instead try this on the command line instead, in an attempt to force numba and numpy 1.23.0, where one would expect a descent error message, instead I get the following:

```
 💣 zsh» pip install numba numpy==1.23.0
Collecting numba
  Using cached numba-0.55.2-cp310-cp310-macosx_10_14_x86_64.whl (2.3 MB)
Collecting numpy==1.23.0
  Using cached numpy-1.23.0-cp310-cp310-macosx_10_9_x86_64.whl (18.1 MB)
Requirement already satisfied: setuptools in ./miniconda3/envs/issue_8188/lib/python3.10/site-packages (from numba) (61.2.0)
Collecting numba
  Downloading numba-0.55.1-cp310-cp310-macosx_10_14_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 2.6 MB/s
  Downloading numba-0.55.0-cp310-cp310-macosx_10_14_x86_64.whl (2.3 MB)
     |████████████████████████████████| 2.3 MB 5.4 MB/s
  Downloading numba-0.51.2.tar.gz (2.1 MB)
     |████████████████████████████████| 2.1 MB 2.6 MB/s
Collecting llvmlite<0.35,>=0.34.0.dev0
  Downloading llvmlite-0.34.0.tar.gz (107 kB)
     |████████████████████████████████| 107 kB 6.5 MB/s
Building wheels for collected packages: numba, llvmlite
  Building wheel for numba (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/esc/miniconda3/envs/issue_8188/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py'"'"'; __file__='"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-wheel-uth07wva
       cwd: /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py", line 354, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py", line 87, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed building wheel for numba
  Running setup.py clean for numba
  ERROR: Command errored out with exit status 1:
   command: /Users/esc/miniconda3/envs/issue_8188/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py'"'"'; __file__='"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8
  Complete output (7 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py", line 354, in <module>
      metadata['ext_modules'] = get_ext_modules()
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/numba_4a981aac0b7b4d1baee6d778fa8249e8/setup.py", line 87, in get_ext_modules
      import numpy.distutils.misc_util as np_misc
  ModuleNotFoundError: No module named 'numpy'
  ----------------------------------------
  ERROR: Failed cleaning build dir for numba
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/esc/miniconda3/envs/issue_8188/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/setup.py'"'"'; __file__='"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-wheel-vl5777kc
       cwd: /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/
  Complete output (26 lines):
  running bdist_wheel
  /Users/esc/miniconda3/envs/issue_8188/bin/python /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 420, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 501, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 966, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 1842, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 191, in <module>
      main()
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 185, in main
      main_posix('osx', '.dylib')
    File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 107, in main_posix
      raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/Users/esc/miniconda3/envs/issue_8188/bin/python' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build numba llvmlite
Installing collected packages: numpy, llvmlite, numba
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/esc/miniconda3/envs/issue_8188/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/setup.py'"'"'; __file__='"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-record-6awn1t4z/install-record.txt --single-version-externally-managed --compile --install-headers /Users/esc/miniconda3/envs/issue_8188/include/python3.10/llvmlite
         cwd: /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/
    Complete output (31 lines):
    running install
    /Users/esc/miniconda3/envs/issue_8188/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    got version from file /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
    running build_ext
    /Users/esc/miniconda3/envs/issue_8188/bin/python /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "/Users/esc/miniconda3/envs/issue_8188/lib/python3.10/subprocess.py", line 1842, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 191, in <module>
        main()
      File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 185, in main
        main_posix('osx', '.dylib')
      File "/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/ffi/build.py", line 107, in main_posix
        raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/Users/esc/miniconda3/envs/issue_8188/bin/python' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/esc/miniconda3/envs/issue_8188/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/setup.py'"'"'; __file__='"'"'/private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-install-lv9rh31u/llvmlite_bcff1d1d5ec44a7d9a7b069b27ed0e66/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/jk/s59wn3zx5g92kvk6t9k74fzr0000gn/T/pip-record-6awn1t4z/install-record.txt --single-version-externally-managed --compile --install-headers /Users/esc/miniconda3/envs/issue_8188/include/python3.10/llvmlite Check the logs for full command output.
pip install numba numpy==1.23.0  9.22s user 2.12s system 79% cpu 14.176 total

```

What I think is happening here, is that `pip` goes and looks for the most recent version of Numba that doesn't constrain NumPy (we only started doing this a while ago) and finds release 0.51.2 -- this however doesn't have a binary wheel since this is Python 3.10 and 0.51.2 predates 3.10 support. And so `pip` will download the source tarball instead, try to compile that and the fail with the output you see above. I am not sure what else we can do to improve the Numba installation user experience for `pip`--- but of there is something we missed, please do let us know, I'd be happy to try.

**Comment by esc** [comment]
Although, perhaps I should add, that if you use the advertised `pip install numba` it will match an appropriate NumPy version, (I presume this is `install_requires` working):

```
 💣 zsh» pip install numba
Collecting numba
  Using cached numba-0.55.2-cp310-cp310-macosx_10_14_x86_64.whl (2.3 MB)
Collecting numpy<1.23,>=1.18
  Using cached numpy-1.22.4-cp310-cp310-macosx_10_15_x86_64.whl (17.7 MB)
Collecting llvmlite<0.39,>=0.38.0rc1
  Using cached llvmlite-0.38.1-cp310-cp310-macosx_10_9_x86_64.whl (25.5 MB)
Requirement already satisfied: setuptools in ./miniconda3/envs/issue_8188/lib/python3.10/site-packages (from numba) (61.2.0)
Installing collected packages: numpy, llvmlite, numba
Successfully installed llvmlite-0.38.1 numba-0.55.2 numpy-1.22.4
pip install numba  5.95s user 1.33s system 91% cpu 7.963 total
```

**Comment by jack-mcivor** [comment]
What is the policy for supported numpy versions? Is it likely that 0.53 will support numpy 1.23?

**Comment by divya-gopinath** [comment]
Ah, this is totally my bad - did not realize that we were pinning a max numpy version in the release branch. Thanks for the quick response here. 

For visibility, I got into this numpy/numba state when installing a package that I created that requires both.

The `install_requires` of my package looks like the following:
```
install_requires=['numpy>=1.20.3', 'scipy', 'scikit-learn', 'pandas', 'tqdm>4.25.0',
                          'packaging>20.9', 'slicer==0.0.7', 'numba', 'cloudpickle']
```

Output when I pip install the package wheel: 
```python
Collecting cloudpickle==1.2.1
  Using cached cloudpickle-1.2.1-py2.py3-none-any.whl (25 kB)
Processing /home/divya/truera_repo/distribution/target/truera-build-dir/bin/model-runner/python/pip-repo/truera_qii/truera_qii-0.40.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl
Collecting pandas
  Using cached pandas-1.4.3-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.7 MB)
Collecting packaging>20.9
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting scikit-learn
  Using cached scikit_learn-1.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (30.8 MB)
Collecting tqdm>4.25.0
  Using cached tqdm-4.64.0-py2.py3-none-any.whl (78 kB)
Collecting slicer==0.0.7
  Using cached slicer-0.0.7-py3-none-any.whl (14 kB)
Collecting scipy
  Using cached scipy-1.8.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.2 MB)
Collecting numba
  Using cached numba-0.55.2-cp39-cp39-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.3 MB)
Collecting numpy>=1.20.3
  Using cached numpy-1.23.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
Collecting pytz>=2020.1
  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)
Collecting python-dateutil>=2.8.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting threadpoolctl>=2.0.0
  Using cached threadpoolctl-3.1.0-py3-none-any.whl (14 kB)
Collecting joblib>=1.0.0
  Using cached joblib-1.1.0-py2.py3-none-any.whl (306 kB)
Requirement already satisfied, skipping upgrade: setuptools in /home/divya/miniconda3/envs/test_conda/lib/python3.9/site-packages (from numba->truera_qii->-r /home/divya/external_data/89ca5cce-6882-4992-b78c-27d588040d9c/models/some_model/condaenv.8dwb0oh3.requirements.txt (line 3)) (61.2.0)
Collecting llvmlite<0.39,>=0.38.0rc1
  Using cached llvmlite-0.38.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: cloudpickle, pytz, six, python-dateutil, numpy, pandas, pyparsing, packaging, threadpoolctl, joblib, scipy, scikit-learn, tqdm, slicer, llvmlite, numba, truera-qii
Successfully installed cloudpickle-1.2.1 joblib-1.1.0 llvmlite-0.38.1 numba-0.55.2 numpy-1.23.0 packaging-21.3 pandas-1.4.3 pyparsing-3.0.9 python-dateutil-2.8.2 pytz-2022.1 scikit-learn-1.1.1 scipy-1.8.1 six-1.16.0 slicer-0.0.7 threadpoolctl-3.1.0 tqdm-4.64.0 truera-qii-0.40.4
```
Note how `numba-0.55.2 numpy-1.23.0` were both installed. Not sure what the issue is here in pip's dependency resolver? I would imagine that when attempting to install `numba==0.55.2` there would be some basic check on numpy as per `numba`'s install_requires.

**Comment by divya-gopinath** [comment]
Poked into this further... the resolution is fine on pip versions 20.3+ or using the 2020 resolver: https://discuss.python.org/t/announcement-pip-20-2-release/4863, but fails on older versions of pip (I was on 20.2.4). 

Closing this out and thanks for the speedy response!

**Comment by esc** [comment]
@divya-gopinath thank you for following up and tracking this down! 👌
