### ISSUE TITLE
`searchsorted` not working with unicode arrays

### ISSUE THREAD

**Issue by stonescw** [numba/numba#8190]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The `np.searchsorted` function does not work with `@njit` when the query array `v` is of unicode dtype. This seems to be because the `np.isnan` function is not implemented for this type. I would like to get this working so that I can use `np.searchsorted` in parallel using `prange` and `@njit(parallel=True)`.

MWE:
```python
# imports
import numpy as np
from numba import njit, prange

# attributes
UNICODE_a = 97
ALPHABET_SIZE = 26

# parameters
n_reference_string = 100
n_query_string = 10
string_length = 32

# create and sort random reference strings
reference_strings_unicode = np.random.choice(
    np.arange(UNICODE_a, UNICODE_a + ALPHABET_SIZE, dtype=np.uint32),
    size=(n_reference_string, string_length),
)
reference_strings = reference_strings_unicode.view(f"<U{string_length}").reshape(-1)
sorted_reference_strings = np.sort(reference_strings)

# create random query strings
query_strings_unicode = np.random.choice(
    np.arange(UNICODE_a, UNICODE_a + ALPHABET_SIZE, dtype=np.uint32),
    size=(n_query_string, string_length),
)
query_strings = query_strings_unicode.view(f"<U{string_length}").reshape(-1)

# JIT-compiled function
@njit
def query(sorted_reference_strings, query_strings):
    return np.searchsorted(sorted_reference_strings, query_strings)

# Execution
query(sorted_reference_strings, query_strings)
```

Error message:
```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
Input In [1], in <cell line: 37>()
     32     return np.searchsorted(sorted_reference_strings, query_strings)
     35 # Execution
---> 37 query(sorted_reference_strings, query_strings)

File /opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/core/dispatcher.py:468, in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 468     error_rewrite(e, 'typing')
    469 except errors.UnsupportedError as e:
    470     # Something unsupported is present in the user code, add help info
    471     error_rewrite(e, 'unsupported_error')

File /opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/core/dispatcher.py:409, in _DispatcherBase._compile_for_args.<locals>.error_rewrite(e, issue_type)
    407     raise e
    408 else:
--> 409     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<function searchsorted at 0x7f67d40d37f0>) found for signature:
 
 >>> searchsorted(array([unichr x 32], 1d, C), array([unichr x 32], 1d, C))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'searchsorted': File: numba/np/arraymath.py: Line 3773.
    With argument(s): '(array([unichr x 32], 1d, C), array([unichr x 32], 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<function _searchsorted.<locals>.searchsorted_inner at 0x7f67ae15e830>) found for signature:
    
    >>> searchsorted_inner(array([unichr x 32], 1d, C), [unichr x 32])
    
   There are 2 candidate implementations:
         - Of which 2 did not match due to:
         Overload in function 'register_jitable.<locals>.wrap.<locals>.ov_wrap': File: numba/core/extending.py: Line 159.
           With argument(s): '(array([unichr x 32], 1d, C), [unichr x 32])':
          Rejected as the implementation raised a specific error:
            TypingError: Failed in nopython mode pipeline (step: nopython frontend)
          No implementation of function Function(<ufunc 'isnan'>) found for signature:
           
           >>> isnan([unichr x 32])
           
          There are 2 candidate implementations:
                - Of which 2 did not match due to:
                Overload in function 'Numpy_rules_ufunc.generic': File: numba/core/typing/npydecl.py: Line 98.
                  With argument(s): '([unichr x 32])':
                 Rejected as the implementation raised a specific error:
                   TypingError: can't resolve ufunc isnan for types [[unichr x 32]]
            raised from /opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/core/typing/npydecl.py:107
          
          During: resolving callee type: Function(<ufunc 'isnan'>)
          During: typing of call at /opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/np/arraymath.py (3746)
          
          
          File "../opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/np/arraymath.py", line 3746:
              def searchsorted_inner(a, v):
                  <source elided>
                  n = len(a)
                  if np.isnan(v):
                  ^
   
     raised from /opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/core/typeinfer.py:1086
   
   During: resolving callee type: Function(<function _searchsorted.<locals>.searchsorted_inner at 0x7f67ae15e830>)
   During: typing of call at /opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/np/arraymath.py (3788)
   
   
   File "../opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/np/arraymath.py", line 3788:
           def searchsorted_impl(a, v, side='left'):
               <source elided>
               for view, outview in np.nditer((v, out)):
                   index = loop_impl(a, view.item())
                   ^

  raised from /opt/anaconda/envs/numba_test/lib/python3.10/site-packages/numba/core/typeinfer.py:1086

During: resolving callee type: Function(<function searchsorted at 0x7f67d40d37f0>)
During: typing of call at /tmp/ipykernel_7977/1750162599.py (32)


File "../tmp/ipykernel_7977/1750162599.py", line 32:
<source missing, REPL/exec in use?>
```

Temporary Fix:
```python
def _searchsorted(func):
    def searchsorted_inner(a, v):
        n = len(a)
        # Commenting out this block solves the problem.
        # if np.isnan(v):
        #     # Find the first nan (i.e. the last from the end of a,
        #     # since there shouldn't be many of them in practice)
        #     for i in range(n, 0, -1):
        #         if not np.isnan(a[i - 1]):
        #             return i
        #     return 0
        lo = 0
        hi = n
        while hi > lo:
            mid = (lo + hi) >> 1
            if func(a[mid], (v)):
                # mid is too low => go up
                lo = mid + 1
            else:
                # mid is too high, or is a NaN => go down
                hi = mid
        return lo
    return searchsorted_inner
```

As I see it, there are couple of options here, but I'm open to better ideas:
1. Implement the `np.isnan` function for the unicode dtype. Needs thinking about because there is no null option for this type.
2. Put a wrapper around the `if` block which prevents calling `np.isnan` if the user has specified (through an option) that there are no null items in the sorted array.

I think 1. is preferable to keep the function as close to that in numpy as possible.

This is the first issue I've raised on an open-source project so please do give me some tips! I'm happy to get involved with the fix if somebody could give me some pointers.

**Comment by gmarkall** [comment]
Many thanks for the excellent description, reproducer, workaround and suggestions!

I can reproduce the issue and verify that your workaround works.

Regarding your suggestions, I note that if I do:

```python
print(np.isnan(query_strings))
```

then I get

```
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/8190/repro.py", line 32, in <module>
    print(np.isnan(query_strings))
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

so it seems like NumPy doesn't support `isnan()` on Unicode types - am I checking for this correctly?

What do you think about a third possibility, that presents `np.isnan` being called in `searchsorted_inner()` where it's not supported (on the `unicode` dtype, and possibly others)?

**Comment by gmarkall** [comment]
(Labelling as a feature request, since the error is a Typing Error that indicates unsupported functionality).

**Comment by stonescw** [comment]
@gmarkall Thanks very much for your reply.

Absolutely right---I have reproduced your error message when I use `np.isnan` on unicode strings in numpy.

I think the third suggestion is a very good one, if I understand correctly. My understanding is that the `isnan` check is there for the case where the array is of the float dtype. Since `nan` is not even possible with e.g. unicode type, then there is no need to perform this step.

Could we implement this with a try-except block or would something hinder this? (I'm not very familiar with the constraints of developing in the numba library, given the JIT compilation.)

**Comment by stuartarchibald** [comment]
Untested starter patch:
```diff
diff --git a/numba/cpython/builtins.py b/numba/cpython/builtins.py
--- a/numba/cpython/builtins.py
+++ b/numba/cpython/builtins.py
@@ -714,7 +714,8 @@ def ol_isinstance(var, typs):
                         types.DictType, types.LiteralStrKeyDict, types.List,
                         types.ListType, types.Tuple, types.UniTuple, types.Set,
                         types.Function, types.ClassType, types.UnicodeType,
-                        types.ClassInstanceType, types.NoneType, types.Array)
+                        types.ClassInstanceType, types.NoneType, types.Array,
+                        types.UnicodeCharSeq)
     if not isinstance(var_ty, supported_var_ty):
         msg = f'isinstance() does not support variables of type "{var_ty}".'
         raise NumbaTypeError(msg)
diff --git a/numba/np/arraymath.py b/numba/np/arraymath.py
--- a/numba/np/arraymath.py
+++ b/numba/np/arraymath.py
@@ -3857,13 +3857,14 @@ def _searchsorted(func):
 
         .. [1] https://github.com/numpy/numpy/blob/809e8d26b03f549fd0b812a17b8a166bcd966889/numpy/core/src/npysort/binsearch.cp
         """  # noqa: E501
-        if np.isnan(v):
-            # Find the first nan (i.e. the last from the end of a,
-            # since there shouldn't be many of them in practice)
-            for i in range(n, 0, -1):
-                if not np.isnan(a[i - 1]):
-                    return i
-            return 0
+        if isinstance(v, (int, float, complex)):
+            if np.isnan(v):
+                # Find the first nan (i.e. the last from the end of a,
+                # since there shouldn't be many of them in practice)
+                for i in range(n, 0, -1):
+                    if not np.isnan(a[i - 1]):
+                        return i
+                return 0
```

**Comment by stonescw** [comment]
Thanks @stuartarchibald, a couple of thoughts:

1. Should we use `isinstance` here, or would a duck-typing solution which checks if `isnan` is implemented for the variable be preferred? 
2. Do we need to include `int` in the tuple? Although I don't think the `np.isnan` function will throw an exception, I think I'm right in saying the effort will be wasted because there is no `nan` in integer arrays?

Other than that, I think it looks good!

**Comment by gmarkall** [comment]
My thoughts on these (commenting as I know Stuart is pretty busy with the release):

>     1. Should we use `isinstance` here, or would a duck-typing solution which checks if `isnan` is implemented for the variable be preferred?

This function is being compiled by Numba, so a duck-typing solution is not well-matched to the kind of code that Numba can compile. The instance check (given we only need floating point types) is simple and (I expect) robust enough.
 
>     2. Do we need to include `int` in the tuple? Although I don't think the `np.isnan` function will throw an exception, I think I'm right in saying the effort will be wasted because there is no `nan` in integer arrays?

I think you're right, we probably don't need `int` because `isnan` will always be false for it.

**Comment by stonescw** [comment]
@gmarkall
Excellent---thanks for getting back to me. All sounds good. Where do we go from here?

**Comment by gmarkall** [comment]
@stonescw Would you like to try making the suggested changes and opening a PR?

There's some guidelines here: https://numba.readthedocs.io/en/stable/developer/contributing.html for getting set up to do so, but skimming through them I do note they're a little sparse in places, so please let me know if you need more specific directions for any part of the process and I'll try and guide you.

**Comment by stonescw** [comment]
@gmarkall Yes, I will do that along the lines suggested above by @stuartarchibald

Thanks very much!

**Comment by stuartarchibald** [comment]
> My thoughts on these (commenting as I know Stuart is pretty busy with the release):

Thanks for following up on this @gmarkall.

> > ```
> > 1. Should we use `isinstance` here, or would a duck-typing solution which checks if `isnan` is implemented for the variable be preferred?
> > ```
> 
> This function is being compiled by Numba, so a duck-typing solution is not well-matched to the kind of code that Numba can compile. The instance check (given we only need floating point types) is simple and (I expect) robust enough.

Anything with `try..except` in Numba code tends to be really expensive (unless LLVM can figure out how to optimise it out), this is because a check for an exception state has to be made after executing each statement, this creates branches and often defeats optimisations e.g. vectorizers. In the above suggestion, everything for `isinstance` is known at compile time and Numba will work out whether to even keep that branch or not based on the types of the variables presented, i.e. if you pass in a unicode array, the JIT compiled code won't even contain that branch!

> > ```
> > 2. Do we need to include `int` in the tuple? Although I don't think the `np.isnan` function will throw an exception, I think I'm right in saying the effort will be wasted because there is no `nan` in integer arrays?
> > ```
> 
> I think you're right, we probably don't need `int` because `isnan` will always be false for it.

Agree, IIRC `isnan` works fine for `int`, but it's creating additional work for the compiler (it'll evaluate `isinstance` to "always True" and `isnan` to "always False", and it'll all get optimised away, but it's not necessary as noted!)

**Comment by stuartarchibald** [comment]
> @gmarkall Yes, I will do that along the lines suggested above by @stuartarchibald
> 
> Thanks very much!

Thanks @stonescw

**Comment by stonescw** [comment]
@gmarkall @stuartarchibald I've raised a draft PR to close the issue but it seems to be failing the CI/CD. Example: 

https://dev.azure.com/numba/numba/_build/results?buildId=12399&view=logs&j=424d22ce-0e93-5738-1c63-d3b7baa6c92e&t=8b8b58a0-8c59-5dc8-25a8-5f59df44a60b&l=51

It looks like it is failing due to the requirement 'llvmlite<0.40,>=0.39.0dev0', but to my understanding I haven't done anything which should affect this.

Any help would be gratefully received!

**Comment by stuartarchibald** [comment]
@stonescw Thanks, there's an explanation here https://github.com/numba/numba/pull/8202#issuecomment-1168614125, it will be sorted out shortly.
