### ISSUE TITLE
"ImportError: Numba needs NumPy 1.22 or less" only on RTD build while using Numba 0.55.2 

### ISSUE THREAD

**Issue by michaelavs** [numba/numba#8233]
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

When we run ReadTheDocs for our package, we are getting the following error:
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/conda/integrate_anissa/lib/python3.10/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/checkouts/integrate_anissa/docs/conf.py", line 14, in <module>
    import uxarray
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/checkouts/integrate_anissa/uxarray/__init__.py", line 1, in <module>
    from .grid import *
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/checkouts/integrate_anissa/uxarray/grid.py", line 13, in <module>
    from .helpers import determine_file_type
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/checkouts/integrate_anissa/uxarray/helpers.py", line 5, in <module>
    from .get_quadratureDG import get_gauss_quadratureDG, get_tri_quadratureDG
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/checkouts/integrate_anissa/uxarray/get_quadratureDG.py", line 2, in <module>
    from numba import njit
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/conda/integrate_anissa/lib/python3.10/site-packages/numba/__init__.py", line 200, in <module>
    _ensure_critical_deps()
  File "/home/docs/checkouts/readthedocs.org/user_builds/uxarray/conda/integrate_anissa/lib/python3.10/site-packages/numba/__init__.py", line 140, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.22 or less")
ImportError: Numba needs NumPy 1.22 or less
```
The environment cat shows we have:
```
+ numba                                0.55.2  py310ha5257ce_0          conda-forge/linux-64        4 MB
+ numpy                                1.21.6  py310h45f3432_0          conda-forge/linux-64        6 MB
```

From reading through [recent issues](https://github.com/numba/numba/issues/8188) in this repo, along with the setup.py file, it sounds like we should not being getting this error message as there is no longer a maximum supported Numpy version. This issue only seems to happen with our ReadTheDocs builds and not when we build/run locally. If you would like to take a look at how our repository is set up you can find it here: https://github.com/UXARRAY/uxarray

Thank you for any help/insight you may be able to provide for us, and let me know if I can give any other details that may assist in diagnosis this issue!

**Comment by michaelavs** [comment]
Issue was resolved. Found that for some reason `python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .` was run during the build which would force a pip install to upgrade all dependencies regardless of whether they still satisfy the new parent requirements, thus causing incompatibility with Numpy and Numba. This was fixed by updating the package `.readthedocs.yml` with the following:
```
build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
      - pip install numpy==1.22
```
Closing issue now.

**Comment by esc** [comment]
@michaelavs -- looks like you found a good solution. To re-iterate: we don't pin Numpy on `main` in `setup.py` but only on release branches. This is why you won't see a `max_numpy_version` in `setup.py` on `main` -- hope that helps.
