### ISSUE TITLE
Numba Wrapper Address Protocol (WAP) is broken

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#8282]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Reproducer is from [Numba docs](https://numba.pydata.org/numba-doc/latest/reference/types.html#wrapper-address-protocol-wap):

```python
import numba, ctypes, ctypes.util, math

libm = ctypes.cdll.LoadLibrary(ctypes.util.find_library('m'))

class LibMCos(numba.types.WrapperAddressProtocol):
    def __wrapper_address__(self):
        return ctypes.cast(libm.cos, ctypes.c_voidp).value
    def signature(self):
        return numba.float64(numba.float64)

cos = LibMCos()

@numba.njit
def foo(f, x):
    return f(x)

print(foo(cos, 0.0))
```

```
$ python a.py
Traceback (most recent call last):
  File "/home/guilhermeleobas/git/numba/repro.py", line 17, in <module>
    print(foo(cos, 0.0))
  File "/home/guilhermeleobas/git/numba/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/guilhermeleobas/git/numba/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
During: typing of argument at /home/guilhermeleobas/git/numba/repro.py (15)

File "repro.py", line 15:
def foo(f, x):
    return f(x)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This stopped working sometime between 0.53 and 0.54.

**Comment by stuartarchibald** [comment]
`git bisect` suggests: 98f733f0a4b33bfa87671b6e04585f9df8ca6b3f is the first bad commit.

**Comment by stuartarchibald** [comment]
Given the contents of 98f733f, I wonder if WAP relied on some import ordering/side effect.

**Comment by stuartarchibald** [comment]
This "fixes" it:
```diff
diff --git a/numba/core/cpu.py b/numba/core/cpu.py
--- a/numba/core/cpu.py
+++ b/numba/core/cpu.py
@@ -58,6 +58,17 @@ class CPUContext(BaseContext):
         # Initialize NRT runtime
         rtsys.initialize(self)
 
+        from numba.core.types import FunctionType, WrapperAddressProtocol
+        from numba.extending import typeof_impl
+        @typeof_impl.register(WrapperAddressProtocol)
+        def typeof_function_type(val, c):
+            if isinstance(val, WrapperAddressProtocol):
+                sig = val.signature()
+            else:
+                raise NotImplementedError(
+                    f'function type from {type(val).__name__}')
+            return FunctionType(sig)
+
         # Add lower_extension attribute
         self.lower_extensions = {}
         from numba.parfors.parfor_lowering import _lower_parfor_parallel
```
the issue is essentially that the `WrapperAddressProtocol` is not registered early enough for typing to know what it is.

**Comment by guilhermeleobas** [comment]
Thanks, Stuart. I think the tests for WAP are not failing on CI because [`test.SubTest`](https://github.com/numba/numba/blob/f9f71df123f62d5f5763505a35910a12cf6275de/numba/tests/test_function_type.py#L634-L638) is swallowing any exception thrown by the compiler.

**Comment by rwgk** [comment]
I'm seeing the exact same problem (PR Description) with numba 0.60. Is this still being worked on?

**Comment by stuartarchibald** [comment]
@rwgk it's not in the milestone for 0.61 and I don't think anyone is working on it I'm afraid. I'm a little puzzled as to why it's not working already as `function_type` is already imported in the registry loading:
https://github.com/numba/numba/blob/d2d8867e50f7cb9e39950e56b940bf0cea83022c/numba/core/cpu.py#L81
but perhaps that is also too late, but that does pose the question of what's going wrong as there isn't really an appropriate "earlier" time to do the registration.
