### ISSUE TITLE
Lowering failure in object mode when big integer constant is present

### ISSUE THREAD

**Issue by seibert** [numba/numba#831]
We cannot lower integers that exceed the range of a 64-bit int in nopython mode, but this should be supported in object mode:
``` python
f = numba.autojit(lambda:10**1024)
f()
```
Current traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/dispatcher.py", line 145, in _compile_for_args
    return self.jit(sig)
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/dispatcher.py", line 136, in jit
    return self.compile(sig, **kws)
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/dispatcher.py", line 271, in compile
    flags=flags, locals=locs)
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/compiler.py", line 551, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/compiler.py", line 261, in compile_extra
    return self.compile_bytecode(res.result, func_attr=self.func_attr)
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/compiler.py", line 275, in compile_bytecode
    return self._compile_bytecode()
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/compiler.py", line 501, in _compile_bytecode
    return self._run_pipeline(pipelines)
  File "/home/dunric/.local/lib64/python2.7/site-packages/numba/compiler.py", line 526, in _run_pipeline
    raise _raise_error(msg, res.exception)
numba.lowering.LoweringError: Failed at object mode backend
Internal error:
ValueError: Integer is too big to be lowered
```

**Comment by pitrou** [comment]
This now works, because integer constants are reified as Python objects in object mode.
