### ISSUE TITLE
nan as dict key

### ISSUE THREAD

**Issue by auderson** [numba/numba#8340]
In Cpython, dict key lookup will first check `__hash__` then `__eq__`: https://github.com/python/cpython/blob/de388c0a7b71c094d36ce40fecef87bdbb8a87d3/Objects/dictobject.c
This causes deviation from python dicts and numba dicts, if nan is used as dict keys. 
In certain cases, numba dict will produce some unexpected errors which I'll show below.

`np.nan` is a constant so they have the same hash:
```python
d = {}
d[np.nan] = 1
d[np.nan] = 2
print(d)
# {nan: 2}
```
`float('nan')` is not (but if stored as constant, then behave the same as `np.nan`)
 ```python
d = {}
d[float('nan')] = 1
d[float('nan')] = 2
print(d)
# {nan: 1, nan: 2}
```
numba seems to use `==` only:
```python
@njit
def test():
    d = {}
    d[np.nan] = 1
    d[np.nan] = 2
    return d

d = test()
```
now this will produce error:
```python
print(d)  # d.keys(), d.values(), d.items()
```
```
Traceback (most recent call last):
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/IPython/core/formatters.py", line 222, in catch_format_error
    r = method(self, *args, **kwargs)
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/IPython/core/formatters.py", line 707, in __call__
    printer.pretty(obj)
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/IPython/lib/pretty.py", line 410, in pretty
    return _repr_pprint(obj, self, cycle)
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/IPython/lib/pretty.py", line 778, in _repr_pprint
    output = repr(obj)
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/numba/typed/typeddict.py", line 187, in __repr__
    body = str(self)
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/numba/typed/typeddict.py", line 182, in __str__
    for k, v in self.items():
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/_collections_abc.py", line 906, in __iter__
    yield (key, self._mapping[key])
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/numba/typed/typeddict.py", line 150, in __getitem__
    return _getitem(self, key)
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/numba/typed/dictobject.py", line 739, in impl
    raise KeyError()
KeyError
```
This is a KeyError so I guess it's from `nan != nan`. Besides:
```python
len(d)
# 2
```
Then the actual content of this numba dict is most likely `{nan: 1, nan: 2}`.

Maybe I don't think this can be called a bug. But it does make numba behave differently from numpy codes. What do you think?

**Comment by auderson** [comment]
I'm using a dict to count values in an array. So in this case I prefer `nan == nan` when it's used as dict keys.

**Comment by auderson** [comment]
> This is a KeyError so I guess it's from nan != nan

I took some time reading numba's source code, and found numba dict also uses hash. So this is actually from :
https://github.com/numba/numba/blob/2e825b000e609e090005f8fb3d567999f1f1940c/numba/cpython/hashing.py#L77-L93
I'm using py3.10 so `hash(nan)` will always be different.

**Comment by apmasell** [comment]
I have been able to reproduce the issue. We will have to figure out the best way to proceed.

**Comment by stuartarchibald** [comment]
This might be hard to resolve as Numba doesn't differentiate between CPython float scalars and NumPy float scalars, they both just end up as `float64` in the type system.

**Comment by auderson** [comment]
Yeah, I mean can we treat nan as a constant and also return _PyHASH_NAN  in python 3.10?

**Comment by apmasell** [comment]
We want to keep compatibility with CPython as much as possible, so we'd rather not change the behaviour of NaN. We discussed possible work arounds. NaN's hash being different is only a problem when used as a dictionary key, as far as we can tell, and using floating point numbers could have a whole bunch of precision and stability problems when used as keys; it might be best to convert them to non-floating point values.

For keeping the NumPy behaviour, it might be easier to convert the floats to an integer with the same bits: `np.float64(your_value).view(np.uint64)`

That would be give the desired behaviour for NaN, though the numbers themselves wouldn't be very useful.

**Comment by auderson** [comment]
Thanks, this is a valid option

> For keeping the NumPy behaviour, it might be easier to convert the floats to an integer with the same bits: `np.float64(your_value).view(np.uint64)`
