### ISSUE TITLE
jit cache pickle exception on many local cuda arrays

### ISSUE THREAD

**Issue by academe-01** [numba/numba#8373]
Anyone facing the same ?

```python
import numba as nb
from numba import cuda


@cuda.jit(cache=True)
def test():
    aa = cuda.local.array((1, 1), nb.float64)
    ab = cuda.local.array((1, 1), nb.float64)
    ac = cuda.local.array((1, 1), nb.float64)
    ad = cuda.local.array((1, 1), nb.float64)
    ae = cuda.local.array((1, 1), nb.float64)
    af = cuda.local.array((1, 1), nb.float64)
    ag = cuda.local.array((1, 1), nb.float64)
    ah = cuda.local.array((1, 1), nb.float64)
    ai = cuda.local.array((1, 1), nb.float64)
    aj = cuda.local.array((1, 1), nb.float64)
    ak = cuda.local.array((1, 1), nb.float64)
    al = cuda.local.array((1, 1), nb.float64)
    am = cuda.local.array((1, 1), nb.float64)
    an = cuda.local.array((1, 1), nb.float64)
    ao = cuda.local.array((1, 1), nb.float64)
    ap = cuda.local.array((1, 1), nb.float64)
    ar = cuda.local.array((1, 1), nb.float64)
    at = cuda.local.array((1, 1), nb.float64)
    au = cuda.local.array((1, 1), nb.float64)
    av = cuda.local.array((1, 1), nb.float64)
    aw = cuda.local.array((1, 1), nb.float64)
    ax = cuda.local.array((1, 1), nb.float64)
    ay = cuda.local.array((1, 1), nb.float64)
    az = cuda.local.array((1, 1), nb.float64)


    aa[:] = 0
    ab[:] = 0
    ac[:] = 0
    ad[:] = 0
    ae[:] = 0
    af[:] = 0
    ag[:] = 0
    ah[:] = 0
    ai[:] = 0
    aj[:] = 0
    ak[:] = 0
    al[:] = 0
    am[:] = 0
    an[:] = 0
    ao[:] = 0
    ap[:] = 0
    ar[:] = 0
    at[:] = 0
    au[:] = 0
    av[:] = 0
    aw[:] = 0
    ax[:] = 0
    ay[:] = 0
    az[:] = 0



test[1, 32]()
```

```
/usr/local/lib/python3.9/site-packages/numba/cuda/dispatcher.py:488: NumbaPerformanceWarning: Grid size 1 will likely result in GPU under-utilization due to low occupancy.
  warn(NumbaPerformanceWarning(msg))
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/numba/cloudpickle/cloudpickle_fast.py", line 568, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.9/site-packages/numba/core/serialize.py", line 186, in reducer_override
    return super().reducer_override(obj)
  File "/usr/local/lib/python3.9/site-packages/numba/cloudpickle/cloudpickle_fast.py", line 644, in reducer_override
    if sys.version_info[:2] < (3, 7) and _is_parametrized_type_hint(obj):  # noqa  # pragma: no branch
RecursionError: maximum recursion depth exceeded in comparison

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/pycharm_project_703/nb_err.py", line 60, in <module>
    test[1, 32]()
  File "/usr/local/lib/python3.9/site-packages/numba/cuda/dispatcher.py", line 491, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/usr/local/lib/python3.9/site-packages/numba/cuda/dispatcher.py", line 625, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "/usr/local/lib/python3.9/site-packages/numba/cuda/dispatcher.py", line 633, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/usr/local/lib/python3.9/site-packages/numba/cuda/dispatcher.py", line 797, in compile
    self._cache.save_overload(sig, kernel)
  File "/usr/local/lib/python3.9/site-packages/numba/core/caching.py", line 652, in save_overload
    self._save_overload(sig, data)
  File "/usr/local/lib/python3.9/site-packages/numba/core/caching.py", line 662, in _save_overload
    self._cache_file.save(key, data)
  File "/usr/local/lib/python3.9/site-packages/numba/core/caching.py", line 479, in save
    self._save_data(data_name, data)
  File "/usr/local/lib/python3.9/site-packages/numba/core/caching.py", line 537, in _save_data
    data = self._dump(data)
  File "/usr/local/lib/python3.9/site-packages/numba/core/caching.py", line 550, in _dump
    return dumps(obj)
  File "/usr/local/lib/python3.9/site-packages/numba/core/serialize.py", line 57, in dumps
    p.dump(obj)
  File "/usr/local/lib/python3.9/site-packages/numba/cloudpickle/cloudpickle_fast.py", line 575, in dump
    raise pickle.PicklingError(msg) from e
_pickle.PicklingError: Could not pickle object as excessively deep recursion required.
```

**Comment by gmarkall** [comment]
Thanks for the report and nice reproducer! I can reproduce the issue.

**Comment by gmarkall** [comment]
I'm not sure this is a CUDA-specific issue per se, it seems like the cache fails when the LLVM IR gets too big. I guess there's no optimization of the IR within Numba for the CUDA target though, so the cache might easily see much larger IR than with the CPU target.

**Comment by academe-01** [comment]
Is there any quick fix ?

**Comment by gmarkall** [comment]
I can't think of a quick fix off the top of my head - I might be able to come up with some other workaround with a bit more thought though.

**Comment by gmarkall** [comment]
Not pickling the LLVM IR for CUDA-jitted functions works around it:

```diff
diff --git a/numba/cuda/codegen.py b/numba/cuda/codegen.py
index 47c6d36a7..42308a25e 100644
--- a/numba/cuda/codegen.py
+++ b/numba/cuda/codegen.py
@@ -305,7 +305,7 @@ class CUDACodeLibrary(serialize.ReduceMixin, CodeLibrary):
             codegen=None,
             name=self.name,
             entry_name=self._entry_name,
-            module=self._module,
+            module=None,
             linking_libraries=self._linking_libraries,
             ptx_cache=self._ptx_cache,
             cubin_cache=self._cubin_cache,
```

Perhaps this is the right thing to do - I need to think a little more about this. If possible, can you try applying the above patch locally and see if it fixes your use case and avoids introducing any unexpected side effects? (if you have multiple GPUs of different compute capabilities this might break that in its current naive form, btw).

**Comment by gmarkall** [comment]
I've started on a fix in #8374. Hopefully this can go into 0.56.1.

**Comment by gmarkall** [comment]
@academe-01 Now that the issue is fixed, it should make it into the upcoming 0.56.1 release.
