### ISSUE TITLE
Checks for function type casting erroneously assume compilation is always possible

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#8405]
Originally noted in https://numba.discourse.group/t/type-inference-for-dispatching-of-function-arguments-in-njit-with-multiple-signatures/1536/2

When function compilation is disabled (e.g. due to eager typing), checks whether one function typing can cast to another typing of the function cause the whole compilation to fail because it forces a compilation which is assumed to succeed, which then raises because compilation is disabled.

For example (slightly modified from the Discourse post):

```python
from numba import njit, float64, bool_
from numba.core.types import FunctionType, UniTuple, Tuple


@njit([float64(float64)])
def f(x):
    return x + 3


@njit([float64(float64, bool_)])
def g(x, b):
    return x if b else 0.0


@njit([float64(FunctionType(float64(float64)), float64, Tuple(())),
       float64(FunctionType(float64(float64, bool_)), bool_, UniTuple(bool_, 1))])
def h(fn, x, *args):
    return fn(x, *args)


h_g = h(g, 1.0, *(True,))
print(f"h_g = {h_g}")

h_f = h(f, 1.0, *())
print(f"h_f = {h_f}")
```

fails with:

```
$ python repro.py 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/discourse-1536/repro.py", line 21, in <module>
    h_g = h(g, 1.0, *(True,))
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 716, in _search_new_conversions
    conv = self.typingctx.install_possible_conversions(args, sig.args)
  File "/home/gmarkall/numbadev/numba/numba/core/typing/context.py", line 585, in install_possible_conversions
    conv = self.can_convert(actual, formal)
  File "/home/gmarkall/numbadev/numba/numba/core/typing/context.py", line 533, in can_convert
    forward = fromty.can_convert_to(self, toty)
  File "/home/gmarkall/numbadev/numba/numba/core/types/functions.py", line 581, in can_convert_to
    if self.dispatcher.get_compile_result(other.signature):
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 981, in get_compile_result
    self.compile(atypes)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 937, in compile
    raise RuntimeError("compilation disabled")
RuntimeError: compilation disabled
```

If I modify the Dispatcher type's `can_convert_to()` method so that it catches the `RuntimeError` caused because compilation is disabled:

```diff
diff --git a/numba/core/types/functions.py b/numba/core/types/functions.py
index f3b313e2c..33b939d54 100644
--- a/numba/core/types/functions.py
+++ b/numba/core/types/functions.py
@@ -578,8 +578,11 @@ class Dispatcher(WeakType, Callable, Dummy):
 
     def can_convert_to(self, typingctx, other):
         if isinstance(other, types.FunctionType):
-            if self.dispatcher.get_compile_result(other.signature):
-                return Conversion.safe
+            try:
+                if self.dispatcher.get_compile_result(other.signature):
+                    return Conversion.safe
+            except RuntimeError:
+                return None
 
 
```

then the example runs to completion:

```
$ python repro.py 
h_g = 1.0
h_f = 4.0
```

**Comment by gmarkall** [comment]
I think it's important (and not too hard) to solve this so I've added it to the 0.57 milestone and assigned myself.
