### ISSUE TITLE
Support averaging across axis in np.average

### ISSUE THREAD

**Issue by divannyteoretik** [numba/numba#8459]
`np.average` ignores `axis` argument and always returns a single value. 
It would be nice to support this functionality, or at least place a warning as it's done in `np.mean`

Here is an example: 
```
from numba import jit
import numpy as np

@jit(nopython=True)
def some_fun():
    return np.average(np.ones((10,10)), axis=0)

print(some_fun())
```

**Comment by apmasell** [comment]
This looks like a regression as the error is there, but not being returned for some reason.

**Comment by guilhermeleobas** [comment]
I can reproduce the reported error on Numba 0.55 and 0.56

```python
$ python a.py
Numba version:  0.55.2
1.0

$ python a.py
Numba version:  0.56.2
1.0
```

On 0.54 I got a compiler error
```python
$ python a.py
Numba version:  0.54.1
Traceback (most recent call last):
  File "a.py", line 11, in <module>
    print(some_fun())
  File "/home/guilhermeleobas/miniconda3/envs/rbc/lib/python3.8/site-packages/numba/core/dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/guilhermeleobas/miniconda3/envs/rbc/lib/python3.8/site-packages/numba/core/dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Use of unsupported NumPy function 'numpy.average' or unsupported use of the function.

File "a.py", line 9:
def some_fun():
    return np.average(np.ones((10,10)), axis=0)
    ^

During: typing of get attribute at a.py (9)

File "a.py", line 9:
def some_fun():
    return np.average(np.ones((10,10)), axis=0)
```

If I recall correctly, this is when Numba started using the `overload_glue`

**Comment by kc611** [comment]
#8420 now adds support for axis in `np.mean` and hence can resolve this issue.

**Comment by stuartarchibald** [comment]
Looks like there's an error in the `@overload(np.average)` implementation:
https://github.com/numba/numba/blob/5d5943af787f00ee0007b84b4872e11d278d962d/numba/np/arraymath.py#L949-L956

if kwarg `weights` is the default i.e. `None`, that branch will always execute.
