### ISSUE TITLE
Test `test_wrapper_address_protocol_libm` failing on mainline

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8506]
## Reporting a bug

PR https://github.com/numba/numba/pull/8503 had a test fail unrelated to the changes in the PR (they were entirely doc changes). The failed build was `Windows py37_np118` the relevant part of the log is:

```
ERROR: test_wrapper_address_protocol_libm (numba.tests.test_function_type.TestFunctionTypeExtensions) [<object object at 0x0000017429A97C60>] (jit={'nopython': True})
Parallel: 491. Serial: 34
Call cos and sinf from standard math library.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\1\s\numba\core\typeinfer.py", line 155, in propagate
    constraint(typeinfer)
  File "D:\a\1\s\numba\core\typeinfer.py", line 229, in __call__
    raise TypingError('non-precise type {}'.format(ty))
numba.core.errors.TypingError: non-precise type pyobject
During: typing of argument at D:\a\1\s\numba\tests\test_function_type.py (628)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\a\1\s\numba\tests\test_function_type.py", line 636, in test_wrapper_address_protocol_libm
    self.assertEqual(jit_(myeval)(mycos, 0.0), 1.0)
  File "D:\a\1\s\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "D:\a\1\s\numba\core\dispatcher.py", line 407, in error_rewrite
    raise e
  File "D:\a\1\s\numba\core\dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "D:\a\1\s\numba\core\dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "D:\a\1\s\numba\core\dispatcher.py", line 129, in compile
    raise retval
  File "D:\a\1\s\numba\core\dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "D:\a\1\s\numba\core\dispatcher.py", line 157, in _compile_core
    pipeline_class=self.pipeline_class)
  File "D:\a\1\s\numba\core\compiler.py", line 715, in compile_extra
    return pipeline.compile_extra(func)
  File "D:\a\1\s\numba\core\compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "D:\a\1\s\numba\core\compiler.py", line 520, in _compile_bytecode
File "numba\tests\test_function_type.py", line 628:
        def myeval(f, x):
            return f(x)
            ^
```

**Comment by stuartarchibald** [comment]
> Perhaps it is the same error: #8282

Thanks, looks like it, closing.
