### ISSUE TITLE
Tracebacks in compiled code don't include all frames

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8510]
This is a feature request to fix this:
```python
from numba import njit
import numpy as np

@njit
def baz():
    raise ValueError()

@njit
def bar():
    baz()

@njit
def foo():
    bar()

foo()
```
produces:
```
$ python exception_example.py 
Traceback (most recent call last):
  File "exception_example.py", line 16, in <module>
    foo()
  File "exception_example.py", line 6, in baz
    raise ValueError()
ValueError
```
whereas in the interpreter it produces:
```
$ NUMBA_DISABLE_JIT=1 python exception_example.py 
Traceback (most recent call last):
  File "exception_example.py", line 16, in <module>
    foo()
  File "exception_example.py", line 14, in foo
    bar()
  File "exception_example.py", line 10, in bar
    baz()
  File "exception_example.py", line 6, in baz
    raise ValueError()
ValueError
```
Essentially, Numba's traceback only captures the entry point and the point at which the exception occurred.

**Comment by ca5446001-tech** [comment]
```python
import os
import operator
import traceback
os.environ["NUMBA_FULL_TRACEBACKS"] = "1"

from numba import types, njit
from numba.extending import typeof_impl, register_model, models, overload
from numba.core.imputils import lower_constant, lower_builtin
from numba.core.typing.templates import infer, infer_global, AbstractTemplate
from numba.core import cgutils

USE_OVERLOAD = False

class My():
    def __init__(self):
        pass

class MyType(types.Type):
    def __init__(self):
        super().__init__("MyType()")
register_model(MyType)(models.OpaqueModel)

@typeof_impl.register(My)
def typeof_reg(val, c):
    return MyType()

if(not USE_OVERLOAD):
    @infer_global(operator.add)
    class MyOpTemplate(AbstractTemplate):
        key = "my.add"
        def generic(self, args, kws):
            return args[1](args[0], args[1])

    @lower_builtin(operator.add, MyType, types.Number)
    def impl_lower_op(context, builder, sig, args, loc=None):
        print("loc:", loc)
        with builder.if_then(cgutils.is_not_null(builder, args[1]), likely=False):
            context.call_conv.return_user_exc(builder, ValueError, ("example exception", ), loc=loc)
        return args[1]
else:
    @overload(operator.add)
    def ov_my_add(x, y):
        if(not isinstance(x, MyType)):
            return
        def impl(x, y):
            if(y):
                raise ValueError("example exception")
            return y
        return impl

my = My()

@lower_constant(MyType)
def lower_fieldref_constant(context, builder, typ, pyval):
    return context.get_dummy_value()

@njit
def main():
    res0 = operator.add(my, 5) # loc: ./tmp.py (41)
@njit
def main1():
    res1 = my + 5              # loc: None

try:
    main()
except Exception:
    print("******Exception with full traceback******")
    print(traceback.format_exc())

try:
    main1()
except Exception:
    print("******Exception missing full traceback******")
    print(traceback.format_exc())
```

I have a custom type which has the addition operator overloaded. It can produce runtime exceptions, that preferably print out the line where the operator was called.

In the minimal example I am just printing out the loc at compile time and always throwing an exception. When I call `add` as a member of the `operator` module, the location is reported as `./tmp.py (41)`. However, when the binop IR (+) is used instead, the line number is not passed to the `lower_builtin` function. This causes the full traceback to skip over the line where the addition happens.

If I use `@overload` then the line number that would be reported is the line inside of the overload, not the actual add line. This also skips over both types of addition calls in the full traceback.
