### ISSUE TITLE
Support catching exceptions raised in njit code from within gdb

### ISSUE THREAD

**Issue by stuartarchibald** [numba/numba#8512]
## Feature request

In C++, exceptions can be thrown and gdb can catch this happening. Example:
```cxx
#include <exception>

void foo(){
    throw std::exception();
}

int main(void)
{
    foo();
    return 0;
}
```
Compile:
```bash
$ $CXX -g -O0 exception.cpp
```
Run:
```bash
$ ./a.out 
terminate called after throwing an instance of 'std::exception'
  what():  std::exception
Aborted
```
Run under gdb control (slightly edited output to remove superfluous information):
```bash
$ gdb -q -ex 'catch throw' -ex 'r' -ex 'bt' ./a.out
Reading symbols from ./a.out...
Catchpoint 1 (throw)
Starting program: a.out 

Catchpoint 1 (exception thrown), __cxxabiv1::__cxa_throw (obj=0x55555556aca0, 
    tinfo=0x555555557dd0 <typeinfo for std::exception@@GLIBCXX_<VERSION>>, dest=0x7ffff7f304b2 <std::exception::~exception()>)
    at <path>/eh_throw.cc
#0  __cxxabiv1::__cxa_throw (obj=0x55555556aca0, tinfo=0x555555557dd0 <typeinfo for std::exception@@GLIBCXX_<VERSION>>, 
    dest=0x7ffff7f304b2 <std::exception::~exception()>)
    at at <path>/eh_throw.cc
#1  0x00005555555551b0 in foo () at exception.cpp:4
#2  0x00005555555551b9 in main () at exception.cpp:9
```

It might be possible and useful to augment Numba's exception generation mechanism to be able to do something similar, this to help with situations such as those described in #8510 and #8511 where an exception is raised but there's insufficient information in the traceback to work out where the exception came from. Further, if an exception has been raised, it might be useful to be able to intercept this and inspect the values/conditions present in the executing code that are associated with reaching the `raise`.

**Comment by stuartarchibald** [comment]
Notes: I've managed to get something working for this. If a call to a "special" known symbol is emitted as part of lowering all `static_raise` IR nodes, then it's possible to just break on these. Extending Numba's gdb python support means a command like `catch-exception` can be introduced to make it easy for users to just start the program under `gdb` and then wait for the exception to be "caught" by virtue of hitting the break point associated with the "special" symbol. It might also be possible to permit filtering on exception type/info, but that will require more thought.
