### ISSUE TITLE
Return the type(obj) in `numba.typeof` when `DISABLE_JIT` is enabled

### ISSUE THREAD

**Issue by haiiliin** [numba/numba#8546]
## Feature request

I use the `numba.typeof` to infer the type of `jitclass`, when I want to debug the code by setting the environment variable `NUMBA_DISABLE_JIT` to `1`, `numba.typeof` raises a `ValueError`, for example:
```python
>>> import os
>>> os.environ['NUMBA_DISABLE_JIT'] = '1'
>>> import numba
>>> @numba.experimental.jitclass
>>> class MyClass:
>>>     def __init__(self):
>>>         pass
>>> MyClassType = numba.typeof(MyClass)
Traceback (most recent call last):
  File "<pyshell#10>", line 1, in <module>
    MyClassType = numba.typeof(MyClass)
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\typing\typeof.py", line 42, in typeof
    raise ValueError(msg)
ValueError: [1mCannot determine Numba type of <class 'type'>[0m
```

Is it possible to return `MyClass` in `numba.typeof` when `DISABLE_JIT` is enabled, just like something in the `numba.typed.List.empty_list`:
https://github.com/numba/numba/blob/598aadf637cd5b7a168713e39ee6b4a1c9751806/numba/typed/typedlist.py#L213-L227

**Comment by sklam** [comment]
> Is it possible to return type(obj) in numba.typeof when DISABLE_JIT is enabled, just like something in the numba.typed.List.empty_list:

I'm worried this change will break a lot of code. DISABLE_JIT should only disable compiling. The expectation of `typeof` is to return the `numba.core.types.Type` given a Python value.
