### ISSUE TITLE
Dynamic jitclass fails

### ISSUE THREAD

**Issue by shaunc** [numba/numba#8608]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I am trying to create a factory that creates a dynamically generated jitclass, specialized by dtype. However I get an internal error, using numba 0.56.4. Code:

```py
from typing import Any, Union, Protocol, TypeVar, Generic, Type
import numba as nb  # type: ignore
import numpy as np
from numpy import typing as npt

DT = TypeVar("DT", bound=np.generic)


class DataRingP(Protocol, Generic[DT]):
    def __getitem__(self, index: int) -> DT:
        """
        Return the index-th item from the DataRing.

        0 index represents current time-slice (just written), with
        increasing indices moving backwards in time.
        """
        ...

    def update(self, value: Union[npt.NDArray[DT], DT]) -> None:
        """
        Add a new value to the DataRing.

        Adds new value to  head of DataRing, pushing out oldest value and shifting all values back one step.
        """
        ...


def data_ring_factory(dtype: Type[DT], default: DT) -> Type[DataRingP[DT]]:
    class DataRing:
        """
        Ring buffer for timeseries data.

        Stores history of either single value or array of values.

        NB: type of update, get-item should be generic (either scalar or array);
        however, numba does not support generic types, so annotated for
        scalar case only. Also does not support specialization based on
        type of value, so values annotated as float32.
        """

        def __init__(
            self,
            max_slices: int,
            shape: tuple[Union[int, np.int64], ...] = (1,),
            default_value: DT = default,
        ):
            full_shape = (max_slices,) + shape
            self.ring: npt.NDArray[DT] = np.full(  # type: ignore
                full_shape, default_value, dtype=dtype
            )
            self.i_next = -1

        def __getitem__(self, index: int) -> DT:
            """
            Return the index-th item from the DataRing.

            0 index represents current time-slice (just written), with
            increasing indices moving backwards in time.
            """
            return self.ring[self.i_next - index]  # type: ignore

        def update(self, value: Union[npt.NDArray[DT], DT]) -> None:
            """
            Add a new value to the DataRing.

            Adds new value to  head of DataRing, pushing out oldest value and shifting all values back one step.
            """
            self.i_next = (self.i_next + 1) % len(self.ring)
            self.ring[self.i_next] = value

    spec: list[tuple[str, Any]] = [
        ("ring", nb.typeof(np.zeros(1, dtype=dtype))),  # type: ignore
        ("i_next", nb.int64),
    ]
    name = f"DataRing{dtype.__name__.capitalize()}"
    dr = type(name, (DataRing,), {})

    return nb.experimental.jitclass(spec)(dr)  # type: ignore


DataRingFloat32 = data_ring_factory(np.float32, np.float32(0))
DataRingInt32 = data_ring_factory(np.int32, np.int32(0))
```
When I import and try to use, numba crashes:
```py
> import dataring as DR
> DR.DataRingInt32(3)

─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ <ipython-input-34-41d9e3f08806>:1 in <module>                                                    │
│                                                                                                  │
│ /Users/shauncutts/Library/Caches/pypoetry/virtualenvs/crypto-features-p9hXZv1e-py3.9/lib/python3 │
│ .9/site-packages/numba/experimental/jitclass/base.py:124 in __call__                             │
│                                                                                                  │
│   121 │   │   # is bound to None and then skipped when invoking the constructor.                 │
│   122 │   │   bind = cls._ctor_sig.bind(None, *args, **kwargs)                                   │
│   123 │   │   bind.apply_defaults()                                                              │
│ ❱ 124 │   │   return cls._ctor(*bind.args[1:], **bind.kwargs)                                    │
│   125                                                                                            │
│   126                                                                                            │
│   127 ##############################################################################             │
│                                                                                                  │
│ /Users/shauncutts/Library/Caches/pypoetry/virtualenvs/crypto-features-p9hXZv1e-py3.9/lib/python3 │
│ .9/site-packages/numba/core/dispatcher.py:468 in _compile_for_args                               │
│                                                                                                  │
│    465 │   │   │   │   │      f"by the following argument(s):\n{args_str}\n")                    │
│    466 │   │   │   │   e.patch_message(msg)                                                      │
│    467 │   │   │                                                                                 │
│ ❱  468 │   │   │   error_rewrite(e, 'typing')                                                    │
│    469 │   │   except errors.UnsupportedError as e:                                              │
│    470 │   │   │   # Something unsupported is present in the user code, add help info            │
│    471 │   │   │   error_rewrite(e, 'unsupported_error')                                         │
│                                                                                                  │
│ /Users/shauncutts/Library/Caches/pypoetry/virtualenvs/crypto-features-p9hXZv1e-py3.9/lib/python3 │
│ .9/site-packages/numba/core/dispatcher.py:409 in error_rewrite                                   │
│                                                                                                  │
│    406 │   │   │   if config.FULL_TRACEBACKS:                                                    │
│    407 │   │   │   │   raise e                                                                   │
│    408 │   │   │   else:                                                                         │
│ ❱  409 │   │   │   │   raise e.with_traceback(None)                                              │
│    410 │   │                                                                                     │
│    411 │   │   argtypes = []                                                                     │
│    412 │   │   for a in args:                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7f94b9222f40>.
Failed in nopython mode pipeline (step: native lowering)

Enable logging at debug level for details.
[1m
File "<string>", line 3:[0m
[1m<source missing, REPL/exec in use?>[0m
```

**Comment by sklam** [comment]
Thanks for reporting the issue.

The error above is caused by an invalid spec `("ring", nb.typeof(np.zeros(1, dtype=dtype))),`. In `DataRing.__init__`, `ring` can be of array more than 1D depending of `shape` argument. Also, Numba does not support array of variable-dimension. The factory method will also need to adjust the array dimension in the jitclass spec.

This issue reveals a problem for the jitclass implementation that it is eating the true error message. 

**Details: how I debug this**

There's an internal error revealed by setting `NUMBA_DEVELOPER_MODE=1`:

```pytb
  File "/path/to/numba/numba/np/arrayobj.py", line 6120, in array_to_array
    assert fromty.mutable != toty.mutable or toty.layout == 'A'
AssertionError: Failed in nopython mode pipeline (step: native lowering)
```

Printing `fromty` and `toty` reveals that type checker didn't properly guard for a invalid cast: `(array(int32, 2d, C), array(int32, 1d, C))`.

Knowing this, there's only one place in the user code that allocates the array:

```python
            full_shape = (max_slices,) + shape
            self.ring: npt.NDArray[DT] = np.full(  # type: ignore
                full_shape, default_value, dtype=dtype
            )
```
does not match the spec (the above can be more than 1D but the spec say 1D):

```python

    spec: list[tuple[str, Any]] = [
        ("ring", nb.typeof(np.zeros(1, dtype=dtype))),  # type: ignore
```

**Comment by shaunc** [comment]
Thanks! will fix and reopen if still causing problems.
