### ISSUE TITLE
Optional UniTuple gives error depending on the signature

### ISSUE THREAD

**Issue by javierttgg** [numba/numba#8610]
## Reporting a bug

When using numba with an optional `UniTuple` I have encountered different behaviors depending on the signature being used.

If we specify that each element of the UniTuple is optional, then the code compile and works as expected:
```
from numba import njit

@njit('i8(UniTuple(Optional(i8), 2))')
def foo(a):
    if (a[0] is None) or (a[1] is None):
        return -1
    else:
        return a[0]

# test.
a = (1, 2)
print(foo(a)) # 1
a = (1, None)
print(foo(a)) # -1
a = (None, None)
print(foo(a)) # -1
```

While if we specify the `UniTuple` itself as an optional parameter, the numba throws the following error when compiling the function.
```python
@njit('i8(Optional(UniTuple(i8, 2)))')
def foo(a):
    if a is None:
        return -1
    else:
        return a[0]
```

```shell
LoweringError: 'NoneType' object has no attribute 'args'
```

At first I thought this was related to the recent #8603, in which it was already commented that numba does not prune branches whether an element is None or not. 

However, what makes me doubt is that if we use as input argument a `ndarray` instead of a `UniTuple` then, the function gets compiled and works correctly:
```python
import numpy as np
from numba import njit

@njit('i8(optional(i4[:]))')
def foo2(a):
    if a is None:
        return -1
    else:
        return 1
    
# test.
a = np.array([1, 2])
print(foo2(a)) # prints 1
a = None
print(foo2(a)) # prints -1
```

Any help is highly appreciated.

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

numba version: `0.56.3`

**Comment by sklam** [comment]
Thank you for submitting the bug report. I can confirm that this is a internal compiler error.

The interest part of the traceback is:

```pytb

  File "/path/to/numba/numba/core/base.py", line 561, in get_function
    raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
NotImplementedError: No definition for lowering static_getitem(OptionalType(UniTuple(int64 x 2)), Literal[int](0)) -> int64

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/path/to/numba/numba/core/errors.py", line 823, in new_error_context
    yield
  File "/path/to/numba/numba/core/lowering.py", line 265, in lower_block
    self.lower_inst(inst)
  File "/path/to/numba/numba/core/lowering.py", line 439, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/path/to/numba/numba/core/lowering.py", line 621, in lower_assign
    return self.lower_expr(ty, value)
  File "/path/to/numba/numba/core/lowering.py", line 1279, in lower_expr
    return self.lower_getitem(resty, expr, expr.value,
  File "/path/to/numba/numba/core/lowering.py", line 764, in lower_getitem
    self.context.typing_context, signature.args, {},
AttributeError: 'NoneType' object has no attribute 'args'
```

The first exception is caused by a failure for static_getitem to unpack an optional type. For the second exception, I'll guess it is a mishandling of a failed function resolution (`signature` being `None` usually indicates that).

**Comment by javiertg9** [comment]
Thank you @sklam for the prompt and helpful response. The first exception may happen only with certain types (in this case `UniTuples`)?  When using `ndarrays` there seems to be no problem as shown in the last example.

**Comment by javierttgg** [comment]
Thank you @sklam for the prompt and helpful response. The first exception may happen only with certain types (in this case `UniTuples`)?  When using `ndarrays` there seems to be no problem, as shown in the last example.
