### ISSUE TITLE
Range Checking for Numpy Arrays

### ISSUE THREAD

**Issue by suuuehgi** [numba/numba#8632]
There appears to be no range checking when using numpy arrays:

```python
>>> from numba import jit
>>> import numpy as np
>>> @jit
... def test(arr, idx):
...     return arr[idx]
... 
>>> test(np.empty(1), idx=5)
0.0
```
whereat
```python
>>> test([1], idx=5)
/home/smonecke/.conda/envs/gt2/lib/python3.10/site-packages/numba/core/ir_utils.py:2147: NumbaPendingDeprecationWarning: 
Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'arr' of function 'test'.

For more information visit https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-reflection-for-list-and-set-types

File "<stdin>", line 1:
<source missing, REPL/exec in use?>

  warnings.warn(NumbaPendingDeprecationWarning(msg, loc=loc))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: getitem out of range
```
correctly fails.

I would like to propose this check as a feature request.

Thank you!

---
**P.S.**

```python
>>> import sys, numba; print(numba.__version__, sys.version)
0.56.4 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:23:14) [GCC 10.4.0]
```

**Comment by gmarkall** [comment]
Could you please try:

```python
from numba import jit
import numpy as np


@jit(boundscheck=True)
def test(arr, idx):
    return arr[idx]


test(np.empty(1), idx=5)
```

and let me know if it meets your needs? (See also bounds checking documentation: https://numba.readthedocs.io/en/latest/reference/pysemantics.html?highlight=boundscheck#bounds-checking)

**Comment by guilhermeleobas** [comment]
With `boundscheck=True`, I get the following:

```python
# example.py
from numba import jit
import numpy as np
@jit(boundscheck=True)
def test(arr, idx):
    return arr[idx]

print(test(np.empty(1), idx=5))
```

```bash
$ python example.py
Traceback (most recent call last):
  File "/Users/guilhermeleobas/git/numba/example.py", line 18, in <module>
    print(test(np.empty(1), idx=5))
IndexError: index is out of bounds
```

**Comment by suuuehgi** [comment]
> Could you please try:

> With boundscheck=True, I get the following:
> [...]
> IndexError: index is out of bounds

I get the same! I'm now fine with setting `NUMBA_BOUNDSCHECK` to 1.
But it appears inconsistent to me that it apparently defaults to True for lists but to False for numpy arrays.

Thank you for the fast reply!

**Comment by guilhermeleobas** [comment]
I'd say it is because it bounds checking introduce a non-negligible overhead, as a check needs to be performed before each array getitem. It might also prevent LLVM from vectorizing the code!? For instance, with the code above, LLVM can only apply vectorization when boundscheck is disabled.

```python
import llvmlite.binding as llvm
llvm.set_option('', '--debug-only=loop-vectorize')

from numba import njit
import numpy as np

@njit(fastmath=True)
def do_sum(x):
    acc = 0
    for i in range(len(x)):
        acc += x[i]
    return acc

arr = np.arange(10, dtype=np.int64)
print(do_sum(arr))
```

With `boundscheck=False`:

```
LV: The target has 32 registers of Generic::VectorRC register class
LV: The target has 31 registers of Generic::ScalarRC register class
LV: Interleaving because of reductions.
LV: Found a vectorizable loop (2) in do_sum
LV: Interleave Count is 2
Setting best plan to VF=2, UF=2
```

But with `boundscheck=True`:
```
... from do_sum
LV: Loop hints: force=? width=0 unroll=0
LV: Not vectorizing: The loop must have an exiting block.
LV: Interleaving disabled by the pass manager
LV: Not vectorizing: Cannot prove legality.
```

**Comment by gmarkall** [comment]
Closing as the original question appears to be answered and there has been no further activity. Please reopen the issue if the answer is still unclear - many thanks!
