### ISSUE TITLE
setattr on an optional type doesn't redirect to the inner type

### ISSUE THREAD

**Issue by sjperkins** [numba/numba#8640]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This seems to be a regression of 
- https://github.com/numba/numba/issues/2606 
- originally fixed in  https://github.com/numba/numba/pull/2610

Also related:
- https://numba.discourse.group/t/cannot-remove-element-from-double-linked-list/1119

Here is a reproducer:

```python
import numba
from numba.experimental import jitclass
import numpy as np

node_type = numba.deferred_type()

@jitclass(spec=[
    ("value", numba.float64),
    ("left", numba.optional(node_type)),
    ("right", numba.optional(node_type)),
])
class Node:
    def __init__(self, value):
        self.value = value
        self.left = None
        self.right = None

node_type.define(Node.class_type.instance_type)

@numba.njit
def node_insert(node, value):
    if value <= node.value:
        if node.left is None:
            node.left = Node(value)
        else:
            node_insert(node.left, value)
    else:
        if node.right is None:
            node.right = Node(value)
        else:
            node_insert(node.right, value)

@numba.njit
def fn(a):
    assert len(a) > 0
    tree = Node(a[0])

    for value in a[1:]:
        node_insert(tree, value)

    return tree

if __name__ == "__main__":
    print(fn(np.arange(10)))
```

The traceback is as follows with `No definition for lowering DeferredType#140484577449904.left = OptionalType(DeferredType#140484577449904)` identifying the problem.

```traceback
Traceback (most recent call last):
  File "/home/simon/code/codex-africanus/essays/reproducer.py", line 46, in <module>
    print(fn(np.arange(10)))
  File "/home/simon/venv/afr/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/simon/venv/afr/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7fc4f4766b30>.
Failed in nopython mode pipeline (step: native lowering)
No definition for lowering DeferredType#140484577449904.left = OptionalType(DeferredType#140484577449904)

File "reproducer.py", line 24:
def node_insert(node, value):
    <source elided>
        if node.left is None:
            node.left = Node(value)
            ^

During: lowering "(node).left = $26call_function.2" at /home/simon/code/codex-africanus/essays/reproducer.py (24)
During: resolving callee type: recursive(type(CPUDispatcher(<function node_insert at 0x7fc54cba7d90>)))
During: typing of call at /home/simon/code/codex-africanus/essays/reproducer.py (26)

Enable logging at debug level for details.

File "reproducer.py", line 26:
def node_insert(node, value):
    <source elided>
        else:
            node_insert(node.left, value)
            ^

During: resolving callee type: type(CPUDispatcher(<function node_insert at 0x7fc54cba7d90>))
During: typing of call at /home/simon/code/codex-africanus/essays/reproducer.py (40)

During: resolving callee type: type(CPUDispatcher(<function node_insert at 0x7fc54cba7d90>))
During: typing of call at /home/simon/code/codex-africanus/essays/reproducer.py (40)


File "reproducer.py", line 40:
def fn(a):
    <source elided>
    for value in a[1:]:
        node_insert(tree, value)
```

**Comment by sjperkins** [comment]
Thanks @guilhermeleobas. I'm trying to reproduce this functionality with a StructRef which seems to be the preferred method of doing things. 

```python
import numpy as np

import numba
from numba.core import types
from numba.experimental import structref
from numba.core.extending import overload_method
from numba.core.errors import TypingError

@structref.register
class NodeType(types.StructRef):
    def preprocess_fields(self, fields):
        return tuple((name, types.unliteral(typ)) for name, typ in fields)

# Unneeded because we're not creating NodeType's in pure Python
# class Node(structref.StructRefProxy):
#     pass

node_type = numba.deferred_type()

TypedNodeType = NodeType(fields=[
    ("value", types.int64),
    ("left", types.optional(node_type)),
    ("right", types.optional(node_type))
])

node_type.define(TypedNodeType)

@numba.njit
def make_node(value):
    node = structref.new(TypedNodeType)
    node.value = value
    node.left = None
    node.right = None

@overload_method(NodeType, "insert")
def node_insert(self, value):
    if value == types.int64:
        def impl(self, value):
            if value <= self.value:
                if self.left is None:
                    self.left = make_node(value)
                else:
                    self.left.insert(value)
            else:
                if self.right is None:
                    self.right = make_node(value)
                else:
                    self.right.insert(value)

        return impl

    raise TypeError(f"value {value} is not int64")


if __name__ == "__main__":
    @numba.njit
    def fn(a):
        assert len(a) > 0

        tree = make_node(a[0])

        for v in a[1:]:
            tree.insert(v)

        return tree

    print(fn(np.arange(10)))
```

but this fails in the following way,  I guess because of the deferred type?

```traceback
python: /root/miniconda3/envs/buildenv/conda-bld/llvmdev_1637857770614/work/lib/IR/DataLayout.cpp:713: llvm::Align llvm::DataLayout::getAlignment(llvm::Type*, bool) const: Assertion `Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed.
Aborted
```

**Comment by gmarkall** [comment]
@sjperkins I just skimmed quickly, but I suspect you might be running into https://github.com/numba/numba/issues/8404 there

**Comment by gmarkall** [comment]
However, I just tried your (@sjperkins ) code from above and still got the same error even with the workaround I posted in #8404.
