### ISSUE TITLE
vectorize fails with boolean outputs with return after a for loop containing a function call

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#865]
The following example:

```python
from numba import vectorize
import numpy as np

def g(p):
    return p*2

@vectorize(['bool_(uint64)'])
def f(n):
    for j in range(n):
        a1 = g(j)
    return True

integers = np.arange(10, dtype=np.uint64)
print(f(integers))
```

Results in the following traceback:

```
Traceback (most recent call last):
  File "b.py", line 7, in <module>
    @vectorize(['bool_(uint64)'])
  File "/home/gmarkall/work/numba/numba/npyufunc/decorators.py", line 69, in wrap
    return vec.build_ufunc()
  File "/home/gmarkall/work/numba/numba/npyufunc/ufuncbuilder.py", line 114, in build_ufunc
    dtypenums, ptr, keepalive = self.build(cres, sig)
  File "/home/gmarkall/work/numba/numba/npyufunc/ufuncbuilder.py", line 149, in build
    cres.objectmode, envptr)
  File "/home/gmarkall/work/numba/numba/npyufunc/wrappers.py", line 175, in build_ufunc_wrapper
    pyapi, env)
  File "/home/gmarkall/work/numba/numba/npyufunc/wrappers.py", line 96, in build_obj_loop_body
    signature, env)
  File "/home/gmarkall/work/numba/numba/npyufunc/wrappers.py", line 51, in _build_ufunc_loop_body_objmode
    store(retval)
  File "/home/gmarkall/work/numba/numba/npyufunc/wrappers.py", line 92, in store
    out.store_direct(retval, builder.load(store_offset))
  File "/home/gmarkall/work/numba/numba/npyufunc/wrappers.py", line 262, in store_direct
    assert ptr.type.pointee == value.type
AssertionError
```

Performing a more simple assignment in the for loop body (e.g. `a1 = 1`) does not appear to have the same effect.

Note: An issue with vectorize and boolean outputs was already noted and fixed in #610.

**Comment by pitrou** [comment]
This now works correctly.
