### ISSUE TITLE
add support for dict types in np.asarray

### ISSUE THREAD

**Issue by auderson** [numba/numba#8672]
Currently `np.asarray` doesn't support dicts:
```python
from numba import njit
import numpy as np
@njit
def f():
    return np.asarray({1:1})
f()
```
```
Traceback (most recent call last):
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/IPython/core/interactiveshell.py", line 3398, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-0dff735416f8>", line 4, in <cell line: 4>
    f()
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/auderson/miniconda3/envs/py3.10/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function asarray>) found for signature:
 
 >>> asarray(DictType[int64,int64]<iv={1: 1}>)
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload of function 'asarray': File: numba/np/arraymath.py: Line 4416.
    With argument(s): '(DictType[int64,int64]<iv=None>)':
   No match.
During: resolving callee type: Function(<built-in function asarray>)
During: typing of call at <ipython-input-5-0dff735416f8> (3)
File "<ipython-input-5-0dff735416f8>", line 3:
def f():
    return np.asarray({1:1})
    ^
```

with this simple overload (copied from list overload here)
https://github.com/numba/numba/blob/7e92e225a6b3465b17f3fd303f179b2d115124a6/numba/np/arraymath.py#L4235-L4248

```python
from numba.extending import overload

@overload(np.asarray)
def np_asarray(a, dtype=None):
    import numba.core.types as nbt
    from numba.core.cgutils import is_nonelike
    from numba.core.types.containers import DictKeysIterableType, DictValuesIterableType, DictType

    impl = None
    if isinstance(a, (DictKeysIterableType, DictValuesIterableType, DictType)):
        if isinstance(a, DictType):
            yield_type = a.key_type
        else:
            yield_type = a.yield_type

        if not isinstance(yield_type, (nbt.Number, nbt.Boolean)):
            raise nbt.TypingError("asarray support for Dict is limited to Boolean and Number types")

        target_dtype = yield_type if is_nonelike(dtype) else dtype

        def impl(a, dtype=None):
            l = len(a)
            ret = np.empty(l, dtype=target_dtype)
            for i, v in enumerate(a):
                ret[i] = v
            return ret

    return impl

```
this will run:
```python
@njit
def f():
    d = {1:2}
    return np.asarray(d.keys()), np.asarray(d.values()), np.asarray(d)
f()
# (array([1]), array([2]), array([1]))
```

**Comment by auderson** [comment]
Oops, numpy version of f() is:
```python
def f():
    d = {1:2}
    return np.array(d.keys()), np.asarray(d.values()), np.asarray(d)
f()
# (array(dict_keys([1]), dtype=object),
# array(dict_values([2]), dtype=object),
# array({1: 2}, dtype=object))
```

Guess we can't use asarray to construct an array directly.
