### ISSUE TITLE
njit(cache=True) is not idempotent

### ISSUE THREAD

**Issue by stuz5000** [numba/numba#8679]
I'm seeing that ```njit(cache=True)``` produces exceptions on its second run, where it succeeded in the first. It's not idempotent.

Run scratch.py. Success. Run again, long error.

The error goes away with this change:
```
#@numba.njit(nogil=True, cache=True)
@numba.njit(nogil=True, cache=False)
def posToRegion(x, y, w, h, size):...
```
(Run twice to be sure)

Possibly, calling a generator from numba causes the problem. I couldn't trigger the problem when calling the posToRegionPixelIndexes generator directly from python.

```
#File: scratch.py
import numpy as np
from scratch_b import *

import numba

w, h = 1920, 1080
apositions = np.array([[419, 848],
                       [419, 848],
                       [421, 851],
                       [621, 884]], dtype=np.int32)

@numba.njit(nogil=True, cache=False)
def _nearbyMatches(apos,
                   w, h,
                   ):
    for jpixIndex_ in posToRegionPixelIndexes(apos[0, 0], apos[0, 1], w, h):
        return


# No problem
# print(list(posToRegionPixelIndexes(apositions[0, 0], apositions[0, 1], w, h)))

print("_nearbyMatches")
# Fails
_nearbyMatches(apositions, 1920, 1080)
print("_nearbyMatches...")
```

```
#file: scratch_b.py
import numba

@numba.njit(nogil=True, cache=True)
def posToRegion(x, y, w, h, size):
    x0, x1 = x - size, x + size + 1
    y0, y1 = y - size, y + size + 1
    if x0 < 0: x0 = 0
    if y0 < 0: y0 = 0
    if x1 > w: x1 = w
    if y1 > h: y1 = h
    return (x0, x1), (y0, y1)

@numba.njit(nogil=True, cache=True)
def posToRegionPixelIndexes(x, y, w, h, size=2):
    (x0, x1), (y0, y1) = posToRegion(x, y, w, h, size)
    nrows, ncols = y1 - y0, x1 - x0
    rowstart = y0 * w + x0
    for _ in range(nrows):
        i = rowstart
        for _ in range(ncols):
            yield i
            i += 1
        rowstart += w

```

Numba: 0.56.4
Python 10

```
Traceback (most recent call last):
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/errors.py", line 823, in new_error_context
    yield
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 265, in lower_block
    self.lower_inst(inst)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 439, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 626, in lower_assign
    return self.lower_expr(ty, value)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 1186, in lower_expr
    res = impl(self.builder, (castval,))
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/base.py", line 1190, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/base.py", line 1220, in wrapper
    return fn(*args, **kwargs)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/imputils.py", line 336, in wrapper
    func(context, builder, sig, args,
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/cpython/iterators.py", line 128, in iternext_zip
    impl = context.get_generator_impl(genty)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/base.py", line 571, in get_generator_impl
    res = self._generators[genty][1]
KeyError: int64 generator(func=<function posToRegionPixelIndexes at 0x7faae1f49120>, args=(int32, int32, int64, int64, omitted(default=2)), has_finalizer=True)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler.py", line 716, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler.py", line 452, in compile_extra
    return self._compile_bytecode()
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler.py", line 520, in _compile_bytecode
    return self._compile_core()
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler.py", line 499, in _compile_core
    raise e
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler.py", line 486, in _compile_core
    pm.run(self.state)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/typed_passes.py", line 394, in run_pass
    lower.lower()
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 168, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 222, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 251, in lower_function_body
    self.lower_block(block)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/lowering.py", line 263, in lower_block
    with new_error_context('lowering "{inst}" at {loc}', inst=inst,
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/sir/venv/p310_opencv/lib/python3.10/site-packages/numba/core/errors.py", line 837, in new_error_context
    raise newerr.with_traceback(tb)
numba.core.errors.LoweringError: Failed in nopython mode pipeline (step: native lowering)
int64 generator(func=<function posToRegionPixelIndexes at 0x7faae1f49120>, args=(int32, int32, int64, int64, omitted(default=2)), has_finalizer=True)

File "scratch.py", line 16:
def _nearbyMatches(apos,
    <source elided>
                   ):
    for jpixIndex_ in posToRegionPixelIndexes(apos[0, 0], apos[0, 1], w, h):
    ^

During: lowering "$24for_iter.1 = iternext(value=$phi24.0)" at .../scratch.py (16)
Exception ignored in: <module 'threading' from '/usr/lib/python3.10/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1567, in _shutdown
    lock.acquire()
KeyboardInterrupt: 
````

**Comment by gmarkall** [comment]
Thanks for the report and a nice reproducer - I can reproduce the issue.

As the Numba maintainers are out for the holidays this will be triaged during the triage meeting of 10th January 2023.

**Comment by sklam** [comment]
Actual fix might take a long time given the lack of resources, so stop gap might be to:

- document that generators don't support caching; or,
- disable caching on generators.

**Comment by timmysilv** [comment]
any chance this bug can be investigated further? 🙏
