### ISSUE TITLE
Access to outer variables in nested functions

### ISSUE THREAD

**Issue by haiiliin** [numba/numba#8693]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I don't know if it is a bug. In the nested functions, variables defined before the function definition can be accessed in both python and nopython mode, and variables defined after the function definition can not be accessed in nopython mode but can be accessed in python mode. Examples are below:

```python
import numba


@numba.njit
def func1():
    msg = "func1() called"

    def wrapper():
        print(msg)

    wrapper()


@numba.njit
def func2():
    def wrapper():
        print(msg)

    msg = "func2() called"
    wrapper()


if __name__ == "__main__":
    print("\nPython mode\n")
    func1.py_func()  # works
    func2.py_func()  # works

    print("\nNumba mode\n")
    func1()  # works
    func2()  # fails
```

Here is the error message:
```
PS C:\Users\Hailin\OneDrive\Desktop\numba-test> python .\test.py

Python mode

func1() called
func2() called

Numba mode

func1() called
Traceback (most recent call last):
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\ir.py", line 267, in get
    return self._con[name]
KeyError: 'msg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\ir.py", line 1124, in get_exact
    return self.localvars.get(name)
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\ir.py", line 269, in get
    raise NotDefinedError(name)
numba.core.errors.NotDefinedError: The compiler failed to analyze the bytecode. Variable 'msg' is not defined.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Hailin\AppData\Local\Programs\Python\Python310\lib\site-packages\numba\core\ir.py", line 267, in get
    return self._con[name]
KeyError: 'msg'
```

**Comment by stuartarchibald** [comment]
Thanks for the report @haiiliin. I think that this is a bug/issue in the bytecode interpreter. Essentially, in bytecode for the "fail" case, the  `STORE_DEREF` for the `msg` var is logically after the `LOAD_CLOSURE` and as a result the interpreter can't "see" that variable at the time the closure is being interpreted.
