### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by KeithSloan** [numba/numba#8695]
I have a FreeCAD workbench that uses the python  hausdorff package.

FreeCAD has been updated to use PythonPython 3.10.8 and when I try to install it and it tries to install numba and I get
the following error.
````
>>> import hausdorff
Traceback (most recent call last):
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/core/typeconv/typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/core/typeconv/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/hausdorff/__init__.py", line 1, in <module>
    from .hausdorff import *
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/hausdorff/hausdorff.py", line 2, in <module>
    import numba
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/__init__.py", line 23, in <module>
    from numba.misc.special import (
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/misc/special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/core/typing/__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/core/typing/context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/core/typeconv/rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "/Applications/FreeCAD.app/Contents/Resources/lib/python3.10/site-packages/shiboken2/files.dir/shibokensupport/feature.py", line 139, in _import
    return original_import(name, *args, **kwargs)
  File "/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/core/typeconv/typeconv.py", line 16, in <module>
    raise ImportError(msg)
ImportError: Numba could not be imported.
--------------------------------------------------------------------------------
If you are seeing this message and are undertaking Numba development work, you may need to rebuild Numba.
Please see the development set up guide:

https://numba.readthedocs.io/en/stable/developer/contributing.html.

--------------------------------------------------------------------------------
If you are not working on Numba development, the original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (/Users/keithsloan/Library/Application Support/FreeCAD/AdditionalPythonPackages/numba/core/typeconv/__init__.py)'.
For help, please visit:

https://numba.readthedocs.io/en/stable/user/faq.html#numba-could-not-be-imported

>>> 
````

**Comment by stuartarchibald** [comment]
Thanks for the report @KeithSloan. Did you try the suggestions available in the URL in the "For help, please visit:..." part of the error message?

**Comment by KeithSloan** [comment]
FreeCAD workbenches are installed via an Addon Manager which my understanding is uses pip to install required python libraries.

I have pm'ed the developer to see if, what they advise.

The https://numba.readthedocs.io/en/stable/developer/contributing.html. link gives me a 404 error

**Comment by stuartarchibald** [comment]
> FreeCAD workbenches are installed via an Addon Manager which my understanding is uses pip to install required python libraries.
> 
> I have pm'ed the developer to see if, what they advise.

OK, thanks. The user FAQs linked above aim to assist with diagnosing and fixing the problem, they are based on a digest of helping many users with installation problems.

> The https://numba.readthedocs.io/en/stable/developer/contributing.html. link gives me a 404 error

Was the `.` on the end in the URL perhaps accidentally included?

**Comment by KeithSloan** [comment]
Okay fixed by using the version of Python installed in FreeCAD.

/Applications/FreeCAD.app/Contents/Resources/bin/python -m pip install --upgrade numba

**Comment by stuartarchibald** [comment]
> Okay fixed by using the version of Python installed in FreeCAD.
> 
> /Applications/FreeCAD.app/Contents/Resources/bin/python -m pip install --upgrade numba

Thanks for confirming. Closing this as resolved.
