### ISSUE TITLE
`List.empty_list(Item)` will not work if `Item` is a `jitclass``

### ISSUE THREAD

**Issue by Acmion** [numba/numba#8733]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Creating an empty typed list with `List.empty_list(Item)` will not work if `Item` is a `jitclass`.

Consider the following code:
```py
import numba as nb
from numba.typed.typedlist import List
from numba.experimental import jitclass

@jitclass
class Item:
    a: nb.int64
    def __init__(self, a):
        self.a = a

@jitclass
class ContainerJitClass:
    data: List[Item]

    def __init__(self):
        self.data = List.empty_list(Item)

@jitclass
class ContainerPrimitive:
    data: List[nb.int64]

    def __init__(self):
        self.data = List.empty_list(nb.int64)
```

With this code one would assume that running the following functions would be ok:

```py
@nb.njit
def f0():
    print(ContainerJitClass().data)
    
@nb.njit
def f1():
    print(ContainerPrimitive().data)
```

Calling `f0()` will error and yield this:
```
Failed in nopython mode pipeline (step: native lowering)
Cannot cast ListType[jitclass.Item#19c19a70af0<a:int64>] to ListType[instance.jitclass.Item#19c19a70af0<a:int64>]: %"inserted.data.1" = insertvalue {i8*, i8*} %"inserted.meminfo.1", i8* %".23", 1
During: lowering "(self).data = $8call_method.3" at D:\dev.py (37)
During: resolving callee type: jitclass.ContainerJitClass#19c19ae4460<data:ListType[instance.jitclass.Item#19c19a70af0<a:int64>]>
```

Calling `f1()` will work just fine. In other words, `List.empty_list(Item)` will not work if `Item` is a `jitclass`. 

### Workaround

The issue can in most cases be worked around with this, but the fix is quite ugly:
```py
@jitclass
class ContainerJitClassFixed:
    data: List[Item]

    def __init__(self):
        l = List()
        l.append(Item(10))
        l.clear()

        self.data = l
```

Now calling this function will work:

```py
@nb.njit
def f2():
    print(ContainerJitClassFixed().data)
```

Calling `List.empty_list(Item)` should work even if `Item` is a `jitclass`. This is important, because it may not always be possible to use the workaround as the class must be initialized with "somewhat" correct data.

## Related Issues

https://github.com/numba/numba/issues/7291 [CLOSED] unable to use List.empty_list of type jitclass or deferred_type in jitclass.__init__

https://github.com/numba/numba/issues/5873 [OPEN] Implement type key-word-argument for numba.typed.List constructor 

## Considerations

This issue can probably be closed if https://github.com/numba/numba/issues/7291 is reopened, which was closed by the original author. Furthermore, the issue also discusses reference deferred types, which is not exactly what the core issue here is.

**Comment by guilhermeleobas** [comment]
Hi @Acmion, thanks for the report. 

Although I can reproduce the original error you reported, the proposed fix also crashes Numba for me due to the type hint. Nevertheless, I think there are two errors happening here:

1. Using Python 3 typing hints doesn't work that well with typed containers.
```python
from numba.typed import typedlist
from numba.core import types
@jitclass
class Foo:
    data: typedlist.List[types.int64]

    def __init__(self):
        ...

$ python example.py
Traceback (most recent call last):
  File "/Users/guilhermeleobas/git/numba/a.py", line 24, in <module>
    class Foo:
  File "/Users/guilhermeleobas/git/numba/numba/experimental/jitclass/decorators.py", line 88, in jitclass
    return wrap(cls_or_spec)
  File "/Users/guilhermeleobas/git/numba/numba/experimental/jitclass/decorators.py", line 77, in wrap
    cls_jitted = register_class_type(cls, spec, types.ClassType,
  File "/Users/guilhermeleobas/git/numba/numba/experimental/jitclass/base.py", line 180, in register_class_type
    spec[attr] = as_numba_type(py_type)
  File "/Users/guilhermeleobas/git/numba/numba/core/typing/asnumbatype.py", line 121, in __call__
    return self.infer(py_type)
  File "/Users/guilhermeleobas/git/numba/numba/core/typing/asnumbatype.py", line 115, in infer
    raise errors.TypingError(
numba.core.errors.TypingError: Cannot infer numba type of python type numba.typed.typedlist.List[int64]
```

2. Typed containers don't support jitclasses. 

The following works for me:
```python
from numba import njit
from numba.typed.typedlist import List
from numba.core import types
from numba.experimental import jitclass
from numba import typeof

@jitclass
class Item:
    a: types.int64

    def __init__(self, a):
        self.a = a

l = List()
l.append(Item(1))

@jitclass([('data', typeof(l))])
class ContainerJitClassFixed:
    data: List[Item]

    def __init__(self):
        l = List()
        l.append(Item(10))
        l.clear()

        self.data = l

@njit
def f2():
    print(ContainerJitClassFixed().data)

f2()
```

**Comment by Acmion** [comment]
Aah, you are quite right. I was trying to circumvent this issue and registered a custom `as_numba_type` function, which I forgot to disable. Like this:

```py
import typing

import numba as nb
from numba.core.types import ListType
from numba.core.typing.asnumbatype import as_numba_type
from numba.experimental import jitclass
from numba.typed.typedlist import List

@as_numba_type.register
def numba_type_converter_typed_list(py_type):
    origin = typing.get_origin(py_type)

    try:
        if issubclass(origin, List):
            item_type = typing.get_args(py_type)[0]

            return ListType(as_numba_type.infer(item_type))

    except:
        return None

@jitclass
class Item:
    a: nb.int64
    def __init__(self, a):
        self.a = a

@jitclass
class ContainerJitClass:
    data: List[Item]

    def __init__(self):
        self.data = List.empty_list(Item)

@jitclass
class ContainerPrimitive:
    data: List[nb.int64]

    def __init__(self):
        self.data = List.empty_list(nb.int64)


@jitclass
class ContainerJitClassFixed:
    data: List[Item]

    def __init__(self):
        l = List()
        l.append(Item(10))
        l.clear()

        self.data = l

@nb.njit
def f0():
    print(ContainerJitClass().data)
    
@nb.njit
def f1():
    print(ContainerPrimitive().data)

@nb.njit
def f2():
    print(ContainerJitClassFixed().data)

# f0() # => fails
f1() # => OK
f2() # => OK
```
Maybe the custom `as_numba_type.register` function can be of use to someone else as well (although the `try: ... except: ...` should probably be implemented more elegantly). At the very least I can circumvent the usage of specs and just rely on python type hints (which I like better).

**Comment by Acmion** [comment]
@guilhermeleobas 

I edited and split this issue into two, to better reflect the actual problems. 

The other issue can now be found here: https://github.com/numba/numba/issues/8734
