### ISSUE TITLE
Inconsistent error state with numpy for zero division

### ISSUE THREAD

**Issue by haiiliin** [numba/numba#8743]
## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

In numpy, the default error state for zero division is `warn` which will raise a warning instead of an error when zero division:
```python
>>> import numpy as np
>>> np.geterr()
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
>>> 1.0 / np.float64(0.0)

Warning (from warnings module):
  File "<pyshell#13>", line 1
RuntimeWarning: divide by zero encountered in double_scalars
inf
```
In numba, an error will be raised by default:
```python
>>> import numba
>>> @numba.njit
... def test_numba_zero_division():
...     print(1.0/np.float64(0.0))

>>> test_numba_zero_division()
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    test_numba_zero_division()
ZeroDivisionError: division by zero
```

Is it a bug?

**Comment by gmarkall** [comment]
xref for general reference: https://github.com/numba/numba/issues/8700

**Comment by stuartarchibald** [comment]
I don't think this is a bug in so much as it was never intended or expected to work. Perhaps it would be good to note this in the documentation associated with Numba's NumPy support.

I think there's a two separate things here:
1. In Numba division such as `python float type / np.float64 type` will still use the CPython semantics of raising if there's a divide by zero. Two options to work around this 1) set the error model e.g. `@njit(error_model='numpy')` which ignores divide by zero in such operations, 2) where divide by zero should not be considered use `np.divide` opposed to the `/` builtin, e.g. `np.divide(1.0, np.float64(0.0))`.
2. The state associated with `np.geterr` etc is not supported and whilst theoretically possible to support, it would be incredibly challenging to implement correctly/in a way that replicates what NumPy does.

**Comment by haiiliin** [comment]
> 1) set the error model e.g. `@njit(error_model='numpy')` which ignores divide by zero in such operations

This seems to be a solution for me, thanks!
