### ISSUE TITLE
Memory overwriting other memory issue?

### ISSUE THREAD

**Issue by mtalha123** [numba/numba#8753]
## Reporting a bug

Take this piece of code:
```
import numba

@numba.njit
def foo():
  lst1 = [[1,2,3,4,5], [6,7,8,9,10]]

  for i in range(300):
    lst2 = []
    lst2.append(1)

    del lst1[1]
    del lst1[0]

    lst1.append([1,2,3,4,5])
    lst1.append([6,7,8,9,10])

    if len(lst2) > 1:
      print("This should never print!")
      print("Length of lst2(should not ever be greater than 1): ", len(lst2))

for i in range(200):
  foo()
```
If you run this, you will get that sometimes the prints happen even though they shouldn't. 'lst2' should never have length more than 1 since it only gets appended to once and then reset in each iteration. It seems that appending to lst1 is somehow "interfering" with lst2. My suspicion is some kind of memory problem where 'lst1' appending is overwriting other memory? But I am not sure.. When I run this, the length of lst2 somehow ends up being 5 sometimes which is super weird.. Thank you for the help!

**Comment by gmarkall** [comment]
Thanks for the report and reproducer. For me this causes an error in `malloc()`:

```
$ python repro.py 
malloc(): unaligned tcache chunk detected
Aborted (core dumped)
```

with the following trace:

```
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=139688940967744) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=139688940967744) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=139688940967744, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007f0bddb8e476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007f0bddb747f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007f0bddbd56f6 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7f0bddd27b8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007f0bddbecd7c in malloc_printerr (str=str@entry=0x7f0bddd2ad40 "malloc(): unaligned tcache chunk detected") at ./malloc/malloc.c:5664
#7  0x00007f0bddbf145c in tcache_get (tc_idx=<optimised out>) at ./malloc/malloc.c:3195
#8  __GI___libc_malloc (bytes=48) at ./malloc/malloc.c:3313
#9  0x00007f0b9e517290 in NRT_MemInfo_new_varsize_dtor () from /home/gmarkall/numbadev/numba/numba/core/runtime/_nrt_python.cpython-310-x86_64-linux-gnu.so
#10 0x00007f0b9e490263 in __main__::foo[abi:v1][abi:c8tJTIcFHzwl2ILiXkcBV0KBSgP9CGZpAgA_3d] ()
#11 0x00007f0b9e490b2e in cpython::__main__::foo[abi:v1][abi:c8tJTIcFHzwl2ILiXkcBV0KBSgP9CGZpAgA_3d] ()
#12 0x00007f0b980f9248 in call_cfunc(Dispatcher*, _object*, _object*, _object*, _object*) () from /home/gmarkall/numbadev/numba/numba/_dispatcher.cpython-310-x86_64-linux-gnu.so
#13 0x00007f0b980f9fdd in Dispatcher_call(Dispatcher*, _object*, _object*) () from /home/gmarkall/numbadev/numba/numba/_dispatcher.cpython-310-x86_64-linux-gnu.so
...
```

I have not yet looked into this further but this kind of issue feels familiar - I think someone else may know more off the top of their head and I'll bring this up at the triage or dev meeting tomorrow.

**Comment by mtalha123** [comment]
Okay thank you!

**Comment by gmarkall** [comment]
From the triage meeting - the reflected list implementation is in use here. I will try with the Typed List API to see if a similar issue occurs.

**Comment by stuartarchibald** [comment]
MWR:
```python
from numba import njit

@njit
def foo():
    lst1 = [[1,],]
    x = [10,]
    for i in range(300):
        # lst1.pop(0) also does the same, `__delitem__` is just a call to this.
        del lst1[0]
        lst1.append(x)

foo()
```

**Comment by stuartarchibald** [comment]
#8757 hopefully fixes this.
