### ISSUE TITLE
jitclass doesn't work when dict class attribute has array as value type

### ISSUE THREAD

**Issue by dstansby** [numba/numba#8808]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Trying to `jitclass` a class that has a `Dict` attribute with an array as the value type fails. Code and traceback below. Removing `jitclass` results in code that runs fine.

```python
import numpy as np
from numba import int64
from numba.experimental import jitclass
from numba.typed import Dict
from numba.types import DictType


@jitclass(
    [
        ("dict", DictType(int64, int64[:, :])),
    ]
)
class StructureManager:
    def __init__(self):
        self.dict = Dict.empty(key_type=int64, value_type=int64[:, :])


s = StructureManager()
s.dict[0] = np.zeros((2, 2), dtype=int)
```

```python
Traceback (most recent call last):
  File "/Users/dstansby/projects/brainglobe/cellfinder-core/test.py", line 18, in <module>
    s = StructureManager()
  File "/Users/dstansby/mambaforge/envs/cellfinder-core/lib/python3.10/site-packages/numba/experimental/jitclass/base.py", line 124, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/Users/dstansby/mambaforge/envs/cellfinder-core/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/dstansby/mambaforge/envs/cellfinder-core/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function getitem>) found for signature:
 
 >>> getitem(class(int64), UniTuple(slice<a:b> x 2))
 
There are 22 candidate implementations:
  - Of which 22 did not match due to:
  Overload of function 'getitem': File: <numerous>: Line N/A.
    With argument(s): '(class(int64), UniTuple(slice<a:b> x 2))':
   No match.

During: typing of intrinsic-call at /Users/dstansby/projects/brainglobe/cellfinder-core/test.py (15)
During: typing of static-get-item at /Users/dstansby/projects/brainglobe/cellfinder-core/test.py (15)

File "test.py", line 15:
    def __init__(self):
        self.dict = Dict.empty(key_type=int64, value_type=int64[:, :])
        ^

During: resolving callee type: jitclass.StructureManager#115e0b7f0<dict:DictType[int64,array(int64, 2d, A)]<iv=None>>
During: typing of call at <string> (3)

During: resolving callee type: jitclass.StructureManager#115e0b7f0<dict:DictType[int64,array(int64, 2d, A)]<iv=None>>
During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by apmasell** [comment]
Unfortunately, use of `int64[:, :]` style type declarations inside JITted code does not work. You can hoist that definition outside the JIT region like this:

```
vt = int64[:, :]
@jitclass(
    [
        ("dict", DictType(int64, vt)),
    ]
)
class StructureManager:
    def __init__(self):
        self.dict = Dict.empty(key_type=int64, value_type=vt)
```
