### ISSUE TITLE
TypedDict tries to cast uint keys to float and fails

### ISSUE THREAD

**Issue by dstansby** [numba/numba#8829]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I am trying to index a `TypeDict[uint64, uint64]`, but somewhere internally numba is trying to cast an int to a float, which is causing an error. Example and error listed below.

```python
from numba import njit
from numba.core import types
from numba.typed import Dict


@njit
def foo():
    # Make dictionary
    d = Dict.empty(
        key_type=types.uint64,
        value_type=types.uint64,
    )
    d[1] = 2
    d[2] = 3
    d[3] = 4

    a = 1
    while a in d:
        a = d[a]

    return a


if __name__ == "__main__":
    foo()
```

```python
% python test.py  
Traceback (most recent call last):
  File "/Users/dstansby/projects/brainglobe/cellfinder-core/test.py", line 25, in <module>
    foo()
  File "/Users/dstansby/mambaforge/envs/brainglobe/lib/python3.10/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/Users/dstansby/mambaforge/envs/brainglobe/lib/python3.10/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<intrinsic _cast>) found for signature:
 
 >>> _cast(float64, class(uint64))
 
There are 2 candidate implementations:
      - Of which 2 did not match due to:
      Intrinsic in function '_cast': File: numba/typed/typedobjectutils.py: Line 22.
        With argument(s): '(float64, class(uint64))':
       Rejected as the implementation raised a specific error:
         TypingError: cannot safely cast float64 to uint64. Please cast explicitly.
  raised from /Users/dstansby/mambaforge/envs/brainglobe/lib/python3.10/site-packages/numba/typed/typedobjectutils.py:75

During: resolving callee type: Function(<intrinsic _cast>)
During: typing of call at /Users/dstansby/mambaforge/envs/brainglobe/lib/python3.10/site-packages/numba/typed/dictobject.py (757)


File "../../../mambaforge/envs/brainglobe/lib/python3.10/site-packages/numba/typed/dictobject.py", line 757:
    def impl(d, key):
        castedkey = _cast(key, keyty)
        ^

During: typing of intrinsic-call at /Users/dstansby/projects/brainglobe/cellfinder-core/test.py (19)

File "test.py", line 19:
def foo():
    <source elided>
    while a in d:
        a = d[a]
        ^
```

**Comment by dstansby** [comment]
It looks like the while loop is the issue here - just returning `d[a]` from the function works fine.

**Comment by dstansby** [comment]
It also looks like this works fine when the dict key and value types are set to `types.int64`, so seems to be an issue specific to uint64.

**Comment by gmarkall** [comment]
The type of a literal `1` is of type `int64`. `int64` and `uint64` unify to `float64` (in the membership check), because that is the only type whose range spans the range of both `int64` and `uint64` (albeit with less precision). If you use a `uint64` for `a` instead, you should get the expected result:

```python
from numba import njit
from numba.core import types
from numba.typed import Dict


@njit
def foo():
    # Make dictionary
    d = Dict.empty(
        key_type=types.uint64,
        value_type=types.uint64,
    )
    d[1] = 2
    d[2] = 3
    d[3] = 4

    a = types.uint64(1)
    while a in d:
        a = d[a]

    return a


if __name__ == "__main__":
    print(foo())
```

```
$ python repro.py 
/home/gmarkall/numbadev/issues/8829/repro.py:13: NumbaTypeSafetyWarning: unsafe cast from int64 to uint64. Precision may be lost.
  d[1] = 2
4
```

**Comment by dstansby** [comment]
👍 I think this has been explained, so closing
