### ISSUE TITLE
TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'

### ISSUE THREAD

**Issue by husqD** [numba/numba#8850]
When I use the compiler on a windows computer with python 3.10 and virtuealenv I get this error:
TypeError: CCompiler_spawn() got an unexpected keyword argument 'env'.

On macOS it works fine.

**Comment by sklam** [comment]
Thanks for the report. Can you provide more information on how to trigger the reported error?

**Comment by husqD** [comment]
Okey, I have created a small example.

Operative system: Windows 10
Python version: Python 3.10.10 
Virutalenv version: virtualenv 20.21.0 
numba version: 0.56.4

Folder tree: 
- venv
- requirements.txt
- main.py

main.py code:
```python
from numba.pycc import CC

cc = CC('my_module')
# Uncomment the following line to print out the compilation steps
#cc.verbose = True

@cc.export('multf', 'f8(f8, f8)')
@cc.export('multi', 'i4(i4, i4)')
def mult(a, b):
    return a * b

@cc.export('square', 'f8(f8)')
def square(a):
    return a ** 2

if __name__ == "__main__":
    cc.compile()
```

Error executing main.py inside virtualenv:
````
Collecting numba
  Using cached numba-0.56.4-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting llvmlite<0.40,>=0.39.0dev0
  Using cached llvmlite-0.39.1-cp310-cp310-win_amd64.whl (23.2 MB)
Collecting numpy<1.24,>=1.18
  Using cached numpy-1.23.5-cp310-cp310-win_amd64.whl (14.6 MB)
Requirement already satisfied: setuptools in c:\users\xxxx\test_numba\venv\lib\site-packages (from numba->-r requirements.txt (line 1)) (67.5.1)
Installing collected packages: numpy, llvmlite, numba
Successfully installed llvmlite-0.39.1 numba-0.56.4 numpy-1.23.5
(venv) PS C:\Users\xxxx\test_numba> python main.py
Traceback (most recent call last):
  File "C:\Users\xxxx\test_numba\venv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 419, in compile
    self.spawn(args)
  File "C:\Users\xxxx\test_numba\venv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 517, in spawn
    return super().spawn(cmd, env=env)
  File "C:\Users\xxxxxxxx\test_numba\venv\lib\site-packages\numpy\distutils\ccompiler.py", line 89, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "C:\Users\xxxxx\test_numba\venv\lib\site-packages\numpy\distutils\ccompiler.py", line 180, in CCompiler_spawn
    raise DistutilsExecError('Command "%s" failed with exit status %d%s' %
distutils.errors.DistutilsExecError: Command "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPYCC_MODULE_NAME=my_module -DPYCC_USE_NRT=1 -IC:\Users\xxxx\test_numba\venv\include -IC:\Program Files\Python310\include -IC:\Program Files\Python310\Include -IC:\\Users\\xxx\test_numba\venv\lib\site-packages\numba\pycc\modulemixin.obj" failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxxxxx\test_numba\main.py", line 17, in <module>
    cc.compile()
  File "C:\Users\xxx\test_numba\venv\lib\site-packages\numba\core\compiler_lock.py", 
line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\xxxx\test_numba\venv\lib\site-packages\numba\pycc\cc.py", line 221, in compile
    objects += self._compile_mixins(build_dir)
  File "C:\Users\xxxx\test_numba\venv\lib\site-packages\numba\pycc\cc.py", line 191, in _compile_mixins
  File "C:\Users\xxxx\test_numba\venv\lib\site-packages\numba\pycc\platform.py", line 
137, in compile_objects
    objects = self._compiler.compile(sources,
  File "C:\Users\xxxx\test_numba\venv\lib\site-packages\setuptools\_distutils\_msvccompiler.py", line 421, in compile
    raise CompileError(msg)
distutils.errors.CompileError: Command "C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX86\x64\cl.exe /c /nologo /O2 /W3 /GL /DNDEBUG /MD -DPYCC_MODULE_NAME=my_module -DPYCC_USE_NRT=1 -IC:\Users\xxx\Escritorio\PROgram Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.xxx6\ATLMFC\include -IC:\Program Files\Microsoft Visual Studio\2022\Communit10.0.19041.0\ucrt -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.19041.0\\shared -IC:\Program Files (x86)\Windows Kits\10\\include\10.0.190En línea: 1 Carácter: 1                                                                               )\Windows Kits\10\\include\10.0.19041.0\\cppw
+ pyhton --version                                                                                    \site-packages\numba\pycc\modulemixin.c /FoC:
+ ~~~~~~                                                                                              e Córdoba\Escritorio\PROGRAMACION\test_numba\
    + CategoryInfo          : ObjectNotFound: (pyhton:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException    
````
