### ISSUE TITLE
Feature: support compilation caching for CUDA target

### ISSUE THREAD

**Issue by shaunc** [numba/numba#8888]
## Feature request

As mentioned here: https://numba.discourse.group/t/cuda-jit-is-there-cache-true/163/4

there is no caching for CUDA jit compilation. To confirm in most recent CUDA, when I try, I get:
```sh
    def _reduce_states(self):
        """
        Reduce the instance for serialization. We retain the PTX and cubins,
        but loaded functions are discarded. They are recreated when needed
        after deserialization.
        """
        if self._linking_files:
            msg = 'Cannot pickle CUDACodeLibrary with linking files'
>           raise RuntimeError(msg)
E           RuntimeError: Cannot pickle CUDACodeLibrary with linking files
```

Our test suite now has >60 kernels for unit testing device functions. Many are taking ~5-10 sec to compile, so this is becoming a big issue for us.

**Comment by shaunc** [comment]
I'm using neither.

The kernel call tree is rather large (for me to post as an example) - is there a way to get more info about what is causing external files to be included?

**Comment by shaunc** [comment]
Hmm.... I'm unfortunately not very familiar with using source builds. After clone of your branch & switch to top level, I get:
```sh
$ sudo /usr/local/anaconda3/bin/python setup.py install
[... snip ...]

creating dist
creating 'dist/numba-0.15.1+19906.g2e5141073-py3.9-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing numba-0.15.1+19906.g2e5141073-py3.9-linux-x86_64.egg
creating /usr/local/anaconda3/lib/python3.9/site-packages/numba-0.15.1+19906.g2e5141073-py3.9-linux-x86_64.egg
Extracting numba-0.15.1+19906.g2e5141073-py3.9-linux-x86_64.egg to /usr/local/anaconda3/lib/python3.9/site-packages
Adding numba 0.15.1+19906.g2e5141073 to easy-install.pth file
Installing numba script to /usr/local/anaconda3/bin

Installed /usr/local/anaconda3/lib/python3.9/site-packages/numba-0.15.1+19906.g2e5141073-py3.9-linux-x86_64.egg
Processing dependencies for numba==0.15.1+19906.g2e5141073
Searching for llvmlite<0.41,>=0.40.0dev0
Reading https://pypi.org/simple/llvmlite/
/usr/local/anaconda3/lib/python3.9/site-packages/pkg_resources/__init__.py:122: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
Downloading https://files.pythonhosted.org/packages/8e/9a/726dfd82bf4e94d45f9fc450ca4ea20a7aab175f763bd15f80cb019a3518/llvmlite-0.40.0rc1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl#sha256=ff3de4551c91cf4016e49182050b90f08501c498538d3f47c6d2bd5d15225345
Best match: llvmlite 0.40.0rc1
Processing llvmlite-0.40.0rc1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
Installing llvmlite-0.40.0rc1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl to /usr/local/anaconda3/lib/python3.9/site-packages
Adding llvmlite 0.40.0rc1 to easy-install.pth file

Installed /usr/local/anaconda3/lib/python3.9/site-packages/llvmlite-0.40.0rc1-py3.9-linux-x86_64.egg
Searching for numpy==1.21.5
Best match: numpy 1.21.5
Adding numpy 1.21.5 to easy-install.pth file
Installing f2py script to /usr/local/anaconda3/bin
Installing f2py3 script to /usr/local/anaconda3/bin
Installing f2py3.9 script to /usr/local/anaconda3/bin

Using /usr/local/anaconda3/lib/python3.9/site-packages
Finished processing dependencies for numba==0.15.1+19906.g2e5141073
(base) shauncutts@silk:~/src/numba_cache_cg$ code test.py
(base) shauncutts@silk:~/src/numba_cache_cg$ time python test.py 
Traceback (most recent call last):
  File "/home/shauncutts/src/numba_cache_cg/numba/core/typeconv/typeconv.py", line 4, in <module>
    from numba.core.typeconv import _typeconv
ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (/home/shauncutts/src/numba_cache_cg/numba/core/typeconv/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shauncutts/src/numba_cache_cg/test.py", line 1, in <module>
    import numba as nb  # type: ignore
  File "/home/shauncutts/src/numba_cache_cg/numba/__init__.py", line 72, in <module>
    from numba.misc.special import (
  File "/home/shauncutts/src/numba_cache_cg/numba/misc/special.py", line 3, in <module>
    from numba.core.typing.typeof import typeof
  File "/home/shauncutts/src/numba_cache_cg/numba/core/typing/__init__.py", line 1, in <module>
    from .context import BaseContext, Context
  File "/home/shauncutts/src/numba_cache_cg/numba/core/typing/context.py", line 11, in <module>
    from numba.core.typeconv import Conversion, rules
  File "/home/shauncutts/src/numba_cache_cg/numba/core/typeconv/rules.py", line 2, in <module>
    from .typeconv import TypeManager, TypeCastingRules
  File "/home/shauncutts/src/numba_cache_cg/numba/core/typeconv/typeconv.py", line 16, in <module>
    raise ImportError(msg)
ImportError: Numba could not be imported.
--------------------------------------------------------------------------------
If you are seeing this message and are undertaking Numba development work, you may need to rebuild Numba.
Please see the development set up guide:

https://numba.readthedocs.io/en/stable/developer/contributing.html.

--------------------------------------------------------------------------------
If you are not working on Numba development, the original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (/home/shauncutts/src/numba_cache_cg/numba/core/typeconv/__init__.py)'.
For help, please visit:

https://numba.readthedocs.io/en/stable/user/faq.html#numba-could-not-be-imported


real    0m0.504s
user    0m0.386s
sys     0m0.045s
(base) shauncutts@silk:~/src/numba_cache_cg$ which python
/usr/local/anaconda3/bin/python
(base) shauncutts@silk:~/src/numba_cache_cg$ ipython
Python 3.9.12 (main, Apr  5 2022, 06:56:58) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import numba
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
File ~/src/numba_cache_cg/numba/core/typeconv/typeconv.py:4, in <module>
      1 try:
      2     # This is usually the the first C extension import performed when importing
      3     # Numba, if it fails to import, provide some feedback
----> 4     from numba.core.typeconv import _typeconv
      5 except ImportError as e:

ImportError: cannot import name '_typeconv' from 'numba.core.typeconv' (/home/shauncutts/src/numba_cache_cg/numba/core/typeconv/__init__.py)

During handling of the above exception, another exception occurred:

ImportError                               Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 import numba

File ~/src/numba_cache_cg/numba/__init__.py:72, in <module>
     69 from numba.core import types, errors
     71 # Re-export typeof
---> 72 from numba.misc.special import (
     73     typeof, prange, pndindex, gdb, gdb_breakpoint, gdb_init,
     74     literally, literal_unroll,
     75 )
     77 # Re-export error classes
     78 from numba.core.errors import *

File ~/src/numba_cache_cg/numba/misc/special.py:3, in <module>
      1 import numpy as np
----> 3 from numba.core.typing.typeof import typeof
      4 from numba.core.typing.asnumbatype import as_numba_type
      7 def pndindex(*args):

File ~/src/numba_cache_cg/numba/core/typing/__init__.py:1, in <module>
----> 1 from .context import BaseContext, Context
      2 from .templates import (signature, make_concrete_template, Signature,
      3                         fold_arguments)

File ~/src/numba_cache_cg/numba/core/typing/context.py:11, in <module>
      9 import numba
     10 from numba.core import types, errors
---> 11 from numba.core.typeconv import Conversion, rules
     12 from numba.core.typing import templates
     13 from numba.core.utils import order_by_target_specificity

File ~/src/numba_cache_cg/numba/core/typeconv/rules.py:2, in <module>
      1 import itertools
----> 2 from .typeconv import TypeManager, TypeCastingRules
      3 from numba.core import types
      6 default_type_manager = TypeManager()

File ~/src/numba_cache_cg/numba/core/typeconv/typeconv.py:16, in <module>
      9     dashes = '-' * 80
     10     msg = (f"Numba could not be imported.\n{dashes}\nIf you are seeing this "
     11            "message and are undertaking Numba development work, you may need "
     12            "to rebuild Numba.\nPlease see the development set up guide:\n\n"
     13            f"{dev_url}.\n\n{dashes}\nIf you are not working on Numba "
     14            f"development, the original error was: '{str(e)}'.\nFor help, "
     15            f"please visit:\n\n{user_url}\n")
---> 16     raise ImportError(msg)
     18 from numba.core.typeconv import castgraph, Conversion
     19 from numba.core import types

ImportError: Numba could not be imported.
--------------------------------------------------------------------------------
If you are seeing this message and are undertaking Numba development work, you may need to rebuild Numba.
Please see the development set up guide:

https://numba.readthedocs.io/en/stable/developer/contributing.html.

--------------------------------------------------------------------------------
If you are not working on Numba development, the original error was: 'cannot import name '_typeconv' from 'numba.core.typeconv' (/home/shauncutts/src/numba_cache_cg/numba/core/typeconv/__init__.py)'.
For help, please visit:

https://numba.readthedocs.io/en/stable/user/faq.html#numba-could-not-be-imported

(base) shauncutts@silk:~/src/numba_cache_cg$ python -c 'import sys; print(sys.executable)'
/usr/local/anaconda3/bin/python
```

**Comment by gmarkall** [comment]
Thanks for the info - I think one problem is that you need the llvmlite RC to be able to build Numba from source, so I think if you did something like 

```
pip install --pre llvmlite
```

you should get llvmlite 0.40.0rc1 installed, then I think you can install from source with pip using:

```
pip install git+https://github.com/gmarkall/numba.git@issue-8888-cg
```

This should be done in an environment that doesn't already have llvmlite or Numba installed.

**Comment by gmarkall** [comment]
> Perhaps we could have an option (default w/ warning?) to exclude linked files? The doc already says that cache might not detect change in libraries.

I just noticed https://github.com/numba/numba/pull/8396 is making progress towards fixing this.

**Comment by shaunc** [comment]
Great -- solved the install problem simply using pip in venv. Now get significant speedup: 13.68s -> 1.52s.  :) Thanks!

One fly in the ointment is I guess any change to file where kernel is seems to invalidate, even if the kernel itself doesn't change. I can work around this somewhat I think.

Out of curiousity, if device functions are cached, is the code read from the cached version and linked, or are the caches only per kernel?

... The issue is solved though - you are welcome to close. Hopefully it can get swept up into the 0.57 release? 😁 ?

```
========================================== slowest 5 durations ===========================================
13.68s call     tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[2_levels]
0.09s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cluster_2_levels]
0.06s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cross_2_x_samples]
0.05s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cross_2]
0.05s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[2_levels]
=========================================== 4 passed in 15.40s ===========================================

Change detected: tests/context/cuda/adapt/cluster/test_prepare.py

[Thu Apr 13 00:17:14 2023] Running: py.test --last-failed --new-first -s --cuda tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters -x -vv --durations 5
========================================== test session starts ===========================================
platform linux -- Python 3.9.12, pytest-7.3.0, pluggy-1.0.0 -- /home/shauncutts/.cache/pypoetry/virtualenvs/timbuktu-6r8-oA4b-py3.9/bin/python
cachedir: .pytest_cache
rootdir: /home/shauncutts/src/factfiber.ai/learn/timbuktu
configfile: pyproject.toml
plugins: snapshot-0.9.0, cov-4.0.0, cases-3.6.14
collected 4 items                                                                                        
run-last-failure: no previously failed tests, not deselecting items.

tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[2_levels] PASSED
tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cross_2] PASSED
tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cross_2_x_samples] PASSED
tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cluster_2_levels] PASSED

========================================== slowest 5 durations ===========================================
1.52s call     tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[2_levels]
0.09s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cluster_2_levels]
0.06s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cross_2_x_samples]
0.05s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[2_levels]
0.05s setup    tests/context/cuda/adapt/cluster/test_optimize.py::test_optimize_clusters[cross_2]
=========================================== 4 passed in 3.23s ============================================
```

**Comment by gmarkall** [comment]
> Great -- solved the install problem simply using pip in venv. Now get significant speedup: 13.68s -> 1.52s. :) Thanks!

You're welcome - thanks for helping to improve Numba!

> One fly in the ointment is I guess any change to file where kernel is seems to invalidate, even if the kernel itself doesn't change. I can work around this somewhat I think.

It's a bit unfortunate, but comparing file modification times is part of how Numba determines the cache is valid.

> Out of curiousity, if device functions are cached, is the code read from the cached version and linked, or are the caches only per kernel?

The caches are only per kernel, and the finally-linked cubin including all called device functions are cached.

> ... The issue is solved though - you are welcome to close.

Thanks - I might leave this open and mark #8895 as fixing this, since it turned out the be the root of your issue.

> Hopefully it can get swept up into the 0.57 release? grin ?

I think that's going to be hard - 0.57 has already dragged on, some Numba maintainers are away this week, the PR hasn't been reviewed yet, and it does slightly change the way the CUDA codegen and dispatcher work, so there are quite a lot of factors stacking against that happening. :cry:
