### ISSUE TITLE
jitclass reflected dunder methods do not work in a njit function

### ISSUE THREAD

**Issue by nathanmoore** [numba/numba#8934]
## Reporting a bug

- [X] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This was tested on 0.57.0rc1 with PR #8906 applied locally.

The reflected dunder methods are not considered when compiling a function that uses a jitclass object. They are used when a jitclass method is called via the interpreter. 

```
import numba

@numba.experimental.jitclass([("value", numba.types.float64),])
class ValueHolder:
    def __init__(self, v):
        self. Value = v
   
    def __radd__(self, lhs):
        return ValueHolder(lhs + self. Value)
    
def on_the_right():
    v = ValueHolder(1.0)
    return 1.0 + v


on_the_right().value  # == 2.0

numba.njit(on_the_right)().value   # fail!
```
```
Traceback (most recent call last):
  File "C:\Users\nate\OneDrive\Documents\numba_issue.py", line 18, in <module>
    numba.njit(on_the_right)().value   # fail!
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nate\miniconda3\envs\numbarc\Lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\nate\miniconda3\envs\numbarc\Lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function add>) found for signature:

 >>> add(float64, instance.jitclass.ValueHolder#183f93a2450<value:float64>)

There are 20 candidate implementations:
  - Of which 18 did not match due to:
  Overload of function 'add': File: <numerous>: Line N/A.
    With argument(s): '(float64, instance.jitclass.ValueHolder#183f93a2450<value:float64>)':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'add': File: unknown: Line unknown.
    With argument(s): '(float64, instance.jitclass.ValueHolder#183f93a2450<value:float64>)':
   No match for registered cases:
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64
    * (float32, float32) -> float32
    * (float64, float64) -> float64
    * (complex64, complex64) -> complex64
    * (complex128, complex128) -> complex128

During: typing of intrinsic-call at C:\Users\nate\OneDrive\Documents\numba_issue.py (13)

File "numba_issue.py", line 13:
def on_the_right():
    <source elided>
    v = ValueHolder(1.0)
    return 1.0 + v
```

This can be worked around by implementing operator.add for the jitclass.
```
@numba.extending.overload(operator.add)
def _fix_radd(lhs, rhs):
    if isinstance(lhs, (numba.types.Integer, numba.types.Float)) and rhs == numba.extending.as_numba_type(ValueHolder):
        return lambda lhs, rhs: rhs.__radd__(lhs)
```

**Comment by stuartarchibald** [comment]
Thanks for the report. This (and similar) reproduces locally. The issue is that Numba's "binop" implementations (and quite a few other fundamental numerical operations) are not currently aware of object based methods as an implementation detail i.e. `operator.add` doesn't "know" about using `__add__`/`__radd__`.

**Comment by stuartarchibald** [comment]
I suggest a temporary "fix" is to note this limitation in the docs, will discuss this at the maintainers meeting tomorrow.

**Comment by iperov** [comment]
jesus, half year ago and still no fix :-\\
I am going to use direct C++ compilation using portable c++ compiler from ziglang. Stable and future-proof alternative for numba.
