### ISSUE TITLE
Regression: NameError: name 'unsafe_empty_inferred' is not defined

### ISSUE THREAD

**Issue by sk1p** [numba/numba#8940]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

The following reproducer crashes with numba 0.57.0:

```python
import numba
import numpy as np

# uncomment one of these lines to work around the problem:
# import numba.np.unsafe.ndarray
# import numba.cuda  # indirectly imports numba.np.unsafe.ndarray

@numba.njit()
def _fn():
    np.array([1 for _ in range(1)])

_fn()
```

Backtrace: 

```
Traceback (most recent call last):
  File "/home/alex/numba-debug/minmin.py", line 12, in <module>
    _fn()
  File "/home/alex/source/numba/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/alex/source/numba/numba/core/dispatcher.py", line 407, in error_rewrite
    raise e
  File "/home/alex/source/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/dispatcher.py", line 129, in compile
    raise retval
  File "/home/alex/source/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/compiler.py", line 742, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/compiler.py", line 460, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/compiler.py", line 528, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/compiler.py", line 507, in _compile_core
    raise e
  File "/home/alex/source/numba/numba/core/compiler.py", line 494, in _compile_core
    pm.run(self.state)
  File "/home/alex/source/numba/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/alex/source/numba/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/alex/source/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/typed_passes.py", line 86, in type_inference_stage
    infer.build_constraint()
  File "/home/alex/source/numba/numba/core/typeinfer.py", line 1039, in build_constraint
    self.constrain_statement(inst)
  File "/home/alex/source/numba/numba/core/typeinfer.py", line 1386, in constrain_statement
    self.typeof_assign(inst)
  File "/home/alex/source/numba/numba/core/typeinfer.py", line 1461, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/home/alex/source/numba/numba/core/typeinfer.py", line 1561, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alex/source/numba/numba/core/typeinfer.py", line 1482, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
NameError: name 'unsafe_empty_inferred' is not defined
```

Either downgrading to numba 0.56.4 or adding an import of `numba.np.unsafe.ndarray` somewhere before the function call works around the issue.

As the crash depends on side-effects of importing modules, I had a look at the registry where `@intrinsic` adds functions. Printing the functions in `numba.core.typing.templates.builtin_registry.functions` before calling `_fn` in the example above reveals the following diff:

```diff
--- ok.txt	2023-05-04 19:00:34.273600133 +0200
+++ crash.txt	2023-05-04 19:00:28.789471655 +0200
@@ -99,5 +99,3 @@
 <class 'abc.OverloadTemplate_iand'>
 <class 'abc.OverloadTemplate_ior'>
 <class 'abc.OverloadTemplate_ixor'>
-<class 'abc._IntrinsicTemplate_empty_inferred'>
-<class 'abc._IntrinsicTemplate_to_fixed_tuple'>
```

So the intrinsic is not registered before `_fn` is called. It does appear in the registry after the crash, though. 

At a first glance, this looked related to #3239, but there, the error was triggered under `forceobj=True`. Setting `forceobj` on the above reproducer also works around the issue.

<details>
<summary>Reproducer with registry dumping</summary>

```python
import sys
import pprint as pp
import numba
import numpy as np

if len(sys.argv) > 1:  # pass some argument to work around the bug
    import numba.np.unsafe.ndarray

@numba.njit()
def _fn():
    np.array([1 for _ in range(1)])

for fn in numba.core.typing.templates.builtin_registry.functions:
    print("before:", fn)

try:
    _fn()
finally:
    for fn in numba.core.typing.templates.builtin_registry.functions:
        print("after:", fn)
```

</details>

**Comment by gmarkall** [comment]
Many thanks for the report and helpful reproducer - this appears to be caused by 002f44eede961cb26bc124865cdaa17949d7a04a.

**Comment by esc** [comment]
@DrTodd13 since this is related to parfors and you had been involved in #8147 -- willit suffice to bring back the `import numba.np.unsafe.ndarray` in `numba/parfors/array_analysis.py`?

**Comment by esc** [comment]
Note to self after OOB conversation with @stuartarchibald : way to fix - add the import to `load_additional_registries` function on the CPU and GPU context instead of restoring the import in `array_analysis.py` -- look here https://github.com/numba/numba/blob/main/numba/core/cpu.py#L60

**Comment by esc** [comment]
There is now a potential fix at: https://github.com/numba/numba/pull/8958
