### ISSUE TITLE
Support for constant arrays of structure types (and therefore complex types) not implemented

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#897]
The following code from a user on the mailing list:

```python
from numba import jit, njit, f8, c16, i2
import numpy as np


def numba_test(number_of_links, left_index, right_index, sparse):

    def right_hand_side_for_numba(vector, temp, ret):

        for i in range(number_of_links):
            li = left_index[i]
            ri = right_index[i]
            temp[li] += sparse[i] * vector[ri]

        # Do things with temp to calculate ret

        return ret

    rhs = njit(f8[:](c16[:], c16[:], f8[:]),
               locals={'number_of_links': i2,
                       'left_index': i2[:],
                       'right_index': i2[:],
                       'sparse': c16[:]}) \
        (right_hand_side_for_numba)

    vector = np.zeros(5, dtype=np.complex128)
    temp = np.zeros(5, dtype=np.complex128)
    ret = np.zeros(2 * 5, dtype=np.float64)

    return rhs, phases, temp, ret

rhs, vector, temp, ret = numba_test(10, np.zeros(10, dtype=np.int16), np.zeros(10, dtype=np.int16), np.ones(10, dtype=np.complex128))

print rhs(vector, temp, ret)
```

Results in the following traceback:

```
$ python a.py 
Traceback (most recent call last):
  File "/home/gmarkall/work/numba/numba/lowering.py", line 275, in lower_block
    self.lower_inst(inst)
  File "/home/gmarkall/work/numba/numba/lowering.py", line 292, in lower_inst
    val = self.lower_assign(ty, inst)
  File "/home/gmarkall/work/numba/numba/lowering.py", line 400, in lower_assign
    value.value)
  File "/home/gmarkall/work/numba/numba/targets/base.py", line 1020, in make_constant_array
    raise TypeError("Do not support structure dtype as constant "
TypeError: Do not support structure dtype as constant array, yet.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 31, in <module>
    rhs, vector, temp, ret = numba_test(10, np.zeros(10, dtype=np.int16), np.zeros(10, dtype=np.int16), np.ones(10, dtype=np.complex128))
  File "a.py", line 23, in numba_test
    (right_hand_side_for_numba)
  File "/home/gmarkall/work/numba/numba/decorators.py", line 171, in wrapper
    disp.compile(sig)
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 279, in compile
    flags=flags, locals=locs)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 552, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 263, in compile_extra
    return self.compile_bytecode(res.result, func_attr=self.func_attr)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 275, in compile_bytecode
    return self._compile_bytecode()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 501, in _compile_bytecode
    return self._run_pipeline(pipelines)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 526, in _run_pipeline
    raise _raise_error(msg, res.exception)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 163, in __call__
    res = self.func()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 452, in stage_nopython_backend
    return self._backend(lowerfn, objectmode=False)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 413, in _backend
    fndesc, exception_map, func = lowerfn()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 404, in backend_nopython_mode
    self.flags)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 688, in native_lowering_stage
    lower.lower(create_wrapper=not flags.no_cpython_wrapper)
  File "/home/gmarkall/work/numba/numba/lowering.py", line 244, in lower
    self.lower_block(block)
  File "/home/gmarkall/work/numba/numba/lowering.py", line 280, in lower_block
    raise LoweringError(msg, inst.loc)
numba.lowering.LoweringError: Failed at nopython mode backend
Internal error:
TypeError: Do not support structure dtype as constant array, yet.
File "a.py", line 12
```

due to the fact that complex types are implemented as a struct, and struct data types are not supported in constant arrays.

**Comment by synapticarbors** [comment]
I was curious to know if the numba developers expect to address this issue in the near future? I have a project where we have a bunch of numpy record arrays sitting around as global module variables that are constant. It would be very convenient to not have to pass each and every one into a large set of methods as arguments.

**Comment by gmarkall** [comment]
PR #956 should address this.

**Comment by synapticarbors** [comment]
Thanks @gmarkall. I'll try to take a look at this soon to make sure it works with my code. Do you have a sense of when the next Numba release will be that includes this? (I can certainly test the branch, but was thinking just in terms of distributing this update to colleagues via conda). Thank again.

**Comment by seibert** [comment]
We now automatically build new developer pre-release numba packages and put them in our binstar channel.  You can test the prerelease by running:
```
conda install -c numba numba
```
You'll need to wait about 2 hours for our internal CI system to upload all the packages. (We build for 65 different combinations of operating system, Python and NumPy, so it takes a while... :) )

We expect the next stable release of Numba (ver 0.17) to be the first week in Februrary.

**Comment by synapticarbors** [comment]
I just began doing some tests using the conda package I installed via @seibert's instructions. I'm seeing some strange behavior that I wanted to report.

```
$ conda list numba
# packages in environment at /Users/lev/anaconda/envs/numbarectest:
#
numba                     0.16.0             np19py27_206
```

and:

```
$ conda info
Current conda install:

             platform : osx-64
        conda version : 3.8.0
  conda-build version : 1.3.5
       python version : 2.7.9.final.0
     requests version : 2.5.1
     root environment : /Users/lev/anaconda  (writable)
  default environment : /Users/lev/anaconda/envs/numbarectest
     envs directories : /Users/lev/anaconda/envs
        package cache : /Users/lev/anaconda/pkgs
         channel URLs : http://repo.continuum.io/pkgs/free/osx-64/
                        http://repo.continuum.io/pkgs/pro/osx-64/
          config file : None
    is foreign system : False
```

I have the following script:

```python
import numpy as np
import numba as nb

nd = np.ones(100000, np.float64)
rec = np.recarray(100000, dtype=[('a', np.float64), ('b', np.int16), ('c', 'S4')])

def update_arrays(x):
    print 'updating array: ', x
    global nd, rec
    nd *= x

    if x % 2:
        rec.a = x
        rec.b = 1
        rec.c = 'abc'
    else:
        rec.a = 2 * x
        rec.b = 2
        rec.c = 'xyz'

def run():
    counter = 1
    for k in xrange(5):
        print k
        update_arrays(counter)
        s, r, x = calculate()
        print '------'
        print s, r, x
        print '------'

        counter += 1


@nb.jit
def calculate():
    s = 0.0
    for k in xrange(nd.shape[0]):
        s += nd[k]

    r = 0.0
    for k in xrange(nd.shape[0]):
        r += rec[k].a

    return s, r, rec[0].c

if __name__ == '__main__':
    run()
```

Two things:

- When I use the `jit` decorator`, it takes over a minute for the script to start printing results of the loop once it hits `calculate()` for the first time. Killing the process with `ctrl + c` gives a traceback that indicates that it's in the numba compile phase. Basically I see:

```
0
updating array:  1
------
```

and then my core hits 100% utilization then it sits there until presumably it finishes jit-ing the `calculate` method and then it continues.

- If I comment out the `@jit` decorator, `nd` and `rec` are updated as I would expect. When I jit the `calculate` method, I'm not sure if I should expect that both `nd` and `rec` will retain their values from when `calculate` is first compiled, or if they should change but be effectively read-only within `calculate`. I seem to be getting a mix of the two:

```
0
updating array:  1
------
100000.0 100000.0 abc
------
1
updating array:  2
------
100000.0 100000.0 xyz
------
2
updating array:  3
------
100000.0 100000.0 abc
------
3
updating array:  4
------
100000.0 100000.0 xyz
------
4
updating array:  5
------
100000.0 100000.0 abc
------
```

The string field of `rec` is updating, but one of the numeric fields is not. 

Please let me know if I'm doing something outside of the scope of numba's current functionality or if I'm using numba incorrectly here. Hopefully this feedback is useful and I appreciate the work you are doing on adding these features.

**Comment by gmarkall** [comment]
Thanks for giving it a try so quickly!

For the first thing: I think the problem is that reported in #875.

For the second thing: when `calculate` is first compiled, the data in the arrays at the time of compilation is compiled into them, and will not be updated on subsequent calls to calculate. You are observing a change in rec.c because rec.c contains a pointer to the data, and it is the data is changed in `update_arrays`. However, the pointer for `rec.c`'s data that is compiled into `calculate` is unchanging. Printing `rec.c.ctypes.data` at each iteration shows that the pointer to the data never changes, even though `rec.c` is a different `chararray` object after each modification.
