### ISSUE TITLE
Cannot get numba to work on Raspberry Pi 4

### ISSUE THREAD

**Issue by ZlaTanskY** [numba/numba#9027]
**Describe the bug**
I try the first snippet of code from this link: https://numba.readthedocs.io/en/stable/user/5minguide.html
But it results in this error:
`LLVM ERROR: Symbol not found: __aeabi_unwind_cpp_pr0`

**To Reproduce**
OS:
```
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
```
Python 3.9 (manual install)
llvm version 11.0.1
Install requirements (scipy is installed from source, v1.8.1):
```
sudo apt-get install llvm -y
LLVM_CONFIG=/usr/bin/llvm-config pip install llvmlite
pip install librosa numpy<1.24 numba==0.56.4 (versions align with llvm 11.0)
```

Then try to execute the code snippet

```
from numba import jit
import numpy as np

x = np.arange(100).reshape(10, 10)

@jit(nopython=True) # Set "nopython" mode for best performance, equivalent to @njit
def go_fast(a): # Function is compiled to machine code when called the first time
    trace = 0.0
    for i in range(a.shape[0]):   # Numba likes loops
        trace += np.tanh(a[i, i]) # Numba likes NumPy functions
    return a + trace              # Numba likes NumPy broadcasting

print(go_fast(x))
```

**Expected behavior**
No error at least

```
import platform; print(platform.platform())
import sys; print("Python", sys.version)
import numpy; print("NumPy", numpy.__version__)
import scipy; print("SciPy", scipy.__version__)
import numba; print("numba", numba.__version__)

librosa.show_versions()
```
Versions:
Linux-6.1.21-v8+-aarch64-with-glibc2.31
Python 3.9.7 (default, Mar  5 2022, 10:26:12) 
[GCC 10.2.1 20210110]
NumPy 1.23.5
SciPy 1.8.1
numba 0.56.4

Do note that it was working on the RPi until last week. I had to perform an apt upgrade in order to install `certbot`. I am not keen on downgrading again, I prefer fixing the problem but I am stuck on what the root cause actually is.

**Comment by esc** [comment]
Can you try `numba -s` and attach the output to this issue, plz?

**Comment by gmarkall** [comment]
Could you also provide the output of 

```
/usr/bin/llvm-config --version --cxxflags --cflags --ldflags --components
```

please?

**Comment by ZlaTanskY** [comment]
> Can you try `numba -s` and attach the output to this issue, plz?
```
(venv) pi@raspberrypi:~/Documents/my_project $ numba -s
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2023-06-19 20:13:44.538036
UTC start time                                : 2023-06-19 19:13:44.538057
Running time (s)                              : 1.533573

__Hardware Information__
Machine                                       : aarch64
CPU Name                                      : cortex-a72
CPU Count                                     : 4
Number of accessible CPUs                     : 4
List of accessible CPUs cores                 : 0-3
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 

Memory Total (MB)                             : 3794
Memory Available (MB)                         : 3035

__OS Information__
Platform Name                                 : Linux-6.1.34-v8+-aarch64-with-glibc2.31
Platform Release                              : 6.1.34-v8+
OS Name                                       : Linux
OS Version                                    : #1657 SMP PREEMPT Fri Jun 16 12:36:29 BST 2023
OS Specific Version                           : ?
Libc Version                                  : glibc 2.31

__Python Information__
Python Compiler                               : GCC 10.2.1 20210110
Python Implementation                         : CPython
Python Version                                : 3.9.7
Python Locale                                 : en_GB.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.56.4
llvmlite Version                              : 0.39.1

__LLVM Information__
LLVM Version                                  : 11.0.1

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA NVIDIA Bindings Available                : ?
CUDA NVIDIA Bindings In Use                   : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

__NumPy Information__
NumPy Version                                 : 1.23.5
NumPy Supported SIMD features                 : ('NEON', 'NEON_FP16', 'NEON_VFPV4', 'ASIMD')
NumPy Supported SIMD dispatch                 : ('None found.',)
NumPy Supported SIMD baseline                 : ('None found.',)
NumPy AVX512_SKX support detected             : False

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : False
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : False
+--> Disabled due to Unknown import problem.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.

__Installed Packages__
Package            Version
------------------ --------
appdirs            1.4.4
async-generator    1.10
attrs              23.1.0
audioread          3.0.0
blinker            1.6.2
certifi            2023.5.7
cffi               1.15.1
charset-normalizer 3.1.0
click              8.1.3
decorator          5.1.1
dominate           2.8.0
exceptiongroup     1.1.1
Flask              2.3.2
Flask-Bootstrap    3.3.7.1
Flask-SSLify       0.1.5
flatbuffers        23.5.26
gunicorn           20.1.0
h11                0.14.0
idna               3.4
importlib-metadata 6.6.0
iniconfig          2.0.0
itsdangerous       2.1.2
Jinja2             3.1.2
joblib             1.2.0
lazy_loader        0.2
llvmlite           0.39.1
MarkupSafe         2.1.2
msgpack            1.0.5
mypy               1.3.0
mypy-extensions    1.0.0
numba              0.56.4
numpy              1.23.5
outcome            1.2.0
packaging          23.1
pandas             2.0.2
pip                23.1.2
pluggy             1.0.0
pooch              1.6.0
pycparser          2.21
PySocks            1.7.1
pytest             7.3.1
pytest-mock        3.10.0
python-dateutil    2.8.2
pytz               2023.3
requests           2.31.0
resampy            0.2.2
scikit-learn       1.2.2
SciPy              1.8.1
selenium           4.9.1
setuptools         60.9.3
six                1.16.0
sniffio            1.3.0
sortedcontainers   2.4.0
soundfile          0.12.1
soxr               0.3.5
tflite             2.10.0
tflite-runtime     2.10.0
threadpoolctl      3.1.0
tomli              2.0.1
trio               0.22.0
trio-websocket     0.10.2
typing_extensions  4.6.2
tzdata             2023.3
urllib3            2.0.2
visitor            0.1.3
Werkzeug           2.3.4
wheel              0.37.1
wsproto            1.2.0
zipp               3.15.0

No errors reported.


__Warning log__
Warning (cuda): CUDA is disabled or no CUDA enabled devices are present.
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning: Conda not available.
 Error was [Errno 2] No such file or directory: 'conda'

Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us
--------------------------------------------------------------------------------
If requested, please copy and paste the information between
the dashed (----) lines, or from a given specific section as
appropriate.

=============================================================
IMPORTANT: Please ensure that you are happy with sharing the
contents of the information present, any information that you
wish to keep private you should remove before sharing.
=============================================================
```

**Comment by ZlaTanskY** [comment]
> Could you also provide the output of
> 
> ```
> /usr/bin/llvm-config --version --cxxflags --cflags --ldflags --components
> ```
> 
> please?

```
(venv) pi@raspberrypi:~/Documents/my_project $ /usr/bin/llvm-config --version --cxxflags --cflags --ldflags --components
11.0.1
-I/usr/lib/llvm-11/include -std=c++14   -fno-exceptions -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-I/usr/lib/llvm-11/include  -D_GNU_SOURCE -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS
-L/usr/lib/llvm-11/lib 
aarch64 aarch64asmparser aarch64codegen aarch64desc aarch64disassembler aarch64info aarch64utils aggressiveinstcombine all all-targets amdgpu amdgpuasmparser amdgpucodegen amdgpudesc amdgpudisassembler amdgpuinfo amdgpuutils analysis arm armasmparser armcodegen armdesc armdisassembler arminfo armutils asmparser asmprinter avr avrasmparser avrcodegen avrdesc avrdisassembler avrinfo binaryformat bitreader bitstreamreader bitwriter bpf bpfasmparser bpfcodegen bpfdesc bpfdisassembler bpfinfo cfguard codegen core coroutines coverage debuginfocodeview debuginfodwarf debuginfogsym debuginfomsf debuginfopdb demangle dlltooldriver dwarflinker engine executionengine extensions frontendopenmp fuzzmutate globalisel hexagon hexagonasmparser hexagoncodegen hexagondesc hexagondisassembler hexagoninfo instcombine instrumentation interpreter ipo irreader jitlink lanai lanaiasmparser lanaicodegen lanaidesc lanaidisassembler lanaiinfo libdriver lineeditor linker lto mc mca mcdisassembler mcjit mcparser mips mipsasmparser mipscodegen mipsdesc mipsdisassembler mipsinfo mirparser msp430 msp430asmparser msp430codegen msp430desc msp430disassembler msp430info native nativecodegen nvptx nvptxcodegen nvptxdesc nvptxinfo objcarcopts object objectyaml option orcerror orcjit passes perfjitevents powerpc powerpcasmparser powerpccodegen powerpcdesc powerpcdisassembler powerpcinfo profiledata remarks riscv riscvasmparser riscvcodegen riscvdesc riscvdisassembler riscvinfo riscvutils runtimedyld scalaropts selectiondag sparc sparcasmparser sparccodegen sparcdesc sparcdisassembler sparcinfo support symbolize systemz systemzasmparser systemzcodegen systemzdesc systemzdisassembler systemzinfo tablegen target textapi transformutils vectorize webassembly webassemblyasmparser webassemblycodegen webassemblydesc webassemblydisassembler webassemblyinfo windowsmanifest x86 x86asmparser x86codegen x86desc x86disassembler x86info xcore xcorecodegen xcoredesc xcoredisassembler xcoreinfo xray
```

**Comment by gmarkall** [comment]
My guess is that it seems like at least one of the libraries that is linked at runtime contains code that generates exceptions (and therefore calls to `__aeabi_unwind_cpp_pr0`). I'm not sure if this will fix it, but one thing to try could be to recreate your Python environment / install with the environment variable `CXXFLAGS=-fno-exceptions` set, but it's a bit of a guess.

**Comment by ZlaTanskY** [comment]
> My guess is that it seems like at least one of the libraries that is linked at runtime contains code that generates exceptions (and therefore calls to `__aeabi_unwind_cpp_pr0`). I'm not sure if this will fix it, but one thing to try could be to recreate your Python environment / install with the environment variable `CXXFLAGS=-fno-exceptions` set, but it's a bit of a guess.

Thanks for your response> I have tried recreating my Python environment with the envinronment variable set to your suggestionm but it did not change the result unfortunately.

**Comment by gmarkall** [comment]
If you create a new virtualenv and install Numba and llvmlite from the AArch64 wheels, does that combination work?

(Might I ask the motivation behind building from source too?)

**Comment by ZlaTanskY** [comment]
> If you create a new virtualenv and install Numba and llvmlite from the AArch64 wheels, does that combination work?
> 
> (Might I ask the motivation behind building from source too?)

Installing like I have done so far seemed the simplest, also I cannot use conda on my RPi together with Python 3.9.
I thought that installing through pip equaled to installing from the aarch64 wheels?

**Comment by esc** [comment]
> > If you create a new virtualenv and install Numba and llvmlite from the AArch64 wheels, does that combination work?
> > (Might I ask the motivation behind building from source too?)
> 
> Installing like I have done so far seemed the simplest, also I cannot use conda on my RPi together with Python 3.9. I thought that installing through pip equaled to installing from the aarch64 wheels?

There seems to be misunderstandings at play here, I will try and explain.

The `aarch64` wheels that we supply have llvm included, so you would not need a system llvm?

In fact for the following:

```
> sudo apt-get install llvm -y
> LLVM_CONFIG=/usr/bin/llvm-config pip install llvmlite
> pip install librosa numpy<1.24 numba==0.56.4 (versions align with llvm 11.0)
```

I am not sure exactly what this is intended to do? It seems like you are trying to force pip to download the source package and compile that against a system LLVM?! That procedure is only needed for 32 bit RPi, but not for `aarch64`, I believe. So I am not even sure what happened in this case, I think the behaviour is undefined. It would have been good to add a copy and paste of the installation logs, that would make it much easier to determine what is going on. My hunch is that something is screwed due to way in which you installed the various components. 

Anyway, you should try the latest version of `numba` and `llvmlite`. In fact my guess would be, that all you really need to do is:

```
pip install librosa
```

And then the dependency chain should resolve appropriately. Is that something you would be willing to try? Do try it and report back the installation logs in case of success or failure, thank you.

**Comment by ZlaTanskY** [comment]
That procedure was done because I have in fact installed a 32-bit Raspbian version:
```
(venv) pi@raspberrypi:~/Documents/my_project $ getconf LONG_BIT
32
```
I cannot update the OS-version of the RPi, as I have too many deployed projects on it. I could buy a new one and start over from there on a 64-bit version, but that still doesn't fix the root cause of this issue.

I did try to remove the installation from source and install the latest librosa package in a newly created virtualenv as you suggested, but it is unable to install `llvmlite` that way.
```
(venv) pi@raspberrypi:~/Documents/my_project $ pip install librosa

...

Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [11 lines of output]
      running bdist_wheel
      /home/pi/Documents/burpp/venv/bin/python /tmp/pip-install-hn8b90lz/llvmlite_8816089bc7b74e5fa19b4eb7aa910f94/ffi/build.py
      LLVM version... Traceback (most recent call last):
        File "/tmp/pip-install-hn8b90lz/llvmlite_8816089bc7b74e5fa19b4eb7aa910f94/ffi/build.py", line 227, in <module>
          main()
        File "/tmp/pip-install-hn8b90lz/llvmlite_8816089bc7b74e5fa19b4eb7aa910f94/ffi/build.py", line 217, in main
          main_posix('linux', '.so')
        File "/tmp/pip-install-hn8b90lz/llvmlite_8816089bc7b74e5fa19b4eb7aa910f94/ffi/build.py", line 135, in main_posix
          raise RuntimeError(msg) from None
      RuntimeError: Could not find a `llvm-config` binary. There are a number of reasons this could occur, please see: https://llvmlite.readthedocs.io/en/latest/admin-guide/install.html#using-pip for help.
      error: command '/home/pi/Documents/burpp/venv/bin/python' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
ERROR: Could not build wheels for llvmlite, which is required to install pyproject.toml-based projects
```

**Comment by esc** [comment]
> That procedure was done because I have in fact installed a 32-bit Raspbian version:
> 
> ```
> (venv) pi@raspberrypi:~/Documents/my_project $ getconf LONG_BIT
> 32
> ```

This is confusing, `numba -s` reports:

```
Machine                                       : aarch64
```

So I was confused and under the assumption that your using a 64 bit OS. Hence I suggested the `pip install librosa`.

It is true that we don't ship wheels for 32 bit, so yes, that variant does indeed need to be installed from source using the system llvm as you have done above.

Unfortunately, I don't have any further suggestions as what you might try, so sorry. I don't think we have ever heard of anyone using numba/llvmlite with 32-bit OS on 64-bit hardware so you may have entered uncharted territory here.
