### ISSUE TITLE
Numba+Cuda doesn't work for me on WSL 2 (but PyTorch+Cuda works fine)

### ISSUE THREAD

**Issue by jorlow** [numba/numba#9032]
Cuda works fine in PyTorch on my WSL 2 (Windows 11 + 22.04.2 LTS) install but it doesn't work for numba.

$ python -c "import torch; print(torch.cuda.is_available())"
`True`

$ python -c "from numba import cuda; print(cuda.is_available())"
`False`

$ python -c "import numba; print(numba.__version__)"
`0.58.0dev0+190.gc9cc06ba1`

I found https://github.com/numba/numba/issues/7104 while trying to troubleshoot and everything I'm seeing pretty much matches what Sahuta saw. I've pasted the output from the various diagnostic commands he was asked to run below.

$ python -c "from numba import cuda; cuda.detect()"
```
Traceback (most recent call last):
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 258, in ensure_initialized
    self.cuInit(0)
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 331, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 399, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [100] Call to cuInit results in CUDA_ERROR_NO_DEVICE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/api.py", line 470, in detect
    print('Found %d CUDA devices' % len(devlist))
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 49, in __len__
    return len(self.lst)
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 428, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 296, in __getattr__
    self.ensure_initialized()
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 262, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_NO_DEVICE (100)
```

$ python -c "import cupyx; print(cupyx.get_runtime_info())"
```
OS                           : Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
Python Version               : 3.10.11
CuPy Version                 : 12.0.0
CuPy Platform                : NVIDIA CUDA
NumPy Version                : 1.24.3
SciPy Version                : None
Cython Build Version         : 0.29.35
Cython Runtime Version       : None
CUDA Root                    : /home/jorlow/mambaforge/envs/course22p2
nvcc PATH                    : None
CUDA Build Version           : 11020
CUDA Driver Version          : 12020
CUDA Runtime Version         : 11080
cuBLAS Version               : 111103
cuFFT Version                : 10900
cuRAND Version               : 10300
cuSOLVER Version             : (11, 4, 1)
cuSPARSE Version             : 11705
NVRTC Version                : (11, 8)
Thrust Version               : 101000
CUB Build Version            : 101000
Jitify Build Version         : 47538c5
cuDNN Build Version          : None
cuDNN Version                : None
NCCL Build Version           : None
NCCL Runtime Version         : None
cuTENSOR Version             : None
cuSPARSELt Build Version     : None
Device 0 Name                : NVIDIA GeForce RTX 2080 Ti
Device 0 Compute Capability  : 75
Device 0 PCI Bus ID          : 0000:0C:00.0
```

$ python -c "from numba import cuda; cuda.cudadrv.libs.test()"
```
Finding driver from candidates: libcuda.so, libcuda.so.1, /usr/lib/libcuda.so, /usr/lib/libcuda.so.1, /usr/lib64/libcuda.so, /usr/lib64/libcuda.so.1...
Using loader <class 'ctypes.CDLL'>
        trying to load driver...        ok, loaded from libcuda.so
Finding nvvm from Conda environment
        located at /home/jorlow/mambaforge/envs/course22p2/lib/libnvvm.so.4.0.0
        trying to open library...       ok
Finding cudart from Conda environment
        located at /home/jorlow/mambaforge/envs/course22p2/lib/libcudart.so.11.8.89
        trying to open library...       ok
Finding cudadevrt from Conda environment
        located at /home/jorlow/mambaforge/envs/course22p2/lib/libcudadevrt.a
Finding libdevice from Conda environment
        trying to open library...       ok
```

> wsl --update
```
Checking for updates.
The most recent version of Windows Subsystem for Linux is already installed.
```

$ lsb_release -a
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:        22.04
Codename:       jammy
```

Running https://github.com/numba/numba/issues/7104#issuecomment-859470459
```
(c_ulong(10612637696), c_ulong(11810832384))
c_ulong(47399829504)
(c_ulong(10610540544), c_ulong(11810832384))
(c_ulong(10612637696), c_ulong(11810832384))
```

Running https://github.com/numba/numba/issues/7104#issuecomment-859483573 yields
```
Traceback (most recent call last):
  File "/tmp/x2.py", line 62, in <module>
    my_init()
  File "/tmp/x2.py", line 25, in my_init
    raise RuntimeError(f'Unexpected return code {ret} from cuInit')
RuntimeError: Unexpected return code 100 from cuInit
```

**Comment by gmarkall** [comment]
What does:

```
python -c "import ctypes; x = ctypes.CDLL('libcuda.so'); x.undef()"
```

print?

**Comment by jorlow** [comment]
$ python -c "import ctypes; x = ctypes.CDLL('libcuda.so'); x.undef()"
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib/x86_64-linux-gnu/libcuda.so: undefined symbol: undef
```

**Comment by gmarkall** [comment]
Thanks, that info is useful - it sounds like you have the Linux (as opposed to WSL2) driver installed in your WSL2 instance. I'm guessing you might have a package called `libnvidia-compute-510` installed - can you try to remove it with `apt-get`? If that's not installed, can you provide the output of 

```
dpkg --get-selections | grep nvidia
```

please?

**Comment by jorlow** [comment]
Your hunch was right. I've had this WSL2 image for a while so it's hard for me to say when/how this got installed.

$ dpkg --get-selections | grep nvidia
`libnvidia-compute-510:amd64                     install`

I removed the package and (just in case) reinstalled cuda-11-8. I re-ran the above command to double check the package had not somehow returned -- it hadn't.

After that, I re-ran this

$ python -c "import ctypes; x = ctypes.CDLL('libcuda.so'); x.undef()"
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/jorlow/mambaforge/envs/course22p2/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcuda.so: cannot open shared object file: No such file or directory
```

But, most importantly,
$ python -c "from numba import cuda; print(cuda.is_available())"
`True`

Thanks for the help! Any idea why this didn't trip up PyTorch?

**Comment by gmarkall** [comment]
> Thanks for the help! Any idea why this didn't trip up PyTorch?

I'd guess that PyTorch is linked to the libraries in some way such that it loads the correct libraries for WSL2, whereas Numba interacts directly with the driver API through ctypes, so will load whichever libcuda.so it finds first, starting with the one that's already on the dynamic linker's search path.

> Btw my mind is blown at the prospect of writing cuda kernels in Python. Super cool project! Thanks for all your work on it and your help!

Many thanks for your kind words!

**Comment by gmarkall** [comment]
Now that we understand (in general) how to diagnose this quickly, I've added #9034 that gives the absolute location of the `libcuda.so` driver so we can tell just from `numba -s` what the cause of the issue is quickly.

**Comment by gmarkall** [comment]
@jorlow Are you happy if we close this issue now?

**Comment by jorlow** [comment]
Thanks!
