### ISSUE TITLE
Bad indices in nopython mode result in confusing error: 'NoneType' object has no attribute '_code'

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#904]
The following code (containing an error, which causes an invalid index to be used in a setitem):

```python
from numba import njit
import numpy as np

t = np.dtype([('x', np.int32), ('y', np.int32)])

arr = np.zeros(1, t)
arr2d = np.zeros((10, 10))

@njit
def val_as_index(arr, arr2d):
    x = arr.x, # Typo: there should not be a comma here
    y = arr.y
    arr2d[x, y] = 100.0

val_as_index(arr[0], arr2d)
```

Results in the following traceback, which is hard to interpret:

```
$ python a.py 
Traceback (most recent call last):
  File "/home/gmarkall/work/numba/numba/typeinfer.py", line 112, in propagate
    constrain(context, typevars)
  File "/home/gmarkall/work/numba/numba/typeinfer.py", line 293, in __call__
    if not context.resolve_setitem(target=ty, index=it, value=vt):
  File "/home/gmarkall/work/numba/numba/typing/context.py", line 91, in resolve_setitem
    return self.resolve_function_type("setitem", args, kws)
  File "/home/gmarkall/work/numba/numba/typing/context.py", line 61, in resolve_function_type
    res = defn.apply(args, kws)
  File "/home/gmarkall/work/numba/numba/typing/templates.py", line 214, in apply
    return self._select(cases, args, kws)
  File "/home/gmarkall/work/numba/numba/typing/templates.py", line 185, in _select
    selected = resolve_overload(self.context, self.key, cases, args, kws)
  File "/home/gmarkall/work/numba/numba/typing/templates.py", line 133, in resolve_overload
    ratings = _rate_arguments(context, args, case.args)
  File "/home/gmarkall/work/numba/numba/typing/templates.py", line 107, in _rate_arguments
    by = context.type_compatibility(actual, formal)
  File "/home/gmarkall/work/numba/numba/typing/context.py", line 329, in type_compatibility
    return self.tm.check_compatible(fromty, toty)
  File "/home/gmarkall/work/numba/numba/typeconv/typeconv.py", line 17, in check_compatible
    return _typeconv.check_compatible(self._ptr, fromty._code, toty._code)
AttributeError: 'NoneType' object has no attribute '_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "a.py", line 15, in <module>
    val_as_index(arr[0], arr2d)
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 150, in _compile_for_args
    return self.jit(sig)
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 141, in jit
    return self.compile(sig, **kws)
  File "/home/gmarkall/work/numba/numba/dispatcher.py", line 276, in compile
    flags=flags, locals=locs)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 552, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 263, in compile_extra
    return self.compile_bytecode(res.result, func_attr=self.func_attr)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 275, in compile_bytecode
    return self._compile_bytecode()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 501, in _compile_bytecode
    return self._run_pipeline(pipelines)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 526, in _run_pipeline
    raise _raise_error(msg, res.exception)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 163, in __call__
    res = self.func()
  File "/home/gmarkall/work/numba/numba/compiler.py", line 357, in stage_nopython_frontend
    self.locals)
  File "/home/gmarkall/work/numba/numba/compiler.py", line 670, in type_inference_stage
    infer.propagate()
  File "/home/gmarkall/work/numba/numba/typeinfer.py", line 386, in propagate
    self.constrains.propagate(self.context, self.typevars)
  File "/home/gmarkall/work/numba/numba/typeinfer.py", line 118, in propagate
    loc=constrain.loc)
numba.typeinfer.TypingError: Failed at nopython frontend
Internal error at <numba.typeinfer.SetItemConstrain object at 0x7f5f9efc40b8>:
'NoneType' object has no attribute '_code'
File "a.py", line 13
```

This is because `normalize_index` returns `None` if it can't normalise an index, so a variable gets assigned a type of `None` and later on during typing the error above is produced.

I am working on a fix that fails faster and provides a better error message explaining the issue.

**Comment by pitrou** [comment]
This has been fixed
