### ISSUE TITLE
Dispatch error

### ISSUE THREAD

**Issue by albop** [numba/numba#9097]
Under some conditions, the dispatch behavior of a function defined with overload seems unpredictible. Issue was initially raised here: https://github.com/EconForge/interpolation.py/issues/104. 
It can be replicated with the two attached files (run   `error.py` which calls some functions defined in `source.py`). Both are compressed in [bug.zip](https://github.com/numba/numba/files/12181883/bug.zip)

To summarize, error.py contains the following loop:

```python
import numpy as np
from source import eval_linear

grid = (np.linspace(0, 10, 11), np.linspace(0, 10, 11))
z1 = np.random.randn(11,11)
z1z2 = np.random.randn(11,11,2)
LINEAR = ((None,), (None,) * 2)  # a constant used for dispatching only

npoints = 300
eval_points = np.column_stack([np.linspace(0, 10, npoints)]*2)

for i in range(1000):

    z1_eval = eval_linear( grid,  z1,  eval_points, LINEAR )
    try:
        assert(z1_eval.shape == (npoints,))
    except Exception as e:
        print(f"Failed in iteration {i}")
        raise(e)

    z1z2_eval = eval_linear( grid,  z1z2, eval_points,  LINEAR)
    try:
        assert(z1z2_eval.shape == (npoints,2))
    except Exception as e:
        print(f"Failed in iteration {i}")
        raise(e)
```

In that loop, `eval_linear` is a nopython jitted function which returns a vector in the first call when z1 is a 2d array (values on the 2d grid to interpolate) but returns a matrix in the second call where z1z2 is a 3d array (vector -values on the 2d grid).

When iterating long enough I always get an error but not always for the same call, with the function returning the wrong type of output. For instance:

```
Failed in iteration 129
Traceback (most recent call last):
  File "/home/pablo/Econforge/interpolation.py/error_min.py", line 26, in <module>
    raise(e)
  File "/home/pablo/Econforge/interpolation.py/error_min.py", line 23, in <module>
    assert(z1z2_eval.shape == (npoints,2))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

The original definition of `eval_linear` comes from the interpolation.py library. I tried to reproduce a simplified version of it in the file `source.py`. The definition is somewhat convoluted (and certainly suboptimal), because:
- a function `eval_spline` does many different things based on the kind of (keyword) arguments it get. In the original library code gets generated. Here I included here just the two combinations needed for the example.
- a function `eval_linear` calls the former one with one of the arguments `k` being equal to 1. For compatibility purpose it also dispatches on positional argument `extrap_mode` whose type is the only thing that matters.

The function eval_linear seems to work well as long as it is not called too many times with different kinds of arguments...

What I have tried so far:
- make a nonjitted version to check whether the algorithmic code does out of bounds access (it does not)
- remove the last argument `LINEAR` in the call.  Error goes away (but then it's not what I want)
- replace the call in the loop by: `eval_spline(grid, C, points, out=None, k=1, diff="None", extrap_mode="linear")`. No problem as long as all the arguments are specified (which is another issue I plan to adress afterwards).

I've got no idea how to investigate it further but am happy to follow any advice.

**Comment by guilhermeleobas** [comment]
Hi @albop, thanks for the report. I tried to execute `error.py` but got the following exception:

```python
$ python error.py
We are going to extrapolate in 'Tuple(UniTuple(none x 1), UniTuple(none x 2))' mode.
Traceback (most recent call last):
  File "/Users/guilhermeleobas/git/numba/error.py", line 14, in <module>
    z1_eval = eval_linear( grid,  z1,  eval_points, LINEAR )
  ...
  File "/Users/guilhermeleobas/git/numba/numba/core/typing/templates.py", line 786, in _build_impl
    ovf_result = self._overload_func(*args, **kws)
  File "/Users/guilhermeleobas/git/numba/source.py", line 17, in __eval_spline
    kk = (k).literal_value
AttributeError: 'Integer' object has no attribute 'literal_value'
```

Could you please check if the file you shared is the correct one?

**Comment by albop** [comment]
Strange, I just reran the files downloaded from github it in an empty environment:
```
llvmlite 0.40.1 lightweight wrapper around basic LLVM functionality
numba    0.57.1 compiling Python code using LLVM
numpy    1.24.4 Fundamental package for array computing in Python
```
with python 3.11.2 . 

Here `z1_eval` should be an 1d array and `z1z2_eval` a 2d array.

**Comment by albop** [comment]
Yes these ones.
I'm on Ubuntu 23.04 but I have just tried it on a windows machine (had to run it several times to get the error).
![Screenshot from 2023-07-27 18-00-52](https://github.com/numba/numba/assets/276777/5de4c8e9-be2b-4fc2-a90b-9f4d85b0bbf8)
On the windows machine, I just downloaded the latest anaconda.

**Comment by albop** [comment]
Since it is starting to look platform dependent I shall say I'm using `Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz` with 64Go ram.

**Comment by guilhermeleobas** [comment]
Btw, I can reproduce it now. Before I was setting the `NUMBA_CAPTURED_ERRORS="new_style"`. Thanks, @stuartarchibald, for pointing that out. 

I'll debug your code later today.

**Comment by guilhermeleobas** [comment]
Hi @albop, I had some time and debug this problem for a bit. What happens is that Numba dispatches the call to the wrong overload when selecting among the two overloads.

Selection happens here:
https://github.com/numba/numba/blob/cd1842ed110c4acc97d9ff28a25e1efcbf0dc908/numba/core/typeconv/typeconv.cpp#L141-L168

**Comment by albop** [comment]
Ah ! That is encouraging ! Thanks for the update @guilhermeleobas .
I can't make sense of it though. Between the two calls, the only difference is the call to the 3d/2d array. Even if one call was doing promotion and the other conversion so as to have the same penalty, the ambiguous ranking should 1/ be deterministic 2/ not depend on the last "LINEAR" argument, right ?
Sorry if I sound too obvious this is not really my area of expertise. Is there a simple way (i.e. without recompilation) to print the précise signatures that have been registered and called) ? Or is there a strict mode to overload a function in strict mode, that is by specifying precisely the arguments types so as to avoid any promotion/casting ?

**Comment by guilhermeleobas** [comment]
After digging a bit more into this problem. Whenever there's a cache **hit**, the segfault happens

https://github.com/numba/numba/blob/cd1842ed110c4acc97d9ff28a25e1efcbf0dc908/numba/_typeof.cpp#L617-L621

Disabling caching here seems to fix the issue

**Comment by guilhermeleobas** [comment]
I found the root cause of this issue. When reallocating the inner string used to store typecode representations, the previous static buffer is not copied to the new buffer:
https://github.com/numba/numba/blob/2b104dbcc9b7add3b3221f5be790dcd511dc28cc/numba/_typeof.cpp#L103-L105

Changing the if block to the following fixes the issue:

```C
    if (w->buf == w->static_buf) {
        w->buf = (char *) malloc(newsize);
        memcpy(w->buf, w->static_buf, w->allocated);
    }
```
