### ISSUE TITLE
Ommited keyword argument can't be a literal

### ISSUE THREAD

**Issue by albop** [numba/numba#9104]
The following code, adapted from one of the numba example on literals raises an error. It results, from the attempt of defining one jitted interpolation function with several keyword arguments (cf https://github.com/EconForge/interpolation.py/issues/107)

```python
import numba

def power(x, n=2):
    raise NotImplementedError

@numba.extending.overload(power)
def ov_power(x, n=2):
    if isinstance(n, numba.types.Literal):
        # only if `n` is a literal
        if n.literal_value == 2:
            # special case: square
            print("square")
            def fun(x,n=2):
                return x * x
            return fun
        elif n.literal_value == 3:
            # special case: cubic
            print("cubic")
            def fun(x,n=2): # n=2, strange but logical
                return x * x * x
            return fun

    print("generic")
    def fun(x,n=3):
        
        return x ** n
    return fun

@numba.njit
def test_power(x, n=2):
    return power(x, n=numba.literally(n))

# should print "square" and "9": OK
print(test_power(3, n=2))

# should print "cubic" and "27": OK
print(test_power(3, n=3))

# Now call test_power without specify the value of n

print(test_power(3))   #: Error
```

The  error ends in
```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/.cache/pypoetry/virtualenvs/interpolation-cFe3xpnh-py3.11/lib/python3.11/site-packages/numba/core/types/misc.py", line 69, in literal
    ctor = Literal.ctor_map[ty]
           ~~~~~~~~~~~~~~~~^^^^
KeyError: <class 'numba.core.dispatcher.OmittedArg'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pablo/Econforge/interpolation.py/literal.py", line 41, in <module>
    print(test_power(3))   #: Error
          ^^^^^^^^^^^^^
  File "/home/pablo/.cache/pypoetry/virtualenvs/interpolation-cFe3xpnh-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py", line 438, in _compile_for_args
    args = [(types.literal
           ^^^^^^^^^^^^^^^
  File "/home/pablo/.cache/pypoetry/virtualenvs/interpolation-cFe3xpnh-py3.11/lib/python3.11/site-packages/numba/core/dispatcher.py", line 438, in <listcomp>
    args = [(types.literal
            ^^^^^^^^^^^^^^
  File "/home/pablo/.cache/pypoetry/virtualenvs/interpolation-cFe3xpnh-py3.11/lib/python3.11/site-packages/numba/core/types/misc.py", line 71, in literal
    raise LiteralTypingError("{} cannot be used as a literal".format(ty))
numba.core.errors.LiteralTypingError: <class 'numba.core.dispatcher.OmittedArg'> cannot be used as a literal
```

**Comment by guilhermeleobas** [comment]
Hi @albop, thanks for the report. I can confirm the bug.
