### ISSUE TITLE
if condition test on variadic parameter tuple failed

### ISSUE THREAD

**Issue by plutonium-94** [numba/numba#9121]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Describe the bug**

When using the `@njit` decorator on a function with an arbitrary number of arguments (`*x`), a `numba.core.errors.TypingError` is thrown when the tuple is empty. However, when checking for the length of the tuple (`if len(x)`) instead of the truthiness of the tuple (`if x`), no error is thrown and the function behaves as expected. 

**To Reproduce**

1. Define the function:
    ```python
    @njit
    def max_(*x):
        return max(x) if x else 0
    ```
2. Call the function with no arguments:
    ```python
    max_()
    ```
3. See error.

**Expected Behavior**

The function should return `0` when called with no arguments, as it does when the condition is changed to `if len(x)`:

```python
@njit
def max_(*x):
    return max(x) if len(x) else 0
max_()
```
This does not produce an error and correctly returns `0`.

**Error Message**
```text
Traceback (most recent call last):
  File "...\lib\site-packages\IPython\core\interactiveshell.py", line 3505, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-107-96dcea1a2319>", line 1, in <module>
    max_()
  File "...\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "...\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function max>) found for signature:
 
 >>> max(Tuple())
 
There are 8 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'MinMaxBase.generic': File: numba\core\typing\builtins.py: Line 906.
    With argument(s): '(Tuple())':
   Rejected as the implementation raised a specific error:
     TypeError: max() argument is an empty tuple
  raised from ...\lib\site-packages\numba\core\typing\builtins.py:919
  - Of which 2 did not match due to:
  Overload in function 'indval_max': File: numba\cpython\builtins.py: Line 588.
    With argument(s): '(Tuple())':
   Rejected as the implementation raised a specific error:
     TypingError: missing a required argument: 'indval2'
  raised from ...\lib\site-packages\numba\core\typing\templates.py:784
  - Of which 2 did not match due to:
  Overload in function 'boolval_max': File: numba\cpython\builtins.py: Line 617.
    With argument(s): '(Tuple())':
   Rejected as the implementation raised a specific error:
     TypingError: missing a required argument: 'val2'
  raised from ...\lib\site-packages\numba\core\typing\templates.py:784
  - Of which 2 did not match due to:
  Overload of function 'max': File: numba\cpython\builtins.py: Line 648.
    With argument(s): '(Tuple())':
   No match.
During: resolving callee type: Function(<built-in function max>)
During: typing of call at <ipython-input-105-4cccaa644969> (3)
File "<ipython-input-105-4cccaa644969>", line 3:
def max_(*x):
    return max(x) if x else 0
    ^
```

Operating System: Windows 10
Python Environment: Anaconda Python 3.10.12

**Comment by gmarkall** [comment]
Thanks for the report! There are a couple of issues at play:

* Numba needs to type all expressions in the function, even those that would never execute, such as `max(x)` where `x` is the empty tuple in this case.
* Numba's branch pruner can sometimes remove this `max(x)` with the empty tuple, for example in the `if len(x)` case you mention above.
* However, the branch pruner does not support the case specifically identified in this issue.

I'm marking this for triage discussion, in case there's a small extension to branch pruning that could help with this case (but I'm not an expert in that area).

Copy/pastable reproducer:

```python
from numba import njit

@njit
def max_(*x):
    return max(x) if x else 0

max_()
```

**Comment by gmarkall** [comment]
Following discussion in triage - this is an extra case that "semantic constants" needs to recognize and propagate the empty tuple as `False`.
