### ISSUE TITLE
arpartition/partition issue: kth out of bounds

### ISSUE THREAD

**Issue by pashaPASHaa** [numba/numba#9124]
## Reporting a bug

Incorrect behaviour of njit-decorated `np.argpartition` / `np.partition` function with partition parameter `kth=-len(array)`.
Code for reproducibility below:

```
import sys
import numba as nb
import numpy as np

from numba import njit


def fn_np(a, k):
    y = np.argpartition(a, -k)
    return y


@njit
def fn_nb(a, k):
    y = np.argpartition(a, -k)  # np.partition as well
    return y


if __name__ == "__main__":

    print(sys.version, nb.__version__)

    a = np.array([30,20,10], dtype='f8')

    print(fn_np(a, k=3))  # ok
    print(fn_nb(a, k=3))  # error
```

Output:
```
3.11.4 (main, Jun  9 2023, 07:59:55) [GCC 12.3.0] 0.57.1
[2 1 0]
Traceback (most recent call last):
  File "/home/shared/bug.py", line 26, in <module>
    print(fn_nb(a, k=3))  # error
          ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/numba/np/arraymath.py", line 1848, in valid_kths
    raise ValueError("kth out of bounds")
ValueError: kth out of bounds
```

**Comment by esc** [comment]
This is a logic error when determining OOB for kths. The following starter patch may fix:

```
diff --git i/numba/np/arraymath.py w/numba/np/arraymath.py
index 50fed28741..d1a70aeb19 100644
--- i/numba/np/arraymath.py
+++ w/numba/np/arraymath.py
@@ -1860,8 +1860,9 @@ def valid_kths(a, kth):
         raise ValueError('kth must be scalar or 1-D')
         # numpy raises ValueError: object too deep for desired array

-    if np.any(np.abs(kth_array) >= a.shape[-1]):
-        raise ValueError("kth out of bounds")
+    for k in kth_array:
+        if k < 0 and k > a.shape[-1] or k > 0 and k >= a.shape[-1]:
+            raise ValueError("kth out of bounds")

     out = np.empty_like(kth_array)
```

**Comment by pashaPASHaa** [comment]
maybe `if k < -a.shape[-1] or k >= a.shape[-1]` (second constraint is different, also no need for `(k < 0)` and `(k > 0)`)?

**Comment by esc** [comment]
> maybe `if k < -a.shape[-1] or k >= a.shape[-1]` (second constraint is different, also no need for `(k < 0)` and `(k > 0)`)?

Now that you mention it, `not (-a.shape[-1] <= k < a.shape[-1])` would probably also work?

**Comment by esc** [comment]
@pashaPASHaa if you have capacity, feel free to open a PR for this. You'd need to add an explicit test for this too, to make sure we don't see any regressions.
