### ISSUE TITLE
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_OPERATING_SYSTEM (30

### ISSUE THREAD

**Issue by ssungchae** [numba/numba#9134]
When I turned the learning around, I started using numba, but this error occurred whether there was a problem with the cuda.

I used the cuda simulator through the $ export NUMBA_ENABLE_CUDASIM=1 command, but I didn't get an error, but I want to use the gpu I have on the server, so I ask about this error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 34, in <module>
    from tridet.evaluators import get_evaluator
  File "/home/work/dd3d/dd3d-supplement-develop2/tridet/evaluators/__init__.py", line 8, in <module>
    from tridet.evaluators.kitti_3d_evaluator import KITTI3DEvaluator
  File "/home/work/dd3d/dd3d-supplement-develop2/tridet/evaluators/kitti_3d_evaluator.py", line 23, in <module>
    from tridet.evaluators.rotate_iou import d3_box_overlap_kernel, rotate_iou_gpu_eval
  File "/home/work/dd3d/dd3d-supplement-develop2/tridet/evaluators/rotate_iou.py", line 17, in <module>
    cuda.select_device(local_rank)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/api.py", line 437, in select_device
    context = devices.get_context(device_id)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 144, in get_or_create_context
    return self._activate_context_for(devnum)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 176, in _activate_context_for
    gpu = self.gpus[devnum]
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 40, in __getitem__
    return self.lst[devnum]
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/devices.py", line 26, in __getattr__
    numdev = driver.get_device_count()
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 428, in get_device_count
    self.cuDeviceGetCount(byref(count))
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 296, in __getattr__
    self.ensure_initialized()
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/driver.py", line 262, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_OPERATING_SYSTEM (304)

Can you give me some advice on how to solve it? Nvidia driver, cuda's libraries are compatible

Please help me..

**Comment by gmarkall** [comment]
What is the output of:

```
python -c "from numba import cuda; cuda.cudadrv.libs.test()"
```

?

**Comment by ssungchae** [comment]
My output : 

**Finding driver from candidates: libcuda.so, libcuda.so.1, /usr/lib/libcuda.so, /usr/lib/libcuda.so.1, /usr/lib64/libcuda.so, /usr/lib64/libcuda.so.1...
Using loader <class 'ctypes.CDLL'>
        trying to load driver...        ok, loaded from libcuda.so
Finding nvvm from Conda environment
        located at /home/work/.conda/envs/dd3d/lib/libnvvm.so.4.0.0
        trying to open library...       ok
Finding cudart from Conda environment
        located at /home/work/.conda/envs/dd3d/lib/libcudart.so.11.6.55
        trying to open library...       ok
Finding cudadevrt from Conda environment
        located at /home/work/.conda/envs/dd3d/lib/libcudadevrt.a
Finding libdevice from Conda environment
        trying to open library...       ok**

**Comment by ssungchae** [comment]
It came up like this when I looked into $numba-s. Isn't it not supposed to be like this?


__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA NVIDIA Bindings Available                : ?
CUDA NVIDIA Bindings In Use                   : ?
CUDA Minor Version Compatibility Available    : ?
CUDA Minor Version Compatibility Needed       : ?
CUDA Minor Version Compatibility In Use       : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

**Comment by gmarkall** [comment]
Thanks - do any non-Numba CUDA programs work?

**Comment by ssungchae** [comment]
This error occurs when you run an example of accelerating a simple operation to CUDA that adds two vectors.


  File "cuda_test.py", line 32, in <module>
    main()
  File "cuda_test.py", line 24, in main
    vector_add[blocks_per_grid, threads_per_block](d_a, d_b, d_c)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/dispatcher.py", line 541, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/dispatcher.py", line 675, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/dispatcher.py", line 683, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/dispatcher.py", line 926, in compile
    kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/dispatcher.py", line 103, in __init__
    self.cooperative = 'cudaCGGetIntrinsicHandle' in lib.get_asm_str()
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/codegen.py", line 108, in get_asm_str
    return self._join_ptxes(self._get_ptxes(cc=cc))
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/codegen.py", line 120, in _get_ptxes
    arch = nvvm.get_arch_option(*cc)
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 447, in get_arch_option
    arch = find_closest_arch((major, minor))
  File "/home/work/.conda/envs/dd3d/lib/python3.8/site-packages/numba/cuda/cudadrv/nvvm.py", line 420, in find_closest_arch
    raise NvvmSupportError(msg)
numba.cuda.cudadrv.error.NvvmSupportError: No supported GPU compute capabilities found. Please check your cudatoolkit version matches your CUDA version.
