### ISSUE TITLE
Nested lists prevent compilation with jitclass

### ISSUE THREAD

**Issue by jstovold** [numba/numba#9165]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Nested lists appear to prevent compilation with @jitclass. 

Compiling the following code:
```
from numba.typed import List
from numba import types
from numba.experimental import jitclass


@jitclass()
class bar:
    baz: types.ListType(types.ListType(types.int32))

    def __init__(self):
        self.baz = List(List([types.int32(x) for x in range(0)]))

    def foo(self):
        a = List([types.int32(x) for x in range(0)])
        a.append(2)
        self.baz.append(a)
        return(self.baz)


test = bar()
print(test.foo())
```

gives the following error:

```
Traceback (most recent call last):
  File "/Users/jamesstovold/Documents/Code/MarkovBrain-NCA/test/testclass.py", line 20, in <module>
    test = bar()
  File "/opt/homebrew/lib/python3.9/site-packages/numba/experimental/jitclass/base.py", line 124, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/opt/homebrew/lib/python3.9/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: native lowering)
Cannot cast ListType[int32] to ListType[ListType[int32]]: %"inserted.data.2" = insertvalue {i8*, i8*} %"inserted.meminfo.2", i8* %".428", 1
During: lowering "(self).baz = $24call_function.11" at /Users/jamesstovold/Documents/Code/MarkovBrain-NCA/test/testclass.py (11)
During: resolving callee type: jitclass.bar#118f6f9a0<baz:ListType[ListType[int32]]>
During: typing of call at <string> (3)

During: resolving callee type: jitclass.bar#118f6f9a0<baz:ListType[ListType[int32]]>
During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>
```

**Comment by sklam** [comment]
There's an error in the code. It's missing a square bracket:

```python

    def __init__(self):
        self.baz = List([List([types.int32(x) for x in range(0)])])
        # --------------^----------------------------------------^
```

The `typed.List` has the same behavior as the builtin `list`:

```python
>>> a = [1, 2]
>>> b = list(a)  
>>> b
[1, 2]
>>> c = list([a])   # what is intended
>>> c
[[1, 2]]
```
