### ISSUE TITLE
vectorize fails on datetime

### ISSUE THREAD

**Issue by cpcloud** [numba/numba#917]
There are a couple issues here:

When I construct a function with `vectorize`, seemingly equivalent ways to construct the signature yield different errors:

First try:

``` python
import numpy as nb
import numpy as np

@nb.vectorize(nb.types.NPDatetime('us')(nb.int64))
def convert_it(x):
    return np.datetime64(x)
```

gives: `TypeError: 'NotImplementedType' object is not callable`

Second try:

``` python
import numba as nb
import numpy as np

@nb.vectorize('NPDatetime("us")(int64)')
def convert_it(x):
    return np.datetime64(x)
```

gives: `TypeError: Invalid datetime metadata string "(us)" at position 1`.

In the latter case, the signature name `'datetime64(ns)` is being passed to `np.dtype` here: https://github.com/numba/numba/blob/master/numba/npyufunc/ufuncbuilder.py#L158 which fails because it should be `datetime64[ns]`. However after adding that change, numba crashes the interpreter:

``` diff
diff --git a/numba/types.py b/numba/types.py
index d4b7438..284a35a 100644
--- a/numba/types.py
+++ b/numba/types.py
@@ -212,7 +212,7 @@ class _NPDatetimeBase(Type):
     """

     def __init__(self, unit, *args, **kws):
-        name = '%s(%s)' % (self.type_name, unit)
+        name = '%s[%s]' % (self.type_name, unit)
         self.unit = unit
         self.unit_code = npdatetime.DATETIME_UNITS[self.unit]
         super(_NPDatetimeBase, self).__init__(name, *args, **kws)
```

``` python
In [3]: @nb.vectorize('NPDatetime("us")(int64)')
def convert_it(x):
    return np.datetime64(x)
   ...:

In [4]: convert_it(np.datetime64('now').view('int64'))
/Users/pcloud/miniconda/envs/py27/bin/python.app: line 3: 22194 Segmentation fault: 11
```

**Comment by pitrou** [comment]
@cpcloud , it seems numpy won't less us call ufuncs with non-unitless datetimes and timedeltas, so we're cooked:

```
>>> def identity(x): return x
... 
>>> ii = vectorize([types.NPTimedelta('s')(types.NPTimedelta('s'))], nopython=True)(identity)
>>> ii(np.timedelta64(5))
numpy.timedelta64(5)
>>> ii(np.array([np.timedelta64(5)]))
array([5], dtype=timedelta64)
>>> ii(np.timedelta64(5, 's'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'ufunc' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
>>> ii(np.array([np.timedelta64(5, 's')]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: ufunc 'ufunc' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

Built-in ufuncs such as np.add use a special resolver (e.g. `PyUFunc_AdditionTypeResolver`) that hardcode some datetime coercion rules. Numba ufuncs can only use the generic resolver (`PyUFunc_DefaultTypeResolver`), short of reimplementing our own resolver...

So if you want to vectorize datetime/timedelta operations, my best advice would be to use ``@jit``, not ``@vectorize``.

**Comment by jzwinck** [comment]
@pitrou I just stumbled upon this limitation, which for people who do a lot of work with time-series data is a significant one.  Has anything been done to communicate with the NumPy developers about getting a fix in NumPy that would enable supporting time units in Numba vectorize?

**Comment by sklam** [comment]
Categorizing this as a feature request that is awaiting changes in NumPy. Numpy has plans to improve ufunc dispatch (https://github.com/numpy/numpy/pull/16723)

**Comment by itamarst** [comment]
The NumPy PR above has been merged, and apparently there is now a C API. 

Would the easy solution just be copying the code for `PyUFunc_AdditionTypeResolver` into Numba and using that as a resolver?

**Comment by itamarst** [comment]
Just bumping this, would the idea above work?
