### ISSUE TITLE
Numba Dispatch error when Number of keyword args > 3 for nested numba calls

### ISSUE THREAD

**Issue by rishabh1212** [numba/numba#9185]
This error happens when defining function `*` is used. I can start with three function definition cases, The first two cases are passed, and the third one which is a minor modification of the second test case fails.

Numba version: '0.57.1'
Python version: '3.9.17'

## Pass Test 1
```python
import numba as nb
def test_1(a, b, c, d, e, f, g):
    return a + b + c + d + e + f + g
test_1 = nb.njit(test_1)

def test_2(a, b, c, d, e, f, g):
    return test_1(a, b, c, d, e, f, g)
test_2 = nb.njit(test_2)
test_2(1, 2, 3, 4, 5, 6, 7)
```

## Pass Test 2
```python
import numba as nb
def test_1(a, b, c, *, d, e, f):
    return a + b + c + d + e + f
test_1 = nb.njit(test_1)

def test_2(a, b, c, d, e, f, g):
    return test_1(a, b, c, d, e, f)
test_2 = nb.njit(test_2)
test_2(1, 2, 3, 4, 5, 6, 7)
```

## Fail Test 3
```python
import numba as nb
def test_1(a, b, c, *, d, e, f, g):
    return a + b + c + d + e + f
test_1 = nb.njit(test_1)

def test_2(a, b, c, d, e, f, g):
    return test_1(a, b, c, d, e, f, g)
test_2 = nb.njit(test_2)
test_2(1, 2, 3, 4, 5, 6, 7)
```
### Error traceback
```
---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
Cell In[10], line 9
      7 test_2 = nb.njit(test_2)
      8 # test_1(1, 2, 3, 4, 5, 6, 7)
----> 9 test_2(1, 2, 3, 4, 5, 6, 7)

File ~/.cache/pypoetry/virtualenvs/indices-ldm-post-process-danSbNDA-py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py:467, in _DispatcherBase._compile_for_args(self, *args, **kws)
    464         msg = (f"{str(e).rstrip()} \n\nThis error may have been caused "
    465                f"by the following argument(s):\n{args_str}\n")
    466         e.patch_message(msg)
--> 467     error_rewrite(e, 'typing')
    468 except errors.UnsupportedError as e:
    469     # Something unsupported is present in the user code, add help info
    470     error_rewrite(e, 'unsupported_error')

File ~/.cache/pypoetry/virtualenvs/indices-ldm-post-process-danSbNDA-py3.9/lib/python3.9/site-packages/numba/core/dispatcher.py:409, in _DispatcherBase._compile_for_args..error_rewrite(e, issue_type)
    407     raise e
    408 else:
--> 409     raise e.with_traceback(None)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at .
tuple index out of range
During: resolving callee type: type(CPUDispatcher())
During: typing of call at /tmp/ipykernel_3435313/3644502072.py (6)

Enable logging at debug level for details.
```

## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by guilhermeleobas** [comment]
Hi @rishabh1212, thanks for the report. I can confirm the bug in Numba main branch.

**Comment by gmarkall** [comment]
However, with arguments passed as keyword arguments:

```python
from numba import njit

@njit
def test_1(a, b, c, *, d, e, f, g):
    return a + b + c + d + e + f

@njit
def test_2(a, b, c, d, e, f, g):
    return test_1(a, b, c, d=d, e=e, f=f, g=g)
test_2(1, 2, 3, 4, 5, 6, 7)
```

We do still have a problem:

```
$ python nbtest.py 
Traceback (most recent call last):
  File "/home/gmarkall/numbadev/issues/9185/nbtest.py", line 10, in <module>
    test_2(1, 2, 3, 4, 5, 6, 7)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 965, in compile
    cres = self._compiler.compile(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 504, in _compile_core
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 364, in run
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/gmarkall/numbadev/numba/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/home/gmarkall/numbadev/numba/numba/core/typed_passes.py", line 88, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1078, in propagate
    errors = self.constraints.propagate(self)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 177, in propagate
    raise e
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 155, in propagate
    constraint(typeinfer)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 578, in __call__
    self.resolve(typeinfer, typevars, fnty)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 601, in resolve
    sig = typeinfer.resolve_call(fnty, pos_args, kw_args)
  File "/home/gmarkall/numbadev/numba/numba/core/typeinfer.py", line 1557, in resolve_call
    return self.context.resolve_function_type(fnty, pos_args, kw_args)
  File "/home/gmarkall/numbadev/numba/numba/core/typing/context.py", line 196, in resolve_function_type
    res = self._resolve_user_function_type(func, args, kws)
  File "/home/gmarkall/numbadev/numba/numba/core/typing/context.py", line 248, in _resolve_user_function_type
    return func.get_call_type(self, args, kws)
  File "/home/gmarkall/numbadev/numba/numba/core/types/functions.py", line 541, in get_call_type
    self.dispatcher.get_call_template(args, kws)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 359, in get_call_template
    pysig, args = self._compiler.fold_argument_types(args, kws)
  File "/home/gmarkall/numbadev/numba/numba/core/dispatcher.py", line 118, in fold_argument_types
    args = fold_arguments(self.pysig, args, kws,
  File "/home/gmarkall/numbadev/numba/numba/core/typing/templates.py", line 218, in fold_arguments
    bind_kws[n] = args[len(kwonly) + idx]
IndexError: tuple index out of range
```

**Comment by rishabh1212** [comment]
@gmarkall for https://github.com/numba/numba/issues/9185#issuecomment-1715806562
Look at `Pass Test 2`, even without passing as kwargs it is successfull.

**Comment by rishabh1212** [comment]
@guilhermeleobas 
>It fails in the interpreter:

Yes, it is expected and thus not part of my tests. I would expect same results for `Test2` and `Test3` but one is pass another is fail
