### ISSUE TITLE
`FunctionType` called by another jitted function throws a `ValueError`

### ISSUE THREAD

**Issue by dlee992** [numba/numba#9206]
```python
import os

from numba import njit
from numba.core.types import FunctionType, int64
from numba.extending import overload_method

# os.environ["NUMBA_DUMP_OPTIMIZED"] = "1"

func_type = FunctionType(int64(int64,))

@njit(int64(func_type))
def f(g):
    return g(1)

@njit(no_cfunc_wrapper=True)
def g(a):
    return a + 1

print(f(g))
```
Throws
```
Traceback (most recent call last):
  File "xx.py", line 21, in <module>
    print(f(g))
  File "numba/experimental/function_type.py", line 163, in _get_wrapper_address
    raise ValueError(f'wrapper address of {type(func)} instance must be'
ValueError: wrapper address of <class 'numba.core.registry.CPUDispatcher'> instance must be a positive integer but got 0 [sig=(int64,) -> int64]
```
In principle, `g` isn't called by C function, I don't think it should have a `cfunc_wrapper`. But removing it will trigger this error.

**Comment by sklam** [comment]
First class function is currently [implemented by going through the cfunc-wrapper](https://github.com/numba/numba/blob/596e8a55334cc46854e3192766e643767bd7c934/numba/experimental/function_type.py#L50-L56). But you are right that it doesn't need to. The `FunctionModel` can be extended with a third pointer that directly uses the function pointer of the Numba function without the cfunc-wrapper.
