### ISSUE TITLE
Caching causes error in structref overloading

### ISSUE THREAD

**Issue by plutonium-94** [numba/numba#9243]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

I've encountered a bug where caching causes an error when overloading attribute of structref in numba. When I run the following code once (without caching), it works as expected. But when I run it again (with caching enabled), it throws an error. If I disable caching, then the code always works correctly.

Here is the code to reproduce the issue:

```python
from numba import types, njit
from numba.experimental import structref
from numba.extending import overload_attribute


@structref.register
class ExampleType(types.StructRef):
    pass


class Example(structref.StructRefProxy):
    @property
    @njit
    def p(self):
        return self.p


@overload_attribute(ExampleType, 'p')
def ol_structref_getattr(self):
    return lambda self: self.x


structref.define_proxy(Example, ExampleType, ('x',))


@njit(cache=True)
def init():
    return Example(0)


print(init().p)
```

And here is the error message:

```
Traceback (most recent call last):
  File "numba_cache_property.py", line 32, in <module>
    print(init().p)
  File "\lib\site-packages\numba\core\dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "\lib\site-packages\numba\core\dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'p' of type numba.ExampleType(('x', int64),)

File "numba_cache_property.py", line 16:
    def p(self):
        return self.p
        ^

During: typing of get attribute at numba_cache_property.py (16)

File "numba_cache_property.py", line 16:
    def p(self):
        return self.p
        ^

```

Operating System: Windows 10
Python Environment: Anaconda Python 3.10.13

**Comment by sklam** [comment]
I have debugged this problem and the root problem is an odd behavior with `cloudpickle` and the `__main__` module such that the `ExampleType` on the first run is treated as different to the `ExampleType` in the subsequent run. 

If I run the script as:

```bash
python -c "import script"
```
instead of
```bash
python script.py
```
it work.

My advice is to put the `ExampleType` outside of the `__main__` script (where `__name__ == "__main__"`).

**Comment by plutonium-94** [comment]
Yes, it is a problem related with `__name__` and modules. When I added
```python
import sys

__name__ = 'some_arbitrary_name'
sys.modules[__name__] = sys.modules.pop('__main__')
```
on top of the script, it was fixed immediately.

**Comment by yxdragon** [comment]
Thank you very much. I found that the structref cache misses [](https://github.com/numba/numba/issues/10021) are also caused by this reason, so is this a bug in pickle? How can we report it to Python?

**Comment by plutonium-94** [comment]
> Thank you very much. I found that the structref cache misses [#10021](https://github.com/numba/numba/issues/10021) are also caused by this reason, so is this a bug in pickle? How can we report it to Python?

As far as I know, `cloudpickle` is different from `pickle`, so this may not be a Python issue.
