### ISSUE TITLE
GIL tests not totally reliable

### ISSUE THREAD

**Issue by pitrou** [numba/numba#926]
Encountered this on Travis, perhaps we need to allow for more threads yet:

```
======================================================================

FAIL: test_gil_released_inside_lifted_loop (numba.tests.test_gil.TestGILRelease)

----------------------------------------------------------------------

Traceback (most recent call last):

File "/home/travis/miniconda3/envs/travisci/lib/python3.3/site-packages/numba/tests/test_gil.py", line 134, in test_gil_released_inside_lifted_loop

self.check_gil_released(cfunc)

File "/home/travis/miniconda3/envs/travisci/lib/python3.3/site-packages/numba/tests/test_gil.py", line 110, in check_gil_released

raise failure

File "/home/travis/miniconda3/envs/travisci/lib/python3.3/site-packages/numba/tests/test_gil.py", line 105, in check_gil_released

self.assertGreater(len(distinct), 1, distinct)

AssertionError: 1 not greater than 1 : {140083955275520}
```

**Comment by seibert** [comment]
Closing as I think this is no longer an issue.
