### ISSUE TITLE
Deferred types broken for jitclass

### ISSUE THREAD

**Issue by Azmisov** [numba/numba#9264]
Here I have reproducer with three test cases to demonstrate:

```python
from numba import deferred_type, njit
from numba.extending import as_numba_type
from numba.experimental import jitclass

test_case = 2

# works, single deferred member
if test_case == 0:
	DeferredBType = deferred_type()

	@jitclass([('b', DeferredBType)])
	class A:
		def __init__(self, b):
			self.b = b

	@jitclass
	class B:
		def __init__(self): pass
	BType = as_numba_type(B)
	DeferredBType.define(BType)

	@njit
	def test():
		b = B()
		a = A(b)

	test()

# fails, two deferred members
if test_case == 1:
	DeferredBType = deferred_type()
	DeferredCType = deferred_type()

	@jitclass([('b', DeferredBType), ('c', DeferredCType)])
	class A:
		def __init__(self, b):
			self.b = b

	@jitclass
	class B:
		def __init__(self): pass
	BType = as_numba_type(B)
	DeferredBType.define(BType)

	@jitclass
	class C:
		def __init__(self): pass
	CType = as_numba_type(C)
	DeferredCType.define(CType)

	@njit
	def test():
		b = B()
		a = A(b)

	test()

# fails, two deferred members (different error message)
if test_case == 2:
	DeferredBType = deferred_type()
	DeferredCType = deferred_type()

	@jitclass([('b', DeferredBType), ('c', DeferredCType)])
	class A:
		def __init__(self): pass

	@jitclass
	class B:
		def __init__(self): pass
	BType = as_numba_type(B)
	DeferredBType.define(BType)

	@jitclass
	class C:
		def __init__(self): pass
	CType = as_numba_type(C)
	DeferredCType.define(CType)

	@njit
	def test():
		a = A()

	test()
```

First test case is just a jitclass with a single deferred member. This works as expected

Second test case just adds a second deferred member. We get an error:

```
test.py:30: NumbaPendingDeprecationWarning: Code using Numba extension API maybe depending on 'old_style' error-capturing, which is deprecated and will be replaced by 'new_style' in a future release. See details at https://numba.readthedocs.io/en/latest/reference/deprecation.html#deprecation-of-old-style-numba-captured-errors
Exception origin:
  File "site-packages/llvmlite/binding/module.py", line 25, in parse_assembly
    raise RuntimeError("LLVM IR parsing error\n{0}".format(errmsg))

  a = A(b)
Traceback (most recent call last):
  File "test.py", line 32, in <module>
    test()
  File "site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.core.typeinfer.CallConstraint object at 0x7eff03a58e90>.
Failed in nopython mode pipeline (step: native lowering)
LLVM IR parsing error
<string>:31:105: error: base element of getelementptr must be sized
  %".17" = getelementptr inbounds {%"deferred.139634571830160.data", %"deferred.139633764192912.data"}, {%"deferred.139634571830160.data", %"deferred.139633764192912.data"}* %".16", i32 0, i32 0
                                                                                                        ^

During: resolving callee type: jitclass.A#7eff04346f10<b:DeferredType#139634571830160,c:DeferredType#139633764192912>
During: typing of call at test.py (30)

Enable logging at debug level for details.

File "test.py", line 30:
def test():
    <source elided>
        b = B()
        a = A(b)
 ^
```

Third test case is the same as the second, except we've removed A's constructor. Same structs, but we get a different error this time:
```
python: /root/miniconda3/envs/buildenv/conda-bld/llvmdev_1680545119445/work/llvm/lib/IR/DataLayout.cpp:748: llvm::Align llvm::DataLayout::getAlignment(llvm::Type*, bool) const: Assertion `Ty->isSized() && "Cannot getTypeInfo() on a type that is unsized!"' failed.
Aborted (core dumped)
```

The third test case has a similar error message to #8404, so maybe the same underlying cause. The second test case error is different however, and this reproducer does not use typed.Dict to trigger it.

Tested on Python 3.11.5, Numba 0.58.1

**Comment by gmarkall** [comment]
Many thanks for the report and detailed reproducer - I can reproduce this with Numba `main`.

**Comment by gmarkall** [comment]
From discussion in the triage meeting - this is an issue that is likely to be resolved by switching the internals of jitclasses to use StructRefs, but this is a long-term ambition / project.
