### ISSUE TITLE
Numba compiled `np.dot` doesn't support type promotion of different data types

### ISSUE THREAD

**Issue by lgeiger** [numba/numba#9268]
When calling `np.dot` with different data types e.g. `float32` and `float64` numpy would automatically promote the data types to the higher precision one according to [`np.promote_types`](https://numpy.org/doc/stable/reference/generated/numpy.promote_types.html#numpy-promote-types).

With Numba `0.58.1` this isn't the case and calling `np.dot` with different dtypes causes the following error:
```python
import numba
import numpy as np

x = np.random.normal(size=512).astype(np.float32)
y = np.random.normal(size=512).astype(np.float64)

@numba.njit
def numba_dot(x, y):
    return np.dot(x, y)

numba_dot(x, y)
```

```
Traceback (most recent call last):
  File "/private/tmp/test.py", line 11, in <module>
    numba_dot(x, y)
  File "/usr/local/lib/python3.11/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/usr/local/lib/python3.11/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function dot>) found for signature:

 >>> dot(array(float32, 1d, C), array(float64, 1d, C))

There are 4 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'dot_2': File: numba/np/linalg.py: Line 525.
    With argument(s): '(array(float32, 1d, C), array(float64, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: Failed in nopython mode pipeline (step: nopython frontend)
   No implementation of function Function(<intrinsic _impl>) found for signature:

    >>> _impl(array(float32, 1d, C), array(float64, 1d, C))
import numba
import numba

   There are 2 candidate implementations:
     - Of which 2 did not match due to:
     Intrinsic in function 'dot_2_impl.<locals>._impl': File: numba/np/linalg.py: Line 543.
       With argument(s): '(array(float32, 1d, C), array(float64, 1d, C))':
      Rejected as the implementation raised a specific error:
        TypingError: np.dot() arguments must all have the same dtype
     raised from /usr/local/lib/python3.11/site-packages/numba/np/linalg.py:563

   During: resolving callee type: Function(<intrinsic _impl>)
   During: typing of call at /usr/local/lib/python3.11/site-packages/numba/np/linalg.py (582)


   File "../../usr/local/lib/python3.11/site-packages/numba/np/linalg.py", line 582:
               def _dot2_codegen(context, builder, sig, args):
                   <source elided>

           return lambda left, right: _impl(left, right)
           ^

  raised from /usr/local/lib/python3.11/site-packages/numba/core/typeinfer.py:1086
  - Of which 2 did not match due to:
  Overload in function 'dot_3': File: numba/np/linalg.py: Line 784.
    With argument(s): '(array(float32, 1d, C), array(float64, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: missing a required argument: 'out'
  raised from /usr/local/lib/python3.11/site-packages/numba/core/typing/templates.py:784

During: resolving callee type: Function(<built-in function dot>)
During: typing of call at /private/tmp/test.py (9)


File "test.py", line 9:
def numba_dot(x, y):
    return np.dot(x, y)
    ^
```

**Comment by gmarkall** [comment]
I think this might have been an intentional design decision, the rationale being that it helps the user avoid accidentally introducing implicit copies that would degrade performance. I will mention this at the issue triage meeting today to confirm.

**Comment by gmarkall** [comment]
This does seem to be the consensus in the triage meeting, but the documentation should state this more clearly, in particular in: https://numba.readthedocs.io/en/latest/reference/numpysupported.html#linear-algebra

As a workaround, explicit creation of a copy of the data with the required dtype needs to be made to call functions like `np.dot` - that way, the performance impact of the copy is made explicit.

**Comment by lgeiger** [comment]
@gmarkall thanks for taking a look. I understand the reasoning for making the copy explicit.

> As a workaround, explicit creation of a copy of the data with the required dtype needs to be made to call functions like `np.dot` - that way, the performance impact of the copy is made explicit.

This is pretty much what I am doing at the moment as some callers are still passing in arrays with different dtypes:
```python
@numba.njit
def generic_dot(x, y):
    x = x.astype(np.float32)
    y = y.astype(np.float32)
    return np.dot(x, y)
```
However this means that I am always paying for the copy even if both arguments are already of the correct type. At least that's what my benchmarks seem to suggest.

In plain Python I'd probably do 
```python
def generic_dot(x, y):
    if x.dtype != np.float32:
        x = x.astype(np.float32)
    if y.dtype != np.float32:
        y = y.astype(np.float32)
    return np.dot(x, y)
```
or
```python
def generic_dot(x, y):
    x = x.astype(np.float32, copy=False)
    y = y.astype(np.float32, copy=False)
    return np.dot(x, y)
```
or use `np.promote_types`. Though both will fail to compile with numba.

Even using
```python
def generic_dot(x, y):
    if x.dtype is not np.dtype(np.float32):
        x = x.astype(np.float32)
    if y.dtype is not np.dtype(np.float32):
        y = y.astype(np.float32)
    return np.dot(x, y)
```
doesn't seem to work inside `njit` as it fails to unify types at runtime.

Do you have any recommendations on how to implement a generic numba function which only pays for copying the data in case the types don't match?

**Comment by lgeiger** [comment]
For reference, replacing `.astype(np.float32)` with `np.asarray(..., dtype=np.float32)` seems to work as expected since it won't copy the array in case the dtypes match:
```python
@numba.njit
def generic_dot(x, y):
    x = np.asarray(x, dtype=np.float32)
    y = np.asarray(y, dtype=np.float32)
    return np.dot(x, y)
```

Though, it would still be good to support `copy=False` in `.astype()` as well.
