### ISSUE TITLE
CUDA kernel execution fails due to module not being found

### ISSUE THREAD

**Issue by COOLIRON2311** [numba/numba#9273]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

CUDA kernel in [my program](https://gist.github.com/COOLIRON2311/492c4eef7c0afb2450428a4dda6b8ce2) fails to execute due to `cudart.dll` not being found:
```
Traceback (most recent call last):
  File "C:\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "c:\Users\user\source\repos\CV\lab7\growcut.pyw", line 247, in start
    self.GrowCut[BPG, TPB](d_I, d_S, d_Theta)
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 673, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 681, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 914, in compile
    kernel = self._cache.load_overload(sig, self.targetctx)
  File "C:\Python310\lib\site-packages\numba\core\caching.py", line 635, in load_overload
    return self._load_overload(sig, target_context)
  File "C:\Python310\lib\site-packages\numba\core\caching.py", line 641, in _load_overload
    key = self._index_key(sig, target_context.codegen())
  File "C:\Python310\lib\site-packages\numba\core\caching.py", line 695, in _index_key
    return (sig, codegen.magic_tuple(), (hasher(codebytes),
  File "C:\Python310\lib\site-packages\numba\cuda\codegen.py", line 359, in magic_tuple
    return (runtime.runtime.get_version(), cc)
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\runtime.py", line 111, in get_version
    self.cudaRuntimeGetVersion(ctypes.byref(rtver))
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\runtime.py", line 65, in __getattr__
    self._initialize()
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\runtime.py", line 51, in _initialize
    self.lib = open_cudalib('cudart')
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\libs.py", line 64, in open_cudalib
    return ctypes.CDLL(path)
  File "C:\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'cudart.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

It had been running successfully about two weeks ago. Haven't changed anything in my system since. Neither Python nor CUDA Toolkit are installed via conda.

My PATH variable includes the following:
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\extras\CUPTI\lib64
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\nvvm\bin
```

## System configuration:
OS: Windows 11 23H2
Python: 3.10.11
Numba: 0.58.1
CUDA Toolkit: 12.2.0.53625
GPU Driver: GeForce Game Ready 546.01

**Comment by COOLIRON2311** [comment]
And I have another piece of code (old enough) which fails to run with a different error message:
```
C:\Python310\lib\site-packages\numba\core\utils.py:213: NumbaPendingDeprecationWarning: Code using Numba extension API maybe depending on 'old_style' error-capturing, which is deprecated and will be replaced by 'new_style' in a future release. See details at https://numba.readthedocs.io/en/latest/reference/deprecation.html#deprecation-of-old-style-numba-captured-errors
Exception origin:
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 144, in __new__
    raise NvvmSupportError(errmsg % e)

  warnings.warn(msg,
Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 139, in __new__
    inst.driver = open_cudalib('nvvm')
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\libs.py", line 64, in open_cudalib
    return ctypes.CDLL(path)
  File "C:\Python310\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'nvvm.dll' (or one of its dependencies). Try using the full path with constructor syntax.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\user\lab3.py", line 22, in <module>
    main()
  File "c:\Users\user\lab3.py", line 18, in main
    integrate[BLK, TPB](0, step, result)
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 673, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 681, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 924, in compile
    kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
  File "C:\Python310\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\numba\cuda\dispatcher.py", line 83, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
  File "C:\Python310\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\numba\cuda\compiler.py", line 194, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "C:\Python310\lib\site-packages\numba\core\compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Python310\lib\site-packages\numba\core\compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
  File "C:\Python310\lib\site-packages\numba\core\compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
  File "C:\Python310\lib\site-packages\numba\core\compiler.py", line 508, in _compile_core
    raise e
  File "C:\Python310\lib\site-packages\numba\core\compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "C:\Python310\lib\site-packages\numba\core\compiler_machinery.py", line 368, in run
    raise patched_exception
  File "C:\Python310\lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Python310\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Python310\lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Python310\lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "C:\Python310\lib\site-packages\numba\core\typed_passes.py", line 464, in run_pass
    lower = self.lowering_class(targetctx, library, fndesc, interp,
  File "C:\Python310\lib\site-packages\numba\core\lowering.py", line 39, in __init__
    self.module = self.library.create_ir_module(self.fndesc.unique_name)
  File "C:\Python310\lib\site-packages\numba\core\codegen.py", line 574, in create_ir_module
    ir_module = self._codegen._create_empty_module(name)
  File "C:\Python310\lib\site-packages\numba\cuda\codegen.py", line 346, in _create_empty_module
    ir_module.data_layout = nvvm.NVVM().data_layout
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\nvvm.py", line 144, in __new__
    raise NvvmSupportError(errmsg % e)
numba.cuda.cudadrv.error.NvvmSupportError: libNVVM cannot be found. Do `conda install cudatoolkit`:
Could not find module 'nvvm.dll' (or one of its dependencies). Try using the full path with constructor syntax.
```

**Comment by COOLIRON2311** [comment]
Hm... Turns out I for some reason had `CUDA_PATH_V12_2` environment variable instead of `CUDA_PATH` and numba for some reason did not respect that.

**Comment by gmarkall** [comment]
Can you provide the output of the command 

```
python -c "from numba import cuda; cuda.cudadrv.libs.test()"
```

please?

**Comment by gmarkall** [comment]
Oh, is the problem now solved?

**Comment by COOLIRON2311** [comment]
Kind of. I've managed to make all the programs run without any issues by renaming `CUDA_PATH_v12_2` to `CUDA_PATH`. One thing I can't quite figure out is why was it named like that in the first place. As far as I remember, I have installed CUDA Toolkit using the official distribution. With a help of `chocolatey` package manager to be precise.

**Comment by COOLIRON2311** [comment]
> Can you provide the output of the command
> 
> ```
> python -c "from numba import cuda; cuda.cudadrv.libs.test()"
> ```
> 
> please?

Sure thing! Now, if the environment variable, which points to CUDA Toolkit installation path, is named `CUDA_PATH` I get the following:
```
Finding driver from candidates:
        nvcuda.dll
        \windows\system32\nvcuda.dll
Using loader <class 'ctypes.WinDLL'>
        Trying to load driver...        ok
                Loaded from nvcuda.dll
Finding nvvm from CUDA_HOME
        Located at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\nvvm\bin\nvvm64_40_0.dll
        Trying to open library...       ok
Finding nvrtc from CUDA_HOME
        Located at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\nvrtc64_120_0.dll
        Trying to open library...       ok
Finding cudart from CUDA_HOME
        Located at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\bin\cudart64_12.dll
        Trying to open library...       ok
Finding cudadevrt from CUDA_HOME
        Located at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\lib\x64\cudadevrt.lib
        Checking library...     ok
Finding libdevice from CUDA_HOME
        Located at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.2\nvvm\libdevice\libdevice.10.bc
        Checking library...     ok
```

And if I rename it to `CUDA_PATH_v12_2` just the way (I suppose) the installer did, I get this output:
```
Finding driver from candidates:
        nvcuda.dll
        \windows\system32\nvcuda.dll
Using loader <class 'ctypes.WinDLL'>
        Trying to load driver...        ok
                Loaded from nvcuda.dll
Finding nvvm from <unknown>
        Located at nvvm.dll
        Trying to open library...       ERROR: failed to open nvvm:
Could not find module 'nvvm.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Finding nvrtc from <unknown>
        Located at nvrtc.dll
        Trying to open library...       ERROR: failed to open nvrtc:
Could not find module 'nvrtc.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Finding cudart from <unknown>
        Located at cudart.dll
        Trying to open library...       ERROR: failed to open cudart:
Could not find module 'cudart.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Finding cudadevrt from <unknown>
        Located at cudadevrt.lib
        Checking library...     ERROR: failed to find cudadevrt:
cudadevrt.lib not found
Finding libdevice from <unknown>
        Located at None
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\libs.py", line 169, in test
    check_static_lib(path)
  File "C:\Python310\lib\site-packages\numba\cuda\cudadrv\libs.py", line 68, in check_static_lib
    if not os.path.isfile(path):
  File "C:\Python310\lib\genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
        Checking library...
```

**Comment by gmarkall** [comment]
Thanks for closing, @COOLIRON2311 - I'm not sure exactly why you didn't have `CUDA_PATH` set, but I'm glad the issue is fixed (and I dont think there's anything specific to Numba here).
