### ISSUE TITLE
numba/core/bytecode.py, line 226, in _compute_lineno     def _compute_lineno(cls, table, code): KeyError: 2

### ISSUE THREAD

**Issue by caicaiwoshishei132** [numba/numba#9275]
> **System ### configuration:**

ubuntu
conda 23.5.2
Python 3.7.0
numba 0.53.0
librosa 0.9.2
resampy 0.4.2
numpy 1.21.6

### After using nuitka to package the funasr project, the following problem occurs:

```
Traceback (most recent call last):
  File "/tmp/myapp/demo.py", line 10, in <module>
    result = model(wav_path)
  File "/tmp/myapp/funasr_onnx/paraformer_bin.py", line 92, in __call__
  File "/tmp/myapp/funasr_onnx/paraformer_bin.py", line 164, in load_data
  File "/tmp/myapp/funasr_onnx/paraformer_bin.py", line 154, in load_wav
  File "/tmp/myapp/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/tmp/myapp/librosa/core/audio.py", line 179, in load
    y = resample(y, orig_sr=sr_native, target_sr=sr, res_type=res_type)
  File "/tmp/myapp/librosa/util/decorators.py", line 88, in inner_f
    return f(*args, **kwargs)
  File "/tmp/myapp/librosa/core/audio.py", line 647, in resample
    y_hat = resampy.resample(y, orig_sr, target_sr, filter=res_type, axis=-1)
  File "/tmp/myapp/resampy/core.py", line 168, in resample
    resample_f_s(
  File "/tmp/myapp/numba/np/ufunc/gufunc.py", line 143, in __call__
    
  File "/tmp/myapp/numba/np/ufunc/gufunc.py", line 32, in add
    
  File "/tmp/myapp/numba/np/ufunc/ufuncbuilder.py", line 212, in add
    _identities = {
  File "/tmp/myapp/numba/np/ufunc/ufuncbuilder.py", line 144, in _compile_element_wise_function
    with global_compiler_lock:
  File "/tmp/myapp/numba/np/ufunc/ufuncbuilder.py", line 93, in compile
    
  File "/tmp/myapp/numba/np/ufunc/ufuncbuilder.py", line 125, in _compile_core
    Trigger the compiler on the core function or load a previously
  File "/tmp/myapp/numba/core/compiler.py", line 606, in compile_extra
    pm.add_pass(PreParforPass, "Preprocessing for parfors")
  File "/tmp/myapp/numba/core/compiler.py", line 349, in compile_extra
    vals.append("{k}={v}".format(k=k, v=getattr(self, k)))
  File "/tmp/myapp/numba/core/untyped_passes.py", line 64, in run_pass
    bc = bytecode.ByteCode(func_id)
  File "/tmp/myapp/numba/core/bytecode.py", line 204, in __init__
    'co_cellvars', 'co_freevars', 'table', 'labels')
  File "/tmp/myapp/numba/core/bytecode.py", line 226, in _compute_lineno
    def _compute_lineno(cls, table, code):
KeyError: 2
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=aten, dispatch_key=Meta)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=prims, dispatch_key=CompositeExplicitAutograd)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=prims, dispatch_key=BackendSelect)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=prims, dispatch_key=Autograd)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=prims, dispatch_key=Meta)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=nvprims, dispatch_key=CompositeExplicitAutograd)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=nvprims, dispatch_key=CompositeImplicitAutograd)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=nvprims, dispatch_key=Autograd)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=nvprims, dispatch_key=Meta)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'
Exception ignored in: <bound compiled_method Library.__del__ of Library(kind=IMPL, ns=aten, dispatch_key=Meta)>>
Traceback (most recent call last):
  File "/tmp/myapp/torch/library.py", line 139, in __del__
AttributeError: 'NoneType' object has no attribute 'remove'

```

**Comment by esc** [comment]
@caicaiwoshishei132 thank you for your report. Unfortunately this is insufficient to reproduce, please provide more info.

**Comment by gmarkall** [comment]
If you have packaged / compiled a package iwth Nuitka, does the bytecode still exist? Whilst what @esc says is true, that there's not enough info here, I do wonder if what you're trying to do could even be expected to work.

**Comment by esc** [comment]
@caicaiwoshishei132 I will close this now as we have not received a response from you. If this issue persists, please follow up with more information and we will be happy to re-open this issue.
