### ISSUE TITLE
NumPy like slice operations don't seem to work in CUDA mode

### ISSUE THREAD

**Issue by bluenote10** [numba/numba#9324]
This is perhaps somewhere in-between a bug report and a feature request.

The Numba for CUDA documentation mentions under [NumPy support](https://numba.readthedocs.io/en/stable/cuda/cudapysupported.html#numpy-support) and the supported NumPy features:

> indexing and slicing works.

I'm trying to make use of basic slicing operations for mutation but they don't seem to work in CUDA mode, while do work in regular Numba CPU mode.

## Feature request

Minimal reproducible example:

```py
import numba.cuda
import numpy as np

def f(array):
    # This works:
    array[0, 0] += 10
    # But these don't work
    array[:, 1] += 1.0
    array[:, 1] = array[:, 0]

f_cpu = numba.njit(f)
f_gpu = numba.cuda.jit(f)

array_cpu = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
array_gpu = numba.cuda.to_device(array_cpu)

print("\nRunning on CPU:")
f_cpu(array_cpu)
print(array_cpu)

print("\nRunning on GPU:")
f_gpu[1, 1](array_gpu)  # type: ignore
print(array_gpu)
```

On CPU this example works. When running in CUDA mode the `array[:, 1] += 1.0` line fails with:

<details>
<summary>Errors in "slice + scalar" case</summary>

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/fabian/git/_ext/ddsp_pytorch/ddsp/experiments/debug/debug_numba_gpu_operations_minimal.py", line 29, in <module>
    f_gpu[1, 1](array_gpu)  # type: ignore
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 673, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 681, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 924, in compile
    kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 83, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/compiler.py", line 194, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 508, in _compile_core
    raise e
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/typed_passes.py", line 91, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/typeinfer.py", line 1086, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in cuda mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function iadd>) found for signature:
 
 >>> iadd(array(float32, 1d, A), float64)
 
There are 14 candidate implementations:
  - Of which 12 did not match due to:
  Overload of function 'iadd': File: <numerous>: Line N/A.
    With argument(s): '(array(float32, 1d, A), float64)':
   No match.
  - Of which 2 did not match due to:
  Operator Overload in function 'iadd': File: unknown: Line unknown.
    With argument(s): '(array(float32, 1d, A), float64)':
   No match for registered cases:
    * (int64, int64) -> int64
    * (int64, uint64) -> int64
    * (uint64, int64) -> int64
    * (uint64, uint64) -> uint64
    * (float32, float32) -> float32
    * (float64, float64) -> float64
    * (complex64, complex64) -> complex64
    * (complex128, complex128) -> complex128

During: typing of intrinsic-call at /home/fabian/git/_ext/ddsp_pytorch/ddsp/experiments/debug/debug_numba_gpu_operations_minimal.py (13)

File "ddsp/experiments/debug/debug_numba_gpu_operations_minimal.py", line 13:
def f(array):
    <source elided>
    # But these don't work
    array[:, 1] += 1.0
    ^
```

</details>

The `array[:, 1] = array[:, 0]` line fails with:

<details>
<summary>Errors in "slice + slice" case</summary>

```
Traceback (most recent call last):
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/lowering.py", line 512, in lower_inst
    impl = self.context.get_function('static_setitem', signature)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/base.py", line 556, in get_function
    return self.get_function(fn, sig, _firstcall=False)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/base.py", line 558, in get_function
    raise NotImplementedError("No definition for lowering %s%s" % (key, sig))
NotImplementedError: No definition for lowering static_setitem(Array(float32, 2, 'C', False, aligned=True), Tuple((slice<a:b>, int64)), Array(float32, 1, 'A', False, aligned=True)) -> none

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/fabian/git/_ext/ddsp_pytorch/ddsp/experiments/debug/debug_numba_gpu_operations_minimal.py", line 29, in <module>
    f_gpu[1, 1](array_gpu)  # type: ignore
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 673, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 681, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 924, in compile
    kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/dispatcher.py", line 83, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/cuda/compiler.py", line 194, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 508, in _compile_core
    raise e
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/typed_passes.py", line 466, in run_pass
    lower.lower()
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/lowering.py", line 187, in lower
    self.lower_normal_function(self.fndesc)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/lowering.py", line 241, in lower_normal_function
    entry_block_tail = self.lower_function_body()
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/lowering.py", line 271, in lower_function_body
    self.lower_block(block)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/lowering.py", line 285, in lower_block
    self.lower_inst(inst)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/lowering.py", line 514, in lower_inst
    return self.lower_setitem(inst.target, inst.index_var,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/lowering.py", line 625, in lower_setitem
    return impl(self.builder, (target, index, value))
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/base.py", line 1187, in __call__
    res = self._imp(self._context, builder, self._sig, args, loc=loc)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/base.py", line 1217, in wrapper
    return fn(*args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/np/arrayobj.py", line 554, in setitem_array
    return fancy_setslice(context, builder, sig, args,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/np/arrayobj.py", line 1675, in fancy_setslice
    src_getitem, src_cleanup = maybe_copy_source(context, builder, use_copy,
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/np/arrayobj.py", line 1248, in maybe_copy_source
    data = context.nrt.allocate(builder, allocsize)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/runtime/context.py", line 47, in wrap
    memptr = func(self, builder, *args, **kwargs)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/runtime/context.py", line 60, in allocate
    return self.allocate_unchecked(builder, size)
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/runtime/context.py", line 67, in allocate_unchecked
    self._require_nrt()
  File "/home/fabian/.virtualenvs/ddsp_pytorch/lib/python3.10/site-packages/numba/core/runtime/context.py", line 42, in _require_nrt
    raise errors.NumbaRuntimeError("NRT required but not enabled")
numba.core.errors.NumbaRuntimeError: Failed in cuda mode pipeline (step: native lowering)
NRT required but not enabled
During: lowering "array[(slice(None, None, None), 1)] = $30binary_subscr.14" at /home/fabian/git/_ext/ddsp_pytorch/ddsp/experiments/debug/debug_numba_gpu_operations_minimal.py (14)
```

</details>

Is this expected behavior or a bug?

**Comment by gmarkall** [comment]
The error messages are not very good, but operations on arrays and slices don't generally work on CUDA. There's a few observations that can be considered separately here:

## The documentation

> indexing and slicing works.

That is technically true, indexing and slicing does work, but you're limited in what you can do with a slice. It should probably clarify the limitations of what you can do with a slice.

## Inplace operations

```python
array[:, 1] += 1.0
```

I think this inplace operation could theoretically be made to work on CUDA today, it just happens not to have its implementation registered with the CUDA target. However, writing an expression that operates on a slice is usually not going to be the right thing to do from a performance perspective, because the operations on the slice will be carried out sequentially by a single thread.

Usually it would make better use of resources to manage the operation such that individual threads cooperate to compute the operation on the slice in parallel, e.g.:

```python
i = cuda.grid(1)
if i < array.shape[0]:
    array[i, 1] += 1.0
```

## Array expressions

```python
array[:, 1] = array[:, 0]
```

Although this particular assignment could be handled without any memory allocation, in general array expressions require the allocation of temporaries, so array expressions are not generally possible yet - this is why the message "NRT required but not enabled" is produced, the Numba Runtime (NRT) handles lifetime management for objects.

There is work underway to enable the NRT for CUDA, which would allow these sorts of expressions to start to be supported, but it's not going to be completed before the end of this year.

Even if it were complete, a manual allocation of work items to threads is generally going to be the most performant way to implement the above operation, like:

```python
i = cuda.grid(1)
if i < array.shape[0]:
    array[i, 1] = array[i, 0]
```

## Modified example

A complete runnable example showing how the above can be used to compute on slices in parallel follows:

```python
from numba import cuda
import numpy as np

@cuda.jit
def f_gpu(array):
    i = cuda.grid(1)

    # Slice the array
    array1 = array[:, 1]
    array0 = array[:, 0]

    if i < array.shape[0]:
        # Computations from "But these don't work" in the original reproducer
        array1[i] += 1.0
        array1[i] = array0[i]

array_cpu = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float32)
array_gpu = cuda.to_device(array_cpu)

f_gpu.forall(array_gpu.shape[0])(array_gpu)
print(array_gpu.copy_to_host())
```

Giving:

```
[[1. 1. 3.]
 [4. 4. 6.]]
```

(The code doesn't really do something entirely sensible given that it immediately overwrites the result of its first computation, but it does the same thing as in the reproducer from the issue description)

Note that I used [forall()](https://numba.readthedocs.io/en/stable/cuda-reference/kernel.html#numba.cuda.dispatcher.CUDADispatcher.forall) as a quick shorthand to launch the right number of threads for the grid to entirely cover the array - a normal launch syntax could also have been used, but would have needed manual computation of the grid and block dimensions.
