### ISSUE TITLE
bug of CUDA Simulator:  Calling another kernel function in a kernel function is not supported

### ISSUE THREAD

**Issue by dignfei** [numba/numba#9329]
- [ √] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [ √] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```Python
import os
os.environ["NUMBA_ENABLE_CUDASIM"]="1"
import numpy as np
from numba import cuda

size = 10
a = np.random.rand(size)
b = np.random.rand(size)
result = np.zeros_like(a)

@cuda.jit
def add(a, b, result,idx):
        result[idx] = a[idx] + b[idx]

@cuda.jit
def add_vectors_gpu(a, b, result):
    idx = cuda.grid(1)
    if idx < a.shape[0]:
        add(a, b, result, idx)
        #result[idx] = a[idx] + b[idx]

add_vectors_gpu[1, 128](a, b, result)
print("success!")
```

> #when “os.environ['NUMBA_ENABLE_CUDASIM']='0'” , It can run success.

> but when “os.environ['NUMBA_ENABLE_CUDASIM']='1'” , error：
```Python
Traceback (most recent call last):
  File "/numbatest1.py", line 26, in <module>
    add_vectors_gpu[1, 128](a, b, result)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 123, in __call__
    bm.run(grid_point, *fake_args)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 297, in run
    raise t.exception[0].with_traceback(t.exception[1])
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 190, in run
    super(BlockThread, self).run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 275, in target
    self._f(*args)
  File "/shareVolume/down_public/cuda/nbtest1.py", line 23, in add_vectors_gpu
    add(a, b, result, idx)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 85, in __call__
    grid_dim, block_dim = normalize_kernel_dimensions(self.grid_dim,
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/errors.py", line 54, in normalize_kernel_dimensions
    raise ValueError(missing_launch_config_msg)
ValueError: tid=[2, 0, 0] ctaid=[0, 0, 0]: 
Kernel launch configuration was not specified. Use the syntax:

kernel_function[blockspergrid, threadsperblock](arg0, arg1, ..., argn)

See https://numba.readthedocs.io/en/stable/cuda/kernels.html#kernel-invocation for help.



```

**Comment by gmarkall** [comment]
If you change the decorator for the called function to `@cuda.jit(device=True)` does that work around the issue for you?

**Comment by dignfei** [comment]
> If you change the decorator for the called function to `@cuda.jit(device=True)` does that work around the issue for you?

Thank you, it can work normally,
 but this brings another issue：
```Python
import os
os.environ["NUMBA_ENABLE_CUDASIM"]="1"
import numpy as np
from numba import cuda

size = 10
a = np.random.rand(size)
b = np.random.rand(size)
result = np.zeros_like(a)

@cuda.jit(device=True) 
def add(a, b, result,idx):
        result[idx] = a[idx] + b[idx]

@cuda.jit(device=True)
def add_vectors_gpu(a, b, result):
    idx = cuda.grid(1)
    if idx < a.shape[0]:
        add(a, b, result, idx)
        #result[idx] = a[idx] + b[idx]

add_vectors_gpu[1, 128](a, b, result)
print("success!")
```
Error : 

```Python
Traceback (most recent call last):
  File "/numbatest1.py", line 23, in <module>
    add_vectors_gpu[1, 128](a, b, result)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 82, in __call__
    return self.fn(*args)
  File "/shareVolume/down_public/cuda/numbatest1.py", line 18, in add_vectors_gpu
    idx = cuda.grid(1)
AttributeError: 'NoneType' object has no attribute 'grid'
```

**Comment by gmarkall** [comment]
Sorry, I wasn't very clear in what I was suggesting - you should use `@cuda.jit` for functions that will be called with a kernel launches, and `@cuda.jit(device=True)` for functions that are called from another `@cuda.jit` function. like:

```python
import os
os.environ["NUMBA_ENABLE_CUDASIM"]="1"
import numpy as np
from numba import cuda

size = 10
a = np.random.rand(size)
b = np.random.rand(size)
result = np.zeros_like(a)

@cuda.jit(device=True) 
def add(a, b, result,idx):
        result[idx] = a[idx] + b[idx]

@cuda.jit
def add_vectors_gpu(a, b, result):
    idx = cuda.grid(1)
    if idx < a.shape[0]:
        add(a, b, result, idx)
        #result[idx] = a[idx] + b[idx]

add_vectors_gpu[1, 128](a, b, result)
print("success!")
```

It used to be that the `device=True` annotation was required when using CUDA hardware, but it is no longer needed - Numba works out from the calling context whether the function is a device function or not. However, it looks like the simulator still has this limitation where device functions must be explicitly annotated.

**Comment by dignfei** [comment]
I once understood your meaning.

but xometimes function A needs to call function add_vectors_gpu,  it will lead to eror：

···python
import os
os.environ["NUMBA_ENABLE_CUDASIM"]="1"
import numpy as np
from numba import cuda

size = 10
a = np.random.rand(size)
b = np.random.rand(size)
result = np.zeros_like(a)

@cuda.jit(device=True) 
def add(a, b, result,idx):
        result[idx] = a[idx] + b[idx]

@cuda.jit
def add_vectors_gpu(a, b, result):
    idx = cuda.grid(1)
    if idx < a.shape[0]:
        add(a, b, result, idx)
        #result[idx] = a[idx] + b[idx]

@cuda.jit
def A(a, b, result):
       # do somethings
       add_vectors_gpu(a, b, result)
add_vectors_gpu[1, 128](a, b, result)
print("success!")
```

**Comment by dignfei** [comment]
I once understood your meaning.

but xometimes function A needs to call function add_vectors_gpu, it will lead to eror：

```Python
import os
os.environ["NUMBA_ENABLE_CUDASIM"]="1"
import numpy as np
from numba import cuda

size = 10
a = np.random.rand(size)
b = np.random.rand(size)
result = np.zeros_like(a)

@cuda.jit(device=True)
def add(a, b, result,idx):
result[idx] = a[idx] + b[idx]

@cuda.jit
def add_vectors_gpu(a, b, result):
idx = cuda.grid(1)
if idx < a.shape[0]:
add(a, b, result, idx)
#result[idx] = a[idx] + b[idx]

@cuda.jit
def A(a, b, result):
# do somethings
add_vectors_gpu(a, b, result)
add_vectors_gpu[1, 128](a, b, result)
print("success!")
```

**Comment by dignfei** [comment]
> Sorry, I wasn't very clear in what I was suggesting - you should use `@cuda.jit` for functions that will be called with a kernel launches, and `@cuda.jit(device=True)` for functions that are called from another `@cuda.jit` function. like:
> 
> ```python
> import os
> os.environ["NUMBA_ENABLE_CUDASIM"]="1"
> import numpy as np
> from numba import cuda
> 
> size = 10
> a = np.random.rand(size)
> b = np.random.rand(size)
> result = np.zeros_like(a)
> 
> @cuda.jit(device=True) 
> def add(a, b, result,idx):
>         result[idx] = a[idx] + b[idx]
> 
> @cuda.jit
> def add_vectors_gpu(a, b, result):
>     idx = cuda.grid(1)
>     if idx < a.shape[0]:
>         add(a, b, result, idx)
>         #result[idx] = a[idx] + b[idx]
> 
> add_vectors_gpu[1, 128](a, b, result)
> print("success!")
> ```
> 
> It used to be that the `device=True` annotation was required when using CUDA hardware, but it is no longer needed - Numba works out from the calling context whether the function is a device function or not. However, it looks like the simulator still has this limitation where device functions must be explicitly annotated.

I once understood your meaning.

but sometimes function A needs to call function add_vectors_gpu, it will lead to eror：

```Python
import os
os.environ["NUMBA_ENABLE_CUDASIM"]="1"
import numpy as np
from numba import cuda

size = 10
a = np.random.rand(size)
b = np.random.rand(size)
result = np.zeros_like(a)

@cuda.jit(device=True) 
def add(a, b, result,idx):
        result[idx] = a[idx] + b[idx]

@cuda.jit
def add_vectors_gpu(a, b, result):
    idx = cuda.grid(1)
    if idx < a.shape[0]:
        add(a, b, result, idx)
        #result[idx] = a[idx] + b[idx]

@cuda.jit
def A(a, b, result):
    # do somethings
    add_vectors_gpu(a, b, result)

add_vectors_gpu[1, 128](a, b, result)
A[1, 128](a, b, result)
print("success!")
```
Error
```Python
Traceback (most recent call last):
  File "/numbatest1.py", line 28, in <module>
    A[1, 128](a, b, result)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 123, in __call__
    bm.run(grid_point, *fake_args)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 297, in run
    raise t.exception[0].with_traceback(t.exception[1])
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 190, in run
    super(BlockThread, self).run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 275, in target
    self._f(*args)
  File "/shareVolume/down_public/cuda/numbatest1.py", line 26, in A
    add_vectors_gpu(a, b, result)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 90, in __call__
    with _push_kernel_context(fake_cuda_module):
  File "/opt/conda/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/opt/conda/lib/python3.10/site-packages/numba/cuda/simulator/kernel.py", line 28, in _push_kernel_context
    assert _kernel_context is None, "concurrent simulated kernel not supported"
AssertionError: tid=[99, 0, 0] ctaid=[0, 0, 0]: concurrent simulated kernel not supported
```


:
