### ISSUE TITLE
Test failure on 32-bit Linux

### ISSUE THREAD

**Issue by pitrou** [numba/numba#934]
```
======================================================================
FAIL: test_prod_magnitude (__main__.TestArrayMethods)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/antoine/numba/numba/tests/support.py", line 140, in assertPreciseEqual
    self._assertPreciseEqual(first, second, prec, ulps, msg)
  File "/home/antoine/numba/numba/tests/support.py", line 228, in _assertPreciseEqual
    _assertNumberEqual(first, second, delta)
  File "/home/antoine/numba/numba/tests/support.py", line 158, in _assertNumberEqual
    self.assertEqual(first, second, msg=msg)
AssertionError: -1373712384 != -4696715432980197376

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/antoine/numba/numba/tests/test_array_methods.py", line 306, in test_prod_magnitude
    self.check_aggregation_magnitude(array_prod)
  File "/home/antoine/numba/numba/tests/test_array_methods.py", line 295, in check_aggregation_magnitude
    self.assertPreciseEqual(npr, nbr)
  File "/home/antoine/numba/numba/tests/support.py", line 145, in assertPreciseEqual
    self.fail("when comparing %s and %s: %s" % (first, second, failure_msg))
AssertionError: when comparing -1373712384 and -4696715432980197376: -1373712384 != -4696715432980197376
```

**Comment by pitrou** [comment]
Two things:
* Numpy's `array.prod` (and other aggregation functions) returns int32 on 32-bit machines, not int64
* LLVM may be generating wrong code here (16- to 64-bit sign extension followed by signed 64-bit multiplication)?

**Comment by pitrou** [comment]
Error also occurs on win-32 and win-64:
https://alpha.binstar.org/antoine/numba/builds/47/2
https://alpha.binstar.org/antoine/numba/builds/47/3
