### ISSUE TITLE
about the `shape` argument for `cuda.shared.array()` and literal types inside the definitin of a kernel

### ISSUE THREAD

**Issue by Whatever314** [numba/numba#9340]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
 visible in the change log (https://github.com/numba/numba/blob/main/CHANGE_LOG).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

i met a similar issue as [No implementation of CUDA shared.array error #8300](https://github.com/numba/numba/issues/8300)
here is the code:
``` python
import numba
from numba import cuda
# import numba.types as nb_types

@cuda.jit
def test_board():
    block_size = cuda.blockDim.x
    test = cuda.shared.array(shape=(block_size, block_size), dtype=numba.float32)
    return

if __name__ == "__main__":
    grid_shape = (2, 2)
    block_shape = (10, 10)
    test_board[grid_shape, block_shape]()
```

and the output:
``` bash
Traceback (most recent call last):
  File "/home/bot/potts/error.py", line 17, in <module>
    test_board[grid_shape, block_shape]()
  File "/home/bot/potts/lib/python3.11/site-packages/numba/cuda/dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/cuda/dispatcher.py", line 673, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/cuda/dispatcher.py", line 681, in _compile_for_args
    return self.compile(tuple(argtypes))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/cuda/dispatcher.py", line 924, in compile
    kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/cuda/dispatcher.py", line 83, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/cuda/compiler.py", line 194, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler.py", line 508, in _compile_core
    raise e
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
                                            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/typed_passes.py", line 91, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bot/potts/lib/python3.11/site-packages/numba/core/typeinfer.py", line 1086, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in cuda mode pipeline (step: nopython frontend)
No implementation of function Function(<function shared.array at 0x7f7822260400>) found for signature:
 
 >>> array(shape=UniTuple(int32 x 2), dtype=class(float32))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload of function 'array': File: numba/cuda/cudadecl.py: Line 26.
    With argument(s): '(shape=UniTuple(int32 x 2), dtype=class(float32))':
   No match.

During: resolving callee type: Function(<function shared.array at 0x7f7822260400>)
During: typing of call at /home/bot/potts/error.py (10)


File "error.py", line 10:
def test_board():
    <source elided>
    block_size = cuda.blockDim.x
    block_state = cuda.shared.array(shape=(block_size, block_size), dtype=numba.float32)
    ^
```

my question is: i want to realize the same feature as my original code i.e. create a shared array with the same shape as the block. and, i don't want to define a global variable and refer to it inside the function. how could i do this?

i have checked the [Notes on Literal Types](https://numba.pydata.org/numba-doc/dev/developer/literal.html?highlight=literal), but how could i somehow transfer a `numba.int32` type into a literal type?

**Comment by Whatever314** [comment]
by the way if you couldn't repeat my error, set the environment variable `NUMBA_CUDA_LOW_OCCUPANCY_WARNINGS` to 0:
``` bash
$ conda env config vars set NUMBA_CUDA_LOW_OCCUPANCY_WARNINGS=0
```

**Comment by Whatever314** [comment]
Alright. Thanks for your answer and your code
👍 , though i will still simply define macros and wait for any updates :)

**Comment by gmarkall** [comment]
I think I'm going to close this issue, as the underlying problem is #7528.
