### ISSUE TITLE
Support calling gufunc without output buffers 

### ISSUE THREAD

**Issue by guilhermeleobas** [numba/numba#9345]
gufuncs have a restriction where the pattern `out = gufunc(arg1, arg2, ..., argN)` is not supported:

```python
from numba import guvectorize
import numpy as np

@guvectorize('(n),(n) -> (n)')
def add(a, b, res):
    for i in range(a.shape[0]):
        res[i] = a[i] + b[i]

a = np.arange(5)
b = np.ones_like(5)
add(a, b)

# Traceback (most recent call last):
#   File "/Users/guilhermeleobas/git/numba/b.py", line 11, in <module>
#     add(a, b)
#   File "/Users/guilhermeleobas/git/numba/numba/np/ufunc/gufunc.py", line 186, in __call__
#     raise TypeError(msg)
# TypeError: Too few arguments for function 'add'. Note that the pattern `out = gufunc(Arg1, Arg2, ..., ArgN)` is not allowed. Use `gufunc(Arg1, Arg2, ..., ArgN, out) instead.
```

I do not know how hard this one is, as one needs to guess the dtype of `res` to compile the correct kernel.

**Comment by max-sixty** [comment]
FYI note this is only the case for dynamic gufuncs — with a signature no output is required:

```
@guvectorize([(numba.int64[:], numba.int64[:], numba.int64[:])],'(n),(n) -> (n)')
def add(a, b, res):
    for i in range(a.shape[0]):
        res[i] = a[i] + b[i]

a = np.arange(5)
b = np.ones_like(a)
add(a, b)
```
