### ISSUE TITLE
Elapsed running time of parallel jit for the logistic regression documentation example is dozens of seconds

### ISSUE THREAD

**Issue by matanster** [numba/numba#9395]
Using numba 0.58.1, python 3.10.13  [GCC 9.4.0] on linux, I am running the [following example code from the docs](https://numba.readthedocs.io/en/stable/user/parallel.html#examples) resulting in quite unexpected behavior:

```python
@numba.jit(nopython=True, parallel=True)
def logistic_regression(Y, X, w, iterations):
    for i in range(iterations):
        w -= np.dot(((1.0 / (1.0 + np.exp(-Y * np.dot(X, w))) - 1.0) * Y), X)
    return w
```

― feeding in the following input arguments:

```python
    N = 100
    D = 100

    Y = np.random.rand(N)
    X = np.random.rand(N, D)
    w = np.random.rand(D)
    iterations = 1000

    print(numba_logistic_regression(Y, X, w, iterations))
```

As opposed to decorating the function with `@njit(parallel=False)`, setting the decorator with `parallel=True` makes the function run for dozens of seconds utilizing 12 logical cores on an i7-8700. Whereas when parallel is set to `False`, or when @jit is not used at all, the function returns quite promptly.

For doubt avoidance, this is the same when using `cache=True` twice, and I doubt that the compilation would use all those cores anyway. 

While I've used numba before, in humble capacities but for a long duration, without parallel=True, it might be worth noting that running the additional method from that same documentation page, `parallel_diagnostics(level=4)`, fails in my case with:

```
Traceback (most recent call last):
  File "example.py", line 34, in <module>
    numba_logistic_regression.parallel_diagnostics(level=4)
  File ".venv3.10/lib/python3.10/site-packages/numba/core/dispatcher.py", line 1035, in parallel_diagnostics
    [dump(sig) for sig in self.signatures]
  File ".venv3.10/lib/python3.10/site-packages/numba/core/dispatcher.py", line 1035, in <listcomp>
    [dump(sig) for sig in self.signatures]
  File ".venv3.10/lib/python3.10/site-packages/numba/core/dispatcher.py", line 1027, in dump
    pfdiag = ol.metadata.get('parfor_diagnostics', None)
AttributeError: 'NoneType' object has no attribute 'get'
```

Since code formatting is much more enabling here, I went ahead posting this here even though my understanding of the parallel options are at this stage not even cursory.

**Comment by matanster** [comment]
P.S. when not using parallel=True, the speedup is approaching x4 that of pure python under a proper benchmark on my mentioned chipset.

**Comment by matanster** [comment]
Explicitly wiring in numba's `prange` in the function while keeping the `@njit(parallel=True), it simply degresses to no speed up at all v.s. regular python. 

This is with numpy version 1.24.4, and also confirmed with numpy 1.25.0 and 1.26.2 alike on my machine. All of these numpy versions, when used without decorating the function with numba, use all cores when running the same function from the example, implying some form of parallelization by numpy for that code.

**Comment by sklam** [comment]
Could this be the overhead cost for parfor region? 

I'm seeing the speed difference just by using the numpy-parfor-pass 

e.g.
```python
parallel = dict(
    comprehension = False,
    reduction = False,
    inplace_binop = False,
    setitem = False,
    numpy = True,
    stencil = False,
    fusion = False,
    prange = False,
)

@numba.jit(nopython=True, parallel=parallel)
```

Will have to inspect the LLVM and assembly to understand more.

**Comment by marioroy** [comment]
The example is failing for me. I am running Numba 0.59, llvmlite 0.42.0 from Conda. Python and NumPy are 3.12.1 and 1.26.3, respectively.

```text
Traceback (most recent call last):
  File "/tmp/a/test.py", line 30, in <module>
    print(logistic_regression(Y, X, w, iterations))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mario/miniconda3/envs/mandel/lib/python3.12/site-packages/numba/core/dispatcher.py", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/mario/miniconda3/envs/mandel/lib/python3.12/site-packages/numba/core/dispatcher.py", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function dot>) found for signature:
 
 >>> dot(array(float64, 2d, C), array(float64, 1d, C))
 
There are 4 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'dot_2': File: numba/np/linalg.py: Line 525.
    With argument(s): '(array(float64, 2d, C), array(float64, 1d, C))':
   Rejected as the implementation raised a specific error:
     LoweringError: Failed in nopython mode pipeline (step: native lowering)
   scipy 0.16+ is required for linear algebra
   
   File "../../home/mario/miniconda3/envs/mandel/lib/python3.12/site-packages/numba/np/linalg.py", line 582:
               def _dot2_codegen(context, builder, sig, args):
                   <source elided>
   
           return lambda left, right: _impl(left, right)
           ^
   
   During: lowering "$14call.4 = call $8load_deref.1(left, right, func=$8load_deref.1, args=[Var(left, linalg.py:582), Var(right, linalg.py:582)], kws=(), vararg=None, varkwarg=None, target=None)" at /home/mario/miniconda3/envs/mandel/lib/python3.12/site-packages/numba/np/linalg.py (582)
  raised from /home/mario/miniconda3/envs/mandel/lib/python3.12/site-packages/numba/core/errors.py:874
  - Of which 2 did not match due to:
  Overload in function 'dot_3': File: numba/np/linalg.py: Line 784.
    With argument(s): '(array(float64, 2d, C), array(float64, 1d, C))':
   Rejected as the implementation raised a specific error:
     TypingError: missing a required argument: 'out'
  raised from /home/mario/miniconda3/envs/mandel/lib/python3.12/site-packages/numba/core/typing/templates.py:784

During: resolving callee type: Function(<built-in function dot>)
During: typing of call at /tmp/a/test.py (19)

File "test.py", line 19:
def logistic_regression(Y, X, w, iterations):
    <source elided>
    for i in range(iterations):
        w -= np.dot(((1.0 / (1.0 + np.exp(-Y * np.dot(X, w))) - 1.0) * Y), X)
        ^
```

**Comment by marioroy** [comment]
The example works otherwise, using the system Python 3.12.1 and Numba installation via pip (installed 0.59.0). I have set `cache=True` and run once. Below are the times comparing tbb, omp, and number of threads on a many-core box. Increasing the number of threads slows down the application using tbb.

```bash
$ time NUMBA_NUM_THREADS=4 NUMBA_THREADING_LAYER=tbb python test.py
0.461s
$ time NUMBA_NUM_THREADS=4 NUMBA_THREADING_LAYER=omp python test.py
0.399s
$ time NUMBA_NUM_THREADS=8 NUMBA_THREADING_LAYER=tbb python test.py
0.758s
$ time NUMBA_NUM_THREADS=8 NUMBA_THREADING_LAYER=omp python test.py
0.402s
$ time NUMBA_NUM_THREADS=16 NUMBA_THREADING_LAYER=tbb python test.py
0.961s
$ time NUMBA_NUM_THREADS=16 NUMBA_THREADING_LAYER=omp python test.py
0.397s
$ time NUMBA_NUM_THREADS=32 NUMBA_THREADING_LAYER=tbb python test.py
1.397s
$ time NUMBA_NUM_THREADS=32 NUMBA_THREADING_LAYER=omp python test.py
0.411s
```

It is surprising the demonstration falters using Python/NumPy/Numba from MiniConda, but not the system's Python (also 3.12.1) and Numba installation via pip.

**Comment by marioroy** [comment]
Results using @sklam's parallel parameters. The tbb times are faster than before for higher thread count.
```text
parallel = dict(
    comprehension = False, reduction = False, inplace_binop = False, setitem = False,
    numpy = True, stencil = False, fusion = False, prange = False,
)
@numba.jit(nopython=True, parallel=parallel, cache=True)
```
```bash
$ time NUMBA_NUM_THREADS=4 NUMBA_THREADING_LAYER=tbb python test.py
0.460s
$ time NUMBA_NUM_THREADS=4 NUMBA_THREADING_LAYER=omp python test.py
0.405s
$ time NUMBA_NUM_THREADS=8 NUMBA_THREADING_LAYER=tbb python test.py
0.478s
$ time NUMBA_NUM_THREADS=8 NUMBA_THREADING_LAYER=omp python test.py
0.409s
$ time NUMBA_NUM_THREADS=16 NUMBA_THREADING_LAYER=tbb python test.py
0.546s
$ time NUMBA_NUM_THREADS=16 NUMBA_THREADING_LAYER=omp python test.py
0.414s
$ time NUMBA_NUM_THREADS=32 NUMBA_THREADING_LAYER=tbb python test.py
0.646s
$ time NUMBA_NUM_THREADS=32 NUMBA_THREADING_LAYER=omp python test.py
0.416s
```
