### ISSUE TITLE
how to accelerate a for loop which consists by vector computation

### ISSUE THREAD

**Issue by leslielee619** [numba/numba#9406]
## error
```
XXXX\Scripts\python.exe XXXXXXXX.py 
Traceback (most recent call last):
  File "XXXXXXXX.py", line 37, in <module>
    func_acc[grid_dim, block_dim](X, Y, A, B, res, 10)
  File "XXXX\lib\site-packages\numba\cuda\dispatcher.py", line 539, in __call__
    return self.dispatcher.call(args, self.griddim, self.blockdim,
  File "XXXX\lib\site-packages\numba\cuda\dispatcher.py", line 673, in call
    kernel = _dispatcher.Dispatcher._cuda_call(self, *args)
  File "XXXX\lib\site-packages\numba\cuda\dispatcher.py", line 681, in _compile_for_args
    return self.compile(tuple(argtypes))
  File "XXXX\lib\site-packages\numba\cuda\dispatcher.py", line 924, in compile
    kernel = _Kernel(self.py_func, argtypes, **self.targetoptions)
  File "XXXX\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "XXXX\lib\site-packages\numba\cuda\dispatcher.py", line 83, in __init__
    cres = compile_cuda(self.py_func, types.void, self.argtypes,
  File "XXXX\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "XXXX\lib\site-packages\numba\cuda\compiler.py", line 194, in compile_cuda
    cres = compiler.compile_extra(typingctx=typingctx,
  File "XXXX\lib\site-packages\numba\core\compiler.py", line 770, in compile_extra
    return pipeline.compile_extra(func)
  File "XXXX\lib\site-packages\numba\core\compiler.py", line 461, in compile_extra
    return self._compile_bytecode()
  File "XXXX\lib\site-packages\numba\core\compiler.py", line 529, in _compile_bytecode
    return self._compile_core()
  File "XXXX\lib\site-packages\numba\core\compiler.py", line 508, in _compile_core
    raise e
  File "XXXX\lib\site-packages\numba\core\compiler.py", line 495, in _compile_core
    pm.run(self.state)
  File "XXXX\lib\site-packages\numba\core\compiler_machinery.py", line 368, in run
    raise patched_exception
  File "XXXX\lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "XXXX\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "XXXX\lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "XXXX\lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "XXXX\lib\site-packages\numba\core\typed_passes.py", line 110, in run_pass
    typemap, return_type, calltypes, errs = type_inference_stage(
  File "XXXX\lib\site-packages\numba\core\typed_passes.py", line 91, in type_inference_stage
    errs = infer.propagate(raise_errors=raise_errors)
  File "XXXX\lib\site-packages\numba\core\typeinfer.py", line 1086, in propagate
    raise errors[0]
numba.core.errors.TypingError: Failed in cuda mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function sub>) found for signature:
 
 >>> sub(array(float64, 1d, C), float64)
 
There are 12 candidate implementations:
   - Of which 10 did not match due to:
   Overload of function 'sub': File: <numerous>: Line N/A.
     With argument(s): '(array(float64, 1d, C), float64)':
    No match.
   - Of which 2 did not match due to:
   Operator Overload in function 'sub': File: unknown: Line unknown.
     With argument(s): '(array(float64, 1d, C), float64)':
    No match for registered cases:
     * (int64, int64) -> int64
     * (int64, uint64) -> int64
     * (uint64, int64) -> int64
     * (uint64, uint64) -> uint64
     * (float32, float32) -> float32
     * (float64, float64) -> float64
     * (complex64, complex64) -> complex64
     * (complex128, complex128) -> complex128

During: typing of intrinsic-call at XXXXXXXX.py (19)

File "XXXX.py", line 19:
def func_acc(X, Y, A, B, res, threshold):
    <source elided>
        x, y = X[col], Y[row]
        dist = ((A - x) ** 2 + (B - y) ** 2) ** 0.5
        ^


Process finished with exit code 1
```

## code
```python
from numba import cuda
import cupy as cp
import numpy as np
import math


@cuda.jit
def func_acc(X, Y, A, B, res, threshold):
    idx = cuda.threadIdx.x + cuda.blockIdx.x * cuda.blockDim.x
    if idx < res.size:
        row = int(math.ceil((idx+1)/res.shape[1]) - 1)
        col = int(idx - res.shape[1]*(row-1))
        x, y = X[col], Y[row]
        dist = ((A - x) ** 2 + (B - y) ** 2) ** 0.5
        res = cp.sum(dist[dist<threshold])

def func(X, Y, A, B, res, threshold):
    for x in X:
        for y in Y:
            dist = ((A - x) ** 2 + (B - y) ** 2) ** 0.5
            res = cp.sum(dist[dist < threshold])


if __name__ == '__main__':
    X = cp.arange(1, 1000, 1).astype('float64')
    Y = X.copy()
    A = cp.arange(1, 1000, 1).astype('float64')
    B = A*2
    res = cp.zeros([2000, 2000])
    block_dim = 32 * 32  # 4090 card的CUDA核心数为128*128; block_dim也称block_num
    grid_dim = math.ceil(X.size * Y.size / block_dim)  # 也称block_num
    func_acc[grid_dim, block_dim](X, Y, A, B, res, 10)
    cuda.synchronize()
    func(X, Y, A, B, res, 10)
    print(res)
```

## my question
Whether numba can accelerate a for loop only if it consists by scalar computation, such as 2D convovle.
Now error apper when i accelerate a for loop which consists by vector computation.
How to fix it? its my first time to use GPU computing，so im very confused.

**Comment by leslielee619** [comment]
i use numpy, njit(parallel=True), and prange, then it works, faster than only use cupy.

**Comment by stuartarchibald** [comment]
Thanks for the report. The issue you are seeing is down to the CUDA target not supporting all of NumPy's behaviours, in part because they don't map directly to the CUDA programming model. The specific error message about `sub(array(float64, 1d, C), float64)` is saying that there's no supported implementation of the subtraction operation for a 1d array and a float, i.e. `array_instance - float_value` for the CUDA target. The reason this works on the CPU is because there's much more general NumPy support available for this target. To make something like this work on CUDA, one common way to achieve this is to either write a loop over the operation so that it runs element at a time, or use the CUDA programming model's thread based indexing to help achieve the same. Hope this helps.
