### ISSUE TITLE
Python 3.13

### ISSUE THREAD

**Issue by sklam** [numba/numba#9413]
This issue is to track tasks and issues with Python 3.13.

Numba support status:

- Started early work on Python3.13.0a3. So far, there is minimal bytecode changes (WIP branch: https://github.com/numba/numba/compare/main...sklam:numba:wip/py3.13). ~We got `numba/tests/test_usecases.py` to pass. However, more involved tests are blocked by an issue with metaclass (https://github.com/python/cpython/issues/114806). As a result, `Type._code` is not set properly.  (temporary debug commit related to the issue: https://github.com/numba/numba/commit/4b6cc78a79530e41e414326fbb7f255d05ee5506)~
- Added development setup using hatchery: https://github.com/numba/numba-hatchery/pull/8
- Work is halted until 3.13.0a4 is available. Expected on Feb 13 2024.
- Work resumes using 3.13.0a6 as https://github.com/python/cpython/issues/114806 is resolved. Continues to look into try-except changes 7/33 failures in `test_try_except.py`

**Comment by aaronzo** [comment]
Great to see some steps towards 3.13 taking place - will numba publish [PEP 703](https://peps.python.org/pep-0703/) free threading wheels (`-cp313t`)?

**Comment by sklam** [comment]
RE: https://github.com/numba/numba/issues/9413#issuecomment-2197205944



> will numba publish [PEP 703](https://peps.python.org/pep-0703/) free threading wheels (`-cp313t`)?

We are talking about providing freethreading packages but the current priority is just to get through all the issues with bytecode changes. 

As of https://github.com/numba/numba/commit/a8ad12aee51f547c01f4844dd85ce2eff4de3d8c, the testsuite is at 493 failures out of 10385.

**Comment by sklam** [comment]
As of 6cafffe62, everything is working on py3.13 except for 3 failures that are unrelated to py3.13:
- `numba.tests.test_lists.TestLists.test_mul_error`
  - Python3.13 is not raising MemoryError in the hatchery docker.
  - `rosetta error: could not find free space for allocation size 1000000000001000`
- `numba.tests.test_nrt.TestNrtMemInfo.test_allocate_invalid_size`
  - `rosetta error: could not find free space for allocation size 2000000000001000`
- `numba.tests.test_function_type.TestFunctionTypeExtensions.test_wrapper_address_protocol_libm`
  - Fail when running alone. Works when with other tests. Probably due to
    initialization problem.

**Comment by jmerkel11** [comment]
Basically the same as aaronzo said, but for [PEP 738](https://peps.python.org/pep-0738/).
At first thanks for your awesome work, then the question: Will you support numba on Android starting with Python 3.13?
Otherwise, current Android support will likely die ( https://github.com/chaquo/chaquopy/issues/834 ).

**Comment by mhsmith** [comment]
Hi, I'm the maintainer of Chaquopy. Both myself and the Numba maintainers now work for Anaconda, so we'll hopefully be able to produce Numba builds for Python 3.13 on Android later in the year. But first we'll need to deal with more fundamental packages like NumPy.

**Comment by jakirkham** [comment]
Think we need `llvmlite` supported on Python 3.13. Is that being tracked in an issue somewhere as well?

**Comment by stuartarchibald** [comment]
@jakirkham thanks for the reminder, there is now https://github.com/numba/llvmlite/issues/1084

**Comment by slayoo** [comment]
For the record, since last week's update, the `macos-14-arm64` image on GitHub Actions ships with system Python 3.13, which makes Numba uninstallable there as of now
 
https://newreleases.io/project/github/actions/runner-images/release/macos-14-arm64%2F20241014.301

**Comment by omegadev21** [comment]
can you give an estimation on when Numba will be ready for python 3.13.0

**Comment by jensdebruijn** [comment]
You can install the release candidate right now

**Comment by slayoo** [comment]
Trying out `numba-0.61.0rc1` (and `llvmlite-0.44.0rc1`) on GitHub Actions macOS runners, it works well on Intel macos-13 image, but fails on Apple-silicon (ARM) macos-14 runner with (https://github.com/open-atmos/PyPartMC/actions/runs/12207324656/job/34058852918):
```
...
 File /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/llvmlite/binding/ffi.py:136, in _lib_wrapper._lib(self)
    132 @property
    133 def _lib(self):
    134     # Not threadsafe.
    135     if not self._lib_handle:
--> 136         self._load_lib()
    137     return self._lib_handle
File /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/llvmlite/binding/ffi.py:130, in _lib_wrapper._load_lib(self)
    124         _ = self._lib_handle.LLVMPY_GetVersionInfo()
    125 except (OSError, AttributeError) as e:
    126     # OSError may be raised if the file cannot be opened, or is not
    127     # a shared library.
    128     # AttributeError is raised if LLVMPY_GetVersionInfo does not
    129     # exist.
--> 130     raise OSError("Could not find/load shared object file") from e
OSError: Could not find/load shared object file
```
Any hints?
Thanks

**Comment by liudonghua123** [comment]
I have the similar problems when install some other package which depend on numba.

```
Liu.D.H  ~   0ms  11:28 > pip install nexaai --prefer-binary --index-url https://nexaai.github.io/nexa-sdk/whl/cpu --extra-index-url https://pypi.org/simple --no-cache-dir
Looking in indexes: https://nexaai.github.io/nexa-sdk/whl/cpu, https://pypi.org/simple
Collecting nexaai
  Downloading https://github.com/NexaAI/nexa-sdk/releases/download/v0.0.9.7/nexaai-0.0.9.7-cp313-cp313-win_amd64.whl (4.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.4/4.4 MB 5.1 MB/s eta 0:00:00
Collecting cmake (from nexaai)
  Downloading cmake-3.31.2-py3-none-win_amd64.whl.metadata (6.5 kB)
Collecting faster_whisper (from nexaai)
  Downloading faster_whisper-1.1.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: typing-extensions>=4.5.0 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (4.12.2)
Requirement already satisfied: numpy>=1.20.0 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (2.1.2)
Collecting diskcache>=5.6.1 (from nexaai)
  Downloading diskcache-5.6.3-py3-none-any.whl.metadata (20 kB)
Requirement already satisfied: jinja2>=2.11.3 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (3.1.4)
Collecting librosa>=0.8.0 (from nexaai)
  Downloading librosa-0.10.2.post1-py3-none-any.whl.metadata (8.6 kB)
Collecting fastapi (from nexaai)
  Downloading fastapi-0.115.6-py3-none-any.whl.metadata (27 kB)
Collecting uvicorn (from nexaai)
  Downloading uvicorn-0.34.0-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: pydantic in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (2.9.2)
Requirement already satisfied: pillow in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (11.0.0)
Requirement already satisfied: huggingface_hub in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (0.26.0)
Collecting modelscope (from nexaai)
  Downloading modelscope-1.21.0-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: prompt_toolkit in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (3.0.48)
Requirement already satisfied: tqdm in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from nexaai) (4.66.5)
Collecting tabulate (from nexaai)
  Downloading tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting streamlit>=1.37.1 (from nexaai)
  Downloading streamlit-1.41.1-py2.py3-none-any.whl.metadata (8.5 kB)
Collecting streamlit-audiorec (from nexaai)
  Downloading streamlit_audiorec-0.1.3-py3-none-any.whl.metadata (2.4 kB)
Collecting python-multipart (from nexaai)
  Downloading python_multipart-0.0.19-py3-none-any.whl.metadata (1.8 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from jinja2>=2.11.3->nexaai) (3.0.2)
Collecting audioread>=2.1.9 (from librosa>=0.8.0->nexaai)
  Downloading audioread-3.0.1-py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: scipy>=1.2.0 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from librosa>=0.8.0->nexaai) (1.14.1)
Requirement already satisfied: scikit-learn>=0.20.0 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from librosa>=0.8.0->nexaai) (1.5.2)
Requirement already satisfied: joblib>=0.14 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from librosa>=0.8.0->nexaai) (1.4.2)
Requirement already satisfied: decorator>=4.3.0 in c:\users\liu.d.h\appdata\local\programs\python\python313\lib\site-packages (from librosa>=0.8.0->nexaai) (5.1.1)
Collecting numba>=0.51.0 (from librosa>=0.8.0->nexaai)
  Downloading numba-0.60.0.tar.gz (2.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 3.7 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Liu.D.H\AppData\Local\Programs\Python\Python313\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-s38twml2\overlay\Lib\site-packages\setuptools\build_meta.py", line 334, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-s38twml2\overlay\Lib\site-packages\setuptools\build_meta.py", line 304, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-s38twml2\overlay\Lib\site-packages\setuptools\build_meta.py", line 522, in run_setup
          super().run_setup(setup_script=setup_script)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Liu.D.H\AppData\Local\Temp\pip-build-env-s38twml2\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 51, in <module>
        File "<string>", line 48, in _guard_py_ver
      RuntimeError: Cannot install on Python version 3.13.0; only versions >=3.9,<3.13 are supported.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Liu.D.H  ~   1m 2.814s  08:52 >
```

**Comment by mathomp4** [comment]
> not sure why this is closed when there was not yet an official release supporting all supported platforms?

Indeed, from what I see, there is no Python 3.13 numba 0.61.0 on conda-forge:

https://anaconda.org/conda-forge/numba/files?version=0.61.0

but it looks like there might be soon:

https://github.com/conda-forge/numba-feedstock/pull/152
