### ISSUE TITLE
np.median raises AssertionError for empty arrays while numpy returns nan

### ISSUE THREAD

**Issue by leoschwarz** [numba/numba#9433]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

This is a very similar issue to #8451 but here it affects `numpy.median` and setting the error_model does not change the outcome.

```python
import unittest
import numpy as np
from numba import njit

def median_numpy(arr):
    return np.median(arr)

@njit
def median_numba(arr):
    return np.median(arr)

class TestCase(unittest.TestCase):
    def test_median_numpy(self):
        self.assertTrue(np.isnan(median_numpy(np.array([], dtype=float))))
        self.assertTrue(np.isnan(median_numpy(np.array([]))))

    def test_median_numba(self):
        self.assertTrue(np.isnan(median_numba(np.array([], dtype=float))))
        self.assertTrue(np.isnan(median_numba(np.array([]))))

if __name__ == "__main__":
    unittest.main()
```

While numpy returns `nan`, numba raises an AssertionError:

```
Failure
Traceback (most recent call last):
  File "/Users/leo/code/msi/code/tests/unit/misc/test_numpy_util.py", line 88, in test_median_numba
    self.assertTrue(np.isnan(NumpyUtil.median_numba(np.array([], dtype=float))))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/leo/.miniconda3/envs/exp-2023-10/lib/python3.11/site-packages/numba/np/arraymath.py", line 1556, in _select_two
    assert high > low  # by construction
AssertionError
```

**Comment by kc611** [comment]
Thanks for reporting this. I can reproduce this locally.

The error is possibly due to lack of a guards around the internal implementation for `np.median` within Numba. 

It originates from the following line:

https://github.com/numba/numba/blob/3edb458c69daeaaffbfc938145c367eda1cf043f/numba/np/arraymath.py#L1582

Where `n = shape of the flattened array = 0` which makes the logic think that variable `low` equals `0` and variable `high` equals `-1`.

A possible fix is to simply check for this edge case and return `nan` if no elements exist within the array. Marking this as a good first issue.

**Comment by tanishac25** [comment]
can i take up this issue?

**Comment by kc611** [comment]
@tanishac25 Sure. The linked PR seems to be abandoned so I don't see a problem.

**Comment by xBloodLotusx** [comment]
Is this still unresolved? If so, can I attempt to tackle it?

**Comment by leoschwarz** [comment]
Hi @xBloodLotusx the test case I posted earlier still fails with numba 0.61.2, I haven't checked `main` branch.

For earlier work, @tanishac25 worked on this in PR #9805 which is still open. Not sure why it wasn't merged.

**Comment by xBloodLotusx** [comment]
> Hi [@xBloodLotusx](https://github.com/xBloodLotusx) the test case I posted earlier still fails with numba 0.61.2, I haven't checked `main` branch.
> 
> For earlier work, [@tanishac25](https://github.com/tanishac25) worked on this in PR [#9805](https://github.com/numba/numba/pull/9805) which is still open. Not sure why it wasn't merged.

I'll check it out! Thanks
