### ISSUE TITLE
test_sum1d_pyobj crashes on aarch64-linux on 0.59.0

### ISSUE THREAD

**Issue by mweinelt** [numba/numba#9442]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

## Report

After updating numba from 0.58.1 to 0.59.0 in nixpkgs we are seeing Python crash during `test_sum1d_pyobj`.

This is with llvmlite 0.42.0 and numpy 1.26.4 on Python 3.11.7 and 3.12.1.

```
FAIL: test_sum1d_pyobj (numba.tests.test_usecases.TestUsecases.test_sum1d_pyobj)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/tests/support.py", line 608, in inner
    self.subprocess_test_runner(test_module=self.__module__,
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/tests/support.py", line 590, in subprocess_test_runner
    self.assertEqual(status.returncode, 0, streams)
AssertionError: -11 != 0 : 
captured stdout: 
captured stderr: Fatal Python error: Segmentation fault

Current thread 0x0000fffff7ff5e20 (most recent call first):
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/tests/test_usecases.py", line 47 in test_sum1d_pyobj
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/tests/support.py", line 616 in inner
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/case.py", line 579 in _callTestMethod
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/case.py", line 623 in run
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/case.py", line 678 in __call__
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/suite.py", line 122 in run
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/suite.py", line 84 in __call__
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/runner.py", line 217 in run
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/testing/main.py", line 169 in run
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/main.py", line 274 in runTests
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/testing/main.py", line 362 in run_tests_real
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/testing/main.py", line 377 in runTests
  File "/nix/store/xg7f3xg4l3w4apmialnid8lm61jdrf57-python3-3.11.7/lib/python3.11/unittest/main.py", line 102 in __init__
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/testing/main.py", line 204 in __init__
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/testing/__init__.py", line 54 in run_tests
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/testing/_runtests.py", line 25 in _main
  File "/nix/store/84iw7rf5k9afw25m3qmwqpfk005imv9d-python3.11-numba-0.59.0/lib/python3.11/site-packages/numba/runtests.py", line 9 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, numba.core.typeconv._typeconv, numba._helperlib, numba._dynfunc, numba._dispatcher, numba.core.runtime._nrt_python, numba.np.ufunc._internal, numba.experimental.jitclass._box, numba.mviewbuf, numba.types.itertools (total: 22)
```

Bisected to

```
fbfb62657af41b9f4acdba8a4a25a80e31ec79f1 is the first bad commit
commit fbfb62657af41b9f4acdba8a4a25a80e31ec79f1
Author: Stuart Archibald <stuartarchibald@users.noreply.github.com>
Date:   Fri Apr 21 13:18:29 2023 +0100

    Remove `compile_isolated` from numba/tests/test_usecases.py
    
    As title.

 numba/tests/test_usecases.py | 101 +++++++++++++++----------------------------
 1 file changed, 34 insertions(+), 67 deletions(-)
```

**Comment by gmarkall** [comment]
@mweinelt Many thanks for the report - I'm not that familiar with nix, and I am not sure if any other Numba user is - is there a quick way to replicate building this package in order to reproduce the error locally?

**Comment by gmarkall** [comment]
@mweinelt I had a thought - does your LLVM 14 build include a backport of this fix: https://github.com/llvm/llvm-project/commit/2e1b838a889f9793d4bcd5dbfe10db9796b77143 ? If not, it's quite possible to commit you bisected to would trigger the underlying issue that that patch fixes.

**Comment by mweinelt** [comment]
> I can try to apply this one, but I will not get to that before Thursday.

Ah well, this was easy enough. And the tests do indeed work with that patch applied. Cheers!

**Comment by gmarkall** [comment]
> Ah well, this was easy enough. And the tests do indeed work with that patch applied. Cheers!

No problem - that should also help out with any other tools / compilers that use RuntimeDyld avoid a segfault on your platform too :-)
