### ISSUE TITLE
Using shared memory in more than one function (global or device) doesn't work

### ISSUE THREAD

**Issue by gmarkall** [numba/numba#953]
The following code:

```python
from numba import cuda, int32

@cuda.jit(device=True)
def inner():
    inner_arr = cuda.shared.array(1, dtype=int32)

@cuda.jit
def outer():
    outer_arr = cuda.shared.array(1, dtype=int32)
    inner()

outer()
```

due to the use of a shared array in the caller and the callee, produces:

```
$ python main.py 
Traceback (most recent call last):
  File "main.py", line 12, in <module>
    outer()
  File "/home/gmarkall/work/numba/numba/cuda/compiler.py", line 455, in __call__
    kernel = self.specialize(*args)
  File "/home/gmarkall/work/numba/numba/cuda/compiler.py", line 467, in specialize
    **self.targetoptions)
  File "/home/gmarkall/work/numba/numba/cuda/compiler.py", line 49, in compile_kernel
    cres = compile_cuda(pyfunc, types.void, args, debug=debug, inline=inline)
  File "/home/gmarkall/work/numba/numba/cuda/compiler.py", line 42, in compile_cuda
    library.finalize()
  File "/home/gmarkall/work/numba/numba/targets/codegen.py", line 145, in finalize
    library._get_module_for_linking(), preserve=True)
  File "/home/gmarkall/.conda/envs/mrrc/lib/python3.4/site-packages/llvmlite/binding/module.py", line 130, in link_in
    link_modules(self, other, preserve)
  File "/home/gmarkall/.conda/envs/mrrc/lib/python3.4/site-packages/llvmlite/binding/linker.py", line 11, in link_modules
    raise RuntimeError(str(outerr))
RuntimeError: Linking globals named '_cudapy_smem': symbol multiply defined!
```

**Comment by sklam** [comment]
I commented out setting internal linkage to shared memory due to a NVVM bug: https://github.com/numba/numba/blob/afd9617eace3009ff1f61485b342f1f5e7b058c0/numba/cuda/cudaimpl.py#L295
I will try to fix it.

**Comment by gmarkall** [comment]
Ah, I see. I wasn't sure if I shouldn't have been declaring shared arrays in separate functions.
