### ISSUE TITLE
numba.core.errors.CompilerError: Failed in nopython mode pipeline (step: analyzing bytecode) / Illegal IR, del found at: del foo

### ISSUE THREAD

**Issue by Semnodime** [numba/numba#9590]
## Reporting a bug
- [x] I have searched the existing issues via [`is:issue in:title "Illegal IR"`](https://github.com/numba/numba/issues?q=is%3Aissue+in%3Atitle+%22Illegal+IR%22)
- [x] I have tried using the latest released version of Numba (`numba==0.59.1`)
- [x] I have included a self contained code sample to reproduce the problem.

## Error
```
/bin/python bug.py 
Traceback (most recent call last):
  File "bug.py", line 11, in <module>
    foo()
  File "/lib/python3.12/site-packages/numba/core/dispatcher.py", line 487, in _compile_for_args
    raise e
  File "/lib/python3.12/site-packages/numba/core/dispatcher.py", line 420, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/dispatcher.py", line 957, in compile
    cres = self._compiler.compile(args, return_type)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/dispatcher.py", line 125, in compile
    status, retval = self._compile_cached(args, return_type)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/dispatcher.py", line 139, in _compile_cached
    retval = self._compile_core(args, return_type)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/dispatcher.py", line 152, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/compiler.py", line 751, in compile_extra
    return pipeline.compile_extra(func)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/compiler.py", line 445, in compile_extra
    return self._compile_bytecode()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/compiler.py", line 513, in _compile_bytecode
    return self._compile_core()
           ^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/compiler.py", line 492, in _compile_core
    raise e
  File "/lib/python3.12/site-packages/numba/core/compiler.py", line 479, in _compile_core
    pm.run(self.state)
  File "/lib/python3.12/site-packages/numba/core/compiler_machinery.py", line 368, in run
    raise patched_exception
  File "/lib/python3.12/site-packages/numba/core/compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "/lib/python3.12/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/site-packages/numba/core/compiler_machinery.py", line 318, in _runPass
    enforce_no_dels(internal_state.func_ir)
  File "/lib/python3.12/site-packages/numba/core/ir_utils.py", line 2219, in enforce_no_dels
    raise CompilerError(msg, loc=dels[0].loc)
numba.core.errors.CompilerError: Failed in nopython mode pipeline (step: analyzing bytecode)
Illegal IR, del found at: del bar

File "bug.py", line 7:
def foo():
    <source elided>
    bar = []
    del bar
    ^
```

## Reproducer
```python3
from numba import njit


@njit
def foo():
    bar = []
    del bar


if __name__ == '__main__':
    foo()
```

**Comment by gmarkall** [comment]
`del` is not supported - I see we don't list it as supported, but we also don't list it as unsupported - in #9593 I've added a note that it is unsupported.
