### ISSUE TITLE
Similar attribute names in nb.types.NamedTuple cause crashes

### ISSUE THREAD

**Issue by ocmob** [numba/numba#9607]
It seems like `nb.optional` doesn't work with `nb.types.NamedTuple` (it does with `nb.types.Tuple`, though). Here is the minimum repro:

`import numba as nb
from typing import NamedTuple

class Params(NamedTuple):
    param1: float
    param2: int

ParamsNumbaType = nb.types.NamedTuple((nb.f8, nb.i8), Params)

@nb.njit(ParamsNumbaType(ParamsNumbaType))
def func(my_tup: Params):
    return my_tup

tup = Params(3., 3)
func(tup)  # Works

class ParamsOptional(NamedTuple):
    param1: float
    param2: int | None = None

ParamsOptionalNumbaType = nb.types.NamedTuple((nb.f8, nb.optional(nb.i8)), ParamsOptional)

@nb.njit(ParamsOptionalNumbaType(ParamsOptionalNumbaType))
def func2(my_tup: ParamsOptional):
    return my_tup

tup = ParamsOptional(3., 3)
func2(tup)  # Fails
`

**Comment by esc** [comment]
@ocmob thank you for reporting this. I have updated the reproducer to include the `import numba as nb`.

**Comment by esc** [comment]
The error message is

```
 💣 zsh» python issue_9607.py
Traceback (most recent call last):
  File "/Users/vhaenel/git/numba/issue_9607.py", line 28, in <module>
    func2(tup)  # Fails
    ^^^^^^^^^^
  File "/Users/vhaenel/git/numba/numba/core/dispatcher.py", line 658, in _explain_matching_error
    raise TypeError(msg)
TypeError: No matching definition for argument type(s) ParamsOptional(float64, int64)
```

**Comment by esc** [comment]
@ocmob looks like I can reproduce this. I am provisionally labelling this as a typing bug until a second maintainer can verify it, thank you for reporting.

**Comment by sklam** [comment]
I'd classify this as a feature request to expand support to `typing.NamedTuple`. All tuple/namedtuple support predates that.
