### ISSUE TITLE
Failure in `test_TestPrangeSpecific`

### ISSUE THREAD

**Issue by esc** [numba/numba#9615]
With `main` from today (fb1d52b988d308852a7023132eabaee8c7a750dd)

```
 💣 zsh» python -m numba.runtests -v numba.tests.test_parfors.TestParforsRunner.test_TestPrangeSpecific
test_TestPrangeSpecific (numba.tests.test_parfors.TestParforsRunner.test_TestPrangeSpecific) ... FAIL

======================================================================
FAIL: test_TestPrangeSpecific (numba.tests.test_parfors.TestParforsRunner.test_TestPrangeSpecific)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/esc/git/numba/numba/tests/test_parfors.py", line 126, in test_TestPrangeSpecific
    self.runner()
  File "/Users/esc/git/numba/numba/tests/test_parfors.py", line 85, in runner
    self.subprocess_test_runner(test_module=themod,
  File "/Users/esc/git/numba/numba/tests/support.py", line 623, in subprocess_test_runner
    self.assertEqual(status.returncode, 0, streams)
AssertionError: -6 != 0 :
captured stdout:
captured stderr: /Users/esc/git/numba/numba/core/typed_passes.py:336: NumbaPerformanceWarning:
The keyword argument 'parallel=True' was specified but no transformation for parallel execution was possible.

To find out why, try turning on parallel diagnostics, see https://numba.readthedocs.io/en/stable/user/parallel.html#diagnostics for help.

File "numba/tests/test_parfors.py", line 4349:
        # Test for issue4007.
        def test_impl(n):
        ^

  warnings.warn(errors.NumbaPerformanceWarning(msg,
.OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
Fatal Python error: Aborted

Thread 0x00000001f2ac2100 (most recent call first):
  File "/Users/esc/git/numba/numba/tests/test_parfors.py", line 253 in check_parfors_vs_others
  File "/Users/esc/git/numba/numba/tests/test_parfors.py", line 3668 in prange_tester
  File "/Users/esc/git/numba/numba/tests/test_parfors.py", line 4463 in test_call_hoisting
  File "/Users/esc/miniconda3-arm64/envs/numba_3.11/lib/python3.11/unittest/case.py", line 579 in _callTestMethod
  File "/Users/esc/miniconda3-arm64/envs/numba_3.11/lib/python3.11/unittest/case.py", line 623

----------------------------------------------------------------------
Ran 1 test in 1.360s

FAILED (failures=1)
```

This points at:

```
    def test_argument_alias_recarray_field(self):
        # Test for issue4007.
        def test_impl(n):
            for i in range(len(n)):
                n.x[i] = 7.0
            return n
        X1 = np.zeros(10, dtype=[('x', float), ('y', int), ])
        X2 = np.zeros(10, dtype=[('x', float), ('y', int), ])
        X3 = np.zeros(10, dtype=[('x', float), ('y', int), ])
        v1 = X1.view(np.recarray)
        v2 = X2.view(np.recarray)
        v3 = X3.view(np.recarray)

        # Numpy doesn't seem to support almost equal on recarray.
        # So, we convert to list and use assertEqual instead.
        python_res = list(test_impl(v1))
        njit_res = list(njit(test_impl)(v2))
        pa_func = njit(test_impl, parallel=True)
        pa_res = list(pa_func(v3))
        self.assertEqual(python_res, njit_res)
        self.assertEqual(python_res, pa_res)
```

**Comment by esc** [comment]
I added https://github.com/numba/pixie/pull/21 to resolve. But actually the problem was somewhere else. `main` is missing a backport of:

https://github.com/numba/numba/pull/9568

**Comment by esc** [comment]
Backport is here: https://github.com/numba/numba/pull/9617
