### ISSUE TITLE
Tuples and inline = 'always' don't play together

### ISSUE THREAD

**Issue by TheTesla** [numba/numba#9632]
## Crashing

Adding `inline='always'` gives me:
```
/home/efame275/py-par-dict/pardictimpl_fast_tuple_dict_inline.py:120: NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  return dicts[hash(key)%nothrds][key]
Traceback (most recent call last):
  File "/home/efame275/.venv-default/lib/python3.12/site-packages/numba/typed/dictobject.py", line 778, in impl
    raise KeyError()
KeyError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/efame275/py-par-dict/pardictimpl_fast_tuple_dict_inline.py", line 154, in <module>
    demo()
SystemError: CPUDispatcher(<function demo at 0x766417112f20>) returned a result with an exception set

```
code:

https://github.com/TheTesla/py-par-dict/blob/538e89b77b661dad9d4181ca22fa3d1e5dfcc653/pardictimpl_fast_tuple_dict_inline.py

## Working

working version without inline:

https://github.com/TheTesla/py-par-dict/blob/538b059ec8866d0644d1c7c0fb1272ff4f590c48/pardictimpl_fast_List.py

output:

```
/home/efame275/py-par-dict/pardictimpl_fast_tuple_dict.py:140: NumbaTypeSafetyWarning: unsafe cast from uint64 to int64. Precision may be lost.
  tmp += par_dict_getitem(pdict, i)
- threads:  1 - time:  13.624 cputime:  13.62
- threads:  1 - time:  5.134 cputime:  5.13
- threads:  2 - time:  6.922 cputime:  13.84
- threads:  3 - time:  5.380 cputime:  16.14
- threads:  4 - time:  4.368 cputime:  17.47
- threads:  5 - time:  3.398 cputime:  16.99
- threads:  6 - time:  2.979 cputime:  17.87
- threads:  7 - time:  2.669 cputime:  18.68
- threads:  8 - time:  2.466 cputime:  19.73
```

## numba -s

```
__Time Stamp__
Report started (local time)                   : 2024-06-27 10:58:27.881693
UTC start time                                : 2024-06-27 08:58:27.881733
Running time (s)                              : 2.450545

__Hardware Information__
Machine                                       : x86_64
CPU Name                                      : znver3
CPU Count                                     : 8
Number of accessible CPUs                     : 8
List of accessible CPUs cores                 : 0-7
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit aes avx avx2 bmi bmi2
                                                clflushopt cmov crc32 cx16 cx8
                                                fsgsbase fxsr invpcid lzcnt mmx
                                                movbe pclmul popcnt prfchw rdrnd
                                                rdseed sahf sse sse2 sse3 sse4.1
                                                sse4.2 sse4a ssse3 xsave

Memory Total (MB)                             : 7940
Memory Available (MB)                         : 4213

__OS Information__
Platform Name                                 : Linux-6.8.0-35-generic-x86_64-with-glibc2.39
Platform Release                              : 6.8.0-35-generic
OS Name                                       : Linux
OS Version                                    : #35-Ubuntu SMP PREEMPT_DYNAMIC Mon May 20 15:51:52 UTC 2024
OS Specific Version                           : ?
Libc Version                                  : glibc 2.39

__Python Information__
Python Compiler                               : GCC 13.2.0
Python Implementation                         : CPython
Python Version                                : 3.12.3
Python Locale                                 : en_US.UTF-8

__Numba Toolchain Versions__
Numba Version                                 : 0.60.0
llvmlite Version                              : 0.43.0

__LLVM Information__
LLVM Version                                  : 14.0.6

__CUDA Information__
CUDA Device Initialized                       : False
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA NVIDIA Bindings Available                : ?
CUDA NVIDIA Bindings In Use                   : ?
CUDA Minor Version Compatibility Available    : ?
CUDA Minor Version Compatibility Needed       : ?
CUDA Minor Version Compatibility In Use       : ?
CUDA Detect Output:
None
CUDA Libraries Test Output:
None

__NumPy Information__
NumPy Version                                 : 1.26.4
NumPy Supported SIMD features                 : ('MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'AVX2')
NumPy Supported SIMD dispatch                 : ('SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512_KNL', 'AVX512_KNM', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL')
NumPy Supported SIMD baseline                 : ('SSE', 'SSE2', 'SSE3')
NumPy AVX512_SKX support detected             : False

__SVML Information__
SVML State, config.USING_SVML                 : False
SVML Library Loaded                           : False
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : False

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: GNU
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda Build                                   : not installed
Conda Env                                     : 24.5.0
Conda Platform                                : linux-64
Conda Python Version                          : 3.12.2.final.0
Conda Root Writable                           : True

__Installed Packages__
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
aiohttp                   3.9.5           py312h98912ed_0    conda-forge
aiosignal                 1.3.1              pyhd8ed1ab_0    conda-forge
anaconda-anon-usage       0.4.4           py312hfc0e8ea_100  
aom                       3.8.2                h59595ed_0    conda-forge
archspec                  0.2.3              pyhd3eb1b0_0  
asttokens                 2.0.5              pyhd3eb1b0_0  
attrs                     23.2.0             pyh71513ae_0    conda-forge
blas                      1.0                    openblas  
blosc                     1.21.5               hc2324a3_1    conda-forge
boltons                   23.0.0          py312h06a4308_0  
brotli-python             1.0.9           py312h6a678d5_8  
bzip2                     1.0.8                h5eee18b_6  
c-ares                    1.19.1               h5eee18b_0  
ca-certificates           2024.3.11            h06a4308_0  
cairo                     1.18.0               h3faef2a_0    conda-forge
certifi                   2024.6.2        py312h06a4308_0  
cffi                      1.16.0          py312h5eee18b_1  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     24.5.0          py312h06a4308_0  
conda-content-trust       0.2.0           py312h06a4308_1  
conda-libmamba-solver     24.1.0             pyhd3eb1b0_0  
conda-package-handling    2.2.0           py312h06a4308_1  
conda-package-streaming   0.9.0           py312h06a4308_0  
cryptography              42.0.5          py312hdda0065_1  
dav1d                     1.2.1                hd590300_0    conda-forge
decorator                 5.1.1              pyhd3eb1b0_0  
distro                    1.9.0           py312h06a4308_0  
double-conversion         3.3.0                h59595ed_0    conda-forge
eigen                     3.4.0                h00ab1b0_0    conda-forge
elfutils                  0.189                hde5d1a3_0    conda-forge
executing                 0.8.3              pyhd3eb1b0_0  
expat                     2.5.0                hcb278e6_1    conda-forge
ffmpeg                    6.1.1           gpl_hee4b679_108    conda-forge
fmt                       9.1.0                hdb19cb5_1  
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_2    conda-forge
fontconfig                2.14.2               h14ed4e7_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
freeimage                 3.18.0              h4b96d29_20    conda-forge
freetype                  2.12.1               h267a509_2    conda-forge
fribidi                   1.0.10               h36c2ea0_0    conda-forge
frozendict                2.4.4           py312h9a8786e_0    conda-forge
frozenlist                1.4.1           py312h98912ed_0    conda-forge
gettext                   0.22.5               h59595ed_2    conda-forge
gettext-tools             0.22.5               h59595ed_2    conda-forge
gl2ps                     1.4.2                h0708190_0    conda-forge
gmp                       6.3.0                h59595ed_1    conda-forge
gnutls                    3.7.9                hb077bed_0    conda-forge
graphite2                 1.3.13            h59595ed_1003    conda-forge
harfbuzz                  8.3.0                h3d44ed6_0    conda-forge
hdf4                      4.2.15               h2a13503_7    conda-forge
hdf5                      1.14.3          nompi_h4f84152_101    conda-forge
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.7             py312h06a4308_0  
imath                     3.1.11               hfc55251_0    conda-forge
ipython                   8.25.0          py312h06a4308_0  
jedi                      0.18.1          py312h06a4308_1  
jsoncpp                   1.9.5                h4bd325d_1    conda-forge
jsonpatch                 1.33            py312h06a4308_1  
jsonpointer               2.1                pyhd3eb1b0_0  
jxrlib                    1.1                  hd590300_3    conda-forge
krb5                      1.20.1               h143b758_1  
lame                      3.100             h166bdaf_1003    conda-forge
lcms2                     2.16                 hb7c19ff_0    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
libabseil                 20240116.2      cxx17_h59595ed_0    conda-forge
libaec                    1.1.3                h59595ed_0    conda-forge
libarchive                3.6.2                h039dbb9_1    conda-forge
libasprintf               0.22.5               h661eb56_2    conda-forge
libasprintf-devel         0.22.5               h661eb56_2    conda-forge
libass                    0.17.1               h8fe9dca_1    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libcurl                   8.7.1                h251f7ec_0  
libdeflate                1.20                 hd590300_0    conda-forge
libdrm                    2.4.120              hd590300_0    conda-forge
libedit                   3.1.20230828         h5eee18b_0  
libev                     4.33                 h7f8727e_1  
libexpat                  2.5.0                hcb278e6_1    conda-forge
libffi                    3.4.4                h6a678d5_1  
libgcc-ng                 13.2.0              h77fa898_10    conda-forge
libgettextpo              0.22.5               h59595ed_2    conda-forge
libgettextpo-devel        0.22.5               h59595ed_2    conda-forge
libgfortran-ng            13.2.0              h69a702a_10    conda-forge
libgfortran5              13.2.0              h3d2ce59_10    conda-forge
libglib                   2.78.4               h783c2da_0    conda-forge
libgomp                   13.2.0              h77fa898_10    conda-forge
libhwloc                  2.10.0          default_h5622ce7_1001    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
libjpeg-turbo             3.0.0                hd590300_1    conda-forge
liblapack                 3.9.0           22_linux64_openblas    conda-forge
libllvm17                 17.0.6               hb3ce162_1    conda-forge
libmamba                  1.5.8                hfe524e5_2  
libmambapy                1.5.8           py312h2dafd23_2  
libmicrohttpd             0.9.77               h97afed2_0    conda-forge
libnetcdf                 4.9.2           nompi_h9612171_113    conda-forge
libnghttp2                1.57.0               h2d74bed_0  
libnsl                    2.0.1                hd590300_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.27          pthreads_h413a1c8_0    conda-forge
libopenvino               2024.0.0             h2da1b83_5    conda-forge
libopenvino-auto-batch-plugin 2024.0.0             hb045406_5    conda-forge
libopenvino-auto-plugin   2024.0.0             hb045406_5    conda-forge
libopenvino-hetero-plugin 2024.0.0             h5c03a75_5    conda-forge
libopenvino-intel-cpu-plugin 2024.0.0             h2da1b83_5    conda-forge
libopenvino-intel-gpu-plugin 2024.0.0             h2da1b83_5    conda-forge
libopenvino-ir-frontend   2024.0.0             h5c03a75_5    conda-forge
libopenvino-onnx-frontend 2024.0.0             h07e8aee_5    conda-forge
libopenvino-paddle-frontend 2024.0.0             h07e8aee_5    conda-forge
libopenvino-pytorch-frontend 2024.0.0             he02047a_5    conda-forge
libopenvino-tensorflow-frontend 2024.0.0             h39126c6_5    conda-forge
libopenvino-tensorflow-lite-frontend 2024.0.0             he02047a_5    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpciaccess              0.18                 hd590300_0    conda-forge
libpng                    1.6.43               h2797004_0    conda-forge
libprotobuf               4.25.3               h08a7969_0    conda-forge
libraw                    0.21.1               h2a13503_2    conda-forge
libsolv                   0.7.24               he621ea3_1  
libsqlite                 3.46.0               hde9e2c9_0    conda-forge
libssh2                   1.11.0               h251f7ec_0  
libstdcxx-ng              13.2.0              hc0a3c3a_10    conda-forge
libtasn1                  4.19.0               h166bdaf_0    conda-forge
libtheora                 1.1.1             h7f98852_1005    conda-forge
libtiff                   4.6.0                h1dd3fc0_3    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libva                     2.21.0               h4ab18f5_2    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libvpx                    1.14.1               hac33072_0    conda-forge
libwebp-base              1.4.0                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.7               hc051c1a_1    conda-forge
libzip                    1.10.1               h2629f0a_3    conda-forge
libzlib                   1.2.13               h4ab18f5_6    conda-forge
loguru                    0.7.2           py312h7900ff3_1    conda-forge
lz4-c                     1.9.4                h6a678d5_1  
lzo                       2.10              hd590300_1001    conda-forge
matplotlib-inline         0.1.6           py312h06a4308_0  
menuinst                  2.0.2           py312h06a4308_1  
mesalib                   23.3.2               h6b56f8e_0    conda-forge
msgpack-python            1.0.8           py312h2492b07_0    conda-forge
multidict                 6.0.5           py312h98912ed_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
nettle                    3.9.1                h7ab15ed_0    conda-forge
nlohmann_json             3.11.3               h59595ed_0    conda-forge
numpy                     1.26.4          py312h2809609_0  
numpy-base                1.26.4          py312he1a6c75_0  
occt                      7.8.1           all_hc3954f8_201    conda-forge
ocl-icd                   2.3.2                hd590300_1    conda-forge
openexr                   3.2.2                haf962dd_1    conda-forge
openh264                  2.4.1                h59595ed_0    conda-forge
openjpeg                  2.5.2                h488ebb8_0    conda-forge
openssl                   3.3.1                h4ab18f5_0    conda-forge
p11-kit                   0.24.1               hc5aa10d_0    conda-forge
packaging                 23.2            py312h06a4308_0  
parso                     0.8.3              pyhd3eb1b0_0  
pcre2                     10.42                hebb0a14_1  
pexpect                   4.8.0              pyhd3eb1b0_3  
pip                       24.0            py312h06a4308_0  
pixman                    0.43.2               h59595ed_0    conda-forge
platformdirs              3.10.0          py312h06a4308_0  
pluggy                    1.0.0           py312h06a4308_1  
proj                      9.3.1                h1d62c97_0    conda-forge
prompt-toolkit            3.0.43          py312h06a4308_0  
prompt_toolkit            3.0.43               hd3eb1b0_0  
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3eb1b0_2  
pugixml                   1.14                 h59595ed_0    conda-forge
pure_eval                 0.2.2              pyhd3eb1b0_0  
pybind11-abi              5                    hd3eb1b0_0  
pycosat                   0.6.6           py312h5eee18b_1  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.15.1          py312h06a4308_1  
pyparsing                 3.1.2              pyhd8ed1ab_0    conda-forge
pysocks                   1.7.1           py312h06a4308_0  
python                    3.12.2          hab00c5b_0_cpython    conda-forge
python_abi                3.12                    4_cp312    conda-forge
pythonocc-core            7.8.1           all_h0638c4f_200    conda-forge
rapidjson                 1.1.0.post20240409      hac33072_1    conda-forge
readline                  8.2                  h5eee18b_0  
reproc                    14.2.4               h6a678d5_2  
reproc-cpp                14.2.4               h6a678d5_2  
requests                  2.31.0          py312h06a4308_1  
ruamel.yaml               0.17.21         py312h5eee18b_0  
setuptools                69.5.1          py312h06a4308_0  
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.2.0                hdb0a2a9_1    conda-forge
sqlite                    3.45.3               h5eee18b_0  
stack_data                0.2.0              pyhd3eb1b0_0  
svgwrite                  1.4.3              pyhd8ed1ab_0    conda-forge
svt-av1                   2.0.0                h59595ed_0    conda-forge
tbb                       2021.12.0            h297d8ca_1    conda-forge
tbb-devel                 2021.12.0            h7c56ddd_1    conda-forge
tk                        8.6.14               h39e8969_0  
tqdm                      4.66.2          py312he106c6f_0  
traitlets                 5.14.3          py312h06a4308_0  
truststore                0.8.0           py312h06a4308_0  
tzdata                    2024a                h04d1e81_0  
urllib3                   2.1.0           py312h06a4308_1  
utfcpp                    4.0.5                ha770c72_0    conda-forge
vtk                       9.2.6           osmesa_py312h1234567_123    conda-forge
vtk-base                  9.2.6           osmesa_py312h1234567_123    conda-forge
vtk-io-ffmpeg             9.2.6           osmesa_py312h1234567_123    conda-forge
wcwidth                   0.2.5              pyhd3eb1b0_0  
wheel                     0.43.0          py312h06a4308_0  
wslink                    2.0.5              pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h166bdaf_2    conda-forge
x265                      3.5                  h924138e_3    conda-forge
xorg-damageproto          1.2.1             h7f98852_1002    conda-forge
xorg-fixesproto           5.0               h7f98852_1002    conda-forge
xorg-glproto              1.4.17            h7f98852_1002    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.1.1                hd590300_0    conda-forge
xorg-libsm                1.2.4                h7391055_0    conda-forge
xorg-libx11               1.8.9                h8ee46fc_0    conda-forge
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdamage           1.1.5                h7f98852_1    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h0b41bf4_2    conda-forge
xorg-libxfixes            5.0.3             h7f98852_1004    conda-forge
xorg-libxrandr            1.5.2                h7f98852_1    conda-forge
xorg-libxrender           0.9.11               hd590300_0    conda-forge
xorg-libxt                1.3.0                hd590300_1    conda-forge
xorg-randrproto           1.5.0             h7f98852_1001    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-util-macros          1.19.3               h7f98852_0    conda-forge
xorg-xextproto            7.3.0             h0b41bf4_1003    conda-forge
xorg-xf86vidmodeproto     2.3.1             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.4.6                h5eee18b_1  
yaml-cpp                  0.8.0                h6a678d5_1  
yarl                      1.9.4           py312h98912ed_0    conda-forge
zlib                      1.2.13               h4ab18f5_6    conda-forge
zstandard                 0.22.0          py312h2c38b39_0  
zstd                      1.5.5                hc292b87_2  

No errors reported.


__Warning log__
Warning (cuda): CUDA driver library cannot be found or no CUDA enabled devices are present.
Exception class: <class 'numba.cuda.cudadrv.error.CudaSupportError'>
Warning (psutil): psutil cannot be imported. For more accuracy, consider installing it.
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_quota_us
Warning (no file): /sys/fs/cgroup/cpuacct/cpu.cfs_period_us

```

**Comment by gmarkall** [comment]
Thanks for the report and self-contained reproducer - I can reproduce the `SystemError` locally with `main`.

**Comment by gmarkall** [comment]
Are our typed dict objects threadsafe? Something to discuss in the triage meeting.

**Comment by TheTesla** [comment]
> Are our typed dict objects threadsafe? Something to discuss in the triage meeting.

There is no concurrent mutation.

**Comment by gmarkall** [comment]
What are `par_dict_sync` and `par_dict_setitem` doing? Is that not concurrent mutation?

**Comment by TheTesla** [comment]
They are mutating dicts depending on the thread ID. At no time, more than one thread mutates the same dict.
