### ISSUE TITLE
Errors not being raised when running code in parallel 

### ISSUE THREAD

**Issue by MitchBond** [numba/numba#9673]
When running the following code I'm finding some inconsistencies in error behaviour when running code in prange
```
@njit
def sim_once(x, y):
    raise ValueError("Invalid value")


@njit(parallel=True)
def numba_func(x):
    n_sims = 20
    y = np.zeros(n_sims)
    for i in prange(n_sims):
        y[i] += 1
        sim_once(x=x, y=y)

    return y


@njit(parallel=False)
def non_parallel_numba_func(x):
    n_sims = 20
    y = np.zeros(n_sims)
    for i in prange(n_sims):
        y[i] += 1
        sim_once(x=x, y=y)

    return y
```

When running `sim_once(x=0, y=1)` a value error is raised as expected. However, when running the `numba_func` with prange there's no error raised and the return value is `np.array([1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 1. 1. 1.])`. Using the `non_parallel_numba_func` a ValueError is raised as expected. 

Interestingly if I replace the `sim_once` function call with `raise ValueError("Invalid vaue"), then the parallel function raises an error. 

Running numba 0.60.0 on python 3.11.8.

**Comment by jack-mcivor** [comment]
I can recreate with the `workqueue` threading layer, but not the `omp` threading layer.

Recreates issue
```bash
docker run --rm -it python:3.11 bash  # 5393dd665963
pip install numpy numba  # numpy==2.0.1 numba==0.60 llvmlite==0.43.0
NUMBA_THREADING_LAYER=workqueue python  # Python 3.11.9 (main, Jul 23 2024, 07:22:22) [GCC 12.2.0] on linux
>>> import numpy as np; from numba import njit, prange, threading_layer
>>> <copy the above, error on `numba_func(2.0)`>
>>> numba_func(2.0)  # no error!
>>> threading_layer()  # 'workqueue'
```
No issue
```bash
docker run --rm -it python:3.11 bash  # 5393dd665963
pip install numpy numba  # numpy==2.0.1 numba==0.60 llvmlite==0.43.0
NUMBA_THREADING_LAYER=omp python  # Python 3.11.9 (main, Jul 23 2024, 07:22:22) [GCC 12.2.0] on linux
>>> import numpy as np; from numba import njit, prange, threading_layer
>>> <copy the above, error on `numba_func(2.0)`>
>>> numba_func(2.0)
Traceback (most recent call last):
  File "<stdin>", line 3, in sim_once
ValueError: Invalid value

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: CPUDispatcher(<function numba_func at 0x7f94f6b24040>) returned a result with an exception set
>>> threading_layer()  # 'omp'
```

I noticed, because I had the same issue on `python:3.11-slim` (which was selecting `workqueue`), but not `python:3.11` (which was selecting `omp`)
