### ISSUE TITLE
TypingError When Accessing Attributes of Nested JitClasses

### ISSUE THREAD

**Issue by cyprienc** [numba/numba#9690]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (0.60.0).
- [x] I have included a self-contained code sample to reproduce the problem.

### Description

I get a `TypingError` when I try to access attributes of a `jitclass` contained in another `jitclass` as a list.

### Error Message

```
Traceback (most recent call last):
  File "/mnt/c/Users/.../scratch.py", line 48, in <module>
    c = C(b_list)
  File "/home/.../mambaforge/envs/env/lib/python3.10/site-packages/numba/experimental/jitclass/base.py", line 124, in __call__
    return cls._ctor(*bind.args[1:], **bind.kwargs)
  File "/home/.../mambaforge/envs/env/lib/python3.10/site-packages/numba/core/dispatcher.py", line 423, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/home/.../mambaforge/envs/env/lib/python3.10/site-packages/numba/core/dispatcher.py", line 364, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'class_type' of type jitclass.A#7fde558affa0<a:int32>

File "scratch.py", line 36:
    def __init__(self, c: list[B]):
        <source elided>
        self.c = c
        self._a = typed.List.empty_list(A.class_type.instance_type)
        ^

During: typing of get attribute at /mnt/c/Users/.../scratch.py (36)

File "scratch.py", line 36:
    def __init__(self, c: list[B]):
        <source elided>
        self.c = c
        self._a = typed.List.empty_list(A.class_type.instance_type)
        ^

During: resolving callee type: jitclass.C#7fde4dab8d00<c:ListType[instance.jitclass.B#7fde4dab87f0<b:ListType[instance.jitclass.A#7fde558affa0<a:int32>]>],_a:ListType[instance.jitclass.A#7fde558affa0<a:int32>]>
During: typing of call at <string> (3)

During: resolving callee type: jitclass.C#7fde4dab8d00<c:ListType[instance.jitclass.B#7fde4dab87f0<b:ListType[instance.jitclass.A#7fde558affa0<a:int32>]>],_a:ListType[instance.jitclass.A#7fde558affa0<a:int32>]>
During: typing of call at <string> (3)


File "<string>", line 3:
<source missing, REPL/exec in use?>

ERROR conda.cli.main_run:execute(125): `conda run python /mnt/c/Users/.../scratch.py` failed. (See above for error)

Process finished with exit code 1
```

### Reproducing Code

```python
from numba import typed, types
from numba.experimental import jitclass

a_spec = {
    "a": types.int32,
}

@jitclass(a_spec)
class A:
    def __init__(self, a: int):
        self.a = a

b_spec = {
    "b": types.ListType(A.class_type.instance_type),
}

@jitclass(b_spec)
class B:
    def __init__(self, b: list[A]):
        self.b = b

c_spec = {
    "c": types.ListType(B.class_type.instance_type),
    "_a": types.ListType(A.class_type.instance_type),
}

@jitclass(c_spec)
class C:
    def __init__(self, c: list[B]):
        self.c = c
        self._a = typed.List.empty_list(A.class_type.instance_type)
        for b in self.c:
            self._a.extend(b.b)

a_list = typed.List.empty_list(A.class_type.instance_type)
a_list.append(A(1))
a_list.append(A(2))

b_list = typed.List.empty_list(B.class_type.instance_type)
b_list.append(B(a_list))

c = C(b_list)
```

### Expected Behavior

The code should compile and execute without errors, creating an instance of `C` containing a list of `B` instances, each containing a list of `A` instances.

### Environment

- Numba version: 0.60.0
- Python version: 3.10
- Operating System: Ubuntu 22.04
- Installation method: Conda

**Comment by gmarkall** [comment]
Thanks for the report... I'm sure I once saw a workaround or another way of doing this at some point, but it's escaping me for now... will update this if / when I remember / find it.

**Comment by cyprienc** [comment]
Thanks for the update @gmarkall.

We're actually considering a significant design choice based on jitclasses. So if I understand correctly, jitclasses won't be improved in the near future? Is there a roadmap at all for them? Or will they be deprecated?
