### ISSUE TITLE
What is the solution?

### ISSUE THREAD

**Issue by h-omani90** [numba/numba#9695]
default_encoding:       cp1252
Assume aggressive 'core.a' caching enabled.
Note: optional global include file 'C:\Users\Lenovo\OneDrive\\u0627\u0644\u0645\u0633\u062a\u0646\u062f\u0627\u062a\Arduino\sketch_aug9a\sketch_aug9a.ino.globals.h' does not exist.
  Read more at https://arduino-esp8266.readthedocs.io/en/latest/faq/a06-global-build-options.html

*** Traceback (most recent call last):
  File "C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 824, in <module>
    rc = main()
  File "C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 819, in main
    handle_error(0)   # commit print buffer
  File "C:\Users\Lenovo\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\3.1.2/tools/mkbuildoptglobals.py", line 274, in handle_error
    print(msg_print_buf, file=fd, end='', flush=True)
  File "D:\obj\Windows-Release\37win32_Release\msi_python\zip_win32\cp437.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 138-146: character maps to <undefined>

exit status 1

Compilation error: exit status 1

**Comment by esc** [comment]
@h-omani90 this does not seem to be related to Numba? Did you post this on the wrong issue tracker?

**Comment by h-omani90** [comment]
> @h-omani90لا يبدو أن هذا له علاقة بـ Numba؟ هل نشرت هذا على متتبع المشكلات الخاطئ؟

**Comment by h-omani90** [comment]
I didn't understand what you mean

**Comment by esc** [comment]
> I didn't understand what you mean

The error message you posted will not be solved here.
