### ISSUE TITLE
Accessing fields from numpy records inside parallel function raises error

### ISSUE THREAD

**Issue by TobyBoyne** [numba/numba#9728]
## Similar issues

#4277, #2625 - Lowering Error for tuples with `parallel=True`

## Reporting a bug

- [ ] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [ ] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

## Details

Accessing values from numpy records inside of parellelized `prange` loops raises a(n unclear) error.

I am using this custom datatype to store a set of ~10 parameters that are used throughout many functions. If there is a better way to handle a dictionary-style parameter object, this would also suffice as a solution for me (maybe I should try `@jitclass`?)

Thanks for all your work on numba, really great project!

### Minimum Repro

Below is a MWE of the issue. Only `foo_fail` raises the error, whereas `foo_pass` works fine. Also, if you change `parallel=False`, then both functions work without error.

```python
from numba import njit, prange
import numpy as np

PARAMS_DTYPE = np.dtype([("delta_z", np.int64)])

@njit(parallel=True)
def foo_fail(params):
    z = 0
    for _ in prange(10):
        z += params["delta_z"]
    return z

@njit(parallel=True)
def foo_pass(params):
    z = 0
    y = params["delta_z"]
    for _ in prange(10):
        z += y
    return z

params = np.record((10,), dtype=PARAMS_DTYPE)
print(foo_pass(params))
print(foo_fail(params))
```

Output
```
100 # first function works fine
...
TypeError: Type of #10 arg mismatch: [8 x i8]* != [8 x i8]
```

### Versions
Python 3.10.11    
numba-0.60.0    
llvmlite-0.43.0

**Comment by gmarkall** [comment]
Thanks for the report and nice reproducer. I can reproduce the issue locally. @DrTodd13 Do you have any thoughts on this one?

**Comment by DrTodd13** [comment]
I don't believe this is a parallel accelerator problem.

`from numba import njit, prange, guvectorize, int64, typeof
from numba.core.types.npytypes import Record
import numpy as np

mcsparts = [("delta_z", int64)]
nprectype = Record.make_c_struct(mcsparts)
pparts = [("delta_z", np.int64)]
PARAMS_DTYPE = np.dtype(pparts)

@guvectorize([(int64, nprectype, int64[:])], '(),()->()')
def manguvec(sched, params, out):
    for i in prange(sched):
        out[i] = params["delta_z"]

params = np.record((10,), dtype=PARAMS_DTYPE)
pz = params["delta_z"]

vout = np.empty(10, dtype=np.int64)
manguvec(np.array([10]), params, vout)
print(vout)
`

`Traceback (most recent call last):
  File "/mnt/home/taanders/tests/numba/issue9728-2.py", line 11, in <module>
    def manguvec(sched, params, out):
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/decorators.py", line 206, in wrap
    return guvec.build_ufunc()
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/gufunc.py", line 140, in build_ufunc
    self.ufunc = self.gufunc_builder.build_ufunc()
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/ufuncbuilder.py", line 376, in build_ufunc
    dtypenums, ptr, env = self.build(cres)
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/ufuncbuilder.py", line 400, in build
    info = build_gufunc_wrapper(
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/wrappers.py", line 504, in build_gufunc_wrapper
    ).build()
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/wrappers.py", line 456, in build
    wrapperlib = self._compile_wrapper(wrapper_name)
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/wrappers.py", line 447, in _compile_wrapper
    self._build_wrapper(wrapperlib, wrapper_name)
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/wrappers.py", line 413, in _build_wrapper
    innercall, error = self.gen_loop_body(builder, pyapi, func, args)
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/np/ufunc/wrappers.py", line 462, in gen_loop_body
    status, retval = self.call_conv.call_function(
  File "/mnt/home/taanders/numba/intel_numba4/numba/numba/core/callconv.py", line 907, in call_function
    code = builder.call(callee, realargs, attrs=_attrs)
  File "/mnt/home/taanders/micromamba/envs/p310_numba/lib/python3.10/site-packages/llvmlite/ir/builder.py", line 881, in call
    inst = instructions.CallInstr(self.block, fn, args, name=name,
  File "/mnt/home/taanders/micromamba/envs/p310_numba/lib/python3.10/site-packages/llvmlite/ir/instructions.py", line 105, in __init__
    raise TypeError(msg)
TypeError: Type of #4 arg mismatch: [8 x i8]* != [8 x i8]
`

The above example uses guvectorize directly (which is what parallel accelerator does under the hood) and it has the same issue.  So, I think the issue is with @guvectorize and Record types.  Pinging @sklam and @stuartarchibald.

**Comment by stuartarchibald** [comment]
Thanks for debugging @DrTodd13, I agree, this doesn't seem to be related to `ParallelAccelerator`, I'll relabel the issue.

**Comment by DrTodd13** [comment]
Later I got to thinking that this might be like tuples where guvectorize doesn't support them but there was so much clamor for parallel accelerator support that we put in a hack to make it work.  I remember at some point Siu was saying that you were thinking about fixing guvectorize to support all types but I don't think any progress has been made on that.  We'll have to decide in this case if there's enough demand to justify a similar hack like tuple for Records.
