### ISSUE TITLE
numba.cuda.cudadrv.driver.CudaAPIError: [34]

### ISSUE THREAD

**Issue by pxrw** [numba/numba#9732]
## Reporting a bug
When I use namba versions in [0.58, 0.59, 0.60]，and type in "python -c "from numba import cuda; cuda.cudadrv.libs.test()", I get the following output:
Finding driver from candidates:
        libcuda.so
        libcuda.so.1
        /usr/lib/libcuda.so
        /usr/lib/libcuda.so.1
        /usr/lib64/libcuda.so
        /usr/lib64/libcuda.so.1
Using loader <class 'ctypes.CDLL'>
        Trying to load driver...        ok
                Loaded from libcuda.so
        Mapped libcuda.so paths:
                /usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
Finding nvvm from Conda environment
        Located at /home/pxr/miniconda3/envs/visionmb/lib/libnvvm.so.4.0.0
        Trying to open library...       ok
Finding nvrtc from Conda environment
        Located at /home/pxr/miniconda3/envs/visionmb/lib/libnvrtc.so.11.7.50
        Trying to open library...       ok
Finding cudart from Conda environment
        Located at /home/pxr/miniconda3/envs/visionmb/lib/libcudart.so.11.7.60
        Trying to open library...       ok
Finding cudadevrt from Conda environment
        Located at /home/pxr/miniconda3/envs/visionmb/lib/libcudadevrt.a
        Checking library...     ok
Finding libdevice from Conda environment
        Located at /home/pxr/miniconda3/envs/visionmb/lib/libdevice.10.bc
        Checking library...     ok
############################################################################
but, when I try to run my code, I got this error message:
Traceback (most recent call last):
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 254, in ensure_initialized
    self.cuInit(0)
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 327, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 395, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [34] Call to cuInit results in CUDA_ERROR_STUB_LIBRARY

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pxr/pxrProject/3Ddetection/MonoMamba/tools/train_val.py", line 16, in <module>
    from lib.helpers.trainer_helper import Trainer
  File "/home/pxr/pxrProject/3Ddetection/MonoMamba/lib/helpers/trainer_helper.py", line 15, in <module>
    from tools import eval
  File "/home/pxr/pxrProject/3Ddetection/MonoMamba/tools/eval.py", line 245, in <module>
    def devRotateIoUEval(rbox1, rbox2, criterion=-1):
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/decorators.py", line 131, in _jit
    disp.compile_device(argtypes, restype)
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/dispatcher.py", line 874, in compile_device
    cc = get_current_device().compute_capability
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/api.py", line 443, in get_current_device
    return current_context().device
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/devices.py", line 153, in _get_or_create_context_uncached
    with driver.get_active_context() as ac:
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 495, in __enter__
    driver.cuCtxGetCurrent(byref(hctx))
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 292, in __getattr__
    self.ensure_initialized()
  File "/home/pxr/miniconda3/envs/visionmb/lib/python3.9/site-packages/numba/cuda/cudadrv/driver.py", line 258, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in CUDA_ERROR_STUB_LIBRARY (34)

Hope to get some help from you, thanks a million!

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

**Comment by gmarkall** [comment]
I think Numba is finding the stub library instead of the real one. Do you have the CUDA driver installed? What does running `nvidia-smi` in a terminal show?

**Comment by pxrw** [comment]
![1727437174323](https://github.com/user-attachments/assets/09dba732-54a9-4155-896d-0a8f3efb577d)
Thanks for you replying, and this is my “nvidia-smi" output

**Comment by gmarkall** [comment]
do you have `LD_LIBRARY_PATH` set?

**Comment by pxrw** [comment]
yes, I set my `LD_LIBRARY_PATH` as this: `export LD_LIBRARY_PATH=/usr/local/cuda-11.8/lib64:$LD_LIBRARY_PATH`, but it's still not work, and output same errors.

**Comment by pxrw** [comment]
I try to change another numba=0.55.2 version in my conda environment, and then, I fond the same issue#8985. I try to follow its way to fix the error, I got this output when I input `python -c "from numba import cuda; cuda.cudadrv.libs.test()"` in the terminal
```
Finding nvvm from System
        located at /usr/local/cuda/nvvm/lib64/libnvvm.so.4.0.0
        trying to open library...       ok
Finding cudart from System
        located at /usr/local/cuda/lib64/libcudart.so.11.2.72
        trying to open library...       ok
Finding cudadevrt from System
        located at /usr/local/cuda/lib64/libcudadevrt.a
Finding libdevice from System
        searching for compute_20...     ok
        searching for compute_30...     ok
        searching for compute_35...     ok
        searching for compute_50...     ok
```

And when I input `python -c "from ctypes import CDLL; CDLL('libcuda.so')._undef"`, I got this
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libcuda.so: undefined symbol: _undef
```

I set my `LD_LIBRARY_PATH` point to the `libcuda`， but I still got the error output like this:
```
Traceback (most recent call last):
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 246, in ensure_initialized
    self.cuInit(0)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 319, in safe_cuda_api_call
    self._check_ctypes_error(fname, retcode)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 387, in _check_ctypes_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [34] Call to cuInit results in UNKNOWN_CUDA_ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pxr/pxrProject/3Ddetection/MonoMamba/tools/train_val.py", line 16, in <module>
    from lib.helpers.trainer_helper import Trainer
  File "/home/pxr/pxrProject/3Ddetection/MonoMamba/lib/helpers/trainer_helper.py", line 15, in <module>
    from tools import eval
  File "/home/pxr/pxrProject/3Ddetection/MonoMamba/tools/eval.py", line 262, in <module>
    def rotate_iou_kernel_eval(N,
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/decorators.py", line 99, in _jit
    return Dispatcher(func, [func_or_sig], targetoptions=targetoptions)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/compiler.py", line 807, in __init__
    self.compile(sigs[0])
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/compiler.py", line 1086, in compile
    kernel = _Kernel(self.py_func, argtypes, link=self.link,
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/core/compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/compiler.py", line 411, in __init__
    self.cooperative = 'cudaCGGetIntrinsicHandle' in lib.get_asm_str()
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/codegen.py", line 103, in get_asm_str
    return self._join_ptxes(self._get_ptxes(cc=cc))
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/codegen.py", line 107, in _get_ptxes
    ctx = devices.get_context()
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 220, in get_context
    return _runtime.get_or_create_context(devnum)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 138, in get_or_create_context
    return self._get_or_create_context_uncached(devnum)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/devices.py", line 153, in _get_or_create_context_uncached
    with driver.get_active_context() as ac:
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 487, in __enter__
    driver.cuCtxGetCurrent(byref(hctx))
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 284, in __getattr__
    self.ensure_initialized()
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/site-packages/numba/cuda/cudadrv/driver.py", line 250, in ensure_initialized
    raise CudaSupportError(f"Error at driver init: {description}")
numba.cuda.cudadrv.error.CudaSupportError: Error at driver init: Call to cuInit results in UNKNOWN_CUDA_ERROR (34)
```

**Comment by pxrw** [comment]
I find all my `libcuda.so` file, 
```
./local/cuda-11.3/targets/x86_64-linux/lib/stubs/libcuda.so
./local/cuda-11.2/targets/x86_64-linux/lib/stubs/libcuda.so
./local/cuda-11.8/targets/x86_64-linux/lib/stubs/libcuda.so
./lib/libcuda.so
./lib/i386-linux-gnu/libcuda.so
```
and try to set these path to my `LD_LIBRARY_PATH` one by one, but they all output the same error...

**Comment by pxrw** [comment]
OK, I solved my problem. In order to test my Mamba environment, I created a soft link from `/usr/lib.licuda.so` to `usr/local/cuda-11.8/targets/x86_64-linux/lib/stubs`, according to the error information, I found this may be the source problem, then I delete this soft link and set my `LD_LIBRARY_PATH=/usr/lib`. Finally I got the right output:
```
from numba import cuda
>>> cuda.gpus
<numba.cuda.cudadrv.devices._DeviceList object at 0x7f0125d911b0>
>>> print(cuda.gpus)
<Managed Device 0>, <Managed Device 1>
```
Thanks very much for your help~
I'll close this issue.

**Comment by mayur20169** [comment]
@pxrw I am trying to solve same issue from past 1 week. Can you please tell how exactly you solved this error.

**Comment by pxrw** [comment]
you can type this command in your terminal `python -c "from ctypes import CDLL; CDLL('libcuda.so')._undef"`, and get an output like this:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/ctypes/__init__.py", line 387, in __getattr__
    func = self.__getitem__(name)
  File "/home/pxr/miniconda3/envs/py10vm/lib/python3.10/ctypes/__init__.py", line 392, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/libcuda.so: undefined symbol: _undef
```
you need add the path `/usr/lib` to your `LD_LIBRARY_PATH`, and `source ~/.bashrc`

**Comment by pxrw** [comment]
By the way, if you create any soft link, link the `/usr/lib/libcuda.so` to another place, you need to remove the soft link.
