### ISSUE TITLE
Strange error message when compiling a function returning None

### ISSUE THREAD

**Issue by pitrou** [numba/numba#975]
This works ok:
```
>>> def f():
...    print(1)
...    return 2
... 
>>> ff = numba.jit(nopython=True)(f)
>>> ff()
2
```

but leaving out the return statement gives this:

```
>>> def f():
...     print(1)
... 
>>> ff = numba.jit(nopython=True)(f)
>>> ff()
Traceback (most recent call last):
  File "/home/antoine/numba/numba/lowering.py", line 280, in lower_block
    self.lower_inst(inst)
  File "/home/antoine/numba/numba/lowering.py", line 316, in lower_inst
    val = self.loadvar(inst.value.name)
  File "/home/antoine/numba/numba/lowering.py", line 659, in loadvar
    ptr = self.getvar(name)
  File "/home/antoine/numba/numba/lowering.py", line 656, in getvar
    return self.varmap[name]
KeyError: '$0.5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/antoine/numba/numba/dispatcher.py", line 157, in _compile_for_args
    return self.compile(sig)
  File "/home/antoine/numba/numba/dispatcher.py", line 277, in compile
    flags=flags, locals=self.locals)
  File "/home/antoine/numba/numba/compiler.py", line 547, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/antoine/numba/numba/compiler.py", line 293, in compile_extra
    return self.compile_bytecode(bc, func_attr=self.func_attr)
  File "/home/antoine/numba/numba/compiler.py", line 301, in compile_bytecode
    return self._compile_bytecode()
  File "/home/antoine/numba/numba/compiler.py", line 534, in _compile_bytecode
    return pm.run(self.status)
  File "/home/antoine/numba/numba/compiler.py", line 191, in run
    raise patched_exception
  File "/home/antoine/numba/numba/compiler.py", line 183, in run
    res = stage()
  File "/home/antoine/numba/numba/compiler.py", line 492, in stage_nopython_backend
    return self._backend(lowerfn, objectmode=False)
  File "/home/antoine/numba/numba/compiler.py", line 447, in _backend
    lowered = lowerfn()
  File "/home/antoine/numba/numba/compiler.py", line 438, in backend_nopython_mode
    self.flags)
  File "/home/antoine/numba/numba/compiler.py", line 684, in native_lowering_stage
    lower.lower()
  File "/home/antoine/numba/numba/lowering.py", line 246, in lower
    self.lower_block(block)
  File "/home/antoine/numba/numba/lowering.py", line 285, in lower_block
    raise LoweringError(msg, inst.loc)
numba.lowering.LoweringError: Failed at nopython (nopython mode backend)
Internal error:
KeyError: '$0.5'
File "<stdin>", line 2
```

**Comment by pitrou** [comment]
This seems to have been fixed somewhere along the way.
