### ISSUE TITLE
Numba 0.60.0 breaks (VSCode) debugpy (on Windows)

### ISSUE THREAD

**Issue by Huite** [numba/numba#9753]
## Reporting a bug

A colleague ran into some problems running a debugger on a script that uses numba inside one of my packages. I noticed the debugger in VSCode on Windows stopped working with the latest release. It takes only a trivial example to trigger:

```python
import numba as nb
import numpy as np


@nb.njit
def f(a):
    out = 0
    for e in a:
        out += e
    return out


def g(a):
    out = a + 1
    return out


a = np.arange(10)
b = f(a)
c = g(a)
```

Just put a breakpoint in function `g` and start debugging the file in VSCode.

It fails with the following stacktrace:

```
PS C:\src\xugrid>  & 'C:\src\xugrid\.pixi\envs\default\python.exe' 'c:\Users\bootsma\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher' '59193' '--' 'C:\src\xugrid\examples\test-debug.py'
src\x5cxugrid\x5cexamples\x5ctest-debug.py' ;f5f2a96f-77db-4413-91af-5fd71fc1a282Traceback (most recent call last):
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 555, in _pydevd_sys_monitoring_cython._get_func_code_info
KeyError: (6, 'C:\\src\\xugrid\\examples\\test-debug.py', <code object f at 0x000001FC3A8E5F20, file "C:\src\xugrid\examples\test-debug.py", line 6>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\xugrid\.pixi\envs\default\Lib\runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\src\xugrid\.pixi\envs\default\Lib\runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "c:\Users\bootsma\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy\__main__.py", line 71, in <module>
    cli.main()
  File "c:\Users\bootsma\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 501, in main
    run()
  File "c:\Users\bootsma\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\adapter/../..\debugpy\launcher/../..\debugpy/..\debugpy\server\cli.py", line 351, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\Users\bootsma\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 310, in run_path
    return _run_module_code(code, init_globals, run_name, pkg_name=pkg_name, script_name=fname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\bootsma\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 127, in _run_module_code
    _run_code(code, mod_globals, init_globals, mod_name, mod_spec, pkg_name, script_name)
  File "c:\Users\bootsma\.vscode\extensions\ms-python.debugpy-2024.12.0-win32-x64\bundled\libs\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 118, in _run_code
    exec(code, run_globals)
  File "C:\src\xugrid\examples\test-debug.py", line 20, in <module>
    b = f(a)
        ^^^^
  File "<stringsource>", line 69, in cfunc.to_py.__Pyx_CFunc_893235__29_pydevd_sys_monitoring_cython_object__lParen__etc_to_py_4code_18instruction_offset.wrap
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 1662, in _pydevd_sys_monitoring_cython._start_method_event
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 562, in _pydevd_sys_monitoring_cython._get_func_code_info
AssertionError: <code object <module> at 0x000001FC3A5868E0, file "C:\src\xugrid\examples\test-debug.py", line 1> != <code object f at 0x000001FC3A8E5F20, file "C:\src\xugrid\examples\test-debug.py", line 6>
PS C:\src\xugrid> 
```

I tested the previous version: numba 0.59.1 allows me to debug without problems (and reverting also fixes it for my colleague).

Here's the `numba -s` dump for completeness:

<details>

```
System info:
--------------------------------------------------------------------------------
__Time Stamp__
Report started (local time)                   : 2024-10-16 16:12:47.350235
UTC start time                                : 2024-10-16 14:12:47.350235
Running time (s)                              : 0.651199

__Hardware Information__
Machine                                       : AMD64
CPU Name                                      : alderlake
CPU Count                                     : 24
Number of accessible CPUs                     : 24
List of accessible CPUs cores                 : 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
CFS Restrictions (CPUs worth of runtime)      : None

CPU Features                                  : 64bit adx aes avx avx2 bmi bmi2
                                                clflushopt clwb cmov crc32 cx16
                                                cx8 f16c fma fsgsbase fxsr gfni
                                                invpcid lzcnt mmx movbe pclmul
                                                popcnt prfchw ptwrite rdpid rdrnd
                                                rdseed sahf sha shstk sse sse2
                                                sse3 sse4.1 sse4.2 ssse3 vaes
                                                vpclmulqdq xsave xsavec xsaveopt
                                                xsaves

Memory Total (MB)                             : 32368
Memory Available (MB)                         : 16350

__OS Information__
Platform Name                                 : Windows-10-10.0.19045-SP0
Platform Release                              : 10
OS Name                                       : Windows
OS Version                                    : 10.0.19045
OS Specific Version                           : 10 10.0.19045 SP0 Multiprocessor Free
Libc Version                                  : ?

__Python Information__
Python Compiler                               : MSC v.1941 64 bit (AMD64)
Python Implementation                         : CPython
Python Version                                : 3.12.7
Python Locale                                 : en_NL.cp1252

__Numba Toolchain Versions__
Numba Version                                 : 0.60.0
llvmlite Version                              : 0.43.0

__LLVM Information__
LLVM Version                                  : 14.0.6

__CUDA Information__
CUDA Device Initialized                       : True
CUDA Driver Version                           : ?
CUDA Runtime Version                          : ?
CUDA NVIDIA Bindings Available                : ?
CUDA NVIDIA Bindings In Use                   : ?
CUDA Minor Version Compatibility Available    : ?
CUDA Minor Version Compatibility Needed       : ?
CUDA Minor Version Compatibility In Use       : ?
CUDA Detect Output:
Found 1 CUDA devices
id 0    b'NVIDIA RTX A1000 Laptop GPU'                              [SUPPORTED]
                      Compute Capability: 8.6
                           PCI Device ID: 0
                              PCI Bus ID: 1
                                    UUID: GPU-bb86f3ad-7a9f-8a73-eab7-609217f339a2
                                Watchdog: Enabled
                            Compute Mode: WDDM
             FP32/FP64 Performance Ratio: 32
Summary:
        1/1 devices are supported

CUDA Libraries Test Output:
None

__NumPy Information__
NumPy Version                                 : 2.0.2
NumPy Supported SIMD features                 : ('MMX', 'SSE', 'SSE2', 'SSE3', 'SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2')
NumPy Supported SIMD dispatch                 : ('SSSE3', 'SSE41', 'POPCNT', 'SSE42', 'AVX', 'F16C', 'FMA3', 'AVX2', 'AVX512F', 'AVX512CD', 'AVX512_SKX', 'AVX512_CLX', 'AVX512_CNL', 'AVX512_ICL')
NumPy Supported SIMD baseline                 : ('SSE', 'SSE2', 'SSE3')
NumPy AVX512_SKX support detected             : False

__SVML Information__
SVML State, config.USING_SVML                 : True
SVML Library Loaded                           : True
llvmlite Using SVML Patched LLVM              : True
SVML Operational                              : True

__Threading Layer Information__
TBB Threading Layer Available                 : True
+-->TBB imported successfully.
OpenMP Threading Layer Available              : True
+-->Vendor: MS
Workqueue Threading Layer Available           : True
+-->Workqueue imported successfully.

__Numba Environment Variable Information__
None found.

__Conda Information__
Conda not available.

__Installed Packages__
Package                       Version     Editable project location
----------------------------- ----------- -------------------------
accessible-pygments           0.0.5
alabaster                     1.0.0
asciitree                     0.3.3
asttokens                     2.4.1
Babel                         2.14.0
backports.tarfile             1.0.0
beautifulsoup4                4.12.3
bokeh                         3.6.0
branca                        0.7.2
Brotli                        1.1.0
build                         1.2.2.post1
certifi                       2024.8.30
cffi                          1.17.1
cfgv                          3.3.1
cftime                        1.6.4
charset-normalizer            3.4.0
click                         8.1.7
cloudpickle                   3.1.0
cmarkgfm                      0.8.0
colorama                      0.4.6
comm                          0.2.2
contourpy                     1.3.0
coverage                      7.6.3
cycler                        0.12.1
cytoolz                       1.0.0
dask                          2024.9.1
dask-expr                     1.1.15
debugpy                       1.8.7
decopatch                     1.4.10
decorator                     5.1.1
distlib                       0.3.9
distributed                   2024.9.1
docutils                      0.21.2
exceptiongroup                1.2.2
executing                     2.1.0
fasteners                     0.17.3
filelock                      3.16.1
folium                        0.17.0
fonttools                     4.54.1
fsspec                        2024.9.0
geopandas                     1.0.1
h2                            4.1.0
hpack                         4.0.0
hyperframe                    6.0.1
identify                      2.6.1
idna                          3.10
imagesize                     1.4.1
importlib_metadata            8.5.0
importlib_resources           6.4.5
iniconfig                     2.0.0
ipykernel                     6.29.5
ipython                       8.28.0
jaraco.classes                3.4.0
jaraco.context                5.3.0
jaraco.functools              4.0.0
jedi                          0.19.1
Jinja2                        3.1.4
joblib                        1.4.2
jupyter_client                8.6.3
jupyter_core                  5.7.2
keyring                       25.4.1
kiwisolver                    1.4.7
llvmlite                      0.43.0
locket                        1.0.0
lz4                           4.3.3
makefun                       1.15.6
mapbox_earcut                 1.0.1
mapclassify                   2.8.1
markdown-it-py                3.0.0
MarkupSafe                    3.0.1
matplotlib                    3.9.2
matplotlib-inline             0.1.7
mdurl                         0.1.2
more-itertools                10.5.0
msgpack                       1.1.0
munkres                       1.1.4
nest_asyncio                  1.6.0
netCDF4                       1.7.1
networkx                      3.4.1
nh3                           0.2.18
nodeenv                       1.9.1
numba                         0.60.0
numba_celltree                0.2.2
numcodecs                     0.13.1
numpy                         2.0.2
packaging                     24.1
pandas                        2.2.3
parso                         0.8.4
partd                         1.4.2
pickleshare                   0.7.5
pillow                        11.0.0
pip                           24.2
pkginfo                       1.10.0
platformdirs                  4.3.6
pluggy                        1.5.0
pooch                         1.8.2
pre_commit                    4.0.1
prompt_toolkit                3.0.48
psutil                        6.0.0
pure_eval                     0.2.3
pyarrow                       17.0.0
pyarrow-hotfix                0.6
pycparser                     2.22
pydata-sphinx-theme           0.15.4
Pygments                      2.18.0
PyMetis                       2023.1.1
pyogrio                       0.10.0
pyparsing                     3.2.0
pyproj                        3.7.0
pyproject_hooks               1.2.0
PySocks                       1.7.1
pytest                        8.3.3
pytest-cases                  3.8.6
pytest-cov                    5.0.0
python-dateutil               2.9.0
pytz                          2024.1
pywin32                       307
pywin32-ctypes                0.2.3
PyYAML                        6.0.2
pyzmq                         26.2.0
readme_renderer               44.0
requests                      2.32.3
requests-toolbelt             1.0.0
rfc3986                       2.0.0
rich                          13.9.2
ruff                          0.6.9
scikit-learn                  1.5.2
scipy                         1.14.1
setuptools                    75.1.0
shapely                       2.0.6
six                           1.16.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.5
Sphinx                        8.1.3
sphinx-gallery                0.18.0
sphinxcontrib-applehelp       2.0.0
sphinxcontrib-devhelp         2.0.0
sphinxcontrib-htmlhelp        2.1.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          2.0.0
sphinxcontrib-serializinghtml 1.1.10
stack-data                    0.6.2
tblib                         3.0.0
threadpoolctl                 3.5.0
toml                          0.10.2
tomli                         2.0.2
toolz                         1.0.0
tornado                       6.4.1
traitlets                     5.14.3
twine                         5.1.1
typing_extensions             4.12.2
tzdata                        2024.2
ukkonen                       1.0.1
urllib3                       2.2.3
virtualenv                    20.26.6
wcwidth                       0.2.13
wheel                         0.44.0
win_inet_pton                 1.1.0
xarray                        2024.9.0
xugrid                        0.12.1
xyzservices                   2024.9.0
zarr                          2.18.3
zict                          3.0.0
zipp                          3.20.2
zstandard                     0.23.0

No errors reported.


__Warning log__
Warning (cuda): Probing CUDA failed (device and driver present, runtime problem?)
(cuda) <class 'FileNotFoundError'>: Could not find module 'cudart.dll' (or one of its dependencies). Try using the full path with constructor syntax.
Warning: Conda not available.
 Error was [WinError 2] The system cannot find the file specified

--------------------------------------------------------------------------------
```

<\details>

**Comment by HIEROT** [comment]
I met the exact same problem today. If no breakpoint set everything is fine otherwise it fails at the first call to a jitted function. It seems that the debugger or numba messed things up.

**Comment by HIEROT** [comment]
confirmed vscode python debugger 2024.12.0 breaks thing up, just roll back to 2024.10.0

**Comment by guilhermeleobas** [comment]
Thanks for the comment @HIEROT. @Huite, can you confirm the rolling back to a previous version of VSCode fixes the issue?

**Comment by Huite** [comment]
I can confirm: VSCode Python debugger `v2024.10.0` works.

For completeness:

Python Debugger v2024.10.0 works with numba 0.59.1 ✔️
Python Debugger v2024.10.0 works with numba 0.60.0 ✔️

Python Debugger v2024.12.0 works with numba 0.59.1 ✔️
Python Debugger v2024.12.0 does not work with numba 0.60.0 ❌

**Comment by guilhermeleobas** [comment]
Ok, thanks. I'll close this PR as this doesn't seem to be Numba's fault.

**Comment by Huite** [comment]
> Ok, thanks. I'll close this PR as this doesn't seem to be Numba's fault.

I'm not entirely sure about that? As I mentioned, the older numba (0.59.1) version does work, even with the latest debugger version.
It seems like **both** the VSCode debugger **and** Numba have changed in their latest releases.

**Comment by guilhermeleobas** [comment]
Oh, sorry. I misread the part you said Numba 0.58 works with VSCode. Reopening

**Comment by sklam** [comment]
i can replicate this on main on osx-64. Problematic lines in the cython code is slightly different though:

```
  File "<stringsource>", line 69, in cfunc.to_py.__Pyx_CFunc_893235__29_pydevd_sys_monitoring_cython_object__lParen__etc_to_py_4code_18instruction_offset.wrap
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 1662, in _pydevd_sys_monitoring_cython._start_method_event
  File "_pydevd_sys_monitoring\\_pydevd_sys_monitoring_cython.pyx", line 562, in _pydevd_sys_monitoring_cython._get_func_code_info
AssertionError: <code object <module> at 0x10ad3bb40, file "/Users/path/to/numba/chk.py", line 1> != <code object f at 0x10b371a70, file "/Users/path/to/numba/chk.py", line 5>
```

**Comment by sklam** [comment]
Summarizing what I found:

- debugpy is expecting new Python frame for the callee but Numba is not setting up callee frames. 
- As of 3.12, CPython `sys.monitoring` code and documentation are assuming the existence of python code object and frame object but that is contradicting the goal of the low-level monitoring tool. See discussion starting at https://github.com/python/cpython/issues/111997#issuecomment-2122895229
- There's a `PyFrame_New()` with ambiguous status: https://github.com/python/cpython/issues/118746#issuecomment-2099800122. Cython only uses it for pre `sys.monitoring` support: https://github.com/cython/cython/blob/a2b9f55670b765d9b482fd7d8533f2df914e7387/Cython/Utility/Profile.c#L616
- As of 3.13, CPython has new C-API that seems to side-step the frame issue https://docs.python.org/3.13/c-api/monitoring.html#monitoring-c-api. But I expect downstream tools will need time to change up to avoid relying on Python frames. Numba also needs to adapt to this new API.
