### ISSUE TITLE
issue with np.argmin with njit(parallel=True), "AssertionError: key already in dictionary: '$np_g_var.1' "

### ISSUE THREAD

**Issue by ryanalbosta** [numba/numba#9809]
Hi all, I apologize for the lack of detail here, but my codebase is enormously complicated and I was unable to generate a minimum working example. Setting up just the input data for this function would take hours, so it's out of my time allowance to do so here.

- I have a function decorated with @njit(parallel=True). It takes a large amount of data in and does a very complex algorithm on it: it's a physics simulation.
- the function compiles just fine with parallel=False, but SOMETIMES fails to compile with parallel=True, and if it compiles it runs Extremely slowly.
- I finally narrowed the issue down to a line including np.argmin. This line is not even responsible for the heavy lifting in my program. Below is the segment of code surrounding this, with simple definitions of each variable. HOWEVER: This will not repoduce the issue. It seems to go well beyond this function itself, but it is definitely this line since removing it and replacing it with a by-hand loop that serves the same purpose fixes the issue. I suspect is has something to do with numba parallel trying to optimize this loop a certain way and conflicting somehow with its other operations, but since it fails to compile and the function is too large for debug=True I can't tell what's wrong. Only other thing of note is I use prange in a seperate loop in this function, but changing that to range does not fix this issue, I only mention it due to all the other reports I see involving it.

Reminder: the below code will NOT reproduce the error. It's just the patch of code in my enormous function that, if removed, prevents it from happening. And yes, part of the code will not be reached with the input data I generated: That is also true for my large function.

  @njit(parallel=True)
  def exfunc(lam, phot_lines, line_wavs, instfunc_array, use_instfunc):
  
      lam_int_array = np.ones(len(lam))
  
      if use_instfunc:
          # final_ans = lam_int_final_0
          output = lam_int_array
          for i in range(len(phot_lines)):
              if phot_lines[i] != 0.:
                  index_min_line = np.argmin(np.abs(lam - line_wavs[i]))
                  if 0 <= index_min_line < len(lam_int_array):
                      dellam_temp1 = line_wavs[i] - lam[index_min_line]
                      lam_temp1 = lam + dellam_temp1
                      arg_sort_temp1 = np.argsort(lam_temp1)
                      int_temp1 = np.interp(lam, lam_temp1[arg_sort_temp1],
                                            instfunc_array[index_min_line][arg_sort_temp1])
                      sum_temp1 = np.sum(int_temp1)
                      if sum_temp1 != 0.:
                          int_temp1 /= sum_temp1
                          int_temp1 *= phot_lines[i]
                          output += int_temp1
      else:
          output = lam_int_array
          # if use_intsphere:
          #     output *= intsphere_func
      return output
  
  def main():
      lam = np.linspace(0., 1., 100)
      use_instfunc = True
      phot_lines = np.zeros(1)
      line_wavs = np.zeros(1)
      instfunc_array = np.ones((len(lam), len(lam)))
      exfunc(lam, phot_lines, line_wavs, instfunc_array, use_instfunc)
  
  if __name__ == '__main__':
      main()

- And here is the error report from my main code:

ERROR REPORT ::
Traceback (most recent call last):
  File "C:\Users\albosta\PycharmProjects\pyfydasim_ryan2\pyfidasim\examples\DIIID\Ryan_A\D_Alpha_doppler_multipoint.py", line 1231, in <module>
    output1 = D_alpha_sim1.run_dop(time * 1000., lam_ranges, caldict_name, datadict_name, sub_beamoff=sub_beamoff,
  File "C:\Users\albosta\PycharmProjects\pyfydasim_ryan2\pyfidasim\examples\DIIID\Ryan_A\D_Alpha_Sim_object_multipoint.py", line 3724, in run_dop
    data1_sim_arr, lstqs_1 = calc_doppler(x0, self, x0_index=None, x0_full=x0)
  File "C:\Users\albosta\PycharmProjects\pyfydasim_ryan2\pyfidasim\examples\DIIID\Ryan_A\D_Alpha_Sim_object_multipoint.py", line 5950, in calc_doppler
    output1, output2, other, vs, v_mag = calc_doppler_numba2(*args_main)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\dispatcher.py", line 442, in _compile_for_args
    raise e
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\dispatcher.py", line 375, in _compile_for_args
    return_val = self.compile(tuple(argtypes))
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\dispatcher.py", line 905, in compile
    cres = self._compiler.compile(args, return_type)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\dispatcher.py", line 80, in compile
    status, retval = self._compile_cached(args, return_type)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\dispatcher.py", line 94, in _compile_cached
    retval = self._compile_core(args, return_type)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\dispatcher.py", line 107, in _compile_core
    cres = compiler.compile_extra(self.targetdescr.typing_context,
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler.py", line 744, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler.py", line 438, in compile_extra
    return self._compile_bytecode()
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler.py", line 506, in _compile_bytecode
    return self._compile_core()
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler.py", line 481, in _compile_core
    raise e
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler.py", line 472, in _compile_core
    pm.run(self.state)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler_machinery.py", line 364, in run
    raise e
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler_machinery.py", line 356, in run
    self._runPass(idx, pass_inst, state)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler_lock.py", line 35, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler_machinery.py", line 311, in _runPass
    mutated |= check(pss.run_pass, internal_state)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\compiler_machinery.py", line 273, in check
    mangled = func(compiler_state)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\typed_passes.py", line 247, in run_pass
    rewrites.rewrite_registry.apply('after-inference', state)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\rewrites\registry.py", line 67, in apply
    matches = rewrite.match(state.func_ir, block, state.typemap,
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\inline_closurecall.py", line 1468, in match
    self.new_body = guard(_inline_const_arraycall, block, func_ir,
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\ir_utils.py", line 1549, in guard
    return func(*args, **kwargs)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\inline_closurecall.py", line 1642, in _inline_const_arraycall
    if guard(inline_array, inst.target, expr,
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\ir_utils.py", line 1549, in guard
    return func(*args, **kwargs)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\inline_closurecall.py", line 1550, in inline_array
    typemap[g_np_var.name] = types.misc.Module(np)
  File "C:\Users\albosta\PycharmProjects\VENV_GENERAL\lib\site-packages\numba\core\utils.py", line 487, in __setitem__
    raise AssertionError("key already in dictionary: %r" % (key,))
AssertionError: key already in dictionary: '$np_g_var.1'

-Running my IDE (pycharm) in debug mode, here are the variables present in utils.py __setitem__ ::

class UniqueDict(dict):
    def __setitem__(self, key, value):
        if key in self:
            raise AssertionError("key already in dictionary: %r" % (key,))
        super(UniqueDict, self).__setitem__(key, value)

- returns from debug:
value = Module(<module 'numpy' from 'C:\\Users\\albosta\\PycharmProjects\\VENV_GENERAL\\lib\\site-packages\\numpy\\__init__.py'>)
self = A very long dictionary seeming to contain some internal list of parameters I use in the function, although lots of them have .# attached to them. ex: the variable i use somewhere in my function is called 'x0', but there are also other variables called x.1, x.2, etc.
key = '$np_g_var.1'

- This error does not occur if parallel is off. Smaller reductions of my code to just the problem error also do not reproduce it, and I don't have time to rebuild my several thousand line physics code to figure out where the line is, I honestly wish I did.

- Replacing np.argmin with my own simple loop fixes the issue for me, so it's not urgent, I just wanted to let y'all know because it's a very weird error and took me a long time to find, and I wanted to help other people if they run into it.

**Comment by gmarkall** [comment]
There were PRs related to removing `mk_unique_var` in the past: https://github.com/numba/numba/pulls?q=is%3Apr+mk_unique_var+is%3Aclosed

This variable, `np_g_var` was involved in at least some of them and I think it presented some difficulty at the time. Just to check, what version of Numba are you using?

**Comment by gmarkall** [comment]
In the triage meeting @stuartarchibald also mentioned that the `inline_closurecall` pass may be causing a scope transfer that reintroduces this already-existing variable into a scope.

**Comment by sklam** [comment]
> the below code will NOT reproduce the error. It's just the patch of code in my enormous function that, if removed, prevents it from happening. 

If parallel-accelerator transformation is failing at the patch of code, one workaround might be to move that patch of code into a separate `@jit(parallel=False)` function.

**Comment by pietrodantuono** [comment]
Upvoting to not keep stale

**Comment by gmarkall** [comment]
> Upvoting to not keep stale

Thanks - this won't go stale again as its labelled as a bug - the bot only makes questions and "needtriage" and "more info needed" items as stale if they get no activity for three months.
