### ISSUE TITLE
numba 0.61.0rc1 fails on macOS 12

### ISSUE THREAD

**Issue by LucaMarconato** [numba/numba#9812]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

Works on the latest release, fails on the latest pre-release (`numba==0.61.0rc1`).

To reproduce:
- install `numba==0.61.0rc1`
- run `from numba import cuda`

Full output from my console. Installing the package:
```python
(ome312) macbook@Lucas-MacBook-Pro-2021 basel % pip install --pre numba==0.61.0rc1
Collecting numba==0.61.0rc1
  Downloading numba-0.61.0rc1-cp312-cp312-macosx_11_0_arm64.whl.metadata (2.7 kB)
Collecting llvmlite<0.45,>=0.44.0dev0 (from numba==0.61.0rc1)
  Downloading llvmlite-0.44.0rc1-cp312-cp312-macosx_11_0_arm64.whl.metadata (4.8 kB)
Requirement already satisfied: numpy<2.2,>=1.24 in /opt/miniconda3/envs/ome312/lib/python3.12/site-packages (from numba==0.61.0rc1) (1.26.4)
Downloading numba-0.61.0rc1-cp312-cp312-macosx_11_0_arm64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 14.3 MB/s eta 0:00:00
Downloading llvmlite-0.44.0rc1-cp312-cp312-macosx_11_0_arm64.whl (26.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.2/26.2 MB 19.6 MB/s eta 0:00:00
Installing collected packages: llvmlite, numba
  Attempting uninstall: llvmlite
    Found existing installation: llvmlite 0.43.0
    Uninstalling llvmlite-0.43.0:
      Successfully uninstalled llvmlite-0.43.0
  Attempting uninstall: numba
    Found existing installation: numba 0.60.0
    Uninstalling numba-0.60.0:
      Successfully uninstalled numba-0.60.0
Successfully installed llvmlite-0.44.0rc1 numba-0.61.0rc1
```
Within `python`:
```
(ome312) macbook % python
Python 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:36:57) [Clang 15.0.7 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from numba import cuda
Traceback (most recent call last):
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/ffi.py", line 141, in __getattr__
    return self._fntab[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'LLVMPY_AddSymbol'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/ffi.py", line 122, in _load_lib
    self._lib_handle = ctypes.CDLL(str(lib_path))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ome312/lib/python3.12/ctypes/__init__.py", line 379, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: dlopen(/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/libllvmlite.dylib, 0x0006): Library not loaded: @rpath/libzstd.1.dylib
  Referenced from: <8AA99741-CE2B-3C12-909E-CC3A7625F555> /opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/libllvmlite.dylib
  Reason: tried: '/opt/miniconda3/envs/ome312/lib/python3.12/lib-dynload/../../libzstd.1.dylib' (no such file), '/opt/miniconda3/envs/ome312/bin/../lib/libzstd.1.dylib' (no such file), '/usr/local/lib/libzstd.1.dylib' (no such file), '/usr/lib/libzstd.1.dylib' (no such file, not in dyld cache)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/numba/__init__.py", line 73, in <module>
    from numba.core import config
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/numba/core/config.py", line 17, in <module>
    import llvmlite.binding as ll
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/__init__.py", line 4, in <module>
    from .dylib import *
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/dylib.py", line 36, in <module>
    ffi.lib.LLVMPY_AddSymbol.argtypes = [
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/ffi.py", line 144, in __getattr__
    cfn = getattr(self._lib, name)
                  ^^^^^^^^^
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/ffi.py", line 136, in _lib
    self._load_lib()
  File "/opt/miniconda3/envs/ome312/lib/python3.12/site-packages/llvmlite/binding/ffi.py", line 130, in _load_lib
    raise OSError("Could not find/load shared object file") from e
OSError: Could not find/load shared object file
```

CC @melonora

**Comment by esc** [comment]
@LucaMarconato yes, this is known, you need to install the llvmlite wheel from anaconda.org on the `arm-64` osx platform. Try adding the following to your `pip` command:

```
--extra-index https://pypi.anaconda.org/numba/label/wheels/simple
```

You can find the wheels here: https://anaconda.org/numba/llvmlite/files?channel=wheels&version=0.44.0rc1&type=pypi

**Comment by Parici75** [comment]
I was having this issue when running tests on a macOS runner with GitHub Action. Following @esc advise, I solved the problem (using poetry) with the following step in my workflow:

```
- name: Add Anaconda PyPI for llvmlite (macOS)
  if: runner.os == 'macOS'
  run: |
    poetry source add --priority=explicit numba https://pypi.anaconda.org/numba/label/wheels/simple
    poetry add --source numba llvmlite
```

However, the issue remains on a windows runner, where this step raises (see [here](https://github.com/Parici75/mltoolbox/actions/runs/12097540904/job/33733017361)):
` Unable to find installation candidates for llvmlite (0.44.0rc1)`

Any hints ?

**Comment by jobovy** [comment]
It looks like there are now windows wheels for Numba, but I'm having this same ``KeyError: 'LLVMPY_AddSymbol'`` issue. I'm using

- numba-0.61.0rc1-cp313-cp313-win_amd64.whl
- llvmlite-0.44.0rc1-cp313-cp313-win_amd64.whl

**Comment by esc** [comment]
@jobovy those issues were recently only discovered for OSX, but not windows. Can you open a new issue for this one please?

**Comment by esc** [comment]
@LucaMarconato @Parici75 did you manage to solve the issues on osx-64 and osxarm-64 using the wheels from anaconda.org? If yes, I'd like to close this issue.

**Comment by Parici75** [comment]
Apologize @esc for my lack of answer.

Yes you can close the issue as the anaconda wheels for osx solve the problem (cf my previous [comment](https://github.com/numba/numba/issues/9812#issuecomment-2510199096)).

**Comment by esc** [comment]
> Apologize @esc for my lack of answer.
> 
> Yes you can close the issue as the anaconda wheels for osx solve the problem (cf my previous [comment](https://github.com/numba/numba/issues/9812#issuecomment-2510199096)).

Ah, yes I see it now, thank you!

**Comment by jobovy** [comment]
> @jobovy those issues were recently only discovered for OSX, but not windows. Can you open a new issue for this one please?

Sure, I opened #9825.

**Comment by esc** [comment]
> > @jobovy those issues were recently only discovered for OSX, but not windows. Can you open a new issue for this one please?
> 
> Sure, I opened #9825.

Excellent, thank you!
