### ISSUE TITLE
@autojit & @asyncio.coroutine

### ISSUE THREAD

**Issue by root-11** [numba/numba#984]
In attempt to run the demo code:

```
import asyncio
from numba import autojit

@autojit
@asyncio.coroutine
def factorial(name, number):
    f = 1
    for i in range(2, number+1):
        print("Task %s: Compute factorial(%s)..." % (name, i))
        yield from asyncio.sleep(1)
        f *= i
    print("Task %s: factorial(%s) = %s" % (name, number, f))

loop = asyncio.get_event_loop()
tasks = [
    asyncio.async(factorial("A", 2)),
    asyncio.async(factorial("B", 3)),
    asyncio.async(factorial("C", 4)),
    asyncio.async(factorial("D", 5))]
loop.run_until_complete(asyncio.wait(tasks))
loop.close()
```

The following error is reported:

"""
C:\Users\bmadsen\Desktop\Nvidia stuff>python asyncio_numba_parallel_execution_of_tasks.py
Traceback (most recent call last):
  File "C:\Conda\anaconda3\lib\site-packages\numba\bytecode.py", line 227, in next
    info = BYTECODE_TABLE[opcode]
KeyError: 72

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "asyncio_numba_parallel_execution_of_tasks.py", line 16, in <module>
    asyncio.async(factorial("A", 2)),
  File "C:\Conda\anaconda3\lib\site-packages\numba\dispatcher.py", line 153, in _compile_for_args
    return self.jit(sig)
  File "C:\Conda\anaconda3\lib\site-packages\numba\dispatcher.py", line 144, in jit
    return self.compile(sig, **kws)
  File "C:\Conda\anaconda3\lib\site-packages\numba\dispatcher.py", line 279, in compile
    flags=flags, locals=locs)
  File "C:\Conda\anaconda3\lib\site-packages\numba\compiler.py", line 552, in compile_extra
    return pipeline.compile_extra(func)
  File "C:\Conda\anaconda3\lib\site-packages\numba\compiler.py", line 267, in compile_extra
    raise res.exception
  File "C:\Conda\anaconda3\lib\site-packages\numba\compiler.py", line 163, in __call__
    res = self.func()
  File "C:\Conda\anaconda3\lib\site-packages\numba\compiler.py", line 260, in <lambda>
    res = _Stage(lambda: self.extract_bytecode(func),
  File "C:\Conda\anaconda3\lib\site-packages\numba\compiler.py", line 253, in extract_bytecode
    bc = bytecode.ByteCode(func=self.func)
  File "C:\Conda\anaconda3\lib\site-packages\numba\bytecode.py", line 317, in __init__
    table = utils.SortedMap(ByteCodeIter(code))
  File "C:\Conda\anaconda3\lib\site-packages\numba\utils.py", line 98, in **init**
    for i, (k, v) in enumerate(sorted(seq)):
  File "C:\Conda\anaconda3\lib\site-packages\numba\bytecode.py", line 231, in next
    raise NotImplementedError(ts % tv)
NotImplementedError: offset=68 opcode=0x48 opname=YIELD_FROM
"""

Does this mean that YIELD FROM is not supported in Python 3.4.2 ?
The reason for asking is that pypi says that 3.4 is supported.

**Comment by seibert** [comment]
Numba does not support some Python language features.  The manual describes some of the limitations (http://numba.pydata.org/numba-doc/0.17.0/reference/pysupported.html#constructs), but fails to mention that "yield" and "yield from" are also not supported.  We need to add that information to the documentation.

**Comment by Juanlu001** [comment]
Are there plans to support generators in numba or are they out of scope? cc @kikocorreoso

**Comment by seibert** [comment]
Direct support for generators is not currently in our roadmap, though calling a JIT function from inside a generator is obviously fine.

**Comment by seibert** [comment]
As an update to this issue, we now compilation and calling of generators in both nopython and object mode.  (Much like with regular functions, nopython mode functions can only call nopython mode generators.)

The example code in this issue still does not work because we do not support `yield from` yet.

**Comment by stuartarchibald** [comment]
Closing this as #1194 captures the feature request.
