### ISSUE TITLE
numba with @jit silently handles float-to-integer conversion in slice indices, causing unexpected behavior

### ISSUE THREAD

**Issue by zzl261004** [numba/numba#9877]
## Reporting a bug

- [x] I have tried using the latest released version of Numba (most recent is
  visible in the release notes
  (https://numba.readthedocs.io/en/stable/release-notes-overview.html).
- [x] I have included a self contained code sample to reproduce the problem.
  i.e. it's possible to run as 'python bug.py'.

```python
import numpy as np
from matplotlib import pylab

def pad(x,n,centre=False):
    if not centre:
        return np.hstack((x,np.zeros(n)))
    else:
        return np.hstack((x[:len(x)/2],np.zeros(n),x[len(x)/2:]))

Fp = np.fft.fft(pylab.hamming(10),n=2**10)
p1=np.fft.ifft(Fp,n=2**12)
p2=np.fft.ifft(pad(Fp, 2**12, centre=True))
pylab.plot(p2[:])
pylab.show()
# result TypeError
```
The result of running the program without using the @jit decorator from numba is:
```
Traceback (most recent call last):
  File "/nowtest/numba_test/log4/test/t1.py", line 12, in <module>
    p2=np.fft.ifft(pad(Fp, 2**12, centre=True))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nowtest/numba_test/log4/test/t1.py", line 8, in pad
    return np.hstack((x[:len(x)/2],np.zeros(n),x[len(x)/2:]))
                      ~^^^^^^^^^^^
TypeError: slice indices must be integers or None or have an __index__ method
```
When using the @jit decorator from numba, a TypeError does not occur.
```python
import numpy as np
from matplotlib import pylab
from numba import jit

@jit
def pad(x,n,centre=False):
    if not centre:
        return np.hstack((x,np.zeros(n)))
    else:
        return np.hstack((x[:len(x)/2],np.zeros(n),x[len(x)/2:]))

Fp = np.fft.fft(pylab.hamming(10),n=2**10)
p1=np.fft.ifft(Fp,n=2**12)
p2=np.fft.ifft(pad(Fp, 2**12, centre=True))
pylab.plot(p2[:])
pylab.show()
#It will not cause a TypeError
```
Environment:
**Numba 0.60.0
Python 3.10.12
Numpy 1.26.4
Operating System: Ubuntu 22.04.4 LTS (Codename: jammy)**

**Comment by gmarkall** [comment]
Many thanks for the report - I can reproduce this behaviour.
